### ISSUE TITLE
Error messages could be made more helpful by automatically focusing input field causing the problem

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1011]
A few examples:
* `unknown account` on `/signin` could re-focus the email field.
* `incorrect password` on `/signin` could re-focus the password field.
* `incorrect password` on `/change_password` could re-focus the password field.

**Comment by issues-bouncer** [comment]
Hey @shane-tomlinson, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by shane-tomlinson** [comment]
I'm going to close this as "works well enough."
