### ISSUE TITLE
Add verification link beneath the buttons in sent emails

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1032]
Found in https://accounts.firefox.com/ver.json (commit 29803083793cec24b45e7ada8e3b214670318ade)

```json
{"version":"0.11.1","commit":"29803083793cec24b45e7ada8e3b214670318ade"}
```

---

### Steps to reproduce:
1. Create a new account and check out the verification email.

### Actual results:
![verify_your_account_-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/2832634/bef41192-cfc6-11e3-9a20-d986dc767b15.png)

### Expected results:
Not sure if we want to put the full verification link (plain text) beneath the [Verify] button so users can easily select-copy-paste, or do, whatever.

**Comment by vladikoff** [comment]
Discussion here: https://github.com/mozilla/fxa-auth-mailer/issues/35
