### ISSUE TITLE
email in Outlook 2013 has "squashed" button

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#1034]
I don't see the same thing with what Litmus reports, but using real Office 2013 Outlook on Windows 7 (from modern.ie), the email I get looks like this:

(and both the reset and verify emails have the same defect).

![outlook2013](https://cloud.githubusercontent.com/assets/758162/2836189/9d2ad024-cff7-11e3-942d-08ffc29d2f48.png)

**Comment by shane-tomlinson** [comment]
All emails are taken care of in fxa-auth-mailer, I moved the bug there. Closing.
