### ISSUE TITLE
Mailinator email support is {{t "no bueno"}}

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1053]
Found in https://accounts.stage.mozaws.net/ver.json (commit 04f143ea4e6d53eb6d7453c3ccf7ec3ca9bb2d24)

```json
{"version":"0.11.2","commit":"04f143ea4e6d53eb6d7453c3ccf7ec3ca9bb2d24"}
```

---

### Steps to reproduce:
1. Create a new account and set it to a mailinator.com email.
2. Try and verify your email.

### Actual results:
Sadness.

![_2__mailinator_-_free__disposable__email_](https://cloud.githubusercontent.com/assets/557895/2867326/ebeb008c-d234-11e3-9e04-fceae080fd2c.png)

### Expected results:
Happiness.

### Workaround:
Select all the text. The "Verify" text appears. White on white, bro.

![_2__mailinator_-_free__disposable__email_](https://cloud.githubusercontent.com/assets/557895/2867330/0632344c-d235-11e3-8623-8bf62658aaa3.png)

**Comment by shane-tomlinson** [comment]
All email templates are now located in the fxa-auth-mailer repo. Moved to https://github.com/mozilla/fxa-auth-mailer/issues/29, closing.
