### ISSUE TITLE
Track unsuccessful logins and display to users in a settings/security panel

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#112]
Per https://github.com/mozilla/fxa-auth-server/issues/222#issuecomment-29769332

> 3) add a security history panel similar to GitHub's where we display recent successful and unsuccessful logins (or at least recent unsuccessful logins).

**Comment by vladikoff** [comment]
We talked about this and we need several components to have this. 
@johngruen @ryanfeeley suggest using an email instead of showing under this info settings

**Comment by shane-tomlinson** [comment]
We should open a user store for this in the fxa repo.

**Comment by rfk** [comment]
Let's close this until it comes back as part of a user story
