### ISSUE TITLE
Make forced reauthentication optional after password change

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1121]
Currently when a password is changed, the user is required to re-authenticate all connected clients. We should make this behavior optional, asking the user which clients they would like to disconnect, so that they can avoid password reentry.

**Comment by issues-bouncer** [comment]
Hey @ryanfeeley, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
from mtg:

@rfk this might need a milestone or something if we want to work on this
