### ISSUE TITLE
about:accounts doesn't detect the lack of localstorage properly

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-content-server#1140]
Steps to reproduce:

1. in a new Fx29 profile, go to `about:config`
2. set `dom.storage.enabled` to `false`
3. try setting up Sync

Expected:

> error message warning about localstorage and linking to a place that tells users to look in `about:config` for `dom.storage.enabled`

Actual:

> unhelpful error message that talks about cookies and links to an equally unhelpful article showing how to enable cookies (which are already fully enabled)

I only found the root of this problem by visiting my old [Persona troubleshooting](http://people.mozilla.org/~fmarier/troubleshoot.html) page.

**Comment by TDA** [comment]
@vladikoff Does the code wrap the localStorage access in a try-catch block? If so, we can simply return false instead of throwing the exception, and then if the returned value is false, we can display the error?

**Comment by vladikoff** [comment]
Fixed 
![image](https://cloud.githubusercontent.com/assets/128755/8826929/d18578d0-3057-11e5-8537-ba3357ed2cc6.png)

**Comment by shane-tomlinson** [comment]
Here is a photo showing from about:accounts:

![screen shot 2015-07-22 at 16 29 55](https://cloud.githubusercontent.com/assets/848085/8829533/0b38d054-308f-11e5-9acf-6b18466d9192.png)
