### ISSUE TITLE
In OAuth after a successful signin, if I get back to the OAuth signin URI, it asks my password again 

### ISSUE THREAD

**Issue by renoirb** [mozilla/fxa-content-server#1195]
*use-case*: First time I get to `/oauth/sigin?state=1&client_id=a&scope=profile` and I sign in, its all fine. But if I happen get back to the same URL later (maybe with different `state`), it asks me to signin again. And that, even if the non oauth (e.g. `/signin`) recognizes that i'm logged in and redirects me to `/settings`.

Few questions:

1) Is this an expected behavior, or just something not done yet?
2) Is there plans to do, and implementation proposal to read somewhere?

**Comment by vladikoff** [comment]
Old issue / question, current "passwordless" should be clearer now.
