### ISSUE TITLE
Help self-hosters comply with the Mozilla Trademark Policy

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#1207]
Unlike our other http+json server repos, this one actually bundles trademarked Mozilla IP such as the Firefox logo and the Mozilla wordmark.  It would be good to have an explicit story about how the trademark policy [1] applies when other folks deploy this code.

If I were to set up a self-hosted version of this repo for my friends and I to use, would I be in violation of the policy?  Probably not, as long as I'm not charging them for it.  Could Debian distribute a package of this repo?  Not without renaming it to "Iceweasel Accounts" and changing the graphics.  Am I even remotely qualified to speculate on such issues?  Nope.

Perhaps we should do what the Firefox build process does, bundling generic free-to-distribute graphics by default, and using a `--enable-official-branding` flag to switch on the Official Mozilla (tm) Trademarks.

[1] https://www.mozilla.org/en-US/foundation/trademarks/policy/

**Comment by shane-tomlinson** [comment]
@rfk - I'm closing this until we decide it really needs done. We can re-open it then.
