### ISSUE TITLE
Inconsistent `links` tags

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1224]
From @pdehaan in https://github.com/mozilla/fxa-content-server/pull/1219#issuecomment-45692657

====================

I'd almost be concerned with a \<div\> to \<ul\> change for consistency, but I'm not sure how consistent the [`links`](https://github.com/mozilla/fxa-content-server/search?q=%22links%22&type=Code) are currently in the .mustache templates or if it warrants my mildest of concerns:

```sh
$ grep -inr "class=\"links\"" app/scripts/templates
```

| PAGE | HTML |
|----|----|
| [/app/scripts/templates/**cannot_create_account**.mustache:10](https://github.com/mozilla/fxa-content-server/blob/0bf2a0e2331ddee6a8564b8d7f69f5419c4dccd4/app/scripts/templates/cannot_create_account.mustache#L10) | `<p class="links">` |
| [/app/scripts/templates/**change_password**.mustache:40](https://github.com/mozilla/fxa-content-server/blob/423029daea3ab0d8eab75cba3da131ba7d9210ac/app/scripts/templates/change_password.mustache#L40) | `<div class="links">` |
| [/app/scripts/templates/**complete_reset_password**.mustache:14](https://github.com/mozilla/fxa-content-server/blob/01865c654799ab9e1d4281da6aa7f766f1f8da00/app/scripts/templates/complete_reset_password.mustache#L14) | `<div class="links">` |
| [/app/scripts/templates/**confirm**.mustache:15](https://github.com/mozilla/fxa-content-server/blob/16399a5bf44da08b26fe32454ecdd3c0b8c466b7/app/scripts/templates/confirm.mustache#L15) | `<div class="links">` |
| [/app/scripts/templates/**confirm_reset_password**.mustache:13](https://github.com/mozilla/fxa-content-server/blob/8b5471c5ad7c2a588ec2b4faefc03c138110fa00/app/scripts/templates/confirm_reset_password.mustache#L13) | `<ul class="links">` |
| [/app/scripts/templates/**delete_account**.mustache:27](https://github.com/mozilla/fxa-content-server/blob/59462de01447bdcbb63957c2966b4ac473bb82de/app/scripts/templates/delete_account.mustache#L27) | `<div class="links">` |
| [/app/scripts/templates/**force_auth**.mustache:29](https://github.com/mozilla/fxa-content-server/blob/70c88e76cc26f7dd9f4e0b9426908260fd3a8ab6/app/scripts/templates/force_auth.mustache#L29) | `<div class="links">` |
| [/app/scripts/templates/**legal**.mustache:6](https://github.com/mozilla/fxa-content-server/blob/0bf2a0e2331ddee6a8564b8d7f69f5419c4dccd4/app/scripts/templates/legal.mustache#L6) | `<section class="links">` |
| [/app/scripts/templates/**reset_password**.mustache:25](https://github.com/mozilla/fxa-content-server/blob/1245b97053ec3600022a2a99109ab65cb697e584/app/scripts/templates/reset_password.mustache#L25) | `<div class="links">` |
| [/app/scripts/templates/**settings**.mustache:12](https://github.com/mozilla/fxa-content-server/blob/7ba16c6f2c6ec57ec020cc0513e79b8aae379a11/app/scripts/templates/settings.mustache#L12) | `<ul class="links">` |
| [/app/scripts/templates/**sign_in**.mustache:35](https://github.com/mozilla/fxa-content-server/blob/00bda1e61cdd04f1dd5024fe1aeca7c9bbccfe72/app/scripts/templates/sign_in.mustache#L35) | `<div class="links">` |
| [/app/scripts/templates/**sign_up**.mustache:73](https://github.com/mozilla/fxa-content-server/blob/ee1c4ceff131ac3a37c596525c43812cb6e20ec5/app/scripts/templates/sign_up.mustache#L73) | `<div class="links">` |

**Comment by johngruen** [comment]
@pdehaan: you know what, i'm gonna un-z-later this bad boy. I noticed doing the Sass work that this links class is being applied like crazy to just just whatever. gonna try to get some clarity around just what the heck is going here.

**Comment by pdehaan** [comment]
@johngruen Awesome! Here's the latest output from #master branch:
```sh
$ grep -inr "class=\"links\"" app/scripts/templates
```

| PAGE | HTML |
|----|----|
| app/scripts/templates/**cannot_create_account.mustache:10:**    | `<p class="links">`
| app/scripts/templates/**change_password.mustache:42:**      | `<div class="links">`
| app/scripts/templates/**complete_reset_password.mustache:15:**    | `<div class="links">`
| app/scripts/templates/**complete_sign_up.mustache:16:**    | `<div class="links">`
| app/scripts/templates/**confirm.mustache:16:**    | `<div class="links">`
| app/scripts/templates/**confirm_account_unlock.mustache:16:**    | `<div class="links">`
| app/scripts/templates/**confirm_reset_password.mustache:14:**    | `<ul class="links">`
| app/scripts/templates/**delete_account.mustache:33:**      | `<div class="links">`
| app/scripts/templates/**force_auth.mustache:32:**    | `<div class="links">`
| app/scripts/templates/**legal.mustache:7:**  | `<section class="links">`
| app/scripts/templates/**reset_password.mustache:26:**      | `<div class="links">`
| app/scripts/templates/**settings/avatar.mustache:13:**    | `<ul class="links">`
| app/scripts/templates/**settings/avatar_camera.mustache:24:**    | `<ul class="links">`
| app/scripts/templates/**settings/avatar_crop.mustache:34:**    | `<ul class="links">`
| app/scripts/templates/**settings/avatar_gravatar.mustache:21:**    | `<ul class="links">`
| app/scripts/templates/**settings.mustache:26:**    | `<ul class="links">`
| app/scripts/templates/**sign_in.mustache:46:**           | `<div class="links">`
| app/scripts/templates/**sign_in.mustache:57:**          | `<div class="links">`
| app/scripts/templates/**sign_in.mustache:85:**      | `<div class="links">`
| app/scripts/templates/**sign_up.mustache:108:**    | `<div class="links">`

**Comment by johngruen** [comment]
Thus spoke @pdehaan
