### ISSUE TITLE
Allow users to remain connected to services and to control access to each service individually

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1238]
Further to our discussion yesterday @ckarlof @johngruen 

When a user’s password is changed, they are forced to re-authenticate in whatever service and/or client they are using. This is inconvenient for the user, and adds a lot of unnecessary UI.

Let's discuss the possibilities of doing away with the need to re-enter the password, and allow users to instead view a list of authorized (and revokable) clients/services on accounts.firefox.com.

![connected-services](https://cloud.githubusercontent.com/assets/68213/3271200/4647a7c0-f309-11e3-94fc-e87743db886c.png)

This is the model used in many places on the web including:
* https://twitter.com/settings/applications
* https://www.facebook.com/settings?tab=applications
* https://github.com/settings/applications

**Comment by ryanfeeley** [comment]
@ckarlof @johngruen Spotted these two in Evernote today after I changed my password
![evernote1](https://cloud.githubusercontent.com/assets/68213/6249027/4e44b3ce-b752-11e4-81e9-f07a85950053.png)
![evernote2](https://cloud.githubusercontent.com/assets/68213/6249028/53349d86-b752-11e4-9839-ca44c9eb2d68.png)

.

**Comment by shane-tomlinson** [comment]
ref #127. Assigning to @rfk to add to roadmap.

**Comment by rfk** [comment]
I've linked this under "future goals" in the FxA roadmap, but we've no plans to schedule it for implementation.  @ryanfeeley this should not stop you from prepping a design here though if you're feeling inspired (modulo our recent chat about feasibility of staying logged in after a password reset).

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @rfk - Should this be a user story in the https://github.com/mozilla/fxa repo instead of here so this work can be prioritized? If so, let's close it out here.

**Comment by rfk** [comment]
Yes; in fact I think it's covered by existing user stories. @ryanfeeley IIUC you're working on a revamp of the designs here anyways, so I'm going to close this out.
