### ISSUE TITLE
Enable CSP when testing with selenium

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1256]
CSP currently seems to be disabled when running selenium tests. We should figure out a way to enabled it locally and on travis.

**Comment by issues-bouncer** [comment]
Hey @zaach, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
@AutomatedTester, if you have a sec, is there any chance CSP will be possible in Firefox Driver + Marionette in future versions of Selenium?

**Comment by shane-tomlinson** [comment]
This is going to be an impossible task with the way we currently dynamically attach scripts in our functional tests. Closing until we decide we are going to do this, or until we figure out a way to run the functional tests without running afoul of CSP.
