### ISSUE TITLE
Account Dashboards

### ISSUE THREAD

**Issue by vmunix** [mozilla/fxa-content-server#127]
3 stories (an epic!?) just to capture these. Breakout/fix as needed.

1) As a signed in user, I want be able view a dashboard page that shows me what services are attached to my Firefox Account so that I can quickly understand how my account is being used.   Ex: https://www.google.com/settings/dashboard

2) As a signed in user, I want to download my data in published formats for services that are attached to my Firefox Account.  Ex: https://www.google.com/settings/takeout

3) As a signed in user, I want to see a report of my Account Activity so that I can understand how/when attached services are being used.  Ex: https://www.google.com/settings/activity

**Comment by shane-tomlinson** [comment]
Assigning to @rfk to add to roadmap and close when appropriate.

**Comment by rfk** [comment]
We have this on our roadmap under "future goals" but it's not scheduled for implementation.  I think this bug is old enough that we can leave it closed it out and revisit with fresh eyes when we get around to implementing this.
