### ISSUE TITLE
No confirmation request when user signs out of firefox account

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1272]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1027152

---

The Firefox Accounts settings page has a sign out button. When tapped, the user is automatically signed out of their profile and returned to settings menu. There should be a pop up asking the user to confirm that they wish to sign out of their profile. Anyone who accidentally taps the button will be automatically signed out.

### Repro Steps:
1) Update a Flame to BuildID: 20140618000202
2) Launch Settings >> Firefox Accounts
3) Sign into a valid Firefox account
4) On the Firefox Accounts Settings screen, tap the sign out button

### Actual:
User is immediately signed out of profile

### Expected:
A pop up appears asking the user to confirm that they wish to sign out

### v2.0 Environmental Variables:
Device: Flame v2.0 MOZ
BuildID: 20140618000202
Gaia: 83844c7679b3b9f6e7f1116c1eeec2d1e7a64eec
Gecko: 55679dc2e72b
Version: 32.0a2
Firmware Version: v121-2

### Notes:

Repro frequency: 100%
See attached: logcat

**Comment by shane-tomlinson** [comment]
bump @johngruen and @ryanfeeley - could we get some of your expertise & opinion here?

**Comment by ryanfeeley** [comment]
I had at one point recommended that we put the Delete Account and Sign Out options behind another option called Advanced Settings to reduce accidental clicks. Would that suffice?

**Comment by johngruen** [comment]
Resolved by #2336. New settings make accidental taps impossible.

**Comment by zaach** [comment]
Once  the newsettings lands we can see if the rate of signing out changes.
