### ISSUE TITLE
inconsistent use of 'use strict'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1318]
Sometimes it's used globally, sometimes inside of the module definition. Choose one.

**Comment by shane-tomlinson** [comment]
Closing as "z-later". Happy to mentor if someone wants to pick this up!

**Comment by TDA** [comment]
ESLint's "strict": [2, "global"] is what we seem to require. Can't seem to find an equivalent in JSHint.
http://eslint.org/docs/rules/strict

**Comment by pdehaan** [comment]
@TDA: Did you find a JSHint/JSCS rule that enforces this, or did you just manually audit+correct all the files?

**Comment by TDA** [comment]
@pdehaan  Nope, couldnt find any in jshint/jscs, and apparently such an option doesnt exist, according to this reply:
http://stackoverflow.com/questions/30672426/jshint-equivalent-of-eslints-strict2-global-mode

I added those to the files(well, a script did anyway).
