### ISSUE TITLE
Don't show Sync password reset warning when the user isn't using Sync.

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#1336]
*Previous title: "Don't show Sync password reset warning when reset request comes from FFOS"*

If the originating client for password reset is FFOS, we shouldn't show that Sync disclaimer message. 

![screen shot 2014-06-30 at 2 42 52 pm](https://cloud.githubusercontent.com/assets/3323249/3434121/720dd8ea-0086-11e4-9118-ca9c42cdc277.png)

**Comment by shane-tomlinson** [comment]
We could possibly use the `sessionTokenContext` or some other signal to figure out if a user has used the account for sync. `sessionTokenContext` does not persist across re-sign-ins if the user signs in to a 2nd service with the same address, so perhaps we add a new field to the account model, something like `syncAccount`, `usedForSync` or just `sync` that is not updated across sign-ins.

**Comment by vladikoff** [comment]
@johngruen @rfk do we still want to do this? We can just add "For security reasons, *if you use Firefox Sync*, resetting your password will..."

**Comment by rfk** [comment]
With device-manager stuff in the works, I think we're finally moving towards a world where we can easily tell whether or not you've got stuff syncing to your account.  We should revisit this once the shape of that service is a little more settled.
