### ISSUE TITLE
Remove robots.txt for production (or make less restrictive)?

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#1338]
Now that we're live, I don't thing we should be so restrictive with our robots.txt policy:

https://accounts.firefox.com/robots.txt

**Comment by vladikoff** [comment]
@ckarlof Should we create a bugzilla bug for this?

**Comment by ckarlof** [comment]
PR to https://github.com/mozilla-services/puppet-config, which you may or may not have access to. If you don't a Gist would suffice.

**Comment by vladikoff** [comment]
Tracking in https://github.com/mozilla/fxa-content-server/issues/1338
