### ISSUE TITLE
When a user cancels the merge warning dialog, the registration form is unable to be submitted

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1345]
Precondition:
- Current or previous usage of the new Sync in the current desktop sandbox

Steps:
 1. Fill out the form to create a new account (not sure if Choose what to sync is relevant) 
 2. Click Next
 3. Click cancel on the merge warning dialog
 4. Notice that the form can no longer be submitted

Expected result:
- Form will submit and merge warning dialog will appear again

Actual result:
- Form behaves as if Next button is diabled

**Comment by johngruen** [comment]
@ryanfeeley can you repro or close?

**Comment by ryanfeeley** [comment]
The Merge Warning dialog now appears again if you try to register after pressing cancel, so as far as I am concerned this has since been fixed!

**Comment by vladikoff** [comment]
Yay!
