### ISSUE TITLE
Redirect from email on B2G leads to signin page, not logged-in state.

### ISSUE THREAD

**Issue by karlht** [mozilla/fxa-content-server#1366]
Re-filing from https://github.com/mozilla/fxa-oauth-server/issues/99:

Platform:  Flame device, B2G 2.0.0

Steps to reproduce: 
1. Go to https://123done-stage.dev.lcip.org
2. Click Sign Up.
3. Enter email and password and COPPA.
4. Open email app, click link in verification email.  (link is: https://accounts.stage.mozaws.net/v1/verify_email?uid=f2a40defde09481299e99cb83585ec39&code=f438b841677bdb6c0b09488a1a8b1274&service=808f8100f67c9396 )

Expected:
1. Arrive in 123done, logged in.

Actual:
1. Arrive on 123done signin/signup page, not logged in.

I suspect a mishandling of a redirect_url, somewhere.

**Comment by vladikoff** [comment]
Just tested it twice on latest Flame firmware, seems like this was fixed!
