### ISSUE TITLE
No content when browsing to /en-us/legal/

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1443]
Found in https://latest.dev.lcip.org/ver.json (commit a8a0d8db58f1a494196d50a1c32be87c0744a3c2)

```json
{
    "version": "0.17.0",
    "commit": "a8a0d8db58f1a494196d50a1c32be87c0744a3c2",
    "l10n": "5baeb4c948",
    "tosPp": "c321fc714a"
}
```

---

### Steps to reproduce:
1. Go to https://latest.dev.lcip.org/en-us/legal/ directly.

--or--

1. Set your browser's default language to "Romanian [ro]" (other's work too, but it apparently needs to be a supported language without a translation).
2. Go to https://latest.dev.lcip.org/signup
3. Click on the [[ Privacy Notice ]] link (or [[ Terms of Service ]]) and you should be taken to https://latest.dev.lcip.org/legal/privacy. It's English, and pretty, and has a Back button.
4. Press the browser refresh button (oddly, it looks like the "Privacy Notice" heading jumps down 1-2px, but ignore that). Your back button also disappears, and your page URL changes to https://latest.dev.lcip.org/en-us/legal/privacy (note the addition of **/en-us/**).
5. Change the URL to https://latest.dev.lcip.org/en-us/legal/ (note the removal of the trailing **/privacy**).

### Actual results:
![firefox_accounts](https://cloud.githubusercontent.com/assets/557895/3682171/e5b3583c-12c5-11e4-8d98-719dcec0df86.png)
**Figure 1.**

### Expected results:
If I go to https://latest.dev.lcip.org/legal/ directly (without leading **/en-us/** or trailing **/privacy**), i see some content:

![legal](https://cloud.githubusercontent.com/assets/557895/3682181/0db5a81c-12c6-11e4-8f7c-2ac762b23df4.png)
**Figure 2.**

**Comment by vladikoff** [comment]
This should 404 indeed!

**Comment by shane-tomlinson** [comment]
This is still a problem.

**Comment by vladikoff** [comment]
Closing this for now, there are no direct links to the mentioned url and last time I checked it was not easy to modify this route.
