### ISSUE TITLE
Organize OAuth flows by client_id

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#1506]
To better manage several oauth flows we should organize them in a key / map.

Draft:
![image](https://cloud.githubusercontent.com/assets/128755/3815074/360d79f2-1cc1-11e4-8a98-baede3fd575a.png)
via @ckarlof

**Comment by shane-tomlinson** [comment]
@vladikoff - is this still necessary? Are we really gonna do it some day?

**Comment by vladikoff** [comment]
> @vladikoff - is this still necessary? Are we really gonna do it some day?

Maybe there is a way to determine how many OAuth flows start when there was already one in progress...

**Comment by vladikoff** [comment]
> Are we really gonna do it some day?

we'll do it when needed
