### ISSUE TITLE
Handle WebChannel errors

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#1513]
Need to add this somewhere in the OAuth flow:
```
channel.on('message', function (data) {
  if (data.message.error) {
     receivedError = true;
     self.displayError(data.message.error, OAuthErrors);
     self._buttonProgressIndicator.done();
   }
});
```

**Comment by vladikoff** [comment]
@shane-tomlinson thoughts on this? With all the new WebChannel features, did you have the need for `data.message.error` ?

**Comment by shane-tomlinson** [comment]
@vladikoff - I am working on a PR (https://github.com/shane-tomlinson/fxa-content-server/pull/26#discussion-diff-30497337R34) to surface channel errors in a generic manner. Let's keep this open for now. Assigning to me.

**Comment by shane-tomlinson** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1173830

**Comment by vladikoff** [comment]
Left a comment here: https://bugzilla.mozilla.org/show_bug.cgi?id=1173830#c1

**Comment by issues-bouncer** [comment]
Hey @shane-tomlinson, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
Dup / Moved to https://github.com/mozilla/fxa-content-server/issues/3668
