### ISSUE TITLE
Channels: if WebChannel is enabled then "about:accounts" events are sent over the WebChannel

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#1528]
If WebChannel flow is enabled, then FxA Native flow will also send events using WebChannel.
i.e 

![image](https://cloud.githubusercontent.com/assets/128755/3850665/9a123276-1e88-11e4-977d-b47e3d7bdb14.png)

![image](https://cloud.githubusercontent.com/assets/128755/3850645/5fc37030-1e88-11e4-98a8-8f97bc558521.png)

Possible fix with https://github.com/mozilla/fxa-content-server/pull/1510

**Comment by vladikoff** [comment]
Will confirm if this still happens

**Comment by shane-tomlinson** [comment]
With the separation of auth brokers and channels, this no longer occurs. `can_link_account` is only sent in the [fx-desktop broker](https://github.com/mozilla/fxa-content-server/blob/8de991cf9a9fa51b16d07dbda980bab382734bc2/app/scripts/models/auth_brokers/fx-desktop.js#L63), and never in the OAuth WebChannel broker. Closing.
