### ISSUE TITLE
Sync: Not possible to tell if errors occurred with a custom "services.sync.tokenServerURI" setting

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#1530]
If a user has a custom configured `services.sync.tokenServerURI` then `about:preferences#sync` UI will not throw errors. 

![image](https://cloud.githubusercontent.com/assets/128755/3863776/0fba287e-1f4e-11e4-9482-3bc84408b775.png)

**Comment by rfk** [comment]
I'm closing this as it's very old, and this doesn't seem like the right place to track it anyway.  If this is still important, please re-file in bugzilla under the Sync component.
