### ISSUE TITLE
add a local-only functional test for the avatar camera view

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1536]
We can't test the camera in our automated flow, but this would be better than manually testing it. Continues #1532.

**Comment by ckarlof** [comment]
@vladikoff, is this possible?

**Comment by vladikoff** [comment]
> @vladikoff, is this possible?

Yeah, we didn't do this because it requires the test machine to have a working camera

**Comment by shane-tomlinson** [comment]
Closing, we don't really have a way to do this.

**Comment by vladikoff** [comment]
We will explore this if really needed
