### ISSUE TITLE
Reevaluate our use of `t` helper functions

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1538]
@nchapman raises a good point in https://github.com/mozilla/fxa-content-server/pull/1496#discussion_r15966824.

Here was my comment

> Ugh, yeah maybe. t, as such, is kind of a hack. The way gettext and extraction are intended to work, t or whatever we call it would actually perform the translation, rather than just act as a stand in. If we want to go through the trouble of creating a module for it, maybe we should just use the translation module instead?

**Comment by pdehaan** [comment]
![](http://i3.kym-cdn.com/photos/images/facebook/000/129/577/1a4.jpg)
