### ISSUE TITLE
Convert avatar header mustache templates into partials

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1551]
Re: https://github.com/mozilla/fxa-content-server/pull/1550/files

Since it looks like the same header repeated 5 times in 5 files, not sure if we want to turn this into a partial or something a bit easier to maintain.

```html
   <header>
     <h3 id="fxa-settings-sub-header"><a href="/settings">{{#t}}Manage account{{/t}}</a> ›</h3>
     <h1 id="fxa-account-picture-header">{{#t}}Account picture{{/t}}</h1>
   </header>
```

Also, not sure if we want to use the &rsaquo; or `&rsaquo;`. Not sure what is more compatible with... things.

**Comment by zaach** [comment]
No longer relevant.
