### ISSUE TITLE
Enable Avatars and Profile Images for Everyone

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1582]
Consider this a tracking bug for when we flip the switch and enable the profile images for everyone.

Related: #1567

**Comment by zaach** [comment]
So this is currently available for mozillian email addresses. The current plan seems to be to wait for RPs to integrate so that we can dogfood a bit more before turning it on for the general public.

**Comment by zaach** [comment]
Current blocker is noted here: https://bugzilla.mozilla.org/show_bug.cgi?id=1140644

We need a tooltip to warn about sharing your email with Gravatar for that option.

**Comment by jrgm** [comment]
Is that the right bug? I'm not allowed to access https://bugzilla.mozilla.org/show_bug.cgi?id=1140644

**Comment by rfk** [comment]
yes; it's a legal bug so confidental by default, I added you to the /cc list

**Comment by ckarlof** [comment]
We currently have some rules around hiding this affordance in the settings page, and we need to decide when to remove these rules so everyone can add a profile image from the settings page.

Profile images on Sync pref pane is scheduled to go live in Fx41 (https://bugzilla.mozilla.org/show_bug.cgi?id=1171253). When do we expose this? Sometime in Beta? The concern was to minimize the time period that release users could add an avatar and not see it in their browser, but also make sure we lead the actual release of Fx41 to give us a little breathing room.

We should also make sure we're comfortable how we're scaling.

@rfk, @edmoz, @zaach, please coordinate.

**Comment by edmoz** [comment]
Currently profile images is enabled for all users (any domain), via Nightly prefs, hamburg menu, accounts settings 'change' link.  I'd like to close this issue - knowing that avatar is riding the trains (hamburger menu support to be uplifted)

**Comment by edmoz** [comment]
I would confirm that 'change' link displays in Fx 42 (Nightly )but not in Fx 39 (Release).

**Comment by zaach** [comment]
The change link is only visible on /settings if you've already added a profile image at some point or have a mozilla email address. If you visit with a fresh, non-mozilla email account it should currently be hidden.

**Comment by rfk** [comment]
More specifically, I believe @ckarlof is talking about this able experiment:

  https://github.com/mozilla/fxa-content-experiments/blob/master/avatar-link/avatar-link-visible.js

Which limits who can see the link to the avatar page on accounts.firefox.com.  AFAICT we have two main options:

  1) just configure that experiment to enable it for everyone some time during the Fx42 beta cycle
  2) gradually step up the percentage of users who see the link in order to test scaling etc

I'm not convinced (2) will give us much incremental value because most people don't just click around in the settings page looking for something to do.

**Comment by rfk** [comment]
I guess we could try enabling it for e.g. 5% of users now, while the profile images are in nightly, and see if it produces any significant uptick in avatar uploads.  That would at least give us a sense of how many people would access it through there vs through the UI in Firefox.

Alternately, can we configure the experiment to enable for users on Fx42 or higher?

**Comment by vladikoff** [comment]
Gravatar is back via this merged PR: https://github.com/mozilla/fxa-content-server/pull/2712
(with a permission dialog now)

**Comment by zaach** [comment]
We can switch the able feature flag to true when Beta is released.

**Comment by rfk** [comment]
Sounds good.  IIUC able will let us a set a future date for enabling the experiment, so we should probably go ahead and configure that in now while we think of it:

  https://github.com/mozilla/fxa-content-experiments/issues/21

**Comment by vladikoff** [comment]
Track this in https://github.com/mozilla/fxa-content-experiments/issues/21
