### ISSUE TITLE
about:accounts functional testing for signin

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#1595]
signin (and maybe other) tests were missing from #1576.

**Comment by shane-tomlinson** [comment]
When @ryanfeeley and I created https://docs.google.com/a/mozilla.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA, I added a ton of Sync related tests. They do not test about:accounts, but synthesize about:accounts responding to FirefoxAccountsCommands.

Closing as "good enough for now."
