### ISSUE TITLE
Ability to upload an avatar picture via drag-n-drop

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1617]
### Steps to reproduce:
1. Go to https://latest.dev.lcip.org/settings/avatar/
2. Open Finder/Explorer and try and drag an image onto the UI to upload a new profile picture.

### Actual results:
Dragging an image onto the "stage" replaces the current page.

### Expected results:
Fancy drop-target which takes the image and uploads it and brings up cropper UI.

**Comment by johngruen** [comment]
@ryanfeeley: are we still doing this? can i close this?

**Comment by ryanfeeley** [comment]
It was in the original design, but descoped at some point. @zaach is it tricky to implement?

**Comment by ckarlof** [comment]
Let's decide if we still want to do this, otherwise, let's close this out.

**Comment by johngruen** [comment]
@ckarlof @ryanfeeley I vote meh

**Comment by ryanfeeley** [comment]
Closing
