### ISSUE TITLE
Convert durations into a more readable format

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1657]
via https://github.com/mozilla/fxa-content-server/pull/1655#discussion_r17499458

In a lot of places we have code like this:
```js
var CERT_DURATION_MS = 1000 * 60 * 60 * 6; // 6hrs
var ASSERTION_DURATION_MS = 1000 * 3600 * 24 * 365 * 25; // 25 years
```

It may be nice if we could switch to some duration library to do something a bit more readable like [**duration-js**](https://www.npmjs.org/package/duration-js):
```js
var CERT_DURATION_MS = new Duration('6h');
var ASSERTION_DURATION_MS = new Duration('52w') * 25; // 25 years
```

Or using [**moment**](https://www.npmjs.org/package/moment):
```js
var CERT_DURATION_MS = moment.duration(6, 'hours');
var ASSERTION_DURATION_MS = moment.duration(25, 'years');
```

---

Actually, here's a longer list of places where we're making up some times:
```sh
$ grep -Ir "1000 *" . --exclude-dir="node_modules" --exclude-dir=".tmp" --exclude-dir="app/bower_components" --exclude-dir="dist"  | grep -v ".svg:" | grep -v "bower_components" | grep -v app/scripts/vendor/

./app/scripts/lib/assertion.js:  var CERT_DURATION_MS = 1000 * 60 * 60 * 6; // 6hrs
./app/scripts/lib/assertion.js:  var ASSERTION_DURATION_MS = 1000 * 60 * 5; // 5mins
./app/scripts/lib/channels/fx-desktop.js:  var DEFAULT_SEND_TIMEOUT_LENGTH_MS = 1000;
./app/scripts/lib/metrics.js:  var TEN_MINS_MS = 10 * 60 * 1000;
./app/scripts/views/form.js:    LONGER_THAN_EXPECTED: 10000, // 10 seconds
./app/scripts/views/mixins/resend-mixin.js:  var SHOW_RESEND_IN_MS = 5 * 60 * 1000; // 5 minutes.
./app/tests/spec/views/confirm.js:            }, view.VERIFICATION_POLL_IN_MS + 1000);
./server/bin/csp-violation-server.js:      when: (new Date()).getTime() / 1000,
./server/lib/configuration.js:    default: 10 * 60 * 1000 // 10 minutes
./tests/functional/firefox/same_account.js:        .sleep(1000)
./tests/functional/lib/helpers.js:    }, [ selector ], 10000);
./tests/lib/restmail.js:          }, 1000);
./tests/server/configuration.js:    var dfd = this.async(10000);
./tests/server/metrics-collector-stderr.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/proxy.js:    var dfd = this.async(1000);
./tests/server/templates.js:      var dfd = this.async(1000);
```

Plus the few places where we did `* 1000` instead of `1000 *`:
```sh
$ grep -Ir "* 1000" . --exclude-dir="node_modules" --exclude-dir=".tmp" --exclude-dir="app/bower_components" --exclude-dir="dist"  | grep -v ".svg:" | grep -v "bower_components" | grep -v app/scripts/vendor/

./app/scripts/lib/metrics.js:  var TEN_MINS_MS = 10 * 60 * 1000;
./app/scripts/views/mixins/resend-mixin.js:  var SHOW_RESEND_IN_MS = 5 * 60 * 1000; // 5 minutes.
./server/lib/configuration.js:    default: 10 * 60 * 1000 // 10 minutes
```

**Comment by npestana** [comment]
@pdehaan Which option seems to be the choice?

**Comment by philbooth** [comment]
@npestana, we just chatted about this and duration.js is the preferred option.

**Comment by larissagaulia** [comment]
@pdehaan,
`var CERT_DURATION_MS = 1000 * 60 * 60 * 6; ` and  `var CERT_DURATION_MS =  new Duration('6h');`
 are not interchangeable. 
new Duration('6h') returns the following object:
Duration {_milliseconds: 21600000}, thus not consistent with the previous type (number)

I'd have to make it
`var CERT_DURATION_MS =  new Duration('6h').milliseconds();`

In my humble opinion it's still more readable. 
I've made all the refactoring locally adding .milliseconds(), can I send you a PR or would you like me to reconsider?

**Comment by vladikoff** [comment]
> new Duration('6h') returns the following object:
Duration {_milliseconds: 21600000}, thus not consistent with the previous type (number)

Yeap that's correct. You can rerun the `grep` command from @pdehaan again and make changes to the files in `./app`. Do not worry about adding Duration.js to tests. 

To add the library you need to add `duration-js` to bower.json (see https://github.com/mozilla/fxa-content-server/blob/master/bower.json), something like `node_modules/.bin/bower i duration.js --save --save-exact` should work. Then include it in requirejs paths: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/require_config.js#L24

Part of the unit tests we need to make sure new `CERT_DURATION_MS` and some others are proper milliseconds. Tests might do that already, need to double check. 

Let us know if you have questions.

**Comment by larissagaulia** [comment]
Outch, I've made it for the tests too, you'd rather I undo it?

**Comment by larissagaulia** [comment]
What should be the <scope> of this refactoring ?
as in refactor(<scope>): Convert durations into duration-js 
can I put client, tests ?

**Comment by vladikoff** [comment]
> Outch, I've done it for the tests too, you'd rather I undo it?

Ah that's fine, send a pull request with those changes and we will discuss.

> What should be the scope of this refactoring ?
> as in refactor(scope): Convert durations into duration-js 
> can I put client, tests ?

`refactor(client): ...` should be fine :+1:
