### ISSUE TITLE
Account management link from Sync should only direct to Sync account

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1671]

**Comment by shane-tomlinson** [comment]
Mark Hammond is already working on this! We support this on the content server side, the browser needs to be modified to use the right link

**Comment by pdehaan** [comment]
@zaach Says that Mark Hammond may already be working on this. Closing.

**Comment by ryanfeeley** [comment]
Also supports for Hello and other upcoming OAuth relying services?

**Comment by zaach** [comment]
We should file a bugzilla bug for Hello if there isn't one, but yes the
content server supports it for any relier.
