### ISSUE TITLE
keyboard accessibility for COPPA flow could use improvement

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1694]
Keyboard accessibility of the COPPA flow needs to be improved. I must use the mouse to cause the year picker to change to the month/day pickers, and pressing a tab from the month picker sets focus to the TOS/PP links.

Follow on for #1682

**Comment by shane-tomlinson** [comment]
The need for this is in question, if #2108 is implemented, this will be unnecessary.

**Comment by pdehaan** [comment]
Closing, pending #2108 PR
