### ISSUE TITLE
Consider adding support links on "Sign in" and "Reset password" pages

### ISSUE THREAD

**Issue by cvan** [mozilla/fxa-content-server#1710]
It would probably be helpful to link to a support page if a user has problems signing in or resetting his/her password. Maybe a user forgets which email address he used? Or a user never receives a confirmation link? We should have an FAQ, SUMO article, or some method of users contacting Mozilla in that case.

# Sign in
![screenshot 2014-09-29 15 38 59](https://cloud.githubusercontent.com/assets/203725/4450746/6a5f5d36-4829-11e4-84e9-382d880f6957.png)

# Reset password
![screenshot 2014-09-29 15 39 08](https://cloud.githubusercontent.com/assets/203725/4450748/6f608cf6-4829-11e4-9392-d11a45c877ed.png)

**Comment by shane-tomlinson** [comment]
@zaach asks "do we have SUMO articles?"

**Comment by vladikoff** [comment]
Do we need to add Services here: https://support.mozilla.org/en-US/ ?

**Comment by vladikoff** [comment]
Will be part of https://github.com/mozilla/fxa-content-server/issues/2765
