### ISSUE TITLE
Error message for invalid email should be generic

### ISSUE THREAD

**Issue by cvan** [mozilla/fxa-content-server#1711]
[Firefox Accounts](https://accounts.firefox.com/signin) shows an "Unknown account" error message when you attempt to sign:

![](https://cloud.githubusercontent.com/assets/203725/4450703/c7fd85a4-4828-11e4-847b-cc6f4f9f234c.png)

Although it's arguably a better user experience to know whether I've signed up for a service before or not, from a privacy perspective it's considered [best practice to use a generic error message for signing in and resetting passwords](https://www.owasp.org/index.php/Error_Handling#Generic_error_messages).

Here's what some major sites do:

[GitHub](https://github.com/):
> Incorrect username or password.

[Google](https://accounts.google.com/AccountChooser):
> The email or password you entered is incorrect.

[Twitter](https://twitter.com/login/):
> The email and password you entered did not match our records. Please double-check and try again.

**Comment by rfk** [comment]
I'm going to close this out, I think we're pretty comfortable with the tradeoffs of the current approach; thanks again for the report @cvan!
