### ISSUE TITLE
Avatar buttons look weird when running in a smaller viewport on mobile

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1730]
Found in https://accounts.stage.mozaws.net/ver.json (commit 7ff9e196311cef2e9e5a1726aa49081f2c0167a5)

```json
{
  "version": "0.22.0",
  "commit": "7ff9e196311cef2e9e5a1726aa49081f2c0167a5",
  "l10n": "9c6f728ea6",
  "tosPp": "2becbeea57"
}
```

---

### Steps to reproduce:
1. Create an account, and go to https://accounts.stage.mozaws.net/settings/avatar/change
2. Shrink your browser to a smaller viewport (larger than 319px wide, smaller than 481px).

### Actual results:
The button background color matches the page background color.

### Expected results:
A border or something at that specific RWD breakpoint.

---

![kontobild](https://cloud.githubusercontent.com/assets/557895/4481801/d64306cc-49a2-11e4-8b97-a14f22e078cb.png)
**Figure 1:** 481px by 734px

---

![kontobild](https://cloud.githubusercontent.com/assets/557895/4481817/f1b45ff0-49a2-11e4-9657-de13752117d1.png)
**Figure 2:** 480px by 734px

---

![kontobild](https://cloud.githubusercontent.com/assets/557895/4481833/0e1c54d6-49a3-11e4-9f22-5b99ac297004.png)
**Figure 3:** 320px by 734px

---

![kontobild](https://cloud.githubusercontent.com/assets/557895/4481839/2285aff8-49a3-11e4-8caf-8c4d1ee46167.png)
**Figure 4:** 319px by 734px

**Comment by zaach** [comment]
Fixed but not auto-closed by #2032.
