### ISSUE TITLE
Password playground

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1732]
So that I can create a strong, memorable password, as a user registering ~~on any website~~ for a Firefox Account, I want to be given some help to create a password based on a phrase.
WIREFRAMES: https://www.lucidchart.com/documents/view/146de3bf-3732-4660-9378-06fa3a4c1eac

**Comment by shane-tomlinson** [comment]
One for the roadmap.

**Comment by shane-tomlinson** [comment]
@rfk - can you add this to the roadmap?

**Comment by ryanfeeley** [comment]
![752429](https://cloud.githubusercontent.com/assets/68213/7144372/0f83bf9a-e2b3-11e4-98a4-0ef0d3de0050.gif)
