### ISSUE TITLE
"System unavailable, try again soon" on avatar camera page if you click too early

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1749]
Found in https://accounts.firefox.com/ver.json (commit )

```json
{
  "version": "0.22.0",
  "commit": "7ff9e196311cef2e9e5a1726aa49081f2c0167a5",
  "l10n": "9c6f728ea6",
  "tosPp": "2becbeea57"
}
```

---

### Steps to reproduce:
1. Go to https://accounts.firefox.com/settings/avatar/change
2. Click on "Camera" icon, and then quickly quickly try and click on the **[Take picture]** button before the page fully loads.

### Actual results:
> _"System unavailable, try again soon"_
Looks like because I was too fast, the "Take picture" button is disabled and doesn't reenable itself.

![account_picture](https://cloud.githubusercontent.com/assets/557895/4550999/3c5818bc-4e6c-11e4-8a7c-736148304e18.png)

### Expected results:
Not that.

### Work around:
Slow down there, buddy.

**Comment by vladikoff** [comment]
@pdehaan cannot reproduce this issue. does this still break for you?

**Comment by pdehaan** [comment]
Unable to repro in prod. Closing.
