### ISSUE TITLE
tighten up error event strings in client metrics

### ISSUE THREAD

**Issue by kparlante** [mozilla/fxa-content-server#1771]
Take a gander at the error events showing up in kibana:
https://kibana.fxa.us-west-2.prod.mozaws.net/#dashboard/temp/tXa9un-WRaWDRcZCRZvlkw

Here's a sample, taken at random:
screen.signup,error.signup.unknown namespace.101,screen.signin,error.signin.unknown namespace.103,error.signin.unknown namespace.Error: Unexpected error,error.signin.unknown namespace.103,error.signin.unknown namespace.Error: Unexpected error,screen.reset_password,screen.confirm_reset_password,screen.signin,error.signin.unknown namespace.Error: Unexpected error,error.signin.unknown namespace.Error: Unexpected error

"unknown namespace" should probably be replaced by something without a space, and "Error: Unexpected error" should be represented by a number.

**Comment by vladikoff** [comment]
"unknown namespace" was fixed

**Comment by vladikoff** [comment]
still happens in the dashboard it seems

**Comment by shane-tomlinson** [comment]
ref #3140

**Comment by vladikoff** [comment]
from triage: try to use the known namespace, in some cases we cannot prevent an "unknown namespace" due to hard errors.

let us know if we really need this.
