### ISSUE TITLE
Switch sv locale to sv_SE

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1773]
The `sv` locale is no longer being updated. We should disable it and make sure we serve `sv_SE` in its place.

**Comment by shane-tomlinson** [comment]
@zaach - is this just as simple as swapping `sv` for `sv-SE` in [production-locales.json](https://github.com/mozilla/fxa-content-server/blob/467f33a36baba967834205b147d7aa2665db358f/server/config/production-locales.json#L40)?

The sv_SE translation is at 100% in https://localize.mozilla.org/sv_SE/accounts/, it'd be nice to see them switched on.
