### ISSUE TITLE
Make the profile image button row responsive

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1779]
The bottom row of profile image buttons looks nasty when scaled down.

How about removing the circle and background like this @johngruen ?
![profile1](https://cloud.githubusercontent.com/assets/68213/4651996/e2738030-54a0-11e4-9f1b-1851458fd16d.png)
![profile2](https://cloud.githubusercontent.com/assets/68213/4651995/e26c211e-54a0-11e4-92dd-bf679a8c8dc7.png)

**Comment by zaach** [comment]
This was closed by https://github.com/mozilla/fxa-content-server/pull/2032
