### ISSUE TITLE
Inconsistent creation of OAuth server options blocks that contain service, redirectUri, etc.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1785]
As noted here: https://github.com/mozilla/fxa-content-server/pull/1778/files#r18929787

Example:

https://github.com/mozilla/fxa-content-server/blob/b00104ed327b1b11c25b2a1366421ba0592d439e/app/scripts/lib/fxa-client.js#L215-L229 

``` js
var signUpOptions = {
  keys: true
};
if (relier.has('service')) {
  signUpOptions.service = relier.get('service');
}
if (relier.has('redirectTo')) {
  signUpOptions.redirectTo = relier.get('redirectTo');
}
if (options.preVerified) {
  signUpOptions.preVerified = true;
}
if (options.preVerifyToken) {
  signUpOptions.preVerifyToken = options.preVerifyToken;
}
```

vs 

https://github.com/mozilla/fxa-content-server/blob/b00104ed327b1b11c25b2a1366421ba0592d439e/app/scripts/lib/fxa-client.js#L295-L297

``` js
var clientOptions = {
  service: relier.get('service'),
  redirectTo: relier.get('redirectTo'),
  resume: self._createResumeToken(relier)
};
```

**Comment by shane-tomlinson** [comment]
Code cleanup, z-later. I'm happy to mentor somebody through this.

**Comment by vladikoff** [comment]
cc @shane-tomlinson @vbudhram this could be part of https://github.com/mozilla/fxa-content-server/issues/2025

**Comment by shane-tomlinson** [comment]
@vladikoff - this issue is when we export fields to the FxA client, not import. Orthogonal but good to tackle too.

**Comment by shane-tomlinson** [comment]
I'm closing this issue. Sure, it's still a "problem", but it's a stylistic issue rather than a bug.
