### ISSUE TITLE
Feedback - avatar icon causes confusion - "If there is an icon, I want to click it"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1787]
Feedback from Dees Chinniah (@cyberdees) with regards to the avatar icon - "If there is an icon, I want to click it. When it doesn't do anything, I think it's broken."

@ryanfeeley, @johngruen, @zaach, @ckarlof - should we remove the icon until the avatar feature is fully ready?

**Comment by edmoz** [comment]
this is fixed
