### ISSUE TITLE
Better fallback avatar image if remote image cannot be resolved

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1804]
Found in https://accounts.stage.mozaws.net/ver.json (commit 83ec3798f4f4330981dcfd0b6bde70f3b727020c)

```json
{
  "version": "0.24.0",
  "commit": "83ec3798f4f4330981dcfd0b6bde70f3b727020c",
  "l10n": "bf5bfdbc4b",
  "tosPp": "69110966d5"
}
```

---

### Steps to reproduce:
1. Currently stage is a bit messed up and points to a https://mozillausercontent.com/ domain and is failing to load profile images.
2. Sign in to https://accounts.stage.mozaws.net/settings/avatar and click the [change] link and upload a new avatar.

### Actual results:
Currently, in the oddly configured stage profile server, I'm getting a broken image and the following error message in mein console:

> _"Failed to load resource: net::ERR_NAME_NOT_RESOLVED"_

Not sure if this is possible, but it'd be nice if we could have a nicer experience than a broken image and possibly display the default avatar or an error message or something if we receive a non 200/304 status code from the profile server for an avatar image.

![account_picture](https://cloud.githubusercontent.com/assets/557895/4795752/0cb9daf8-5dff-11e4-9dcc-2ff463480676.png)
**Figure 1:** 13 console errors, but the first 12 all seem to be CSP "Report Only" errors.

### Expected results:

Error message and more pretty broken image experience (perhaps setting the `<img>` tag's background-image style to the default avatar, or whatever).

**Comment by zaach** [comment]
We can show the default image when the custom image cannot load for whatever reason, though that might leave the user confused about why their uploaded image isn't showing up.
