### ISSUE TITLE
Firefox Accounts web site has a useless horizontal scrollbar, at some window-sizes

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#1805]
![screenshot from 2014-10-24 17-53-14](https://cloud.githubusercontent.com/assets/2365255/4796647/d8967230-5e04-11e4-9e14-6e273c1c7f66.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1089013

STR:
 1. Visit https://accounts.firefox.com/settings and log in.
 2. If there's not already a horizontal scrollbar, try maximizing or resizing your browser-window.

ACTUAL RESULTS: Horizontal scrollbar, with like 10px of scrollability. Nothing visibly overflowing, so no useful reason for it to be there.

EXPECTED RESULTS: No horizontal scrollbar.

This happens because of the <footer id="legal-footer">, which has "width:100%", and whose x-position is offset slightly by the <body>'s default margin. This makes it overflow on the right side by a bit.

The footer needs one of the following to not overflow:
 (1) "left: 0"
 (2) "left:0; right:0;" & drop the width declaration (which means width becomes implied

or:
 (3) we could give the body "margin: 0"

Option (2) is probably the cleanest & most minimal change, I think.

**Comment by rfk** [comment]
I couldn't reproduce this just now, and I feel like we might have refactored it away; @johngruen or @vladikoff do you recall seeing a fix go by for this?

**Comment by vladikoff** [comment]
Ah yes fixed it long time ago, I think. Thanks!
