### ISSUE TITLE
Hello: FxA screen does not go away after signup/password reset

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1810]
STR

1) Have a verified account ready
2) Open Loop
3) Initiate a reset password flow
4) Verify the password reset
5) Now two FxA screens are displayed.

Similar for the signup flow.

**Comment by shane-tomlinson** [comment]
@vladikoff to check the unexpected error does not occur. The window staying open is by design.

**Comment by vladikoff** [comment]
the error was fixed via https://github.com/mozilla/fxa-content-server/pull/1812
