### ISSUE TITLE
Document client metrics

### ISSUE THREAD

**Issue by kparlante** [mozilla/fxa-content-server#1815]
@shane-tomlinson, lets work together on documenting this so that more people can make effective use of the resource!

In particular, information about what shows up in the events under what circumstances: screens, errors, etc.

**Comment by kparlante** [comment]
@shane-tomlinson : do we have a listing of all of the screens, events and errors somewhere? I think getting those documented would be super helpful. This is a key step in getting @ryanfeeley, @vladikoff and others involved in building custom dashboards. @ckarlof

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson : do we have a listing of all of the screens, events and errors somewhere? I think getting those documented would be super helpful. This is a key step in getting @ryanfeeley, @vladikoff and others involved in building custom dashboards. @ckarlof

We do not. I have a feeling this is going to be a major task (1-2 days min), so we'll have to carve out a chunk of time for it.

**Comment by ckarlof** [comment]
We could start with an incremental approach, e.g., document the events as they come up for the use cases for dashboards.

**Comment by shane-tomlinson** [comment]
Closing because this is a long running work in progress.
