### ISSUE TITLE
Don't disable vertical scroll on the FxA popup

### ISSUE THREAD

**Issue by krupa** [mozilla/fxa-content-server#1832]
## steps to reproduce:
1. Load https://marketplace.allizom.org/
2. Click Sign in
3. Notice the FxA popup

## expected behavior:
All the links and info fit into the screen and if they don't we don't disable vertical scroll.

## observed behavior:
'Use a different account' link is not visible.

![screenshot 2014-11-03 13 22 29](https://cloud.githubusercontent.com/assets/557895/4890933/4fb1c0b0-63a3-11e4-990d-78b8fb9febe3.png)
screenshot: https://www.dropbox.com/s/b58e4xney0vkgkv/Screenshot%202014-11-03%2013.22.29.png?dl=0

**Comment by vladikoff** [comment]
Seems fixed!

**Comment by shane-tomlinson** [comment]
Closing as fixed, @krupa, can you confirm?
