### ISSUE TITLE
Remove afterResetPasswordConfirmationPoll from Broker?

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#1838]
Is it true that Broker's don't need to know about password resets? This seems indistinguishable to an `afterLogin` to me (both in the code and in concept).

**Comment by shane-tomlinson** [comment]
I'm closing this, we are using afterREsetPasswordConfirmationPoll in the firstrun broker to notify the firstrun page when the reset password verification has completed.
