### ISSUE TITLE
Support multiple accounts in account chooser

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1844]
See @ryanfeeley's chart for deets: https://www.lucidchart.com/documents/view/94411aff-b7a8-45e6-ba0f-d479da583d3e/1

**Comment by zaach** [comment]
Should we perhaps log metrics on how many accounts users have? Then we can determine if this is worth working on.

**Comment by shane-tomlinson** [comment]
@zaach - what constitutes an account, can one email be used in multiple accounts for different contexts?

**Comment by zaach** [comment]
> what constitutes an account, can one email be used in multiple accounts for different contexts?

I'm not sure what "different contexts" means here.

**Comment by shane-tomlinson** [comment]
> I'm not sure what "different contexts" means here.

sessionContext I should have said.

**Comment by zaach** [comment]
Closing until we actually want to do this.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/pull/4493

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/1882
