### ISSUE TITLE
Get rid of Session.oauth

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1847]
`Session.oauth` is the last significant piece of data that we store in `Session`.

**Comment by vladikoff** [comment]
@shane-tomlinson says this is still used in the verification flow.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3140

**Comment by shane-tomlinson** [comment]
As part of 3140, I am writing verification info to localStorage using the brokers in a slightly more sane manner. It may be a good opportunity to fix this too.

**Comment by vladikoff** [comment]
from mtg: we can just migrate `/lib/session.js` stuff into `storage.js`. We might need to worry about migrating the users. However currently session is only used for `oauth` fields and those do not live for that long. They are just used for verifying the verification a "new tab" of the same browser.

**Comment by vladikoff** [comment]
from mtg: Not going to happen.
