### ISSUE TITLE
Cannot change year pulldown after validation triggered in Safari

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1850]
I was testing Firefox Accounts in Safari. After failing to select a year, the field-pinned message appeared letting me know that year is required. In Safari, I was unable to select a year, the pulldown became disabled.
![safari-problem](https://cloud.githubusercontent.com/assets/68213/4938760/b9f7a602-65cd-11e4-9569-2ade534dbb04.png)

**Comment by zaach** [comment]
Closing until someone trips over this again.
