### ISSUE TITLE
Sync up with upstream browserid-crypto repo?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#1853]
We've just gone through a bit of renaming and reshuffling in the upstream jwcrypto lib to reduce maintenance burden:

  * renamed to "browserid-crypto" so that folks don't think it's useful for generic JWT operations
  * removed cruft that was in support of never-actually-released-to-production data format changes

Is it worth trying to sync up the vendored version in this repo with the upstream version, so that we're all running from the same at-least-sort-of-maintained codebase?  (And possibly revisit #960 in the process?)

**Comment by shane-tomlinson** [comment]
@rfk says close it out.
