### ISSUE TITLE
Add metrics to functional tests for flows

### ISSUE THREAD

**Issue by kparlante** [mozilla/fxa-content-server#1861]
@shane-tomlinson and @ryanfeeley are doing great work documenting the flows and making sure each one has functional tests: https://github.com/mozilla/fxa-content-server/issues/1823,  [Google Document](https://docs.google.com/a/mozilla.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA)

The next step is to add the generated metrics to each test, which would give us a documented, tested record of the expected metrics for each flow.

Along with https://github.com/mozilla/fxa-content-server/issues/1815, we should consider this as supporting the 2015 metrics goals.

**Comment by kparlante** [comment]
@ckarlof, @shane-tomlinson, @ryanfeeley : IMO, functional tests for client metrics are going to be important to make full use of this data by a wider set of people. We'll have greater trust in the data, and the data will be better documented. (This use case -> that metrics output).

@vladikoff and @zaach had some ideas at Thursday's meeting about how to implement it, I believe involving writing metrics output to local storage so that the testing framework could evaluate it.

**Comment by shane-tomlinson** [comment]
two PRs were opened for this, closing. If tests are needed for individual screens/flows, let's open new issues. Thanks @kparlante and @eoger!
