### ISSUE TITLE
logic to choose startup page done in multiple places

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1870]
Place 1: https://github.com/mozilla/fxa-content-server/blob/cd5f023c86bdd91b97124012cbfff8d95cb0f73d/app/scripts/router.js#L156

Place 2: https://github.com/mozilla/fxa-content-server/blob/cd5f023c86bdd91b97124012cbfff8d95cb0f73d/app/scripts/models/auth_brokers/fx-desktop.js#L54

**Comment by shane-tomlinson** [comment]
ref #1837

**Comment by philbooth** [comment]
Die!
