### ISSUE TITLE
base.ephemeralMessages is used for more than ephemeral messages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1873]
It is used for several types of single use data and should be renamed for clarity.

**Comment by shane-tomlinson** [comment]
Closing as z-later, happy to mentor anybody that wants to pick this up.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/commit/dfeb53bf0624298c883710c3184c51aba3de5ad8 @shane-tomlinson correct if wrong

**Comment by shane-tomlinson** [comment]
Yup, thanks for closing this!
