### ISSUE TITLE
Firefox Account management/sign-up allows for insertion of doctored code

### ISSUE THREAD

**Issue by hlieberman** [mozilla/fxa-content-server#1874]
Though the [security model](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol) of the onepw protocol mentions that an active attacker can bypass the entire protocol and learn the password directly, it is an off-handed reference to a severe problem.

The entire Sync process is protected against an active attacker, from PGP signed copies of code that you can validate does what you expect, to the implementation of the Sync protocol in Firefox, such that even an active attacker is only be able to perform an "easy" brute-force (1000-round PBKDF) against kB, aka the sync data.

The page that allows you to login to register and change your password, however, is vulnerable to complete exposure of the password and thus kB due to the implementation of the authentication layer in web content.  These pages should be moved into the about: namespace and distributed with Firefox itself.

**Comment by shane-tomlinson** [comment]
These tradeoffs were both understood and documented before the protocol was implemented. We decided to proceed, with that knowledge in public, so that others could analyze and report additional weaknesses.

Closing as "by design". Thank you for the feedback @hlieberman.
