### ISSUE TITLE
Missing password field on /signin page in convoluted Sync flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1877]
1) Sign in to the sync flow
2) Open the browser's preferences, click "Forget this email" or "disconnect"
3) Click "Sign in"
4) Open another tab to accounts.firefox.com/signin
5) No password field!
6) Click "Sign in".
7) A "Session expired" error.

Expected
In step 5, a password field should be shown.

Found in https://github.com/mozilla/fxa-content-server/pull/1733#issuecomment-62963853, but reproducible on prod.

**Comment by zaach** [comment]
Is someone actually working on this? It's unassigned but is categorized as "in progress".

**Comment by rfk** [comment]
Just noting that I can still reproduce this on latest prod
