### ISSUE TITLE
use "service", "entrypoint" for internal links and support site; "campaign" for social media

### ISSUE THREAD

**Issue by kparlante** [mozilla/fxa-content-server#1898]
While chasing down a different issue, I noticed that some number of users come to the signup page via an error page (500, or unexpected_error), which sets no "service" or "entrypoint" parameters. 

User flows with `service=none` can also happen if a user is directed at /signup via social media, the mozilla support site, or a promotion -- we don't really have a way of distinguishing between the scenarios.

Half-baked ideas:
- pass along an "errorpage" entrypoint from 500 page
- get social media to use "campaign" on links
- get mozilla support to set entrypoint
- do a review of other internal links see if we should set service or entrypoint
- link client metrics sessions from multiple tabs or disparate browser sessions, and possibly other server logging (short term stable identifier -- this came up in conversation w @ckarlof today) 

Perhaps we need to document/set guidelines for how to invoke FxA signup/signin

**Comment by shane-tomlinson** [comment]
This has become the standard. I'm going to close this. See https://www.youtube.com/watch?v=0hiUuL5uTKc
