### ISSUE TITLE
flash of red 'Unexpected error' during tests (particularly during sign_up)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#1901]
I had noticed this visually while running tests, and had mentioned to @ckarlof and @pdehaan.

Sorry for filing such a lame bug, but I'll be flying all day tomorrow, so thought I should get this in as a placeholder.

STR
- just run tests locally so you can see the browser
- something like: node ./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaAuthRoot=https://api-accounts.stage.mozaws.net/ fxaContentRoot=https://accounts.stage.mozaws.net/ fxaEmailRoot=http://restmail.net fxaOauthApp=https://123done-stage.dev.lcip.org/
- or node ./node_modules/.bin/intern-runner config=tests/intern_stage fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaEmailRoot=http://restmail.net fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaProduction=true

Occasionally you will see a red flash of 'Unexpected error'. It seems to perhaps be more common on stage than latest, which is perhaps due to stage being two hostnames not one, or latency (I believe latest is in Oregon, and stage in Virginia). Anyways, that flash is the same one that you will see on a hard network error, so I expect this is about handling of of the status xhr when the account gets set up by the test, or something like that.

**Comment by shane-tomlinson** [comment]
Recap from today's meeting - When the polling function errors, check the request's status. If `status===0`, and `onbeforeunload` has been triggered, ignore the error.
