### ISSUE TITLE
add `bounceEmail` to the User model

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1913]
There's a TODO in `signup`/`confirm` about adding `bounceEmail` to the User model. /cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
Closing since I don't remember the context anymore.

**Comment by pdehaan** [comment]
@shane-tomlinson, did you want to delete those TODOs?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson, did you want to delete those TODOs?

That's right, I self-merged in 81dc9d39734b29f9c6b3149ae222fbf5e09b054c.

**Comment by pdehaan** [comment]
@shane-tomlinson, you sir, are my hero!
