### ISSUE TITLE
Avatar flickers on screen reload

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#1922]
![avatar-flicker](https://cloud.githubusercontent.com/assets/68213/5132305/4d06dcb4-70c9-11e4-9130-586fbb421102.gif)

It looks as though the server is not resizing the avatar image to 240×240 and that the browser is scaling it down.

Shouldn’t we be scaling it down server-side to improve rendering speed and load time?

**Comment by edmoz** [comment]
please retest

**Comment by vladikoff** [comment]
@ryanfeeley ping

**Comment by ryanfeeley** [comment]
Cannot replicate, good stuff!
