### ISSUE TITLE
[ff18] avatars broken in FF18 (was: one failing test for avatars with FF 18.0.2 Linux Ubuntu)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#1930]
This test ' visit gravatar with gravatar set' https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/avatar.js#L88-L122 fails with a timeout. I'm not sure if the use of the 'src*=' selector not being supported in FF18, or other cause.

**Comment by vladikoff** [comment]
@jrgm Hm strange so it works on latest, but not on stage or prod 
![image](https://cloud.githubusercontent.com/assets/128755/5995961/d212e5a6-aa6c-11e4-9063-057e6f8150db.png)
![](http://v14d.com/i/54cf01d3c84b0.jpg)

**Comment by vladikoff** [comment]
Also works on Stable:
![](http://v14d.com/i/54cf04320ae34.jpg)

What could be different? // cc @zaach
