### ISSUE TITLE
Avatar picture is distorted for 1920x1080 camera

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#1931]
@zaach i look even weirder than i usually do.

![screen shot 2014-11-24 at 10 45 29 am](https://cloud.githubusercontent.com/assets/3323249/5167639/92cda966-73c7-11e4-9089-e492a322ff98.png)

**Comment by shane-tomlinson** [comment]
@johngruen, @zaach - is this still a problem?

**Comment by zaach** [comment]
Yes

On Tue, Mar 24, 2015 at 4:38 AM, Shane Tomlinson <notifications@github.com>
wrote:

> @johngruen <https://github.com/johngruen>, @zaach
> <https://github.com/zaach> - is this still a problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/fxa-content-server/issues/1931#issuecomment-85459152>
> .
>



-- 
Zach Carter

**Comment by ryanfeeley** [comment]
@pdehaan I think he has an external web cam, higher quality.

**Comment by zaach** [comment]
@johngruen might have a UX workaround to help users out here.

**Comment by shane-tomlinson** [comment]
@zaach, @johngruen - is the avatar picture still distorted?
