### ISSUE TITLE
Add force_auth with an unverified account functional tests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1933]
The functional test audit (#1823) found we have no functional tests for `/force_auth/ with an unverified account. @ryanfeeley says the user should always be send to the `/confirm` screen.

* [x] Sync
* [x] WebChannel/Loop
* [x] Redirect/123done
* [ ] Iframe/Marketplace

ref #1934

**Comment by shane-tomlinson** [comment]
The iframe test requires a change to 123done to support force_auth in the iframe. Not sure of the best way to approach that.

**Comment by shane-tomlinson** [comment]
Since we plan to deprecate the iframe flow for OAuth reliers, and the firstrun flow will never send users to force_auth, I'm closing this as "as done as we need it to be."

**Comment by vladikoff** [comment]
:+1:
