### ISSUE TITLE
Lots of duplication in the functional tests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1948]
A lot of the tests are duplicated 5 times, once for each broker. One example is "sign in, verified user." Often times the only differences are in the setup, post-window-open and the post-condition checks.

One idea that I have been mulling over is the idea of a test suite template. The test suite template would contain template functions for each of the expected use cases we want to test. Consumers of the template would be responsible for providing the setup/post-window-open and post-condition test functions for each test.

This would allow us to add new use cases to test and ensure all brokers must fill in the appropriate overrides and are tested.

This idea comes out of the Functional Test Audit (#1823)

**Comment by vladikoff** [comment]
We fixed a lot of this with new stuff in helpers.js such as:
* new sign up helper
* new messaging helper
* new open relier helper
