### ISSUE TITLE
Add option to the login flow to clear the email field.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/fxa-content-server#1950]
In the in-app payments flow we are logging out the user at our end which then invokes the web-based login. On that URL it would be useful to us if we can add a parameter that clears the email.

If you pass `email=%20` this clears the field. But that would be a hack. I'd like to be able to pass something like email=false (at the moment passing any string populates the field with that string).

Also interestingly as an aside appending `&email` you get the email populated with `undefined`

**Comment by shane-tomlinson** [comment]
From IRC:
> [13:47:42]  <muffinresearch>	our use-case is that we've logged the user out at our end and we're starting login from scratch. (The user is telling us they don't want to proceed as the the user they're currently logged-in as.) As a result we don't want the email hint from the last user. In other words I think what you're saying is right.

**Comment by shane-tomlinson** [comment]
re-opening, closed due to a bad push to master.
