### ISSUE TITLE
Prompt user to upload avatar after verification?

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1952]
This should increase the adoption of profile images.

**Comment by zaach** [comment]
We need to use able to enable this, but must determine which Firefox train to enable it for (e.g. don't enable experiment for release channel).

**Comment by vladikoff** [comment]
talking to @rfk for Q3 we are gonna try to simply that a bit and only do it after email verification

**Comment by rfk** [comment]
Reason being, you currently can't upload any custom profile data until after you've verified your account, so it's be a big task to implement a pre-verification capture of this info.

**Comment by rfk** [comment]
I don't think this blocks avatars-in-fx41, de-prioritising this for now until it comes back as part of a user story.

**Comment by rfk** [comment]
(please correct me if we do actually need this in for Fx41)

**Comment by shane-tomlinson** [comment]
@billmaggs, @rfk - Should this be in an Aha card?

**Comment by vladikoff** [comment]
I will write up an idea into Aha

**Comment by vladikoff** [comment]
Created https://mozilla.aha.io/ideas/ideas/FXA-I-3
