### ISSUE TITLE
Odd behavior when clicking on links from "Privacy Notice" and "Terms of Service" pages when using framed 123done flow

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#1968]
Found in https://123done-stage.dev.lcip.org/ver.txt (commit f40fc6c)

```
f40fc6c awsbox tweak
```

---

### Steps to reproduce:
1. Go to https://123done-stage.dev.lcip.org/iframe
2. Click on **[Sign Up]** button.
3. Click on the _"Terms of Service"_ link.
4. Scroll down to **"3. Features"** section.
5. Click on the inviting and eye-catching https://find.firefox.com link.

### Actual results:
![123done___do_stuff](https://cloud.githubusercontent.com/assets/557895/5369483/4659b8c8-7fc9-11e4-948a-0115e6372d91.png)
**Figure 1.** iframed find.firefox.com.

### Expected results:
Not sure if we can specify a base href or base target since that content is coming in via Markdown from the legal repo (IIRC). But that may work for iframed flow but be suboptimal for the mobile flows. Internet is hard.

**Comment by shane-tomlinson** [comment]
This is a problem in the firstrun experience as well.

**Comment by shane-tomlinson** [comment]
ref #2225. 

Proposed solution - if in the iframe or iOS, open links from the TOS/PP agreements in new tabs.

**Comment by vladikoff** [comment]
With Google Chrome for iOS they convert links to strings in this format: "See more details via the contact page (http://google.com/....) " where the links are not clickable. 

See ![](http://i.imgur.com/qs6Y6vZ.jpg)

**Comment by vladikoff** [comment]
I propose a solution to serve a special version that has links removed (converted as screenshot above). this way we don't have to worry about losing signups or causing issues with new tabs in iOS

**Comment by pdehaan** [comment]
Do we need a separate version of the TOS/PP, or can we do this all w/ CSS?
http://stackoverflow.com/questions/2091168/disable-a-link-using-css

Plus maybe some fancy ::after + content hacks: http://timkadlec.com/2008/01/display-a-links-href-when-printing/

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @johngruen - another strangeness found. See #2326.

**Comment by shane-tomlinson** [comment]
ref #2225, #2044
