### ISSUE TITLE
Can the forced sizing for the legal text be removed?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#1980]
From a user on the sync-dev mailing list:
> Can the forced sizing for the legal text be removed, at least on
> devices with a large screen? ( #main-content { width: } and
> #legal-copy { height: } )  It's currently needlessly forcing scroll,
> which feels like the site is being sneaky and doesn't actually want me
> to read the text.  That seems to work against the image Mozilla has
> been cultivating as the Good Guys.  The relevant PR -
> https://github.com/mozilla/fxa-content-server/pull/1706 - didn't seem
> to have any explanation as to why it was done, just what.

**Comment by shane-tomlinson** [comment]
+1!

**Comment by vladikoff** [comment]
@johngruen @ryanfeeley thoughts?

**Comment by brampitoyo** [comment]
Feel free to follow #2037, where I’ve proposed a solution in line with comment 1.

**Comment by johngruen** [comment]
Closing as dupe of #2037 and @ckarlof's bitter tears.
