### ISSUE TITLE
IE >= 10 Login spinner takes forever 

### ISSUE THREAD

**Issue by renoirb** [mozilla/fxa-content-server#1984]
We are having an issue [with our version of FxA](https://github.com/webplatform/fxa-content-server/commits/webplatform-customizations) and we are wondering if you experienced a similar issue and if it has been fixed since then. We forked FxA on May 21.

## Reproduce

Under Internet Explorer 10+, on a OAuth signin flow. When the user clicks signin, the "spinner" goes for a long time.

Sometimes it resumes and gets back to the callback. But most of the time it hangs for a long time. In some cases, we can even "wake it up" by clicking somewhere random (e.g. the white background) in the FxA view.

The behavior [can be seen here at precisely 2:34](https://www.youtube.com/watch?v=i6faS2RpPd8&list=PLNw2qw1Nek8BwZ4iJB0Fb9myh-VA2mHav&index=3).

PS: I didn’t, yet, try with the current FxA version. I’m working on it.

## Related
* [Initial email asking about this problem](https://mail.mozilla.org/pipermail/dev-fxacct/2014-December/001248.html)

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/5768111/cbccc46c-9cdb-11e4-98e3-82999403a75c.png)
Was able to login! Seems like it is working on our end.
