### ISSUE TITLE
FxA screen says %(serviceName) instead of "Marketplace" when lang = Bengali

### ISSUE THREAD

**Issue by krupa** [mozilla/fxa-content-server#1985]
## pre-conditions:
1. Set your language on the flame to Bengali.
2.  Test was done on 2.0 (32.0) with the webflow.

## steps to reproduce:
1. Load marketplace-dev app on your flame device
2. Click on the Sign in button.
3. Notice the header on the FxA page

## expected behavior:
The Service Name is always populated correctly (in this case, it would be Marketplace Dev)

## observed behavior:
FxA screen on the browser says %(serviceName) instead of "Marketplace Dev" 

## notes:
reproducible on both the browser and the app.

## screenshot
![fullsizerender 1](https://cloud.githubusercontent.com/assets/301317/5420229/1b8e3748-824b-11e4-82cd-1e431a3117e5.jpg)

**Comment by shane-tomlinson** [comment]
@mathjazz - any word on this?

**Comment by mathjazz** [comment]
@shane-tomlinson No, I didn't get any response, so I just commited the fix as proposed by @zaach:
https://github.com/mozilla/fxa-content-server-l10n/commit/af42c77fdacd550e45ede0c3e861727d87d27bf2

**Comment by ckarlof** [comment]
@zaach, can we close this out?

**Comment by zaach** [comment]
Not yet. Two of the strings still needed to be fixed so I suggested translations on Verbatim. @mathjazz Can you review and merge those, too?

**Comment by mathjazz** [comment]
Strings are fixed on Verbatim and committed to the repo:
https://github.com/mozilla/fxa-content-server-l10n/commit/af42c77fdacd550e45ede0c3e861727d87d27bf2

Are there any other strings that need to be fixed?

**Comment by zaach** [comment]
@mathjazz Thanks! That was the last of them.

**Comment by zaach** [comment]
@mathjazz ah, wait a sec, I misunderstood. There were two *more* strings that I suggested today on Verbatim. These two:
```
187:msgstr "রিকোয়েস্ট বডিতে %(param)???ি প্যারামিটারটি অবৈধ"
490:msgstr "%(email)-এই ঠিকানায় একটি যাচাইকরণ লিঙ্ক পাঠানো হয়েছে"
```

**Comment by mathjazz** [comment]
Oh, sorry.

Now that's committed, too:
https://github.com/mozilla/fxa-content-server-l10n/commit/1d9d16022efef0a6152df45ca2c4a648d4ea633b

**Comment by zaach** [comment]
I checked on my FxOS phone and the string updates are working on [latest](https://123done-latest.dev.lcip.org/) :+1:. This should hit production on Monday.
