### ISSUE TITLE
email rate limiting code in two areas

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#1988]
We have email rate limiting code in both [views/mixins/resend-mixin.js](https://github.com/mozilla/fxa-content-server/blob/423df58cca49296d27a136484de02b48a8d17310/app/scripts/views/mixins/resend-mixin.js) and [lib/fxa-client.js](https://github.com/mozilla/fxa-content-server/blob/423df58cca49296d27a136484de02b48a8d17310/app/scripts/lib/fxa-client.js#L196), both with similar aims - to limit the number of emails a user can send. We should take care of this in one place.

**Comment by shane-tomlinson** [comment]
I'm going to close this until we work on it. I'd be happy to mentor any contributors through this.

**Comment by riadhchtara** [comment]
Hi, are you still interested in mentoring this bug?
I want to create a function that limits the number of emails a user can send. Where should I put it? 
In views/mixins/resend-mixin.js, lib/fxa-client.js or in another file?
Thanx

**Comment by pdehaan** [comment]
@shane-tomlinson to mentor!

**Comment by riadhchtara** [comment]
@pdehaan thanks :-)
@shane-tomlinson : i m interested in working on this after my pull request #2277  is landed

**Comment by eoger** [comment]
@shane-tomlinson Should we merge the email limits constants into one constant?

**Comment by vladikoff** [comment]
ping @shane-tomlinson

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Should we merge the email limits constants into one general EMAIL_RESEND_MAX_TRIES constant?

Sounds good to me!
