### ISSUE TITLE
Confine confirm screen to explicit flows

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#1995]
On current master if you visit the `confirm` screen directly while logged in and verified it will transition to `signup_complete`. If you're unverified it will stay put and if you are not logged in it will transition to `signup`.

@shane-tomlinson mentions in https://github.com/mozilla/fxa-content-server/pull/1987#discussion_r21967723 that we should restrict the `confirm` to users that were explicitly sent there. This occurs after you sign up, sign in while unverified, or visit a `/settings/` page while unverified.

So, decisions to make wrt transitioning from `confirm` in all other cases: 

1. Not signed in -> `signup` (flash error message?)
1. Signed in unverified -> stay on `confirm` ?
1. Signed in verified -> `settings` with a flash message? "You've already confirmed your account."

**Comment by shane-tomlinson** [comment]
@zaach - you took care of this, didn't you? When I visit `/confirm` w/o being signed in, I am redirected to the `/signup` page.

**Comment by shane-tomlinson** [comment]
@zaach - I think you fixed this. Closing. You can re-open if you didn't.
