### ISSUE TITLE
Stuck in the email confirmation state with a wrong email

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2002]
**STR**
- Create an account, do not verify.
- Navigating to https://accounts.firefox.com/settings redirects to /confirm
- Realize that the email has a typo in it. (i.e my email is **not** vlad33@restmail.net, but vlad32@restmail.net)

**Expected**

A way to fix the typo in the email and create a new account.

**Actual**

No way to re-signup and fix the email typo. 

![image](https://cloud.githubusercontent.com/assets/128755/5533432/ef854fb0-8a15-11e4-977a-0581bd6b69da.png)

**Workaround**
- Manually navigate to https://accounts.firefox.com/signup 
- _or_ 
- Clear browser cache and navigate to https://accounts.firefox.com/ 

```
{"version":"0.27.0","commit":"90fac5cf80fb49c1c41f92c8f32f9272ddb94c8a","l10n":"4168ef3cb7","tosPp":"95ae5682b4"}
```

**Comment by ryanfeeley** [comment]
Looking at the iOS client, we wondered why there was not a way to undo a bad email from this screen, but the problem is that the client is not connected to the web in such a way that it can detect discarded account attempts. We really need to do more to connect the two more intelligently. The "Choose what to sync" checkbox also might be a bit strange on iOS (we should put all the sync datatype selections on the web to mitigate this). @ckarlof

**Comment by ckarlof** [comment]
If the email is non-deliverable, then we should detect that we redirect back to the signup page. If the email was deliverable, then I think we may still want a way for the user to "cancel", which could take them back the signup page. Thoughts on a "cancel" link, @ryanfeeley?

**Comment by shane-tomlinson** [comment]
> If the email is non-deliverable, then we should detect that we redirect back to the signup page. 

This is [already the behavior](https://github.com/mozilla/fxa-content-server/blob/467f33a36baba967834205b147d7aa2665db358f/app/scripts/views/confirm.js#L101).

> If the email was deliverable, then I think we may still want a way for the user to "cancel", which could take them back the signup page.

+1. The lack of a "cancel" button I think may have some historical context related to https://github.com/mozilla/persona/issues/2223. I'd love to see it re-introduced.

**Comment by ryanfeeley** [comment]
@ckarlof @shane-tomlinson Can we also clear it from the client (i.e. Firefox Desktop) if they click cancel/undo on the web?

**Comment by shane-tomlinson** [comment]
> Can we also clear it from the client (i.e. Firefox Desktop) if they click cancel/undo on the web?

Can you walk me through how the two are related? If a user has already signing up for a Firefox Account in Sync, signing up for another account from a web property seems like a separate event. If the user realizes they entered the wrong email address when signing in from the web property, hits cancel, that doesn't seem like it should affect Sync.

**Comment by ryanfeeley** [comment]
A sync user would also see the screenshot @vladikoff posted above. Once they reach that point their browser is in unverified state with the original email that was entered, no?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I don't feel very intelligent tonight. Can you be more explicit? What is the sync/web flow that causes the problem, and what is the desired outcome?

**Comment by ryanfeeley** [comment]
To sleep on: User go to Firefox. User click Sign in to Sync. User go to sign up form and put in wrong email. User gets to Confirm your account screen and sees wrong email. If user had option to start over, would Firefox preferences panel show the corrected email? When is Firefox seeded with the email of the account?
![shane-at-ryanfeeley-com](https://cloud.githubusercontent.com/assets/68213/6493414/8a1ac6f4-c288-11e4-875c-4b14f4481b73.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - very helpful, thank you!

**Comment by ryanfeeley** [comment]
A screenshot is word a thousand words. A retina screenshot, four thousand.

**Comment by shane-tomlinson** [comment]
Copying over @ryanfeeley's description from #2652 

-------------------------

So that I can avoid a world of manual undo pain, as a registering Sync user, I want to be able to go back on the **Confirm your account** screen which will clear the email address seeded into my Firefox desktop client.
![email-undo](https://cloud.githubusercontent.com/assets/68213/8460542/737e2850-1ff3-11e5-9d8b-85edc4f5fa42.png)

**Comment by vladikoff** [comment]
I guess we need 2 code paths to fix this:
1. for normal oauth / browser flows
2. for desktop, desktop should signal back to Firefox UI

**Comment by vladikoff** [comment]
Last design we got from @ryanfeeley ![](https://cloud.githubusercontent.com/assets/68213/8853183/86fdb842-3127-11e5-992b-1a0102839731.png)

A few issues: 

1. Different account might be confusing, because the user probably mistyped an email .

2. Firefox sync needs to be able to revert the email in the UI.

**Comment by ryanfeeley** [comment]
If we can do this right, and really delete unverified account on the web and the browser, here is some  copy variations for links:
* Undo
* Wrong email?
* Mistyped email?
* Start over

Clicking any of them would take the user back to the registration form, and delete the unverified accounts on the web and the browser. We should show a temporary success message that says "{Email} deleted succcessfully"

Any favourites?

**Comment by vladikoff** [comment]
Need to keep sync in mind, also add metrics

**Comment by ckarlof** [comment]
Ryan and I reviewed it, and based on a combination of native UI controls in the browser (e.g., sync prefs to remove account, etc) + using the back button for web based reliers, we think it's worth de-prioritizing this for now.

**Comment by ryanfeeley** [comment]
@ckarlof I still think that adding a "Forget this email" link is worth doing (although it would not say that, perhaps best "Wrong email? Start over.") New bug on issue just came in: https://bugzilla.mozilla.org/show_bug.cgi?id=1179327

**Comment by ckarlof** [comment]
I gave this a whirl and at first blush it seems we might have a regression. I signed up with an invalid email and it seems that the account was auto-deleted, but 

>    If the email is non-deliverable, then we should detect that we redirect back to the signup page.
>   This is already the behavior.

The above didn't happen. Also when I refreshed the confirm page, I got a terrible "Account is connected" page from about:accounts. There are probably enough paper cuts in this flow to warrant looking at it again.

**Comment by ckarlof** [comment]
> New bug on issue just came in: https://bugzilla.mozilla.org/show_bug.cgi?id=1179327

That was reported on FxOS, which IIUC, uses a native implementation.

**Comment by ckarlof** [comment]
Here's a quick UX audit.

I signed up with `oihofihoushdfu333huhsd@gmail.com`. The email bounced, but our confirmation page didn't detect it (https://github.com/mozilla/fxa-content-server/issues/2002#issuecomment-77129538 suggests that we should be detecting that it bounced). 

<img width="574" alt="screenshot 2015-11-17 11 48 10" src="https://cloud.githubusercontent.com/assets/2365255/11222818/8d87a316-8d21-11e5-963d-33e914e7b42f.png">

If I click resend, then it does detect that it bounced and redirects me back to signup but with no message:

<img width="500" alt="screenshot 2015-11-17 11 48 35" src="https://cloud.githubusercontent.com/assets/2365255/11222830/9f452cc2-8d21-11e5-874d-52b817de16cd.png">

I'm still connected to the browser though, which is not great:

<img width="909" alt="screenshot 2015-11-17 11 48 49" src="https://cloud.githubusercontent.com/assets/2365255/11222842/a98dde68-8d21-11e5-92ca-a96470439459.png">

And if I refresh the about:accounts page, I also get something not great:

<img width="533" alt="screenshot 2015-11-17 11 49 05" src="https://cloud.githubusercontent.com/assets/2365255/11222925/0b30d7b0-8d22-11e5-83c5-7a64857e5c27.png">

I think a cancel button here would be great, but there are other gaps worth addressing as well.

**Comment by rfk** [comment]
> The email bounced, but our confirmation page didn't detect it
> (#2002 (comment) suggests that we should be detecting that it bounced).

I just tried this out as well.  It detects the bounce when I try to signup via the web, but *not* when I signup via the sync about:accounts flow.  Perhaps the about:accounts flow disables fxa-content-server from polling the account status and thus detecting the change to bounced status?

**Comment by rfk** [comment]
> I'm still connected to the browser though, which is not great:

I think this reflects an unhandled error in the browser code.  Trying it out, the browser logs tell met that it gets a 401 on the `/recovery_email/status` endpoint, which is expected when the bounced account gets deleted:
```
INFO: 1447982028005	FirefoxAccounts	DEBUG	entering pollEmailStatus: timer
INFO: 1447982028005	FirefoxAccounts	DEBUG	entering pollEmailStatus: timer
INFO: 1447982028005	FirefoxAccounts	DEBUG	entering pollEmailStatus: timer
INFO: 1447982028243	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028243	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028243	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -243
INFO: 1447982028243	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -243
INFO: 1447982028243	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028243	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -243
INFO: 1447982028244	Hawk	DEBUG	Received 401 for /recovery_email/status: retrying
INFO: 1447982028244	Hawk	DEBUG	Received 401 for /recovery_email/status: retrying
INFO: 1447982028244	Hawk	DEBUG	Received 401 for /recovery_email/status: retrying
INFO: 1447982028490	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028490	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028490	Hawk	DEBUG	(Response) /recovery_email/status: code: 401 - Status text: Unauthorized
INFO: 1447982028490	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -490
INFO: 1447982028490	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -490
INFO: 1447982028490	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -490
INFO: 1447982028491	FirefoxAccounts	ERROR	error GETing /recovery_email/status: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
INFO: 1447982028491	FirefoxAccounts	ERROR	error GETing /recovery_email/status: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
INFO: 1447982028491	FirefoxAccounts	ERROR	error GETing /recovery_email/status: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
```

But this doesn't trigger the browser to enter its "you need to re-auth" state.

**Comment by rfk** [comment]
I filed the browser-side bug as https://bugzilla.mozilla.org/show_bug.cgi?id=1226449

**Comment by shane-tomlinson** [comment]
> I just tried this out as well. It detects the bounce when I try to signup via the web, but not when I signup via the sync about:accounts flow. Perhaps the about:accounts flow disables fxa-content-server from polling the account status and thus detecting the change to bounced status?

You are 100% correct, we do *not* poll on the client when embedded [from about:accounts](https://github.com/mozilla/fxa-content-server/blob/0c6b0a609d202564b07787f9961cff24e07c1543/app/scripts/models/auth_brokers/fx-desktop-v1.js#L41-L44). We disable polling because the browser is doing its own poll. Duplicate polling caused double the auth-server load.

**Comment by shane-tomlinson** [comment]
Ref #2038

**Comment by vladikoff** [comment]
From #3358:

> For the first time in a while, in Chrome, I went to accounts.firefox.com. Because the last time I used it was to create an account (that I don't think I ever verified) I was redirected to the **Confirm your account** screen.
<img width="493" alt="confirm-your-account" src="https://cloud.githubusercontent.com/assets/68213/12125412/2c79d846-b3b9-11e5-97b7-61cb60ea9a84.png">
There was no way to escape this screen, so I think that we should add a **Use a different account** link above **Resend email** which would take users to a fresh login screen.

**Comment by shane-tomlinson** [comment]
Check out [this note](https://github.com/mozilla/fxa-content-server/blob/efea825/app/scripts/views/confirm.js#L52:L56):

> Back button is only available for signin for now. We haven't fully
> figured out whether re-signing up a user and sending a new
> email/sessionToken to the browser will cause problems. I don't think
> it will since that's what happens on a bounced email, but that's
> a discussion for another time.

**Comment by shane-tomlinson** [comment]
@rfk - are we ever going to work on this?

**Comment by rfk** [comment]
If it's as simple as removing the `isSignIn` mentioned in the note above, perhaps we should just do it and be done with it?  I don't have any theories about how this might break things from the browser's PoV.

**Comment by vladikoff** [comment]
from mtg: try sending log out message to the browser when clicking back.

**Comment by vladikoff** [comment]
Seems like no one ever reports this as a problem , closing for now
