### ISSUE TITLE
When FxA login page loads for Fx Sync, I see lots of flashing. 

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2016]
It seems like a bunch of things that should be hidden (some error or informational messages) are shown, and then hidden after page load.

**Comment by shane-tomlinson** [comment]
Screen capture from licecap.

Notice the "Must be at least 8 characters" text is displayed and the TOS/PP copy increases in size.
![zoom-in-text](https://cloud.githubusercontent.com/assets/848085/5629248/3cd9c02c-95a9-11e4-825b-1403f473e300.gif)

**Comment by shane-tomlinson** [comment]
This was fixed by @vladikoff in 740006de, closing.
