### ISSUE TITLE
Allow users to change their "display name" from Settings

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2023]
This will require UX input.

Depends on https://github.com/mozilla/fxa-profile-server/issues/84.

**Comment by vladikoff** [comment]
Closing until further notice for display name integration. Currently we are not working on it

**Comment by zaach** [comment]
Oh hey! I'm working on this. :)

**Comment by zaach** [comment]
This is subsumed by #2336. Closing.
