### ISSUE TITLE
views should rely on the Relier model to fetch relier data, not the URL search params

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2026]
Now that we have the ever so awesome [Relier models](https://github.com/mozilla/fxa-content-server/tree/master/app/scripts/models/reliers), we should fetch data from those instead of from the query parameters. Fetching data from both places could lead to [cache coherency problems](http://cmsc411.com/multiprocessors/cache-coherence-problem) if the relier is updated but the query parameter is not.

> ➜  views git:(master) rgrep "searchParam" .
./base.js:      this.automatedBrowser = !!this.searchParam('automatedBrowser');
./base.js:    searchParam: function (itemName) {
./base.js:      return Url.searchParam(itemName, this.window.location.search);
./base.js:      this[itemName] = this.searchParam(itemName);
./reset_password.js:      return this.searchParam('email') || Session.prefillEmail || '';
./settings.js:      var uid = self.searchParam('uid');
./sign_in.js:      this.prefillEmail = Session.prefillEmail || this.searchParam('email');
./sign_up.js:      var email = Session.prefillEmail || this.searchParam('email');
➜  views git:(master)

Email verification data is imported as well, though this does not make sense to put on the relier:
> ➜  views git:(master) ✗ rgrep "importSearch" .
./base.js:    importSearchParam: function (itemName) {
./complete_reset_password.js:        this.importSearchParam('token');
./complete_reset_password.js:        this.importSearchParam('code');
./complete_reset_password.js:        this.importSearchParam('email');
./complete_sign_up.js:        this.importSearchParam('uid');
./complete_sign_up.js:        this.importSearchParam('code');

**Comment by shane-tomlinson** [comment]
@zaach - the only non-email `searchParam` is `uid` - could that come from the `Account` model?

**Comment by zaach** [comment]
@shane-tomlinson I'm not sure I understand how that API is supposed to look. I'd imagine an `account` attribute could be set on the relier after importing the `uid` query param. The relier would dig the associated `Account` out of `User`'s cache.

**Comment by shane-tomlinson** [comment]
@zaach - I was thinking the relier would fetch the `uid` from the URL [here](https://github.com/mozilla/fxa-content-server/blob/f5fa83ee7787851637fb7e375e341819ef4476dc/app/scripts/models/reliers/relier.js#L51), then the account would be created with the `uid` from the relier [here](https://github.com/mozilla/fxa-content-server/blob/f5fa83ee7787851637fb7e375e341819ef4476dc/app/scripts/views/settings.js#L27).

**Comment by zaach** [comment]
@shane-tomlinson Gotcha-- that's what I was thinking, too. Would it make sense to have the relier go ahead and initialize the account after importing the param? It abstracts more logic from the view, which probably shouldn't be concerned with how the relier chooses the account.
