### ISSUE TITLE
Question: does a `p.reject()` without a return do anything?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2031]
@vladikoff and @zaach - I was spelunking in [views/sign_in.js](https://github.com/mozilla/fxa-content-server/blob/8beec51167e75651afa2763c860039f99411aec5/app/scripts/views/sign_in.js) and came across these two `p.reject()` statements introduced in 7780e49aa007db60d12e29ea791d60489298ad3a:

1. https://github.com/mozilla/fxa-content-server/blob/8beec51167e75651afa2763c860039f99411aec5/app/scripts/views/sign_in.js#L106
1. https://github.com/mozilla/fxa-content-server/blob/8beec51167e75651afa2763c860039f99411aec5/app/scripts/views/sign_in.js#L129

Without a `return` statement in front of them, do they do anything?

When I add a `return`, the tests start to fail because there is no error message to display.

**Comment by zaach** [comment]
It doesn't do anything without a return... They should reject with an actual error.

**Comment by pdehaan** [comment]
FWIW, looks like the only 2 references:

```sh
$ grep -irn "\.reject()" . --exclude-dir={node_modules,bower_components,dist,.tmp}

./app/scripts/views/sign_in.js:106:        p.reject();
./app/scripts/views/sign_in.js:129:          p.reject();
```
