### ISSUE TITLE
test broken on latest - polls forever for a second email that is never sent

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2033]
See http://tests.dev.lcip.org:8111/viewLog.html?buildId=627&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_state=18&focus=909 and others. 

This appears to have been introduced here:

https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/oauth_sign_in.js#L154-L159

with the code for GH-1982

**Comment by zaach** [comment]
The second email is never sent. The request is sent to the auth-server endpoint (`v1/recovery_email/resend_code`) but the auth-server suppresses the email for whatever reason. Rate limitting?

**Comment by zaach** [comment]
Filed https://github.com/mozilla/fxa-customs-server/issues/72

**Comment by ckarlof** [comment]
You might be able to learn something from the fxa-dev server logs while it's running. Did this send any other emails before getting limited? It looks like it's currently set to 3 (https://github.com/mozilla/fxa-dev/blob/master/roles/customs/templates/config.json.j2#L7).

**Comment by jrgm** [comment]
Yeah, so isn't this resendBlackoutPeriod in https://github.com/mozilla/fxa-auth-server/pull/654?
https://github.com/mozilla/fxa-auth-server/blob/master/routes/account.js#L434-L440 prevents sending for an initial 10 minutes.

**Comment by zaach** [comment]
@jrgm Bingo– confirmed this locally.
