### ISSUE TITLE
Age dropdown state does not handle sign up -> sign in -> sign up loop correctly

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2035]
STR:

* Navigate to `about:accounts`
* Select magic year, currently "2002"
* Observe transition to month/day boxes
* Tap *Already have an account? Sign in.*
* Tap *Create account*
* Observe month/day boxes are gone and year reads "2002"

I can't say whether the year check then fails, i.e., we then assume the user is born on Dec 31, 2002 and is therefore too young.

**Comment by shane-tomlinson** [comment]
I'm going to close this *for now* because we have a new coppa flow in the works. We can re-open if we decide we are going to stick with the current flow.
