### ISSUE TITLE
ToS and PN experience is not great

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2037]
It was not really awesome when I went to look at our ToS and PN. I had a full screen window and all I had was a 3 inch viewport to scroll through. I realize it's probably always been like this, but it made me sad. What can we do to improve it @johngruen?

![screen shot 2015-01-12 at 5 44 05 pm](https://cloud.githubusercontent.com/assets/2365255/5714829/e853dc02-9a82-11e4-9934-062f86c6c96c.png)

**Comment by vladikoff** [comment]
Also see https://github.com/mozilla/fxa-content-server/issues/1980

**Comment by brampitoyo** [comment]
What’s your thought on opening up these link in a new window/tab? It’ll allow us to widen the ToS and PN paragraphs so they’re more readable.

Even if we open these links in the same window, we could probably make #main-content’s width relative, and #legal-copy’s height a large part of the screen (reserving the top/bottom part for the Back button).

**Comment by shane-tomlinson** [comment]
We used to have the TOS/PP agreements show the full text and let the browser handle scrolling, I forget why we changed it.

**Comment by johngruen** [comment]
@ckarlof @brampitoyo @shane-tomlinson: As shane mentions, there was a rationale here, but i'm also not totally recalling. I think it might have been that presenting the full ToS/PN looked insanely long when presented in a continuous narrow box.

 @brampitoyo using a second window isn't viable here becasue some clients that use FxA don't have tab/window management options. Self-assigning, I'll put together a PR later this week, there's no reason we can't just make the page wider where possible.
