### ISSUE TITLE
Unactionable error messages are displayed to the user.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2046]
Comments start with @ckarlof in https://github.com/mozilla/fxa-content-server/pull/2019#discussion_r22622235 when reviewing [this line](https://github.com/mozilla/fxa-content-server/pull/2019#discussion-diff-22622235R191):

> This seems a little weird to me. We should figure out a strategy for user vs dev error messages. This is really an dev message, but there's nothing an end user can do about it. 

@zaach suggests:
> How about: always message "Unexpected error" to the user for dev errors, then log the actual details to console and metrics.

@shane-tomlinson (me) follows on with:
> I had to dig deep to think about the original intent of this message. If the relier did things correctly, a user should not see this message. This message is aimed at RP developers who are integrating with FxA. The message's intent is to signal "hey, you forgot something."

> In #1982, we check for required OAuth parameters on startup and redirect to /400.html if a parameter is missing. The name of the missing parameter is displayed to the user. We could do the same here. See #1740 and #1972 for more background.

> Or, perhaps we could do something like display "Unexpected error" which would be aimed at users, and also a "See more..." link that opens an expanded information element that displays RP developer facing information.

> A third alternative is to use the developer console. Right now our console is pretty noisy, if reduce the amount of noise we could give RP devs information they can use.

> I want to give RP developers useful information when they forget something.

@zaach responds:
> I'd favor a mix of two and three: Show "Unexpected error" then perhaps a hint to developers to check the console for more info.

>> A third alternative is to use the developer console. Right now our console is pretty noisy, if reduce the amount of noise we could give RP devs information they can use.

> Any details on the noise you're seeing? I filed #2036, which was the only noise I noticed while causally perusing the site.

**Comment by ckarlof** [comment]
Yep, 107 errno is one of them too.

**Comment by vladikoff** [comment]
We improved a lot of our error strings and messages since then. Let's file new issues if we need to fix more of those.
