### ISSUE TITLE
From Bugzilla: Bug 1005085 - In about:accounts, can't tab navigate to the "Manage" button.

### ISSUE THREAD

**Issue by karlht** [mozilla/fxa-content-server#2049]
https://bugzilla.mozilla.org/show_bug.cgi?id=1005085 has details -- it's blocking https://bugzilla.mozilla.org/show_bug.cgi?id=996243, which is the accessibility review for FxA.

I'm pretty sure the relevant line is https://github.com/mozilla/fxa-content-server/blob/master/app/sync/manage.html#L32 -- it just needs a tabindex="0" added to it.

I can submit a PR for review if you like, but it might be easier for one of the established developers to do it.

**Comment by ckarlof** [comment]
A copy of manage.html happens to live in our content server repo, but the file in mozilla-central is the one that actually needs to be patched: http://mxr.mozilla.org/mozilla-central/source/browser/base/content/aboutaccounts/aboutaccounts.xhtml
