### ISSUE TITLE
500 page is not allowed to be framed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2050]
@ferjm uncovered a bug today when trying to use the iframe flow:

> Load denied by X-Frame-Options: https://stable.dev.lcip.org/500.html does not permit framing.

We should allow the 500 page to be framed so we can display catastrophic errors to the user.

**Comment by vladikoff** [comment]
@shane-tomlinson https://github.com/mozilla/fxa-content-server/commit/b25faa2c2ff1e99c1628b0ba210fd0914639fd52

**Comment by vladikoff** [comment]
Fixed already in latest train http://jsfiddle.net/hrjs8ayd/

**Comment by pdehaan** [comment]
What about the 404 page? I tweaked the URLs in @vladikoff's JSFiddle but neither env showed a framed 404.

**Comment by vladikoff** [comment]
@pdehaan I'm not sure. ping @shane-tomlinson

**Comment by shane-tomlinson** [comment]
@pdehaan, @vladikoff - excellent catch, opened #2056 for:

* 404
* 502
* 503
