### ISSUE TITLE
Less jargon-y error message for errno 107 from the auth server

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2052]
I don't know why this happened (https://github.com/mozilla/fxa-auth-server/issues/859), but "Unexpected error" is probably good enough.

![invalid](https://cloud.githubusercontent.com/assets/2365255/5849146/0e454f12-a196-11e4-9c5f-4cac087653e1.png)

**Comment by ckarlof** [comment]
This is also a good opportunity to revisit how we message other oddball errors from the Auth API.

**Comment by shane-tomlinson** [comment]
Very very similar to #2046.

**Comment by ckarlof** [comment]
Closing in favor of #2046.
