### ISSUE TITLE
Unclear alignment on secondary sign-in links

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2055]
For an authenticated user, the links at the bottom of the sign-in page have no apparent alignment:
![bill](https://cloud.githubusercontent.com/assets/68213/5866257/a03d7ee0-a25d-11e4-9adc-132a55ceb494.png)

**Comment by johngruen** [comment]
@ryanfeeley it's stupid that this is still just sitting there like a lump. low hanging fruit. will fix monday.
