### ISSUE TITLE
XHR requests that respond w/ 404 show error message w/ full HTML of 404 page.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2059]
Link to https://github.com/mozilla/fxa-js-client/issues/142
## STR
1. Check out master and apply the diff from below
2. Open `http://127.0.0.1:3030/signin`
3. Try to sign in.
### diff to apply

``` diff
diff --git a/app/scripts/lib/config-loader.js b/app/scripts/lib/config-loader.js
index 3e83494..b92cd39 100644
--- a/app/scripts/lib/config-loader.js
+++ b/app/scripts/lib/config-loader.js
@@ -59,6 +59,7 @@ function (
       return xhr.getJSON('/config')
           .then(function (config) {
             self._config = config;
+            config.authServerUrl = "undefined";
             return config;
           });
     },
```
### result

![screen shot 2015-01-23 at 11 24 04](https://cloud.githubusercontent.com/assets/848085/5873825/839c93e4-a2f2-11e4-96b6-3d6334a224a2.png)

**Comment by vladikoff** [comment]
This was fixed since we moved away from XHRing the /config
