### ISSUE TITLE
If startup is slow, we show a blank page

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2060]
Found while exploring https://github.com/mozilla/fxa-js-client/issues/142

If the request to `/config` takes a while, a largely blank screen is shown to the user. A spinner or `loading` message would be nice.

## STR
1. apply the patch from below
1. load up http://127.0.0.1:3030/signin

## diff to apply 
```diff 
diff --git a/server/lib/routes/get-config.js b/server/lib/routes/get-config.js
index 41354f1..205212b 100644
--- a/server/lib/routes/get-config.js
+++ b/server/lib/routes/get-config.js
@@ -48,6 +48,7 @@ module.exports = function (i18n) {
   route.path = '/config';
 
   route.process = function (req, res) {
+    return;
     // `language` and `cookiesEnabled` are dynamic so don't cache.
     res.header('Cache-Control', 'no-cache, max-age=0');
```

## Result
![screen shot 2015-01-23 at 11 44 57](https://cloud.githubusercontent.com/assets/848085/5874122/d2c3e212-a2f5-11e4-9769-266e27014f9f.png)

**Comment by mathstuf** [comment]
I'm seeing this as well. However, the server is on a LAN and `/config` returns almost instantly, so that isn't the only thing that causes this. I see no error messages in the nginx logs or in the output of the servers.

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by shane-tomlinson** [comment]
Closing as dup of #2980
