### ISSUE TITLE
404s on /apple-touch-icon-*.png

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2062]
Looking through the Kibana logs, I noticed that we have a few 404s for some apple icons:

- "GET /apple-touch-icon-120x120-precomposed.png HTTP/1.1"
- "GET /apple-touch-icon-120x120.png HTTP/1.1",
- "GET /apple-touch-icon.png HTTP/1.1",
- "GET /apple-touch-icon-precomposed.png HTTP/1.1",

Not sure if these are worth addressing, but I hates me some 404s as it clouds up our logs and makes it difficult to pull out legit 404s...

After a bit of Googling, I found these interesting links:
- https://mathiasbynens.be/notes/touch-icons
- https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

/cc @johngruen @ryanfeeley

**Comment by vladikoff** [comment]
ping @ryanfeeley @johngruen

**Comment by vladikoff** [comment]
Will ask @ryanfeeley today if it is okay to use the logo as those icons

**Comment by pdehaan** [comment]
Related: #2281; _"Add various favicons for the FxA website"_

**Comment by ryanfeeley** [comment]
For posterity, a handy guide:
https://github.com/audreyr/favicon-cheat-sheet

Generate our icons from this large PNG:
https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/
