### ISSUE TITLE
Reset password expires too fast

### ISSUE THREAD

**Issue by cedk** [mozilla/fxa-content-server#2063]
When your email server uses grey listing method, the reset email can too some time to arrive.
This is even more annoying as the outgoing server is always different.
This makes the link to confirm the reset having a expired token.

**Comment by jrgm** [comment]
Thanks! This is actually covered in https://github.com/mozilla/fxa-auth-server/issues/845.

**Comment by jrgm** [comment]
Closing in favour of https://github.com/mozilla/fxa-auth-server/issues/845
