### ISSUE TITLE
Send "painted", "loaded", or "ready" message after XHR resources have been loaded

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2066]
Firefox for iOS wants to load `fxa-content-server` in a background webview and display when the page is painted.  Right now, the normal DOM "loaded" event is not appropriate because additional XHR responses may not have completed, leading to a pop of text and restyling.  This issue tracks sending a custom "FirefoxAccountsCommand" when background XHR requests impacting render have completed.

**Comment by ckarlof** [comment]
@shane-tomlinson, some of these would probably be useful for the iframe flow, too.

**Comment by ckarlof** [comment]
Having these will also give @ncalexan a better way of measuring the user visible load times.

**Comment by ncalexan** [comment]
Verified against https://latest.dev.lcip.org/signin?service=sync&context=fx_desktop_v1.  Thanks, team!

**Comment by shane-tomlinson** [comment]
> Verified against https://latest.dev.lcip.org/signin?service=sync&context=fx_desktop_v1. Thanks, team!

:+1: You're welcome!
