### ISSUE TITLE
Reset Firefox feature is a potential footgun for single device Sync users to lose their Sync data

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2068]
From @gerv in the dev-fxaccount list:

> Scenario:
>
> * User find Firefox is slow
> * User does "Reset Firefox"
> * User finds that they can't remember their Sync password, because the
  login time is so long and they haven't used it in months
> * User resets Sync password
> * User wonders where on earth all their data is
> * User's data is all now erased from both places where there were
  copies of it

> This very nearly just happened to me. The only think which prevented me
was some small print on the reset password page that I nearly didn't
read, precisely because resetting one's password works the same
_everywhere_, and that making it work the same as everywhere else is
(supposedly) why we abandoned the old form of sync for the new one.

> What else can be done to make this massive dataloss scenario less likely?

> Could we, for example, not clear Sync info when we Reset Firefox?

> Or could we put warnings next to the Reset option which say "Make sure
you know your Sync password before you do this", or even make people who
are using Sync type their password before Reset happens?

> Gerv

**Comment by gerv** [comment]
Are we sure Sync is the place to fix this, rather than Reset Firefox? I posted to the list to generate a discussion...

**Comment by ckarlof** [comment]
> Are we sure Sync is the place to fix this, rather than Reset Firefox?

If you want it to be actionable, I'd file something in Bugzilla against Reset Firefox.

**Comment by gerv** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1129485 filed. But don't let that stop you taking action on the FxA end.

**Comment by shane-tomlinson** [comment]
@gerv, according to https://bugzilla.mozilla.org/show_bug.cgi?id=972196#c11, this bug was fixed on the Firefox end as of Fx36b1.

Closing as fixed. Thanks for filing!
