### ISSUE TITLE
400.html 'Bad Request' responses do not render message detail value

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2070]
STR

1. Load https://accounts.stage.mozaws.net/oauth/signup?scope=profile 
2. The client will subsequently request https://accounts.stage.mozaws.net/400.html?message=Missing%20OAuth%20parameter%3A%20client_id&errno=1005&namespace=oauth&param=client_id

Expected: some additional detail rendered in page, e.g., "Missing OAuth parameter: client_id"
Actual: only the header 'Bad Request' is shown.

**Comment by shane-tomlinson** [comment]
nginx may be serving the static 400 page directly, which would not display the error.

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by shane-tomlinson** [comment]
nginx does not serve 400 pages, the content server does. The real problem is the handlebars tag that prints the error message is stripped in dist:

### dev

```html
<div id="main-content" class="card">
  <header>
    <h1 id="fxa-400-header">{{#t}}Bad Request{{/t}}</h1>
  </header>

  <section>
     {{#if message}}
      <div class="error visible">{{message}}</div>
    {{/if}}
  </section>
</div>
```

#### prod
```html
<div id="main-content" class="card">
  <header>
    <h1 id="fxa-400-header">Bad Request</h1>
  </header>

  <section>
  </section>
</div>
```
