### ISSUE TITLE
`this.timeout =` in a `beforeEach` has no effect.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2078]
Found while trying to debug why [this test](https://travis-ci.org/mozilla/fxa-content-server/builds/48746975) was failing when run remotely.

## STR
1. Add the following line to `node_modules/intern-geezer/lib/Test.js`, line 171
1. `        console.log('self.timeout: %s', self.timeout);`
1. Run the reset_password functional tests.

## Expected
1. each test should say `self.timeout: 90000`

## Actual
1. each test says `self.timeout: 30000`

**Comment by vladikoff** [comment]
Waiting for a new Intern release to fix this one up

**Comment by shane-tomlinson** [comment]
Closing because this is going to be fixed by intern.
