### ISSUE TITLE
log whether `customizeSync` is forced

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2079]
Follow on from #2065:

In a4a26f9189ca1776f1b0f8087b42eba9a3ef3eef, we added the ability for Firefox Desktop to force `customizeSync` to be checked on signup. @kparlante asks that we log that.

**Comment by vladikoff** [comment]
@shane-tomlinson Once CWTS is in FF Desktop then all clients will be forcing customizeSync.

We should remove the `customizeSync` param once all CWTS lands, unless it is somehow will still be used.

**Comment by shane-tomlinson** [comment]
> We should remove the customizeSync param once all CWTS lands, unless it is somehow will still be used.

There will be some legacy browsers hanging around for a while, though after a sufficient grace period it shouldn't be a problem to say "meh". Removing support doesn't break anything, it just forces users to click the checkbox if they actually want to customize their sync prefs.

**Comment by shane-tomlinson** [comment]
with fx_desktop_v2, customizeSync doesn't make any sense. Closing.
