### ISSUE TITLE
log screen size/whether the user is on a mobile device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2080]
@ryanfeeley asks:

> we would also like to know the difference between (responsive) mobile and desktop view because we're more likely to recommend showing passwords on mobile by default (where you can hide your screen more easily, and where every key you press is shown over the keyboard anyway) than desktop.

**Comment by kparlante** [comment]
@shane-tomlinson, @ryanfeeley : do you want to distinguish responsive-mobile and desktop by user agent, or are you also considering screen size (or other factors)?

**Comment by ryanfeeley** [comment]
I suppose a combination may be required to really know if it's being viewed on a smartphone instead of a table or laptop. If we were to start showing passwords by default, I would start with smartphones first if the data supported it.

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @kparlante - Screen size has been logged since 0f5f35135098b0502a9276549d4d74160a28279a - see #1373. These currently show in the metrics as:
```
screen: { 
  width: <xxx>, 
  height: <yyy> 
}
```

I can add devicePixelRatio and the clientWidth/clientHeight if those will help.

**Comment by shane-tomlinson** [comment]
Fixed by #2103
