### ISSUE TITLE
[ff18] Avatar Camera capture does not work

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2085]
@zaach should we hide the "Camera" button in browsers that do not support `getUserMedia`?

![image](https://cloud.githubusercontent.com/assets/128755/6007595/6cdbf196-aae9-11e4-8f4f-53c50700f4f0.png)

**Comment by shane-tomlinson** [comment]
Ref #2224

**Comment by shane-tomlinson** [comment]
In Fx18, navigator.mozGetUserMedia is supported, with some caveats [1].

* `media.navigator.enabled` needs to be set to `true` in about:config
* `navigator.mozGetUserMedia` is still available if `media.navigator.enabled` is set to `false`.
* `stream.stop()` is not a function. There is a `video.pause`, though that does not disable the camera.

[1] - http://mozillamediagoddess.org/2012/07/13/navigator-mozgetusermedia-has-just-landed-in-firefox-desktop-nightly-builds/

**Comment by vladikoff** [comment]
@zaach should we fix this in Train 42? basically only allow camera if `getUserMedia` is available

**Comment by zaach** [comment]
We added an environment check for `getUserMedia` in https://github.com/mozilla/fxa-content-server/commit/0a0405bd6f0bd4f74cb9cd0bc4634ddbeb041832 but it sounds like ff18 needs special consideration since it exposes `navigator.mozGetUserMedia` even when it doesn't work.

**Comment by vladikoff** [comment]
@zaach Oh great, forgot about that, that makes this not that urgent. Thanks!

**Comment by vladikoff** [comment]
Closing until needed
