### ISSUE TITLE
All XHR requests should be required to have a "dataType"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2086]
We have now had two issues relating to the lack of `dataType` and JSON responses not being decoded on FF 18. We should check to make sure all XHR requests should have a `dataType` set and except if not, to make sure we find these problems during development. See #1786 and #2084.

The should be added to https://github.com/mozilla/fxa-content-server/blob/f31671fd602ace652b65f8b7721869f67185f4fb/app/scripts/lib/xhr.js#L30

**Comment by vladikoff** [comment]
Should be careful because some XHR requests may not be JSON.

**Comment by vladikoff** [comment]
Closing until we see with this issue again, my comment from March still stands.
