### ISSUE TITLE
Provide a mechanism for WebChannel OAuth reliers to receive an encryption key derived from kB

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2088]
Context around driving use cases and requirements here: https://mail.mozilla.org/pipermail/dev-fxacct/2015-February/001348.html

Providing FxA keys to reliers is on our FxA roadmap (FxA 15.5 of https://docs.google.com/document/d/1A4DaBA1sWYmJ1p1ILQTWzEeTTfl61TuhapBctDcwJ0Q/edit?usp=sharing), although it wasn't really prioritized for Q1. 

@rfk and @shane-tomlinson, can you take the lead on this, and determine whether it's feasible for Q1, and whether we need de-prioritize other work to Q2? Given we don't need to support the general case makes the solution more manageable, but I'd like you to confirm that. 

@adamroach says "we'd need a dev environment enough in advance of March 30th".

**Comment by rfk** [comment]
This is something I'm personally quite excited about so it's great to have a concrete driver to move it forward.

> enough in advance of March 30th

Some more context for our reference, from @adamroach email: "Ideally, we'd like to be able to work with this during the Firefox 39 development cycle, so we'd need a dev environment enough in advance of March 30th".  FF39 is on central during March and moves to Aurora in early April.

**Comment by rfk** [comment]
From discussion with @ckarlof, if we're going to push on this for Q1, we should aim to have something ready for dev consumption by early March while FF39 is on central.

**Comment by rfk** [comment]
@shane-tomlinson if you have the bandwidth to mentor me on this one, I'd love to take it on as an opportunity to get more familiar with our front-end code.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson if you have the bandwidth to mentor me on this one, I'd love to take it on as an opportunity to get more familiar with our front-end code.

:+1: We have a 1:1 scheduled for Feb 10, want to discuss then? Obviously, if you have any questions ahead of time, hit me up!

A good place to start is https://github.com/mozilla/fxa-content-server/blob/master/docs/architecture.md

**Comment by ckarlof** [comment]
> A good place to start is https://github.com/mozilla/fxa-content-server/blob/master/docs/architecture.md

While looking at that, if something is confusing or missing, make a PR. :)

**Comment by ckarlof** [comment]
@adamroach has a nice diagram on how they would use key-wrapping in Loop:

https://www.dropbox.com/s/93rw3yjequ8ps3z/loop-keys.pdf?dl=0

**Comment by ckarlof** [comment]
@rfk, we should think about how pass keys around. I suggest as [JWKs](https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41).

**Comment by ckarlof** [comment]
Might need to pump the brakes on this for a little bit: https://bugzilla.mozilla.org/show_bug.cgi?id=1115340#c11

Let's wait for :rbarnes to propose an alternative architecture. For those of you that don't know Richard, he leads the crypto eng team at Mozilla and is an all around cool dude. It's great to have him helping out here. I chatted with him a bit, and I think he's roughly going to propose we give back a random key wrapped with kB rather than a derived key, or provide an encryption/decryption oracle for kB.

**Comment by rfk** [comment]
Cool, good to have an experienced set of eyes on this.  My only concern is that the linked discussion is moving further and further away from something that can be easily opened up in the oauth flow...but I guess that's not really a Product Requirement at this stage anyway

**Comment by ckarlof** [comment]
> My only concern is that the linked discussion is moving further and further away from something that can be easily opened up in the oauth flow...but I guess that's not really a Product Requirement at this stage anyway

I don't think it is, actually. You could implement this client side encryption API in some iframe postMessage thing.

**Comment by rfk** [comment]
> some iframe postMessage thing

That's still pretty far from "oauth" ;-)

After digesting the linked proposal, I think my concern has crystalized into "it's a very stateful API".  There will be lots of edge-cases with logging out and logging in in different tabs, different contexts, different browsers.  All manageable of course, but complex and potentially error-prone.

That's not a concern for loop-inside-gecko though, where we've got plenty of stateful FxA stuff going on already.

**Comment by ckarlof** [comment]
> That's still pretty far from "oauth" ;-)

Not entirely. For example, the message to encrypt and decrypt requires an OAuth token with the right scope.
> After digesting the linked proposal, I think my concern has crystalized into "it's a very stateful API".  

Yep, that's a little boogery. We could focus on the kA case for OAuth general API, which could still use the iframe for providing Richard's oracle API. We could make that stateless.

**Comment by ckarlof** [comment]
> There will be lots of edge-cases with logging out and logging in in different tabs, different contexts, different browsers. All manageable of course, but complex and potentially error-prone.

Then again, if the iframe can't do the action, it could also signal "auth needed", and that complexity could be handled by the fxa-relier-client.
