### ISSUE TITLE
"Index or size is negative or greater than the allowed amount" for avatar uploaded to latest

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2093]
"Index or size is negative or greater than the allowed amount" for avatar uploaded to latest.dev.lcip.org/settings/avatar
![animated](https://cloud.githubusercontent.com/assets/68213/6087619/e68aebde-ae1b-11e4-977b-ee758ffe6cf5.gif)

**Comment by rfk** [comment]
This looks like the same issue @vmunix hit at Whistler, fixed in https://github.com/mozilla/fxa-content-server/issues/2639
