### ISSUE TITLE
`login` message should indicate whether the account is verified

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2094]
A request from @ncalexan to help with the iOS flow:

> I want the "logged in" message to include whether the account is verified

**Comment by ckarlof** [comment]
Is this as easy as adding `verified` to https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-desktop.js#L106?

`verified` is a [persistent prop on Account](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L26), and also returned by the [auth API during login](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountlogin).

**Comment by ckarlof** [comment]
@vladikoff, want to give it a shot?
