### ISSUE TITLE
notification mechanism for sending events to all channels

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2095]
We need a mechanism for sending messages to the browser when the user changes account settings. Views currently instantiate with a `broker` that is some variety of AuthBroker.

We *could* add an independent `settingsBoker` property to views to handle notifications about settings changes. I'm open to other approaches.

**Comment by shane-tomlinson** [comment]
@zaach - what about just using the existing fx-desktop broker?  The basic idea is if profile info changes, we would notify all the brokers, the brokers would then decide how to handle the notification. All brokers except the fx-desktop broker would drop the message on the ground. fx-desktop would send a message out to the browser, which would do its thing.

**Comment by zaach** [comment]
@shane-tomlinson Yes, we could add to an existing broker though probably not fx-desktop since we've deprecated it. The `auth` naming made it unclear to me if that was appropriate, but they *are* instantiated on every page regardless of whether you're entering an auth flow or not, so :+1: .

**Comment by shane-tomlinson** [comment]
@zaach - ah, now I have a better understanding. The AuthBrokers interact with the reliers, adding this functionality to an existing AuthBroker seems like it breaks that abstraction. Your original proposal seems more correct than my counter-proposal, and would probably be easier to reason about if it were in its own standalone unit.

**Comment by ckarlof** [comment]
@zaach and I had a quick chat. We talked about a general notification abstraction. For example, you could submit events that get broadcast to both other FxA tabs in the same browser and the Desktop browser through WebChannel.
