### ISSUE TITLE
/config not appended to publicUrl

### ISSUE THREAD

**Issue by mathstuf** [mozilla/fxa-content-server#2096]
I have my servers being reverse proxied through nginx and URL paths aren't being created properly.

```
https://example.com/content -> content server
https://example.com/auth -> auth server
https://example.com/ -> static files
```

However, `https://example.com/config` is being generated when it should be `…/content/config`.

**Comment by mathstuf** [comment]
For that matter, same with `/signup`. Are URLs being created just with the hostname somewhere?

**Comment by shane-tomlinson** [comment]
Hi @mathstuf,
Thanks for the feedback, I'm a bit confused about the problem here. Are you saying that the content server should only respond to queries of the form `/content/config` and not to just `/config`? You are probably right, when running multiple servers on one box, we always assume anything for the root directory goes to the content server.

You may be able to side-step this using some nginx foo, I'm not well enough versed to know the solution.

I'll have a look at our code to see if there is a quick solution.

**Comment by shane-tomlinson** [comment]
@mathstuf - I haven't been able to figure out a "quick" fix for this. The simplest manner seems to be to create an express [sub-app](http://expressjs.com/4x/api.html#app.mountpath), mounted at the pathname portion of the `public_url`.

This "works", but requires a myriad other changes. All templates and RequireJS config need to be updated to take into account the new root, which is a bit more than I have time for at the moment.

I leave where I made it to. As you can see, `/content` is hard coded in a couple of places, these will need to be updated to point to the correct location.

```diff
diff --git a/app/scripts/require_config.js b/app/scripts/require_config.js
index d8aa3b3..5dffc70 100644
--- a/app/scripts/require_config.js
+++ b/app/scripts/require_config.js
@@ -3,7 +3,7 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
 require.config({
-  baseUrl: '/scripts',
+  baseUrl: '/content/scripts',
   paths: {
     jquery: '../bower_components/jquery/dist/jquery',
     backbone: '../bower_components/backbone/backbone',
diff --git a/server/bin/fxa-content-server.js b/server/bin/fxa-content-server.js
index 5f1b4b3..ca76a58 100755
--- a/server/bin/fxa-content-server.js
+++ b/server/bin/fxa-content-server.js
@@ -7,6 +7,7 @@
 var fs = require('fs');
 var https = require('https');
 var path = require('path');
+var url = require('url');
 var config = require('../lib/configuration');
 
 var mozlog = require('mozlog');
@@ -49,8 +50,16 @@ logger.info('page_template_directory: %s', PAGE_TEMPLATE_DIRECTORY);
 
 function makeApp() {
   'use strict';
+  var baseUrl = url.parse(config.get('public_url')).pathname;
+  if (baseUrl === '/') {
+    baseUrl = '';
+  } else if (! /\.+\/i$/.test(baseUrl)) {
+    baseUrl += '/';
+  }
 
+  var wrapperApp = express();
   var app = express();
+  wrapperApp.use(baseUrl, app);
 
   app.engine('html', consolidate.handlebars);
   app.set('view engine', 'html');
@@ -98,7 +107,7 @@ function makeApp() {
   // server error!
   app.use(serverErrorHandler);
 
-  return app;
+  return wrapperApp;
 }
 
 var app,
diff --git a/server/lib/routes/get-index.js b/server/lib/routes/get-index.js
index 92b1a2c..e478f37 100644
--- a/server/lib/routes/get-index.js
+++ b/server/lib/routes/get-index.js
@@ -8,7 +8,9 @@ module.exports = function () {
   route.path = '/';
 
   route.process = function (req, res) {
-    res.render('index');
+    res.render('index', {
+      root: '/content'
+    });
   };
 
   return route;
diff --git a/server/templates/pages/src/index.html b/server/templates/pages/src/index.html
index a2925e9..1bf4f40 100644
--- a/server/templates/pages/src/index.html
+++ b/server/templates/pages/src/index.html
@@ -12,23 +12,23 @@
         <meta name="viewport" content="width=device-width">
 
         <!-- build:css(.tmp) /styles/{{ locale }}.css -->
-        <link rel="stylesheet" href="/bower_components/normalize-css/normalize.css">
-        <link rel="stylesheet" href="/styles/fontello.css">
+        <link rel="stylesheet" href="{{root}}/bower_components/normalize-css/normalize.css">
+        <link rel="stylesheet" href="{{root}}/styles/fontello.css">
         {{#if fontSupportDisabled}}
-        <link rel="stylesheet" href="/styles/system-font-main.css">
+        <link rel="stylesheet" href="{{root}}/styles/system-font-main.css">
         {{else}}
-        <link rel="stylesheet" href="/styles/fonts/{{ locale }}.css">
-        <link rel="stylesheet" href="/styles/main.css">
+        <link rel="stylesheet" href="{{root}}/styles/fonts/{{ locale }}.css">
+        <link rel="stylesheet" href="{{root}}/styles/main.css">
         {{/if}}
         <!-- endbuild -->
 
         <!-- build:js /scripts/vendor/env-test.js -->
-        <script src="/scripts/vendor/env-test.js"></script>
+        <script src="{{root}}/scripts/vendor/env-test.js"></script>
         <!-- endbuild -->
 
         <!--[if lt IE 9]>
           <!-- build:js /bower_components/html5shiv/dist/html5shiv.js -->
-          <script src="/bower_components/html5shiv/dist/html5shiv.js"></script>
+          <script src="{{root}}/bower_components/html5shiv/dist/html5shiv.js"></script>
           <!-- endbuild -->
         <![endif]-->
     </head>
@@ -55,7 +55,7 @@
              with a cache aware URL.
          -->
         <!--[if gt IE 9]><!-->
-        <script data-main="/scripts/main" src="/bower_components/requirejs/require.js"></script>
+        <script data-main="{{root}}/scripts/main" src="{{root}}/bower_components/requirejs/require.js"></script>
         <!--<![endif]-->
     </body>
 </html>
```

If nginx can take care of this, it may be your best option.

**Comment by mathstuf** [comment]
No, it shouldn't *respond* to such queries, but *generate* URLs like that. Right now I have a special case for `/config` to rewrite it to `/content/config` which then gets `proxy_pass`'d with another rewrite rule. I guess static files should be rewritten too, but then docs on what paths are static and which need to be proxied would be welcome since right now I'm sort of abusing the fact that generated URLs aren't technically valid and using nginx to serve those up. It's just that `/config` was an exception to that rule. I guess making the content server the root would also work on my end (though I don't see why such a restriction should exist). If that is the recommended and supported deployment method, then docs mentioning that would be welcome.

**Comment by mathstuf** [comment]
OK, so I changed nginx to proxy the root to the content server (and `/auth` to the auth server) and things worked. The docs should either mention that the content server must be hosted at the root or support for non-root content servers should be added.

**Comment by shane-tomlinson** [comment]
> OK, so I changed nginx to proxy the root to the content server (and /auth to the auth server) and things worked. The docs should either mention that the content server must be hosted at the root or support for non-root content servers should be added.

Thanks for the feedback @mathstuf, you are keeping us honest. PRs welcome for either one, I'd be happy to mentor you through the process if you are willing. :D

**Comment by vladikoff** [comment]
Current workaround is to host the content server on the subdomain.
Otherwise please send a pull request to fix this up if you have time!
