### ISSUE TITLE
Fix signed out message

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2102]
When the user signs out of accounts.firefox.com, there is a green "Signed out" message that appears above the login screen. It seems out of place. Should we:

1. Append the word "sucessfully" (e.g. "Signed out succesfully") or…
2. Remove the message entirely.

**Comment by shane-tomlinson** [comment]
Added in #924 for #891. I'm partial to adding "successfully"

**Comment by shane-tomlinson** [comment]
@ryanfeeley - here are all the "success" messages, could you give them a quick review?

```bash
➜  views git:(issue-2102-signed-out-successfully) ✗ rgrep "success:" .
./change_password.js:              success: t('Password changed')
./complete_reset_password.js:                success: t('Account verified')
./complete_sign_up.js:                    success: t('Account verified')
./confirm.js:                    success: t('Account verified')
./confirm_reset_password.js:                  success: t('Account verified')
./confirm_reset_password.js:        success: t('Password reset. Sign in to continue.')
./delete_account.js:                    success: t('Account deleted successfully')
./settings.js:            success: t('Signed out')
```

**Comment by ryanfeeley** [comment]
Ooooh, handy. I probably originally argued that "successfully" wasn't necessary due to the use of green. Even if that was the case I now think we should append "successfully" to each phrase. Exception: "Password reset successfully." not "Sign in to continue successfully." :)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - to confirm the changes:
* Password changed => Password changed successfully
* Account verified => Account verified successfully
* Password reset. Sign in to continue => Password reset successfully. Sign in to continue
* Account deleted => Account deleted successfully
* Signed out => Signed out successfully

**Comment by ryanfeeley** [comment]
Yep! Just need a period after Sign in to continue.
