### ISSUE TITLE
Make COPPA ask "How old are you?" instead

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2108]
Pending clearance from our legal team, we are going to take some snark-reducing measures and change our neutral age verification mechanism by replacing the birth year pull down with a digit-only text input and the question: How old are you?
![coppa](https://cloud.githubusercontent.com/assets/68213/6231057/3af98fc6-b692-11e4-8b6e-124c0348b9b6.gif)

Filing bug to get it in backlog, more detail coming shortly.

**Comment by johngruen** [comment]
@ryanfeeley: the clip above is a bit misleading. I think we want to ask how old users are on the same page as the email/password inputs. Also not adding a mandatory checkbox on our ToS/PN

**Comment by ryanfeeley** [comment]
Some extra margin is required above the COPPA field, as the password requirement may be present too.
![coppa-proposed](https://cloud.githubusercontent.com/assets/68213/6232021/79d40b72-b697-11e4-8557-c3ce40d0e4ac.gif)

**Comment by johngruen** [comment]
@ryanfeeley: modest proposal...what would it look like to use that pattern on all fields? I already implemented it for the change password page. It would aid usability and solve that pesky 'password must be 8 characters' string hanging out under the password input.

**Comment by ryanfeeley** [comment]
I'd prefer we use it only when it's really helpful as it requires extra margin and can collide with validation. That said, it's very helpful on almost all but the simplest of forms (logins or single password entries).

**Comment by johngruen** [comment]
@ryanfeeley: i think the margin issue is a wash...that '8 characters' string adds a shit-ton of margin below the password field and it already collides with validation. having the labels tightly pinned to the top of each input wouldn't add any margin in this context

**Comment by johngruen** [comment]
@ryanfeeley: before and after
![diff](https://cloud.githubusercontent.com/assets/3323249/6233286/c778c9e6-b69f-11e4-81e4-23524f6aad75.gif)

**Comment by ryanfeeley** [comment]
@johngruen Getting pinged about COPPA old-feelings-maker. Is this coming?

**Comment by vladikoff** [comment]
@ryanfeeley @johngruen setting train-41, maybe we can hack on updating this.

**Comment by vladikoff** [comment]
We are gonna use "oauth.signup.screen" + "signup.screen" + success events and do an AB test

**Comment by xmatthewx** [comment]
Would love to see the results of the A/B tests.
