### ISSUE TITLE
use our own build of selenium server 2.45 on tests.dev.lcip.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2115]
Hey @vladikoff. I built https://people.mozilla.org/~jmorrison/selenium-server-standalone-2.45.0-jrgm.jar, so we can actually test with firefox 35 (due to https://code.google.com/p/selenium/issues/detail?id=8390). 
Works for me with java7. Wanna put this on tests.dev.lcip.org so we can test current firefox, at least until an official release becomes available?

**Comment by jrgm** [comment]
@vladikoff ping

**Comment by vladikoff** [comment]
@jrgm hey, great work getting it to compile, I haven't tried that. I shall update to your custom build and latest Firefox in the next few days! :+1:

**Comment by rfk** [comment]
thanks @jrgm, I tried the updated version and it worked a treat

**Comment by vladikoff** [comment]
This version I got from the `#ateam` channel should work with FF36 http://ci.seleniumhq.org/selenium-server-047ab5f8f98dbc967c1e7b018cb8f73424f04387.jar

**Comment by jrgm** [comment]
@vladikoff - ah, cool. Yeah, my version was immediately broken when 36 was released. (Hmm, I'm going to put a beta version running against stable or latest on teamcity, so we have a little more warning).

**Comment by jrgm** [comment]
Regular release of 2.45 is out http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
