### ISSUE TITLE
strange partial circle when profile image is not found.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2117]
My profile server in fxa-local-dev is not working correctly, so profile images are not being stored/retrieved correctly. All uploaded profile images 404, leaving a strange partial circle on the screen:

![screen shot 2015-02-19 at 13 16 05](https://cloud.githubusercontent.com/assets/848085/6267171/aece1dec-b839-11e4-8c05-7f10678d81af.png)

Link to #2116

**Comment by ckarlof** [comment]
I've seen this too.

**Comment by zaach** [comment]
Dupe of #1804.
