### ISSUE TITLE
about:accounts and the content server use different fonts.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2118]
The content server uses Fira Sans. about:accounts uses Helvetica Neue DeskInterface, with the 'sans serif' font-family declaration.

### about:accounts
![screen shot 2015-02-19 at 16 51 53](https://cloud.githubusercontent.com/assets/848085/6271296/aea63480-b857-11e4-8e48-3d63bdfea373.png)

### accounts.firefox.com
![screen shot 2015-02-19 at 16 48 46](https://cloud.githubusercontent.com/assets/848085/6271301/b6072cf2-b857-11e4-98dc-83a849136546.png)

I'm not adverse to using 'sans-serif' everywhere as it would speed up the initial render.

**Comment by zaach** [comment]
@ryanfeeley @johngruen Should we ditch custom fonts everywhere?

**Comment by ryanfeeley** [comment]
@zaach Definitely not as Fira Sans is the font that was cu$tom built for Mozilla, and is a looker at that. I'm not averse to a sans-serif fallback though. IMHO we should ship it in the browser and use it sparingly in there too.

**Comment by zaach** [comment]
Gotcha. IIRC there was a reason it was disabled on desktop. I'm not sure what the bug was.
