### ISSUE TITLE
bower failure should be ERR, not WARN

### ISSUE THREAD

**Issue by 501st-alpha1** [mozilla/fxa-content-server#2132]
When I ran `npm install`, the last line of output was:

    npm WARN cannot run in wd fxa-content-server@0.31.0 bower update --config.interactive=false -s (wd=[snip])

Running the provided `bower` command manually, I noticed that it failed because I was running as root, and `bower` complained about that. (This part is fine, I understand why running as root is not ideal. I can temporarily work around by manually runing the `bower` command and adding the `--allow-root` option.)

The problem I wish to report is that the `fxa-content-server` doesn't work correctly if this command fails, as it did for me above. (It gives 404s on the `bower_components` directory.) Thus, I think this should be an error that causes a hard fail, not a warning.

**Comment by vladikoff** [comment]
I don't think we can really control / change the `npm WARN` behaviour to a `npm ERR`. 
The `cannot run in wd` is something npm does. 

However, we can either add `--allow-root` to the post install Bower command or tell users not to install as root. The first option might be better.
