### ISSUE TITLE
/settings page not providing "loaded" message

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2137]
After #2066, I expect to get a "loaded" message from https://stable.dev.lcip.org/settings?context=fx_desktop_v1.  In practice, I'm seeing a "login" message and no "loaded" message at all.

@zaach and I discussed in #fxa and he thinks this is a bug.

**Comment by ncalexan** [comment]
In fact, this also appears to be my error; but there may be a content server error (inconsistency?) as well.

/signin completes even if I `postMessage(data, url)` with a bad URL.  /settings fails when I `postMessage` with a bad URL.  Perhaps the validation of the incoming message is inconsistent?  By bad URL, I mean one that looks like `Optional(https://...)`, like in #2138.

**Comment by zaach** [comment]
Right, the issue with settings is that the error occurs before the screen has been rendered. The `loaded` event is only sent after the screen has rendered and is visible.

**Comment by zaach** [comment]
We should make sure the `loaded` event is still sent if an error page is shown as the first screen.
