### ISSUE TITLE
Flashes or pops when tapping the content or body on iOS devices

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2140]
I'm seeing flashes or pops of the horizontal range of the "content box" when I tap the content or body of pages.  (On iOS devices.)  By "horizontal range", I mean it looks like the vertical range of the content box and the horizontal range of the screen.

**Comment by vladikoff** [comment]
We discussed it in triage and it seemed like it is a really minor issue with the WebView. 

If the flashes are affecting user experience then we may reconsider.
