### ISSUE TITLE
"Unexpected error" when attempting to use fxa-content-server

### ISSUE THREAD

**Issue by 501st-alpha1** [mozilla/fxa-content-server#2145]
I am attempting to host my own Firefox Accounts server. I have started up an `fxa-auth-server` and an `fxa-content-server`, both without errors. (In what follows, let `[fxa-auth]` be the URL of the `fxa-auth-server`, and `[fxa-content]` be the URL of the `fxa-content-server`.) I set the following entries in `about:config`:

    identity.fxaccounts.auth.uri                 [fxa-auth]
    identity.fxaccounts.remote.force_auth.uri    [fxa-content]
    identity.fxaccounts.remote.signin.uri        [fxa-content]
    identity.fxaccounts.remote.signup.uri        [fxa-content]
    identity.fxaccounts.settings.uri             [fxa-content]

After navigating to the Firefox Sync menu, and clicking sign up, I am directed to `about:accounts?action=signup`. After the page loads, I can see the Firefox logo, and blue bar below it, and nothing else. In the Javascript console, I see the following:

    "Critical error:"
    Error: unexpected error
    Stack trace:
    .toError@https://[fxa-content]/scripts/lib/errors.js:103:11
    errorIfNoResponse/outstandingRequest.timeout<@https://[fxa-content]/scripts/lib/channels/mixins/postmessage_receiver.js:40:7

I don't see anything in the `fxa-auth-server` log to indicate that it ever receives any requests. I also don't see much abnormal in the `fxa-content-server` log, except for the following line, which appears at the same time the previous error does:

    fxa-content-server.server.requests.ERROR: 500.html {}

What am I doing wrong? What can I do to troubleshoot this problem further?

**Comment by shane-tomlinson** [comment]
> In the Javascript console, I see the following:

Are there any XHR requests with a non-200 status displayed in the console?

**Comment by 501st-alpha1** [comment]
The only other status is `304`. I show 29 XHR requests in the console.

**Comment by vladikoff** [comment]
To debug this we will need a more detailed report for the XHR requests. 
Manually navigate to [ identity.fxaccounts.remote.signup.uri   ] (without the firefox native flow)
Then see if you can record the requests against the auth server. Those requests should have the error that is causing this.

**Comment by 501st-alpha1** [comment]
Interesting. When I navigate to `[fxa-content]`, the UI shows up correctly (all requests are again either `200` or `304`), and I can fill out the form to create an account. However, which I click "Sign up", I get this error message:

> An attempt was made to use an object that is not, or is no longer, usable.

No more requests are made when I click the button.

Any ideas?

**Comment by 501st-alpha1** [comment]
@vladikoff What else can I do to troubleshoot this?
