### ISSUE TITLE
Make /settings endpoint communicate to Desktop channel when password changes or account is deleted

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2152]
On iOS, I'm embedding accounts.firefox.com/settings in the Settings Home Panel.  The user can change their password or even delete their Firefox Account.  I want to be able to react those changes seamlessly in the embedding panel.

I propose that the content server include new login details from /settings/change_password, and include a bare message about deleting the account entirely.

**Comment by ckarlof** [comment]
This is what the WebChannel infrastructure was built to do.

WebChannels are way for chrome and trusted Web pages to communicate more effectively. @zaach is laying some initial stuff in place to signal avatar-image-change events out to Desktop -- I think these events would be a good followup.

**Comment by ncalexan** [comment]
I think the `/settings/change_password` message should include the same bundle of data as the initial `signedin` message.   That'll let us fetch new keys.

**Comment by ncalexan** [comment]
Oh, sweet!  I didn't realize this happened.  Go team!
