### ISSUE TITLE
Enable CSP (or CSP Report-Only) on latest.dev.lcip.org?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2155]
Maybe we should put this in fxa-dev, but this is really a question of should we (not how). So it's here. 

Should we do one of these on latest and see how things look?

**Comment by vladikoff** [comment]
@jrgm CSP Report-Only, would that make functional tests break or can we just enable it with no issues?

**Comment by jrgm** [comment]
Enabling CSP-Report-Only won't break functional tests; it's in report-only on stage and intern tests pass there. (I have a violation in stage that I need to fix up the headers for, but that's a separate topic).

**Comment by shane-tomlinson** [comment]
@jrgm to confirm we can do this.

**Comment by jrgm** [comment]
Ah, right. Selenium sets "security.csp.enable" to false in the FirefoxDriver. See [previous notes](https://github.com/mozilla/fxa-content-server/issues/1256). Enabling CSP in the profile results in a spew of meaningless false-positive CSP violation reports. 

One of the core selenium folks commented [here](https://code.google.com/p/selenium/issues/detail?id=7640) that "<i>The current FirefoxDriver implementation has serious disfunction when CSP is enabled. It is next to impossible to fix this. Let's hope the next implementation aka Marionette will be able to work with CSP enabled</i>".

However, we can enable CSP on latest <i>as long as</i> we do not force CSP on in the FirefoxDriver. The tests all pass and there are no violation reports from the selenium run, so any occurences of a violation report could be taken seriously, should it occur. (To actually enable CSP on latest, will need [this PR](https://github.com/mozilla/fxa-content-server/pull/2278), a fix for the violation report handler, and probably some fxa-dev template changes to add the appropriate config settings for fxa-content-server).

**Comment by vladikoff** [comment]
We have CSP Report-Only reporting errors now, which is great! The new FirefoxDriver is not ready, so we cannot do anything further here on the content server for now. Maybe we should create a CSP milestone in the future?

**Comment by shane-tomlinson** [comment]
I'm re-opening this after an email exchange with @fmarier. We can send both CSP and CSP-report-only headers, __at the same time__. This allows us to add known good rules to CSP, and rules that are still causing us problems to CSP-report-only. We *should* be able to fully enable all rules except inline-script, which is needed by Selenium. Even this update would be a major win.
