### ISSUE TITLE
Revisit/document pinning of `p` dependency to a specific git hash

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2160]
While mucking around with bower, I noticed that our bower.json pins the `p` dependency to a specific git hash.  The fxa-js-client repo also pins it, but to a different and conflicting git hash.  Why do we need to pin it like this?  It would be great to use a tagged release but failing that, can we document the reason for the pin in bower.json?

**Comment by shane-tomlinson** [comment]
@rfk - good question. What would be even more awesome is to use a single copy, but I'm not sure if there is a way to do that.

**Comment by pdehaan** [comment]
Re versions, not sure why we're pinning to a specific SHA, but we could probably pin each repo to one of the releases.

https://github.com/rkatic/p/commits/master
https://github.com/rkatic/p/releases

It looks like our fxa-content-server SHA is pinned to 2 commits before the v0.4.9 release.
