### ISSUE TITLE
Sync profile image updates across tabs/frames

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2164]
When #2095 is done we'll have a notification mechanism for signalling profile changes across tabs and frames. We should use that to keep the UI in sync.

**Comment by ncalexan** [comment]
Is this done?  Ready for action?  I'm trying to understand what the messaging will look like in clients if two tabs are open to accounts.firefox.com.

**Comment by zaach** [comment]
It's ready for action. How'd I imagine it'd work: when a page with an avatar loads, we attach a listener to `notifications`* that can fetch the latest profile data and update the view.

* `notifications` listens to events from other tabs: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/notifications.js#L47-L53

**Comment by shane-tomlinson** [comment]
This works now, closing.
