### ISSUE TITLE
simplify router.js->error handling

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2167]
follow on from #2147. See comment https://github.com/mozilla/fxa-content-server/pull/2147#issuecomment-76155999

> @zaach, I just want to make sure I have the logic correct, because it's kind of fiddly. Maybe we have an opportunity for cleanup.
> 
> Walking through the scenario - we'll say the startup screen is the /signin screen.
> 1. `self._firstViewHasLoaded` is set to false on startup.
> 2. The first call to `showView` is called with SignInView. SignInView renders, throws an error.
> 3. The `.fail` branch is called, which uses the view's `navigate` function to redirect to `unexpected_error`.
> 4. The call to `navigate` eventually makes its way back to the router, which calls showView with the UnexpectedErrorView.
> 5. UnexpectedErrorView successfully renders, the success branch of the promise is used.
> 6. self._firstViewHasLoaded is still `false`, so the broker is notified, even though we had a failure.
> 
> Maybe a cleanup is to remove the call to view.navigate and call the router's navigate directly. To do so, we need to set ephemeralMessages.error. All views by default use a singleton EphemeralMessages created in views/base.js. Views are already set up to accept an injected ephemeralMessages, which is used extensively in testing. We could create the EphemeralMessages instance in app-start, pass it to router, which then passes it to views. Instead of calling view.navigate and needing to think about what happens, we set the error on ephemeralMessages, then call this.navigate directly, resulting in fewer parts to think about? The disadvantage is the router knows about ephemeralMessages. Perhaps this is acceptable, and it would allow us to remove the singleton instance created in base.js

**Comment by shane-tomlinson** [comment]
Closing because this is not absolute critical path, we can re-open when we find the desire. Would be happy to mentor folks through it.

**Comment by jstrutz** [comment]
I'm happy to have a go at this, if it still merits some attention.  Does your offer for guidance still stand?

**Comment by shane-tomlinson** [comment]
@jstrutz - this is labelled a "good-first-bug", but the description makes me think this could be a huge time sink for little immediate reward.

**Comment by jstrutz** [comment]
@shane-tomlinson - sounds good; I'll find an issue which is a better use of our time :)

**Comment by vladikoff** [comment]
Please reopen if still needed!
