### ISSUE TITLE
Show password by default experiment

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2169]
So that I can experience fewer errors, as a Firefox Accounts user, I want to be able to see and know that my passwords are turned on by default.

So that we can tell if it it improves the users experience of forms that contain passwords, as team members of Firefox Accounts, we want to show passwords by default and compare the errors and user feedback with masking by default.
![show-password-default-on](https://cloud.githubusercontent.com/assets/68213/7046319/d0a16f50-ddd2-11e4-8352-6d0f6b833e03.png)

**Comment by ckarlof** [comment]
Seems ok, I guess. What's the data you want to collect here? How do you know it was a success or a failure?

**Comment by ryanfeeley** [comment]
Fewer password-related errors were fired than before.

**Comment by shane-tomlinson** [comment]
> Fewer password-related errors were fired than before. 

Fewer as an absolute count is not really helpful since the absolute number of login attempts is constantly in flux. Fewer errors as a percentage when compared against another number is more useful. Another useful metric to consider is password reset attempts per number of login attempts.

**Comment by ckarlof** [comment]
> Fewer password-related errors were fired than before.

We need to be more specific. In particular, I don't think the value is in getting the user through the signup flow without any password related errors (e.g., I think the only password error in signup is "too short"). 

I think the value is helping the user remember their password. One metric may be around the rate of password resets vs login attempts, as @shane-tomlinson suggests, but they may be others of use as well.

**Comment by ryanfeeley** [comment]
> I think the only password error in signup is "too short"

Reducing incorrect passwords on login probably offers the most benefit to users, but if we could also tie it to future interactions like resets or subsequent logins, that would be fantastic.

For registration, showing the password would hopefully lead to less resets.

For change password, more correct old passwords.

For logins, fewer incorrect passwords.

Make sense?

**Comment by ckarlof** [comment]
> Make sense?

It all makes sense, but we still need this captured as some concrete metrics/data collection proposal. E.g., do we need to track password resets attempts for each user over time to answer this?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I started to outline some possible metrics we could use in https://id.etherpad.mozilla.org/password-visibile-metrics. The list will need to be refined and whittled down, but a start.

**Comment by shane-tomlinson** [comment]
I'm closing this until we decide to actually do it. We can re-open at that time.
