### ISSUE TITLE
All channels - validate & log errors with serialization 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2173]
Follow on from #2157. @vladikoff correctly [points out](https://github.com/mozilla/fxa-content-server/pull/2157#discussion_r25699601) we should validate commands and log serialization errors.

**Comment by shane-tomlinson** [comment]
Ref #2151

**Comment by shane-tomlinson** [comment]
@vladikoff - This looks like all channels are affected by this problem.

**Comment by shane-tomlinson** [comment]
Changing the title to reflect the general nature of this issue.

**Comment by vladikoff** [comment]
This might be fixed already, Shane to check this...

**Comment by shane-tomlinson** [comment]
Killing this as fixed.
