### ISSUE TITLE
Remove duplication of sjcl/hkdf code

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2174]
In #2143 we introduced a directly dependency on sjcl and hkdf, which duplicates a dependency that was already present in the fxa-js-client code.  We need to figure out how to remove this duplication and have them both use a single shared version of these libs.

**Comment by vladikoff** [comment]
This probably means we need to reconfigure the way the fxa-js-client is currently packaged or the way it is included in the project.

**Comment by rfk** [comment]
Right, I figure there's some bower magic that will give us what we want here.

**Comment by shane-tomlinson** [comment]
@rfk - see #1343. sjcl was already included twice, does that mean we now include it 3 times?

**Comment by shane-tomlinson** [comment]
jwcrypto was removed in 35997a040069a63fc37ed85b810dc090b6d2603c, so still only two references.
