### ISSUE TITLE
Add functional tests for oauth webchannel keys

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2175]
In #2143 we introduced the ability to get relier-specific keys through the webchannel broker, but we skipped an end-to-end functional test in order to get it out in train-32.  Let's add a proper functional test.

**Comment by shane-tomlinson** [comment]
hey hey, I just did that in #2357 2357

**Comment by shane-tomlinson** [comment]
@rfk, you added all these tests already, haven't you?

**Comment by rfk** [comment]
Yes, as part of #2385
