### ISSUE TITLE
email suggestion tooltip is not keyboard accessible

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2185]
This little fella has no way of tabbing into it.

![screen shot 2015-03-04 at 13 42 48](https://cloud.githubusercontent.com/assets/848085/6505823/bdefc212-c33d-11e4-89b5-d292eff8c2d4.png)

Ref #2009

**Comment by shane-tomlinson** [comment]
Closing for now due to lack of bandwidth, would still love to see this done and we are happy to mentor contributors.

**Comment by vladikoff** [comment]
Other tooltips that have these issue : account lock and sign up if account does not exist

**Comment by riadhchtara** [comment]
Hi, I'm interested in working on this one
But i m not able to reproduce it: I tried  to use set177@gmail.con (https://latest.dev.lcip.org/signup)
But the tool tip is not shown.
Could you please help me

**Comment by vladikoff** [comment]
@riadhchtara you need to add `?mailcheck=1` to the sign up url

**Comment by riadhchtara** [comment]
@vladikoff thanks, it s working :)

**Comment by riadhchtara** [comment]
Could you please check the new code?
I will include the tests later
