### ISSUE TITLE
email suggestion tooltip close button and iframe close button are different

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2186]
### email suggestion tooltip close button

![screen shot 2015-03-05 at 13 47 20](https://cloud.githubusercontent.com/assets/848085/6505863/3413b8d6-c33e-11e4-99b9-cd2d9812ad57.png)

### iframe close button

![screen shot 2015-03-05 at 13 47 59](https://cloud.githubusercontent.com/assets/848085/6505876/4b5603fa-c33e-11e4-831c-5f5e3ffc4854.png)

@ryanfeeley and @johngruen - what do you think, should we unify?

**Comment by ryanfeeley** [comment]
No, I think they are both well suited to the their respective context, but I do appreciate the attention to detail.
