### ISSUE TITLE
Introduce new strings behind a feature flag

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2189]
If we add new strings behind a feature flag we no longer have to worry about when we merge the PR or when we extract strings– new strings and old strings will co-exist until we decide enough translations have been completed to remove the old strings. We could also enable the feature for locales that have complete translations.

**Comment by ckarlof** [comment]
Good work @zaach on identifying opportunities to move faster.

**Comment by shane-tomlinson** [comment]
Closing because not immediately actionable.
