### ISSUE TITLE
Avatar crop page is weird in IE 10

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2191]
![screen shot 2015-03-06 at 11 12 58 am](https://cloud.githubusercontent.com/assets/3903/6531953/dcf930a8-c3f1-11e4-9a9c-33cc8a5c0b85.png)

The slider doesn't work either. The plus and minus buttons do adjust the slider value, but moving the slider with your cursor has no affect.

Everything else seems okay.

**Comment by pdehaan** [comment]
@pdehaan to verify in latest.dev.lcip and IE10 VM.

**Comment by pdehaan** [comment]
@pdehaan Verifying that this still isn't working on Win 10+IE 11.
Can confirm that the slider looks the same (broken lines) but alignment and everything seems to work in Edge browser.

**Comment by shane-tomlinson** [comment]
ref #2824

**Comment by shane-tomlinson** [comment]
I'm going to close this until IE11 becomes a higher priority for us.
