### ISSUE TITLE
event log inconsistencies between label and status.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2193]
The status field of the tooltip status events are inconsistent with other events. Other events use a `.` separator, the tooltip status events use a `-`.

cc @vladikoff and @kparlante

**Comment by shane-tomlinson** [comment]
The email suggestion tooltips are not alone. The email verification screens [use `_`](https://github.com/mozilla/fxa-content-server/blob/d66a6fe6928c7413aef05f36018e11c0cb15cde8/app/scripts/views/complete_reset_password.js#L47) between the label and the status.

Updating the title to reflect the more general nature of the problem.

**Comment by vladikoff** [comment]
All future events should use dots between the label and the status
