### ISSUE TITLE
Several errors are not referenced anywhere - how should these be deprecated?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2194]
[DESKTOP_CHANNEL_TIMEOUT](https://github.com/mozilla/fxa-content-server/blob/49a3cf29562d942e1199a2dc44d34098904a9ae3/app/scripts/lib/auth-errors.js#L163) is not referenced anywhere within client code. Can it be safely removed?

CHANNEL_TIMEOUT is another.

**Comment by shane-tomlinson** [comment]
Ref #2146 - Found while looking for that issue's solution.

**Comment by shane-tomlinson** [comment]
@ckarlof says we could just comment out the lines, which would keep the context in place.

**Comment by rfk** [comment]
>  just comment out the lines, which would keep the context in place.

:+1:, perhaps with a brief note on when or why it was removed.

**Comment by shane-tomlinson** [comment]
We decided, comment the errors out. Closing.
