### ISSUE TITLE
Allow styling flexibility of Accounts 

### ISSUE THREAD

**Issue by habber** [mozilla/fxa-content-server#2198]
We would like to allow styling flexibility of accounts iframe so that when embedding on Mozilla.org (and elsewhere) so that it fits with the design and content of the page. We would like to do the following. Please let us know if this is possible: 
- Remove the logo and box around the form fields http://cl.ly/image/001E3x1V1H2R

- Edit or remove form title - text at top of form that currently reads “Create a Firefox Account to continue to Firefox Sync”. This copy may work better styled differently on the page where this form exists. 

- Alter background color and/or remove background

- In reference to this form https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v1

**Comment by shane-tomlinson** [comment]
@habber - can you post a bug number, or add some context inline so we can understand how/where this will be used?

**Comment by habber** [comment]
@shane-tomlinson  Sure. The initial purpose for this would be for the /firstrun web page for Firefox 38 launch on May 12th (the first web page that a user sees when they download Firefox). I'm working on page mockups and can put them in a bug tomorrow. I don't want to design something that can't be done, but in the mockups I won't diverge from the items I listed above.

**Comment by ckarlof** [comment]
One of the goals of FxA is to have a consistent UX everywhere, so I'm hesitant to make changes without the guidance of @ryanfeeley and @johngruen, who are responsible for FxA UX.

**Comment by habber** [comment]
@ckarlof Of course. We met with @ryanfeeley yesterday. He instructed us to file issues here in Github and we'll work closely with FxA UX throughout. We'll stick to requesting and discussing very minor stylistic updates that wouldn't alter the mechanics or interaction of the sign up/in flow or impact the future "UX everywhere" plans.

**Comment by ckarlof** [comment]
@ryanfeeley, can you please give guidance here? In particular, some of these requests here sound a little too open ended, and I'm not sure we want to provide a general mechanism for reliers to control these aspects. E.g., as requested:

> Alter background color and/or remove background

sound more powerful that we need to it be. What background color do you want to change it to? Can we start with that specific color as an option, or allow a specific set of colors as an option? Likewise for the form title.

I'm hesitant to give reliers the ability to dynamically change the background to *any* color. This feature could lead to an inconsistent FxA UX because it would allow developers to dynamically change the FxA look and feel on a whim ("purple sounds good today!") without consulting @ryanfeeley.

**Comment by ryanfeeley** [comment]
@ckarlof It's cool. We met to discuss the possibility of offering a different container style for the FxA auth.

Something like:
![fxa-overlay-inline](https://cloud.githubusercontent.com/assets/68213/6579994/0a095764-c724-11e4-9e03-7e5b92e7e9d2.png)
This would save users a step, and allow our auth to appear inline, beside marketing content. I would be very involved in overseeing the application of this style, but the overall goal is to increase signups.

**Comment by ryanfeeley** [comment]
@habber Perhaps a better title for this issue is "Offer an inline-optimized iframe style for Firefox Account authentication."

**Comment by habber** [comment]
@ryanfeeley Sure. I can be more specific. I'll file a bug with mockups that visualize what I've noted in the 4 points above and your team can respond with what is possible. Do you know which bug component I should file it under?

**Comment by ckarlof** [comment]
I'd file a bugzilla bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody%40mozilla.org&bug_file_loc=http%3A%2F%2F&bug_ignored=0&bug_severity=normal&bug_status=NEW&cf_blocking_b2g=---&cf_blocking_fennec=---&cf_feature_b2g=---&cf_fx_iteration=---&cf_fx_points=---&cf_status_b2g_1_4=---&cf_status_b2g_2_0=---&cf_status_b2g_2_0m=---&cf_status_b2g_2_1=---&cf_status_b2g_2_1_s=---&cf_status_b2g_2_2=---&cf_status_b2g_3_0=---&cf_status_firefox36=---&cf_status_firefox37=---&cf_status_firefox38=---&cf_status_firefox39=---&cf_status_firefox_esr31=---&cf_status_firefox_esr38=---&cf_tracking_b2g=---&cf_tracking_e10s=---&cf_tracking_firefox36=---&cf_tracking_firefox37=---&cf_tracking_firefox38=---&cf_tracking_firefox39=---&cf_tracking_firefox_esr31=---&cf_tracking_firefox_esr38=---&cf_tracking_firefox_relnote=---&cf_tracking_relnote_b2g=---&component=FxAccounts&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&defined_groups=1&flag_type-203=X&flag_type-37=X&flag_type-4=X&flag_type-41=X&flag_type-5=X&flag_type-607=X&flag_type-720=X&flag_type-721=X&flag_type-737=X&flag_type-781=X&flag_type-787=X&flag_type-791=X&flag_type-799=X&flag_type-800=X&flag_type-835=X&flag_type-846=X&flag_type-853=X&flag_type-855=X&flag_type-856=X&flag_type-857=X&flag_type-863=X&flag_type-864=X&flag_type-870=X&flag_type-875=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Mac%20OS%20X&priority=--&product=Core&rep_platform=x86&target_milestone=---&version=unspecified).

The bulk of this work is going to be the re-working of the Sync login code to use the iframed FxA UX, not these look and feel changes. The Fx Sync login was built as a one-off before we had these more generalized mechanisms, so it'll be a non-trivial amount of work to give us more login options outside of `about:accounts`. 

Also, while FxA is still my responsibility, @rfk is now directly leading it. You can work with @rfk, @shane-tomlinson, and @ryanfeeley directly on this, and I'll provide guidance as necessary.

**Comment by shane-tomlinson** [comment]
> This would save users a step, and allow our auth to appear inline, beside marketing content. I would be very involved in overseeing the application of this style, but the overall goal is to increase signups.

Ah, so one thing being asked for is a way to embed FxA in an already existing page, without the lightbox look. @jpetto and I discussed this a few weeks ago, I've opened several issues and an initial PR on the relier client.

See [1][2][3] and [4].

[1] - https://github.com/mozilla/fxa-relier-client/issues/48
[2] - https://github.com/mozilla/fxa-relier-client/issues/49
[3] - https://github.com/mozilla/fxa-relier-client/issues/50
[4] - https://github.com/mozilla/fxa-relier-client/pull/54

**Comment by habber** [comment]
I've created a bug for this here https://bugzilla.mozilla.org/show_bug.cgi?id=1142046

**Comment by pwalm** [comment]
We at Marketplace are in the same boat as @habber, we'd love to be able to embed the FxA login/sign up flow into our site. We were thinking of taking it a bit further and embedding it (at least the sign in) into our nav.

We've got a sub-nav drawer that slides down for things like search or user settings...
![screen shot 2015-03-11 at 3 28 16 pm](https://cloud.githubusercontent.com/assets/6797635/6608340/571643de-c803-11e4-8da8-e2339527594f.png)

 ... and it would be awesome if we could follow the same pattern for FxA stuff:
![screen shot 2015-03-11 at 3 51 04 pm](https://cloud.githubusercontent.com/assets/6797635/6608693/7479add2-c806-11e4-9123-027da454811b.png)
(100% unofficial, just mocked it up for the sake of reference)

What does the FxA team think, is this taking it too far?

**Comment by ryanfeeley** [comment]
That would be too far ;)

We have built a lot of features into the Firefox account login form. For example soon if you partially mistype a domain in an email address it will suggest a corrected one, if you attempt to many logins you will be throttled, and many more. If we start creating multiple interfaces to Firefox accounts login we will potentially be maintaining them in multiple places on different release schedules. We are following Google's model which is very future-friendly, hopefully we won't be using just passwords in a few years.

**Comment by pwalm** [comment]
Fair enough! Thanks for the background.

**Comment by shane-tomlinson** [comment]
Ref #2178

**Comment by shane-tomlinson** [comment]
Ref #2101

**Comment by shane-tomlinson** [comment]
ref #2197

**Comment by shane-tomlinson** [comment]
This was fixed by #2593 and #2178, closing.
