### ISSUE TITLE
Reject email addresseses without a dot in the domain component

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2199]
When testing a form I entered in an intentionally invalid email syntax, but was able to proceed. The form should not submit until a valid email is entered (and messages should appear)
![whoneeds](https://cloud.githubusercontent.com/assets/68213/6585875/91e863f6-c74b-11e4-83b2-532b591893a8.png)

**Comment by pdehaan** [comment]
Funny story, that...
See #1909 (which fixed #1871)
Plus a few other old issues on it, like #619

**Comment by ckarlof** [comment]
Yeah, sorry @ryanfeeley that's technically a "valid email".

**Comment by pdehaan** [comment]
@ryanfeeley:
![](http://www.reactiongifs.com/wp-content/uploads/2013/01/BURN.gif)

**Comment by ryanfeeley** [comment]
Without a TLD? Or is it only a TLD? Shouldn't there be a . in there?

**Comment by ryanfeeley** [comment]
I read the issues above. I'll prepare a different treatment. The number of people who omit the period while typing their email will outnumber the people who have an email address without a period by a factor of maybe a million. Let's not let pedantry be a defining force of our UX.

**Comment by ryanfeeley** [comment]
AKA TIL that an email lacking a period can still be valid, so obviously, even though they are frighteningly rare, we should allow them without confirmation in our registration, even though there is no UI to go back and correct the email.

**Comment by ckarlof** [comment]
Perhaps the email suggestion feature that @vladikoff is working on will help address your concerns? For example `gmailcom` may get autosuggested to `gmail.com`.

> The number of people who omit the period while typing their email will outnumber the people who have an email address without a period by a factor of maybe a million. Let's not let pedantry be a defining force of our UX.

Absolutely. The only point we meant to message was that `x@y` is a indeed a valid email, so it may need messaging that's different if you want give that case any special treatment.

**Comment by ryanfeeley** [comment]
I'll work with @vladikoff on this. Some mistyped domains like gmailcom get fixed while others like hotmailcom don't, but it seems like the right UI for the job.

**Comment by rfk** [comment]
Can we safely close this bug in favour of the concrete fix in #2202 ?

**Comment by ryanfeeley** [comment]
@rfk Safe, but I think @ckarlof already closed it.

**Comment by rfk** [comment]
so he did, it was way up there in the scrollback where I couldn't see it

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/pull/123

**Comment by shane-tomlinson** [comment]
The strawman is to disallow email addresses that only contain a TLD in production because these are almost certainly not really routable addresses. We can add a configuration option to help self-hosters who may legitimately have an email address@sometld locally on their network.

**Comment by shane-tomlinson** [comment]
From [ICANN's announcement "Dotless Domain Names Prohibited"](https://www.icann.org/news/announcement-2013-08-30-en):

> At its meeting on 13 August 2013, the ICANN Board New gTLD Program Committee (NGPC) adopted a resolution affirming that "dotless domain names" are prohibited. Dotless domain names are those that consist of a single label (e.g., http://example, or mail@example). Dotless names would require the inclusion of, for example, an A, AAAA, or MX, record in the apex of a TLD zone in the DNS (i.e., the record relates to the TLD-string itself).

**Comment by rfk** [comment]
If we can use the above link as a concrete reference to point people to when they ask, sounds good to me!

**Comment by ryanfeeley** [comment]
@rfk Should we be using: http://emailregex.com/

**Comment by rfk** [comment]
We're going to move on disallowing dotless domains in a new issue on the auth-server side: https://github.com/mozilla/fxa-auth-server/issues/1193.  Whatever we do, let's ensure that the logic is consistent between client and server.

**Comment by ryanfeeley** [comment]
@rfk Anything we can do to drive that 7% bounce rate down. I hate the thought of 7% of users never telling Sync prefs to forget the email and never signing up again.
