### ISSUE TITLE
[style-wars] duplicate avatar on /settings

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2200]
STR: https://ux.dev.lcip.org/setttings when signed in

![dual-avatars](https://cloud.githubusercontent.com/assets/758162/6586777/a0dd3466-c739-11e4-9a75-aa85bba59515.png)

Also, the image appears to be off-center, and the `Change` link is showing to a non-mozilla email address.

**Comment by ckarlof** [comment]
testing, FTW.

**Comment by pdehaan** [comment]
Similar issues w/ webcam and gravatar avatars as well:
![manage_account](https://cloud.githubusercontent.com/assets/557895/6586848/61b2cfca-c73a-11e4-9e22-513654268191.png)

**Comment by rfk** [comment]
For completeness, I see the same thing (but without centering issues) when logged in with no avatar set.
![screen shot 2015-03-11 at 17 31 16](https://cloud.githubusercontent.com/assets/34695/6591468/852fe5b6-c814-11e4-976d-3ac0eba17a1e.png)

**Comment by ckarlof** [comment]
paging @johngruen. I suspect this is a regression introduced by the CSS refactor.

**Comment by johngruen** [comment]
Yep yep. Tracking all this and some more stuff Ryan noticed. Will tweak the PR Friday.

**Comment by dannycoates** [comment]
Piling on
![screen shot 2015-03-12 at 4 13 15 pm](https://cloud.githubusercontent.com/assets/87619/6630303/96f7cd66-c8d4-11e4-824f-033e883872a1.png)

**Comment by johngruen** [comment]
@pdehaan: i fixed the duplication issue in my latest push to the style-wars branch. I get an error when i try to save images to my local build, so IDK if fixing the double fixed the alignment problems as well (fingers crossed). Same question marks apply for @dannycoates issue.

**Comment by shane-tomlinson** [comment]
Fixed. Closing.
