### ISSUE TITLE
Some nits with the mailcheck feature

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2204]
Just my notes about the mailcheck feature.

- `me@fastmail.fm` gets a suggestion for `fastmail.fr`, which is wrong.

- `me@somewhere.ca` gets a suggestion for `somewhere.cz`, which is wut?

- in general, I don't think there's a win in trying to correct mispelling of two-letter TLDs. You could start a Danish-Deutschland war!

- when you tab away from the email field, and a suggestion pops up, the Esc key should be able to dismiss it. But it seems the listener for that key is only on the actual email field.

But aside from that, really nice feature!

**Comment by pdehaan** [comment]
Also, hypothetical question for @vladikoff and @ryanfeeley, but if I register with my fake email address of "peter@gnail.ca", the mailcheck tooltip says:

> Did you mean gmail.com? ✕

If I dismiss the tooltip (because I have a @gnail.ca email address) it may be nice if we remembered that and didn't redisplay that tooltip if they happen to focus/blur that email field again.

**Comment by vladikoff** [comment]
@pdehaan yea good suggestion, we didn't get a chance to include it in the first PR

**Comment by pdehaan** [comment]
@vladikoff Yeah, I don't think it's high priority, but a "nice to have".

And for the record, this is super awesome! Great work!

**Comment by pdehaan** [comment]
I can also get into a slightly weird behavior when trying to submit an invalid form when the email address is focused.

go to https://latest.dev.lcip.org/signup?mailcheck=1 and enter an email address of "peter@gsnail.co" then hit the signup button. You'll notice a very quick flash of the mailcheck tooltip and then it disappears immediately when the _"Valid password required"_ message pops up.
