### ISSUE TITLE
[style-wars] Mailcheck isn't styled correctly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2205]
@vladikoff's new mailcheck feature is pref'ed off, but you can enable it by adding `?mailcheck=1` to the URL.

1. Color is off.
2. Link not underlining.
3. Close button is too close to "things".

---

![firefox_accounts](https://cloud.githubusercontent.com/assets/557895/6630156/f7418376-c8d2-11e4-9efb-fb2c69e7c489.png)
**Figure 1:** https://latest.dev.lcip.org/signup?mailcheck=1

---

![firefox_accounts](https://cloud.githubusercontent.com/assets/557895/6630168/134aebf2-c8d3-11e4-9f64-225aa0f77d34.png)
**Figure 2:** https://ux.dev.lcip.org/signup?mailcheck=1

**Comment by johngruen** [comment]
@pdehaan: should be fixed by my latest changes

**Comment by shane-tomlinson** [comment]
Closing as fixed. I checked this yesterday.
