### ISSUE TITLE
Cannot log into Firefox Accounts with a saved password

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-content-server#2210]
STR:

* log in to Firefox Accounts on desktop and save the password for easier re-login
* log out of Firefox Accounts
* try to log in again so that Firefox autofills your password

The Sign In button is disabled even though the password has been filled in. To enable the Sign In button you can re-type your password but that defeats the password manager. This is a recent regression because saved passwords used to work.

Screencast from https://marketplace.allizom.org/ (which is on the stable dev server): http://screencast.com/t/A0fa0BCeepNb

**Comment by vladikoff** [comment]
via IRC:
```
[12:13:18]  <vladikoff>	 kumar, hey, is the "password has been filled in" using the Firefox password manager?
[12:13:31]  <kumar>	 yes
[12:13:36]  <kumar>	 I didn't try it on Android though
[12:13:39]  <kumar>	 maybe the same thing happens
[12:13:40]  <vladikoff>	 kumar, thanks
```

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/593

**Comment by shane-tomlinson** [comment]
Closing as dup.
