### ISSUE TITLE
Sign out messages should disappear on forms when user start logging in

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2211]
When the user enters characters into the username or password field, the messages should disappear.

![fxa-signed-out-successfully](https://cloud.githubusercontent.com/assets/68213/6672735/9258ac54-cbcb-11e4-8dfd-6c23fecdfe77.png)
![fxa-session-expired](https://cloud.githubusercontent.com/assets/68213/6672736/926bc492-cbcb-11e4-9016-cc4a96bd8c87.png)

**Comment by vladikoff** [comment]
@ryanfeeley What if the user clicks on the input and does not get a chance to read the error message? Should we proceed with this?

**Comment by ryanfeeley** [comment]
Safe with this assumption though?
> When the user enters characters into the username or password field, the messages should disappear.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - should they also be hidden for input-less forms if the user just clicks "submit"?

**Comment by ryanfeeley** [comment]
@shane-tomlinson What's an input-less form? The "Continue" form? Sure.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson What's an input-less form? The "Continue" form? Sure.

email opt-in Subscribe/unsubscribe

**Comment by ryanfeeley** [comment]
I'm just talking about the sign out messages on the login form.

**Comment by larissagaulia** [comment]
Hi! I fixed the issue by adding a keypress event in the [signIn](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/sign_in.js#L78) view.  Should I add a functional test in [here](https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/sign_in.js) ? (In this case I would have to sign in, sign out, type a letter into a field and make sure the div .succes is set to display:none, right? Or else, how should I test it? @ryanfeeley, @vladikoff thanks in advance!

**Comment by vladikoff** [comment]
@larissagaulia Send a pull request with what you have so it is easier to see the changes.

**Comment by larissagaulia** [comment]
Sure, I just thought it would be easier if I sent along the tests... =) Gonna send a PR in the morning :)

**Comment by vladikoff** [comment]
@larissagaulia more feedback:

>  I fixed the issue by adding a keypress event in the signIn view. 

Check out `FormView` that might be a better place for it.

> Should I add a functional test in here ? (In this case I would have to sign in, sign out, type a letter into a field and make sure the div .succes is set to display:none, right? Or else, how should I test it?

Functional tests can be difficult, so skip that for your pull request. Instead add / modify an existing a unit test. You can run the unit tests by going to http://127.0.0.1:3030/tests/index.html 

Take a look at `app/tests/spec/views/form.js` it has a lot of good stuff in there such as ` assert.equal(view.$('.error').text(), 'BOOM');` and other error testers.

Feel free to send a PR with what you have already though, will make it easier 

Hopefully this is helpful :)

**Comment by vladikoff** [comment]
@larissagaulia another useful thing, there is already "hiding" behaviour available for "Account Exists" warnings, maybe you can reuse the logic: 
![exists](https://cloud.githubusercontent.com/assets/128755/13910911/09d4fb7c-ef00-11e5-86d3-1cb5485f9906.gif)

**Comment by larissagaulia** [comment]
Thank you for the info! I'll take a look at the unit tests and submit it after your review, ok? I've put the events in sign_in coz it's the lowest on the hierarchy, I didn't think I should modify a broader View.

**Comment by vladikoff** [comment]
@larissagaulia excellent start! I added comments here: https://github.com/mozilla/fxa-content-server/pull/3615 :+1:
