### ISSUE TITLE
Reset password field labels should surface when user inputs

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2212]
Currently: 
![reset-password](https://cloud.githubusercontent.com/assets/68213/6672782/ea5cfb80-cbcb-11e4-90f5-733f79030b8e.png)

Should behave like the Change Password form where the placeholders ascend on input and turn in to field labels.

**Comment by shane-tomlinson** [comment]
@zaach - is this part of the settings 2.0 work?

**Comment by zaach** [comment]
Nope

**Comment by pdehaan** [comment]
Ref: #2848

**Comment by shane-tomlinson** [comment]
Added to #2848, closing.
