### ISSUE TITLE
weird ligature on change password page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2213]
@jrgm found this while we were debugging something else.

Go to [/app/scripts/templates/change_password.mustache:12](https://github.com/mozilla/fxa-content-server/blob/190fedde665a933aa1666d054cb35c7fc6c69c60/app/scripts/templates/change_password.mustache#L12):

```
{{#t}}Once you're ﬁnished, use your new password to sign in on all of your devices.{{/t}}
```

You'll see that the `ﬁ` is actually a ligature (char code 64257), and not `fi` (which is two characters). Not sure if this could cause any issue w/ localizers or anything (it looks like all the [-l10n client.po files](https://github.com/mozilla/fxa-content-server-l10n/blob/6a338c7f5909fe0fe578af892e7040b4fd46684a/locale/nl/LC_MESSAGES/client.po#L372) use the ligature in the key).

**Comment by pdehaan** [comment]
Here was the traditional @pdehaan half-assed code which I used to scape all the .po files for other potentially weird chars with higher ascii codes.

```js
'use strict';

var client = require('./i18n/schemas/client-schema.json').properties;
var server = require('./i18n/schemas/server-schema.json').properties;

var MAX_CHAR_CODE = 1000;

dumpKeys('client.json', highAsciiKeys(client));
dumpKeys('server.json', highAsciiKeys(server));

function filterKeys(maxCharCode) {
  return function (key) {
    return key.split('').some(function (char) {
      return (char.charCodeAt(0) > maxCharCode);
    });
  };
}

function getMaxCharCode(str) {
  return str.split('').reduce(function (prev, curr) {
    return Math.max(prev, curr.charCodeAt(0));
  }, -1);
}

function highAsciiKeys(keys) {
  return Object.keys(keys).filter(filterKeys(MAX_CHAR_CODE));
}

function dumpKeys(label, keys) {
  if (keys.length > 0) {
    console.log(label);
    keys.forEach(function (key) {
      var maxCode = getMaxCharCode(key);
      console.log('- "%s" [%d]\t => %s', String.fromCharCode(maxCode), maxCode, key);
    });
  }
}
```

And the output is as follows:
```
$ node schemalint.js
client.json
- "ﬁ" [64257]	 => Once you're ﬁnished, use your new password to sign in on all of your devices.
- "…" [8230]	 => Working…
```
**Note:** There wasn't anything seemingly interesting in the server.pot file with a high char code.

**Comment by johngruen** [comment]
@pdehaan can i just solve this by deleting the ligature and typing the letters `f` and `i` in that order? Seems weird that this is sitting open.

**Comment by pdehaan** [comment]
@johngruen Maybe probably. But since it's a string, it probably has some l10n-process impact as well (although no actual localized strings change, only the key).

We'll have to summon @shane-tomlinson and @zaach and see if this is worth fixing.
Or we can bring it up at tomorrow's bug triage meeting.

![](https://31.media.tumblr.com/72087759b0e2ed88f9f5084f4a06a0a1/tumblr_inline_nlc6cknzBz1r79k32.gif)

**Comment by zaach** [comment]
We can just search/replace to fix the .po files.

**Comment by shane-tomlinson** [comment]
moving to the l10n repo.

**Comment by shane-tomlinson** [comment]
Re-opening this issue after seeing the problem originates in our templates, not with the .po files. We should fix this.
