### ISSUE TITLE
Tests: Account locked tests are failing on TeamCity

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2215]
http://tests.dev.lcip.org:8111/viewLog.html?buildId=1386&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog

![image](https://cloud.githubusercontent.com/assets/128755/6720819/31c57f7e-cd9d-11e4-8c2a-fa06eb6a285c.png)

**Comment by shane-tomlinson** [comment]
@vladikoff - which version of the fxa-auth-server & fxa-auth-db-mem (unless it's using the MySQL drivers) are being run?

**Comment by vladikoff** [comment]
Checking https://latest.dev.lcip.org/auth/
says 
```
{"version":"1.33.0","commit":"a22dec3071aca7873167034521119daef37a4c1e"}
```
at this moment
