### ISSUE TITLE
Display avatar on change password and delete account pages?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2220]
Currently, I think we may only show the avatar on the [/settings](https://latest.dev.lcip.org/settings) page:

![manage_account](https://cloud.githubusercontent.com/assets/557895/6736825/780ceb84-ce24-11e4-9a9a-4b35e9a14e4e.png)

---

Not sure if it makes any sense to display the avatars on the other settings pages where I have to enter my account password, to give me a bit more of a [false?] sense of security so I know the page isn't an elaborate phishing ruse:

### [Change password](https://latest.dev.lcip.org/change_password)

![change_password](https://cloud.githubusercontent.com/assets/557895/6736863/b1ffa048-ce24-11e4-93d1-fa50cff55f18.png)

---

### [Delete account](https://latest.dev.lcip.org/delete_account)

![delete_account](https://cloud.githubusercontent.com/assets/557895/6736872/cd9090ec-ce24-11e4-9ada-d4e5dd4939db.png)

---

I think seeing my spirit animal, SpongeBob, would let me know "hey, this page is legit as hell, yo! I trust these cats with my top secret password."

**Comment by pdehaan** [comment]
/cc @ryanfeeley @johngruen 

If this is stupid, feel free to point and laugh, then immediately close the issue.

**Comment by ryanfeeley** [comment]
Great idea for Delete account! Add above email address. Not sure about Change password (which would require more work to keep user focused on task)

**Comment by vladikoff** [comment]
@zaach I don't think this is on track to be in Train 42, thoughts?

**Comment by zaach** [comment]
No, this is tied to #2336.

**Comment by zaach** [comment]
Since these will be sub-views on the settings page, this doesn't really make sense anymore. Closing.
