### ISSUE TITLE
Fx for iOS - Attempt to use camera to set avatar results in "Could not initialize camera"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2224]
STR:

1. Install Fx for iOS
1. Sign in to the browser from the preferences. Sign in with a mozilla.com address.
1. When signed in, click on name in Fx preferences to re-open FxA. The "Manage account" page should open.
1. Click on the "Change" link.
1. Select "Camera"
1. BOOM.

We should determine whether a camera upload is supported before showing the Camera option.

**Comment by shane-tomlinson** [comment]
cc @zaach, @ncalexan.

**Comment by ncalexan** [comment]
Hey, thanks for this testing!  My guess is that the embedding webview needs to implement a permission grant or similar, which we don't do.  If you can work around on your side, I'd appreciate it.

**Comment by vladikoff** [comment]
Relevant bug: https://github.com/mozilla/fxa-content-server/issues/2085

**Comment by zaach** [comment]
Are there any more details for the "BOOM" step? What's the error? Does it occur immediately?

**Comment by vladikoff** [comment]
@zaach
Yeap right away:
![](http://v14d.com/i/55232b3cbfb18.jpg)

I'll see if I can get you a debug / error log

**Comment by zaach** [comment]
I recall talking with @ryanfeeley about disabling the camera option for mobile OSes since they allow you to take a picture from the file picker option anyway.

**Comment by shane-tomlinson** [comment]
> I recall talking with @ryanfeeley about disabling the camera option for mobile OSes since they allow you to take a picture from the file picker option anyway.

Is it possible to detect if navigator.getUserMedia is available, and if not, hide the "camera" link?

**Comment by shane-tomlinson** [comment]
ref #2308

**Comment by ryanfeeley** [comment]
Good example of camera working on mobile (iOS anyway) http://how-old.net/

On desktop it just goes to file selection, but on iOS is asks "Take Photo" or "Photo Library" (or "Cancel").

On our desktop, we allow the camera too, unlike that site.

Is there direct access to the camera from mobile?
