### ISSUE TITLE
Fx for iOS - the "mozilla" link in the top-right corner does not open the expected page.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2226]
STR

1. Install Fx for iOS
1. Open FxA via the preferences.
1. Click the "mozilla" link in the top right corner.
1. Nothing happens.

**Comment by shane-tomlinson** [comment]
cc @ncalexan

**Comment by johngruen** [comment]
@shane-tomlinson what device are you using here? The Mozilla logo should not be visible at all on mobile displays. Are you on an iPad?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson what device are you using here? The Mozilla logo should not be visible at all on mobile displays. Are you on an iPad?

Yes. This is Fx for iOS too.

**Comment by johngruen** [comment]
@shane-tomlinson: we may need to set a mobile-native class or something to override? right now i'm not sure how else get rid of this thing without tenuous breakpoint acrobatics.

**Comment by vladikoff** [comment]
This is an iPad only issue. not present on iPod / iPhone

**Comment by shane-tomlinson** [comment]
ref #2225
