### ISSUE TITLE
Fx for iOS - Noticable Loading Jank

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2227]
Because `#stage` has some default padding before the content gets rendered there's a noticeable jump in the box. We should probably hide the whole `#main-content` thing until backbone has started and the first view is rendered.

**Comment by shane-tomlinson** [comment]
@johngruen - Are you loading via the preferences or from the URL bar? From preferences, I see a spinner until the content is loaded.

**Comment by johngruen** [comment]
@shane-tomlinson yeah, but there's still a jump as `#main-content` is being drawn.
