### ISSUE TITLE
Fx for iOS - Prevent viewport resize

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2228]
Zooming on mobile is bad vibes, we should lock the viewport. something like: 

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

**Comment by shane-tomlinson** [comment]
> we should lock the viewport.

This makes me cringe. Isn't that bad accessibility practice?

**Comment by johngruen** [comment]
@shane-tomlinson: not really no. presumably the UI should be designed to be large enough and with big enough hit targets where zooming is unnecessary. Further, iOS has global accessibility controls that allow for zooming should the user need it. 

Locked viewport sizing is a standard pattern for web-loaded auth on iOS.

**Comment by shane-tomlinson** [comment]
I'm uncomfortable completely disabling zoom.

I just tried the system's global zoom on my iPad and it's a pretty terrible experience. When I search [maximum-scale accessibility](https://www.google.co.uk/#q=maximum-scale+accessibility) in Google, all the top hits are "NOOOOOO!"

The BBC recommends setting the maximum-scale to [no lower than 2](http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/design/zoom).

**Comment by vladikoff** [comment]
> Locked viewport sizing is a standard pattern for web-loaded auth on iOS.

Chrome iOS allows me to zoom in on the sign in form a bit.

**Comment by vladikoff** [comment]
To proceed with this:

@johngruen are you okay if we find a way to give a bit of zoom? @ryanfeeley thoughts?

**Comment by ryanfeeley** [comment]
I have no thoughts, just questions. Why disable? Because focusing between inputs changes the view size?

**Comment by vladikoff** [comment]
Closing this for now unless we really want to add this

**Comment by shane-tomlinson** [comment]
Ref #6083

**Comment by devinreams** [comment]
Continued discussion and possible "fix" here: https://bugzilla.mozilla.org/show_bug.cgi?id=1467525
