### ISSUE TITLE
Fx for iOS - Relative sizes of page header and subheaders don't feel right

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2229]
The header typography looks off to me. I'd like the subheader to be smaller and higher weight on mobile screens.

@ryanfeeley bearing in mind that the current state looks fine on desktop...screenshots for my proposed change on smaller breakpoints below:

Current: 
![screen shot 2015-03-24 at 10 29 34 am](https://cloud.githubusercontent.com/assets/3323249/6803880/e63e3d48-d210-11e4-841b-1ca57c7bcfda.png)

Proposed:
![screen shot 2015-03-24 at 10 29 24 am](https://cloud.githubusercontent.com/assets/3323249/6803898/04a08336-d211-11e4-81fb-b9c5c7971af2.png)

**Comment by ryanfeeley** [comment]
I agree. It's not quite right. Maybe splitting the sentence is also a bad idea because it bothered me less before when "Continue" was the first word of the second line. Is that a new weight that will have to be loaded?

**Comment by johngruen** [comment]
@ryanfeeley nah, we use it on the legal pages

**Comment by ryanfeeley** [comment]
Split sentence, different font, different weight... Still feels off. @bryanbell care to chime in?

**Comment by pdehaan** [comment]
Re: legal page UI,

![firefox_accounts__terms_of_service](https://cloud.githubusercontent.com/assets/557895/6829988/313ea45e-d2d4-11e4-8014-70ea875390d2.png)
via https://accounts.firefox.com/legal/terms

**Comment by shane-tomlinson** [comment]
@johngruen - are you still doing this one?

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.
