### ISSUE TITLE
Consider showing a better error message when log in via FxA times out

### ISSUE THREAD

**Issue by krupa** [mozilla/fxa-content-server#2233]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1145619 for more details.

Currently, when there is a timeout, FxA shows the error message "Invalid Assertion" which isn't very useful. 

(long-ish) screencast: http://screencast.com/t/b4mMmyySZXtx

**Comment by shane-tomlinson** [comment]
@krupa - when I load that link, it loads a static image. Is that expected?

**Comment by shane-tomlinson** [comment]
We should probably show unexpected error here.

**Comment by shane-tomlinson** [comment]
@krupa, what are the concrete STRs we can use to reproduce the problem here? Is it just an XHR timeout?

**Comment by vladikoff** [comment]
from mtg: Checked datadog for this error and did not see any occurrences of this, will reopen if becomes an issue again
