### ISSUE TITLE
sessionTokenContext is not used by the browser anywhere - should it be passed in the `login` data?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2238]
STR
1. Search https://dxr.mozilla.org/mozilla-central/search?q=sessionTokenContext&case=true
1. Look at https://github.com/mozilla/fxa-content-server/blob/f2a2d9cb5c2ecdeb70576bbab69f37d27b88b77e/app/scripts/models/auth_brokers/fx-desktop.js#L111

@ncalexan - do you depend on `sessionTokenContext`?

@zaach - Should we remove that field from the sent data?

**Comment by shane-tomlinson** [comment]
@zaach - Related - in [models/account.js->isFromSync](https://github.com/mozilla/fxa-content-server/blob/ceead38da0c239a8817f822b17f58d4910f35b92/app/scripts/models/account.js#L104), we determine whether a sessionToken is from Sync if the context query parameter is `fx_desktop_v1`. The `context` field is fetched from the relier. For the new `/firstrun` page, @ckarlof and I discussed setting `service=sync&context=iframe`. Obviously `iframe!==fx_desktop_v1`, and lots of expectations are broken.

I am wondering if in the fx-desktop relier I should hard code the `context` to `fx_desktop_v1`, or whether `isFromSync` could rely on the relier's `service` field instead, which in both of these cases will be `sync`.

**Comment by shane-tomlinson** [comment]
@ncalexan - it doesn't look like you are using `sessionTokenContext` either - https://github.com/mozilla/firefox-ios/blob/66c8d746f0c8ca0f3c03122663205276b8ed85ab/FxAClient/FxAClient.swift#L56

**Comment by shane-tomlinson** [comment]
Or, more recently - https://github.com/mozilla/firefox-ios/blob/8f2838769b07b8cc115ee90c0ba853bc70cb87b9/Account/FxAClient10.swift#L156

**Comment by ckarlof** [comment]
I think it's simply an accident that it's being passed up. `sessionTokenContext` is used entirely in the Web side, IIUC.

**Comment by vladikoff** [comment]
Let's remove it ! sessionTokenContext

**Comment by shane-tomlinson** [comment]
ref #2658

**Comment by vladikoff** [comment]
Fixed.
