### ISSUE TITLE
Eliminate lint rule for 'Extra comma. (it breaks older versions of IE)'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2245]
I never liked this rule, but as long as it was preventing problems with IE8 and below, it had value. But if
IE8 is dead to us, should we remove this lint rule? (I think I heard once that trailing commas are a preferred thing to reduce diff churn in some other mozilla code base).

**Comment by pdehaan** [comment]
JSHint rule explanation: https://jslinterrors.com/extra-comma

---

> _**What browsers support object literals with trailing commas?**
> Most browsers support object literals with trailing commas. You are only out of luck in Internet Explorer 8 and earlier ([compatibility table](http://rauschma.github.io/js-feature-matrix/))._
> 
> &mdash; via http://www.2ality.com/2013/07/trailing-commas.html
