### ISSUE TITLE
browsehappy boilerplate is repeated in 3 places, we should maybe use a partial

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2257]
Searching for ["browsehappy"](https://github.com/mozilla/fxa-content-server/search?l=html&q=browsehappy&utf8=%E2%9C%93) returns 3 separate results:

- server/templates/pages/src/privacy.html
- server/templates/pages/src/terms.html 
- server/templates/pages/src/index.html 

Not sure if it makes sense to convert that to a partial and include it in 3 places to reduce code duplication (plus makes it easier to tweak the message or IE support).

**Comment by vladikoff** [comment]
We should make it a partial

**Comment by vladikoff** [comment]
Closing until needed
