### ISSUE TITLE
Add functional tests to ensure static error pages are translated in production environment

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2258]
Follow on from #2252 and #2256. It was found that the static error pages are not translated in the production environment. We should add some tests to ensure this does not regress.

**Comment by vladikoff** [comment]
from mtg: we can use a query param to force some locale and test to make sure the page is translated (static pages such as 404, 400.html and make sure the translation kicks in.)

good first bug

**Comment by shane-tomlinson** [comment]
Are we really going to do this? No. Closing.
