### ISSUE TITLE
COPPA day picker renders incorrectly on hover

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2261]
The day select picker renders incorrectly on hover, but only if there's no month selected.

![coppadate](https://cloud.githubusercontent.com/assets/3903/6905187/205ffc0e-d6db-11e4-8efe-72a7ab0ed66e.gif)

**Comment by shane-tomlinson** [comment]
I do not see this on the current master, has @johngruen fixed this?

**Comment by zaach** [comment]
Looks like it is indeed fixed on master.
