### ISSUE TITLE
Update AUTHORS file with latest contributors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2272]
Noticed that we're missing about 4 names from the AUTHORS file.
It's a pretty simple `npm run contributors`, but it may be nice if we could automate it a bit more.

I tried using [superlukas/**grunt-git-contributors**](https://github.com/superlukas/grunt-git-contributors) but it outputs a file with email addresses, which can lead to lots of duplication of names.
Another option may be to use something like [sindresorhus/**grunt-shell**](https://github.com/sindresorhus/grunt-shell) to execute our `npm run contributors` script, so we could possibly tie it into our bump/version task flow; see [grunttasks/version.js](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/version.js) and [grunttasks/bump.js](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/bump.js).

**Comment by vladikoff** [comment]
I think we closed a bug like this earlier because we just do not have that many contributors ( so it was not worth automating)

**Comment by pdehaan** [comment]
Hhmm, probably #708.
I quickly tried figuring out how we could do this w/ **grunt-shell**, but I don't think it was liking all the pipes and redirects in the `git shortlog -s | cut -c8- | sort -f > AUTHORS` command.

But still, omitting 4/37 names (~11%) from our contributor list seems a bit "sub-optimal".

**Comment by pdehaan** [comment]
FWIW, we need to regenerate the [AUTHORS](https://github.com/mozilla/fxa-content-server/blob/master/AUTHORS) file again now that @zaach merged #2264
