### ISSUE TITLE
IE8/IE9 - with JS disabled, both "browse happy" and "Firefox Accounts requires JavaScript" are displayed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2279]
Found while testing #2277 

![screen shot 2015-04-06 at 11 11 28](https://cloud.githubusercontent.com/assets/848085/7003161/f4c39e0c-dc4d-11e4-84d3-268dbf170aaf.png)

**Comment by johngruen** [comment]
@shane-tomlinson  this is intentional to stress just how broken their browser is :)

**Comment by johngruen** [comment]
I'll fix this next week

**Comment by vladikoff** [comment]
from irc:
`[15:46:35]  <jgruen>	Browse happy is better`

So we are going to show the "update the browser" message
