### ISSUE TITLE
The default avatar should not show before an avatar loads

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2280]
On /settings the default avatar appears briefly before my avatar loads.

Preferred behaviour:

1. No delay, show immediately
1. If there will be a delay, show nothing in the interim

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you check latest? This should have been fixed in https://github.com/mozilla/fxa-content-server/pull/2106

**Comment by ryanfeeley** [comment]
You’re right, it works!
