### ISSUE TITLE
Add various favicons for the FxA website

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2281]
Pretty handy guide:
https://github.com/audreyr/favicon-cheat-sheet

Generate from large PNG here:
https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/

**Comment by pdehaan** [comment]
Related: #2062; _"404s on /apple-touch-icon-*.png"_

**Comment by vladikoff** [comment]
dup https://github.com/mozilla/fxa-content-server/issues/2062
