### ISSUE TITLE
server/* not being linted by JSHint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2283]
Re: https://github.com/mozilla/fxa-content-server/pull/2278#discussion_r27801398

@jrgm and I were discussing this earlier, but It looks like our current Grunt JSHint task ([./grunttasks/jshint.js](https://github.com/mozilla/fxa-content-server/blob/81dc9d39734b29f9c6b3149ae222fbf5e09b054c/grunttasks/jshint.js)) isn't linting anything in the server/** directory.

```js
    grunt: [
      'Gruntfile.js',
      'grunttasks/*.js'
    ],
    app: {
      src: [
        '<%= yeoman.app %>/**/*.js',
        '!<%= yeoman.app %>/bower_components/**',
        '!<%= yeoman.app %>/scripts/vendor/**'
      ]
    },
    tests: [
      '<%= yeoman.tests %>/**/*.js'
    ]
```

I did a quick check and it looks like there are 70 "problems" in the server/* directory if I add it to the current default JSHint rules, although I think a large portion of those are because the Convict config file uses the reserved word `default`, which JSHint doesn't like.

Not sure if we care or excluded that directory on purpose, but thought it was worth pointing out in a bug for discussion [or to collect whimsical GIFs].

**Comment by pdehaan** [comment]
Curious: https://github.com/mozilla/fxa-content-server/pull/504

**Comment by pdehaan** [comment]
Hey, maybe _I_ broke this!
See: https://github.com/mozilla/fxa-content-server/pull/510

Not sure why I'd be that stupid, except for the fact that I am that stupid...

**Comment by shane-tomlinson** [comment]
> Not sure why I'd be that stupid, except for the fact that I am that stupid...

I say this to myself on a weekly basis.

**Comment by pdehaan** [comment]
> > Not sure why I'd be that stupid, except for the fact that I am that stupid...

> I say this to myself on a weekly basis.

You say how stupid I am too? :sob:

**Comment by shane-tomlinson** [comment]
> > > Not sure why I'd be that stupid, except for the fact that I am that stupid...

> > I say this to myself on a weekly basis.

> You say how stupid I am too? :sob:

:footprints: meet :open_mouth: - I should have thought about phrasing. s/to/about
