### ISSUE TITLE
Measure how users bounce when typing into password field on registration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2287]
We want users to authenticate effortlessly, entering their credentials without issue so on registration, so we should measure which users bounce when they start typing in to the password field and how often.

**Comment by shane-tomlinson** [comment]
This is very similar to #2298.

**Comment by vladikoff** [comment]
Same as https://github.com/mozilla/fxa-content-server/issues/2290#issuecomment-157118540
