### ISSUE TITLE
Measure how well users remember their passwords

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2288]
Because we want new users to be more able to remember their password, we should measure:
* % of first signin after signup with at least one "incorrect password" error.
* % of signin page visits with at least one "incorrect password".
* % of first signin after signup that results in a password reset.
* % of signin page visits that result in a password reset.

**Comment by vladikoff** [comment]
We now got some new graphs ready and issues open for password reset / change.
