### ISSUE TITLE
Measure how well users are able to register

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2289]
Because we want registering users who view their password to make fewer mistakes when signing up, we want to measure:
* % of "incorrect password" errors on the first signin after signup.
* % of successful signins with one or more "incorrect password".
* % of users who perform a password reset on the first signin after signup.
* % of visits to /signin or /oauth/signin that result in a password reset.
* % of users that toggle the "show password" button.
* % of users that erase at least once character in the password.

**Comment by vladikoff** [comment]
We have a lot of this info now, we can create a new issue if we need something detailed...
