### ISSUE TITLE
Measure how many mistakes users make when signing in

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2290]
Because we want users who see their password on signin to make fewer mistakes, we should measure:
* % of successful signins with at least one "incorrect password".
* % of users that toggle the "show password" button.
* % of users that erase at least once character in the password.
* Median number of attempts before correct password is entered.
* Median number of attempts before password reset is initiated.

**Comment by vladikoff** [comment]
Closing this for now because not priority, we can do more password experimentation using the password bloom filter
