### ISSUE TITLE
Measure when users delete the password they have entered on registration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2291]
Because we want users to authenticate effortlessly, entering their credentials without issue, we should measure:
* On registration, the rate users delete the password they have entered.

**Comment by shane-tomlinson** [comment]
Should we measure when a user deletes any character?

**Comment by ryanfeeley** [comment]
Great idea! Yes!

**Comment by vladikoff** [comment]
@ryanfeeley sorry could you explain this a bit? I enter password then I delete it? Why? 

Do we see if users change their mind or something?

**Comment by ryanfeeley** [comment]
Not worth the effort nor really meaningful. Seemed like a good idea in April.
