### ISSUE TITLE
Measure users showing and hiding the password field on the login form

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2292]
Because we want users to authenticate effortlessly, entering their credentials without issue, we should measure:
* On login, rate users toggle the show password control from hidden to shown, and shown to hidden

**Comment by ryanfeeley** [comment]
We have these events, but need to tag the current experience as hidden by default (which will change to visible for A/B testing):
* fxa.content.change_password.password.hidden
* fxa.content.change_password.password.visible
* fxa.content.oauth.signin.password.hidden
* fxa.content.oauth.signin.password.visible
* fxa.content.signin.password.hidden
* fxa.content.signin.password.visible

**Comment by vladikoff** [comment]
> Measure users showing and hiding the password field on the login form

We got these events now in DataDog
