### ISSUE TITLE
Measure how long users stay focused on the login form’s password field

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2293]
Because we want users to authenticate effortlessly, entering their credentials without issue, we should measure:
* On login, how long users remain focused on the password field

**Comment by shane-tomlinson** [comment]
Ah, nice one.

**Comment by vladikoff** [comment]
Will need to add metrics timing in the future pr.

**Comment by ryanfeeley** [comment]
Done in the dog.
