### ISSUE TITLE
Measure when users add or modify their profile picture or display name

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2294]
Because we want those who manage their passwords more be more engaged in other aspects of the browser, we should measure:
* Which users add or modify their profile picture and display name and how often

**Comment by ryanfeeley** [comment]
Suggested event names:
* fxa.content.settings.avatar.new.upload
* fxa.content.settings.avatar.change.upload
* fxa.content.settings.avatar.new.camera
* fxa.content.settings.avatar.change.camera
* fxa.content.settings.avatar.new.gravatar
* fxa.content.settings.avatar.change.gravatar

**Comment by vladikoff** [comment]
Will need a pr for this. @shane-tomlinson let me know what you think of these even names.

**Comment by vladikoff** [comment]
Working on this, does it make sense to set action:
```
fxa.content.settings.avatar.change.action.new.upload
```

**Comment by ryanfeeley** [comment]
Good idea. So one tag for when they start a process and another when it's successful?

**Comment by vladikoff** [comment]
@ryanfeeley we should move the `or display name` part to another bug.
