### ISSUE TITLE
Measure when users sign out

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2295]
Because we don’t want users to sign out more, we should measure how many users click sign out and how often.

**Comment by vladikoff** [comment]
Needs a pr to track sign outs
https://github.com/mozilla/fxa-content-server/blob/3562e8f5c788b0b5661fd99965dedd8fe5832f40/app/scripts/views/settings.js

**Comment by vladikoff** [comment]
Adding:

fxa.content.settings.signout.submit
fxa.content.settings.signout.success
fxa.content.settings.signout.error  -> see See issue #616

**Comment by vladikoff** [comment]
```
{
  "viz": "timeseries",
  "requests": [
    {
      "q": "sum:fxa.content.settings.signout.submit{*}.as_count()",
      "type": "bars"
    },
    {
      "q": "sum:fxa.content.settings.signout.success{*}.as_count()",
      "type": "bars"
    },
    {
      "q": "sum:fxa.content.settings.signout.error{*}.as_count()",
      "type": "bars"
    }
  ],
  "events": []
}
```
