### ISSUE TITLE
relax es3/trailing commas in the app subdirectory?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2296]
In #2276, @riadhchtara removed the `es3: true` declaration for the top level directory, meaning our server code is not limited to using es3 features and can use trailing commas.

I asked him to *not* remove the equivalent line in the `app/.jshintrc` file because we may need to support IE9 for MDN. Here is a [link to an MSDN article](http://blogs.msdn.com/b/ie/archive/2010/06/25/enhanced-scripting-in-ie9-ecmascript-5-support-and-more.aspx) about ES5 support in IE9. Really, it looks like we *should* be good.

I am copying over context from comments others have made.

-------------------------------

@jrgm in https://github.com/mozilla/fxa-content-server/pull/2276#issuecomment-90206359
> Man. It sucks that this 'trailing comma' is lumped in with other es3 stuff. The other way to do it is keep 'es3', but set "-W070": true in .jshintrv, which, intuitively, will quiet this warning.

@pdehaan in https://github.com/mozilla/fxa-content-server/pull/2276#issuecomment-90218138

> We could also try and manage the trailing commas in jscs:

>   http://catatron.com/node-jscs/rules/require-trailing-comma/
>    http://catatron.com/node-jscs/rules/disallow-trailing-comma/

> Or, we could replace JSHint with ESLint (which is pretty cool, and more actively maintained).

**Comment by vladikoff** [comment]
No longer needed, removing jshint soon. https://github.com/mozilla/fxa-content-server/issues/2582
