### ISSUE TITLE
Measure when users delete their account

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2297]
Because we don't want users deleting their account more often, we should measure how many users delete their account.

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/7574041/7835e89c-f7f8-11e4-93c3-40f578a27565.png)

**Comment by ryanfeeley** [comment]
Available shortly in Datadog

**Comment by vladikoff** [comment]
Actually going to reopen this.
We have a screen event, but we don't track the delete submit:
https://github.com/mozilla/fxa-content-server/blob/2cf874dab99c0c262e81e1edeefd4e975c8aac48/app/scripts/views/delete_account.js#L49
We should track both delete view and submit.

**Comment by vladikoff** [comment]
Existing: `fxa.content.screen.delete_account`
Needed: `fxa.content.delete_account` - submit action.

**Comment by vladikoff** [comment]
Fixes now, dashboard code:
```
{
  "viz": "timeseries",
  "requests": [
    {
      "q": "sum:fxa.content.screen.delete_account{*}.as_count()",
      "type": "bars"
    },
    {
      "q": "sum:fxa.content.delete_account.deleted{*}.as_count()",
      "type": "bars"
    }
  ],
  "events": []
}
```
