### ISSUE TITLE
Measure bounce rates on account authentication pages

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2298]
Because we want users to be comfortable with visible passwords by default we should measure: 
* Bounce rate on /signin
* Bounce rate on /oauth/signin
* Bounce rate on /signup
* Bounce rate on /oauth/signup.
* % of users who start to type their password then bounce.

**Comment by shane-tomlinson** [comment]
For the more clueless of us, how should we define a bounce?  A user that visits, e.g., the /signin page and then leaves FxA, or a user that visits /signin, then browses to any other page, even within FxA?  I can imagine several possibilities.

**Comment by ryanfeeley** [comment]
Pretty sure it means leaving the site (accounts.firefox.com) entirely. https://support.google.com/analytics/answer/1009409?hl=en

**Comment by vladikoff** [comment]
In terms of DataDog metrics we need to add:

`fxa.content.signup.bounce`
`fxa.content.signin.bounce`
`fxa.content.oauth.sign(in|up).bounce`
maybe for all views: something like `fxa.content.[VIEW].bounce`
To track this we measure if the user go to the view but then closed the window or navigated away.
Once they interact with: **inputs, links, buttons** then it is no longer a bounce.

**Comment by vladikoff** [comment]
Needs Pr.

**Comment by ryanfeeley** [comment]
Got it in the dog.
