### ISSUE TITLE
Measure page reloads by user

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2299]
Because we want to decrease the frustration users often feel, we should measure page reloads.

According to @shane-tomlinson:
* There are no native DOM events AFAIK, but we may be able to do something like, in one page load, save the current URL to sessionStorage. If on the next page load that URL is there and the same, then we can be reasonably certain the user re-loaded the page

**Comment by vladikoff** [comment]
We need a pull request to add this

**Comment by eoger** [comment]
I discussed this with @zaach, this is not an easy problem and there's no obvious solution.

What happens if isMetricsCollectionEnabled() (random result) in app-start.js returns true the first time a page is loaded, then it returns false the next time? How do we log the refresh event?

**Comment by vladikoff** [comment]
> returns true the first time a page is loaded, then it returns false the next time

2 things here - 

1. we are aiming to turn on metrics for 100% of users: https://github.com/mozilla/fxa-content-server/issues/2422
2. even if it is not 100%, store the information if the user got lucky with `isMetricsCollectionEnabled`, (via localstorage or whatever)

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-content-server/pull/2455
