### ISSUE TITLE
visiting /settings?setting=avatar&uid=... does not redirect

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2301]
In #2250 we added a new route but didn't test that it works when additional parameters are specified.

STR:
1. While logged in, visit settings with query params, e.g. http://127.0.0.1:3030/settings?setting=avatar&email=zack.carter%40gmail.com&uid=9fa3cfecbe6e4cbaa05074e43da5b080

Expected:

Get redirected to the avatar change page.

Actual:

Stays on the settings page.

**Comment by vladikoff** [comment]
Would updating `'settings(/)?setting=avatar':` to 'settings(/)?setting=avatar*':` fix this?

**Comment by shane-tomlinson** [comment]
> Would updating 'settings(/)?setting=avatar': to 'settings(/)?setting=avatar*': fix this?

That depends on `setting=avatar` being the first parameter, which is pretty susceptible to human error. @zaach - perhaps the first scheme [you proposed](https://github.com/mozilla/fxa-content-server/commit/344f9c70ebd7fc7bae9eb9ab31c8682e42c64b47#diff-fb9537d2bf95cbbd0025dda8d398cd6dR30) is a better approach?

**Comment by vladikoff** [comment]
Here is an example of matching the whole query string (that we might still be able to use): http://jsfiddle.net/h5j2w4L8/ 
Sorry I was not aware that additional params would be present, i.e it was only a quick redirect.

**Comment by zaach** [comment]
@vladikoff No worries!

The benefit of using the router was that we didn't need extra logic but it looks like that's unavoidable. I may go with the previous approach so we can reuse the query parsing that happens in the relier library.
