### ISSUE TITLE
Specify a touch-friendly checkbox design

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2302]
In anticipation of moving our "Choose what to sync" to the web, our checkbox design should be touch-friendly. Do we need to change the kind of control and the positioning (on the right Android?)

https://www.dropbox.com/s/qjvbxvmg766ndfu/Choose%20What%20to%20Sync.pdf?dl=0

Apple seems to just copy iOS on iCloud.com (desktop)
![checkbox](https://cloud.githubusercontent.com/assets/68213/7047023/dd1f9e3c-ddd7-11e4-9b89-8496969c3dfd.gif)

Other inspiration:
http://tympanus.net/codrops/tag/button/

Android:
http://developer.android.com/guide/topics/ui/controls.html

**Comment by vladikoff** [comment]
Also http://www.google.com/design/spec/components/switches.html#switches-switch

**Comment by ryanfeeley** [comment]
Would want the style to eventually support AJAX checkbox (showing progress)
<img width="721" alt="animated-checkboxes" src="https://cloud.githubusercontent.com/assets/68213/8705250/4d9cf676-2add-11e5-9ed6-90a1abbf0259.png">

**Comment by ryanfeeley** [comment]
how's this for an off checkbox?

.checkbox {
    height: 20px;
    width: 20px;
    border: 2px solid rgb(0, 149, 221);
    margin-right: 10px;
}

**Comment by vladikoff** [comment]
Some WIP is based on https://github.com/google/material-design-lite/tree/master/src/checkbox that includes an SVG based checkbox with a JS component that we can use for later to show progress.

**Comment by vladikoff** [comment]
@ryanfeeley here's a work in progress 

After | Before

![image](https://cloud.githubusercontent.com/assets/128755/10155238/94d98d4e-6640-11e5-93a5-2ce4b7d56952.png)

**Comment by ryanfeeley** [comment]
Hi Vlad, this was just for the design part, which would include animation. I originally assigned @bryanbell but for some reason @johngruen unassigned him?

**Comment by johngruen** [comment]
@ryanfeeley I unassigned him b/c i thought we were supposed to unassign things that had been assigned and untouched for a really long time?

**Comment by vladikoff** [comment]
> which would include animation

What kind of animation?

**Comment by ryanfeeley** [comment]
@johngruen What if the world really worked like that? I think Bryan and Horlander are actually working on this but haven't interacted with GitHub over it. I'll get on them.

@vladikoff Semi-specified above: https://github.com/mozilla/fxa-content-server/issues/2302#issuecomment-121689371

I should probably specify what happens when the action was not successful.

**Comment by johngruen** [comment]
@ryanfeeley: the world of fxa does work like that
