### ISSUE TITLE
Move “choose what to sync” options to the content server

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2303]
Currently when the user selects “choose what to sync” on the web, they are not presented with the sync datatype selections until after email verification. We should do like Fennec and ask them on the next step if they have chosen to choose what to sync.

![choose what to sync](https://cloud.githubusercontent.com/assets/68213/7048045/640b5052-ddde-11e4-8598-8617e307b435.png)

Is there a way we can do this that would not require desktop client change coordination?

**Comment by ryanfeeley** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1152356

**Comment by shane-tomlinson** [comment]
> Is there a way we can do this that would not require desktop client change coordination?

I think this requires a Desktop change.

**Comment by ryanfeeley** [comment]
What about triggering the client UI exactly the way Fennec does instead of a web UI?

**Comment by vladikoff** [comment]
from mtg:
To track that the new design is successful we should see an increase of signins (new devices added)

**Comment by vladikoff** [comment]
Closing this in favour of  https://github.com/mozilla/fxa-content-server/issues/3080
