### ISSUE TITLE
IE8 - tos/pp agreements render as plain text

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2304]
STR

1. Load up IE8
1. Visit https://accounts.firefox.com/legal/terms

![screen shot 2015-04-08 at 19 05 55](https://cloud.githubusercontent.com/assets/848085/7051765/7c7cb31c-de22-11e4-876f-2b57f1c4bcf7.png)

**Comment by pdehaan** [comment]
Why doesnt BrowseHappy display here if you're using IE8?

**Comment by vladikoff** [comment]
> Why doesnt BrowseHappy display here if you're using IE8?

Because IE8 probably fetches the partial instead of the whole page:
https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/get-terms-privacy.js#L12

**Comment by shane-tomlinson** [comment]
> Because IE8 probably fetches the partial instead of the whole page:
https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/get-terms-privacy.js#L12

Yup. It's pretty easy to fix, reverse the `text/partial` and `text/html` blocks.

**Comment by shane-tomlinson** [comment]
From the [express res.format documentation](http://expressjs.com/api.html#res.format):

> Performs content-negotiation on the Accept HTTP header on the request object, when present. It uses req.accepts() to select a handler for the request, based on the acceptable types ordered by their quality values. If the header is not specified, the first callback is invoked.

**Comment by shane-tomlinson** [comment]
IE8's request headers (Accept header set to */*):

```
GET /legal/terms HTTP/1.1
Accept: */*
Accept-Language: en-US
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Accept-Encoding: gzip, deflate
If-None-Match: W/"Zr6QUZy+gJ3OKdi/lpdTgw=="
Host: 192.168.1.91:3030
Connection: Keep-Alive
Pragma: no-cache
```

Firefox's for comparison:

```
User-Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0
Pragma:	no-cache
Host:	localhost:3030
DNT:	1
Connection:	keep-alive
Cache-Control:	no-cache
Accept-Language:	en,es;q=0.7,de;q=0.3
Accept-Encoding:	gzip, deflate
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
