### ISSUE TITLE
"no-js" class is not used anywhere

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2306]
The "no-js" class is not used in either JavaScript or CSS. We should remove it from the HTML and the test that removes it if JS in enabled in [env-test.js](https://github.com/mozilla/fxa-content-server/blob/a475d3a95e09112889120ce05cc855ba54151c1f/app/scripts/vendor/env-test.js#L20).

Ref #2279

**Comment by riadhchtara** [comment]
I want to work on this

**Comment by riadhchtara** [comment]
@shane-tomlinson : Could you please have a look?

**Comment by riadhchtara** [comment]
thanks :-)
