### ISSUE TITLE
We have both `Avatar` and `ProfileImage` - should the names be unified?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2307]
From IRC:

> [21:18:06]  <stomlinson>	zaach: one thing I noticed, is there a conceptual difference between functions that use `ProfileImage` and those that use `Avatar`?
> [21:18:32]  <zaach>	stomlinson: the profile server uses Avatar, so functions that mirror the api use that name
> [21:19:25]  <stomlinson>	zaach: potential source of confusion?
> [21:21:02]  <zaach>	hasn't been so far afaict
> [21:21:17]  <zaach>	profile image is what we use for user facing strings
> [21:21:26]  <zaach>	avatar was sort of the internal name
> [21:21:51]  <zaach>	but going forward i'd like to go with profile image

**Comment by shane-tomlinson** [comment]
ref #2136

**Comment by zaach** [comment]
Closing for now
