### ISSUE TITLE
Fx for iOS - Avatars "Take Photo" closes the content server window

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2308]
Avatar upload with the "Take Photo" option crashes the content server embed

Should this be filed on bugzilla?

Tested on build `1.0 (7)`

![uploadfxa](https://cloud.githubusercontent.com/assets/128755/7055028/8fc5a53c-de0e-11e4-9ba2-32ea3426ff9b.gif)

**Comment by vladikoff** [comment]
cc @ncalexan

**Comment by shane-tomlinson** [comment]
According to [1], iOS 8 is broken with file uploads.

> File uploads are broken!! Every file upload is not working, you can select a file or take a picture and after that JavaScript will not get any data, as well as the server on a POST upload through HTML or XMLHttpRequest upload. The problem doesn’t seem to apply for home screen webapps.

[1] - http://www.mobilexweb.com/blog/safari-ios8-iphone6-web-developers-designers

**Comment by vladikoff** [comment]
The file upload issue for Safari is fixed in 8.0.2. However this bug / fix does not apply to FxiOS

**Comment by pdehaan** [comment]
If this still crashes w/ latest build, we should consider hiding the button on iOS since crashing is a "poor user experience".

**Comment by vladikoff** [comment]
@zaach we got https://github.com/mozilla/fxa-content-server/blob/660136152e3521aee937fad647f0508352bbd146/app/scripts/lib/environment.js#L93
to detect fxios, how much avatar should we hide on fxios?

**Comment by zaach** [comment]
We should hide the upload photo option.

**Comment by vladikoff** [comment]
I tried the latest build of FxiOS and I see no way of getting to the avatar section anymore.


@st3fan @ncalexan let us know if that is a bug or not. Should users be able to get to FxA settings ( + change their avatar) from Firefox iOS? 

![iosfx](https://cloud.githubusercontent.com/assets/128755/9390786/3cacd216-4741-11e5-9649-1dd4dc98efe1.gif)

**Comment by ncalexan** [comment]
On Thu, Aug 20, 2015 at 10:42 AM, Vlad Filippov <notifications@github.com>
wrote:

> I tried the latest build of FxiOS and I see no way of getting to the
> avatar section anymore.
>
> @st3fan <https://github.com/st3fan> @ncalexan
> <https://github.com/ncalexan> let us know if that is a bug or not. Should
> users be able to get to FxA settings ( + change their avatar) from Firefox
> iOS?
>

iOS does not yet link to /settings, since we don't listen for interesting
messages (like profile changes, or password changes).

**Comment by vladikoff** [comment]
Okay thanks Nick,

@zaach , I'm removing "blocker" from this, we can also close this because at this time this flow is not available at all.

**Comment by zaach** [comment]
:+1:
