### ISSUE TITLE
Improve our account verification email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2315]
I think we can do better account verification email than this:

![fxa-email](https://cloud.githubusercontent.com/assets/68213/7119305/ae7b4e60-e1d2-11e4-8e15-14f0169bb05a.png)

Our conversion numbers are lower than I think they should be.

We should also consider sending this email when accounts go unverified (so copy should reflect this).

How to proceed?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you move this issue to the [fxa-auth-mailer](https://github.com/mozilla/fxa-auth-mailer/) repo?

**Comment by pdehaan** [comment]
Filed as https://github.com/mozilla/fxa-auth-mailer/issues/35. Closing.
