### ISSUE TITLE
Update to latest grunt-contrib-imagemin?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2320]
Currently I think we're using an old forked version of [vladikoff/**grunt-contrib-imagemin@0.9.2**](https://github.com/vladikoff/grunt-contrib-imagemin/tree/keepOldImage), but we seem to have intermittent install issues w/ imagemin+npm.

Not sure how difficult it would be to switch from our forked version back to mainline, or not... But looks like [gruntjs/**grunt-contrib-imagemin@0.9.3**](https://github.com/gruntjs/grunt-contrib-imagemin/) ([CHANGELOG](https://github.com/gruntjs/grunt-contrib-imagemin/blob/master/CHANGELOG)) removed **pgquant** which may cause us fewer headaches.

**Comment by vladikoff** [comment]
good idea, we have a custom version (for reasons...) but I can rebase it

**Comment by vladikoff** [comment]
currently pngquant still installs because imagemin was not updated.
filed https://github.com/gruntjs/grunt-contrib-imagemin/issues/301

Going to wait until that is updated to update our fork.

**Comment by vladikoff** [comment]
Got rid of imagemin, woo
