### ISSUE TITLE
Legal links are touching in Hebrew settings page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2327]
Found in https://accounts.stage.mozaws.net/ver.json (commit 24167ba551537ff5dc086a7299d3da3b4b8fda2d)

```json
{
  "version": "0.34.1",
  "commit":"24167ba551537ff5dc086a7299d3da3b4b8fda2d",
  "l10n":"bdc9dc0c61",
  "tosPp":"61b90cfa29"}
```

---

### Steps to reproduce:
1. Set browser locale to Hebrew (he) and sign in.
2. Go to https://accounts.stage.mozaws.net/settings
3. Look at links at bottom of the page.

### Actual results:
![_](https://cloud.githubusercontent.com/assets/557895/7193435/9ab19008-e455-11e4-9729-0cb89a870c0a.png)

### Expected results:
More spacing between the Privacy and Terms links. The UI looks better in "en-US" and "fr":
![gerer_le_compte](https://cloud.githubusercontent.com/assets/557895/7193453/d38da0f6-e455-11e4-8b82-ef4917ed996c.png)

**Comment by johngruen** [comment]
@pdehaan oy vey!

**Comment by vladikoff** [comment]
ping @johngruen

**Comment by shane-tomlinson** [comment]
@johngruen - did you fix this? If not, can you un-assign yourself?

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
This was fixed
![image](https://cloud.githubusercontent.com/assets/128755/8505113/04fcf2ca-21ac-11e5-9e1b-641ce1118959.png)

**Comment by vladikoff** [comment]
@pdehaan I wonder why the email is listed twice on the settings page 
![image](https://cloud.githubusercontent.com/assets/128755/8505126/616362ba-21ac-11e5-996e-e54af5c51ae9.png)

**Comment by pdehaan** [comment]
My, @vladikoff, what big eyes you have!

Why yes, the email _IS_ listed twice in Hebrew.
"Why?" you ask?


```pot
#: app/scripts/templates/settings.mustache:3
#, fuzzy
msgid "You are signed in as"
msgstr "מחובר כעת בתור  %(email)s"
```
&mdash; via [**fxa-content-server-l10n** ./locale/he/LC_MESSAGES/client.po#L802-L805](https://github.com/mozilla/fxa-content-server-l10n/blob/0102ec6760490b4605cfc3987ce01ccc3795291b/locale/he/LC_MESSAGES/client.po:802-805)

Note that the `msgid` doesn't have an `email` param anymore, but the translation still does...

And here is the latest templating stuff in **fxa-content-server**:
```html
<p class="signed-in-email-message">{{#t}}You are signed in as{{/t}}<br />{{email}}</p>
```
&mdash; via [**fxa-content-server** ./app/scripts/templates/settings.mustache:16](https://github.com/mozilla/fxa-content-server/blob/8673920efab153a730ba9dbd7a1d0d7745c63d1c/app/scripts/templates/settings.mustache#L16)

**Comment by pdehaan** [comment]
And, after a bit of grep-in', it looks like we only have 3 languages with dual `%(email)` strings due to nein-updated translations:

```sh
$ grep -irn -A1 'msgid "You are signed in as"' locale | grep "%(email)"

./locale/ca/LC_MESSAGES/client.po-804-msgstr "Heu iniciat la sessió com: %(email)s"
./locale/he/LC_MESSAGES/client.po-805-msgstr "מחובר כעת בתור  %(email)s"
./locale/pl/LC_MESSAGES/client.po-807-msgstr "Jesteś zalogowany jako: %(email)s"
```
