### ISSUE TITLE
Allow the user to change their email ID

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2335]
So that I can access my account if I have forgotten my password and need to reset it, as a logged-in Firefox Account holder, I want to be able to change my email address.

https://www.lucidchart.com/publicSegments/view/53e2818a-5cb8-4faa-a663-5c910a00848c

**Comment by ckarlof** [comment]
Next steps are to break down the work for this. Maybe make this a checklist bug?

**Comment by ckarlof** [comment]
Dup of #2527.
