### ISSUE TITLE
Ship new "Settings Page" UX 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2336]
This is a tracking issue for the new UX:

* [x] Extend profile client to handle `displayName`
* [x] New Layout / Templates (CSS)
* [x] Deploy a new ux box for this feature (@vladikoff) - https://uxwip.dev.lcip.org/signup (tracks issue-2336-new-settings-page branch)
* [ ] ....
![image](https://cloud.githubusercontent.com/assets/128755/7240269/ccc52606-e77d-11e4-939b-c887b0c4e19d.png)

**Comment by pdehaan** [comment]
@johngruen @ryanfeeley 

Not sure if the "Email Address" formatting looks backwards.

Should the "Email Address" be the big-bold text, or the person's actual email address? (Since the display name and email address are arguably the more important pieces of information here).
I understand the consistency angle, but I was almost expecting the latter, sort of similar to the popup on the change password screen:

![change_password](https://cloud.githubusercontent.com/assets/557895/7241205/1748d112-e76c-11e4-8d67-3e10c63fabea.png)

**Comment by zaach** [comment]
@johngruen @vladikoff I created a new branch here: https://github.com/mozilla/fxa-content-server/tree/issue-2336-new-settings-page

**Comment by vladikoff** [comment]
https://uxwip.dev.lcip.org/signup is live tracks the above branch ^

**Comment by zaach** [comment]
@vladikoff Nice! Does that mean autodeploy on push?

**Comment by vladikoff** [comment]
@zaach yeap!

**Comment by zaach** [comment]
@johngruen Heads up, we now have a [Communication preferences](https://www.dropbox.com/s/6pd0c4o38jt3p4e/checkbox-fallback.png?dl=0) screen to accommodate.

**Comment by pdehaan** [comment]
@zaach Where would that "Email preferences" link go to?
I'm assuming "Back" just takes you back to the generic /settings route.

/cc @ryanfeeley

**Comment by johngruen** [comment]
shakes fist at @ryanfeeley

**Comment by rfk** [comment]
"Email preferences" links out to an external newsletter-management page hosted on www.mozilla.org

**Comment by johngruen** [comment]
@zaach https://www.dropbox.com/s/k5f217dyy2lemj6/fxa-settings.png?dl=0

**Comment by zaach** [comment]
![screen shot 2015-06-18 at 3 58 42 pm](https://cloud.githubusercontent.com/assets/3903/8244202/01d52a7a-15d3-11e5-8ec9-b62a2735a661.png)

Display name updates successfully.

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by zaach** [comment]
@jrgm @vladikoff The auto-updating box seems busted again :bomb:

**Comment by johngruen** [comment]
@zaach weird bug on the branch...my password needs to be 9 characters to activate the signup button

**Comment by jrgm** [comment]
> @jrgm @vladikoff The auto-updating box seems busted again :bomb:

@zaach - so yum has become corrupted on that box. It's not worth the effort to do the repair. Just destroy the uxwip stack, and then build a new uxwip stack with fxa-dev.
