### ISSUE TITLE
marketing snippet should be able to log multiple marking links

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2338]
Currently we only allow [one link to be logged](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/metrics.js#L274). The 38.1 FxiOS snippet can have 2 links, both of which should be logged.

Ref #2316

**Comment by shane-tomlinson** [comment]
I propose to log something like the following snippet as part of the metrics that are sent to the /metrics endpoint:

```js
...
marketing: [
  {
    id: 'android-sync',
    url: 'https://play.google.com/somebiglongscarylink',
    clicked: false
  },
  {
    id: 'hello',
    url: 'https://hello.firefox.com',
    clicked: true
  }
],
...
```

This would give us the ability to log an arbitrary number of marketing items, potentially across multiple screens.

**Comment by shane-tomlinson** [comment]
cc @kparlante

**Comment by shane-tomlinson** [comment]
@kparlante's feedback in dev-fxaccount:

> That said, your proposal causes some problems, as nested json is harder to consume in any of our tools -- the json blob needs special case code to be parsed (heka) or is basically inaccessible (kibana3). (Datadog and kibana4 probably fall somewhere in the middle: possible but painful).
> 
> Suggestion: log a more compact, easy-to-parse-in-tools format. Don't include the url: it is not needed for stats and the id/url mapping can be managed elsewhere.
> ...
>   marketing: [android-sync:false,hello:true]
> ...

**Comment by shane-tomlinson** [comment]
More feedback from @kparlante in dev-fxaccount:


> I'm guessing the growth team would want to ask similar questions either by url or by snippet id (or by the snippet id/url pairing). I'm also guessing they don't want to use kibana for this, but will want a data feed.
>
> Another proposal: create a separate message type for snippet-views, with one message for each snippet entry. Include the id/url/clicked fields. If segmentation data is needed, include those fields as well (or use a common "session id" with the client-metrics message).
>
> The tabular data for snippet-views can then be viewed/processed in kibana (or output to another system) easily, and/or we can write a heka filter to generate a tabular aggregated/rollup output for a bespoke dashboard.

**Comment by shane-tomlinson** [comment]
> Another proposal: create a separate message type for snippet-views, with one message for each snippet entry. Include the id/url/clicked fields. If segmentation data is needed, include those fields as well (or use a common "session id" with the client-metrics message).

@kparlante - I want to dig in here. If I understand your proposal, multiple messages would be logged for marketing data. One message would be the marketing data as is currently formatted. The new message(s) would be individual entries, one for each marketing URL. Each marketing entry would contain each of the three fields mentioned.

e.g.:
```json
{"time":"2015-05-07T13:00:00.000Z","op":"client.metrics","pid":27573,"v":1,"lang":"en",...}
{"campaignId":"spring-2015-android-ios-sync","url":"https://www.mozilla.org/newsletter/ios/","clicked":true,"time":"2015-05-07T13:00:00.000Z","op":"client.marketing","hostname":"Shanes-Retina-MBP.local","pid":30856,"v":1}
```

The first entry is the marketing entry as we have always had, the second is an individual marketing impression with the extra meta-data added. I specify an op of `client.marketing` - does that seem reasonable?

Is this along the lines of what you were thinking of?

**Comment by kparlante** [comment]
@shane-tomlinson : yes, that was what I was thinking. You may want to add a few segmentation fields to the "client.marketing" entry, in particular `lang`, `service`, and the user_agent fields
