### ISSUE TITLE
Refreshing /confirm brings you back to /signup 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2341]
```
{"version":"0.35.0","commit":"fadd0306bf1117c96dd1ee25d1981147a6727d55","l10n":"7e0bf097f8","tosPp":"c8e5dadb24"}
```

Is this the desired behaviour? (recent change or bug?)
@shane-tomlinson @zaach 

![confirm](https://cloud.githubusercontent.com/assets/128755/7282079/8c6ffeb2-e8fb-11e4-8633-fa98f22447bf.gif)

**Comment by zaach** [comment]
Somewhat expected. The confirm page only loads when you are directed there from a sign in/up flow.

**Comment by vladikoff** [comment]
@zaach does this mean we can close both this and https://github.com/mozilla/fxa-content-server/issues/2002?

**Comment by zaach** [comment]
For #2002 we should try to redirect to /confirm with the account credentials like we do for sign in/up.

**Comment by zaach** [comment]
Refreshing the page is a separate issue. We can probably close this for now.
