### ISSUE TITLE
Provide a way to direct users to /signin or /signup based on their session state

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2344]
Reliers won't know if the user is already authenticated with FxA on the web, so they can't reliably send them to the correct page. It would be helpful for reliers if we redirected from /signup to /signin if the user is already authenticated.

STR

1) go to /signin and sign in to an existing account
2) go to /signup
3) notice the page stays on /signup

Expected
1) go to /signin and sign in to an existing account
2) go to /signup
3) see sign in form

We can make this the default behavior or add a flag/new route. If we choose the latter, the oauth-server would need to be updated to use the new path to signup. If we make it the default behavior we'll need a flag to disable the redirect so the user can still get to the sign up form if needed (or perhaps we clear all cached sessions like we do for "Choose a different account").

**Comment by vladikoff** [comment]
@zaach could you please clarify: 

> so the user can still get to the sign up form if needed (or perhaps we clear all cached sessions like we do for "Choose a different account").

When would we need this besides ""Choose a different account"" ? 
Re: the flag itself, how about `/signup?force=1`?

**Comment by zaach** [comment]
@vladikoff I was thinking when you click the "Create an account" link on the sign-in form it would clear credentials, then the sign-up form would render without a redirect. Maybe that's too heavy handed. For the flag, perhaps `force_signup=1` so it's more specific.

**Comment by vladikoff** [comment]
@zaach thanks, agreed on `force_signup=1`

**Comment by zaach** [comment]
Forgot to mention, but we should also verify that the session token is still valid before redirecting.

There's also this case: The user has two sets of credentials cached, one for a Sync account and one for another service, but the other service is currently signed in. If the sessionToken is expired, should then check the Sync account next? (Same for a non-Sync account?) Perhaps we can handle that in a follow up.

**Comment by vladikoff** [comment]
> but we should also verify that the session token is still valid before redirecting. 

This will introduce significant delay, I'm worried about this.

**Comment by zaach** [comment]
> This will introduce significant delay, I'm worried about this. 

True– it's probably a less common case so we could just allow the sign-in to fail, e.g. when the account has been deleted.

Related: #1877

**Comment by vladikoff** [comment]
meeting note: we should check if something like Loop has a "signup" action that might send a user to a sign in form

**Comment by vladikoff** [comment]
@zaach this is what we have in the FxAccountsOAuthClient.jsm:
https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsOAuthClient.jsm#38

**Comment by shane-tomlinson** [comment]
What about just sending them to "/"?

**Comment by shane-tomlinson** [comment]
I'm really uncomfortable with the semantics of users who are sent to the "/signin" page to automatically be sent to the "/signup" page and vice versa.

Similar functionality is needed for the firstrun experience, and I [propose sending the user to `/`](https://github.com/mozilla/fxa-content-server/issues/2101#issuecomment-85555029)

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-relier-client/issues/52

**Comment by rfk** [comment]
@shane-tomlinson raises a good point, it's not clear whether or why we can't just use `/` in this case.

**Comment by rfk** [comment]
Whoops accidental closage...

**Comment by rfk** [comment]
I sent an email to ensure that pocket devs are looped into this discussion.  But broadly, I support @shane-tomlinson's position here and we should investigate doing this via a separate route.  Let's consider making the default oauth action be "do the right thing" rather than forcing the choice between signin and signup.

Currently the `action` param defaults to `signin`, so as a relier you get the following chocies for your redirect:
```
  GET /v1/authorization                =>  /signin
  GET /v1/authorization?action=signin  =>  /signin
  GET /v1/authorization?action=signup  =>  /signup
```

We chould change it so that specifying no action means "go ahead and show whatever makes the most sense", like so:
```
  GET /v1/authorization                =>  /
  GET /v1/authorization?action=signin  =>  /signin
  GET /v1/authorization?action=signup  =>  /signup
```

Potential bikeshedding [1] of the path to the new do-the-right-thing route aside, this seems a little cleaner than adding additional flags to tweak behaviour of the existing routes.  Thoughts?

[1] https://github.com/mozilla/fxa-content-server/issues/2101#issuecomment-96443904

**Comment by zaach** [comment]
:+1: . I like `/oauth` as a path.
