### ISSUE TITLE
OAuth flow: signal what type of auth occurred to the relier

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2345]
Reliers may want to know if the user has signed in or up and whether they had to type in a password so that they can customize their landing page experience.

We could solve this by appending params to the redirect URL.

Note: Sign-in doesn't require a password if the user has authenticated with Sync.

cc @rfk

**Comment by rfk** [comment]
> whether they had to type in a password so that they can customize their landing page experience

Random aside: it may be possible for reliers to infer this from the `last_auth_at` timestamp that we already make available to them.

Anyway, my gut instinct is that a flag URL param to indicate signup-versus-signin is the right level of granularity here, and we don't need to look down to the detail of "did the user have to type in a password".

**Comment by rfk** [comment]
Concretely, we could mirror the query-param API that allows reliers to select between signup and signin here:

  https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#get-v1authorization

And at completion of the flow, pass either `action=signup` or `action=signin` as part of the redirect response.

**Comment by zaach** [comment]
:+1:

**Comment by shane-tomlinson** [comment]
I have to admit that I'm slightly confused by the requirement - RPs want to show distinct landing pages based on whether they are a new user *to us*? Shouldn't they really only care if the user is new to *them*?

**Comment by rfk** [comment]
> RPs want to show distinct landing pages based on whether they are a new user to us?

Yes.  It's pretty esoteric.

The concrete ask here is that pocket has the ability for users to set a pocket-specific password after signing in via OAuth.  If the user does so, they can then signin with *either* the oauth dance or a plain email/password combination.  You can see this in action if you try out their "login with Google" flow today.

Pocket have previously run experiments to show that this increases overall user engagement with the product, and would like to run more such experiments with the FxA flow.  But we don't want to prompt the user to create two passwords in quick succession, one for a new FxA and then another for pocket.

So the idea would be: if the user authenticates via FxA and completes with `action=signin`, the RP is free to experiment with asking them to set an RP-specific password.  But if auth completes with `action=signup` then they really shouldn't.

It seems like it will be a really rarely used feature.  But if it's simple enough for us to signal, it will have some concrete value for this integration.

**Comment by vladikoff** [comment]
Moving to train 38
