### ISSUE TITLE
OAuth prompt page should indicate what information will be shared

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2346]
We don't have a full-blown OAuth permissions screen yet, but we do have a "continue to $RELIER" prompt page.  We should add information to this page describing what data will be shared with the relier, so that the user is not surprised when the relier later e.g. sends them an email.

/cc @zaach @rfeeley, and thanks to @seanmonstar for calling this out.

**Comment by rfk** [comment]
In other words, we want to offer a similarly candid assessment of what's about to happen as this google auth prompt:
![g_prompt_page](https://cloud.githubusercontent.com/assets/34695/7312165/9b508d8a-ea8a-11e4-9c52-ab67b17cb059.png)

**Comment by shane-tomlinson** [comment]
I thought there was a strong desire to *not* offer a full blown permissions screen. Is this needed only because Pocket is a 3rd party site?

**Comment by seanmonstar** [comment]
Not a full permissions page. Just including a line that "$site will also receive your email and avatar" or something, near the continue button. 

An eventual permissions page would include all scopes, and check boxes to disable some. This is just so users aren't surprised, if they didn't realize we were giving access to their email address.

**Comment by shane-tomlinson** [comment]
> We don't have a full-blown OAuth permissions screen yet, but we do have a "continue to $RELIER" prompt page. 

We don't actually have "continue to relier". This functionality broke Marketplace, so we took it out. See #2343, #1723, #1725, and #1942.

**Comment by shane-tomlinson** [comment]
> We don't actually have "continue to relier".

I should have been more clear. We do not have a "continue to relier" from the verification pages.

**Comment by rfk** [comment]
> We do not have a "continue to relier" from the verification pages.

Sorry to add additional confusion to the "continue to relier from verification page" issue.  I don't believe this bug is related to that work.  Rather it affects the initial "signin to continue to X" or similar prompt at the start of the oauth dance.

> I thought there was a strong desire to not offer a full blown permissions screen.
> Is this needed only because Pocket is a 3rd party site?

IIUC there's been a strong desire to:
1) not have a permissions screen for trusted mozilla reliers
2) not build a permissions screen infra until we actually need it for something

So you're right, this suddenly comes up because pocket is a 3rd-party site and we haven't been designing for those yet.  It's a very low-risk 3rd-part site (e.g. we actually have a contractual relationship, they're not some random site off the interweb) but still, it's not Mozilla-hosted so we need to sanity-check all our assumptions in this flow.

**Comment by rfk** [comment]
Note that we already flag reliers as being trusted or not, via the `whitelisted` [1] client property.  I see that my initial comments didn't call this out explicitly, but the extra info/prompts would be only for 3rd-party reliers.  The experience for existing mozilla reliers would remain unchanged.

[1] soon to be something-other-than-`whitelisted` per https://github.com/mozilla/fxa-oauth-server/issues/188

**Comment by vladikoff** [comment]
from meeting: How do we track if the user saw that screen already and proceed without it. i.e once the user agreed to it once already

**Comment by rfk** [comment]
Does this need to be a separate screen, or is the information small enough that we could add it to the existing prompt page?  This one and its siblings:
![screen shot 2015-04-28 at 11 35 54](https://cloud.githubusercontent.com/assets/34695/7361390/ce6ef98c-ed9a-11e4-8d54-06a7c3f32383.png)

We can iterate towards a separate screen of course, but I'm very interested in doing the minimum possible amount of work here to start with.

**Comment by vladikoff** [comment]
@ryanfeeley ^

**Comment by rfk** [comment]
Having caught up on the rest of my emails, I see that there was IRL discussion of a separate permissions screen at the fxa frontend standup this morning.  If you all are in a happy place with it already, do not let me back-seat-drive this thing :-)

**Comment by rfk** [comment]
Per IRL discussion, we're going to try to ship a separate permissions-esque screen in time for the pocket release.  The first version won't offer the ability to customize the requested permissions, but will inform the user of what's going on as well as the ToS for the relier.

> How do we track if the user saw that screen already and proceed without it. i.e once the user
> agreed to it once already

I'd like to explicitly take this off the table for our initial version, or at least scope it down to a simple cookie-like approach.  @ryanfeeley how would you feel about going live without the ability to remember whether the user has previously seen the permission screen?  We can safely add it in later without changing the relier-facing API.

**Comment by zaach** [comment]
@ryanfeeley In your proposed flow, we show the profile information and allow the user to edit their info, but this won't be possible unless the account is already verified. This won't work for sign-up, so we'll have to do a screen like Google's for now and only mention what is shared in generic terms.

Also, it might be confusing that we say we're sharing the user's name when there is no UI to actually set their name. "What name are they sharing? From where??"

**Comment by zaach** [comment]
Screen below:
![screen shot 2015-04-29 at 3 59 40 pm](https://cloud.githubusercontent.com/assets/3903/7403259/ca580a52-ee88-11e4-9ba6-66c535dec0ed.png)

Also, having the name of the relier positioned as a heading while also part of a phrase makes it hard for l10n. We'll either need to special case English like we do for "to continue to" or make it the same weight as the rest of the phrase. If we special case it, we need an alternative string that other locales will use in place of "would like to know...".

**Comment by ryanfeeley** [comment]
Soon AFK but latest https://www.lucidchart.com/publicSegments/view/553eb09f-f574-4a67-84f0-7a7f0a009e60

**Comment by zaach** [comment]
Awesome. Well that clears up my concerns.

**Comment by rfk** [comment]
In the "of Pocket (getpocket.com)" text, will we derive "getpocket.com" from their relierUri or allow them to configure this independently?  Deriving from relierUri seems safer if it'll work.

**Comment by pdehaan** [comment]
@ryanfeeley: which is the latest mockup? @zaach's https://github.com/mozilla/fxa-content-server/issues/2346#issuecomment-97610521 shows an avatar image and first+last name text inputs, but your PDF didn't.

**Comment by zaach** [comment]
@pdehaan Ryan's is the latest

**Comment by zaach** [comment]
To minimize the complexity we may implement this as a modal.
