### ISSUE TITLE
Display links to relier ToS in signup/signin flows

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2347]
Details t.b.d. but we'll need to do this somehow, so here's a bug to remind us.  For the sign-in case it may feed into #2346.  @zaach suggested we expand the client meta-data in fxa-oauth-server to include the necessary links.

**Comment by shane-tomlinson** [comment]
Shouldn't the relier show their own TOS/PP links?

We are going down the full on Persona route. Double the TOS/PP was not double the pleasure, if anything it was double the ugliness.

**Comment by rfk** [comment]
> Shouldn't the relier show their own TOS/PP links?

In the general case I don't think they can.  If you have a firefox account and you're currently signed in, we want to offer one-click connection to the relier.  So potentially, the only UI you'll see is our "signin to X" oauth landing page.

**Comment by shane-tomlinson** [comment]
@ryanfeeley suggested today that perhaps this could live on the permissions screen.

**Comment by rfk** [comment]
:+1: assuming we actually wind up with a separate permissions screen

**Comment by rfk** [comment]
Per IRL discussion, we're going to attempt a separate permissions screen and the ToS links will indeed live there.  Assigning this to @zaach who is driving work on the permissions screen.

**Comment by rfk** [comment]
The latest word is that pocket will display these links on their post-login landing page, so this is RESOLVED/WONTFIX for now.
