### ISSUE TITLE
Tests for tos and pp refresh back button are failing.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2354]
Two new tests added in https://github.com/mozilla/fxa-content-server/pull/2331 
https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/tos.js#L56-L74
https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/pp.js#L59-L77

are consistently failing when run against stage, and are also failing at times on latest with beta.

http://tests.dev.lcip.org:8111/viewLog.html?buildId=2196&buildTypeId=fxa_LatestFirefoxBetaTests&tab=buildLog#_focus=360

**Comment by vladikoff** [comment]
Hmm this is pretty strange, seems to be mostly okay on LATEST. Will need to investigate ...

**Comment by jrgm** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/2370. Closing.
