### ISSUE TITLE
tests/functional/oauth_channel.js->testIsBrowserNotifiedOfLogin signature is gross

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2360]
it takes a context and two booleans. We should collapse these.

Ref #2357

**Comment by riadhchtara** [comment]
hi,
I will take care of this one :)

**Comment by riadhchtara** [comment]
Atul, a friend of mine is in contributing to the project. So I will mentor him to solve this issue

**Comment by pdehaan** [comment]
![](http://www.quickmeme.com/img/f6/f6f1edf89273cbe018100ea5d168283f9813f143c275e5b4d9d8e1d3c0d689dc.jpg)

**Comment by riadhchtara** [comment]
You made my day by this :-)

**Comment by riadhchtara** [comment]
@ava14: the only thing that needs to be changed is the commit message: could you please change it to:
refactor(tests): remove the extra booleans from
testIsBrowserNotifiedOfLogin
Fixes #2360
otherwise everything is fine: nice work

**Comment by riadhchtara** [comment]
Could anyone please review my review?
@pdehaan : I'm still  kid :)
