### ISSUE TITLE
Add support for Node 0.12

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2365]
See https://github.com/mozilla/fxa-auth-server/pull/920

It'd be super neat if we updated **fxa-content-server** to work with Node 0.12.x and io.js and update our travis.yml to run tests for those envs.

![](https://31.media.tumblr.com/6102fb750a0f9cb93b00ada9259b886b/tumblr_inline_nndyuwqKFX1raprkq_500.gif)

**Comment by vladikoff** [comment]
It already works, just need to add Travis testing

**Comment by pdehaan** [comment]
Oh, i thought it wasn't working yet since the auth-server didn't support 0.12.
Well cool, sounds like an easy .travis.yml fix and then figure out how to solve the npm issue where we're manually installing npm@2.4 (see [.travis.yml:22](https://github.com/mozilla/fxa-content-server/blob/6fd10dae2dcd38401be03031488598e06e69ae0b/.travis.yml#L22)) -- which works fine for Node 0.10 w/ npm 1.4, but probably not so great for Node 0.12 w/ npm 2.7+.
