### ISSUE TITLE
Firefox password manager asks to remember password in iframe flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2373]
The Firefox password manager does not allow passwords from [about:accounts](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/LoginManagerContent.jsm#568) to be saved. The firstrun flow is not about:accounts, hence the password manager asks if the user wants to save their password.

It looks like this behavior can be disabled w/o a Firefox change by adding [autocomplete=off](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/LoginManagerContent.jsm#589) to the form element.

cc @ckarlof

ref #2101, #363, #1780, #1788

**Comment by shane-tomlinson** [comment]
ref #2101

**Comment by shane-tomlinson** [comment]
My proposal:

* Skip the autocomplete=off on the password field, if type===password
* Instead, add autocomplete=off to the form field if the relier is sync.
* And, add autocomplete=off to the password field when type===text

**Comment by ckarlof** [comment]
I got some sad news about this: Firefox doesn't respect `autocomplete=off` anymore and it's not how we stop the "remember your password" dialog from appearing on about:accounts anymore. [It's not elegant, BTW](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/LoginManagerContent.jsm#570).

**Comment by rfk** [comment]
Capturing Shane's suggestion from an email thread: perhaps we should expand that regexp to also match "https://accounts.firefox.com/.*service=sync" or similar.  It would remain a gross hack, made only slightly grosser by expanding it to cover this new case.

**Comment by rfk** [comment]
A slightly better approach would be to prevent the save-password prompt from advertising sync when you're at one of these URLs, rather than preventing the save-password prompt entirely.

**Comment by shane-tomlinson** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1173688 to track this from the Fx side.

**Comment by shane-tomlinson** [comment]
Closing, this was fixed in record time by the Fx team. Thank you @edmoz for working your magic!

**Comment by ckarlof** [comment]
It's amazing what happens when we all work together!
