### ISSUE TITLE
Need an untrusted relier for testing

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2383]
We currently use 123done for testing relier flows, but it's a trusted client. To test features like the permission screen we'll need an untrusted relier set up in all of our testing environments.

/cc @jrgm

**Comment by vladikoff** [comment]
@zaach do we need another repo or can we reuse something?

**Comment by zaach** [comment]
@vladikoff It could probably be a branch of 123done, using new oauth credentials.

**Comment by jrgm** [comment]
321done?

**Comment by pdehaan** [comment]
Whatever happened to http://myfavoritebeer.org/?
All just sittin' there like a fat baby.

**Comment by ckarlof** [comment]
> 321done?

Oh, that @jrgm.

**Comment by pdehaan** [comment]
@vladikoff is this done?
