### ISSUE TITLE
Relier keys don't work after signup and verify in same browser

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2384]
This was originally reported as https://bugzilla.mozilla.org/show_bug.cgi?id=1161560.

If you go to sign into Hello, create a new account, and then verify in the same browser then the login flow fails to produce relier keys.  Verifying in a different browser works fine.

We suspect that the keys=true state is not correctly tunneled through the verification link.  When verying in the same browser, the tab that you open after clicking the "verify" link is the one that ultimately handles the completion of the oauth dance.  If this tab doesn't know enough context to derive keys, it will fail to return them.

**Comment by rfk** [comment]
Some simple console.log() debugging seems to confirm the hypothesis.  In new verification tab claims that `relier.wantsKeys()` is false, and hence doesn't derive the keys.  The original tab (assuming it is still open) does proceed to derive the keys, but its result is ignored.

**Comment by rfk** [comment]
Ugh, @shane-tomlinson I'm going to need your help with this one.

It's a fairly simple matter to correctly tunnel the `keys=true` state through in the resume token and/or the local oauth session data.  But we also need access to the `keyFetchToken` and `unwrapBKey` in order to actually derive the keys.  These are very sensibly not persisted in the account data, meaning there's no obvious way for the verification tab to access them.

It's not clear to me how we handle the matching case in sync:

* sign up for sync with a new account
* copy the verification link and paste it into the tab containing `about:accounts`
* the email gets verified and sync is somehow still able to access the key material

How do we handle this in the case of the verification-confirmation-polling page going away?

**Comment by rfk** [comment]
FWIW, just persisting the `keyFetchToken` and `unwrapBKey` will *work*.  I tried this in https://github.com/mozilla/fxa-content-server/pull/2385 and it does indeed fix the reported bug.  But it's far from ideal.

It also causes the originating tab to get a cryptic error, since both the originating tab *and* the verifying tab will now attempt to use the same `keyFetchToken`:

![screen shot 2015-05-06 at 16 59 36](https://cloud.githubusercontent.com/assets/34695/7488718/4c051b8e-f411-11e4-8ba1-38f1f870e60b.png)

**Comment by rfk** [comment]
Oh, I guess I should put in concrete Steps to Reproduce for full context:

1) Activate Hello and go to "sign in or sign up"
2) Sign up with a new account and receive the verification email
3) Open the verification email in the same browser

We'll fail to deliver the expected encryption keys to Hello, and it will enter an error state.

**Comment by rfk** [comment]
As an alternative to persisting the key-fetch material, perhaps we could:

* for web-channel reliers, try to complete the flow in the originating tab rather than the verification tab
* if we find we can't derive relier keys for whatever reason, get the user to sign in again rather than just silently failing to return the keys

This would give a good experience when verifying in a new tab, and an OK experience when the originating tab has been closed.

**Comment by rfk** [comment]
Alternately, we can try to persist the key-fetch material only in the cases where we need it.  But this seems like a layering violation in the current architecture.

**Comment by shane-tomlinson** [comment]
@rfk - I'm rambling here to put my thoughts together and to understand the requirements better. I'm going backwards from the requirement that if the user verifies in the same browser, a WebChannel should ship the keys off to Loop. I'm also working under the assumption that only *one* tab should send off the keys.

* If the original tab is still open, it can send the keys - have the original tab ship the keys.
* If the original tab is no longer open, we need a way to derive keys to send. We need a keyFetchToken.

Possible solutions to getting a keyFetchToken in tab 2:
* Store the keyFetchToken in localStorage, fetch it. What are the security repercussions of this?
* Have the user re-enter their password, and a keyFetchToken can be fetched from the server.
* Can a keyFetchToken be fetched from the server with only a sessionToken, or does the keyFetchToken rely on the user's password for derivation (I'm assuming so)?

The first seems insecure, but easy. The second can be done if we determine the relier wantsKeys and we ship the user off to /force_auth. this.relier.email will need to be set if it is not already or else the /force_auth screen will blow its top. The third is probably not possible.

**Comment by shane-tomlinson** [comment]
@rfk - shuttling the user off to /force_auth is pretty straight forward, though the UX is perhaps not as beautiful as expected. wantsKeys will need to be added to the resume token, then re-constituted when the verification page loads. (see @vladikoff's open PR which does just that and may be merged today - https://github.com/mozilla/fxa-content-server/pull/2366/files#diff-ca4d7096469c2a76694bb8214760cbaaR100)

```diff
diff --git a/app/scripts/views/complete_sign_up.js b/app/scripts/views/complete_sign_up.js
index 825a970..b9ae009 100644
--- a/app/scripts/views/complete_sign_up.js
+++ b/app/scripts/views/complete_sign_up.js
@@ -69,6 +69,12 @@ function (Cocktail, FormView, BaseView, CompleteSignUpTemplate,
               return false;
             }

+            // isOriginalTabStillOpen will need to be written, ref https://github.com/mozilla/fxa-content-server/blob/d28e761d8f15c4e96f68d99570958c2a1261db05/app/scripts/lib/channels/inter-tab.js#L27
+            //if (self.relier.wantsKeys() && ! isOriginalTabStillOpen()) {
+              self.relier.set('email', self.getAccount().get('email'));
+              self.navigate('force_auth');
+              return false;
+            //}
+
             if (! self.relier.isDirectAccess()) {
               self.navigate('signup_complete');
               return false;
```

**Comment by rfk** [comment]
> Can a keyFetchToken be fetched from the server with only a sessionToken

Nope.  We'd also need `unwrapBKey` anyway so I don't think there's a way around it.

**Comment by rfk** [comment]
Thanks for the tips, I'll have a go at this.

> +            //if (self.relier.wantsKeys() && ! isOriginalTabStillOpen()) {

This seems like the wrong place to be figuring out the tab state.  Perhaps we should do this in an exception-driven manner, e.g. `afterSignUpComplete` could throw an special error if it needed keys but didnt have them, and the view could detect that and navigate appropriately.

**Comment by rfk** [comment]
AFAICT there's three cases that we need to tease apart:

* verify in original browser, with originating tab still open => let originating tab deal with it
* verify in original browser, with originating tab closed => force_auth and publish the keys from there
* verify in other browser => behaviour stays the way it is currently

> then re-constituted when the verification page loads

Aha, I was very confused when I couldn't find anywhere that actually parsed the resume-token.

**Comment by rfk** [comment]
A related problem, which causes the error I screenshotted above, is that the web-channel broker causes the oauth flow to finish in *both* tabs.  ISTM that whichever tab finishes it first is the one that Hello takes its result from, and the complete_sign_up page almost always wins since it doesn't need to poll for verification status.

The following untangling of concerns seems to make sense to me:

1) The afterCompleteSignUp() and afterCompleteResetPassword() methods should grow an argument indicating whether the originating tab is still open.  This would leverage and expand the existing logic for dealing with this case in the password reset flow, and is decided entirely by the views.
2) The web-channel broker should use this information to decide whether to finish the oauth flow in response to these events, or to allow the originating tab to finish it.  We strongly prefer that the original tab do it.  This logic is local to the broker.
3) If we try to finish the oauth flow and find we can't generate keys, raise an error and let the view redirect us to the force-auth page so we can start over.

@shane-tomlinson how does this sound at a high level?

**Comment by shane-tomlinson** [comment]
> Perhaps we should do this in an exception-driven manner, e.g. afterSignUpComplete could throw an special error if it needed keys but didnt have them, and the view could detect that and navigate appropriately.

This is definitely more elegant than what I had in mind, also more flexible. If the broker can get the unwrapBKey and keyFetchToken from wherever it can get them, then the view needs to know nothing about the tab state.

> AFAICT there's three cases that we need to tease apart:

You now understand all the issues @ryanfeeley and I went through to put together https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/. ;)

You should probably consider if the verification tab replaces the original tab too, though I think it collapses into one of the others.

> 1) The afterCompleteSignUp() and afterCompleteResetPassword() methods should grow an argument indicating whether the originating tab is still open. This would leverage and expand the 
existing logic for dealing with this case in the password reset flow, and is decided entirely by the views.

Which part is decided by the view? Whether the tab is still open, or whether to complete the flow? Something about that doesn't seem right. Maybe the broker can create and query a "Tabs" model or something like that to determine whether there are other tabs open. The Tabs model would check [crosstab.util.tabCount()](https://github.com/mozilla/fxa-content-server/blob/cdd999e395d560f67762c3b3d258859e5852902a/app/scripts/lib/channels/inter-tab.js#L27). Or perhaps the InterTabChannel can expose that information itself and the interTabChannel instance created in [app-start](https://github.com/mozilla/fxa-content-server/blob/cdd999e395d560f67762c3b3d258859e5852902a/app/scripts/lib/app-start.js#L155) can be passed in [to the WebChannelAuthenticationBroker](https://github.com/mozilla/fxa-content-server/blob/cdd999e395d560f67762c3b3d258859e5852902a/app/scripts/lib/app-start.js#L316).

I feel like the view should not be a part of the decision making process, but rather should respond, if needed, to a decision made elsewhere, e.g., the exception thrown in the broker that you mention above.

> 2) The web-channel broker should use this information to decide whether to finish the oauth flow in response to these events, or to allow the originating tab to finish it. We strongly prefer that the original tab do it. This logic is local to the broker.

:+1:

**Comment by ckarlof** [comment]
What would the simplest thing to do?

What if we stop trying to notify the WebChannel on the email verification link page? This would mean that if the user closes the original tab then she won't be logged in to Loop, but it might be a simpler implementation. The user can always re-initiate the login flow. 

Otherwise, as you guys point out, we'll need some coordination between the two tabs as to who is going to broadcast the login event. This could be done fairly cleanly with a [Command pattern](http://en.wikipedia.org/wiki/Command_pattern). We could stuff the login event data in a Command object in localStorage somewhere and the first consumer that uses it (i.e., sends it over the WebChannel), will delete it. When the second tab goes for it and finds nothing, it could just do nothing.

**Comment by rfk** [comment]
> Which part is decided by the view? Whether the tab is still open, or whether to complete the flow?
> Something about that doesn't seem right.

I guess I was feeling that "the broker shouldn't need to know about tabs" and so was giving that responsibility to the view by default.  But there's already tab-handling logic in the redirect broker, so it wouldn't be out of place to do similar in the web-channel broker.

> What if we stop trying to notify the WebChannel on the email verification link page? 

This will almost certainly work, but there's comments in the code to the effect of "we're doing this on purpose".  I've no context on why it was originally done that way and I'm afraid it might break some other flow I don't know about.

**Comment by rfk** [comment]
> We could stuff the login event data in a Command object in localStorage somewhere
> and the first consumer that uses it (i.e., sends it over the WebChannel), will delete it.

I think I'm going to go with a variant of this idea, it seems like the least amount of surgery to the existing code and will get us close to where we want to be.  Unfortunately it will mean persisting the key-fetch material to localStorage briefly.  But if we get something that works, we can take our time on iterating towards a better approach.

**Comment by rfk** [comment]
I've updated https://github.com/mozilla/fxa-content-server/pull/2385 with a minimal fix that does the following:

* Stores the `keyFetchToken` and `unwrapBKey` as part of the oauth session data when `wantsKeys()==true`.
* Loads and uses the stored values if we're completing the flow in the verification tab.
* Uses the presence of `this.session.oauth` as a flag to check whether the flow already completed in another tab.

This works in my local testing, although obviously I need to add a bunch of tests for these changes.  I'm not happy about persisting the key-related stuff to disk, but at least it's only there transiently and only for this one flow.

@shane-tomlinson would you be happy to ship something along these lines in train-37, as a compromise solution to get the bug fixed for Hello?  That would give us some breathing room to work on the tab-coordination thing as a better solution.

**Comment by shane-tomlinson** [comment]
> This will almost certainly work, but there's comments in the code to the effect of "we're doing this on purpose". I've no context on why it was originally done that way and I'm afraid it might break some other flow I don't know about.

Check #1825 & #1816 for background information.

**Comment by rfk** [comment]
> would you be happy to ship something along these lines in train-37,
> as a compromise solution to get the bug fixed for Hello? 

We can of course try to do better for train-37, but it might be nice to have some sort of fix in our pocket.
