### ISSUE TITLE
Add metrics on number of users landing on signin page with an existing session

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2393]
Depending on their existing session state, users who land on our signin page may have the option of continuing without re-entering their password, or they may have to re-enter it to confirm their identity.  Let's gather metrics to determine what percentage of users are falling into each category.

See #2391 for a concrete reason this metrics will be valuable.

**Comment by vladikoff** [comment]
need to add it here: https://github.com/mozilla/fxa-content-server/blob/7422f1e0fe42c39adfd149fcc12a7a77ce7cb9b8/app/scripts/views/sign_in.js#L270

**Comment by rfk** [comment]
Ideally, I think we should tease apart four distinct cases here:

1) sign-in with no state => enter both email and password
2) sign-in with cached email but no session => enter password
3) sign-in with cached session, but it's not sync => enter password
4) sign-in with cached session from sync => click through with no password

The difference between (3) and (4) is the one relevant to #2391 but the others are likely of general interest going forward.

**Comment by rfk** [comment]
(taking this myself, as it seems pretty small and will be a good opportunity to learn more about the front-end metrics events)
