### ISSUE TITLE
Consider using BroadcastChannel instead of localStorage sync for browsers that support it.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2397]
The [BroadcastChannel](https://developer.mozilla.org/docs/Web/API/Broadcast_Channel_API) is a new Web API that allows multiple tabs on the same domain to communicate with each other without persisting data to disk. Think of it as multi-tab pub-sub. Awesome.

We currently use the localStorage via a library called crosstab.js to serve this purpose. Using BroadcastChannel in supporting browsers would allow supporting browsers to never store sensitive data to disk.

**Comment by pdehaan** [comment]
Looks like only Firefox supports this currently, per http://caniuse.com/#feat=broadcastchannel

**Comment by vladikoff** [comment]
Closing until there is more browsing support
