### ISSUE TITLE
campaign and entrypoint are only imported for the fx-desktop relier & needed more generically

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2399]
The code to import the `campaign` and `entrypoint` query parameters lives in the [fx-desktop relier](https://github.com/mozilla/fxa-content-server/blob/5a3c0683198c535bbcc9337849ab0217945ff600/app/scripts/models/reliers/fx-desktop.js#L23).

From the marketing team in [bugzilla #1162192](https://bugzilla.mozilla.org/show_bug.cgi?id=1162192):

> This is important as we use the spring 2015 campaign to drive users to create Firefox accounts. We don't currently have a landing page to drive users to, so as our various channels (social, email and snippet) encourage Firefox Accounts creation, we need a way to measure conversions for testing and optimization purposes.

and 

> We want to track the number of accounts created on that page by source. So if we were using GA, we'd have UTM tags in our various URLs to the page that would allow us in GA to create a breakdown of which channel drove x number of conversions. Email xx percent of total YY and social / Facebook zz percent of total yy and so on. 

and

> Hey team! Similar to how we can directly track back campaigns and content to Firefox downloads, our hope is that we can do the same thing with Accounts. It would be valuable to identify what kind of content works, and what kind of content doesn't in driving accounts sign ups. 

A first step is to import these values from [models/relier.js](https://github.com/mozilla/fxa-content-server/blob/5a3c0683198c535bbcc9337849ab0217945ff600/app/scripts/models/reliers/relier.js#L51) instead.

How we surface this information to the marketing team is a different question.

**Comment by ncalexan** [comment]
Android and iOS would like to use `entrypoint`, or something similar, to track whether our first run experience is driving Account flow volume.  We're very interested in whether new users complete the flow.
