### ISSUE TITLE
OAuth: support `verification_redirect` for password reset and account reset

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2401]
It would be great if we do not "dead-endon on password reset or account reset with `verification_redirect`
![](https://cloud.githubusercontent.com/assets/848085/7597889/812c2302-f8ee-11e4-9465-17e5725c18fb.png)

https://github.com/mozilla/fxa-content-server/pull/2366#issuecomment-101411879
https://github.com/mozilla/fxa-content-server/pull/2366

**Comment by vladikoff** [comment]
Should also move all functional tests for verification_redirect into its own file.

**Comment by shane-tomlinson** [comment]
ref #2402

**Comment by vladikoff** [comment]
Pushing this to train-40, pocket is not even using the basic verification_redirect

**Comment by vladikoff** [comment]
@rfk what should we do here? Will Pocket use this feature? Should we wait for them to try out the "sign up" only flow + wait for feedback or proceed with this?

**Comment by rfk** [comment]
Yes, let's bump it until we get feedback from pocket that they're using the feature again.  IIUC they are going to try it out again soon, but I'm sure they've got a lot of threads to follow up on.

**Comment by vladikoff** [comment]
> Yes, let's bump it until we get feedback from pocket that they're using the feature again. IIUC they are going to try it out again soon, but I'm sure they've got a lot of threads to follow up on.

Okay, thanks Ryan!

**Comment by issues-bouncer** [comment]
Hey @vladikoff, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
Blocked on Pocket's feedback.

**Comment by rfk** [comment]
ref #2670

**Comment by vladikoff** [comment]
No action here AFAIS, however some discussion here: https://github.com/mozilla/fxa-content-server/issues/2349 

let me know if we need to reopen...
