### ISSUE TITLE
Odd login flow when trying to sign in to Pocket (and you close original tab)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2402]
Found in https://accounts.firefox.com/ver.json (commit 25dedeb0b1f2d5212f34e41ed17317bc5fbf5477)

```json
{ "version":"0.36.3",
  "commit":"25dedeb0b1f2d5212f34e41ed17317bc5fbf5477",
  "l10n":"412fdf2ec9",
  "tosPp":"15e58d3fe8"}
```

---

### Steps to reproduce:
1. Sign in to Pocket in FF Nightly (or Beta) or via https://getpocket.com/ff_signup
2. You get redirected to https://accounts.firefox.com/oauth/signup?client_id=749818d3f2e7857f&state=9c813309bff83a37fec13455fc1c0da5&scope=profile
3. Sign up for a new account.
4. Open a new tab.
5. Close the original tab (where you registered).
6. Verify your account in the new tab.

### Actual results:

![konto_bestatigt](https://cloud.githubusercontent.com/assets/557895/7601231/603fa2b6-f8c8-11e4-8b82-3493d0b48375.png)

You reach a dead end, and you're... lost. There is no redirect or anything.
Worse, going back and clicking the Pocket button again, shows that you're not really signed in.

![konto_bestatigt](https://cloud.githubusercontent.com/assets/557895/7601254/a9c8ace8-f8c8-11e4-83d3-162a0426661c.png)

Returning back to getpocket.com, shows that you're not really signed in to... anything.
![pocket](https://cloud.githubusercontent.com/assets/557895/7601263/bfd3f178-f8c8-11e4-8855-11c60ef0421e.png)

Going to https://accounts.firefox.com/ redirects you to https://accounts.firefox.com/settings which shows you as successfully signed in to FxA.

It seems the only way to really log in is to press the Pocket button **again**, and now enter your password **again**:

![anmelden_weiter_zu_pocket](https://cloud.githubusercontent.com/assets/557895/7601280/ed311e66-f8c8-11e4-9f5d-82b20a08bbd2.png)

After you enter your password, you're finally prompted to set your Pocket password (which will be used for 3rd party apps like Twitter or Flipboard.

### Expected results:

WHAAATTTT?
Closing the original tab seems to be pretty bad and puts you in a bad state.
I was hoping that clicking the verification link in a new tab would _not_ dead-end me, but it seems like no such luck and we're expecting that original tab and it's polling to save us.

### Feelings GIF:
![](http://i.imgur.com/K8TyNMO.gif)

**Comment by pdehaan** [comment]
/cc @ryanfeeley 
Not sure if we had a separate tracking bug for this flow with the oversized "PROCEED" button, or if that covers a slightly different case.

I just tripped over this case when testing Pocket integration today and it left me literally weeping under my desk.

**Comment by pdehaan** [comment]
possibly but not entirely similar to #2401 and #2366

**Comment by ryanfeeley** [comment]
I believe the PROCEED button @zaach is implementing will help, but the user will reasonably expect that the add-on will be signed-in and come to life like Hello or Sync. This is a problem if it does not.

**Comment by rfk** [comment]
IIUC, @vladikoff's next iteration of the "proceed" button should help with this, assuming we can make it so that clicking the button actually completes the flow rather than just redirecting back to the start of the process.
