### ISSUE TITLE
password visibility metrics are *very* verbose

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2403]
For example, for a single /oauth/signin page view, I see:

```
"oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web","oauth.signin.ask-password.shown.session-from-web"
```

ref #2394

**Comment by rfk** [comment]
Ouch.  I gues this reflects `views.sign_in.context()` being called multiple times while rendering the page, which in turn is calling `_suggestedAccountAskPassword` multiple times?  We could debounce this with a simple flag, but from my limited understanding of the rendering process, I'm surprised it's being called so many times.

**Comment by shane-tomlinson** [comment]
@rfk - I should have caught this in my review. re context being called so many times see #1523. Finally, get off the computer!
