### ISSUE TITLE
OAuth: remove 'state' from RELIER_FIELDS_IN_RESUME_TOKEN

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2405]
See https://github.com/mozilla/fxa-content-server/pull/2366#discussion_r30160740

**Comment by ckarlof** [comment]
CRSF protection is one use case for state, but it's use is not limited to that. I don't have all the context here, but we should always provide the state back to the relier (same or different browser), and then it sort out what needs to happen.

**Comment by shane-tomlinson** [comment]
Closing then. Thanks @ckarlof
