### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2413]
We can't seem to find any definitive list anywhere (docs, README, wiki, MDN) where we officially state what browsers we support.

I know we dropped IE8 support, i'm unclear on IE9 support, or if we officially support Safari, or Android.

We may want to add it to a wiki page or README or something.
Googling around, I found this for Persona: https://developer.mozilla.org/en-US/Persona/Browser_compatibility

**Comment by pdehaan** [comment]
Ha, I did find https://github.com/mozilla/fxa-content-server/issues/105 (which this is probably a dupe of), but it'd be nice if we published that list somewhere more discoverable.

**Comment by vladikoff** [comment]
IE10, FF18+, iOS 8+ browser engine, Android 4.x+ ?

**Comment by jrgm** [comment]
> IE10, FF18+, iOS 8+ browser engine, Android 4.x+ ?

Apparently, Fennec must support Android 2.3+ (API 9+)
