### ISSUE TITLE
Update permission screen design 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2423]
via https://github.com/mozilla/fxa-content-server/pull/2377#issuecomment-102157760

## Draft Design
![](https://cloud.githubusercontent.com/assets/68213/7641190/0c0cbe1a-fa56-11e4-9c54-0f440bcf33b4.png)

**Comment by vladikoff** [comment]
@ryanfeeley @johngruen will that ^^^^(screenshot above) be the final design?

**Comment by ryanfeeley** [comment]
Looks good to me. We can tweak colour later. What happens in the add-on? Does it get stuck in an unverified state like Sync? From what I understand, it will remain unchanged (unauthenticated).

**Comment by vladikoff** [comment]
> What happens in the add-on? Does it get stuck in an unverified state like Sync? From what I understand, it will remain unchanged (unauthenticated).

Sorry, which add-on?

**Comment by ryanfeeley** [comment]
@vladikoff Oops, I mean "Service integration"... the panel.
