### ISSUE TITLE
Avatars: "No Gravatar" error should redirect back to /settings/avatar/change 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2428]
## Expected
Should redirect to ` /settings/avatar/change ` if no gravatar found.
If no gravatar found, then the user should consider some other option to upload an avatar.

## Actual

Currently the user will get moved to /settings

![gravatar-change](https://cloud.githubusercontent.com/assets/128755/7657617/53802506-fb01-11e4-91ee-3883e85009ac.gif)

**Comment by vladikoff** [comment]
Should be a really simple patch, but want to check with @zaach and @ryanfeeley first.

**Comment by ryanfeeley** [comment]
This will be okay when we finally remove the /settings/avatar page and just put the "change" link under the Avatar in /settings. Are we ready to do that yet?

**Comment by vladikoff** [comment]
>  Are we ready to do that yet?

I don't think so

**Comment by vladikoff** [comment]
Thanks @eoger & @zaach !! :cake:
