### ISSUE TITLE
OAuth relier scopes should be checked before any user interaction occurs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2435]
Follow on from #2426.

Currently the scopes are only checked when a call is made to /authorization on the OAuth server. This only occurs once the user has accepted the permissions on signin, and after the user verifies their email on signup.

ref https://github.com/mozilla/fxa-oauth-server/issues/257

**Comment by vladikoff** [comment]
from mtg: What are the consequences of not providing the error UX? 
cc @rfk @shane-tomlinson

**Comment by ckarlof** [comment]
@vladikoff is assigned to drive triage on this one.

**Comment by shane-tomlinson** [comment]
> from mtg: What are the consequences of not providing the error UX?
> cc @rfk @shane-tomlinson

The primary driver is to give reliers earlier feedback they messed up.

**Comment by vladikoff** [comment]
> The primary driver is to give reliers earlier feedback they messed up.

I feel like we can deprioritize (not "3 hearts" issue) or even close this unless reliers are having trouble integrating by sending illegal scopes. Let me know your thoughts

**Comment by shane-tomlinson** [comment]
> I feel like we can deprioritize (not "3 hearts" issue) or even close this unless reliers are having trouble integrating by sending illegal scopes. Let me know your thoughts

Sounds fine to me. We can re-open if we see this is really a PITA for reliers.

**Comment by shane-tomlinson** [comment]
Re-opening as a good defense in depth measure.

**Comment by shane-tomlinson** [comment]
Ref #2477, #3505

**Comment by shane-tomlinson** [comment]
Reliers should be testing their integration to catch this problem.
