### ISSUE TITLE
Allow verification_redirect from the verification tab but *not * the original tab?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2436]
Capturing Matt's feedback on the `verification_redirect` feature from #2366:
"""
I implemented the new "verification_redirect" parameter on our staging server.

However, I am seeing an issue that might be confusing for users (and could cause problems).

Basically, with the new setup, you end up with two tabs:

(1) The original tab you started the process with - it is on the "Check your email" screen

(2) The new tab that opens when you click the verification link in the email

In the new setup, once you click the link in the email, BOTH tabs end up redirecting into Pocket - basically attempting to process the signup twice. This is not ideal for a number of reasons.

Seems to me that if "verification_redirect" is on, then the original "Check your email" screen should just stay on that screen and not redirect.

Does that make sense?
"""

Doing the redirect in both tabs was in fact the intended behaviour of the PR, but maybe is not quite the right experience for pocket after all.

A simple option may be to add something like `verification_redirect=only` to trigger the opposite of the original behaviour, leaving the "check your email tab" where it is and completing the flow only in the verification tab.  But there are probably a lot of corner cases to consider.  Maybe we can do something clever with detecting the active tab, like Vlad suggested in https://github.com/mozilla/fxa-content-server/pull/2385/#discussion_r30044874.

Thoughts @ryanfeeley @vladikoff @zaach ?

**Comment by rfk** [comment]
> Maybe we can do something clever with detecting the active tab

Concretely, this might look something like the following logic (in both the "check your email" tab and the verification tab):

* If the tab is active then redirect back to the relier automatically
* If the tab is not active then show the "Proceed" button or similar, so the user is not dead-ended, but also not confused by multiple simultaneous attempts to redirect to pocket in multiple tabs.

**Comment by shane-tomlinson** [comment]
My comments are out of order to yours

> If the tab is active then redirect back to the relier automatically

Let's simplify as much as possible. 99 times out of 100, the active tab is going to be the verification tab. That 1 time in 100, the user would open the verification tab then immediately move to another tab, in which case neither the verification tab nor the original tab may be active.

> A simple option may be to add something like verification_redirect=only

Perhaps not for this PR, but we should consider how a relier would specify the original tab is preferred for reliers like Marketplace. An original tab preference is a bit tricky, because the original tab may have been closed by the user before they verify their email address.  If the relier specifies the original tab but the user has closed the original tab, do we provide an option to fallback to the new tab?

We should also consider how this plays out with the iframe flow. I hope we are not headed for a combinatorial disaster.

[1] - https://docs.google.com/a/mozilla.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA

**Comment by rfk** [comment]
Re-opening this because I'm not sure if we've actually solved the issue to everyone's satisfaction.  Going through the functional tests at:

  https://github.com/mozilla/fxa-content-server/blob/train-38/tests/functional/oauth_sign_up_verification_redirect.js

AFAICT the current behaviour of `verification_redirect=always` can be summarized as:

  * if verifying in a different browser, show the "proceed" button
  * if verifying in the same browser, complete the oauth flow in all tabs

@vladikoff does that sound right?  I could easily be mis-understanding the flow here.

I agree that this is simpler than the previous behaviour and more in line with what the "always" name suggests.  But IIUC, it doesn't address the behaviour that was identified by pocket:

> once you click the link in the email, BOTH tabs end up redirecting into Pocket
> - basically attempting to process the signup twice

If so, then we should keep this open and continue iterating on the flow.

**Comment by vladikoff** [comment]
> > once you click the link in the email, BOTH tabs end up redirecting into Pocket -
basically attempting to process the signup twice

Hey Ryan, we made sure that only one of the tabs "processes the sign up". And what I mean by "processing sign up" is "submitting the code and hitting verify on the oauth server". The second tab will redirect to the relier's redirect_uri after the fact and that tab is assuming that Pocket is already logged in and ready to go. I hope this is the best scenario for Pocket.

**Comment by rfk** [comment]
After chatting about the details with @vladikoff I think we can safely close this out, and open new bugs if we want to iterate further.  Thanks @vladikoff!
