### ISSUE TITLE
Flow doc needs updated with `verification_redirect` behaviors.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2437]
From https://github.com/mozilla/fxa-content-server/issues/2436, ref #2366, #2438 

https://docs.google.com/a/mozilla.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/

A useful table from https://github.com/mozilla/fxa-content-server/pull/2366#issuecomment-100530393

Scenarios that need to be defined for `verification_redirect=always`:

Scenario | Expected behavior on verification tab
------------ | ------------------------------------------------
User verifies in the same browser in a new tab, original tab is still open | auto redirect => relier
User verifies in the same browser in a new tab, original tab is closed | auto redirect => relier
User verifies in the same browser by replacing original | auto redirect => relier
User verifies in a different browser, original tab is still open | button click => relier
User verifies in a different browser, original tab is still closed | button click => relier

**Comment by vladikoff** [comment]
Note: I updated the doc, need Shane to check

**Comment by shane-tomlinson** [comment]
@vladikoff - is the doc up to date with the latest behaviors?

**Comment by vladikoff** [comment]
@shane-tomlinson should be! I updated it only when the final pr landed

**Comment by shane-tomlinson** [comment]
Checked, looks good to me! Closing, thanks @vladikoff!
