### ISSUE TITLE
"Year of birth" dropdown does not update in recent Fennec

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2439]
Hi folks, running a custom-built Fennec Nightly 41, on `/signup` I see the following:
* tap year of birth
* observe pop-up list;
* select any entry (say 1991);
* observe pop-up list disappearing;
* see "Year of birth" selected but not updated (i.e., 1991 is not shown);
* tap any other field (email, say);
* observe "Year of birth" updated (i.e., 1991 is shown).

**Comment by vladikoff** [comment]
Cannot repro with Fennec from https://nightly.mozilla.org/
Do I need to wait a day for it to update?

> a custom-built Fennec Nightly 41

How custom? From `master` ?

**Comment by vladikoff** [comment]
Still works in Nightly today. 
41.0a1 2015-05-20

**Comment by ncalexan** [comment]
Huh.  I cannot explain.
