### ISSUE TITLE
Email marketing opt-in (redux)

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2443]
After a long hiatus, we're revisiting the notion of email marketing opt-in from #992 and #993.  We'll offer an opt-in checkbox on the sign-up page which, when checked, will result in the user being automagically subscribed to a particular newsletter in the basket API.

(This will enable a bunch of other stuff downstream of basket in a new thing called "Journey Builder" but we don't have to worry about that here).

For the user's perspective, there are two things we need to provide:

1) The opt-in checkbox at signup
2) A way to manage to manage opt-in settings after the fact

@ryanfeeley has provided the following design: https://www.lucidchart.com/documents/view/b9161199-e94f-4a1b-8af0-2f8756038605.  In the interests of shipping something sooner, let's pare it down to just the "Primary location" checkbox on initial signup page, plus the "communication preferences" management UI.

The proposed flow will operate as follows:

* User checks the checkbox on sign-up
* We store this fact in the resume token, session, whatever, so we can remember it after verification
* When the user verifies their account, we effect the opt-in by:
  * Generating an OAuth token with scope "basket"
  * Passing this to a proxy server API that consumes OAuth and speaks to basket via secret API key, to effect the change

Driving this client-side means we will lose some fraction of the signups due to not completing the opt-in for whatever reason, e.g. they do it in a different browser, they close the verification tab before it completes, etc etc.  But it reduces the number of things we have to touch to get this done.

Interacting with the checkbox on the management page would do a similar operation to toggle the subscription on or off.

Longer term, we would add OAuth support directly to basket and drop the proxy server API, per https://bugzilla.mozilla.org/show_bug.cgi?id=1051808.

For the "manage all Firefox email preferences" link, we need to get a user-specific token out of basket and embed that in the URL.  The OAuth-authenticated server would also provide an API for doing this.

So I see the following sub-tasks:

- [x] confirm final strings for opt-in text and management screen
- [x] confirm final design with @ryanfeeley 
- [x] create a basket API utility lib, to decouple UI and server-facing work
- [x] implement all the UIs, calling into stubbed-out basket API lib
- [x] implement simple oauth-to-basket proxy API
- [x] hook up basket API lib to talk to the real server
- [x] stand it all up in dev and try it out

That's...a lot of ground to cover, but each compontent seems well-contained and well-defined.  @shane-tomlinson is there anything in here that's a surprise after our discussion yesterday?

**Comment by rfk** [comment]
Per discussion with engagement folks, the opt-in should subscribe the user to a new newsletter called "firefox-accounts-journey".  We can effect this by calling the following API with `optin=Y` to skip basket's native email verification loop:

   http://basket.readthedocs.org/en/latest/newsletter_api.html#news-subscribe

They're also happy for us to target this at just en-US users for initial launch.  This should simplify requirements around getting their language prefs to go through correctly to basket.  I assume we can use able to effect this partial rollout easily.

**Comment by rfk** [comment]
> create a basket API utility lib

For this, I'm thinking a very coarse API along the lines of:

* getEmailPreferencesURL(account)  -> user-specific email prefs management link
* getEmailOptInFlag(account)  -> whether they're currently opted in
* setEmailOptInFlag(account, true/false)  -> set or clear their opt-in state

Just to decouple the two halves of the implementation as early as possible.

**Comment by shane-tomlinson** [comment]
> That's...a lot of ground to cover, but each compontent seems well-contained and well-defined. @shane-tomlinson is there anything in here that's a surprise after our discussion yesterday?

Nothing surprising. 

Adding a tad more context about the settings screen - from Jessilyn Davis:

> The Communication preference screen should *only* at this time have the link to the Email Preference Center and it should say "Email Preferences".  

This significantly reduces the scope of the work needed on the settings page.

Thinking ahead to the subsequent trains, @ryanfeeley's mocks shows the ability to manage the user's preference from the settings page. Will the content server be able to synchronize state with JourneyBuilder, for cases where a user manages their preferences from JourneyBuilder, makes an update, and then visits FxA afterwards?

**Comment by rfk** [comment]
> The Communication preference screen should only at this time have the link to the
> Email Preference Center and it should say "Email Preferences". 

So, just link directly out to basket, no local checkbox for the "Firefox Accounts Journey" thing?  If so, do we just replaces the "Communication preferences" link on the main settings page, with an "Email preferences" link that goes straight to basket?

> for cases where a user manages their preferences from JourneyBuilder

I'd have to get @pmclanahan's thoughts on that one.  IIUC all user prefs management is done through Basket, so if we pull their prefs state out of basket via its API rather than trying to duplicate any of it ourselves, then this should all work OK.

**Comment by rfk** [comment]
After chatting with folks today, IIUC we have the following split underway for this work:

* @shane-tomlinson working on interface changes, possibly based on his work in the previous PR
* @zaach working on the backend oauth-to-basket proxy service
* Me attempting to make myself useful on all the coordination and bits in between

Please let me know if I do not, in fact, understand correctly :-)

**Comment by rfk** [comment]
@zaach, please push any WIP backend stuff you might have for this by end of week, and I can try stringing them all together with the dev basket server while it's US/UK holiday next week.

**Comment by vladikoff** [comment]
This is shipping in Train 38.2 hopefully! :clap:

**Comment by rfk** [comment]
yep! great work everyone, :heart: this team
