### ISSUE TITLE
Pasted passwords do not enable the sign in button

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2450]
When a user pastes a password into the password field to log in (at least on iOS), the sign in button does not become enabled the way it does when they are typed it, but it should.

**Comment by shane-tomlinson** [comment]
Dup of #593, closing.

**Comment by shane-tomlinson** [comment]
Re-opening, #593 is for auto-filled passwords, this is for pasted passwords. It seems like the browser is not sending a `change` or `keydown` event. That's unfortunate.

**Comment by johngruen** [comment]
@ryanfeeley @shane-tomlinson I'd rather not be assigned to this since debugging it probably means building firefox for iOS locally to test. FWIW, this button still does the right thing even though the color isn't changing.
