### ISSUE TITLE
Discuss this design for Edit Profile

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2451]
(sorry, GitHub image upload not working for me atm)

Add Edit Profile Link to Manage Account
https://www.dropbox.com/s/xtku2yaqrbsf4fp/fxa-settings.png?dl=0

New Edit Profile Screen
https://www.dropbox.com/s/mo2fhpbp21bkl4l/fxa-settings-edit-profile.png?dl=0

Deprecated
https://www.dropbox.com/s/mstc25ts7rie7c0/fxa-avatar-deprecated.png?dl=0

**Comment by zaach** [comment]
Should "Name" be "Your name", just in case there's any confusion?

**Comment by ryanfeeley** [comment]
I'm a little allergic to using "Your" (or "My") because it requires consistent application, and I'm hoping that in the context of Edit Profile with the picture above provides the needed context.

Matej pointed out that I should file a bug because on the new COPPA picker we say "How old you are?" but for legal we say "I agree". Switching like this is not great.

**Comment by johngruen** [comment]
@ryanfeeley this doesn't totally jibe with the settings redesign @zaach and i are going to be working on in a few weeks: 

https://www.dropbox.com/s/k5f217dyy2lemj6/fxa-settings.png?dl=0

**Comment by ryanfeeley** [comment]
@johngruen forgot to mention that this is a temporary state so we can start collecting names and avatars.

**Comment by vladikoff** [comment]
The "name" part almost seems like naming the avatar instead of setting my "Display Name" 

![image](https://cloud.githubusercontent.com/assets/128755/7800675/fe715362-02e6-11e5-9321-a7f9a5980c06.png)

**Comment by ryanfeeley** [comment]
Twitter and Slack say simply use "Name", and I like that it's open-ended (vs nickname or full name). I'll do more digging.

**Comment by vladikoff** [comment]
I don't mind "Name", to me it seems the input is too close to avatar changes

**Comment by ryanfeeley** [comment]
Agreed, this might be confusing to people who have never seen a Profile screen before after clicking Edit Profile. :)

**Comment by johngruen** [comment]
@vladikoff @ryanfeeley: confusion should be mitigated by the FxA settings changes @zaach and I are implementing in a few weeks

**Comment by vladikoff** [comment]
Yessss!

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/2336

**Comment by shane-tomlinson** [comment]
ref #1787

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @zaach, @johngruen - can this be considered discussed? If so, can we close this out?
