### ISSUE TITLE
Change the word I to you in legal terms checkbox label

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2453]
So that we're  referring to the user in a consistent manner, we should stick with "you" consistently, including in our ToS checkbox label.

CURRENT:
By proceeding, I agree to…

PROPOSED:
By proceeding, you agree to…

Found in multiple places:
https://github.com/mozilla/fxa-content-server/search?utf8=%E2%9C%93&q=%22by+proceeding,%20i%20agree%22

**Comment by vladikoff** [comment]
@zaach setting "good first bug", is it just a simple change or is there more to it?
