### ISSUE TITLE
`untrusted` relier functional tests - pre-verified test times out.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2463]
Found while working on #2462.

#### local STR/by hand run of the test

1. visit `http://127.0.0.1:10139/api/preverified-signup?email=<email_address>`
1. Complete password/coppa
1. Accept permissions
1. The confirm screen?

#### Expected

1. Either the user is redirected back to the relier OR
1. We explicitly ignore the preVerifyToken for untrusted reliers and update the test to check that the user is redirected to the confirm screen OR
1. This test does not exist because the relier is *untrusted*.

#### Selenium log
```
Test main - oauth permissions - preverified sign up FAILED on firefox 37.0.2 on MAC:
NoSuchElement: [POST http://localhost:4444/wd/hub/session/3c7e09f2-ca29-4417-a8a2-9774078d1ff7/element / {"using":"css selector","value":"#loggedin"}] Unable to locate element: {"method":"css selector","selector":"#loggedin"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: 'a53b301', time: '2015-04-06 21:57:50'
System info: host: 'Shanes-Retina-MBP.local', ip: '192.168.1.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_31'
Driver info: driver.version: unknown
```

**Comment by vladikoff** [comment]
Strange, this used to work, hmmm

**Comment by vladikoff** [comment]
Ah this is due to https://github.com/mozilla/fxa-auth-server/blob/master/.env.dev#L11

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-server/commit/1472e74de8b1d27fe7a64b890ef2a18578576422
