### ISSUE TITLE
views/confirm_reset_password unit test stalls occasionally

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2469]
STR

1. Load the unit tests
1. Refresh until the views/confirm_reset_password test stalls

:cry:

**Comment by vladikoff** [comment]
Cannot reproduce on FF38.0.1 or latest stable Chrome. refreshed with no cache ~10 times.

**Comment by zaach** [comment]
I'll see if I can reproduce.

**Comment by shane-tomlinson** [comment]
Closing for now, I cannot reproduce.

**Comment by shane-tomlinson** [comment]
Hopefully fixed by #3081.
