### ISSUE TITLE
iOS Safari - Private Browsing throws 500

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2479]
![image](https://cloud.githubusercontent.com/assets/128755/7827747/00b2a744-03f9-11e5-94cc-7edd21b57d76.png)

### Expected 

Show a warning that content server does not work with Safari private browsing?

Some reference on the error: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by shane-tomlinson** [comment]
with #2480, Safari Private Browsing mode now shows the "cookies disabled" screen.

![screen shot 2015-07-09 at 13 49 38](https://cloud.githubusercontent.com/assets/848085/8595590/7313709c-2641-11e5-912c-8aa5cc7babeb.png)

**Comment by vladikoff** [comment]
Also checked, this is now fixed
