### ISSUE TITLE
Avatars: displayAccountProfileImage() throws an Unauthorized error on /signin

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2481]
![image](https://cloud.githubusercontent.com/assets/128755/7828075/b5d22336-03fc-11e5-8fb4-64030e4f7aac.png)

**Comment by zaach** [comment]
Probably hitting this: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L248-L249

Note to assignee: We could bail earlier, in avatar-mixin.
