### ISSUE TITLE
Tests: Password reset tests sometimes ask for sign-in 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2483]
![](http://v14d.com/i/5565d491cfca6.png)

Shane linked the following code that we may investigate: 

Refs: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm_reset_password.js#L76 

Refs: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm_reset_password.js#L227

Happens only on TeamCity. Regular password reset and webchannel password reset tests are affected. 

No clear to reproduce this yet. This error happens more when running a lot of tests (i.e using more memory). Slowing down the network does not help. Running this test on its own threw an error once out of ~12 times tried.

**Comment by vladikoff** [comment]
I updated the vnc driver, firefox and rebooted the test machine and this issue went away

**Comment by vladikoff** [comment]
This still happens: 
![image](https://cloud.githubusercontent.com/assets/128755/8853860/d138b3be-312a-11e5-99b5-0ad7b3e40cb3.png)

Which causes this failure:
```
× firefox on any platform - reset_password flow - reset password, verify same browser (34.779s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/f0e91fb7-b642-4b55-88c7-f0895737a6ba/element / {"using":"css selector","value":"#fxa-settings-header"}] Unable to locate element: {"method":"css selector","selector":"#fxa-settings-header"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'vladikoff', ip: '192.168.1.174', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.7.0_67'
Driver info: driver.version: unknown
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1055:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:42:36>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.find  <node_modules/intern/node_modules/leadfoot/Command.js:23:10>
  at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16>
  at testAtSettingsWithVerifiedMessage  <tests/functional/reset_password.js:104:8>
  at Command.<anonymous>  <tests/functional/reset_password.js:373:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:517:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:534:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at Command.<anonymous>  <tests/functional/reset_password.js:106:48>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:517:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:536:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at testAtSettingsWithVerifiedMessage  <tests/functional/reset_password.js:105:8>
  at Command.<anonymous>  <tests/functional/reset_password.js:373:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:517:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:534:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:533:10>
  at Test.registerSuite.reset password, verify same browser [as test]  <tests/functional/reset_password.js:372:10>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
```

**Comment by vladikoff** [comment]
I need help tracking this down

**Comment by vladikoff** [comment]
By taking screenshots on test failures we are able to see what went wrong, here is another one from TeamCity: 
![2015_07_23_081323_4305](https://cloud.githubusercontent.com/assets/128755/8854065/f1c754ae-312b-11e5-9555-11a3eee81ff5.png)

**Comment by shane-tomlinson** [comment]
Let's put this on the priority queue to set aside time, I think this could
easily turn into a time sink. I wonder if this is related to the  other
cached credential problems we see.

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-content-server/pull/2895

**Comment by vladikoff** [comment]
This still happens :(

**Comment by vladikoff** [comment]
If we cannot find a fix we should modify tests to expect a "sign in" view instead of settings

**Comment by vladikoff** [comment]
@shane-tomlinson seems like 10 seconds is not enough of a timeout for functional tests running against a remote browser: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm_reset_password.js#L24 

What should we do?

**Comment by shane-tomlinson** [comment]
> What should we do?

Thanks for digging in, I am going to have a deep dive today. I have a couple of ideas that I could use your feedback on.

1. Increase the timeout - pro - easy, con - users who verify in a second browser need to wait longer.
1. If a `login` message is received from the inter tab channel, stop waiting for the server to say "all is good", we know all is good and can proceed. When experimenting with this last night, this seemed promising.

Maybe a combination of these is a good approach.

**Comment by vladikoff** [comment]
Seems like #3083 fix was not enough
![](http://v14d.com/i/560415064c3ab.jpg)

Running more tests...

**Comment by vladikoff** [comment]
new one http://tests.dev.lcip.org:8111/viewLog.html?buildId=6319&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_

![](http://v14d.com/i/5604217d658c3.jpg)

**Comment by vladikoff** [comment]
Still happens both on Teamcity 8111 and Travis :(

**Comment by shane-tomlinson** [comment]
Huh, and I just spent the day thinking "Seems like travis is mostly fixed." What a PITA.

**Comment by shane-tomlinson** [comment]
@vladikoff - http://tests.dev.lcip.org:8111/viewLog.html?buildId=6796&tab=buildResultsDiv&buildTypeId=fxa_StomlinsonDevLcipOrg   maybe... maybe!

**Comment by vladikoff** [comment]
wooo so greeeeen

![](http://v14d.com/i/562a630ec3f05.png)

**Comment by vladikoff** [comment]
This was fixed by Shane! @shane-tomlinson woo hoo

**Comment by shane-tomlinson** [comment]
FIXEEEDDDD!!!!
