### ISSUE TITLE
Delete accessToken when account is removed from localStorage

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2486]
We cache `accessToken`s in localStorag so that we can display profile images with minimal latency, but we don't currently clean up when the account is removed. We should tidy this up.

**Comment by vladikoff** [comment]
@zaach was this fixed already? we removed accessTokens from localStorage

**Comment by zaach** [comment]
This was about deleting them from the server, but we're using ephemeral tokens now so not really needed.
