### ISSUE TITLE
instead of passing clients around, create them on demand

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2487]
From https://github.com/mozilla/fxa-content-server/pull/2452/files#r30813006:

@shane-tomlinson

> @zaach - Except for fxa-client, I don't think any of these clients save any state. Instead of creating all these clients on startup and passing them around, we could just pass in a list of service urls and have the callers of the clients create them when needed? Dunno.

@zaach

> :+1: :+1: We could allow both ways (since passing clients is still useful for testing) and default to using the URL list.

**Comment by vladikoff** [comment]
Renamed in favour of https://github.com/mozilla/fxa-content-server/issues/4983
