### ISSUE TITLE
"The page is temporarily unavailable" message in banner

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2490]
Found in https://uxwip.dev.lcip.org/ver.json

``` js
{
  version: "0.35.0",
  commit: "849292a04aecf85d2abf4ddf8b36dabc24000534",
  l10n: "7e0bf097f8",
  tosPp: "c8e5dadb24"
}
```
### Steps to reproduce:
1. Go to https://uxwip.dev.lcip.org/signup
2. Create a new account.
3. Click [Sign up]
### Actual results:

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7871474/ef6c9a56-0544-11e5-8fb0-8d4cd2577746.png)
### Expected results:

Fewer HTMLs.

**Comment by pdehaan** [comment]
Same thing happens w/ [Sign in](https://uxwip.dev.lcip.org/signin).
Not sure if the server(s) are all running, but I'm guessing this may be an edge case w/ fxa-content-server where we aren't intercepting some error state and still dumping the full server response, which may be raw HTML.

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/8938001/d6df6cf6-3529-11e5-84e7-a772bb4a5c3e.png)

This was fixed in the recent trains with better error handling. Tested with a custom server responses. Please let us know if this happens again

**Comment by vladikoff** [comment]
nvm still happens 
![image](https://cloud.githubusercontent.com/assets/128755/8947104/e2c1e19e-3564-11e5-97f2-6db079af36d1.png)

**Comment by shane-tomlinson** [comment]
that's fugly. re-opening.

**Comment by vladikoff** [comment]
to find a  fix for this make sure the "mock" server responds with a html 502, not a 404

**Comment by shane-tomlinson** [comment]
Dup of #2059, closing.
