### ISSUE TITLE
Correlate metrics across email verification

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2491]
Right now we sample metrics from a subset of page views in a totally random manner.  This means that if the user creates an account and then follows the link to verify their email, there's no correlation between the metrics from these two flows.  We might receive metrics events from either, neither, or both.

Let's try to add a bit of determinism back in so that we can be more confident in the meaning of verification-related metrics.  One possibility I was discussing with @vladikoff, would be to have a query param that forces metrics collection to take place, and set it on outgoing emails if we're collecting metrics from the originating page.

**Comment by rfk** [comment]
For a concrete ask related to this functionality, see https://bugzilla.mozilla.org/show_bug.cgi?id=1162192.

**Comment by shane-tomlinson** [comment]
ref #2542, #2101

**Comment by rfk** [comment]
We'll get most of what we need for this out of #2456 and #2542, so I closed the original PR and will pick this up again once those are landed.

**Comment by shane-tomlinson** [comment]
Aside from Google Analytics metrics, specific metrics asked for:
* `campaign`
* `entrypoint`

ref #2579

**Comment by shane-tomlinson** [comment]
ref #2780

**Comment by shane-tomlinson** [comment]
I'm closing this. The last bit was completed with #2780.
