### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2493]
Was trying to quickly test https://email.dev.lcip.org/signup in Chrome, and noticed this gem in the developer tools console:

> #### _Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/._

For some reason Chrome isn't letting me see the source code for that line, but it's minified anyways so it may not be uber helpful.

ref #2577

**Comment by pdehaan** [comment]
![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7890462/0df6a92e-05fb-11e5-9569-75fe3c155046.png)

**Comment by shane-tomlinson** [comment]
I suspected this might happen some day. Are metrics still being sent for the time being?

Time to move to the [sendBeacon API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) for browsers that support it.

That, or we send event stream data more frequently, like every time there is an event. I don't really like that approach though.

**Comment by shane-tomlinson** [comment]
For those wondering about the link to whatwg - https://xhr.spec.whatwg.org/#the-open%28%29-method

**Comment by rfk** [comment]
I'd be curious how frequently we navigate ourselves away from the page (e.g. when completing an oauth redirect) versus how frequently we get unload by user action.  In the former case we could do an async XHR and ensure it completes before proceeding.

**Comment by shane-tomlinson** [comment]
Another for you Phil!

**Comment by philbooth** [comment]
@shane-tomlinson @vladikoff

I've been working on this issue today and spotted something in my tests that I wanted to check with you guys.

Currently, if the `/metrics` request fails, the `events` list is still cleared, which seems wrong to me. Is that a bug or is it correct behaviour?

**Comment by vladikoff** [comment]
> Currently, if the /metrics request fails, the events list is still cleared, which seems wrong to me. Is that a bug or is it correct behaviour?

Does not sound like correct behaviour. However this issue would be minimal, the route responds right away: https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/post-metrics.js#L19 

I guess only things like connection issues / timeout would affect this. We can fix that if you want

**Comment by philbooth** [comment]
Cool, thanks for the info. :)

**Comment by philbooth** [comment]
@vladikoff @shane-tomlinson

Couple of questions:

1. It feels like there are two independently-reviewable changes in here:

   1. Using `sendBeacon` if it is available, falling back to XHR if it isn't.
   2. Explicitly flushing metrics before we navigate away from the app.

   Would you prefer them as separate PRs or together?

2. Is there an easy way / are there any docs about how to test the OAuth flow locally? Presumably `fxa-local-dev` includes everything I need, but I'm not sure how to actually invoke the process as a user.

**Comment by vladikoff** [comment]
> Is there an easy way / are there any docs about how to test the OAuth flow locally? Presumably fxa-local-dev includes everything I need, but I'm not sure how to actually invoke the process as a user.

OAuth Trusted client: http://127.0.0.1:8080/
OAuth Untrusted client:  http://127.0.0.1:10139/

**Comment by philbooth** [comment]
Thanks! :)

**Comment by vladikoff** [comment]
> Using sendBeacon if it is available, falling back to XHR if it isn't.

I guess this will get rid of the warnings in Chrome. any other advantages?

> Explicitly flushing metrics before we navigate away from the app.

We already do that or try to do that with the unload event.

**Comment by philbooth** [comment]
> We already do that or try to do that with the unload event.

Right, but in order to use `unload` we have to send them synchronously and I thought the point of this issue was that we shouldn't do that because it's deprecated?

By "explicitly flushing", I meant Ryan's suggestion of postponing navigation until an asynchronous flush has completed, not flushing synchronously on `unload`.

**Comment by shane-tomlinson** [comment]
I have not reviewed/tested this yet - how tough is it to tease the two suspected PRs apart?

**Comment by philbooth** [comment]
> I have not reviewed/tested this yet - how tough is it to tease the two suspected PRs apart?

Not tough at all. The linked PR, #2737, only addresses the `sendBeacon` bit. I am working on the postponed navigation bit separately. :)

**Comment by philbooth** [comment]
Fwiw, the postponed navigation changes are also now done in a separate branch: [phil/issue-2493-postponed-navigation](https://github.com/mozilla/fxa-content-server/compare/phil/issue-2493-postponed-navigation?expand=1)

There is some conflict between the two changesets however, so I'm not going to open a PR on this one until the other one has progressed one way or another. I just wanted to note the branch down for the record.

**Comment by shane-tomlinson** [comment]
re-opening until [the postponed navigation PR](https://github.com/mozilla/fxa-content-server/compare/phil/issue-2493-postponed-navigation) is merged.
