### ISSUE TITLE
Where should the Basket proxy live?

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2494]
I had a chat with Travis about this curious growth on the content server known as the "Basket proxy". 

A couple observations: 
* It's not clear how temporary (or not) this is intended to be, but temporary things tend to hang around a while.
* IMO, this proxy is outside the core concern of the content server.

I scratched my head a bit, and:

**Should this proxy live on the FxA profile server?**

Subscribing to an newsletter is likely a concern of the user's FxA profile, the profile server already has code paths for verifying OAuth tokens, and if this proxy rocks on for a while, the profile server also seems like a more appropriate home.

**Comment by rfk** [comment]
I intend for this to be *very* temporary, but that's no guarantee of what will happen in practice.

Perhaps we should just spin it out into an entirely separate service?  This seems more inline with how we plan for it to work long-term, talking directly to basket as a separate service.  @zaach if we did that, would it complicate (or perhaps simplify?) the testing situation for the code in the content-server?

**Comment by shane-tomlinson** [comment]
#2535 was opened to extract the basket proxy server into its own repo, closing.
