### ISSUE TITLE
Avatar blank when session is expired

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2495]
When the user goes to Manage their account from desktop, and their session is expired on the web, the avatar does not show. Not shown: when I signed in, the avatar displayed perfectly in /settings.
![manage](https://cloud.githubusercontent.com/assets/68213/7922210/bbc7138e-0878-11e5-9d71-52b78ff7153f.gif)

**Comment by shane-tomlinson** [comment]
Nice spot @ryanfeeley

**Comment by vladikoff** [comment]
I can reproduce this 
![image](https://cloud.githubusercontent.com/assets/128755/8686021/7f8b1164-2a37-11e5-8acd-358ce07da387.png)

**Comment by shane-tomlinson** [comment]
@vladikoff: is this in progress, or should it be moved back to "ready" or "next"?

**Comment by edmoz** [comment]
we this on Train-43 if possible.
