### ISSUE TITLE
Marketing email signup copy is easy to miss on /signup

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2496]
### Steps to reproduce:
1. Go to https://email.dev.lcip.org/signup
2. Look at the checkbox label copy above the giant [Sign up] button.

### Actual results:
Copy is easy to miss and gets somewhat lost amongst the TOS/PN link copy.

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7922664/a11255c8-0862-11e5-8975-70df9f33c073.png)
**Figure 1:** Regular viewport.

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7922673/aa657c2c-0862-11e5-8548-187a31a6217d.png)
**Figure 2:** Narrower viewport, TOS/PN text shrinks, but not the newsletter link; so it stands out a bit more.

### Expected results:
Not sure if the copy should be bolded or something weight-ier?

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7922720/ed2aff1e-0862-11e5-9532-e99223e0dd8c.png)
**Figure 3:** Added an inline `font-weight:bold;` but I think that causes the text to wrap to 2 lines in Chrome.

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @johngruen - what are your thoughts?

**Comment by ryanfeeley** [comment]
Compared to the logo, the heading, the username, password, year of birth, legal terms, sign up button and sign-in link, it's the least important thing on the page and weighted appropriately. A little space above wouldn't hurt though. @johngruen?

**Comment by johngruen** [comment]
@pdehaan @ryanfeeley made the top margin 20px in the 'big' responsive view to give a bit more separation. I think that's all we should do.
