### ISSUE TITLE
Enable avatars for all accounts?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2497]
The avatar UI is currently able-d off in production, restricted to only users on mozilla domains.  Are we ready to enable it for all users, or should we wait until e.g. the settings page refresh has landed?

@zaach thoughts?

**Comment by vladikoff** [comment]
We have a few issues open re: avatars https://github.com/mozilla/fxa-content-server/issues?q=is%3Aopen+is%3Aissue+label%3Aavatars

**Comment by zaach** [comment]
Dupe of #1582.

**Comment by rfk** [comment]
thanks @zaach :-)
