### ISSUE TITLE
Communications preferences page is a bit vague on what email you're signing up to/for

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2498]
### Steps to reproduce:
1. Sign up at https://email.dev.lcip.org/signup
2. After verifying your account, click on the ["Communication preferences" link](https://email.dev.lcip.org/settings/communication_preferences) on the [/settings](https://email.dev.lcip.org/settings) page.

### Actual results:

The copy is pretty generic, and I don't really know what content I'm signing myself up for.

![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923013/ddfabe10-0864-11e5-8e06-55f5a98ff712.png)
**Figure 1:** Communication preferences page

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/7923028/f0ad28b8-0864-11e5-9bd1-ff1c74b2628b.png)
**Figure 2:** Signup page

If I click that vague "Email preferences" link in the Communication preferences page, it takes me to a Newsletter Subscriptions page which shows the 1-2 newsletters that I have been signed up for ("Firefox & You" and "Firefox Accounts Journey (English only)".

I wasn't sure if we should add more copy to the communication preferences page which gives more information about what you're signing up for:

> _**Firefox & You**
> A monthly newsletter and special announcements giving you tips to improve your experience with Firefox on your desktop and Android device._

Or I ~~Googled~~ Yahoo!ed for "Firefox & You" and found this page: https://www.mozilla.org/en-US/newsletter/ which has some good copy:

> _Subscribe to monthly updates and keep current with Mozilla news, including the latest tips and tricks for getting the most out of your Firefox browser. It’s the perfect way for us to keep in touch!_

**Comment by rfk** [comment]
This wording is from the engagement folks and IIUC it's intentionally generic; the more generic the wording, the more stuff we can potentially send you down the track if it seems like a good idea, without getting into legal trouble.

The one to watch here is "Firefox Accounts Journey" which is the product engagement stream, where you'll be sent news and tips on all the cool things you can connect to with your Firefox Account.  Like Sync.  And Hello.  Maybe even Pocket.  And all the stuff we haven't even implemented yet.

**Comment by pdehaan** [comment]
@rfk,
![](https://31.media.tumblr.com/06de321738c175c27f391cd2960d2e48/tumblr_inline_nox99at6wG1raprkq_500.gif)
**Figure 3:** SO MANY FEELINGS!

**Comment by rfk** [comment]
Pretty much sums it up...

**Comment by rfk** [comment]
I'm going to close this out, if we feel strongly about changing it we should file a bugzilla issue and loop in engagement, legal, etc
