### ISSUE TITLE
"Email preferences" link is vague and doesn't inform you that it points to an outside site

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2500]
### Steps to reproduce:
1. Go to https://email.dev.lcip.org/signup
2. Create and verify your account.
3. Go to https://email.dev.lcip.org/settings/communication_preferences
4. Click the "Email preferences" link.
### Actual results:

FxA is replaced with https://www-dev.allizom.org/en-US/newsletter/...
### Expected results:

Add `target="_blank"` to the Email preferences link? Add some icon which lets the user know that the link may open in a new tab/window. I think Wikipedia does this for external links maybe.

**Comment by ryanfeeley** [comment]
@pdehaan Are you thinking of something more like this? 
![mozilla-email-preferences](https://cloud.githubusercontent.com/assets/68213/7926275/0c6991ac-089e-11e5-9fce-22e512597a0f.png)

@johngruen should have a say here. He and @zaach will be tackling this and other pages shortly.

I'm not sure I'm a fan of having an external link icon, but opening in a new tab makes sense.

**Comment by pdehaan** [comment]
@ryanfeeley Yeah, that's what I was thinking of.
Or at least the `target=_blank`. I was just a bit weirded out since I think this is the only link where we go to an external site (apart from the TOS/PN pages).

**Comment by shane-tomlinson** [comment]
@zaach - are you handling this page with your settings refresh?

**Comment by johngruen** [comment]
@ryanfeeley @zaach: ryan's proposal should work

**Comment by shane-tomlinson** [comment]
@johngruen - is this part of your settings refresh? If not, I nominate @philbooth to work on this.

**Comment by shane-tomlinson** [comment]
@zaach - is this part of the settings 2.0 work?

**Comment by zaach** [comment]
No, this can be handled independently of the settings related changes.
