### ISSUE TITLE
Communication preferences page is slow to render

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2501]
### Steps to reproduce:
1. Go to https://email.dev.lcip.org/signup
2. Register and verify your account.
3. Go to https://email.dev.lcip.org/settings/communication_preferences

### Actual results:
Page is slooooowwwwww...
![firefox_accounts](https://cloud.githubusercontent.com/assets/557895/7923544/deb250c6-0868-11e5-8c5c-f182c3780159.png)

Eventually the page loads and displays this...
![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923551/f0e697e8-0868-11e5-9f84-a1c881e01bc9.png)

Not sure if we can just render the page immediately since the only thing that we presumably need to wait for is whether we should show "Subscribe" or "Unsubscribe" button label.

### Expected results:
Faster rendering. I think this is partially because the basket stage server is slow and this is muuuuch better in prod. But still.

**Comment by rfk** [comment]
> since the only thing that we presumably need to wait for is whether we should show
> "Subscribe" or "Unsubscribe" button label.

We also need to wait for the special token to include in the "email preferences" link; thankfully both pieces of data are available in a single request!

**Comment by pdehaan** [comment]
So theoretically we could initially display:

> **Communication preferences**
> Get the latest news about Mozilla and Firefox.

And then possibly disable the Subscribe/Unsubscribe button and use a spinner for the label, display the Back link, and either hide the "Email preferences" link or disable it until we hear back from Basket server.

At least that way the page renders something immediately.

**Comment by zaach** [comment]
Closing this. Open a new issue if this is still a thing on the new settings page.
