### ISSUE TITLE
Some timing/rendering issues with subscribe/unsubscribe messages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2502]
### Steps to reproduce:
1. Go to https://email.dev.lcip.org/signup
2. Register and verify your account.
3. Go to https://email.dev.lcip.org/settings/communication_preferences
4. Subscribe or Unsubscribe from the newsletter.

### Actual results:
The button caption doesn't always stay in sync with the status messages.
![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923641/b882324e-0869-11e5-82fb-be723be3ca9e.png)
**Figure 1:** After clicking the "Unsubscribe" button.

But things generally look kosher if I refresh the page, so I don't know if this is a timing issue or rendering issue perhaps:

![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923669/fc2191b6-0869-11e5-870d-39fc3557991f.png)
**Figure 2:** After a page refresh (note the correct button caption now)

**Comment by pdehaan** [comment]
It doesn't seem to _always_ happen, but in my informal testing it seems to be happening for me 50% of the time.

![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7923766/e2bd9cdc-086a-11e5-8162-baa4874ec277.png)

**Comment by shane-tomlinson** [comment]
@pdehaan - is this still a problem on latest? I've been trying it over and over and have not been able to reproduce.

**Comment by pdehaan** [comment]
@shane-tomlinson I don't think this will repro on latest.dev.lcip.org since that uses a NullBasket server proxy. I'll test in stage shortly.

**Comment by shane-tomlinson** [comment]
Thanks @pdehaan - I see it now.
