### ISSUE TITLE
Add permission screen for Gravatar profile image option

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2503]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1140644, we should let users know their email will be shared with Gravatar if they choose that option. We can add a tooltip with the appropriate messaging.

@ryanfeeley Got any input on the copy we should use here?

**Comment by vladikoff** [comment]
I don't have access to that bug but I'm not sure if a tooltip is enough of a warning for mobile.

**Comment by ryanfeeley** [comment]
@vladikoff True, a tooltip as depicted would leave mobile users behind.
![check-wordpress-gravatar](https://cloud.githubusercontent.com/assets/68213/7926446/bee88714-08a0-11e5-80a6-4ee50c6a7343.png)

Some assumptions:
* Users seeing an unfamiliar name and icon in this context will assume it’s link to a 3rd party
* Users who are not comfortable with Gravatar know what it is, and not to click on the icon
* An "are you sure?" dialog is an extra step that would annoy Gravatar users

Safe or challenge?

**Comment by rfk** [comment]
@vladikoff  I added you to the bugzilla bug.  Please call out concerns w.r.t. mobile users over there for completeness; since we have legal involved we need to make sure everyone has full context on the decisions here.

**Comment by pdehaan** [comment]
Or, if the user clicks the Gravatar button, we could show an `alert()` or `confirm()` dialog.

**Comment by johngruen** [comment]
@ryanfeeley why don't we slap a little disclaimer on the bottom using the same style as the tos/pn string on /signup? tooltips are so 1998

**Comment by zaach** [comment]
How it'd look on the current Avatar screen (using mika's copy):
<img width="497" alt="screen shot 2015-07-07 at 5 05 10 pm" src="https://cloud.githubusercontent.com/assets/3903/8560276/05c4aeba-24cb-11e5-987d-5eb35c3ba0d0.png">

And the new modal:

<img width="572" alt="screen shot 2015-07-07 at 5 13 32 pm" src="https://cloud.githubusercontent.com/assets/3903/8560344/902d4670-24cb-11e5-99cc-4433df77ac25.png">

I can go ahead and include this in the settings refresh if we're cool with it.

**Comment by ryanfeeley** [comment]
I've never seen that copy before, nor does it exist in my inbox. How about remove the copy and use the screen we use for Pocket when the user clicks the Gravar icon. This is a permission request, and any user clicking this will likely know what Gravatar is to begin with.

<img width="504" alt="gravatar-permission" src="https://cloud.githubusercontent.com/assets/68213/8573125/f73d7140-255d-11e5-8923-09d075e6c23f.png">

**Comment by zaach** [comment]
@ryanfeeley I like it :+1: . Oh, and the copy was from: https://bugzilla.mozilla.org/show_bug.cgi?id=1140644#c2

**Comment by ryanfeeley** [comment]
Oh yeah, that bug.

**Comment by ckarlof** [comment]
Great, I'd like to see this ready in time for Fx41 when avatars go live in release channel for Firefox.

**Comment by edmoz** [comment]
sounds like we have a plan to move forward with the screen.  Legal is going to update the PN and we should have a clear path to ship.

**Comment by vladikoff** [comment]
Done!
