### ISSUE TITLE
Unexpected errors on iPhone Safari 8 and others  

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2506]
Seeing some 404s in production for this. I cannot exactly count how many via Kibana (if anyone can filter it somehow please let me know). 

GET /unexpected_error?uid=[uid]&code=[code]&service=sync HTTP/1.1
more info in content-nginx-logs-2015-05-31

Seems to be always `service=sync`

**Comment by vladikoff** [comment]
@jrgm is there a way to get more data on how many errors we are getting on this?

**Comment by vladikoff** [comment]
and maybe lock down which iPhone Safari versions are affected

**Comment by issues-bouncer** [comment]
Hey @vladikoff, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by jrgm** [comment]
Here's the details you were looking for: 
https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20Content%20Unexpected%20Error

**Comment by vladikoff** [comment]
Blocked by https://github.com/mozilla/fxa-content-server/pull/2529

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/8489102/28a79278-20e6-11e5-8b9f-ff2c6c2e4393.png)

**Comment by vladikoff** [comment]
@jrgm Hey, is there a way to get a full user agent string for one of these errors? The kibana "iPhone 600" is not enough. It would be really useful to get the iOS Version string.
such as `Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X)`

If we confirm that this is iOS 5.0 then we need to polyfill .bind

**Comment by vladikoff** [comment]
@jrgm something **not from today**, because I did a few tests with iOS5

**Comment by jrgm** [comment]
I sent you a sample for data from June 30 from one webhead.

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-content-server/pull/2708
