### ISSUE TITLE
Passing in unknown scopes causes the login to hang just prior to redirect

### ISSUE THREAD

**Issue by crankycoder** [mozilla/fxa-content-server#2508]
I just copied this over from https://github.com/mozilla/fxa-oauth-server/issues/264

During testing with MozStumbler, I noticed that if I pass in an unknown scope - in this case 'mozstumbler', the login screen hangs after login.   The button remains disabled and I have to cancel.  It's not apparent that an error occured as no error message is shown.

I get the same behaviour if I include 'profile:avatar' instead of mozstumbler in the list of scopes.

The login URL I used was :

https://stable.dev.lcip.org/oauth/signin?client_id=d0f6d2ed3c5fcc3b&state=99&scope=profile:email%20profile:display_name%20mozstumbler&redirect_uri=http://mycallback_url_here

![sign_in_continue_to_insecure_mozilla_stumbler_leader_board](https://cloud.githubusercontent.com/assets/4829/7943948/ea69ba1c-0935-11e5-883f-582d2fd08773.png)

**Comment by shane-tomlinson** [comment]
Is this a dup of https://github.com/mozilla/fxa-content-server/issues/2435?

**Comment by rfk** [comment]
I suspect it's a dup, although it doesn't sound like this even triggered the error UI that was added in the predecessor of that bug (#2426)

**Comment by shane-tomlinson** [comment]
@crankycoder - Did you type the password in the input box when the screen loaded the first time, change the scopes in the URL bar, forcing the page to reload and the password to be pre-filled and the sign in button to not change state? If so, this may also be a partial dup of #593 and #2450, which may have just been fixed in #2509.

**Comment by vladikoff** [comment]
from meeting:

does not react to 404s from untrusted clients.

**Comment by vladikoff** [comment]
from meeting: 

should show error, nothing else

**Comment by vladikoff** [comment]
@shane-tomlinson did recent improvements to the oauth param validation fix this?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson did recent improvements to the oauth param validation fix this?

It does not, at least not for trusted reliers. For trusted reliers we allow anything. The hang still happens.

**Comment by vladikoff** [comment]
need to check if this still happens...

**Comment by vladikoff** [comment]
cc @vbudhram @vladikoff

**Comment by vbudhram** [comment]
Tested this with URL from above and it does not freeze on login. Closing this until further notice.
