### ISSUE TITLE
metrics: fxa.content.error.signup.auth.1012 is not working

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2512]
1012 error is missing from datadog

**Comment by vladikoff** [comment]
1016 is also missing

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/blob/b6e5b00fa4598787abae10eaeb6f74b8c816684b/app/scripts/lib/auth-errors.js

**Comment by shane-tomlinson** [comment]
These errors are displayed, but never logged. :/ https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/coppa/coppa-date-picker.js#L89
