### ISSUE TITLE
metrics: fxa.content.error.signup.unknown_namespace.101

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2513]
for some reason, error 101 reports with unknown_namespace

![image](https://cloud.githubusercontent.com/assets/128755/7964851/01dd85fe-09e8-11e5-847e-5ef4e67abac8.png)

**Comment by vladikoff** [comment]
When this is fixed we need to make sure to update the existing dashboard to include the fixed namespace

**Comment by shane-tomlinson** [comment]
ref #2623
