### ISSUE TITLE
Disable Gravatar option

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2515]
Until #2503 is resolved, we should hide the Gravatar option. This could be a feature flag that we switch on/off with able.

**Comment by shane-tomlinson** [comment]
@zaach - disAble it

**Comment by pdehaan** [comment]
@shane-tomlinson: 
![](http://s2.quickmeme.com/img/12/12710061ec1b8ec6b7fa09807a2b4f6c7c208950ddab1952d95037fcb0c754fc.jpg)

**Comment by zaach** [comment]
closed by #2548.
