### ISSUE TITLE
Multiple messages logged to console if Gravatar image cannot be found

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2519]
### Steps to reproduce:
1. Create a new account at https://accounts.firefox.com/
2. Verify your account and go to https://accounts.firefox.com/settings/avatar/change
3. Set your account picture to "Gravatar"

### Actual results:
Two messages get logged to your console saying:
> "No Gravatar found"

![account_picture](https://cloud.githubusercontent.com/assets/557895/7972698/7a690794-0a03-11e5-8b9b-28eec37a9878.png)

### Expected results:
1 error message is fine (if we must) but 2 seems excessive.
It almost seems like one is coming from the API and the other may be from the ephemeral message.

**Comment by vladikoff** [comment]
remove error logging from this
