### ISSUE TITLE
Display change avatar link for users that have an avatar

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2523]
From today's fxa-web-coordination meeting:

> @zaach: let's expose it on the settings page if the user has a mozilla email OR they've added a profile image (e.g. by visiting the avatar change page directly from the browser settings page)

---

Not sure where else we may need/want to make this change.
I think we show an avatar in the **force_auth** flow, as well as oauth signin

![sign_in_to_continue_to_firefox_marketplace](https://cloud.githubusercontent.com/assets/557895/7991031/00d1deae-0aaa-11e5-9013-f04e7d478958.png)

**Comment by zaach** [comment]
To clarify my comment, I think we should show the "Change avatar" *link* on the settings page if they have a mozilla email address or they've already set a profile image. Currently, even if they have a profile image set, they won't see the change link unless they have a mozilla email.

**Comment by shane-tomlinson** [comment]
I'm a bit lost about the exact request here. :/

Is it to hide the avatar on the signin/force_auth page if the user does not have an avatar (ref #1787) or is it to expose the link on the settings page if the user has an avatar/mozilla address, or is it both?

**Comment by zaach** [comment]
It is "to expose the link on the settings page if the user has an avatar/mozilla address".

**Comment by zaach** [comment]
Closed by #2547
