### ISSUE TITLE
Basket/proxy mishandling email addresses with non-alphanum characters

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2524]
STR

1. Sign up with foo+bar@example.com
2. Try to subscribe and unsubscribe, and watch network traffic in browser
3. /lookup-user appears unable to remember state of user
4. Instead sign up as `foo@example.com`. No more confusion. 

Haven't traced through whether its the proxy or basket itself that has the problem, but I think it may be in the proxy from what I have seen.

**Comment by rfk** [comment]
At a guess, we're not URL-encoding the `+` properly and it's being translated into a space.
