### ISSUE TITLE
Update AUTHORS file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2525]
Yay! We've had a few new contributors helping on the project lately, so we should refresh the AUTHORS file.

I ran `npm run contributors` and then diffed the file and got this:
```
$ git diff AUTHORS
diff --git a/AUTHORS b/AUTHORS
index e516e05..b4c088a 100644
--- a/AUTHORS
+++ b/AUTHORS

@@ -1,6 +1,6 @@
 Andrew Chilton
-Atul Vaibhav
 Austin King
+ava14
 Benson Wong
 besnik@programeshqip.org
 Brian Warner
 ...
 Chris Karlof
 ckarlof
 Dan Callahan
 Danny Coates
+Edouard Oger
 Eric Le Lay
 Francois Marier
 Jamon Camisso
 ...
 Jed Parsons
 John Gruen
 John Morrison
 johngruen
+Jon Petto
 Mark Striemer
 markh@babelzilla.org
 matjaz@mozilla.com
 ...
 Nick Chapman
 Peter deHaan
 petercpg@mail.moztw.org
 Renoir Boulanger
+Riadh Chtara
 riadhchtara
 Ryan Kelly
+Sai Prashandth Chandramouli
 Sam Penrose
 Sean McArthur
 Shane Tomlinson
```

Everything looks good, with FIVE new contributors (Sai, Riadh, Jon Petto, Edouard, ava14), but it looks like we _LOST_ a contributor too: "Atul Vaibhav".
Looks like Atul was added by @shane-tomlinson in https://github.com/mozilla/fxa-content-server/commit/b2a0b54a3f6400028c400b0b6888b95b6a626371, so not sure if Atul was added manually, or why we'd see a contributor disappear from the generated list -- but thought it was worth pointing out in case we need manually re-add the name again (and then every time we regenerate the file).

**Comment by rfk** [comment]
Is Atul the same person as "ava14"?

**Comment by pdehaan** [comment]
@rfk Not sure. I checked https://github.com/ava14 but there wasn't any personal details.

**Comment by shane-tomlinson** [comment]
> @rfk Not sure. I checked https://github.com/ava14 but there wasn't any personal details.

It is, if you do a `git log`, you'll see it in the email address.

> +Riadh Chtara
> riadhchtara

This is the same person as well. Maybe swap the 2nd for the first.

**Comment by pdehaan** [comment]
@shane-tomlinson,
True, "riadhchtara" is in the AUTHORS file twice, presumably because of a changed name or Git author setting between commits. Same w/ "Chris Karlof" vs "ckarlof", "John Gruen" vs "johngruen" above. Since the extraction and generation is automated, probably not worth trying to [intelligently] remove dupes after each regeneration. \*shrug\*

**Comment by vladikoff** [comment]
IMHO We cannot keep guessing which username, nickname or name developers want to use. Updated the file via script.

**Comment by shane-tomlinson** [comment]
> IMHO We cannot keep guessing which username, nickname or name developers want to use. Updated the file via script.

Agreed, I guessed the name because I didn't know there was a script. :/
