### ISSUE TITLE
Email preferences link doesn't work in latest

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2526]
Found in https://latest.dev.lcip.org/ver.json (commit 3ba608667545b88763f8459f3ea0603b46676da0)

```json
{
    "version": "0.38.1",
    "commit": "3ba608667545b88763f8459f3ea0603b46676da0",
    "l10n": "219c7a853a",
    "tosPp": "cd433a143e"
}
```

---

### Steps to reproduce:
1. Go to https://latest.dev.lcip.org/settings/communication_preferences
2. Toggle the Subscribe/Unsubscribe button a couple times.
3. Click on the "Email preferences" link.

### Actual results:
My "Email preferences" link goes to https://www-dev.allizom.org/newsletter/existing/12 (the "12" in the URL seems suspicious, as I thought this used to be a wacky UUID/SHA).

The link ends up resolving to https://www-dev.allizom.org/en-US/newsletter/recovery/ which says:

> **The supplied link has expired or is not valid. You will receive a new one in the next newsletter, or below you can request an email with the link.**

![newsletter_email_recovery_ _mozilla](https://cloud.githubusercontent.com/assets/557895/7995527/63e5ca7a-0acb-11e5-9703-501e1d0f3ca3.png)

### Expected results:

Show me some email preferences where I can toggle some checkboxes and radio buttons.

**Comment by rfk** [comment]
@pdehaan if you can repro this consistently, it'd be great to see a devtools network dump of the requests/responses to the basket proxy.

**Comment by pdehaan** [comment]
Interestingly, if I test this on https://email.dev.lcip.org/settings/communication_preferences it generates an Email preferences link like this:

https://www-dev.allizom.org/newsletter/existing/57829c33-a1b3-40d8-9450-b2bafc8cd9cf

![newsletter_subscriptions_ _mozilla](https://cloud.githubusercontent.com/assets/557895/7995562/e83855ea-0acb-11e5-9194-b9037fb38c68.png)

---

```json
{
    "version": "0.38.1",
    "commit": "5046377384303c3eb7999b1e753f863f7f6e6178",
    "l10n": "18e3e8b617",
    "tosPp": "dcbc323819"
}
```

**Comment by rfk** [comment]
Ah, this may be using the "null basket server" that @zaach made for testing, rather than talking to the real basket.  In which case the email-preference link would not be expected to work.

**Comment by pdehaan** [comment]
@rfk: you're in luck, it fails 100% of the time, every time.

![communication_preferences](https://cloud.githubusercontent.com/assets/557895/7995600/57d4b376-0acc-11e5-82c4-934ce3b7f13c.png)

**Comment by pdehaan** [comment]
@rfk,

> Ah, this may be using the "null basket server" that @zaach made for testing

Good point! It was unusually fast for Basket. And that'd probably explain why I'm token "12" instead of something more GUID-ey.

**Comment by rfk** [comment]
Heh.  OK, this deploy is almost certainly using the null-basket-server which doesn't have support for email preferences link.  We need to make that work for QA purposes, but I'm confident this is an artifact of our test deployment and not an issue when talking to a live basket server.

**Comment by rfk** [comment]
(which is to say, leave this open we definitely need to fix it, but it's not a blocker for anything)

**Comment by jrgm** [comment]
Yes, the fxa-dev setup by default uses the "null" basket server, since in order to use a real basket server requires an api_key that I cannot check into the fxa-dev repo.

**Comment by jrgm** [comment]
Note: I manually put the key where email.dev.lcip.org can use it (talks to the basket dev instance, not basket prod).

**Comment by pdehaan** [comment]
Sweet, thanks @jrgm and @rfk!
I'm fine with closing this as "not a bug" for Latest, as I assume it will work in Stage and Prod without issues.

**Comment by rfk** [comment]
> I'm fine with closing this 

Nah, it shouldn't be too hard to make it do something sensible in dev; let's leave it open but low-priority

**Comment by shane-tomlinson** [comment]
We could create a NullBasketPreferencesManager Server too. ;)

**Comment by vladikoff** [comment]
Closing as low-priority, we should find if there is an issue via stage.
