### ISSUE TITLE
Allow users to change their account email address

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2527]
Users should be able to change their account email address to prevent them from getting locked out if they forget their password and lose access to their old email account.

This depends on: https://github.com/mozilla/fxa-auth-server/issues/489

@ryanfeeley has the UX for this.

/cc @eoger

**Comment by zaach** [comment]
@ryanfeeley post the mockups here when you get a chance.

**Comment by ryanfeeley** [comment]
https://www.lucidchart.com/documents/view/9c9a4647-615f-4b7c-a4db-71ae10afcd04

**Comment by shane-tomlinson** [comment]
@zaach - Can you explain more about the need for this feature? Which password is being forgot in this scenario, the email provider password?

**Comment by shane-tomlinson** [comment]
Also, we have to ensure reliers do not depend on the user's email address as the unique identifier, or else the user's relier account will be inaccessible.

**Comment by shane-tomlinson** [comment]
Finally, how will this interact with a user who has a Sync session?

**Comment by ryanfeeley** [comment]
Hi Shane: email addresses are not permanent for all users, therefore we should allow users to change their email. If we don't there will be a small portion of forgetful users who will be unable to log in.

**Comment by ckarlof** [comment]
Next steps are to break down the work for this with a github checklist.

**Comment by ckarlof** [comment]
@eoger, I believe we're using the WIP for work-in-progress PRs. When you're ready to start this self-assign, and move into waffle:in progress.

**Comment by ryanfeeley** [comment]
@ckarlof @eoger @shane-tomlinson @zaach I am starting to think that we should first require that users verify their original email address as part of the process. Would be more secure for people who still control over their original email, but the downside is that for users who lost control over their original email address, they would not be able to regain control.

**Comment by billmaggs** [comment]
I think that's an easy one; most people will still control their email account, and for those people who have lost control of what is probably a principal email account, they've probably got bigger problems than losing access to Sync data.

**Comment by ryanfeeley** [comment]
@rfk A few on social media still ask about this.
* https://twitter.com/deshpandesuraj/status/656419408881975296
* https://twitter.com/ahtmly2k/status/666361808458924033
* https://twitter.com/ade_fatality/status/695751417940738048
* https://twitter.com/KevinDemsi/status/636689643023437824

**Comment by shane-tomlinson** [comment]
This is FxA-28 on Aha, closing here.
