### ISSUE TITLE
Tests: latest communication preferences - do not opt in to the marketing email FAILED

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2530]
http://tests.dev.lcip.org:8111/viewLog.html?buildId=3030&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog
```
[Step 1/1] Test main - communication preferences - opt in to the marketing email FAILED on firefox 38.0 on LINUX:
[22:56:56][Step 1/1] CancelError: Timeout reached on main - communication preferences - opt in to the marketing email
[22:56:56][Step 1/1] Error: Timeout reached on main - communication preferences - opt in to the marketing email
[22:56:56][Step 1/1]   at Error  <anonymous>
[22:56:56][Step 1/1]   at new ErrorCtor  <node_modules/intern-geezer/node_modules/dojo/errors/create.js:13:21>
[22:56:56][Step 1/1]   at null._onTimeout  <node_modules/intern-geezer/lib/Test.js:177:38>
[22:56:56][Step 1/1]   at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
````

**Comment by rfk** [comment]
I can repro locally, digging in now...

**Comment by rfk** [comment]
Looks like it's getting a CORS request error on the `/subscribe`

**Comment by rfk** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:1114/subscribe. (Reason: CORS request failed).

**Comment by jrgm** [comment]
Oh, actually could be a couple of problems here, the CORS locally above, and this bit. I saw this at some point but didn't file a bug at the time. My bad. 

Look at this test code: https://github.com/mozilla/fxa-content-server/blob/master/tests/lib/basket.js#L12-L36

So, when run from the intern-runner test client (tests.dev.lcip.org) against latest.dev.lcip.org, that code will look in the local configuration for where to poll for user status. Oops. It needs to poll somewhere on latest.dev for that /lookup-user status.

**Comment by rfk** [comment]
Hmm, looks like my CORS error was a red herring caused by the lack of a local basket server, merging https://github.com/mozilla/fxa-local-dev/pull/17 fixed it locally for me

**Comment by jrgm** [comment]
Okay, if local is solved, perhaps we can defer getting a comprehensive solution for remote intern-runner tests for now, and just get a way to skip this test if `fxaProduction=true`? @vladikoff? @zaach?
