### ISSUE TITLE
Extricate basket-proxy code into its own special repo

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2535]
Since we intend for the basket-proxy to go away, let's keep it as isolated as possible from the rest of the code.  I made a new repo for it here:

  https://github.com/mozilla/fxa-basket-proxy

**Comment by vladikoff** [comment]
Nobody is current working on this, backlogging. We should prioritize this

**Comment by rfk** [comment]
Re-opening, we'll have to re-apply https://github.com/mozilla/fxa-content-server/pull/3098 once prod is switched over to using the new repo

**Comment by vladikoff** [comment]
check with @jrgm, to be merged in the next few days
