### ISSUE TITLE
Make resume-token a full-blown model

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2542]
(Spun off from https://github.com/mozilla/fxa-content-server/pull/2492#issuecomment-109765583)

We have this notion of a "resume token" that can be used to tunnel contextual information through an email verification loop.  It's currently treated like an implementation detail of the Relier model, but we should split it out into a full-blown top-level model so that other parts of the code can also access this functionality.  Two immediate examples come to mind:

  * to record whether the user was chosen for metrics gather, or for an able experiment
  * to record whether we have a pending email opt-in to process after verification

**Comment by shane-tomlinson** [comment]
fixed by #2567, closing.
