### ISSUE TITLE
Metrics: Ship Sentry Integration for JS Errors

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2552]
TODO
- [x] File bugzilla bug to enable this = https://bugzilla.mozilla.org/show_bug.cgi?id=1175326
- [x] Create PR: https://github.com/mozilla/fxa-content-server/pull/2529
- [x] Merge PR: https://github.com/mozilla/fxa-content-server/pull/2529
- ~~[x] Puppet Config: https://github.com/mozilla-services/puppet-config/pull/1391~~
- [x] Merge https://github.com/mozilla/fxa-content-experiments/pull/9

**Comment by shane-tomlinson** [comment]
@vladikoff - what content does the bugzilla bug need? Does integration with Sentry need approval from anywhere?

**Comment by vladikoff** [comment]
> what content does the bugzilla bug need?

There is an API_KEY that needs to be setup in prod, also the prod config has to be adjusted.

**Comment by issues-bouncer** [comment]
Hey @vladikoff, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
The content server part is done

@jrgm "need info"'d you on the bugzilla bug: https://github.com/mozilla/fxa-content-server/issues/2552
