### ISSUE TITLE
404 for `POST /undefined/v1/recovery_email/verify_code`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2557]
Pulled over from an issue @jrgm filed in https://github.com/mozilla/fxa-js-client/issues/142:

---------------------------------

Was looking at some Kibana logs of 404 on the content server and noticed this odd url that was 404:

`POST /undefined/v1/recovery_email/verify_code HTTP/1.1"`

There's quite a few of these and they don't appear to be tied to any particular browser version.

```
{
  "_source": {
    "Timestamp": "2015-01-21T09:26:09.440Z",
    "Type": "elb_upstream",
    "Logger": "FxaContentWebserver",
    "Severity": 7,
    "Payload": "",
    "EnvVersion": "",
    "Pid": 0,
    "Hostname": "ip-nnn-nnn-nnn-nnn",
    "upstream_response_time": 0.003,
    "http_x_forwarded_for": "",
    "http_referer": "https://accounts.firefox.com/verify_email?uid=xxxxx&code=xxxxx",
    "body_bytes_sent": 672,
    "user_agent_browser": "Chrome",
    "user_agent_os": "Android",
    "user_agent_version": 39,
    "request": "POST /undefined/v1/recovery_email/verify_code HTTP/1.1",                                                                    
    "request_time": 0.003,                                                                                                                  
    "status": 404                                                                                                                           
  },                                                                                                                                        
}     
```

In a rough look, it looks like the check here needs to guard against undefined
https://github.com/mozilla/fxa-js-client/blob/ec7b4bcd4e797dda2f7a3bac077af87f6ec0fa17/client/FxAccountClient.js#L37
Didn't trace back to where the caller of that is passing in an empty uri though.

**Comment by shane-tomlinson** [comment]
@jrgm - comment from @ckarlof - can we add a redirect from /undefined/* to /*

**Comment by vladikoff** [comment]
-1 on the /undefined/ endpoint, this was already broken for a few trains, we should properly fix this instead IMHO

**Comment by vladikoff** [comment]
from meeting: we should check if /config times out, if it times out we can try repeating the request or asking the user to refresh the page? cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
re-opening until we prove to ourselves via Sentry and Kibana that we have really fixed this, for real.

**Comment by vladikoff** [comment]
I looked at Kibana logs for the past 4 days and seems like 404s went away, I will file an issue if I see any error like this in Sentry.
