### ISSUE TITLE
Remove grunt-contrib-imagemin dep?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2568]
Should we dump/replace grunt-contrib-imagemin devDependency from fxa-content-server? It brings in a LOT of nested sub-sub-sub dependencies like gifsicle, jpegtran, optipng, svgo, and others. Plus it has its own special npm@>=2.1.5 quirks.

From IRC:
```
10:48 AM @vladikoff: @pdehaan, i really wanna ditch imagemin, it's like over 50 mb of stuff
10:48 AM @vladikoff: @pdehaan, the binary is 30 mb 
```

**Comment by vladikoff** [comment]
> 38,424,572 bytes (80.9 MB on disk) for 17,283 items

thing causes more problems than it solves.

**Comment by pdehaan** [comment]
Not sure we're even USING imagemin: https://github.com/mozilla/fxa-content-server/search?utf8=%E2%9C%93&q=imagemin

Only real reference I saw was a commented out reference in /grunttasks/build.js. :cry:

**Comment by jrgm** [comment]
:+1: to removing it.

(Although, it is an awesome stress test for the npm developers ;-) )
