### ISSUE TITLE
A few 499 errors from basket proxy

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2572]
https://kibana.fxa.us-west-2.prod.mozaws.net/#dashboard/temp/AU3e50663q0_6xopP3J_

There are 5 requests returning 499 error code, which is what nginx logs when the client end of the connection closes before a response is returned. SInce these requests all take almost 60 seconds, that is the ELB shutting it down. So the proxy is blocked waiting on a response from either our oauth server, or a response from the basket API.

Looking in the app logs on the webheads, I see these error messages at exactly the times that the 499 is recorded by nginx:

Error #1: <tt>{"Timestamp":1433920548311000000,"Logger":"fxa-content-server","Type":"server.basketproxy.subscribe.error","Severity":2,"Pid":2185,"EnvVersion":"2.0","Fields":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"}}</tt>

Error #2: <tt>{"Timestamp":1433950131319000000,"Logger":"fxa-content-server","Type":"server.basketproxy.subscribe.error","Severity":2,"Pid":2185,"EnvVersion":"2.0","Fields":{"code":"ECONNRESET","sslError":"ZERO_RETURN"}}</tt>

So, appears to be a problem with basket. /cc @pmclanahan

**Comment by pmclanahan** [comment]
I see a few (6) errors in the `subscribe` view over the last 24 hours, and they seem to be timeouts trying to connect to Exact Target. Apparently your timeout is shorter than ours and you just give up. That's fair, but I don't think these should be unexpected. ET has a tendency to do this. 

However, a call to `subscribe` should work without having to contact ET during the request cycle. That's normally taken care of by our async workers which will retry if ET is unresponsive. That is unless the `sync=Y` parameter is sent, in which case basket needs to return the user's basket token, for which it does have to contact ET during the request. I believe the call does involve the `sync=y` parameter. Do we know if this is a hard requirement? If so, you may need to have to implement a retry facility of your own.

**Comment by jrgm** [comment]
> That is unless the sync=Y parameter is sent, in which case basket needs to return the user's basket token, for which it does have to contact ET during the request

I don't believe (and don't see in the code) that we are posting to basket /subscribe with `sync=Y`. 

Is that correct, @zaach?

**Comment by shane-tomlinson** [comment]
> I don't believe (and don't see in the code) that we are posting to basket /subscribe with sync=Y.

We are not. "sync" is nowhere to be found in [1] or [2].

[1] - https://github.com/mozilla/fxa-content-server/blob/master/server/bin/basket-proxy-server.js
[2] - https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/marketing-email-client.js

**Comment by pmclanahan** [comment]
Hmm. Okay. Do we know which endpoint(s) on basket these errant requests were hitting? 

(maybe some of this info is in the kibana mentioned in the issue, but I don't have access to that)

**Comment by vladikoff** [comment]
@pmclanahan does this help? :
![](http://v14d.com/i/5579ae26b694c.jpg)

**Comment by pmclanahan** [comment]
@vladikoff indeed it does! Thanks. Though now I'm very curious about the request data as well... Do we have that? If I could see what was requested (minus the email address of course) I could much more easily diagnose. I'm surprised that they're subscribe calls that don't use `sync`. Could be that the problems Exact Target was having caused requests to back up on the basket side and timeout everything. Hmm.

**Comment by shane-tomlinson** [comment]
As a hack, could we have the proxy server retry on 499 so that a few more users are opted in?

**Comment by jrgm** [comment]
We backed off the timeout on the front-end ELB, which means we no longer get a 499 reported on that side. However, we still continue to see requests timing out after 60 seconds in attempting to reach the basket API.

**Comment by jrgm** [comment]
See also #2587.

**Comment by shane-tomlinson** [comment]
ref #2587

**Comment by vladikoff** [comment]
possible fix: add retry

**Comment by shane-tomlinson** [comment]
Closing as subsumed by #2873.
