### ISSUE TITLE
Metrics: Add more tags from feature detection of mobile and desktop 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2575]
Add more tags from feature detection of mobile and desktop

We need a way to create metrics graphs based on user's device, to answer questions like: "Did the user choose to use Show Password on mobile or desktop?"

**Comment by vladikoff** [comment]
check if ua parser has a mobile tag and send that tag to datadog.

**Comment by vladikoff** [comment]
will check with @ryanfeeley

**Comment by ryanfeeley** [comment]
@vladikoff what do i know?

**Comment by ckarlof** [comment]
We're going to "trust @vladikoff" to make sense of all these vague reminders.

**Comment by vladikoff** [comment]
@ryanfeeley the old debate of - "What do you consider to be a "mobile" device?"

For the "Show Password" metric, what is important to you? "touch screen" device or some resolution boundary (i.e <1024px display)?   Is something like https://github.com/kaimallea/isMobile#why-use-ismobile good enough to set as a tag?

Updated issue title and description

**Comment by ryanfeeley** [comment]
Tap vs click is probably the biggest identifier. Would a hybrid Windows device require a third category?

**Comment by vladikoff** [comment]
Cool, we should be able to add a `tap` / `click` tag somehow

**Comment by shane-tomlinson** [comment]
@vladikoff - since DataDog told us the number of tags we already have slows down queries, do we still want to add more?

2nd, Is this actually in progress?  If not, can you move it out of the in progress column?

**Comment by vladikoff** [comment]
Just use the existing tags and compare using the user agent tags, we won't be adding custom tap vs click tags
