### ISSUE TITLE
Metrics: iOS Safari does not send page unload events

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2577]
tested locally, closing a tab in iOS 8 Safari does not send metrics data
it should produce a log like this when the tab is closed (taken from desktop Safari):

{"time":"2015-06-10T21:00:00.000Z","op":"client.metrics","hostname":"vladikoff","pid":86750,"v":1,"lang":"en","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17","duration":1772,"context":"web","broker":"base","entrypoint":"none","service":"none","migration":"none","campaign":"none","nt.navigationStart":0,"nt.fetchStart":0,"nt.domainLookupStart":0,"nt.domainLookupEnd":0,"nt.connectStart":0,"nt.connectEnd":1,"nt.requestStart":1,"nt.responseStart":4,"nt.responseEnd":12,"nt.domLoading":12,"nt.domInteractive":55,"nt.domContentLoadedEventStart":55,"nt.domContentLoadedEventEnd":55,"nt.domComplete":60,"nt.loadEventStart":60,"nt.loadEventEnd":60,"events":["signup.email-optin.visible.true","screen.signup"],"event_durations":[668,712],"screen.width":1680,"screen.height":1050}

**Comment by shane-tomlinson** [comment]
This is really disappointing, I am really starting to think we should automatically submit data just before redirecting back to the relier, blocking the redirection until the XHR request completes. Of course, this will not help if the iOS user reloads the page, but it'll be a start in the right direction.

**Comment by shane-tomlinson** [comment]
It looks like iOS Safari does not yet support sendBeacon either - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

ref #2493

**Comment by vladikoff** [comment]
from meeting:
 to investigate why interval is not sending events

**Comment by vladikoff** [comment]
updated issue title, `unload` does not fire. However metrics are sent if the page sits there for ~10 minutes. The DataDog tag to use is `agent_os_family:ios`

**Comment by philbooth** [comment]
Not sure whether this is relevant or of interest but I know [boomerang.js](https://github.com/lognormal/boomerang) has a long history of sending beacon data cross-browser before page unload. Specifically, [for iOS it uses the `pagehide` event](https://github.com/lognormal/boomerang/blob/master/boomerang.js#L905-L912):

```js
// pagehide is for iOS devices
// see http://www.webkit.org/blog/516/webkit-page-cache-ii-the-unload-event/
if(w.onpagehide || w.onpagehide === null) {
    BOOMR.utils.addListener(w, "pagehide", unload_handler);
}
else {
    BOOMR.utils.addListener(w, "unload", unload_handler);
}
```

Just thought I'd mention in case we want to do something similar.

**Comment by vladikoff** [comment]
@philbooth I think I tested pagehide earlier and it didn't work well enough, we have a pending PR that fixes this though

**Comment by vladikoff** [comment]
:+1:  thanks Shane!
