### ISSUE TITLE
Consume & report GA tags to metrics?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2579]
A possible idea to help out the growth team - consume Google Analytics query parameters and report them to our metrics infrastructure so they can run similar queries everywhere.

cc @rfk, @jpetto, @habber

ref #2399 
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1162192

**Comment by shane-tomlinson** [comment]
We could also relay the GA tags back to the relier when the signin/signup flow has completed.

**Comment by rfk** [comment]
Chris more provided me the following notes in email after I chatted with him about this last week:
"""
From this page:

https://support.google.com/analytics/answer/1033867?hl=en

Campaign Source (utm_source)
Required. Use utm_source to identify a search engine, newsletter name, or other source.
Example: utm_source=google

Campaign Medium (utm_medium)
Required. Use utm_medium to identify a medium such as email or cost-per- click.
Example: utm_medium=cpc

Campaign Term (utm_term)
Used for paid search. Use utm_term to note the keywords for this ad.
Example: utm_term=running+shoes

Campaign Content (utm_content)
Used for A/B testing and content-targeted ads. Use utm_content to differentiate ads or links that point to the same URL.
Examples: utm_content=logolink or utm_content=textlink

Campaign Name (utm_campaign)
Used for keyword analysis. Use utm_campaign to identify a specific product promotion or strategic campaign.
Example: utm_campaign=spring_sale


Example URL:

https://accounts.firefox.com/?utm_source=snippet&utm_medium=snippet&utm_content=snippet001A&utm_campaign=spring-campaign

At a minimum, it should be medium, source, and campaign and sometimes utm_content/utm_term will be populated too.

I would probably also sanitize the values of the parameters to ensure they are letters, numbers, dashes, underscores, and periods and probably nothing else to ensure no one is trying to stuff code into the values.
"""

**Comment by vladikoff** [comment]
from meeting:
  how will the data be consumed?

**Comment by chrismore** [comment]
Thanks, everyone!
