### ISSUE TITLE
Remove JSHint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2582]
Once #2578 lands and we're all happy w/ ESLint, we should remove the old JSHint subsystem (since we don't need redundant linting).

https://github.com/mozilla/fxa-content-server/search?utf8=%E2%9C%93&q=jshint

**Comment by TDA** [comment]
Would be happy to do this once we get that merged :)

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/2550#issuecomment-110278916

>> @shane-tomlinson: I dig this plan. Can we run them in parallel for a bit until we have eslint set up just so, and then rip out jshint as a 2nd step?

> @vladikoff: That's a good idea!

Let's wait until we get the OK from Shane and Vlad and Zaach before ripping out JSHint's guts.

**Comment by pdehaan** [comment]
https://github.com/mozilla/fxa-js-client/issues/156#issuecomment-111261215

> @shane-tomlinson: Let's keep the two running concurrently for maybe a week, then rip out JSHint.

**Comment by TDA** [comment]
Looks like JSHint has 7 days to live ;) @pdehaan
