### ISSUE TITLE
requests to the basket proxy must be fully asynchronous

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2587]
If there is a long delay in connecting to the basket server, the UI for subscribe/unsubscribe just hangs with a spinner for ~60 seconds, until the ELB aborts the incoming request to the proxy server.

This occurs both when doing a signup and checking the subscribe checkbox, and when visiting the communication preferences screen, and when clicking subscribe/unsubscribe on that screen. 

ISTM, it would be better to not wait at all for the response from the content server on /subscribe, /unsubscribe and /lookup-user, and just spin on a button (i.e., show the user that the page can load or that the signup is complete, but be lazier about the determining what state they are in). 

To make it easier to decide what to do, I rigged an fxa-dev box to alternate between blocking the connection (for 30 to 90 seconds) to basket locally (the null server) and unblocking it (for 30 to 90 seconds)

**Comment by jrgm** [comment]
Hmm, submitted that a bit prematurely...

**Comment by rfk** [comment]
Could we drop the ELB timeout to e.g. 5 or 10 seconds as a simple workaround for this?  If basket has not got back to use by then, it seems unlikely to get back to us at all.

There's a risk that we end up "lying" to the user, telling them that the operation succeeded when in fact it did not.  This would be particularly bad for users clicking "unsubscribe" but not actually getting unsubscribed.

**Comment by jrgm** [comment]
The test box I rigged up is at https://jrgm2.dev.lcip.org/, and I set it so it will be blocking for 30 to 60 seconds, and unblocked for 30-60 seconds.

> Could we drop the ELB timeout to e.g. 5 or 10 seconds as a simple workaround for this? 

I'd rather timeout the request to the basket API so we can respond yea or nay. When the ELB fires its timeout, it just hard disconnects, so the browser gets an arbitrary 504 response from the ELB. (I dunno, maybe it doesn't make a difference who sends back the error).

**Comment by jrgm** [comment]
Note: lowering on the ELB affects all connections to content server (think of the main js bundle size).

**Comment by pdehaan** [comment]
> (think of the main js bundle size)

Ref: https://github.com/mozilla/fxa-content-server/issues/1461

**Comment by rfk** [comment]
> lowering on the ELB affects all connections to content server

Oh yeah.  I guess maybe less of an issue once it's in its own stack, but doing a nicer timeout inside the basket-proxy itself does seem like a better idea than messing with the ELB.

**Comment by shane-tomlinson** [comment]
> Oh yeah. I guess maybe less of an issue once it's in its own stack, but doing a nicer timeout inside the basket-proxy itself does seem like a better idea than messing with the ELB.

When I was junking up @zaach's initial basket proxy, I made both subscribe and unsubscribe "fire and forget" from the proxy->basket. It worked well enough, but I worried that users would receive no feedback.

We could still do a fire/forget request, immediately respond to the user, and keep trying (using some reasonable approach with a timeout) on the proxy upon failure.

**Comment by rfk** [comment]
I'm strongy opposed to telling the user we've unsubscribed them unless we've actually unsubscribed them.  Doing a "fire and forget" from the proxy->basket for the subscribe call sounds OK though, and would certainly make a difference in the complete-verification stage.

**Comment by shane-tomlinson** [comment]
I have no aversion fire-forget and doing a simple retry, at least for subscribe. Unsubscribe is probably far less frequent and may not warrant an update just yet.

**Comment by shane-tomlinson** [comment]
Closing as subsumed by #2873.
