### ISSUE TITLE
Run lint scripts on a prepush git hook

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2592]
(From https://github.com/mozilla/fxa-content-server/pull/2591#issuecomment-111643568)

We could use something like https://www.npmjs.com/package/pre-commit or https://www.npmjs.com/package/husky and make it a devDep so everybody is forced into the precommit route.

IIRC, we used [**husky**](https://github.com/typicode/husky) (with [**grunt-newer**](https://github.com/tschaub/grunt-newer) so it'd only lint modified files instead of all files) in [mozilla/chronicle](https://github.com/mozilla/chronicle/) and then just ran the custom lint task on `prepush`.

**Comment by shane-tomlinson** [comment]
I find pre-commit too granular because I commit very frequently. I use a pre-push hook:

in my `.git/hooks/pre-push`
```
exec grunt lint
```

**Comment by vladikoff** [comment]
pre-push hook +1 !
