### ISSUE TITLE
Should we remove jscs and add the equivalent rules to eslint?

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2598]
Since we are now removing JSHint from the code base, and many of the features that JSCS provides is also found in ESLint, should we move towards integrating everything into ESLint or still maintain a separate JSCS?

**Comment by pdehaan** [comment]
I vote yes, although I doubt we can replace all the jscs rules w/ ESLint equivalents (without writing a bunch of custom ESLint rules).

But i think we should move as much into the .eslintrc files (or that global shared eslint-config-fxa) as makes sense so we can share them easily between projects/repos.

**Comment by TDA** [comment]
I would think so too, would save us a lot of time to use the global scaffold to add/modify eslint to multiple repos.

**Comment by vladikoff** [comment]
-1 Please do not remove JSCS

**Comment by pdehaan** [comment]
Oh, totally, lets not remove JSCS completely, but I think it may make sense to move any JSCS rules that are also available in ESLint into the .eslintrc file instead of .jscsrc.

**Comment by TDA** [comment]
@vladikoff @pdehaan 
http://eslint.org/docs/rules/#stylistic-issues
contains almost 70% of the jscs rules we have in right now, most notably:
no-with/no-eval
spacing and indentation options.

The advantage of moving these to the eslint global file would be easy extension of rules as required in child folders. 
The disadvantage is basically knowing which rules are enforced by jscs and which by eslint, but the rules are verbose enough, and our linter should also give out verbose errors for us to fix.

**Comment by vladikoff** [comment]
> Oh, totally, lets not remove JSCS completely, but I think it may make sense to move any JSCS rules that are also available in ESLint into the .eslintrc file instead of .jscsrc.

Sure that make sense, if there are rules that are **exactly** duplicate move them to eslint
