### ISSUE TITLE
Age dropdown uses hardcoded years

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#260]
https://accounts.dev.lcip.org/age
Currently the dropdown menu has the years "1960s or earlier", "1970s", "1980s", "1990s", "2000".."2007" (see [app/scripts/templates/age.mustache](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/age.mustache))

Should those be hard coded? Are we planning on updating the list every year or so? Or should the dates be dynamically generated based on the current year?

---

![firefox_accounts](https://f.cloud.github.com/assets/557895/1926505/30e11630-7e44-11e3-9eec-10ea571c54d6.png)

**Comment by vladikoff** [comment]
This should be fixed via https://github.com/mozilla/fxa-content-server/issues/2108
