### ISSUE TITLE
Configuration for rule "globals" is invalid: Value "[object Object]" is the wrong type

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2600]
Another weird ESLint issue when running `eslint .` from the CLI (using latest eslint@0.23.0):

```
$ eslint .

/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/app/.eslintrc:
	Configuration for rule "globals" is invalid:
	Value "[object Object]" is the wrong type.
```

Looks like we shouldn't be nesting `globals: {}` in the `rules` section of the app/.eslintrc file, but it should be the same depth as `env` and `rules`:

```js
{
  "env": {
    ...
  },
  "globals": {
    "router": false
  },
  "rules": {
    ...
  }
}
```
**Listing 1:** Good.

---

```js
{
  "env": {
    ...
  },
  "rules": {
    "globals": {
      "router": false
    },
    ...
  }
}
```
**Listing 2:** Current [/app/.eslintrc:9-11](https://github.com/mozilla/fxa-content-server/blob/c089ae6bd770f1219c7d3650d675d740e354dae4/app/.eslintrc#L9-L11)

---

See http://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/2599#issuecomment-112518805

**Comment by TDA** [comment]
@pdehaan Looking into this, can I make a single PR for issues 2599,2600,2602?
