### ISSUE TITLE
WebChannel: "Response not received for: loaded"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2601]
1. went to about:accounts?entryPoint=menupanel via the menu panel.
2. After a while got this error in the console: `Response not received for: loaded`

@shane-tomlinson is this something we should be worried about ?

![image](https://cloud.githubusercontent.com/assets/128755/8186830/88a3c56c-141a-11e5-94d9-785123eed6ba.png)

**Comment by shane-tomlinson** [comment]
@vladikoff - nothing to worry about. I'm half way through a refactor of the channels for some requests to be "fire and forget" notification messages, and others to be requests. The "loaded" message is a notification message that does not expect a response.
