### ISSUE TITLE
[stage] Error `e is undefined` from underscore.js due to 'use strict'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2611]
The exception is thrown in `underscore.js` code bundled in https://accounts.stage.mozaws.net/scripts/77440150.main.js
```
define("require_config", function(){});

//     Underscore.js 1.8.3
//     http://underscorejs.org
//     (c) 2009-2015 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
//     Underscore may be freely distributed under the MIT license.

(function() {

  // Baseline setup
  // --------------

  // Establish the root object, `window` in the browser, or `exports` on the server.
  var root = this;

  // Save the previous value of the `_` variable.
  var previousUnderscore = root._; // <-- throws exception here
  ...
  ...
```

`this`, of course, is due to `this` being undefined unless explicitly passed in strict mode. 

However, I'm not sure why https://latest.dev.lcip.org is not showing the same error as https://accounts.stage.mozaws.net since they are built essentially the same way (`npm install && grunt build`).

Nonetheless, we appear to be overapplying `use strict` to underscore.js, which clearly is expecting `this` to be a reference to the global context.

**Comment by jrgm** [comment]
I actually see a few places with changes like https://github.com/mozilla/fxa-content-server/compare/train-39...master#diff-0fcf653302aba42e5234e032dbac9debL3, where 'use strict' is hoisted from function to file scope. Were those intended to be changed that way?

**Comment by vladikoff** [comment]
Thanks for reporting this @jrgm and sorry about the issue. I see why it is different in the environments (the placement of scripts is different in every build). Reverting `use strict` rules and forcing the functional rule ASAP.

**Comment by vladikoff** [comment]
@jrgm should be fixed now, please try redeploying stage :fire_engine:

**Comment by jrgm** [comment]
Hey @vladikoff, thanks for the quick turnaround. I was wondering if the difference was some sort of ordering aspect.

Anyways, tests against stage are good with this update to content-server. 


---
Separate but related, tests.dev.lcip.org somehow got hung up in running tests, and appeared to me that there a few background firefox procs spinning cpu; I think I got things running there correctly again, but we can chat in the morning.
