### ISSUE TITLE
npm start should copy `local.json` from local.json-dist if that does not exist

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2619]
`npm start` should copy `local.json` from local.json-dist if that does not exist

The goal behind this is to reduce the steps for developers to start the server

**Comment by pdehaan** [comment]
@vladikoff Should we only do that for certain `process.env.NODE_ENV`s?

I have this hacky code, but wasn't sure if we should wrap in a `if (process.env.NODE_ENV === 'development') {...}` block:

```js
#!/usr/bin/env node

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const fs = require('fs-extra');
const path = require('path');

const RELATIVE_FILE = 'server/config/local.json';
const CONFIG_FILE = path.resolve(__dirname, '..', RELATIVE_FILE);

if (! fs.existsSync(CONFIG_FILE)) {
  console.log('%s doesn\'t exist. Creating...', RELATIVE_FILE);
  fs.copySync(CONFIG_FILE + '-dist', CONFIG_FILE);
}
```

---

```
$ ./scripts/check-config.js
server/config/local.json doesn't exist. Creating...
```
**Listing 1:** If the `./server/config/local.json` file doesn't already exist.

---

```bash
$ ./scripts/check-config.js
```
**Listing 2:** If the `./server/config/local.json` file already exists (no output).

**Comment by vladikoff** [comment]
> @vladikoff Should we only do that for certain process.env.NODE_ENVs?

I don't think anyone except dev uses `npm start`. Deployments should use CONFIG_FILES or change production.json.

The `if (process.env.NODE_ENV === 'development') {...}` is tricky because of `NODE_ENV=dev`. Also  developers do not have NODE_ENV defined sometimes.
