### ISSUE TITLE
"client has sent too many requests" error is not translated

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2623]
Oddly enough, the error message is translated in the [l10n repo](https://github.com/mozilla/fxa-content-server-l10n/blob/4a59dadabaa1d3f9dbc3e40626dc9219e275bb2c/locale/es/LC_MESSAGES/client.po#L1079), it's just commented out.

![screen shot 2015-06-21 at 14 25 33](https://cloud.githubusercontent.com/assets/848085/8271802/e6347b08-1821-11e5-8b54-04ab0398d4d9.png)

**Comment by vladikoff** [comment]
needs to be rechecked, woo!

**Comment by vladikoff** [comment]
From the other bug:

> I noticed when overdoing it with password reset form that our message has regressed.

> https://github.com/mozilla/fxa-content-server/pull/848/files

> Current: Client has sent too many requests
> Proposed: Attempt limit exceeded. Try again later.

**Comment by shane-tomlinson** [comment]
ref #2513 2513

**Comment by shane-tomlinson** [comment]
Oh dear. None of the errors returned from fxa-client are being normalized using [errors.js->normalizeXHRError](https://github.com/mozilla/fxa-content-server/blob/660136152e3521aee937fad647f0508352bbd146/app/scripts/lib/errors.js#L130). If there is a discrepancy between the error string returned by the server and the error string we have defined for that error in AuthErrors.js, then the server's string is shown untranslated.

For example, the server error message is `Client has sent too many requests`. [auth-errors.js](https://github.com/mozilla/fxa-content-server/blob/660136152e3521aee937fad647f0508352bbd146/app/scripts/lib/auth-errors.js#L99) says the error string should be `Server busy, try again soon`. Because of the discrepancy and because `Client has sent too many requests` is not used anywhere else, the translation is [commented out in the .po file](https://github.com/mozilla/fxa-content-server-l10n/blob/4a59dadabaa1d3f9dbc3e40626dc9219e275bb2c/locale/es/LC_MESSAGES/client.po#L1079).

The unnormalized XHR error is also the cause of the `unknown_namespace` being reported to metrics in #2513.

**Comment by vladikoff** [comment]
@shane-tomlinson thanks for debugging into it!
