### ISSUE TITLE
No license information at the top of the production JS

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2626]
From https://accounts.firefox.com/scripts/31d882bb.main.js:

>var requirejs,require,define;!function(global){function isFunction(a){return"[object Function]"===ostring.call(a)}function isArray(a){return"[object Array]"===ostring.call(a)}function each(a,b){if(a){var c;for(c=0;c<a.length&&(!a[c]||!b(a[c],c,a));c+=1);}}function eachReverse(a,b){if(a){var c;for(c=a.length-1;c>-1&&(!a[c]||!b(a[c],c,a));c-=1);}}function hasProp(a,b){return hasOwn.call(a,b)}function getOwn(a,b){return hasProp(a,b)&&a[b]}function eachProp(a,b){var c;for(c in a)if(hasProp(a,c)&&b(a[c],c))break}function mixin(a,b,c,d){return b&&eachProp(b,function(b,e){(c||!hasProp(a,e))&&(!d||"object"!=typeof b||!b||isArray(b)||isFunction(b)||b 

That's a shame. The MPL 2.0 snippet isn't strictly required for built resources, but it'd be nice. We should check what other library authors require too. At a minimum, we should say "you can find the code used to build this at "https://github.com/mozilla/fxa-content-server/"

Ref #2625

**Comment by pdehaan** [comment]
Related? https://github.com/mozilla/fxa-content-server/issues/147

**Comment by pdehaan** [comment]
So I think we can just use the [`banner`](https://github.com/gruntjs/grunt-contrib-uglify#banner) option and pass our MPL-2.0 snippet header via the Gruntfile. (see https://github.com/gruntjs/grunt-contrib-uglify#banner-comments). Not sure of the build order, but if we're running on latest/stage/dev, we may even be able to reference the generated _ver.json_ file in order to get the SHA and append that before/after the MPL license header.

Comically, we could also specify the [`screwie8`](https://github.com/gruntjs/grunt-contrib-uglify#screwie8) flag to potentially shave a few bytes:

> Pass this flag if you don't care about full compliance with Internet Explorer 6-8 quirks.

**Comment by vladikoff** [comment]
@shane-tomlinson we talked about this a few weeks back and I think @zaach mentioned that our source can already be found easily via GitHub.  I agreed and we closed https://github.com/mozilla/fxa-content-server/issues/147, if you disagree I guess we can keep this issue open and fix it.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson we talked about this a few weeks back and I think @zaach mentioned that our source can already be found easily via GitHub.

It can be found easily, if you know where to look. I'd like to be a bit more explicit with a link to where the source can be found. MPL License info is strictly optional in compressed resources, but we *should* find out how to handle 3rd party library licenses.

**Comment by pdehaan** [comment]
Ref: #2647

Current output (with patch applied):
```js
/*! fxa-content-server@0.40.0 -- Tue Jun 30 2015 14:29:01
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * For more information, see https://github.com/mozilla/fxa-content-server/
 */
```
