### ISSUE TITLE
Danish: Sign up button takes user to the privacy policy

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2628]
Brought to my attention by our Danish translator. An error exists in the current Danish translation where a user that clicks the signup button is displayed the privacy policy.

STR

1. Open a new browser profile
1. Set the locale to Danish (da)
1. Open https://accounts.firefox.com/signup
1. Fill out the form
1. Click the submit button.
1. What's up with the privacy policy?

![danish-sign-up](https://cloud.githubusercontent.com/assets/848085/8281475/392bfad4-18e0-11e5-8dc8-d6b5bdfb82c3.gif)

The translator believes this should be fixed in commit https://github.com/mozilla/fxa-content-server-l10n/commit/a8702dbd9df4a5ba8267744a87eabdfbc29e4602

**Comment by johngruen** [comment]
![-1](https://cloud.githubusercontent.com/assets/3323249/8461194/d0921a4c-1ff8-11e5-92d1-65f492a23196.jpg)

**Comment by johngruen** [comment]
@shane-tomlinson looks like this is fixed in latest

**Comment by jrgm** [comment]
> looks like this is fixed in latest

It was fixed in prod last week by re-releasing fxa-content-server with new l10n. 

But that reminds me. Is there no defense against a translation breaking the UI this way?d

**Comment by shane-tomlinson** [comment]
> But that reminds me. Is there no defense against a translation breaking the UI this way?

There probably is, given enough time and testing. Forcing localizers to translate HTML in embedded strings has always been a worry of mine, I just haven't figured out how to get around it entirely.

**Comment by pdehaan** [comment]
IIRC, this breakage probably could have been caught by some cryptic HTMLLint sorcery.
https://github.com/mozilla/fxa-content-server-l10n/commit/a8702dbd9df4a5ba8267744a87eabdfbc29e4602#diff-5a1899d8f96c5acaca370fea22db7d0cL674

It looks like it was just somebody accidentally removing the opening `<` in a `</a>` tag, which makes things go wrong real fast.

But yeah, I think it'd be down to us grabbing the files from fxa-content-server-l10n via bower, compiling them all per-language (so, `grunt build`), then running grunt-htmllint on the 950+ generated files in _/server/templates/pages/dist/\*\*/\*.html_ (and then hope we don't get a ton of false warnings).

**Comment by shane-tomlinson** [comment]
I just tested this. Fixed. Closing. Moving @pdehaan's remarks to #2659
