### ISSUE TITLE
Replace p with bluebird in bower.json?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2633]
Looks like we're using **p** in [bower.json](https://github.com/mozilla/fxa-content-server/blob/37a6a74b1c3db4ef54dd69b9732120dbd3fa57dd/bower.json#L17), and **bluebird** in [package.json](https://github.com/mozilla/fxa-content-server/blob/37a6a74b1c3db4ef54dd69b9732120dbd3fa57dd/package.json#L26).

Not sure if it makes sense to use the same Promise lib for front and back end stuff, because reasons.
Looks like [**bluebird**](https://github.com/petkaantonov/bluebird) is available in package.json and bower.json variants:

---

> There are many ways to use bluebird in browsers:
> - Direct downloads
>    - Full build bluebird.js
>    - Full build minified bluebird.min.js
> - You may use browserify on the main export
> - You may use the bower package.
> 
> &mdash; via https://github.com/petkaantonov/bluebird#browsers

**Comment by vladikoff** [comment]
> A minimal bluebird browser build is ≈38.92KB minified*, 11.65KB gzipped and has no external dependencies.

AFAIK We don't have plans to switch to bluebird because of its size and complexity
