### ISSUE TITLE
"Index or size is negative or greater than the amount allowed" when adding avatar

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2634]
@vmunix ran into this when trying to add an avatar. Below is a screenshot and the image he used.

![screenshot 2015-06-24 11 20 09](https://cloud.githubusercontent.com/assets/2365255/8338072/6a5730f4-1a63-11e5-8daa-6bb49abbeb67.png)

![lemongrab_small](https://cloud.githubusercontent.com/assets/2365255/8338129/e961b1a8-1a63-11e5-80b7-3227cc7cf7b0.png)

**Comment by eoger** [comment]
Reproduced it successfully. This is because of float operations accuracy problems.
I'm working on a fix right now!

**Comment by edmoz** [comment]
avatar no like lemon grab
![the_earl_of_lemongrab_by_darthguyford-d5r9gts](https://cloud.githubusercontent.com/assets/3698618/8418943/2c3fbd02-1e6b-11e5-917a-a48c1a7763e3.jpg)
