### ISSUE TITLE
Hide unexpected error on the /confirm page

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2638]
Submitted the registration form successfully and and left the **Confirm Your Account** page page open. An hour later when I opened my laptop lid, and was just coming on to wi-fi, the page displayed an unexpected error.
![fxa-unexpected-error](https://cloud.githubusercontent.com/assets/68213/8387555/40cb6276-1c0e-11e5-979b-edfdc8792ea9.png)

**Comment by vladikoff** [comment]
@ryanfeeley were you on hilton wifi that has a login gate? I.e it first required you to login to wifi?

**Comment by ryanfeeley** [comment]
When I closed my lid I was, but when I opened it I was at the Westin.

**Comment by vladikoff** [comment]
@ryanfeeley it could be that it was the wrong wifi, but I will check

**Comment by ckarlof** [comment]
> @ryanfeeley it could be that it was the wifi was not connected properly, but I will check..

It was either "captive portal-ed" or disconnected, but it does look like the error was caused by the CORS preflight request getting blocked.

**Comment by vladikoff** [comment]
Renamed the issue, I guess the consensus was to provide a better message to the user. 
The CORS error is misleading though, if the auth server is not accessible then the content server will think that it is a CORS issue.

**Comment by rfk** [comment]
We see a steady trickle of users in SUMO who run into situations like this, which likely means many more who hit it and don't say anything.   Bumping the priority as it looks pretty small and well-defined.

**Comment by rfk** [comment]
Sentry error reports suggest we get around 200 failed DNS resolutions and related network problems per hour.

**Comment by ryanfeeley** [comment]
@rfk Too colloquial?

> "Apologies—our servers are currently not playing nice."

Also, I think we can safely subtract every instance of "Unexpected error" from our Happiness tally.

**Comment by rfk** [comment]
ISTM that the error is almost certainly not our fault, but rather due to some network weirdness on behalf of the user.  Probably hard to communicate that though.

**Comment by vladikoff** [comment]
We should update the confirm page not to throw `unexpected` and just keep trying.

**Comment by ryanfeeley** [comment]
@vladikoff Would a reload button help?
