### ISSUE TITLE
Metrics: opt-out option for the settings screen

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2642]
We discussed this a bit in Whistler. We need a way for logged-in users to opt-out from metrics.

**Comment by vladikoff** [comment]
Just a note for @johngruen that this could be part of the new settings design

**Comment by ckarlof** [comment]
I support this. This will help clear the way for:

* more instrumentation in our flows
* A/B testing for logged in users

**Comment by ckarlof** [comment]
As an example, here the copy that KISSmetrics has:

https://www.kissmetrics.com/user-privacy

**Comment by vladikoff** [comment]
@ckarlof @rfk  what if instead of adding options to the settings screen we just use DNT? We could leave a note that if DNT is enabled then metrics is off.

**Comment by ckarlof** [comment]
This is somewhat of a misuse of DNT (http://donottrack.us/): 

> Do Not Track is a technology and policy proposal that enables users to opt out of tracking by websites they do not visit, including analytics services, advertising networks, and social platforms.

I think that the last time I floated this by Legal, they said no. Plus it isn't sticky with the user's account (across devices).

**Comment by vladikoff** [comment]
@rfk if this is important for Product we should make an Aha card for this feature, or skip it and focus on other stuff.
