### ISSUE TITLE
Basket: handle 500 errors from basket and show a maintenance message

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2644]
```
The basket API server goes down every night.
ACTION: needs a content server bug to show a maintenance message
```

**Comment by jrgm** [comment]
If it were a simple fix, it would be good to fix this for train-40 (as an update to the current tag).

**Comment by pdehaan** [comment]
Maybe add this GIF if we get a 500?


![](https://camo.githubusercontent.com/4a7cf94aedbd23c13cc2d75fdc3b2af5c816c208/687474703a2f2f7374617469632e646967672e636f6d2f7374617469632f696d616765732f6469676765722e676966)

**Comment by jrgm** [comment]
I'm okay with that image, but the text should read 'Coming Soon'.

**Comment by pdehaan** [comment]
Maybe we can use Able to A/B test it versus this:

![](http://www.doorsixteen.com/wpcms/wp-content/uploads/2012/12/hanginthere_cat.jpg)

**Comment by shane-tomlinson** [comment]
> The basket API server goes down every night.
ACTION: needs a content server bug to show a maintenance message

For real? What is the time window? Nobody told us about this earlier?

**Comment by ckarlof** [comment]
> What is the time window? Nobody told us about this earlier?

Valid points to raise, but we always need to think about the UX we want when a service we rely on fails..

**Comment by rfk** [comment]
> Nobody told us about this earlier?

I don't think that going down is the *intended* behaviour from the basket side; @jrgm do you have a bug describing the behaviour we see from basket, for them to dig into?

**Comment by shane-tomlinson** [comment]
> Valid points to raise, but we always need to think about the UX we want when a service we rely on fails..

We have been, and have been discussing ways to handle short periods of intermittent downtime. 20 minutes of guaranteed sustained downtime per day is not what was expected, and bumps the urgency.

**Comment by rfk** [comment]
FYSA I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1179496 for digging in on the basket side

**Comment by rfk** [comment]
ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1182679

**Comment by TDA** [comment]
@rfk That has been fixed with this PR :) wont be long now !
