### ISSUE TITLE
Allow a Sync user to undo an incorrectly registered email address

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2652]
So that I can avoid a world of manual undo pain, as a registering Sync user, I want to be able to go back on the **Confirm your account** screen which will clear the email address seeded into my Firefox desktop client.
![email-undo](https://cloud.githubusercontent.com/assets/68213/8460542/737e2850-1ff3-11e5-9d8b-85edc4f5fa42.png)

**Comment by johngruen** [comment]
@ryanfeeley why is this sync specific? why not in general for FXA?

**Comment by ryanfeeley** [comment]
Actually great idea for all of them. How the unverified email address gets unstuck from the desktop client software is harder than just the web, but yeah, let's support this feature for web and native clients.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I have always wanted the back button, I'm surprised there isn't a bug on file about it. If the user goes "back", perhaps we should remove the just registered email from the dB. We have to make sure Sync can handle the user registering a new email w/o verifying the old one.

**Comment by shane-tomlinson** [comment]
ref #2654

**Comment by ryanfeeley** [comment]
Related information from Datadog: Bounced emails as a % of account verifications = 1.67%.

**Comment by mhammond** [comment]
Desktop will be capable of handling this fine - probably with a trivial change so desktop can listen for a "forget the current (unverified/incorrectly-typed) user" command.

**Comment by shane-tomlinson** [comment]
> Desktop will be capable of handling this fine - probably with a trivial change so desktop can listen for a "forget the current (unverified/incorrectly-typed) user" command.

Thanks for the quick confirmation @mhammond.

**Comment by vladikoff** [comment]
Sort of a dup of https://github.com/mozilla/fxa-content-server/issues/2002

**Comment by shane-tomlinson** [comment]
@ryanfeeley - @vladikoff is right, I'm closing this one as a dup of #2002
