### ISSUE TITLE
Reword and slowly fade in the resend account verification email link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2654]
About 1/4 of registering users click the "Resend email" link. Is this because they're not reading it and it's placed in the "whatever button [1] spot, or because they are waiting a sufficient amount of time and not receiving the email? We're not sure, but I'd like to propose we change the text to “Didn’t arrive? Resend" and slowly fade in the link as depicted in the animation.
![herbatderp](https://cloud.githubusercontent.com/assets/68213/8461928/0a8825c0-1ffe-11e5-9ad4-2e43d0b8a1c2.gif)
But unlike the animation, when the user clicks the link, we should probably drop focus on the link, and slowly fade it in again.

[1] h/t @dolske https://blog.mozilla.org/dolske/2007/10/21/whatever/

**Comment by shane-tomlinson** [comment]
@ryanfeeley - is this 1/4 of users, or the total count adds up to 1/4 of users? Slight difference, each user can click the button 4 times before it's hidden. It would be nice to have those broken out.

The wording change I dig. The fade in, I'm indifferent to. We could just limit the user to one re-send, we only actually send on the 1st and 4th clicks anyways. If there is a "back" link as well, it'd look kind of ghetto with one link at full opacity and the other fading in.

This seems ripe for an A/B test.

**Comment by shane-tomlinson** [comment]
ref #2652

**Comment by ryanfeeley** [comment]
We derived that number in Datadog by dividing the number of time the resend confirmation was shown into the number of times the registration success page was shown.

i.e. content.confirm.resend / ( content.signup.success + content.oauth.signup.success)

It's around 24%, and yes, my description simplified things a bit, but it's a lot, no?

When the back link comes in, I'll design that, but I'm thinking the resend link should always be further down, almost at the bottom.

**Comment by johngruen** [comment]
that's hella slow

**Comment by johngruen** [comment]
@ryanfeeley: right...so @shane-tomlinson is saying that an individual user could resend an email up to 4 times. this would mean that that resend event might not be 24% of users hitting the link once each, but rather 6% of users hitting it four times each. It would be helpful to know which is which. 

There's also possibly a larger issue here because if users don't receive emails at all they can never trigger success events. This data doesn't tell us if the resend UI is broken or if some subset of our users simply isn't getting our emails and can therefore never get to the success rate.

**Comment by ryanfeeley** [comment]
To clarify, I'm pretty sure the content.signup.success screen is the **Confirm you account** screen and not the **Account verified** screen. I agree that it would be nice to have more insight into the email flow, but I don't imagine any finding would nullify the proposed copy/fade changes. Copy is a little better, fade in (and I agree, the timing should be faster) also helps user focus on checking their email instead of clicking the whatever button.

**Comment by johngruen** [comment]
@ryanfeeley: your design definitely feels like an improvement, but I was a little unclear about your math. dug into datadog and looked at the following: 

```
{
  "requests": [
    {
      "q": "( sum:fxa.content.confirm.resend{$env}.as_count() / sum:fxa.content.screen.confirm{$env}.as_count() ) * 100",
      "type": "line"
    }
  ],
  "viz": "timeseries"
```

this is a little more direct than your equation since it looks at confirm.resend hits over total pageviews on the confirm page. This still doesn't solve for the multiple click problem (which, I bet your design with ameliorate)*  

Anyway the results are equally damning with a 26.4 % hit rate over the last week.

![screen shot 2015-07-01 at 6 04 03 pm](https://cloud.githubusercontent.com/assets/3323249/8466001/4b999ff8-201c-11e5-8f4d-8e2f9f1699e5.png)

**Comment by johngruen** [comment]
@ryanfeeley: also, its worth noting that your design might screw us here. If people are hitting the resend link becasue they need it (not just becasue it's there) this design basically throws a roadblock in there direction. might be cool to signal the ability to resend right away in a disabled button with a 3 second countdown timer

**Comment by johngruen** [comment]
@ryanfeeley or, for starters do this: 
- move the resend link to the bottom and change the language
- don't do the fade in thing when the page loads, just have the link there...
- user clicks, disable the link, change the copy to try again 5...4...3...2...1
- enable the link again
- repeat until user has used up all 4 resend attempts

**Comment by pdehaan** [comment]
but instead of 5..4..3... maybe make the user wait 15-30 seconds before they can resend. Or maybe even 60s, but maybe thats offensively high since I'd kind of lose it if I had to watch a button label count backwards from 60 before re-enabling.

**Comment by ryanfeeley** [comment]
Faster timing. Just enough so they realize it's not a whatever button.
![manual-resend](https://cloud.githubusercontent.com/assets/68213/8483729/bb328df8-20c0-11e5-9e68-29c1b4f4ed33.gif)

**Comment by shane-tomlinson** [comment]
The fade in, I'm still indifferent to. I'm still not convinced this is going to look great with two buttons, and deviating from the left/right paradigm introduces inconsistency unless done everywhere.

>  maybe make the user wait 15-30 seconds before they can resend. Or maybe even 60s, but maybe thats offensively high since I'd kind of lose it if I had to watch a button label count backwards from 60 before re-enabling.

30 seconds seems reasonable. Timing can be tested to see if it affects resend/completion rates.

**Comment by vladikoff** [comment]
@johngruen @ryanfeeley need more stable / ux designs for this so we can proceed. 

Also let's not forget to track if the new changes improve the flow

**Comment by ryanfeeley** [comment]
What kind of improvements can we detect? Fewer clicks on the Resend button with as many or more account verifications?

**Comment by ryanfeeley** [comment]
@vladikoff I'd still like to text change while we debate this. Shall I file a separate issue?

**Comment by shane-tomlinson** [comment]
> @vladikoff I'd still like to text change while we debate this. Shall I file a separate issue?

Please, we can move forward with that pretty easily.

**Comment by ryanfeeley** [comment]
If I had to specify the fade, I'd say 3 seconds until it starts appearing, and then 1/2 second to fade in. And repeat when the user clicks resend. It's hopefully just enough time for them to check their email instead of just clicking it first. Would love to see this improve verification rate, but really, I think it's just a way to make the experience less inelegant (unless 1/4 of people really do need to click **Resend** and if that's the case we have a bigger problem).

**Comment by johngruen** [comment]
@vladikoff @shane-tomlinson This has probably been mentioned above, but it would be reasonable to register each click as a different event so we can actually see the number of % of users who click once or more. Further, it seems like the timing between hits could tell us a lot (short delays = button mashing and long delays = actually not getting the email)

@ryanfeeley in fact, it might be better if we instrument the metrics on this before changing the UI (minus the string, which we should update) since it will help us establish the actual % rate at which users are hitting the button, rather than the current metric which is obscured by the multiple occurrences of the same event across the same session.

**Comment by shane-tomlinson** [comment]
> but it would be reasonable to register each click as a different event

> "events":["signup.email-optin.visible.true","screen.signup","signup.submit","signup.success","screen.confirm","confirm.submit","confirm.resend","confirm.submit","confirm.submit","confirm.submit","confirm.too_many_attempts","confirm.resend"]

Right now each click is a `confirm.submit`, perhaps we could encode a count to the event name so they are easier to differentiate?

**Comment by shane-tomlinson** [comment]
Why `confirm.submit` you ask? Because the "Resend" button is hooked up to a form submit handler. :/

**Comment by rfk** [comment]
> it seems like the timing between hits could tell us a lot

IIRC we do record this.  I don't think it's exposed to datadog but you can dig up the timings from an individual session from kibana events.

**Comment by vladikoff** [comment]
@ryanfeeley should we work on this or close it?

**Comment by ryanfeeley** [comment]
I think we should still do it because it helps the user focus on reading the instructions which leads them to checking their email. The resend link is an unnecessary distraction in the first few seconds.

**Comment by vladikoff** [comment]
> I think we should still do it because it helps the user focus on reading the instructions which leads them to checking their email. The resend link is an unnecessary distraction in the first few seconds.

:+1:

**Comment by ryanfeeley** [comment]
@vladikoff Can't be more than a teensy bit of code. Wanna work on it in person?

**Comment by ryanfeeley** [comment]
@vladikoff @javaun While I think this design will help users focus on checking their email faster, I do think it should be ranked below having an "Open Google Mail" button feature: https://github.com/mozilla/fxa-content-server/issues/3640

**Comment by larissagaulia** [comment]
@vladikoff, just to sum up:
1) The "Didn't arrive? Resend." link is going to START fading in 3sec after page load/click. 
2) takes 1/2 a minute to full opacity
3) disappears after being clicked.
4-a) go back to step 1) if is the 3rd time being clicked or less. 
4-b) don't show it if already clicked 4 times.

Keep metrics events as-is. i mean, named `confirm.submit`

right?

**Comment by vladikoff** [comment]
@larissagaulia  https://github.com/mozilla/fxa-content-server/issues/2654#issuecomment-118108432

> 2) takes 1/2 a minute to full opacity

Does it take that long in that comment that I linked? 

> 3) disappears after being clicked.

No need to make it disappear. Let's just leave the current behaviour
