### ISSUE TITLE
chronic 404 errors from apple-touch-icon junk

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2655]
Just noting this chronic noise that would be nice to get rid of if there is a reasonable fix.

```
GET /apple-touch-icon-precomposed.png HTTP/1.1         804  
GET /apple-touch-icon-120x120-precomposed.png HTTP/1.1  83  
GET /apple-touch-icon-152x152-precomposed.png HTTP/1.1   9  
GET /apple-touch-icon-76x76-precomposed.png HTTP/1.1     5  
GET /apple-touch-icon-76x76.png HTTP/1.1                 3
```

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/2062

**Comment by pdehaan** [comment]
@vladikoff added the following files in #2340 PR:
- /app/apple-touch-icon-120x120.png
- /app/apple-touch-icon-152x152.png
- /app/apple-touch-icon.png

---

I was trolling through https://mathiasbynens.be/notes/touch-icons and found this trick:
```html
<link rel="apple-touch-icon-precomposed apple-touch-icon" href="apple-touch-icon-precomposed.png">
```

Not sure if we can just specify the precomposed and non-precomposed path and point to the same HREF and see if that silences some of these 404s, without needing to upload another 4-5 images.

/cc @johngruen @ryanfeeley
