### ISSUE TITLE
291 requests to 404 on /unexpected_error in 24 hour sample

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2656]
I was looking at the source of some noise in logs in #2655, and also noticed these errors of a GET for /unexpected_errors with various permutations of uid, code, service, resume and scope in the arguments.

**Comment by jrgm** [comment]
You can drill down on these errors in https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/file/content_http_status.json. If you need help in driving Kibana, I'm happy to show you how it works (or how to beat it with a stick until it shows you something).

**Comment by jrgm** [comment]
Doing a bit of bucketing by browser, these errors are overwhelmingly from `iPhone Safari 600`.

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/2506 ?

**Comment by jrgm** [comment]
Yea. Thought this seemed familiar. Updated other issue with a dashboard on unexpected_error
