### ISSUE TITLE
user is able to sign out if they sign in from firstrun flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2658]
STR

1. Get yer hands on the development firstrun flow (https://github.com/shane-tomlinson/firstrun-example/)
1. Update the SERVER_ORIGIN to `http://127.0.0.1:3030` in https://github.com/shane-tomlinson/firstrun-example/blob/master/client/index.html#L14
1. Start the firstrun sample server.
1. Update the Firefox profile's user.js to point to the local stack
1. open 127.0.0.1:8111
1. Sign up or sign in. Complete verification if signing up
1. Re-open 127.0.0.1:8111 after signup/signin completes.
1. The "sign out" link should not be displayed

ref #2101

**Comment by rfk** [comment]
IIUC, the `account.isFromSync()` check only looks for a sessionTokenContext indicating it came from Firefox desktop.  But in the iframed first-run flow you have `context=iframe` instead of `context=fx_desktop_v1`.

Out of curiosity, what happens if they do sign out?  Does their sync state get busted somehow?  There's not a lot of commentary in the code about why we hide the signout link when the account is from sync.

**Comment by shane-tomlinson** [comment]
> indicating it came from Firefox desktop. But in the iframed first-run flow you have context=iframe

Spot on. [I suspected this would be problematic](https://github.com/mozilla/fxa-content-server/issues/2238#issuecomment-86170861) some day.

**Comment by shane-tomlinson** [comment]
> Out of curiosity, what happens if they do sign out? Does their sync state get busted somehow? There's not a lot of commentary in the code about why we hide the signout link when the account is from sync.

I've been wondering about this too. @ckarlof or @zaach? If there are no adverse effects, I'd just as easily leave this in.

Ref #612, and #731.

From #612:
> Currently, there is a bug in Desktop such after you log into Sync with a previously verified account, you see this page, which is the FxA for the Web signed in page (https://bugzilla.mozilla.org/show_bug.cgi?id=968353). The "Sign out" link is intended to sign you out of your FxA account on the Web. However, it also logs you out of Sync, although in a confusing manner because the browser learns of that fact asynchronously when it later learns the token is invalid.
>
> We shouldn't reuse that token for both "logged in" contexts. When we're using accounts.firefox.com to sign in to desktop, I propose that we don't remember any sessionToken on the Web. If the user subsequently visits accounts.firefox.com, she can log in at that time. Alternatively, we can request a separate sessionToken for managing the user's logged in state on the Web. I think the former would be simpler now.

Although, I will note, using the profile I am currently writing in, I am signed out of https://accounts.firefox.com, but Sync still syncs as expected. Perhaps I am in some strange corner case land.

**Comment by zaach** [comment]
> Although, I will note, using the profile I am currently writing in, I am signed out of https://accounts.firefox.com, but Sync still syncs as expected. Perhaps I am in some strange corner case land.

When you click "Use a different account" it doesn't destroy your session tokens– it just forgets them. That could very well cause your current situation.

**Comment by shane-tomlinson** [comment]
@zaach - could we pow-wow on an approach to fix this?

**Comment by shane-tomlinson** [comment]
@zaach - if I hard code [context](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/reliers/fx-desktop.js#L22) to `fx_desktop_v1` here and remove the [context query param import](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/reliers/fx-desktop.js#L38), the problem goes away. This feels dirty.

Is `sessionTokenContext` only used to determine whether the user can see the signout link? If so, is there any harm in using the relier's `service` instead, which for Sync should always be `sync`?

In [account.js->isFromSync](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L120), I could check whether the `sessionTokenContext` is `fx_desktop_v1` or `sync`.

Or, I could take a similar approach to what you do in user.js when you [updated the user storage format](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/user.js#L182). I could go through each account, check if its `sessionTokenContext` is `fx_desktop_v1`. If that is the case, then set a new field on the account, `sessionTokenService`, equal to `sync`, and use `sessionTokenService` in the [isFromSync check](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L120).

Sorry for the ramble, I'm trying to tease apart these concepts still.

**Comment by shane-tomlinson** [comment]
@zaach - another idea is to store in localStorage `isSessionFromSync`. Straight to the point.

**Comment by zaach** [comment]
> another idea is to store in localStorage isSessionFromSync. Straight to the point.

I like this option. Perhaps the name could reflect what's distinct about these sessions, e.g. `isSessionSharedWithFirefox` or similar.

**Comment by shane-tomlinson** [comment]
> Perhaps the name could reflect what's distinct about these sessions, e.g. isSessionSharedWithFirefox or similar.

I like this far more than any of the previous ideas. Thanks @zaach!
