### ISSUE TITLE
More reliable passwordless login when you're connected to sync

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2662]
As noted in #2391, our passwordless-login experience is currently pretty fragile.  You can do a passwordless login if you've got a special sessionToken that's known to have come from sync.  But this token can be cleared unintentionally for a veriety of reasons, such as switching accounts on the web or clearing your localStorage data.

Let's make this more reliable by having a way for accounts.firefox.com to interrogte the browser's signed-in state.  I can imagine there being a quite elaborate protocol in future, but to begin the simple ability to say "is anybody logged in here?" and get a response back saying "yes, and here's the email, sessionToken, etc" would let us make some solid improvements to the consistency of our experience.

We already have a "session_status" command in about:accounts, it may be just a matter of generalizing this to the non-about-accouts flow:

  https://hg.mozilla.org/mozilla-central/file/f5e3bacfb60e/browser/base/content/aboutaccounts/aboutaccounts.js#l232

Also possibly the same as, or overlaps with, https://bugzilla.mozilla.org/show_bug.cgi?id=1178924

**Comment by shane-tomlinson** [comment]
This idea dovetails nicely with work that @ncalexan wants to do with Fennec.

**Comment by rfk** [comment]
This is now in Aha: https://mozilla.aha.io/features/FXA-39
