### ISSUE TITLE
50{0,2,3}.html files not copied into /dist in train-39

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2663]
This commit https://github.com/mozilla/fxa-content-server/commit/39667b9aa5a599b275546e4a26ce116232e10bcb#diff-9967321b5ac5fdb93f3a809c374359a3R27 in https://github.com/mozilla/fxa-content-server/pull/2543 broke the copying of the 50{0,2,3}.html files into `dist`. In production, these files are served statically by nginx. 

There was a test that showed that this was broken in train-39, and while I ran that test, I somehow missed it. I will put this test into the teamcity CI tomorrow.

But since a failure to copy into `/dist` only becomes apparent in stage, perhaps a better test would be to maintain a manifest of what is expected to be copied to `/dist`. Obviously not every file under `/dist`, but roughly the equivalent of `find ./dist -maxdepth 1`.

**Comment by shane-tomlinson** [comment]
@jrgm - you are very diplomatic. I broke it.

**Comment by vladikoff** [comment]
@jrgm did we not catch this because we do not run server tests against latest? If so we should revisit that...

**Comment by jrgm** [comment]
Yeah, so there is work needed to get this to run against latest, which I was hoping to eventually do; the crux of the issue is that the meaning of fxaProduction is a little overloaded. Even then, the nginx configurations on latest vs. stage/prod are not equivalent (and I spent most of my time trying to figure out how nginx broke the display of /503.html).
