### ISSUE TITLE
Add support for OTP/Google Authenticator

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2665]
@TDA's summer project is to experiment with adding Google Authenticator support to FxA. We'll use the experience & knowledge gained to decide on next 2FA steps, including:

* Whether we really want 2FA
* Whether to add GA support to other clients (Android/FxOS/FxiOS)
* Additional factors

Ref:
* https://mana.mozilla.org/wiki/display/Identity/Two+Factor+Auth+for+FxA
* https://bugzilla.mozilla.org/show_bug.cgi?id=1000620
* https://etherpad.mozilla.org/fxa-2fa
* https://id.etherpad.mozilla.org/fxa-2FA
* https://id.etherpad.mozilla.org/fxa-backend-data-2fa

**Comment by vladikoff** [comment]
@shane-tomlinson should we close this for now until there is a user story / feature in Aha?

**Comment by shane-tomlinson** [comment]
@vladikoff - yes, yes we should. Good call. An [Aha story already exists](https://mozilla.aha.io/features/FXA-37), in the parking lot. Closing here until we can re-prioritize and pursue this work.

Thanks for all the effort and artifacts @TDA, it was a great project to work with you on!

**Comment by TDA** [comment]
@shane-tomlinson Glad to have worked on this with you :)
