### ISSUE TITLE
Remove Session from fxa-client.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2666]
There is one last call to [Session.clear in fxa-client.js](https://github.com/mozilla/fxa-content-server/blob/f0f917ec1bc2ca357fb9cf727a6f53a82e91a456/app/scripts/lib/fxa-client.js#L253). That's the last bit of state that is not passed in. 

It would be nice to do the `Session.clear()` outside of fxa-client.js, making fxa-client just that bit more pure. We could then go as far as rethink the need for fxa-client, I'm starting to wonder whether it has outlived its usefulness.

**Comment by vladikoff** [comment]
@shane-tomlinson i am removing good-first-bug from this unless you think it is easy to explain what to do here

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/1847#issuecomment-296696073 See comment
