### ISSUE TITLE
Further refinements to verification_redirect

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2670]
Capturing the next round of feedback from Pocket on our verification_redirect flow; the following is from Pocket CTO Matt Koidin:

---------------

I was playing around with the "verification_redirect=always" flag today and I'm still not sure the current flow can work for us.

I am hitting:

https://stable.dev.lcip.org/oauth/signin?client_id=f1f14591ed14f570&state=2429c94b2c11b75e3f94acc0d3cb36f5&scope=profile%3Auid%20profile%3Aemail%20profile%3Adisplay_name&verification_redirect=always

After I signup for an account, I get an email asking me to confirm.

When I confirm, the confirm email tab completes the auth and connects to Pocket.

A second or so later, the original tab also completes the auth and connects to Pocket.

The problem is that the user then effectively has two tabs connecting to Pocket - one has our GSF flow (since its a first run) and one does not. There might be some things we can do on our side, but just seems pretty prone to race conditions that I haven't fully analyzed.

My ideal setup would be:

(1) The confirm email tab completes the auth and connects to Pocket.

(2) The original tab doesn't auto-complete. It either remains as is -or- possibly refreshes and just has a "Continue to Pocket" CTA on it.

Could we create a new "verification_redirect" option that facilities that? Perhaps there are three options for verification_redirect:

- original - the original tab is the one that auto completes
- confirm - the confirm tab is the one that auto completes
- always - both tabs complete

Thoughts?
---------

@ryanfeeley @vladikoff I'd like have a chat about further iterations to this flow.  I think it fits squarely within ckarlof's "focus on improvements early in the user experience" guideline.  We shouldn't feel obliged to just give Pocket whatever they ask for, but we should take this feedback seriously.

Matt's "ideal setup" makes sense to me, especially with an explicit "continue" button.  (To be honest, it's morre-or-less what I thought we were going to ship).

**Comment by shane-tomlinson** [comment]
> original - the original tab is the one that auto completes

If the user closes the original tab, or replaces the original tab with the verification tab, no tab completes.

**Comment by rfk** [comment]
I think what Matt means by "original" here is pretty much our default approach, ie the original tab completes or the verification tab completes if it thinks it has replaced the original tab.

**Comment by shane-tomlinson** [comment]
ref #2343

**Comment by shane-tomlinson** [comment]
So really, they want the behavior specified in the closed #2436.

**Comment by rfk** [comment]
Aye, and your comment about "I hope we are not headed for a combinatorial disaster" in #2436 still applies.

**Comment by vladikoff** [comment]
No action here AFAIS, however some discussion here: https://github.com/mozilla/fxa-content-server/issues/2349 

let me know if we need to reopen...
