### ISSUE TITLE
The _custom_rows.scss module is a hot mess

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2671]
Basically can't tell what's going on in that thing. It needs to be cleaned out.

[/app/styles/modules/_custom-rows.scss](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/modules/_custom-rows.scss)

**Comment by shane-tomlinson** [comment]
@johngruen - is it still a hot mess? If not, shut this down.

**Comment by vladikoff** [comment]
> @johngruen - is it still a hot mess? If not, shut this down.


Only ~100 lines, we can revisit this later
