### ISSUE TITLE
Links in the privacy page

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa-content-server#2672]
At: https://accounts.firefox.com/legal/privacy

For example: 
* Mozilla Privacy Policy is not a clickable link.
* "You send us different types of data depending on what features of the Services you use. Learn More." Learn More has odd capitalisation and isn't a link, like you might expect.
* ..."Firefox by clicking here" the here isn't a clickable link.

Looks like there's something funky going on with data-visible-url, so not sure how on purpose is this. Tested on nightly 41.0a1 (2015-06-29).

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/2504
dup of https://github.com/mozilla/fxa-content-server/issues/947
