### ISSUE TITLE
Link to Gmail if the address is @gmail on the email "Confirmation Screen"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2673]
![image](https://cloud.githubusercontent.com/assets/128755/8485306/b9a4857c-20ca-11e5-8085-cad14bccaca6.png)

**Comment by vladikoff** [comment]
from @ryanfeeley 

![image](https://cloud.githubusercontent.com/assets/128755/8485312/c985c8e8-20ca-11e5-9849-12a448a496a6.png)

**Comment by vladikoff** [comment]
For gmail we can do this:
```
https://mail.google.com/mail/u/?authuser=SOME_ADDRESS@gmail.com
```

**Comment by ryanfeeley** [comment]
Excellent! Déjà vu from Manage button in FxA sync.

**Comment by ryanfeeley** [comment]
Love that this gets us a better "whatever" button for so many users cc/ @dolske

**Comment by ryanfeeley** [comment]
@vladikoff I'm sure we both agree that it open in a new tab.

**Comment by vladikoff** [comment]
> @vladikoff I'm sure we both agree that it open in a new tab.

:+1:

**Comment by johngruen** [comment]
@vladikoff @rfeeley: what happens on IOS?

**Comment by vladikoff** [comment]
@johngruen we can only limit this to Desktop or something? or disable on iOS

**Comment by johngruen** [comment]
@vladikoff @ryanfeeley that sounds good as a start, it seems like doing this on mobile could cause trouble depending on context.

**Comment by pdehaan** [comment]
+1, I vote we only do this on Desktop browsers using some clever CSS.

**Comment by pdehaan** [comment]
And now the question that everybody is dying to ask... What "popular web email providers" will/can we support?

- [x] Gmail
- [ ] Yahoo
- [ ] Outlook.com
- [ ] ?

**Comment by johngruen** [comment]
@pdehaan erm, it's hard to target just desktop or just tablets with CSS and presumably we don't want this functionality on tablets either...

**Comment by johngruen** [comment]
which is to say, maybe we need a more rubust solution than just hiding stuff in CSS

**Comment by pdehaan** [comment]
@johngruen: Rats. I was hoping we could use something like `@include respond-to('big') { ... }`, but yeah, I guess that would still probably include most tablets (since I think that breakpoint is somewhere around 520px wide).

**Comment by ckarlof** [comment]
It may be a good idea, but I'm skeptical that opening her Gmail is the user's biggest problem in the signup flow. If we wanted to try it, I'd start with Gmail and see if it improves the verification rate. If it doesn't, then I'd say remove it, because it just adds complexity.

**Comment by rfk** [comment]
This is officially a "user requested feature" :smile::

   https://input.mozilla.org/en-US/dashboard/response/5550361

**Comment by vladikoff** [comment]
Who wrote it ? :eyes:

**Comment by rfk** [comment]
Anonymous user feedback; I guess in theory it could @ryanfeeley trying to create inflated interest in this feature...

**Comment by ryanfeeley** [comment]
For the record, this idea, which is @vladikoff’s improved the verification rate for Gmail users by 6%!

**Comment by vladikoff** [comment]
Yay!
