### ISSUE TITLE
Ensure firstrun flows act as expected

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2674]
Here are the latest mocks:

![09june2015-growth-firstrun](https://cloud.githubusercontent.com/assets/848085/8486259/70e67c4c-20fb-11e5-80d7-e910126f135b.png)

Unlike the normal Sync flow, the "settings" page should be displayed after sign in, and the "account verified" page should be displayed in the original tab after account verification.

ref #2101

**Comment by rfk** [comment]
These mocks seem to indicate customs links in the settings page, like "learn about firefox for iOS".

**Comment by shane-tomlinson** [comment]
> These mocks seem to indicate customs links in the settings page, like "learn about firefox for iOS".

I'm more interested in the flow than the links at this point.

**Comment by jpetto** [comment]
Let's not worry about the links at this point. (I don't think they're finalized anyway.) If the host page can be notified of each action (successful verification/sign in), we can display additional links in the host page.
