### ISSUE TITLE
Enable marketing email opt-in in more languages

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2676]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1179873

We can usefully enable this checkbox for the following languages, which have localized newsletter content:  DE, ES, PT-BR, RU, ID, FR, HU, PL.

**Comment by shane-tomlinson** [comment]
@rfk - Ben Niolet mentions in the referenced bugzilla bug that we'd have to pass the user's language down to Basket. This bug is more than just enabling the opt-in for those locales. :/

**Comment by rfk** [comment]
Per https://github.com/mozilla/fxa-content-server/pull/2452#issuecomment-105720993 the path forward seems to be to just pass on the raw Accept-Lanuage value and let basket figure out how to turn it into a lang.  I'll follow up in the linked bugzilla bug.

**Comment by shane-tomlinson** [comment]
Possibly no work in the content server, dependent on the response to https://bugzilla.mozilla.org/show_bug.cgi?id=1179873#c3. mozilla/fxa-content-experiments#25 has been opened to enable more locales.

**Comment by rfk** [comment]
Looks like they're going to add the ability to send accept-language with the subscription request: https://bugzilla.mozilla.org/show_bug.cgi?id=1188047

We'll need to wait for the final shape of that API before we can move this forward, but I expect it to be a fairly minor change on our side (e.g. passing along literal accept-language header somehow)

**Comment by shane-tomlinson** [comment]
> Looks like they're going to add the ability to send accept-language with the subscription request: https://bugzilla.mozilla.org/show_bug.cgi?id=1188047

So, we have to shuttle the accept-language with the subscribe request and the locale sent in the fxa-register call is ignored?

**Comment by rfk** [comment]
Not *ignored*, but may not be processed reliably by the time they need this information during the subscription process.

**Comment by shane-tomlinson** [comment]
Removing from train-43. Once the Basket portions are available, we can assign this to a train.

**Comment by rfk** [comment]
Basket component in review here: https://github.com/mozilla/basket/pull/143

**Comment by rfk** [comment]
The modified subscription endpoint is now available in basket: https://bugzilla.mozilla.org/show_bug.cgi?id=1193364
