### ISSUE TITLE
Email verification should still work even if cookies are disabled or localstorage is not available

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2677]
For cases such as this, in iOS or browser: 

![](https://cloud.githubusercontent.com/assets/128755/7827747/00b2a744-03f9-11e5-94cc-7edd21b57d76.png)

I propose we get the /verify_email working without cookies. 

ref: https://github.com/mozilla/fxa-content-server/issues/2480
ref: https://github.com/mozilla/fxa-content-server/issues/2479

**Comment by shane-tomlinson** [comment]
How frequently does this occur? Where are users signing up that they are then verifying their email in iOS Safari w/o encountering the "FxA needs cookies" error earlier? I imagine they sign up in desktop then verify on their phone, but that's only a conjecture.

**Comment by vladikoff** [comment]
> How frequently does this occur?

via https://github.com/mozilla/fxa-content-server/issues/2656 "291 requests to 404 on /unexpected_error in 24 hour sample" In my testing I was not able to identify any issues with our JavaScript code, so it could be that many users have iOS devices with cookie off or run in private browser mode.

> Where are users signing up that they are then verifying their email in iOS Safari w/o encountering the "FxA needs cookies" error earlier? 

my guess: They signup for sync on desktop and get an email on their iphone. they open accounts.firefox.com on their phone because that's where the notification comes form.

**Comment by shane-tomlinson** [comment]
From https://github.com/mozilla/fxa-content-server/issues/2480#issuecomment-118808116

---------------------------

I just realized why this happens. In app-start.js, [initializeUuid](https://github.com/mozilla/fxa-content-server/blob/a29dbc519e1f60b19feb4751cf598fc34a87c7f1/app/scripts/lib/app-start.js#L130) occurs before the [cookie check](https://github.com/mozilla/fxa-content-server/blob/a29dbc519e1f60b19feb4751cf598fc34a87c7f1/app/scripts/lib/app-start.js#L641). Since initializeUuid accesses localStorage, an exception is thrown if cookies are disabled. A thrown exception causes the 500 page to be shown.

**Comment by vladikoff** [comment]
probably use sentry instead of regular metrics to track how many cookie issues we get. this is because regular metrics might require local storage or cookies, need to confirm

**Comment by shane-tomlinson** [comment]
With #2708, if the user opens the verification link with cookies disabled, the "Cookies Disabled" screen is shown. If the user then enabled their cookies and clicks "try again", verification completes.

![verify-cookies-disabled](https://cloud.githubusercontent.com/assets/848085/8595232/47411f42-2640-11e5-92f1-c04699142bb3.gif)

Brain fart alert: 
Another further solution is to move the cookies disabled check out to the views, perhaps in a mixin. A view could include the mixin if it knows it requires cookies or access to DOM storage. If the view does not require cookies or DOM storage, it doesn't add the mixin.

the complete_sign_up view, if done in a way that does not require access to DOM storage, would not include the mixin and could complete without worrying about whether cookies are enabled.

Possible? Dunno, we might have to re-write parts of the view, but it's a good thought experiment.

**Comment by vladikoff** [comment]
from mtg: closing this for now, we improved the messaging for this and now it should say something like "user, enable cookies"
