### ISSUE TITLE
Metrics: customize-sync is not in metrics?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2691]
We should see how many people click on 
![image](https://cloud.githubusercontent.com/assets/128755/8524386/e9aaf07a-23c8-11e5-88bb-34bca4db1ad1.png)

**Comment by shane-tomlinson** [comment]
We should, the checkbox-mixin is added to the signup view, and that checkbox has an id.

**Comment by shane-tomlinson** [comment]
Yup, from the logs to `POST /metrics`:

> "signup.checkbox.change.customize-sync.checked","signup.checkbox.change.customize-sync.unchecked"

These need to be added to the [client-metrics doc](https://github.com/mozilla/fxa-content-server/blob/master/docs/client-metrics.md)

**Comment by vladikoff** [comment]
Ah yes found it 
![image](https://cloud.githubusercontent.com/assets/128755/8526072/4f0e1740-23d2-11e5-97ba-885ffea892c0.png)

Thanks @shane-tomlinson!
