### ISSUE TITLE
Confirm the user wants to delete their avatar when she clicks the "X" when changing her avatar

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2693]
I think I accidentally did it and didn't know what happened when my avatar suddenly disappeared.

**Comment by vladikoff** [comment]
@johngruen @ryanfeeley what should this look like? modal or notification in the view?

**Comment by johngruen** [comment]
@vladikoff in new settings world, the change avatar thing will happen in a modal anyway. let's do a confirm notification in the view. I'll work with @zaach to get this done.

**Comment by ryanfeeley** [comment]
Yeah, even though it's done as I specced it, I don't like the X either and have clicked it a few times because it looks like a close icon.

Better?
![clear](https://cloud.githubusercontent.com/assets/68213/8580493/fd254742-2588-11e5-8dc6-712b29e009c5.png)

Or maybe a circle with a line through it? I'll check the icon set.

@jgruen Thoughts?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - how will this play out with the addition of the Gravatar button? A 4 button line?

**Comment by ryanfeeley** [comment]
Yeah, I think 4 wil fit okay.

**Comment by pdehaan** [comment]
@ryanfeeley has "ideas".

**Comment by edmoz** [comment]
let's do this for avatars fx41

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @zaach mentions the new settings page may fix this already. Can you confirm?

**Comment by ryanfeeley** [comment]
@shane-tomlinson He is right, though I need to make a design that lets the user expand and collapse the avatar options inline (so that the only modal is the camera window). This issue should remain assigned to me.

**Comment by ckarlof** [comment]
@zaach says this will be addressed by the settings refactor.

**Comment by vladikoff** [comment]
should be fixed with merge of https://github.com/mozilla/fxa-content-server/pull/2748
