### ISSUE TITLE
Coppa for all users?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#270]
Does Coppa apply all users, regardless or country of origin, or strictly for users living in the US?
I tried getting a clear answer from http://www.coppa.org/coppa.htm but .... words.

If Coppa only applies to persons under 13 in the US (and territories) do we need another screen which forces users to choose a country of origin (assuming we can't seed that from a geoip lookup or something) and see if Coppa applies to them?
Or does Coppa apply to everybody since our servers are US residents?

**Comment by shane-tomlinson** [comment]
I'm going to close this until we decide to revisit.
