### ISSUE TITLE
Refactor app-start.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#2703]
From a [comment in #2480](https://github.com/mozilla/fxa-content-server/issues/2480#issuecomment-119246177):

> I think app-start.js is conceptually quite complex. It does a lot of stuff. In addition to actually doing that stuff, it also encodes the sequence that the stuff is done in and a bunch of state resulting from the stuff. I don't know what the perfect solution would look like, but it would be an improvement if the sequencing was encoded in data rather than in code I think. This is obviously a big-ish refactoring so I'm not suggesting I do it now, but I did want to mention it. Any thoughts?

**Comment by shane-tomlinson** [comment]
Let's ponder the right approach, it's very much like a module loader.

**Comment by rfk** [comment]
As part of this, we should consider whether we can collapse the `User` and `UniqueUserId` models into a single model, rather than having them split across two separate stages of the initialization.

**Comment by shane-tomlinson** [comment]
> As part of this, we should consider whether we can collapse the User and UniqueUserId models into a single model, rather than having them split across two separate stages of the initialization.

I believe, yes, we should.

**Comment by eoger** [comment]
We talked about this today with @shane-tomlinson, @zaach and @vladikoff, the general idea is to create or ideally re-use an existing module system (requirejs with [plugins](http://requirejs.org/docs/plugins.html)). FxDesktop style lazy getters were also mentioned too.
All of this would also eventually leader to a better chunk division by webpack.
To be continued, I'll try to make a prototype soon.

**Comment by shane-tomlinson** [comment]
I'm going to move this out of "in progress" and into ready. This is going to be an ongoing project.

**Comment by shane-tomlinson** [comment]
Are we really going to do this? Probably not. Closing.
