### ISSUE TITLE
Include country information in client metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2718]
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1162192#c28

We may need clarification on the exact requirements here, e.g. do we need to geolocate based on IP, and if so how and where will we do that.

**Comment by vladikoff** [comment]
Let the server look up the ip during post-metrics then throw out the IP.

**Comment by vladikoff** [comment]
@rfk I looked into this a bit, to get this data we have at least 2 options:

Option 1: use one of the geo ip node modules that use a db of ip addresses 
i.e https://github.com/bluesmoon/node-geoip (this uses the MaxMind geoip database that has to be refreshed / redownloaded - there is a module that does that automatically). The "issue" with this approach is that we need to load the database into memory.

Option 2: Mozilla might have a service that will allow us to make an ip request. This is what Heka logs are using currently. issue with this approach is that we need to make external requests to get this data.

**Comment by rfk** [comment]
> The "issue" with this approach is that we need to load the database into memory.

What's the overhead?  IIRC we don't have much memory pressure in content-server webheads currently, since they mostly serve static content.

@vladikoff do the growth team want/need this for completeness with the GA work you've been doing, or can we background this task for a while?

**Comment by rfk** [comment]
We appear to have this thing: https://github.com/mozilla/geodude, which we could run locally or talk to an existing hosted instance, depending on request and memory overhead tradeoffs.

**Comment by vladikoff** [comment]
from quick discussion: this seems to be only useful for security related events. 

Otherwise Heka should be able to process the logs to get answers re: CDNs if needed

**Comment by rfk** [comment]
I feel like we can close this out until it comes back as a specific ask, either from an external team for campaign metrics, or via a specific question that we ourselves would like to answer.  @vladikoff what do you think?

**Comment by vladikoff** [comment]
> I feel like we can close this out until it comes back as a specific ask, either from an external team for campaign metrics, or via a specific question that we ourselves would like to answer. @vladikoff what do you think?

Agreed!

**Comment by shane-tomlinson** [comment]
> I feel like we can close this out until it comes back as a specific ask, either from an external team for campaign metrics, or via a specific question that we ourselves would like to answer. @vladikoff what do you think?

I have a question - Are there parts of the world that are far from the FxA servers where load time performance suffers?
