### ISSUE TITLE
Expose the ability to add a profile picture in /settings to everyone

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2722]
We currently have some rules around hiding this affordance in the settings page, and we need to decide when to remove these rules so everyone can add a profile image from the settings page. 

Profile images on Sync pref pane is scheduled to go live in Fx41 (https://bugzilla.mozilla.org/show_bug.cgi?id=1171253). When do we expose this? Sometime in Beta? The concern was to minimize the time period that release users could add an avatar and not see it in their browser, but also make sure we lead the actual release of Fx41 to give us a little breathing room. 

@rfk, @edmoz, @zaach, please coordinate.

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/1582 ?

**Comment by ckarlof** [comment]
Ok, I'll close this one and narrow the scope of #1582.

**Comment by zaach** [comment]
:+1:
