### ISSUE TITLE
Only process supported/production locales during grunt build?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2729]
Currently, I *believe* we're processing all the locales for things returned by [fxa-content-server-l10n](https://github.com/mozilla/fxa-content-server-l10n/) repo, or from the [legal-docs](https://github.com/mozilla/legal-docs/) repo.

We currently track the 42(!?) production locales in [./server/config/production-locales.json](https://github.com/mozilla/fxa-content-server/blob/master/server/config/production-locales.json) versus about 100 locales in [./server/config/local.json-dist `supportedLocales`](https://github.com/mozilla/fxa-content-server/blob/master/server/config/local.json-dist#L16) versus about 108 locales listed in https://github.com/mozilla/fxa-content-server-l10n/tree/master/locale.

Not sure if only looping over the `production` locales during `grunt build` and generating those specific locales pages and resources would speed up the build any.

**Comment by vladikoff** [comment]
Seems like a bit of moving parts with this, closing until required
