### ISSUE TITLE
Send a WebChannel message to Fennec when the user signs out 

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2731]
Exactly like #2152, but for the "Sign out" link.  Android could use this for ncalexan/fxa-web-signin-addon to remove the native account.

/cc @zaach @shane-tomlinson

**Comment by shane-tomlinson** [comment]
Let's discuss.

**Comment by shane-tomlinson** [comment]
Ref #2658. In fx-desktop, we do not allow the user to sign out if the user signed up/in for Sync. Depending on whether that behavior is still needed, we might want to consider that for Fennec too.

**Comment by shane-tomlinson** [comment]
From IRC:

> 21:16 <stomlinson> nalexnader: Currently we do not allow users that sign up/in for Sync to sign out.
> 21:17 <stomlinson> nalexander: We hide the sign out button. We can enable it for Fennec if you want, but you'll have to handle the sign out message.
> 21:17 <nalexander> stomlinson: tieing the two together more closely "at the begin" should include tieing them more closely "at the end".
> 21:18 <nalexander> stomlinson: yeah, keep hiding it.  It's good for now.

From that, I'm going to close this issue as a WONTFIX for now. We can re-open if we decide to enable sign out of Sync from FxA.
