### ISSUE TITLE
Switch to secure-handlebars module?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2732]
Per: https://github.com/mozilla/fxa-content-server/issues/2659#issuecomment-120034606,

I saw the [**secure-handlebars**](https://github.com/yahoo/secure-handlebars) module on npm the other day and looked interesting, and may prevent some good XSS vectors from our externally loaded repos.

[**secure-handlebars**: Known Limitations & Issues](https://github.com/yahoo/secure-handlebars/blob/master/README.md#known-limitations--issues)

It looks like they also have a [**express-secure-handlebars**](https://www.npmjs.com/package/express-secure-handlebars) module which may be useful since we use Express.

---

https://github.com/mozilla/fxa-content-server/search?q=handlebars&type=Code&utf8=%E2%9C%93

**Comment by vladikoff** [comment]
We use mustache on the front-end, and we don't have that many server templates, so I don't think it will help
