### ISSUE TITLE
"Unauthorized" error when switching from /signup to /signin

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2741]
Found in https://accounts.firefox.com/ver.json (commit 726a047b79daf6ec52b893bd7acfd65525fc9ae4)

```js
{
  version: "0.40.0",
  commit: "726a047b79daf6ec52b893bd7acfd65525fc9ae4",
  l10n: "86056510dd",
  tosPp: "d40365ec45"
}
```

---

### Steps to reproduce:
1. Go to https://accounts.firefox.com/signup
2. Open your developer console.
3. Click the **Already have an account? Sign in.** link at the bottom.

### Actual results:

```
Unauthorized
    c.View.extend.logError @ 778ac72e.main.js:7
    (anonymous function)   @ 778ac72e.main.js:8
    F                      @ 778ac72e.main.js:6
    E                      @ 778ac72e.main.js:6
    l                      @ 778ac72e.main.js:6
```

Looking at this on latest.dev.lcip.org, it seems to be getting triggered from this code:
```js
    /**
     * Log an error to the event stream
     */
    logError: function (err) {
      err = this._normalizeError(err);

      // The error could already be logged, if so, abort mission.
      // This can occur when `navigate` redirects a user to a different
      // screen and an error is passed. The error is logged before the screen
      // transition, the new screen is rendered, then the original error is
      // displayed. This avoids duplicate entries.
      if (err.logged) {
        return;
      }
      err.logged = true;

      if (typeof console !== 'undefined' && console) {
        console.error(err.message || err); // -------- THIS LINE RIGHT HERE, APPARENTLY.
      }
```

It looks like `logError()` may be getting called from [`displayAccountProfileImage()` in /app/scripts/views/mixins/avatar-mixin.js:36](https://github.com/mozilla/fxa-content-server/blob/43150210383e7b349a9b97b4154ce047607ac9a0/app/scripts/views/mixins/avatar-mixin.js#L36).

### Expected results:

No error. Or something.

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/2481
