### ISSUE TITLE
Improve the message that appears when a user goes offline

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2749]
Do I hear an echo?
<img width="772" alt="unexpected-error" src="https://cloud.githubusercontent.com/assets/68213/8663441/b9e64bb6-297f-11e5-9f51-4213df1b9576.png">

**Proposed:**
h1. No connection
h2. You must be connected to the internet to manage your account.
button. Try again

**Comment by shane-tomlinson** [comment]
Are we in a cave?

**Comment by pdehaan** [comment]
I'm guessing "Unexpected error" doesn't _always_ mean "No connection" though, and not sure we could make an /offline route, because if the user is offline with no connection would it load?

**Comment by vladikoff** [comment]
Closing in favour of https://github.com/mozilla/fxa-content-server/issues/2998
