### ISSUE TITLE
Oauth "enter password" page triggers a Password Manager prompt with "No Username"

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#2754]
This is case when we have a cached username and prompt for a password. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1182671

**Comment by shane-tomlinson** [comment]
From the bugzilla bug:

-------------------------------

STR:
 0. Start with a fresh profile (or one w/ no firefox account password saved at least)

 1. Visit https://accounts.firefox.com/signin and sign in. Dismiss the "save password" prompt. (Do not save your password).

 2. Visit https://find.firefox.com/ and click "Sign in" button
    --> You're just prompted to enter your password.

 3. Enter your password and sign in.

ACTUAL RESULTS:
A "remember password" prompt appears, with Username = "No username" and Password = the password that I just entered.  (From the user's perspective, this is a useless prompt; of course I don't want to save just my password without a username. If I want to save anything, I'd like to save both.)

EXPECTED RESULTS:
Prompt should contain my username.  In other words: this oauth sign-in page should expose my username in a way that the password-manager can see.

MattN probably knows what the best course of action would be here.  (Maybe some hidden <input> on the page, with my username pre-entered?)

**Comment by shane-tomlinson** [comment]
We already have an `input type="hidden"` with the email address:

![screen shot 2015-07-14 at 18 32 15](https://cloud.githubusercontent.com/assets/848085/8688948/be898368-2a56-11e5-99bb-12c592fb644a.png)
