### ISSUE TITLE
Add an affordance to report a problem

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2765]
Was just talking to @TDA about this.

### Possible STR

Go to https://accounts.firefox.com/signup
See a bad translation in my language

### Expected

Have a way to report a bad translation

### Actual

Have to file a bug with bugzilla or not report it. 

@mathjazz is there a link to we can direct users to report this? are there any other products that do this?

**Comment by mathjazz** [comment]
I'm afraid we don't have better place to link to than https://l10n.mozilla.org/.

I'm not aware of other products doing that, but I love the idea. Maybe we should set an example for other projects to follow.

Maybe related: https://github.com/mozilla/contribute.json/issues/61

**Comment by pdehaan** [comment]
+1 on a contribute.json file.
Could we point the "report a bad translation" link to the fxa-content-server-l10n repo's new issue page?

**Comment by vladikoff** [comment]
From meeting: 
We mostly agree that there should be some way to report it but not sure how. 
Where can we link users? Is it a form? input mozilla / SUMO ? Is there something else we can use?

**Comment by mathjazz** [comment]
As I already said, the best place is probably https://l10n.mozilla.org/.

We could link to Verbatim:
https://localize.mozilla.org/projects/accounts/

But locales also started moving to Pontoon:
https://pontoon.mozilla.org/projects/firefox-accounts/

**Comment by vladikoff** [comment]
@ryanfeeley if you can think of a place that we can add this to any of the current pages then let me know. 

Looking at current designs I don't think we have space for a link to https://l10n.mozilla.org/ but maybe in the future

**Comment by ryanfeeley** [comment]
Great idea to get people more involved. I think the best place would be where we show the legal links. I would keep the message generic. Something like: "Report an issue".

Settings section:
![report-an-issue2](https://cloud.githubusercontent.com/assets/68213/8959877/304d637c-35db-11e5-8e76-4382833d41be.png)

Elsewhere:
![report-an-issue1](https://cloud.githubusercontent.com/assets/68213/8959874/2e1cdfba-35db-11e5-99f5-85c70077b1e7.png)

Clicking the link would include details about the page (page title, URL, date/train) and would allow the user to elaborate.

We could deploy as a test and see how many issues are L10n related.

**Comment by pdehaan** [comment]
Where would that link go? It's pretty generic. 

Should we just redirect to https://github.com/mozilla/fxa-content-server/issues/new and they can fill out a new bug which we triage and move to the l10n or legal-docs or fxa-auth-server repos if needed? Or just to the more generic https://github.com/mozilla/fxa-content-server/issues page where they can search for an existing bug before filing a new one?

Or should we create a wiki page in the **mozilla/fxa** repo which points the users to the correct repo if they want to report a content server or auth server issue versus a l10n or legal-docs translation issue?

**Comment by vladikoff** [comment]
Maybe something like this: 
![image](https://cloud.githubusercontent.com/assets/128755/8963714/849c1a68-35ef-11e5-9c58-e49fcf848e93.png)

**Comment by ryanfeeley** [comment]
I like where this is going. How about:
<img width="473" alt="file-an-issue" src="https://cloud.githubusercontent.com/assets/68213/8986465/52ef16f8-36aa-11e5-9922-7befb5187656.png">

**Comment by vladikoff** [comment]
@ryanfeeley so

Translation would go to: https://l10n.mozilla.org/
Problem with sync - Where would this go?
Firefox Accounts - Where would this go??

**Comment by ryanfeeley** [comment]
How about:
Problem with sync: https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Firefox%20Sync%3A%20Cross-client
Firefox Accounts: https://github.com/mozilla/fxa-content-server/issues/new

If only there was a way to include platform details or referer URL.

**Comment by vladikoff** [comment]
@ryanfeeley great stuff!

@rfk thoughts on links above ^ ?

**Comment by vladikoff** [comment]
GitHub also supports bug templates, example: https://github.com/theintern/intern/issues/new?body=Description:%0A%0ASteps+to+reproduce:%0A%0A1.%20%E2%80%A6%0A2.%20%E2%80%A6%0A3.%20%E2%80%A6%0A%0AExpected%20result:%0AActual%20result:%0A%0AIntern%20version:%0A%0AAny%20additional%20information:

**Comment by vladikoff** [comment]
However that means users need a GitHub account, so I think GitHub will not work for this.

**Comment by ryanfeeley** [comment]
@vladikoff !!
![158pc](https://cloud.githubusercontent.com/assets/68213/8986913/626ec50e-36ac-11e5-9696-49a2ebeea2c9.gif)

**Comment by ryanfeeley** [comment]
I'm also not averse to use creating a Twitter account. Is email too firehosey?

**Comment by vladikoff** [comment]
@ryanfeeley this also exists: https://input.mozilla.org/en-US/feedback/firefox?#moreinfo + https://input.mozilla.org/en-US/feedback?

**Comment by rfk** [comment]
I like where this is going!

We don't have a great funnel for getting stuff from input.mozilla.org back to where devs can see it, although I think that's getting better.

I think it might be simpler to funnel both sync and FxA issues into bugzilla in the first instance, for consistency, and for a lot of little reasons (we have more control over the experience, where' more likely to get an email at which we can follow up with them, we might one day be able to log into bugzill with FxA, ...)

**Comment by vladikoff** [comment]
We need some SUMO links too , see: https://github.com/mozilla/fxa-content-server/issues/1710

**Comment by rfk** [comment]
I like the idea of offering SUMO links in places where it makes sense.  In particular, a SUMO link for "can't sign in to your account" would be useful in general, and would be a good place to do an official version of the "FxA China" help message from [1].

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1131472

**Comment by rfk** [comment]
> Translation would go to: https://l10n.mozilla.org/

I'm not convinced this is the best place to send users from a link that says "suggest a better translation".  The link text promises some action, but goes to a landing page from which the next action is not obvious.  In the absence of anything better, I think we should link to a bug template input page, and take responsibility for triaging the resulting bug to the appropriate place (including finding someone to translate the report for us if we need to).

Is this issue growing too big and diverse?  We could break it down into specific implementation bugs like:

* Create bug input templates for reporting issues in transations, in sync, and in FxA itself
* Create a "report an issue" page linking to the above
* Add targeted help links to SUMO articles in places where users are likely to run into trouble:
  * in authentication error messages
  * on password change and reset pages
  * in our outgoing emails

That's probably enough stuff that we can spin up a "help affordances" milestone and sprint on this for a cycle or two.

**Comment by vladikoff** [comment]
from meeting with SUMO this will not be so useful at this moment.

**Comment by ryanfeeley** [comment]
@vladikoff So we are giving up on the idea of allowing users to report a problem?

**Comment by vladikoff** [comment]
@ryanfeeley yeah pretty much, we pitched it to SUMO during a meeting

**Comment by ryanfeeley** [comment]
@vladikoff So we are giving up on the idea of allowing users to report a problem?
