### ISSUE TITLE
Add contribute.json file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2767]
Ref #2765 

We should add a /contribute.json file, and probably point it to our parent *mozilla/fxa** repo.
https://contribute.paas.allizom.org

Example: https://www.mozilla.org/contribute.json

**Comment by vladikoff** [comment]
@pdehaan why is it "https://contribute.paas.allizom.org", is there an official one or is that it?

**Comment by pdehaan** [comment]
@vladikoff I don't know, man. That's just the link that they pasted at the top of https://github.com/mozilla/contribute.json. But I agree, totally weird that they couldn't have found a better domain.

**Comment by pdehaan** [comment]
Rough first draft:
```json
{
    "bugs": {
        // THESE POINT TO CONTENT SERVER. BETTER IDEAS?
        "list": "https://github.com/mozilla/fxa-content-server/issues",
        "mentored": "https://github.com/mozilla/fxa-content-server/labels/good-first-bug",
        "report": "https://github.com/mozilla/fxa-content-server/issues/new"
    },
    "description": "Firefox Accounts is the authentication and authorization system for Cloud Services at Mozilla, providing access to services such as Firefox Sync and Firefox Hello.",
    "keywords": [
        "fxa",
        "accounts"
    ],
    "name": "Firefox Accounts",
    "participate": {
        "docs": "https://github.com/mozilla/fxa",
        "home": "https://github.com/mozilla/fxa",
        "irc": "irc://irc.mozilla.org/#fxa",
        "irc-contacts": [
            "chilts",
            "ckarlof",
            "dcoates",
            "jrgm",
            "pb",
            "pdehaan",
            "rfkelly",
            "seanmonstar",
            "stomlinson",
            "vladikoff",
            "zaach"
        ],
        "mailing-list": "https://www.mozilla.org/about/forums/#dev-fxacct"
    },
    "repository": {
        "license": "MPL-2.0",
        "tests": "https://travis-ci.org/mozilla/bedrock/", // NOT SURE WHAT TO PUT HERE
        "url": "https://github.com/mozilla/fxa"
    },
    "urls": {
        "dev": "https://latest.dev.lcip.org",
        "nightly": "https://nightly.dev.lcip.org/", // I THINK THIS WAS A 404
        "prod": "https://accounts.firefox.com",
        "stable": "https://stable.dev.lcip.org",
        "stage": "https://accounts.stage.mozaws.net"
    }
}
```

**Comment by vladikoff** [comment]
Yeah `"nightly": "https://nightly.dev.lcip.org/",` does not exist anymore

>    "tests": "https://travis-ci.org/mozilla/bedrock/", // NOT SURE WHAT TO PUT HERE

Maybe we can skip that one

**Comment by vladikoff** [comment]
@pdehaan bugs you can link to https://github.com/mozilla/fxa or https://github.com/mozilla/fxa#fix-bugs--

**Comment by pdehaan** [comment]
@vladikoff Updated sample JSON above. Not sure about pointing to **mozilla/fxa** since it wouldn't list any "good-first-bugs" or probably have any real issues. But maybe a good enough place to capture user bugs and then ask them to re-file over in _repo {x}_ instead once we triage it.

**Comment by pdehaan** [comment]
Kind of goofy, but another option for the bugs links may be to point to our waffles.
Something like https://waffle.io/mozilla/fxa-content-server?label=good%20first%20bug,good-first-bug

Still not 100% ideal since that wouldn't include all the fxa-auth issues, but may be better than pointing to the fairly empty and meta **mozilla/fxa** bug list.

**Comment by rfk** [comment]
I'm going to clean up this label nonses, I swear.  We'll standardize on one "good first bug" label across all our repos, making a nice neat link like:

  https://waffle.io/mozilla/fxa?label=good-first-bug

(Also, I think that lists of labels are conjunctive, not disjunctive, so the previous link would only show issues with *both* labels.)

**Comment by vladikoff** [comment]
https://contribute.paas.allizom.org looks dead, closing until we need this
