### ISSUE TITLE
.success and .error classes appear too close to the headers on settings page

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2770]
The settings page has the .success and .error classes appear too close to the h1 header in the page.

#### STR:

1. Sign up for FxAccounts
2. Open up the url for validating the email.

Observed Results:
﻿﻿﻿﻿https://www.dropbox.com/s/8pmywwrba7ff22q/Screenshot%202015-07-16%2015.49.02.png?dl=0

Expected Results:
Proper Alignment of the success and error messages.

**Comment by zaach** [comment]
This no longer affects settings, so I'll remove that milestone.

**Comment by vladikoff** [comment]
no longer an issue with the new design:

![image](https://cloud.githubusercontent.com/assets/128755/9880764/0e97ed20-5b9b-11e5-8649-5b839fedee76.png)
