### ISSUE TITLE
Cached user should not skip password reset warning

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2774]
When a cached user forgets their password and clicks to reset their password, they go directly to the email sent screen. They should instead be taken to the Reset password screen so they see this copy:
> For security reasons, resetting your password will erase your Sync data from our servers. A new Sync backup will be created from your local browsing data.

**Comment by vladikoff** [comment]
![rec](https://cloud.githubusercontent.com/assets/128755/10919858/13692690-823b-11e5-9e54-c7bfadb53ffa.gif)

This was fixed.
