### ISSUE TITLE
Throttled text regressed to previous version.

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2775]
I noticed when overdoing it with password reset form that our message has regressed.

https://github.com/mozilla/fxa-content-server/pull/848/files

> **Current:** Client has sent too many requests
> **Proposed:** Attempt limit exceeded. Try again later.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/2623

**Comment by shane-tomlinson** [comment]
Dup of #2623, closing.
