### ISSUE TITLE
determine if sync 1.1 migration param is being sent and make sure it's graphed in datadog

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#2783]
there should be sync 1.1 migrators signing up, but I'm not seeing it on datadog. Can someone check in on this?

I'll msg vlad the url i'm looking at.

**Comment by rfk** [comment]
More specifically, Firefox will include `migration=sync11` in the URL when the user is coming from the migration process.  AFAICT this should correspond to a `migration:sync11` *tag* on events in datadog, but I don't know enough about datadog to advise on how to surface such tags.

**Comment by vladikoff** [comment]
> determine if sync 1.1 migration param is being sent 

it is being sent, created 2 graphs here:
https://app.datadoghq.com/dash/57926/fxa-content-server---sync
