### ISSUE TITLE
Handle short-lived access tokens for fetching profile info

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2785]
We currently cache the `accessToken` and don't attempt to refresh it if auth fails... we should fix that.

**Comment by rfk** [comment]
I wonder if it'd be simpler not to cache it at all, rather than implementing complex retry logic.  Eventually we intend for these things to be quite short-lived.

**Comment by zaach** [comment]
👍 I have a wip that removes them from the local storage cache.
