### ISSUE TITLE
firstrun - send a signal to the parent on unsuccessful signup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2791]
An unsuccessful signup would be when there are form validation errors.

https://bugzilla.mozilla.org/show_bug.cgi?id=1150231#c19

Ref #2101, #2790

**Comment by rfk** [comment]
@shane-tomlison it looks like this is the last remaining open `/firstrun` bug; can it be safely closed?

**Comment by shane-tomlinson** [comment]
> @shane-tomlison it looks like this is the last remaining open /firstrun bug; can it be safely closed?

It cannot be, we haven't done it yet.

**Comment by rfk** [comment]
Heh, fair enough, my appologies for an inelegantly phrased question.

Do you want to continue working on it this cycle, or should we re-consider prioritization given https://github.com/mozilla/fxa-content-server/issues/2101#issuecomment-126403302 ?

**Comment by shane-tomlinson** [comment]
> Do you want to continue working on it this cycle, or should we re-consider prioritization given #2101 (comment) ?

@rfk - The Growth team wants this, I'm not convinced it'll really provide much value. This is one of those things that I think will be safe to think about for a cycle or two, to figure out a non-terrible approach.

**Comment by shane-tomlinson** [comment]
I'm going to shut this down until this is really needed.
