### ISSUE TITLE
Strip HTML tags from display name in new Settings page UI?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2794]
![firefox_accounts](https://cloud.githubusercontent.com/assets/557895/8790685/9a683296-2f05-11e5-90be-6607aa4cd5ca.png)

I never did see the `alert()`, so I assume everything is getting escaped properly, but I guess it only takes once place where we don't escape it before it gets amusing (either on our site, or if we're passing arbitrary HTML to reliers, etc).

**Comment by pdehaan** [comment]
Nevermind, if I manually refresh the page, I see a glorious alert!
:micdrop:

---

<img width="617" alt="manage_account__account_picturedisplay_namepassworddelete_account" src="https://cloud.githubusercontent.com/assets/557895/8790803/f1af88a0-2f06-11e5-86fe-3eb038adbe47.png">

**Comment by vladikoff** [comment]
:fearful:

**Comment by rfk** [comment]
:boom:

**Comment by shane-tomlinson** [comment]
> :boom:

On a tangential note, this is one of the many reasons I like nunjucks, it parses the template into an AST, then escapes any DOM node attributes so this doesn't happen.

**Comment by TDA** [comment]
What the :O :O :O We are XSS'able? :| :\ This is serious stuff :( @pdehaan Are you able to hit other types of XSS? Can you provide a link that alerts when I open it? If so, we need to move this to high priority :( @pdehaan

**Comment by pdehaan** [comment]
@TDA Not that serious, the new settings UX is still WIP and not really published. You can play with it at https://ux.dev.lcip.org/settings while we work out the ghosts.
Plus, I think at this point I'd be XSSing myself. This would probably only be serious when other reliers start displaying a user's display name. But yeah, would be interesting to test more once we integrate 123done to use a display name and see if I can to some cross site `alert(document)` type stuff.

**Comment by rfk** [comment]
We should also double-check these values when we store them; I filed https://github.com/mozilla/fxa-profile-server/issues/126

**Comment by rfk** [comment]
@pdehaan a related challenge: could you craft an email address that would pass our validation check [1]but include an XSS vector?  I don't think so because we don't allow `<` or `>`, but maybe there's additional tricks we should watch our for?

[1] https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/validators.js#L46

**Comment by TDA** [comment]
@pdehaan This should help: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
and this http://ha.ckers.org/xss.html --> Original from rsnake :D golden I'd say.

**Comment by shane-tomlinson** [comment]
@rfk - We need to revisit this. We put a lot of effort into preventing XSS early on, I want to make sure we haven't slipped since.

All external input that has the potential to be displayed should be validated & possibly html escaped before being stored. It's the only way to really prevent bad values from making it back to the user. Otherwise a bad actor could bypass the front end's validations entirely by calling the auth server endpoints directly.

**Comment by vladikoff** [comment]
Setting train 43 as target because I heard that this is part of the new settings ui

**Comment by pdehaan** [comment]
@rfk So far no dice on a crafty email address (since we apparently blacklist `<` and `>` and `;` and `"`), but I'll keep going through OWASP docs.

**Comment by rfk** [comment]
> possibly html escaped before being stored

This is a classic tension of responsibilities. Storing it in html-escaped form makes it easy to include safely in web-content, but harder in other places.  For example, some of these values might show up in plaintext emails or native browser UI.

Plenty of words have been spilled on whether it's better to escape on input or output:
  * http://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/
  * http://security.stackexchange.com/questions/32394/when-to-escape-user-input
  * http://stackoverflow.com/questions/9512873/is-it-better-to-escape-encode-the-user-input-before-storing-it-to-database-or-to

I tend to favour "store in canonical form, encode on the edges" but it does make more work for the edges.

@shane-tomlinson let's spin off a separate issue or thread to discuss the broader approach, and we can keep this issue focused on fixing the immediate problems for train-43.

**Comment by rfk** [comment]
> let's spin off a separate issue or thread to discuss the broader approach

Which of course you've already done, and in a sec-sensitive bug just in case we actually find anything that would give us trouble in production:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1186386

**Comment by zaach** [comment]
This code path no longer exists in the settings branch.
