### ISSUE TITLE
Test signup flows (esp. from first-run) in Windows 10

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2801]
Windows 10 is coming soon (on the order of "days" IIUC) and makin the upgrade a smooth experience is a big priority for Mozilla.  @pdehaan has graciously volunteered to test the FxA flows in Firefox on Windows 10 just to make sure that they're working as intended.  FWIW I don't expect any problems but if there are any, we need to know with some urgency.

@pdehaan please report any findings here, even if it's just "every looks good :+1:"

(And my apologies for tossing this on the pile at the last minute, it only just showed up on my radar)

**Comment by shane-tomlinson** [comment]
No need to panic, I knew this was coming and have done basic Windows 10 testing (signup & signin from 123done). No problems so far.

@rfk - all browsers that are not Firefox > 40 will break in the firstrun flow. The firstrun flow requires the browser respond to certain requests (`can_link_account`) made via WebChannels. If the browser does not support WebChannels or the ability to respond to the event, everything stops.

**Comment by rfk** [comment]
@shane-tomlinson :heart:

**Comment by rfk** [comment]
> all browsers that are not Firefox > 40 will break in the firstrun flow.

This flow is version-specific though, right?  Browsers older than 40 should not be given the post-40 first-run flow?

**Comment by shane-tomlinson** [comment]
> This flow is version-specific though, right? Browsers older than 40 should not be given the post-40 first-run flow?

That's right. Fx 39 is given the v39 version of the flow, 39.05 the 39.05 version. Here are the URLs from the last two versions of Fx:

> https://www.mozilla.org/en-US/firefox/39.0/firstrun/
> https://www.mozilla.org/en-US/firefox/39.05/firstrun/

And Fx 40's variant lives under 40.0
> https://www.mozilla.org/en-US/firefox/40.0/firstrun/

**Comment by rfk** [comment]
Win10 is out, I think we can close this - thanks @shane-tomlinson and @pdehaan!
