### ISSUE TITLE
Offer users an escape from the confirm screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2815]
Currently when users register an account, they are stuck at the account confirmation screen until they check the email account and click the verification link.

We should provide a link back to /signup labelled **Use a different account**.

If they are Sync or Hello users, we should clear the seeded account that exists in their client in an unverified state. If it is unverified in FxA, we should remove it there too.

<img width="540" alt="fxa-use-a-different-account" src="https://cloud.githubusercontent.com/assets/68213/8853183/86fdb842-3127-11e5-992b-1a0102839731.png">

**Comment by pdehaan** [comment]
@ryanfeeley Dupe of #2002; "Stuck in the email confirmation state with a wrong email"?

**Comment by ryanfeeley** [comment]
Yeah, I had talked to @vladikoff this week about doing one just for non-Sync users, and started on this, but we should just cover all users in one bug.
