### ISSUE TITLE
need dashboard of single vs multi-device FxA users

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#2817]
Product teams would like this as well as a KPI toward many initiatives.  Can we do this in datadog?  Breaking this out by device count by desktop or mobile would be extra credit.

**Comment by rfk** [comment]
These kind of "cumulative count" queries don't seem like a great fit for datadog.  I think the best way to get this is to do https://github.com/mozilla/fxa-auth-server/issues/983 and then run reports off it, which will give us both multi-device users and decent churn statistics.

**Comment by rfk** [comment]
fx-content-server is not the best place to track this bug; closing in favour of https://github.com/mozilla/fxa/issues/21 and linked work
