### ISSUE TITLE
Win 10 + Edge 20.10162.0.0 Upload Avatar isn't circular

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2824]
Found in https://latest.dev.lcip.org/ver.json:

```js
{
  version: "0.42.0",
  commit: "9ec6b1812e76fa9576462bd9c4cebf4544698f9f",
  l10n: "df6ea29f7f",
  tosPp: "27d35cc967"
}
```

![capture2](https://cloud.githubusercontent.com/assets/557895/8885139/c539b760-3211-11e5-84fb-1655459a2693.PNG)

**Comment by vladikoff** [comment]
related https://github.com/mozilla/fxa-content-server/issues/1821

**Comment by pdehaan** [comment]
I have a Windows 10 laptop, I can recheck this.

**Comment by vladikoff** [comment]
Thanks Peter!

**Comment by pdehaan** [comment]
![capture](https://cloud.githubusercontent.com/assets/557895/10890593/a10db004-814d-11e5-9f23-86bf12b40d5d.PNG)

No idea what this means, but here's what I'm currently seeing in IE Edge w/ production (0.48.0 -- commit 35797ad)

**Comment by vladikoff** [comment]
![ie](https://cloud.githubusercontent.com/assets/128755/10890682/639c7704-8167-11e5-9edc-e5a4ba7ae321.gif)

**Comment by pdehaan** [comment]
![capture_ffnightly](https://cloud.githubusercontent.com/assets/557895/10890715/7037bfbe-814e-11e5-8229-83a5b90b8700.PNG)

Actually, it doesn't look like it's working on FF Nightly either on Win 10.

**Comment by pdehaan** [comment]
Upon further investigation, we can probably ignore me.
The Camera app on Windows 10 isn't even detecting my integrated Lenovo camera, so looks like it may be something related to my computer. :slow_clap:

**Comment by shane-tomlinson** [comment]
@pdehaan - We are going to be jerks and close this, can you re-open if you see this problem elsewhere?
