### ISSUE TITLE
Cannot do camera avatar upload on Win 10 w/ IE 11 (works on Edge)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2825]
Found in https://latest.dev.lcip.org/ver.json:

```js
{
  version: "0.42.0",
  commit: "9ec6b1812e76fa9576462bd9c4cebf4544698f9f",
  l10n: "df6ea29f7f",
  tosPp: "27d35cc967"
}
```

![capture3](https://cloud.githubusercontent.com/assets/557895/8885241/a992db08-3212-11e5-909f-f4069dfb0692.PNG)
**Figure 1:** IE 11 on left. Edge on right.

**Comment by zaach** [comment]
IE 11 doesn't support getUserMedia, says Vlad.

**Comment by vladikoff** [comment]
> IE 11 doesn't support getUserMedia, says Vlad.

There are some hacks via Flash and etc, but not worth it
