### ISSUE TITLE
Bump to npm@2 in .travis.yml instead of hardcoding 2.4?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2827]
Per https://github.com/shane-tomlinson/fxa-crypto-utils/pull/12#issuecomment-123828708 conversation w/ @jrgm.

Currently we're installing **npm@2.4** in the [.travis.yml](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/.travis.yml#L32-L33) file.
That's great for Node 0.10.x which comes w/ **npm@1.4.x** but not so great for Node 0.12 which comes w/ **npm@2.11.x**. Which means we're basically downgrading npm.

Should we, like, not do that?

### Node 0.10:
```sh
$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.40

$ node --version
v0.10.40

$ npm --version
1.4.28

$ nvm --version
0.23.3

$ npm install -g npm@2.4
```
**NOTE:** Upgrading from **npm@1.4.28** to **npm@2.4**.

---

### Node 0.12:
```sh
$ nvm install 0.12
######################################################################## 100.0%
Now using node v0.12.7

$ node --version
v0.12.7

$ npm --version
2.11.3

$ nvm --version
0.23.3

$ npm install -g npm@2.4
```
**NOTE:** Downgrading from **npm@2.11.3** to **npm@2.4**

**Comment by vladikoff** [comment]
> not so great for Node 0.12 which comes w/ npm@2.11.x. Which means we're basically downgrading npm.

The downgrade has no issues so far. Did you find any?

**Comment by pdehaan** [comment]
@vladikoff: I didn't notice anything, I was just pointing it out in case there have been notable stability improvements between npm@2.4.x and npm@2.13.x that we may want to pick up.

Plus, [this comment](https://github.com/shane-tomlinson/fxa-crypto-utils/pull/12#issuecomment-123831614) from @jrgm in a different repo:
> @jrgm: I don't think anyone suggested 2.4.1 or any specific version. Doing npm@2 is what we should use. (One of these releases will break our travis run someday, but npm has pretty good turnaround on fixing the things (most edge cases) that break in any release, and if we really have to, we can just temporarily pick a non-broken version to get our tests passing again until a fix comes).

**Comment by vladikoff** [comment]
updated to use npm@2

**Comment by pdehaan** [comment]
Ref #2846
