### ISSUE TITLE
Travis is (agressively) caching deps

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2828]
Per https://github.com/mozilla/fxa-content-server/pull/2826#issuecomment-124767546

Current [package.json](https://github.com/mozilla/fxa-content-server/blob/issue-2789-de-eslint-complexity/package.json#L77) shows that we should be installing **eslint-config-fxa@1.8.1**, but the `npm ls` in the travis logs shows that we're installing the older **eslint-config-fxa@1.7.0**.

Not sure if there is a way to automatically kill all Travis caches when we change the package.json or npm-shrinkwrap.json file, but yeah. It looks like we bumped all the dependencies in #2806, #2807, #2809, and #2814, but Travis is still using old, cached versions of node_modules.

**Comment by TDA** [comment]
nit: aggressive. 
I can see that it was friday evening :P

**Comment by vladikoff** [comment]
Something is weird with Travis caching or maybe some npm issue, the only way to resolve this on our end is to disable travis cache or make sure we clear it when dependencies are updated.

You can see more in the linked issue above.
