### ISSUE TITLE
invalid style attributes found on anchor tags in i18n

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2831]
So, running the #2742 html parser on the i18n/ folders, we get this:
https://www.dropbox.com/s/vlaf2pi294l23vb/Screenshot%202015-07-26%2012.11.10.png?dl=0

Should `style` attributes be allowed on `a` tags? Is this a new addition that needs a change to our parser? or is this not allowed?

@shane-tomlinson

**Comment by pdehaan** [comment]
If I'm reading this correctly, the `style` attributes are coming from: [/templates/verify.html:55](https://github.com/mozilla/fxa-auth-mailer/blob/6aac195ff6d1692b239c7906fd1becd95ee85ebf/templates/verify.html#L55):

```
#: templates/verify.html:7
msgid ""
"For more information, please visit <a href='https://support.mozilla.org' "
"style='color: #0095dd; text-decoration: none;'>Mozilla Support</a>"
msgstr ""
"Pour davantage d'informations, veuillez consulter <a "
"href='https://support.mozilla.org' style='color: #0095dd; text-decoration: "
"none;'>l'assistance de Mozilla</a>"
```

```html
{{{t "For more information, please visit <a href='https://support.mozilla.org' style='color: #0095dd; text-decoration: none;'>Mozilla Support</a>"}}}
```

**Comment by TDA** [comment]
@pdehaan Is that a good thing or a bad thing?

**Comment by rfk** [comment]
It's a good thing in the sense that it's our own style attribute being reflected, not l10ners inserting their own custom styles :-)

Since these are email templates, I guess we have to allow it one way or another, in order to be compatible with display in a wide variety of email clients.  I think @johngruen did a recent refactor of that template which may have introduced it.

**Comment by vladikoff** [comment]
> @pdehaan Is that a good thing or a bad thing?

`style` attr is an XSS attack vector, we must find a way to only allow it in emails + do an exact match with the original template and make sure it was not changed.

**Comment by shane-tomlinson** [comment]
@TDA put in major effort to fix this! @vladikoff says it found problems in the wild. Works as advertised. Closing.
