### ISSUE TITLE
5xx oauth authorization errors still redirect to relier

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2832]
Found while investigating #2830, ref mozilla/fxa-oauth-server#315
#### Basic STRs
1. Update the OAuth server to return a 5xx error for POST /v1/authorization
2. Visit 123done, redirect to FxA.
3. Sign in
4. I'm redirected back to 123done - eh?
#### Expected

A big error message is displayed.

**Comment by shane-tomlinson** [comment]
After digging in a bit more.

It seems that it is possible to call /v1/authorization without a scope for some reliers and not others. It seems to depend on whether a token is requested or not. If a token is requested, scope must be specified. If token is not requested, then scope does not need to be specified. @rfk - is that correct?

@zaach - You also might be able to help here. Errors fetching an OAuth token are surpressed [on this line in account.js](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/app/scripts/models/account.js#L108). git blame just says it's `mozilla`s code. I imagine this is expected behavior, but it seems odd. How come we are surpressing errors there?

**Comment by shane-tomlinson** [comment]
ref #2834

**Comment by zaach** [comment]
@shane-tomlinson IIRC we ignored errors because fetching the token there (within `fetch`) is an optimization, i.e. methods that need a token will attempt to fetch one if it's missing anyway. Now that we don't cache `accessToken`s in localStorage that optimization is not too useful.

**Comment by vladikoff** [comment]
from mtg: kill it for now, unless we see it again.
