### ISSUE TITLE
Attempt to fetch avatar is made after failure to fetch OAuth token

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2835]
#### STR:

1. Apply the diff from below
1. Visit 123done
1. Open the developer console, enable network requests
1. Click "sign in" on 123done
1. Watch the developer console make the request to the oauth server's `/v1/authorization`, then the profile server's `/v1/avatar`

#### Expected:
1. No extra request to the profile server. The user isn't authorized.

#### The proof:
![screen shot 2015-07-27 at 14 01 57](https://cloud.githubusercontent.com/assets/848085/8906697/853f1b24-3468-11e5-83d8-277c62e3eb6a.png)

#### The diff:
```diff
diff --git a/app/scripts/lib/oauth-client.js b/app/scripts/lib/oauth-client.js
index 09f24bc..2ffd6c0 100644
--- a/app/scripts/lib/oauth-client.js
+++ b/app/scripts/lib/oauth-client.js
@@ -22,6 +22,9 @@ function (xhr, OAuthErrors) {
 
   OAuthClient.prototype = {
     _request: function (method, endpoint, params) {
+      if (params) {
+        delete params.scope;
+      }
       return this._xhr[method](this._oAuthUrl + endpoint, params || null)
         .fail(function (xhr) {
           var err = OAuthErrors.normalizeXHRError(xhr);
```

Ref https://github.com/mozilla/fxa-oauth-server/issues/315

**Comment by vladikoff** [comment]
@shane-tomlinson to check this

**Comment by shane-tomlinson** [comment]
@shane-tomlinson to check if this has been fixed.

**Comment by shane-tomlinson** [comment]
Since https://github.com/mozilla/fxa-oauth-server/issues/315 is fixed, the new diff is:

```diff
diff --git a/app/scripts/lib/oauth-client.js b/app/scripts/lib/oauth-client.js
index 09f24bc..65913a4 100644
--- a/app/scripts/lib/oauth-client.js
+++ b/app/scripts/lib/oauth-client.js
@@ -22,6 +22,8 @@ function (xhr, OAuthErrors) {
 
   OAuthClient.prototype = {
     _request: function (method, endpoint, params) {
+      params = {};
+
       return this._xhr[method](this._oAuthUrl + endpoint, params || null)
         .fail(function (xhr) {
           var err = OAuthErrors.normalizeXHRError(xhr);
```

The request for the users avatar no longer occurs if the request to `/authorization` has failed:

![screen shot 2015-10-12 at 16 36 49](https://cloud.githubusercontent.com/assets/848085/10431871/8fd22b8e-70ff-11e5-995b-cab1feb7cfe0.png)

Closing as fixed.
