### ISSUE TITLE
Add floating labels for display name and delete account panes in settings 2.0 remix

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2848]
Per https://github.com/mozilla/fxa-content-server/pull/2748#issuecomment-125771978

Another thing I casually noticed which may or not be settings 2.0 related, but I find the floating prompts (on ux.dev.lcip.org) to be a bit inconsistent (especially now that all the settings are on a single page).
Basically if you change your password, you get a nice floating prompt that says "Old password" and "New password" floating above the form inputs when you start typing. It may be worth sprinkling that magic on the other form fields (Display name and Delete account) for consistency sake.
You can also tell me to shut up and file it as a separate issue (or just shut up). Both perfectly fine responses.
/cc @ryanfeeley

**Comment by ryanfeeley** [comment]
I believe that @johngruen had originally suggested we implement this broadly. I'm game for that as long as it doesn't collide with validation awkwardly.

**Comment by johngruen** [comment]
@ryanfeeley...it was a thought anyway. Let's start with settings here and work our way outward should we deem it necessary. You're right to suggest that this will likely require some fine tuning.

**Comment by shane-tomlinson** [comment]
I like consistency.

**Comment by shane-tomlinson** [comment]
See #2212 to add the text to the reset password field labels too.
