### ISSUE TITLE
Cannot use camera to take avatar picture on FF Nightly (42) on Windows 10

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2849]
via https://accounts.firefox.com/settings/

```json
{
    "version": "0.41.1",
    "commit": "9f1b71ca69f49e75a26b873c46733f63b53e0a27",
    "l10n": "fceb086f0b",
    "tosPp": "d40365ec45"
}
```

I was trying to take an avatar photo with my camera on my Lenovo w/ Win 10 (Preview) and it just returns a weird camera icon with a line through it. Didn't see anything interesting in my developer console telling me why it was failing.

![capture5](https://cloud.githubusercontent.com/assets/557895/8948196/43912b94-3559-11e5-9a72-c50dff033a48.PNG)

**Comment by pdehaan** [comment]
Can reproduce on https://latest.dev.lcip.org/settings/avatar/camera too.
Again, nothing in my developer tools console, but this was the first time I saw the easter-egg in the wild:

```
"             _.-~-.
           7''  Q..\
        _7         (_
      _7  _/    _q.  /
    _7 . ___  /VVvv-'_                                            .
   7/ / /~- \_\\      '-._     .-'                      /       //
  ./ ( /-~-/||'=.__  '::. '-~'' {             ___   /  //     ./{
 V   V-~-~| ||   __''_   ':::.   ''~-~.___.-'' _/  // / {_   /  {  /
  VV/-~-~-|/ \ .'__'. '.    '::                     _ _ _        ''.
  / /~~~~||VVV/ /  \ )  \        _ __ ___   ___ ___(_) | | __ _   .::'
 / (~-~-~\\.-' /    \'   \::::. | '_ ` _ \ / _ \_  / | | |/ _` | :::'
/..\    /..\__/      '     '::: | | | | | | (_) / /| | | | (_| | ::'
vVVv    vVVv                 ': |_| |_| |_|\___/___|_|_|_|\__,_| ''

Hi there, nice to meet you!

Interested in having a direct impact on hundreds of millions of users? Join
Mozilla, and become part of a global community that’s helping to build a
brighter future for the Web.

Visit https://careers.mozilla.org to learn about our current job openings.
Visit https://www.mozilla.org/contribute for more ways to get involved and
help support Mozilla.

---

If you don't want to see this message next time, run this JS statement:

    easterEgg.disableEasterEgg()
"
```

**Comment by pdehaan** [comment]
Clicking "Take picture" doesn't actually take my picture, but sets my avatar to the no camera icon:
![capture6](https://cloud.githubusercontent.com/assets/557895/8948299/929abc9a-355a-11e5-92da-bc08cb0c061a.PNG)

**Comment by vladikoff** [comment]
@pdehaan does the camera work here: https://www.simpl.info/getusermedia/ ?

**Comment by pdehaan** [comment]
@vladikoff Fails for me on Win 10 using FF 39 (release) and 42.0a1 (nightly).
I'll check in IE11+Edge shortly to see if it's possibly a webcam issue.

**Comment by pdehaan** [comment]
Weird. Same behavior on Edge (shows the broken camera icon).
Oddly, IE11 doesn't even prompt me for camera access and just shows a big black box.

**Comment by pdehaan** [comment]
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1188964

**Comment by vladikoff** [comment]
Works fine in stable and nightly for me.

![image](https://cloud.githubusercontent.com/assets/128755/8965165/bd47b176-35f7-11e5-9623-bc0dfa8ee0a0.png)

**Comment by pdehaan** [comment]
Weird. @vladikoff Do you have a Windows laptop, or is that in a VM? Maybe I just have a bad laptop/install.

**Comment by vladikoff** [comment]
@pdehaan that's in a VM. does the camera work anywhere at all? some photo app or something
