### ISSUE TITLE
 Only allow /signin (not /signup) in Firefox for iOS

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2860]
From @ncalexan in https://bugzilla.mozilla.org/show_bug.cgi?id=1182255

------------------------

It's possible that the Sync state machine for Firefox for iOS won't implement "clean server" initialization, at least for v1.  Such initialization is tricky and error-prone; we didn't implement it for the first few Fennec releases.

To work-around, we might restrict Firefox for iOS to only allow /signin (not /signup) on the content server.  The idea is that if you already have a Firefox Account, then you likely already have a Desktop (or Android) Sync client, which will have initialized the server.  This isn't perfect, since the server can be wiped, or you can be node-migrated, etc -- but it's a decent work-around.

This ticket tracks:

* having fxa-content-server folks estimate the work to not show /signup;
* whatever Firefox for iOS work is needed to opt-in to this configuration.

**Comment by shane-tomlinson** [comment]
@rfk has already been working on this so assigning to him.

**Comment by shane-tomlinson** [comment]
Decided in that bug, Fx on iOS will initially specify `context=fx_ios_v1`. We will create a new authentication broker for this.

**Comment by shane-tomlinson** [comment]
A new column has been added to [the ever growing flow doc](https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA) to define the expected flow.

**Comment by vladikoff** [comment]
Not sold on `fx_ios_v1`, see comment in https://github.com/mozilla/fxa-content-server/issues/2861#issuecomment-126342306

**Comment by rfk** [comment]
I'm PTO this coming week and won't be able to do much work on this, de-assigning myself for that period.

**Comment by rfk** [comment]
Initial work to support the custom context value: #2865

And for referene, a hack I did to hide the signup links on FxiOS: https://github.com/mozilla/fxa-content-server/commit/c3f70d0bfc8c67eaa429418eb7b56a8307c31174
