### ISSUE TITLE
add support for `context=fx_ios_v1`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2861]
As noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1182255#c12

This will be used so that we can control the Fx on iOS flow independently of other environments.

Ref #2860

**Comment by vladikoff** [comment]
@rfk What about a different strategy where ios reports its capabilities instead? 
I was hoping we could unify the way we do Firefox <=> Content Server communication and not create a context for each environment which adds complexity:

```
 if (this._isFirstRun()) {
          this._authenticationBroker = new FirstRunAuthenticationBroker({
            iframeChannel: this._iframeChannel,
            relier: this._relier,
            window: this._window
          });
        } else if (this._isFxDesktopV2()) {
          this._authenticationBroker = new FxDesktopV2AuthenticationBroker({
            window: this._window,
            relier: this._relier
          });
        } else if (this._isFxDesktopV1()) {
          this._authenticationBroker = new FxDesktopV1AuthenticationBroker({
            window: this._window,
            relier: this._relier
          });
        } else if (this._isWebChannel()) {
          this._authenticationBroker = new WebChannelAuthenticationBroker({
            window: this._window,
            relier: this._relier,
            fxaClient: this._fxaClient,
            assertionLibrary: this._assertionLibrary,
            oAuthClient: this._oAuthClient,
            session: Session
          });
        } else if (this._isIframe()) {
          this._authenticationBroker = new IframeAuthenticationBroker({
            window: this._window,
            relier: this._relier,
            assertionLibrary: this._assertionLibrary,
            oAuthClient: this._oAuthClient,
            session: Session,
            channel: this._iframeChannel,
            metrics: this._metrics
          });
        } else if (this._isOAuth()) {
          this._authenticationBroker = new RedirectAuthenticationBroker({
            window: this._window,
            relier: this._relier,
            assertionLibrary: this._assertionLibrary,
            oAuthClient: this._oAuthClient,
            session: Session
          });
        } else {
          this._authenticationBroker = new BaseAuthenticationBroker({
            relier: this._relier
          });
        }
```

**Comment by shane-tomlinson** [comment]
@vladikoff - Can you say more?

**Comment by vladikoff** [comment]
Using `v1` and `v2`, we ask for `capabilities` using a message before load, rough draft: 

### Firefox 42 says:
```
undefined 
```
(no response)
### Firefox 43 says:
```
    let capabilities = {
        chooseWhatToSync: "web_v1"
    }
```

### iOS v1 says
```
    let capabilities = {
        signInOnlyMode: "signin_v1"
    }
```
which means: I cannot do sign_up man :(


### iOS v2 says (now supports all the features)
```
    let capabilities = {
        chooseWhatToSync: "web_v1"
    }
```

### Fennec
```
    let capabilities = {
        chooseWhatToSync: "web_v1"
    }
```

**Comment by rfk** [comment]
@vladikoff :+1: to something like this for the long term, but I think we need a simpler fallback option on the timeframes we're talking about here for iOS.

**Comment by ncalexan** [comment]
@rfk @vladikoff having the iOS client respond to new messages is not complicated.

As discussed with @vladikoff in IRC, what I worry about are edge cases (messages dropped, etc) and timing: what if the client takes 0.5 seconds to respond?  5 seconds?

**Comment by rfk** [comment]
I really like this "capabilities handshake" approach and I think it feeds into a bunch of other stuff we want to do with the web-based signin flow in future (like asking if there's anyone natively logged in to the browser).

But over in https://bugzilla.mozilla.org/show_bug.cgi?id=1182255#c11 I'm hearing "we need this locked down in a matter of days", which doesn't sound like enough time to coordinate all the necessary details of such a protocol.  @ncalexan please correct me if the timeline looks more generous from your perspective :-)
