### ISSUE TITLE
Short screens shouldn't have shadows 

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#2862]
@pdehaan brought this up over in settings 2.0

If page isn't tall enough, I'm still seeing slightly rounded corners and dropshadows.
![manage_account__account_picturedisplay_namecommunication_preferencespassworddelete_account](https://cloud.githubusercontent.com/assets/557895/8945427/27c1152c-353c-11e5-8f45-2a7662f51976.png)
**Figure 1:** Fine.

---

![manage_account__account_picturedisplay_namecommunication_preferencespassworddelete_account](https://cloud.githubusercontent.com/assets/557895/8945439/3b0999f6-353c-11e5-872b-923bb738fd50.png)
**Figure 2:** Page is "too narrow" and goes full width in a mobile-esque view. Lookin' great!

---

![manage_account__account_picturedisplay_namecommunication_preferencespassworddelete_account](https://cloud.githubusercontent.com/assets/557895/8945451/5e393738-353c-11e5-85f1-7bdfd3fca0b2.png)
**Figure 3:** Page is "too short", and goes into full width mode (similar to figure 2), although now we still see rounded corners and drop shadows. We may need a bit of viewport CSS tweakin.

**Comment by rfk** [comment]
@zaach per our discussion yesterday, it sounds like we can't get much @johngruen bandwidth this cycle, do you want to take this yourself or move it out of "now"?

**Comment by zaach** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/commit/7bf7fbf6bebbe5483b1031d2d2abaf38a83c6cc7.
