### ISSUE TITLE
requests to basket by proxy must be cancelled for a timeout of ~10 seconds

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2870]
The front end code now timeouts requests to the basket server if the request takes more than 2500ms, which is great for the the end-user. 

However, that still leaves the basket-proxy-server waiting for up to 60 seconds (I think an ELB or other LB on the remote end of the call controls this timeout). This has significant impact operationally. @ckolos and I had the pleasure of getting up at 3am (my time, 5am his time) after alarms and pagers went off when the basket api server went down for **5 hours** Friday morning and nobody knew how to fix it.

This hanging call gets recorded as a 60 second HTTP response in the nginx server logs on our side. It would be better if the basket-proxy-server aborted its request to the basket api in 10 seconds or less, given the frontend timeout of 2500. 

Longer term, it is **unacceptable** to continue to directly communicate with an API server that can only provide one 9 of uptime, and a different solution for integrating with Basket must be developed.

**Comment by rfk** [comment]
Ouch :-(

I assume an acceptable alternative would introduce a queueing layer between us and basket, but I'm a little wary of the user-experience aspects fo doing that.  If I click "unsubscribe" and it tells me I was unsubscribed, I'd be pretty surprised to see marketing emails still coming through because the unsubscribe request is pending in a queue somewhere.

Question: if the basket-proxy-server went away and the front-end code was able to talk directly to basket, would that be any more acceptable than the current situation?

**Comment by rfk** [comment]
@jrgm was the alarm for "there were too many failing requests" or was it specifically due to the 60s+ responses?

**Comment by jrgm** [comment]
Yeah, I understand that UX would be harder to do. On the other hand, **five hours** of 'System Unavailable' shown to users trying to subscribe or unsubscribe isn't exactly a quality user experience, not to mention **20 minutes** of the same **every single night**.

> Question: if the basket-proxy-server went away and the front-end code was able to talk directly to basket, would that be any more acceptable than the current situation?

So, that would eliminate long requests seen on the server-side, but it wouldn't improve the problem that the end-user is shown an error message about 2% of the time. There hasn't apparently been any progress on https://bugzilla.mozilla.org/show_bug.cgi?id=1179496 since 2015-07-10, and we shouldn't have users interact with a service that has demonstrated such a lack of stability.

> @jrgm was the alarm for "there were too many failing requests" or was it specifically due to the 60s+ responses?

It was a monitor for average latency seen via ELB metrics and also shown in nginx logs.

**Comment by rfk** [comment]
> It was a monitor for average latency seen via ELB metrics and also shown in nginx logs.

I guess my question is, if we'd had this timeout in place in the proxy, would you still have been paged?

**Comment by jrgm** [comment]
I haven't done the math to see if that would have cause the average to drop below the threshold. I said 10 seconds as a ballpark number that is > 2.5 seconds on the frontend (from the way I read that code). Could maybe do 5 seconds, but still haven't done the math on how much/many of these long queries would get below an alert threshold. However, this issue, to timeout the request to basket earlier, is really just a bandaid for the very short term.

**Comment by rfk** [comment]
> However, this issue, to timeout the request to basket earlier, is really just a bandaid for the very short term

Indeed.  ISTM the only two acceptable long-term options are going to be:

  1) decouple from basket via a work queue, and do what we can about the UX, or
  2) run our own copy of basket and try to keep the damn thing up.

Likely (1) will turn out to be more attractive on balance...

**Comment by rfk** [comment]
From the kibana HTTP logs for content-server, I see peaks of around 300 requests to "GET /basket/lookup-user" every hour.  These are the folks who are visiting the "communication preferences" page and could potentially see the "service unavailable" message when basket goes down.  That's low compared to our total traffic, but not so low that these poor folks deserve hours of service outage on a regular basis.

**Comment by rfk** [comment]
@jrgm I filed #2873 to make sure we keep working on a longer-term gameplan for this thing
