### ISSUE TITLE
Decouple from any synchronous requests to the basket API

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2873]
Per #2870, the basket API has persistently terrible uptime and reliability, and it regularly makes for a bad experience for our users and for ops.  We need to find a way to integrate with it more asynchronously, which probably means storing more state on our side.

Strawman for something that might work:

* continue splitting off basket-proxy-server into its own repo
* give it an actual database, and let it store a local copy of the "is this user subscribed?" bit
* subscribe/unsubscribe operations flip the bit locally and enqueue a task that syncs it with upstream basket

**Comment by billmaggs** [comment]
Ryan should restate the problem.

**Comment by rfk** [comment]
I turned this into an Aha card at https://mozilla.aha.io/features/FXA-52
