### ISSUE TITLE
Avatar preview get clipped when rotating camera

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2879]
Found in https://latest.dev.lcip.org/ver.json (commit 9b6beda3ce88c81bed0b877447c6bc6be5a044f4)

```js
{
  version: "0.42.0",
  commit: "9b6beda3ce88c81bed0b877447c6bc6be5a044f4",
  l10n: "d4eafc2302",
  tosPp: "27d35cc967"
}
```

---

### Steps to reproduce:
1. Tested on my trusty LG Nexus 4.
2. Go to https://latest.dev.lcip.org/settings/ and change your avatar.
3. Select Camera, then share your front or back facing camera.
4. Rotate your phone from portrait to landscape.

### Actual results:
![screenshot_2015-08-04-09-42-43](https://cloud.githubusercontent.com/assets/557895/9066970/69e46e88-3a8f-11e5-8cad-55b933233854.png)
**Figure 1 (before):** Phone in portrait mode. Lookin' good!

![screenshot_2015-08-04-09-42-57](https://cloud.githubusercontent.com/assets/557895/9066980/89722af6-3a8f-11e5-92b0-81ad17ae007f.png)
**Figure 2 (after):** Phone in landscape mode. Note that half my preview gets clipped. Despite that, clicking the "Take picture" button takes a normal looking photo. So only the preview is messed up.

### Expected results:
Circular preview should remain circular while rotating the phone.

**Comment by shane-tomlinson** [comment]
@zaach - on my Galaxy S6, portrait mode has cut off sides:

#### Portrait 

![screenshot_2015-09-07-11-10-08](https://cloud.githubusercontent.com/assets/848085/9714653/408d14cc-5551-11e5-90c1-3051eeea89e7.png)

#### Landscape

![screenshot_2015-09-07-11-10-21](https://cloud.githubusercontent.com/assets/848085/9714659/5322f174-5551-11e5-9c2a-1cc1fbbcabbc.png)

**Comment by vladikoff** [comment]
Change to "Follow up quality work" and unblock the milestone if we have to
