### ISSUE TITLE
Generate metrics doc?

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-content-server#2884]
It might be easier to keep track of metrics if there were documented within the view files and extracted out. Devs would be able to easily see/modify the expected events. This could look like a comment in the file with a delimiter to let a preprocessor know it's special, then just markdown:

```
/* ~Metrics~

# change_password
* error.change-password.auth.121 - account locked
* change-password.unlock-email.send - user attempted to send unlock email
* change-password.unlock-email.send.success - unlock email successfully sent

*/
```

At the very least, we could append these to the per screen section of the client metrics doc.

**Comment by vladikoff** [comment]
> It might be easier to keep track of metrics if there were documented within the view files and extracted out.

Instead of that, would it be possible for unit tests to extract out that information? so some special way of running Mocha that collects all events that happened and then we can append that list?

**Comment by zaach** [comment]
That'd be neat; although mocks and stubbing could possibly interfere.

**Comment by vladikoff** [comment]
No plans to do this right now. will come back to this if we start adding a lot of metrics events
