### ISSUE TITLE
Desktop uses "entryPoint", we expect "entrypoint"?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2885]
First Sentry report while train-42 was in prod for a few minutes:

```
Query:	
service=sync&context=fx_desktop_v1&entryPoint=VALUE
```

https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser-fxaccounts.js#439

@shane-tomlinson would this be an issue for our metrics and stuff that the casing is wrong for the query param of `entryPoint`?

**Comment by vladikoff** [comment]
I notice something else creates this query: `service=sync&context=fx_desktop_v1&entrypoint=abouthome`, should we lower case entrypoint or something

**Comment by shane-tomlinson** [comment]
Did this just recently change? I have always seen a lowercase `p` until I updated Beta today.

**Comment by shane-tomlinson** [comment]
At least I could swear it has always been entrypoint. Going back to Fx 39, clicking on the Sign in to Sync on the hamburger menu, I see entryPoint. So confused.

**Comment by rfk** [comment]
I also filed a client bug to work towards consistent capitalization: https://bugzilla.mozilla.org/show_bug.cgi?id=1193179
