### ISSUE TITLE
Add polyfills for bind and other functions for <es5

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2886]
We got 26 reports (while Sentry was live with train-42):

```
experiments.bundle in r.getFirstMatch
Object function (t){return this.activeSubjectKeys[t.key(e)]} has no method 'bind'
```

Should we bother supporting Android 2.3.3?
## Stack

![image](https://cloud.githubusercontent.com/assets/128755/9078262/4f686530-3b09-11e5-9fc4-378241bced44.png)

**Comment by vladikoff** [comment]
We can try just adding https://github.com/es-shims/es5-shim and it might all fix itself

**Comment by zaach** [comment]
:+1: shim it. :ship:

**Comment by shane-tomlinson** [comment]
> :+1: shim it. :ship:

Ugh. That's another 5kb of library. Can we just shim in the parts we know we use, like Array.prototype.(filter|map|reduce) & Function.prototype.bind? Alternatively, move back to underscore functions, or create a shim that defers to the underscore functions?

**Comment by vladikoff** [comment]
> Alternatively, move back to underscore functions

Talked to Zach about this yesterday and using .bind with underscore is pretty ugly and requires a lot of refactoring, so we wanted to shim this instead

**Comment by vladikoff** [comment]
> That's another 5kb of library.

Hopefully we can just load it if required and not for all users

**Comment by shane-tomlinson** [comment]
> Hopefully we can just load it if required and not for all users

That sounds like it'll require feature detection and a lot of overhead.

**Comment by shane-tomlinson** [comment]
My guess is a certain subset of Android users verify their emails on their phones, similar to what we've seen on the iPhone. So this might be a bit higher priority than I initially suspected. I'm a bit loathe to add another library when we use only a subset of its functionality. We could shim in the features we are using manually. Another alternative is to could convert a ES5 Array operations to underscore operations since there are far fewer of those than `.bind`s, and shim in Function.prototype.bind.

**Comment by zaach** [comment]
Looking at our code a bit more, there's a pretty good mix of `_.bind` and Function.prototype.bind in there... We should either use one or the other and I'm leaning toward underscore in light of these issues. It'll probably be less of a refactor than going the other way and removing all our uses of underscore.

**Comment by zaach** [comment]
Tangential, we might want to look into lodash as an alternative to underscore so we can generate a custom build.

**Comment by vladikoff** [comment]
> Tangential, we might want to look into lodash as an alternative to underscore so we can generate a custom build. 

1. Yeah +1 to ditch underscore and use lodash, but out of scope for this issue. I guess the decision is between `_.bind` and `shim`. It seems you and Shane would rather use `_.bind`, so let's do that and fix those up.

2. In addition, the error itself is not in our code but in the experiments bundle code that means we have to fix Able's bind as well

**Comment by shane-tomlinson** [comment]
> In addition, the error itself is not in our code but in the experiments bundle code that means we have to fix Able's bind as well 

w.r.t. `Function.prototype.bind` (or similar), I'm pretty easy. That particular function is pretty trivial to [shim in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill). We should check for other ES5 features that are used by Able or the verification flow just to make sure. I'm thinking in particular some of the `Array.prototype` functions. I have an old Android phone somewhere, not sure what version it's running. I'll dig it out and see once I get home.

**Comment by vladikoff** [comment]
Talked to @philbooth about this a bit!

**Comment by shane-tomlinson** [comment]
> Talked to @philbooth about this a bit!

Deets? Should we just polyfill the function and call it a day?

**Comment by philbooth** [comment]
> Deets? Should we just polyfill the function and call it a day?

Fwiw, I'm in favour of polyfilling selectively on a function-by-function basis.

Vlad and I were discussing it in the context of [this](https://github.com/mozilla/fxa-content-server/pull/3344/files#r48553775). I'd much rather see a gradually-growing dedicated module for polyfills than conditional code like that. The polyfills are interpreted once and automatically degrade with old clients, in-line conditions are interpreted per-invocation and are likely to get left behind in the codebase long after old clients have gone away.

**Comment by shane-tomlinson** [comment]
> Vlad and I were discussing it in the context of this. I'd much rather see a gradually-growing dedicated module for polyfills than conditional code like that.

100% in agreement.

**Comment by shane-tomlinson** [comment]
Since so many users try to verify their email on mobile devices, it probably behooves us to fix this specific problem and polyfill the Function.prototype.bind. We can add a small polyfill file in the page head before able.

**Comment by vladikoff** [comment]
Let's add `bind`, `endsWith` ^

**Comment by vladikoff** [comment]
check `trim`, `forEach`

**Comment by vladikoff** [comment]
@shane-tomlinson revisiting this quickly. do we just need `bind` for sure? and a check to make sure we use $.trim() instead of .trim (currently used ~4 times)? and _.forEach instead .forEach (currently used ~6 times)

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson revisiting this quickly. do we just need bind for sure? and a check to make sure we use $.trim() instead of .trim (currently used ~4 times)? and _.forEach instead .forEach (currently used ~6 times)

I feel we should just polyfill the functions we use, it'll be less brittle to remembering "hey, I can't use [].forEach, but must use _.forEach".

**Comment by vladikoff** [comment]
>I feel we should just polyfill the functions we use, it'll be less brittle to remembering "hey, I can't use [].forEach, but must use _.forEach".

Okay sounds good!

**Comment by pdehaan** [comment]
I thought you were moving to ES2015 and babel?

**Comment by shane-tomlinson** [comment]
> I thought you were moving to ES2015 and babel? 

Babel will convert to ES5, we need a few functions polyfilled for verification on old android phones.

**Comment by shane-tomlinson** [comment]
We are going to kill this. It has been 3 years.

**Comment by davismtl** [comment]
Related?
https://github.com/mozilla/fxa-amplitude-send/issues/59

**Comment by shane-tomlinson** [comment]
> Related? mozilla/fxa-amplitude-send#59

Possibly, does OS in Amplitude come from the signup or verification page view? If the user signs up in Firefox Desktop and verifies on Android, is OS set to the Desktop OS or Android?

**Comment by davismtl** [comment]
IIUC, we set the OS as early as the form view so that we can filter on top of funnel.
