### ISSUE TITLE
lib/metrics "flush with timer" fails in Chrome when "?coverage=true" is added

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2891]
![](http://v14d.com/i/55c25e192432d.png)

@philbooth any ideas, is it just a timing issues or will webkit browsers not send metrics?

**Comment by philbooth** [comment]
@vladikoff I'm not seeing it on Chrome on my machine, so not sure what the problem is at the moment. I'm on the case though...

**Comment by vladikoff** [comment]
@philbooth oh it only happens when you run with "http://localhost:3030/tests/index.html?coverage=true"

**Comment by vladikoff** [comment]
so should not be a problem in production but just an issue with Blanket and coverage

**Comment by philbooth** [comment]
Phew! :relieved:

Will definitely get to the bottom of it tomorrow.

**Comment by vladikoff** [comment]
yeap no rush, thanks!!
