### ISSUE TITLE
"Must be at least 8 characters" tooltip is not effective

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2894]
@ryanfeeley from our new Sentry metrics the "Must be at least 8 characters" is one of the most popular user facing errors

![image](https://cloud.githubusercontent.com/assets/128755/9100084/d0c42a6a-3ba4-11e5-99e5-1bda56cb31d6.png)

Tooltip:
![image](https://cloud.githubusercontent.com/assets/128755/9100140/30b00444-3ba5-11e5-866f-a3833b29de12.png)

Is this something we can improve?

**Comment by vladikoff** [comment]
@ryanfeeley so after talking about this in RL, what should we do about this?

**Comment by ryanfeeley** [comment]
We can't do a lot for people who leave the entire form blank and press the big button, but we can do a few things before the "Must be at least 8 characters" tooltip fires.

1. When the user focuses on the password field, make the colour of the "Must be at least 8 characters" match the blue of the border, and then transition over a second to the original grey.
1. As the user types in the password field, change this message with each keystroke to:
  1. "Must be at least 8 characters"
  1. "Must be at least 7 more characters"
  1. "Must be at least 6 more characters"
  1. "Must be at least 5 more characters"
  1. "Must be at least 4 more characters"
  1. "Must be at least 3 more characters"
  1. "Must be at least 2 more characters"
  1. "Must be at least 1 more character"

**Comment by ryanfeeley** [comment]
@vladikoff BTW that screenshot isn't the tooltip. Everyone who focuses on the password field sees that.

**Comment by vladikoff** [comment]
> @vladikoff BTW that screenshot isn't the tooltip. Everyone who focuses on the password field sees that.

Yeah sorry.

> As the user types in the password field, change this message with each keystroke to

I wonder if there is trick we can think for localizing this properly.

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @vladikoff - What is the UX goal, to reduce the number of people that see the tooltip?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yes, authentication parkour is the goal.

**Comment by vladikoff** [comment]
will investigate further

**Comment by philbooth** [comment]
Closing.
