### ISSUE TITLE
Track page views with google analytics

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2898]
we only save 3 events for now, but no page events

cc @ryanfeeley

**Comment by ckarlof** [comment]
@vladikoff, can you elaborate more on what events we should add?

**Comment by vladikoff** [comment]
>  but no page events

@ckarlof, we would send the `screen` events that we have in the client metrics currently . This way we can see what the user flows throughout the site.
Basically these but we would be sending actual paths, such as /signup /signin, etc (without query params)

![](http://v14d.com/i/55db5cbe3dcaa.jpg)
