### ISSUE TITLE
Reconnect to Sync password field is out of view and inaccessible for avatar user

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2902]
Here's a bad one for iOS. When the user is asked to Reconnect to Sync and has an avatar, their avatar loads and the password field is pushed out of view and inaccessibe.
![img_6084](https://cloud.githubusercontent.com/assets/68213/9120073/470af228-3c48-11e5-91a3-a44f5683a5bb.PNG)

**Comment by vladikoff** [comment]
@ryanfeeley what can we do to fix this? ideas?

**Comment by ryanfeeley** [comment]
@johngruen may have some? or @darrinhenein?

**Comment by darrinhenein** [comment]
Can we just force the height of the image element/wrapper? This way the webview can target the password field properly?

cc @ryanfeeley @zaach

**Comment by johngruen** [comment]
@rfeeley...it can't scroll? Can we just default to focusing the password field?

**Comment by vladikoff** [comment]
@ryanfeeley @johngruen does the iOS mobile view hit our media query breakpoint for this mini view:

![](http://v14d.com/i/55c3b25611b37.jpg)

if so then maybe we should make the avatar smaller in the "mini" view?

**Comment by vladikoff** [comment]
iPhone 4s simulator view:
![image](https://cloud.githubusercontent.com/assets/128755/9121151/7d7f740e-3c4e-11e5-8518-d43d92ac630e.png)

**Comment by vladikoff** [comment]
@ryanfeeley 

>  the password field is pushed out of view and inaccessibe.

Isn't it pushed after you tap the input for the password (and it scrolls to the input) or does the keyboard just randomly show up?

**Comment by ryanfeeley** [comment]
@vladikoff The password field has focus. It may take it when the page loads, or I may have had to tap it.

**Comment by vladikoff** [comment]
Talked to @ryanfeeley and we could not see the issue. closing
