### ISSUE TITLE
Upgrade the password tooltip

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2904]
0. 2 AB tests

First,  make the "8 characters" notice more noticeable:
1. make the text blue  (same as border of inputs)
2. make the text show once the user triggers the password field and it should stay there until it is valid
![](http://v14d.com/i/55c3bd1fd0d18.png)

Second, change the colour of the "SHOW" and see if more people use it.  
Hover: 
![image](https://cloud.githubusercontent.com/assets/128755/9122276/e3125528-3c55-11e5-84a7-ccf0076dfe7c.png)
![image](https://cloud.githubusercontent.com/assets/128755/9122279/eda458ce-3c55-11e5-9412-1e73f1bc73f1.png)

**Comment by vladikoff** [comment]
Related to https://github.com/mozilla/fxa-content-server/issues/2894

**Comment by shane-tomlinson** [comment]
> 2 AB tests

I like it. Can you split this into two issues?

**Comment by vladikoff** [comment]
Will split this into 2 issues...

**Comment by vladikoff** [comment]
Closing for now, unless we find this is important.
