### ISSUE TITLE
No way to sign into FxA on Firefox TV

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2905]
## STR:
0. Plug in the Firefox TV.
1. Switch on Firefox TV.
2. Open Firefox.
3. Try to sign in using settings/preferences.

## Expected Behavior:
1. I am able to see a way to login so I can use my TV as an obscenely bulky mobile phone.

## Actual behavior:
1. NO WAY TO SIGN IN!!!!.

## Good to have:
1. Find people who want sign-in on TV

cc'ing @pdehaan and @ckarlof - He suffered this excruciating 'no-sign-in' problem on the TV downstairs.

**Comment by vladikoff** [comment]
nothing actionable from the fxa-content-server until someone requests this functionality
