### ISSUE TITLE
First Run form is sometimes blank in Firefox 40 when navigated away from the flow

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2906]
## STR:
1. Open https://www-demo4.allizom.org/en-US/firefox/40.0/firstrun/?v=2
2. Click on the other links, eg: Mozilla link up top.
3. Come back to this page.

## Expected Behavior:
1. Page displays the sign up sheet

## Actual Behavior:
1. An empty white box.
https://www.dropbox.com/s/uhvm61lbiby6u8l/Screenshot%202015-08-06%2015.12.50.png?dl=0

Is this expected behavior? Or am I the only one getting this weird page?
@shane-tomlinson 

## Warning extremely weird behavior ahead, proceed with caution.
* This only happens on my regular firefox(stable release) not on the FF that gets started with npm start.
* I mean like on the same machine. Two Firefoxes producing different results.
* Both are FF 40.0, using the same link.
* the regular one is already signed into sync, while the `npm start` ff is not.

### MOAR Screenshots
https://www.dropbox.com/s/0wc7csnqd6hkgs3/Screenshot%202015-08-06%2015.53.40.png?dl=0
https://www.dropbox.com/s/bt2uqu2jspiyqca/Screenshot%202015-08-06%2015.52.13.png?dl=0
The one on the left is my regular firefox, the one on the right is the `npm start` ed one

**Comment by vladikoff** [comment]
Could not reproduce this in stable or beta. Is there some specific download?

**Comment by vladikoff** [comment]
from irc yesterday: this does not happen on a fresh profile.

**Comment by edmoz** [comment]
I wasn't able to repro on allizom.org - it's possible demo4 points at stage and isn't a production grade instance...

**Comment by vladikoff** [comment]
demo4 is using  https://accounts.stage.mozaws.net
@TDA let us know if you can reproduce this on: https://www.allizom.org/en-US/firefox/40.0/firstrun/

**Comment by TDA** [comment]
@vladikoff Unable to reproduce on that, I get a white box but it almost instantly expands to the sign-in/up screen.

**Comment by shane-tomlinson** [comment]
> This only happens on my regular firefox(stable release) not on the FF that gets started with npm start.
> I mean like on the same machine. Two Firefoxes producing different results.
> Both are FF 40.0, using the same link.

Fx Stable is Fx 39. Fx 40 is beta. Are you using Stable or Beta? FWIW, I'm not able to reproduce on either.

**Comment by TDA** [comment]
I probably meant Beta update channel. My bad. Sorry! @shane-tomlinson
