### ISSUE TITLE
self is not equal to this??

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#2908]
## STR
1. Create a method inside a view inside any fxa-content-server/app/scripts/**/*.js (this has been tested on signup.js, communication_preferences.js, and on two_factor_auth.js[yet to be PR'ed].)
2. Eg: 
```
var self = this;
self.$el.find('#someid').chainedWithSomeMethod;
console.dir(this);
console.dir(self);
console.log(self === this);
```
3. Open the console on the browser.
4. Now change self to this on line 2 --> this.$el.find....
5. Check o/p on the console.

## Expected Behavior
* Both steps 3 and 5 return the same results

## Actual behavior
* Step 3 displays the 3 console logging directives
* Step 5 displays the 3 console logging directives, but also a CSP Error

Screenshots:
* Step 3:
    * https://www.dropbox.com/s/c19au7pirghmb9s/Screenshot%202015-08-06%2016.47.06.png?dl=0
* Step 5
    * https://www.dropbox.com/s/l8c3fhtsk7kusg7/Screenshot%202015-08-06%2016.49.26.png?dl=0
    * https://www.dropbox.com/s/x3gnh1qpothu8i0/Screenshot%202015-08-06%2016.53.08.png?dl=0

## Reproducibility:
1. I am able to reproduce this quite successfully on a Firefox 40.0(Mac OSX), with almost 80% success rate. 
2. Tested on 3 different pages, 5 times each(total 15), and got this to work 12 times.

tagging @shane-tomlinson and @karlht as I have shown them a demo of this.
cc'ing @jrgm as according to Karl, jrgm's full of 'javascript'. :D

**Comment by vladikoff** [comment]
@TDA sorry, could you create a branch with what you are seeing?
Your STR is not sufficient

Thanks
