### ISSUE TITLE
Measure distinct errors for empty email input and invalid email syntax

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2909]
Currently we record the same error whether or not the email field is empty or just contains invalid email syntax.

While the error message we present can remain the same…
![email](https://cloud.githubusercontent.com/assets/68213/9139356/ce85186e-3cf7-11e5-8011-1b8da5a72271.png)

… we should record these as separate events on the server **so that we can we tell if something requires deeper investigation**.

**Comment by shane-tomlinson** [comment]
I'm going to call this the easiest fix ever. We already did this in checkin 71489471.

I opened #2928 to add documentation about the various email validation metrics.

@ryanfeeley, the two metrics you are looking for on the signup page:

* error.signup.auth.1011 - user did not enter an email address
* error.signup.auth.1023 - user entered an email address that was invalid

For the signin page, replace signup with signin.

**Comment by shane-tomlinson** [comment]
Dup of #1814.
