### ISSUE TITLE
Disable spell check on email field

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2910]
Email addresses are never in a dictionary. We should remove spell check on the username field with "spellcheck=false".

**Comment by shane-tomlinson** [comment]
> Email addresses are never in a dictionary.

This is an invalid assumption that I got beat down for once. Some folks add their email addresses to their phone's dictionary.

**Comment by vladikoff** [comment]
> This is an invalid assumption that I got beat down for once. Some folks add their email addresses to their phone's dictionary.

Ah yes I've seen this too! Great point Shane

**Comment by vladikoff** [comment]
> @ryanfeeleyryanfeeley reopened this a minute ago

:scream:

**Comment by ryanfeeley** [comment]
That's ridiculous guys. We are designing for most users, and a squiggly red underline appearing in a field for most users is problematic. The kind of people who add their email address to a dictionary are not the kind of people who mistype their email.

**Comment by shane-tomlinson** [comment]
> The kind of people who add their email address to a dictionary are not the kind of people who mistype their email.

They are the type who on their mobile phone enter part of their address and use the dictionary to fill in the rest.

**Comment by shane-tomlinson** [comment]
Really, it makes almost no difference to me. But, we have to realize we are making a huge assumption and some user is going to be annoyed and complain at some point. I want somewhere to point them that says "we thought about this."

**Comment by shane-tomlinson** [comment]
@ryanfeeley - which browser is problematic?

**Comment by vladikoff** [comment]
@ryanfeeley will check how other inputs work

**Comment by ryanfeeley** [comment]
Google does it. Their ID is an email. So is ours. We should do it.
