### ISSUE TITLE
verified screen should link or embed sending sms link phone

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#2911]
currently the verified acct page has a link to google play web store, and iOS beta sign up. We should consider adding a link to this SMS phone page or embedding a form to send to that api:

https://www.mozilla.org/en-US/firefox/sms/

**Comment by shane-tomlinson** [comment]
Can you make this into a user story instead of opening an issue here?

**Comment by shane-tomlinson** [comment]
@edmoz, can you move this to a user story if it's still needed?

**Comment by rfk** [comment]
I moved it to here for further discussion: https://mozilla.aha.io/features/FXA-46
