### ISSUE TITLE
Handle NS_ERROR_FILE_CORRUPTED with localStorage

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2913]
NS_ERROR_FILE_CORRUPTED
Ref: http://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

![image](https://cloud.githubusercontent.com/assets/128755/9143191/e0486b1c-3d12-11e5-9a64-eedf6ec36e7f.png)

**Comment by vladikoff** [comment]
![](http://v14d.com/i/55c558a202186.jpg)

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/9174681/6266946e-3f4f-11e5-9254-f36a75a42998.png)

**Comment by shane-tomlinson** [comment]
Also NS_ERROR_STORAGE_IOERR, NS_ERROR_FILE_NO_DEVICE_SPACE, NS_ERROR_FILE_CORRUPTED,  NS_ERROR_STORAGE_CONSTRAINT, NS_ERROR_FAILURE, NS_ERROR_STORAGE_BUSY, NS_ERROR_OUT_OF_MEMORY, SecurityError (This operation is insecure)

A scan through the Sentry reports seems it's always on the firstrun page, which should only be shown to users of a new profile. The error always occurs in the same place within crosstab:

![screen shot 2016-01-21 at 18 45 51](https://cloud.githubusercontent.com/assets/848085/12490788/412d8d42-c06f-11e5-98f7-fd60064741e6.png)

**Comment by shane-tomlinson** [comment]
ref #2969

**Comment by shane-tomlinson** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1240238

**Comment by vladikoff** [comment]
We now redirect users to the `cookie` page if there are major storage errors.
