### ISSUE TITLE
Discontinue support for `campaign` query parameter

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2920]
As @vladikoff notes in https://github.com/mozilla/fxa-relier-client/issues/51#issuecomment-129479266, `campaign` was originally for the Growth team. They now specify the `utm_campaign` parameter. Should we discontinue support for `campaign` and support only one way to do things.

**Comment by vladikoff** [comment]
I will check DataDog and make sure we are not getting events

**Comment by shane-tomlinson** [comment]
If DataDog shows nothing, we should put a notice on the mailing list to solicit feedback.

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/9178143/a76d4ff8-3f63-11e5-9fb6-433c27464c0a.png)


@shane-tomlinson datadog is showing `fxa-embedded-form`, what is that?

**Comment by vladikoff** [comment]
@shane-tomlinson sorry, is "fxa-embedded-form" firstrun?

**Comment by vladikoff** [comment]
We use the campaign tracking for the mobile snippets:

![](http://v14d.com/i/55cad5844c604.png)

Where should we transition those? should those just be regular events? 
i.e `fxa.content.marketing.android.click.newsletter` ?

**Comment by philbooth** [comment]
When tackling this, we need to make sure that all references to `campaign` are updated. For instance there is test data in `app/tests/spec/models/mixins/resume-token.js` that could easily be missed etc.
