### ISSUE TITLE
More than one certificate/authorization request made on /settings

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2921]
STR

1. Sign in to FxA on https://accounts.firefox.com
1. Open the dev tools console
1. Load up https://accounts.firefox.com/settings
1. Watch the multiple cert/authorization requests occur

First noticed in the review for settings refresh #2748, but the problem happens on prod too.

![why-so-many-certs](https://cloud.githubusercontent.com/assets/848085/9175781/616796dc-3f7f-11e5-810e-62fee2bcb1c1.png)

**Comment by zaach** [comment]
This is a consequence of no longer persisting the access token in localStorage– each `account` instance has to refetch it. We'll need to reuse the same account instance where possible to negate this.
