### ISSUE TITLE
The Changelog is ugly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#2923]
The [CHANGELOG.md](https://github.com/mozilla/fxa-content-server/blob/d08885ed0161e4782359815c28511a0a7084a7d6/CHANGELOG.md#0430-2015-08-04) objectively looks pretty mediocre.

I _think_ this may be due to a recent bump to [**grunt-conventional-changelog@3.0.0**](https://github.com/btford/grunt-conventional-changelog/blob/master/CHANGELOG.md) in #2883. We may need to tweak what options we pass to **conventional-changelog**.

I was playing with the following settings and it looked somewhat better, but was just stalling when I tried setting the `releaseCount` to 0 (regenerate changelog for all versions &mdash; but I Ctrl+C'ed the process after about 4 minutes so maybe I was just impatient).

```
      changelogOpts: {
        preset: 'angular',
        releaseCount: 0
      }
```

---

### SCREENSHOT:

<img width="727" alt="fxa-content-server_changelog_md_at_master_ _mozilla_fxa-content-server_and_express-busboy" src="https://cloud.githubusercontent.com/assets/557895/9179416/4c683882-3f51-11e5-9cdd-8bbccc06e9d3.png">

**Comment by vladikoff** [comment]
> regenerate changelog for all versions — but I Ctrl+C'ed the process after about 4 minutes so maybe I was just impatient).

@pdehaan let's just regenerate for the past 2 versions, is that possible?

**Comment by pdehaan** [comment]
@vladikoff: This is getting messed up.

I can regenerate 1 or 2 past versions, but it starts breaking quickly at 3 and 4 and just stalled for 20m on "0".
So if I regenerate 1 past version (basically trying to redo 0.43.0), then it seems to dump out "Bug Fixes", and "Features", but isn't displaying the v0.43.0 train's "Refactor" or "Chore" commits; which means we're missing about 17 commits.

Unless somebody can come up with a quick fix or figure out what's going on, I vote for reverting the grunt-conventional-changelog and sticking with the old version forever. I'm still not seeing great behavior in **grunt-conventional-changelog@4.0.0**. I can try digging into this a bit more this afternoon when I get time and try and file these upstream in **conventional-changelog** if I can reproduce using the CLI.

**Comment by vladikoff** [comment]
> but isn't displaying the v0.43.0 train's "Refactor" or "Chore" commits; which means we're missing about 17 commits.

those won't be there because the angular preset does not show them
