### ISSUE TITLE
Metrics: verify-email events do not add up verification.success events

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2925]
![image](https://cloud.githubusercontent.com/assets/128755/9180412/62480f5a-3f70-11e5-8f21-cc44cb0b9b60.png)

@shane-tomlinson ,
See the 2nd and the 3rd graph, any ideas why we would have more "success" events than page views?

**Comment by vladikoff** [comment]
Fixed in train 43

Thanks @shane-tomlinson !

**Comment by shane-tomlinson** [comment]
For future readers, fixed by https://github.com/mozilla/fxa-content-server/pull/2857
