### ISSUE TITLE
easter egg printed on every page load

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#2927]
STR

1. load https://accounts.stage.mozaws.net/
2. open console, enter 1 + 1
3. reload page

Expected: console does not move
Actual: spam

**Comment by vladikoff** [comment]
@jrgm this is how the hacks blog does it I think, could you check if that's the same issue here: https://hacks.mozilla.org/

I guess if it didn't print every page load then you could miss it or something

**Comment by jrgm** [comment]
Yeah, I guess I might miss being pointlessly annoyed.

**Comment by TDA** [comment]
@jrgm 
@vladikoff 
Isnt that the expected behavior? For the easter egg to be printed every time?

**Comment by shane-tomlinson** [comment]
@jrgm - you can always disable it! `easterEgg.disableEasterEgg()`

**Comment by vladikoff** [comment]
@jrgm this is expected behaviour, please reopen and let us know if we can somehow improve this
