### ISSUE TITLE
The camera picture is not centered correctly

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-content-server#2930]
Quote from [bug 1193246 on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1193246):

> Environment used:
> 
> FF 41, 42
> OS: Win 7 x64, Mac OS X 10.10.4, Ubuntu 12.04 x86
> 
> STR:
> 
> 1. Sign in to Sync.
> 2. From about:preferences#sync go to https://accounts.firefox.com/settings/avatar/change in order to add a new photo to the account.
> 3. Press camera and share the camera.
> 4. Press Take Picture.
> 
> Issue:
> The picture taken at step 4 is not correctly centered.

I can confirm the bug.

**Comment by vladikoff** [comment]
@eoger could you attach a screenshot or something that would explain what "not correctly centered" would be?

**Comment by eoger** [comment]
<img width="543" alt="screen shot 2015-08-11 at 10 51 55 am" src="https://cloud.githubusercontent.com/assets/6424575/9205448/210ee9f8-4017-11e5-9a30-1ae82c2f6104.png">
<img width="487" alt="screen shot 2015-08-11 at 10 52 02 am" src="https://cloud.githubusercontent.com/assets/6424575/9205451/22ac9756-4017-11e5-903b-17f40fab3ad9.png">

**Comment by vladikoff** [comment]
Thanks @eoger !
