### ISSUE TITLE
firstrun - 500 page is not visible

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2934]
I saw the `illegal iframe error`, but did not see the 500 page, even though it is requested. This problem also occurs with the `[object Object]` error we see in Sentry, which seems to occur if an XHR request aborts.

![screen shot 2015-08-12 at 17 06 19](https://cloud.githubusercontent.com/assets/848085/9234262/ba6ae782-412f-11e5-8302-d92be1117d28.png)

**Comment by vladikoff** [comment]
I reproduce this by:

1. opening a Windows 7 VM with 512 RAM
2. start a fresh profile
3. close the first run when you see it for the fresh profile (it will probably load okay)
4. open new tab, open its devtools, devtools settings -> disable cache when devtools are open
5. leave the tab alone from step 4, open a new tab with a YouTube video, example: https://www.youtube.com/watch?v=FikxXp73O_Y , set video to be 1080p in settings
6. repeat step 5 so you have 2 tabs open with 1080p videos playing: ![](http://v14d.com/i/55ccd3dd5bcb4.png)
7. go back to the clean tab in step 4, and paste the url for firstrun:  https://www.mozilla.org/en-US/firefox/40.0/firstrun/ , go back to one of the youtube tabs and keep an eye on the first run tab loading indicator
8. once the tab is finishing loading, click on the tab and you will see that the form didn't load 

![](http://v14d.com/i/55ccd427e9cef.png)
![](http://v14d.com/i/55ccd1c31b5ae.jpg)

**Comment by shane-tomlinson** [comment]
This is not caused by content server code, but rather by the firstrun page setting the opacity of the content server to 0 on startup.

![screen shot 2015-08-16 at 16 48 49](https://cloud.githubusercontent.com/assets/848085/9293997/da51654e-4436-11e5-8069-619d6131dc67.png)

The opacity is changed to 100 either on the `loaded` or `resize` message.

ref https://github.com/mozilla/bedrock/blob/master/media/js/firefox/australis/fx40/firstrun.js#L30.

@jpetto - Can we put our heads together to work around this?

**Comment by shane-tomlinson** [comment]
For a super simple way to reproduce this problem:

1. Install adblock plus
1. Add a new filter: `https://accounts.firefox.com/config`

Reload the firstrun page.

When done testing, don't forget to remove the filter.

**Comment by jpetto** [comment]
@shane-tomlinson - I've [added a 1500ms timeout to the page after setting the iframe `src`](https://github.com/mozilla/bedrock/blob/bug-1195391-remove-video-fx38%2B-firstrun/media/js/firefox/australis/fx40/firstrun.js#L76). If the `ping` event hasn't occurred at that time, the iframe is displayed. You can test it on demo4 with the Adblock technique:

https://www-demo4.allizom.org/en-US/firefox/40.0/firstrun/

What do you think about this workaround? Is 1500ms too short/long to wait for the `ping` event to send & receive?

**Comment by chrismore** [comment]
@shane-tomlinson thoughts above? This change is wrapped up with the PR about removing the video and I'd like to get the video off the site asap.

@jpetto If we can't come to a good resolution on the error page and timeout, should we move these changes into separate PRs?

**Comment by shane-tomlinson** [comment]
@chrismore - @jpetto and I had an out of band conversation last night which I have not yet recapped here. 

The approach seems reasonable, I have to test to confirm. Jon was going to make is to change the timeout from 1.5s to 2.5s. 

Once we have #2980 figured out (add a throbber to the page on startup to give some indication the page is loading), it may be reasonable to remove the timeout all together and just show the content server's throbber while the page is loading.

**Comment by shane-tomlinson** [comment]
@jpetto and @chrismore - tested on https://www-demo4.allizom.org/en-US/firefox/40.0/firstrun/ by blocking the call to https://accounts.stage.mozaws.net/config, looks good!

I'm going to close this issue. The fix will by taken care of by the firstrun code when @jpetto's change makes it to prod.

Thanks @jpetto!
