### ISSUE TITLE
errors fetching /config log `[object Object]`.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2935]
the config-loader's XHR request to `/config` does not convert errors into a form that our error logging understands.

STR:

1. Apply the diff from the bottom
1. Open the developer console
1. Load FxA
1. Boom

![screen shot 2015-08-12 at 20 45 04](https://cloud.githubusercontent.com/assets/848085/9234812/0fc25b9a-4133-11e5-912d-e0fc5839fc7a.png)

```diff
diff --git a/app/scripts/lib/xhr.js b/app/scripts/lib/xhr.js
index 1f37b97..385b777 100644
--- a/app/scripts/lib/xhr.js
+++ b/app/scripts/lib/xhr.js
@@ -136,7 +136,7 @@ define([
      * @return {promise}
      */
     getJSON: function (url, data, success) {
-      return p.jQueryXHR($.getJSON(url, data, success));
+      return p.jQueryXHR($.getJSON(url, data, success).abort());
     }
   };
 });
```

**Comment by shane-tomlinson** [comment]
Noticed several times when trying to figure out the cause of #2934

**Comment by ckarlof** [comment]
I noticed this got a train 44 milestone added. Is it a high priority thing that we want to do this train? If so, let's triage it into the appropriate column.

**Comment by shane-tomlinson** [comment]
Ref #2944, #2955, #2956, #2957.

**Comment by shane-tomlinson** [comment]
Closing, the PR merged.
