### ISSUE TITLE
Production: experiments.bundle.js does not specify any caching

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2936]
experiments.bundle.js does not specify any cache headers. Since it does not include a cache busting mechanism in the request name, we cannot use long lived cache control headers. We could use etags and respond with a 304 if the etag matches, to at least eliminate the data transfer. In my simulated edge network firstrun page request (see pic below), it took nearly 15 seconds to transfer experiments.bundle.js, we could reduce this down to a few seconds with etags.

@jrgm - could this be taken care of by nginx?
@dannycoates - if not by nginx, could it be done by express-able?

![screen shot 2015-08-12 at 21 19 58](https://cloud.githubusercontent.com/assets/848085/9235727/78859a2a-4138-11e5-8aec-176b237ed659.png)

**Comment by jrgm** [comment]
It could be done with nginx, but express-able is in a better position to say when the content is the same etag.

**Comment by dannycoates** [comment]
The bundle can't currently be cached because it includes the server's current `Date.now()` as `remoteNow` which is used for all experiment date operations since the client time might not be correct.

We can move the initialization of `remoteNow` out of the bundle, but it needs to be set by something that isn't cached.

**Comment by shane-tomlinson** [comment]
> The bundle can't currently be cached because it includes the server's current Date.now() as remoteNow which is used for all experiment date operations since the client time might not be correct.
>
> We can move the initialization of remoteNow out of the bundle, but it needs to be set by something that isn't cached.

Huh. Thanks for the info. Need to ponder this a bit.

**Comment by vladikoff** [comment]
Closing for now until it becomes an issue
