### ISSUE TITLE
utm parameters being dropped after verification?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2937]
From Chris More in IRC:

-------------------------------------

[21:31:03]  <cmore>	stomlinson: one thing i noticed about the UTM parameters on the iframe is that they get dropped when a user verifies their email address and the iframe URL changes. All verified emails have no source/medium. Not sure what we can do about that other than preserving the UTM tags being passed when redirecting after verified.

**Comment by vladikoff** [comment]
Should we add the utm params into the resume token?

**Comment by shane-tomlinson** [comment]
> Should we add the utm params into the resume token?

[They already should be there](https://github.com/mozilla/fxa-content-server/blob/b789684bcdc2bd594a0eaddd9add28cd07293804/app/scripts/models/resume-token.js#L22).

**Comment by vladikoff** [comment]
Bit of a confusing bug report, but here goes:

> the UTM parameters on the iframe is that they get dropped when a user verifies their email address and the iframe URL changes

I verified my email and checked my iframe src, all URL query parameters seems to be 

![image](https://cloud.githubusercontent.com/assets/128755/9529299/7830d888-4cc7-11e5-92c9-b803a50a4441.png)

**********

> All verified emails have no source/medium. Not sure what we can do about that other than preserving the UTM tags being passed when redirecting after verified.

That one seems like a bug, we do not properly set `utm_*` params in the resume token. I'll have a patch for that. NOTE: the emails that the user gets have a token encoded `resume=eyJlbnRyeXBvaW50IjpudWxsLCJ1dG1DYW1wYWlnbiI6In...` so you don't see the utm_* params in the URL, but they are decoded and reported to the server to send the GA event. cc @chrismore
