### ISSUE TITLE
enable en-gb as a locale 

### ISSUE THREAD

**Issue by satdav** [mozilla/fxa-content-server#2942]
Hello I am wondering if we can get en-gb as a locale for the firefox accounts service if we are not going to enable it can I suggest we change to en instead of en-US 

We have a team of en-gb locale ready to work on this p's we use pontoon.mozilla.org to localise files

**Comment by rfk** [comment]
(from irc) some existing translations on pontoon: https://pontoon.mozilla.org/en-gb/firefox-accounts/

**Comment by rfk** [comment]
And according to Pontoon it's at 100% complete, so perhaps we just need to flip a switch to enable this in production?  /cc @jrgm

**Comment by vladikoff** [comment]
@mathjazz may also have more information about `en-gb`

**Comment by satdav** [comment]
@vladikoff  its ready to be enabled at your end for en-gb its all ready localised on pontoon

**Comment by mathjazz** [comment]
Sounds good to me.
