### ISSUE TITLE
clicking on 'email prefs' results in blank iframe in firstRun page

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#2945]
1. (i'm on dev edition) goto:  https://www.mozilla.org/en-US/firefox/40.0/firstrun/
2. click on 'communication preferences'
3. click on 'Email preferences'

actual: iframe is blank and i see this:
09:24:32.474 Load denied by X-Frame-Options: https://www.mozilla.org/en-US/newsletter/existing/69d4b10e-8e5e-4f8d-8a38-7b87e4d1b449 does not permit framing.1 <unknown>

**Comment by shane-tomlinson** [comment]
Proof of this:

![blank-email-preferences](https://cloud.githubusercontent.com/assets/848085/9255670/c2e09106-41e2-11e5-8d46-61ca6186a09f.gif)

**Comment by ckarlof** [comment]
Going back to our original discussions with Marketplace, this is one of the reasons why we were so hesitant to do these embedded flows. Looking to the future, I recommend we keep the scope of the embedded flow as limited as possible (i.e., scoped to signin and signup). As quickly as possible after that, it would be nice to get to a top level page if we want to drop the user into settings or whatnot.

**Comment by rfk** [comment]
Perhaps the iframed view should hide all those tempting clickable links to "settings" etc and just show your logged-in state?  Or open them in a new tab?

**Comment by vladikoff** [comment]
Related: There is also a link to Gravatar if the user uploads the an avatar through gravatar (Courtesy of Gravatar) message  
![image](https://cloud.githubusercontent.com/assets/128755/9416356/290878f0-4813-11e5-8a25-c6d6904eca73.png)

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Would it be possible to just redirect any user who views the settings page to to accounts.firefox.com/settings?

This iframe is a portal that must be sealed up forever. For the love of God. 
![being john malkovich](https://cloud.githubusercontent.com/assets/68213/9470976/4e8da9cc-4b1c-11e5-8ef3-d8d0096f8c50.png)

**Comment by vladikoff** [comment]
> Would it be possible to just redirect any user who views the settings page to to accounts.firefox.com/settings?

What do we show to the user in the iframe when they signin?

**Comment by ryanfeeley** [comment]
Account verified screen with the green checkmark.

**Comment by vladikoff** [comment]
> Account verified screen with the green checkmark.

That's when they sign up, what about signin (login) though? i.e I verified my account 3 months ago and then I signin and I see it again? that's confusing

**Comment by ryanfeeley** [comment]
If the user signs in, we should try to target the entire page to redirect to /settings or even better the signed-in Sync preferences. Either of those combined with the "you are now signed in to sync" will be acceptable.

**Comment by vladikoff** [comment]
### Actual 

![image](https://cloud.githubusercontent.com/assets/128755/9473467/03aaf826-4b29-11e5-9196-e0086c700563.png)

### Expected

![image](https://cloud.githubusercontent.com/assets/128755/9473476/0bd17c46-4b29-11e5-857b-70336075abd6.png)

**Comment by vladikoff** [comment]
cc @jpetto @ckarlof

**Comment by rfk** [comment]
This sounds fine to me, but I'd like to see an explicit "OK" from the growth team before we move ahead with it.

> even better the signed-in Sync preferences

Agreed this would be even better, but may require additional support from the browser.

**Comment by jpetto** [comment]
Opened a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1199258) to get input from cmore & habber.

I don't believe we have a way to directly open the Sync preferences, but we certainly can redirect to accounts.firefox.com/settings.

**Comment by ckarlof** [comment]
> I don't believe we have a way to directly open the Sync preferences, but we certainly can redirect to accounts.firefox.com/settings.

I'd strongly prefer we have a consistent post FxA-creation Sync on-boarding experience. 

@ryanfeeley's designs are moving us to use `about:preferences#sync` as the post-login landing page for Sync: https://bugzilla.mozilla.org/show_bug.cgi?id=1189842

I think there are details to figure out, and let's iterate towards the great experience we want longer term. We do have the ability to make the necessary changes in whatever we code need to after all. :)

**Comment by ckarlof** [comment]
@vladikoff @ryanfeeley That said, for this iteration, let's find whatever stopgap we can to make this flaw better.

**Comment by vladikoff** [comment]
From bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1199258#c2 

 > Holly Habstritt Gaal [:Habber] writes:

> Just to be clear... the redirect solution does the redirect immediately after successful signin (Step 2)? Not after they click "communication preferences" (Step 3), correct? If this is true, redirect solution will take users away from the /firstrun URL without them explicitly deciding to exit. At the moment there is no other content on the page that we wish users to interact with. However, there have been requests to display other content on this page (ie: one tertiary link to promote iOS, etc). After they sign in, it's an opportunity to have the user complete a follow-up action or learn something else on this page (or whatever mozilla.org page this is embedded on). Redirecting them too soon could be a missed opportunity. 

> A few ideas:
> - solve with the redirect solution for now, knowing that we need to come up with a different solution soon that does not take the user away from this page w/ out them explicitly clicking a link to do so

> - open 'Email Settings' in new tab (unsure if this is possible from the iframe)

> - replace 'communication preferences' link on this screen http://cl.ly/image/1E0W3n0m1f08 with a link that goes here about:preferences#sync, so the user chooses to exit. 


> The accounts team (rfeeley & team) should make the call on how the links are displayed in the iframe since they own the product. However, since the iframe needs to stand alone and potentially work when other content on a web page is a priority, I would hesitate from any automatic redirects away from a page where the iframe is embedded that the user wouldn't expect. We have the opportunity to use this iframe on other pages where it is useful to the user, not just on /firstrun.

@jpetto It seems you are able to listen for the "LOGIN" event, is it possible to fix this for now and redirect users to https://accounts.firefox.com/settings . Please let me know if you need any changes made to the content server to support that.

**Comment by rfk** [comment]
It sounds like the broad shape of the solution here is "whoever is doing the embedding should navigate the page somewhere useful".  This seems sensible, but is it worth backstopping this on our side by showing a non-interactive "login status" page in the iframe, rather than settings?   Like this:

![03aaf826-4b29-11e5-9196-e0086c700563](https://cloud.githubusercontent.com/assets/34695/9534727/218d04f6-4d5e-11e5-983e-b7fd572aedf2.png)

(Which is actually just settings with all the links hidden, but I don't think that's workable in a post-settings-2.0 world)

**Comment by ryanfeeley** [comment]
Except that "Almost done!" copy on the left is not accurate, hence the redirect suggestion.

**Comment by rfk** [comment]
Right, it's still up to the embedder to do something useful after the login step completes, and redirecting is the best option available in /firstrun right now.  But you can imagine a future iteration where they e.g. change the copy to describe some next step rather than ending the flow and redirecting away.

Anyway, I don't want to derail a short-term fix here, and it sounds like the redirect to settings it a good one.

**Comment by habber** [comment]
Hey there. @jpetto , @ryanfeeley  and I met quickly to discuss some of ideas brought up here and in the bug. This is what we landed on:

Decision for now:
Redirect page right when they sign-in. (user selects option in iframe that says they already have an account > user signs in > page redirect occurs)

More ideal solution to discuss:
To allow the iframe to collaborate and not compete w/ the content surrounding it and not unexpectedly send users away from a web page, display as few links as possible in the iframe. The user can sign-in in the form w/ no additional links to take them away from page (ie: remove Email Prefs link). It is up to current webpage to offer additional links and listen to events in the iframe. @shane-tomlinson - would we work with you for removing links in the iframe? (all decisions would be aligned with @ryanfeeley 's UX guidelines)

**Comment by shane-tomlinson** [comment]
Another strange case to consider is how to handle users who are authenticated to FxA that re-load the firstrun page. They'll see the settings page.

Do we care?

>  @shane-tomlinson - would we work with you for removing links in the iframe? 

@habber - My response is at https://bugzilla.mozilla.org/show_bug.cgi?id=1199258#c8. It seems closely aligned with your suggestion. I suggest we halt the user flow after the user signs in so that the user is never shown the settings page. The firstrun page does what it will when it receives the `login` message.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - a secondary suggestion that would have at least avoided the original bug is if we open the Basket email preferences in a new tab - what do you think?

**Comment by vladikoff** [comment]
> @ryanfeeley - a secondary suggestion that would have at least avoided the original bug is if we open the Basket email preferences in a new tab - what do you think?

Then we have to :police_car: police every link in our settings, see https://github.com/mozilla/fxa-content-server/issues/2945#issuecomment-133528087

**Comment by shane-tomlinson** [comment]
> Then we have to :police_car: police every link in our settings, see #2945 (comment)

Ah yes. There is that. Embedding settings is indeed a pain.

**Comment by ckarlof** [comment]
> Ah yes. There is that. Embedding settings is indeed a pain.

My memory tells me this is one of the motivators for why we don't embed settings in about:accounts.
