### ISSUE TITLE
firstrun - throwing "can only be placed into an IFRAME on approved sites"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#2946]
![image](https://cloud.githubusercontent.com/assets/128755/9256820/e55b22aa-41bf-11e5-9817-413bb1fde91e.png)
![](http://v14d.com/i/55ccd50605405.png)

**Comment by vladikoff** [comment]
I reproduce this by:

1. opening a Windows 7 VM with 512 RAM
2. start a fresh profile
3. close the first run when you see it for the fresh profile (it will probably load okay)
4. open new tab, open its devtools, devtools settings -> disable cache when devtools are open
5. leave the tab alone from step 4, open a new tab with a YouTube video, example: https://www.youtube.com/watch?v=FikxXp73O_Y , set video to be 1080p in settings
6. repeat step 5 so you have 2 tabs open with 1080p videos playing: ![](http://v14d.com/i/55ccd3dd5bcb4.png)
7. go back to the clean tab in step 4, and paste the url for firstrun:  https://www.mozilla.org/en-US/firefox/40.0/firstrun/ , go back to one of the youtube tabs and keep an eye on the first run tab loading indicator
8. once the tab is finishing loading, click on the tab and you will see that the form didn't load 

![](http://v14d.com/i/55ccd427e9cef.png)
![](http://v14d.com/i/55ccd1c31b5ae.jpg)

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/fxa-content-server/blob/43150210383e7b349a9b97b4154ce047607ac9a0/app/scripts/lib/origin-check.js#L32

**Comment by ckarlof** [comment]
100ms timeout. We should certainly increase that, and we might also consider adding an friendly error message if it triggers like "Oops, we encountered a problem. Try reloading the page." If the user encountered this due to a ton of shit running in her browser, maybe reloading would help.

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by ckarlof** [comment]
From IRC, @vladikoff and I discussed this hotfix:
* increase the timeout
* add some metrics so we can learn the distribution of the timeouts

**Comment by vladikoff** [comment]
Fixed 

![](http://v14d.com/i/55cd236626c0b.jpg)
