### ISSUE TITLE
Remove support for exclude_signup=1

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#2950]
In support of the Firefox on iOS launch, we added the ability to disable new account creations because FxiOS is not ready to support them [1], [2].  Per my little rant in [3], we do not want to encourage other reliers to use this "feature", and I'm hopeful that we can remove it entirely once FxiOS has support for setting up sync with newly-created accounts .

So let's make sure we have a plan to get rid of `exclude_signup=1`.   I see two options, based on discussion in [4] and subsequent comments.

1. Make it so that you must specify *both* `context=fx_ios_v1` and `exclude_signup=1` in order to get the signup-disabling behaviour.  This will discourage other reliers from discovering it or coming to rely on it.  Once FxiOS ships a version with support for handling new accounts and it has sufficient penetration of install base, completely remove support for `exclude_signup=1`.  Assuming nobody else has showed up wanting to use it, we can also remove all the logic that shows/hides the signup links as well.

  Pro: easy for FxiOS developers to enable/disable the signup-disabling behaviour in dev environments.
  Pro: we get to pretend that this whole signup-disabling thing never happened.
  Con: we have to wait for a new version of FxiOS to ship and then remember to get around to this.
  Con: risk of confusing UX for users who, for whatever reason, are trying to set up an old version of   FxiOS after we remove `exclude_signup=1` support.

2. Remove support for `exclude_signup=1` immediately, and make `context=fx_ios_v1` the only way to opt-in to the signup-disabling behaviour.  Provide a new `context=fx_ios_v2` that's just like `v1` except that it allows signups, and FxiOS can switch to it whenever they're ready.

  Pro: easy for FxiOS developers to enable/disable the signup-disabling behaviour in dev environments.
  Pro: we can do all of that right now, rather than waiting for a new FxiOS version to ship.
  Con: we're committing to keeping the signup-disabling logic around indefinitely.

I lean towards (1) as the better option as it's more explicit about what's going on, and would let us entirely remove this functionality at low risk and cost, per [5].  But I'd be happy with either and I think they'd both meet the needs of the client dev team and our users.  @shane-tomlinson if you feel that (2) is better overall, I'll gladly defer to your judgement.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1190097
[2] https://github.com/mozilla/fxa-content-server/pull/2868
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=1182255#c31
[4] https://bugzilla.mozilla.org/show_bug.cgi?id=1182255#c39
[5] https://bugzilla.mozilla.org/show_bug.cgi?id=1182255#c19

**Comment by rfk** [comment]
Also, more thoughts on this from @shane-tomlinson in https://github.com/mozilla/fxa-content-server/pull/2868#issuecomment-127169056

**Comment by rfk** [comment]
@shane-tomlinson please take a look at this when you're back from PTO

**Comment by shane-tomlinson** [comment]
@rfk - Yep, now that you clearly state the goals, the first option seems like the best path forward.

**Comment by rfk** [comment]
OK, great.  @shane-tomlinson do you want to take on the work for this as part of ths current train?

**Comment by shane-tomlinson** [comment]
@rfk - see #3028, assigned to you. ;)

**Comment by rfk** [comment]
LGTM; I guess we then just need a follow-up bug for:

> Once FxiOS ships a version with support for handling new accounts and it has
> sufficient penetration of install base, completely remove support for exclude_signup=1

**Comment by rfk** [comment]
> we then just need a follow-up bug

Actually I guess we can just leave this bug open and put it back in the backlog

**Comment by vladikoff** [comment]
> rfk added this to the fennec-web-login milestone on Aug 20

I'm removing the fennec-web-login milestone from this because this is more related to iOS and we are keeping this bug open until all FxiOS gets updated to 1.1+
Let me know if wrong

**Comment by vladikoff** [comment]
can be removed once FxiOS 1.1 ships and everyone has updated! :arrow_up:
