### ISSUE TITLE
Need Metrics data for Avatars

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#2951]
What questions do we have of the Avatars feature to see it's value, progress, and analyze it's UX. Here are questions I would have:
* What's funnel look like from viewers who land on the /settings page?
* What percentage of users have an avatar over time
* histogram of images uploaded
* percentage using camera/upload/gravatar

This data would drive:
* understanding the usage and detection of quality issues with avatars
* drive feature development if there is high traffic

**Comment by vladikoff** [comment]
https://app.datadoghq.com/dash/59141/fxa-content-server---avatars

> What's funnel look like from viewers who land on the /settings page?

See dashboard: `% of users that get to avatar change from the settings screen`

> What percentage of users have an avatar over time

We cannot do exact "over time" but see `Avatar users as a % of new registrations`

> histogram of images uploaded

We cannot do that one. cc @philbooth

> percentage using camera/upload/gravatar

See `Avatar upload vs camera vs gravatar comparison`

**Comment by vladikoff** [comment]
There is other stuff in that dashboard, let me know if you want other graphs added

**Comment by rfk** [comment]
@vladikoff thanks, these datadog dashboards are a great start!  Based on conversation in product meeting, it sounds like there's additional things we want to track that aren't well-served by datadog, so I'm re-opening this and taking ownership to identify what they are and file follow-up bugs to ensure we can get them.

**Comment by rfk** [comment]
Let's work towards measuring:

* Percentage of accounts with an avatar set: https://github.com/mozilla/fxa-profile-server/issues/139
* User satisfaction with the feature: https://github.com/mozilla/fxa-content-server/issues/3010
* The effect that setting an avatar has on user retention (using whatever mechanism we can figure out for https://github.com/mozilla/fxa/issues/46)
