### ISSUE TITLE
Universally ignoring `isVerified` errors seems like the wrong thing to do.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2954]
https://github.com/mozilla/fxa-content-server/blob/150e9db2abb684a8e36fdc09bd31fe0029fce640/app/scripts/models/account.js#L98

It seems like we should only be ingoring `UNAUTHORIZED` errors and handling the rest.

Follow on from https://github.com/mozilla/fxa-content-server/pull/2933/files#r37024931

**Comment by philbooth** [comment]
At least log the different errors.

**Comment by vladikoff** [comment]
@philbooth @shane-tomlinson do you want Sentry or console logging for this?

**Comment by philbooth** [comment]
> ...do you want Sentry or console logging for this?

Sentry seems like it would be more useful?

**Comment by vladikoff** [comment]
@philbooth Yeap, agreed! Thanks for the response

**Comment by vladikoff** [comment]
@philbooth Yeap, agreed! Thanks for the response
