### ISSUE TITLE
If the auth server is down, "Unexpected error" is shown to the user

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2955]
It's not a particularly helpful error message. We have a "service unavailable" error message we could make use of.

STR

1. Stop the auth server.
1. Visit the content server.
1. Watch the blowup.

![no-auth-server-unhelpful-error](https://cloud.githubusercontent.com/assets/848085/9294044/ea425f06-4438-11e5-9810-9bceab4f2e0c.gif)

Ref #2935, #2944, #2956, #2957.

**Comment by shane-tomlinson** [comment]
Ref #2944

**Comment by shane-tomlinson** [comment]
@vladikoff - I imagine the error logging is not particularly helpful in this case either:

> content-server PORT 3030-3 (out): fxa-content-server.server.requests.INFO: GET /metrics-errors?sentry_version=4&sentry_client=raven-js/1.1.18&sentry_key=__API_KEY__&sentry_data=%7B%22project%22%3A%22metrics-errors%22%2C%22logger%22%3A%22javascript%22%2C%22platform%22%3A%22javascript%22%2C%22request%22%3A%7B%22url%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Funexpected_error%22%2C%22headers%22%3A%7B%22User-Agent%22%3A%22Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010.10%3B%20rv%3A40.0)%20Gecko%2F20100101%20Firefox%2F40.0%22%7D%7D%2C%22exception%22%3A%7B%22type%22%3A%22Error%22%2C%22value%22%3A%22Unexpected%20error%22%7D%2C%22stacktrace%22%3A%7B%22frames%22%3A%5B%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Fbower_components%2Ffxa-js-client%2Ffxa-client.js%22%2C%22lineno%22%3A1019%2C%22colno%22%3A4%2C%22function%22%3A%22flush%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Fbower_components%2Ffxa-js-client%2Ffxa-client.js%22%2C%22lineno%22%3A1312%2C%22colno%22%3A9%2C%22function%22%3A%22onSettled%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Fscripts%2Flib%2Ffxa-client.js%22%2C%22lineno%22%3A42%2C%22colno%22%3A19%2C%22function%22%3A%22wrapClientToNormalizeErrors%2FwrappedClient%5Bkey%5D%3C%2FwrappedClient%5Bkey%5D%3C%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Fscripts%2Flib%2Ferrors.js%22%2C%22lineno%22%3A106%2C%22colno%22%3A17%2C%22function%22%3A%22.toError%22%2C%22in_app%22%3Atrue%7D%5D%7D%2C%22culprit%22%3A%22http%3A%2F%2F127.0.0.1%3A3030%2Fscripts%2Flib%2Ferrors.js%22%2C%22message%22%3A%22Unexpected%20error%22%2C%22extra%22%3A%7B%22session%3Aduration%22%3A637%7D%2C%22event_id%22%3A%2280a0575e635b41e7a885d1ba7f0d8f84%22%7D 200 0.240

Running the sentry data through `decodeURIComponent`, then the result of that through JSON.parse  results in:

![screen shot 2015-08-16 at 17 12 33](https://cloud.githubusercontent.com/assets/848085/9294087/4379e746-443a-11e5-8dda-12b28132149a.png)

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/2998
