### ISSUE TITLE
inconsistent handling of down oauth server error handling

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2956]
If the OAuth server is down, errors are handled differently depending on the page. The root settings page shows no error. The communications preferences page shows "System unavailable, try again soon." The change avatar using the camera page shows "Unauthorized."

STR

1. Kill the oauth server.
1. Reload the settings page.
1. Try to change the communications preferences.
1. Set an avatar photo using the camera.

![no-oauth-server-no-error](https://cloud.githubusercontent.com/assets/848085/9294116/30f5b1b2-443b-11e5-8ce9-d7d8b65ab129.gif)

**Comment by shane-tomlinson** [comment]
Ref #2935, #2944, #2955, #2957.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/2998
