### ISSUE TITLE
inconsistent handling of down profile server error handling

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2957]
If the Profile server is down, errors are handled differently depending on the context. The root settings page shows no visible error but does in the console. The communications preferences page doesn't care. The change avatar page shows a console error but no user visible error until trying to upload a photo using the camer, and then it says "System unavailable, try again soon."

STR

1. Kill the profile server.
1. Reload the settings page.
1. Try to change the communications preferences.
1. Set an avatar photo using the camera.

![no-profile-server-no-problem](https://cloud.githubusercontent.com/assets/848085/9294129/d5dbc9c8-443b-11e5-9112-05e2b85eb6a7.gif)

Ref #2935, #2944, #2955, #2956 .

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/2998
