### ISSUE TITLE
Way to track/visualize load time performance needed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2958]
We currently send navigationTiming data to the `/metrics` endpoint and send it to Heka. We don't do much with it after that. It would be nice to also send this info to DataDog or GA so we can easily graph our site's load time performance. The stats to be displayed needs to be decided upon, a good initial set would be the quartiles for [domInteractive or domContentLoadedEventEnd](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API).

**Comment by vladikoff** [comment]
Added via https://github.com/mozilla/fxa-content-server/pull/3042
