### ISSUE TITLE
Sentry Error: origin check timeout (& illegal iframe error, though far reduced)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2965]
![screen shot 2015-08-17 at 22 04 41](https://cloud.githubusercontent.com/assets/848085/9316437/ee80a0ba-452c-11e5-812b-7e1f349983fc.png)

@vladikoff and @jrgm - illegal iframe error is still there, though far reduced, we are seeing a few (in comparison to a week ago) iframe timeout errors.

https://sentry.prod.mozaws.net/operations/fxa-content-product/group/91865/
https://sentry.prod.mozaws.net/operations/fxa-content-product/group/91903/

**Comment by vladikoff** [comment]
Should be fixed now!
