### ISSUE TITLE
Sentry Error: A usable image was not found

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2966]
![screen shot 2015-08-17 at 22 13 20](https://cloud.githubusercontent.com/assets/848085/9316499/493e0c18-452d-11e5-908a-c75b761e1519.png)

https://sentry.prod.mozaws.net/operations/fxa-content-product/group/86337/

**Comment by vladikoff** [comment]
DataDog should have the % on this error if there is an error code.

**Comment by vladikoff** [comment]
Works as expected, we might tweak the message. this happens when a corrupted image is uploaded
