### ISSUE TITLE
Sentry Error: more expired links than expected?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2967]
<img width="795" alt="expired-links" src="https://cloud.githubusercontent.com/assets/848085/9316575/c2ee75d4-452d-11e5-9d76-ddbaac5f2462.png">

https://sentry.prod.mozaws.net/operations/fxa-content-product/group/85502/

**Comment by TDA** [comment]
Can I call nit:`has expired` for sentry logging?

**Comment by vladikoff** [comment]
@TDA https://github.com/mozilla/fxa-content-server/blob/719b2ae68ecb004f3946948f516bd1de0293ef5f/app/scripts/lib/auth-errors.js#L207

**Comment by philbooth** [comment]
Extra auth server error codes to distinguish?

**Comment by vladikoff** [comment]
> Extra auth server error codes to distinguish? 

We shall use the Auth Server DataDog to determine what exactly is happening with the verify links.

**Comment by vladikoff** [comment]
Only happens on complete-reset-password now, which is normal. 

Ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/explore/errno/2876/
