### ISSUE TITLE
Sentry Error: Undefined on verify email error

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2968]
![undefined-verify-email](https://cloud.githubusercontent.com/assets/848085/9316599/f29efea2-452d-11e5-8e7a-8893839c65fd.png)

**Comment by vladikoff** [comment]
@shane-tomlinson sorry, could you link to the report, sometimes it is hard to find it (even with search)

**Comment by shane-tomlinson** [comment]
https://sentry.prod.mozaws.net/operations/fxa-content-product/group/85505/

**Comment by vladikoff** [comment]
Ah yes, I think this is related to https://github.com/mozilla/fxa-content-server/issues/2886

**Comment by vladikoff** [comment]
Hm maybe not, some samples redirect to /cookies_disabled, so maybe "verify_email" throws something early on.

**Comment by vladikoff** [comment]
Not seeing this in Sentry anymore, for now..
