### ISSUE TITLE
Sentry Error: NS_ERROR_UNEXPECTED

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2969]
![ns_error_unexpected](https://cloud.githubusercontent.com/assets/848085/9316618/07e15fe4-452e-11e5-896e-00357fde487c.png)

https://sentry.prod.mozaws.net/operations/fxa-content-product/group/92586/

**Comment by shane-tomlinson** [comment]
Ref #2913

**Comment by shane-tomlinson** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1240238

**Comment by vladikoff** [comment]
We will follow up once we get better logging from Sentry

**Comment by vladikoff** [comment]
Fixed this up and sentry looks better now
