### ISSUE TITLE
No startup spinner displayed to user to give some sort of feedback for slow loads.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2980]
I could swear we used to have a startup spinner that was displayed to the user before any views were rendered to let them know "something is happening." 

Noticed when trying to figure out where the spinner was for the firstrun flow.

ref https://github.com/mozilla/fxa-content-server/issues/2934

cc - @jpetto

**Comment by shane-tomlinson** [comment]
I pulled this into next. We now have several screens that make XHR requests before rendering anything, users who enter FxA via one of these pages currently receive a poor experience.

**Comment by jpetto** [comment]
I second @shane-tomlinson's assertion that there used to be a startup spinner. Did we have the same fever dream?
