### ISSUE TITLE
Test failing: flush writes to localStorage instead of making a xhr request

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-content-server#2984]
<img width="895" alt="screen shot 2015-08-19 at 12 06 28 pm" src="https://cloud.githubusercontent.com/assets/6424575/9366197/bf092b10-466a-11e5-89bb-f1fa5382c19a.png">

flushTime property is different on both objects.

**Comment by vladikoff** [comment]
Sometimes fails sometimes passes.
I guess we can just `delete filteredData.flushTime`, like we delete duration
