### ISSUE TITLE
COPPA selectors in form.js have to go

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#2989]
Follow on from #2977.

These two coppa specific selectors need to go:
* [ ] https://github.com/mozilla/fxa-content-server/blob/7b2cf5badb12d9e6b7a96c330a09fc6ce4f78c98/app/scripts/views/form.js#L217
* [ ] https://github.com/mozilla/fxa-content-server/blob/7b2cf5badb12d9e6b7a96c330a09fc6ce4f78c98/app/scripts/views/form.js#L284

This should be replaced with a general solution.

cc @vladikoff

**Comment by vladikoff** [comment]
Let's revisit this once we have to update validation in our forms or COPPA
