### ISSUE TITLE
First character of password entry is capitalized on iOS

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2991]
I have unconfirmed reports that when `context=fx_ios_v1` the first letter of the password input entry is automatically capitalized.  I believe that's controlled by the web content and not the embedding `WKWebView`.  Could I get confirmation and a fix, if it is in the content server?

**Comment by vladikoff** [comment]
if SHOW password is used then iOS capitalizes the password. cc @ryanfeeley 

We can try to fix it up for train 44

**Comment by vmunix** [comment]
Thx, I was the unconfirmed reporter.  :)

**Comment by ryanfeeley** [comment]
@vladikoff Should we also make autocorrect spelling false on that field?

**Comment by vladikoff** [comment]
@ryanfeeley yea that's part of the patch too
