### ISSUE TITLE
fxa.content.screen.settings.avatar metric seems broken

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3004]
Ref: https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1437938827284&to_ts=1440530827284&tile_size=m&exp_metric=fxa.content.screen.settings.avatar,fxa.content.screen.settings.avatar.crop&exp_scope=&exp_agg=sum&exp_row_type=metric

@zaach any clues?

**Comment by zaach** [comment]
The "avatar" screen isn't a thing, do you want avatar.change?

**Comment by vladikoff** [comment]
ah yes! perfect!
