### ISSUE TITLE
Password tooltip CSS regression on /signup

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3019]
### Actual

![image](https://cloud.githubusercontent.com/assets/128755/9620823/7d34d986-50ed-11e5-8141-fcdb4f12359a.png)

### Expected 

![image](https://cloud.githubusercontent.com/assets/128755/9632358/b50b2ca4-5154-11e5-9aae-26164a00ca67.png)

Train-45 commit change ref: https://github.com/mozilla/fxa-content-server/commit/936c64bfe0303f9bf19c230d61ba54f647592e39#diff-82d2573781639c8e7305c4388a87dd59R13

Only affects `master`

**Comment by shane-tomlinson** [comment]
What is the regression here?

**Comment by vladikoff** [comment]
Updated with "Expected", the message should be centered.

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-content-server/pull/3022
