### ISSUE TITLE
source maps do not work correctly in prod

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3020]
A Source map is served, but not working correctly in prod.

**Comment by vladikoff** [comment]
Works fine for me http://v14d.com/i/55e6f892cd43b.jpg

**Comment by vladikoff** [comment]
Let me know what you mean by "but not working correctly"

**Comment by shane-tomlinson** [comment]
re-opening, does not work in Firefox:

![screen shot 2015-09-02 at 15 02 27](https://cloud.githubusercontent.com/assets/848085/9633244/bbfc9514-5183-11e5-952a-b7f53a32eaaa.png)

Files are not separated, I cannot set a breakpoint, the expanded source is useless.

**Comment by shane-tomlinson** [comment]
Ok, now I can set a breakpoint. Ugh.

The part about the main bundle not being separated out into the component files still stands.

**Comment by vladikoff** [comment]
> The part about the main bundle not being separated out into the component files still stands.

@shane-tomlinson probably a firefox problem, either not supported or broken

**Comment by vladikoff** [comment]
The sourcemap is generated from main.js not from multiple files, so you won't see file separation.

**Comment by vladikoff** [comment]
> The sourcemap is generated from main.js not from multiple files, so you won't see file separation.

To see multiple file view we have to change the way the sourcemap works + copy all dev files into dist as part of the build. Not sure if that is worth it. (I just use the search functionality in devtools to jump to the point I need)
