### ISSUE TITLE
Resume tokens can be extraordinarily long

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3026]
Our resume tokens are getting really long.  They can currently contain the following fields:
- campaign
- entrypoint
- state
- utmCampaign
- utmContent
- utmMedium
- utmSource
- utmTerm
- verificationRedirect
- uniqueUserId

With the added overhead of JSON-and-b64-encoding.  This can lead to weirdness like the stretched display of emails over in https://github.com/mozilla/fxa-auth-mailer/issues/73, and just general ugliness when displaying the URLs verbatim.

Can we do better?  Mabye.  Three options:
- do nothing, it's fine the way it is
- use a more efficient encoding, e.g one that doesn't require all the field names to be present as strings
- store the resume-token contents server-side and generate shorter opaque ids through which they can be looked up (this would cost two round-trips to the server though)

**Comment by rfk** [comment]
(also we need a "too damn long!" meme in here, stat)

**Comment by shane-tomlinson** [comment]
> store the resume-token contents server-side and generate shorter opaque ids through which they can be looked up (this would cost two round-trips to the server though)

I'm not sure what repercussions this would have on the front end. We assume the resume token info is available on startup and populate the relier with the information before any further action occurs. If we were to work around that, could the data be returned as part of the code verification to eliminate the extra XHR request?

**Comment by rfk** [comment]
Hmm, good point, putting an XHR that early into the startup flow doesn't seem like a great idea.

**Comment by vladikoff** [comment]
@rfk if we are adding more fields in https://github.com/mozilla/fxa-content-server/issues/3550 then the token might be even longer now, so this issue is becoming even more relevant again.

**Comment by rfk** [comment]
Indeed.  My sense is that we don't need to block on this, but we should keep an eye on it.

Most of the resume-token contents are metrics-related:

* flowId (new!)
* flowBeginTime (new!)
* campaign
* entrypoint
* utmCampaign
* utmContent
* utmMedium
* utmSource
* utmTerm
* uniqueUserId

It would be neat if we could store all of those in e.g. memcahed, indexed by a single id (the flowId?), and look them up if we need them from wherever it is we need them.  That would reduce the contents of the resumeToken to just:

* flowId
* state
* verificationRedirect

But I don't really have a sense of how big that sort of refactor would be.

**Comment by rfk** [comment]
Another option could be to just avoid encoding the keys.  We know what the possible keys are and can enumerate them in order.  Instead of encoding as an object like:

```
  { "entrypoint": "preferences", "utmCampaign": "facebook2016", "uniqueUserId", "1234567890abcdef" }
```

We could encode as a list where each position maps to a specific key, like:

```
  [ "preferences",,"facebook2016",,,,,"1234567890abcdef"]
```

This would make adding keys a little more fragile, and removing keys essentially impossible without breaking old tokens.  But the tokens would be much shorter!

**Comment by ryanfeeley** [comment]
![64443533](https://cloud.githubusercontent.com/assets/68213/16589024/61d085b0-429f-11e6-99de-5f8d36f5d45e.jpg)

**Comment by ryanfeeley** [comment]
![1e60897861e401b796adbb3a4c540623](https://cloud.githubusercontent.com/assets/68213/16589079/8a304a68-429f-11e6-9e3e-c0fa8ae47506.jpg)
@rfk

**Comment by vladikoff** [comment]
@rfk should we still worry about this? we removed the long urls from emails...

**Comment by rfk** [comment]
I'm less worried about this with the latest styling changes to our emails, and it didn't sound like we had a clear winner of a solution.  I'm going to close it out, if it still bugs us I'm sure we'll re-open in due course.
