### ISSUE TITLE
All settings panels report the screen name as `settings`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3029]
```
["settings.communication-prefs-link.visible.true","screen.settings","settings.newsletter.optin.false","settings.refresh","settings.profile_image_not_shown","screen.settings","screen.settings","screen.settings","screen.settings"]
```

Not a problem if we banish the settings page from being iframed (#2945), but something I found while testing #3006.

**Comment by shane-tomlinson** [comment]
cc @zaach.

**Comment by vladikoff** [comment]
@zaach moved to `next`

**Comment by shane-tomlinson** [comment]
This is a problem in general, not for just the iframe flow.

**Comment by vladikoff** [comment]
switched to @shane-tomlinson

**Comment by zaach** [comment]
Ah, well I'll dump my current thoughts: the issue is that we get the `screenName` from the URL of the window at the time the view is created, which is a problem when we create multiple views at once, e.g. on /settings. Ideally, views could declare their `screenName` and we'd prefer that if present.
