### ISSUE TITLE
Track how long browsers remain in the unverified state

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3046]
Because we don't offer users a convenient way to correct mistyped emails, we may have a large number of users stuck in the unverified state.

I'm hoping that these number are already available, but I would like to see a distribution of how long users are in the unverified state.

Ideally it's a bell curve shape, and if not, we can improve the experience to make it this way.

**Comment by vladikoff** [comment]
Hm this issue is *probably* for the auth server instead

**Comment by ryanfeeley** [comment]
@vladikoff Should I just copy and paste it?

**Comment by vladikoff** [comment]
@ryanfeeley let's discuss it in triage next week (monday)

**Comment by ckarlof** [comment]
If you mean *browsers* and not accounts, I'm not sure how we'd do this other than instrumenting the actual browser.

**Comment by vladikoff** [comment]
@ryanfeeley 
I think we got a bit confused what you are looking for here. Could you explain or expand the issue a bit more?
Are you looking for Firefox Desktop "Unverified State" or user's global account unverified state?

You mention "Track how long browsers" and then you say "I would like to see a distribution of how long users " so it is a bit confusing.

**Comment by rfk** [comment]
Let's try to measure this cheaply on the server side.  Whenever we get a verification ping and the account is unverified, emit an log event and include the time since account creation.  I'm hopefuly we can do this without making an extra db query, because doing an extra db query on the verification pings would be a performance killer.

If we can't measure it cheaply, let's re-evaluate whether and how to do it.

**Comment by philbooth** [comment]
I've tested out sending this data to `fxa-testing-dog` using the linked PR and it arrives correctly. I can see it coming in on a time-series graph, for instance.

I haven't got a distribution graph to work yet though. I've asked datadog support for help but if anyone here has any pointers, feel free to chime in.

**Comment by vladikoff** [comment]
@ryanfeeley 

Instead of doing `Track how long browsers remain in the unverified state`, are you okay with 
`Track how long accounts remain in the unverified state (using fxa-auth-server timing)`?

**Comment by ryanfeeley** [comment]
I guess we can know if they are created via Sync?

**Comment by vladikoff** [comment]
> I guess we can know if they are created via Sync?

I don't think we can determine that, I can start signing up for sync, but then actually confirm my account when I'm signing into Pocket.

Ref: https://github.com/mozilla/fxa-auth-server/blob/phil/verification-time/lib/routes/account.js#L681

@philbooth thoughts?

**Comment by rfk** [comment]
Per discussion in meeting, "track how long accounts remain in the unverified state, regardless of service" is a valuable step and we should do that first before decided whether to ask more detailed questions.
