### ISSUE TITLE
bounceemail test failure (consistent on stage, at least sometimes if not all on latest)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3047]
There is a test failing in stage, like so, probably on a timing difference:
`
× firefox on any platform - sign_up with an email that bounces - sign up, bounce email, allow user to restart flow but force a different email [37m (29.916s)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/a17b5ce8-66b9-4a7c-b18f-5529095ea2bb/element / {"using":"id","value":"fxa-confirm-header"}] Unable to locate element: {"method":"id","selector":"fxa-confirm-header"}
`

which is https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/bounced_email.js#L40
```
    'sign up, bounce email, allow user to restart flow but force a different email': function () {
      var client = new FxaClient(AUTH_SERVER_ROOT, {
        xhr: nodeXMLHttpRequest.XMLHttpRequest
      });

      return FunctionalHelpers.fillOutSignUp(this, bouncedEmail, PASSWORD, CUTOFF_YEAR - 1)
        .findById('fxa-confirm-header') //<-- HERE
        .end()

```

I think a visibleByQSA would fix it. @vladikoff thoughts?

**Comment by vladikoff** [comment]
I will check it out, adding the QSA check makes sure that the template is populated with the title instead of an empty "fxa-confirm-header" element. not sure if that will help

**Comment by jrgm** [comment]
This also fails, at least sometimes, on latest
http://tests.dev.lcip.org:8111/viewLog.html?buildId=5886&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=424

**Comment by vladikoff** [comment]
I'll check it out ...
