### ISSUE TITLE
"No username" in password manager during 'force_auth'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3049]
### Actual
![image](https://cloud.githubusercontent.com/assets/128755/9792750/c0fadf1c-57af-11e5-9963-987ca6b0a48c.png)

### Expected

Username should be the email

### Notes

Looks like the fix for  https://github.com/mozilla/fxa-content-server/issues/2754 did not work for force_auth or was not applied

**Comment by shane-tomlinson** [comment]
Bah, in https://github.com/mozilla/fxa-content-server/commit/ff38e16a81163ee4baa1a04d949bec7f8166646a, I only added the fix to the sign_in template w/ cached creds, not for force_auth.
