### ISSUE TITLE
Display name overflow on new settings page looks clipped

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#3052]
<img width="181" alt="screenshot 2015-09-11 10 01 54" src="https://cloud.githubusercontent.com/assets/2365255/9820970/2ed3db94-586c-11e5-9994-465405f4a743.png">

**Comment by ckarlof** [comment]
This was on Firefox 43, Nightly.

**Comment by shane-tomlinson** [comment]
ref #3055
