### ISSUE TITLE
Loading of settings page via Manage link in Sync preferences page is not smooth

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#3053]
I get some flashing and see the Firefox logo briefly.

**Comment by shane-tomlinson** [comment]
cc @zaach

**Comment by shane-tomlinson** [comment]
ref #3007 as one possible source of slowness.

**Comment by ckarlof** [comment]
Also, /settings seems to take a while to load, even after it's cached (I get the spinner all the time).

**Comment by zaach** [comment]
> Also, /settings seems to take a while to load, even after it's cached (I get the spinner all the time).

Hints at #3007 and other API calls.

**Comment by rfk** [comment]
Here's the series of XHR I see when reloading `/settings` (to try to use a warm cache):

* GET /session/status
* POST /certificate/sign
* POST /authorization
* GET /profile
* GET /session/status
* GET /session/status
* GET /session/status
* GET /session/status
* GET /session/status
* GET /profile
* POST /certificate/sign
* POST /authorization
* GET /lookup-user
* POST /destroy
* GET /avatar

There's also likely some non-trivial CPU being burnt when generating those two signed assertions.

**Comment by shane-tomlinson** [comment]
> There's also likely some non-trivial CPU being burnt when generating those two signed assertions.

Huh, this was fixed once before: https://github.com/mozilla/fxa-content-server/issues/2921

**Comment by vladikoff** [comment]
for next 2 weeks / to check with other patches

**Comment by shane-tomlinson** [comment]
ref #3092, @shane-tomlinson to double check if this is "smooth enough"

**Comment by shane-tomlinson** [comment]
We only generate one certificate and make one session/status request now. We still create 2 OAuth tokens and make 2 profile requests. The first can't be helped, the 2nd we are working on.

The settings page is much smoother now. Manual tests tried:

* Sign in from /signin
* force refresh from /settings
* refresh using cache from /settings
* refresh and force refresh sub-panels

Closing as "Good enough for now."
