### ISSUE TITLE
When I change my avatar on the new settings page, a line appears at the bottom of the list of options

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#3054]
This appears concurrently with the lightbox showing.

**Comment by vladikoff** [comment]
@ckarlof any way to get a screenshot? which "list of options" ?

**Comment by ckarlof** [comment]
It briefly appears and then seems to disappear. 

![line](https://cloud.githubusercontent.com/assets/2365255/9821152/63089f48-586d-11e5-9225-649a582326d9.gif)

**Comment by vladikoff** [comment]
@ckarlof thanks for the gif!

**Comment by shane-tomlinson** [comment]
I no longer see this problem against either prod or local dev. Closing as fixed.
