### ISSUE TITLE
New Settings header UI tweaks

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#3055]
Let's make the Avatar a bit bigger and make the overall layout mirror other pages a bit more closely.
@ckarlof @ryanfeeley 
<img width="1100" alt="settings" src="https://cloud.githubusercontent.com/assets/3323249/9822641/65413a50-5876-11e5-90be-6ea583d1e3e4.png">

**Comment by ryanfeeley** [comment]
Love it!

**Comment by billmaggs** [comment]
Much, much better. How about display name in there somewhere if people end up using them?

**Comment by johngruen** [comment]
@billmaggs sure, I can play around with that one...also note to self, @ryanfeeley suggested making the header a bit roomier adn the bottom border a bit lighter

**Comment by billmaggs** [comment]
Looks like there may still be lots of white space in the Settings when seen on Mobile as noted in a previous Issue. May need to be updated.

**Comment by rfk** [comment]
@johngruen is this ready for implementation or do you need to make another round of tweaks?

**Comment by johngruen** [comment]
@rfk ready to go. I can knock this one out this week.

**Comment by johngruen** [comment]
@shane-tomlinson @vladikoff fistbumps all around
