### ISSUE TITLE
Mobile row height in settings

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#3056]
This one comes from @ncalexan. 

The row heights on mobile settings look a little big..let's reduce the top/bottom padding by a few pixels.
![fxa settings on fennec](https://cloud.githubusercontent.com/assets/3323249/9822853/b4d51496-5877-11e5-9566-3cf7bdd7ac13.png)

**Comment by billmaggs** [comment]
This design has been updated and probably doesn't look this way now.....

**Comment by shane-tomlinson** [comment]
ref #3055.

**Comment by shane-tomlinson** [comment]
Closing in favor of #3055 which has the new proposed designs.
