### ISSUE TITLE
iframe responsive view not responsive enough

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3060]
Working on some stub installer designs with @verdi and he noticed that the responsive view is snapping a little late. See image.
![responsive](https://cloud.githubusercontent.com/assets/68213/9878306/fcb2cfd6-5b8f-11e5-8301-bc44775b7c50.gif)

**Comment by ncalexan** [comment]
I notice this on Fennec -- we seem to be pinned to at least 360px wide.

**Comment by ryanfeeley** [comment]
Uh oh, seems to also affect current iOS users (iPhone 5S 320 retina pixels wide) ![2015-09-16 12 58 00](https://cloud.githubusercontent.com/assets/68213/9912199/3832c05e-5c74-11e5-85ce-8d5b1ad6bec1.png)

**Comment by vladikoff** [comment]
Promoting this, we are getting a lot of reports of this issue
