### ISSUE TITLE
new settings panel blocks waiting on basket /lookup-user

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3061]
It looks to me that the new settings panel blocks waiting on basket /lookup-user.

**Comment by rfk** [comment]
Indeed it does, and this will make for a bad experience if there's any basket downtime or slowness.  It sounds like our simplest option is to try to delay this request until the user activates the "communication preference" panel, rather than doing it at page load time.

**Comment by jrgm** [comment]
This really should be done for train-46 at minimum. It's a big problem.

**Comment by ckarlof** [comment]
Indeed. I had the same concern. Related is #3053.

**Comment by rfk** [comment]
He may not have the bandwidth to take it on himself, but I think we'll need @zaach's advice on the best way to approach this.

**Comment by jrgm** [comment]
"basket" has had problems for hours now, and there is apparently no support for this at all.

New user signups now block for 2.5 seconds, which is a lovely user experience. For hours.

**Comment by rfk** [comment]
> New user signups now block for 2.5 seconds

Just to clarify, this blocking occurs when they go to load the settings page at the end of the flow?

We could get brutal and remove this panel from the settings page until we can refactor our way out of this.  The only functionality it currently offers is the ability to unsubscribe from the marketing emails, and this functionality is also available via "unsubscribe" and "modify your preferences" links from within the emails themselves.

**Comment by jrgm** [comment]
> Just to clarify, this blocking occurs when they go to load the settings page at the end of the flow?

Yes
