### ISSUE TITLE
Layout issues in “Sign in” pop-up window of marketplace (bug 1204421) 

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3065]
(Migrating #3059 from a PR to an issue for discussion and triage)

In [1] was reported a Marketplace bug where it loads the FxA signin page in a popup window, but the layout is distorted.  It appears this was cased by the settings UI refresh which introduces this style on the `.card` class:

```
  &.card {
    width: 420px;
  }
```

Which makes it wider than the marketplace popup window's fixed width.

In #3059 was proposed a fix that made things work for marketplace, but broke layout on wider screens.

I see two options for fixing:
* We could use `max-width: 420px` rather than `width` on this element, like in the `&.panel` declaration immediately following `&.card`.
* Marketplace could make their popup wider to accommodate the new layout.

Does the first seem reasonable from the FxA side?

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1204421

**Comment by rfk** [comment]
I ni?d :chuck in the linked bug to get more info on how to triage this.

**Comment by johngruen** [comment]
@rfk, this issue will take me a few secs to fix. we just need to add some breakpoints to the `.card` class. Stay tuned

**Comment by shane-tomlinson** [comment]
ref #3060, fixed by #3071

**Comment by pdehaan** [comment]
Closing. I believe this was fixed by #3071.
