### ISSUE TITLE
Support choose-what-to-sync via the web for Fennec?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3080]
Along with the move to web-hosted signin UI, Fennec would also like to use web-hosed choose-what-to-sync UI.  This bug tracks figuring out whether we can provide that in the required timeframe, and if so then settling on the details of how.

Original feature bug from when we were working on this in desktop: https://github.com/mozilla/fxa/issues/18
Original PR from @vladikoff: https://github.com/mozilla/fxa-content-server/pull/2757
Corresponding Fennec bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1191068

Per discussion with @ncalexan, we would need to make this available sometime while Fennec 43 is on Aurora.  Realistically that means deploying it in train-48 or earlier, which is two cycles from now.

I suspect that it may be simpler to deploy this for Fennec than for Desktop, because we don't necessarily need a full-blown capabilities handshake - we would know that *all* devices with `context=fx_fennec_v1` support choose-what-to-sync on the web.  In which case we may be able to do something like:

* settle the message protocol and let Fennec build their client-side support in 44.1 (train-47)
* resurrect the UI components of #2757 but with simplified capabilities stuff, available only to fennec in 44.2 (train-48)
* work on desktop support with full capabilities model (or equivalent) in 44.3 or beyond

But I'm not close enough to the details to know whether that's a good idea.  @vladikoff @shane-tomlinson thoughts?

The alternative is for Fennec to do what Desktop does today, and use a native choose-what-to-sync UI that pops up after the login has completed.  Nick tells me that's doable, but if that's the way to go, we should let them know sooner rather than later.

**Comment by vladikoff** [comment]
What should we do to "manage" sync data types on Fennec?
Is there something that shows this list like it does on Desktop:
<img src=http://v14d.com/i/55fc24dbf2cea.jpg width=200 />

Do we need to worry about that?

**Comment by ncalexan** [comment]
On Fri, Sep 18, 2015 at 10:52 AM, Vlad Filippov <notifications@github.com>
wrote:

> What should we do to "manage" sync data types on Fennec?
> Is there something that shows this list like it does on Desktop:
>
> <https://camo.githubusercontent.com/fd3309dbc2c7c80c1b565cdf8141838f290a4c75/687474703a2f2f763134642e636f6d2f692f353566633234646266326365612e6a7067>
>
> Do we need to worry about that?
>
@vladikoff Yes, that exists in Fennec: it's the (native) Status Activity.
It looks like
https://people.mozilla.org/~nalexander/screenshots/06.Sync.Settings.png.

**Comment by rfk** [comment]
It sounds like the next step here is for @vladikoff and @ncalexan to sync up IRL about some of the details here, to see if the web-based implementation is really feasible.

I also have a suggestion about the precise form of the message that reports back the chosen datatypes, but I'll save it for when we get down to that level of detail...

**Comment by vladikoff** [comment]
Some work here: https://github.com/mozilla/fxa-content-server/pull/3077

**Comment by vladikoff** [comment]
from mtg: 
in the message back we should be specific about the service and probably version it:
``` 
services:{
   sync: ... sync v1.5 { declinedEngines ....}
}
```

**Comment by rfk** [comment]
> probably version it

I suspect this won't be worth it, as the client should already know what version of the service it was trying to connect to, and our services don't actually change version that often.
