### ISSUE TITLE
iOS Sync users should not have to re-enter their passwords

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3086]
STEPS TO REPRODUCE:
On iOS sign in to Sync
Then click the username to go to account management features

WHAT HAPPENS:
User must re-enter their password to manage account

WHAT SHOULD HAPPEN:
User should not have to re-enter their password until the session on the web has expired

Depicted:
![ios-reauth](https://cloud.githubusercontent.com/assets/68213/9995638/2e895c9e-6051-11e5-8b4b-336b71afb7d0.png)

**Comment by vladikoff** [comment]
> WHAT SHOULD HAPPEN:
User should not have to re-enter their password until the session on the web has expired

So they would just see "Sign in", click it and then go back to FxiOS Settings? (Keep in mind there is no content server settings view on FxiOS)

**Comment by ryanfeeley** [comment]
OK, so @vladikoff explained it. It is just weird like this for now until settings appears.
