### ISSUE TITLE
Reloading settings page is really slow

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3096]
Am noticing that reloading this page* takes a long time to render.

https://accounts.firefox.com/settings?uid=THISISAUID&email=email%40gmail.com&entrypoint=menupanel

\* swapped the UID with THISISAUID

**Comment by shane-tomlinson** [comment]
Dup of #3053?

**Comment by ryanfeeley** [comment]
Yep.
