### ISSUE TITLE
No way to generate histogram/distribution graphs for navigationTiming data

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3101]
We send navigationTiming data to StatsD, but are unable to generate histogram/distribution graphs because StatsD automatically rolls up the stats into 25th, mean, median, 75th, 95th, and max, but does not retain the original data. We may need to send these stats as [histogram](http://docs.datadoghq.com/guides/dogstatsd/#histograms) data instead (or in addition to). Also read [this note about how DataDog handles timing data](http://docs.datadoghq.com/guides/dogstatsd/#timers).

Thankfully, node-statsd supports [histogram data too](https://github.com/sivy/node-statsd).

Ref #3100.

cc @philbooth, @vladikoff.

**Comment by philbooth** [comment]
Changing to histogram makes no difference, I've tested it in `fxa-testing-dog` [here](https://app.datadoghq.com/dash/70289/fxa-dev---testing-out-statsd-timinghistogram-weirdness?live=false&page=0&is_auto=false&from_ts=1443183846220&to_ts=1443187446220&tile_size=m).

The key, I think, is that we only have access to the summarised metrics `.avg`, `.median`, `.max` etc, not to the raw data-points. I have an email thread going with somebody from datadog about it, will update here as soon as there is some concrete progress.

**Comment by philbooth** [comment]
These are the salient chunks from the datadog correspondence. I've edited out the surrounding fluff, so shout if you think there's any important context missing.

> It's the `.as_count()` function that takes in the actual raw values. This query is essentially summing the raw metric count. FYI, only counting metrics - such as the specific metric used in this example - will respond to the `as_count()` function. You can recognize such a metric by the presence of `.count` at the end of its name.
>
> Take a look at the following doc that looks at graphing functions in details. Lots of good info there, perhaps you'll find it helpful.
>
> http://help.datadoghq.com/hc/en-us/articles/204820019-Graphing-with-Datadog-from-the-query-to-the-graph

...

> A pure distribution graph would be a little different from the sort of data you can view in Datadog, which would be more metrics over time. That said there are working solutions.
>
> The distribution visualization type is useful only when metrics are aggregated across tags. In my example graph I'm incrementing a count of `fxa.content.pbooth.bar.histogram.count`. So, there is only a single metric being queried. There are currently no differentiations applied to this metric - just a integer, so there's only a single metric to distribute. In order to set distribution params you would set tags for the different ranges you'd like to distribute over your graph.
>
> For example, imagine that you wanted to see a breakdown of the age of every person using, say, a web app of yours. These ages are coming in as a raw counts for each user (`user.age`). In order to distribute these ages correctly you'd want to tag `user.age` with an age/range (something like `age:<value>`), thereby creating delimitation in what was previously graphed as a simple count. You would then be able to graph by age, allowing you to see a breakdown, but this would still apply as a metric over time value. To change this, you could create larger rollup periods using the .rollup function defined in http://docs.datadoghq.com/graphing/#functions.
>
> Please see the following doc for a primer on tagging.
>
> http://docs.datadoghq.com/guides/tagging/

**Comment by philbooth** [comment]
Also, for completeness, my last message to them:

> Thanks Matthew, that does make sense now although I'm not sure how useful it is to us at the moment. Is there any possibility that you guys might at some point implement automatic classification into ranges, e.g. based on standard deviations from the mean for a given data set?
>
> Our use-cases are timing-based, where it is difficult to correctly tag the data with an appropriate range. For instance performance metrics, which can vary naturally over time. Depending on what time-period is being graphed, the tags that we would want to classify the data by will vary too.
>
> Ideally, we'd want the graph itself to work out the mean and the standard deviation for the data-set, put the mean in the center of the graph and then plot each data-point in the correct bar depending on how many standard deviations greater or lesser than the mean it is. Of course, I have no idea how feasible such an approach would be for you guys, but just wanted to share it as the kind of thing we were hoping for.

**Comment by vladikoff** [comment]
from mtg: @shane-tomlinson to check the milestone for this one, not needed for FXA-49..

**Comment by rfk** [comment]
> from mtg: @shane-tomlinson to check the milestone for this one, not needed for FXA-49..

assigned to @shane-tomlinson for next action

**Comment by vladikoff** [comment]
@shane-tomlinson to deal with this bug..

**Comment by shane-tomlinson** [comment]
We still have no distribution, but we have median and 95th%, good enough for now. Closing.
