### ISSUE TITLE
implement "maintenance mode" error handling to show "calm" errors

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3103]
We've all seen the whale, but it would be good to have a way to have mode which would cause the client to just politely say "sorry, I can't do that right now". 

Activation on the server side should be possible to turn on and turn off without making other changes, or restarting services. (Touching a well-known file on disk and a background poller in the content-server, OR put a signal handler in that toggles the state).

**Comment by rfk** [comment]
/cc @ryanfeeley for some guidance on what the UX might look like here.

From an API perspective, I assume this would look similar to how to does in e.g. sync, with the server sending a specially 503 that triggers a particular kind of error message in the client.

@jrgm are you facing a particular change procedure for which you wish you had this feature?  A concrete example might help with understanding the UX requirements here.

**Comment by jrgm** [comment]
For the UX, I was thinking that if a user visits any top-level page, they get a page that just says "sorry, later". For users who have already loaded, e.g., /settings, any interaction with the page would eat an error response, and instead of showing a scary error in red, the notification would just say "sorry, later".

I wasn't thinking of any change to the API servers. 

I have a database maintenance pending, and something like this would be less stressful on users ("is it me? Wut?"), and give a perception that things will return to normal soon. I don't expect much drama if the multi-AZ upgrade works as expected, but it crossed my mind that this is something we should have. It's a wishlist item; not looking for a rushed hack to get this in place.

**Comment by rfk** [comment]
Thanks @jrgm, that does indeed clarify things.

> I wasn't thinking of any change to the API servers. 

The easiest way to propagate such a state to already-loaded clients would be to have the API servers return the errors, but I guess that means you might have to flip the "maintenance mode" bit on multiple servers.

> not looking for a rushed hack to get this in place.

Luckily we are both on the same page in that case :-)

**Comment by shane-tomlinson** [comment]
Ref #829

**Comment by ryanfeeley** [comment]
I'll design both the static page for new & returning visitors, and a temporary message for current users attempting to perform an action. Assigning to myself for now.

**Comment by ryanfeeley** [comment]
@jrgm How is something like this for active users? (example shows someone who submitted form right after servers went down) 
![uhoh](https://cloud.githubusercontent.com/assets/68213/10230070/529be4e4-6849-11e5-8029-0629b935aa43.png)

**Comment by ryanfeeley** [comment]
And for returning or new visitors…
![uhoh2](https://cloud.githubusercontent.com/assets/68213/10230197/e7ae7236-6849-11e5-8800-6a44da1443ee.png)

**Comment by vladikoff** [comment]
:eyes:

**Comment by ryanfeeley** [comment]
OH "can't be perfect all the time"

**Comment by shane-tomlinson** [comment]
> OH "can't be perfect all the time"

My ego cannot accept this.

**Comment by ryanfeeley** [comment]
This image centered on a #f2f2f2 background should do the trick? @vladikoff  ![error_background_f2f2f2](https://cloud.githubusercontent.com/assets/68213/13091680/5af6574e-d4ca-11e5-9382-452ff65ea288.png)

**Comment by vladikoff** [comment]
@jrgm and @vladikoff to talk about this...

**Comment by ryanfeeley** [comment]
Note: show the image at half-width (433px) as it's 2x size.
