### ISSUE TITLE
Module dependencies are not sorted alphabetically

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3108]
If a module has [a bunch of unsorted dependencies](https://github.com/mozilla/fxa-content-server/blob/354c4a26954d783f74afaf30b7027e586bee7889/app/scripts/lib/app-start.js#L19-L64), it's difficult to find the one I care about.

Ref #3107

**Comment by shane-tomlinson** [comment]
The giant list of unsorted dependencies in app-start.js points to larger problems. Sorting the list would at least make reading/scanning the ugliness a bit less painful.

**Comment by vladikoff** [comment]
@shane-tomlinson was this fixed with eslint?

**Comment by shane-tomlinson** [comment]
@vladikoff - I started a patch to an eslint plugin that I still need to expand upon. I added functionality to enforce alphabetization for AMD style code, now that we are using the simplified CommonJS wrapper, no go. But, the original problem has been manually fixed, deps are now sorted alphabetically. Closing.
