### ISSUE TITLE
Broken vertical spacing on "Signed out successfully" message

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3119]
When I sign out, the div for the message bumps into the title above it:

<img width="189" alt="screen shot 2015-09-30 at 16 50 20" src="https://cloud.githubusercontent.com/assets/64367/10198392/b3ce7c7e-6793-11e5-89d4-29071d07b29e.png">

**Comment by philbooth** [comment]
Weirdly/interestingly, this appears to not always be the case. Just now I did it, same browser (Fx 43), and it looked fine:

<img width="221" alt="screen shot 2015-09-30 at 17 25 49" src="https://cloud.githubusercontent.com/assets/64367/10199419/8be0c262-6798-11e5-8672-2af8629a50a6.png">

**Comment by philbooth** [comment]
Could this be related to https://github.com/mozilla/fxa-content-server/issues/3099?

The distinguishing feature between the two states described above was having dev tools open. If I open and close dev tools, it flicks between the two states.

**Comment by vladikoff** [comment]
> Could this be related to #3099? 

Yeap the small responsive template has the spacing issue it seems

**Comment by shane-tomlinson** [comment]
There was another, related, bug open about this before, @TDA tried to fix it with #2973. Original bug is #2770. It looks like the bug is more general than originally reported.
