### ISSUE TITLE
Enable Romanian in production

### ISSUE THREAD

**Issue by mathjazz** [mozilla/fxa-content-server#3125]
Romanian (ro) is fully translated, could you enable it in production?

@stelistcristi

**Comment by ioana-chiorean** [comment]
Thanks @mathjazz !

**Comment by shane-tomlinson** [comment]
Thanks @mathjazz, @stelistcristi, and @ioana-chiorean! PR opened to enable the locale. Romainian should be enabled with train 47 in ~ 1.5 weeks time.
