### ISSUE TITLE
Communication preferences spinning wheel off axis

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3127]
The spinning wheels that indicates progress of newsletter subscription process appears off axis. Not centered?
![spin](https://cloud.githubusercontent.com/assets/68213/10255739/64df8396-691a-11e5-99e7-22eb81990edb.gif)

**Comment by johngruen** [comment]
@ryanfeeley what browser are you using? The spinner is generated by the same spinner class that's used across FXA. I'm not seeing anything in DevEdition. I do see a slight jog in the gif you're showing, but in my build it looks okay: 
![spinner](https://cloud.githubusercontent.com/assets/3323249/10257652/efe5c85e-6958-11e5-8d94-7f71042e9a01.gif)

HOWEVER, i did notice that the spinner is positioned on the high side at smaller break points. We should definitely fix this: 
![small-spinner](https://cloud.githubusercontent.com/assets/3323249/10257670/098cbe66-6959-11e5-86e0-9fa266758a8b.gif)

**Comment by johngruen** [comment]
@ryanfeeley: not seeing the off-axis spinner in release either.

**Comment by johngruen** [comment]
@ryanfeeley btw you can save yourself a bit of headache by firebugging the the submit button there. add a `disabled` class to the button and then replace the text with `<div class="spinner"></div>`

**Comment by ryanfeeley** [comment]
Good tip! It's Nightly.

**Comment by shane-tomlinson** [comment]
> HOWEVER, i did notice that the spinner is positioned on the high side at smaller break points. We should definitely fix this:

ref #1941

**Comment by shane-tomlinson** [comment]
@johngruen says this only happens in Nightly. Let's keep our eye on this to see if the same behavior makes its way to Aurora and Beta.

**Comment by vladikoff** [comment]
Checking latest Nightly and it seems to be fine now.
