### ISSUE TITLE
Separate string needed for "Sign in" header

### ISSUE THREAD

**Issue by splewako** [mozilla/fxa-content-server#3128]
https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/sign_in.mustache#L4-L10

Polish and some other languages use different form for active elements like buttons and links than for  headers or titles.

![img_4088](https://cloud.githubusercontent.com/assets/1074871/10262719/10e18b44-69d4-11e5-91c9-b1ab29347a91.png)

**Comment by shane-tomlinson** [comment]
@splewako - We want to understand the request better because cross-language nuances are hard to comprehend when your native language doesn't have the concept.

Is "Sign in" in the header is different to "Sign in" when used as an imperative, like on the button?

**Comment by splewako** [comment]
> Is "Sign in" in the header is different to "Sign in" when used as an imperative, like on the button?

Yes, as general rule imperative strings shouldn't be used as titles/headers, some locales use nouns for titles, and verbs for actions (for example button labels).

This may not be that visible on a webpage but for example in Firefox OS we often have different forms for settings item label (first) activating settings view with some title/header (second) and submit button (third) while en-US has only one form.

**Comment by shane-tomlinson** [comment]
Thanks @splewako - do you know of any resources where we could find out more about best practices?

**Comment by splewako** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices

Asking l10n-drivers team or on l10n irc channel would be also good idea.

**Comment by vladikoff** [comment]
@mathjazz did you ever have to deal with this type of issue?

**Comment by mathjazz** [comment]
Yeah, title and button should be separate strings. You will have to use msgctxt to have two different entries with the same msgid in the PO file:
https://developer.mozilla.org/en-US/docs/gettext#Using_context_with_msgctxt

**Comment by vladikoff** [comment]
@zaach @shane-tomlinson we need to chat about getting the context value into our strings.

@zaach for .mustache templates does this make sense:

before:
```
{{#t}}Create a Firefox Account{{/t}}
```
after:
```
{{#t context=''header"}}Create a Firefox Account{{/t}}
```
This should extract as:

```
#: app/scripts/templates/sign_up.mustache:1
#: app/scripts/templates/sign_up.mustache:4
msgctxt "header"
msgid "Create a Firefox Account"
msgstr ""
```

I'm not sure what to do with `t(..)` helpers. From docs: https://github.com/zaach/jsxgettext#jsxgettext-- it seems plural forms will get into the way of the context values. 

Ideas?

Ref: https://github.com/zaach/jsxgettext

**Comment by zaach** [comment]
It looks like there's an open jsxgettext issue for contexts:
https://github.com/zaach/jsxgettext/issues/94

Ref:
http://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html
(scroll to --keyword=keywordspec)

On Wed, Nov 11, 2015 at 11:29 AM, Vlad Filippov <notifications@github.com>
wrote:

> @zaach <https://github.com/zaach> @shane-tomlinson
> <https://github.com/shane-tomlinson> we need to chat about getting the
> context value into our strings.
>
> @zaach <https://github.com/zaach> for .mustache templates does this make
> sense:
>
> before:
>
> {{#t}}Create a Firefox Account{{/t}}
>
> after:
>
> {{#t context=''header"}}Create a Firefox Account{{/t}}
>
> This should extract as:
>
> #: app/scripts/templates/sign_up.mustache:1
> #: app/scripts/templates/sign_up.mustache:4
> msgctxt "header"
> msgid "Create a Firefox Account"
> msgstr ""
>
> I'm not sure what to do with t(..) helpers. From docs:
> https://github.com/zaach/jsxgettext#jsxgettext-- it seems plural forms
> will get into the way of the context values.
>
> Ideas?
>
> Ref: https://github.com/zaach/jsxgettext
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/fxa-content-server/issues/3128#issuecomment-155835743>
> .
>



-- 
Zach Carter

**Comment by vladikoff** [comment]
We need to patch everything for this. 

https://github.com/zaach/jsxgettext-recursive should be looking for handlebars attributes. pass them on to the templates and we also need to adjust our translation function to make sure it picks up the right string based on its context (from json??)

**Comment by vladikoff** [comment]
from talking to @zaach:

for 

`{{#tc context="header"}}Create a Firefox Account{{/tc}}` we should be able to get the attrs with the handlebars parser.

For js strings , we need to add another helper for strings that have context and it might look like something like this:

`tc('hi', 'header')` -> for strings with context 
`t('hi')` -> for strings with no context

**Comment by shane-tomlinson** [comment]
> tc('hi', 'header') -> for strings with context
> t('hi') -> for strings with no context

`context` is pretty overloaded when it comes to l10n. `context` here is used to mean "where is this string used?" `context` [in views.js means "the data used for string interpolation"](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/base.js#L196). For our own sanity, let's decide on standardized nomenclature and use distinct names for these two concepts. If we have to update the name of the thing we currently call `context`, so be it.

Second, are we 100% positive `context` is only ever going to be a string? Could it ever be a number/object/something-more-complex?

**Comment by zaach** [comment]
> Second, are we 100% positive context is only ever going to be a string? Could it ever be a number/object/something-more-complex?

xgettext-like tools will expect a string literal.

**Comment by vladikoff** [comment]
Another contributor sent a related messages to this:

```
Hi Vlad, 

Could you clarify what is the context of the string "(current)"? I 
assume there would be an implied noun or similar to go along with it? 

Also, I don't know if there are technical limits or if this has been 
discussed before, but it'd be very helpful if partial strings like this 
one had comments in .po file that translators could see in their tools. 

Merike 
```

**Comment by shane-tomlinson** [comment]
\*/
