### ISSUE TITLE
Redirect ineligible users from the _complete screens to an auth screen.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3133]
Follow on from #3094.

@vladikoff [pointed out](https://github.com/mozilla/fxa-content-server/pull/3094#discussion_r40964066) during his review that the `_complete` screens do not check whether the user is eligible to be on that screen. We should do so.

[More context copied over](https://github.com/mozilla/fxa-content-server/pull/3094#discussion_r40998111):

> `account_unlock_complete`, `force_auth_complete`, `reset_password_complete` and `signin_complete` can all check the user's status since the user should have a `sessionToken` (or so we say at this point in time). `signup_complete` may not have a `sessionToken` if the user verifies in a second browser - the 1st browser shows `signup_complete` after `confirm` but has no `sessionToken` while the second browser receives the `sessionToken`.

**Comment by vladikoff** [comment]
This seems outdated, we are changing these screens at the moment with multi-device work...
