### ISSUE TITLE
Screen rotation zooms FxA layout in iOS Firefox

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3134]
Normal view on latest:
![2015-10-05 09 37 26](https://cloud.githubusercontent.com/assets/68213/10285705/087c6d0e-6b58-11e5-853f-44b49f5d0270.png)

When rotated 90°:
![2015-10-05 09 37 50](https://cloud.githubusercontent.com/assets/68213/10285713/12c509a6-6b58-11e5-809c-3371a082afee.png)

How I feel about this:
![2015-10-05 09 37 50 copy](https://cloud.githubusercontent.com/assets/68213/10285730/26ac9d1c-6b58-11e5-8e50-f05b16728fd7.png)

**Comment by vladikoff** [comment]
cc @johngruen

**Comment by johngruen** [comment]
@vladikoff @ryanfeeley WHYYYYYYY????

**Comment by johngruen** [comment]
@ryanfeeley i'm going to propose that this isn't an issue with FXA, but may be an Firefox on iOS. Here's the deal: 
- this only happens if you have previously zoomed in or out on settings in portrait mode
- this doesn't happen on iOS safari or Chrome

**Comment by johngruen** [comment]
@ryanfeeley I was able to reproduce this bug in other websites on FFiOS, closing this bug and bringing it up to the mobile testers list.
