### ISSUE TITLE
Enable the "Sync preferences" button from the verification page for Fennec

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3140]
Currently we only show the "Sync preferences" button in the signup tab, but it would probably be more useful on the verification page because that's where the user is.

The "Sync preferences" button should be shown on the verification page if:
1) The user verifies in the same browser that they signed up in.
2) The same user is verifying as signed up.

Ref #2771

**Comment by vladikoff** [comment]
@shane-tomlinson and me to talk about this....

**Comment by vladikoff** [comment]
@shane-tomlinson do we need to add this to the resume token?

**Comment by shane-tomlinson** [comment]
@vladikoff - I was mulling this over last week because I was gonna do it this week. You beat me to tagging it with your head. :D We currently store oauth verification info in Session.oauth, which we know has some problems (#1506). I think we can possibly kill two birds with one stone by storing verification info into localStorage keyed by user id, instead of client_id as proposed in #1506. A user should be signing up for one relier at a time (yeah, there are edge cases where they could have two tabs open to two reliers, but really, do we care?). We can store verification info into localStorage like:

```js
verificationInfo: {
  <userid_1>: {
    context: <context>,
    some_other_meta_info: {}
  },
  <userid_2>: {
    context: <another_context>,
    some_other_meta_info: {}
  }
}
```

When the user verifies, if their user id is in localStorage.verificationInfo, then we know they are verifying in the same browser. We can pull out the context, know the user started with Fennec, know they are finishing with Fennec, establish the WebChannel, and send the message.

**Comment by vladikoff** [comment]
>  You beat me to tagging it with your head. :D

I assigned myself to triage this with you. 

>I think we can possibly kill two birds with one stone by storing verification info into localStorage keyed by user id, instead of client_id as proposed in #1506. A user should be signing up for one relier at a time (yeah, there are edge cases where they could have two tabs open to two reliers, but really, do we care?).

Yeah we don't care about the 2 open tab case (We had another bug open regarding this but closed it)

The approach sounds good.  @shane-tomlinson, I feel like you already thought this through more than I did and you can take this issue. If not then reassign this to me and I'll take a look

**Comment by rfk** [comment]
> there are edge cases where they could have two tabs open to two reliers, but really, do we care?

I don't care as long as we can error out cleanly in one of them.  I would care if we had weirdness like one relier receiving the login state intended for another relier.  Although harmless, it's the sort of thing that could freak users/reliers out.
