### ISSUE TITLE
Fennec flow needs functional tests for reset password

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3147]
See https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA

**Comment by vladikoff** [comment]
@shane-tomlinson and @vladikoff to talk about this..

**Comment by vladikoff** [comment]
Closing for now until this is needed or has some specific features
