### ISSUE TITLE
Fennec flow needs function tests for account unlock

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3148]
See https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquoh

**Comment by vladikoff** [comment]
Removing milestones, moving to just `tests`

**Comment by shane-tomlinson** [comment]
Killing until Fennec acts differently to other brokers, otherwise we are adding more work for ourselves and more code to maintain.
