### ISSUE TITLE
profile oauth tokens not destroyed from settings page.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3154]
When the settings page is loaded, two OAuth tokens are created, only one is destroyed.

I believe the Basket token is destroyed whereas the profile token is not. 

@rfk - While I was working on Basket, you stressed we should clean up our OAuth tokens when done with them. What do you think a reasonable approach is here where the user may need to perform several actions that require an OAuth token - is it better to reuse the same one, or destroy immediately after use and generate a new one when required?

![screen shot 2015-10-09 at 13 57 03](https://cloud.githubusercontent.com/assets/848085/10394256/d8b798f8-6e8d-11e5-96e0-5ee784ddc997.png)

ref #3053

**Comment by rfk** [comment]
Cleaning up tokens is much less critical now that @seanmonstar's refresh-tokens work has landed, these tokens now have expiry times and can be purged on the backend without the client having to do an explicit cleanup.  I suggest issuing just a single token, taking note of its expiry time, and using it until it expires.

(Of course, you may require different scopes for different operations, in which case you should probably request different tokens, but that's another story...)

**Comment by shane-tomlinson** [comment]
> (Of course, you may require different scopes for different operations, in which case you should probably request different tokens, but that's another story...)

That's what we are doing here, one token is for Basket to consume, the other for the content server.

**Comment by rfk** [comment]
I think it's The Right Thing to use two separate tokens for this, one for the profile data and one for basket.  Probably nothing bad would happen if we used a combined token for both, but we should set a good example w.r.t. oauth hygiene and keeps things with separate scopes separate.

@shane-tomlinson it's not clear to me whether I've answered your questions here or not, but attempting to summarize:

* use different tokens when you need different scopes
* feel free to keep tokens around until they expire and re-use them for requests that require the same set of scopes

**Comment by shane-tomlinson** [comment]
Thanks @rfk. It sounds like we are doing the right thing then. Closing as INVALID.
