### ISSUE TITLE
 'Old password' pre-filled in accounts.firefox.com/settings/change_password

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3161]
Raising this from https://bugzilla.mozilla.org/show_bug.cgi?id=1213812

1. Go to accounts.firefox.com and sign in with a valid account
2. Go to accounts.firefox.com/settings/change_password

Result: The 'Old password' input field is pre-filed with your current password

**Comment by shane-tomlinson** [comment]
Ref #3034

**Comment by shane-tomlinson** [comment]
#3039 did not go far enough to ensure the formPrefill information *stays* cleared once the view is destroyed. Each view's `beforeDestroy` handler re-fills the formPrefill model with data right after the model was cleared.

**Comment by shane-tomlinson** [comment]
> #3039 did not go far enough to ensure the formPrefill information stays cleared once the view is destroyed. Each view's beforeDestroy handler re-fills the formPrefill model with data right after the model was cleared.

I was wrong here, we *do* clear formPrefill information after signing in. The issue here seems to be with the password manager rather than anything we are doing incorrectly.

**Comment by shane-tomlinson** [comment]
My comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1213812#c4

> I have the password manager disabled and am unable to reproduce the behavior mentioned here against either accounts.firefox.com or the local development environment. When I use a fresh profile with the password manager enabled, the "old password" is pre-filled. As :nalexander mentions, I believe this is the expected behavior with the password manager enabled.
> 
> :rfk what do you think?

@rfk

**Comment by rfk** [comment]
Agreed, this sounds like expected password-manager behaviour, let's close it out
