### ISSUE TITLE
main in jQuery b is null

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3162]
Seeing a few of these errors since Train 46:
```
main in jQuery
b is null
```

Sentry ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/group/112091/

![image](https://cloud.githubusercontent.com/assets/128755/10459074/e3fa5ec4-719b-11e5-9575-d500f3c4acfc.png)

**Comment by shane-tomlinson** [comment]
Now that you point it out, I've seen similar when testing the settings screen names, something with $.modal was blowing up.

**Comment by rfk** [comment]
This issue has been hanging out at the bottom of "next" for quite a while; @vladikoff I don't see it anymore when browsing sentry and the linked graph looks like it's at zero, perhaps this has been resolved in the meantime?

**Comment by vladikoff** [comment]
Woah you are right! Fixed :D
