### ISSUE TITLE
"Learn More" on the /cannot_create_account does not work in FxiOS

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3164]
![image](https://cloud.githubusercontent.com/assets/128755/10464367/7680a364-71b7-11e5-92c6-11cd81e29bf5.png)

This is an external link that cannot be opened in the FxiOS Sync context
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1213210#c3

**Comment by shane-tomlinson** [comment]
I think the appropriate action here is to do the same thing we do in the TOS/PP agreements and show the link's href next to the learn-more text. @ryanfeeley, @johngruen, thoughts?

**Comment by johngruen** [comment]
seems legit

**Comment by vladikoff** [comment]
from mtg: check the context instead of browser sniffing for this

**Comment by ryanfeeley** [comment]
seems smart enough.

**Comment by vladikoff** [comment]
@ryanfeeley @shane-tomlinson thoughts: 

![image](https://cloud.githubusercontent.com/assets/128755/10587108/a1aeafda-766d-11e5-9db1-e2f41f3a938b.png)
 

?

**Comment by vladikoff** [comment]
After irc discussion with @ryanfeeley , we are making changes to the link style. Approved view:

![](http://v14d.com/i/56253b926bdb9.jpg)

bottom - old design,  top - new design
![](http://v14d.com/i/56253ae1c533e.jpg)

**Comment by ryanfeeley** [comment]
👍

**Comment by shane-tomlinson** [comment]
@ryanfeeley - in https://github.com/mozilla/fxa-content-server/issues/3164#issuecomment-149311406, should we shrink the space between "Cannot create account" and "You must meet certain..."? Not needed for this PR, we can open a new issue.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Well spotted. Yes, it should probably match the space other other dead-end messages like cookies required (looks like 24px bottom margin on h1, no top padding on section)
![screenshot 2015-10-20 10 30 51](https://cloud.githubusercontent.com/assets/68213/10610414/b3653868-7715-11e5-8464-cdde9e3476d4.png)

**Comment by shane-tomlinson** [comment]
Oh, there's a link on `/cookies_disabled` too, we should check that in Fx for iOS to see if that needs this update too.

**Comment by AaronMT** [comment]
This is still an issue.

**Comment by vladikoff** [comment]
> This is still an issue; the link is merely not hyperlinked.

By design, we cannot hyperlink it because we cannot navigate away in that view.

**Comment by AaronMT** [comment]
I see, I must be remembering the Android view. Thanks for clarifying.
