### ISSUE TITLE
Display name not updated in all tabs on account update.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3170]
STR
1. In the same browser, sign in and open two tabs to `/settings`
2. In tab A, change the display name
3. Check for the change in tab B. The display name is not updated.
4. Now try the same thing with an avatar. The avatar is updated.

Found while developing #3092. Ref #2164 where the profile image was not being synced across tabs.

**Comment by vladikoff** [comment]
from mtg: good first bug, look at how avatar is updated and do the same

**Comment by vladikoff** [comment]
Nobody good-first-bugged this for a year :( , reopen if we still need this....
