### ISSUE TITLE
"Choose what to sync" design refresh

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3183]
from @ryanfeeley:

![image](https://cloud.githubusercontent.com/assets/128755/10552016/e706d7ca-741e-11e5-939d-3aea615aa8f3.png)

**Comment by vladikoff** [comment]
Not sure about 2x2 layout for "Desktop preferences" and the mobile layout.

**Comment by vladikoff** [comment]
The extra drop shadow was in the latest high quality image that right gave us here: https://github.com/mozilla/fxa/issues/18#issuecomment-145631542

**Comment by ryanfeeley** [comment]
Here is an improved shadow. What exact width do you need? I can build it for that size (don't scale this one down). ![keynote-to-the-rescue](https://cloud.githubusercontent.com/assets/68213/10552187/1813cec6-7420-11e5-90ca-98ca1749eee1.png)

**Comment by shane-tomlinson** [comment]
> Not sure about 2x2 layout for "Desktop preferences" and the mobile layout. 

2x2 is also brittle with "long" languages like German and Swedish.

**Comment by shane-tomlinson** [comment]
The sub-header color is the default, an update would cause an inconsistency with other locations in the site. I vote for consistency.

I used `Cancel` because we have `Cancel` almost everywhere else where a secondary button is presented:

```
➜  templates git:(master) rgrep "Cancel" *
choose_what_to_sync.mustache:      <a href="#" id="back">{{#t}}Cancel{{/t}}</a>
permissions.mustache:      <li><a href="#" id="back">{{#t}}Cancel{{/t}}</a></li>
settings/avatar_camera.mustache:        <button class="settings-button secondary" id="back">{{#t}}Cancel{{/t}}</button>
settings/avatar_crop.mustache:        <button class="settings-button secondary" id="back">{{#t}}Cancel{{/t}}</button>
settings/avatar_gravatar.mustache:        <button class="settings-button secondary" id="back">{{#t}}Cancel{{/t}}</button>
settings/change_password.mustache:        <button class="settings-button secondary cancel">{{#t}}Cancel{{/t}}</button>
settings/communication_preferences.mustache:        <button class="settings-button secondary cancel unpaired">{{#t}}Cancel{{/t}}</button>
settings/communication_preferences.mustache:        <button class="settings-button secondary cancel">{{#t}}Cancel{{/t}}</button>
settings/delete_account.mustache:        <button class="settings-button secondary cancel">{{#t}}Cancel{{/t}}</button>
settings/display_name.mustache:        <button class="settings-button secondary cancel">{{#t}}Cancel{{/t}}</button>
settings/gravatar_permissions.mustache:        <button class="settings-button secondary" id="back">{{#t}}Cancel{{/t}}</button>
test_template.mustache:    <button type="submit" class="cancel">Cancel</button>
```
-----------------------
```
➜  templates git:(master) rgrep "Back" *
confirm_account_unlock.mustache:      <a id="back" class="left" href="#">{{#t}}Back{{/t}}</a>
pp.mustache:    {{#canGoBack}}
pp.mustache:        <button id="fxa-pp-back" class="back">{{#t}}Back{{/t}}</button>
pp.mustache:    {{/canGoBack}}
reset_password.mustache:    {{#canGoBack}}
reset_password.mustache:        <a id="back" href="#">{{#t}}Back{{/t}}</a>
reset_password.mustache:    {{/canGoBack}}
test_template.mustache:      <button type="submit" id="back">Back</button>
tos.mustache:    {{#canGoBack}}
tos.mustache:        <button id="fxa-tos-back" class="back">{{#t}}Back{{/t}}</button>
tos.mustache:    {{/canGoBack}}
➜  templates git:(master)
```

Again, I vote for consistency.

**Comment by ryanfeeley** [comment]
Valid arguments, I just don't like finding out you have made these decisions after it has shipped. I'll be working a formal UI review into our process from now on.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - it looks like `Cancel` is primarily used in the settings, aside from Permissions and Choose what to Sync. Should we change both of those to `Back`?

**Comment by ryanfeeley** [comment]
Related: https://github.com/mozilla/fxa/issues/18

**Comment by ryanfeeley** [comment]
Could the datatypes be in two columns but only one column if the strings were two long? Something like min-width: 50%? @johngruen may know.

**Comment by shane-tomlinson** [comment]
> Could the datatypes be in two columns but only one column if the strings were two long? Something like min-width: 50%? @johngruen may know.

This seems like a job for [flex-box](https://developer.mozilla.org/en-US/docs/Web/CSS/flex?redirectlocale=en-US&redirectslug=CSS%2Fflex).

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/3139#issuecomment-149874678

**Comment by vladikoff** [comment]
@ryanfeeley you asked me yesterday about the resolution for the new image:

We need 2 images here:
https://github.com/mozilla/fxa-content-server/blob/master/app/images/choose_what_to_sync_devices.jpg
https://github.com/mozilla/fxa-content-server/blob/master/app/images/choose_what_to_sync_devices%402x.jpg

300x165 and 600x330

You can send them as a PR or provide a link here so we can update them :smile:

**Comment by billmaggs** [comment]
We're planning to sync Add ons as well as Prefs? These are Web Extensions?

**Comment by vladikoff** [comment]
@billmaggs We are planning to give those options only in Desktop, see work in progress screenshot here: https://github.com/mozilla/fxa/pull/65#issuecomment-150651204
