### ISSUE TITLE
Excessive whitespace between header and content in `/cannot_create_account`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3199]
Current (using context=fx_ios_v1):

![image](https://cloud.githubusercontent.com/assets/128755/10587108/a1aeafda-766d-11e5-9db1-e2f41f3a938b.png)

@ryanfeeley [says it should look more like `/cookies_disabled`](https://github.com/mozilla/fxa-content-server/issues/3164#issuecomment-149585682):

![screenshot 2015-10-20 10 30 51](https://cloud.githubusercontent.com/assets/68213/10610414/b3653868-7715-11e5-8464-cdde9e3476d4.png)

> (looks like 24px bottom margin on h1, no top padding on section)

**Comment by vladikoff** [comment]
To get to `/cannot_create_account` just enter an age < 12 on the sign up form
To clear cookies go to the `/clear` route, then will let you sign up again.
