### ISSUE TITLE
/cookies_disabled contains an external link, cannot be opened in Fx for iOS

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3200]
Not sure if Fx for iOS users can disable cookies when signing up for Sync, but we should be consistent with the approach taken in #3164 on the COPPA page.

![screenshot 2015-10-20 10 30 51](https://cloud.githubusercontent.com/assets/68213/10610414/b3653868-7715-11e5-8464-cdde9e3476d4.png)

**Comment by vladikoff** [comment]
No way to disable cookies, and even if Safari cookies are disabled sign in still works:

![](http://v14d.com/i/56265720600c4.jpg)
