### ISSUE TITLE
Allow display name to use emojis like 🚲✨☕️✨

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3208]
So that I can express myself more uniquely and humorously, as an account holder user, I want to be able to use emojis in my display name on the web and in Firefox.

**Comment by bwinton** [comment]
✨☕️✨ works, but everything after 🚲 gets cut off for no apparent reason…

**Comment by rfk** [comment]
Server-side validation code is here for reference:

  https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/display_name/post.js#L10

Maybe it's being accidentally triggered by the bicycle and we need to tweak it.

**Comment by rfk** [comment]
Marking this good-first-bug, I think the right way to start is to add a testcase in [1] and see whether that passes or fails, and we can find the right place to put the fix from there.

[1] https://github.com/mozilla/fxa-profile-server/blob/master/test/api.js#L805

**Comment by bwinton** [comment]
If it helps, the character info for bicycle is:
> 🚲
> Bicycle
> Unicode: U+1F6B2, UTF-8: F0 9F 9A B2

**Comment by rfk** [comment]
This is definitely being stripped by profile-server:

```
>>> requests.post("https://profile.accounts.firefox.com/v1/display_name", u"{\"displayName\": \"rfkelly \U0001F6B2 sparkle\"}".encode("utf8"), headers={"Authorization": AUTHZ})
<Response [200]>
>>> requests.get("https://profile.accounts.firefox.com/v1/display_name", headers={"Authorization": AUTHZ}).content
'{"displayName":"rfkelly "}'
```

So I'm going to migrate it to that repo.

**Comment by rfk** [comment]
Closing in favour of https://github.com/mozilla/fxa-profile-server/issues/186
