### ISSUE TITLE
Don't show session expired error when entry point is about:preferences

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3222]
Our suggested account view contains all the context a user needs to proceed. We don't need to show session expired error when entry point is about:preferences.

<img width="1030" alt="whatsgoingonhere" src="https://cloud.githubusercontent.com/assets/68213/10766696/0415fd1c-7caf-11e5-9d85-6bc15452abbe.png">

**Comment by rfk** [comment]
@ryanfeeley how similar is this issue to what's described in https://github.com/mozilla/fxa-content-server/issues/3410, e.g. would getting rid of this "session expired" error be sufficient to fix the experience in #3410?

**Comment by rfk** [comment]
(Obviously it would be more awesome if you didn't have to re-enter your password at all in #3410, but I think that's a much bigger work item)

**Comment by vladikoff** [comment]
ping @ryanfeeley re: 

> @ryanfeeley how similar is this issue to what's described in #3410, e.g. would getting rid of this "session expired" error be sufficient to fix the experience in #3410?

**Comment by vladikoff** [comment]
from mtg: From visual point of view Don't display the error "Session Expired". #3410 looks like the same thing ....
