### ISSUE TITLE
FxA based Channels exposes `send`, Backbone.Events exposes `trigger`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3228]
We should unify, I propose standardizing on `trigger`.

@philbooth ?

**Comment by philbooth** [comment]
I concur!

**Comment by philbooth** [comment]
Putting this back on to the backlog, sorry.

I tried to make the change but broke a bunch of stuff because `BaseChannel` extends `Backbone.Events`, so my change clobbered Backbone's `trigger` implementation.

**Comment by vladikoff** [comment]
from mtg: not gonna do this due to different return types in `send` vs `trigger`...
