### ISSUE TITLE
crosstab/InterTabChannel invokes callbacks with an event, Backbone.Events invokes callbacks w/ passed in data.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3229]
crosstab invokes callbacks w/ an event that contains an `event` and `data` field. Backbone.Events invokes callbacks w/ the data passed to the `trigger` function. We should unify on the Backbone.Events way of doing things.

ref #3228 

@philbooth - thoughts?

**Comment by philbooth** [comment]
Again I concur!
