### ISSUE TITLE
Inconsistent styling between input and select fields text color

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#323]
### Steps to reproduce:
1. Go to https://accounts-latest.dev.lcip.org/signup
2. Enter a email, password, and date of birth.
3. Compare the text color in the `<input>` fields vs the `<select>` field.

### Actual results
The text in the `<select>` field is gray (#C0C9D0 ?):
![firefox_accounts](https://f.cloud.github.com/assets/557895/1989496/d7187abe-8477-11e3-83bb-7b876f5075fe.png)

The text in the `<input>` is black-ish (#454F59).

### Expected results:
The input and select fields should have consistent styles. It doesn't look like the `<select>` tag supports a similar `placeholder` attribute and this gets kind of ugly pretty quick since styling `<option>` values directly only seems to work when the select menu is open.

(see PR #315 for more comments)

---

![firefox_accounts](https://f.cloud.github.com/assets/557895/1989512/07739f54-8478-11e3-8200-24e1b551668f.png)

**Comment by shane-tomlinson** [comment]
I claim this is fixed.

![screen shot 2015-04-29 at 16 44 12](https://cloud.githubusercontent.com/assets/848085/7394987/0996f182-ee8f-11e4-8f16-6b4cbe797dee.png)

Closing.
