### ISSUE TITLE
auth_brokers/base.js->canCancel should be a capability

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3235]
See https://github.com/mozilla/fxa-content-server/blob/1203582cb33420c5ad03216b33b1fc774c933372/app/scripts/models/auth_brokers/base.js#L90-L95

**Comment by divyabiyani** [comment]
Hi @shane-tomlinson I want to work on this bug.
Could you please expain me what do u mean by capability here?

**Comment by vladikoff** [comment]
@divyabiyani You need to move the `canCancel` function and move it into capabilities 

https://github.com/mozilla/fxa-content-server/blob/1203582cb33420c5ad03216b33b1fc774c933372/app/scripts/models/auth_brokers/base.js#L275
