### ISSUE TITLE
url: https://accounts.firefox.com/scripts/<checksum>.main.js is a fat baby

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3242]
url: https://accounts.firefox.com/scripts/<checksum>.main.js

That's currently 615KB in size (213KB with gzip), which if I recall correctly is more than in the past, and even at 500KB is a good size chunk. Can we audit the contents to see if there are any available savings.

**Comment by shane-tomlinson** [comment]
ref #1461

**Comment by pdehaan** [comment]
See also:
- https://github.com/mozilla/fxa-content-server/issues/1461
- https://github.com/mozilla/fxa-content-server/issues/3015

**Comment by vladikoff** [comment]
Fixed via ^ above commits

<img src=https://media.giphy.com/media/14kqI3Y4urS3rG/giphy.gif width=150 />

**Comment by shane-tomlinson** [comment]
We're getting there... Slowly but surely.
