### ISSUE TITLE
Support "Disconnect" using WebChannels from the content server to Firefox Desktop

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3252]
Send WebChannel messages to the browser on FxA initiated actions:
* disconnect current device
* update current device name

Accept WebChannel messages from the browser for browser initiated actions:
* update current device name
* update current device ID
* user sign out.

Possibly:
* handshake to determine browser's currently authenticated user state.

Part of https://github.com/mozilla/fxa-content-server/issues/3250

**Comment by vladikoff** [comment]
Reorganizing this a bit:

Send WebChannel messages to the browser on FxA initiated actions:

**disconnect current device**
~~update current device name~~

Accept WebChannel messages from the browser for browser initiated actions:

**update current device name** - When name is updated in browser, tell the content server to refresh.
~~update current device ID~~
~~user sign out.~~

**Comment by vladikoff** [comment]
We landed a descoped version of this. follow up to discuss here: https://github.com/mozilla/fxa-content-server/issues/3308
