### ISSUE TITLE
Improve copy for proposed email change 

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3260]
@mozmatej

When a user wants to change their email, they have to first provide a new email address and then verify it. Until they verify the email, their Firefox Account settings should reflect that their account email is in flux, and that they need to verify it using the link in the email, or cancel the change request altogether.

Mozilla add-ons does this (but lacks a way to resend the email or cancel the request):
![amo-change-email](https://cloud.githubusercontent.com/assets/68213/10947277/1af6dd34-82f5-11e5-898b-e8aab1958970.png)

And this is the draft treatment copy I'd love for you to improve (links included):
<img width="562" alt="change-email" src="https://cloud.githubusercontent.com/assets/68213/10947301/3508c5c0-82f5-11e5-8355-d89d0bcba2c1.png">

**Comment by ryanfeeley** [comment]
And for context, it will appear after they fill out and submit this section: 
![change-email-expanded](https://cloud.githubusercontent.com/assets/68213/10947368/88b380c0-82f5-11e5-9907-8dc751ab604f.png)

**Comment by MozMatej** [comment]
I would make it: "Your account email will change to second@email.com once you confirm it."

**Comment by ryanfeeley** [comment]
Beautiful, much better, thanks!!!
