### ISSUE TITLE
Show communication preferences for all en-* dialects

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3266]
Users whose browser reports en-GB, en-CA or other non-en-US english dialects will not see the "communication preferences" option in the settings page, and I assume will not see the "get the latest news and tips" opt-in either.  Should we just open this up to en-* or do we have plans to one-day provide translated content for these other locales?

I'll ask the engagement team to weigh in on this one.

(Am I opening a geo-political can of worms here?)

**Comment by bniolet1** [comment]
No flags from me. When we send email to EN, it's global EN anyway. So if we open it to other non-us locales, we're good as long as they're EN

**Comment by vladikoff** [comment]
I think the change should be in https://github.com/mozilla/fxa-content-experiments/blob/dev/communication-prefs/communication-prefs.js
