### ISSUE TITLE
New inter-tab notification logic interacts badly with browser state

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3267]
Over in https://github.com/mozilla/fxa-content-server/pull/3232 we refactored our inter-tab state synchronization to use the "notifications" abstraction, and there was much rejoicing.  As a result, our state-syncing events are now sent out over the WebChannel channel, which means they're now received and acted on by the browser.

Unfortunately, I don't think the browser is really prepared for that interaction, and it can cause things to get weird.

One example is https://github.com/mozilla/fxa/issues/76, where the browser now receives a duplicate webchannel-based "fxaccounts:login" message which causes it to destroy its existing good login state.  

There may be other edge-cases, such as this new "fxaccounts:logout" message causing the browser to throw away login state:  https://github.com/mozilla/fxa-content-server/commit/ecebd942ee5672198d308d453982aae9f2b8f01f#diff-f6f26d253984759fd1ff90518fbcde33R157

IIUC the general problem here is, we were previously broadcasting *global* events that affect the state of the account itself, like "profile changed" and "account deleted".  We're now broadcasting *local* events about the state of the application, not the state of the account.  And they're being picked up by something that has a different notion of how to manage that state.

I'm not sure what the best option is here, but I think we need to backoff from some of these changes until the browser is prepared to handle them.  Perhaps we can just avoid sending app-state-related messages over webchannels for the time being?

**Comment by rfk** [comment]
I had hoped we might be able to unblock train-49 by just removing the broadcast of SIGNED_IN and SIGNED_OUT events, since AFAICT they're all new after the linked PR and so we shouldn't break any existing behavior.  But I noticed that we add another one in [1] that replaces some existing cross-tab signally, and I wasn't comfortable about just removing that.

So I'm going to stop poking at this and leave it for @shane-tomlinson and @philbooth to weigh in on.

[1] https://github.com/mozilla/fxa-content-server/pull/3233/files#diff-10f1d562f7d1fbb313ab0b7219f873c1L123

**Comment by philbooth** [comment]
That's interesting, I was worried something like this might happen and originally chose event names that didn't clash with anything already in use. [Changing that to re-use existing event names happened quite late in the review process](https://github.com/mozilla/fxa-content-server/pull/3232#discussion-diff-43509399), so it is an easy switch to go back to what I had before. Will PR and get @shane-tomlinson to review it this morning.

**Comment by rfk** [comment]
OK, SGTM :-)

FWIW I really like the approach with the merged notifications and a single set of consistent events, hopefully we can get back to that state once we have a better story for syncing between browser state and web content.

**Comment by vladikoff** [comment]
Released in https://github.com/mozilla/fxa-content-server/releases/tag/v0.49.3
