### ISSUE TITLE
Don't broadcast webchannel login events without a keyFetchToken?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3268]
Over in the fxa-sync auth broker we have a bit of code [1] that prevents us partial account state to the browser.  If there's no keyFetchToken on the account data, we know the browser will freak out so we don't send it along.

Should we do something similar for any "fxaccounts:login" messages going out via WebChannels?  We don't have a good way to detect "the browser freaks out" as a failure mode in our automated testing, so this might be a worthwhile stopgap to prevent bugs like https://github.com/mozilla/fxa/issues/76.

[1] https://github.com/mozilla/fxa-content-server/blob/327d67ded5ae1d738fbb1b5e4264038a2bed7c64/app/scripts/models/auth_brokers/fx-sync.js#L190

**Comment by shane-tomlinson** [comment]
> Should we do something similar for any "fxaccounts:login" messages going out via WebChannels?

That `fxaccounts:login` message should only be sent over the web channel IFF using a Sync broker. This problem exists because of #3267 and will go away once that is fixed.

**Comment by vladikoff** [comment]
There should be no more webchannel events without the keyfetchtoken, those were fixed.
