### ISSUE TITLE
Choose what to Sync and COPPA interacted badly (in Fennec)

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#3275]
STR:
1) typo your age (2 instead of 22);
2) get COPPA blocked.
3) try again.
4) Observe COPPA block *after* Choose what to Sync page.
I just tried to repeat these STR and did not see unusual behaviour.  Something transitory, perhaps?  Filing in case I see it again.

**Comment by vladikoff** [comment]
> 3) try again.
4) Observe COPPA block after Choose what to Sync page.

These steps are unclear, I could not reproduce it here. 
Once you get COPPA blocked, the only way to get rid of it is to clear your data and try to sign up again.

**Comment by vladikoff** [comment]
I tried to reproduce this again but was not able to. Let us know if you see this again or someone else reports this. Thanks!
