### ISSUE TITLE
"I got the attached message - which still stays Firefox of iOS coming soon"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3280]
Report issue with our marketing snippet

**Comment by vladikoff** [comment]
New view:

![image](https://cloud.githubusercontent.com/assets/128755/11128321/22c9c708-8947-11e5-9be7-ed9ac62a80fd.png)

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
:+1:
