### ISSUE TITLE
views/marketing_snippet.js is no longer used, should be removed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3284]
[views/marketing_snippet.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/marketing_snippet.js) was deprecated by views/marketing_snippet_ios.js on June 2nd of 2015. It still takes up space in our codebase, and minds, as well as user downloads. We should remove it and save users a kb.

Note to contributors interested in taking on this issue, you'll also have to remove left-over references [in ready.js](https://github.com/mozilla/fxa-content-server/blob/6a4c81a4f4067b64307adff038be97fe3d71118f/app/scripts/views/ready.js#L16), the [unit test setup](https://github.com/mozilla/fxa-content-server/blob/6a4c81a4f4067b64307adff038be97fe3d71118f/app/tests/test_start.js#L103), the [unit test itself](https://github.com/mozilla/fxa-content-server/blob/6a4c81a4f4067b64307adff038be97fe3d71118f/app/tests/spec/views/marketing_snippet.js), and possibly in [fxa-content-experiments](https://github.com/mozilla/fxa-content-experiments/blob/dev/spring-campaign-2015/spring-campaign-2015.js) once the content server patch has merged. There are probably other places that I'm missing too.

**Comment by shane-tomlinson** [comment]
As always, things are not as easy as they first appear. marketing_snippet.js is the base for marketing_snippet_ios.js. More thought on the approach needed.

**Comment by RPraneetha** [comment]
In that case, should the marketing.mustache file be removed too?

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
I'm doing this now to simplify the multi-device PR.
