### ISSUE TITLE
Fennec hits a bad media query when keyboard is enabled

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3288]
![](https://bug1224178.bmoattachments.org/attachment.cgi?id=8686575)

Read this for more information: http://robinosborne.co.uk/2014/09/12/android-browsers-keyboards-and-media-queries/

https://bugzilla.mozilla.org/show_bug.cgi?id=1224178

**Comment by johngruen** [comment]
oh boy, i thought I nuked any VH media queries...guess not :(

**Comment by vladikoff** [comment]
Cannot reproduce this anymore, closing for now...
