### ISSUE TITLE
Measure email bounces on password resets of valid accounts

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3295]
If users forget their passwords, they are up sh*t creek. If their emails bounce when they try to send a reset, they are also without a paddle. We need to do more for our lost users.

Is there anything we can do in terms of messaging? Search and rescue?

**Comment by rfk** [comment]
These metrics should be in datadog now, named `account.email_bounced.already_verified`.  I see a small but non-zero rate of these on the "fxa.auth.account.email_bounced" graph here:

  https://app.datadoghq.com/dash/67081/fxa-auth-server?live=true&page=0&is_auto=false&from_ts=1451880444376&to_ts=1454472444376&tile_size=m&fullscreen=false

Is the rate high enough for us to try to prioritize work on this?  We've talking about re-doing our flows around bounced emails for a while, transitioning these users into a "bounced" state from which they can dig themselves out is probably a good idea.

**Comment by rfk** [comment]
I'm closing this bug because the requested metrics are now available.  If we have something concrete we can do for this small-but-non-zero set of users, let's discuss in product planning and ramp it up as a feature card.

**Comment by ryanfeeley** [comment]
@rfk Excellent! If my math is right it looks like 7% of registrations bounce, and 1.3% of resets bounce.
<img width="698" alt="screenshot 2016-02-24 10 18 02" src="https://cloud.githubusercontent.com/assets/68213/13290028/1e48cde2-dae0-11e5-929d-946054db2ab9.png">
