### ISSUE TITLE
Permissions error following Docker instructions

### ISSUE THREAD

**Issue by michielbdejong** [mozilla/fxa-content-server#3298]
Following the [Docker instructions from the README](https://github.com/mozilla/fxa-content-server#docker-based-development), I get an error where npm tries to create `/opt/fxa/.npm`.

This is probably because the npm install command is [run as user fxa](https://github.com/mozilla/fxa-content-server#docker-based-development), whereas the folder mounted in from the host with `-v $PWD:/opt/fxa` option is owned root or some other user on the host.

Work-around:
````bash
$ docker build --rm -t mozilla/fxa_content_server .
$ chmod ugo+w .   #   <----------------
$ docker run --rm -v $PWD:/opt/fxa mozilla/fxa_content_server npm install
$ chmod ugo+w ./server/config/   #   <----------------
$ docker run -it --rm -v $PWD:/opt/fxa --net=host mozilla/fxa_content_server
````
But there might be a nicer solution?

**Comment by michielbdejong** [comment]
Ah, maybe I'll just try to create a Dockerfile for https://github.com/mozilla/fxa-local-dev and use that instead.

**Comment by vladikoff** [comment]
There are several challenges with Docker for FxA. 

What are you trying to accomplish?

If you are looking to something to DEV against, please use https://stable.dev.lcip.org/
If you are looking to contribute use https://github.com/mozilla/fxa-local-dev , that repo is not docker ready. There are issues making sure the verifier properly talks to the server docker VM.
We also welcome PRs to existing docker instructions, we do not use those Docker instructions for anything. You might also find this useful: https://github.com/mozilla/fxa-auth-server/pull/1033

**Comment by michielbdejong** [comment]
Thanks! I'm looking to self-host. Making some progress with fxa-local-dev now, will see if I can adapt that to use a real database, and then put an https offloader in front of it, on my personal domain name.
