### ISSUE TITLE
Add openid-connect-compatible discovery document

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3299]
The OpenID Connect spec defines a discovery protocol through which reliers can learn about the various endpoints and supported features of the IdP [1].  We should implement such a thing for Firefox Accounts.  I think it's most sensible deployed as part of the content-server API because this allows reliers to discover all our other endpoint URLs just by knowing "accounts.firefox.com".

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-38-openid-connect#discovery

**Comment by shane-tomlinson** [comment]
Revenge of the discovery document. 

Ref https://github.com/mozilla/fxa-auth-server/issues/738.

**Comment by rfk** [comment]
Heh, absolutely!  I'm tempted to add a couple of custom keys into it for our own purposes as well, so that e.g. the browser can dynamically discover webchannel setup pages.
