### ISSUE TITLE
bower build problems on tests.dev.lcip.org (and also on tc-tests.dev.lcip.org)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3302]
e.g., http://tests.dev.lcip.org:8111/viewLog.html?buildId=7543&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog

Not sure what is causing this, but since two independent boxes fail the same way, seems to be some external problem, but maybe not. Dunno.

**Comment by jrgm** [comment]
Perhaps similar to https://github.com/bower/bower/issues/2037

**Comment by jrgm** [comment]
I could reproduce on a non-test box. I forced bower to use lru-cache@2.7.0 (2.7.1 was released 8 hours ago), and and the error is gone. See also https://github.com/isaacs/node-lru-cache/issues/60

**Comment by vladikoff** [comment]
@jrgm we just need to bump to latest bower 1.6.x. it has shrinkwrap, and lru-cache is locked there: https://github.com/bower/bower/blob/master/npm-shrinkwrap.json#L662

**Comment by vladikoff** [comment]
Should be fixed!
