### ISSUE TITLE
Inconsistent marketing messaging for Android vs iOS?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3305]
The mobile marketing snippet currently looks like this:
![screen shot 2015-11-27 at 14 51 05](https://cloud.githubusercontent.com/assets/34695/11433787/7dd759c8-9516-11e5-9565-a9ca4080ce6b.png)

It uses a generic "Download Firefox for mobile devices." message to introduce the link to the play store, and a specific "Download Firefox for iOS!" message to introduce the link to the app store.  I suppose it's justified while iOS is new and shiny, but longer-term, should we treat them consistently and just say the generic "Download Firefox for mobile devices" with a link to both stores?

**Comment by vladikoff** [comment]
from mtg: "looks poor", lots of issues!

Only show if the verification step was on iOS but not sign up.

**Comment by vladikoff** [comment]
from mtg: determine the signup context: 
if iOS sign up in FxiOS then Safari verification should not have "Get on iOS", but should have "Get on Google Play"

**Comment by shane-tomlinson** [comment]
@jpetto - care to chime in?

**Comment by jpetto** [comment]
Completely agree that the current messaging is inconsistent. I'm not the final authority on such messaging, but IMO we could remove the "Get Firefox for iOS!" text, leaving only "Download Firefox for mobile devices." I don't believe we are calling out iOS next to Android so specifically anywhere on mozilla.org.

In terms of signup context, I agree that showing an App Store button on FxiOS is not great UX (same goes for Android/Play Store). I'm also unsure how useful a link to the Play Store will be to a user on iOS, or a link to the App Store is to a user on Android. Neither scenario could directly download anything. Perhaps the most universal solution for users on iOS/Android would be to provide a "Get Firefox for your other devices" link that directs to https://www.mozilla.org/firefox/products/?

If we want to push a little harder, we could leverage our send to device widget, which exists on both https://www.mozilla.org/firefox/ios/ and https://www.mozilla.org/firefox/android/. This requires a bit more work by the user (clicking another button to invoke the widget, entering an email address/phone number), but could result in more alternate platform downloads.

It may be worth scheduling a meeting with Holly to talk about the best UX going forward.
