### ISSUE TITLE
about 16 tests failing on latest.dev.lcip.org+tests.dev.lcip.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3306]
Probably/possibly related to upgrading selenium to 2.48.2, as I have passing tests with teamcity and 2.47.1/Fx42 on tc-tests.dev.lcip.org https://github.com/mozilla/fxa-content-server/issues/3291

**Comment by vladikoff** [comment]
from mtg: Downgrade for now and deal with it later
