### ISSUE TITLE
Figure out support for auto "Device Refresh" for the devices view

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3308]
We should figure out if we need this feature or if we can live without it. The amount of work to implement Firefox Desktop -> Content Server update signalling might not be worth it. It will require all content server pages to send a webchannel LOADED event that will subscribe them to updates from Firefox Desktop. We should also keep in mind that if any of those pages navigate away from the content server then Desktop should not send events (this might work automatically through message origin checks)

From https://github.com/mozilla/fxa-content-server/issues/3252

**Comment by rfk** [comment]
It sounds like this would dovetail nicely with work on the long-mooted "device handshake" [1], which will require us to tackle these same questions.

[1] https://mail.mozilla.org/pipermail/dev-fxacct/2015-September/001708.html

**Comment by vladikoff** [comment]
@vladikoff @shane-tomlinson @philbooth to chat about this...

**Comment by vladikoff** [comment]
From our chat we talked a lot about push and push probably won't work for this. Backlogging this until priority, so far we have a refresh button and we shall see if we can make more improvements to this

**Comment by vladikoff** [comment]
@ryanfeeley Should we just have metrics on the `refresh` button and if a lot of users click on it that means we need auto refresh?

**Comment by vladikoff** [comment]
Closing until there is a require user story here

**Comment by ryanfeeley** [comment]
> @ryanfeeley Should we just have metrics on the refresh button and if a lot of users click on it that means we need auto refresh?

Great assumption. Bummer this can't be a nice live connection.
