### ISSUE TITLE
Investigate about:accounts load failures on Fennec

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3310]
(Thanks to @ncalexan for providing initial telemetry on the web-based about:accounts flow in Fennec!)

 On Fennec Aurora, about 10% of attempts to load about:accounts fail to receive the "LOADED" message from content:

  https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2015-11-27&keys=%252Fsignup!__none__!__none__!__none__&max_channel_version=aurora%252F44&measure=ABOUT_ACCOUNTS_CONTENT_SERVER_LOADED_RATE&min_channel_version=null&product=Fennec&sanitize=1&sort_keys=submissions&start_date=2015-11-11&table=0&trim=1&use_submission_date=0

The percentage is smaller on Nightly, around 3%:

  https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2015-11-27&keys=%252Fsignup!%252Fsettings%252Favatar%252Fchange!%252Fsettings!%252Fforce_auth&max_channel_version=nightly%252F45&measure=ABOUT_ACCOUNTS_CONTENT_SERVER_LOADED_RATE&min_channel_version=null&product=Fennec&sanitize=1&sort_keys=submissions&start_date=2015-11-02&table=0&trim=1&use_submission_date=0

It's not obvious to me what might cause such a failure to load; maybe users giving up while waiting for the page to load?  We should try to learn more in collaboration with the Fennec team.

**Comment by shane-tomlinson** [comment]
@ncalexan - is this still a problem? The linked to dashboards do not load any data.

**Comment by ncalexan** [comment]
> @ncalexan - is this still a problem? The linked to dashboards do not load any data.

If it is, I'm not aware of it.  I was ruminating just a few days ago about how solid the FxA signin experience seems to be in Fennec -- we never _hear of_ people having difficulty signing in, although they may be having that difficulty and not be able to provide feedback.  In any case, close it out!
