### ISSUE TITLE
Add a further warning to reset password page

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3320]
Another report of a user inadvertently wiping their sync data. We should add this line in white with red background: "This will erase any Sync data we have as it is encrypted with your password." and make a small edit to the line beneath it.
<img width="487" alt="reset-screen" src="https://cloud.githubusercontent.com/assets/68213/11747327/a03805dc-9ff0-11e5-94af-58d5d0dfeb7b.png">

Related: https://github.com/mozilla/fxa-auth-mailer/issues/105

**Comment by rfk** [comment]
Do we need to get l10n input on the copy here?

**Comment by vladikoff** [comment]
Still in progress...

**Comment by vladikoff** [comment]
Closing, different bugs coming...
