### ISSUE TITLE
"Unexpected Error" when signing up after reloading about:accounts?action=signup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3335]
STR

1. Using any Fx >= 43 (not tested on Fx 42), open a new profile
1. Click the hamburger menu
1. Click "Sign in to Sync"
1. Click "Create Account"
1. Reload the page using CMD-R
1. Fill out sign up form, submit.
1. Wah wah.

![unexpected-error-reload-about-accounts-with-action](https://cloud.githubusercontent.com/assets/848085/11902885/dd403744-a5ac-11e5-97e0-586b948d2a12.gif)

I believe this is due to the same reason as #3329

**Comment by shane-tomlinson** [comment]
Should be fixed when https://bugzilla.mozilla.org/show_bug.cgi?id=1233668 lands

**Comment by shane-tomlinson** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=411469398d76

**Comment by vladikoff** [comment]
Fixed via the desktop patch! Woot!
