### ISSUE TITLE
When users resets password during Sync registration, they are not signed in to Sync

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3343]
ACTUAL

1. In a new profile, a user goes to sign in to Sync but clicks **Forgot Password?**
1. User completes password reset
1. User is not automatically signed in to Sync

EXPECTED

1. In a new profile, a user goes to sign in to Sync but clicks **Forgot Password?**
1. User completes password reset
1. **User is succesfully signed in to Sync**

**Comment by vladikoff** [comment]
@ryanfeeley Cannot reproduce it here: 

![image](https://cloud.githubusercontent.com/assets/128755/12038682/2c52dade-ae28-11e5-9e16-ed77e718f858.png)

I made a new password and it worked! 

when you say:

> User completes password reset

User must create the new password in that new Desktop Firefox.

**Comment by ryanfeeley** [comment]
@vladikoff It says that, but is it signed in, in Preferences?

**Comment by vladikoff** [comment]
> @vladikoff It says that, but is it signed in, in Preferences? 

Yeap!

**Comment by ryanfeeley** [comment]
This was in release on Windows. Who's got it?

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/12040345/47986ddc-ae36-11e5-8952-2255eb1894ab.png)

**Comment by ryanfeeley** [comment]
Hmmm…

**Comment by rfk** [comment]
> User must create the new password in that new Desktop Firefox.

What happens if they complete it in a different browser?

**Comment by shane-tomlinson** [comment]
> What happens if they complete it in a different browser?

If they complete in a different browser, the password entered in browser 2 cannot be sent to browser 1, and the user is never signed in. This is known behavior, as outlined in [the big flow doc](https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/edit#gid=0). In browser 1, the user *should* be sent to the signin page after they verify in browser 2, the user can then complete the sign in in browser 1.

**Comment by rfk** [comment]
> In browser 1, the user should be sent to the signin page after they verify in browser 2,
> the user can then complete the sign in in browser 1

@ryanfeeley does this correspond to the behaviour that you saw?

**Comment by ryanfeeley** [comment]
@rfk No, the entire process happened on one machine. I'll try to fire up Windows and verify the behaviour.
