### ISSUE TITLE
Signing in to Sync on desktop briefly shows unexpected error message

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3353]
Signing in to Sync on desktop briefly shows unexpected error message.
![fest](https://cloud.githubusercontent.com/assets/68213/12100140/08d0ea42-b2fb-11e5-8e70-e51b94336291.gif)

**Comment by shane-tomlinson** [comment]
Dup of #3330, which has a fix - #3331, which @vladikoff is on the hook to review. Closing as dup.

**Comment by shane-tomlinson** [comment]
Reopening, this is not a dup of #3330, sorry for the haste @ryanfeeley.

force_auth with this context has a similar problem, it redirects to /settings when it should not.

**Comment by shane-tomlinson** [comment]
Ref #3343
