### ISSUE TITLE
Validate all messages and payloads before they cross a security boundary

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3354]
Ref https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/user.js#L308

**Comment by rfk** [comment]
We could go even further and strictly specific the allowed message types, and the allowed data properties on each type.  May help us catch things we don't even know to look for.

**Comment by shane-tomlinson** [comment]
> We could go even further and strictly specific the allowed message types, and the allowed data properties on each type. May help us catch things we don't even know to look for.

A message passing data schema. I've done one of these before, long long ago.

**Comment by shane-tomlinson** [comment]
I'm going to re-open this because the referenced PR only took care of events sent via the notifier, we now have to take care of events sent in each of the brokers, if the message crosses a security boundary.

**Comment by rfk** [comment]
Are we going to do more work on this one in the upcoming cycle, or should we put it back in the queue for a while?

**Comment by shane-tomlinson** [comment]
> Are we going to do more work on this one in the upcoming cycle, or should we put it back in the queue for a while?

Can we put this on "next" to keep it from falling through the cracks?

**Comment by rfk** [comment]
yes, "next" is still "back in the queue" compared to where it is now :-)

**Comment by vladikoff** [comment]
figuring out how other oauth params will handle this

**Comment by shane-tomlinson** [comment]
In particular, this was about WebChannel messages.

**Comment by vladikoff** [comment]
from mtg: we need to add extra validation to stuff in `auth_brokers/fx-sync.js`, mostly need to add extra validation to the payloads. We currently only check the require fields.

**Comment by shane-tomlinson** [comment]
Putting this back into the backlog.

**Comment by shane-tomlinson** [comment]
Ref #4981

**Comment by vladikoff** [comment]
🗡 closing this for now
