### ISSUE TITLE
Add a sign-in link to the Confirm Your Account screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3358]
For the first time in a while, in Chrome, I went to accounts.firefox.com. Because the last time I used it was to create an account (that I don't think I ever verified) I was redirected to the **Confirm your account** screen.
<img width="493" alt="confirm-your-account" src="https://cloud.githubusercontent.com/assets/68213/12125412/2c79d846-b3b9-11e5-97b7-61cb60ea9a84.png">
There was no way to escape this screen, so I think that we should add a **Use a different account** link above **Resend email** which would take users to a fresh login screen.

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/2002
