### ISSUE TITLE
Adding 10px right-padding to COPPA age input

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3359]
Firefox now inserts a spinner control on numeric inputs, and our age input lacks the right-side padding to accomodate it. We should add 10px of right-side padding to the input so it lines up nicely with the edge of **Show** in the password field above it.

**Current:**
<img width="356" alt="age-current" src="https://cloud.githubusercontent.com/assets/68213/12128960/a1ee518c-b3ce-11e5-9b4b-1947f52cdd66.png">

**Proposed:**
<img width="359" alt="age-proposed" src="https://cloud.githubusercontent.com/assets/68213/12128969/ad4a78da-b3ce-11e5-9262-65240008b890.png">

**Comment by rfk** [comment]
IIRC our next deploy will include styling to make that spinner go away: https://github.com/mozilla/fxa-content-server/commit/c6da26ca7a82d041df13eafd085b16da533738c0

**Comment by rfk** [comment]
But we can keep it and add some padding if you prefer :-)

**Comment by vladikoff** [comment]
> Firefox now inserts a spinner control on numeric inputs,

We were always hiding it in WebKit / Blink (per approved design), so we also removed it in Firefox.

**Comment by ryanfeeley** [comment]
Apparently it's different in most browsers. https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/

**Comment by ryanfeeley** [comment]
I like it in a way because it might give the users a clue that they need to type an integer or some kind, even if it is too small for our fields. Worth an experiment @vladikoff?

**Comment by vladikoff** [comment]
> I like it in a way because it might give the users a clue that they need to type an integer or some kind, even if it is too small for our fields. Worth an experiment @vladikoff?

I don't think that button is useful in any sense, you have to click it up 10+ times to use it correctly (to avoid COPPA). The controls make more sense with small number inputs, such as selecting a small quantity of something (e.g buying tickets online using the number input)

**Comment by ryanfeeley** [comment]
I see your point, but miss your experimental period @vladikoff.

**Comment by ryanfeeley** [comment]
I think this issue is worth closing.
