### ISSUE TITLE
'iframe oauth channel' functional tests fail when run against stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3361]
The iframe oauth channel tests fail when run against https://accounts.stage.mozaws.net/. Running interactively, the iframe does not come up, so fail. However, manually clicking through will allow the tests to pass. @vladikoff suggests this is probably due to timing differences (maybe a race with installing the event handler).

**Comment by vladikoff** [comment]
Adding a 1 second delay fixes but will need a better solution for this.

**Comment by vladikoff** [comment]
@jrgm One thing that I noticed (might be unrelated):

https://123done-latest.dev.lcip.org/iframe vs https://123done-stage.dev.lcip.org/iframe , the stage one is missing fonts

**Comment by jrgm** [comment]
Huh, odd. 

Anyways, I have a branch that uses ansible and cloudformation to (re)build that stage instance of 123done. (It was previously done with awsbox). 

When I get a dull moment, I will be swapping in a rebuilt 123done which may fix the fonts.
