### ISSUE TITLE
figure out how to not have sentry ask for defunct /scripts/deadbeef.main.js when release goes live

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3363]
Not sure this is possible. Maybe the fix will be for kibana to have a UA that it can exclude. 

But anyways, when a new release goes live, there are a flurry of requests for the old version of main.js that shows as a spike of 404, which is an unsettling bit of noise.

**Comment by vladikoff** [comment]
I might be able to modify the name of the script, from
`"module":"ef9e639b.main","filename":"/scripts/ef9e639b.main.js"` to just `/main.js`, same with module name.  This might be a solution

**Comment by vladikoff** [comment]
to be clear: modify that in the error reports
