### ISSUE TITLE
Enable Web based CWTS from the firstrun flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3365]
CWTS on the web is [explicitly forbidden in the firstrun flow](https://github.com/mozilla/fxa-content-server/blob/34c9728c99e929ad714c5cf6cf68d1b405bb2792/app/scripts/models/auth_brokers/first-run.js#L29). This is unfortunate.

**Comment by vladikoff** [comment]
What are the blockers for this?

**Comment by shane-tomlinson** [comment]
Let's reach out to the Growth team to see if this scares them before flipping it on.

**Comment by shane-tomlinson** [comment]
> What are the blockers for this?

No technical blockers that I can think of. I'll contact the Growth team.
