### ISSUE TITLE
Format last connected date in Devices View

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3377]
![](http://v14d.com/i/56953d7a492f3.jpg)

Hey @philbooth I got the view above ^, do we still need to format that number or is this my local setup?

**Comment by philbooth** [comment]
Oh, we still need to format it. I completely forgot about the front-end, sorry. I can do it tomorrow if you like.

**Comment by vladikoff** [comment]
@philbooth depends if you have time, otherwise we can leave this open for someone else to fix, just wanted to file an issue and check.
