### ISSUE TITLE
Expired token sign-in screen lacks password field

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3378]
User keeps pressing **Sign in** and keeps getting this screen.
<img width="481" alt="screen shot 2016-01-12 at 1 44 27 pm" src="https://cloud.githubusercontent.com/assets/68213/12273231/af779598-b932-11e5-8291-615a57cf2710.png">

**Comment by vladikoff** [comment]
@ryanfeeley this is not enough information to reproduce the issue. Could you check https://github.com/mozilla/fxa-content-server/issues/3283 and see if the steps to reproduce are the same?

**Comment by vladikoff** [comment]
Actually this one seems different from #3283, @ryanfeeley do you have any details about how you got into that state?

**Comment by ryanfeeley** [comment]
I don't recall as I was in the middle of a demo. I believe I had clicked "Manage Account" from Sync prefs and got there. It was actually my primary account (I changed the email in dev tools).

These are the kinds of errors that I would like a special treatment as I would classify them as "building is on fire" errors.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - did you delete the account, create and verify the account, then click "manage" in sync preferences?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Absolutely not, it's my primary account. I didn't even change the password.

**Comment by ryanfeeley** [comment]
I think "use a different account" clearing the session could be part of the problem.

**Comment by shane-tomlinson** [comment]
Possible regression of #1964?

**Comment by shane-tomlinson** [comment]
Possible dup of #1877, that bug has STRs.

**Comment by rfk** [comment]
This bug has been in "next" for a while, but it's not obvious how to make it actionable without concrete steps to reproduce.

I've spent about an hour trying to reproduce it with a variety of logins and logouts concurrently across various services, but have not been successful.  I can generate the passwordless "sign-in" screen, and I can make it show a "session expired" error, but for me the "session expired" error is always accompanied by the re-appearance of the password input.

@ryanfeeley have you seen this re-occur?  Is it possible that we've perturbed this bug out of existence with fixes we made to the related bugs linked above?  I wonder if it's some slightly-worse edge-case of #1877, which does reproduce reliably.

If we don't have any good ideas for how to reproduce this, we should consider merging it with #1877 and bumping that one up to "next" in its place.

**Comment by rfk** [comment]
> for me the "session expired" error is always accompanied by the re-appearance of the password input

More specifically, I get the same weird no-avatar sign-in page that @ckarlof noted in this comment:
https://github.com/mozilla/fxa-content-server/issues/1964#issuecomment-139647533

**Comment by vladikoff** [comment]
I can reproduce this by restarting the local dev `auth-server db memory`: 

## STR

* Sign up / sign in into the browser
* `➜  fxa-local-dev git:(master) ./pm2 restart 1`
* Click Manage account

## Actual

I get this with latest code: 
![image](https://cloud.githubusercontent.com/assets/128755/14753297/67a60794-08a2-11e6-8955-9dc941ddc337.png)

## Expected 

Anything but the above screenshot.

**Comment by rfk** [comment]
yikes!

**Comment by vladikoff** [comment]
Re: https://github.com/mozilla/fxa-content-server/issues/3378#issuecomment-213570133 we go to /settings and that causes the Session Expired errors.

In force_auth, we set fatal error to "Deleted account", but then base.js (line 198) display Status messages Session Expired is still the status message.

**Comment by vladikoff** [comment]
Form not displaying is by design to avoid UID conflicts.

**Comment by vladikoff** [comment]
partial fix: https://irccloud.mozilla.com/pastebin/QGsXU5gh

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/1877

We are working on fixing that.
