### ISSUE TITLE
For focused fields, make the help text the same colour as the border

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3384]
Currently all of our field labels are grey (#8a9ba8).

Some of the fields, like the password field on registration, only appear when the field has focused

Others, like the password fields shown when changing passwords, are present whenever the field has content.

One constant currently is that the while the field helpers are grey (#8a9ba8), the focused borders are blue (#0095dd).

As a nice touch of polish, so that users can better associate helper text with focused fields, we should transition/make their colour the same blue as a focused field border – blue (#0095dd).

Example:
![focus](https://www.lucidchart.com/publicSegments/view/6dc2a2bb-ae05-4eec-a9c1-db4102842289/image.png)

**Comment by shane-tomlinson** [comment]
I dig this change. Do you think we should give the same treatment to the placeholder and button text, so everything appears as if it's one logical unit, or would that end up in blue overload?

**Comment by ryanfeeley** [comment]
Place no, but "Show"? That's a good idea. I even like the idea of making the "Show" on state white text on blue. I'll mock it up as part of this bug?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Added Show password state!

**Comment by shane-tomlinson** [comment]
@ryanfeeley - that's beautiful.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Is it easy to find all the fields? Are they always called label-helper?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Yup, `.label-helper` is used for the floating placeholders, `.show-password-label` is used for the "Show" button.

**Comment by vladikoff** [comment]
Let's just do it 🇮🇹!

**Comment by rfk** [comment]
yes, I don't think there's value in e.g. doing this one as an experiment

**Comment by ryanfeeley** [comment]
The tricky part will be coordinating the nice smooth color transition that we currently have between the field and the label.
