### ISSUE TITLE
Settings screen panes do not close when Back button is pressed

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3386]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238960

Reproduced with Firefox 44.0b8 (build ID 20160111185352) on Windows 10 64-bit, Windows 7 64-bit, Mac OS X 10.8.5 and Ubuntu 12.04 32-bit

STR
*prequisite: user has a Firefox account
1. Launch Firefox with clean profile.
2. Log in using a Firefox account.
3. Go to about:preferences#sync and click "manage Account"
4. On The Firefox accounts page, click "Change" at any option (i.e. Display name/Communication preferences)
5. Hit the Back button.

Expected Results
The pane (Display name/Communication preferences) is closed.

Actual results
The pane is not closed, even if the URL changes. The pane correctly closes when "Cancel" is clicked, so it should also close for the back button.

Additional notes:
Reproducing with latest Nightly (20160111030207), latest DevEdition (20160112004003) and Firefox 43.0.4 (20160105164030).
Not a recent regression, it reproduces on Firefox 36 also (https://accounts.firefox.com/settings)

**Comment by vladikoff** [comment]
![loadup](https://cloud.githubusercontent.com/assets/128755/13613702/44c940f4-e53b-11e5-9563-1c5b3938a134.gif)

**Comment by swatilk** [comment]
I would like to work on this issue

**Comment by vladikoff** [comment]
Hey @swatilk!

Some reference:

Take a look at https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/scripts/views/mixins/settings-panel-mixin.js#L19

and https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/back-mixin.js#L54

You might be able to fix this by using the existing [back event](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/back-mixin.js#L54) and collapse the settings panel.

Let us know if you have questions. To get a local environment see https://github.com/mozilla/fxa-local-dev

@shane-tomlinson any other tips?

**Comment by swatilk** [comment]
@vladikoff thanks for the tips

**Comment by vladikoff** [comment]
@vbudhram recently updated this and added an ESCAPE handler, so the fix for this should be easier: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/app.js#L44
