### ISSUE TITLE
 Unable to upload picture to Firefox Accounts from firstrun

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3388]
Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1238932

---

Created attachment 8706901 [details]
Gif showing the issue

Affected builds:

Affected OS's:

STR:
1. Start Firefox
2. Visit https://www.mozilla.org/en-US/firefox/44.0/firstrun/ or 43.0 instead of 44.0 
3. Sign in with a new account
4. Revisit url from step 2
5. Click 'Add' button from Account picture
6. Click Upload and select an image from drive

Expected: The selected image is uploaded to FxA

Actual: Nothing happens after selecting the image.

Notes:
- Not sure if this is a recent regression, it also reproduces in 43.0, will get back on this asap.
- Doing the same thing from https://accounts.firefox.com/settings works as expected

---

> Affected builds:
> - Firefox 43 RC
> - Firefox 44 beta 8
> 
> Affected OS's:
> - Ubuntu 12.04 32-bit
> - Mac OS X 10.8.5
> - Windows 10 64-bit

![unable-to-upload-photo-from-firstrun](https://bug1238932.bmoattachments.org/attachment.cgi?id=8706901)

**Comment by vladikoff** [comment]
Should open that link in a new tab

**Comment by vladikoff** [comment]
@shane-tomlinson can we fix it using a "hard-redirect" to this page https://accounts.firefox.com/settings/avatar/change ?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson can we fix it using a "hard-redirect" to this page https://accounts.firefox.com/settings/avatar/change ?

I don't think we can hard redirect the outer page. It would be good to understand why this happens. Is an event handler not firing, is data not being received, is an error being thrown and swallowed?

**Comment by vladikoff** [comment]
> I don't think we can hard redirect the outer page. It would be good to understand why this happens. Is an event handler not firing, is data not being received, is an error being thrown and swallowed?

We can navigate the parent with:
https://www.w3.org/TR/2010/WD-html5-20100624/the-iframe-element.html#attr-iframe-sandbox-allow-top-navigation

I was hoping the "Email Preferences" link can also be fixed with the "hard-redirect" navigation.

**Comment by vladikoff** [comment]
This works now since Train-75. I was able to upload an avatar from the firstrun view ![](http://v14d.com/i/58595429ef231.jpg)
