### ISSUE TITLE
Wrong link redirect when clicking Email Preferences from Firefox Accounts

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3389]
Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1238940

---

Affected builds:
- Firefox 43.0 RC
- Firefox 44 beta 8

Affected OS's:
- Ubuntu 12.04 32-bit
- Mac OS X 10.8.5
- Windows 10 64-bit

STR:
1. Start Firefox
2. Visit https://www.mozilla.org/en-US/firefox/44.0/firstrun/ or 43.0 instead of 44.0 
3. Sign in with a new account
4. Revisit url from step 2
5. Click 'Change' from Communication preferences
6. Click Email preferences url

Expected: I'm redirected to https://www.mozilla.org/en-US/newsletter/existing/6143bb27-5b46-4ea0-9ecf-0581883a1b7a

Actual: A blank area will appear.

Notes:
- Not sure if this is a recent regression, it also reproduces in 43.0, will get back on this asap.
- Doing the same thing from https://accounts.firefox.com/settings works as expected

**Comment by muffinresearch** [comment]
Looks like the blank area is caused by framing which is denied by headers:

```
Load denied by X-Frame-Options: https://www.mozilla.org/en-US/newsletter/existing/01af8593-cca5-8a55-6b4e-28ef89b2a665 does not permit framing.
```

Looks like this on desktop:

![get_a_firefox_account_ _mozilla](https://cloud.githubusercontent.com/assets/1514/18353648/c02a75b2-75da-11e6-9cf9-739d5f42a1be.png)

**Comment by vladikoff** [comment]
This was fixed, email prefs link is now hidden on that page + any external links will open in new tabs now.
