### ISSUE TITLE
Discuss password reset improvements for unknown accounts

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3393]
<img width="493" alt="fxa-unknown" src="https://cloud.githubusercontent.com/assets/68213/12395840/ee319664-bdd1-11e5-88c1-5aafdcbae500.png">

According to DataDog 22.89% of views of the password reset page result in this "unknown account" error.

What are the possible reasons people would get this error?

1. User has an account, but with a different email address
1. User has an account, but mistyped the right email address
1. User doesn't have an account, but assumed otherwise
1. Bad actor trying to see if users have an account

Other possibilities? Do we have any data to support how many of each exist?

If there are a large number of #4, perhaps we should do what sites like kayak.com do and not divulge that a user has an account by showing the same "reset email sent" screen and  sending this email instead.

<img width="912" alt="kayak-forgot" src="https://cloud.githubusercontent.com/assets/68213/12396038/3ee6da28-bdd3-11e5-9bb2-a3b668e3c1ed.png">

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-customs-server/issues/66

**Comment by rfk** [comment]
> If there are a large number of #4, perhaps we should do what sites like kayak.com
> do and not divulge that a user has an account

Given https://github.com/mozilla/fxa-auth-server/issues/1176 and https://github.com/mozilla/fxa-content-server/issues/3489 I think we're committed to leaking this info in our UX, and will rely on rate-limiting to mitigate potential for abuse.

@ryanfeeley is there more we can do for users in categories 1 through 3?

**Comment by ryanfeeley** [comment]
Our current UI that helps users log is too tangled up realistically do this.
