### ISSUE TITLE
Measure when users successfully change their passwords

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3396]
We currently record when users view the **Change Password** section in **Settings**, including many of the users’ trials and tribulations with changing their password, but we don’t record when they successfully change their password.

So that we can optimize our change password experience, as a Firefox Accounts team, we should track when users successfully change their password.

Proposed metric name: fxa.content.settings.change_password.success

![change-password-stats](https://cloud.githubusercontent.com/assets/68213/12402208/6938bc30-bdf9-11e5-9ed5-dc123f01dfc4.png)

**Comment by vladikoff** [comment]
Yeah put it somewhere before `invokeBrokerMethod` https://github.com/mozilla/fxa-content-server/blob/6f2c6a3360f7bf250cb23455b93da7098a12663e/app/scripts/views/settings/change_password.js#L48

**Comment by vbudhram** [comment]
I think I can tackle this one!
