### ISSUE TITLE
Clarify for how long verification emails are valid

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3397]
When users send new account or password reset emails, they have no idea how long they are valid for. We should let them know in at least one part of the UX.

Help me help them by telling me for how long verification emails are valid.

**Comment by vladikoff** [comment]
We need to check the expiration for the links...

**Comment by philbooth** [comment]
Password forgot: 60 minutes
Password change: 15 minutes
Account reset: 15 minutes

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-auth-server/blob/726351ee258f7e37d2986d8f02b52a2b21141830/config/index.js#L235

need to check prod config for these values...

**Comment by ryanfeeley** [comment]
I'm not sure I understand which of those three refer to the parts of the reset flow (I only see one verification link going out in the reset flow). Can you confirm? And what about new account verification links? Are they 60 minutes?

![firefox-sync](https://www.lucidchart.com/publicSegments/view/4d816217-8c5a-48be-a14e-79d8eac303d8/image.png)

cc/ @philbooth

**Comment by vladikoff** [comment]
@dannycoates would you know these better?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - "You will lose any Sync data that is not saved to one of your devices" and "you will lose any unsaved Sync data"... I know the intent is to scare people, but I'm wondering if there is a way to make the messages more actionable. At a minimum it seems like there should be a sign in link on the "Enter new password" page, possibly in the error message. I'd also put a link to "How Sync works" in that error message too, just so users understand what you are trying to convey and whether they need to worry.

**Comment by rfk** [comment]
> need to check prod config for these values...

I grepped puppet-config for references to "lifetime" but didn't find anything related to fxa, so I think the default values apply; @jrgm can you confirm?

> I'm not sure I understand which of those three refer to the parts of the reset flow
> (I only see one verification link going out in the reset flow).

It's the "password forgot token", valid for 60 minutes.  The "password change" and "account reset" tokens are for internal use and don't show up in emails to the user.

>  And what about new account verification links? Are they 60 minutes?

As far as I can tell from the code, new account verification links links should be valid indefinitely.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I'm afraid that the only actionable device a user can take at this point is to sign in on another device; however if they've forgotten their password, how can they do that?

**Comment by rfk** [comment]
@ryanfeeley does the above answer your questions, or are there further things you'd like us to dig into as part of this bug?

**Comment by ryanfeeley** [comment]
All clarified! Thanks gang!
