### ISSUE TITLE
Run an experiment to reduce bounces and increase verifications

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3400]
So that I can avoid wasting my time, as a confusable Firefox Accounts registrant, I want to a label helper ensure that the email I enter is one that I own and check.

![fxa-email-helper](https://cloud.githubusercontent.com/assets/68213/12430740/40276d84-bebf-11e5-94a3-1bab533b6679.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm neither for nor against this idea, and seems like a good candidate for an AB test. What metrics should we measure - bounce rate, verification rate, mailcheck usage?

**Comment by ryanfeeley** [comment]
Yes, to all three! i only mentioned the first two in the issue title.

**Comment by shane-tomlinson** [comment]
Ref #3401

**Comment by rfk** [comment]
Merging the mailcheck issues into a feature card at https://github.com/mozilla/fxa/pull/128, so closing out here
