### ISSUE TITLE
Improve styling of Mailcheck experiment

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3401]
So that I can fix more typos, as a Firefox Account registrant, I want to know more obviously when I have mistyped a domain.

![mailcheck-restyle](https://cloud.githubusercontent.com/assets/68213/12430924/745aff5c-bec0-11e5-8898-c0191be65bac.png)

Notice the extra spacing that is required after the email field (to avoid overlapping the password field).

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @vladikoff - My feel is the proposed change will lead to an increase in mailcheck usage as well as a reduction in bounced emails. This would be a good AB test experiment. If we do an AB test, what should we measure?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Can we add it to the current experiement as treatment2? So that we measure all the same things as the original treatment?

**Comment by rfk** [comment]
Merging the mailcheck issues into a feature card at https://github.com/mozilla/fxa/pull/128, so closing out here
