### ISSUE TITLE
CircleCI - Intermittent failure - device panel works with query param, same device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3405]
From https://circleci.com/gh/mozilla/fxa-content-server/1854

> × firefox on any platform - settings devices - device panel works with query param, same device (30.093s)
CancelError: Timeout reached on firefox on any platform - settings devices - device panel works with query param, same device
  at null._onTimeout  <node_modules/intern/lib/Test.js:162:20>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.device panel works with query param, same device [as test]  <tests/functional/settings_devices.js:99:12>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:236:37>
  at Promise.cancel  <node_modules/intern/node_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:164:21>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>

**Comment by vladikoff** [comment]
Could be fixed by https://github.com/mozilla/fxa-dev/issues/213
