### ISSUE TITLE
Use a different account clears web session

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3410]
STEPS:
1. Be logged in to sync
2. Go to accounts.firefox.com/signin
3. Click Use a different account
4. In Sync preferences, go to Manage and get this.

<img width="513" alt="screenshot 2016-01-21 10 25 26" src="https://cloud.githubusercontent.com/assets/68213/12484692/749f4ae4-c029-11e5-83b4-960945b4c33d.png">

**Comment by shane-tomlinson** [comment]
This is one of the prime reasons for the desire to have closer integration between the browser and FxA. The goal is to have the browser communicate its view of the user's session state to FxA. I believe there is already a card or issue on this.

**Comment by shane-tomlinson** [comment]
Ref #3421 for how users end up at accounts.firefox.com/signin after signing up/in to sync.

**Comment by shane-tomlinson** [comment]
(Marketing links from Twitter)

**Comment by vladikoff** [comment]
See https://github.com/mozilla/fxa-content-server/issues/3222#issuecomment-214439791

**Comment by vladikoff** [comment]
Need to update https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/base.js#L242, just log the error, do not give it to navigate.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/commit/6103a64e20d926dcedd08d36c0b58f79f002da8e
