### ISSUE TITLE
Inform the firstrun page if the user has clicked on the "email opt in" check box.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3411]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1231496

--------------------------------

We want to see how many people opt-in to email communications as part of the Accounts signup within a GA dashboard.

Idea is to add a true/false parameter for the checkbox as part of the signup event. True = email opt-in is checked. False = email opt-in is not checked.

Is this possible?

--------------------------------

On the bedrock side, the change should be fairly trivial. However, we will need the status of that checkbox communicated to the page from the FxA iframe.

:stomlinson - What do you think? Would it be difficult to send an extra boolean along with the signup_must_verify event?

cc @jpetto, @vladikoff 

@vladikoff - do we send this info to GA now? I don't believe we do, but want to make sure.

**Comment by vladikoff** [comment]
> @vladikoff - do we send this info to GA now? I don't believe we do, but want to make sure.

We do not
