### ISSUE TITLE
Exceptional number of setLocalStorageItem errors in Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3414]
Very similar to #2969 and #2913. Sentry shows an exceptional number (many millions) of setLocalStorageItem errors in Sentry. 

![screen shot 2016-01-22 at 11 34 01](https://cloud.githubusercontent.com/assets/848085/12509728/6df445fe-c0fc-11e5-8ea6-24a066f2324c.png)

Errors reported: NS_ERROR_STORAGE_IOERR, NS_ERROR_FILE_NO_DEVICE_SPACE, NS_ERROR_FILE_CORRUPTED,  NS_ERROR_STORAGE_CONSTRAINT, NS_ERROR_FAILURE, NS_ERROR_STORAGE_BUSY, NS_ERROR_OUT_OF_MEMORY, SecurityError (This operation is insecure)

A scan through the Sentry reports seems it's always on the firstrun page, which should only be shown to users of a new profile. The error always occurs in the same place within crosstab:

![screen shot 2016-01-21 at 18 45 51](https://cloud.githubusercontent.com/assets/848085/12490788/412d8d42-c06f-11e5-98f7-fd60064741e6.png)

Curiously, the volume of this error dropped as soon as train 54 was released. We are unsure of why, except for a possible problem with Sentry reporting.

I am unable to get any of the corrupt errors. I am able to get an NS_ERROR_FILE_READ_ONLY error with the following STRs and Firefox 43:

* Close Firefox
* Go into the profile directory
* chmod 444 webappsstore.sqlite
* Start Firefox
* Open the firstrun page (https://www.mozilla.org/en-US/firefox/43.0/firstrun/). The firstrun page appears fine.
* Open the console, look for the NS_ERROR_FILE_READ_ONLY error

![screen shot 2016-01-22 at 11 41 40](https://cloud.githubusercontent.com/assets/848085/12509820/3948f902-c0fd-11e5-8d24-85a7cfeaa88c.png)

* If I refresh the signup screen, I am shown the "cookies disabled" message.

Another curiosity is if previous to refreshing the signup screen and causing "cookies_disabled" to appear, I can sign up to a new account without a problem, I am only shown the cookies_disabled screen if I verify in the same browser. The signup tab never shows the "cookies_disabled" screen.

The NS_ERROR_FILE_READ_ONLY error count keeps incrementing because crosstab writes to localStorage every 3 seconds to see if any other tabs are open. This could help explain the volume of errors.

A simple "fix" for the volume of errors is to prevent crosstab from functioning if [BroadcastChannels exist](). This will not fix the underlying issue, which is localStorage data is unable to be written, but it will reduce the number of errors sent to Sentry.

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1240238

**Comment by shane-tomlinson** [comment]
If I set permissions on webappsstore.sqlite to 000, I see a `NS_ERROR_FILE_ACCESS_DENIED` error in the console and FxA is blank within the firstrun page, similar to @andymckay's report.

![screen shot 2016-01-22 at 12 46 41](https://cloud.githubusercontent.com/assets/848085/12511065/488865ac-c106-11e5-982e-4853ecbf8e69.png)

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3415

**Comment by shane-tomlinson** [comment]
We still see localStorage errors, though not nearly as many. I'm closing this issue, we can file follow on issues if we feel it's necessary.
