### ISSUE TITLE
Redirect Firefox Accounts users from login and registration to about:accounts

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3421]
So that I don't inadvertently create a Firefox Account that takes me nowhere but to Settings, as a registering user in Firefox, I want to be redirected from accounts.firefox.com/signup to about:accounts?action=signup&entrypoint=menupanel

So that I don't inadvertently log in to a Firefox Account that takes me nowhere but to Settings, as a current user in Firefox, I want to be redirected from accounts.firefox.com/signin to about:accounts?action=signin&entrypoint=menupanel

**Comment by rfk** [comment]
@ryanfeeley I'm not sure I understand what's motivating this bug, can you please add a little more detail about what the user might be doing to wind up in this state?  As a registering user in Firefox, what were you doing on accounts.firefox.com/signup in the first place?

**Comment by ryanfeeley** [comment]
Users in the past have been directed to create a Firefox Account for the purpose of Sync via a web link to accounts.firefox.com. Creating an account there will not connect a browser to Sync, but where possible (the user is in Firefox), it should.

**Comment by rfk** [comment]
We need to try to be careful about discerning user intent here, it would be a bad failure case if we connect a user to sync when that's *not* what they were actually trying to do.

IIRC, we may not have this problem any more anyway, since it is now possible for a properly-crafted link to https://accounts.firefox.com/ to sign you in to sync without having to go via about:accounts. We may be better off trying to audit all our links and make sure they work that way, rather than trying to redirect in the general case.

**Comment by rfk** [comment]
This kibana dash shows users who request `/signup` on the content-server without a `service=` or `client_id=` query param, and who thus might find themselves creating an account for no useful reason:

  https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/temp/AVJ8H39XayLd6KaGF1Iu

There's about 10 every 30 mins, from a rich mix of user-agents.  Digging in the HTTP referer headers reveals people coming to this page from:

  * google searches
  * SUMO articles like [1] or inquiries like [2]
  * Android and FirefoxOS devices without a referer header

The SUMO folks probably mean to manage the account that's connected to their browser; I've no idea what expectations the other folks might have.

[1] https://support.mozilla.org/en-US/kb/access-mozilla-services-firefox-accounts
[2] https://support.mozilla.org/en-US/questions/1003802

**Comment by ryanfeeley** [comment]
@rfk @vladikoff  If there really are people googling Firefox Accounts to sign up for Sync (and especially if there are 500K/year by your math) we should probably give them a little help.

Even something simple that just links them to a page with some intelligence like: mozilla.org/firefox/sync
<img width="368" alt="screenshot 2016-01-26 11 28 33" src="https://cloud.githubusercontent.com/assets/68213/12587051/c202ad12-c420-11e5-9100-e71a970418d3.png">

Make sense?

**Comment by rfk** [comment]
SGTM; should we do a similar treatment for the /signin page as well?

**Comment by ryanfeeley** [comment]
@rfk Yes! I'll rename the issue.

**Comment by rfk** [comment]
Assigning to myself for priority triage

**Comment by vladikoff** [comment]
@rfk @ryanfeeley 
How are we going to link to `about:accounts`? Should we use one of the sync promotional pages for this?

Does the `"Are you signing up for sync?"` have to be red? can it be blue? (so it does not look like a full error)

**Comment by ryanfeeley** [comment]
@vladikoff Our blue is better. More informational. Good suggestion.

**Comment by rfk** [comment]
> Assigning to myself for priority triage

Note to self: this ^ didn't go so well :-/

>  How are we going to link to about:accounts? Should we use one of the sync promotional pages for this?

Yes, I think we should link to https://mozilla.org/firefox/sync or similar product page with some smarts in it, which should do the right thing regardless of what version of Firefox you're on.

**Comment by ryanfeeley** [comment]
ORIGINAL PROPOSAL:
Are you signing up for Firefox Sync? Get started from <a href="#">this page</a>.

NEW PROPOSAL:
Looking for Firefox Sync? <a href="#">Get started here.</a>

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/15554384/e49d2396-2291-11e6-8ef3-62a2a9803589.png)

**Comment by vladikoff** [comment]
Add metrics of how many people click on it VS an easy way to find out how many see it.

**Comment by vladikoff** [comment]
- [ ] Add new string with `t(‘String here’)`
- [ ] Add metrics `logEvent` (how many saw, how many clicked)
- [ ] Might need to add a precaution for window.opener (see https://mathiasbynens.github.io/rel-noopener/) 
- [ ] Unit test: only non-sync and non-oauth broker see the note (only direct visit to 127.0.0.1:3030 / accounts.firefox.com). Test metrics events.
- [ ] Functional test (Sync note visible, maybe just add assertion to existing tests? No need to add clicking on “Get Started Here” just assert the link.)

**Comment by star1951** [comment]
about:accounts?action=signin&entrypoint=firstrun#
