### ISSUE TITLE
Browser becomes unresponsive when stressing the Firefox Accounts page [bz1238961]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3427]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238961

Reproduced with Firefox 44.0b8 (build ID 20160111185352) on Windows 10 64-bit, Windows 7 64-bit, Mac OS X 10.8.5 and Ubuntu 12.04 32-bit

STR
*prequisite: user has a Firefox account
1. Launch Firefox with clean profile.
2. Log in using a Firefox account.
3. Go to about:preferences#sync and click "manage Account"
4. On The Firefox accounts page, click "Change" at each of the available options
5. Close them one by one.
6. Play a bit with them (open/close them)

Expected Results
Each action is correctly performed.

Actual results
The browser becomes unresponsive after a few moments.

Additional notes:
Reproducing with latest Nightly (20160111030207), latest DevEdition (20160112004003) and Firefox 43.0.4 (20160105164030).
This is intermittent, searching for a regression will require additional time.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1238961#c4
