### ISSUE TITLE
The FXA settings are overlapping the Add account picture screen [bz1238962]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3428]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238962

Reproduced with Firefox 44.0b8 (build ID 20160111185352) on Ubuntu 12.04 32-bit

STR
*prequisite: user has a Firefox account
1. Launch Firefox with clean profile.
2. Log in using a Firefox account.
3. Go to about:preferences#sync and click "manage Account"
4. Click "Add" an account picture.
5. Click anywhere outside the pop-up.
6. Hover over the pop`up.

Expected Results
The UI is properly displayed, no glitches can be seen.

Actual results
The add picture screen is filled with glitches.
Screenshot: http://i.imgur.com/5oxrbUM.jpg

Additional notes:
Reproducing with latest Nightly (20160111030207), latest DevEdition (20160112004003) and Firefox 43.0.4 (20160105164030).
This is a regression, it does not reproduce on Firefox 36.
Will track down a regression range as soon as time permits.

**Comment by shane-tomlinson** [comment]
I have been unable to repro this. Can anybody else?

**Comment by vladikoff** [comment]
Not able to repro even on 32-bit versions of ubuntu and various. Closing until we get more information and bette repro steps.
