### ISSUE TITLE
Add a treatment for Mailcheck experiment that remove blur requirement

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3430]
So that I can fix more typos, as a Firefox Account registrant, I want to know more when I have mistyped a domain before I focus elsewhere.

![treatment3](https://cloud.githubusercontent.com/assets/68213/12618106/7c276b14-c4e0-11e5-8927-b8b240cbf7c7.png)

Shown with styling from proposed treatment2, though we could do for both visual styles.

Related: https://github.com/mozilla/fxa-content-server/issues/3401

**Comment by rfk** [comment]
I suggest we merge this and #3401 into a "mailcheck, take two" feature effort, so that we can keep track of all the changes and prioritize the work appropriately.  I even made a card for it in Aha: https://mozilla.aha.io/features/FXA-79

**Comment by rfk** [comment]
There could be some interesting details to this, e.g. how do we detect that it's time to validate the email?  Do we wait for the user to stop typing briefly before kicking off the check, or do we validate it on each keypress and show the suggestion whenever we think there's a match?

**Comment by ryanfeeley** [comment]
@rfk I'm going to guess that it's a hairy enough of a problem that a library already exists to solve it.

**Comment by ryanfeeley** [comment]
But if I had to take a crack at it, I would start with one that simply looked for ".com" to appear after a "@" character. That will catch many of them.

**Comment by rfk** [comment]
Merging the mailcheck issues into a feature card at https://github.com/mozilla/fxa/pull/128, so closing out here

**Comment by ryanfeeley** [comment]
@rfk Is this coming back?

**Comment by rfk** [comment]
Yep.  It's in our Q2 list in Aha (FxA-79) so let's discuss and prioritize in the product meeting on Friday.
