### ISSUE TITLE
Both `fxaccounts:delete` and `fxaccounts:delete_account` WebChannel messages sent

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3432]
Fx Desktop expects `fxaccounts:delete`, Fennec expects `fxaccounts:delete_account`.

[fxaccounts:delete](https://github.com/mozilla/fxa-content-server/blob/cad9b095044a00bc136e1be65da6766153b3d516/app/scripts/lib/channels/notifier.js#L24-L27) is sent from the notifier [via user.js](https://github.com/mozilla/fxa-content-server/blob/cad9b095044a00bc136e1be65da6766153b3d516/app/scripts/models/user.js#L210).
[fxaccounts:delete_account](https://github.com/mozilla/fxa-content-server/blob/cad9b095044a00bc136e1be65da6766153b3d516/app/scripts/models/auth_brokers/fx-sync-web-channel.js#L23) is sent from the WebChannel brokers.

Luckily, both messages are sent, though from different locations. This should be unified.

Ref #3419, #3431

**Comment by shane-tomlinson** [comment]
#### Fennec and Desktop expect different messages:

<img width="552" alt="screen shot 2016-01-27 at 18 33 48" src="https://cloud.githubusercontent.com/assets/848085/12624188/9e253936-c525-11e5-9b03-804ca4bd6298.png">

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/3240 ?

**Comment by shane-tomlinson** [comment]
@vladikoff - yup, thanks. I'm going to close the other one because this has more detail.

**Comment by shane-tomlinson** [comment]
From https://github.com/mozilla/fxa-content-server/issues/3240#issuecomment-153032896:

> We should move FxA -> browser WebChannel commands into a shared module so we can avoid these discrepancies.
