### ISSUE TITLE
Reload of https://accounts.firefox.com/unexpected_error should reload '/' to get back to normal

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3434]
STR
- Load https://accounts.firefox.com/unexpected_error
- Hit reload in the browser

Expected: try to reload something other than `/unexpected_error`
Actual: user can't bail from a transient error with a simple reload

I think we all expect that a reload should get back to usable UI after hitting some transient error, but this page is a dead end. (Yeah, they can hit `HOME`, but I think it's easy to look past that option.)

**Comment by shane-tomlinson** [comment]
Hey @ryanfeeley - any thoughts on the UX for making this happen?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Ideally there is no such destination as /unexpected_error, merely that the content can load into the current page a user is on. That way, hitting refresh might work. Make sense?

**Comment by vladikoff** [comment]
>@shane-tomlinson Ideally there is no such destination as /unexpected_error, merely that the content can load into the current page a user is on. That way, hitting refresh might work. Make sense? 

Even then (if the `unexpected error` content is loaded into the page) after the user sees this they can refresh and get back to `/`?

**Comment by ryanfeeley** [comment]
@vladikoff Yes.

**Comment by vladikoff** [comment]
This was fixed via https://github.com/mozilla/fxa-content-server/issues/3715
