### ISSUE TITLE
Is force_auth unnecessarily mixing-in some mixins?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3437]
`force_auth` extends `sign_in`.

`Cocktail` mixes in non-destructively.

Therefore it seems unnecessary for `force_auth` to mix-in `PasswordMixin` and `SignedInNotificationMixin`, which are already mixed-in by `sign_in`. Perhaps I'm wrong though and there is good reason. Needs looking at.

**Comment by shane-tomlinson** [comment]
From IRC: 
> The last mixin that force_auth has is the PasswordResetMixin, looking at the PasswordResetMixin, it mixes in ResumeTokenMixin, which is already on the sign_in view too. Could that cause problems?
