### ISSUE TITLE
password-mixin.js->isPasswordAutoCompleteDisabled - no longer needed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3440]
As outlined in #2373, Firefox no longer respects `autocomplete=off`. [password-mixin.js-.isPasswordAutoCompleteDisabled](https://github.com/mozilla/fxa-content-server/blob/8c7a52148738f6a824b45532ff5f93627eb86d00/app/scripts/views/mixins/password-mixin.js#L26:L31) returns `true` if the relier is Sync. Since `autocomplete=off` is no longer respected, we might as well remove this function, any references to it, and any references to `autocomplete=off` on password fields.

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1173688

cc @rfk, @ckarlof.

**Comment by shane-tomlinson** [comment]
FWIW, Firefox has regressed and again asks to save the FxA password on both the firstrun page and from about:accounts

<img width="627" alt="screen shot 2016-01-28 at 12 14 13" src="https://cloud.githubusercontent.com/assets/848085/12644175/eac60af2-c5b8-11e5-8451-00869e4abab0.png">
<img width="457" alt="screen shot 2016-01-28 at 12 09 22" src="https://cloud.githubusercontent.com/assets/848085/12644176/edacec54-c5b8-11e5-9911-246b49513797.png">

**Comment by shane-tomlinson** [comment]
Firefox asking to save the password is now the expected behavior, so the above comment is not relevant. 

That also makes this work even more worthwhile. Dead code is code that drags us down.

**Comment by rfk** [comment]
:+1:

**Comment by vladikoff** [comment]
No longer needed!

**Comment by feelcoder** [comment]
@vladikoff as I'm working on issues #3507, which is still related to password, I might as well work on this. Is it a good idea?
