### ISSUE TITLE
Some os_family metrics are reporting as simply "windows"

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3445]
Some versions of Windows appear with their number (e.g. XP, 7, etc.) but there is one that is simply "windows"
![d85a4388b63d776532fcfe744d6a3e0723a6f3fe](https://cloud.githubusercontent.com/assets/68213/12658780/14bbc0fc-c5d9-11e5-81b4-5e453f86a859.png)
What is it? Are we logging something incorrectly?

**Comment by vladikoff** [comment]
I think it might be because `ua-parser`  does not support Windows 10 https://github.com/tobie/ua-parser/pull/476/files

**Comment by ryanfeeley** [comment]
I wondered if this would be a problem for when "Windows 11" comes out, but it looks like it may never come out: http://www.techradar.com/us/news/software/operating-systems/microsoft-confirms-there-will-be-no-windows-11-1293309
Should I close this issue?

**Comment by rfk** [comment]
From the closed-ness of the linked ua-parser issue, should we expect the latest release of ua-parser to properly handle windows 10, or do we need to somehow upgrade to a newer or renamed version?  Let's keep this issue going to figure that out.
