### ISSUE TITLE
Baseline measurements for `loaded` and `requestEnd`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3448]
Create baseline, pre-CDN measurements for the `loaded` internal event and `requestEnd` navigationTiming event. Measure the quartiles,, 95%, and mean.

**Comment by shane-tomlinson** [comment]
Ref #3101

**Comment by shane-tomlinson** [comment]
ref #3457, #3468

**Comment by vladikoff** [comment]
closing, graph exists, will check graph
