### ISSUE TITLE
investigate poor time-to-be-usable performance on firstrun page

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3450]
I don't have the fastest internet connection, but fast enough. But if I'm using that network for other things, and then startup firefox on a new profile, it takes about 6 seconds to show usable form fields, which is not a great user experience.

Easy enough to reproduce:
1. in Preferences->Advanced->Network and clear Cached Web Content
2. open a new tab and show Tools->Web Developer->Network
3. load https://www.mozilla.org/en-US/firefox/44.0/firstrun/
4. Use a low speed network (real/simulated) and watch the UI and then check the network timings

**Comment by rfk** [comment]
IIUC the metrics we'll be gathering for the CDN work will provide a good first approximation of the timing here, and give us a concrete starting point to work from  (ref https://github.com/mozilla/fxa-content-server/issues/3448)

**Comment by shane-tomlinson** [comment]
&lt;rant&gt;Poor performance is not limited to the firstrun flow. We have ignored performance so far and now our load time suffers. We send a lot of resources (JS, fonts, CSS), and we make a lot of unnecessary requests. Some requests should be combined or eliminated (`/config`, client.json, experiments.bundle.js); a delay the response of any of these slows down render. We don't use SPDY or HTTP/2 so no connection multiplexing. Our main js bundle is 658KB, 225KB w/ gzip. We add libraries w/o thinking about the repercussions. We have multiple versions of some libraries (p-promises for example). We have dead code that's not used (large portions of jQuery, some portions of jQuery UI). All the code for /settings is included for /signup and /signin, without being necessary. All the code for generating assertions and other crypto is in the main bundle even though it's not needed until later. Not only does the JS behemoth have to be downloaded, it must then be parsed in its entirety.&lt;/rant&gt;

**Comment by rfk** [comment]
There's a lot of work to do, but I'm hopeful that the motivating power of graphs can help us here.  If we had a prominent plot of load times creeping up and up and up, we may have been more incentivized to avoid decisions like that in the past.  Once we have one that we can watch creeping back down, we'll feel good about prioritizing this kind of work in the future.

That's my hope at least :-)

**Comment by shane-tomlinson** [comment]
I just realized there is another contributing factor to the poor firstrun performance. The firstrun page sets the `src` attribute of the FxA iframe dynamically, using JS, I beleive after the rest of the page has loaded. I believe this was done so that they are guaranteed to have a postMessage event handler listening for our `ping` message. 

The TLDR - our perceived performance is negatively affected by their performance.

**Comment by jrgm** [comment]
Still takes 6 or more seconds for same STR.

**Comment by shane-tomlinson** [comment]
> Still takes 6 or more seconds for same STR.

Yup.

**Comment by vladikoff** [comment]
Should be fixed via:

https://github.com/mozilla/fxa-content-server/commit/053153e
https://github.com/mozilla/fxa-content-server/commit/c1f5260
+ CDN
