### ISSUE TITLE
Add hover states to avatar upload buttons

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3451]
Follow-up issues from @jstrutz in https://github.com/mozilla/fxa-content-server/pull/3379:
"""
I notice that the buttons for this dialog don't have any hover or pointer-down states, which leaves it feeling a little unresponsive.
"""

**Comment by vladikoff** [comment]
@ryanfeeley will investigate the svg magic

**Comment by ryanfeeley** [comment]
Can be applied with filters.

HOVER
filter: hue-rotate(3deg) saturate(1.1) brightness(.85); 

ACTIVE
filter: hue-rotate(3deg) saturate(1.1) brightness(.75);

**Comment by ryanfeeley** [comment]
Ready for someone to do this @rfk? Filter works for this.
