### ISSUE TITLE
Guard against empty redirectURI in oauth client config

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3452]
Over in https://github.com/mozilla/fxa-oauth-server/issues/384 we saw an OAuth relier whose redirectURI was the empty string, and it caused us to get into a weird state trying to redirect to ourselves.  While this *should* never happen, it seems worth putting in a bit of defensive programming around the oauth client config to ensure we can give good error messages if it does.

**Comment by shane-tomlinson** [comment]
I understand the reasoning, though I think if the data hits the content server, it's already too late. Input errors like should be guarded against early in the process, on the oauth console and oauth server. This shouldn't stop us from adding validation anyways. #2025 is already on file to validate OAuth query params.
