### ISSUE TITLE
functional test failure on master: sign_up - sign up with a verified account forces the user to sign in

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3461]
× firefox on any platform - sign_up - sign up with a verified account forces the user to sign in (1.206s)
AssertionError: expected '' to equal 'signin0.9366139306221157@restmail.net'
  at Function.assert.equal  <node_modules/intern/node_modules/chai/chai.js:2028:10>
  at Command.<anonymous>  <tests/functional/sign_up.js:317:24>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at <tests/functional/sign_up.js:315:16>
  at onSettled  <app/bower_components/fxa-js-client/fxa-client.js:1312:9>
  at Immediate.flush [as _onImmediate]  <app/bower_components/fxa-js-client/fxa-client.js:1019:6>
  at processImmediate [as _immediateCallback]  <timers.js:383:17>

**Comment by shane-tomlinson** [comment]
This problem only manifests when using the newest Selenium WebDriver (2.50.1), with 2.47.1, tests pass all the time. With 2.50.1, the click on the signin link occurs before the link is fully displayed, so the page does not transition.

**Comment by vladikoff** [comment]
Crazy!

**Comment by vbudhram** [comment]
Running with Selenium 2.48.2 and get similar error.

**Comment by vbudhram** [comment]
I think this might be a timing issue with the error animation on the page. Putting a `sleep` before polling for anchor tag resolves the issue. See [here](https://github.com/mozilla/fxa-content-server/pull/3469/files#diff-babcde6a15e74fb6e482120dca2549aeR115).

Could possibly be related to circleci test failing [issue](https://github.com/mozilla/fxa-content-server/issues/3373).

**Comment by vladikoff** [comment]
> I think this might be a timing issue with the error animation on the page. Putting a sleep before polling for anchor tag resolves the issue. See here.

visibleByQSA should take care of that, sadly we cannot use `.sleep` to fix this because it will create more inconsistency with slow loading pages

**Comment by shane-tomlinson** [comment]
> visibleByQSA should take care of that, sadly we cannot use .sleep to fix this because it will create more inconsistency with slow loading pages

The thing I realized about `visibleByQSA` is that it resolves as soon as even one line is visible. I thought we might be able to use the `data-shown` attribute, but that's added at the [beginning of the animation instead of the end](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/base.js#L42).

**Comment by vladikoff** [comment]
> The thing I realized about visibleByQSA is that it resolves as soon as even one line is visible. 

I think if can try adding an option for the height of the error bar into it https://github.com/mozilla/fxa-content-server/blob/af41a82c849a9562ea8199e348f893d556526055/tests/functional/lib/helpers.js#L187

changing `offsetWidth` to height of the error bar, this way the link is clickable

**Comment by vladikoff** [comment]
we need a new helper that uses the old helper with offsetWidth
