### ISSUE TITLE
Unexpected border around the marketing section of `/ready` in the firstrun flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3471]
STR

1. Sign up from the firstrun flow. Keep the tab open.
1. Verify the email in a different tab/browser.
1. Go back to the tab from step 1.

![screen shot 2016-02-03 at 14 01 14](https://cloud.githubusercontent.com/assets/848085/12790381/e643dd52-ca99-11e5-95c9-a2edb2f2bf03.png)

**Comment by shane-tomlinson** [comment]
cc @jpetto - it looks like there is now 20px of padding on the `.fxaccounts` element:

<img width="1129" alt="screen shot 2016-02-03 at 17 51 42" src="https://cloud.githubusercontent.com/assets/848085/12791427/0dbf6a22-ca9f-11e5-9a7d-c9957c385abe.png">

**Comment by shane-tomlinson** [comment]
This is a problem on the bedrock end, https://bugzilla.mozilla.org/show_bug.cgi?id=1245573 has been opened. Closing here.

**Comment by jpetto** [comment]
The [fix was just merged](https://github.com/mozilla/bedrock/pull/3871) and should go out to prod today.

**Comment by shane-tomlinson** [comment]
Thanks @jpetto!
