### ISSUE TITLE
postMessage origin error on /firstrun signup form using FF 37.0a1

### ISSUE THREAD

**Issue by alexgibson** [mozilla/fxa-content-server#3473]
Using the latest Nightly, visiting this page: https://www.mozilla.org/en-US/firefox/47.0a1/firstrun/

Error in the console:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.allizom.org') does not match the recipient window's origin ('https://www.mozilla.org').
```

I don't see the same error using Firefox 44.

**Comment by shane-tomlinson** [comment]
Also talked about in #3465.

This is known about, copying text from IRC:

```
22:53 <stomlinson> jrgm: Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.allizom.org') does not match the recipient window's origin ('https://www.mozilla.org'). accounts.firefox.com
22:53 <stomlinson> jrgm: from the link rfkelly just posted.
22:54 <•rfkelly> oof
22:54 <stomlinson> jrgm: that message is courtesy of a patch jburke had merged yesterday.
22:55 <•rfkelly> why is it talking to allizom?
22:56 <stomlinson> ahha, it's sending a postMessage to both www.mozilla.org and www.allizom.org, the 2nd for testing purposes.
22:58 <stomlinson> rfkelly: we send the message to all origins in allowed_parent_origins at once to avoid delaying startup too much. everything is as expected, ignore me. Just a new warning message that scared me.
```

It occurs because this patch landed in Firefox a few days ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1139849

**Comment by rfk** [comment]
IIRC, @shane-tomlinson proposed fixing this by requiring iframed reliers to pass in their expected origin as a query parameter.  This will allow us to to stricter checking *and* avoid having to postMessage out to multiple origins in an attempt to discover which one is live.

**Comment by shane-tomlinson** [comment]
> IIRC, @shane-tomlinson proposed fixing this by requiring iframed reliers to pass in their expected origin as a query parameter. This will allow us to to stricter checking and avoid having to postMessage out to multiple origins in an attempt to discover which one is live.

Yes, and since we already rely on node to serve index.html, and with no plans to change this, updating how we do the origin check will be all the more awesome.

**Comment by vladikoff** [comment]
Related to #2606

**Comment by shane-tomlinson** [comment]
This will go away once #2606 is fixed. Closing here.
