### ISSUE TITLE
Sentry: move the release version from the server component

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3474]
Sentry: move the release version from the server component to the js file during build. 

This way when production will not get out of sync when DNS changes but the page has the old code.

**Comment by shane-tomlinson** [comment]
The client could somehow report its version to Sentry.

**Comment by shane-tomlinson** [comment]
This is especially important during DNS crossover where clients have old code, but error reports are sent to a server w/ new code.
