### ISSUE TITLE
Stop skipping the first step of reset password for force auth users

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3477]
CURRENT:
When users are forced to authenticate, they have the option to reset their password. Currently this skips the first screen and sends the reset email directly. This is problematic because many users don't understand the ramifications of resetting their password (and potentially losing sync data).

PROPOSED:
Take them to the Reset Password form with their email filled in, read-only.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm putting this in backlog for now, but please bump if you want this prioritized.

**Comment by ryanfeeley** [comment]
If I'm reading DataDog correctly, it looks like 43.8% of users are logging in via force_auth. If that's the case, does that bump it up?

**Comment by rfk** [comment]
> it looks like 43.8% of users are logging in via force_auth

This seems extraordinarily high, @ryanfeeley which graph are you looking at for this number?

**Comment by ryanfeeley** [comment]
@rfk Check DataDog login dashboard for the cart "T: % of users are being denied a passwordless login by our sess…"

**Comment by rfk** [comment]
IIUC that graph's not specific to the force_auth view; it's about whether we can give you this nice one-click-to-login view:
![screen shot 2016-02-09 at 12 23 00](https://cloud.githubusercontent.com/assets/34695/12905047/f106f232-cf27-11e5-93a5-f6a5d8ac89db.png)

Or this less nice one that makes you re-enter you password:
![screen shot 2016-02-09 at 12 23 06](https://cloud.githubusercontent.com/assets/34695/12905051/f74086ea-cf27-11e5-8470-805424b6be1c.png)

**Comment by shane-tomlinson** [comment]
> IIUC that graph's not specific to the force_auth view; it's about whether we can give you this nice one-click-to-login view:

@ryanfeeley - @rfk is correct. "T: % of users are being denied a passwordless login by our sess…" is only for the `/signin` page where users who originally sign up/in for Sync and we would expect to not to have to enter their password must for some unfortunate reason enter their password. Users on `/force_auth` by default are denied a passwordless login and do not count towards this.

**Comment by shane-tomlinson** [comment]
> is only for the /signin page where users who originally sign up/in for Sync and we would expect to not to have to enter their password

Ref #1195, #2391, #2662

**Comment by shane-tomlinson** [comment]
ref #3419
