### ISSUE TITLE
Choose what to Sync is inconsistent order

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#3478]
It looks like "Passwords", "Add-ons", and "History" aren't consistently ordered in FxA web vs <about:preferences#sync>

<img width="493" alt="preferences" src="https://cloud.githubusercontent.com/assets/557895/12833339/f5411ade-cb54-11e5-88db-8d255c4b0acc.png">

<img width="480" alt="firefox_sync_and_heka_dashboard" src="https://cloud.githubusercontent.com/assets/557895/12833328/e1bc7e54-cb54-11e5-8855-60324411282d.png">

**Comment by vladikoff** [comment]
Yeah it is because Add-ons and Prefs do not show on Fennec
Also with long l10n names it is 1 column in the web view

**Comment by vladikoff** [comment]
related to https://github.com/mozilla/fxa-content-server/pull/3247
