### ISSUE TITLE
Play Store logo is out of date

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3482]
Oops, I complained to the website team ages ago about this on mozilla.org and we have the same issue.
<img width="538" alt="old-google" src="https://cloud.githubusercontent.com/assets/68213/12859158/461a2edc-cc22-11e5-9355-c0caa94a9e83.png">

**Comment by vladikoff** [comment]
@jpetto do you have new icons for https://github.com/mozilla/fxa-content-server/tree/master/app/images/google_play_store_button ?

**Comment by jpetto** [comment]
All current Google Play badges were downloaded from [Google's generator](https://play.google.com/intl/en_us/badges/), which now appears to have far fewer language options. We'll have to make some decisions on how to handle the scaled back locale support.

I need to pull them down for mozilla.org anyway, and when I do I'll file a PR to update those in this repo.

**Comment by vladikoff** [comment]
Thanks!

Sad to hear about missing language options, but oh well. Maybe those will just use the old logo

**Comment by vladikoff** [comment]
Looks like the google badge is changing again in the next few days:

![image](https://cloud.githubusercontent.com/assets/128755/14503398/ee74f9dc-017d-11e6-84da-897436b1cafd.png)

**Comment by ryanfeeley** [comment]
@vladikoff Let's host a logo party!

**Comment by vladikoff** [comment]
Ok this was updated with more languages now: https://play.google.com/intl/en_us/badges/

**Comment by ryanfeeley** [comment]
@vladikoff Is this really not actionable? Perhaps combin with: https://github.com/mozilla/fxa-content-server/issues/3697

**Comment by vladikoff** [comment]
@ryanfeeley  from:

> I need to pull them down for mozilla.org anyway, and when I do I'll file a PR to update those in this repo.

I marked this `not actionable` because we were waiting for that ^
