### ISSUE TITLE
easterEgg should autmatically disable itself if it's in an iframe

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3483]
I got a ReferenceError trying to disable the easteregg in the dev console:

![screen shot 2016-02-06 at 13 40 22](https://cloud.githubusercontent.com/assets/34695/12864177/3e48a8c2-ccd7-11e5-9eee-b67143a19dce.png)

**Comment by shane-tomlinson** [comment]
> I got a ReferenceError trying to disable the easteregg in the dev console:

From the firstrun flow or about:accounts? If so, there is no way to reach in to the iframe to access `easterEgg`

**Comment by vladikoff** [comment]
Possible solution: let the easter egg detect if it is in the iframe and not show itself?

**Comment by shane-tomlinson** [comment]
> Possible solution: let the easter egg detect if it is in the iframe and not show itself?

Might be a good option. Another is to show it once or twice and auto-disable?

**Comment by vladikoff** [comment]
(Plot twist: `ReferenceError` is the **real** easter egg)

**Comment by rfk** [comment]
I don't recall, but it was probably from the first-run flow while I was digging around in there last week.

**Comment by rfk** [comment]
> Another is to show it once or twice and auto-disable?

If nobody objects, let's do this one; changing bug title appropriately.

**Comment by pdehaan** [comment]
I'm not sure what "has been shown a few times" means. Are we just blindingly `console.log()`ing the first X times a user visits FxA? Or are we going to be clever and try and detect if the DevTools are open and only THEN show the easterEgg and increment the counter?
(Related https://github.com/sindresorhus/devtools-detect)

I think that if we're just going to show the easter egg ~3 times regardless of if the user sees said easter egg, we should just bite the bullet now and remove the easter egg path completely.

**Comment by rfk** [comment]
Sounds complicated.  I don't like complicated, let's do a simple thing instead: https://github.com/mozilla/fxa-easter-egg/pull/17
