### ISSUE TITLE
If a relier passes in an email parameter, check to see what an account exists for that email to choose between "signin" and "signup" views

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3489]
amo migration: check if email exists, redirect to proper view

@ryanfeeley @rfk what do we put here exactly?

**Comment by vladikoff** [comment]
@rfk @vbudhram to chat about this

**Comment by ryanfeeley** [comment]
Follow the red line past NO AMO https://raw.githubusercontent.com/mozilla/addons/master/docs/images/fxa-migration.png

**Comment by rfk** [comment]
@ryanfeeley your link reminded me, AFAIK the screen that says "This account already exists on AMO. Why?" is not implemented and not captured by outstanding work either here or in AMO.  Is it still something you want to move forward with?  If so we'll need to coordinate with AMO to figure out an implementation plan.

**Comment by ryanfeeley** [comment]
It was in the original acceptance criteria: "When they change their email to one that already exists in FxA or AMO, they see the message This account already exists on Mozilla Add-ons." and I don't see how we can do without it. If the user has gotten this far in the migration, we should make sure they don't fall off the cliff.

**Comment by shane-tomlinson** [comment]
>  "When they change their email to one that already exists in FxA or AMO, they see the message This account already exists on Mozilla Add-ons." 

I'd like to push back - why is this check necessary? What new information does the message give the user? I'm being obstinate because this makes FxA depend on AMO, and every additional dependency turns into a maintenance headache.

**Comment by shane-tomlinson** [comment]
>  What new information does the message give the user?

Perhaps an alternative question is, is that an end state in itself, and if so, why? What are we attempting to guard against? What alternatives were considered?

**Comment by ryanfeeley** [comment]
@shane-tomlinson AMO accounts have account data—contributed addons, reviews, profiles. These accounts can be either of the original AMO account type or FxA accounts on AMO. So if a user tries to migrate their old AMO account into an already existing AMO.FxA account, it's a collision that I don't imagine can be resolved because the accounts have their own account data. Don't we need an error message at least?

**Comment by rfk** [comment]
FTR, I strongly agree with @shane-tomlinson that displaying this error state should be AMO's responsibility, not FxA's, because the alternative is a bi-directional data dependency that will add lots of complexity (ref https://github.com/mozilla/addons/pull/9#issuecomment-159094865)

**Comment by rfk** [comment]
I should not have started this discussion as a tangent in another issue.  Redirecting to a fresh issue for further discussion, so we can keep this one focused on what its title says: https://github.com/mozilla/fxa/issues/118

**Comment by rfk** [comment]
ref https://github.com/mozilla/fxa-auth-server/issues/1176

AFAICT the content-server-side logic should be:

* If we're on the root `/oauth/` view, and hence need to pick which form to present
* And we've been provided an email address in the `email` query parameter
* And there's no local browser state to tell us we should go to the signin view
* Then call the auth-server to check whether an account exists for that email, and
    * If an account does exist, show the signin view
    * If an account doesn't exist, show the signup view
    * If there's an error checking, do whatever it is we already do
