### ISSUE TITLE
implement SMS Install Link form

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#3497]
Feature: https://github.com/mozilla/fxa/tree/master/features/FxA-46-sms-install-link

This form should appear on the success (post_verification) page when the browser is from a desktop. Design to be provided in https://github.com/mozilla/fxa/issues/119

The submit action of the form should send the phone number to Basket, `/news/subscribe_sms`.

**Comment by rfk** [comment]
> The submit action of the form should send the phone number to Basket, /news/subscribe_sms.

I wonder if it's useful to proxy this call through our own backend servers, so we can emit metrics about it.  We might even want to record a "this user requested an sms link" flag of some sort, so that when they later connect a mobile device, we can properly attribute that to the use of the link.

**Comment by vladikoff** [comment]
from triage: @rfk do we keep this open ?
