### ISSUE TITLE
Reject sending emails to domains that don't receive email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3500]
Before we check to see if an email bounces, we should check to see if the domain even has an MX record configured to receive email. If users enter an email for a domain that does not receive email, we should present this error message.
![no-mx](https://cloud.githubusercontent.com/assets/68213/12981584/490be662-d0af-11e5-8c63-159538d02d68.png)

**Comment by rfk** [comment]
I really like this idea.  Closing it here in favour of a "feature card" over in https://github.com/mozilla/fxa/pull/123, to make it easier to prioritize.
