### ISSUE TITLE
Password length warning does not disappear after entering valid password

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#3507]
CURRENT:

1. From http://accounts.firefox.com/signup
2. Enter email, start typing password
3. Password warning appears
4. User enter's a password longer then the minimum, warning still visible
5. Warning disappears on blue

![screen shot 2016-02-12 at 3 07 15 pm](https://cloud.githubusercontent.com/assets/1295288/13018910/62f6ca6a-d19a-11e5-8142-cf99664fb6d1.png)

EXPECTED:

1. As the user is typing password and exceeds the minimum length, password warning disappears

**Comment by ryanfeeley** [comment]
@vbudhram Nice catch! Should also reappear if edited below 8 again.

**Comment by shane-tomlinson** [comment]
From @ryanfeeley - it should only show if the field is focused and the password is < 8 chars.

**Comment by feelcoder** [comment]
This is a nice issue. I think I will work on it

**Comment by vladikoff** [comment]
@feelcoder Awesome! It seems like this is only controlled by CSS here for now: https://github.com/mozilla/fxa-content-server/blob/master/app/styles/modules/_input-row.scss#L77 so we might need to add some JavaScript logic to this. 

To make sure it works on all password fields with the "Must be at least 8 characters" you might findthe `password-mixin` file useful: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/password-mixin.js file.

**Comment by feelcoder** [comment]
@vladikoff  I've looked at those file, Still working on it since and pretty much new in mustache.js. Understanding how the javascript object are being called using mustache.js

**Comment by ryanfeeley** [comment]
@feelcoder Glad to have you on this!

**Comment by TDA** [comment]
@vbudhram I believe this issue is not present right now on master. If you can confirm, we can close this.

**Comment by vbudhram** [comment]
@TDA this was fixed in https://github.com/mozilla/fxa-content-server/pull/3739, closing.

**Comment by TDA** [comment]
@vbudhram Awesome! Thanks Vijay!
