### ISSUE TITLE
OAuth relier's privacy_uri and terms_uri are not displayed anywhere

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3513]
Ref #3426 

`privacy_uri` and `terms_uri` are [imported from client information](https://github.com/mozilla/fxa-content-server/blob/2248a662cd6de1b12eaa734629d4d75495ef2c20/app/scripts/models/reliers/oauth.js#L169:L170) received from the OAuth server. These values are [passed to the permissions template](https://github.com/mozilla/fxa-content-server/blob/2248a662cd6de1b12eaa734629d4d75495ef2c20/app/scripts/views/permissions.js#L35:L37), but then [never used](https://github.com/mozilla/fxa-content-server/blob/2248a662cd6de1b12eaa734629d4d75495ef2c20/app/scripts/templates/permissions.mustache).

**Comment by rfk** [comment]
Aye, we added these in a flurry of activity during the Pocket integration, and then it turned out we didn't need them.  Perhaps we should just remove them from the API unless and until they actually come into play again in the future?

**Comment by shane-tomlinson** [comment]
> Perhaps we should just remove them from the API unless and until they actually come into play again in the future?

Yes, less API surface area, less code to become confused about.
