### ISSUE TITLE
Grey border around iframe content on Fx 46+

### ISSUE THREAD

**Issue by jpetto** [mozilla/fxa-content-server#3516]
On Fx 46+ (which now sets [`context=fx_firstrun_v2` in the iframe URL](https://github.com/mozilla/fxa-content-server/pull/3418)), a grey border is visible around the iframe content. The border appears to be applied to the `#main-content` element.

cc @ryanfeeley 

![screen shot 2016-02-17 at 4 35 51 pm](https://cloud.githubusercontent.com/assets/317532/13127419/d5cca91c-d594-11e5-87a6-fb1ea65aeb46.png)

**Comment by shane-tomlinson** [comment]
@jpetto - looking at that page, I don't see `service=sync`, only `context=fx_firstrun_v2`. `service=sync` is required too.

**Comment by jpetto** [comment]
Hm, I'm seeing `service=sync` in the URL. Copied from 46.0a2's dev tools:

```
https://accounts.firefox.com/?utm_campaign=fxa-embedded-form&utm_medium=referral&utm_source=accounts-page&utm_content=fx-&entrypoint=accounts-page&service=sync&context=fx_firstrun_v2&style=chromeless&haltAfterSignIn=true
```

It's also [in the template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/accounts.html#L42).

**Comment by shane-tomlinson** [comment]
Support for `fx_firstrun_v2` is part of [train-56](https://github.com/mozilla/fxa-content-server/commit/552b24d66bc2c98c2c6a60a42d88577441254c36#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR31), which should go out today! Without that support, `chromeless` is ignored and the border is displayed.

**Comment by vladikoff** [comment]
:+1:
