### ISSUE TITLE
Cannot upload profile image - A usable image was not found

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3519]
STR
1. With latest.dev.lcip.org or accounts.stage.mozaws.net, sign up for an account and verify email.
2. In account profile, try to add an account picture
3. Click '+ Upload', and pick a valid image file from local disk. 
4. Click Open or Ok in the filepicker

Expected: image is uploaded into browser dom and can be adjusted 
Actual: error message: "A usable image was not found"

This blocks releasing train-56. The above STR work with current production code.

**Comment by rfk** [comment]
Code delta for avatar-related stuff:

```
$ git diff v0.55.2..master app/scripts/views/settings/avatar*.js 
diff --git a/app/scripts/views/settings/avatar_change.js b/app/scripts/views/settings/avatar_change.js
index 28c6d27..37e09b2 100644
--- a/app/scripts/views/settings/avatar_change.js
+++ b/app/scripts/views/settings/avatar_change.js
@@ -83,9 +83,7 @@ define(function (require, exports, module) {
           require(['draggable', 'touch-punch'], function () {
             var cropImg = new CropperImage();
             self.navigate('settings/avatar/crop', {
-              data: {
-                cropImg: cropImg
-              }
+              cropImg: cropImg
             });
           });
         }, 1000);
@@ -124,9 +122,7 @@ define(function (require, exports, module) {
               });
               require(['draggable', 'touch-punch'], function () {
                 self.navigate('settings/avatar/crop', {
-                  data: {
-                    cropImg: cropImg
-                  }
+                  cropImg: cropImg
                 });
               });
               defer.resolve();
diff --git a/app/scripts/views/settings/avatar_crop.js b/app/scripts/views/settings/avatar_crop.js
index 4f3cc0d..70daf35 100644
--- a/app/scripts/views/settings/avatar_crop.js
+++ b/app/scripts/views/settings/avatar_crop.js
@@ -28,8 +28,7 @@ define(function (require, exports, module) {
     initialize: function (options) {
       options = options || {};
 
-      var data = this.ephemeralData() || {};
-      this._cropImg = data.cropImg;
+      this._cropImg = this.model.get('cropImg');
 
       if (! this._cropImg && this.broker.isAutomatedBrowser()) {
         this._cropImg = new CropperImage();
```

**Comment by rfk** [comment]
I also see a `model.get('cropImg')` but no instances of a corresponding `model.set('cropImg')`:

```
$ grep -r "model.*cropImg" *
views/settings/avatar_crop.js:      this._cropImg = this.model.get('cropImg');
```

**Comment by rfk** [comment]
So as of https://github.com/mozilla/fxa-content-server/pull/3429, we're passing the image as a model rather than via ephemeral data.  But the avatar crop view is a child view and I think something goes a bit wonky with passing the model through to the child view.

**Comment by rfk** [comment]
This fixes it locally for me, by ensuring that the ChildView gets created with the appropriate Model instance:

  https://github.com/mozilla/fxa-content-server/compare/rfk/hackily-pass-options-to-child-view

But I don't think it's very architecturally sound, so I'll leave a proper PR to the folks who know what they're doing :-)

**Comment by vladikoff** [comment]
Leadfoot was recently updated to support file uploads, we should be able to improve functional testing for the <input> uploader to make sure we test like the real user would. Currently there is some fake upload business going on via the query parameter. See http://stackoverflow.com/questions/28430547/file-upload-in-intern-js for details.

**Comment by shane-tomlinson** [comment]
@rfk - I originally tried the approach your patch uses, this caused breakages with error and success messages, so I went with each child view gets its own model and then copies data back to the parent model when needed. I'll look into this today.
