### ISSUE TITLE
Measure if showing the password results in fewer errors during password change

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3524]
Our change password experience appears to be riddled with user error.
<img width="558" alt="change-password-errors" src="https://cloud.githubusercontent.com/assets/68213/13180452/811b9550-d6f6-11e5-8f6d-922b385bfdbf.png">
We know that more users show the password on this screen than anywhere else the password field appears. Are users more successful when they show the password field?
If so, how much more successful?
When do users show the password field: right away, or only after receiving several errors.
It would be good to have these metrics in place before we experiment with alternative show password UI.

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @shane-tomlinson to chat about this tomorrow.

**Comment by shane-tomlinson** [comment]
@ryanfeeley and I had a chat, about further breaking this down into two steps:

1. Test variations of "show/hide" to see if any affect usage.
1. If one variant is a runaway winner, see if variations of the password shown/hidden w/ that icon affect error (or success) rates.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm only backlogging this because you aren't here to give me designs (and you had better not before you are back from vacation!). Let's pull this out of backlog when you return.

**Comment by shane-tomlinson** [comment]
A better idea - put it in blocked.

**Comment by vladikoff** [comment]
waiting for @ryanfeeley to come back

**Comment by vladikoff** [comment]
TODO: we will compare different metrics in other issues.
