### ISSUE TITLE
cancelling change password does not reset what is typed in "old" or "new" password field

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3526]
STR
- go to change password dialog (with and without a saved password)
- enter (or add) some characters to old password
- enter some characters to new password
- cancel
- go back into change password dialog

Expected: on re-entering change password dialog, I would expect the same initial state as the first time entering. I did **cancel** the previous action, didn't I?
Actual: previous content is retained after a cancel

**Comment by shane-tomlinson** [comment]
This is a subset of #3544, closing.
