### ISSUE TITLE
csp-violation: route.500.Error: request entity too large

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3536]
For 'POST /_/csp-violation'. A number of these from apparently the same user. We do have caps in place to disallow excessively large POSTs. I don't know if we need to adjust the limit (since I don't know if this was an actual CSP report, or what it was, including how long it would it have been).

**Comment by vladikoff** [comment]
Well, there needs to be some sort of limit, so instead this route could throw a 413 and not a 500?

**Comment by jrgm** [comment]
Actually, the logging of errors by csp and metrics is not making any sense. I have 5xx errors that don't name the route. And in principle the bodyParser to produced that `request entity...` text, would also be returning 413. Where does 500 come from?

**Comment by vladikoff** [comment]
Should be fixed for general cases via https://github.com/mozilla/fxa-content-server/issues/3167 
Otherwise csp-violation endpoints are limited in size. Let me know if you see more of these.
