### ISSUE TITLE
Use platform-specific download links in devices view?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3540]
In the initial version of the devices view, we offer "get firefox" links for various platforms, but they all go to the same URL.  Would we be better off using platform-specific URLs, e.g. having android link to https://www.mozilla.org/en-US/firefox/android/ rather than https://www.mozilla.org/en-US/firefox/new ?

/cc @ryanfeeley

**Comment by rfk** [comment]
For context, original advice from was @chrismore in https://github.com/mozilla/fxa/pull/89#issuecomment-159730048

**Comment by ryanfeeley** [comment]
Here is the view count of a typical settings section (will be similar to Devices section) by OS.
<img width="556" alt="screenshot 2016-02-25 16 39 08" src="https://cloud.githubusercontent.com/assets/68213/13335288/54925b62-dbde-11e5-9ef7-c36ae3769b02.png">
I think if we are offering links to iOS and Android, they should be better than to /new.

**Comment by rfk** [comment]
If you visit the current page in a signed-in instance of firefox (which is most likely from the devices view) then you get a message "Congrats! You’re using the latest version of Firefox.".  This isn't likely to drive users to set up firefox on additional devices, so I think we should indeed link to more targeted pages.  Suggestion:

* "Windows", "OSX", and "Linux" point to where they currently do
* "Android" points to https://www.mozilla.org/en-US/firefox/android/
* "iOS" points to https://www.mozilla.org/en-US/firefox/ios/

I assume we can use the same utm_* params etc and just change the target page.

**Comment by vladikoff** [comment]
@ryanfeeley @rfk do we still want to do this?

**Comment by rfk** [comment]
/me defers to @ryanfeeley; although I dont think it's on-theme with any of the things we have planned for Q3

**Comment by ryanfeeley** [comment]
@vladikoff Sure, it's a better experience.

**Comment by vladikoff** [comment]
@ryanfeeley do we have a design where would those links go in the current devices view?

**Comment by ryanfeeley** [comment]
@vladikoff Already in production (just text links). We just want to improve the location when the links point to. 
<img width="544" alt="untitled" src="https://cloud.githubusercontent.com/assets/68213/16455006/dc393d60-3de0-11e6-9d8a-d84a5ddf174d.png">

**Comment by vladikoff** [comment]
> We just want to improve the location when the links point to. 

Oh great, thanks!!

**Comment by vladikoff** [comment]
Make links platform specific.

**Comment by TDA** [comment]
I can take this up!
