### ISSUE TITLE
When users cancel a settings change, forms should be reset

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3544]
When users cancel a settings change, forms should be reset.

1. When users cancel changing their Display Name, the field should reset to the previous value
1. When users cancel changing their password, the password fields should be cleared.
1. When users cancel changing deleting their account, the password field should be cleared.

**Comment by shane-tomlinson** [comment]
This is a superset of what @jrgm pointed out in #3526. Closing that issue in favor of this.
