### ISSUE TITLE
Propagate event metadata to the auth server

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3551]
To facilitate https://github.com/mozilla/fxa-auth-server/issues/1200 and [FxA-70](https://github.com/mozilla/fxa/blob/master/features/FxA-70-kpi-dashboards/README.md#data-capture-and-storage), the front-end must propagate event metadata to the auth server.

Specifically, the existing fields `service`, `context`, `entrypoint`, `campaign` and `migration` are required, as is the new `flowId` that will be created as part of #3550.

Agreement is obviously needed with the auth server as to whether they should be sent in the query string or in the request body.

**Comment by philbooth** [comment]
@rfk, was your plan to calculate `flowTime` as event data gets imported, or should it be set in the event data by the emitter of the event?

If the latter, the PR for this issue will also need to propagate a `flowBeginTime`, so that the other emitters can calculate their `flowTime`.

**Comment by philbooth** [comment]
I think there are enough data items here that we should add them to the request body rather than the query string. There's also talk about possibly sending `utm_*` parameters too, so those mentioned here may not be the final list.

Over in https://github.com/mozilla/fxa-auth-server/issues/1200, it was suggested that the new data could be added under a `metrics_context` parent field.

**Comment by rfk** [comment]
>  should it be set in the event data by the emitter of the event?

^ this one; I think trying to calculate it in the event-processing machinery will be more painful than doing it ourselves.
