### ISSUE TITLE
backport #3554 to branch of v0.57.0 to make tag v0.57.1 for release

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3556]
https://github.com/mozilla/fxa-content-server/pull/3554 changes the copy of error pages into dist where it should be. That has been merged to master.

If this all checks out, then we should cherry-pick or merge from the issue-3549 branch to train-57 to make a v0.57.1 tag for release.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/releases/tag/v0.57.1 :gift:
