### ISSUE TITLE
"Invalid OAuth parameter: %(param)s" error in console when trying to log into site

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#3561]
I was trying to log into testpilot.stage and something is currently misconfigured (not relevant), but while looking at my DevTools console, I noticed that I was getting an unhelpful message of:

> "Invalid OAuth parameter: %(param)s"

![sign_in_to_continue_to_test_pilot_stage_and_fetch_api_and_embedly-proxy_dev_mozaws_net___version__](https://cloud.githubusercontent.com/assets/557895/13507155/43bd131a-e136-11e5-890c-915051e0e4c9.png)

Where main.js:22902 seems to be this:

![sign_in_to_continue_to_test_pilot_stage_and_fetch_api](https://cloud.githubusercontent.com/assets/557895/13507211/8bc267be-e136-11e5-9a5d-8b38a1738500.png)
&mdash; via [/app/scripts/views/base.js:555](https://github.com/mozilla/fxa-content-server/blob/90289d85a66b11de9955b63689bef81b8b063f4b/app/scripts/views/base.js#L555)

**Comment by vbudhram** [comment]
We recently introduced extra validation on OAuth Params, Ref #3469, guessing that is the cluprit. What is the value of scope that is failing? It should be in query params.. Here is a [link](https://github.com/mozilla/fxa-content-server/blob/46cc1addcb504aa69cda3fe11fe5dddfdada4910/app/tests/spec/models/reliers/oauth.js#L320) with some of the test scope values that are valid/invalid. @shane-tomlinson thoughts?

**Comment by pdehaan** [comment]
@vbudhram I think the scope was "" (nada). I was more concerened about that pesky `%(param)s` in my console though.

**Comment by shane-tomlinson** [comment]
ref #3025
