### ISSUE TITLE
surface number of tests failing in functional tests and provide a way to report on chronic failing tests

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3563]
This is a long-standing issue with these tests. We have a regular set of flaky tests, but we're not integrated enough with teamcity/internjs to provide an easy way to see what is failing and how regularly these tests are failing. So a wishlist item to see if we can make better use of these test runs and results.

**Comment by vladikoff** [comment]
A lof of issues block this one, such as ` slowly restarting latest` and fixing the reporter in TeamCity

**Comment by jrgm** [comment]
Addressed `slowly restarting latest` in https://github.com/mozilla/fxa-dev/pull/233, and getting error stacks in the TeamCity reporter in https://github.com/theintern/intern/pull/593.

**Comment by vladikoff** [comment]
The new TeamCity reporter does this now in https://tc-test.dev.lcip.org/ 👍
