### ISSUE TITLE
Adjust robots meta tags

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3565]
According to [1][2] we should add a "noindex" robots tag to our pages in order to prevent them showing up in google search results.  We can do it either by <meta> tag or header, and I see no reason not to do both.  Concretely, we'll need to:

* Change our robots.txt to allow Google to crawl inbound links and see the robots tags
* Add a <meta name="robots" content="noindex, nofollow" /> tag to our base HTML template
* Change the server to send an "X-Robots-Tag: noindex, nofollow" header on all responses

[1] https://www.youtube.com/watch?v=KBdEwpRQRD0#t=196s
[2] https://support.google.com/webmasters/answer/93710

**Comment by vladikoff** [comment]
> Change our robots.txt to allow Google to crawl inbound links and see the robots tags

this should be done here: https://github.com/mozilla-services/puppet-config/issues/1326

**Comment by rfk** [comment]
If I understand the linked bug correctly, we wanted to do it there because we wanted to use a different file in production.  It's not obvious to me whether that's still necessary, or whether a policy of "crawl anything, but index nothing and dont follow any links" is appropriate for all of dev, stage, and prod.

**Comment by rfk** [comment]
Also there's a "fetch as google" thing we can use to check on what Google thinks of our site: https://support.google.com/webmasters/answer/6066468?hl=en&rd=2

**Comment by vladikoff** [comment]
> "crawl anything, but index nothing and dont follow any links" is appropriate for all of dev, stage, and prod.

I was hoping fxa-dev boxes would not be crawled via robots.txt

**Comment by rfk** [comment]
>  I was hoping fxa-dev boxes would not be crawled

This is also fine by me, just want to make sure we're all on the same page

**Comment by vladikoff** [comment]
We had an issue open https://github.com/mozilla/fxa-content-server/issues/1338 but closed it in favour of https://github.com/mozilla-services/puppet-config/issues/1326 Not sure what else we can do on the content-server for this.
