### ISSUE TITLE
Should display warning only when using Sync on Password Reset?

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#3567]
Currently when resetting a user's password, an orange banner is shown with a warning on the consequences of this action, per updated [mockups](https://github.com/mozilla/fxa/tree/master/features/FxA-72-reset-password). The ticket seems to imply that it should be all Firefox account users. Or should this be only for Sync users?

@ryanfeeley Let me know what you think.

Ref: https://github.com/mozilla/fxa-content-server/pull/3559

**Comment by rfk** [comment]
>  Or should this be only for Sync users?

We don't yet have a good way to detect whether someone is a sync user; in practice "all our users are sync users" is currently a pretty good approximation

**Comment by vbudhram** [comment]
Sounds good to me. Closing ticket.
