### ISSUE TITLE
Update functional tests to use new helper methods

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#3568]
There is a lot of boilerplate code in the [functional tests](https://github.com/mozilla/fxa-content-server/tree/master/tests/functional) that could be updated to use the new [functional helper methods](https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/lib/helpers.js#L999).

Example: https://github.com/mozilla/fxa-content-server/pull/3559/files#diff-d439d799790145303d01d7ffb9067c4aL222

**Comment by vladikoff** [comment]
We are slowly converting these a lot of these, let's refactor the test files as needed.
