### ISSUE TITLE
Scope normalization breaks login to Marketplace

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3576]
We hit a snag deploying train-57 of content-server.  Attempts to login to marketplace would fail with a 500 error and the following info in the marketplace logs:

```
oauthlib.oauth2.rfc6749.parameters in validate_token_parameters
Warning: Scope has changed from "profile" to "profile:email profile:avatar profile:display_name profile:uid". 
```

It seems that the default behaviour of the oauth library used by marketplace, is to freak out and throw an error if the scopes requested do not precisely match the ones that are actually granted:

  https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/parameters.py#L401

We broke this with #3509 where we started normalizing "profile" into its constituent sub-scopes, in order to display the consent screen.  I think an appropriate fix is to only do this normalization if we actually need to show to consent screen, but I'll see how that works out in code...

**Comment by jrgm** [comment]
>  Attempts to login to marketplace would fail with a 500 error and ...

Just to be clear for @shane-tomlinson reading this later, this never actually got into production.

**Comment by rfk** [comment]
Indeed, thanks - @jrgm caught this in final QA before putting the deploy live.
