### ISSUE TITLE
"Working…" logged to debug console when pausing on CWTS screen

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3578]
STR:

* In a fresh profile, set up sync and open developer tools debug console
* Create a new account
* On the choose-what-to-sync page, wait around for a while

The "Working..." message will be displayed in the debug console which, although it doesn't seem to cause any harm, is a bit odd.

**Comment by shane-tomlinson** [comment]
Dup of #3527, closing.
