### ISSUE TITLE
CWTS "back" button fails with a security error on Android

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3579]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1254585

STR:

* Open Fennec with a logged-out profile, connect remote debugging tools and open dev console
* Sign in the sync, creating a new account
* On the CWTS page, click "back"

For me, this reliably refuses to go back, and logs a message saying "SecurityError: The operation is insecure".  Subsequent attempts to continue from the CWTS page fail with the same error message.

**Comment by shane-tomlinson** [comment]
This may be due to the call to history.back

**Comment by shane-tomlinson** [comment]
This may be due to the combination of history.back and pushState, visiting the TOS/PP agreements has the same result. I tentatively claim this is a regression due to 6c306e0912874ae3a9bd8eaf430a8aabfb0f335c. 

Ref #3296, #3395

**Comment by rfk** [comment]
@shane-tomlinson I recall you mentioning android in the recent CSP-tweaking work you did, any chance that might have also fixed the issue here?  I guess we can try it out when train-66 ships and see...

**Comment by shane-tomlinson** [comment]
@rfk - this wouldn't be due to CSP, but rather the security model of embedded pages in Fennec. This may have been fixed by 5b87852d though which checks whether pushState can be used before initializing Backbone's history.

**Comment by shane-tomlinson** [comment]
I just tested this on Fennec against https://stomlinson.dev.lcip.org - the back button now works nicely. Closing as fixed by 5b87852d3b3d257d5647a09deabd844c926da94c.

**Comment by vladikoff** [comment]
Yay!
