### ISSUE TITLE
UX review for password reset

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3589]
Implementation of this feature is complete, let's put it up on an fxa-dev box for @ryanfeeley to review.  @vbudhram can you please stand one up and drop the URL here when it's ready?

(I don't recall how much you worked with fxa-dev previously, ping me if you want any help getting a fresh box stood up)

**Comment by ryanfeeley** [comment]
@vbudhram Excited to test this!

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I've assigned this to you since all of the password reset changes have landed in master and you are already in the midst of the review.

**Comment by vladikoff** [comment]
@ryanfeeley to do a review....

**Comment by rfk** [comment]
@ryanfeeley said it shipped so we can close this :-)
