### ISSUE TITLE
validate info populated from the resume token

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3591]
Follow on from #3538.

Info loaded from the ResumeToken should be fully validated. 

If the data is invalid... We should log the error, ignore the invalid fields, and treat the verification as if it occurred in a 2nd browser.

**Comment by rfk** [comment]
@shane-tomlinson to triage

**Comment by shane-tomlinson** [comment]
I'm assigning the initial stab at this to @philbooth since he's already doing it in #3619. If he lays the framework, the other fields can be added in a follow-on PR.

**Comment by philbooth** [comment]
The foundations for this have been laid in #3682.

**Comment by shane-tomlinson** [comment]
AFAICT, the only items left to validate are in the reliers.

**Comment by vbudhram** [comment]
from mtg: closing
