### ISSUE TITLE
Re-use flowId for uniqueUserId?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3592]
#3587 introduces a new `flowId`. It's been [suggested](https://github.com/mozilla/fxa-content-server/pull/3587#issuecomment-196408347) that we use it to replace `uniqueUserId` at some point. This issue is to do that.

**Comment by vladikoff** [comment]
If we get a new flowId on every refresh then this is not suitable

**Comment by philbooth** [comment]
> If we get a new flowId on every refresh then this is not suitable

Just noting here that, as per https://github.com/mozilla/fxa-content-server/pull/3587#issuecomment-198216230, I may have been wrong about that approach.

**Comment by philbooth** [comment]
@shane-tomlinson just pointed out that the `uniqueUserId` is currently written to and read from local storage, so it persists after a user signs out. That seems like a different lifetime to our idea of a `flowId`. Before unifying the two, we'd need to invalidate/delete the `uniqueUserId` on each sign out. I don't know enough about `uniqueUserId` to know if that is a problem.

**Comment by shane-tomlinson** [comment]
I'm killing this issue with fire. We cannot reuse the uniqueUserId for the flowId because the two have different lifespans.

**Comment by vladikoff** [comment]
:+1:
