### ISSUE TITLE
Propose a new design for duplicate Sign Up buttons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3593]
The Sign Up button appears on Registration and Choose what to Sync. @ckarlof noted correctly this is not great.

**Comment by ryanfeeley** [comment]
Rename second button to "Confirm"?

**Comment by rfk** [comment]
This will also play into user expectations around #3502 and #3481

**Comment by rfk** [comment]
In fact if we move the actual account creation until after the CWTS screen, maybe it's the first button that should change to "Next" or something?

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3502#issuecomment-183053661

**Comment by ryanfeeley** [comment]
Fixed!
