### ISSUE TITLE
High number of `parseMessage` errors in Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3594]
![screen shot 2016-03-14 at 20 52 40](https://cloud.githubusercontent.com/assets/848085/13759554/b65242d0-ea26-11e5-889d-eb2224106577.png)

![screen shot 2016-03-14 at 20 51 39](https://cloud.githubusercontent.com/assets/848085/13759558/ba216e68-ea26-11e5-8b64-5cab19c13b56.png)

**Comment by shane-tomlinson** [comment]
I'm curious to know what is causing this, and what the effects are. We may need to know the postMessage event origin domain to fully figure out what is going on here too.

Ref #3465, #3486

**Comment by vladikoff** [comment]
From the samples i looked at I'm seeing only issues with `context=fx_desktop_v1`

Ref: https://github.com/mozilla/fxa-content-server/blob/7d8c2c0661c4492895d39cc10ebcbd602f4bf596/app/scripts/lib/channels/fx-desktop-v1.js#L54

**Comment by vladikoff** [comment]
@shane-tomlinson  @vladikoff to talk about this...
