### ISSUE TITLE
Change password leads to 2nd device spinning/working msg on reauth

### ISSUE THREAD

**Issue by edmoz** [mozilla/fxa-content-server#3603]
1. on android nightly - change password to something else
2. goto desktop nightly prefs - click on 'manage'
3. enter your new password from step 1

actual: working... message appears and button spinner spins forever.

expected: it should redirect to successful reauth screen.  After restart - i was signed in

**Comment by edmoz** [comment]
I'm also seeing this in reauth from a pw reset.

**Comment by shane-tomlinson** [comment]
Huh, this is a very similar case to https://github.com/mozilla/fxa-content-server/pull/3419/files#diff-35a0b43541e39e8448e4863c4f03e631R116, which was fixed yesterday. Looks like another case to worry about.

**Comment by vladikoff** [comment]
@shane-tomlinson @vladikoff to check this out...

**Comment by vladikoff** [comment]
Some STR: https://github.com/mozilla/fxa-content-server/issues/3680

@shane-tomlinson when you say: 

>  same root cause.

Do you know what the cause is? I think we tried to schedule a meeting about this but maybe you figured out the problem anyway ?

**Comment by vladikoff** [comment]
From mtg: "The reason is - the browser does not take over because it is not about:accounts."

**Comment by vladikoff** [comment]
![](https://cloud.githubusercontent.com/assets/128755/14753031/91c96298-08a0-11e6-8076-745a2d568c2f.gif)

**Comment by shane-tomlinson** [comment]
Yup, same reason. The browser doesn't open settings in about:accounts. w/ a Desktop Sync context, we assume the browser is going to take over after sign in and halt the flow.

**Comment by vladikoff** [comment]
Related https://github.com/mozilla/fxa-content-server/issues/3378#issuecomment-213570133

**Comment by vladikoff** [comment]
draft: 2 checks: if NOT isAboutAccounts (aka is NOT Remote)  + if instanceOf HALT then make it Null?

**Comment by vladikoff** [comment]
3 Patches:
1. Removes Session Expired
2. Fixes Show password when invalid token
3. detect the above, add a better check for aboutAccounts and update behaviours.

**Comment by vladikoff** [comment]
> draft: 2 checks: if NOT isAboutAccounts (aka is NOT Remote) + if instanceOf HALT then make it Null?

@shane-tomlinson I did some tests with that approach:

I get to settings after a non remote force_auth: 
<img src=http://v14d.com/i/572b9aea299a3.jpg width=250 />

Browser is stuck in this: 
![image](https://cloud.githubusercontent.com/assets/128755/15054079/c1c6660c-12d3-11e6-83f1-7b8ef029a08a.png)

(this is when I comment out the `//afterForceAuth: new HaltBehavior(),` behaviour)

I'm stuck in "Please sign in" until I click "Forget this email" even I undo the change `afterForceAuth` and try to login via `about:accounts`

**Comment by vladikoff** [comment]
hm the above might be related to my bad sync server config, will check again

**Comment by vladikoff** [comment]
> hm the above might be related to my bad sync server config, will check again

Okay checked again and our plan should still work, i had a bad config with the token server.
