### ISSUE TITLE
Invoke flow.begin activity event from the client

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3608]
Ensuing from https://github.com/mozilla/fxa-content-server/pull/3587#issuecomment-198216230, there was some discussion about when `flow.begin` activity events should be emitted. Crucially, they should only happen when the user is beginning a device-connection flow.

As a result, https://github.com/mozilla/fxa-content-server/pull/3607 was opened to remove the `flow.begin` event that I added to the index server route. Even checking the value of `originalUrl` from that route does not give us the control we need, since the client is responsible for redirecting from `/` to `/signup`, `/signin`, `/confirm` and `/settings`.

The aforementioned discussion also suggested using the resume token as a means to persisting the `flowId` across devices. For that reason, https://github.com/mozilla/fxa-content-server/pull/3607 also ditched the server-generated `flowId`, which was being recreated on every request.

The purpose of this issue is to replace those two removed features with something more fit for purpose. Then subsequent to this, there is another issue open to handle the question of unifying `flowId` and `uniqueUserId`.

For this issue, @shane-tomlinson and I came up with the following approach:

1. Server injects `flowBeginTime` to the markup (this is already happening).
2. After a bunch of other stuff has happened, the client redirects to `/signup` or `/signin`.
3. Client checks resume token.
    1. If it has a `flowId`, client uses that for step `5`.
    2. If there is no `flowId`, generate a new one for use in step `5` and update the resume token.
4. Client reads `flowBeginTime` from the DOM.
5. Client makes request to a new activity event endpoint, sending `event`, `flowId` and `flowBeginTime` as params.
6. Server emits activity event.

@shane-tomlinson, please comment if I've got any of that wrong. @rfk, does this sound okay to you?

**Comment by rfk** [comment]
Sounds OK to me.  Is there another metrics-related request that we might profitably bundle this one with, or does it have to be a standalone request for reliability reasons?

**Comment by philbooth** [comment]
> Is there another metrics-related request that we might profitably bundle this one with, or does it have to be a standalone request for reliability reasons?

Oh, good point, we could add it to `/metrics`. @shane-tomlinson, you cool with that?

**Comment by shane-tomlinson** [comment]
> Oh, good point, we could add it to /metrics. @shane-tomlinson, you cool with that?

We often send multiple /metrics reports per page load, any tab blur will cause a report to be sent. If only one report is logged to Heka, I'm fine with sending with metrics.

**Comment by rfk** [comment]
Another thing to note is that this approach will miss users who abandon the flow before the javascript finishes loading, e.g. because it's huge and took way too long.  It seems we must either over- and under- count with `flow.begin` events given the current constrains of the system, so let's run with the approach in this bug for now, and we can iterate in future if a better way presents itself.
