### ISSUE TITLE
activityEvents are being logged in Travis

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3609]
@shane-tomlinson @philbooth Looking at Travis logs I now see these logs:

![](http://v14d.com/i/56ec67d044a6c.png)

Should we hide them like we hide other logs?

**Comment by philbooth** [comment]
Oh yeah, definitely. Sorry for adding the noise!

**Comment by philbooth** [comment]
There's a fix for this issue at https://github.com/mozilla/fxa-content-server/pull/3619/commits/34341d161a05b3bd80517426625f0b8796f9e236 (part of https://github.com/mozilla/fxa-content-server/pull/3619).

**Comment by vladikoff** [comment]
part of https://github.com/mozilla/fxa-content-server/pull/3619
