### ISSUE TITLE
all tests failing against latest.dev.lcip.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3611]
All functional tests are failing when run against latest.dev.lcip.org: http://tests.dev.lcip.org:8111/viewLog.html?buildId=9810&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=18&state=18

Running the same way from a linux host with Fx 45.0.1, the client stalls loading the firstrun page:
```
On Web Console:

downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal \
  src index:1) source: \
  https://www.mozilla.org/media/fonts/OpenSans-Regular-webfont.2696e36f12c5.woff responsive-bundle.2b0724257ae0.css:1:1575

downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans Light" style:normal weight:normal stretch:normal \
  src index:1) source: \
  https://www.mozilla.org/media/fonts/OpenSans-Light-webfont.1c8075cacedb.woff

On Browser Console:

1458541112145	   Browser.SelfSupportBackend	   ERROR _loadSelfSupport - Non HTTPS URL provided:  Log.jsm:751:0

downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal \
  src index:1) source: \
  https://www.mozilla.org/media/fonts/OpenSans-Regular-webfont.2696e36f12c5.woff responsive-bundle.2b0724257ae0.css:1:1575

downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans Light" style:normal weight:normal stretch:normal \
  src index:1) source: \
  https://www.mozilla.org/media/fonts/OpenSans-Light-webfont.1c8075cacedb.woff responsive-bundle.2b0724257ae0.css:1:554
```

**Comment by jrgm** [comment]
Also fails against `stage`, which is currently running `master` of fxa-content-server.

**Comment by shane-tomlinson** [comment]
@jrgm Is this a change w/ Fx 45, does Fx 44 have the same problem?

**Comment by shane-tomlinson** [comment]
@jrgm - FWIW, those problems originate on the firstrun page, not ours.

**Comment by shane-tomlinson** [comment]
@jrgm - why is the firstrun page loading for the functional tests?

**Comment by vladikoff** [comment]
It says `Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.` this means connectivity between the runner and the WebDriver extension is not working. Usually happens when the WebDriver add-on is blocked.

**Comment by vladikoff** [comment]
I'll try updating Selenium and see if that fixes it./...

**Comment by shane-tomlinson** [comment]
@jrgm, I can only get the referred to error to happen locally if I kill the WebDriver .jar process, otherwise no problem with Fx 45.0.1 on linux.

**Comment by vladikoff** [comment]
@shane-tomlinson also `http://tests.dev.lcip.org:8111` is running selenium 48.2 at the moment

**Comment by vladikoff** [comment]
Updating to Selenium 53 helps. :+1:
