### ISSUE TITLE
unexpected strings being added to extracted .po files

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3612]
From https://github.com/mozilla/fxa-content-server-l10n/pull/112#issuecomment-199232790

See:
* https://github.com/mozilla/fxa-content-server-l10n/blob/f5677b262adbb9ddf5b046a31f44fd48fe40c9bf/locale/pl/LC_MESSAGES/server.po#L356-L372
* https://github.com/mozilla/fxa-content-server-l10n/blob/f5677b262adbb9ddf5b046a31f44fd48fe40c9bf/locale/pl/LC_MESSAGES/server.po#L401-L405

**Comment by vladikoff** [comment]
One of the examples is here: https://github.com/mozilla/fxa-auth-mailer/blob/master/lib/db.js#L34

**Comment by shane-tomlinson** [comment]
> One of the examples is here: https://github.com/mozilla/fxa-auth-mailer/blob/master/lib/db.js#L34

Ahha. I'll bet jsxgettext looks for `t('` and not for whether that `t` comes comes after punctuation or whitespace.

**Comment by vladikoff** [comment]
We need to switch it to `gettext` only, https://github.com/mozilla/fxa-auth-mailer/blob/master/mailer.js#L272

**Comment by vladikoff** [comment]
> We need to switch it to gettext

Tried to do this but it is still picking up the `get` Strings

**Comment by vladikoff** [comment]
@shane-tomlinson l10n-extract already uses the `gettext` here: https://github.com/mozilla/fxa-auth-mailer/blob/master/Gruntfile.js#L86 Any ideas why it would still be processing the wrong keyword?

**Comment by splewako** [comment]
@vladikoff: I'm still seeing the same strings in recently exported files - is this expected?

https://github.com/mozilla/fxa-content-server-l10n/blob/a3d3cabcdf81e30ac3aade0649b0553742db3664/locale/pl/LC_MESSAGES/server.po#L469-L488
