### ISSUE TITLE
Users wanting to change their email are left frustrated

### ISSUE THREAD

**Issue by Caspy7** [mozilla/fxa-content-server#3617]
It is not currently possible to change a Firefox Account email address. There are however valid reasons that users find themselves wanting to do so (such as that address becoming unavailable in the future). 

The logical route users often take is to click the "Manage Account" link on the Sync tab which takes them to https://accounts.firefox.com/settings

Currently this page offers no explanation or solutions to this problem. This can leave users frustrated. I have seen and heard of multiple users asking how to accomplish this.

It was only after searching online that I concluded that it was not possible. One of the top hits from a sumo question simply stated "Sorry, changing the email address isn't an option." and that was all. 

We should give users a better experience on this topic.  

Let's consider adding a link in the settings page to a fuller, more diplomatic answer such as a sumo page just for it.  It could explain that it's not _currently_ possible and suggest the workaround of disconnecting devices and creating a new account - and that no data should be lost with this approach.  This way at least we have more control than whatever comes up on search results (for those who do search).

**Comment by vladikoff** [comment]
from triage: we should discuss this in the product meeting

 cc @rfk

**Comment by rfk** [comment]
I like this suggestion at lot.  An additional benefit of using a targetted SUMO page for this, is that we may be able to use metrics on how many people are viewing the page, as a way to judge the importance of implementing this feature.

**Comment by vladikoff** [comment]
Adding "not actionable" to this, @rfk maybe we should convert this to a card in features waffle?

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-features/issues/27
