### ISSUE TITLE
There's a slow memory leak in the content server

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3620]
Given that we turn over webheads every ~2 weeks, this doesn't impact (but responses may be slower than normal). But anyways, noticed that RSS for the server is >500MB, which is unusual for node 0.10, and most likely there is a leak of some kind.

**Comment by vladikoff** [comment]
Looks like https://github.com/SalesforceEng/tough-cookie/issues/48 due to usage of `request`. At least that's what the debugger shows. Updating to Node 4 should help.

**Comment by rfk** [comment]
@jrgm has this improved any with train-64?

**Comment by jrgm** [comment]
So much for node 4. This leaks faster than in node 0.10. 5 days to reach service impacting levels. Autoscaling replacement servers in now.

**Comment by vladikoff** [comment]
These 2 PRs might help deal or better understand the leak:

* https://github.com/mozilla/fxa-content-server/pull/4345
* https://github.com/mozilla/fxa-content-server/pull/4344

**Comment by jrgm** [comment]
Still a problem.

**Comment by vladikoff** [comment]
> Still a problem.

I don't see train 73 in prod yet. Do you get memory leaks on stage as well?

**Comment by vladikoff** [comment]
I see a leak with Handlebars templates: 

![image](https://cloud.githubusercontent.com/assets/128755/20405951/60120cb8-acd9-11e6-9bad-14cd8768bc4d.png)

After switching to directly using Handlebars I see the same:
![](http://v14d.com/i/582e108abfa28.jpg)

We need to find a way for Handlebars to clean up after itself or garbage collect the rendered template.

**Comment by vladikoff** [comment]
When I run with NODE_ENV=production then I assume it caches it:

![](http://v14d.com/i/582e15f18bb3e.jpg)

**Comment by vladikoff** [comment]
So then I run it for longer time and I get

![image](https://cloud.githubusercontent.com/assets/128755/20408075/f6c8957a-ace1-11e6-9467-014b6631e5e3.png)

**Comment by vladikoff** [comment]
Updating to latest Helmet 3 should decrease memory usage significantly in the csp code: 
![](http://v14d.com/i/58362151cf95f.png)


PR lives in https://github.com/mozilla/fxa-content-server/pull/4444

**Comment by vladikoff** [comment]
need to check the memory usage in train-75, waiting for deploy...

**Comment by vladikoff** [comment]
As of train-76:

```
[12:46:29]  <jrgm>	vladikoff: no egregious offenders. Maybe higher than I'd expect (400-500MB).
[12:46:44]  <jrgm>	But if that's steady state, then good.
[12:47:42]  <vladikoff>	jrgm, is there a graph that will tell us that is in steady state?
[12:48:02]  <jrgm>	vladikoff: we don't have such a graph.
```
