### ISSUE TITLE
Fix "Error: env: must be one of the possible values:"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3622]
If you have `NODE_ENV=dev` forced in the shell then you will get a warning: 

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: env: must be one of the possible values: ["production","development"]: value was "dev"
Warning: Task "server" not found. Use --force to continue.
```

We need to either update the `npm start` script or do something with that config.

cc @pdehaan thoughts?

**Comment by pdehaan** [comment]
Looks like we have [at least] a couple instances of "dev":

```sh
$ grep -irn "NODE_ENV=" . --exclude-dir=node_modules

./tests/ci/deps.sh:19:LOG_LEVEL=error NODE_ENV=dev node ./bin/server.js &
./tests/ci/deps.sh:28:LOG_LEVEL=error NODE_ENV=dev npm start &
```

Odd, i would have thought that **convict** would have caught that, but I must be missing something:

```js
  env: {
    default: 'production',
    doc: 'What environment are we running in?  Note: all hosted environments are \'production\'.',
    env: 'NODE_ENV',
    format: [
      'production',
      'development'
    ]
  },
```

**Comment by vladikoff** [comment]
from irc discussion: express.js, react and etc use

```
      'production',
      'development'
```

So we can keep those in the content server. We need to convert other servers to use `production`, etc instead of short `prod`, `dev`.

**Comment by rfk** [comment]
> We need to convert other servers to use production, etc instead of short prod, dev

@jrgm or @jbuck is this something we should prioritize from your POV?
