### ISSUE TITLE
Harmonize FxA colors with new style guide colors

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3632]
So that Firefox properties can begin to look like one big happy family, we should harmonize the FxA colors with the new style guide colors. Sass it up @johngruen!

**Comment by johngruen** [comment]
@ryanfeeley will do...for reference, i threw this together last month: https://github.com/FirefoxUX/firefox-color-vars

**Comment by vladikoff** [comment]
That would be cool!

**Comment by vladikoff** [comment]
@TDA was there another bug where you already did this?

**Comment by TDA** [comment]
@vladikoff Yes I have this in #3753
