### ISSUE TITLE
Errors are not interpolated before being sent to Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3636]
@philbooth found this while working on #3619.

Here's an example in Sentry:

![screen shot 2016-04-01 at 14 13 44](https://cloud.githubusercontent.com/assets/848085/14211663/ccf96ab2-f81e-11e5-8e73-e8d8fd20db0d.png)

**Comment by vladikoff** [comment]
@shane-tomlinson this might be fixed via your PR to app-start and @vbudhram PR for the logger

**Comment by shane-tomlinson** [comment]
Fixed by #3764, closing.
