### ISSUE TITLE
FxA can be created using special characters in the age field [bz1260731]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3639]
From https://github.com/mozilla/fxa-bugzilla-mirror/issues/134 which was copied from
From https://bugzilla.mozilla.org/show_bug.cgi?id=1260731

Build: 3.0 (9)

Steps to reproduce:
1. Launch Mozilla Firefox
2. Create Firefox account
3. Type "1." or "12," in the age field

Actual result:
- The user can create an account with an incorrect inputted age

Expected result:
- The user age field should not contain special characters 

Note: 
- Typing "."/"," characters in the age field will cause inconsistency regarding the minimum age required to create Firefox account.
- This inconsistency does not occur on Android version as the age field will become blank when typing these characters.
- When typing other characters like ")[%;" the age text field is deleted.

**Comment by shane-tomlinson** [comment]
We should be able to attach a keydown handler to the age field. If the character is not a digit, call event.preventDefault().

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-bugzilla-mirror/issues/134
