### ISSUE TITLE
Add a button to Open in Yahoo / HotMail

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3640]
In order to reduce verification time, for Google Apps for Domains users, we should offer a button to **Open in Google Mail** on verification and reset pages.

**Comment by vladikoff** [comment]
> Google Apps for Domains users

Not sure we can detect those

**Comment by ryanfeeley** [comment]
@vladikoff maybe? https://gist.github.com/erans/1087324

**Comment by vladikoff** [comment]
Will need to talk to @rfk about this....

**Comment by rfk** [comment]
It sounds like this will require some amount of server-side work to do the DNS lookup, making it a non-trivial feature, so I'd like to see it stated in terms of a hypothesis, assumptions, etc.  Maybe we can do some small amount of work to validate the underlying assumptions, e.g. some quick analysis to see what % of incoming signups are Google Apps for Domains users.  If that's a small number, it may not be worth investing in at this stage.

**Comment by ryanfeeley** [comment]
https://github.com/mozilla/fxa-content-server/issues/3656

**Comment by rfk** [comment]
Putting this in the backlog, to resurface when we get metrics from the linked issue #3656

**Comment by vladikoff** [comment]
Blocked by https://github.com/mozilla/fxa-auth-db-mysql/pull/134

**Comment by rfk** [comment]
> Determine what % of our users are using Google Mail

Turns out it's around 1.7%; for comparison around 11.5% of users are @yahoo.com and around 9.2% are @hotmail.com.  Can we do a similar "Open in ..." trick for those users?  If so it's probably better bang for our buck than targeting Google Apps for Domains users at this time.

**Comment by ryanfeeley** [comment]
Whoah, well hard to argue that 1.7% is worth the effort. Yahoo and Hotmail make more sense. @rfk should it be done as an experiment even though we know that it worked for Gmail users?

**Comment by vladikoff** [comment]
@ryanfeeley renamed issue to Yahoo / Hotmail

**Comment by rfk** [comment]
> should it be done as an experiment even though we know that it worked for Gmail users

In the spirit of replication, I think we should repeat the gmail experiment with the next biggest mail provider and see if we get the same result.  We should have code infrastructure we can re-use for that, right?

**Comment by vladikoff** [comment]
I'm -1 on repeating the experiment, imho testing out with `@gmail` was enough.

**Comment by rfk** [comment]
Summarizing IRL discussion with @vladikoff: I think we should maintain the discipline of measuring whether the new button is a success, and take the time to compare its performance to the gmail button.  But I don't care about doing e.g. a 50% rollout with a control group to decide whether or not to enable it, or other "experimenty" things like that.

**Comment by larissagaulia** [comment]
Couldn't find any API to auto fill the user email (to use on redirect link). Suggestions?

**Comment by TDA** [comment]
> Couldn't find any API to auto fill the user email (to use on redirect link). Suggestions? 
AFAIK, Yahoo mail doesnt auto-fill from a URL, and doesnt have an API end-point for doing that either. Not sure about Hotmail. I'd say redirecting them to the login page is sufficient enough, but I will let @ryanfeeley comment about the UX involved.
