### ISSUE TITLE
errors.js->normalizeXHRError does not handle 503 responses w/o a body.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3641]
https://github.com/mozilla/fxa-content-server/blob/a91d53d4b571f8d8c7a5b0e9d48cbbe1e5d7cb2f/app/scripts/lib/errors.js#L180

**Comment by shane-tomlinson** [comment]
This should result in a `SERVICE_UNAVAILABLE` error.

**Comment by rfk** [comment]
Similarly, a `429` response with no body should produce a rate-limiting error, allowing us to send this from nginx if necessary

**Comment by shane-tomlinson** [comment]
Fixed by #4231, closing.
