### ISSUE TITLE
Replace Clear Sans with Fira Sans weight of 200

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3643]
Currently we're using two big web fonts. We should stick to the one we commissioned, Fira Sans. Weight of 200 seems to look good every (fictional screen attached).

<img width="475" alt="screenshot 2016-04-06 15 21 11" src="https://cloud.githubusercontent.com/assets/68213/14329818/3655db5e-fc0b-11e5-834a-a7ce1ea85fdd.png">

Wanna have a go at it @johngruen?

**Comment by ryanfeeley** [comment]
Here is the registration page without adjusting the leading problem apparent in Fira Sans (or perhaps it was the previous font Clear Sans that had the leading problem?)
<img width="470" alt="leading" src="https://cloud.githubusercontent.com/assets/68213/14330838/5e5cff56-fc10-11e5-861d-fa9b9ea62634.png">

**Comment by ryanfeeley** [comment]
Settings:
<img width="602" alt="settings" src="https://cloud.githubusercontent.com/assets/68213/14330922/d178a558-fc10-11e5-99c9-1f9683fb7df2.png">

**Comment by ryanfeeley** [comment]
Mobile: <img width="447" alt="scaled" src="https://cloud.githubusercontent.com/assets/68213/14330955/0399daca-fc11-11e5-9cfd-9a819d4f65ba.png">

**Comment by shane-tomlinson** [comment]
This makes me happy @ryanfeeley!
