### ISSUE TITLE
Stop sending error messages to the 400/500 pages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3649]
We initially did this because we did not have Sentry and needed to log errors another way. Now we have Sentry. We should use it, and stop using the `message` query parameter to pass data. Arbitrary *text* can be sent in message, which is displayed to the user. There is no HTML injection attack, but the text field can be used to cause confusion.

**Comment by shane-tomlinson** [comment]
@rfk - Where do you feel this should be prioritized along with the other work?

**Comment by rfk** [comment]
I'd like to see us get to this in the next cycle, it is a regularly reported "security vulnerability" in bugzilla; I'm hopeful that it's not a huge amount of work, but if it is in fact a rabbit hole, we should reconsider treating it with such high priority.

**Comment by vladikoff** [comment]
So we have two blocks here:

```
   app.get('/400.html', function (req, res) {
      res.removeHeader('x-frame-options');
      logger.error('400.html', {
        client_id: req.query.client_id, //eslint-disable-line camelcase
        context: req.query.context,
        errno: req.query.errno,
        message: req.query.message,
        namespace: req.query.namespace,
        param: req.query.param
      });
      return res.render('400', {
        message: req.query.message,
        staticResourceUrl: STATIC_RESOURCE_URL
      });
    });

    app.get('/500.html', function (req, res) {
      res.removeHeader('x-frame-options');
      logger.error('500.html', {
        context: req.query.context,
        errno: req.query.errno,
        message: req.query.message,
        namespace: req.query.namespace
      });
      return res.render('500', { staticResourceUrl: STATIC_RESOURCE_URL });
    });
```

that do `logger.error`, We can still keep the logging and use the Sentry endpoint to also report the same using Sentry's `query` object. It is up to @jrgm if we still want to log these to Heka.
