### ISSUE TITLE
fully validate email query param

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3650]
In #3606 we started fully validating the email query parameter in the `/force_auth` flow. Before #3606, force_auth acted differently to other views when an email is invalid, it printed its own error message. Now that we have unified behaviors, we should push the validation into [models/relier.js](https://github.com/mozilla/fxa-content-server/blob/b889bdfd5e36941c4de88eddddb5e76add418daa/app/scripts/models/reliers/relier.js#L41) so that it's available to all views.

Note, there is no HTML injection attack with an invalid email. The invalid email will be displayed to the user in an input field, which may cause confusion.

**Comment by shane-tomlinson** [comment]
@rfk - Can you help us prioritize this?

**Comment by rfk** [comment]
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1251195

This and related bugs keep getting reported, I think we should try to deal with them in the next batch of quality work that we are able to make time for.
