### ISSUE TITLE
Suggest showing the password to users who mistype their password

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3654]
Currently about half of all logins see the "Incorrect password" error. Some users would be greatly helped by showing their password. We should change the message so that users can learn and choose to show the password field when they are struggling. This will result in reducing login time, and the number of attempt limits exceeded.

![unmask-tip](https://cloud.githubusercontent.com/assets/68213/14474915/4bf4b7f2-00cd-11e6-9789-1b30a09ba90d.png)

**Comment by shazow** [comment]
If you're targeting users who re-use their passwords (rather than use a password manager), showing somekind of visualization of the hash of their password might be a nice easy safe way to give an indicator of whether it's something they're familiar with or not (which correlates with whether it's the correct password). For example: https://chriszarate.github.io/supergenpass/mobile/, note the little icon that changes as you enter the master password. It could be something even lower-fidelity, such as changing the colour of the [Show] button accordingly.

**Comment by ryanfeeley** [comment]
@shazow I really like that feature for Supergenpass, but I'm not sure it’s worthy of that prime real estate for Firefox Account users. And I worry it would weird users out (who are often skittish about deviations from password conventions).

**Comment by shazow** [comment]
It doesn't need to warrant any additional real estate, it could be something as subtle as changing the color of the input box border for example. Anyways, good idea to keep in the back of your pocket, maybe worth user testing. I imagine 80% of the user's wont care, and 20% will benefit from it.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - should we get a feature card opened about this in Aha and do all the good stuff like suggest ways to measure success?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Do I smell an experiment? I don't mind that approach, but @vladikoff and @vbudhram are still working on the Show Password experiment.

Larger question, perhaps for @rfk, should we be doing every proposed feature as an experiment, or does that slow us down?

**Comment by shane-tomlinson** [comment]
> Larger question, perhaps for @rfk, should we be doing every proposed feature as an experiment, or does that slow us down?

It may well slow us down, though I still think it's the right way to go for most (not all) features. Introducing a feature as an experiment allows us to generate metrics about the new feature and compare those against the control group while while reducing bias from non-related changes made from one train to the next.

**Comment by rfk** [comment]
I agree with @shane-tomlinson above; there's value in running these as experiment even if they're small, and in doing the up-front work to determine how we'll measure their success.  For example for this feature, I can imagine two different ways of measuring success:

* Whether users choose to show the password when prompted
* Whether users who choose to show the password are more likely to succeed at logging in

Doing this as an experiment will probably be slower, it's true.  But that means we should practice getting faster at doing lightweight experiments 😁.

**Comment by ryanfeeley** [comment]
@rfk @shane-tomlinson That means there are a number of outstanding issues that I should probably re-pitch as experiments. I agree that it helps us focus on impact. Should every experiment get an A-ha card?

**Comment by rfk** [comment]
>  Should every experiment get an A-ha card?

It's my opinion that Aha slows us down in the early pitching phase, and I'll be very glad to accept PRs pitching experiments that don't have an assigned Aha card number (e.g. [1]).  We can assign a card number when they get picked up for scheduling/implementation.

[1] https://github.com/mozilla/fxa/tree/master/features/proposed/check-domain-mx

**Comment by vladikoff** [comment]
@ryanfeeley we moved to the 'focus' behaviour for this. let me know if we should go back to this idea

**Comment by ryanfeeley** [comment]
@vladikoff Now, more than ever. No need for the third state depicted above, any **Show** link would be an instant toggle and not work in this context.

Here is an updated design:
![incorrect-password](https://cloud.githubusercontent.com/assets/68213/18011672/1fd75f18-6b84-11e6-887b-ac6d5d04b46e.png)

**Comment by shazow** [comment]
Might be clearer if the [Show] button turned to a similar colour as the error message and expanded to [Show Password?] (bonus points for transitions), then you can keep the error message as short as the original.

**Comment by ryanfeeley** [comment]
I would settle for red border until focused, but that would be another issue.

**Comment by vladikoff** [comment]
This was fixed 👍
