### ISSUE TITLE
Determine what % of our users are using Google Mail

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3656]
Not all users who use Google Mail are Gmail users. Many are Google Apps for Domains users, which is used by many organizations large and small.

Before we invest time in building https://github.com/mozilla/fxa-content-server/issues/3640 @rfk suggests we determine what % of our users are using Google Mail to see what impact this feature will have.

Of interest to @vladikoff and probably @jrgm too.

**Comment by rfk** [comment]
👍 and it may pay to go even slightly broader: what's the breakdown of canonical MX for our users?  We may find that there are substantially more (say) yahoo mail users than google-apps-for-domains users and should direct our attention there first.

One idea for measuring this: a node script that reads a stream of email addresses on stdin, does the dns lookup, and calculates a ranked count of MX domains from that sample.  Then @jrgm can take a random sample from our db, pipe it through the script, and get  cheap estimate of what impact this feature could have.

**Comment by eoger** [comment]
It's not great (no domain caching) but here's a bash command that does what you're describing :
`while read email; do echo $email | awk -F'@' '{print $2}' ; done | while read domain; do dig -t mx +noall +answer +short $domain | sort -n | awk 'NR==1{print $2}' ; done | uniq -c`

**Comment by vladikoff** [comment]
I don't think we can do anything with this on the content-server point of view, this is an ops issue.

**Comment by rfk** [comment]
Migrating to auth-server; I suspect we'll want to ship it as a small script in order to make sure we get the lookup logic right, e.g. falling back to checking A records if there's no MX.

https://github.com/mozilla/fxa-auth-server/issues/1237
