### ISSUE TITLE
JSCS to be ported to ESLint?

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3669]
According to this comment: https://github.com/jscs-dev/node-jscs/issues/1511#issuecomment-210822517, JSCS is no longer in production and is being combined with ESLint. So is it time to revisit this question: https://github.com/mozilla/fxa-content-server/issues/2598, remove JSCS and map the rules to the equivalent ESLint rules?

@pdehaan 
@vladikoff

**Comment by pdehaan** [comment]
Definitely time to remove JSCS, almost. Per http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint it looks like they're still working on porting rules, etc.
I think we wait until the next major ESLint version with JSCS engine/rules, then remove JSCS dependencies.

**Comment by vladikoff** [comment]
We are probably ~6 months to a year until a stable ESLint with jscs rules is in place. 
I don't want to pollute the bug tracker with this. 

See https://github.com/eslint/eslint/pull/5875/files#diff-04c6e90faac2675aa89e2176d2eec7d8R119

**Comment by pdehaan** [comment]
http://eslint.org/blog/2016/07/jscs-end-of-life

> **JSCS End of Life**
> When we announced that JSCS was joining ESLint, it was with a stated support period for JSCS of three months. _Those three months have now passed and JSCS is now considered **fully deprecated**._

**Comment by TDA** [comment]
BOOM! MINE!!!!
@pdehaan

**Comment by vladikoff** [comment]
Compat milestone: https://github.com/eslint/eslint/milestone/15

**Comment by shane-tomlinson** [comment]
Can we slowly start removing rules from jscs that can be handled by eslint?
