### ISSUE TITLE
Improve handling of errors in reset_password_confirm=false flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3670]
From @rfk:

> If you visit /reset_password?reset_password_confirm=false and an email address that doesn't have an account, you currently just get a blank page and an "unknown account" error in the JS console. AFAICT this is because we don't actually render the page in this flow, but instead directly submit reset request.

If the user arrives at this screen and reset_password_confirm=false, we can fairly reliably guess the user clicked on a link in an email because their account has been reset. We should be consistent with how force_auth handles this situation and not allow the user to change the email field on the reset password page. If the account no longer exists, instead of allowing the user to change the email address, redirect the user to the "force signup screen" which shows an "account no longer exists" error. The user is able to sign up again, but they are unable to change their email address or navigate to sign in.

**Comment by vladikoff** [comment]
from mtg: should we close this or remove `reset_password_confirm=false` entirely ?

**Comment by vladikoff** [comment]
> from mtg: should we close this or remove reset_password_confirm=false entirely ?

Should we?

**Comment by shane-tomlinson** [comment]
Ref #3653

**Comment by vbudhram** [comment]
from mtg: we should close
