### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cwittmer** [mozilla/fxa-content-server#3675]
Hi,

is it possible to improve the doku in a way that a 'non-developer' is able to setup an own firefox-sync and firefox-auth service ?
I really miss a comunication matrix, which is telling service a is communicating with service b and c.
Is it enough when all services (all on one host) are listening on 127.0.0.1 and are reached by an 'apache' or 'nginx' reverse proxy ?
Thank you very much :)

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-auth-server/issues/1236#issuecomment-212922736
