### ISSUE TITLE
force_auth does not login properly, stuck on Working...

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3680]
context: fx_desktop_v2
firefox: 45.0.2

happens both in prod and local dev

### STR

* sign in with an account to Firefox
* open a new tab and go to  /clear to clear storage
* go back to about:preferences#sync
* click "Manage Account" 
* try to signin in the new tab (with the session expired warning)

### Expected

Should login

### Actual

The UI is stuck on `Working...`.

### GIF

![force_auth](https://cloud.githubusercontent.com/assets/128755/14753031/91c96298-08a0-11e6-8076-745a2d568c2f.gif)

**Comment by vladikoff** [comment]
Can be testing locally with:

## Prod:

```
➜  fxa-local-dev git:(master) pwd
/Users/vladikoff/mozilla/fxa-local-dev
➜  fxa-local-dev git:(master) FXA_ENV=prod npm start
```

## Local (have servers running):

```
➜  fxa-local-dev git:(master) FXA_ENV=prod npm start
```

**Comment by shane-tomlinson** [comment]
Dup of #3603, same root cause.
