### ISSUE TITLE
Improve current device design by removing time and adding colour

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3684]
So that I can more easily discern the current device and avoid any confusing time stamp information, as a FxA user, I want the current device to appear slightly differently.

CURRENT:
![fxa-current-device-current](https://cloud.githubusercontent.com/assets/68213/14794825/b8ba5060-0af3-11e6-91dd-e668326258c4.png)

PROPOSED:
![fxa-current-device-proposed](https://cloud.githubusercontent.com/assets/68213/14794827/bae64524-0af3-11e6-8dbd-cccb2eb44242.png)

GREEN HEX #57bd35

**Comment by rfk** [comment]
To be clear, should we keep the timestamp information on the other, non-current devices?

**Comment by shane-tomlinson** [comment]
I like the aesthetics of the green line, but think there is value in seeing when the current device last updated. My memory fails me, is the date shown the last Sync date, or the last time a cert was issued?

**Comment by rfk** [comment]
It's the last time a cert was issued (well, technically right now it's not anything because we had to disable the db writes that were tracking that field...but when we re-enable them it'll be the time a cert was last issued)

**Comment by ryanfeeley** [comment]
> To be clear, should we keep the timestamp information on the other, non-current devices?

Correct, this is just for the current device. The date is not the last Sync date, but rather a date that has will only confuse the user (especially when they are currently logged in from the browser that they are looking at). Best to remove it.

**Comment by shane-tomlinson** [comment]
> Correct, this is just for the current device. The date is not the last Sync date, but rather a date that has will only confuse the user (especially when they are currently logged in from the browser that they are looking at). Best to remove it.

I'm bikeshedding, following that line of reasoning, do *any* of the dates serve a useful purpose as they are currently implemented? Would the dates that are less granular cause less confusion, perhaps to a day level? "Last connected: today", "Last connected: yesterday", "Last connected: 2 days ago"..."Last connected: last week"

**Comment by vladikoff** [comment]
> I'm bikeshedding, following that line of reasoning, do any of the dates serve a useful purpose as they are currently implemented? Would the dates that are less granular cause less confusion, perhaps to a day level? "Last connected: today", "Last connected: yesterday", "Last connected: 2 days ago"..."Last connected: last week"

I'm not clear what you are suggesting. 
If you are suggesting using numbers for X days - we cannot do that because of l10n limitations.
If you are suggesting adding `last connected:` to the list - I guess we can do that, would be repetitive though.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I would like us to improve the granularity of the dates as I'm not quite happy with the compromise we made for easier localization.

**Comment by ryanfeeley** [comment]
> we cannot do that because of l10n limitations

I would like to dispute this. Other features we have localize this exact thing.

**Comment by vladikoff** [comment]
> Other features we have localize this exact thing.

What other features?

**Comment by ryanfeeley** [comment]
By "we" I meant at Mozilla, not in FxA. Trying to track down.
