### ISSUE TITLE
Signing in to Hello after Sync generates zombie sessions that cannot be killed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3687]
Ref https://github.com/mozilla/fxa-auth-server/issues/1239

Follow on notes from @rfk:

-------------------------------------

@jrgm not only do these STR produce an unexpected "New signin" email, they generate an unkillable zombie session that cannot be logged out of.  STR:

* Do all the things @jrgm said above, so you're logged in to both Sync and Hello
* Go into Sync preferences and disconnect from sync
* Go into the Hello settings and log out of Hello
* Restart your browser just to be sure there's no transient state
* Visit https://accounts.firefox.com

Expected result: I should be signed out, because I signed out in both places that I signed in

Actual result:  I'm still logged in to FxA, and there's no "sign out" button anywhere that will let me sign out.

If I understand what's happening here, the Hello login is generating a fresh sessionToken, but not clearing the sessionTokenConext, so we still thing the token is associated with sync.  The sequence of logins takes accounts.firefox.com through the following states:

* Initial state -> (sessionToken=null, sessionTokenContext=undefined)
* Log in to sync -> (sessionToken=token1, sessionTokenContext="fx_desktop_v1")

In this state, we don't show a "sign out" button on the web interface, because the session is owned by sync.

* Log in to Hello -> (sessionToken=token2, sessionTokenContext="fx_desktop_v1")

Now we *think* the session is owned by sync, but it isn't.  We incorrectly fail  to show the "sign out" link.

From here, logging out of Sync will destroy token1, but that won't affect accounts.firefox.com because it's already forgotten about that token.  Logging out of Hello won't destroy token2, because Hello is an OAuth relier and never sees the session-token.

Bleh.

**Comment by rfk** [comment]
I think there's a quick in, and a long term fix here:

Quick win, suggested by @shane-tomlinson: stop hiding the "sign out" button for sync sessions, the browser now supports a "logout" webchannel message so we can usefully act on sign-out intent even for sync sessions.

Long-term fix: The hello login should simply re-use the existing session from sync, rather than having to create a new one.  This might imply adding a new API to the auth-server that lets you generate a keyFetchToken from an existing session.

**Comment by vladikoff** [comment]
https://support.mozilla.org/en-US/kb/hello-status and https://bugzilla.mozilla.org/show_bug.cgi?id=1287827 💀 .

Please open new issues if we have any follow up actions here

**Comment by rfk** [comment]
> Quick win, suggested by @shane-tomlinson: stop hiding the "sign out" button for sync sessions,
> the browser now supports a "logout" webchannel message so we can usefully act on sign-out
> intent even for sync sessions.

@shane-tomlinson do you think this is worth escalating to a stand-alone bug?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you think this is worth escalating to a stand-alone bug?

Added #4017
