### ISSUE TITLE
Ensure PII is not logged from CSP reports.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3689]
CSP reports contain a `source` field. `source` comes from [`source-file`](https://github.com/mozilla/fxa-content-server/blob/d9ab90c1e29854a30c3464a97154094bdb51b2de/server/lib/routes/post-csp.js#L34) in the CSP report. Clicking on the "manage account" link from about:preferences#sync open the settings page with the user's email address and uid. Ensure PII is scrubbed on the backend when the CSP report is logged.

**Comment by rfk** [comment]
Does https://github.com/mozilla/fxa-content-server/pull/3566 help with this at all?

**Comment by shane-tomlinson** [comment]
> Does #3566 help with this at all?

Nope.

<img width="573" alt="screen shot 2016-04-27 at 09 29 56" src="https://cloud.githubusercontent.com/assets/848085/14846233/ae6bd0d0-0c5a-11e6-838a-b54ac2df4416.png">

**Comment by shane-tomlinson** [comment]
Wait a second. That's... different to what I expected. The referrer there is `""`, and the `source` contains the email.

**Comment by shane-tomlinson** [comment]
OK, looking again at the logs, the `referrer` is not the problem, `source` is. Updating the description.
