### ISSUE TITLE
Fix checkbox style

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3691]
Our checkbox does not need a hover state, and should be the same as the text (#8a9ba8). For the down states, it should appear like:
![checkbox](https://cloud.githubusercontent.com/assets/68213/14832476/8904eec2-0bc8-11e6-8cd4-27811867bf25.png)

**Comment by TDA** [comment]
Was this not fixed by https://github.com/mozilla/fxa-checkbox/pull/14 ?
