### ISSUE TITLE
Make mobile apps link directly to their respective stores

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3692]
Currently on our account verification pages we offer links to our mobile apps, but they link to our mozilla.org product pages. According to Alex Davis we should remove this step and instead link directly to the respective stores.

App Store:

* https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=ios&creative=button&fallback=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fapple-store%2Fid989804926%3Fpt%3D373246%26ct%3Dadjust_tracker%26mt%3D8

Play Store:

* https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=android&creative=button

**Comment by ryanfeeley** [comment]
https://github.com/mozilla/fxa-auth-mailer/issues/142

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm confused about which links you are referring to... Both links on the verification landing pages point directly to one of the two stores. [From the templates](https://github.com/mozilla/fxa-content-server/blob/2d7ffc9017afbc516dd6ab89cb94681ce01594f3/app/scripts/templates/marketing_snippet_ios.mustache#L9:L18):

iOS:
`https://itunes.apple.com/app/apple-store/id989804926?ct=fxa-verification-link`

Android:
`market://details?id=org.mozilla.firefox&amp;referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dsync-android-snippet`

**Comment by vladikoff** [comment]
@ryanfeeley do we need to use `https://app.adjust.com/` ?

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff I emailed you both Alex’s email for context.

**Comment by vladikoff** [comment]
@shane-tomlinson I'm still lost with all the different urls, what do we need to update?

**Comment by shane-tomlinson** [comment]
@vladikoff - I just sent an email to Alex asking for confirmation.
