### ISSUE TITLE
Tweak style of app/play store badges

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3697]
![app-stores](https://cloud.githubusercontent.com/assets/68213/14900172/498813b4-0d5d-11e6-92c2-b436cba8074d.png)
- ~~Update to use latest SVG/PNG app/play store icons~~ See https://github.com/mozilla/fxa-content-server/issues/3482
- Space 10px apart
- Reduce "Download…" line to 14px in font-size

**Comment by vladikoff** [comment]
Switching the Google Play icon is out of scope for this bug, there is another issue for that one here: https://github.com/mozilla/fxa-content-server/issues/3482

@ryanfeeley I haven't tested the `small` layout for this change yet. With the `small` layout we might get the same vertical view we have currently.

**Comment by shane-tomlinson** [comment]
FWIW, the new design is very nice.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Thanks, but still a big step down from @johngruen’s great Android-only version that had some personality. Unfortunately personality is not my strong suit.

**Comment by ryanfeeley** [comment]
Someone love this bug please.

**Comment by vladikoff** [comment]
Updating latest images is in bug https://github.com/mozilla/fxa-content-server/issues/3482

**Comment by pgadige** [comment]
I'd like to work on this issue. Could you please assign it to me?

**Comment by vladikoff** [comment]
@pgadige Hey! Sure, see: https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/app/scripts/templates/marketing_snippet.mustache and https://github.com/mozilla/fxa-content-server/blob/7c5aee43ab38b99e840d52d4478957c4def31e35/app/scripts/views/marketing_snippet.js#L32-L39

You might have to tweak the logic in the current code to always show the snippet while you tweak styles. See style notes here: https://github.com/mozilla/fxa-content-server/blob/master/README.md#development-notes

**Comment by shane-tomlinson** [comment]
@pgadige - thanks for getting involved! I just realized while looking at the code the easiest way to force see those badges without going through any extra work is to open this URL (assuming you have the content server running locally):

http://127.0.0.1:3030/signup_complete?service=sync

**Comment by shane-tomlinson** [comment]
ref #4218
