### ISSUE TITLE
find.firefox.com and hello account signup/signin broken in train-60

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3698]
With either find.firefox.com or hello in the browser, start the oauth flow.
Expected: signin/signup
Actual: Error: "Bad Request - Invalid OAuth parameter: image_uri"

**Comment by vladikoff** [comment]
@jrgm it is set to `none` in https://oauth.accounts.firefox.com/v1/client/f86f8eee897230ab

You might need to set it to `""` like Pocket: https://oauth.accounts.firefox.com/v1/client/749818d3f2e7857f

**Comment by vladikoff** [comment]
and Hello: https://oauth.accounts.firefox.com/v1/client/a8b39c2b1cab722e also needs to be `""`.

There is new Validation here: https://github.com/mozilla/fxa-content-server/blob/d07b577218f80b67ed7c22fc25bfa3ab8acfc516/app/scripts/models/reliers/oauth.js#L26

**Comment by vladikoff** [comment]
@jbuck fixed this! 🎆

**Comment by jbuck** [comment]
(I haven't actually run this update yet)

**Comment by jbuck** [comment]
Now it's really fixed!

**Comment by vladikoff** [comment]
👍
