### ISSUE TITLE
Sanely handle regeneration of flowId and flowBeginTime after sign-out

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#3705]
Currently, `flowId` and `flowBeginTime` are set once, when the view is first loaded. This is fine in most cases but, if a user signs in, signs out and then signs in again, all without refreshing the page, the same values for `flowId` and `flowBeginTime` will be sent to the auth server and emitted in ~~activity~~ flow events.

Perhaps that's not a problem and the metrics queries will be fine regardless. If that is the case, we can happily close this issue.

But if it is a problem, we need to regenerate the `flowId` and `flowBeginTime` after a user signs out. ~~The `flowId` part is easy because it is already generated client-side. The `flowBeginTime` must come from the server though, which makes the change less clear-cut.~~

~~One option would be to add a `GET /time` route expressly for this purpose. Alternatively, we could modify the existing `GET /config` route to include a timestamp instead.~~

~~Either way, there is some concern about setting `flowBeginTime` on the `metricsContext` model in two different ways. After initialisation, it is rendered into the DOM via the `data-flow-begin` attribute on the `body` element and set on the model from there. Adding an XHR request that sets it again later might be confusing down the line.~~

~~To ease those concerns, it might be prudent ditch the `data-flow-begin` attribute in favour of using an XHR request in all cases. And that change may itself entail some extra handling for the case where a sign-in request is made before the server time response has been received (if such a case is possible).~~

**Comment by rfk** [comment]
> To ease those concerns, it might be prudent ditch the data-flow-begin
> attribute in favour of using an XHR request in all cases. 

Part of the point of flow-begin-time is that it's from before the browser started loading all the js assets etc.  Which doesn't really count if you're starting a new login flow in an already loaded page, but is important for fresh page loads.

How simple would it be, to just clear flowId and flowBegin time after successfully completing a login, and have any subsequent calls to e.g. /account/login be missing data rather than containing incorrect data?  That may be a better short-term compromise.

**Comment by philbooth** [comment]
> How simple would it be, to just clear flowId and flowBegin time after successfully completing a login, and have any subsequent calls to e.g. /account/login be missing data rather than containing incorrect data? 

That would be literally the simplest fix possible so 👍.

**Comment by philbooth** [comment]
When we do this, we also need to ensure we clear `metrics._eventMemory` in `lib/metrics.js` so that, e.g. the engage event will be emitted correctly.

**Comment by philbooth** [comment]
In today's meeting, it was pointed out this probably explains the weird flows reported in [bug 1316463](https://bugzilla.mozilla.org/show_bug.cgi?id=1316463).
