### ISSUE TITLE
Browser is not immediately notified of password change if user browses directly to /settings

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3707]
## STR

1. Sign up to FxA from Sync.
1. Verify email.
1. Apply the diff from the bottom of the description.
1. Open /settings directly, without clicking "manage account" from about:preferences#sync
1. Open the dev console
1. Change the user's password
1. Look for `command: change_password` or `command: fxaccounts:change_password`

## Expected

Browser is immediately notified of password change.

## Actual

Browser is not notified

## Cause of the problem

Since the user browsed directly to /settings, the "direct" broker is used and the browser is not notified. Now that I am writing through this, delete account may suffer from the same problem.

## Possible solution

We could check the stored `sessionTokenContext` and notify the browser on change password and delete account. We could also wait for push notifications to take care of all of this for us.

## Patch to apply

```diff
diff --git a/app/scripts/lib/channels/duplex.js b/app/scripts/lib/channels/duplex.js
index 7436ba5..401e4a9 100644
--- a/app/scripts/lib/channels/duplex.js
+++ b/app/scripts/lib/channels/duplex.js
@@ -107,6 +107,7 @@ define(function (require, exports, module) {
      */
     send: function (command, data) {
       var self = this;
+      console.log('command', command);
       return p()
         .then(function () {
           return self._sender.send(command, data, null);
```

**Comment by vladikoff** [comment]
>  We could also wait for push notifications to take care of all of this for us.

This landed a few weeks ago:
https://github.com/mozilla/fxa-auth-server/commit/77e53bfa3513fd793d5dd13afacda2e7d62ec7e2

**Comment by vbudhram** [comment]
Closing per mtg, will reopen if push notifications does not fix this.
