### ISSUE TITLE
500.html, 502.html, and 503.html all return an HTML status code of 200?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3714]
I found these tests surprising: https://github.com/mozilla/fxa-content-server/blob/e484bd46f4d5026daae439dda0b65515d4d776af/tests/server/routes.js#L88:L92

It seems like the returned HTML status code should match the error page.

**Comment by vladikoff** [comment]
I think if they returned real 500s then @jrgm would be overwhelmed with these errors due to all the js crashes.
