### ISSUE TITLE
Replace marked library with other Markdown parser

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#3728]
... it has (and had) some issues, and we can probably find something a bit more active.

- https://nodesecurity.io/advisories/101
- https://nodesecurity.io/advisories/23
- https://nodesecurity.io/advisories/24
- https://nodesecurity.io/advisories/22

On Test Pilot, we're currently using [**remarkable**](http://npm.im/remarkable) ([see usage](https://github.com/mozilla/testpilot/blob/master/gulpfile.js#L64-L73)), but not sure if its a 1:1 drop in replacement.

Semi-related, but we could also add a shame-badge from https://david-dm.org/mozilla/fxa-content-server to keep track of dependency "freshness" and confidence.

**Comment by vbudhram** [comment]
Per meeting: backlog

**Comment by jbuck** [comment]
I'd also suggest marky-markdown as a markdown parser: https://www.npmjs.com/package/marky-markdown

**Comment by TDA** [comment]
+1 to marky-markdown, they are based on markdown-it, which is very fast.

**Comment by TDA** [comment]
Generated HTML by the markdown libs for the markdown: `# hello, I'm markdown`:

### Marked (Currently used):
`<h1 id="hello-i-m-markdown">hello, I&#39;m markdown</h1>\n`

### Marky-Mark:
`<h1 id="user-content-hello-im-markdown" class="deep-link"><a href="#hello-im-markdown">hello, I&apos;m markdown</a></h1>\n`

### Remarkable:
`<h1>hello, I\'m markdown</h1>\n`

Remarkable seems the most natural way of doing this.

**Comment by vladikoff** [comment]
@TDA see the heading code: https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/grunttasks/marked.js#L12

**Comment by pdehaan** [comment]
@vladikoff but do we need the header ids? I vaguely recall we had to do some hackery for certain locales because the ids were all coming back the same, but it seems like we could do without them.

**Comment by TDA** [comment]
@vladikoff and @pdehaan 
Diff between what remarkable produces by default to what we have right now:
```

2,3c2,4
< <p>We care about your privacy. When Firefox Cloud Services (the "Services") sends information to Mozilla (that's us) our <a data-visible-url="https://www.mozilla.org/privacy/" href="https://www.mozilla.org/privacy/">Mozilla Privacy Policy</a> describes how we use that information.</p>
< <h2 id="h2852581bca14ff637412b7259a4b6b4ff">Things you should know:</h2><p>You send us different types of data depending on what features of the Services you use.</p>
---
> <p>We care about your privacy. When Firefox Cloud Services (the “Services”) sends information to Mozilla (that’s us) our <a href="https://www.mozilla.org/privacy/">Mozilla Privacy Policy</a> describes how we use that information.</p>
> <h2>Things you should know:</h2>
> <p>You send us different types of data depending on what features of the Services you use.</p>
5c6
< <li><strong>Firefox Account</strong>: When you sign up for an account, we receive your email address and a hash of your password.  In addition, you may optionally add a profile image.  If you choose Gravatar, we'll share your email address with Gravatar to obtain your profile image.</li>
---
> <li><strong>Firefox Account</strong>: When you sign up for an account, we receive your email address and a hash of your password.  In addition, you may optionally add a profile image.  If you choose Gravatar, we’ll share your email address with Gravatar to obtain your profile image.</li>
9c10
< <hr>
---
> <hr />
12,15c13,14
< <li><p><strong>Online Data Tools</strong>: We use “online data tools” such as cookies, clear GIFs and web beacons to provide the functionality of our products and services. For example, cookies assist with user sign-in and authentication. We also use these same tools to collect data to improve our products and services. For example, we use cookies to provide web analytics.</p>
< </li>
< <li><p><strong>Options</strong>: You can learn more about what cookies are and manage cookies in Firefox by clicking <a data-visible-url="https://support.mozilla.org/kb/cookies-information-websites-store-on-your-computer" href="https://support.mozilla.org/kb/cookies-information-websites-store-on-your-computer">here</a>. Note that certain features of our and other products and services may not function properly without the aid of cookies.</p>
< </li>
---
> <li><p><strong>Online Data Tools</strong>: We use “online data tools” such as cookies, clear GIFs and web beacons to provide the functionality of our products and services. For example, cookies assist with user sign-in and authentication. We also use these same tools to collect data to improve our products and services. For example, we use cookies to provide web analytics.</p></li>
> <li><p><strong>Options</strong>: You can learn more about what cookies are and manage cookies in Firefox by clicking <a href="https://support.mozilla.org/kb/cookies-information-websites-store-on-your-computer">here</a>. Note that certain features of our and other products and services may not function properly without the aid of cookies.</p></li>

```

Only 3 notable differences:
1. Header ID's
2. quotes vs smart quotes
3. `data-visible-url` usage

**Comment by TDA** [comment]
@vladikoff @shane-tomlinson 
I need inputs on points 1 and 2 above.
Looking closer at https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/app/scripts/views/legal_copy.js#L35
Looks like 3 is added by this legal_copy.js file, so shouldn't be a problem. 

Go ahead with switch to remarkable?

**Comment by shane-tomlinson** [comment]
Serious question, is this needed? The only markdown documents we parse come from our legal translators, and I think we trust them?

**Comment by shane-tomlinson** [comment]
For points and 1 and 2.

1. id's shouldn't matter so much as long as they don't break our tests. 
2. Whether smart quotes can be used depend on how the legal translations are done. I don't remember. If the markdown templates are pre-translated before the conversion to HTML and do not need the `t` helper function, changing normal quotes to smart quotes is allowed. If `t` is used to look up the translated strings, then smart quotes will break the lookup.

**Comment by pdehaan** [comment]
Re: smart quotes,
Looks like **remarkable** has a flag for that: https://github.com/jonschlinkert/remarkable#typographer
But yeah, it is probably very wise to match the same quote logic as the previous library.

> @shane-tomlinson "Serious question, is this needed?"

Probably not _"needed"_, but currently we have 4 "vulnerabilities" being reported via Travis-CI+nsp in our logs. Removing **marked** as a dependency would resolve 2 of those. That would only leave 2 reported issues, which are both due to **moment** (via **able** -- via **convict** and **hapi** > **joi**).
It should be easy enough to bump **convict** to the latest version and fix that issue. But the Hapi+Joi issue would have to be resolved by explicitly ignoring the advisory using the [.nsprc](https://github.com/mozilla/fxa-content-server/blob/master/.nsprc) file.
