### ISSUE TITLE
Don't poll /account/login when checking for account lockout status

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3740]
(Migrating from https://github.com/mozilla/fxa-customs-server/issues/111)

We currently check for account lockout status by polling the /account/login endpoint.  This generates a lot of failed login attempts and could trigger rate-limiting on the email or IP address.  We should instead poll a status endpoint to avoid triggering rate-limiting behaviour.

**Comment by shane-tomlinson** [comment]
Backlog until we perform the UX review of the account lockout feature.

**Comment by vladikoff** [comment]
account lockout was removed 💯
