### ISSUE TITLE
Checkbox is not vertically aligned

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3742]
<img width="343" alt="screenshot 2016-05-17 14 51 23" src="https://cloud.githubusercontent.com/assets/68213/15335103/e0539f26-1c3e-11e6-9093-c09ee26e9cbc.png">

.fxa-checkbox__box-outline should be -2px instead of 2px

**Comment by vladikoff** [comment]
Where is this from? Mine looks fine

**Comment by ryanfeeley** [comment]
@vladikoff  Latest

**Comment by ryanfeeley** [comment]
Probably Fira did it.

**Comment by vladikoff** [comment]
@ryanfeeley 
![image](https://cloud.githubusercontent.com/assets/128755/15338345/5df057ea-1c34-11e6-8200-6d2732e70621.png)

**Comment by ryanfeeley** [comment]
@vladikoff Uh oh, I think it was the Fira Sans on my Mac that Firefox was using, not the web version :(
