### ISSUE TITLE
Remove checkbox hover states

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3743]
Our checkboxes have a weird babyblue hover state. Please remove.
![baby-blue](https://cloud.githubusercontent.com/assets/68213/15335138/076189ac-1c3f-11e6-91f7-7f4e4cce9228.gif)

**Comment by johngruen** [comment]
@ryanfeeley they are also misaligned with the text :(

**Comment by ryanfeeley** [comment]
@johngruen Turns out the misalignment was due to me having Fira Sans installed on my Mac!

**Comment by vbudhram** [comment]
@ryanfeeley Should this be removed for all checkboxes or just for CWTS ones?

**Comment by ryanfeeley** [comment]
@vbudhram All the checkboxes.
