### ISSUE TITLE
Reduce clickable area of checkbox labels

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3744]
Our checkbox labels are clickable for the entire row. Only the checkbox and text should be clickable.
![baby-blue](https://cloud.githubusercontent.com/assets/68213/15335192/499d3186-1c3f-11e6-87f5-8c906163d4f8.gif)

**Comment by ryanfeeley** [comment]
![checkbox](https://cloud.githubusercontent.com/assets/68213/15335256/92d21c72-1c3f-11e6-907b-fe1682e46a67.png)

**Comment by ryanfeeley** [comment]
@TDA BTW this is the screen capture GIF maker i'm using http://www.cockos.com/licecap/

**Comment by TDA** [comment]
@ryanfeeley Updated with gif
![checkboxes](https://cloud.githubusercontent.com/assets/432707/15444611/82c1893e-1ea7-11e6-819b-4c220d8a0069.gif)
