### ISSUE TITLE
Rename sass variables to more meaningful names

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3753]
Right now we have names like:
```
$button-background-color: #0095dd;
$info-background-color: #0095dd;
$input-row-focus-border-color: #0095dd;
$input-placeholder-color: #8a9ba8;
$input-row-border-color: #8a9ba8;
```
As you can see, too much repetition, losing the DRY principle for which we use Sass.
I vote that we change these to more meaningful names, to something like whats described here:
https://davidwalsh.name/sass-color-variables-dont-suck

~~EDIT: I also vote for using css-variables. Same end result.~~
EDIT: from [here] (https://github.com/mozilla/fxa-content-server/pull/3755/files/6a79b2fa2780ce033ddfa2505dd269b91a42cfe4#r64020198), no css-vars cuz no support.

@ryanfeeley 
@shane-tomlinson

**Comment by pdehaan** [comment]
Semi-related, but it may be worth running something like [**colorguard**](http://npm.im/colorguard) against the repo since I don't think I've done that in 18+ months.

```js
// grunttasks/colorguard.js
module.exports = function (grunt) {
  grunt.config('colorguard', {
    css: {
      files: [{
        src: [
          '<%= yeoman.app %>/styles/main.css',
          '<%= yeoman.app %>/styles/sync.css',
          '<%= yeoman.app %>/styles/system-font-main.css'
        ]
      }]
    }
  });
};
```

### Output:
```
✗ grunt colorguard
Running "colorguard:css" (colorguard) task

>> #F2F2F2 [main.css:11, ...] is too close (2.6306067895807894) to #FFFFFF [main.css:14, ...]
>> #8A9BA8 [main.css:98, ...] is too close (1.9477707638427477) to #909CA8 [main.css:1387, ...]
>> #C3CFD8 [main.css:170, ...] is too close (1.6290039413230841) to #C5CDD4 [main.css:392, ...]
>> #000000 [main.css:245, ...] is too close (2.9629278871164075) to #111111 [main.css:268, ...]
>> #DDDDDD [main.css:1112, ...] is too close (0.9119568556386488) to #D9D9D9 [main.css:1235, ...]

Done.

Execution Time (2016-05-19 22:00:19 UTC)
loading tasks   4.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 78%
colorguard:css  1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22%
Total 5.4s
```

Those colors may all be valid, but probably good to audit them to make sure we can't get away with merging the similar colors.

**Comment by TDA** [comment]
Following up from usage of css variables in #3755, why not make a complete switch to css variables instead? will save quite a few lines of code. Will impact a lot of files though.

**Comment by shorlander** [comment]
> As you can see, too much repetition, losing the DRY principle for which we use Sass.
> I vote that we change these to more meaningful names, to something like whats described here:
> https://davidwalsh.name/sass-color-variables-dont-suck

I can understand the desire for better names, but I think I disagree with the suggestion that you don't want variables for your color shades and tints. The reason for defining those is so you can maintain consistency across elements. If you start dynamically changing the color values on the fly you litter your styles with potential places for inconsistency.

**Comment by TDA** [comment]
@shorlander See #3783 , I have indeed used variables for colors (actually copied over a lot from the style guide, and changed them from css variables to sass variables).

**Comment by vladikoff** [comment]
blocked by #3754
