### ISSUE TITLE
Restyle buttons to conform to the Mozilla style guide

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3754]
From IRC:
The style guide from shorlander has a state defined for the web:
http://people.mozilla.org/~shorlander/styleguide/ui-elements/buttons-all.html

We should ensure that FxA sticks to the style guide.

@ryanfeeley 
@shane-tomlinson 
@rfk

**Comment by TDA** [comment]
@ryanfeeley 
@shane-tomlinson 
### Current status:
### Disabled:
![screenshot 2016-05-19 15 17 56](https://cloud.githubusercontent.com/assets/432707/15411453/f240bd30-1dd4-11e6-92ad-4adec7f90116.png)

### Enabled - Default:
![screenshot 2016-05-19 15 34 13](https://cloud.githubusercontent.com/assets/432707/15411778/37135f88-1dd7-11e6-9929-1b6d5b419b2e.png)

### Enabled - Hover:
![screenshot 2016-05-19 15 35 09](https://cloud.githubusercontent.com/assets/432707/15411816/7dade616-1dd7-11e6-8de5-e04e33d298fc.png)

### Enabled - Pressed (Active)
![screenshot 2016-05-19 15 42 44](https://cloud.githubusercontent.com/assets/432707/15411906/5d604c36-1dd8-11e6-9970-ae85d4a68642.png)

### Enabled - Focused
![screenshot 2016-05-19 15 49 53](https://cloud.githubusercontent.com/assets/432707/15412035/5afaf2e2-1dd9-11e6-8910-560b81be16b5.png)

**Comment by ryanfeeley** [comment]
@TDA looking good but I still think that I detect the original blue in the "Did you mean…" in the view Enabled - Default. Definitely replace all the blue with the default button blue.

**Comment by vladikoff** [comment]
let's try to deploy an lcip box..
