### ISSUE TITLE
bug(rtl): Fix settings page on RTL locales

### ISSUE THREAD

**Issue by mohamed7afezz** [mozilla/fxa-content-server#3761]
On RTL locales, 
- Firefox log and slogan should be in the right.
- Sign out Button should be in left.
- Action buttons float left.

Just like this:

![2](https://cloud.githubusercontent.com/assets/9789109/15443616/0184f20a-1eea-11e6-8141-368aea2778c3.png)

we can solve this issue by change this style when RTL locales:
```
.settings-unit-stub .settings-unit-summary {
    float: right;
}

#fxa-settings-header-wrapper #fxa-manage-account {
    background-position: right 8px;
    padding-right: 36px;
}

#fxa-settings-header-wrapper #fxa-manage-account {
    float: right;
}

#fxa-settings-header-wrapper .settings-button {
    float: left;
}
```

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Thanks for CC:ing me. Thrilled to have full RTL support. As long as this doesn't break the responsive view, let's do it.
