### ISSUE TITLE
Port autoprefixer to --prefix-free

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3763]
Currently we are using autoprefixer to add *all* prefixes (-webkit,-ms,-o,-moz) to our stylesheet `main.css`, putting it at over 64kb.

Porting to something like --prefix-free (written by the amazingly talented @leaverou), and adding only the required prefixes for a given browser, shaves off over 5.5kb from our `main.css`, putting it at a neat ~58kb. Adding --prefix-free adds only 2kb, still saving a valuable ~3.5kb.

Also, there's no change in code required, just a change of library.

@pdehaan 
@shane-tomlinson

**Comment by TDA** [comment]
http://lea.verou.me/prefixfree/

**Comment by LeaVerou** [comment]
Please don't use that URL, it's completely outdated. The correct one is http://leaverou.github.io/prefixfree/

**Comment by TDA** [comment]
@LeaVerou I updated it earlier :) (From your book ofcourse) :D Thank you so much!

**Comment by TDA** [comment]
Closing this due to concerns raised [here] (https://davidwalsh.name/goodbye-vendor-prefixes), [here] (https://andywalpole.me/#!/blog/143894/-prefix-free-versus-postcssautoprefixer), and seeing a visible slowdown (with FOUT) on implementing this :(

**Comment by vladikoff** [comment]
Maybe switching to postcss's autoprefixer will yield better results with file size.

**Comment by LeaVerou** [comment]
From the 2nd article:

> -prefix-free is a hammer that adds prefixes to the CSS even if the browser no longer requires them (the project’s title is a misnomer). It does so by copying the entire stylesheet to memory, iterating over every property, matching them up with known vendor prefixed words as it does so.

FWIW, this is completely false. -prefix-free does feature testing and will never add unneeded prefixes, it only adds the prefixes the current browser needs. Also I'd recommend against taking Andy Walpole seriously when he talks about my work, he has been trolling and harassing me over multiple online venues for a few years now, so he seems pretty biased. David Walsh on the other hand is legit, and that's a good article.

But if you see a slowdown, then yes, it might not be a good idea. I wouldn't recommend it for crucial things, like e.g. layout or for huge websites.

**Comment by TDA** [comment]
@LeaVerou Hey, yes I can see that the article is pretty biased, and that prefix-free only adds the required prefixes, but I guess the thing is, our stylesheet is already over 60kb, and I guess that's what causes the FOUT when I try to add prefix-free to Firefox Accounts. Thank you so much for your help! It is indeed a great library, just not the right one for us right now :(
