### ISSUE TITLE
Audit colorguard for the fxa-content-server

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3765]
From @pdehaan 's comment [here] (https://github.com/mozilla/fxa-content-server/issues/3753#issuecomment-220466095), lets add colorguard to the fxa-content-server to keep us all honest with colors.

**Comment by pdehaan** [comment]
Not to say that we have to build it into the pipeline or as Grunt task in `lint`, but could be interesting to manually audit every few months to see if we have a lot of almost-not-quite-same colors.

But to counter that, having 3GB of [dev]dependencies when you install fxa-content-server may be ridiculous as it eventually turns into a giant kitchen sink.

**Comment by vladikoff** [comment]
> Not to say that we have to build it into the pipeline or as Grunt task in lint, but could be interesting to manually audit every few months to see if we have a lot of almost-not-quite-same colors.

Agreed, let's just audit for now.

**Comment by TDA** [comment]
Running colorguard against main.css and removing duplicates, I get about 15 collisions:
```
  line 14    col 7  #fff collides with #f2f2f2                       (11:24)
  line 268   col 3  #111 collides with #000                          (245:26)
  line 327   col 3  rgba(138, 155, 168, 0.54) collides with #8a9ba8  (98:11)
  line 340   col 5  rgba(0, 149, 221, 0.26) collides with #0095dd    (50:9)
  line 342   col 5  rgb(138, 155, 168) collides with #8a9ba8         (98:11)
  line 360   col 5  rgba(0, 0, 0, 0.1) collides with #000            (245:26)
  line 360   col 5  rgba(0, 0, 0, 0.1) collides with #111            (268:15)
  line 363   col 5  rgba(138, 155, 168, 0.26) collides with #8a9ba8  (98:11)
  line 393   col 5  #c5cdd4 collides with #c3cfd8                    (170:24)
  line 458   col 7  #f2f2f2 collides with #fff                       (14:24)
  line 1238  col 7  #d9d9d9 collides with #ddd                       (1115:27)
  line 1361  col 3  #000 collides with #111                          (268:15)
  line 1390  col 5  #909ca8 collides with #8a9ba8                    (98:11)
  line 1738  col 5  rgba(0, 0, 0, 0.5) collides with #000            (245:26)
  line 1738  col 5  rgba(0, 0, 0, 0.5) collides with #111            (268:15)
```

Your thoughts @ryanfeeley ??

**Comment by ryanfeeley** [comment]
@TDA 
You are correct about line 14, 393 and 1390.
I'm not sure about line 1238. Probably safe to merge, but hard to say. They aren't the same.
![untitled-1](https://cloud.githubusercontent.com/assets/68213/15583888/c1c711a6-2345-11e6-8b1c-0c433f8717d0.png)
Do you know how they're used?

**Comment by TDA** [comment]
@ryanfeeley Right now:
```
#fxa-settings-header-wrapper {
  border-bottom: 1px solid #ddd;
 }
```
and 
```
.settings-button.secondary:active, 
.settings-button.secondary:hover, 
.settings-button.secondary:focus {
      background: #d9d9d9; }
```

**Comment by ryanfeeley** [comment]
@TDA Thanks! Totally merge-able. I'd take #ddd for simplicity’s sake.

**Comment by TDA** [comment]
@ryanfeeley thank you!

**Comment by vladikoff** [comment]
blocked by restyle buttons PR #3754
