### ISSUE TITLE
Bump grunt version to >=0.4.5 for its peer dependencies to stop failing

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3766]
From the fxa-engineering meetup, and due to the following errors on `npm i`, lets bump up the grunt version to >= 0.4.5, which is the minimum to satisfy all the peer deps.

### Error log:
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-autoprefixer@3.0.4 wants grunt@>=0.4.2
npm ERR! peerinvalid Peer grunt-concurrent@2.3.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-po2json@0.2.0 wants grunt@>=0.4.1
npm ERR! peerinvalid Peer grunt-requirejs@0.4.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-sri@0.0.5 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-usemin@3.1.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-copyright@0.3.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-bump@0.7.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-marked@0.1.3 wants grunt@>=0.4.2
npm ERR! peerinvalid Peer grunt-amdcheck@1.3.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-colorguard@0.2.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-htmllint@0.2.7 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-newer@1.2.0 wants grunt@>=0.4.1

@shane-tomlinson You were right, it happened to me too :(
@pdehaan

**Comment by pdehaan** [comment]
I'm confused, it looks like we're already pinning to [**grunt@1.0.1**](https://github.com/mozilla/fxa-content-server/blob/855bf39bd0f6d71f53f57817924452504581d2f8/package.json#L39) in our pacakge.json:

```js
"grunt": "1.0.1",
```

/cc @vladikoff (our resident Grunt-expert)

**Comment by TDA** [comment]
@pdehaan Something similar here: https://github.com/AppGyver/grunt-steroids/issues/15

**Comment by TDA** [comment]
Closing this, for anyone else getting this issue:
1. `rm -rf node_modules`
2. `npm i`
