### ISSUE TITLE
npm-shrinkwrap not correctly generated

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3767]
It contains several diffs like this that point to files instead of remote repositories:

```diff
    "grunt-requirejs": {
       "version": "0.4.2",
---       "from": "git://github.com/vladikoff/grunt-requirejs.git#2ce7bac37fcc3d1e57214d8381332ce559611aea",
+++       "from": "../../../../../var/folders/2s/kvpksz8x39v7jwv525h5gqn00000gn/T/npm-6124-172eaee0/git-cache-043f211b59c6/2ce7bac37fcc3d1e57214d8381332ce559611aea",
       "resolved": "git://github.com/vladikoff/grunt-requirejs.git#2ce7bac37fcc3d1e57214d8381332ce559611aea",
       "dependencies": {
         "requirejs": {
@@ -6307,7 +6326,7 @@
                     },
                     "inherits": {
                       "version": "2.0.1",
                       "from": "inherits@2.0.1",
                       "from": "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz",
                       "resolved": "https://regi
```

**Comment by shane-tomlinson** [comment]
@TDA - I'm punting this one to you because you generated the last npm-shrinkwrap.json. 

Can you blow away your `node_modules` dir, delete `npm-shrinkwrap.json`, re-install the modules using `npm install --production`, re-run `npm shrinkwrap`, and check in? As a last step after checkin, run `npm install` without `--production` to install the dev deps.

**Comment by pdehaan** [comment]
Not sure if we want to look at something like [**shrinkydink**](https://github.com/nlf/shrinkydink) which may sanitize stuff like this.
