### ISSUE TITLE
feat(locale): add Persian locale support

### ISSUE THREAD

**Issue by mohamed7afezz** [mozilla/fxa-content-server#3775]
100% complete https://pontoon.mozilla.org/fa/firefox-accounts/

@vladikoff  @jrgm @vbudhram r?

**Comment by shane-tomlinson** [comment]
@mohamed7afezz - this is curious because fa is already enabled in production. We may have to map fa to fa_IR, but are unsure of the repercussions of doing so.

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/15753769/daa7e448-28c2-11e6-9591-3a089428fdb6.png)

**Comment by 5y** [comment]
Hi,
In fact there is only one name for standard persian localization and it's (fa) because there is other available Persian(farsi) in other country except Iran(IR).
And recently we finished translate for firefox account and idnk why already enabled in production!

Bests,
Reza

**Comment by vladikoff** [comment]
So yeah it seems like it was already enabled and works. @5y please let us know if there is a problem viewing or using it
