### ISSUE TITLE
Change password of Sync user causes user to be signed out of Sync after Firefox restart

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3779]
### STR

1. Sign in to Sync using FxA
1. Open the FxA settings pane via "manage account" link in "about:preferences#sync"
1. Under `Password`, click `change` button.
1. Change the user's password.
1. User still appears to be signed into Firefox.
1. Restart Firefox.
1. Open `about:preferences#sync`
1. In the hamburger menu, click the "force sync" icon.
1. User must re-sign in

<img width="497" alt="screen shot 2016-05-25 at 16 34 31" src="https://cloud.githubusercontent.com/assets/848085/15546120/a97a0f0e-2296-11e6-9c9e-a05c6c33981b.png">

### Expected
User should not need to re-sign in.

**Comment by vladikoff** [comment]
```
[11:47:12]  <vladikoff>	stomlinson, ah change pass step should relogin I'm guessing? 
[11:48:36]  <stomlinson>	vladikoff: yeah, it should send the new details to the browser that uses those instead of the old ones. I have no idea where the problem is yet.
```

**Comment by shane-tomlinson** [comment]
Ref #3603 - not sure if they are related at all.

**Comment by shane-tomlinson** [comment]
cc @mhammond, @rfk - Mark, when I test locally, it looks like updated session info is being correctly sent to the browser via the WebChannel. The browser [stores the new info](https://dxr.mozilla.org/mozilla-central/rev/5511d54a3f172c1d68f98cc55dce4de1d0ba1b51/services/fxaccounts/FxAccountsWebChannel.jsm#344), but possibly does not check the verification status of the new session or generate a new cert? I'm trying to figure out where in the flow things break down.

**Comment by vladikoff** [comment]
I cannot reproduce this in Nightly against prod.

**Comment by shane-tomlinson** [comment]
> I cannot reproduce this in Nightly against prod.

I can 100% of the time against prod using current Beta (47.0b8)

**Comment by shane-tomlinson** [comment]
> I can 100% of the time against prod using current Beta (47.0b8)

Same with Nightly.

**Comment by rfk** [comment]
I was not able to reproduce on Nightly

**Comment by rfk** [comment]
Although I *did* just successfully reproduce on Release

**Comment by shane-tomlinson** [comment]
Here's a video:

![sync-change-password](https://cloud.githubusercontent.com/assets/848085/15557471/130cec50-22cb-11e6-9c64-d836da048884.gif)

**Comment by rfk** [comment]
Relevant console dump from the browser:

```
1464213012082	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1464213012082	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1464213012083	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1464213012083	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}
1464213012083	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1464213012084	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1464213012308	Sync.BrowserIDManager	ERROR	Could not authenticate: {"details":{"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format"}}
1464213012311	Sync.ErrorHandler	ERROR	Sync encountered a login error
```

**Comment by shane-tomlinson** [comment]
I lied, no repro on nightly. I was probably doing something goofy like testing against the wrong server earlier.

**Comment by rfk** [comment]
@mhammond does this ring any bells for you, as something that would have been fixed recently in Nightly?

**Comment by mhammond** [comment]
That sounds alot like https://bugzilla.mozilla.org/show_bug.cgi?id=1207889, which landed on 48. https://bugzilla.mozilla.org/show_bug.cgi?id=1044530 might also help (also on 48) but doesn't seem directly related.

**Comment by rfk** [comment]
If this is confirmed fixed in latest Nightly, is there any action for us to take on the FxA side, or do we just need to wait for the fix to ride the trains?

**Comment by mhammond** [comment]
Can it be reproduced in Aurora? If not, then my bet remains bug 1207889, in which case we could request uplift to beta meaning it would be in release soon. If it can be reproduced on Aurora, I guess I'd need to look further and request uplift in the bug that actually fixed it.

**Comment by rfk** [comment]
I was not able to reproduce on Aurora; @shane-tomlinson could you please try as well to confirm?

**Comment by mhammond** [comment]
> in which case we could request uplift to beta meaning it would be in release soon

Although to play devil's advocate, Sync has had this behaviour since it first landed with FxA support, and it took until 48 before it bubbled to the top of the priority list, meaning we didn't consider it a significant problem for over 2 years. The patch isn't trivial (but it's not over-complex either) and uplifting to beta this close to being merged to release is risky. Given that, I'm not convinced we should actually request uplift here - we probably should have requested uplift to Aurora when it first landed. I'm not strongly against it if someone feels strongly that we should, but given the above it's difficult to make a compelling case to the release-drivers.

WDYT?

**Comment by rfk** [comment]
I don't feel strongly about requesting uplift, especially for a non-trivial patch, as long as we're confident we understand the behaviour here

**Comment by shane-tomlinson** [comment]
I'm reading through the referenced Bugzilla bugs now, there is something that stands out at me in [Ryan Kelly's comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1207889#c9):

> * Send unconditional WebChannel messages on password_change and password_reset, like we currently do for e.g. profile data change.

Currently, we *only* send web channel messages on password change if the user clicks "manage account" via about:preferences#sync, or the user initiates a password reset from about:accounts. I am hesitant to always send these messages unless the browser performs a check against the email sent in payload to prevent an unintentional change to the Sync user. If the browser *does* do that check, let's open an issue and move ahead.

I tested against Aurora, no reproduce there. I think [@mhammond's change password patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1207889) did the trick.

**Comment by mhammond** [comment]
>  I am hesitant to always send these messages unless the browser performs a check
> against the email sent in payload to prevent an unintentional change to the Sync user.

It does - https://dxr.mozilla.org/mozilla-central/rev/8d0aadfe7da782d415363880008b4ca027686137/services/fxaccounts/FxAccounts.jsm#552

**Comment by shane-tomlinson** [comment]
> It does - https://dxr.mozilla.org/mozilla-central/rev/8d0aadfe7da782d415363880008b4ca027686137/services/fxaccounts/FxAccounts.jsm#552

Thanks @mhammond - I must have been looking with a blindfold on yesterday.

Closing this issue since the bug has been fixed by browser code. Opened #3788 to always send a WebChannel message on password change/reset.
