### ISSUE TITLE
Always send a WebChannel notification after password reset/change

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3788]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1207889#c9
Ref #3779 

If the user resets a password reset outside of about:accounts or changes their password without clicking on the "Manage account" link in about:preferences#sync, the browser is not notified of the updated session and eventually stops syncing. This is not a great user experience. 

We should always send a WebChannel notification if the user changes or resets their password. If the browser receives a message and sees the new creds are for a user that is not the currently signed in Sync user, it'll ignore the new creds and all will be right with the world. If the email and uid match, the browser will use the new creds, and all will be right with the world.

cc @mhammond, @rfk

**Comment by shane-tomlinson** [comment]
@mhammond, @rfk - I'm looking at the [expected WebChannel messages](https://dxr.mozilla.org/mozilla-central/rev/f378a56b25ce2a2997b263c1857629f3f18d7400/services/fxaccounts/FxAccountsWebChannel.jsm#30-36). There is `fxaccounts:change_password`, but no corresponding `fxaccounts:reset_password`. 

We currently [send `fxaccounts:login`](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-desktop-v2.js#L64) if the user has reset their password from within about:accounts, I just want to confirm that is the expected message for this case. I imagine an `fxaccounts:login` will just re-initialize Sync?

**Comment by rfk** [comment]
That seems OK to me.  Do we preceed it with a can_link_account like we do for the standard login case?

**Comment by shane-tomlinson** [comment]
> That seems OK to me. Do we preceed it with a can_link_account like we do for the standard login case?

We do not currently, I'm trying to think through the repercussions of doing not doing so. I'm having a hard time thinking of a scenario where we would need to. The only time the "fxaccounts:login" message would be sent is if 1) the current relier requests keys (aka - is Sync - this is the current behavior), or 2) if the email for which the password is being reset was used to sign into Sync on the current device w/o being previously logged out (this is the additional behavior I'm working on). It's improbable for a user to sign in to Sync as two different users on the same browser w/o first logging out as one of the users. I say improbable because it's possible the user loads https://accounts.firefox.com/signin?context=fx_desktop_v3&service=sync manually and sign in twice with different emails.

Sending "can_link_account" could in theory cause the "different user" warning to be displayed to the user during the password reset flow, even during OAuth flows. I imagine that would be entirely unexpected by the user. If the browser supported an `fxaccounts:reset_password` message, it could check whether the email/uid's match and update the creds if so, and ignore if not.

w/o requiring Fx changes, sending and handling can_link_account for reset password is going to cause upheaval on the content server. For any WebChannel capable environment, we'll have to send can_link_account over the web_channel, even if the user is resetting the password in the oauth flow. This would require both the WebChannel auth broker and OAuth auth broker to be loaded, then handle the can_link_account message in a sane manner. I'm not sure how to best approach that, though I feel it'll add a lot of complexity to the current auth broker architecture. We have wanted to untangle the two responsibilities of the auth brokers, communication and UI state machine management, for a while, this may push us to doing so.

I'm not sure what can of worms we are opening with the reset password flow. We'll have to be careful to correctly handle users who verify on 2nd devices too. :/

**Comment by mhammond** [comment]
I suspect fxaccounts:login will work, but it doesn't seem the right choice - there's a risk that parts of the system will assume this is a "first" login. I *think* that as long as you don't send declinedSyncEngines or customizeSync it will work OK, but I'm not quite sure and also concerned about the future.

fxaccounts:change_password seems like a better choice and should be roughly the same so long as, eg, the session token and other credential related keys are set explicitly to null. A new message probably makes the most sense long term so the server doesn't need to know exactly which fields should be set to null, but might work OK in the meantime.

Either way, you'd really need to test thoroughly to know for sure.

**Comment by rfk** [comment]
> Sending "can_link_account" could in theory cause the "different user" warning
> to be displayed to the user during the password reset flow, even during OAuth flows.

Aye, I hadn't really considered the implications for non-sync flows, and I fear I've paged out too much of the context around this issue.  I agree that `can_link_account` is only suitable for when the user is actively trying to log in to sync and we shouldn't try to add it in other cases.  Accidentally causing the browser to connect to the wrong sync account would be a disaster...

**Comment by vladikoff** [comment]
from mtg: still in progress...

**Comment by shane-tomlinson** [comment]
Change is done, reset needs to be done.

**Comment by shane-tomlinson** [comment]
As of today, the browser is successfully disconnected from Sync immediately and the user is asked to sign in again. I feel like this is "good enough", there is at least no delay like there used to be. Closing.
