### ISSUE TITLE
models use `fetch` and self initialize even if they do not need asynchronous intialization

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3789]
@rfk noticed this with the unique-user-id.js, though user.js has the problem too. `fetch` is meant for asynchronous initialization when remote resources are used to populate a model. The creator of the model, rather than the model itself should call `fetch`. If the model does not need asynchronous initialization, it shouldn't have a fetch.

Ref #3736

**Comment by vladikoff** [comment]
from mtg: 🗡 closing this for now unless needed
