### ISSUE TITLE
Wrap PO file lines at 200 characters

### ISSUE THREAD

**Issue by mathjazz** [mozilla/fxa-content-server#3795]
Pontoon now wraps PO file lines at 200 characters instead of 78 as it did until now. We made this change because most of our Gettext based projects (amo, sumo, input, etc.) also wrap lines at 200 characters, and the diff should be much smaller now (https://github.com/mozilla/addons-server/issues/2181).

However, Firefox Accounts seems to be wrapping lines at 79 characters, so it would be great if you could change that setting and unify it with other projects.

**Comment by vladikoff** [comment]
@shane-tomlinson any ideas where this is set?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson any ideas where this is set? 

@vladikoff - It may be in this call to [msgmerge](https://github.com/mozilla/fxa-content-server-l10n/blob/master/scripts/merge_po.sh#L18) - It looks like we can set the width using the `-w` flag.

From `man msgmerge`:

![screen shot 2016-05-31 at 14 58 56](https://cloud.githubusercontent.com/assets/848085/15676984/3c3f765a-2740-11e6-8071-63c83e516738.png)

**Comment by shane-tomlinson** [comment]
Opened https://github.com/mozilla/fxa-content-server-l10n/pull/128

**Comment by mathjazz** [comment]
👍
