### ISSUE TITLE
unexpected strings being added to extracted .po files

### ISSUE THREAD

**Issue by splewako** [mozilla/fxa-content-server#3802]
This is https://github.com/mozilla/fxa-content-server/issues/3612 again as it doesn't seem to be fixed and I cannot reopen original issue.

https://github.com/mozilla/fxa-content-server-l10n/blob/a3d3cabcdf81e30ac3aade0649b0553742db3664/locale/pl/LC_MESSAGES/server.po#L469-L488

**Comment by shane-tomlinson** [comment]
Fixed by https://github.com/mozilla/fxa-content-server-l10n/pull/131. Closing.
