### ISSUE TITLE
Disconnected devices don't disconnect

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3807]
During our weekly Sync workout, @vladikoff disconnected my Firefox from our temporary account, but I remain disconnected through many manual syncs. Does Push change this?

**Comment by rfk** [comment]
@ryanfeeley do you mean "I remain connected through many manual syncs"?  Did @vladikoff disconnect you through the devices view?  If so, then yes, I would expect push to change this by making the device discover the disconnection event quicker.

**Comment by ryanfeeley** [comment]
> Did @vladikoff disconnect you through the devices view? If so, then yes, I would expect push to change this by making the device discover the disconnection event quicker.

Yes.

**Comment by vladikoff** [comment]
@eoger when you get a second could you link the desktop bug that should help with this? (we merged server support for this earlier)

**Comment by shane-tomlinson** [comment]
Needs to be fixed in the browser. Closing here.

**Comment by eoger** [comment]
[Desktop bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1277026)
