### ISSUE TITLE
password-mixin.js->onPasswordKeyUp is missing unit tests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3809]
<img width="1067" alt="screen shot 2016-06-02 at 11 57 05" src="https://cloud.githubusercontent.com/assets/848085/15742861/5a644dfc-28b9-11e6-8b59-493615a1855c.png">

@vbudhram - I missed this when reviewing #3793.

**Comment by vbudhram** [comment]
Sorry about that 😢, will add!
