### ISSUE TITLE
Expired reset links too numerous

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3831]
About 1/5 password reset links appear to be expired (1025).

What's happening?

<img width="562" alt="screenshot 2016-06-09 18 02 26" src="https://cloud.githubusercontent.com/assets/68213/15947996/7015bf7e-2e6c-11e6-8f50-a23b5d7447c9.png">

**Comment by TDA** [comment]
@ryanfeeley Could be due to low timeout of password_reset_links?
`VERIFICATION_POLL_IN_MS` seems to be set to `4000` or am I looking at the wrong stuff?

**Comment by TDA** [comment]
@ryanfeeley Changing that value seems to have no effect on the expiration. Passwords still expire for me.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - which DataDog graph is this?

**Comment by ryanfeeley** [comment]
@shane-tomlinson It's on the FxA Content Server - Password Resets dashboard. Still the top error by far on this page.

**Comment by vladikoff** [comment]
@shane-tomlinson do you remember the reason to use error 1025 if we receive unknown account here: https://github.com/mozilla/fxa-content-server/blob/c3c04f81262c7fbbd41d00f500c2006f69cf9250/app/scripts/views/complete_sign_up.js#L138 ?  (and some other places)

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you remember the reason to use error 1025 if we receive unknown account here: https://github.com/mozilla/fxa-content-server/blob/c3c04f81262c7fbbd41d00f500c2006f69cf9250/app/scripts/views/complete_sign_up.js#L138 ? (and some other places)

Yeah, the thought was if the account is unknown when the user goes to click on a verification link, the user has deleted their account and the link has effectively been expired.

**Comment by vladikoff** [comment]
@shane-tomlinson do you think it makes sense to introduce a new error code with the same message so we can debug this issue and figure out if it is a true 1025 throwing or the "
account got deleted case"

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you think it makes sense to introduce a new error code with the same message so we can debug this issue and figure out if it is a true 1025 throwing or the "
account got deleted case"

Seems totally sane to me.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-auth-db-mysql/issues/149

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3989 which is to use a separate error code for account deleted. The message can be the same.

**Comment by philbooth** [comment]
Ref https://github.com/mozilla/fxa-auth-server/issues/1373

**Comment by vladikoff** [comment]
This should be fixed via https://github.com/mozilla/fxa-auth-server/issues/1373

Reopen if still see it
