### ISSUE TITLE
Line break on permission screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3833]
Spotted this on Latest when trying out the Pocket registration flow.
<img width="484" alt="screenshot 2016-06-10 12 58 27" src="https://cloud.githubusercontent.com/assets/68213/15972424/675dff36-2f0c-11e6-819e-a327438440cc.png">

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/15972524/f1b8da8e-2f0c-11e6-93d7-464af23e63cf.png)
