### ISSUE TITLE
Get rid of "signed out successfully" message

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3835]
What's with the blip?
![white](https://cloud.githubusercontent.com/assets/68213/15975491/b8137a78-2f1b-11e6-9c3d-78651dfd977f.gif)

**Comment by vladikoff** [comment]
u got auto fill?

**Comment by ryanfeeley** [comment]
Ah, yeah, I had saved the password @vladikoff. What should we do?

**Comment by shane-tomlinson** [comment]
I was fixing this elsewhere. There may be a bug already filed.

**Comment by shane-tomlinson** [comment]
This is due to a collision in `afterRender` with one of the mixins. I could swear I fixed this.

**Comment by vladikoff** [comment]
> This is due to a collision in afterRender or afterVisible with one of the mixins. I could swear I fixed this.

Are you sure it is not autofill?

**Comment by shane-tomlinson** [comment]
> Are you sure it is not autofill?

No, not sure. I had a thought last night that it wasn't my PR that the similar problem I saw was fixed in earlier, but rather @rfk's. [Here's a link to the discussion](https://github.com/mozilla/fxa-content-server/pull/3736#discussion_r65227503)

**Comment by shane-tomlinson** [comment]
Copying in the relevant portions of the referenced thread:

> This is the offending line. We now have two `afterRender` functions that return a promise. This and [afterRender in sign_up.js](https://github.com/mozilla/fxa-content-server/blob/d45a60cc79aad37af1a64eadd07b695bcc29078c/app/scripts/views/sign_up.js#L101). Whichever resolves first will cause [displayStatusMessages](https://github.com/mozilla/fxa-content-server/blob/d45a60cc79aad37af1a64eadd07b695bcc29078c/app/scripts/views/base.js#L199) to be called. Since the afterRender in sign_up.js itself returns a promise, `displayStatusMessages` is called, and THEN [FormView's afterRender](https://github.com/mozilla/fxa-content-server/blob/d45a60cc79aad37af1a64eadd07b695bcc29078c/app/scripts/views/sign_up.js#L111) function is called, which calls `enableSubmitIfValid`. Since the error message was previously displayed, the model contains no `error` and the error message is taken away.
...
> What's the solution? Maybe rename this function from "afterRender" to "afterVisible". It doesn't fix the underlying collision issue with Cocktail, it just sidesteps the issue. I hope.
...
> Local testing of the name change from afterRender to afterVisible does seem to fix the problem. Don't know what that does to all of your stuff though. ;)

**Comment by shane-tomlinson** [comment]
> Are you sure it is not autofill?

Though after watching the video several times, this does seem the most straight forward possible explanation.

**Comment by shane-tomlinson** [comment]
We take away the error messages on a change event, maybe we have to do some ghetto state management and only remove the messages on a keyup/keypress event, if the element value has changed.

**Comment by vladikoff** [comment]
Action item: get rid of signed out successfully
