### ISSUE TITLE
Focus input fields after user clicks cancel in settings page and navigates to the child view again

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3843]
Currently, when the user presses `cancel` on any of the settings-child-views, once the panel is hidden, the focus is lost. So if the user clicks `change` again, the input fields are not focused.

### STR:
1. Click `change` on `display_name` in `settings` view. Notice that the input field is focused.
2. Click `cancel` on settings/display_name.
3. Click `change` on `display_name` in `settings` view again. Notice that the input field is *not* focused.

~~Kinda~~ Closely related to #3648

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/3845
