### ISSUE TITLE
Regression: TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3846]
![image](https://cloud.githubusercontent.com/assets/128755/16124980/77b483d2-33e9-11e6-9a7a-ce28da1b9101.png)

```
TypeError: setting a property that has only a getter
  at this(main.js:20314:22)
  at ErrorUtils(main.js:20332:6)
  at cb(main.js:56508:13)
  at HandleCallback(main.js:19859:7)
  at Then(main.js:19851:3)
  at Then(main.js:19557:3)
```
Ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/336231/

**Comment by shane-tomlinson** [comment]
When I saw this locally, we were attempting to add a property to an error that was a  String. This works in Chrome, but not Firefox.

**Comment by vladikoff** [comment]
From vidyo: 

seems like some error objects cannot have their message changed.
To fix this issue let's use a Try Catch, and maybe signal to `captureException` that the error was the one where we could not change the message.

**Comment by vladikoff** [comment]
@larissagaulia let's try to merge this one for train-65

**Comment by vladikoff** [comment]
Some notes: https://github.com/mozilla/fxa-content-server/blob/2cad043a2a09f25e54c5f59e8c6a637da89419d2/app/scripts/lib/error-utils.js

### Current:

```js
 // Ensure the message is interpolated before sending to
 // sentry and metrics.
 error.message = this.getErrorMessage(error);
 sentryMetrics.captureException(error);
```

### Patched (pseudocode):

```js
 // Ensure the message is interpolated before sending to
 // sentry and metrics.
 try {
 // some errors do not allow reassigning a read-only message property
 error.message = this.getErrorMessage(error);
} catch(e) {
 // unable to change error message.
}
 sentryMetrics.captureException(error);
```
You can mock `getErrorMessage` in the test make sure it throws.
Check other tests that do (or use `sinon.stub`):
```js
        view.afterSubmit = function () {
          throw new Error('error that is not displayed');
        };
```

Let's ignore this: ` maybe signal to captureException that the error was the one where we could not change the message.` from above. we are going to report the error anyway, don't want to double the rate of same errors..
