### ISSUE TITLE
Flush caches on TravisCI?

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3855]
TravisCI seems to *not* be running the latest of our linting tools: sasslint, eslint etc.

From @pdehaan IRC:
```
not sure how to flush caches on travis-ci, maybe talk w/ Vlad+Shane tomorrow as to why our CI is lame
```

**Comment by vladikoff** [comment]
Removed in https://travis-ci.org/mozilla/fxa-content-server/caches

might help
