### ISSUE TITLE
add `shrinkwrap`ing as a command in package.json

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3859]
From https://github.com/mozilla/fxa-auth-server/pull/1293#issuecomment-227262890, we should probably add a shrinkwrap command to the content-server as well, just like the auth-server, so that all of us are using the same flow.
(Also, this will definitely save me from screwing up *almost* every time I regen shrinkwrap)
@pdehaan

**Comment by vladikoff** [comment]
@pdehaan can we instead develop a module with a `bin` that does this and include it all our projects? not just fxa?

**Comment by vladikoff** [comment]
@pdehaan it should support some args like `--dev` for wrapping dev deps if needed. (in fact this may exist already)

**Comment by pdehaan** [comment]
> can we instead develop a module with a bin that does this and include it all our projects?

I'd like to say "no" (mainly because the first command is `rm -rf node_modules` which would delete your theoretical module that you're trying to run). But I can run this past @jrgm and see if he has any ideas, versus just copy-pasting a 60 character npm script into the 7 FxA repos.

**Comment by vladikoff** [comment]
@pdehaan it can either be a global tool then OR maybe it can just from memory?

**Comment by TDA** [comment]
Why not a grunt-task/shell-script on fxa-local-dev instead? it searches all subdirs (fxa-*), and then runs those commands? @pdehaan

**Comment by pdehaan** [comment]
I published [**npmshrink**](https://www.npmjs.com/package/npmshrink) and it _seemed_ to work when I `npm install`ed it globally, but your mileage may vary.

**Comment by TDA** [comment]
@pdehaan Needs readme. r-.

**Comment by pdehaan** [comment]
@TDA the module is only 4 lines of shell script, I have faith you'll be able to crack the code.

**Comment by TDA** [comment]
@pdehaan Needs tests.

**Comment by vladikoff** [comment]
👀

**Comment by pdehaan** [comment]
> @pdehaan Needs tests.

Ha! Pull requests welcome.

**Comment by vladikoff** [comment]
move docs to /fxa-local-dev or /fxa with usage for @pdehaan module?  @rfk ?

**Comment by rfk** [comment]
It's not obvious to me what the proposed alternatives are here, is it:

```
npm run shrinkwrap
```
 versus

```
npm install -g npmshrink
npmshrink
```

I don't have any strong preferences here.

**Comment by shane-tomlinson** [comment]
fwiw, I removed the `npm run shrinkwrap` command from the referenced auth server PR.
