### ISSUE TITLE
Empty page if fxa-auth-server cannot be reached

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3863]
This is a possible regression, STR includes turning off the auth-server but users might experience this when the auth server is failing to connect.
## STR
- Create account, verify, go to settings
- Turn off fxa-auth-server locally
- Refresh /settngs
## Actual
- blank screen
## Expected
- Navigate to sign_up / sign_in page or some error state

![w](https://cloud.githubusercontent.com/assets/128755/16236546/bb4bde86-37a6-11e6-861b-09d8e48ba781.gif)

**Comment by vladikoff** [comment]
waiting for @shane-tomlinson to discuss this.

**Comment by shane-tomlinson** [comment]
> This is a possible regression, STR includes turning off the auth-server but users might experience this when the auth server is failing to connect.

This may be related to the recent checkAuthorization change I made to views/base.js, though I'm not sure. We call `/recovery_email/status` to check the status of the session, then call /certificate/sign so we can fetch an OAuth token to get the user's profile and basket information. We do session check before a view's [beforeRender](https://github.com/mozilla/fxa-content-server/blob/0ff2e355efb898c82822dc5bbfbdab9351f25b21/app/scripts/views/base.js#L178), if there is a problem, the error is first checked in [checkAuthorization](https://github.com/mozilla/fxa-content-server/blob/0ff2e355efb898c82822dc5bbfbdab9351f25b21/app/scripts/views/base.js#L249). If the session is expired, then we redirect to a signin or signup page. Other errors are re-thrown and caught by [views/app.js](https://github.com/mozilla/fxa-content-server/blob/0ff2e355efb898c82822dc5bbfbdab9351f25b21/app/scripts/views/app.js#L126), which delegates to [views/base.js->fatalError](https://github.com/mozilla/fxa-content-server/blob/0ff2e355efb898c82822dc5bbfbdab9351f25b21/app/scripts/views/base.js#L575) where the error is reported to Sentry and nothing else happens. The user is left without feedback. Not awesome.

**Comment by shane-tomlinson** [comment]
If no viewed is displayed, we would have to render *something* in which we could print the error message.

**Comment by vladikoff** [comment]
Let's close this for now unless we see it again
