### ISSUE TITLE
Fix nsp https://nodesecurity.io/advisories/117 warning

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3865]
From https://nodesecurity.io/advisories/117, travis reports one more vulnerability. Should we make NSP as warnings instead of errors? I know it sounds stupid, but having to update .nsprc with stuff everyday seems redundant since most of these are so downstream that we need to wait for PR's to land there and propagate upstream :|

@pdehaan I am blaming you.

**Comment by pdehaan** [comment]
I accept your blame.

I prefer errors over warnings, mainly because:

1. I get to make you do all the work.
2. If they are demoted back to warnings, they may get overlooked.

Updating .nsprc every day is awesome because it means that new vulns are being found+disclosed+fixed in the Node community.

**Comment by TDA** [comment]
`I get to make you do all the work`
Naish. Anything you want sensei.

**Comment by vladikoff** [comment]
Once this is fixed remove 117 from https://github.com/mozilla/fxa-content-server/blob/master/.nsprc#L22
