### ISSUE TITLE
"Unexpected Error" when opening communication preferences when basket is in maintenance mode.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3866]
First noticed by @jbuck.

Basket seems to be in maintenance mode, calling lookup_user results in a response of:

<img width="456" alt="screen shot 2016-06-22 at 15 01 43" src="https://cloud.githubusercontent.com/assets/848085/16269513/80ea8942-388a-11e6-87ba-92503eed3a6d.png">

This causes this error to be thrown:

<img width="235" alt="screen shot 2016-06-22 at 15 01 01" src="https://cloud.githubusercontent.com/assets/848085/16269528/8b2d1ce4-388a-11e6-9c58-4c9a9b9f6ca8.png">

Which is displayed to the user as:

<img width="487" alt="screen shot 2016-06-22 at 15 01 28" src="https://cloud.githubusercontent.com/assets/848085/16269531/913b7874-388a-11e6-88a5-42e76f7041db.png">

This occurs in prod right now.

**Comment by jbuck** [comment]
From #moc:

> 10:07 AM <jbuck> jgmize: pmac: either of you around? FxA is getting a {"status": "error", "code": 1, "desc": "user data is not available in maintenance mode"} from basket.m.o
> 10:07 AM <pmac> jbuck: yeah. hoped to be out of maintenance today, but not looking good now.
> 10:08 AM <pmac> I'm hoping we can get at least user data back shortly
> 10:09 AM <jbuck> pmac: okay, is there a bug I can follow?
> 10:11 AM <pmac> jbuck: not at present. we're working with the contractor doing the work. basket is switching backend providers from Exact Target to salesforce.com
