### ISSUE TITLE
Create Account button is empty during account creation request

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3882]
![sign2](https://cloud.githubusercontent.com/assets/128755/16400230/88a9b4e8-3ca7-11e6-9269-a6a7f6530e3a.gif)

You can see the text disappears for 1-2 seconds. try on a slow connection for maximum emptiness 🐞

**Comment by shane-tomlinson** [comment]
Doh, that's because the spinner is white. cc @ryanfeeley

**Comment by TDA** [comment]
Should the spinner be changed to the `$color-blue: #0996f8;` ? /cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@shane-tomlinson @TDA Shouldn't the button be blue in this state? Ideally it should be white spinner on blue button, no?

**Comment by vladikoff** [comment]
>Shouldn't the button be blue in this state? 

Isn't the button disabled after submit? and following the guidelines disabled buttons are white?

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson @TDA Ah true, the button is disabled… I don't think the spinner should be blue, but rather the same colour as the Create Account text which I believe is #999. Make sense?
