### ISSUE TITLE
Unexpected error on comm prefs eats the horizontal rule

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3886]
Only seems to happen on latest when there is an unexpected communication preferences error, but I noticed that the horizontal rule gets eaten and there is nothing between the Cancel button and the Password section.

![screenshot 2016-06-28 15 40 37](https://cloud.githubusercontent.com/assets/68213/16429820/c0c0d812-3d46-11e6-820b-f3d6bc4c5586.png)

**Comment by TDA** [comment]
Is this perhaps because the Cancel button is pushed down a bit?

**Comment by ryanfeeley** [comment]
@TDA Maybe? But there should be a line between the Cancel button and the Password heading.

**Comment by TDA** [comment]
@ryanfeeley Is this still occurring? I think the side-by-side subscribe/cancel does not exhibit. If you can confirm, we can close this.

**Comment by vladikoff** [comment]
@TDA stop the fxa-basket-proxy via `./pm2 stop 4` and you will see:

![](http://v14d.com/i/57bde3340752f.jpg)

**Comment by ryanfeeley** [comment]
Still happening for me on: latest.dev.lcip.org
