### ISSUE TITLE
"didn't arrive? resend" fade in is very very very sllllooooowwww.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3887]
cc @ryanfeeley - can we make this a half second? 5 seconds is cooky and gives the whole page an unbalanced feel.

![resend-fadein](https://cloud.githubusercontent.com/assets/848085/16451949/ddce9270-3dfd-11e6-91b0-3ecb3b1d8383.gif)

**Comment by vladikoff** [comment]
@shane-tomlinson it has to be slow IMHO. we had an elevated graph of people just clicking send because we removed the "1st and 4th send only earlier". 

Maybe we should fade "Back" as well? (I wonder if some users will started pressing "Back" too now 😜  )

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson it has to be slow IMHO. 

A longer delay seems sufficient to address rapid fire clicks, the unnaturally slow fade-in is ugly.

**Comment by shane-tomlinson** [comment]
I also suggest we stack the two sides vertically, the back button hanging out by itself looks off balance.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Well spotted. Keen eye appreciated Shane!

**Comment by ryanfeeley** [comment]
@vladikoff Fading both in seems like the best solution.

**Comment by TDA** [comment]
👍 for stacking them instead of side-by-side, that way we won't have to fade in the `back` button. Also, since animations arent supported on FF <= 31, we should probably have this as a transition that gets triggered on page load, that way we can support FF >=4.

**Comment by shane-tomlinson** [comment]
Re-opening, both buttons fade in, which is better, but the fade in is still very slow.

**Comment by vladikoff** [comment]
I think the speed is fine. In addition since we started sending email on each click (+sign in confirmation?) the metrics on the endpoint tripled. 
![image](https://cloud.githubusercontent.com/assets/128755/16489764/f4a6054e-3ea4-11e6-9565-caebd1758c7c.png)


@ryanfeeley please check the speed 🚤

**Comment by shane-tomlinson** [comment]
> I think the speed is fine. In addition since we started sending email on each click (+sign in confirmation?) the metrics on the endpoint tripled. 

@vladikoff and I have determined we were talking past each other. The delay is fine, and necessary. We could probably even increase that. It's the fadein speed I think looks ugly.

**Comment by vladikoff** [comment]
from irc: 

```
[11:18:24]  <vladikoff>	rfeeley, yea but stomlinson says the fade speed is slow (not the delay of the fade)
[11:18:53]  <vladikoff>	rfeeley, pause before the fade is fine, but the fade itself is slow
[11:19:08]  <rfeeley>	vladikoff: he’s right. one second should be fine.
```

@larissagaulia Is there a way we can make the animation be : `5 second pause` before the animation then `1s fade` for the button.
