### ISSUE TITLE
sign in of unverified user results in two emails being sent

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3890]
STR

1. Sign up to an FxA account, do not verify.
1. Sign in with email from step 1. Which email should I use to verify? If I click the "complete sign in" email, I am asked to re-confirm my address. If I click the "complete sign up" one, everything works correctly.

Caused by https://github.com/mozilla/fxa-auth-server/issues/1314, but functional tests need to be added here to ensure the flow works as expected.

**Comment by vladikoff** [comment]
Fixed in fxa-auth-server, still need to add tests

**Comment by shane-tomlinson** [comment]
> Fixed in fxa-auth-server, still need to add tests

Hey, I think I have a PR to do just that. Assigning to me.
