### ISSUE TITLE
Sign-up does not degrade gracefully

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3891]
### STR:
* Sign up for a new account without `styles` loaded (slower connection, or disable stylesheets)
* Click submit

### Expected results
* `email resent` is not visible

### Actual Results
* `email resent` is visible

<img width="505" alt="screenshot 2016-06-29 11 39 21" src="https://cloud.githubusercontent.com/assets/432707/16464298/66ce0520-3dee-11e6-97e5-22bcbe840040.png">

**Comment by vladikoff** [comment]
I don't think we support these edge cases where some notifications are not showing. As long as the email gets resent we should be good IMHO

**Comment by TDA** [comment]
@vladikoff This has 2 notifications instead of 1. Is that all right? `Email resent` and `Email sent`?

**Comment by vladikoff** [comment]
> @vladikoff This has 2 notifications instead of 1. Is that all right? Email resent and Email sent?

Yeah, header vs info notification
