### ISSUE TITLE
Store the canonical email capitalization returned by the server in local storage

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3893]
I noticed that when I logged into my account with ALL-CAPS, that my email appeared in ALL-CAPS in Settings.

When I logged in to a second device and used mIxEd CaSe the ALL-CAPS was replaced with the mIxEd CaSe version.

Should we be respecting how users happen to capitalize their emails when authenticating? I can't think of any good reasons why we should.

**Comment by rfk** [comment]
We store the capitalization entered by the user when they first signed up, and I think we should use that consistently.  AFAICT this is just the content-server storing the email in localstorage in weirdly capitalized form, and it should instead store the canonical capitalization returned by the server.

(There's a whole "incorrect email case" error returned by the server to help drive this process)

**Comment by divyabiyani** [comment]
I want to work on this bug.
Could someone help me on where to get started?

**Comment by vladikoff** [comment]
@rfk @shane-tomlinson I checked the /create and /login logic and it does not return the email created with in the response? Should we change that?

For sign-in we might be able to fix this bug by returning the email from the error: https://github.com/mozilla/fxa-js-client/blob/master/client/FxAccountClient.js#L256-L259

But that will not work for signup

**Comment by shane-tomlinson** [comment]
The call to `/account/create` probably doesn't need to be updated, we'll have the email the user signed up with already. The call to `/account/login` probably should, and we should check the password reset flow. I'm wondering what other edge cases exist. We should probably take care to display the right thing if the user already has a session and goes directly to settings, the call to /recovery_email/status could return the email too, which will be saved to the account data and displayed.

This might be meatier than our typical "good first bug"

**Comment by vladikoff** [comment]
> The call to /account/create probably doesn't need to be updated, we'll have the email the user signed up with already. 

The issue is that we will have `WOWCAPS` locally but on the server it will lowercase it to `wowcaps`, then there is a mismatch.

![image](https://cloud.githubusercontent.com/assets/128755/18837512/02e4f36e-83d2-11e6-830c-7955971bacf1.png)

**Comment by shane-tomlinson** [comment]
Ahha, if the user has signed up previously but never verified?

**Comment by vladikoff** [comment]
from mtg:
- for signup no need to worry about it
- for signin: the login endpoint should return the email and we need to use it.
- **is this worth doing?**

**Comment by vladikoff** [comment]
from mtg: 

* 'lowercase' everything?

**Comment by ryanfeeley** [comment]
👍

**Comment by rfk** [comment]
> for signin: the login endpoint should return the email and we need to use it.

This is supposed to already happen, if you enter an incorrectly-cased email, you should get this errno=120 and be told the correct case to use:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/error.js#L187

If that's not happening, it's a bug somewhere.  (And conversely, if you don't see this error, that means the user entered their email with the expected capitalization).

**Comment by vladikoff** [comment]
> This is supposed to already happen, if you enter an incorrectly-cased email, you should get this errno=120 and be told the correct case to use:

Yea this works, it is caught by the fxa-js-client but we can tweak that.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4463

**Comment by vladikoff** [comment]
@shane-tomlinson also see https://github.com/mozilla/fxa-content-server/issues/3893
