### ISSUE TITLE
avatar photos are not synchronized

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3897]
STR (using two browsers):

1. Using an account without a profile photo, point browser A and browser B to /settings.
1. In browser A, set a profile photo.
1. In browser B, click "Add avatar" button.
1. New profile photo shows up in the modal dialog after a moment. Close the modal. Why isn't the profile photo there too?

![add-a-photo-funk](https://cloud.githubusercontent.com/assets/848085/16488316/d710b268-3ec7-11e6-8ea2-620b3786259e.gif)

Found while testing #3850

------------------------

One possible solution is to use a global "Account" model that is passed to all the views. Views would subscribe to changes on the global account model and update their UI appropriately. MVC basics. Instead, we have ephemeral Account models that are not shared and we have to a lot of unnatural tracking of changes.

**Comment by vladikoff** [comment]
Does this seem like a very highly unlikely scenario where a user has to have two different browsers, both signed to FxA and be changing the avatar? Or is there a more common story here? (I think we had a similar issue open before about this)

**Comment by TDA** [comment]
@shane-tomlinson  @vladikoff Is it just me, or are the button colors getting screwed up on this view as well? Seems to me, after clicking `Take Picture`, it whites out for a second 😱

**Comment by vladikoff** [comment]
@TDA that should be fixed now, different issue

**Comment by TDA** [comment]
@vladikoff Ok cool, I think this issue is filed cuz of the issues raised in https://github.com/mozilla/fxa-content-server/pull/3850 ?

**Comment by shane-tomlinson** [comment]
You are right @vladikoff that these are highly contrived STRs, and I am perfectly fine backlogging this forever. 

What worries me more than the photo is that we aren't automatically keeping Account data in sync across multiple views of what is supposed to be the same data. MVC solved that problem years ago, we just haven't been making use of it.

**Comment by vladikoff** [comment]
from mtg: kill it cc @TDA
