### ISSUE TITLE
Display warning message when I type an empty `Display Name`

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3901]
When I open the display name panel, I might select `Change` without entering a name. This is exacerbated by the fact that now we remove `Display Name` on pressing `Cancel`.

@ryanfeeley Would it be better to display a warning, what is the optimal UX in this situation?

**Comment by ryanfeeley** [comment]
@TDA It should still be possible for users to remove their display name by emptying the field and press Change.

Should we keep the Change button disabled until there is a change detected?

Pressing Cancel should function like a form reset button, not clear. If the user has a name set and presses cancel, their name should remain. In this way, it differs from the password field.

**Comment by vladikoff** [comment]
Thanks @ryanfeeley !

**Comment by vladikoff** [comment]
It should reset the value back to the original (set display name, (current username))

"When web forms first came out there was a reset button and it was good" ~ @ryanfeeley

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/3845

**Comment by ryanfeeley** [comment]
![0d701a6118310243dc267074288f37ac](https://cloud.githubusercontent.com/assets/68213/17604911/dfb9de96-5fe5-11e6-9aef-e21ab2e47e72.jpg)
