### ISSUE TITLE
tests: implement a utility function to close windows (and never close the last window).

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3902]
So, we've had issues running the functional tests where a test would fail, and then every subsequent test would fail, reporting "browser may have died". 

Having seen it happen locally, I believe it's where the test code closes the last window (which quits the browser on *nix and win32, although not on osx). 

So, refactor the tests to do all window closing in a utility function that punts on window close if there is only one remaining window.

**Comment by shane-tomlinson** [comment]
> So, refactor the tests to do all window closing in a utility function that punts on window close if there is only one remaining window.

This is a great idea. Abstract all the actions. 🍰

**Comment by shane-tomlinson** [comment]
ref #4002 because this seems to happen a lot more with Marionette.
