### ISSUE TITLE
"Looking for Sync" and status messages are displayed together - looks sloppy.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3903]
If a status message (success or error) is displayed in sign in or sign up, both the status message and the blow "Looking for Sync" message are displayed together, which looks a bit sloppy.

STR

1. Sign in to an account.
1. From the settings page, sign out.
1. Look at the signin page.

<img width="453" alt="screen shot 2016-07-01 at 12 55 05" src="https://cloud.githubusercontent.com/assets/848085/16557415/763f5c6a-41d7-11e6-8f3c-df800dff6818.png">

Proposed fix:

Only display the "Looking for Sync" message if no status message is displayed when the page is first rendered. If a status message is displayed, the user is probably signing out, or their session has expired. In either case, the user is probably not looking for Sync and the status message is needless information.

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
The "Looking for Sync" message also appears if the user has already signed in to Sync and then visits https://accounts.firefox.com directly.

<img width="462" alt="screen shot 2016-07-04 at 14 00 09" src="https://cloud.githubusercontent.com/assets/848085/16561170/af8d7c00-41ef-11e6-9d87-f0c361242768.png">

**Comment by vladikoff** [comment]
> if the user has already signed in to Sync and then visits https://accounts.firefox.com directly.

Yeah I'm not sure how many people we want to direct to Sync from there. up to @ryanfeeley. 
We could also be missing some metrics from the "suggested sign in view" because that one is reported as the "sign in" view.

**Comment by vladikoff** [comment]
Action item: keep the 2 panels with error / notification, but remove this from Sign In

**Comment by ryanfeeley** [comment]
We’re not trying to prevent people from signing in to manage their account, we are trying to prevent people registering for a Firefox Account from going to Settings when they actually want to set up Sync.

It's only needed on accounts.firefox.com/signup (with no service).
