### ISSUE TITLE
Improve time granularity of device manager

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3907]
For localization reasons, we descoped the original design and stripped off the numbers. I'm still uncomfortable with this decision and think we should internationalize the connection times to include numbers.

![devices-disconnect-and-refresh-only](https://cloud.githubusercontent.com/assets/68213/16558723/847f3ed4-41b5-11e6-929b-c1c3c9218712.png)

I'm sure someone at Mozilla has already translated this, although I haven't done an exhaustive search to find out where.

**Comment by shane-tomlinson** [comment]
To do this, we'll need to figure out how to do singular/plural in our translation tools. We've restricted ourselves to a single form so far.

For example:

`1 minute ago`
`2 minutes ago`

[Well defined formats for this exist](https://www.gnu.org/software/gettext/manual/html_node/Translating-plural-forms.html), we just have to figure out how to use them within our tooling.

We have to figure out how to create `msgid` and `msgid_plural` within our extracted .po files.

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-bugzilla-mirror/issues/154
