### ISSUE TITLE
Sort devices by last synced and not last authenticated

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3908]
Currently our device manager lists devices by last authenticated, rather than last synced, which is likely the greater security concern of the two.

We should discuss and consider working with the sync team to be able to present a last synced time.

**Comment by shane-tomlinson** [comment]
Ref #3899

**Comment by vladikoff** [comment]
WE DID IT. (by last connected + name)

**Comment by vladikoff** [comment]
Not last synced, see other issue

**Comment by ryanfeeley** [comment]
@vladikoff I was missing a word in the title…

**Comment by vladikoff** [comment]
@ryanfeeley oh, are we planning to have "last synced time" available?

**Comment by ryanfeeley** [comment]
@vladikoff 
> We should discuss and consider working with the sync team to be able to present a last synced time.

**Comment by vladikoff** [comment]
Setting [not actionable] because we don't have an api to consume for this yet.

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
agreed this would be nice, but not likely to be able to move on it in q3

**Comment by vladikoff** [comment]
Needs https://github.com/mozilla/fxa-auth-server/issues/1044

**Comment by vladikoff** [comment]
cc @udaraweerasinghege let's check this by looking at the new fields we are adding in the auth server

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/5264
