### ISSUE TITLE
Error when using local FxA with Android Firefox

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#3918]
Not sure if this is the correct spot for this, but figured it might be good to track. Currently, when using either an emulator or physical android device and using Firefox browser, all requests to a local FxA will fail.

STR:

1) Run fxa-local-dev
2) Reconfigure Firefox Android browser to point to local FxA. [Reference]( https://docs.services.mozilla.com/howtos/run-fxa.html)
3) Attempt to sign-in or perform an action, will give `Unexpected Error` will the following trace.

```
module.exports.toError@http://192.168.0.5:3030/scripts/lib/errors.js:106:17wrapClientToNormalizeErrors/wrappedClient[key]</<@http://192.168.0.5:3030/scripts/lib/fxa-client.js:45:19onSettled@http://192.168.0.5:3030/bower_components/fxa-js-client/fxa-client.js:800:9flush@http://192.168.0.5:3030/bower_components/fxa-js-client/fxa-client.js:507:4
```

Note: When pointing to a deployed version of FxA, this error does not occur.

**Comment by rfk** [comment]
I wonder if it's freaking out because of `http://` rather than `https://`.

**Comment by vbudhram** [comment]
@rfk That very well could be it. Do you know anyone else that has run Fennec with a local FxA system? Possible that I am missing some setting in Fennec?

**Comment by rfk** [comment]
Unfortunately I do not, and TBH I haven't tried it myself either.

**Comment by vladikoff** [comment]
Use instructions from here: https://github.com/mozilla/fxa-local-dev#firefox-for-android

![image](https://cloud.githubusercontent.com/assets/128755/18894970/217af4b4-84e4-11e6-9ecc-682e7004bc3e.png)
