### ISSUE TITLE
User can still interact with settings page after being disconnected from another device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3928]
Follow on from https://github.com/mozilla/fxa-content-server/pull/3924.

STR

1. Sign up, verify.
1. Sign in for Sync on two devices.
1. On both devices, open setting page with `forceDeviceList=true` query parameter to see the device list.
1. On device A, find device B in the device list and disconnect it.
1. On device B, change the user's display name.

Expected
User on Device B should not be able to update the user's display name.

**Comment by shane-tomlinson** [comment]
This is due to the OAuth token still being valid even though the sessionToken is not.

**Comment by rfk** [comment]
We should just use short-lived OAuth tokens; a token <= 5mins validity would be just fine settings page purposes.  The `POST /v1/authorization` API on the oauth-server accepts a `ttl` argument for exactly this purpose.

**Comment by shane-tomlinson** [comment]
> The POST /v1/authorization API on the oauth-server accepts a ttl argument for exactly this purpose.

Sounds like an easy, minimal solution - thanks @rfk.

**Comment by shane-tomlinson** [comment]
> Sounds like an easy, minimal solution - thanks @rfk.

I just thought - this will work great for endpoints that require OAuth tokens, but not for change password and delete account. Both require a password, so it's not terrible if a user can interact, but at some point change password may require a verified session token. Maybe we have to check the sessionToken before either of these actions?

**Comment by rfk** [comment]
Right, I think eventually we'll want to move both of these endpoints to requiring a verified sessionToken...but in that case, they avoid the bug here for free, because the sessionToken has been invalidated already.

**Comment by shane-tomlinson** [comment]
Ref #3982

**Comment by vladikoff** [comment]
closed in favour of https://github.com/mozilla/fxa-content-server/issues/3982
