### ISSUE TITLE
Failing functional test: "Firefox Desktop Sync v2 force_auth - unverified - web flow, verify, from original tab's P.O.V."

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3929]
This is using the lastest auth-server and content-server, in dev or prod mode.

When the call to /recovery_email/status is made when the email is finally verified, the session is not marked as verified. This used to pass, not sure what's going on.

cc @vbudhram.

**Comment by shane-tomlinson** [comment]
This failure is due to verification reminder emails. Ugh. Instead of checking the 2nd email, we have to check the 4th email.

**Comment by vladikoff** [comment]
> This failure is due to verification reminder emails. Ugh. Instead of checking the 2nd email, we have to check the 4th email.

Hm you can slow down the reminder emails in dev if you want. It won't break anything, you can set first to 5 seconds and second to 10 seconds.

Here: https://github.com/mozilla/fxa-auth-mailer/blob/master/config/dev.json#L7

**Comment by vladikoff** [comment]
>  we have to check the 4th email.

I suggest not doing that because reminders are sent via polling and it is unpredictable

**Comment by shane-tomlinson** [comment]
Re-opening until the auth-server is re-wrapped with the newest auth-mailer.

**Comment by vladikoff** [comment]
rewrapped! 🔧
