### ISSUE TITLE
Accept and log utm_* metrics params on password change, password reset, and sign-in confirm

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3932]
In https://github.com/mozilla/fxa-auth-mailer/issues/182 we're going to include utm_* metrics parameters in links from our various emails.  I'm kinda hopeful that the existing support for such params in this repo will mean that they just start showing up in datadog for free.

But we should confirm that this is the case for the ones we care about most urgently - the password-change, password-reset and confirm-signin links that form key success metrics for [1].

If I follow e.g. a password-reset link from an email, and the link contains utm_* params, will those params show up as event tags in datadog?

[1] https://github.com/mozilla/fxa/tree/master/features/proposed/FxA-99-improved-login-notification#metrics

**Comment by shane-tomlinson** [comment]
@rfk - can you prioritize this one?

**Comment by rfk** [comment]
We need it for the sign-in geolocation milestone; -> next

**Comment by rfk** [comment]
So AFAICT, we do ingest utm_* params from the page and submit them as part of the metrics bundle to the sever:

  https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/metrics.js#L36

But we don't include them in the events that we send to datadog:

  https://github.com/mozilla/fxa-content-server/blob/master/server/lib/statsd-collector.js#L25

So we may have some amount of server-side work to do to ensure we can analyze the metrics from https://github.com/mozilla/fxa-auth-mailer/issues/182.  @vladikoff would it be reasonable to add the utm_* values as tags on the events sent to datadog, or is this likely to cause Bad Things to happen?  I recall there being some issues with specifying too many tags on an event.

**Comment by rfk** [comment]
From mtg: @vladikoff had some thoughts on how to manage this which he's going to record in this bug

**Comment by vladikoff** [comment]
@vbudhram ok so, we already pass the utm params as part of the metrics request:

![](http://v14d.com/i/57a4aaceab199.jpg)

So just add the utm values into https://github.com/mozilla/fxa-content-server/blob/master/server/lib/statsd-collector.js#L27 to attach them to the events.

**Comment by vladikoff** [comment]
I think this was fixed, cc @vbudhram

**Comment by vbudhram** [comment]
Yup! Forgot to link issue, thanks!
