### ISSUE TITLE
empty current device shows up under devices

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3933]
![](http://v14d.com/i/578954cfab00b.jpg)

@philbooth I was working on some stuff locally (using fxa-local-dev) and noticed a device with no name showed up in the devices view. I did not use the account for sync. Should it be there?

**Comment by TDA** [comment]
(Hoping this is not something I did) 😨

**Comment by vladikoff** [comment]
> (Hoping this is not something I did) 😨

<img src=http://v14d.com/i/5772a3a731a58.jpg width=170 />

**Comment by rfk** [comment]
> I did not use the account for sync. 

@vladikoff what did you use the account for?  This is most likely due to the placeholder device stuff, I wonder if it creates a device record when you e.g. log in directly to FxA itself as well as to an OAuth relier.

**Comment by philbooth** [comment]
> Should it be there?

Nope, it's a bug, sorry. (and don't worry @TDA, I introduced it! 😄)

The auth server [checks `request.query.service` in the handler for `/certificate/sign`](https://github.com/mozilla/fxa-auth-server/blob/b536fd736b09e7ac5104127aeb2c4c6a5f8c142b/lib/routes/sign.js#L57-L65) and creates the placeholder device if it's not set or equal to `'sync'`:

```js
} else if (! service || service === 'sync') {
  // Synthesize a device record for Sync sessions that don't already have one
  return devices.upsert(request, sessionToken, {})
    .then(
      function (result) {
        deviceId = result.id.toString('hex')
      }
    )
}
```


Stupidly, I didn't think to check that this wasn't being invoked for normal web sessions when I tested it.

So I guess we need a more foolproof way to differentiate between Sync sessions and non-Sync sessions (which works for all Sync clients, legacy, Fennec etc). Running some tests locally now but also maybe you guys know already?

**Comment by philbooth** [comment]
The secondary issue is that your user agent string appears to have gone down the failed-to-parse execution path, which also troubles me. Digging into that too...

**Comment by rfk** [comment]
Ugh, sorry if I lead you down a wrong path here @philbooth, I was sure content-server always sent `service=foo` when requesting a certificate :-(

Can we change content-server so that it does so?

**Comment by philbooth** [comment]
Just had a quick across-the-partition chat with @shane-tomlinson about this and he didn't seem to freak out too much when I asked if we could send a default service of `'fxa'` (or something) in the no-service case.

Anyway, Shane, this is the context for that question, feel free to comment or make some other suggestion...
