### ISSUE TITLE
Failing functional test: "settings devices - device panel works with query param, same device"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3938]
> firefox on any platform - settings devices - device panel works with query param, same device (2.649s)
AssertionError: device name is correct: expected '' to equal 'Test Runner Session Device'
  at Function.assert.equal  <node_modules/intern/browser_modules/chai/chai.js:2277:10>
  at Command.<anonymous>  <tests/functional/settings_devices.js:105:18>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.device panel works with query param, same device [as test]  <tests/functional/settings_devices.js:104:10>
  at <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>

cc @philbooth

**Comment by philbooth** [comment]
This is fixed by https://github.com/mozilla/fxa-auth-server/pull/1344, which is available in auth server tag `v1.65.1`.

**Comment by shane-tomlinson** [comment]
Thanks for the response @philbooth. Updated locally and good to go.

ref #3937.
