### ISSUE TITLE
Remove signin confirmation transition code

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3939]
Now that signin confirmation is merged and (so far) sticking, we should remove [the transition code](https://github.com/mozilla/fxa-content-server/blob/a2c9656ca7544596ea1eefb5dd8f0bea3de2e43b/app/scripts/lib/fxa-client.js#L411) that was added to the [fxa-client](https://github.com/mozilla/fxa-content-server/blob/a2c9656ca7544596ea1eefb5dd8f0bea3de2e43b/app/scripts/lib/fxa-client.js#L509) to handle independent upgrade and rollback of the auth server and content server.

The unit tests will need to be updated to remove checks for the old paths.

**Comment by vladikoff** [comment]
Not sure that this is a `good-first-bug` might be a lot to explain to new contributors, but i could be wrong
