### ISSUE TITLE
babel-preset-es2015-nostrict is 185 mb

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3944]
@shane-tomlinson is there a way to just select what we use or do we need all the packages https://github.com/alexykot/babel/tree/master/packages ?

**Comment by TDA** [comment]
I think there is a way to install only the presets we want: https://babeljs.io/docs/plugins/
Or i might be completely wrong and you just had to read an entire page with no good info.

**Comment by shane-tomlinson** [comment]
Is the download size causing problems? If so, locally or on CI? Can we use caching to smooth those over? We don't cache deps on Circle AFAICT, which could probably help us out quite a bit. Locally, the npm cache should in general keep a copy so subsequent installs of the same version should not require a full download.

Of the big list of packages, we should only be downloading the ones specified in [es2015-nostrict's package.json](https://github.com/alexykot/babel/blob/master/packages/babel-preset-es2015-nostrict/package.json). 

Here is the size of each component:

```bash
➜  node_modules git:(master) du -h -d 1                              git:(master|)
7.6M	./babel-plugin-check-es2015-constants
7.6M	./babel-plugin-transform-es2015-arrow-functions
7.6M	./babel-plugin-transform-es2015-block-scoped-functions
9.2M	./babel-plugin-transform-es2015-block-scoping
9.3M	./babel-plugin-transform-es2015-classes
12M	./babel-plugin-transform-es2015-computed-properties
7.6M	./babel-plugin-transform-es2015-destructuring
8.8M	./babel-plugin-transform-es2015-duplicate-keys
7.6M	./babel-plugin-transform-es2015-for-of
11M	./babel-plugin-transform-es2015-function-name
7.6M	./babel-plugin-transform-es2015-literals
9.8M	./babel-plugin-transform-es2015-modules-commonjs
9.2M	./babel-plugin-transform-es2015-object-super
9.2M	./babel-plugin-transform-es2015-parameters
8.8M	./babel-plugin-transform-es2015-shorthand-properties
7.6M	./babel-plugin-transform-es2015-spread
8.8M	./babel-plugin-transform-es2015-sticky-regex
7.6M	./babel-plugin-transform-es2015-template-literals
7.6M	./babel-plugin-transform-es2015-typeof-symbol
9.0M	./babel-plugin-transform-es2015-unicode-regex
19M	./babel-plugin-transform-regenerator
190M	.
```

We could possibly ditch the [transform-regenerator](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-regenerator), [unicode-regex]("https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-unicode-regex"), [modules-commonjs](https://github.com/babel/babel/tree/master/packages/babel-plugin-tra    nsform-es2015-modules-commonjs) (unless we go with webpack), and the two class related ones. 

If we can cache the initial download, that to me feels preferable to putting together what will grow to be our own preset.

**Comment by vladikoff** [comment]
> We don't cache deps on Circle AFAICT,

I think it has something in place that does that automatically for node projects. 

Anyway I'm gonna close this because it seems like the 185mb of modules is not a problem for other devs. I noticed a spike in memory usage too which could be related to babel but could be a false report.
