### ISSUE TITLE
Add more info link to Password Hints

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3945]
Now that we have #3731 issue closed by #3791 . We should add the `More info` link to these password hints, and track the number of clicks as a metric to check whether our hints are actually found to be useful by users.

cc/ @rfk 
@ryanfeeley

**Comment by ryanfeeley** [comment]
@tda Yes! Even if we hid it on mobile and showed the link on desktop. Could CSS do that?

**Comment by TDA** [comment]
@ryanfeeley Pretty sure we can :)

**Comment by vladikoff** [comment]
track exits from sign up for the new page

**Comment by rfk** [comment]
> track exits from sign up for the new page

Without blocking the work on this feature, I think this is also a great opportunity to step back and ask, "how will we measure this?".  We can use datadog events to measure e.g. the number of people that

**Comment by rfk** [comment]
Whoops, hit "close and comment" somehow by mistake...

Anyway, I was going to say, we can use datadog events to measure things like "number of people who click the more info link", but I don't think we currently have a good story for measuring things of the form "number of people who did X, and then failed to do Y".

**Comment by shane-tomlinson** [comment]
Assigned to myself to review the text.
