### ISSUE TITLE
Remove the account lockout feature

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3949]
We have had account unlock in our codebase for > 1.5 years, w/o it ever being turned on in production. @ryanfeeley and I did a UX review a couple of weeks ago, and it's a mess. With the coming targeted features meant to keep bad people at bay while minimizing friction for valid users, account lockout doesn't seem particularly useful.

cc @rfk

**Comment by shane-tomlinson** [comment]
@rfk - if you still agree, I'll open corresponding issues in all the other repos.

**Comment by rfk** [comment]
I support this decision; everything that account-lockout can do, we should be able to do with simpler and more generic code via features like https://github.com/mozilla/fxa-features/issues/11

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-features/issues/12
