### ISSUE TITLE
CSP: www gravatar uploads will cause CSP errors

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#3950]
In the profile server we allow uploads of `www.gravatar` profile photos: https://github.com/mozilla/fxa-profile-server/blob/master/lib/config.js#L68

However the content server CSP will block anything besides `https://secure.gravatar` https://github.com/mozilla/fxa-content-server/blob/3e3fdc8948355306bcae738c2051f62aa204cec0/server/lib/csp/blocking.js#L25

@seanmonstar do you remember why would some gravatar photos have `http://www` instead of https? 

cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
If we loosened the CSP rules to allow a gravatar served via http, the browser will display a mixed content warning, which would be pretty gross. Can we just disable `http://www.gravatar` and only allow `https://secure.gravatar.com`, or maybe even slurp up the image from gravatar and serve it ourselves?

**Comment by vladikoff** [comment]
> Can we just disable http://www.gravatar and only allow https://secure.gravatar.com

Probably the way to go, but @seanmonstar might need to confirm why we have support for `http://`

**Comment by seanmonstar** [comment]
Nope, no clue. My guess is it came from an IRC conversation with @zaach. Was it an issue with loading an https image while working on dev? Trying to load it into a canvas to crop? I don't really know.

**Comment by zaach** [comment]
¯\_(ツ)_/¯

**Comment by rfk** [comment]
Do we in fact have anyone using non-https gravatar URLs in production?  Let's look in the DB and if there aren't any, it's probably safe to remove it.

**Comment by vladikoff** [comment]
> Do we in fact have anyone using non-https gravatar URLs in production? Let's look in the DB and if there aren't any, it's probably safe to remove it.

@jrgm @jbuck is there an easy way to check this?

**Comment by jbuck** [comment]
I had a look at the prod database and we only have user-uploaded images and secure gravatar images:

```
+--------------------------------+
| domain                         |
+--------------------------------+
| https://firefoxusercontent.com |
| https://secure.gravatar.com    |
| https://mozillausercontent.com |
+--------------------------------+
```

To obtain this list again simply run: `SELECT DISTINCT SUBSTRING_INDEX(url, '/', 3) AS domain FROM avatars;`

**Comment by jbuck** [comment]
So, I think it's totally okay to only support secure Gravatar images
