### ISSUE TITLE
`Didn't arrive resend` is not translated?

### ISSUE THREAD

**Issue by TDA** [mozilla/fxa-content-server#3952]
<img width="463" alt="screenshot 2016-07-20 19 10 16" src="https://cloud.githubusercontent.com/assets/432707/17009300/426592ea-4eae-11e6-9a9e-9a0076587a53.png">

Was testing out the email flows today when I ran across this. Is this supposed to be this way? Language is `Arabic`.
EDIT: this is on fxa local, might very well be an issue on my computer.

@vladikoff

**Comment by shane-tomlinson** [comment]
It's not translated in the [Arabic .po file](https://github.com/mozilla/fxa-content-server-l10n/blob/5ba1362337639006f2e7d1518f55b94ebac06c22/locale/ar/LC_MESSAGES/client.po#L619), closing as "we have to pass the buck to our localization friends."

cc @mohamed7afezz

**Comment by mohamed7afezz** [comment]
Translated Done :dancer: 
But how be keep in touch with new string @shane-tomlinson?

**Comment by shane-tomlinson** [comment]
Thanks @mohamed7afezz! We generally send an email to the dev-l10n-web mailing list whenever we update the .po files. You can sign up at https://lists.mozilla.org/listinfo/dev-l10n-web to receive notices.
