### ISSUE TITLE
change closeCurrentWindow logic to check if this is the last window

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#3953]
When run on Linux, closing the last window will terminate the browser. So there should be check that this is not the last window before calling closeCurrentWindow, which will cause all subsequent tests to fail. 

The currently running test is already going to fail if it thinks the current window is not the last window, but I reckon the next test should be able to get things back in order.

**Comment by shane-tomlinson** [comment]
Is this a dup of #3902?

**Comment by vladikoff** [comment]
> Is this a dup of #3902?

Should be!
