### ISSUE TITLE
Remove custom FxOS 1.x CSP code when helmet supports the expected directives.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3958]
Follow on for #3940. We merged custom rules for FxOS and old Fennec to use the pre-CSP 1.0 xhr-src directive instead of connect-src. I opened a patch for [helmet's csp module](https://github.com/helmetjs/csp/pull/43) that provides the same functionality. If/when that patch lands, let's ditch our local code and just let Helmet do its thing.

**Comment by vladikoff** [comment]
@shane-tomlinson https://github.com/helmetjs/csp/pull/43 merged, woohoo!
