### ISSUE TITLE
In device manager, preface "minutes/hours/days/weeks/months ago" with "Last active:"

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3960]
In device manager we shouldpreface "minutes/hours/days/weeks/months ago" with "Last active:"

e.g. Last active: months ago

**Comment by vladikoff** [comment]
@ryanfeeley that's false information though no? that information is Authenticated Date, no?

**Comment by ryanfeeley** [comment]
@vladikoff I think "last active" is vague enough. According to @shane-tomlinson or @rfk it's the difference between last authenticated and last synced is within a day or two.
