### ISSUE TITLE
"Looking for Firefox Sync" and "Did you mean" overlap and are the same color, hard to read.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3964]
<img width="351" alt="screen shot 2016-07-22 at 12 10 41" src="https://cloud.githubusercontent.com/assets/848085/17055612/d084a162-5005-11e6-9eb6-5546144c67a7.png">

**Comment by vladikoff** [comment]
Hah, good find!
@ryanfeeley ideas?

**Comment by TDA** [comment]
Shift the tooltip to the bottom instead? But might overlap the password field in that case 😖

**Comment by ryanfeeley** [comment]
Two possibilities:

1. Put an × on the righthand side of the "Looking for Firefox Sync?" message that lets the user close it like the "Did you mean…" message. (my preference)
2. Hide the message after the user has submitted the form. This assumes they read the message and felt that the message was not relevant and proceeded to sign in anyway.

Thoughts?

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff Which of the two solutions work best for you?

**Comment by vladikoff** [comment]
@ryanfeeley 

> Put an × on the righthand side of the "Looking for Firefox Sync?" message that lets the user close it like the "Did you mean…" message. (my preference)

works for me 👍

**Comment by ryanfeeley** [comment]
<img width="486" alt="screenshot 2016-08-04 15 11 07" src="https://cloud.githubusercontent.com/assets/68213/17414974/b06bdc4c-5a55-11e6-8902-7b762b9fcbcb.png">

**Comment by vladikoff** [comment]
@ryanfeeley Thanks!!
