### ISSUE TITLE
Hallway testing of sign-in confirmation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#3968]
@shane-tomlinson mentioned he was planning to do a bit of this around the office, filing an issue so that we don't forget to ask him about the outcomes :-)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - are you comfortable we can close this?

**Comment by ryanfeeley** [comment]
Testing went well with in person (employee) participants and one I observed on usertesting.com. The only big issue is how iOS closes the "confirm this sign-in" email, about which I've already filed a bug.
