### ISSUE TITLE
Discuss a better relative time for device manager

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3973]
I'm hoping we can revisit our "minutes/days/week/months ago" copy.

How can it be better?

Google seems to show "X minute(s) ago" to "X hour(s) ago" and then shows an absolute day (e.g. July 25, 2016).

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa-bugzilla-mirror/issues/154 and #3907
