### ISSUE TITLE
Request settings page OAuth tokens with a TTL of 5 minutes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3982]
This is to help with #3928 where users can still interact with the settings page after they have been disconnected from another device.

**Comment by vladikoff** [comment]
check the oauth client `/v1/authorization';` requests

**Comment by vladikoff** [comment]
Testing this and I got 

```
XMLHttpRequest cannot load http://127.0.0.1:9010/v1/authorization. Request header field ttl is not allowed by Access-Control-Allow-Headers in preflight response.
```

 cc @rfk @seanmonstar

**Comment by seanmonstar** [comment]
The oauth server does not look for the ttl in a header, but as a parameter.

**Comment by vladikoff** [comment]
@seanmonstar ah thanks, confused it with the Push server 👍
