### ISSUE TITLE
signin verification link different if the user clicks "resend"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3984]
If the user clicks "resend" on the "confirm this sign-in" screen, the verification link is different in both emails. Here are the links as reported by `./pm2 logs 0`

The `code` and `uid` are the same, the resume token is different.

![screen shot 2016-07-26 at 16 48 25](https://cloud.githubusercontent.com/assets/848085/17145074/d2c203a4-5350-11e6-8802-3d6a4635f4ba.png)

The first decodes to:

```json
{
  "entrypoint": "menupanel",
  "flowBegin": 1469547963708,
  "flowId": "69b77443d51a8f05aff8614f19b8776d247ba6d7a6d650f9c611b564762445b9",
  "resetPasswordConfirm": true,
  "uniqueUserId": "44fc34df-4af5-4270-b143-f3b5e84d44ca",
  "utmCampaign": null,
  "utmContent": null,
  "utmMedium": null,
  "utmSource": null,
  "utmTerm": null
}
```

The second to:

```json
{
  "entrypoint": "menupanel",
  "resetPasswordConfirm": true,
  "uniqueUserId": "44fc34df-4af5-4270-b143-f3b5e84d44ca",
  "utmCampaign": null,
  "utmContent": null,
  "utmMedium": null,
  "utmSource": null,
  "utmTerm": null
}
```

The first contains `flowBegin` and `flowId`, the 2nd doesn't.

cc @philbooth - is this problematic for your metrics?

**Comment by vbudhram** [comment]
This could potentially make sense, if the user is logging in from a new browser? The [verification code sent](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L1056) corresponds to the current session, so the email will only verify the session that performed resend code request.

**Comment by shane-tomlinson** [comment]
> This could potentially make sense, if the user is logging in from a new browser?

Same browser. Done by clicking "resend" on the confirm signin screen.

**Comment by philbooth** [comment]
This is definitely a bug. Will have a look at fixing it tomorrow.

**Comment by philbooth** [comment]
@shane-tomlinson just reported that this issue also exists for sign-up.
