### ISSUE TITLE
Mobile view shows that fields are focused, but keyboard is not up

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3985]
On mobile devices, when a text input or password field is focused, there is usually a cursor present and the keyboard is exposed. On FxA it appears to be unrelated.

![2016-07-26 11 10 28](https://cloud.githubusercontent.com/assets/68213/17145357/cf2aa788-5327-11e6-8ac0-abfa7a4c829a.png)

Can we get the cursor in there automatically? Or is it better to leave the field unfocused?

**Comment by shane-tomlinson** [comment]
Ref #248, #251.

@ryanfeeley - on mobile, we don't normally autofocus anything if the device supports touch events (see the above referenced bugs). Is that Fx on iOS's Sync sign in screen?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yes, I had signed in previously, but it does with too with the username field on registration.

**Comment by shane-tomlinson** [comment]
Thanks @ryanfeeley - I was able to reproduce this on my wife's iPhone. My guess is the UI web view used by Fx for iOS reports that it doesn't support touch events, so we focus, but the browser realizes the focus is done through JS and refuses to show the keyboard. That or we attempt to focus too early, before the screen is actually visible to the user. In either case, we shouldn't be focusing the input element.

**Comment by vladikoff** [comment]
This should be fixed.
