### ISSUE TITLE
FxA requires scrolling on an iPad 2 when signing in to Sync

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3992]
STR

1. Use and old iPad 2.
2. Load up Fx 5 for iOS.
3. Sign up or in to FxA for Sync

![img_0036](https://cloud.githubusercontent.com/assets/848085/17218767/e6844ffa-54e0-11e6-89fa-5373d4fff3b7.jpg)

![img_0035](https://cloud.githubusercontent.com/assets/848085/17218659/763bcd54-54e0-11e6-8cb9-a545ca990aa8.PNG)

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/firefox-ios/issues/1161

**Comment by philbooth** [comment]
Closing, not actionable by us.
