### ISSUE TITLE
Confirm sign-in submission and resend events are identical

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#3994]
I'm getting matching values for:
* fxa.content.confirm_signin.resend
* fxa.content.confirm_signin.submit

Everything okay?
https://app.datadoghq.com/graph/embed?token=531d55315cee165ec719e255f21470c69400e4a508e45efe8e1960a971d9bc6d&height=500&width=1000&legend=true

**Comment by shane-tomlinson** [comment]
yup, that's because the resend button is hooked up to the submit handler. As expected. There is no actual form being submit, using "submit" in our views was a convenience to reduce the amount of code to be written.

**Comment by ryanfeeley** [comment]
@shane-tomlinson ok, so just ignore that metric?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson ok, so just ignore that metric?

Yeah, should be safe to do so. You'll see the same pattern for fxa.content.confirm.resend/fxa.content.confirm.submit and fxa.content.confirm_reset_password.resend/fxa.content.confirm_reset_password.submit

Though, I have to admit, using submit like this is confusing and not semantically correct. We should stop being lazy and do the right thing. My fault. I should talk to the nearly 3 year younger myself who made that decision.
