### ISSUE TITLE
Tests: verification_redirect=always test fails due to bad state

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4000]
This test - ' firefox on any platform - oauth sign up verification_redirect - signup, same browser different window, verification_redirect=always ', fails about 90% of the time in stage (with 66.1 builds).

**Comment by vladikoff** [comment]
![v4jjmln](https://cloud.githubusercontent.com/assets/128755/17273987/d9f346ce-5698-11e6-80bf-eab182587073.gif)

**Comment by jrgm** [comment]
Sorry to have wasted issue #4000 on such a weak bug report. Go #4001. Oh wait, that was me too, with a dumb utility script.

**Comment by shane-tomlinson** [comment]
For testing: /tests/teamcity/run-server.sh stage

**Comment by vladikoff** [comment]
@shane-tomlinson I can reproduce this locally with:

> ./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaEmailRoot=http://restmail.net fxaProduction=true firefoxBinary=/Users/vladikoff/Desktop/FF46.app/Contents/MacOS/firefox-bin grep="signup, same browser different window, verification_redirect=always"



See https://github.com/mozilla/fxa-content-server/issues/4053#issuecomment-245296866

**Comment by shane-tomlinson** [comment]
@vladikoff - that command acts the same as `npm run test-latest grep=xxx` right?

**Comment by vladikoff** [comment]
> @vladikoff - that command acts the same as npm run test-latest grep=xxx right?

Yeap + custom Firefox

**Comment by vladikoff** [comment]
This issue is super tricky because of several reasons:

* either of the tabs can complete the flow depending on the polling timer in the tab
* 123Done validates states only once and is basically not designed to handle "verification_redirect=always"

One possible solution:

The tests should look for 2 LOGGED_IN selectors or one LOGGED_IN and a "Bad Request - unknown state" (in original or new tab)
