### ISSUE TITLE
Ensure flowId gets propagated through reset password views

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4004]
Arising from some discussion in https://github.com/mozilla/fxa-content-server/pull/3990#issuecomment-236584965, there is an unresolved question of whether we want users that sign in via a password reset to show up in our flow metrics?

Currently we don't emit a `flow.begin` event if a user lands on that view and subsequent activity events won't have flow metadata. On the one hand, I can see this as a good thing because it won't pollute the metrics for our time-to-device-connection KPI. On the other hand, I can see it as something that we may want to measure.

**Comment by rfk** [comment]
My initial reaction is no, the password-reset and all activity associated with it is part of an already existing attempt to log in to something, and should be part of the same flow for metrics purposes.

**Comment by philbooth** [comment]
> password-reset and all activity associated with it is part of an already existing attempt to log in to something, and should be part of the same flow for metrics purposes.

Cool, thanks. We still have an issue to fix fwiw because I don't think the flow model gets propagated from the initial sign-in view as things stand.

**Comment by philbooth** [comment]
In light of the above discussion, I'm editing the title of this issue.

**Comment by philbooth** [comment]
For the record, this issue has now been witnessed in the wild, see:

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/349903/

(thanks @vladikoff for noticing)

**Comment by rfk** [comment]
Similar to the sign-up flow, we should look at client-side flow metrics for this like "user engaged with reset page", "user attempted to submit reset form" and so on.

**Comment by rfk** [comment]
IIUC, to emit the right flow events here, we'll want content-server to submit its metricsContext bundle to the password-reset-related endpoints on auth-server.  Here's a stub that allows auth-server to accept those request parameters, which we'll need to ship on the train *before* any of the content-server stuff lands:

 https://github.com/mozilla/fxa-auth-server/pull/1490
