### ISSUE TITLE
Sign in form can still submit after being rate limited

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4006]
I found this while investigating our rate limited login stats and the coming email authorization.

On the signin page, after being rate limited, it's possible to submit the form just by modifying the password field.

![rate-limited-can-still-interact](https://cloud.githubusercontent.com/assets/848085/17300078/cac959b0-5808-11e6-9891-1f41e7ae1265.gif)

Because of this, a single user can cause the rate limited stats to spike.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4007

**Comment by rfk** [comment]
The server's error response includes a pretty accurate "number of seconds you should wait before trying again".  The content-server could (a) enforce that it waits for this time, and (b) maybe show this time to the user somehow, per https://github.com/mozilla/fxa-bugzilla-mirror/issues/48 https://github.com/mozilla/fxa/issues/135

**Comment by vladikoff** [comment]
> (b) maybe show this time to the user somehow, per mozilla/fxa-bugzilla-mirror#48 mozilla/fxa#135

This was done 👍
