### ISSUE TITLE
Multiple "114" events reported for a single user if they re-submit

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4007]
Ref #4006.

If a user submits the signin form multiple times even though they are rate limited, multiple 114 errors are reported, which can cause spikes in our metrics. It may be better to report a single 114 for a single session no matter how many times the user is actually rate limited.

Fixing #4006 would do a bit to help too.

**Comment by shane-tomlinson** [comment]
I'm no longer convinced this is a bug, we just need to use a different denominator in our dashboards.

**Comment by rfk** [comment]
Cases like this, is where I think some sort of explicit aggregation of events into "flows" could be useful so we can ask questions like "what percentage of login flows received a 144 error?".  Hopefully we can work towards that with https://github.com/mozilla/fxa-features/issues/13
