### ISSUE TITLE
Clicking `Confirm sign-in` email button twice displays "Verification link damaged" error

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4009]
Pulled over from https://github.com/mozilla/fxa-auth-server/issues/1367

-------------------------

STR: 

1) Signup and verify account
2) Login into Sync with account that requires sign-in verification
3) Click `Confirm sign-in` button in email, page opens to verified success view
4) Click `Confirm sign-in` button again

Expected:
page opens to verified success view

Actual:
page opens damage verification link view
<img width="466" alt="screen shot 2016-07-26 at 12 13 32 pm" src="https://cloud.githubusercontent.com/assets/1295288/17145984/9c8bf036-532a-11e6-83ea-2eca71f4714a.png">

-------------------------------

I think the simplest possible solution is to convert the auth-server's 110 error response to a EXPIRED_VERIFICATION_LINK, or at least display the same message.

**Comment by vladikoff** [comment]
Need to update strings, we have the strings already
