### ISSUE TITLE
Add parameter to link on Looking for Firefox Sync? Get started here.

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4021]
Should we add add a parameter to link on "Looking for Firefox Sync? Get started here."?

If yes, what should it be?

**Comment by vladikoff** [comment]
> add a parameter

Sorry what parameter?

**Comment by ryanfeeley** [comment]
@vladikoff UTM? So mozilla.org can more precisely categorize the traffic into GA.

**Comment by vladikoff** [comment]
Ah sure,

> If yes, what should it be?

Pick one and we will add it

**Comment by ryanfeeley** [comment]
@vladikoff "stumbler"

**Comment by vladikoff** [comment]
@vbudhram you added a bunch of utm params recently, any insights for this one?

**Comment by vbudhram** [comment]
@vladikoff How do these sound?

* utm_source = fx-website
* utm_medium = fx-accounts
* utm_campaign = fx-signin
* utm_content = fx-sync-get-started

**Comment by ryanfeeley** [comment]
👍 Thanks!
