### ISSUE TITLE
Some 500 responses to /_/csp-violation

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4031]
From Kibana:

<img width="927" alt="screen shot 2016-08-10 at 09 16 52" src="https://cloud.githubusercontent.com/assets/848085/17546649/2488f48c-5edb-11e6-960e-f4bf3e1c1f2c.png">

Nothing [stands out to me that would cause an exception with the route](https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/post-csp.js).

Attaching a heart to this because 500 responses cause stress, spurious ones even more so.

**Comment by philbooth** [comment]
Not sure how likely it is in reality, but the thing that stands out to me is [dereferencing `report` without checking whether it was in in the request body](https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/post-csp.js#L31-L44). If it's not set for any reason we should return a 400 error.

**Comment by shane-tomlinson** [comment]
> Not sure how likely it is in reality, but the thing that stands out to me is dereferencing report without checking whether it was in in the request body.

I initially thought that too until I noticed [the line that checks whether the request is well-formatted](https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/post-csp.js#L25).

Does returning `false` cause a 500?

**Comment by vladikoff** [comment]
We already do `res.json({result: 'ok'});` so either this error happened when the content server was updating / down or the request was malformed in such a way that Express was not able to process it properly (could be the size of the request)

**Comment by vladikoff** [comment]
need to check the kibana dashboard to see how many of these we are getting

**Comment by jrgm** [comment]
Yeah, see the other bug. String.length !== String "byteLength".

**Comment by vladikoff** [comment]
trigger a csp warning with a script sample that has unicode characters. 
dxr has code that truncates the script sample.

**Comment by vladikoff** [comment]
from mtg: on the server we can parse the content and not use the `bodyParser`.

**Comment by jrgm** [comment]
I think there is a fix for this pending in Gecko - https://bugzilla.mozilla.org/show_bug.cgi?id=1307321

**Comment by shane-tomlinson** [comment]
Closing as "this is firefox's fault"
