### ISSUE TITLE
password-strength-mixin and password-prompt-mixin have a circular dependency.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4045]
[password-strength-mixin calls displayPasswordWarningPrompt](https://github.com/mozilla/fxa-content-server/blob/c1f52600020981d0a317f277b721bf3d9f91f4b8/app/scripts/views/mixins/password-strength-mixin.js#L93) which is available on [password-prompt-mixin](https://github.com/mozilla/fxa-content-server/blob/c1f52600020981d0a317f277b721bf3d9f91f4b8/app/scripts/views/mixins/password-prompt-mixin.js#L48). 

[password-prompt-mixin calls checkPasswordStrength](https://github.com/mozilla/fxa-content-server/blob/c1f52600020981d0a317f277b721bf3d9f91f4b8/app/scripts/views/mixins/password-prompt-mixin.js#L78) which is available on [password-strength-mixin](https://github.com/mozilla/fxa-content-server/blob/c1f52600020981d0a317f277b721bf3d9f91f4b8/app/scripts/views/mixins/password-strength-mixin.js#L73).

This is a big ixnay, these two modules should be teased apart.

`checkPasswordStrength` returns a promise with the password status, which could be used by the password-prompt-mixin to call `displayPasswordWarningPrompt` itself.

Or, these two could be folded into each other.

**Comment by shane-tomlinson** [comment]
Ref #4044

**Comment by TDA** [comment]
Definitely my fault, and i will fix it up, what's the preferred approach here @shane-tomlinson ?
