### ISSUE TITLE
Create SVG icons for Devices & Apps section

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4049]
Currently we have bitmap icons for laptop, smartphone and tablet devices.

We can make the upcoming Devices & Apps section in Settings better by having monochrome SVG icons for the following.

Sync clients:
1. Apple iPhone
2. Apple iPad
3. Apple computer (MacBook? iMac?)
4. Android smartphone
5. Android tablet
6. Windows computer
7. Generic smartphone
8. Generic tablet
9. Generic computer

OAuth services:
1. Mozilla Add-ons
2. Pocket
3. Generic OAuth service (fallback)

Example with all the same icon:
![devices-and-apps](https://cloud.githubusercontent.com/assets/68213/17632124/cfef45b4-6094-11e6-8a61-d7474537f315.png)

Trying to assign you @shorlander but perhaps you need to be added to this repo?

**Comment by ryanfeeley** [comment]
@vladikoff Can you add @shorlander to this repo? I'd like to assign it to him.

**Comment by rfk** [comment]
> Can you add @shorlander to this repo? I'd like to assign it to him.

I've invited him to a team that will allow this, but he'll have to accept the invitation.

**Comment by rfk** [comment]
The icons for this can land as part of https://github.com/mozilla/fxa-content-server/pull/4294 but we'll need a follow-up PR to use the os-specific variants.

Also, I noticed that the provided set of SVGs doesn't include "Generic OAuth service (fallback)", @ryanfeeley thoughts on what to use in that case?

**Comment by ryanfeeley** [comment]
@rfk Use the laptop computer icon, though we should be moving quickly on that if a new OAuth service appears. Jokingly Horlander said to use a "GET STEPHEN TO MAKE AN ICON" icon.

**Comment by rfk** [comment]
What about this awesome "server in the cloud" icon? http://image.flaticon.com/icons/svg/31/31988.svg

:-P

> we should be moving quickly on that if a new OAuth service appears

We now have Pontoon as well.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I don't think this can be closed as the icons are not all in there. Note his PR above with OS specific icons.

**Comment by shane-tomlinson** [comment]
Re-opening as per @ryanfeeley's comment above.

**Comment by ryanfeeley** [comment]
@davismtl Stephen graciously provided us these icons in October. Surely we can get them into FxA faster than this.

**Comment by davismtl** [comment]
@ryanfeeley Escalate this in triage. It's your opportunity to remind engineering of small UI tasks like this that we should get out of the way.
