### ISSUE TITLE
[stage] flaky tests in train-67

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4053]
Just noting these for consideration. Running functional tests on stage with train-67, I have these failures in 9 runs. None fail always, but the 7/9 seems like it could use some investigation.

```
   7/9 firefox on any platform - oauth sign up verification_redirect - signup, same browser different window, verification_redirect=always
   2/9 firefox on any platform - oauth permissions for untrusted reliers - signin with additional requested permission
   1/9 firefox on any platform - signup - signup, verify different browser - from new browser's P.O.V.
   1/9 firefox on any platform - oauth signup - signup, verify same browser by replacing the original tab
   1/9 firefox on any platform - confirm - sign up with a gmail address, get the open gmail button
```

**Comment by vladikoff** [comment]
re: verification_redirect=always 

I get: 
![image](https://cloud.githubusercontent.com/assets/128755/18315505/4335c49e-74e5-11e6-8a05-63d29faa20d2.png)

**Comment by vladikoff** [comment]
this should be fixed except: https://github.com/mozilla/fxa-content-server/issues/4000
