### ISSUE TITLE
Return email address to Choose What To Sync screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4062]
We used to show the user's provided email address on the Choose What To Sync screen (in grey, under the title), but it's since disappeared.
<img width="454" alt="screenshot 2016-08-17 15 01 45" src="https://cloud.githubusercontent.com/assets/68213/17750907/c4ffa368-6492-11e6-99b5-b02c9f9a7bab.png">
Seeing the email helps the user know if they've entered it incorrectly, so they can correct it, and end up actually syncing.
Please fix and see if it's removal had any impact on verification rate, and also the back button usage (FxA Content Back Dashboard in Datadog)

**Comment by ryanfeeley** [comment]
@shane-tomlinson Uh oh, looks like it got hidden in June of last year (!) when we decided to allow firstrun to hide our "to continue to Firefox Sync" header...
https://github.com/mozilla/fxa-content-server/issues/2743
Obviously was not intended to hide this subhead too.

**Comment by vbudhram** [comment]
Was testing something else and found this when creating through the sync ui. Maybe this is first run related?

![screen shot 2016-08-17 at 4 01 19 pm](https://cloud.githubusercontent.com/assets/1295288/17751187/f6e900ee-6493-11e6-92e5-681904af3dba.png)

**Comment by ryanfeeley** [comment]
👍
