### ISSUE TITLE
Did train 62 reduce bounce rate?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4064]
Looks like train 62 was responsible for a large drop of bounced emails. Reading the release notes, I can't figure out why though… Check the chart. https://app.datadoghq.com/dash/54208/fxa-content-front-end---browser-details?live=false&page=0&is_auto=false&from_ts=1463691853000&to_ts=1466283853000&tile_size=m&fullscreen=89687178
![train62](https://cloud.githubusercontent.com/assets/68213/17754021/9075fd46-64a0-11e6-84f8-cf3ffb381ace.png)

**Comment by rfk** [comment]
This graph is from the `auth.1018` error, which IIUC is an error number that's synthesized by the content-server when it sees certain signals during the sign-up flow.  So it's possible that the circumstances under which this error is generated have changed.

I also wonder if it's related to what you noticed over in https://github.com/mozilla/fxa/issues/162 with bounces not being handled correctly.

**Comment by vladikoff** [comment]
from mtg: Need to investigate the bounces 

We have an upcoming flow event for bounces.

**Comment by vladikoff** [comment]
bounce metrics will be available via https://github.com/mozilla/fxa-content-server/issues/4040
