### ISSUE TITLE
Capture Country as Meta Data

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4069]
We currently don't capture country for our metrics. It would be valuable to be able to segment our metrics by country or to just know what the most popular countries. 

Example of how DevTools uses countries: 
https://sql.telemetry.mozilla.org/queries/857#1715

Mobile also captures country data but I haven't had the time yet to make a re:dash graph as an example. However, it does look quite similar to DevTools with country codes. (e.g. US, CA, FR)

**Comment by vladikoff** [comment]
from mtg:

@rfk,

* we are guessing that we would log the country in activity / flow events. Would we store the country metrics context?

* what is the priority on this? we are able to answer the 'most popular' country right now (@jrgm **might** have a way without redash)

**Comment by rfk** [comment]
> we are guessing that we would log the country in activity / flow events. 

Sounds reasonable to me.

> what is the priority on this? 

Let's focus on getting the initial set of flow metrics graphs up and running, and we can then add this as follow-up work.

**Comment by rfk** [comment]
This came up again in conversation.  I think there's now an obvious implementation plan - do geo lookup on the IP address submitting the `flow.begin` event, and include the result in the flow metadata.  @davismtl and I still agree that it's a follow-up to the existing work though.

**Comment by Kiiirby** [comment]
@rfk Can we move this to the front burner? Regional metrics are crucial for achieving our Firefox OKRs.

**Comment by rfk** [comment]
@davismtl and/or @juliemccracken we need to check this with legal or data stewards or are we already clear to have this data wind up in our redshift metrics?

**Comment by davismtl** [comment]
Julie (can't seem to mention her in GitHub) will be checking in her next legal meeting. Should not be a prob since we basically already collect it via GA.

I also wanted to add something @rfk said in an email thread:

"We already have the code to do country lookups, to get country data into redshift I think we'd need to:

1) Refactor the geolocation code so that we only ever do it <= once per request
2) Decide on the data model.  Do we tag every event with geo lookup?  Only flow.begin events?  Something else?
3) Implement said event tagging and get it deployed, which I don't think would be too much code given (1)
4) Update our heka -> S3 export scripts to include the new data
5) Update our redshift import scripts to pull in the new data"

**Comment by vladikoff** [comment]
@davismtl @rfk do we still need this open here?

**Comment by davismtl** [comment]
According to this page, we are now tracking it: https://github.com/mozilla/fxa-auth-server/blob/master/docs/metrics-events.md

If we can confirm with a bug number where it was completed, that would be good.

Also, we should probably dive into this new data to make sure it is as expected.

**Comment by philbooth** [comment]
We track language at the moment but not the country the user is in.

**Comment by davismtl** [comment]
Ahh, well in that case, let's leave this open.

**Comment by rfk** [comment]
> Julie (can't seem to mention her in GitHub) will be checking in her next legal meeting

@juliemccracken did we get resolution on this question?

**Comment by juliemccracken** [comment]
I talked to Brian about this back in early May when legal was revising Mozilla's privacy policy. Brian indicated that as long as country is stored in logs, as opposed to database, and is subject to the same deletion policy as other logged data, it's ok to collect it.

**Comment by vladikoff** [comment]
from above:

> "We already have the code to do country lookups, to get country data into redshift I think we'd need to:

> Refactor the geolocation code so that we only ever do it <= once per request
Decide on the data model. Do we tag every event with geo lookup? Only flow.begin events? Something else?
Implement said event tagging and get it deployed, which I don't think would be too much code given (1)
Update our heka -> S3 export scripts to include the new data
Update our redshift import scripts to pull in the new data"

**Comment by vladikoff** [comment]
closing this, we have this in Amplitude
