### ISSUE TITLE
fx_ios_v2 authentication broker is unused - time to remove?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4073]
the fx_ios_v2 authentication broker is so far unused. v2 adds CWTS on the web and WebChannel capabilities. The Fx for iOS half was never written, and now we have unused code.

I propose we keep the broker file to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1289480#c13, but change it to act exactly like fx_ios_v1 (for now), and remove all the extra unit/functional tests for CWTS until we need them, possibly in fx_ios_v3.

cc @vbudhram, @vladikoff.

**Comment by rfk** [comment]
FWIW I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1297566 to record the "no CWTS on FxiOS" problem.

**Comment by rfk** [comment]
In the meantime though, I support removing this unused code.
