### ISSUE TITLE
Remove transition animation on Show password toggle

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4076]
Now that Show password is press-to-show, the transition animation on Show password is confusing. Best to remove it for now entirely so the button switches as instantly as the password does.

**Comment by TDA** [comment]
@ryanfeeley Drop all transitions states: both color and background-color?

**Comment by TDA** [comment]
@ryanfeeley Is this still occurring? I think the side-by-side subscribe/cancel does not exhibit. If you can confirm, we can close this.

**Comment by ryanfeeley** [comment]
@TDA Yes, it should just switch immediately like the •••••••••••••• to text.

**Comment by madalincm** [comment]
I've checked amo-dev and I can see now see that the old behavior is back (click - the password is shown, click again the password is hidden)

**Comment by shane-tomlinson** [comment]
@madalincm - what is the amo-dev server? Does it use our production FxA server or some other server? I just tested both prod and stage, the password only shows while the button is depressed. stable.dev.lcip.org on the other hand, is running out of date code and has the behavior you describe.

@jrgm or @vladikoff - can we get stable updated?

**Comment by madalincm** [comment]
Hello Shane the amo-dev server is this one: https://addons-dev.allizom.org/en-US/firefox/ It uses a devolment FxA  server as far as I am aware.

Here is a quick screencast for the behavior on addons-dev.allizom 
http://screencast.com/t/Y196QqQx6Y

**Comment by shane-tomlinson** [comment]
Thanks @madalincm - I've just confirmed that addons-dev points to our "stable" server, which is currently running stale code. I'll talk with ops to ensure this gets updated.

**Comment by jrgm** [comment]
I have updated stable to current versions, so give it a try now.
