### ISSUE TITLE
extract font/image url from css in server tests to check headers (esp. access-control-allow-origin)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4092]
I noticed that we don't request font/image urls included in the css for appropriate headers, particularly access-control-allow-origin (an abuse of CORS IMHO, but part of the specs nonetheless).

**Comment by vladikoff** [comment]
from mtg: 

parse css urls and check if they work...

**Comment by shane-tomlinson** [comment]
@jrgm - your tests took care of this, didn't they?

**Comment by shane-tomlinson** [comment]
Closed by https://github.com/mozilla-services/cloudops-deployment/pull/990
