### ISSUE TITLE
Bounce not triggering from Choose What To Sync screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4094]
STEPS TO REPRODUCE
1. Create a fresh Firefox profile
2. Create a Sync account by any means using an email that will bounce
3. Stay on the Choose What To Sync screen for as long as the email will typically bounce
4. Click **Save settings**

EXPECTED RESULTS
- When the email bounces, the user is returned to registration with the email field outlined and the message “Your verification email was just returned. Mistyped email?”

ACTUAL RESULTS
- The screen stays indefinitely, and when the user clicks **Save settings** they are taken to a message-free registration free.

![null](https://cloud.githubusercontent.com/assets/68213/18014840/dae4de3a-6b92-11e6-8c8a-fefb7b4e45b6.gif)

From **accounts.firefox.com**:
![stillnull](https://cloud.githubusercontent.com/assets/68213/18014859/f423d158-6b92-11e6-8e2c-1a344d1ac1fc.gif)

When the user clicks **Save settings** before the bounce:
![nullagain](https://cloud.githubusercontent.com/assets/68213/18014869/03277a10-6b93-11e6-89cf-0fe3e1ba92b9.gif)

**Comment by ryanfeeley** [comment]
Related to: https://github.com/mozilla/fxa-content-server/issues/4064 ?

**Comment by shane-tomlinson** [comment]
ref #4193

**Comment by ryanfeeley** [comment]
@rfk @davismtl I heard from Micheal Verdi that this bug has been observed in user testing, but differently.

Paraphrasing:  After entering an invalid Gmail address, what would cause clicking on the **Save settings** button on the **Choose what to sync** step, take a user back to **Create an account** over and over again until exceeding the **Create account** attempt limit?

**Comment by Verdi** [comment]
Yep - I just encountered this on a user test where the person was tying to use a made up email. He didn't get an error about the made up email. He was just taken back to the first step where he clicked create an account, when to choose what to sync and clicked save settings and was taken back to create an account. This happened a few times until he got the "attempt limit exceeded" error.

**Comment by shane-tomlinson** [comment]
ref #4193

**Comment by ryanfeeley** [comment]
@vladikoff Still an issue…

**Comment by ryanfeeley** [comment]
@vladikoff Is this happening soon? I still experience it.

**Comment by rfk** [comment]
I expect we'll soon have better bounce reporting from the server, based on the work @seanmonstar  has been doing.  @shane-tomlinson @vladikoff is our plan here still "add some polling on the CWTS screen" that can check for the status of the account?

**Comment by shane-tomlinson** [comment]
ref #5311
