### ISSUE TITLE
Keep show password button hidden until there is anything to show

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4095]
The new press-and-hold Show Password function may appear broken to some users as it is present even when there is no password to show. Simply make the button appear, without any special transition, when characters are entered.

PROPOSED:
![show-on-input](https://cloud.githubusercontent.com/assets/68213/18015434/b89a4a1a-6b95-11e6-9d58-1d90b9cdb97b.png)

**Comment by TDA** [comment]
MINE!
