### ISSUE TITLE
Use open in webmail button on reset sent page

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4096]
People love the Open in Gmail (and Yahoo, Hotmail, Live) button. Let's use it on the reset email sent page too.
![open-in-email](https://cloud.githubusercontent.com/assets/68213/18018910/6f8cb378-6ba7-11e6-993d-ba7577b5569f.png)

**Comment by TDA** [comment]
Is @larissagaulia gonna take this up? Or.....? *wink wink*

**Comment by larissagaulia** [comment]
@TDA, If it makes you happy it's all yours! ;)

**Comment by ryanfeeley** [comment]
Come on @vladikoff, take the feature to the next level.

**Comment by RPraneetha** [comment]
Should the "Open in Gmail" button link to gmail.com or to the default mail application (like Outlook)?

**Comment by shane-tomlinson** [comment]
@RPraneetha - we have a mixin to take care of the button behavior.

See:

* https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/open-webmail-mixin.js


For examples of how this is used, see:

* https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm.js#L193
* https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/confirm.mustache#L24:L28

You'll want to do something similar to:

* https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/confirm_reset_password.js
* https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/confirm_reset_password.mustache

If you run into any blocks, lemme know!

**Comment by shane-tomlinson** [comment]
@divyabiyani is working on this, pulling it into active.
