### ISSUE TITLE
for consideration: don't Vary the js checksum due to embedded timestamp

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4101]
Not sure if I want this or not, but putting this out there for consideration.

We currently embed a timestamp based on when it was generated in the js content. e.g., 
```
--- dat1/fxa-content-server/dist/scripts/87590e6b.main.js	2016-08-29 16:30:35.000000000 -0700
+++ data/fxa-content-server/dist/scripts/7c07e9ff.main.js	2016-08-29 20:19:03.000000000 -0700
@@ -1,4 +1,4 @@
-/*! fxa-content-server@0.68.1 -- Mon Aug 29 2016 23:29:41
+/*! fxa-content-server@0.68.1 -- Tue Aug 30 2016 03:18:08
  *
  * Git sha: 9df2233946ee04270c76ebec7e91e177c48290cf
  *
```

An argument could be made that the shasum should depend only on the effective content of the js, not a variable comment value. Or not. Discuss...

**Comment by vladikoff** [comment]
Makes sense ...

**Comment by vladikoff** [comment]
from mtg: 

* Remove the date from the comment
* If possible, generate the hash from the contents (if we remove the date it might just work)
