### ISSUE TITLE
Browser2 signed out if Browser1 changes password

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4104]
Re: https://github.com/mozilla/fxa-content-server/issues/3788

I have browser1 and browser2 signed in to sync on the same account.

If I change the password in browser1, browser2 immediately challenges for the new password (and then goes through email conf flow). 

Is this the intended UX?

**Comment by vladikoff** [comment]
@shane-tomlinson when I saw this at first it reminded me of https://github.com/mozilla/fxa-content-server/commit/56417ac24fab96a9110958cd199d09a0fe312ff2

**Comment by shane-tomlinson** [comment]
> Is this the intended UX?

Let's just say it's not unexpected. Since the password has changed, the user has to sign in on all their devices again with the new password just so they can Sync.

Maybe there is a way around it for password change that preserves the security properties of the feature, but I don't know what that is. Tunnel a code through push notifications?

**Comment by rfk** [comment]
Is the question here whether the second device should have to prompt for the password at all, or whether it should have to go through the sign-in confirmation flow again?

**Comment by shane-tomlinson** [comment]
>  or whether it should have to go through the sign-in confirmation flow again?

I assumed this part. My response did not at all make that clear. The requirement for the user to enter their password is a hard requirement AFAICT, whether they go through sign-in confirmation is not.

**Comment by shane-tomlinson** [comment]
Closing this issue as "working as expected". With @vbudhram's new features, the signin confirmation requirement will be eased if the user's devices are currently on the same IP address.
