### ISSUE TITLE
Add ability to delegate sending emails to auth-server

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#4105]
As part of https://github.com/mozilla/fxa-auth-server/issues/1325, we need to give the content server the ability to delegate sending verification emails on login to the auth-server.

This is part of https://github.com/mozilla/fxa-auth-server/pull/1435#issuecomment-243655573. Once this has been added, we can set the default action of the auth-server to [send verification email](https://github.com/mozilla/fxa-auth-server/pull/1435/files#r76800227) on login, if unverified.

**Comment by shane-tomlinson** [comment]
I can imagine this done as a multi-step process to allow for independent update/rollback of the auth server and content server.

Here's a strawman:

1. We have determined that *only the content server resends emails*, all other clients assume the auth server will do it. See mozilla/fxa-auth-server#1325 for discussion. Have the auth server send account creation emails on /account/create and /account/login w/ unverified account for all requests that do not originate from the content server.
2. Have the content server send a flag in /account/login and /account/create that says "you send account creation emails." Add functionality to the auth server that sends the email for content server originating requests if the flag is present. The auth server will respond with some data that says "I've sent the email." If the returned flag is not present, the content server knows it needs to send the email.
3. Have the auth server *always* send the account creation email. Send the "we've sent it" flag to the content server. Remove functionality from the content server that sends the email.
4. Stop sending the "we've sent it" flag in auth server responses.

**Comment by vbudhram** [comment]
@shane-tomlinson I like this approach. Ryan mentioned something similar in his [comment](https://github.com/mozilla/fxa-auth-server/pull/1435#issuecomment-243655573).

The only note, is that the `emailSent` response value was not included auth-server related [PR](https://github.com/mozilla/fxa-auth-server/pull/1435) for this because auth-server emails are sent right away and did not wait for the response to finish.

While having `emailSent` is important for rollback, I wonder if it mitigated enough by having it over several trains? 

@rfk Thoughts?

**Comment by rfk** [comment]
If you're passing the `sendEmailIfUnverified` option in the request body, you already can't rollback to an older auth-server version - it would be an unknown request parameter and produce a validation error.

I guess we could instead pass it as a query parameter, include `emailSent` in the response, and save ourselves on train's worth of waiting by shipping both the content-server and auth-server pieces together.  But I don't think it's a huge deal either way.

We should definitely do part (1) from Shane's suggestion though.  We can tell whether the request comes from content-server by looking at the metricsContext parameter, so we should default `sendEmailIfUnverified` to false for requests from content-server, and true otherwise.

**Comment by shane-tomlinson** [comment]
> If you're passing the sendEmailIfUnverified option in the request body, 

I imagined this being a query parameter, like similar flags to other endpoints, so we do not run afoul of validation.

**Comment by vbudhram** [comment]
Thanks for input guys, I will update auth-server to accept `sendEmailIfUnverified` as query param and have it default to send emails from all non content-server requests.

@shane-tomlinson I think I might have gotten confused with `emailSent`, and will add it to response. For some reason, I thought it meant that email was delivered, but in this case, it is just at an attempt was made to send it.
