### ISSUE TITLE
Sentry trying to fetch non-existent bower_components/fxa-js-client/fxa-client.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4106]
I deployed train-68, but there was a background level of 4xx requests, and I rolled back.

Turns out it was all Sentry trying to GET `bower_components/fxa-js-client/fxa-client.js`, which is not in the build. 

So, I copied `bower_components/594037fb.fxa-js-client/fxa-client.js` to `bower_components/fxa-js-client/fxa-client.js` and pushed that into s3, and I'll go again.

**Comment by vladikoff** [comment]
You probably need this https://github.com/mozilla/fxa-content-server/commit/0627b173af696dbb3ff2d2aa1315927f1db4e1bd

**Comment by vladikoff** [comment]
should be fixed in train 0.68.3
