### ISSUE TITLE
Users trying to download non-existent file from accounts.firefox.com/bower_components/fxa-password-strength-checker/build/fxa-password-strength-checker.js?1472696566386

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4107]
Users try to download `/bower_components/fxa-password-strength-checker/build/fxa-password-strength-checker.js?1472696566386`, but there is no such file. There is a shasum-ed variant of that name though. Rolled back for a second time. That's all for tonight.

**Comment by jrgm** [comment]
To be clear, these were 404 requests by real end users (not sentry).

**Comment by shane-tomlinson** [comment]
We just changed the build so that requireOnDemand uses real cache busting URLs, not cache busting based on the date in the query parameter. The problem outlined here is a user that downloaded the pre-update "main.js" and then requested the password-strength-checker post upgrade.

**Comment by shane-tomlinson** [comment]
Similar to #4106, an easy workaround is to copy `/app/bower_components/<shasum>.fxa-password-strength-checker.js` to `/app/bower_components/fxa-password-strength-checker.js`

Let's never use non-cache busting URLs again. This is a nightmare.

**Comment by vladikoff** [comment]
should be fixed in train 0.68.3
