### ISSUE TITLE
Register link does not work anymore after an unsupported age is entered

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/fxa-content-server#4110]
Steps to reproduce:

1.Load AMO-stage page and select the “Register” link.
2.Complete the required fields and introduce a not supported age(less than 13).
3. Click the “Create account” button
4. Click again on Register link

Expected results:
After step 3 the message “You must meet certain age requirements to create a Firefox Account.” is displayed and user is blocked. 
After step 4 user is redirected to “Create an Account” page.

Actual results:
User cannot create an account after step 4.

Note/Issues:
If the user selects “Learn More” link and after goes back two times the “Create an Account” page will work as expected.
Also, if the browser is closed and reopened the Register links works.
Verified on FF51.0a1(Win 7 64-bit)
This issue is reproducing in AMO dev and stage and production server

Here is a video for this issue:
![fxaacc](https://cloud.githubusercontent.com/assets/15885467/18172058/d12683f6-706c-11e6-9abb-ec4e569978e8.gif)

**Comment by shane-tomlinson** [comment]
Thanks for the report @cosminbadescuSV. This is the expected behavior and was guided by legal. Once we learn a user is under-age, we have to take reasonable measures to prevent the user from trying again.

You can close the browser and try again, or clear cookies and try again.
