### ISSUE TITLE
Do we need to version dist/i18n/*.json?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4113]
When a new content-server release is ready to go live, first the static content is pushed into an S3 bucket. Since the strings are in, e.g., dist/i18n/client.json, when we push to S3, the strings from the new train overwrite those from the old train. Do we need to better control this with versioning (ugh)?

**Comment by jrgm** [comment]
Nevermind. client.json comes from https://accounts.stage.mozaws.net/i18n/client.json, e.g., the webhead, not the CDN.

**Comment by jrgm** [comment]
Although, we do clobber strings on an s3 push, so incompatible string changes will break clients.

**Comment by shane-tomlinson** [comment]
> Although, we do clobber strings on an s3 push, so incompatible string changes will break clients.

Strings should come from the webhead, not the CDN, no need to push to the CDN they won't be requested from there.

**Comment by shane-tomlinson** [comment]
> will break clients.

Client's won't *break*, they'll just show the english version of the string if a string is not available.

**Comment by shane-tomlinson** [comment]
Thought, to be completely fair to @jrgm, it'd suck if you were a user that didn't read english and saw one of the strings he mentions. I have wanted to bundle the translations in with the .js bundle for a while, my objective is to speed load time. The same solution would mitigate this problem.

Some possible approaches:

1. Write the translations to the HTML somewhere, possibly as a meta tag.
2. Build a version of the JS bundle for each locale, each bundle would contain the translations as a JSON blob.
3. Build a version of the JS bundle for each locale, where we replace `t` wrapped strings with their translation.
