### ISSUE TITLE
Urls in css that failed to resolve.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4114]
I was doing the implementation for  https://github.com/mozilla/fxa-content-server/issues/4092, and lo, it's complaining about two missing URLs: https://accounts-static.stage.mozaws.net/styles/spinner.gif and https://accounts-static.stage.mozaws.net/styles/close.png.

There is no file named 'spinner.png' in the fxa-content-server tree, and while there is ./app/bower_components/jquery-modal/close.png, I doubt that is the file it is looking for.

**Comment by jrgm** [comment]
Ah, sorry, there is `./app/bower_components/jquery-modal/spinner.gif` (I did a `find` for `spinner.png`).

Anyways, I suppose the issue is that we are glomming `.app/bower_components/jquery-modal/jquery.modal.css` into the overall concatenated CSS blob without adjusting the `url(...)` to resolve from `./styles/deadbeef.en.css`.

**Comment by vladikoff** [comment]
spinner.gif is no more and was replaced with a base64 url image since then.
