### ISSUE TITLE
/signin_complete inconsistently shows the "sync preferences" button

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4115]
I'm spinning this out from #4060 to investigate as a separate issue. 
## STR:

while (true) {
1. Disconnect from sync, and choose "sign in".
2. Sign in with an existing account.
3. Check your email for sign-in confirmation
4. Click the "Confirm sign-in" link to open it in the same browser
5. Observe the "You are now ready to use Firefox Sync" page.
}
## Expected result:

It should always have a big blue "Sync Preferences" button like this:

![screen shot 2016-09-05 at 13 03 32](https://cloud.githubusercontent.com/assets/34695/18236445/2dfe893a-7369-11e6-8c1d-b6f3c03d3ae3.png)
## Actual result:

Sometimes it doesn't have one, like this:

![screen shot 2016-09-05 at 13 01 52](https://cloud.githubusercontent.com/assets/34695/18236437/18fcc704-7369-11e6-8a0d-0077d2b3beb4.png)

**Comment by rfk** [comment]
If I try to interrogate the page's state via devtools, I observe the following whenever the button is shown:

```
>>> router.broker.hasCapability("syncPreferencesNotification")
true
>>> router.broker.relier.isSync()
true
>>> router.broker.__proto__.type
"fx-desktop-v3"
```

And the following when it is not shown:

```
>>> router.broker.hasCapability("syncPreferencesNotification")
false
>>> router.broker.relier.isSync()
true
>>> router.broker.__proto__.type
"base"
```

Which would certainly explain the absence of the button.

**Comment by rfk** [comment]
IIUC the verification context is supposed to be read from localstorage.  Even on pages that do not display the 'sync preferences' button, I see what looks like a correct entry in localStorage:

```
>>> localStorage["__fxa_storage.verificationInfo"]
"{"dbc502f8ba53419a95a12553dfb8c1b3":{"context":{"context":"fx_desktop_v3"}}}"
```

So perhaps its some sort of problem with reading this value out of storage during application start.

**Comment by philbooth** [comment]
Related: Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1300762

**Comment by shane-tomlinson** [comment]
After much bashing my head and  logging console messages, I am starting to ask myself whether this is caused by a browser bug. When this bug manifests, if I read localStorage in the verification tab of the 2nd sign in, the read values are those stored from the *first* sign in, not the 2nd. If I log what all tabs read/write to localStorage, the 2nd sign-in writes the expected data to localStorage, but those values are not ready by the verification tab.

It could also be that localStorage is "globally shared mutable state" and a tab is writing to localStorage when we do not expect it to, but so far I have not seen signs of this.

**Comment by rfk** [comment]
Interestingly, I was not able to reproduce this on current release (48.0.2) after five tries, but was able to quickly reproduce again on Nightly.  Some change in localStorage behaviour perhaps?

**Comment by rfk** [comment]
@shane-tomlinson I think you're right, I've come to believe this is a browser bug related to e10s.  I made a video demonstrating the disconnect between localStorage in the `about:accounts` iframe and localStorage in top-level web content:

  https://rfk.id.au/static/scratch/localstorage_weirdness.mov

I'm no expert on localStorage, but I'm pretty sure that's not supposed to happen...

If I go into about:preferences#general and disable multi-process, I don't seem to be able to reproduce this issue, and neither was I able to reproduce it on release.

**Comment by rfk** [comment]
Maybe related: https://bugzilla.mozilla.org/show_bug.cgi?id=666724

**Comment by vladikoff** [comment]
"Sync Pref" button is no more!

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4763
