### ISSUE TITLE
Password strength warning overlaps "how old are you?" in small viewport

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4133]
STR:
- Go to https://accounts.firefox.com/signup?passwordStrengthCheck=true
- Make your browser window really skinny, to force the small-screen styling thingy
- Enter credentials to sign up for a new account, with password "password"
- Tab down to the "how old are  you?" box

The orange warning popup seems to overlap the floated "how old are you?" label, making the screen look really crowded:

![screen shot 2016-09-09 at 14 53 37](https://cloud.githubusercontent.com/assets/34695/18375898/86a44f7a-769d-11e6-928f-3abb43608c71.png)

**Comment by ryanfeeley** [comment]
That's quite an eyeful. Should we add × to the the message? I don't want to add more space between the fields.

**Comment by TDA** [comment]
@ryanfeeley We could also make the text shorter on smaller screens with lets say, "This is a common password. Read more.."  which will fit in a single line on smaller screens.

**Comment by vladikoff** [comment]
@ryanfeeley says WONTFIX

**Comment by ryanfeeley** [comment]
<img width="668" alt="screenshot 2016-12-16 15 42 28" src="https://cloud.githubusercontent.com/assets/68213/21277843/457835ec-c3a6-11e6-98d9-0d2c955ef6ba.png">

**Comment by vladikoff** [comment]
#Armenia
