### ISSUE TITLE
What are these strange OAuth links on social media?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4134]
Link is in the first screenshot, result of clicking on the link in the second. Is this meaningful?

![2016-09-05 00 03 53](https://cloud.githubusercontent.com/assets/68213/18399202/f21607f8-769d-11e6-9189-d42f44e50e19.png)
![2016-09-05 00 03 40](https://cloud.githubusercontent.com/assets/68213/18399203/f217762e-769d-11e6-8952-ac9c629c80b7.png)

**Comment by rfk** [comment]
This worries me, could be some sort of attack attempt.  @ryanfeeley it may be worth moving this into a private bugzilla bug.

**Comment by rfk** [comment]
FTR that fb.me short URL redirects to:

https://accounts.firefox.com/oauth/signup?client_id=749818d3f2e7857f&state=a56f4e1d9b8250a497567d1c2514da81&scope=profile%3Auid+profile%3Aemail+profile%3Adisplay_name

Which is a login attempt to pocket.

**Comment by shane-tomlinson** [comment]
@rfk - what's the next step here?

**Comment by rfk** [comment]
TBH I don't see a valuable next-step we can take on our side, I'm going to just close this out.
