### ISSUE TITLE
Discuss a way to prevent users from using their webmail password

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4136]
Some users will re-use their webmail password as their Firefox Account password. This is obviously disastrous if they are using it in other places too, and those places get hacked.

We can suggest to all users that they don't do this, but not everyone will read it.

Let's discuss if there is a way to prevent users from using their webmail password on any of the existing webmail systems.

**Comment by rfk** [comment]
Just a note to say I agree this is worth discussing, but I don't have any brilliant suggestions to offer.  It may be that the best we can do for this specific case, is continue improving our secondary security measures to help all users with weak passwords.

**Comment by ryanfeeley** [comment]
@rfk It's a lot of up-front information to present if we want users to know everything they really should know before entering their new password. I'm currently working on this.

**Comment by vbudhram** [comment]
Per meeting: Need some more details , solutions and impact of doing this.

**Comment by vladikoff** [comment]
Please reopen if there are any ideas that can help achieve this..

**Comment by ryanfeeley** [comment]
@vladikoff I think it will ultimately end up having us replace our fancy (and useless) progressive password hint, and just saying something about not using the same password as their email. Stay tuned.
