### ISSUE TITLE
Sentry Error: undefined is not an object (evaluating 'document.getElementsByClassName("docs-homescreen-gb-container")[0].style')

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4138]
TypeError: undefined is not an object (evaluating 'document.getElementsByClassName("docs-homescreen-gb-container")[0].style')
  at ? (/signup_complete:1:67)

328k of these, all in one spike.

All Safari 9.0

**Comment by vladikoff** [comment]
`docs-homescreen-gb-container` lives on `view-source:https://docs.google.com/document/u/0/?showDriveBanner=true#`

**Comment by shane-tomlinson** [comment]
> docs-homescreen-gb-container lives on view-source:https://docs.google.com/document/u/0/?showDriveBanner=true#

WTxxx? Why would that show up in our metrics?

**Comment by vladikoff** [comment]
@shane-tomlinson also why Safari 9.0 !

**Comment by vbudhram** [comment]
Closing per meeting, not showing up as a top alert

**Comment by Klaasvaak** [comment]
We are also having this issue in Sentry. Did you figure out what caused the problem?

**Comment by shane-tomlinson** [comment]
> Did you figure out what caused the problem?

We unfortunately, have not.

**Comment by davidstevens37** [comment]
@shane-tomlinson or @Klaasvaak Did either of you figure out what was causing this?

**Comment by shane-tomlinson** [comment]
> Did either of you figure out what was causing this?

Nope.

**Comment by ConorHiggins** [comment]
@shane-tomlinson This issue is now coming up for us on our web app. Any idea of the source in the past few months? So far we've had 45k events in Sentry 👎

**Comment by wesbos** [comment]
I just got 14,000 of these events from a single user and it maxed out my sentry account :\ would love to know what is causing this.

**Comment by vladikoff** [comment]
@wesbos my first guess -> some bot embeds sites into google docs for strange reasons... archiving? security checks? phishing?

**Comment by benvinegar** [comment]
Sentry users struggling with this:

1. We [just merged a change](https://github.com/getsentry/raven-js/pull/861) into Raven.js that suppresses back-to-back duplicate errors. It should prevent non-stop firing errors from eating up your quota. We're going to deploy it on sentry.io first to sanity check that it works, and assuming it's fine, cut a new version (3.12.0) early next week (e.g. 2/27/17).

2. If you can confirm the source of this error, we accept PRs against our [browser extension filters](https://github.com/getsentry/sentry/blob/master/src/sentry/filters/browser_extensions.py).

**Comment by sampotts** [comment]
@benvinegar Google sent me here. We just had 12k worth of this error from One IP, browser etc - we're using v3.9.1 of the JavaScript Raven lib. Any idea?

**Comment by benvinegar** [comment]
@sampotts – with the same message signature? Note you have to enable this filter in your project settings. And I also recommend upgrading to the latest version of Raven.js.

**Comment by sampotts** [comment]
@benvinegar Yep but it seems to have stopped. I've turned on the filter for next time though and will upgrade the JS lib.

**Comment by svitaliyv** [comment]
same issue
