### ISSUE TITLE
Sentry Error: System unavailable, try again soon

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4141]
There are between 5500 and 7700 of these ~~an hour~~ a day reported to Sentry.

**Comment by vladikoff** [comment]
@shane-tomlinson could you link to sentry reports in the issue here

**Comment by shane-tomlinson** [comment]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/347136/events/8348681/

**Comment by vladikoff** [comment]
@shane-tomlinson all of those have a namespace `config`. so the error that throws is https://github.com/mozilla/fxa-content-server/blob/fcf1ebf85de833c1098eb6685a17bae4bf3d4a08/app/scripts/lib/config-loader.js#L61

**Comment by shane-tomlinson** [comment]
Ref #2585 about ditching the call to /config and placing config values into the HTML or JS somehow.
