### ISSUE TITLE
Display new messaging for sign-in already verified tokens

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#4148]
A new error code was introduced to handle when a user clicks a sign-in confirmation email link twice, https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/auth-errors.js#L301, however the messaging reads "The link you clicked to verify your email is expired.".

While technically correct, we could probably give the user more details on what happened, ex. "The verification link has already been used."

**Comment by vbudhram** [comment]
@ryanfeeley Input on what wording makes sense here?

**Comment by ryanfeeley** [comment]
How about: ![screenshot 2016-09-08 14 48 42](https://cloud.githubusercontent.com/assets/68213/18515566/d6a4367e-7a63-11e6-9718-f27f5195cc46.png)

**Comment by ryanfeeley** [comment]
@vbudhram Does this fade in a "resend" link? I forget

**Comment by vbudhram** [comment]
@ryanfeeley This screen actually doesn't display a resend button. Clicking the link originally, causes the session associated with it to be verified. Performing a `resend` wouldn't make sense because it would attempt to verify an already verified session.

**Comment by ryanfeeley** [comment]
@vbudhram Ah, makes sense.

I suppose the headling should be changed. I tweaked the body a little more too.

## Sign-in already confirmed
That confirmation link was already used, and can only be used once.

![screenshot 2016-09-14 12 51 55](https://cloud.githubusercontent.com/assets/68213/18521423/0b4f7a30-7a7a-11e6-838b-5633ad3d539b.png)

**Comment by vbudhram** [comment]
@ryanfeeley This LGTM, I think it provides more context that the other messaging.

**Comment by vbudhram** [comment]
Closed via https://github.com/mozilla/fxa-content-server/pull/4176
