### ISSUE TITLE
When I'm logged in, auto-fill my email address on the reset_password page

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4151]
I'm spinning this off from https://bugzilla.mozilla.org/show_bug.cgi?id=1288712

STR:
* Sign in to your Firefox Account
* Go to /settings and select 'change password'
* Click the 'forgot password?' link

Expected result:

* I go to a reset-password page that's pre-filled for the account I'm logged in to

Actual result:

* I'm sent to a reset-password page where have to re-enter my email address, in spite of being logged in.

**Comment by shane-tomlinson** [comment]
Removing the `good-first-bug` label. This behavior is intentional, @ryanfeeley wanted to throw up roadblocks to password reset to force users to read the big red text that says they could lose all of their Sync data.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/tree/master/features/FxA-72-reset-password

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I'm assigning this to you to get your feedback.

**Comment by ryanfeeley** [comment]
As designed, though I'm still not happy with this flow and will be proposing changes shortly.

**Comment by rfk** [comment]
OK, thanks.  Let's close this out as "working as intended" and follow up on new proposals in separate issues.
