### ISSUE TITLE
Discuss: Is it time to remove `preVerifyToken` support?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4152]
`preVerifyToken` support was added to allow FirefoxOS Marketplace users who were already verified using Persona to sign up for Firefox Accounts without the need to verify a second time. Now that Firefox OS is no longer maintained, we should consider removing this functionality.

According to DataDog, about between 100 and 200 pre-verified accounts are created per day.

<img width="548" alt="screen shot 2016-09-15 at 12 58 39" src="https://cloud.githubusercontent.com/assets/848085/18549072/25cb801e-7b44-11e6-83ff-c11380834022.png">

The purple line is last month, the blue line is current.

What I find curious is that these users are [reported as successfully pre-verified via fxa.content.signup.preverified.success](https://github.com/mozilla/fxa-content-server/blob/ba772856c872820e881157dc155d56e8fdfdbf78/app/scripts/views/mixins/signup-mixin.js#L73), but the corresponding [fxa.content.signup.preverified](https://github.com/mozilla/fxa-content-server/blob/ba772856c872820e881157dc155d56e8fdfdbf78/app/scripts/views/sign_up.js#L359:L361) event is non-existent.

**Comment by shane-tomlinson** [comment]
Even more curious, Marketplace is an OAuth relier, `fxa.content.signup.preverified` and `fxa.content.signup.preverified.success` are not even the correct events to be looking for. Instead, we should be looking for `fxa.content.oauth.signup.preverified` and `fxa.content.oauth.signup.preverified.success`, neither of which is seen by DataDog.

![screen shot 2016-09-15 at 13 12 17](https://cloud.githubusercontent.com/assets/848085/18549445/60e727fa-7b46-11e6-9cc6-98edd1b530bc.png)

@jrgm, @vladikoff - any ideas?

**Comment by rfk** [comment]
At a high level, I support removing this feature.  I'm very curious why there's a non-zero rate of users being created through this flow.

**Comment by rfk** [comment]
> Even more curious, Marketplace is an OAuth relier, fxa.content.signup.preverified and 
> fxa.content.signup.preverified.success are not even the correct events to be looking for

As far as I can see in datadog, only the `fxa.content.signup.preverified.success` event is present.  If I group them by `service`, all the events appear to have `service=sync`.

The code that emits the `success` event doesn't actually check that a pre-verified token was used, it just checks whether the account has `verified: true` immediately after the create.  So these appear to be sync users who are being created pre-verified somehow.  Very strange...

**Comment by rfk** [comment]
I'm looking at the flow here:

  https://github.com/mozilla/fxa-content-server/blob/ba772856c872820e881157dc155d56e8fdfdbf78/app/scripts/views/mixins/signup-mixin.js#L57

And I wonder if these are people who:

1. Fill in the account signup form and submit it
2. See the choose-what-to-sync form, but then
3. Get a "you've got mail" notification, deal with it immediately and verify the account, then
4. Go back to completing the choose-what-to-sync form, with a now verified account

Is this possible?  It's not obvious to me whether the CWTS screen would detect the change in account state and then pass it on to `onSignUpSuccess`.

**Comment by rfk** [comment]
In any case, if the expected OAuth events are not showing up in our metrics, then it sounds like we're tentatively clear to set about removing this feature.

**Comment by philbooth** [comment]
> According to DataDog, about between 100 and 200 pre-verified accounts are created per day.

Maybe related:

https://sql.telemetry.mozilla.org/queries/1205/source

These are users who are triggering our completion signal for the sign-up flow, but for which we are not emitting an `account.verified` flow event. It may be that they are just another manifestation of the problem discussed in https://github.com/mozilla/fxa-auth-server/issues/1457, or maybe they are something different that is related to this anomaly.

**Comment by shane-tomlinson** [comment]
> I'm looking at the flow here:
> 
> https://github.com/mozilla/fxa-content-server/blob/ba772856c872820e881157dc155d56e8fdfdbf78/app/scripts/views/mixins/signup-mixin.js#L57
> 
> And I wonder if these are people who:
>
>  Fill in the account signup form and submit it
>  See the choose-what-to-sync form, but then
>  Get a "you've got mail" notification, deal with it immediately and verify the account, then
>  Go back to completing the choose-what-to-sync form, with a now verified account
> 
> Is this possible? It's not obvious to me whether the CWTS screen would detect the change in account state and then pass it on to onSignUpSuccess.

YES!! Using the flow outlined above, check this out:

![screen shot 2016-09-16 at 10 32 36](https://cloud.githubusercontent.com/assets/848085/18581525/f10cd246-7bf8-11e6-90dc-c30080323845.png)

BAM! So, ~ 200 users a day verify their account before they complete CWTS. I wonder if that has the possibility of skewing our numbers. I wonder how many more users verify but never complete CWTS.

**Comment by shane-tomlinson** [comment]
From Allen Short on the Marketplace team:

> preVerifyToken was indeed only used when migrating users from Persona to FxA and its use was removed from the Marketplace codebase in Jan 2015.
> 
> https://github.com/mozilla/zamboni/commit/97aacb669ea9f066cc1a51635bbde20e24e4f392#diff-33115e6e90d565419dfd81e2a80900f8L43

**Comment by rfk** [comment]
Let's remove it them; it should be straightforward to bring back if we find we need it for something else.
