### ISSUE TITLE
Remove the "need inspiration" link from password strength warning

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4157]
Our initial metrics indicate that few users are clicking it, and a chunk of those that do click it, don't appear to be coming back.  Rather than continue investing in e.g. l10n for this feature, seems like we should just pull it out.

@ryanfeeley please comment to indicate your approval or otherwise?

**Comment by ryanfeeley** [comment]
I think it's safe to remove it from here, but I haven't given up on offering help to users that want it. This just isn't the right context.
