### ISSUE TITLE
Open in webmail button appears in English

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#4158]
This string [1] is localized [2], but it appears in English on production 

[1] https://github.com/mozilla/fxa-content-server/blob/42310452874f68dc2592ecdb92eae82089a14a28/app/scripts/templates/confirm.mustache#L26
[2] https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/fr/LC_MESSAGES/client.po#L134-L137

<img width="511" alt="capture d ecran 2016-09-16 a 18 43 01" src="https://cloud.githubusercontent.com/assets/1294206/18593821/6e057124-7c3d-11e6-8493-d894c8bab98a.png">

**Comment by shane-tomlinson** [comment]
Thanks for the report @TheoChevalier - Pontoon [reports this string was translated 12 months ago](https://pontoon.mozilla.org/fr/firefox-accounts/LC_MESSAGES/client.po/?search=open+gmail&string=134258), so I'm not sure why it's not being translated correctly. Digging in now.

**Comment by shane-tomlinson** [comment]
I have found the problem, the helper function we use for extraction does not do any actual translation, and we [are not running the buttonName through the translator](https://github.com/mozilla/fxa-content-server/blob/7b31dc29dd1eef2b4b2b52d7f6370c144e507009/app/scripts/views/mixins/open-webmail-mixin.js#L99).
