### ISSUE TITLE
Log an explicit success event when signup/signin completed

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4163]
As discussed in https://github.com/mozilla/fxa-content-server/issues/4130, the way we currently use screen events to measure the completion rate of various things can be quite fragile.  @shane-tomlinson suggested we emit specific events for "signup succeeded" and "signin succeeded" that are not tied to a particular screen, to make it easier to stay on top of our core success metrics.

**Comment by vbudhram** [comment]
Great history behind why there are so many `sigin.success` metrics in Datadog, https://github.com/mozilla/fxa-content-server/pull/4606#discussion_r95581170

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4230
