### ISSUE TITLE
Add minimum spinner time to refreshing devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4165]
Much like [this bug for Sync in desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1239042) we need to provide feedback that the device refresh button is doing something.

For our purposes, one revolution of the spinner is sufficient. If that's not easily calculable 1600ms will do.

**Comment by ryanfeeley** [comment]
DO IT

**Comment by ryanfeeley** [comment]
1600ms not 160ms @vladikoff

**Comment by shane-tomlinson** [comment]
Dup of #4570, closing.
