### ISSUE TITLE
Clean up settings panel navigation logic

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4166]
We can move the 'routes' into templates with `data-` and use that to navigate, etc

Ref: https://github.com/mozilla/fxa-content-server/pull/4131#r79147802

**Comment by sunakshi96** [comment]
@vladikoff you mean router.js  in app/scripts/lib/? Also  in which sub directory under templates, we can move router?

**Comment by vladikoff** [comment]
Let's reopen this if we revisit this 🗡
