### ISSUE TITLE
Cannot use "Disconnect" after pressing ESC in clients_disconnect

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4169]
Ref: https://github.com/mozilla/fxa-content-server/pull/4131#pullrequestreview-624743

**Comment by shane-tomlinson** [comment]
@ryanfeeley suggested started with hooking up an Escape key handler in the "Reasons for disconnecting" modal dialog.

**Comment by vladikoff** [comment]
We are switching to Radio buttons in the "reasons" view in PR: https://github.com/mozilla/fxa-content-server/pull/4578 + ESC is already working, but there is a bug where you cannot use "Disconnect" after hiding the panel once using the ESC key:

![a](https://cloud.githubusercontent.com/assets/128755/21770958/7c2854c2-d653-11e6-998f-60a2e55cc6e4.gif)

I also noticed in Chrome the **panel closes** but in Firefox the panel stays open after pressing ESC. 
@divyabiyani do you see the same on your machine?

**Comment by divyabiyani** [comment]
@vladikoff In my case, firefox is also closing the panel after ESC but only once.

**Comment by vbudhram** [comment]
This may or may not be related to this issue, but `Devices & apps` view does not collapse when you press escape. All other settings pages collapse. I wonder if it has something to do with `autofocus` because no button in clients view as that attribute.

**Comment by vladikoff** [comment]
@vbudhram yea the ESC event is not properly set on the panel (no input element is in focus on that panel). Also the view is re-rendered when new items load up which adds to this problem

**Comment by vladikoff** [comment]
@vbudhram also see 
https://github.com/mozilla/fxa-content-server/issues/4569
https://github.com/mozilla/fxa-content-server/issues/4166
https://github.com/mozilla/fxa-content-server/issues/3386

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-content-server/pull/4716
