### ISSUE TITLE
Use selenium to take screen shots of all screens?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#417]
This could help us detect styling regressions.

**Comment by vladikoff** [comment]
Should have time in the next few days to get to this. Will probably use SauceLabs for screenshots due to lack of support of the `takeScreenshot` command on mobile platforms

**Comment by vladikoff** [comment]
http://screenshots.dev.lcip.org/ is now live! 

Send your ideas to the issue tracker here: https://github.com/vladikoff/fxa-cyclops/issues

**Comment by shane-tomlinson** [comment]
@vladikoff - This is one of the sweetest things I've ever seen.
