### ISSUE TITLE
grunt-rev interprets images files as utf8 when calculating an md5 of the file

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4180]
I looked into why all the image names changed with node4, while the actual image content had not.  The answer is that grunt-rev interprets all files according to `grunt.file.defaultEncoding`, which by default is utf8. Differences on `Buffer` implementations between node 0.10 and node 4, lead to different hash values, although neither is a correct `md5` of the file contents.

A later version of grunt-rev.js has fix related to properly handling utf8, although I think the correct fix is to call `grunt.file.read` with `{ encoding: null }` and just treat all files as byte sequences, independent of how they are intended to the interpreted/rendered.

Anyways, not sure if we need to much about this. If file content changes, most likely grunt-rev will have a corresponding change in what it computes as a new filename. Still, having real md5sum values in the filename would have been nice.

**Comment by shane-tomlinson** [comment]
Ref #4190

**Comment by vladikoff** [comment]
from mtg: Fork from 0.1.0

**Comment by vladikoff** [comment]
this was fixed
