### ISSUE TITLE
.map files do not have cache busting URLs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4185]
![screen shot 2016-09-23 at 17 05 38](https://cloud.githubusercontent.com/assets/848085/18792840/078fa8a6-81b0-11e6-81ba-74aa97eec529.png)

If we push two versions of a JS resource that point to the same map, one of those two JS files is going to use the wrong map.

Ref #4177

**Comment by vbudhram** [comment]
from mtg: a normal user doesnt normally see this

**Comment by vladikoff** [comment]
Closing for now
