### ISSUE TITLE
fork and fix grunt-rev from whatever version we are using, or just write our own.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4190]
Unsupported module, and the md5 is totally wrong. HEAD of the repo does not even install or pass on travis. npm ftw!

**Comment by shane-tomlinson** [comment]
grunt-usemin is no longer maintained either - https://github.com/yeoman/grunt-usemin

**Comment by shane-tomlinson** [comment]
This and #4180 seem to be the same issue. One is a suggestion, one is an observable effect. Should we keep only one of these open?

**Comment by pdehaan** [comment]
Looks like there is an open PR for this at https://github.com/cbas/grunt-rev/pull/32, but that repo seems unmaintined for the past ~4 years. (same w/ grunt-filerev)

Or we could just write our own module, and then unmaintain it.

**Comment by jrgm** [comment]
... and that pull request is wrong ;-)

**Comment by pdehaan** [comment]
Ah, I saw your `{ encoding: null }` comment in #4180 and saw https://github.com/cbas/grunt-rev/pull/32/files#diff-e7578b93a9244a3063f6222e6c27a72fR21 and assumed it was the same solution. Fair enough... I'll stop talking now.

**Comment by vladikoff** [comment]
fixed, there is a pr with its own issue

**Comment by jrgm** [comment]
Actually, that other PR would get the right result, but leaves behind an unused parameter. If encoding:null, the a Buffer is passed to update, in which case the `fileEncoding` is ignored.
