### ISSUE TITLE
Add ellipses to Settings expand

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4195]
See ref: https://github.com/mozilla/fxa/issues/192

**Comment by vladikoff** [comment]
Replace all `&hellip;` and (...) 3 dots with `…`

**Comment by shane-tomlinson** [comment]
👍 My fears were unfounded.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/issues/4202 by @divyabiyani  👍
