### ISSUE TITLE
In Display Name keep Change button disabled until content is different

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4201]
STEPS TO REPRODUCE
In Settings with a display name set, open the Display name section

EXPECTED RESULTS
Change button remains disabled until content in input is changed

ACTUAL RESULTS
Change button is always active

![change](https://cloud.githubusercontent.com/assets/68213/18877811/7723852c-849c-11e6-8c3a-f435a4cf9faa.gif)

**Comment by rackstar17** [comment]
Hello.
I am new to this codebase and am interested in the issue.
I have looked up the files relating to this issue 
The template which is `display_name.mustache` and related js which is `display_name.js` 
But I'm having trouble applying the fixing logic to it .
Can you help me get started ?
Thanks.

**Comment by rackstar17** [comment]
@ryanfeeley Hi. I want to work on this issue , can you read my above comment and get me started on this.
Thanks.

**Comment by vladikoff** [comment]
@TDA can you provide some tips on this to @rackstar17  ?

**Comment by TDA** [comment]
@vladikoff Sure!  Correct me if I am wrong :)
@rackstar17 You will need to do the following:
1. Have a way to recognize that the display_name field is active. To do this, you will want an `focus` event. See `fxa-content-server/app/scripts/views/mixins/floating-placeholder-mixin.js` for a similar approach.
2. Disable the `change` button by default. 
3. See if the text has changed, if so, enable the button.

Handle these scenarios:
1. User types in nothing new => Button is disabled
2. User types in something new => Button is enabled
3. User types in something new, but deletes it later and only old text is found => Button is disabled

Boilerplate code:
```
events: {
  'focus .display-name': 'yourAwesomeFunc'
},

yourAwesomeFunc: function () {
  // do all your stuff
}
```
