### ISSUE TITLE
Need UX review for Connected Apps

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4213]
@ryanfeeley @davismtl please visit: 

https://latest.dev.lcip.org/settings/clients?forceDeviceList=1&forceAppsList=1
http://accounts.firefox.com/settings?forceDeviceList=1&forceAppsList=1

and provide any feedback to unblock this feature and clear it to be enabled to users without a url flag.

On latest you can use these apps to test:

https://123done-content.dev.lcip.org/
https://321done-content.dev.lcip.org/

On prod you can use add-ons, pocket, etc.

**Comment by davismtl** [comment]
@vladikoff Sorry for the delay. What account should I use to login here? (mine doesn't seem to work)
https://latest.dev.lcip.org/settings/clients?forceDeviceList=1&forceAppsList=1

**Comment by vladikoff** [comment]
> @vladikoff Sorry for the delay. What account should I use to login here? (mine doesn't seem to work)
https://latest.dev.lcip.org/settings/clients?forceDeviceList=1&forceAppsList=1

You need make a new account on that **latest** server.

**Comment by davismtl** [comment]
Right, that seems obvious now that you say it. lol
Will that account be persistent moving forward or does it get regularly wiped?

**Comment by vladikoff** [comment]
> Will that account be persistent moving forward or does it get regularly wiped?

It does not regularly get deleted but it may be deleted at any moment.

**Comment by davismtl** [comment]
@vladikoff @rfk (since vlad is on pto) 
I setup and am running "latest" on my laptop following this: https://gist.github.com/vladikoff/6fd3886031e0d608ad631eca29d7760d

Next up I tried to do this:
> On latest you can use these apps to test:
> https://123done-content.dev.lcip.org/
> https://321done-content.dev.lcip.org/

I get "Unable to Connect" :-/
Any suggestions?

**Comment by rfk** [comment]
If we're testing on latest, ISTM those URLs should be:

* https://123done-latest.dev.lcip.org/
* https://321done-latest.dev.lcip.org/

> I get "Unable to Connect" 

Where do you get this?

**Comment by rfk** [comment]
The following worked for me:

* Install and run fxa-dev-launcher per the instructions in that gist
* Sign in to sync in the launched browser
* Visit https://123done-latest.dev.lcip.org/ in that browser and sign in
* Visit https://latest.dev.lcip.org/settings/clients?forceDeviceList=1&forceAppsList=1 in that browser

I get the following:

![screen shot 2016-10-14 at 10 37 54](https://cloud.githubusercontent.com/assets/34695/19370854/4dcc3370-91fa-11e6-8fba-1d0cf6a53c8c.png)

> I get "Unable to Connect"

Also it occurs to me, that you may have just happened to hit latest while it was updating itself, or while some bustage was being fixed, and the server happened to be down.  Simply trying again might be enough.

**Comment by davismtl** [comment]
> If we're testing on latest, ISTM those URLs should be:
> https://123done-latest.dev.lcip.org/
> https://321done-latest.dev.lcip.org/

Well look at that! Those URLs worked :)
Thanks :)

**Comment by davismtl** [comment]
@vladikoff 
The feature works well. The UX/UI is a bit rough around the edges though.

With the version I tested, an app looks like a laptop so it's hard to tell the difference with a Firefox browser. I think Feeley is getting you the icons. (or already did)

Also, when I click "Disconnect...", the line just disappears without any warning or message. 
If I were to put myself in my mother's shoes (for example), I don't think she would have any idea what that button did as a result of clicking on it.

I think @ryanfeeley need to make a couple of proposals to address the following:
- Add a short explanation of what these "Disconnect..." buttons will do. I think we're too close this feature and we need to address that many people are not technical and have no idea what disconnecting an app (or device means).
- Also add a small confirmation message for apps that says something like "This app no longer has access to your Firefox Account. You may however regrant permission to this site by re-logging into it with your Firefox Account" (ideally in less words)

**Comment by ryanfeeley** [comment]
We have a design to accomodate a message like that in the original design spec (see #6b) https://docs.google.com/document/d/1VrysJ4LFPZ20IeMMmRts5l_2GUHhm890rlQhD012U_g/edit

I think that message works, but we should also work with AMO to log the user out (and update our message when we do).

**Comment by vladikoff** [comment]
> an app looks like a laptop so it's hard to tell the difference with a Firefox browser. I think Feeley is getting you the icons. (or already did)

@ryanfeeley could we please get a "default" service icon? currently we only have Pocket and Add-ons, we need some default for 123done, 321done, oauth console, pontoon and others...

**Comment by ryanfeeley** [comment]
> @ryanfeeley could we please get a "default" service icon? currently we only have Pocket and 
> Add-ons, we need some default for 123done, 321done, oauth console, pontoon and others...

I thought I filed this. Best thing to do is use the capital letter from the service and use full corner radius (circle). Use white capital letter on light grey. I can mock up.

**Comment by ryanfeeley** [comment]
@vladikoff 
    background: #bebebe;
    border: none;
    color: #fff;
    border-radius: 50%;
![screenshot 2016-11-08 17 51 16](https://cloud.githubusercontent.com/assets/68213/20120739/04223922-a5dc-11e6-8608-d0c25221cd57.png)
