### ISSUE TITLE
Remove colon from device timestamps

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4214]
Because we'll likely end up mixing time-stamp types (last active, last login, created, registered, etc.) we should remove the colon so that timestamps are more distinguishable.

CURRENT

* Last active: 3 days ago

PROPOSED

* Last active 3 days ago

**Comment by RPraneetha** [comment]
Can I work on this issue or is it already assigned to someone else?

**Comment by shane-tomlinson** [comment]
@RPraneetha - already taken care of in #4222. If you need help choosing another bug, you can ping us in the #fxa IRC channel!

**Comment by vladikoff** [comment]
This was fixed 👍
