### ISSUE TITLE
Ensure that current device is always the top item in devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4215]
STEPS TO REPRODUCE
Have a few devices syncing

EXPECTED RESULTS
Current device is always first

ACTUAL RESULTS
In some conditions, current device is not first. I'm actually not sure how to reproduce this.

**Comment by vladikoff** [comment]
> In some conditions, current device is not first. I'm actually not sure how to reproduce this.

Did you login via new "web" session instead of sync?

**Comment by ryanfeeley** [comment]
@vladikoff I'm not sure. But I've done sync and settings view from this machine more recently so current should be first. 
![screenshot 2016-09-29 11 53 49](https://cloud.githubusercontent.com/assets/68213/18961564/6a559574-863b-11e6-8327-c4767d222e08.png)

**Comment by vladikoff** [comment]
Cool, thanks for the screenshot

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-content-server/pull/4430
