### ISSUE TITLE
flow.begin event should identify the starting view

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4217]
This came up in my meeting with @davismtl just now.

The `flow.begin` event should indicate which view the user landed on. Either via metadata or as different events for each view.

**Comment by vladikoff** [comment]
hm we already have `.engage` events, is this not enough?

**Comment by davismtl** [comment]
flow.begin is our top of funnel. We can't accurately measure how many people see the start of our our signin vs our signup flow. We can only make the distinction in step 2, once they start to engage with a flow.

This means, if we try to optimize wording of CTA to signin or signup, we won't accurately know how many people are exposed to each form.

It'll also help measure the difference in engagement rate of the form by form location (e.g. firstrun, vs settings).

Hope that clarifies

**Comment by philbooth** [comment]
Added a `shipit` label because this affects our metrics queries so it would be good to ship in 71 if possible.
