### ISSUE TITLE
cachebust goog play store images

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4218]
currently not cache busted. Images are changing. Discuss.

**Comment by vladikoff** [comment]
Looking at Git History those images change very rarely, Apple images have not changed in 2 years. 
My suggestion is to just leave these alone and not add extra cache processing to these. 

If we get new version of images let's just reference them manually with a new name in the directory and templates. Please let me know if we need to do that to the new Android images or if that already figured itself out
