### ISSUE TITLE
`sign_in - data-flow-begin attribute is set` functional test does not return promise, fails when does

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4219]
See https://github.com/mozilla/fxa-content-server/blob/9af4895b910dda03dda9b3b44a3b4f4552687b99/tests/functional/sign_in.js#L185:L188

cc @philbooth

**Comment by vladikoff** [comment]
Related to this: https://github.com/mozilla/fxa-content-server/issues/3892

I think if you specifically grep this test then you are gonna have a bad time.
