### ISSUE TITLE
Metric investigation: Sign-ing success vs Sync sign-in success

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4230]
In Vijay's post-analysis of the launch of email signin confirmation feature, it was mentioned that pre-signin confirmation, we had 100% signin success but that Sync sign-in success was between 42-52%.

Why is there a 50% difference between the FxA and Sync signin success rates?

Here is the feature doc where we flagged this question:
https://github.com/mozilla/fxa/commit/f23707fa535935bbb934df62af2de8668f366187#commitcomment-19273910

**Comment by rfk** [comment]
For context, this is referring to the "sync signin success %" graph on this dashboard: https://app.datadoghq.com/dash/163668/fxa-content---signin-confirmation

The metric being plotted is `ewma_10( ( ( a + b + c ) / ( d + e ) ) * 100 ) ; ewma_10( ( ( a + b ) / ( d + e ) ) * 100 )` with:

* `a` = `fxa.content.signin.signin.success`
* `b` = `fxa.content.force_auth.signin.success`
* `c` = `fxa.content.complete_verification.signin.success`
* `d` = `fxa.content.signin.submit`
* `e` = `fxa.content.force_auth.submit`

>  it was mentioned that pre-signin confirmation, we had 100% signin success

IIUC this was referring to "100% signin success if you enter the right password", simply by virtue of there not being any more steps to complete in the flow.

The broader question though, is why is this metric only at around 50%?  Surely it's not the case that fully half of all signin form submissions generate an error of some kind...is it?

**Comment by rfk** [comment]
> Surely it's not the case that fully half of all signin form submissions 
> generate an error of some kind...is it?

Well shut my mouth, I can get the percentage from 50% up to 66% if I include `fxa.content.error.signin.auth.102`, `103`, `110`, `114` and `999` in the numerator.  I was datadog let me do wildcarding so I could say `"fxa.content.error.signin.*"`.

**Comment by rfk** [comment]
I don't have any more time to poke at this one today, but "sync signin error %" would make a good companion graph to "sync signin success %".  Perhaps we can make this simpler by emitting a generic "fxa.content.error.signin.auth" event for *any* errno, as well as the more precise "fxa.content.error.signin.auth.XXX".

**Comment by shane-tomlinson** [comment]
The short answer is because of the way we define "signin success" - See https://github.com/mozilla/fxa-content-server/pull/4606#discussion_r95581170 for a bunch of context, and https://github.com/mozilla/fxa-content-server/pull/4606#discussion_r95802896 for more.

The slightly longer answer is signin.success is only emitted if the user totally completed the signed in flow, as a fully verified user. Users who sign in with an unverified account and must verify their email, and users that go through signin confirmation and must verify their email will never emit a signin.success event.

more...thought...needed....

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-content-server/pull/4606 where we added the one true "signin.success"
