### ISSUE TITLE
Messaging size mismatch

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4233]
Our messages should be consistent in size. In this example, the red is correct and the blue is not.
<img width="462" alt="screenshot 2016-10-01 13 56 02" src="https://cloud.githubusercontent.com/assets/68213/19082161/f16514ca-8a2a-11e6-8ab8-53fb5dc7bab6.png">

**Comment by vladikoff** [comment]
@ryanfeeley what should it be?

**Comment by ryanfeeley** [comment]
@vladikoff 

Inspector says:

.error, .info, .success {
	border-radius: 2px;
	color: #fff;
	display: none;
	margin-bottom: 5px;
	padding: 5px;
	position: relative;
	top: -15px;
}

**Comment by vladikoff** [comment]
> the red is correct and the blue is not.

Ah ok, that makes sense! we actually had it like the red, but then followed the proposed design to make it bigger.

**Comment by ryanfeeley** [comment]
@vladikoff I think it might only be that height if there is an × on the right. I forget.

**Comment by divyabiyani** [comment]
![dbt](https://cloud.githubusercontent.com/assets/8852007/19103895/523e7850-8af7-11e6-873f-3cbcf959c144.png)
@ryanfeeley Is this the desired output?

**Comment by ryanfeeley** [comment]
@divyabiyani Yes, thank you! Question: is that a Chrome screenshot? I noticed that our fonts render lighter in Chrome.

**Comment by divyabiyani** [comment]
@ryanfeeley No,its firefox sreenshot.
Also,I think this is due to this particular [code](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/_state.scss#L33-L35).

**Comment by vladikoff** [comment]
this was fixed!
