### ISSUE TITLE
`var self = this` is a footgun waiting to happen.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4238]
TIL about [window.self](https://developer.mozilla.org/en-US/docs/Web/API/Window/self) which is a reference to a WindowProxy version of `window`. For all intents and purposes `window.self === window`. This made #4237 possible, because you can do [self.SOME_VARIABLE_HERE](https://github.com/mozilla/fxa-content-server/blob/bed3feb9fcd370293c97a6884a768c2d8a9edd3b/app/scripts/views/confirm.js#L163) in a local function without `self` ever being defined. ESLint doesn't complain. Neither does JSHint. Nor do the browsers. 

Should we banish `var self = this` and just bite the bullet and switch to fat arrows?

Ref #4237

**Comment by philbooth** [comment]
> Should we banish `var self = this` and just bite the bullet and switch to fat arrows?

🔥 BURN IT! 🔥

**Comment by vbudhram** [comment]
I'm for it. Or at least if it is used, then there has to be some associated comment why.

**Comment by TDA** [comment]
Nuke it!
