### ISSUE TITLE
Discuss improving Account Confirmed screen metrics

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4242]
![account-confirmed](https://cloud.githubusercontent.com/assets/68213/19116954/484dcaba-8ae5-11e6-9136-eac7c5056c07.png)

Inspired from a chat yesterday with @shane-tomlinson.

Currently our metrics don't distinguish between the different contexts surrounding where users confirm their email. This makes it difficult to know how many accounts we are confirming in a day, but also the proportions of experiences we are delivering.

It appears as though we are probably counting the Account Confirmed screen multiple times.

1. The first time the user clicks the email link is the only time we should count that the account is confirmed.
1. If the user’s browser redirects to the Account Confirmed screen, it should be recorded as a different event.
1. If they click the link after the account is confirmed, it should be recorded as a different event (even if the screen is the same).

Should we:

* have a way to distinguish between users who verify in the originating version of Firefox?
* have a way to distinguish between users who verify in a version of Firefox that already has already verified a different count? (i.e. "Your account is ready")
* distinguish other things?

Likely of interest to our metrics master @davismtl

**Comment by davismtl** [comment]
Great catch guys!

If we are over counting then it is likely skewing our funnel metrics.

It would be interesting to tell the difference between these 3. I feel like 1. & 3. mentioned above could potentially be tracked if have a user or flow id. We just need to do a total count vs uniques. (but perhaps that's not possible) As per 2. , it does seem to be an event of its own.
