### ISSUE TITLE
testIsBrowserNotifiedOfLogin fails on latest

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4243]
![image](https://cloud.githubusercontent.com/assets/128755/19119512/fc22d230-8aed-11e6-84c4-f41273520f7c.png)

Ref: https://tc-test.dev.lcip.org/viewLog.html?buildId=15757&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

cc @jrgm @shane-tomlinson @philbooth

**Comment by vladikoff** [comment]
To reproduce run with: 

> npm run test-latest grep="Firefox Desktop Sync v1" firefoxBinary=/Users/vladikoff/Desktop/FF46.app/Contents/MacOS/firefox-bin

**Comment by vladikoff** [comment]
seems like `data.verified` comes back as `false`
> AssertionError: account is not verified: expected true to be false
  at Assertion.<anonymous>  <node_modules/intern/browser_modules/chai/chai.js:589:10>
  at Assertion.addProperty  <node_modules/intern/browser_modules/chai/chai.js:4240:29>
  at Function.assert.isFalse  <node_modules/intern/browser_modules/chai/chai.js:2521:31>
  at Command.<anonymous>  <tests/functional/lib/fx-desktop.js:80:20>

**Comment by vladikoff** [comment]
> [12:21:40]  <stomlinson>	vladikoff: I think ".net" and ".com" have to be "\\.net" and "\\.com", I remember jrgm or pb saying that.
[12:22:35]  <stomlinson>	vladikoff: but then again, I haven't successfully gotten the new format to work yet

**Comment by philbooth** [comment]
@vladikoff, if the regex thing is the cause, I believe this may fix the problem:

https://github.com/mozilla/fxa-dev/pull/279

**Comment by vbudhram** [comment]
@vladikoff, looks like when testing locally with `master` of auth and content branches it goes through confirm sign-in process. When testing with latest it does not. This could imply that the regex is not being set correctly as @philbooth mentioned.

**Comment by vbudhram** [comment]
FWIW, re-ran this with `npm run test-latest grep="Firefox Desktop Sync v1"` and all test passes.

**Comment by vladikoff** [comment]
Yay!

**Comment by vladikoff** [comment]
This was fixed.
