### ISSUE TITLE
npm ERR! Failed at the fxa-content-server@0.70.0 start-remote script.

### ISSUE THREAD

**Issue by Anh3h** [mozilla/fxa-content-server#4244]
i get the following error when i do 'npm run start-remote':
 fxa-content-server@0.70.0 start-remote /home/courage/Desktop/Current project/fxa-content-server
> node scripts/check-local-config && CONFIG_FILES=server/config/local.json,server/config/content.json grunt server

Loading "connect-fonts.js" tasks...ERROR
>> Error: Cannot find module 'gobbledygook'
Loading "l10n-supported-locales.js" tasks...ERROR
>> Error: Cannot find module 'gobbledygook'
Loading "po2json.js" tasks...ERROR
>> Error: Cannot find module 'gobbledygook'
Loading "remarkable.js" tasks...ERROR
>> Error: Cannot find module 'gobbledygook'

Running "server" task

Running "clean:app" (clean) task
>> 0 paths cleaned.

Running "selectconfig:app" (selectconfig) task
Using configuration files server/config/local.json,server/config/content.json

Running "l10n-create-json" task

Running "copy:strings" (copy) task
Copied 218 files
>> No "po2json" targets found.
Warning: Task "po2json" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2016-10-05 16:53:01 UTC+1)
loading tasks  18.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
copy:strings   345ms  ▇▇ 2%
Total 18.8s

npm ERR! fxa-content-server@0.70.0 start-remote: `node scripts/check-local-config && CONFIG_FILES=server/config/local.json,server/config/content.json grunt server`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the fxa-content-server@0.70.0 start-remote script.
npm ERR! This is most likely a problem with the fxa-content-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/check-local-config && CONFIG_FILES=server/config/local.json,server/config/content.json grunt server
npm ERR! You can get their info via:
npm ERR!     npm owner ls fxa-content-server
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.0-38-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-remote"
npm ERR! cwd /home/courage/Desktop/Current project/fxa-content-server
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/courage/Desktop/Current project/fxa-content-server/npm-debug.log
npm ERR! not ok code 0

some one please help me!!!

**Comment by vladikoff** [comment]
> npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28

Your node and npm are out of date.
Make sure to get `node 4.5 or 4.6`
