### ISSUE TITLE
New web console doesn't render our easter-egg?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4248]
I noticed this while debugging something else:

![screen shot 2016-10-06 at 13 49 44](https://cloud.githubusercontent.com/assets/34695/19138904/e2dcaed4-8bcb-11e6-8a54-56ada4f1355f.png)

There was an email on fx-team this morning about a "New web console in Nightly", I wonder if that's what is causing this to mis-render.

**Comment by TDA** [comment]
@rfk +1 to this. Cant see the easter egg properly on nightly 52.0a in any mode (docked/undocked) :( 
I can see it fine on 50.0b3 and b4

**Comment by shane-tomlinson** [comment]
Likely a Firefox issue. Backlog to keep track of it, hopefully the problem fixes itself via Fx updates.

**Comment by rfk** [comment]
Definitely a Firefox issue, but I fear it may be on purpose, i.e. they're deliberately changed the way that strings are output in the console and it won't be fixed.  Something to keep an eye on, but anyways, definitely not our highest priority right now :-)

**Comment by vladikoff** [comment]
Seems like that was fixed!

![image](https://cloud.githubusercontent.com/assets/128755/19665018/012a7684-9a11-11e6-917d-e5fc8c335ee0.png)
