### ISSUE TITLE
Remove the "sync preferences" button

### ISSUE THREAD

**Issue by Verdi** [mozilla/fxa-content-server#4250]
At some point over the last year, we added a "Sync Preferences" button to the account verified step. In user testing I'm seeing this as problematic for a couple of reasons:

1. People misunderstand the nature of the button label. One participant thought clicking the button would then sync their preferences with something. 
2. There's no action required or desired on this page. People have already chosen what to sync. There is no need to manage their account or to change the name of their device.
3. Setting brand new users loose in the preferences can lead to problems. I've had two participants reach this point so far (still more test videos to watch) but both of them then **continued to look around the rest of the preferences and make crippling changes to Firefox.**

It seems to me that the main reason for this button is to reinforce the idea of connecting a second device with the multi-device image and the links to the mobile applications. So my suggestion for the immediate future is:

- Change the button copy to something like "Learn about connecting a second device"
- Link to http://mozilla.org/firefox/sync which will display content about signing in on a mobile device, complete with app store buttons.

![syncinfo](https://cloud.githubusercontent.com/assets/107992/19158691/4e83f3b2-8baf-11e6-85d2-208c5a1b456e.jpg)

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by rfk** [comment]
Hi @ryanfeeley, could you please take a look at this and suggest a concrete course of action for us to take?

**Comment by ryanfeeley** [comment]
<img width="1517" alt="screenshot 2016-10-17 16 40 32" src="https://cloud.githubusercontent.com/assets/68213/19454982/4c54f702-9489-11e6-8bda-7d7f0a74f29f.png">

This is a tough one. We know that this page is opened in many different contexts:

1. In the originating signed-in Firefox (when we show the Sync Preferences button)
1. In another Firefox that is not signed in
1. In a non-Firefox browser
1. In Firefox that is signed in with another user

Am I missing any cases @shane-tomlinson?

For the case where we show the Sync Preferences button, I think the [marketing page](https://www.mozilla.org/en-US/firefox/sync/) does the best job possible.

<img width="1517" alt="screenshot 2016-10-17 16 44 33" src="https://cloud.githubusercontent.com/assets/68213/19455043/851a607c-9489-11e6-91bc-baec23327781.png">

**Comment by ryanfeeley** [comment]
Related: https://github.com/mozilla/fxa-content-server/issues/3697

**Comment by ryanfeeley** [comment]
I think @Verdi is right, and that it is safe to assume that the Sync Preferences button is not helping. What we need is for users to do is connect a second device. I'm working on this with a revised onboarding flow, but for now we should remove it (and complete #3697 so that the buttons appear above the fold for more users).

**Comment by rfk** [comment]
I updated the issue title to reflect the advice of "remove it".
