### ISSUE TITLE
When user completes password reset, they should be notified to sign in again on other devices.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4255]
When a user completes the password reset process, all of their sessions are invalidated. A user has to go back and sign in again to all of their devices, but we don't let them know that. We just say "Password reset complete". It'd be nice if it said something along the lines of "You must now sign in again using your new password on your other connected devices"

<img width="427" alt="screen shot 2016-10-07 at 10 52 35" src="https://cloud.githubusercontent.com/assets/848085/19186048/42395df4-8c7c-11e6-9ae5-b8b72ea5421b.png">

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Great idea. Keep assigned to me. Seeing as the number one category of user today have zero devices connected when resetting, we should probably know before making a recommendation. @shane-tomlinson Can you file an issue to have the capability to use the devices API to offer an intelligent recommendation?

**Comment by ryanfeeley** [comment]
@davismtl @shane-tomlinson Instead of doing a smart one, I think this generic approach will work, and looks closer to our new account verified screens. 
![password-reset](https://cloud.githubusercontent.com/assets/68213/20073876/07bdd482-a4fc-11e6-82d4-7058b047361d.png)

**Comment by shane-tomlinson** [comment]
I like the wording, though I worry allowing users to click on the store badges will distract them from re-connecting their other devices.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Fair point. @alex Want to break the tie?

**Comment by vladikoff** [comment]
@ryanfeeley you mean @davismtl ...

**Comment by davismtl** [comment]
If they are resetting their password, the most important thing is to get them to log back into their original device. I would not drive them to mobile until after they log back into their original device. 

Perhaps after login, if we detect that they don't have a second device, we display a CTA to install mobile.

**Comment by ryanfeeley** [comment]
@davismtl @shane-tomlinson Should this page open a smart banner if they have Firefox for iOS installed?

**Comment by davismtl** [comment]
Good question. 
- If they triggered the reset from a different device, I don't want to distract them from going back to their original device where they reset their password. 
- If their originating device for the password reset was the same iOS device, then I think a smart banner would make sense to get them back quickly.

**Comment by vladikoff** [comment]
@ryanfeeley says just use the new mockup 

<img src=https://cloud.githubusercontent.com/assets/68213/20111208/7566a996-a5b5-11e6-8499-89bc66448c74.png width=350 />

Ready to build!

**Comment by MihaiNinu** [comment]
test
