### ISSUE TITLE
input overlapping modal

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4257]
![](http://v14d.com/i/57f7ac0b5f884.jpg)

This is happening due to the label-helpers that require the z-index.

**Comment by vladikoff** [comment]
This issue is not in Firefox 51 or Chrome
This issue is in Firefox 49.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1278136

**Comment by shane-tomlinson** [comment]
@vladikoff - I think you'll have to make the z-index value 6, tooltips use a value of 5:

<img width="600" alt="screen shot 2016-10-07 at 21 05 26" src="https://cloud.githubusercontent.com/assets/848085/19203923/dec53dd2-8cd1-11e6-93f4-56eb600a53a0.png">

I'm not sure if there are any other z-index's above 5.
