### ISSUE TITLE
[Unblock sign-in] Intermittently, entering the authorization code redirects back to the login page

### ISSUE THREAD

**Issue by petruta** [mozilla/fxa-content-server#4272]
[Steps to reproduce]:
1. Go to https://signin-unblock.dev.lcip.org/
2. Enter an email address and a wrong password so that "Authorize this sign-in" page is opened
3. Paste the authorization code received by email and select "Continue"

[Expected result]:
- Account's settings page is opened

[Actual result]:
- Sometimes, the user is redirected to the previously login screen where the email and the erroneous password are prefilled and the message "Incorrect password. To double-check what you've entered, press and hold down the Show button." is shown

**Comment by shane-tomlinson** [comment]
@petruta - This is expected behavior, if you entered the password incorrectly on the first page. We do not know whether you entered the password incorrectly until after you have entered the unblock code.

**Comment by shane-tomlinson** [comment]
@petruta - on the other hand, if the password is entered correctly, this is indeed a problem.

**Comment by petruta** [comment]
Thanks, Shane!

As I understood from documentation "A user that successfully enters the code will be signed in. If the user is signing in for Sync, the signin-confirmation step will be skipped since the user will have just verified their email address. For Sync users, the flow will complete at about:preferences#sync", the user will be signed in, if the code is correct.
If that's not the case, I will update my test cases.

**Comment by shane-tomlinson** [comment]
> If that's not the case, I will update my test cases.

Thanks for pointing out the inconsistency, I'll update the doc to reflect reality. There is a technical reason the password must also be correct, the password is used to generate the Sync encryption key! 

Closing as "the doc needs to be updated!"

**Comment by petruta** [comment]
I think the behavior should be consistent, since only intermittently the user is redirected to the previously login page. 
In some cases, account's settings are opened after entering the authorization code.
I couldn't find a correlation between those two.

**Comment by shane-tomlinson** [comment]
@petruta - the user is only redirected back to the login page if the user entered the wrong password, otherwise signin completes. Signin will *only* complete if the correct password was entered in the first step. This behavior was specified to minimize the number of steps users have to go through.
