### ISSUE TITLE
Create `Why is this happening to me?` content for SUMO

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4288]
Follow on for signin unblock. When we have this, add a new experiment in the [fxa-content-experiments repo](https://github.com/mozilla/fxa-content-experiments) that contains a `blockedSigninSupportUrl` value.

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa/blob/2264bb23f6a89c12768edcef5a57c44c1a81182f/features/FxA-106-signin-unblock/README.md

**Comment by ryanfeeley** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1310822

**Comment by ryanfeeley** [comment]
Looks good to go IMHO

**Comment by vladikoff** [comment]
Needs a PR in the content server or able update

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa-content-experiments/pull/48/files opened with content link, need to find out whether to add any utm_* parameters to the link for SUMO's metrics.

**Comment by vladikoff** [comment]
We have some issues with formatting when links are stacked on the same line:

![image](https://cloud.githubusercontent.com/assets/128755/20316153/ba14cb8a-ab2e-11e6-9250-46a47bc96173.png)

What should we do about this?

**Comment by vladikoff** [comment]
@shane-tomlinson ah seems like Chrome only

Looks fine in FF:

![image](https://cloud.githubusercontent.com/assets/128755/20316208/f072fcd8-ab2e-11e6-9376-422c0b7221ba.png)
