### ISSUE TITLE
OAuth services Disconnect button does not need the …

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4292]
STEPS TO REPRODUCE
Log into AMO with your FxA
Log into FxA Settings and check out Devices & app
Click on Disconnect… button beside AMO

EXPECTED RESULTS
Disconnect is not immediate because … denotes that action is revocable

ACTUAL RESULTS
AMO is immediately disconnected

Until the action is revocable, please remove the …

**Comment by vladikoff** [comment]
This was fixed.
