### ISSUE TITLE
Discuss logging AMO users out when disconnecting from FxA

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4293]
**STEPS TO REPRODUCE**
1. Sign in to AMO
2. Go to FxA Settings (Devices & apps)
3. Disconnect AMO
4. Return to AMO

**EXPECTED RESULTS**
- AMO is signed out

**ACTUAL RESULTS**
- AMO is still signed in

Let's cooperate with AMO to complete the Disconnect experience.

**Comment by rfk** [comment]
/cc @andymckay @mstriemer 

A similar question has come up a few times in bugzilla - if a user changes or resets their Firefox Accounts password, should they automatically get logged out of sites like AMO or Marketplace?  See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1178634

It's a hard problem in general, figuring out the right amount of coupling between relier and IdP login sessions, and IIUC it's something that the OAuth community doesn't have a whole lot of consensus around.  There are a few (draft) specs that would let us do this, but I'm not sure they're widely implemented:

* OIDC session management: http://openid.net/specs/openid-connect-session-1_0.html
* OIDC front-channel logout: http://openid.net/specs/openid-connect-frontchannel-1_0.html
* OIDC back-channel logout: http://openid.net/specs/openid-connect-backchannel-1_0.html

FxA could implement one or more of these without too much drama, if we have reason to believe that reliers would use them.

So, in the first instance it's mostly a question for the AMO team - are you interested in a mechanism for FxA to signal AMO to log the user out, when they e.g. change their password, or revoke access through a not-released-to-the-public-yet OAuth management dashboard?

**Comment by andymckay** [comment]
301 to @muffinresearch

**Comment by mstriemer** [comment]
This doesn't seem like something we want to check all the time so if we were doing this I'm guessing we'd want to cache it for an hour or something and do it in the background or only require the check for requests that modify things. Changing account info, uploading add-ons and new versions, etc.

Doing it sync for an initial GET request feels like overkill, I'm not sure if there's any data we'd want to restrict reading. I think we'd need to update how we manage sessions so we know the last time a session authenticated so that we can invalidate all old sessions and not just the first one that we see.

**Comment by mstriemer** [comment]
I'm not sure if FxA supports changing email addresses but we have an open issue to update our data if it changes (https://github.com/mozilla/addons-server/issues/1609). Would we be able to use this to update any data we get from FxA as well? Email, name, profile photo (perhaps that updates on its own?), although currently we are just using the email.

**Comment by rfk** [comment]
> I'm not sure if FxA supports changing email addresses

Not yet, but we eventually will.

One simple option here, is to set up an SQS queue into which FxA can send events like "user X changed their email" or "user X revoked your oauth token", and have AMO pull events off this queue and process them.

**Comment by shane-tomlinson** [comment]
Should this be made into a feature card? Sounds pretty bulky.

**Comment by vcarciu** [comment]
Same behavior observed after totally deleting the FxA. User is still logged in AMO

**Comment by vladikoff** [comment]
> Doing it sync for an initial GET request feels like overkill, I'm not sure if there's any data we'd want to restrict reading. 

Agreed with this, will probably slow down AMO as well. Closing for now until we need this functionality...
