### ISSUE TITLE
`flow.<view_name>.engage` should not use `this.viewName` (which includes OAuth)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4300]
What we really want is just the last bit of the `viewName`, without the possible `oauth` portion.

cc @philbooth

**Comment by philbooth** [comment]
Same for `.begin` events, I didn't realise it was wrong when I implemented those.

For the record:

```sql
SELECT DISTINCT(type)
FROM flow_events
WHERE type LIKE 'flow.%'
GROUP BY type;
```

```
flow.begin
flow.oauth.signin.engage
flow.signin.submit
flow.signin.engage
flow.oauth.signup.engage
flow.signup.begin
flow.have-account
flow.signup.engage
flow.signup.submit
flow.force-auth.engage
flow.force-auth.submit
flow.oauth.signin.begin
flow.signin.begin
flow.oauth.signup.begin
flow.force-auth.begin
```

**Comment by philbooth** [comment]
Also note that the reason we don't need the `oauth` portion here is because it can already be ascertained from the `service` property.

**Comment by vladikoff** [comment]
> Also note that the reason we don't need the oauth portion here is because it can already be ascertained from the service property.

Nice!
