### ISSUE TITLE
`flow.<view_name>.submit` should use `signup` instead of `signin` when signing in from signup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4301]
The signin-mixin declares a default `signInSubmitContext: 'signin'` which uses `signin` when login occurs from the `signup` page.

cc @philbooth

**Comment by shane-tomlinson** [comment]
@philbooth - a [`flow.signup.submit` already exists](https://github.com/mozilla/fxa-content-server/blob/d39313bc264841f338dbda9cdb27cf5498628d19/app/scripts/views/mixins/signup-mixin.js#L33).

**Comment by philbooth** [comment]
Yeah, submit looks fine, it is just `begin` and `engage` that we need to fix. They're both mentioned in #4300, closing this.
