### ISSUE TITLE
Add custom "unknown account" error for AMO

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4302]
AMO migration is now over, but there are some late stragglers who want their AMO data. These users can still get their data if they use control the email address used for their original account. We can change the message from:

CURRENT:
![746bc54596e4deff020a27909a9cc03bc2085b19_1_375x499](https://cloud.githubusercontent.com/assets/68213/19529805/69a28db6-95ff-11e6-8734-5956bc165d2f.png)

PROPOSED:
“Unknown Firefox Account. To retrieve your Add-on data for that account, **sign up** for a Firefox Account using the same email address."

**Comment by mstriemer** [comment]
There is also an AMO and FxA support article [1] that might be worth linking to. This message looks good though so that might be enough on its own.

[1] https://support.mozilla.org/en-US/kb/access-your-add-ons-firefox-accounts

**Comment by shane-tomlinson** [comment]
@mstriemer - I didn't realize until reviewing #4308 that we still have the `migration=amo` code in place on the content server. Any chance AMO could bring its half back? From out point of view, that would require no work on our end. ;)

**Comment by mstriemer** [comment]
The migration flow is a bit annoying since it adds an extra step and the user could still run into this if they don't understand what's going on.

Maybe instead of updating the error message (I poked around in the code and it looks non-trivial) we could just have a link to our support documentation in the bottom?

<img width="443" alt="screenshot 2016-10-20 12 26 18" src="https://cloud.githubusercontent.com/assets/211578/19570669/9f2ce4ba-96c0-11e6-8bbf-7280cf242f9b.png">

I'm not sure how that would work in languages with longer strings but you get the idea.

**Comment by ryanfeeley** [comment]
Here's an idea. What if the error message instead said:

* Unknown Firefox Account. Do you want to **migrate your old Add-ons account**?

Which would then link to a hidden migration experience (same a before, but from a non-advertised URL).

Thoughts?

**Comment by mstriemer** [comment]
I don't think we need to do anything special to migrate the account. They just need to register for a Firefox Account with the same email address. I could see something like:

* Unknown Firefox Account. **Sign up** to access your Add-ons account.

But I feel this could be strange for users that don't have an Add-ons account but thought they might have a Firefox Account or just entered the wrong email or something.

This might be generic enough that new users aren't confused and hopefully it prompts the old users to click that **Sign up** link.

**Comment by shane-tomlinson** [comment]
> This might be generic enough that new users aren't confused and hopefully it prompts the old users to click that Sign up link.

Sync users make up 95+% of our traffic and a message about signing up for AMO would cause confusion, so we definitely want to limit any AMO specific messaging to AMO users.

> Unknown Firefox Account. Sign up to access your Add-ons account.

We may serve the stragglers better by putting some messaging in their face before they attempt to sign in:

<img width="437" alt="screen shot 2016-10-21 at 11 55 51" src="https://cloud.githubusercontent.com/assets/848085/19596221/67bdb8fe-9785-11e6-837c-7c3a0d347752.png">


If the user clicks on the link, it takes them to the `/signup` page where the same message is displayed, but without the link:

<img width="433" alt="screen shot 2016-10-21 at 11 55 56" src="https://cloud.githubusercontent.com/assets/848085/19596225/6c939e70-9785-11e6-8f04-1502c225a249.png">

**Comment by vladikoff** [comment]
@shane-tomlinson does this still need feedback from @ryanfeeley ?

**Comment by shane-tomlinson** [comment]
@vladikoff - yup

**Comment by mstriemer** [comment]
Was anything done for this? I don't see a linked PR.

We had someone asking on IRC about how to recover their account this morning so it seems people are still hitting this.

**Comment by vladikoff** [comment]
@ryanfeeley ?

**Comment by ryanfeeley** [comment]
@mstriemer Do users call it AMO?

**Comment by ryanfeeley** [comment]
On unknown account error:
* [RED] Unknown Firefox Account. Sign up using your previous Add-ons account email address to access your Add-ons data.

Always on FxA.AMO registration form:
* [BLUE] Looking for your Add-ons data? Sign up for a Firefox Account with your old Add-ons account email address.

Always on FxA.AMO login form:
* [BLUE] Looking for your Add-ons data? Sign up for a Firefox Account with your old Add-ons account email address.

**Comment by mstriemer** [comment]
Some people refer to it as AMO but I think Add-ons is better, that's what the homepage's heading says. Those messages look good to me.

I might lean towards just including a help link though as that is probably something we can leave around forever. We might want to disable a big blue message if it's mostly irrelevant at some point.

We could potentially pass `help_url=https://mzl.la/2hUjOGH` and that could be displayed in the footer or as "Unknown account. **Need help?**" when the error occurs.

It is quite nice to set the expectation before log in though, I'm happy with either one.

**Comment by vladikoff** [comment]
@shane-tomlinson what do you want to use to "detect AMO"? if name has "Add-ons" in it or something?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson what do you want to use to "detect AMO"? if name has "Add-ons" in it or something?

Mmmm... Seems a bit brittle. I wonder if we can add AMO's client_id as a config value, and when the front end loads, the content server checks the value of client_id against the known AMO client_id and adds a new configuration item into the config meta tag which is then queried by the front-end. That seems like a lot of work since we'd have to make updates to puppet-config, fxa-dev, etc, and that could be prone to error if the amo client_id ever changes.

Another alternative is to use the no longer sent `migration=amo` query parameter. We could use that to indicate "show this special text".

**Comment by vladikoff** [comment]
> Another alternative is to use the no longer sent migration=amo query parameter. We could use that to indicate "show this special text".

Yea param would be better, maybe even `migration=amo_v2` or something. I don't like the client_id approach because those can rotate and are different on every test server / stage

**Comment by vladikoff** [comment]
@mstriemer @shane-tomlinson we need to agree on a param that AMO should send via the sign in / sign up attempts. See above ^

**Comment by mstriemer** [comment]
Sending `migration=amo` again works for me. If it's easier to use something else that's fine too.

**Comment by vladikoff** [comment]
@mstriemer @shane-tomlinson bringing back  `migration=amo` works for me 👍

**Comment by shane-tomlinson** [comment]
@ryanfeeley - In the section `Always on FxA.AMO login form:`, the phrase "Sign up" is used instead of "Sign in", is "Sign up" correct?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yes that was deliberate. The thinking is that the first time an old AMO user sees it, they will think "Oh, I can just make an account with my old AMO data" and the second time they see it, they will remember that they'd made an account. Seem sound?

**Comment by shane-tomlinson** [comment]
> Seem sound?

Yeah, just wanted to make sure!

**Comment by mstriemer** [comment]
Thanks everyone!
