### ISSUE TITLE
Improve device connection dialog with radio buttons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4303]
In order to improve the quality of response, we should present the options are radio buttons, instead of hiding them under a drop-down menu.

DEFAULT:
![disconnect-radio1](https://cloud.githubusercontent.com/assets/68213/19531303/34fa5b88-9605-11e6-801b-a4405ddc2af6.png)

SELECTED:
![disconnect-radio2](https://cloud.githubusercontent.com/assets/68213/19531306/37281576-9605-11e6-8924-2be41667b737.png)

VALIDATION:
![disconnect-radio3](https://cloud.githubusercontent.com/assets/68213/19531308/394dce9a-9605-11e6-9144-24951ff14218.png)

**Comment by ryanfeeley** [comment]
Although they are going to be harder to engineer than originally believed, the radio buttons are from about:addons. ![screenshot 2016-10-19 15 03 17](https://cloud.githubusercontent.com/assets/68213/19533327/456e410c-960d-11e6-9389-85850225a442.png)

**Comment by vladikoff** [comment]
We can extend the fxa-checkbox and include the radio controller form: https://getmdl.io/components/index.html#toggles-section sizes and styling can be tweaked

**Comment by ryanfeeley** [comment]
@vladikoff Howz about:

Reason for disconnecting…
* Suspicious device
* Lost or stolen device
* Old or replaced device
* Duplicate device
* Rather not say
* Other reason (provide text input?)

**Comment by vladikoff** [comment]
latest on this:

* use the new radio button css stuff from nightly, do not bother with the replacing and hiding the radio technique 
* once the new styling stuff is in stable we should remove the fxa-checkbox and just use CSS stuff.
