### ISSUE TITLE
inconsistent screen names when opening verification link from email.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4307]
We have:
- `verify_email`
- `complete_signin`
- `complete_reset_password`

With #4306, we are using the following nomenclature:

`confirm_*`=>`*_confirmed` for the initiating tab.
(verify_email|complete_signin|complete_reset_password) => `*_verified` for the verification tab.

To be consistent with the nomenclature in #4306, I would like to make the following route changes:
- `verify_email` => `verify_signup`
- `complete_signin` => `verify_signin`
- `complete_reset_password` => `verify_reset_password`

We could make corresponding changes on the auth-server/auth-mailer to update the URLs. To avoid breaking any existing links, we can add redirect (301) handlers from the old endpoints to the new endpoints.

cc @philbooth

**Comment by shane-tomlinson** [comment]
I would also like to change the screen name of `confirm` to `confirm_signup` to round out this screen name nomenclature unification.

**Comment by vladikoff** [comment]
from mtg: closing this for now, will reopen if needed
