### ISSUE TITLE
"Account no longer exists" message is displayed for a valid account

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4316]
After an account is deleted, if they attempt to sign in with a different account, we show "Account no longer exists". More details:
https://github.com/mozilla/addons-server/issues/3803#issuecomment-255445538

**Comment by rfk** [comment]
Copying context from the original bug, for easy reference:

"""
Steps to reproduce:
1. Click "Register" link from AMO-stage https://addons.allizom.org/en-US/firefox/
2. Create a new account (go to e-mail and confirm the)
3. Click "Manage Firefox Account... " link from Account Settings page
4. Click "Delete" account button (and confirm)
5. Click "Have an account? Sign in" link from the end of the "Create a Firefox Account" page
6. Delete e-mail and password fields and enter details for an existing account
7. Click "Sing in"

Expected results:
User is redirected to AMO homepage.

Actual results:
The message "Account no longer exists" is displayed.

Notes/Issues:
If the page is refreshed the message "Missing parameter: e-mail" is displayed.
Verified on FF49(Win 7).
"""

And the screen capture from https://github.com/mozilla/addons-server/issues/3803#issuecomment-255445538:

![delete-fxa-error mov](https://cloud.githubusercontent.com/assets/211578/19608884/945f37ac-9799-11e6-83d5-b3b1e36a06e3.gif)

**Comment by vladikoff** [comment]
- backlogging this because we do not get a lot of account deletes
- this happens due to force_auth storing some user data from the Manage view in AMO.

**Comment by shane-tomlinson** [comment]
I suspect this occurs because the click on "Manage Firefox Account" opens the settings page with an email and uid, which is imported into the relier. When the user lands on the force_auth page, that info is still in the relier, the force_auth page checks the uid against the email address, sees they are different, and prints "account no longer exists."

**Comment by shane-tomlinson** [comment]
Ref #5394
