### ISSUE TITLE
Tests: Circle gets rate limited

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4318]
![](https://cloud.githubusercontent.com/assets/128755/18488917/7eb46460-79c9-11e6-9d0d-665f827dde73.png)
![](http://v14d.com/i/580e1ceb79842.png)

Ref: https://github.com/mozilla/fxa-content-server/issues/4128#issuecomment-246801800

**Comment by vladikoff** [comment]
More gmail'ing landed in: https://github.com/mozilla/fxa-content-server/pull/4313 so more may get rate limited.

**Comment by shane-tomlinson** [comment]
Hmm, https://github.com/mozilla/fxa-dev/blob/11d2091e43ce5377c0cab36613864aaf0ede5eee/roles/customs/templates/config.json.j2 is *not* the config being used by fxa-ci's customs-server.

**Comment by shane-tomlinson** [comment]
This happens on latest and stage too.

**Comment by vladikoff** [comment]
- Should we make "@restmail.net" use the button too so we can test this functionality?
