### ISSUE TITLE
Devices: Why is the Refresh button so popular?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4325]
Here's a breakdown of events:

Blue is `screen`.
Orange is `refresh` button clicks. 

![](http://v14d.com/i/580f792f80452.jpg)

The % of clicks vs views was at ~38%. There is a case that some users click it more than once but still. 

My one guess is that the list doesn't load fast enough or is empty, so the users are trying to hit refresh.

cc @ryanfeeley

**Comment by vladikoff** [comment]
Add loading animation to the button when you first open the panel

**Comment by ryanfeeley** [comment]
Related: https://github.com/mozilla/fxa-content-server/issues/4165

**Comment by vladikoff** [comment]
Closing in favour of https://github.com/mozilla/fxa-content-server/issues/4165
