### ISSUE TITLE
failing tests on latest.dev.lcip.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4339]
Last 4 runs, these 3 all fail:

```
4/4 fail - Firefox Desktop Sync v2 reset password - reset password with a gmail address, get the open gmail button
4/4 fail - confirm - sign up with a gmail address, get the open gmail button
4/4 fail - oauth sign_in - verified, blocked, incorrect password
```

The last 2 also consistently fail in stage with train-72.

**Comment by shane-tomlinson** [comment]
> 4/4 fail - confirm - sign up with a gmail address, get the open gmail button
> 4/4 fail - oauth sign_in - verified, blocked, incorrect password

These two failures occurred against fxa-dev boxes when rate limiting kicked in.

**Comment by jrgm** [comment]
the `verified, blocked, incorrect password` will pass if I introduce a 500ms sleep at https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/oauth_sign_in.js#L200

**Comment by vladikoff** [comment]
@shane-tomlinson do we need some view Header check in

```js
        .then(testElementExists('#fxa-signin-unblock-header'))
        .then(fillOutSignInUnblock(email, 0))
        // What view should be here before the path is checked?
        .then(testUrlPathnameEquals('/oauth/signin'))
        .then(fillOutSignIn(this, email, PASSWORD))
```

**Comment by shane-tomlinson** [comment]
@vladikoff - that's exactly what we needed to do, #4341 opened, mind reviewing?
