### ISSUE TITLE
"Unexpected error" after signin on Fx for iOS and verifying on Desktop

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4367]
STR

1) In Fx for iOS, sign in.
2) Open the signin confirmation email in another browser.
3) Look at this:

![image](https://cloud.githubusercontent.com/assets/848085/19977142/f056377a-a1c8-11e6-981f-e5e805fe0712.png)

**Comment by vladikoff** [comment]
I did a test of STR this and things worked correctly:

1st time:

![image](https://cloud.githubusercontent.com/assets/128755/21819623/771e7870-d73a-11e6-8d47-d081f331a684.png)

2nd time: 

![image](https://cloud.githubusercontent.com/assets/128755/21819620/73b0d3e0-d73a-11e6-822f-0afd72373fa7.png)
