### ISSUE TITLE
Add SMS form to the add sync device view

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4373]
![image](https://cloud.githubusercontent.com/assets/128755/20020720/161c946e-a2a9-11e6-936c-58ee52bb1802.png)

![image](https://cloud.githubusercontent.com/assets/128755/20020713/0d8b647e-a2a9-11e6-8fb0-5204078de56a.png)

**Comment by davismtl** [comment]
Did we not have a text above the buttons and below sms field that says: "If you did not receive your download link by sms, you can download Firefox in the following stores from your phone."
(or something like that)

**Comment by davismtl** [comment]
@shane-tomlinson do you know if we will likely go with Twilio for this. I want to make sure legal has time to do a review so that they are not a blocker down the road.

**Comment by rfk** [comment]
I have an open TODO to ask Travis about this

**Comment by davismtl** [comment]
Ok thanks. In the meantime, I have just planted a seed with Brian to let him know what we are planning and that we will shortly submit a bug for legal review.

I also mentioned our end game of an auto-login link so I will see what questions comes back from him.

**Comment by vladikoff** [comment]
Feature doc started here: https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#heading=h.qrbb2drvq5dg

**Comment by vladikoff** [comment]
from mtg: milestone needs to change to Phase 2
