### ISSUE TITLE
this.translator is undefined in "serviceNameTranslator"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4375]
Ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/364074

Also see: https://sentry.prod.mozaws.net/operations/fxa-content-product/?query=translator%20is%20undefined

**Comment by vladikoff** [comment]
@shane-tomlinson I think this is because Config and L10N are started up in parallel:

![image](https://cloud.githubusercontent.com/assets/128755/20110659/391615d2-a5b3-11e6-9348-53104efe287f.png)


`initializeRelier` requires `this.translator` but it might not be set at the time it is called. We should probably move `initializeConfig` out of the `p.all`. Might be even better now because it is not making XHR calls for the config.

![image](https://cloud.githubusercontent.com/assets/128755/20110691/5ec9114e-a5b3-11e6-9739-f737f68497fc.png)

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/2061
