### ISSUE TITLE
We should pass service=$CLIENT_ID when signing certs for oauth logins

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4376]
The content-server currently calls the auth-server's `/certificate/sign` endpoint for two related-but-different reasons:

* To generate assertions for its own use, when e.g. fetching data from profile-server.
* To generate assertions on behalf of an oauth relier, when logging in to that relier.

AFAICT it currently sends `service=content-server` in both cases.  For metrics purposes it would be helpful to distinguish these, by passing `service=$CLIENT_ID` when generating assertions for an oauth login flow.

**Comment by rfk** [comment]
For an example of where this came up, see the "engagement ratio by service" graph:

  https://sql.telemetry.mozilla.org/queries/1598/source

**Comment by philbooth** [comment]
Sorry @rfk, I went to pick this up today but I couldn't find where the "generate assertions on behalf of an oauth relier, when logging in to that relier" bit of code is.

What I can see is that `fxa-client::certificateSign` is only called from `assertion::generate`, which is only called from `account::createOAuthToken`. `createOAuthToken` is called from two places that I can see, in `_fetchProfileOAuthToken` and `models/marketing-email-prefs::_withMarketingEmailClient`. Neither of those appears to be the code I'm looking for.

Can anybody point me in the right direction?

/cc @shane-tomlinson @vladikoff

**Comment by philbooth** [comment]
> Can anybody point me in the right direction?

Mystery solved, @shane-tomlinson pointed me in the right direction on IRC:

```
./models/auth_brokers/oauth.js:      return this._assertionLibrary.generate(account.get
```

My grep-fu was weak and ineffective!
