### ISSUE TITLE
User can close the FxA window in Fx for iOS before `login` message is sent.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4377]
In c04980db, we added a 5 second delay after completing signup/signin before sending the `login` notification to Fx for iOS. We did this so that users would see some messaging that says "go check your email" before Fx for iOS took over the screen and displayed its own messaging.

This delay gives the user a window of opportunity to close the FxA window before the `login` message is sent. If this happens, the browser is none the wiser of the user's login and will never start syncing.

If we can detect the window is about to close, maybe in a `beforeunload` handler, we should send the `login` message immediately.

**Comment by vladikoff** [comment]
I bet `beforeunload` is still not supported in Safari / WebKit iOS so we need some other solution

**Comment by shane-tomlinson** [comment]
> I bet beforeunload is still not supported in Safari / WebKit iOS so we need some other solution

Ugh, I forgot about that. `blur` like you do with event reporting?

**Comment by vladikoff** [comment]
@shane-tomlinson that might also not work because `blur` is then you get out of Safari or switch Safari tabs, in this case the view is destroyed I assume...

**Comment by sleroux** [comment]
Just wanted to check in - is this workaround something we can do prior to Dec 22 (our tentative iOS 6.0 release date) or is it worth going the full phased route as explained in https://bugzilla.mozilla.org/show_bug.cgi?id=1289480?

**Comment by rfk** [comment]
> is this workaround something we can do prior to Dec 22

FWIW I wouldn't count on us getting another deploy out production in that timeframe.  @sleroux ping me tomorrow if you want to discuss what some other options might be.

**Comment by shane-tomlinson** [comment]
I found out today that we can use a `visibilitychange` event to  cause the message to be sent, but the message will only be sent if the user clicks the home button, and I imagine (though have not tested) if the user opens their email client from the notification bar. 

Using `visibilitychange` does *not* help users who click `Settings`, if the user clicks that, no message is ever sent.

**Comment by vladikoff** [comment]
from mtg: 

should we change timeout for train-79?

**Comment by shane-tomlinson** [comment]
> should we change timeout for train-79?

Yes, that's one of 3 patches I'm putting together today to add on to train-79.

**Comment by shane-tomlinson** [comment]
While testing on device, I just realized I made a bone-headed decision when adding the delay - no wonder signin success is so low on iOS. I added the delay for *all* accounts, not just *unverified* accounts. If a user is verified and does not need to go through signin confirmation, the screen just sits there for 5/10 seconds, says "working...", and then if the user hasn't given up, the message is sent the browser does the right thing. This is silly. The `login` message should be sent right away for verified users.

**Comment by vbudhram** [comment]
> The login message should be sent right away for verified users.

Good point, I think originally when we added this, all users went through confirmation so they would always see that screen. Now, user's can potentially bypass confirmation with IP profiling. We should definitely just send the send the `login` message for these users since they are verified already.
