### ISSUE TITLE
Make our cached sign-in screen more password manager friendly

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4388]
I noticed that this page does not work well with my password manager. It won't retrieve the logins until I manually look for them.

about:accounts?action=signin&entrypoint=synced-tabs

![screenshot 2016-11-09 13 12 40](https://cloud.githubusercontent.com/assets/68213/20149278/91100e84-a67e-11e6-8f90-203c6cb2aff8.png)

I think it may be the way we are presenting the email address (although could it be because it's an about:accounts page?)

**Comment by shane-tomlinson** [comment]
The email address is present in a hidden email form element, which worked in the past, perhaps about:accounts interferes like you say. Can you try by just visiting https://accounts.firefox.com/signin and seeing if the same problem occurs?

**Comment by vladikoff** [comment]
Firefox password manager works fine with this but @ryanfeeley actually used 1Password, so that one needs to be tested....
