### ISSUE TITLE
404's  for prod /signup_complete in train-73

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4389]
I see  /signup_complete was removed in https://github.com/mozilla/fxa-content-server/pull/4306. However it appears to still be used by clients, presumably with cached content (or new content on the crossover).

I rolled back to content-server train-72.

**Comment by shane-tomlinson** [comment]
I'm often wrong on these matters but this doesn't make sense, signup_complete was completely bundled into the JS along with everything else. There are no external links directly to the page from anywhere. The only way I know of a user being able to load this page directly is by refreshing while on signup_complete. What am I missing?

**Comment by jrgm** [comment]
Skews somewhat to mobile (android, ios), but covers all platforms.

**Comment by jrgm** [comment]
@shane-tomlinson - let me know how you want to proceed with this.

**Comment by vladikoff** [comment]
Fixed via a PR! Hopefully!
