### ISSUE TITLE
Trying to Log in with a new account from a new tab will redirect the user to Firefox Accounts page

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/fxa-content-server#4400]
This is a follow up to https://github.com/mozilla/addons-server/issues/3987

Steps to reproduce:

1.Log in with valid credentials.
2.Log out.
3.Select Log in again.
4.In the Sign in page hover over “Use a different account” and open it in a new tab.

Expected results:
The Sign in page is displayed.

Actual results:
The Firefox Accounts page is displayed and the user is signed in.

Notes/Issues:
Verified on FF49.0.2(Win 7 64-bit).
Clicking it on “Use a different account” will redirect the user to the Sign in page.
Here is a video for this issue: 
![animation](https://cloud.githubusercontent.com/assets/15885467/20208042/11b94e62-a7f4-11e6-8bf6-4dd7da233f02.gif)

**Comment by rfk** [comment]
>  2.Log out.
> [...]
> Actual results:
> The Firefox Accounts page is displayed and the user is signed in.

I guess part of the problem here is the disconnect between AMO and FxA login state.  The "log out" above is logging our of AMO, but you remain signed in to FxA.

**Comment by rfk** [comment]
>  4.In the Sign in page hover over “Use a different account” and open it in a new tab.

Nonetheless, I do agree that this is a bug, and opening in a new tag should "do the right thing" as much as possible.

**Comment by vladikoff** [comment]
This was fixed in https://github.com/mozilla/fxa-content-server/issues/4584 Thanks for the report!

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF54.0a1 (Wind 7 64-bit).
Postfix video:
![logg](https://cloud.githubusercontent.com/assets/15885467/23249778/b1af48c0-f9ae-11e6-8bc9-a684348df12c.gif)
