### ISSUE TITLE
Functional tests needed for IP profiling feature

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4401]
Ref #4399, https://github.com/mozilla/fxa-auth-server/pull/1525.

With the new IP profiling feature, users that sign in for Sync from the same IP address within one day do not need to go through signin confirmation. We should add tests for this.

**Comment by vbudhram** [comment]
@shane-tomlinson 👍, as a side note, the auth-server will need to be updated to support a exact time frame for ip-profiling since it uses keywords `day, week, month, old` as date ranges.

https://github.com/mozilla/fxa-auth-server/blob/63673ffd74faedaf7d2a626cfc620b563d598b5f/lib/routes/account.js#L544.

**Comment by rfk** [comment]
Stepping back, I think it's reasonable to expect that the logic for choosing when to send a confirmation email will continue to evolve.  Are we setting ourselves up for lots of churn in the functional tests here, updating them in lock step with every change to the auth-server?

I wonder if we could make the sign-in confirmation "optional" in the functional tests, e.g. after logging in, look to see whether sign-in confirmation was required, complete it if so, and ignore it if not.

**Comment by shane-tomlinson** [comment]
> after logging in, look to see whether sign-in confirmation was required, complete it if so, and ignore it if not.

This would be a nightmare due to the number of ways a user can verify: new tab same device with original tab open, new tab same device with original tab closed, same tab same device, different device with the original tab open, different device with original tab closed. Conditional logic for each would end up being a mess, and I don't want to eliminate any of the tests because each scenario occurs in real life.

Based on your feedback, I think we should have two distinct sets of sets:

1. User must go through signin confirmation.
2. User does not need to go through signin confirmation.

The good news is, we already have both sets of tests! The bad news is a change to the auth server may be needed to get them running again. The auth server has signinConfirmation.enabledEmailAddresses with the documentation `If feature enabled, force sign-in confirmation for email addresses matching this regex.` We use this to force particular email addresses through signin confirmation in the functional tests. fxa-dev boxes set this value to ["^(sync.*@restmail\\.net|.+@mozilla\\.com)$"](https://github.com/mozilla/fxa-dev/blob/master/roles/auth/templates/config.json.j2#L29).

With IP profiling, it looks like signinConfirmation.enabledEmailAddresses is ignored because 
[features.canBypassSigninConfirmation](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L594) does not take into account whether signin confirmation is forced for the given email address. 

My new proposal is we modify auth-server behavior to bring back configurable forced signin confirmations even if the user has signed in within the last 24 hours.

**Comment by vbudhram** [comment]
> With IP profiling, it looks like signinConfirmation.enabledEmailAddresses is ignored because
features.canBypassSigninConfirmation does not take into account whether signin confirmation is forced for the given email address.

I could argue that might be a bug and should be fixed. Users who are forced into confirm sign-in, should probably not have a way to bypass it.

**Comment by shane-tomlinson** [comment]
> I could argue that might be a bug and should be fixed. Users who are forced into confirm sign-in, should probably not have a way to bypass it.

He, I'm glad we came to the same conclusion.

**Comment by seanmonstar** [comment]
> I could argue that might be a bug and should be fixed. Users who are forced into confirm sign-in, should probably not have a way to bypass it.

I wouldn't have assumed it's a bug based on the field naming. `enabledEmailAddresses` means to me that those addresses *can* have the feature enabled, but if other conditions aren't met, the name doesn't imply they are forced.

**Comment by rfk** [comment]
I agree, it's badly named and `forceEmaiLAddresses` or similar would be better.

**Comment by shane-tomlinson** [comment]
This has been addressed by @seanmonstar and @vbudhram in https://github.com/mozilla/fxa-auth-server/pull/1554, closing.
