### ISSUE TITLE
Audit .nsprc

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#4410]
It looks like we can possibly remove oodles of entries from the .nsprc file:

This seems to be the minimum:

```js
{
  "exceptions": [
    // uglify-js
    "https://nodesecurity.io/advisories/39",
    "https://nodesecurity.io/advisories/48",

    // negotiator
    "https://nodesecurity.io/advisories/106"
  ]
}
```

**Comment by TDA** [comment]
I can take this up! (and I promise I will actually finish it this time)

**Comment by vladikoff** [comment]
@TDA don't worry about this one, thanks though!

**Comment by pdehaan** [comment]
Ref #4416
