### ISSUE TITLE
Validate the utm_* parameters before emitting flow events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4415]
We already do this for `context`, `entrypoint`, `migration` and `service` but we should add it for `utm_*` too.

They should be validated slightly differently though, as they are not values which we are wholly in control of. Instead we should drop any invalid parameters and let the event itself be emitted with the remaining data.

**Comment by philbooth** [comment]
IIRC, consensus was to permit alpha-numeric, hyphen, underscore, period and then valid URI characters.

**Comment by vladikoff** [comment]
Yea, agreed, I don't think we want to have a set of list of these.

**Comment by philbooth** [comment]
Also, we can drop `utm_term` from the payload entirely.

**Comment by shane-tomlinson** [comment]
The relier models only check whether the values are strings, having consistency in the validation between the front and backends would be awesome.

https://github.com/mozilla/fxa-content-server/blob/d082a4070e942fec0f43a66c49f1514aef87019c/app/scripts/models/reliers/relier.js#L49
