### ISSUE TITLE
Device name inaccurate

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4423]
My device name is not accurate. Could this be related to the fact that I use the same profile in Firefox and Nightly on the same computer? (never simulaneously)

![pasted_image_at_2016_11_17_03_30_pm](https://cloud.githubusercontent.com/assets/68213/20406965/7741d054-acdd-11e6-89dc-33f3a4b34861.png)

**Comment by rfk** [comment]
"Firefox 53, Mac OSX 10.11" looks like a synthetic devicename created by the auth-server; are those the only three devices in your account?

**Comment by ryanfeeley** [comment]
Full list (many duplicates though) 
<img width="538" alt="screenshot 2016-11-17 15 56 08" src="https://cloud.githubusercontent.com/assets/68213/20407223/689ce114-acde-11e6-9012-85adeac16e3b.png">

**Comment by rfk** [comment]
I'm guessing the duplicates here are due to you having to sign back in to sync multiple times on this device?

**Comment by rfk** [comment]
(And what I suspect is that the "current device" here is not actually your current device, but some other sessionToken that's been left around and somehow got a placeholder device record synthesized for it.  Bleh...)

**Comment by rfk** [comment]
@ryanfeeley sorry, I lost track of this one a little.  Are you still seeing this behaviour?  If so, could you please remind me what's wrong with the device name?  Is it just that it's not reporting the custom device name from your device, or is the Firefox or OS version information also incorrect?

**Comment by vladikoff** [comment]
Please reopen if you see it happen again...
