### ISSUE TITLE
Unescaped HTML entity on French login page

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#4427]
Received reports about this unescaped `&nbsp;` entity in the “Forgot password?” string, which was previously displayed correctly.

<img width="453" alt="capture d ecran 2016-11-18 a 12 56 58" src="https://cloud.githubusercontent.com/assets/1294206/20430945/35527f56-ad8f-11e6-9643-1e89ceda8c01.png">

I replaced the entity with the UTF-8 character in the translation https://pontoon.mozilla.org/fr/firefox-accounts/LC_MESSAGES/client.po/?search=Mot+de+passe+oubli%C3%A9%C2%A0%3F&string=134227
But you might want to check what went wrong :)

**Comment by shane-tomlinson** [comment]
Thanks @TheoChevalier! with #4296, all DOM writes are HTML escaped by default to help prevent XSS. We didn't expect an HTML character code in that string, so it's escaped.

So that we have a record to point others to, what is the UTF-8 character sequence you used to replace `&nbsp;`?

**Comment by shane-tomlinson** [comment]
@jrgm or @jbuck - Are there any "easy" remedies we can use to fix this string on prod?

**Comment by TheoChevalier** [comment]
@shane-tomlinson I used 'NO-BREAK SPACE' (U+00A0)
