### ISSUE TITLE
Add "Duplicate device" option to reason for disconnecting

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4429]
Add "Duplicate device" option to reason for disconnecting just above "Rather not say"
<img width="458" alt="duplicate" src="https://cloud.githubusercontent.com/assets/68213/20446801/6d286d5e-ada9-11e6-92a0-5598347edeba.png">

**Comment by ryanfeeley** [comment]
@davismtl Apparently the majority of users are saying "Rather not say"... I am guessing once we add a "Duplicate device" option, it will take a bug chunk of those.

**Comment by davismtl** [comment]
Interesting. That makes a lot of sense.
Do we have an issue filed to add that as an option?

**Comment by vladikoff** [comment]
from mtg: @ryanfeeley `Can we have an "other..." option as well?`

**Comment by ryanfeeley** [comment]
@philbooth Perhaps once we move to radio buttons, we can achieve this with fewer options. By default we can leave all the radio buttons deselected, but allow the user to submit without selecting a reason. This makes giving a reason voluntary (note that the duplicate item is missing in this mockup)
![devices-radio-copy-2](https://cloud.githubusercontent.com/assets/68213/20500192/81034014-b002-11e6-8339-473749bd89d6.png)
