### ISSUE TITLE
lib/service-name.js - it only translates "Sync", is it really needed?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4436]
We added [lib/service-name.js](https://github.com/mozilla/fxa-content-server/blob/eb79afcd3d36a9d2bda1e95d13fa19892a1901b9/app/scripts/lib/service-name.js) to translate service names before we supported OAuth. The only service name it translates is sync. Has this abstraction outlived its usefulness? Should it be killed off?

ref https://github.com/mozilla/fxa-content-server/issues/4375

**Comment by vladikoff** [comment]
Seems like no locales translated the service name anyway https://github.com/mozilla/fxa-content-server-l10n/blob/a7cf1dd4942ab6ecab7a2219a9ffd985350c8c70/locale/th/LC_MESSAGES/client.po#L459 

so probably kill it,  yes.
