### ISSUE TITLE
unit tests only pass if default language is english

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4437]
ref https://github.com/mozilla/fxa-content-server/issues/4375

STR
1. Set browser's locale to something we support that's not English (or any of its variants).
2. Run the frontend unit tests.

Check this not-awesomeness out:

<img width="768" alt="screen shot 2016-11-22 at 15 54 45" src="https://cloud.githubusercontent.com/assets/848085/20530681/0f09c7d8-b0cc-11e6-8fdd-7485622310c4.png">

**Comment by vladikoff** [comment]
from mtg: 

* force the translator to always be English 
* or find another way to fix this..

**Comment by vladikoff** [comment]
@shane-tomlinson i looked at this a bit. with the current code 

```js

  const Translator = function () {
  };

  Translator.prototype = {
    // In dev mode, this will request localized translations.
    // In prod mode, this will be replaced with the actual translations.
    // `__translations__` is used in hopes that it's a slight bit less likely
    // than `translations` to be used in another module, a collision would
    // bork the build.
    // DO NOT EDIT BELOW HERE W/O CHECKING LOCALIZED BUILDS
    __translations__: JSON.parse(require('text!/i18n/client.json')),
    // DO NOT EDIT ABOVE HERE W/O CHECKING LOCALIZED BUILDS

    set (translations) {
      this.__translations__ = translations;
    },
```

we rely on Accept-Language and i cannot pass a query param into the `require` statement to override.

One way we can fix this issue in tests is by calling:
```
      translator = new Translator();
      translator._clearTranslationValues();
```

`_clearTranslationValues` would set all values of every key in loaded translations to null, then the tests will always use English strings.

Would that work ?

**Comment by shane-tomlinson** [comment]
@vladikoff - doh, now I see the error of my ways. This should have been obvious. Your suggestion seems like it'd work just fine and dandy.
