### ISSUE TITLE
Should external links be converted to text on Fennec?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4448]
I noticed this while testing https://github.com/mozilla/fxa-content-experiments/pull/48.

External links are [converted to text in the "fennec_v1" broker](https://github.com/mozilla/fxa-content-server/blob/819f098bc4dfaaadb86641dc754003fee96aaa5e/app/scripts/models/auth_brokers/fx-fennec-v1.js#L31). 

![screenshot_20161124-114421](https://cloud.githubusercontent.com/assets/848085/20598819/e6c18b94-b242-11e6-9e68-bb71bd8e7f71.png)

I'm not sure why, because Fennec opens about:accounts instead of native UI. about:accounts *should* allow external links to be opened w/o a problem.

Testing now....

**Comment by shane-tomlinson** [comment]
cc @ncalexan

**Comment by shane-tomlinson** [comment]
The new "Why is this happening?" link works as expected because it contains a `target="_blank"` attribute, the ones in the TOS/PP agreements do not. Perhaps links in the TOS/PP agreement should add a `target` as well. 

cc @ryanfeeley

**Comment by vladikoff** [comment]
> about:accounts should allow external links to be opened w/o a problem.

It would show "offline" for direct links: https://github.com/mozilla/fxa-content-server/issues/3637

**Comment by shane-tomlinson** [comment]
> It would show "offline" for direct links: #3637

Yeah, that's what I saw with the TOS/PP, but everything seems to work as expected with a `target=_blank` attribute.

**Comment by ncalexan** [comment]
> I'm not sure why, because Fennec opens about:accounts instead of native UI. about:accounts should allow external links to be opened w/o a problem.

To the best of my knowledge, external links like this will Just Work.  Easy to test: with the Remote Debugger, you can hack up the DOM content as much as you like.
