### ISSUE TITLE
Age input does not accept input on Windows Surface

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4450]
A friend showed me Firefox on his Windows Surface tablet yesterday. I immediately tried to sign in to Sync to see if it would work. Unfortunately the age input would not accept any characters, blocking all attempts at registration. I saw this a couple months ago on an older version of Firefox at the library. I would like this field to be given some serious cross-platform QA, because it seems to be a very fragile link in our sign-up flow.

**Comment by shane-tomlinson** [comment]
> I would like this field to be given some serious cross-platform QA,

Can someone buy me a Windows Surface tablet?

**Comment by vladikoff** [comment]
@ryanfeeley i think there is a Surface at the office, could you see if it works on http://www.quirksmode.org/html5/inputs/tests/inputs_numbers.html ?

**Comment by shane-tomlinson** [comment]
More info needed, works fine on the surface tablet we have here with both keyboard attached and without.

![20161124_151711](https://cloud.githubusercontent.com/assets/848085/20603537/dc2e96b0-b259-11e6-8a01-6813ab5df849.jpg)

The biggest problem is in landscape mode, the virtual keyboard hides part of the input and it's not possible to scroll to make the age input visible.

![20161124_152018](https://cloud.githubusercontent.com/assets/848085/20603545/e8c47610-b259-11e6-803a-6e44ad228781.jpg)

**Comment by ryanfeeley** [comment]
This is the same screen keyboard, although I had initated it with a stylus.

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson Did some digging in DataDog, looks like this is a Windows 7 issue. 
![screenshot 2016-11-25 16 01 21](https://cloud.githubusercontent.com/assets/68213/20635244/92218eb8-b328-11e6-80b9-93206321bd3c.png)

**Comment by vladikoff** [comment]
Works fine with touch or stylus here as well

![](http://v14d.com/i/583da9547dd85.jpg)
