### ISSUE TITLE
How should a Surface table show up in the device list?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4460]
You can see from this photo it's currently considered a desktop device:

![20161125_174632](https://cloud.githubusercontent.com/assets/848085/20632703/7413fe38-b337-11e6-8c91-b0503a6ae45c.jpg)

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@shane-tomlinson Laptop icon seems fine. Instead of a blank line below, what kind of user agent string do we have access to? Something human readable?

**Comment by shane-tomlinson** [comment]
> Instead of a blank line below, what kind of user agent string do we have access to? 

We have no UA string at that point, UA strings are not stored. @philbooth would know more since he developed the backend portion.

**Comment by philbooth** [comment]
> We have no UA string at that point, UA strings are not stored. @philbooth would know more...

That's correct, we don't store the user-agent string, just the result from parsing it.

So, for user agent strings that could be parsed, we also have the following fields available to display:

* browser
* browser version
* OS
* OS version

Depending on the string, some or all of those fields may not be set.

The only time we store the user agent string is if it could not be parsed and the device name is not set (so it's probably a placeholder device record). In that case, we store a (possibly truncated) copy of the string for the device name.

IIRC, the main argument against storing the whole user agent string every time was legal approval / PII.

**Comment by vladikoff** [comment]
I was just checking this stuff on Surface Gen 1 and there is nothing in the UA indicating that it is a Surface device. (Nothing in the "Device Name" either).

**Comment by ryanfeeley** [comment]
Instead of a blank line, can we show:
 {browser} {browser version} on {OS} {OS version}

e.g. Firefox 51 on OS X 10.11.6
