### ISSUE TITLE
Changing password with incorrect email capitalization will brick your password

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4463]
Steps to reproduce:

* Create an account, say "example@gmail.com"
* Sign out, and sign back in with different email capitalization, say "Example@gmail.com"
* Wait 15 minutes and/or restart memcached, to avoid the aggressive rate limited identified in https://github.com/mozilla/fxa-auth-server/issues/1570
* Change your password
* Sign out, and try to sign back in

Expected result:

* I should be able to sign back in using the password I just set.

Actual result:

* I can't sign in.

The problem is in this "password change" flow: https://github.com/mozilla/fxa-js-client/blob/master/client/FxAccountClient.js#L828

When it calls `/password/change/start`, it detects that you entered a different email capitalization, and retries the request with the original capitalization stored on the account.  But when it calls `/password/change/finish` to set the new `authPW`, it uses the capitalization you entered at login, not the canonical one.  In other words, the value of `email` on this line:

  https://github.com/mozilla/fxa-js-client/blob/master/client/FxAccountClient.js#L844

Does not get updated to reflect the proper capitalization.  It calculates a bogus value for `authPW` and then stores that on the account.

The result is that you can no longer log in to the account:

* If you try to login using the original capitalization, then your calculation of `authPW` will not match what's on the server, and the login will be rejected.
* If you try to login using a different capitalization, then the server will reject it with an "incorrect email case" error.

ISTM the quick fix here is to change the js-client, so that it propagates the updated email address through the whole password-change flow.  But there may be other edge-cases here that we need to think through.

**Comment by rfk** [comment]
>  ISTM the quick fix here is to change the js-client, so that it propagates the
> updated email address through the whole password-change flow.

Alternately, we need to reflect the canonical email capitalization in the `Account` and `User` models, rather than keeping the capitalization that the user entered at login.

**Comment by rfk** [comment]
Resetting the password does seem to fix the problem though.  Fortunately the password-reset email gets sent using the canonical capitalization, so when you re-set `authPW` through that flow, you're using the right value.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/3893

**Comment by vladikoff** [comment]
@shane-tomlinson also see https://github.com/mozilla/fxa-content-server/issues/3893
