### ISSUE TITLE
Two "merge warnings" can be displayed to the user

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4474]
Follow on from https://github.com/mozilla/fxa-content-server/pull/4472.

STR
1. Using local dev w/ #4472 applied, create 2 accounts, a@a.com and block123@restmail.net (case is important)
2. Sign in for Sync using a@a.com
3. Sign out, sign in for Sync using BLOCK123@restmail.net

![two-merge-warnings](https://cloud.githubusercontent.com/assets/848085/20706814/fa004092-b620-11e6-806c-5d23ad514269.gif)

This only happens if a user is blocked AND tries to sign in with an unnormalized email address.

**Comment by vladikoff** [comment]
@shane-tomlinson any possible solutions come to mind?

**Comment by shane-tomlinson** [comment]
We [could compare the emails in all lowercase in the fx-sync broker](https://github.com/mozilla/fxa-content-server/blob/0c89b9a933e18bcd4163d4584c0f129c4432c969/app/scripts/models/auth_brokers/fx-sync.js#L87), I'm wondering if that opens any strange security holes or unexpected behavior.

**Comment by shane-tomlinson** [comment]
Another option is to sign in the user, get the canonical form from the auth-server, send the request to the browser. If the user cancels, sign out the user. That feels gross, and like it leaves a lot of room for dangling sessions.

**Comment by vladikoff** [comment]
@shane-tomlinson how about fixes in the Firefox Client?

**Comment by vladikoff** [comment]
from mtg: closing for now, unless the issue comes back
