### ISSUE TITLE
Send metricsContext payload to /account/reset

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4477]
With train-74 out the door, we've got our first set of password-reset-related flow events coming in.  Taking a look at the available metrics, it looks like the flow_id is not correctly preserved across the password-reset email loop.

I see some flows like this, that stop at `flow.reset-password.submit`:

```
 5d9d9b8   |         0 | flow.signup.begin
 5d9d9b8   |     11804 | flow.signup.have-account
 5d9d9b8   |     13614 | flow.signin.forgot-password
 5d9d9b8   |     15580 | flow.reset-password.engage
 5d9d9b8   |     22426 | flow.reset-password.submit

 669e3fd   |         0 | flow.signin.begin
 669e3fd   |      3040 | flow.signin.engage
 669e3fd   |     19239 | flow.signin.submit
 669e3fd   |     61361 | flow.signin.forgot-password
 669e3fd   |     62864 | flow.reset-password.engage
 669e3fd   |     73662 | flow.reset-password.submit

```

And I see some flows that appear to start at `flow.complete-reset-password.engage`:

```
 151aacd   |         0 | flow.signin.begin
 151aacd   |     25916 | flow.complete-reset-password.engage
 151aacd   |     32227 | flow.complete-reset-password.submit

 1d1eca6   |         0 | flow.signin.begin
 1d1eca6   |     27686 | flow.complete-reset-password.engage
 1d1eca6   |    111100 | flow.complete-reset-password.submit
 1d1eca6   |    256511 | flow.signin.engage
 1d1eca6   |    281022 | account.login
 1d1eca6   |    281042 | flow.signin.submit
 1d1eca6   |    281238 | flow.signin.attempt
 1d1eca6   |    322054 | account.keyfetch
 1d1eca6   |    322478 | account.signed
 1d1eca6   |    322478 | flow.complete
```

But at first glance, I don't see any that successfully traverse a password reset and succeed at logging in.

**Comment by rfk** [comment]
The link in my email out to /complete_reset_password does have the correct flow_id in its resume token, and it is included when the page calls /verify_code.  But it *doesn't* seem to be included when the page submits client-side metrics via /metrics for some reason.

**Comment by rfk** [comment]
I'd also be expecting to see server-side events like `password.forgot.send_code.start` in these flows [1] but I can't see any such events in redshift.

[1] https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/password.js#L352

**Comment by rfk** [comment]
I started a basic password-reset funnel here:

  https://sql.telemetry.mozilla.org/queries/1825/source#3240

It looks like around 20% of password-reset attempts end up completing.  It's not immediately clear whether some are completing but we're not getting the metrics on it.

@philbooth any idea why the server-side password reset events might not be coming through?

**Comment by philbooth** [comment]
> @philbooth any idea why the server-side password reset events might not be coming through?

Hmm, can't think of any off the top of my head, but I'll dig into it now.

**Comment by philbooth** [comment]
So it turns out the metrics context payload isn't propagated to `/account/reset`, where we need it to call `stash` against the returned tokens. And because that endpoint does not expect the payload yet, we'll have to wait a train for it to ship in the auth server before we can come back to fix it here and in `fxa-js-client`.

Leaving this open until then.

**Comment by rfk** [comment]
In the linked auth-server PR I see log lines like:

```
flowEvent {"event":"password.forgot.send_code.start","userAgent":"Firefox-iOS-FxA/5.3 (Firefox)","time":1480511151787,"flow_id":"9d0437d21a3bdc251549f65814521325b8beee05326b7870723532a9a25444d0","flow_time":7096,"service":"sync"}
```

But these don't appear to be making it through to the redshift database.  Should they have shipped in train-74?

**Comment by philbooth** [comment]
> `password.forgot.send_code.start` ... these don't appear to be making it through to the redshift database. Should they have shipped in train-74?

Firstly, apologies. I only skim-read this issue then rushed off to fix it, so missed the comment about those events. They actually part of train 73 so something else is definitely wrong too. Investigating now.

**Comment by philbooth** [comment]
> They were actually part of train 73...

Wait, no, they weren't. The updated `fxa-js-client` for that change never got pulled into the content server. So that means they were first brought in with the update to remove the extended metrics context data in 01e06a5b59d2dafab56b788df50429612b054095, which ships in train 75.
