### ISSUE TITLE
clicks on app store buttons not recorded if metrics already flushed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4479]
Found this while testing #4370

STR

1. Sign up FxA for Sync, verify in Firefox Desktop.
2. Blur the window to cause metrics to be sent.
3. In the console, look for the app store metrics with `"clicked": false`.
4. Click an app store link.
5. No new metrics reported for link. Wah wah.

Contrast this with:

1. Sign up FxA for Sync, verify in Firefox Desktop.
2. Click an app store link.
3. In the console, look for the app store metrics with `"clicked": true`.

![no-metrics-click-recorded](https://cloud.githubusercontent.com/assets/848085/20755863/6abede96-b708-11e6-8ef0-5b5805f6a05c.gif)

**Comment by philbooth** [comment]
From the meeting, maybe the click should be an event in its own right.

**Comment by vladikoff** [comment]
from mtg: @vladikoff and @shane-tomlinson to chat about this ...
