### ISSUE TITLE
Device names are under the "Disconnect" button in RTL languages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4480]
Found by @ryanfeeley:

![device-manager-in-arabic.png](https://irccloud.mozilla.com/file/0bS97r10/Screenshot%202016-11-30%2010.57.20.png)

**Comment by vladikoff** [comment]
Related: https://github.com/mozilla/fxa-content-server/issues/4413

**Comment by ryanfeeley** [comment]
Should RTL look more like this? <img width="558" alt="screenshot 2016-11-30 10 57 20" src="https://cloud.githubusercontent.com/assets/68213/20770059/5eb4e690-b712-11e6-9d00-96cdf26e04e2.png">

**Comment by shane-tomlinson** [comment]
@mohamed7afezz - pardon the message out of the blue, you helped us get our RTL story in order a few months back. If you have a few mins, I'd like to get your input since none of us are RTL readers by default. Does the above proposed change follow RTL best practices? Is there anything we should modify/improve?

**Comment by mohamed7afezz** [comment]
Hi @shane-tomlinson 
It's my pleasure to help with you and plz feel free to ping me any time.
All above RTL look fine and very organized. I just recommand to float "Missing or duplicate items?" message right to be under list of client name.

**Comment by shane-tomlinson** [comment]
Also filed in Bugzilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1324832
