### ISSUE TITLE
Move email verification from client to server

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4482]
> When a user gets a "verify account" email and navigates to it we should use the fxa-content-server *server* to perform the verification instead of front-end app. 

Here's the current logic "front-end" logic: https://github.com/mozilla/fxa-content-server/blob/9cbf5d91dea1e871251ffccdbdda1db6d06cb2c8/app/scripts/lib/fxa-client.js#L338

and https://github.com/mozilla/fxa-js-client/blob/746abf79745d9825c1f0f180d15519e1983ca95f/client/FxAccountClient.js#L269

The server should perform the same request as the fxa-js-client request above ^. (use the auth url from config, stored in https://github.com/mozilla/fxa-content-server/blob/master/server/lib/configuration.js#L155 )
 
Ref: https://github.com/mozilla/fxa-content-server/pull/4476#issuecomment-263918584

**Comment by vladikoff** [comment]
TODO (first attempt at this): 

* Intercept the /verify_email url call (URL provided to you in the email or mail_helper) by creating a new route handler. See example linked below for a custom route handler....
* use the `got` request library to make a request (example: https://github.com/mozilla/fxa-content-server/blob/f9006d4e0042002c3f5624e6c626130601c8da22/server/lib/routes/post-metrics-errors.js#L8 and https://github.com/mozilla/fxa-content-server/blob/f9006d4e0042002c3f5624e6c626130601c8da22/server/lib/routes/post-metrics-errors.js#L68
 
* After verification on the server show the normal "Verified" view of the front-end app. Check what changes are required on the front-end to avoid errors...

After: 

* Implement a TIMEOUT value
* Log verification errors to Sentry...

**Comment by shane-tomlinson** [comment]
Re-opening since we removed server side verification due to rate-limiting.

**Comment by shane-tomlinson** [comment]
I can imagine us getting around the rate limiting by using a shared secret between the customs and content servers.

We also have to consider how to handle marketing email-opt ins. A flag is sent to /verify_email when doing [client side verification](https://github.com/shane-tomlinson/fxa-content-server/blob/4ff4dffa97c1b522be2c3f8eefa4ce8d50848bed/app/scripts/models/account.js#L599), but AFAICT we lost this with [server side verifiation](https://github.com/shane-tomlinson/fxa-content-server/blob/4ff4dffa97c1b522be2c3f8eefa4ce8d50848bed/server/lib/routes/get-verify-email.js#L88).
