### ISSUE TITLE
Make authorization codes case-insensitive

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4483]
STEPS TO REPRODUCE
Log in until you need an authorization code
Enter authorization code in lower-case

EXPECTED RESULTS
Code is case-insensitive, and authorization is granted

ACTUAL RESULTS
Code is case-sensitive, and authorization is denied

**Comment by rfk** [comment]
Are you sure case-sensitivity was the problem?  I tried this and was not able to reproduce, entering the code in lower case worked fine.

**Comment by shane-tomlinson** [comment]
authorization code comparisons are case-insensitive, all unblock codes are [converted to uppercase](https://github.com/mozilla/fxa-auth-server/blob/505b6271b0fdd0dd9147b04dec2430369a59d584/lib/routes/account.js#L447) by the server [before comparison](https://github.com/mozilla/fxa-auth-server/blob/505b6271b0fdd0dd9147b04dec2430369a59d584/lib/routes/account.js#L463).
