### ISSUE TITLE
Content needed for "Why is this required?" link

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4485]
For the link at the bottom:

<img width="305" alt="screen shot 2016-12-01 at 14 51 40" src="https://cloud.githubusercontent.com/assets/848085/20798152/c3bfec1a-b7d5-11e6-9488-aab7efdb2857.png">

**Comment by ryanfeeley** [comment]
Copy in the style of the the disconnect dialog (no close button)

> ### Why does it take two to tango?
> To work fully, Sync needs Firefox running on two or more devices. If you just want to use it to back up one device, you can never reset your password. All of your data is encrypted with your password, so resetting it means erasing your data from our servers.

**Comment by vladikoff** [comment]
from mtg: @shane-tomlinson reassigned to you, we got the content from Ryan

**Comment by shane-tomlinson** [comment]
This has been rolled into #4370, closing here. Thanks @ryanfeeley for the content!

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson Thinking of mobile last (!), do you think this needs a "Got it" button at the bottom in our primary style?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - YES!! Clicking "anywhere" is kindasortanotdiscoverable.

**Comment by ryanfeeley** [comment]
Moreshortened @shane-tomlinson:

**Why sync multiple devices?**
The Sync service isn’t a permanent backup, it’s simply a secure way to transfer saved bookmarks, history and passwords between your own devices. You should install Firefox and sync at least two devices to protect against losing your data if you forget your login or reset your password.
