### ISSUE TITLE
Avatar chooser positioned out of view on mobile

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4491]
Likely a fixed positioning issue, the avatar chooser appears almost entirely off screen on an iPhone 5S, likely Android too.

STEPS TO REPRODUCE
1. On an iPhone, visit accounts.firefox.com/settings
2. In Account picture section, click Change… button

EXPECTED RESULTS
- Avatar chooser opens and is centred in view

ACTUAL RESULTS
- Avatar view is out of view

Not manty users see this, but I wanted @davismtl to know.

![2016-12-02 10 31 39](https://cloud.githubusercontent.com/assets/68213/20990782/ccf03224-bc7e-11e6-8c97-dfd2fd24538b.png)

**Comment by vladikoff** [comment]
Cannot be reproduced easily (in the simulator at least):

<img src=http://v14d.com/i/584b02fdbf77a.jpg width=250 />

**Comment by ryanfeeley** [comment]
@vladikoff I had @jacklin-ux (who needs to be added to this repo) try in Android and it was fine. It's on my iPhone 5S for sure.

**Comment by rfk** [comment]
> @jacklin-ux (who needs to be added to this repo) 

He should have an invite to the fxa github teams, but he'll need to go in and confirm the invite before he can access the repo.
