### ISSUE TITLE
Password input length-limited on some platforms?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4496]
In https://www.reddit.com/r/firefox/comments/5f6mn6/invalid_authorization_code_sync_signin/dayvjbb/ as user reports difficulty in signing in with a really long password:

"""
Recently I changed password to the realy long one. As I can see, there is a limit in FFox x64 version on linux. and I can't even type in all chars.
"""

I'm able to enter > 250 characters in the password field and submit successfully, but I wonder if there might be platform-specific issues at play here.  Anyone able to test on FFox x64 on linux to see if it reproduces there?

**Comment by shane-tomlinson** [comment]
Password should not be length limited, we don't do any. If any is done, that sounds like it would be a platform issue.

**Comment by vladikoff** [comment]
Tested on Linux x64 Stable and Nightly with a long password of `qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890qwertyuiopasdfghjklzxcvbnm,.12345678901234567890`

and was able to login. 

**I think this user basically confused the "Authorization Code input" with the "Password Input"**
