### ISSUE TITLE
User cannot login/register on AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa-content-server#4497]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/ in you Firefox browser
2. Log in/Register with valid credentials 

Expected results:
User is logged in with success.

Actual results:
User is not logged in or registered. An "Unexpected error" message is displayed.

Notes/Issues:
"500" error code is displayed in the console.
Verified on FF50(Win 7). Issue is only reproducing on AMO-dev.
Screenshots for this issue: 
![login_001](https://cloud.githubusercontent.com/assets/15685960/21092921/c3296396-c057-11e6-99a5-d88f324c6ef1.png)
![register](https://cloud.githubusercontent.com/assets/15685960/21092924/c78754a2-c057-11e6-919c-b4067b76306d.png)

**Comment by vladikoff** [comment]
We had some DB issues, should work now....

Ref: https://github.com/mozilla/fxa-auth-server/issues/1590

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7) - while logging with FxA, user is logged with success on AMO.
Postfix screenshot: 
![2016-12-14_1021](https://cloud.githubusercontent.com/assets/15685960/21174696/590c35ce-c1e7-11e6-9228-7f70fff6bf3a.png)

**Comment by ValentinaPC** [comment]
Issue is reproducing again.
Verified on AMO-dev FF50(Win 7) at Log in and Register.
Please see the screenshots:
![create](https://cloud.githubusercontent.com/assets/15685960/21182957/51b52444-c20e-11e6-8823-fa8e11cce2e5.png)
![-dev](https://cloud.githubusercontent.com/assets/15685960/21182958/51b60300-c20e-11e6-9a04-a01e7b0927a2.png)

**Comment by vladikoff** [comment]
Should be fixed now. 

@jrgm I restarted `db` , stopped `mail`

**Comment by ValentinaPC** [comment]
yeah, it seems to work as expected.
Postfix video: 
![login](https://cloud.githubusercontent.com/assets/15685960/21189688/2d7b37c0-c228-11e6-9d38-e27ac305658f.gif)

**Comment by vladikoff** [comment]
👍

**Comment by ValentinaPC** [comment]
Issue is reproducing again. :(
![19 12 2016](https://cloud.githubusercontent.com/assets/15685960/21313758/448f0c34-c5fc-11e6-946d-fe69a5b28b44.png)

**Comment by vladikoff** [comment]
Okay our devOps are back and we are closely monitoring the state of these deploys 👀

**Comment by vcarciu** [comment]
This is reproducible again on -dev .
