### ISSUE TITLE
Show password button not shown on sign-in page if filled via password manager or prefilled

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4499]
STEPS TO REPRODUCE
1. In Windows 8.1 Nightly 53.0a1 (2016-12-13) (32-bit) sign in to Sync
1. Have the password pre-filled
1. Disconnect and sign in again (not sure this step is needed)

EXPECTED RESULTS
Show password button appears

ACTUAL RESULTS
It does not

<img width="1440" alt="screenshot 2016-12-13 11 51 13" src="https://cloud.githubusercontent.com/assets/68213/21149847/ddee9a6a-c12a-11e6-9d0b-7078ffad9edd.png">

**Comment by ValentinaPC** [comment]
Note (maybe it helps): if the password is edited - deleting or adding a char/number - the "Show" button is displayed.
Verified on FF50.0.2(Win 7).
Please take a look: 
![show](https://cloud.githubusercontent.com/assets/15685960/21175584/be8e874a-c1eb-11e6-8c09-e81b2470cb3a.gif)

**Comment by ryanfeeley** [comment]
I'm pretty sure I edited it and it didn't show, but regardless, the Shown should be shown if there is anything to show. If should only be hidden is there is nothing to show.

**Comment by shane-tomlinson** [comment]
> If should only be hidden is there is nothing to show.

The reverse is also true, it should only be displayed if there is something to show. This is the way it's supposed to be implemented, because it's cleaner to add to the DOM when needed than hide when not needed. Unfortunately, I didn't handle the autofill case.

**Comment by shane-tomlinson** [comment]
I'm able to reproduce this with the current Aurora and the built in Fx password manager.

**Comment by madalincm** [comment]
@shane-tomlinson 
Verified in FF53(Win7 x64)
This issue is still reproducing using the original steps:
![showpasswordbutton](https://cloud.githubusercontent.com/assets/15685441/26625203/12b1b952-45fc-11e7-8977-a6581e9c8b83.gif)
