### ISSUE TITLE
clicks on external links are not logged

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4512]
This was noticed while reviewing how to report metrics for clicks on the "sign in" button on the "connect another device" screen in #4370. For connect another device, the experiment logs clicks on the signin button, but no general capability exists for users that click on external links elsewhere in the app, e.g., from the TOS/PP pages.

It'd be nice to understand how often our users click on external links. We should log clicks on them, in a sane way, taking care not to expose PII.

**Comment by vladikoff** [comment]
Let's reopen if we need this in metrics
