### ISSUE TITLE
Remove avatar section and improve avatar hover state

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4520]
Let's simplify the settings section, but getting rid of the Account picture section. An improved hover effect with inner white border should help. Also add link title "Change account picture"
<img width="550" alt="screenshot 2016-12-16 12 55 25" src="https://cloud.githubusercontent.com/assets/68213/21272874/f73c2d50-c38e-11e6-93c9-29a0a28f4fea.png">

Most editing the avatar don't come from here anyway:
<img width="1387" alt="screenshot 2016-12-16 12 56 49" src="https://cloud.githubusercontent.com/assets/68213/21272924/213d7654-c38f-11e6-835c-29dc1c99901a.png">

**Comment by vladikoff** [comment]
Yea!

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I am a strong -1 on this suggestion. Using only a hover state will make it almost impossible for mobile or screen reader users to discover the change avatar functionality. 

I have this suspicion the linked to graph does not show what you think it shows. My hunch is you are interpreting the graph as showing users that open `/settings/avatar/change` directly from preferences or the menupanel. If so, that's a misinterpretation. Rather, the graph shows users that *somehow* get to the avatar section from preferences or the menupanel. It could be they opened settings from the "manage account" link and then clicked on "Account picture".

A suggestion was floated in HI that I liked was to alter the settings page layout to be more hierarchical. A "profile" section and a "security" section I think the suggestion was.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Good point. We are one of the few internet properties that has a responsive profile section. Most have an entirely different view. I'll take a look and see what's the latest on this issue.

**Comment by vladikoff** [comment]
closing for now until we needed ...
