### ISSUE TITLE
“None connected” is not localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#4532]
Discovered this one after #4529, and thought it was related, but turns out I can’t find this string in Pontoon, so it’s likely hardcoded. The Get app button could probably get some love too (just shortened the French translation as a temporary solution)

 <img width="545" alt="capture d ecran 2016-12-20 a 17 24 57" src="https://cloud.githubusercontent.com/assets/1294206/21358644/a239e042-c6d9-11e6-9c48-88b237a0b4c3.png">

**Comment by vladikoff** [comment]
the second issue you mentioned is part of https://github.com/mozilla/fxa-content-server/issues/4413

Thanks for taking a look at these @TheoChevalier !
