### ISSUE TITLE
"sign up, wait for confirmation screen, click resend" test is being rate-limited

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4537]
```
CancelError: Timeout reached on firefox on any platform - confirm - sign up, wait for confirmation screen, click resend
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:92:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:92:15>
```

This one test failed 3 times in a row: 
![image](https://cloud.githubusercontent.com/assets/128755/21373024/58d247ae-c6e9-11e6-9919-35d4d3bf2378.png)

https://tc-test.dev.lcip.org/viewType.html?buildTypeId=FxaLatest_FunctionalTests

**Comment by shane-tomlinson** [comment]
I found this nugget in [visibleByQSA](https://github.com/mozilla/fxa-content-server/blob/d4984df8d7e97ead8b30ea46199f2a2603f1c070/tests/functional/lib/helpers.js#L240):

> // If the element is animating, try again after a delay. Clicks
> // do not always register if the element is in the midst of
> // an animation.

The '#resend' element fades in, using a CSS animation.

**Comment by shane-tomlinson** [comment]
I'm going to re-open this until we see results on tc-test.

**Comment by vladikoff** [comment]
Issue is due to rate limiting, https://github.com/mozilla/fxa-content-server/pull/4561#issuecomment-269506407

**Comment by shane-tomlinson** [comment]
> Issue is due to rate limiting, #4561 (comment)

Great catch. Do we need to add mailinator to the list on latest too?

**Comment by vladikoff** [comment]
@shane-tomlinson i don't think we have a "list" like that for latest. We have this list: https://github.com/mozilla/fxa-customs-server/blob/9b94bd1bdd012217e322d2e008e16f3d7e57c22c/lib/config/config.js#L176 that is used everywhere and I'm not sold about adding mailinator to that list.

**Comment by shane-tomlinson** [comment]
Hmm, from that list, who is using mockmyid.com? Persona is no more, mockmyid.com shouldn't work anymore.

**Comment by vladikoff** [comment]
@shane-tomlinson I remember seeing Nick Alexander using it for testing some Fennec Sync. @rfk or @jrgm might know of other uses.

**Comment by shane-tomlinson** [comment]
> I'm not sold about adding mailinator to that list.

I wouldn't want to add mailinator globally, but I want to get latest functional tests passing. The two obvious workarounds are to add mailinator to the list for latest, or use a different email that won't be rate limited but still provides the functionality we need.

**Comment by vladikoff** [comment]
@shane-tomlinson maybe we can just use `@mockmyid` in that test and leave it in the list.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson maybe we can just use @mockmyid in that test and leave it in the list.

Seems like a winner.

**Comment by rfk** [comment]
>  I remember seeing Nick Alexander using it for testing some Fennec Sync

Yes, I vaguely recall this being one reason.  I've also used it in some sync loadtests in the past because it's easy to generate valid assertions for.  But given the demise of persona (and the fact that it isn't a Mozilla-owned domain) we should probably work towards replacing it anywhere it's being used.

Removing it from the customs bypass list might be a good way to flush out anyone still using it :-)

**Comment by vladikoff** [comment]
Ok let's remove it! However then we need another domain we can use in https://github.com/mozilla/fxa-content-server/pull/4583/files
