### ISSUE TITLE
Change title and add service name on password reset page

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4538]
This is a combination of https://github.com/mozilla/fxa-bugzilla-mirror/issues/118#issuecomment-267688317 and https://bugzilla.mozilla.org/show_bug.cgi?id=1320213#c3.  Please change the current "forgot password" page to say "reset account" and to include the name of the service being accessed, if any:

![screen shot 2016-12-21 at 14 24 23](https://cloud.githubusercontent.com/assets/34695/21376470/66b11e90-c789-11e6-8c47-14ee91852871.png)

**Comment by shane-tomlinson** [comment]
I understand the intent and agree with the goals, but I'm wondering if we can make further tweaks for clarity and to tie this screen back to the previous action (clicking on "Forgot password?")

First, `Reset account` as the title and `Reset password` in the button leaves me with a bit of cognitive dissonance. Can they be the same?

Second, Is `Reset password` a better title with an update to the red portion to say something along the lines of `When you reset your password, your account will be reset and you will lose any Sync data that is not on one of your devices.`? 

I have this suspicion that users who click on "Forgot password?" in the /signin page are going to land on this page, see "Reset account", and go "WOAH! I just want to reset my password!"

Using `Reset password` as the title and updating the red text to inform the user that resetting their password resets their account will give the user the information they need while still providing a title that makes sense when tied to the previous action.

**Comment by rfk** [comment]
> First, Reset account as the title and Reset password in the button leaves
> me with a bit of cognitive dissonance. 

@ryanfeeley's mock in https://github.com/mozilla/fxa-bugzilla-mirror/issues/118#issuecomment-267688317 changed the button to say "Begin reset", but I didn't notice that when I was squishing it together with the subheader change.

**Comment by vladikoff** [comment]
from mtg: something about the 90s. 

Header: Reset Account
Button: Begin Reset
