### ISSUE TITLE
The "get app" buttons appear briefly when loading the devices view

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4541]
When I load the devices view, it takes a second or so to request my devices list.  In that time, the "get app" buttons flash briefly onto the screen and are then replaced, making it feel a little janky:

![flashing_get_app_buttons](https://cloud.githubusercontent.com/assets/34695/21416232/5179510a-c865-11e6-9722-acf4d9bd69ba.gif)

I think it would be better to start from just a blank list while the initial list is loaded.  /cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@rfk Related, I guess even a dupe? https://github.com/mozilla/fxa-content-server/issues/5040

**Comment by rfk** [comment]
Good call, I'm going to close this in favour of #5040
