### ISSUE TITLE
App store images do not use cache busting URLs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4544]
Follow on from #4177.

Unique app store icons exist for many supported locales. Because of this, URLs to the images are inserted using JavaScript, and do not use cache-busting URLs.

One possible solution to this is to not insert using JS, but rather create a list of CSS rules, one for each translated locale, with the path to the image. The URL within the CSS will be updated to be cache busting.

**Comment by vladikoff** [comment]
Yea there was an issue before, we closed it because we update those images once in 2+ years https://github.com/mozilla/fxa-content-server/issues/4218#issuecomment-257029409
