### ISSUE TITLE
Only allow one Settings section to be open at a time

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4569]
Good suggestion to make FxA Settings more mobile friendly, but collapsing sections when opening other sections.

https://bugzilla.mozilla.org/show_bug.cgi?id=1325306

When a user has a Settings section open and opens another section, the original section should close as if "Done" were pressed (which may reset the form content, depending on the section)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - do you want this behavior for mobile, or mobile and desktop?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I put this in backlog because I am unsure of the priority, but you can promote it if you want it done now.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Both mobile and desktop. I'll assess our backlog and indicate priority.
