### ISSUE TITLE
Add artificial delay to the "Refresh" button in the devices view

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4570]
@ryanfeeley said that we need to keep the button spinning for a bit - 1800ms

**Comment by shane-tomlinson** [comment]
@ryanfeeley - do you want nearly 2 seconds, or 180 ms?

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @vladikoff - like the other bug, I put this in the backlog, but feel free to promote this.

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff It was 1600ms (1.6 seconds) https://github.com/mozilla/fxa-content-server/issues/4165

**Comment by vladikoff** [comment]
@ryanfeeley thanks!

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson I still don't see 1.6 seconds of aniation on this buttons.

**Comment by vladikoff** [comment]
@ryanfeeley yea, we haven't added it yet

**Comment by heatherbooker** [comment]
I'd like to take a look at this if it's still up for doing!

So to clarify:
- Current situation is that clicking it once shows the spinner for 1600ms, and clicking it again shortly after blinks the button but doesn't show a spinner
- Ideally clicking it once shows the spinner for 1800ms, and clicking it again shortly after the first click should..continue the current behaviour?

Is that correct?

**Comment by vladikoff** [comment]
@heatherbooker please take a look at this code: https://github.com/mozilla/fxa-content-server/blob/808ad8d1b12215f937c1eadb6f65a9a7e8488c49/app/scripts/views/decorators/progress_indicator.js#L21

See if you can modify that code such that if `var target = this.$(el);` has a data-attribute of `data-spinner-min-time` then it will resolve the Promise early but will still spin for specified `spinner-min-time` 

The `el` in this case is the submit button, so the template in clients mustache needs to modified to have the `data-` attribute.

**Comment by heatherbooker** [comment]
Thanks @vladikoff for the pointer! I'm still not understanding why I can't seem to make the spinner appear when running the code locally. Perhaps I'm missing something but this currently feels like an insurmountable obstacle to making it run longer!

I've tried looking all the places I thought it made sense to look and adding debug statements and plain ol console.logs but I can't quite grasp the flow of the code, ie what happens once the "Refresh" button is clicked. Ex, I can see that methods like 'start' and 'done' are being called in the [progress indicator view](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/progress_indicator.js), but adding something like:

```js
// in 'start' method (before setting this._showIndicatorTimeout) :
      this._indicatorMinTimeout = setTimeout(() => {
        this._indicatorMinTimeout = null;

        this.done();

      }, MIN_SPINNER_MS);

// in 'done' method (after first if statement) :
      if (this._indicatorMinTimeout) {
        return;
      }

```

to that progress indicator view doesn't seem to have an impact. 

Further suggestions for ways to grok what is going on would be awesome :)

**Comment by heatherbooker** [comment]
Further thoughts: it looks like the [timer-mixin](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/timer-mixin.js#L23) kills all setTimeouts when `destroy` is triggered [in the progress indicator](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/progress_indicator.js#L72) view, which happens after render from the submit method in [clients.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/clients.js#L208).

So I think that 1) the way to have the indicator keep showing for the desired amount of time is a setTimeout, and therefore 2) there needs to be some way to maintain this timeout in the face of the 'destroy' call, or a timeout could be set/reset after the `trigger('destroy')` call in views/progress_indicator. Is the second option, ex

```js
// views/progress_indicator.js
destroy () {
  this.done();

  this.trigger('destroy');

  // Set timeout here to continue showing indicator for 1800ms minus time elapsed.

  this.remove();
},
```

viable? (I'm not exactly sure how Backbone's this.remove might affect it.)

**Comment by shane-tomlinson** [comment]
Hi @heatherbooker - thanks for working on this. The ProgressIndicator's `destroy` method is being called because the parent view (DevicesView) is being re-rendered once the XHR request to fetch the devices has completed. Unfortunately, adding a 2nd timer would not fix the problem since the Refresh button is completely re-rendered, automatically removing the spinner from the DOM.

I'm going to have to think about how to work around this.
