### ISSUE TITLE
Settings avatar slow to update

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4574]
Note that while the zoomed view is up to date, the previous avatar still appears.
![bug](https://cloud.githubusercontent.com/assets/68213/21573742/1d11acb2-ceb6-11e6-910a-9baf4873511c.gif)

**Comment by shane-tomlinson** [comment]
Dup of the closed #3897.

**Comment by shane-tomlinson** [comment]
Ref #3374

**Comment by shane-tomlinson** [comment]
Closing since #5006 has a concrete suggestion.
