### ISSUE TITLE
Add "Web sessions" to Devices View

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4585]
Ref: https://github.com/mozilla/fxa-content-server/issues/4212#issuecomment-269816320

![](https://cloud.githubusercontent.com/assets/68213/21571918/eee6d164-cea1-11e6-82a0-82a2c1478316.png)

icon link https://www.dropbox.com/s/k1vjx5xsymmxiod/defaultFavicon.svg?dl=0

**Comment by ryanfeeley** [comment]
@vladikoff Hmm… colour is wrong in production. Can you correct it without a new file? Should be the same colour as the Add-ons icon.

**Comment by vladikoff** [comment]
Filed here https://github.com/mozilla/fxa-content-server/issues/4951
