### ISSUE TITLE
Missing sessionToken on force_auth

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4586]
See ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/375126/

cc @shane-tomlinson @philbooth 

Should we be concerned about this? The error is hit all the way in the fxa-js-client?
Sentry says it started with train 76.

*********

![image](https://cloud.githubusercontent.com/assets/128755/21630776/6ce437c4-d202-11e6-92d5-8815bfaf294c.png)

**Comment by philbooth** [comment]
Interesting. Train 76 looks fairly innocuous from the logs, I don't see anything that seems like it would suddenly start failing this test when called from `certificateSign`.

Tracing back up the stack, it looks like we'd get a better trace of where this is coming from if we checked the session token [in here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L185-L195) and failed at that point. Does that seem right to you guys?

Also, is it me, or does the second part of that preceding check in the `required` function look like complete nonsense? `val === {}` will always fail won't it? Should it really be something like `Object.keys(val).length === 0`?

**Comment by vladikoff** [comment]
From mtg: ![](http://v14d.com/i/5878e82990652.png), 

seems like the profile image call?

**Comment by vladikoff** [comment]
account.js does not check if sessionToken is there

```
    _generateAssertion () {
      var sessionToken = this.get('sessionToken');

      // assertions live for 25 years, they can be cached and reused while
      // this browser tab is open.
      var existingAssertionPromise = this._assertionPromises[sessionToken];

      if (existingAssertionPromise) {
        return existingAssertionPromise;
      }

      var assertionPromise = this._assertion.generate(sessionToken);

      this._assertionPromises[sessionToken] = assertionPromise;

      return assertionPromise;
    },

```
