### ISSUE TITLE
Make Get started here link go to Sync setup

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4605]
<img width="507" alt="screenshot 2017-01-10 11 56 58" src="https://cloud.githubusercontent.com/assets/68213/21815815/f2685ffa-d72b-11e6-81fe-692ed5198640.png">

Currently the link goes here:
https://mozilla.org/firefox/sync?utm_source=fx-website&utm_medium=fx-accounts&utm_campaign=fx-signup&utm_content=fx-sync-get-started

We should instead link here: https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=uitour

**Comment by ryanfeeley** [comment]
@shane-tomlinson Pls update with more specific entrypoint

**Comment by vladikoff** [comment]
I guess it would only go there if it is Firefox and it supports fx_desktop_v3...

**Comment by shane-tomlinson** [comment]
We can do the same thing we do with "connect_another_device", [determine if the user is on Fennec or Desktop](https://github.com/mozilla/fxa-content-server/blob/f44dcb5829ce657d48cb710424df344cfc5bd021/app/scripts/views/connect_another_device.js#L187:L215), and Do The Right Thing.

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson Ah yes, sorry, I should clarify. We should only change the link for Firefox users. Obviously Chrome, Safari and other users are better off with the original link (that prompts them to download Firefox).

**Comment by ryanfeeley** [comment]
@vladikoff @vbudhram @shane-tomlinson @davismtl @rfk This would be handy to have for secondary email. We could direct users to sign in to Sync so they can perform secondary email actions.

**Comment by davismtl** [comment]
> @vladikoff @vbudhram @shane-tomlinson @davismtl @rfk This would be handy to have for secondary email. We could direct users to sign in to Sync so they can perform secondary email actions.

I'm not sure I see the connection of proposed change to adding a second email.

If we add conditions here as per where we drive a user,  @ryanfeeley  please update the user flow diagram to include this logic.
