### ISSUE TITLE
error loading settings

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4608]
Fx 50
```
Unexpected error  6d9880dc.main.en.js:17:4181
	d.prototype.error https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:4181
	c.exports.captureError https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:27946
	c.exports.captureAndFlushError https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:28091
	c.exports.fatalError https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:28337
	B<.fatalError https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:19:16136
	F https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:23206
	E https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:23160
	l https://accounts.cdn.mozilla.net/scripts/6d9880dc.main.en.js:17:21212
```

**Comment by jrgm** [comment]
Loading settings page. Not every time, but often.

**Comment by vladikoff** [comment]
@jrgm is this on train 77 or which?

**Comment by vladikoff** [comment]
We had some issues earlier with the CSS loading that could be related to some cdn issues:

![](https://i.imgur.com/3Az7a2T.jpg)

**Comment by shane-tomlinson** [comment]
Was this resolved?

**Comment by vladikoff** [comment]
Cannot reproduce this all morning

**Comment by jrgm** [comment]
Yo. I duplicated my JS error from last night with Network Link Conditioner (from XCode Tools). Requires a slow link.

**Comment by vladikoff** [comment]
@jrgm ah Yes I see this issue with the 3G setting or "Very bad network" setting.

At first glance it seems that the `requireOnDemand` tries to load the fxa-client and times out

**Comment by vladikoff** [comment]
@jrgm strange thing is that on latest with the same bad conditions everything is fine :(

**Comment by shane-tomlinson** [comment]
We suspect this is due to either an XHR timeout or a requireJS timeout.

**Comment by vladikoff** [comment]
To reproduce this locally you can add this:

```
      var getNow = win.require;
      getNow.config({
        waitSeconds: 0.0000000001
      });
```

and start the server with `npm run start-production`
