### ISSUE TITLE
client side metrics sending is a bundle of complexity

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4610]
This is follow on from #4602 and #4603.

@vladikoff and @philbooth both hit me on the head and made me realize the front end goes through a lot of hoops to only send certain events once - in particular, navigationTiming and App store impressions/clicks.

To ensure those events are only sent once, we keep additional state and filtering logic. This is kinda silly, because an event in the event stream already has the desired behavior and doesn't require any extra logic.

Each field in navigationTiming could be considered an event. The offset of all events are already calculated from navigationTiming.navigationStart. Each item in navigationTiming could be added to the event stream with the appropriate offset.

Likewise, App store impressions and clicks can also be considered events. We'll need a way to sanely encode the link URL, but that seems tractable.

I resisted doing this work because it requires a backend change -  and the backend will need to handle both old and new versions of the front end. Old front ends will send these fields as "top level metrics" whereas new clients will send the metrics in the event stream.

@philbooth's comment clinched it - "if I opened this PR and you reviewed it, I think you'd ask for the same change."

**Comment by philbooth** [comment]
The other question I meant to ask about #4602 before it got merged was whether [this change](https://github.com/mozilla/fxa-content-server/blob/7c468e7146c5048e893d95a689684f8afeac2070/app/scripts/lib/metrics.js#L277-L279) was strictly necessary?

```js
  // Create a deep copy of the data so that any modifications to contained
  // objects or arrays do not affect the returned copy of the data.
  return JSON.parse(JSON.stringify(allData));
```

Presumably things were okay before when we just returned `allData` directly, so is something else different now that means we have to pay for the deep clone?

Given that `getAllData` is called repeatedly for every user, we could maybe do our bit for global warming by eliminating this little bit of extra CPU load on every client machine. 😄

**Comment by shane-tomlinson** [comment]
> The other question I meant to ask about #4602 before it got merged was whether this change was strictly necessary?

It's possible it's no longer necessary, I made last minute changes to the way the filtering worked. Checking now.

**Comment by shane-tomlinson** [comment]
OK, context re-loaded. Yes, it's necessary. I [store a reference to the last set of sent data](https://github.com/mozilla/fxa-content-server/blob/153292b1778fc0976622995d5694f39f8a72bc3d/app/scripts/lib/metrics.js#L174). The next time a flush request occurs, I compare the proposed flush set [against the previously flushed set](https://github.com/mozilla/fxa-content-server/blob/153292b1778fc0976622995d5694f39f8a72bc3d/app/scripts/lib/metrics.js#L170) to determine whether a flush is actually required. If all the values of the proposed flush set are the same as in the previously flushed set, no flush is required. 

With only a shallow copy, any updates to a top level metric are immediately reflected in `this._lastFlushedData` as well, because `this._lastFlushedData` contains references to the top level metric and not copies of the value the referred to. With a deep copy, copes of the values are created, with distinct references. We can update the top level metrics, and know that doesn't affect the values stored by `this._lastFlushedData`.

**Comment by philbooth** [comment]
Cool, so if we fix this issue and push everything through the events mechanism, we could at that point remove the deep clone?

**Comment by shane-tomlinson** [comment]
> Cool, so if we fix this issue and push everything through the events mechanism, we could at that point remove the deep clone?

If top level metrics only contain things that essentially become tags in DataDog nomenclature, then yeah, should be able to.

**Comment by philbooth** [comment]
Let's accept we're never going to fix this and move on. Closing.
