### ISSUE TITLE
Show password button does not show password

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-content-server#4627]
I was setting up a new copy of Firefox Developer Edition (52.0a2 2017-01-16) like this:
- Installed the browser
- Opened it, clicked the 'set up sync' button
- Clicked 'sign in to existing account' button
- Entered my existing Firefox Account email
- Entered my password
- Clicked the 'show password' button to be sure I typed it right

I could see the password flicker for a second but then it reverted back to bullet points.

This was on Mac 10.12.2 in case that matters.

**Comment by vladikoff** [comment]
@kumar303 this is by design, you have to hold the "SHOW" button

cc @ryanfeeley

**Comment by kumar303** [comment]
Oh, hah, that wasn't obvious
