### ISSUE TITLE
Replace `var` with `let` and `const` in server side code.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4632]
@philbooth brings up a good point in [this PR comment](https://github.com/mozilla/fxa-content-server/pull/4623#discussion_r96604671) about changing `var` to `const` and `let` on the server side code. Node 4.6 supports the new keywords. We should feel free to convert as we go, like we do on the front-end.

**Comment by pdehaan** [comment]
Relevant ESLint rules:
- http://eslint.org/docs/rules/no-var
- http://eslint.org/docs/rules/prefer-const

Both rules seem to be auto-fixable, so if you're lucky you may be able to do `eslint . --fix` (or whatever target directories you want) and sit back and watch the magic.

**Comment by shane-tomlinson** [comment]
Oh... I didn't know `--fix` was a thing. Thanks @pdehaan!

**Comment by vladikoff** [comment]
@shane-tomlinson,  
 @divyabiyani and I will be working on some ESLint improvements and will include this in the ESLint updates, so I assigned this issue.
