### ISSUE TITLE
Confirm that connect another device shows the right message

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4634]
Just a quick one for @shane-tomlinson…

I noticed that when I copied and pasted the confirmation URL into different browsers, I would get "This device is connected" even though I would be in Chrome or signed in to Firefox with a different user.

Will what ships to production be smarter and show the right thing?

* Say "Email verified" in all browsers except the originating Firefox.
* Show original "Account confirmed" screen for Firefoxes already occupied by other users.

**Comment by vladikoff** [comment]
> I copied and pasted the confirmation URL

Did you copy paste the verification link or did you copy paste the page it redirect you to?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - you and @vladikoff are both right.

### confirm in Chrome
<img width="475" alt="screen shot 2017-01-19 at 12 23 35" src="https://cloud.githubusercontent.com/assets/848085/22106762/3eb1d2b6-de42-11e6-98f0-dddca80c58c2.png">

### confirm b@b.com with a@a.com already signed in

<img width="456" alt="screen shot 2017-01-19 at 12 27 12" src="https://cloud.githubusercontent.com/assets/848085/22106854/af07270a-de42-11e6-9f8d-29112d1ccb60.png">

Where you are right - if you paste in the URL with `connect_another_device`, you'll see the wrong message.

Where @vladikoff is right - you aren't supposed to paste that URL, you are supposed to paste the `verify_email` url (the original link in the email) with `&forceExperiment=connectAnotherDevice&forceExperimentGroup=treatment` appended.

So there is a bug, but most users won't see it.

**Comment by shane-tomlinson** [comment]
> So there is a bug, but most users won't see it.

Another way to access the first bug (Email verified->This device is connected) is to refresh the final page.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I definitely copied and pasted the URL. But the URL that we include in the email isn't going to change in production is it? How can we know what device a user will open the link on before they open it?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson I definitely copied and pasted the URL. But the URL that we include in the email isn't going to change in production is it? How can we know what device a user will open the link on before they open it?

The URL in the email is not changing, but once the user opens the URL from the email, we make decisions based on the user-agent and the user's signed in state about which screen they should be redirected to. Some users are redirected to `signup_complete` (which is existing behavior), others are redirected to `connect_another_device`.

**Comment by ryanfeeley** [comment]
@shane-tomlinson 👍
