### ISSUE TITLE
Do away with storing multiple accounts in local storage

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4635]
Do away with that ^

Ref: https://github.com/mozilla/fxa-content-server/pull/4584/files#r96395664

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa-content-server/pull/4493 was opened to see how many people actually have stored accounts. That should ship with train-78.

**Comment by vladikoff** [comment]
> #4493 was opened to see how many people actually have multiple stored accounts. That should ship with train-78.

Were there any results from that?

**Comment by vladikoff** [comment]
from mtg: 🗡  Kill it
