### ISSUE TITLE
Flaky functional test - communication preferences - opt-in on signup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4638]
I see this fail locally ~ 50% of the time.

**Comment by vbudhram** [comment]
Was able to reproduce locally 
```
{"using":"css selector","value":"#preferences-url"}] Unable to locate element: #preferences-url
```

**Comment by vladikoff** [comment]
`#preferences-url` is the basket link to Email Prefs i think.

**Comment by shane-tomlinson** [comment]
Check out this not awesomeness - if the user is signed up to Basket, then `#preferences-url` should be available. If the user is not signed up to Basket, then the `#preferences-url` should not be available. But... I have one screenshot of the user signed up to Basket without the link. One screen shot of the user signed up to Basket with the link. And one after the user unsubscribed, yet still, with the link.

<img width="515" alt="screen shot 2017-02-17 at 21 05 36" src="https://cloud.githubusercontent.com/assets/848085/23120769/9b7161de-f755-11e6-9f1f-40ad2748af6e.png">



<img width="494" alt="screen shot 2017-02-17 at 21 16 18" src="https://cloud.githubusercontent.com/assets/848085/23120781/a3b00cce-f755-11e6-8db4-261fc1aab3ec.png">


<img width="492" alt="screen shot 2017-02-17 at 21 15 43" src="https://cloud.githubusercontent.com/assets/848085/23120774/9f216e6e-f755-11e6-85ba-6fba7e492984.png">

**Comment by rfk** [comment]
Is this still an issue after our recent war on flaky tests?

**Comment by shane-tomlinson** [comment]
It hasn't been, but that's only "success by coincidence" which isn't very gratifying.

**Comment by shane-tomlinson** [comment]
I'm going to take "success by coincidence" for now...
