### ISSUE TITLE
Stop passing direct references to sentryMetrics and replace them with events?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4639]
This question arose while I was refactoring some stuff out of the views into the metrics object. The thing I was refactoring wanted access to `sentryMetrics`, which the views receive but the metrics object does not. I could just pass in `sentryMetrics` as an extra option to the metrics object, but it is exactly this kind of coupling that makes `lib/app-start.js` such a mess and refactoring things more difficult than it needs to be.

Errors are pretty much the perfect use-case for events, I think. The thing that experiences the error really shouldn't give a toss about implementation details of the thing that reports the error. If we have a broader objective of decoupling front-end code by leaning on events more, I think this is a great place to start.

The benefits may not seem that great for just `sentryMetrics` on its own, but if we gradually divert more and more of our inter-object communication through an events mechanism, it will reduce the number of direct dependencies we have between modules. Events eat spaghetti for breakfast.

**Comment by philbooth** [comment]
And actually, the main `metrics` object is another good candidate I think. All that stuff could go through the `notifier`.

**Comment by vbudhram** [comment]
from uno: closing
