### ISSUE TITLE
Circle functional tests fail to build

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4641]
This doesn't happen all the time, but most of the time. It seems to be related to Docker.

See https://circleci.com/gh/mozilla/fxa-content-server/5882

It's hard to determine exactly what is causing the failure, but these two lines look promising:

> Loading "changelog.js" tasks...ERROR
> >> Error: Cannot find module 'fxa-conventional-changelog'

In other runs it complains about SASS.

**Comment by shane-tomlinson** [comment]
cc @jbuck, @vladikoff

**Comment by jbuck** [comment]
Patch in https://github.com/mozilla/fxa-content-server/pull/4644
