### ISSUE TITLE
Use field-level error for age required

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4653]
“As a registering user, I want you to tell me where on the form it hurts.”
![age](https://cloud.githubusercontent.com/assets/68213/22163407/b623c9c4-df20-11e6-8f24-61e19331e3dd.png)

**Comment by shane-tomlinson** [comment]
Did we move the error text because of the "your password is too easy" help text?

**Comment by ryanfeeley** [comment]
@shane-tomlinson I think we had it in the wrong place to begin with because originally the message was not going to mention the password specifically but rather the more secure "invalid password/username" type message (so we never reveal to a user if they have an account with a given email). The design now just matches the copy better.

**Comment by alisha17** [comment]
Hi,
Can I work on this bug ?

**Comment by vladikoff** [comment]
Hello @alisha17 , I think there is already a PR open for this issue which is this: https://github.com/mozilla/fxa-content-server/pull/4805

**Comment by vershwal** [comment]
This has been done in PR #4867. Please check.

**Comment by vershwal** [comment]
Hey @ryanfeeley 
This has been done in PR #4867. Please check.

**Comment by vladikoff** [comment]
And it is live in production! good work @vershwal !
