### ISSUE TITLE
Double stacked link margins to make them touch-friendly

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4655]
Currently our stacked links are very close to each other and under the recommended minimum of 30px of height. We should double the vertical margin from 5px to 10px to push it over this limit and make it more readable for everyone, and clickable for mobile.
![padding](https://cloud.githubusercontent.com/assets/68213/22165615/d186be74-df2a-11e6-9219-4fcc76e2c1fc.png)

**Comment by shane-tomlinson** [comment]
👍 - I was playing with the Surface over the weekend - it has a full resolution screen but I was using it as a touch device. Trying to click on links that were stacked too close together was painful.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Though this research is more for button/objects, I might bump this up more based on the research presented here: http://scotthurff.com/posts/how-to-make-truly-tappable-user-interfaces

**Comment by ryanfeeley** [comment]
@vladikoff Is this in effect? Looked tight to me on Android.

**Comment by ryanfeeley** [comment]
@vladikoff Closed?

**Comment by vladikoff** [comment]
@ryanfeeley this was fixed in Desktop, but not in Mobile mode 🦉

**Comment by ryanfeeley** [comment]
@vladikoff Shall I file an issue for that? It's specifically a "touch-friendly" issue.

**Comment by vladikoff** [comment]
I'm excited @shane-tomlinson
