### ISSUE TITLE
Our HSTS header will expire in the year 2510

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4657]
```
$ curl -s -D - https://accounts.firefox.com/__version__ | grep -i strict-transport
Strict-Transport-Security: max-age=15552000000; includeSubDomains
```

Please leave a note for your descendants to expect this.

**Comment by vladikoff** [comment]
See https://github.com/mozilla/fxa-content-server/blob/517a287a8948dcca64e36a8bb34fd32061dc7212/server/lib/hpkp.js#L15

**Comment by jrgm** [comment]
Yeah, I should have mentioned, it was broken with the upgrade to helmet 3.x

**Comment by vladikoff** [comment]
@jrgm I guess we will have to change `format: 'duration'` to seconds somehow in our config...
