### ISSUE TITLE
Error metrics tagged as `object_Object` in datadog

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4659]
I noticed this oddity in datadog just now:

![screen shot 2017-01-24 at 13 58 12](https://cloud.githubusercontent.com/assets/34695/22232446/851c2dba-e23d-11e6-9fbb-2fceb891db8e.png)

There are error events in there named things like "fxa.content.error.settings.clients.disconnect.auth.object_Object".  I assume that's taken the classic "[object Object"] stringification of an object and converted it into a metric name.

**Comment by rfk** [comment]
Looks like they're few in number, but happen pretty regularly:

  https://app.datadoghq.com/dash/54202/fxa-content---front-end-errors?fullscreen=176944184

**Comment by vladikoff** [comment]
Yeah this is an issue with tokens becoming out of date, will patch it up...
