### ISSUE TITLE
Discuss sending the sign-in confirmation to users in a tab

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4667]
How do we let users authorize new devices to Sync without requiring them to reverify their email address? We can leverage the power of sending tabs in Firefox. Icon is for position (and LOLs) only.

![confirm-sign-in-send-tab](https://cloud.githubusercontent.com/assets/68213/22263540/cc41dbea-e242-11e6-9b3d-ce9af60c744d.png)

Let's discuss sending sign-in confirmation to users with at least one connected device in a tab.

**Comment by rfk** [comment]
I like this as an option; I have lots of questions and I wonder how often it will be *less* convenient for the user:

* They're not at their main computer
* They're reinstalling a device without cleanly logging out first; we would still think they've got a device connected to their account, and try to push a tab to it, but there's nothing there to receive it.
* If they have several devices, will receiving the tab on all of them be annoying?

Are there heuristics we could use to decide when to send a tab vs send an email?  Would it make sense to let the user choose?

**Comment by ryanfeeley** [comment]
> * They're not at their main computer

We could use heuristics to decide this. If they are on desktop, connecting another desktop  (or, the same reinstalled) we can default to email. But in the event of desktop to mobile, or mobile to desktop, I think this should work.

> * They're reinstalling a device without cleanly logging out first; we would still think they've got a device connected to their account, and try to push a tab to it, but there's nothing there to receive it.

Opt out of that.

> * If they have several devices, will receiving the tab on all of them be annoying?

You have perhaps found a missing piece. What if the tab is arrives on a different device after the sign-in has already been confirmed? I suppose that might be a little annoying. Would be auto-advance to this?

<img width="476" alt="image" src="https://cloud.githubusercontent.com/assets/68213/22296158/4f5014c6-e2e7-11e6-8fc8-9f5207b79dd9.png">

> Are there heuristics we could use to decide when to send a tab vs send an email?  Would it make sense to let the user choose?

Yes, I would follow what I described above. It depends on device awareness, one of the big reasons for having our device mgr to begin with.

**Comment by ryanfeeley** [comment]
Ask for me from @davismtl: draft a feature document.

**Comment by shane-tomlinson** [comment]
@ryanfeeley to start a feature doc.
