### ISSUE TITLE
Update FxA/Sync User Flow Diagram

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4683]
Our user flow diagram and screenshots are out of date. We should re-document this.

Here is the old user flow:
https://www.lucidchart.com/documents/edit/46781408-52b1-b652-9823-7a810a00c462/0?shared=true&

Here is pdf version of LucidChart: 
https://www.lucidchart.com/documents/edit/46781408-52b1-b652-9823-7a810a00c462/0?shared=true&

(updated from comment below)
Here is the WIP of the new flow being worked on by @vpomerleau : 
https://www.lucidchart.com/invitations/accept/8cb5f000-3940-4ae7-a1df-0a3346c983ff

**Comment by vpomerleau** [comment]
Here is a link to the new draft/work-in-progress User Flow Diagram for FxA/Sync: https://www.lucidchart.com/invitations/accept/8cb5f000-3940-4ae7-a1df-0a3346c983ff

**Comment by vpomerleau** [comment]
@rfk, @ryanfeeley, @davismtl I've also sent you an invite to collaborate via email

**Comment by davismtl** [comment]
@ryanfeeley @rfk While looking at this, feels like this would be really useful for creating a test plan for Softvision.

@vpomerleau looks great! I'll dive in more. As discussed, let's put all the screenshots you took in Google Drive and link to them from diagram.

**Comment by ryanfeeley** [comment]
@vpomerleau Whew! Lots of work. Thanks for this. I'm looking at it and giving it some OCD TLC.

**Comment by vpomerleau** [comment]
Thanks @ryanfeeley! It's definitely a work in progress that can use some TLC. As @davismtl mentionned, I'll start adding fresh screenshots today.

**Comment by ryanfeeley** [comment]
@vpomerleau We learned early that Lucidchart will choke on embedded bitmap images. Best to link to them in DropBox, Google Drive or elsewhere on the web (and somewhere you can update easily).

**Comment by vpomerleau** [comment]
@ryanfeeley Yep, @davismtl just created a shard Google Drive folder so I can link from the chart :)

**Comment by vpomerleau** [comment]
@rfk Could I be added as a contributor to the repo? I couldn't change the status of the task. Had to bug @davismtl to do it for me :) Thanks!

**Comment by rfk** [comment]
> @rfk Could I be added as a contributor to the repo?

Done, let me know if you still have any issues with your access.

**Comment by vpomerleau** [comment]
Thanks @rfk!

**Comment by davismtl** [comment]
@vpomerleau 
You improvements from the weekend look great! It's much easier to read in this vertical format.

You're flow diagram has already helped QA a bit with improving their end to end testing of FxA. While taking it out for a test drive, they identified a couple of small mistakes in it (I wouldn't expect anything else from QA).

Pockets and Add-on are both entrypoints to registration and login however they don't bring you into the whole Sync flow. I think that these entrypoints will need their own flows. (your placeholder for Pageshots will likely also fall into this flow)

Thanks again for you help! Your work is already very helpful to us.

**Comment by rfk** [comment]
@vpomerleau I invited you as a collaborator on this repo, but I think you'll need to go into https://github.com/mozilla/fxa-content-server/invitations and confirm the invite before we can assign you to the issue.

**Comment by vpomerleau** [comment]
@rfk Done. Thanks!

**Comment by vbudhram** [comment]
from mtg: closing for now
