### ISSUE TITLE
Discuss changing what users see when they sign in on additional devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4685]
Currently we show users who have signed in to Sync on additional devices this screen or Prefs. What we’d like to do is highlight the lesser-known features of Sync. (could link to SUMO page)

Other option is:  "Right-click to send this link to another device" which could help them send a surpise page to their other device.

Possible @shane-tomlinson?

![connect-device copy 2](https://cloud.githubusercontent.com/assets/68213/22388530/e8678ab8-e4ae-11e6-842d-76fafa44180c.png)

**Comment by ryanfeeley** [comment]
Ideally drop SUMO link.
Need to show on-device and off-device state.
On-device can have the demo link.
Need to spec demo pages.

**Comment by ryanfeeley** [comment]
Design Firefox brand off-device too.

**Comment by vladikoff** [comment]
from mtg: "from a link can we tell if the user has at least one device already connected?"

**Comment by ryanfeeley** [comment]
@rfk @vladikoff Illustration needed, but what about this?
![sync-party-started](https://cloud.githubusercontent.com/assets/68213/22446856/f59a1ef6-e71c-11e6-9d2b-e12b534e303b.png)

**Comment by davismtl** [comment]
As per our discussion.

- If the user is confirming on a Firefox with no login, that should be default. (last screen above)
- If the user is on Fx for desktop, show them the first proposed screen and teach them to send a link. The link should be a page about send Tab and perhaps other Sync features. (do we need to make a page?)
- If the users is on mobile, show how to share on iOS/Android. It may be easier to put a carousel of images. Show the beginning of the second image so the user knows they can swipe. (e.g. iOS users need to know how to active feature in share menu)

**Comment by rfk** [comment]
> from a link can we tell if the user has at least one device already connected?

If it will make the UX significantly better, I think we can find a way to make this so, for example by just embedding a count in the link as suggested by @seanmonstar.  It may not be 100% accurate all the time, e.g. if you clink through the link after disconnecting a device.  But it should be enough to make the UX look nice in the vast majority of cases.

If we're going to move forward on this, let's start up a feature card and doc.

**Comment by shane-tomlinson** [comment]
I had a shower moment that connects this with #2886. @vladikoff and I discussed various ways to allow users who verify on old Android devices to successfully complete verification. One solution was to skip using XHR to complete verification and go old school - open the verification link points to an endpoing on the auth server, the auth server completes verification and then redirects to the appropriate screen on the content server, a screen that hopefully uses no. This scheme would work perfectly for this situation - if verification successfully completes, the auth server would look up how many devices the user has connected and when it redirects to the "*_complete" page on the content server, it'd add the number of devices as a  new query parameter. The content server can then show the appropriate screen.

**Comment by vladikoff** [comment]
from mtg: this needs to become a feature doc...

@davismtl and @ryanfeeley to add this as Part 2 to the "send tab" doc.

**Comment by ryanfeeley** [comment]
Still working on feature doc, and with Martell on illustrations (which includes ALL of our illustrations on web and even client)

**Comment by vladikoff** [comment]
from meeting: ux still in the works. @ryanfeeley let's migrate to a feature doc...

**Comment by rfk** [comment]
Specifically, let's ensure there's a feature card in https://waffle.io/mozilla/fxa-features and link to the WIP feature doc from there
