### ISSUE TITLE
Empty setting page if profile server is down

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#4690]
STR

1) From fxa-local-dev, `./pm2 start servers.json`
2) Kill profile server
3) Signup, verify an account
4) Login to view settings

Expected:
Can view setting page, maybe display empty avatar?

Actual:
Empty page, with no warning or indication of what happen.

This is a very low priority bug but puzzling because you can go through the  signup, verify and login flows with no issues when profile server is down.

**Comment by shane-tomlinson** [comment]
Suspiciously similar to #3863 and I could swear there was a larger discussion about how the FxA frontend should respond to any server being down.

**Comment by vladikoff** [comment]
This should probably show an error (that it failed to talk to the profile server)

**Comment by vbudhram** [comment]
from uno: closing for now
