### ISSUE TITLE
Invalid parameter value on iOS login

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4691]
A user who is syncing on other devices is getting this Invalid parameter value error on iOS login

https://twitter.com/biggin9219/status/826693139113136129

cc/ @st3fan @sleroux @grigoryk

**Comment by rfk** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1334545

**Comment by rfk** [comment]
"Invalid parameter" here means the auth-server is rejecting something in the request with a 107 errno.  The name parameter "value" does not correspond to any valid request parameters as far as I know, but it could be that the auth-server is accidentally sending back the wrong name for something.

**Comment by shane-tomlinson** [comment]
Next for investigation

**Comment by vladikoff** [comment]
Fixed in latest iOS beta
