### ISSUE TITLE
CASE_MATTERS in the URL path - blank pages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4693]
found by @ryanfeeley - 

1) visit https://accounts.firefox.com/SIGNUP

You'd expect to see something other than a throbber here, whether it's a 404 or just the signup page, but you don't

**Comment by vladikoff** [comment]
from mtg: it should show a 404 instead of spinning...

**Comment by TDA** [comment]
<img width="1141" alt="screenshot 2017-02-12 13 00 56" src="https://cloud.githubusercontent.com/assets/432707/22860419/5d653ad8-f123-11e6-8e1e-1b1fb8f36103.png">

@vladikoff Is this not the 404 page? I am on FF 52.03b.

**Comment by vladikoff** [comment]
This was fixed 👍
