### ISSUE TITLE
Capture Language (or locale) in Meta Data

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4694]
Context:
During a recent firstrun a/b test, we observed that our control was performing much better than the page in production. Normally these pages are identical. The exception in the A/B test is that the control was only displayed to EN-US.

This means that there are other languages, locales or geographic regions that are really under performing.

We need to save language or locale.

Related: https://waffle.io/mozilla/fxa/cards/57bb62ccf7a3eaa80292e2f8 (add country)

**Comment by shane-tomlinson** [comment]
cc @philbooth 

We report the user's locale already to the backend when [reporting to /metrics](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/metrics.js#L255). I'm not sure if there's an equivalent concept with flow metrics and the metricsContext that goes with some requests to the auth server.

**Comment by philbooth** [comment]
Yep, this needs to be fixed in `fxa-activity-metrics` and the data pipeline. I'll do it at the same time as mozilla/fxa-activity-metrics#36, which will be Real Soon Now.

**Comment by shane-tomlinson** [comment]
Migrated to https://github.com/mozilla/fxa-activity-metrics/issues/48, closing here.
