### ISSUE TITLE
The `can_link_account` warning is shown for different email capitalization

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4700]
A user reported this on IRC. STR:

* Sign in to Firefox with a lowercase email, like "example@restmail.net"
* Sign out
* Sign in with a mixed-case variant of the same email, like "Example@restmail.net"

Firefox will show the "a different user was logged in on this device" warning, even though it's the same account. We should use a case-insensitive comparison.

I've confirmed this behaviour on both Desktop and Fennec, although it's not obvious to me whether we can fix it in content-server if if each browser will have to handle it themselves.

**Comment by shane-tomlinson** [comment]
This is a dup, I just can't find the original.

**Comment by shane-tomlinson** [comment]
IIRC, we decided previously we couldn't do anything about this on the content server. We send the `can_link_account` request *before* doing the login on the auth-server. We did so to avoid creating a session/keys if the user clicked "cancel" in the merge warning. We only know the canonical form after the login request. We could do extra trickery where we create a session, get the canonical email, then do the merge warning, if there's a cancel, then delete the session, but that seems like a lot of work for (my guess) not a super common case.

**Comment by rfk** [comment]
Hmm...and I guess the client can't do a case-insensitive comparison either, because it only keeps a hash of the previously-logged-in email for PII reasons.  @shane-tomlinson if you think there's nothing we can do here, please just close this out.
