### ISSUE TITLE
User received an error message saying "no message"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4701]
A user in IRC reported seeing an error message during their login attempt, saying "no message".  The only instance of this I could find, was the USER_CANCELLED_LOGIN error here:

  https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/auth-errors.js#L131

I was not able to reproduce a flow that would cause this text to actually be displayed to the user, but evidently it's possible.  We might consider changing the message text to be a little more descriptive :-)

**Comment by vladikoff** [comment]
Let's make it say `"Login attempt cancelled"` instead of no `"no message"`

**Comment by vershwal** [comment]
Hi @seanmonstar @vladikoff 
I would like to work on this issue. I'll be filing a PR soon.
