### ISSUE TITLE
force_auth + incorrect email case => invalid authorization code

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#4702]
The force_auth flow appears to still have the email-case bug that was causing large numbers of "invalid authorization code" errors.  A user described this to me in IRC and from what I can tell, they were re-logging-in to sync through the force-auth flow but with a different email capitalization.  You can reproduce it by doing:

* Create an account with lowercase email, like "example@restmail.net"
* Make failing login attempts to that account until you get rate-limited
* Visit force-auth with email in mixed capitalization, like https://accounts.firefox.com/force_auth?email=Example%40restmail.net
* Attempt to login with the correct password
* Do the authorization code email loop, and observe that you get "invalid authorization code" despite carefully copy-pasting the code from your email

Devtools shows that the page makes two failing requests to /v1/account/login:

* The first fails due to incorrect email case, but consumes the authorization code
* The second fails due to the now-invalid authorization code

**Comment by vladikoff** [comment]
Good find !

**Comment by rfk** [comment]
@shane-tomlinson and I just chatted about this, sounds like the "force auth" part might be a red herring, and we will need to add some special-case handling of the incorrect-case+unblock-code situation in the auth-server.

**Comment by rfk** [comment]
Actually, this may get fixed when train-79 goes live, thanks to changes to the way we handle the "incorrect email case" error in https://github.com/mozilla/fxa-auth-server/pull/1623.  IIUC that change will cause us to return "incorrect email case" *before* we consume the unblock code.

**Comment by vladikoff** [comment]
👍

**Comment by rfk** [comment]
I can confirm that this appears fixed with the release of train-79; will be interesting to see how much of a difference shows up in our metrics!
