### ISSUE TITLE
signins on firstrun page sometimes finish at "Working..."

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4706]
If a user is not forced to go through signin confirmation, a signin finishes at "working..." The user is successfully signed in and starts syncing, but no screen transition occurs.

STR

1. Sign up for Sync, verify.
3. Using a new profile, sign in to Sync from the firstrun page. This sign-in should not need to go through signin confirmation:

<img width="903" alt="screen shot 2017-02-07 at 15 52 20" src="https://cloud.githubusercontent.com/assets/848085/22700659/4f02dbf4-ed53-11e6-8a0d-947470885c6f.png">

cc @ryanfeeley, @jpetto, @davismtl, @vladikoff

We aren't sure when this started, though there are several possible explanations.

The firstrun page opens FxA with the `haltAfterSignIn=true` query parameter. [We had this problem](https://github.com/mozilla/fxa-content-server/blob/d99cabfa88e6db666f3c540ca03b00ba8bc8df66/app/scripts/models/auth_brokers/fx-firstrun-v1.js#L44:L48) and to side-step it, the firstrun page would receive a `login` message and take over the UI. The firstrun page no longer takes over the UI, FxA does no transition, and the user sees kind of a yucky experience.

@ryanfeeley has a couple of DataDog graphs to give us an indication of how frequently this occurs in the wild. There was a big bump in late-Nov through mid-Dec that subsided, then another spike in the past week.

#### Working errors on all pages
![Working errors on all pages](https://irccloud.mozilla.com/file/lc0DRDkf/Screen%20Shot%202017-02-07%20at%2011.12.10%20AM.png)

#### Working errors on the firstrun signin page
![Working errors on the firstrun signin page](https://irccloud.mozilla.com/file/ntnUCEKZ/Screen%20Shot%202017-02-07%20at%2011.17.09%20AM.png)

#### Working errors on all firstrun pages

<img width="1343" alt="screen shot 2017-02-07 at 17 12 28" src="https://cloud.githubusercontent.com/assets/848085/22702503/db1b885c-ed58-11e6-9910-2380f02391de.png">

**Comment by vladikoff** [comment]
cc @alexgibson

**Comment by shane-tomlinson** [comment]
A couple possible fixes:

1. Bring back whatever UI magic the firstrun page did at one point whenever it receives the `login` message.
2. Have the `signin` page ignore `haltAfterSignIn` and redirect the user to `signin_verified`.

I'm not sure what other options there are, or even which of these two is simpler.

**Comment by shane-tomlinson** [comment]
There are some funnelcake tests being run to send users to signin instead of signup, @davismtl believes these completed last week. Do any of these tests take over the screen on `login`? If the firstrun based screen transition were re-introduced, would it affect any (still running) funnelcake tests?

**Comment by davismtl** [comment]
Correction: the funnelcake tests that will drive to signin will start either EOW or next week.

The test that ended last week was the one where we hid the form on the firstrun page by default. It ended on Feb 1st.

**Comment by shane-tomlinson** [comment]
This is being taken care of by @jpetto within the firstrun page. The tentative PR is at https://github.com/mozilla/bedrock/pull/4643.

**Comment by shane-tomlinson** [comment]
I just tested this.. It's been fixed. Thanks so much @jpetto!
