### ISSUE TITLE
Success message removed on CWTS if user clicks on a checkbox

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4714]
I'm not sure whether this is expected or not, and fixing this might be a bit fiddly because we remove status messages as soon as the form changes.

STR.

1. Sign up to FxA for Sync
2. On the CWTS screen, click an item.

![success-removed](https://cloud.githubusercontent.com/assets/848085/22836863/0865009a-efb6-11e6-9ed7-8f8d5614a842.gif)

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@shane-tomlinson I'm not too fussed by this, but your attention to detail is impressive. I would not rank this highly, but if it's easy, go for it.

**Comment by philbooth** [comment]
Agreed in the meeting this was a bit meh, closing.

**Comment by ryanfeeley** [comment]
@davismtl You may want to re-open this? I still think the "Mistyped email" should appear in where the "Back" is.

**Comment by vladikoff** [comment]
wrong issue
