### ISSUE TITLE
Investigate whether there are frustrating user flows associated with the SMS install link

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4721]
I've seen this in Firefox but Alex rightly pointed out that maybe its not too big a deal because this link is for people who don't have Firefox yet.

But anyway, if the SMS install link is left open in a tab, when you re-open Firefox it can cause the App Store to be opened again. And again, repeatedly, every time you try to open Firefox, ad infinitum. Vlad knows what I mean.

Not sure if it's something we want to spend time on, or what the best way to handle it is.

**Comment by rfk** [comment]
> Not sure if it's something we want to spend time on

FWIW, I'm sure: this is definitely something we need to get to the bottom of before rolling out this flow to any more than a handful of test users.

**Comment by vladikoff** [comment]
I tested this flow a few times, and if we open the link in Firefox then it goes the Play Store.
From there the user can hit "open" and get back to Firefox and it will just stay there. Seems like that was either fixed in Firefox or in adjust 👍
