### ISSUE TITLE
navigationTiming values are sometimes negative

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4722]
Found this while investigating some anomalies with the navigationTiming metrics. Sometimes `domComplete`, `domContentLoadedEventEnd`, `domContentLoadedEventStart`, `domInteractive`, `domLoading`, `loadEventEnd`, and `loadEventStart` are negative.

Example:
```
domComplete: -11, domContentLoadedEventEnd: -11, domContentLoadedEventStart: -11, domInteractive: -23, domLoading: -23, loadEventEnd: -10, loadEventStart: -11,  
```

There is [this snippet in the w3c navigationTiming spec](https://www.w3.org/TR/navigation-timing/#dom-performancetiming-domcomplete):

> This attribute must return the time immediately before the user agent sets the current document readiness to "complete".
>
> If the current document readiness changes to the same state multiple times, domLoading, domInteractive, domContentLoadedEventStart, domContentLoadedEventEnd and domComplete must return the time of the first occurrence of the corresponding document readiness change.

I think this is a problem in speed-trap, but am documenting it here for visibility.

cc @philbooth because he's talking through the problem with me.

**Comment by shane-tomlinson** [comment]
It seems like [it's possible we use Date.now() instead of navigationTiming.navigationStart [here](https://github.com/rum-diary/speed-trap/blob/0e7e4000098731c07636438ce1a561471bcc8439/src/speed-trap.js#L134), but I haven't been able to reproduce this locally.

**Comment by shane-tomlinson** [comment]
Ref #5188

**Comment by philbooth** [comment]
Link to the PR, for the benefit of anyone peering at this from waffle:

https://github.com/rum-diary/speed-trap/pull/15
