### ISSUE TITLE
Change link label on Choose What to Sync from Back to Mistyped email?

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4726]
We should be more clear about why there is a secondary action on the choose what to sync page. It will help users notice and rectify mistyped email more. We will know this to be true when we see more users clicking the link, fewer bounces and a higher verification rate.
![mistyped](https://cloud.githubusercontent.com/assets/68213/22998139/6abad3dc-f3a3-11e6-9712-6dd7b3adee17.png)

**Comment by davismtl** [comment]
My thoughts
1) This is showing up after the user has confirmed their email so it's too late to change their email. (currently) 
2) The back button feels like its legacy from a previous flow when this screen probably showed up before the email confirmation screen. (just a guess)
3) If you want to rename the back button because (if for some reason) it is not too late for the user to change their address, the "mistyped email?" should be next to the email. It doesn't make sense that one is at the top and the other at the bottom. It lacks context without the address next to it.

**Comment by ryanfeeley** [comment]
@davismtl This screen shows up after the registration form has been submitted. The email has been sent but they have not verified it yet.

**Comment by vpomerleau** [comment]
@ryanfeeley Currently, this screen shows up *after* the user has opened the
confirmation email and clicked on verify email. So they are able to access
the email they entered. If they entered the wrong email, they won't see the
"choose what to sync" page.

As the flow currently is, a back (or "mistake in your email?") button might
make more sense on the "confirm your account" page that is displayed first.

Has this order been A/B tested?
A. Confirm your account --> Choose what to sync
B. Choose what to sync --> Confirm your account

I've seen the opposite order (option B) in an edge case where I created a
new account from previously deleted credentials.

**Comment by davismtl** [comment]
@vladikoff Let's not put this in Next yet. There doesn't seem to be consensus on next steps.

@ryanfeeley @vpomerleau perhaps we do a "Sync Fest" tomorrow to go through this flow together?

**Comment by ryanfeeley** [comment]
@davismtl @vpomerleau Let's do a Sync fest, but as you can see in the video, the CWTS screen follows registration form and not verification. https://youtu.be/3NsCHy-tBWw

**Comment by davismtl** [comment]
Thanks @ryanfeeley for the video.

I will admit that it was my mistake to have not double checked the flow. For some reason after what @vpomerleau had reported, I was under the impression something had changed and the email confirmation came before the settings (which explains point #1 & #2 of my comment). I stand corrected which makes this flow way better than I thought. I have taken the time to go through the flows and also confirm.

Speaking to @vpomerleau , she seems puzzled by how she could have gotten the order confused. She's going to repeat some flows to double check on her end too.

This only leaves point #3 of my comment. If we change "Back" to something like "Mistyped email", IYO does it make more sense to put it at the top next to the email. Also, I realize that the green message fades away too after some time. This could remove the context of the "Mistyped email" message.

See how the green message disappeared:
![screen shot 2017-02-17 at 9 16 36 am](https://cloud.githubusercontent.com/assets/19537086/23076157/207caf8c-f4f4-11e6-85e9-52ef2cf39d53.png)

What are your thoughts?

**Comment by vpomerleau** [comment]
Thanks @ryanfeeley for catching my mistake! I'm not sure how that one happened. I feel like I did see that flow at some point, but I haven't been able to repeat it today. Confirmation bias?

I've corrected the [flow diagram](https://www.lucidchart.com/invitations/accept/8551732f-c40b-482c-a3d5-269bda3f95a8) for this and will double-check the rest of the documented flow.

At the CWTS screen, the confirmation email has already been sent (and the account has been created), but the user likely hasn't tried to access it. Users have two opportunities to notice a mistake in their email address (on CWTS and 'Confirm your account' screens). Should an opportunity for error recovery ('Mistyped email?') be added to both screens?

![confirmaccount_errorrecovery](https://cloud.githubusercontent.com/assets/22231637/23078491/cdf586da-f4fd-11e6-984b-c3c46cf5d6f7.jpg)

Also, as @davismtl mentioned, the green banner sometimes (but not always) disappears. Is this the desired behavior?

**Comment by ryanfeeley** [comment]
This doesn't match the convention we've established elsehwere (where secondary actions are below the primary).

We probably should keep the green bar on this page. @davismtl is mentioned on that related bug.

As an alternative to keep it where it is, we could rewrite the green confirmatio message to include a link. Something like:

* user123 @davismtl domain.com created. [Mistyped email](#)?

Better?

**Comment by davismtl** [comment]
Yes, this seems to work form me.

IIUC, here is the summary:
- keep green bar there (don't allow it to hide)
- Change the copy in the green bar to say: _your@email.com created. Mistyped email?_

Do we think that some users might only detect the mistyped email on the email confirmation step? If so, is there something we could do about @vpomerleau 's recommendation? It might get people to double check their address before they hit "Resend".

**Comment by ryanfeeley** [comment]
@davismtl Worth making into variations and see which one results in improved verification rate?
![variations](https://cloud.githubusercontent.com/assets/68213/24210823/a7f6e66e-0f00-11e7-87e2-196168bf66ef.png)

**Comment by davismtl** [comment]
@ryanfeeley 
I'm unsure it's really worth testing unless a lot of people click on this. 
The one on the left seems more obvious to me than looking to the bottom of the page to fix my email. (but maybe I'm bias)

If you want to test it and we think it's worth the effort, I don't think the verification rate will be our success metric. I think it will be as simple as measuring the difference in clicks between the two variations (on "Mistyped email?").

**Comment by ryanfeeley** [comment]
@davismtl Sure, as long as the green bar persists after the user clicks a checkbox (currently it disappears).

I am also not in love with the term "created" as it's really just held temporarily like a reservation.

What about one of these options:
* user<span></span>@domain.com submitted. [Mistyped email?](#)
* user@<span></span>domain.com reserved. [Mistyped email?](#)
* user<span></span>@domain.com received. [Mistyped email?](#)

**Comment by vladikoff** [comment]
Fixed!

**Comment by shane-tomlinson** [comment]
We never fixed this. :(

**Comment by vladikoff** [comment]
Ah, everyone said we did, but we didn't :(

**Comment by ryanfeeley** [comment]
@vladikoff I swear it was a regression. I will find the screenshots!

**Comment by ryanfeeley** [comment]
Can't find any. It was all a dream.

**Comment by ryanfeeley** [comment]
@davismtl What about:

* user<span></span>@domain.com registered. [Mistyped email?](#)

**Comment by davismtl** [comment]
Sounds good
