### ISSUE TITLE
Manage Account link does not take user to Settings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4748]
It's Tuesday, but this is a standard Monday for me in Nightly OS X at least.

SCREEN RECORDING
https://youtu.be/5OG8CsEtIMM

STEPS TO REPRODUCE
1. Be signed in to Sync, but wait a few days perhaps for some session to expire (?)
2. Click Manage Account

EXPECTED RESULTS
* Be taken to Settings for that user

ACTUAL RESULTS
* Session somehow expires over the weekend (I don't believe I even restarted Nightly)
* User taken to force auth screen
* User required to confirm sign-in
* Upon sign-in confirmation, am taken to Sign-in Confirmed screen, not Settings

**Comment by rfk** [comment]
@ryanfeeley do you do other account-related actions in this browser, e.g. sign in to FxA reliers on the web?

(The good news is that we seem to have a solid plan for resolving this issue, via a patch to Firefox; but I wish I understood how you're able to trigger it so reliably)

**Comment by shane-tomlinson** [comment]
> (The good news is that we seem to have a solid plan for resolving this issue, via a patch to Firefox; but I wish I understood how you're able to trigger it so reliably)

There are a few things that will be guaranteed to put you into this behavior: clear history, reset profile, restricted cookie preferences.

**Comment by ryanfeeley** [comment]
> There are a few things that will be guaranteed to put you into this behavior: clear history, reset profile, restricted cookie preferences.

I never do any of those things. I'll try to replicate with relier soon.

**Comment by ryanfeeley** [comment]
More details 
<img width="1396" alt="screenshot 2017-02-27 13 52 47" src="https://cloud.githubusercontent.com/assets/68213/23374882/253aa756-fcf4-11e6-9f6e-8991432ae86a.png">

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4763
