### ISSUE TITLE
Fix the "created" green bar in mobile view

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4749]
We don't need Choose What To Sync on iOS yet, but may in the future. Currently it looks like the Back link is lacking vertical space, and the green bar is off screen. Not viewed on mobile, but resized my desktop window.
<img width="432" alt="screenshot 2017-02-21 14 40 42" src="https://cloud.githubusercontent.com/assets/68213/23183849/72d8c928-f84b-11e6-89e2-0321bb676699.png">

**Comment by shane-tomlinson** [comment]
> We don't need Choose What To Sync on iOS yet

It's used by Android now though.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - has somebody already fixed this? It looks like this for me:

<img width="426" alt="screen shot 2017-03-02 at 13 34 27" src="https://cloud.githubusercontent.com/assets/848085/23509305/30e4edf4-ff4d-11e6-8c7b-496688de47a9.png">

<img width="331" alt="screen shot 2017-03-02 at 13 35 37" src="https://cloud.githubusercontent.com/assets/848085/23509313/35096e50-ff4d-11e6-874a-a761abd6aad1.png">

**Comment by rfk** [comment]
>  the green bar is off screen

From meeting, this ^ was the remaining concern.

**Comment by ryanfeeley** [comment]
@shane-tomlinson I think the screenshot you posted above is not our smallest size. Firefox desktop window won't even go small enough to show how it looks on iPhone. Best to use inspector, and slide view small or responsive view.

**Comment by vladikoff** [comment]
from mtg: renamed

**Comment by shane-tomlinson** [comment]
Ah yes, I see it now.
