### ISSUE TITLE
Log people that are signing in with only one device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4753]
I'm not sure if we have a way to get this already, but we disabled CAD for people that are signing in because users might have more than one device and the text isn't awesome for those users. We should find out how many users are signing in with only one device so we can properly prioritize work to enable CAD for users who are signing in w/ only a single device.

**Comment by rfk** [comment]
We have a bit of logic on the auth-server to do this for users with an extraordinarily high number of sessions:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L755

We could add something similar to log those users who have zero active sessions, and/or zero device records.

**Comment by vladikoff** [comment]
from mtg: moving to Part 3 of this milestone...

**Comment by vbudhram** [comment]
from mgt: can be find in amplitude
