### ISSUE TITLE
Emit a "profile changed" event to Fx for iOS whenever the user's profile changes.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4755]
For WebChannel capable browsers, we send a `profile:changed` message whenever the user updates their display name or avatar. It looks like Fx for iOS would like to receive a similar notification whenever users open FxA settings from Fx for iOS.

One unknown I'd like to address is how a user will be able to open the settings page from Fx for iOS. The only way I know how to do so is to sign in with an unverified account, verify the account and click "verify email" in Fx for iOS before it has figured out it needs to change state.

cc @st3fan, @sleroux

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1246689

**Comment by st3fan** [comment]
@shane-tomlinson Two questions: should we move account management out of the limited Aettings WebView and just open this in a normal browser tab instead? Does anything change once we have push notifications implemented?

**Comment by shane-tomlinson** [comment]
> Should we move account management out of the limited Aettings WebView and just open this in a normal browser tab instead? 

On an iPad, many operations would look better if settings were opened in a new tab instead of a WebView. For example, profile operations might look cramped in a WebView.

> Does anything change once we have push notifications implemented?

I asked @rfk whether push notifications exist for profile changes, he said "not at this time." https://github.com/mozilla/fxa-features/issues/118 suggests making that a reality, though Ryan mentioned there are some technical challenges.

WebChannel based integrations can rely on a `profile:changed` message that is sent whenever the user updates their profile from the local browser. We could add a similar message to the FirefoxAccountsCommand CustomEvent based channel, though migrating Fx for iOS to WebChannels is preferable from our P.O.V., we'd have one way to communicate with all modern Foxes.

**Comment by vladikoff** [comment]
Push notification stuff landed in https://github.com/mozilla/fxa-features/issues/118
