### ISSUE TITLE
“Your new password must be different” error should be field-specific

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4768]
Discovered during Sync Fest.

“Your new password must be different” error should be field-specific
https://irccloud.mozilla.com/file/5rmX6ADE/new-different.png

**Comment by shane-tomlinson** [comment]
I'm happy to mentor a contributor through this.

**Comment by ryanfeeley** [comment]
Do we have any?

**Comment by shane-tomlinson** [comment]
> Do we have any?

We do! [sms_send.js](https://github.com/mozilla/fxa-content-server/blob/11ca81d767a9262a65172f6e7fa4e2c78b03684c/app/scripts/views/sms_send.js#L138:L144) is the model to follow for this error too.

**Comment by Prathiksha01** [comment]
Hi. I'd like to contribute to this. :))

**Comment by shane-tomlinson** [comment]
Hi @Prathiksha01, thanks for putting your hand up! I haven't thought through all of the details, but my guess is this shouldn't be too difficult. The hardest part of contributing is probably going to be [setting up the development environment](https://github.com/mozilla/fxa-local-dev).

Once that's set up, you are going to want to add an error handler in the [change_password view](https://github.com/mozilla/fxa-content-server/blob/d129a6b6c7b876006edf7753d44c028816cb70c3/app/scripts/views/settings/change_password.js), before the [first `.then` after this.user.changeAccountPassword](https://github.com/mozilla/fxa-content-server/blob/d129a6b6c7b876006edf7753d44c028816cb70c3/app/scripts/views/settings/change_password.js#L47). We use promises, so between the closing `)` and the subsequent `.then(`, insert something like this:

```js
.fail((err) => {
  if (AuthErrors.is(err, 'PASSWORDS_MUST_BE_DIFFERENT')) {
    this.showValidationError(this.$('#new_password'), err);
    return;
  }

  throw err;
})
```

The unit tests will likely need to be updated as well, those are in [app/tests/spec/views/settings/change_password.js](https://github.com/mozilla/fxa-content-server/blob/d129a6b6c7b876006edf7753d44c028816cb70c3/app/tests/spec/views/settings/change_password.js).

If you have any issues, you can stop by our irc channel in irc.mozilla.org the channel is #fxa.
