### ISSUE TITLE
docker: .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4780]
Experiment with the container for this server, I'm getting:

> fxa-content-web_1  | {"Timestamp":1488734612102000000,"Logger":"fxa-content-server","Type":"route.500.Error: Command failed: /bin/sh -c git fetch -v origin dev && git reset --hard FETCH_HEAD\nerror: cannot open .git/FETCH_HEAD: Permission denied\n\n","Severity":2,"Pid":7,"EnvVersion":"2.0","Fields":{"stack":"\nerror: cannot open .git/FETCH_HEAD: Permission denied\n\n\n    at ChildProcess.exithandler (child_process.js:213:12)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n    at Socket.<anonymous> (internal/child_process.js:330:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:487:12)"}}

Besides fixing this I guess it might be useful to also add ENV vars for the experiments section

cc @jbuck

**Comment by vladikoff** [comment]
from mtg: Maybe: we need to pull the experiments dir outside of the container or use /var/tmp?.

Be careful with `root` permissions on the copy. 
"Point it to some dir that we have write permissions for"

**Comment by jbuck** [comment]
What if we pulled in this repo when building the container?

**Comment by vladikoff** [comment]
> What if we pulled in this repo when building the container?

The 'repo' gets pulled every 10 minutes to fetch experiments changes

**Comment by jbuck** [comment]
It should fix the permissions issue & provide a quicker first-start if it was pulled in when building the container

**Comment by vladikoff** [comment]
> It should fix the permissions issue & provide a quicker first-start if it was pulled in when building the container

That might work!
