### ISSUE TITLE
Remove link underline on resend email link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4788]
Spotted on my iPad, and pretty sure link was not focused in any way.
![img_1492](https://cloud.githubusercontent.com/assets/68213/23666935/539d108e-032a-11e7-850c-0fc62718d48f.JPG)

**Comment by apoorvasingh17** [comment]
I would like to work on this issue. Can anyone give me some pointers regarding the same?

**Comment by apoorvasingh17** [comment]
In which file can I find the code to edit this?

**Comment by tameeshB** [comment]
@apoorvasingh17 
A way to start searching for what part of the codebase contains a certain string, you can use this tool called "grep" 
Here's a simple command:
`grep -r 'someText' .`
This command will search for all occurrences of the string "someText" in all files in the present and all subdirectories.
http://opensourceforu.com/2012/06/beginners-guide-gnu-grep-basics-regular-expressions/

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you confirm this still happens? I just tested on the simulator and no underline is displayed:

<img width="375" alt="screen shot 2017-08-18 at 10 18 24" src="https://user-images.githubusercontent.com/848085/29452564-4bdca628-83f6-11e7-8d4c-90434eaed040.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson I could not reproduce on an iPad.

**Comment by shane-tomlinson** [comment]
Thanks @ryanfeeley, closing.
