### ISSUE TITLE
Device Manager Doesn't Recognize Emojis and other special chars

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4790]
During Sync Fest today, we realized that the Beta symbol from Firefox ß displays a question mark in Device Manager.

Also, if you have an emoji in your device name, it also doesn't appear.

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-profile-server/issues/186

**Comment by rfk** [comment]
> dup of mozilla/fxa-profile-server#186

Same underlying bug, but the device-manager

**Comment by rfk** [comment]
> dup of mozilla/fxa-profile-server#186

I'm not 100% sure it is - in theory we should be rejecting any strings that contain characters that would be affected by that bug, but here:

>  the Beta symbol from Firefox ß displays a question mark in Device Manager.

It sounds like we're somehow accepting the string and corrupting it?  I wonder if it's a separate encoding issue between client and server.

**Comment by rfk** [comment]
>  the Beta symbol from Firefox ß displays a question mark in Device Manager.

I tried connecting Firefox release version, then I changed the device name to "Firefox ß", and it appears to be correctly reflected in the device manager:

<img width="424" alt="capture" src="https://cloud.githubusercontent.com/assets/34695/23726789/b1d48224-04a9-11e7-9cf9-8b62864f13ea.PNG">

I wonder if this is an encoding issue, e.g. the browser sending its name in latin-1 instead of utf8.  @davismtl what browser did you test with, desktop or mobile?  On a particular platform?

**Comment by vladikoff** [comment]
> @davismtl what browser did you test with, desktop or mobile? On a particular platform?

@rfk this is Firefox for iOS beta

**Comment by vladikoff** [comment]
@rfk https://github.com/mozilla-mobile/firefox-ios/blob/13186294f11b9bfc3279f94d7497ffcf6691a7a8/Client/Configuration/FirefoxBeta.xcconfig#L5

**Comment by rfk** [comment]
My first guess would be iOS device registration client is submitting that in an incorrect encoding.

**Comment by shane-tomlinson** [comment]
@st3fan, @sleroux - is the character encoding utf-8 being used for device registration on Fx for iOS?

**Comment by davismtl** [comment]
I was using Firefox ß for iOS. I've consistently seen this problem with ios beta in device manager since we launched it but had yet to file a bug.

If it means anything, I uninstall and reinstall beta pretty often. I also log out and back in pretty often for Sync fest.

**Comment by rfk** [comment]
I'm going to dup this to https://github.com/mozilla/fxa-auth-db-mysql/issues/229, which should fix this by storing the special characters in a proper encoding.
