### ISSUE TITLE
Hook up "Send SMS" to auth server's /sms/status endpoint

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4791]
This allows us to gate users based on their country.

Depends on https://github.com/mozilla/fxa-js-client/issues/235.

**Comment by shane-tomlinson** [comment]
Ref #4789

**Comment by rfk** [comment]
For clarity, is this to use the API exposed in https://github.com/mozilla/fxa-js-client/issues/235 ?

**Comment by philbooth** [comment]
> For clarity, is this to use the API exposed in mozilla/fxa-js-client#235?

I think so, yep.

**Comment by vladikoff** [comment]
cc @shane-tomlinson @philbooth to talk about this. from mtg: it would really nice to this in a point release of train-83

**Comment by shane-tomlinson** [comment]
Fixed by https://github.com/mozilla/fxa-content-server/pull/4827, closing.
