### ISSUE TITLE
Can't log in: "Cookies and local storage are required."

### ISSUE THREAD

**Issue by KumaraMonk** [mozilla/fxa-content-server#4796]
Go to any page within https://addons.mozilla.org/
Click on "Log in"

I get

    Cookies and local storage are required.

    Please enable cookies and local storage in your browser to access Firefox Accounts. Doing so will enable functionality such as remembering you between sessions.

    Learn more

As far as I can tell these ARE enabled. All other websites are working fine. No such complains, except for ths site.

(Note: This is the second time I've to move this issue elsewhere. How are people suppose to know the right "department" to submit Mozilla bugs?)

**Comment by vladikoff** [comment]
@KumaraMonk Hello!

Which version of Firefox are you using? Please provide the user agent.
In addition, could you please try to login with a fresh / new Firefox profile without any add-ons or settings tweaks?

**Comment by KumaraMonk** [comment]
51.0.1 (64-bit)
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0

Will safe mode do?

**Comment by vladikoff** [comment]
@KumaraMonk try both, safe mode first, if still fails, then fresh profile. Thanks!

**Comment by KumaraMonk** [comment]
@vladikoff Have you tried logging in to the same to test first?

**Comment by KumaraMonk** [comment]
@vladikoff Never mind. Thanks to @shane-tomlinson, I've set dom.storage.enabled to true, and the problem is solved.

Note: I've no idea what's dom.storage.enabled or how it was set to false.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/1848

**Comment by woctezuma** [comment]
For info, I had this issue as well this morning. The way, I solved it was:
- reboot Firefox in fail-safe mode with all addons deactivated,
- log in,
- see that it works,
- reboot Firefox in normal mode,
- see that I am now already logged in.

Since I have done this, I have tried to log out and log in again in normal mode, and it works now.
