### ISSUE TITLE
[Intermittent] Missing Session Token message on '/sms' page

### ISSUE THREAD

**Issue by kkumari22** [mozilla/fxa-content-server#4802]
Prerequisite: Existing SessionToken
STR:
1. Navigate to 'https://accounts.firefox.com/sms?service=sync'
2. Enter mobile number
![missing session token](https://cloud.githubusercontent.com/assets/16670573/23773279/58f93b0c-04d3-11e7-9737-be8b0f8bb949.PNG)
 in phone number field
3. Click send

Expected: There should not be "Missing sessionToken" error message

Actual: "Missing sessionToken" error messages appears intermittently

**Comment by shane-tomlinson** [comment]
Missing sessionToken is an error returned by the fxa-js-client.

**Comment by vladikoff** [comment]
I did 2 tests with clean local storage and with different query params. Seems like this issue was fixed. It could have been caused by opening a service=sync window without a session.
