### ISSUE TITLE
Mock out SMS sending for functional tests.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4807]
Right now a subset of functional tests [are only run if a test number is configured](https://github.com/mozilla/fxa-content-server/blob/8a2c5e7b98a4182ec10d7f351162e9c3fee46e7c/tests/functional/send_sms.js#L135), with the side effect these tests are not run on Circle (and probably not on latest either). In addition, we had to introduce a [10 second delay](https://github.com/mozilla/fxa-content-server/blob/8a2c5e7b98a4182ec10d7f351162e9c3fee46e7c/tests/functional/send_sms.js#L165) to avoid running afoul of Nexmo rate limiting, which is yuck.

A better solution is to mock out sending the SMS for most functional tests, perhaps flagged by a query parameter. We'd still want to exercise the integration with the auth-server, so perhaps [this test](https://github.com/mozilla/fxa-content-server/blob/8a2c5e7b98a4182ec10d7f351162e9c3fee46e7c/tests/functional/send_sms.js#L122) and [this test](https://github.com/mozilla/fxa-content-server/blob/8a2c5e7b98a4182ec10d7f351162e9c3fee46e7c/tests/functional/send_sms.js#L157) could still make the auth-server call to send the SMS.

**Comment by vladikoff** [comment]
Done!
