### ISSUE TITLE
In Settings, make Add… buttons blue

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4818]
So that I can more easily see what is incomplete in my set-up, as an FxA user, provide a more immediate indication of which section is currently missing data.
a.k.a. Apply primary button style to the **Add…** button.
![add-user-blue](https://cloud.githubusercontent.com/assets/68213/24061530/2685db24-0b2e-11e7-9a5b-50b6ad89b029.png)

**Comment by sunakshi96** [comment]
Hii 
I would Like to claim this issue :-)

**Comment by sunakshi96** [comment]
But the problem https://github.com/mozilla/fxa-local-dev doesnt contain this file. :-)

**Comment by vershwal** [comment]
Hello @sunakshi96 
Firstly you need to install all the dependencies and set up the server locally for which you can follow the steps as mentioned [here](https://github.com/mozilla/fxa-local-dev). Then you will be able to change the script and style files and see the changes locally.
The code structure is great, you will definitely love to contribute here.

**Comment by sunakshi96** [comment]
@vershwal thankyou.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you explain a bit about why? I don't fully get it. Do the colors return to grey once the user has performed the action?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Sure! The idea is to highlight the areas that are not complete (and likely re-order them in a different issue).

Similar to an intentional gap:
http://ui-patterns.com/patterns/Intentional-gaps/examples/17018

Probably closest would be this "Add a workspace" example in Facebook:
![best_screen_shot_2014-12-29_at_14 08 38](https://cloud.githubusercontent.com/assets/68213/24209495/dc17c106-0efc-11e7-9624-751e66729201.jpg)

**Comment by vladikoff** [comment]
Existing PR to fix this here: https://github.com/mozilla/fxa-content-server/pull/4823/files
