### ISSUE TITLE
Can't install fxa-content-server-l10n: status code 406

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-content-server#4819]
Using node v4.5.0 (npm v2.4.1) as recommended on [fxa-local-dev](https://github.com/mozilla/fxa-local-dev#dependencies), running `npm install` gives me:

> npm ERR! fetch failed https://github.com/mozilla/fxa-content-server-l10n.git#master
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406

**Comment by vladikoff** [comment]
@eoger ah I think this is due to old npm / node

**Comment by eoger** [comment]
Funny thing is in [fxa-auth-mailer](https://github.com/mozilla/fxa-auth-mailer/blob/master/scripts/download_l10n.sh) we don't have this problem because we use a git:// URL.
