### ISSUE TITLE
"SMS sender address illegal" in prod

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4825]
![image](https://cloud.githubusercontent.com/assets/128755/24109657/baf7d272-0d67-11e7-9917-f47162d4f202.png)

**Comment by jbuck** [comment]
This is because we deployed train-82 with the updated stage & prod Nexmo credentials, but did not change the sender ids, which are dev-only.

**Comment by jbuck** [comment]
Fixed on stage, deploying to prod now

**Comment by jbuck** [comment]
Fixed on prod.
