### ISSUE TITLE
Revisit server validation rules

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4830]
We need to clean up and maybe relax the validation rules a bit. 
Sentry reports that some rules are too strict as well.

For example utm params can have a `/` in them

Ref: https://github.com/mozilla/fxa-content-server/pull/4794#discussion_r105194533

**Comment by vladikoff** [comment]
@shane-tomlinson is reporting that something like `firefox/sync` is gonna be dropped

**Comment by vbudhram** [comment]
Revisit during workweek...

**Comment by rfk** [comment]
Feels like we did a bunch of this work recently, can this be closed?

**Comment by vladikoff** [comment]
Affirmative!
