### ISSUE TITLE
Losing styles in Chrome on Refresh

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4831]
# STR

* Open Chrome in incognito 
* Go to https://accounts.firefox.com
* Right click on the page, click inspect
* reload the page using the Reload button in chrome

## Error

```
Access to CSS stylesheet at 'https://accounts.cdn.mozilla.net/styles/adb16cbb.en.css' from origin 'https://accounts.firefox.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://accounts.firefox.com' is therefore not allowed access.
```

#### ⚠️  The gif below goes to a different route than STR, please ignore that.

![](http://imgur.com/iQ78H4q.gif)

**Comment by seanmonstar** [comment]
This happened the very first time I tried it, but closing Chrome and trying again and I can no longer reproduce.

**Comment by vladikoff** [comment]
Closing for now, seems fixed
