### ISSUE TITLE
Fix validation log in fxa-content-server.js

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4841]
This code

```js
      logger.error({
        error: err.details.map(details => details.message).join(','),
        op: 'validation.error',
        path: req.path,
      });
```

In https://github.com/mozilla/fxa-content-server/blob/b0ff599099f50dd4f5d17eec9977db5080f011a4/server/bin/fxa-content-server.js#L161

Needs to be `logger.error('validation.error', { ...object here...})` to properly log. Otherwise you get this:

> {"Timestamp":1490211703294000000,"Logger":"fxa-content-server","Type":"server.main.[object Object]","Severity":2,"Pid":99881,"EnvVersion":"2.0"}

**Comment by sunakshi96** [comment]
So the object here is the details like error, op and path in first instance?

**Comment by vladikoff** [comment]
@sunakshi96 object would have `error` and `path`. op is moved to be the first argument to `.error`

**Comment by sunakshi96** [comment]
I would like to fix this bug!

**Comment by vladikoff** [comment]
@sunakshi96 okay!
