### ISSUE TITLE
[stage] faiing/flakey tests with train-83 on stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4847]
Failures in 6 runs:
- [x] 6/6 visit gravatar with gravatar set
- [ ]  6/6 sign up, wait for confirmation screen, click resend
   - merged a fix to see proper logs https://github.com/mozilla/fxa-content-server/commit/27c7797e9017b95af9307a44df0fcd9ce0ffae3a
- [x] 6/6 refreshing the signup screen ([Fixed 4850](https://github.com/mozilla/fxa-content-server/pull/4850))
- [x] 3/6 with an unregistered email ([Fixed in 4853](https://github.com/mozilla/fxa-content-server/pull/4853))
- [x] 3/6 signup, verify different browser, verification_redirect=always (Fixed in https://github.com/mozilla/fxa-content-server/pull/4869)
- [x] 3/6 rp listed in apps, can be deleted ([Fixed in 4853](https://github.com/mozilla/fxa-content-server/pull/4853))
- [x] 2/6 signup, same browser different window, verification_redirect=always  (Fixed in https://github.com/mozilla/fxa-content-server/pull/4869)
- [ ] 2/6 reset password with a restmail address, get the open webmail button
- [ ] 1/6 verified, verify same browser
- [ ] 1/6 signin with an unknown account does not allow the user to sign up
- [ ] 1/6 sign up Fx Desktop, verify in Android Chrome

Clearly something wrong with 3 `6/6` tests; then some flakiness.

**Comment by jrgm** [comment]
On latest (with master, nothing changed during test runs), failures in 6 runs:

6/6 refreshing the signup screen
5/6 with an unregistered email
5/6 rp listed in apps, can be deleted
4/6 visit gravatar with gravatar set
4/6 signup, verify different browser, verification_redirect=always
3/6 signup, same browser different window, verification_redirect=always
2/6 visit gravatar with gravatar set
2/6 signin with an unknown account does not allow the user to sign up
1/6 signup, verify same browser
1/6 signin without `prompt=consent`, then re-signin with `prompt=consent`

**Comment by vladikoff** [comment]
The `6/6 sign up, wait for confirmation screen, click resend` has stack:

>  [sign up, wait for confirmation screen, click resend] TypeError: callback.call is not a function
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:545:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.sign up, wait for confirmation screen, click resend [as test]  <tests/functional/confirm.js:56:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

**Comment by shane-tomlinson** [comment]
teamcity uses Centos to run Selenium

**Comment by shane-tomlinson** [comment]
> 6/6 firefox on any platform: Firstrun Sync v2 sign_up sign up, verify same browser, force SMS

Is SMS enabled on stage?

**Comment by philbooth** [comment]
> > 6/6 firefox on any platform: Firstrun Sync v2 sign_up sign up, verify same browser, force SMS
> 
> Is SMS enabled on stage?

I have a nagging sense that [this mistake](https://github.com/mozilla/fxa-auth-server/pull/1766#issuecomment-289530464) on my part means we might need to uplift part of the assiciated fix to the train 83 auth server:

> After adding `countryCode` to fxa-geodb, I completely forgot to propagate it through our wrapper module, `lib/geodb.js`.

I'll open a PR against train 83 with just that fix in, and we can discuss in that PR whether it's needed.

**Comment by shane-tomlinson** [comment]
For Firstrun Sync v2 sign_up, ref https://github.com/mozilla/fxa-auth-server/pull/1778

**Comment by jrgm** [comment]
I picked up auth-server v1.83.3 in stage. Good news. One functional test run passed every single test! (561/561). Another run had 6 failures, below:

- firefox on any platform: Firefox Desktop Sync v2 sign_in verified, verify different browser - from original tab's P.O.V.         
- firefox on any platform: Fx Fennec Sync v1 sign_in 
- firefox on any platform: Fx Fennec Sync v1 sign_in blocked, valid code entered        
- firefox on any platform: Fx Fennec Sync v1 sign_in unverified     
- firefox on any platform: Fx Fennec Sync v1 sign_in verified, verify same browser   
- firefox on any platform: FxiOS v1 sign_in signin with an unknown account does not allow the user to sign up       
- firefox on any platform: oauth signup signup with existing account, coppa is valid, credentials are wrong

**Comment by vladikoff** [comment]
We fixed around half of these, there are now separate bugs for left over issues
