### ISSUE TITLE
running functional tests on ubuntu; tab crash => message about WebChannelMessageToChrome?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#4854]
A few times running functional tests in an Ubuntu VM, I get a tab crashed page and the tests stop.

In Browser Console, I see `WebChannelMessageToChrome sent with an object from a non-whitelisted principal`, which may or may not be related. Mean anything to anyone? The page is `https://accounts.stage.mozaws.net/verify_email?uid=...`.

**Comment by vladikoff** [comment]
>  I get a tab crashed page and the tests stop.

Out of RAM?

> WebChannelMessageToChrome sent with an object from a non-whitelisted principal,

@jrgm The profile probably needs to be configured for stage to make sure you don't see that error. Some settings here: https://github.com/vladikoff/fxa-dev-launcher/blob/master/profile.js#L70-L106

**Comment by shane-tomlinson** [comment]
@jrgm - that's suspicious, it sounds like you are using an old version of Firefox. We stopped [sending Objects over WebChannels in Fx >= 50](https://github.com/mozilla/fxa-content-server/blob/b78a26cff66f9b978e343414007aaa9d20bfdae2/app/scripts/lib/channels/senders/web-channel.js#L111:L117). If you are using Fx < 50, you need to add FxA to about:config's `webchannel.allowObject.urlWhitelist` - see [this bit in the fxa-dev-launcher](https://github.com/vladikoff/fxa-dev-launcher/blob/a1910b881886e9ef929bd16cd9c1d3871c026c11/profile.js#L106)

**Comment by jrgm** [comment]
I was running 50.1.0

**Comment by jrgm** [comment]
`latest` and `stage` both take the profile configured in https://github.com/mozilla/fxa-content-server/blob/master/tests/intern.js#L45-L85. Do you mean that something required by the ./tests/**/* is missing in that config?

**Comment by vladikoff** [comment]
oh maybe, we should check locally

**Comment by shane-tomlinson** [comment]
Closing until we see this again.
