### ISSUE TITLE
Firefox Android is having trouble with signin confirmation

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4857]
Ref: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/382411/tags/browser/?cursor=3249879%3A0%3A0

Seems like a lot of system unavailable messages

![](https://i.imgur.com/6Obvj1K.png)

**Comment by vladikoff** [comment]
Setting P1

**Comment by seanmonstar** [comment]
Without a user/password to sentry, we can't see anything about the report. Could we post back any relevant information back to this issue?

**Comment by vladikoff** [comment]
>Could we post back any relevant information back to this issue?

Sure! I looked at some of the details. 

Around 400 reports of this issue daily (10% sample I think). 
The error code `errno` is 1039. This right here: https://github.com/mozilla/fxa-content-server/blob/b5942aee40bae4adcd8374a2e55e4c0e626ea841/app/scripts/views/confirm.js#L128

82% of this error is on Firefox Mobile.

Affected views: confirm 45%, confirm-signin 55%
Smartphone: 52% , Tablet: 46%, + Other

Android version 4 and up

Seems to suggest that this is an issue with polling. 

<img src=https://user-images.githubusercontent.com/128755/28837824-2fa50df2-76bc-11e7-908a-baa21c12c58d.png width=250 />

**Are spotty mobile connections to blame for this?** Maybe polling is too fast for mobile internets?

**Comment by seanmonstar** [comment]
It could be that the network failed on the device. I see in the code that the error is simply reported and polling resumes, so this may not actually impact users at all.

It'd probably be a good idea to adjust the `this.logError` call to include the original error. The original error includes the status code, which could be `0` if there is a network error (error occurs in firefox, not from server).

**Comment by vladikoff** [comment]
Closing for now, the error is not user visible, just polling fail, probably due to slow mobile networks
