### ISSUE TITLE
Add descriptions to Choose What to Sync

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#4863]
Users don't understand what syncing passwords and tabs mean.
Users don't know that history includes forms.

Let's make "Choose what to sync" clear.

@ryanfeeley, you did a mockup when we were in Toronto based on iCloud sync preferences. Still have it?

**Comment by ryanfeeley** [comment]
I discussed this with Michelle a while ago. She felt that in this case, less is more. Adding 6 descriptions to 6 checkbox options on a small page is likely too much to take in. This page also has very little drop off. In the past month, over 94% of the people who see it submit it.

**Comment by davismtl** [comment]
If less is more, then let's remove sync options.

If we're going to keep sync options, then let's make sure users understand.

I propose we test it. The design you had looked great. Do you still have it?

**Comment by ryanfeeley** [comment]
@davismtl I couldn't find it, but will recreate if needed. Wasn't hard.

**Comment by davismtl** [comment]
@ryanfeeley please do re-make it. I think it helps to look at it to determine "how busy" it will be.

**Comment by vladikoff** [comment]
@ryanfeeley do we still want to do this?

**Comment by ryanfeeley** [comment]
@davismtl @vladikoff I renamed "Add-ons" to "Extensions & themes", tweaked the sizing, changed the heading, and added one line to describe it. I'm also going to have @mheubusch take a look.

Thoughts?
![choose-what-to-sync](https://user-images.githubusercontent.com/68213/28474773-cfc1be32-6e17-11e7-850e-44c14cb65ecd.png)

**Comment by vladikoff** [comment]
for competition, the new graphic is : 

<img src=https://user-images.githubusercontent.com/128755/28475366-cd5fb912-6e19-11e7-8985-71fc334927b5.png width=450 />

**Comment by ryanfeeley** [comment]
And hopefully soon animated!
![sync devices](https://user-images.githubusercontent.com/68213/27445236-00315b46-5747-11e7-8967-f77694bc2d6d.gif)

**Comment by davismtl** [comment]
Thoughts:

- I love the animation. Really cool and simple.
- If you are going to rename some of them, History could maybe become **History & Forms** to be more accurate
- I'm not fond of the text that you proposed. Maybe... "Choose which data of yours you want accessible everywhere you use Firefox. We encrypt everything for your security." I'm not even a fan of this but... Put value prop first, mention encryption after.
- How could we add details about each sync element? What are **open tabs**? Users often ask" "Will this mean when I open something it will open everywhere else?" Another example of what we here "If I select **History** will it make it easier for sites to target me with ads?" (#1 reason for not selecting history) And of course "What the hell are add-ons/extensions? I don't need those."

**Comment by vladikoff** [comment]
from mtg: for next 2 weeks to figure out cc @ryanfeeley @davismtl

**Comment by vladikoff** [comment]
@ryanfeeley any updates on this?

**Comment by vladikoff** [comment]
@ryanfeeley is not sold on this.

**Comment by davismtl** [comment]
@Rfeeley does the solution need to be identical for mobile and desktop?

For example, could we use a tool tip to add the description on desktop (which works well with a mouse) but for mobile, we just put the description below the engine in a scrollable list? Mobile tends to be more friendly to scrolling.

**Comment by rfk** [comment]
If we don't want to add text inline in the page, can we add some sort of "learn more" link that goes to SUMO article with descriptions of each item?

**Comment by rfk** [comment]
Also, adding some context from the waffle triage meeting:  we moved this into "blocked" because it's on our Q3 OKR list, but there doesn't seem to be any agreement about how to move it forward.  Let's make a point of discussing this in the product meeting on Thursday if we can't come up with something beforehand.

**Comment by davismtl** [comment]
update:
@ryanfeeley and I discussed. He will explore something similar to my previous comment.

> For example, could we use a tool tip to add the description on desktop (which works well with a mouse) but for mobile, we just put the description below the engine in a scrollable list? Mobile tends to be more friendly to scrolling.

**Comment by vladikoff** [comment]
from mtg: @ryanfeeley is working on this

ux feedback: add hover for the options. on mobile, try inline, needs update.

**Comment by davismtl** [comment]
I create a feature card for this here:
https://projects-beta.growthhackers.com/cards/add-descriptions-to-sync-engines-in-cwts/1zv1g_nkjvkNj9fX1gS9Zw

We should make a feature document for this too. I'll try to schedule a kick-off.

**Comment by vladikoff** [comment]
from mtg: in the works!

**Comment by davismtl** [comment]
Feature document in the works: 
https://docs.google.com/document/d/1gEet2W5Z0zllza4_dqM-BCovi3NnM9o6ReWUbfCrzCs/edit#

**Comment by vladikoff** [comment]
from mtg: new copy and stuff, see doc above ^^

**Comment by vladikoff** [comment]
from mtg: i'm back. "we are stuck in a box"

**Comment by ryanfeeley** [comment]
I love the copy, but it won't fit in the box and I don't want to drop the animation.
<img width="854" alt="firstrun" src="https://user-images.githubusercontent.com/68213/32195633-37ef61dc-bd94-11e7-8627-46e746d9f2ec.png">

**Comment by davismtl** [comment]
@ryanfeeley Would it be acceptable put the checkboxes on 2 columns? (even though we have odd numbers in 2 sections)

**Comment by ryanfeeley** [comment]
@davismtl I tried that first, but it makes the page unreadable. Do you think we could split them into three steps? Even as an experiment?

**Comment by davismtl** [comment]
@ryanfeeley I would prefer to avoid putting it on 3 steps. 

Why is "skip this step" displayed here? Shouldn't that be done? Wouldn't that give us the room we need?

**Comment by rfk** [comment]
> Why is "skip this step" displayed here?

The "why" here is "because that button lives in the surrounding page, not in our iframe".  We have a couple of ways we could proceed in order to make it disappear, but they're all non-trivial (not outright *hard*, but not as easy as just hiding the button).

**Comment by shane-tomlinson** [comment]
I realize this was discussed and decided upon many moons ago, my memory fails me in middle-age. What are the reasons for showing CWTS? Would the world end CWTS was not displayed by either FxA or the browser? Could we skip the step and allow users to deselect from about:preferences#sync, or bring back the checkbox on signup that allows users to display CWTS if they so choose? If we skipped the screen and instead displayed it post-verification, would signup registration rates improve?

I want to be be clear myself that we are going down this Sync rabbit hole for the right reasons. I worry that in the future when new Sync buckets are added, none of the proposed solutions are going to look very good.

**Comment by vladikoff** [comment]
>What are the reasons for showing CWTS? 

One of the reasons was to make users understand what they are signing up for.
(The other reason was to get rid of the scary native Firefox dialog that was there after sign up :) )

**Comment by shane-tomlinson** [comment]
> (The other reason was to get rid of the scary native Firefox dialog that was there after sign up :) )

This is what I am questioning when I ask "Would the world end (if) CWTS was not displayed by either FxA or the browser?"

**Comment by ryanfeeley** [comment]
@shane-tomlinson The world would end for people who don't automatically want all their passwords uploaded to a cloud service they know little or nothing about. But really it's more about helping users know what they are signing up for. When we had a simple "Choose what to sync" button on registration, most people clicked on it. That's a strong signal.

**Comment by davismtl** [comment]
I think it needs to remain there but I think we can do better since the list of engines is getting longer.

Chrome links to it but doesn't display everything in their flow by default.

<img width="713" alt="chrome" src="https://user-images.githubusercontent.com/19537086/32457455-0de7b674-c2de-11e7-9dc2-ccbb018b1142.png">

**Comment by rfk** [comment]
> The world would end for people who don't automatically want all their passwords
> uploaded to a cloud service they know little or nothing about.

Right, pretty much this - if we don't ask before the syncing actually starts, then users who may have privacy concerns with specific datatypes will have to race with sync to disable those datatypes in the preferences UI before it uploads them as part of the first sync.  I don't think many users fall into that camp, but the ones that do care a whole awful lot about it.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson The world would end for people who don't automatically want all their passwords uploaded to a cloud service they know little or nothing about. But really it's more about helping users know what they are signing up for. When we had a simple "Choose what to sync" button on registration, most people clicked on it. That's a strong signal.

It is a strong signal, but it's only one signal. We haven't tested others, and we shouldn't stop until we have tested others! We know each additional screen causes ~ 6% drop in signup, can we remove the screen for the majority of users and bump the signup rate by 6%?

> Right, pretty much this - if we don't ask before the syncing actually starts, then users who may have privacy concerns with specific datatypes will have to race with sync to disable those datatypes in the preferences UI before it uploads them as part of the first sync. I don't think many users fall into that camp, but the ones that do care a whole awful lot about it.

I buy this argument, though I do not buy that the approach we are using is optimal. My feeling we optimize too heavily for the privacy concerned camp to the detriment of the majority. I'd bet money CWTS causes confusion and hurts signup rates, and with the descriptions, we are going to cause more confusion and hurt signup rates further. The problem can only worsen as new buckets are added.

I propose we optimize for the majority. Allow the privacy concerned camp to make changes, but force them to go through an extra hoop.

Concretely, re-add a checkbox on the signup page, the checkbox is checked by default. The label would be something along the lines of "Sync everything including history, passwords, form data, etc."

Users that keep the box selected skip CWTS. Users that de-select the box go through CWTS.

**Comment by vbudhram** [comment]
from uno: team discussed and decided to close
