### ISSUE TITLE
Does anyone use "verification_redirect=always"`?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4870]
If not, I suggest we kill it. The tests are crazy complex, IIRC, the code to implement it was complex too, and I'm not smart enough to keep how it works in my head. Was this for Hello? For Pocket?

cc @vladikoff, @rfk

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/4847

**Comment by rfk** [comment]
It was originally added for pocket IIRC, and nobody else was using it.  We could walk through their current signup flow and see if it's still used.  Can we tell metrics on current usage from e.g. content-server HTTP logs?

**Comment by vladikoff** [comment]
`verification_redirect` to me feels like the 'default' oauth behaviour. We might also need this for web extensions. However, I'm not opposed to removing it 🗡

**Comment by shane-tomlinson** [comment]
I looked in Kibana for `verification_redirect`, it's being used by testpilot.firefox.com though I thought they removed FxA integration.

**Comment by rfk** [comment]
>  I thought they removed FxA integration.

They definitely did
