### ISSUE TITLE
`resume` being flagged as invalid

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4885]
See https://sentry.prod.mozaws.net/operations/content-express-server-dev/issues/385251/events/10099594/

resume tokens end with `=` or `==`, not just alphanum. There isn't yet a type for this in [server/lib/validation.js](https://github.com/mozilla/fxa-content-server/blob/fe500604eaaeaa7f0736c044280cf335f7ae3d1f/server/lib/validation.js), but we should make one so it's validated the same way everywhere.

**Comment by shane-tomlinson** [comment]
I only realized after the fact I was looking at the dev reports. I don't see the same problem on prod.

**Comment by vbudhram** [comment]
Closed via https://github.com/mozilla/fxa-content-server/pull/4956
