### ISSUE TITLE
Sometimes failing functional tests leave a window open

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4896]
Some tests open a 2nd window, then check the contents of that window. If the test fails, then the 2nd window remains open. This can cause cascading failures down the road.

We should ensure we close all windows except for the original window on test teardown. Perhaps this can be done as part of `clearBrowserState` since all tests call it.

**Comment by vladikoff** [comment]
> We should ensure we close all windows except for the original window on test teardown. Perhaps this can be done as part of clearBrowserState since all tests call it.

👍
