### ISSUE TITLE
Setup a new secret validation key for server validation

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#4901]
We had to disable content server account validation in train-83. Let's setup a new key so we can avoid getting rate limited by the customs server

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-content-server/blob/fe500604eaaeaa7f0736c044280cf335f7ae3d1f/server/lib/configuration.js#L153

**Comment by shane-tomlinson** [comment]
@vladikoff - do we still need this?

**Comment by vladikoff** [comment]
Closing for now!
