### ISSUE TITLE
Ensure the parsing library works with the new Fx for iOS UA string format

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4908]
Ref https://github.com/mozilla/fxa-auth-server/pull/1787#discussion_r109521184
Ref https://github.com/mozilla-mobile/firefox-ios/pull/2556

**Comment by davismtl** [comment]
Don't know if this is related: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1355902

**Comment by vladikoff** [comment]
Did some tests on this and it seems to be working correctly.  We also are able to detect the browser on the front-end here: https://github.com/vladikoff/ua-parser-js/blob/643d1698aef5bed095e1264ae258902bf346175c/src/ua-parser.js#L252
