### ISSUE TITLE
flaky functional test on Circle/TeamCity - signup with existing account, coppa is valid, credentials are wrong

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4910]
See https://circleci.com/gh/mozilla/fxa-content-server/6598#tests/containers/1

> × firefox on any platform - sign_up - signup with existing account, coppa is valid, credentials are wrong (18.315s)
ScriptTimeout: [POST http://localhost:4444/wd/hub/session/166c64cf-3f7e-45d6-b73a-edd59bf6c5ac/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t\t(function poll() {\n\t\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse {\n\t\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t})();\n\t\t\t\t\t}).apply(this, arguments);","args":["return (function (selector, options) {\n      var $matchingEl = $(selector);\n\n      if ($matchingEl.length === 0) {\n        return null;\n      }\n\n      if ($matchingEl.length > 1) {\n        throw new Error('Multiple elements matched. Make a more precise selector - ' + selector);\n      }\n\n      if (! $matchingEl.is(':visible')) {\n        return null;\n      }\n\n      if ($matchingEl.is(':animated')) {\n        // If the element is animating, try again after a delay. Clicks\n        // do not always register if the element is in the midst of\n        // an animation.\n        return null;\n      }\n\n      return true;\n    }).apply(this, arguments);",[".error a[href=\"/signin\"]",{}],10000,67]}] Timed out
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-107-generic', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, firefox_binary=/home/ubuntu/fxa-content-server/firefox/firefox, acceptSslCerts=false, processId=22612, browserVersion=50.1.0, platformVersion=3.13.0-107-generic, name=tests/intern_functional_circle, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIACWXhkoAAAAAAAAAA...}]
Session ID: ac020db9-2197-4b90-898c-123c629c27b6
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at ProxiedSession.Session.executeAsync  <node_modules/intern/node_modules/leadfoot/Session.js:736:15>
  at <node_modules/intern/node_modules/leadfoot/helpers/pollUntil.js:90:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:70:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.signup with existing account, coppa is valid, credentials are wrong [as test]  <tests/functional/sign_up.js:240:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:489:9>
  at process._tickCallback  <node.js:418:13>

https://tc-test.dev.lcip.org/viewLog.html?buildId=9358&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests#testNameId5439616669097800699

**Comment by vladikoff** [comment]
FixeD!
