### ISSUE TITLE
Move to L20n

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#4920]
It's the future! Also, it's design helps with an issue we ran into, where need the phrase "Sign In" in 2 different tenses as un #4916.

Test Pilot is an example app we can look at that is using with Pontoon.

**Comment by vladikoff** [comment]
@mathjazz  is this a good idea? or is there something else we should use?

**Comment by mathjazz** [comment]
Deferring to @stasm and @zbraniecki.

**Comment by shane-tomlinson** [comment]
Can experiment to prove that a wholesale change saves dev time or fixes current problem/warts? The current l10n infrastructure is so deeply embedded that'd it'd take significant engineering effort to re-tool. 

We haven't run into any insurmountable engineering problems, integration is pretty well figured out, extraction and import works well, there is no performance hit of loading external scripts/resources, and the ongoing maintenance costs are fairly minimal.

**Comment by vladikoff** [comment]
Agreed with @shane-tomlinson. Let's reopen if there is some solid reasoning to move to `.ftl` files

**Comment by stasm** [comment]
Thanks for considering FTL, still :) We're in the process of splitting L20n into smaller modules. The initiative is called Project Fluent: http://projectfluent.io/  It already supports node.js environments better than L20n does.  The separation into smaller single-purpose modules will make it easy to add support for Handlebars in the future.

Once Project Fluent matures I'd love to have another conversation about using it in Firefox Accounts, provided it brings improvements to your and localizers' workflow.

**Comment by vladikoff** [comment]
> Once Project Fluent matures I'd love to have another conversation about using it in Firefox Accounts, provided it brings improvements to your and localizers' workflow.

@stasm that would excellent 👍 . Let's revisit that in the future!
