### ISSUE TITLE
"Internal server error" when running Firefox Desktop Sync v3 sign_in - verified, verify different browser - from original tab's P.O.V.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4922]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=9531&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

<img width="1117" alt="screen shot 2017-04-11 at 14 09 44" src="https://cloud.githubusercontent.com/assets/848085/24910739/a41ea340-1ec0-11e7-8b25-840751857494.png">

Line 105 of sync_v3_sign_in.js is "openVerificationLinkInDifferentBrowser" - we are making an XHR request to verify the user's email.

**Comment by shane-tomlinson** [comment]
This looks like an auth-server problem, logging it here to begin with, will migrate as necessary or when we fix the problem there.

**Comment by vladikoff** [comment]
@jrgm can we verify that these are not server restarts ? for example if db takes longer than 10 seconds to restart then requests will timeout

**Comment by shane-tomlinson** [comment]
I haven't seen this problem since, closing.
