### ISSUE TITLE
Flaky functional test - oauth sign_in - unverified, acts like signup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4925]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=9417&tab=buildResultsDiv&buildTypeId=fxa_Latest6Tests#testNameId1397757965510096122

> CancelError: Timeout reached on firefox on any platform - oauth sign_in - unverified, acts like signup at null._onTimeout <node_modules/intern/lib/Test.js:141:20> at Timer.listOnTimeout <timers.js:92:15> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Command.finally <node_modules/intern/node_modules/leadfoot/Command.js:566:15> at <node_modules/intern/lib/Test.js:216:37> at Promise.cancel <node_modules/intern/browser_modules/dojo/Promise.ts:343:37> at null._onTimeout <node_modules/intern/lib/Test.js:143:21> at Timer.listOnTimeout <timers.js:92:15>

**Comment by vladikoff** [comment]
Seems fine for now
