### ISSUE TITLE
"To continue to Firefox Sync" not mentioned on /force_auth

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4928]
Found during Sync Fest!

Compare and contrast:

### signin

<img width="467" alt="screen shot 2017-04-11 at 16 26 49" src="https://cloud.githubusercontent.com/assets/848085/24917058/de7b41ac-1ed3-11e7-8d0c-d73460f8a754.png">

### force_auth

<img width="459" alt="screen shot 2017-04-11 at 16 27 06" src="https://cloud.githubusercontent.com/assets/848085/24917063/e1dc8644-1ed3-11e7-8e97-1c434842e4f8.png">

@ryanfeeley - what should the force_auth screen look like? Should we mirror the /signin page above the profile image?

**Comment by vladikoff** [comment]
from mtg: let's add the copy to force_auth

**Comment by aayushis12** [comment]
Hi, I would like to work on this bug as my first bug. Please assign and provide further details on the same.

**Comment by ryanfeeley** [comment]
👍 Let's do it.

**Comment by vladikoff** [comment]
@aayushis12 Please see the two templates here: 

![image](https://user-images.githubusercontent.com/128755/28542824-a4ef5e5a-708b-11e7-917b-bce20a154314.png)

You need to make the changes to the  `force_auth` template and add the "continue to Firefox Sync"  string, just like it is in the other templates.

To quickly get started see https://github.com/mozilla/fxa-content-server#quick-start and the rest of the document. You also need to write / add a test into this file: https://github.com/mozilla/fxa-content-server/blob/5f1af068cf9c35ae4da28143750bf8f91fc5ae2d/app/tests/spec/views/force_auth.js#L618 and verify that the template has new string.

**Comment by aayushis12** [comment]
Hi, I am a beginner. Please guide me a little bit. Thanks.

**Comment by rfk** [comment]
@aayushis12 so the first step will be to get a local checkout of this repository up and running to develop with.  You'll need to ensure you have installed the dependencies listed here:

  https://github.com/mozilla/fxa-local-dev#dependencies

Then follow the steps described here to get a copy of the code and run the server locally:

 https://github.com/mozilla/fxa-content-server#quick-start

And if you get all that running, you should be able to open http://127.0.0.1:3030 in your browser and see a working local copy of the Firefox Accounts website.  From that point we can get you set up to modify and test the above templates.

If you get stuck at any point please ask a specific question and we'll try to get you pointed in the right direction.

**Comment by aayushis12** [comment]
Hi,
Is there a way to install GMP on Windows.I tried Cygwin but I am stuck there and don't know exactly how to continue further.

**Comment by shane-tomlinson** [comment]
> Is there a way to install GMP on Windows.I tried Cygwin but I am stuck there and don't know exactly how to continue further.

@seanmonstar - any tips? Have you successfully set up FxA on Windows?

**Comment by rfk** [comment]
For the purposes of this bug, I think it may also be OK just to skip GMP, it's needed by some other parts of the system but not by fxa-content-server if I recall correctly.

**Comment by aayushis12** [comment]
I get the error 'scripts is not recognised as an internal or external command' when I execute npm run start-remote. Why is that coming?

**Comment by vladikoff** [comment]
@aayushis12 this probably means your node.js installation is not properly configured on your machine

**Comment by aayushis12** [comment]
@vladikoff but when I do node -v in my command prompt then it runs fine.

**Comment by vladikoff** [comment]
@aayushis12 what about `npm -v `?

**Comment by aayushis12** [comment]
@vladikoff yes that also works fine. The version is 3.10.10

**Comment by aayushis12** [comment]
Hi,
Can there be some other reason because of which this error -  'scripts is not recognised as an internal or external command' can come?

**Comment by aayushis12** [comment]
@rfk  I get this after doing npm run-script`
Lifecycle scripts included in fxa-content-server:
  postinstall
    bower update --allow-root --config.interactive=false -s && scripts/download_l10n.sh
  start
    node scripts/check-local-config && grunt server
  test
    intern-runner config=tests/intern

available via `npm run-script`:
  build-production
    grunt build
  prepush
    grunt quicklint
  shrinkwrap
    npmshrink:prod
  start-production
    grunt build && CONFIG_FILES=server/config/local.json,server/config/production.json grunt serverproc:dist
  start-remote
    scripts/run_remote_dev.sh
  test-circle
    intern-runner config=tests/intern_functional_circle fxaAuthRoot=https://fxaci.dev.lcip.org/auth fxaEmailRoot=http://restmail.net fxaOauthApp=https://oauth-fxaci.dev.lcip.org fxaUntrustedOauthApp=https://321done-fxaci.dev.lcip.org fxaProduction=true bailAfterFirstFailure=true
  test-functional
    intern-runner config=tests/intern_functional
  test-functional-oauth
    intern-runner config=tests/intern_functional_oauth
  test-latest
    intern-runner config=tests/intern_functional_full fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 fxaContentRoot=https://latest.dev.lcip.org/ fxaEmailRoot=http://restmail.net fxaOauthApp=https://123done-latest.dev.lcip.org/ fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ fxaProduction=true fxaToken=https://token.dev.lcip.org/1.0/sync/1.5
  test-sauce
    intern-runner config=tests/intern_sauce
  test-server
    intern-client config=tests/intern_server
  test-travis
    intern-runner config=tests/intern_travis

`
Probably, I should try this on Ubuntu only

**Comment by rfk** [comment]
>  Probably, I should try this on Ubuntu only

I'd like to have all this stuff working well under windows, but sadly right now, you'll probably have an easier time on a Linux or OS X variant :-(

**Comment by aayushis12** [comment]
Hi,
When I go to the address 127.0.0.1:3030, I get 'Unable to connect to the server' error.I have all the dependencies installed on Linux. How can I resolve this?

**Comment by aayushis12** [comment]
When I run the command 'npm run start-remote', I get this error missing scripts- start remote, Am I supposed to add something in the config file? How can I resolve this?

**Comment by DGRamya** [comment]
@vladikoff , There is no PR for this issue and also the issue is opened long back, Can I work on this issue?
