### ISSUE TITLE
Constant loading of account verified screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4930]
STEPS TO REPRODUCE
1. Create a profile and authenticate Sync
1. In a new profile, sign up for a new account
1. Open the verification link in the original profile

EXPECTED RESULTS
* Account verified screen loads fully

ACTUAL RESULTS
* Favicon makes it looks as though the page is loading endlessly
<img width="743" alt="screenshot 2017-04-11 11 30 21" src="https://cloud.githubusercontent.com/assets/68213/24917285/ae013d66-1eaa-11e7-9fbd-39e46d279626.png">

**Comment by vladikoff** [comment]
This should be fixed
