### ISSUE TITLE
Connect another device experience missing in Safari for iOS

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4939]
STEPS TO REPRODUCE
1. In a fresh desktop Firefox register in the first-run flow
1. Verify email address on an iOS device

EXPECTED RESULTS
* Connect another device experience is shown on each
![verified 2x-copy](https://cloud.githubusercontent.com/assets/68213/24930962/708619fa-1ed9-11e7-91cf-b296eaa6e3cd.png)

ACTUAL RESULTS
* Previous experience is shown to each
![2017-04-11 16 51 58](https://cloud.githubusercontent.com/assets/68213/24930967/75e2ae90-1ed9-11e7-9cdb-3fadecbff475.png)
<img width="1513" alt="screenshot 2017-04-11 16 51 46" src="https://cloud.githubusercontent.com/assets/68213/24930968/75e3274e-1ed9-11e7-83f7-805b1ecd8b95.png">

cc/ @shane-tomlinson

**Comment by shane-tomlinson** [comment]
> Connect another device experience is shown on each

We never added this to the firstrun's "confirm" page, we didn't prioritize it.

What version of Fx for iOS are you using?

**Comment by shane-tomlinson** [comment]
> > Connect another device experience is shown on each
>
> We never added this to the firstrun's "confirm" page, we didn't prioritize it.

I also don't see it in the spec - https://github.com/mozilla/fxa/tree/master/features/FxA-51-connect-another-device

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I just tested verifying in Safari w/o a problem:

![img_0746](https://cloud.githubusercontent.com/assets/848085/24932460/8fef9e30-1f09-11e7-8140-bb0eec8b1c63.PNG)

Do you have a user already signed in?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Is this in the emulator? Font is missing.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - nope, that's my phone.

**Comment by vladikoff** [comment]
@shane-tomlinson can we close this?
