### ISSUE TITLE
Redirect firstrun users to CAD in the signup tab after user verifies their email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4944]
Originally reported by @ryanfeeley in https://github.com/mozilla/fxa-content-server/issues/4939.

On the firstrun page, instead of showing the user "Account verified" when we have detected the user verified, we should send the user to "/connect another device" so we have more touch points that encourage users to connect a 2nd device.

**Comment by ryanfeeley** [comment]
Current:
<img width="472" alt="screen shot 2017-04-18 at 10 28 06 am" src="https://cloud.githubusercontent.com/assets/68213/25136006/d6d1754a-2421-11e7-86c8-1bdeb7296101.png">


Proposed:
<img width="515" alt="screen shot 2017-04-18 at 10 28 24 am" src="https://cloud.githubusercontent.com/assets/68213/25136022/def19fd4-2421-11e7-808b-e3f663055e0b.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson Though SMS screen is preferable

**Comment by davismtl** [comment]
@shane-tomlinson This is a pretty big one. It occurred to me that this means that the control we are using to measure SMS is wrong. :-/

We are measuring SMS against our old connect another device screen.

@ryanfeeley Please replace the image you put above with one that is not blank. I know that we will be replacing the image soon but let's still make sure we don't deploy a fix without an image.

**Comment by davismtl** [comment]
Spoke to @shane-tomlinson .
The SMS is not displayed here. It is only displayed on the tab opened after email confirmation.

We've decided that for the sake of saving time, we will see how well SMS does and then we might just deploy that to this screen, skipping the phase 1 design from above.

I don't want Shane to deploy this to then after to take it down a couple of weeks later to replace it with SMS.

**Comment by ryanfeeley** [comment]
@davismtl OK, well then can we at least use this screen as I know it performs better than what we show today.
<img width="504" alt="image" src="https://cloud.githubusercontent.com/assets/68213/25152007/ae974e90-2455-11e7-810f-b120c48b7d61.png">

**Comment by davismtl** [comment]
@ryanfeeley Sorry, I might not have been very clear.

Your screen is phase 1. Since Shane has a lot of other work on his plate, as soon as we know if phase 2 is outperforming phase 1, we'll just immediately jump to phase 2. For the time being, we won't roll-out phase 1 on this touchpoint.

Outcome:
- it may delay by like 2 weeks updating this touchpoint 
- we'll skip phase 1 and go directly to phase 2
- we'll save Shane a deploy

**Comment by ryanfeeley** [comment]
@davismtl This screen is deprecated as the new design outperforms it by a large margin. We even published the numbers on Good UI. http://goodui.org/evidence/test078
We won't be able to provide the SMS screen in every instance so this will be the default screen anyway. I just want to make sure we're on track to deprecate it.

**Comment by davismtl** [comment]
Excellent point @ryanfeeley . You are totally right, we will not be displaying SMS to all user and this should be the default screen otherwise.

@shane-tomlinson How long would it take to roll-out phase 1 to the sign-up tab?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - the firstrun page is the only place we'll be able to get this in without browser work. When FxA is embedded in about:accounts, Firefox takes over the page as soon as it detects the user has verified their email.

I experimented with adding this to the firstrun page, a lot of @ryanfeeley visual TLC is needed:

<img width="348" alt="screen shot 2017-04-25 at 14 38 25" src="https://cloud.githubusercontent.com/assets/848085/25486308/a18f7e7a-2b58-11e7-813a-e763c36867ce.png">


<img width="379" alt="screen shot 2017-04-25 at 14 40 26" src="https://cloud.githubusercontent.com/assets/848085/25486316/a8deeb5c-2b58-11e7-9c4b-7d8c0f618521.png">


<img width="365" alt="screen shot 2017-04-25 at 14 40 35" src="https://cloud.githubusercontent.com/assets/848085/25486319/ac819a0c-2b58-11e7-80c6-494e92961fd7.png">

**Comment by davismtl** [comment]
This looks good to me. The grayed out iFrame is a bit weird so def need some love from @ryanfeeley .

As per the copy, I really don't like that first sentence. I'm not fond of the parentheses in the headline either. I had to read it a few times. Example of shortening the first 2 sentences into 1:

"Sync lets you securely find *your* bookmarks, passwords and more from any of *your* devices running Firefox."

Let's keep it short and sweat.

**Comment by ryanfeeley** [comment]
@davismtl 
![lrvnpyqm8dlag](https://cloud.githubusercontent.com/assets/68213/25497525/bc3956fc-2b39-11e7-84e4-e3e570aa1699.gif)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Thanks for the help with the "why is this required" modal, I'm going to put a bit of work into getting the iframe to resize for the modal text. We talked about updating the text to be a bit clearer, did you have text in mind?

<img width="344" alt="screen shot 2017-05-02 at 16 11 33" src="https://cloud.githubusercontent.com/assets/848085/25624664/0a619fe4-2f52-11e7-96bc-b5d41236f2fe.png">

Now for the main sms form - here's a screenshot within the iframe:

<img width="339" alt="screen shot 2017-05-02 at 16 00 31" src="https://cloud.githubusercontent.com/assets/848085/25624219/a4b6d548-2f50-11e7-922b-216f9a18859f.png">

Think the app store buttons are too big?

**Comment by ryanfeeley** [comment]
@shane-tomlinson We still see the old screen in sync fest. Is the new one coming soon? https://github.com/mozilla/fxa-content-server/issues/4944#issuecomment-294862555

**Comment by shane-tomlinson** [comment]
@ryanfeeley - did you follow [these steps for testing](https://github.com/mozilla/fxa-content-server/pull/5026#issuecomment-302473659)?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - this isn't in prod yet, the PR hasn't yet merged.

**Comment by vladikoff** [comment]
This is now unblocked, final content here: https://github.com/mozilla/fxa-content-server/issues/4485
