### ISSUE TITLE
SMS legal text needs to be updated to include Canada

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4945]
The current text says "SMS service available to U.S. phone numbers only." We have been given permission to allow Canada, the text should reflect this.

<img width="350" alt="screen shot 2017-04-12 at 16 38 57" src="https://cloud.githubusercontent.com/assets/848085/24966408/c1159588-1f9e-11e7-8d85-3a98c6ca1225.png">

**Comment by vladikoff** [comment]
Sorry!

**Comment by shane-tomlinson** [comment]
We'll soon have GB enabled too.

**Comment by vladikoff** [comment]
Still waiting for Legal

**Comment by juliemccracken** [comment]
Legal will have something ready for us to use by the end of the day (May 2nd)

**Comment by shane-tomlinson** [comment]
From an email from @juliemccracken:

> Legal has asked that we change the first line of the SMS notification message to "SMS service only available in certain countries." The rest of the notice should remain as-is.
