### ISSUE TITLE
Fira font is missing on Shane's iPhone

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4947]
For some reason, our web font Fira is not appearing on @shane-tomlinson phone.

![font](https://cloud.githubusercontent.com/assets/68213/24976241/abd0937e-1f96-11e7-8a04-97ae689ffff7.PNG)

Is this just a Shane issue? Only Shane can tell.

**Comment by shane-tomlinson** [comment]
That's because I have Firefox Focus installed, and have it set to block fonts.
