### ISSUE TITLE
Connect another device URL missing store icons if ?service=sync not specified

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4948]
Making the Connect Another Device more robust means that we can link to it for more places (like our post-verification email) so that users are directed to do the best thing based on context. @shane-tomlinson 

STEPS TO REPRODUCE
1. In a non-Firefox desktop browser visit: https://accounts.firefox.com/connect_another_device

EXPECTED RESULTS
* App/Play Store icons appear
<img width="251" alt="image" src="https://cloud.githubusercontent.com/assets/68213/24976515/be6406fa-1f97-11e7-8785-2d648b841689.png">

ACTUAL RESULTS
* They don't
<img width="251" alt="image" src="https://cloud.githubusercontent.com/assets/68213/24976511/b4ada616-1f97-11e7-84f9-3cb41a056075.png">

**Comment by rfk** [comment]
> Making the Connect Another Device more robust means that we can link to it for more places
> (like our post-verification email)

Or perhaps, from about:preferences#sync instead of the existing in-product app store icons.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - your URL is missing ?service=sync. The icons won't appear w/o it. That's because the marketing-mixin is used in all kinds of other pages and is only supposed to be shown to Sync users.

Please reload with the ?service=sync query param, and if it works, can you close this down?

FWIW, here's how it looks in Chrome:
<img width="796" alt="screen shot 2017-04-12 at 21 20 53" src="https://cloud.githubusercontent.com/assets/848085/24977730/f0d61e9c-1fc5-11e7-8bf9-926c39612693.png">

**Comment by rfk** [comment]
Is there any reason to land on this page from a service other than sync?  If not then it might make sense assume `service=sync` when someone is linked directly to this page (if such a thing is possible).

**Comment by ryanfeeley** [comment]
@shane-tomlinson Works! So does that mean that we use that link from our post-verification email instead of the Sync marketing page?

**Comment by rfk** [comment]
(I mean, even the messaging and pictures and "why is this required" here are all specific to sync anyway)

**Comment by shane-tomlinson** [comment]
@rfk - I'd rather not make an update because well.. It'd require special casing in the mixin/marketing view for one page and so far the only way real life users arrive at the page is via our gating logic.

**Comment by shane-tomlinson** [comment]
OTOH - if there comes a time when we show this page w/o the service=sync query params, I'd be happy to make that update.
