### ISSUE TITLE
Optimize age chooser for integer spinner

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4952]
I noticed that the integer spinner is appearing in Nightly and that FxA is crunching it a bit. Can we give it more height? Or perhaps 10px padding on the right?
<img width="372" alt="screenshot 2017-04-11 10 52 58" src="https://cloud.githubusercontent.com/assets/68213/25023041/5d63f5a2-2066-11e7-9311-499595a1e80d.png">

**Comment by vladikoff** [comment]
from mtg: hide it

**Comment by vladikoff** [comment]
This was fixed
