### ISSUE TITLE
Why are there so few flow.verify-email.view events?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4953]
I was planning to use these in the query for calculating success of the SMS install link feature but it turns out they don't happen as often as I thought they should:

```
fxa=# select count(*) from flow_events where type = 'flow.verify-email.view';
 count
-------
  677
(1 row)

fxa=# select count(distinct timestamp::date) from flow_events where type = 'flow.sms.view';
 count
-------
    26
(1 row)

fxa=# select distinct timestamp::date from flow_events where type = 'flow.sms.view' order by 1;
 timestamp
------------
 2017-03-06
 2017-03-07
 2017-03-08
 2017-03-09
 2017-03-10
 2017-03-14
 2017-03-15
 2017-03-16
 2017-03-17
 2017-03-18
 2017-03-19
 2017-03-20
 2017-03-21
 2017-03-22
 2017-03-24
 2017-03-25
 2017-03-27
 2017-04-05
 2017-04-06
 2017-04-07
 2017-04-08
 2017-04-09
 2017-04-10
 2017-04-11
 2017-04-12
 2017-04-13
(26 rows)
```

**Comment by shane-tomlinson** [comment]
@philbooth - there should be very few verify-email flow events, the screen is only displayed to users if there's an error. Otherwise, users are redirected to `/connect_another_device`, `/sms`, and `/signup_verified`

**Comment by philbooth** [comment]
Oh, right. I must have misunderstood you the other day, I thought this was supposed to be the starting point for all users going through the connect another device flow.

**Comment by shane-tomlinson** [comment]
> Oh, right. I must have misunderstood you the other day, I thought this was supposed to be the starting point for all users going through the connect another device flow.

We can add a flow event that says "yep, the user has been here" if that'll make the metrics processing a bit simpler. Otherwise, I imagine we'll have to sum the 4 possible screens, which'll be a drag.

**Comment by philbooth** [comment]
> ...if that'll make the metrics processing a bit simpler.

I think it will, I've opened #4978.
