### ISSUE TITLE
Web sessions not appearing in Safari

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4959]
STEPS TO REPRODUCE
1. Sign in to Sync on Firefox
2. Sign in to accounts.firefox.com in Safari (i.e. not syncing)

EXPECTED RESULTS
- Safari web session appears as current session in Safari

ACTUAL RESULTS
- Safari web session does not appear in Safari at all, but does appear in Firefox

Figure 1. Firefox (left) and Safari (right)
<img width="1167" alt="screenshot 2017-04-18 15 23 34 2" src="https://cloud.githubusercontent.com/assets/68213/25150601/81dd9102-2450-11e7-813d-6e46aa506fdf.png">

**Comment by vladikoff** [comment]
@ryanfeeley we only show sessions in **Firefox 53+**

**Comment by ryanfeeley** [comment]
@vladikoff Because…?

**Comment by vladikoff** [comment]
@ryanfeeley Part of 'feature' roll out, it's riding the trains and is in testing 

Ref: https://github.com/mozilla/fxa-content-experiments/blob/dev/clients/sessions.js#L9

**Comment by ryanfeeley** [comment]
@vladikoff I don't understand why we would ever show different items in different browsers. @davismtl

**Comment by vladikoff** [comment]
@ryanfeeley Once FF53 becomes stable we will enable it everywhere! It was an experiment to see if we can gate feature based on FF version, but seems like this experiment is fail!

**Comment by ryanfeeley** [comment]
This is probably not the best use of FF version gating. For a feature like this is makes sense to limit it by account.

**Comment by vladikoff** [comment]
@ryanfeeley but then you woundn't see them during sync fest for example. :( (we usually lock based on `@mozilla and @softvision`

**Comment by shane-tomlinson** [comment]
I'd be interested in reading the rationale behind FF version based gating and how that compares to other forms of gating we use. I'm neither for nor against FF version based gating here, I thought it was a neat idea. If gating based on FF versions isn't appropriate for this feature, is there a feature where it is?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Definitely makes sense to gate when specific client features are required. I could see for example using SVG animations in newer browsers but stills in older versions. I could also see limiting avatar editing like rotating/cropping to browsers that support it. But I don't see why we would show users in one browser version that they had four device/apps connected to their account and only two in another.

**Comment by vladikoff** [comment]
>  But I don't see why we would show users in one browser version that they had four device/apps connected to their account and only two in another.

In this case it is `We show web sessions or we do not show them at all`.
