### ISSUE TITLE
Web session timestamp needs more context

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4960]
So that the time stamps resemble our other timestamps, we should include more context.

Top is current, bottom is proposed.

<img width="239" alt="image" src="https://cloud.githubusercontent.com/assets/68213/25151346/3e3f7d7c-2453-11e7-935c-c617b29cb6fb.png">

**Comment by vladikoff** [comment]
That would be cool!

**Comment by ryanfeeley** [comment]
@vladikoff So to be clear, web sessions are only able to report when they were first signed in, but other apps like Add-ons can report the last time the session was used?

**Comment by rfk** [comment]
> web sessions are only able to report when they were first signed in, but other apps
> like Add-ons can report the last time the session was used

I believe this is accurate, yes.  Web sessions suffer the same problem as device sessions, where we're not tracking last-active time due to overwhelming database write load.  OAuth apps don't have this problem due to much smaller volume.

**Comment by vladikoff** [comment]
Good to go and ready to be fixed!

**Comment by DGRamya** [comment]
@vladikoff , Can I work on this issue? Could you please more details.

**Comment by vladikoff** [comment]
🗡
