### ISSUE TITLE
functional test failure - oauth settings clients - rp listed in apps, can be deleted

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4968]
> StaleElementReference: [POST http://localhost:4444/wd/hub/session/78e04e71-beb7-4b37-b570-135dc9f0165c/element/3066/click / {}] The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: '2c2ab056496c', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, firefox_binary=/home/teamcity/firefox-channels/latest/en-US/firefox/firefox-bin, acceptSslCerts=false, processId=10254, browserVersion=50.1.0, platformVersion=4.4.41-36.55.amzn1.x86_64, name=tests/intern_functional_full, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIAHyak0oAAAAAAAAAA...}]
Session ID: e4013df7-9ca3-4c75-8695-c319b844bfee
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:92:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:67:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:191:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:148:10>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.rp listed in apps, can be deleted [as test]  <tests/functional/oauth_settings_clients.js:90:10>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

**Comment by shane-tomlinson** [comment]
@vladikoff - I think this test is breaking because of web sessions - check it out:

<img width="560" alt="screen shot 2017-04-20 at 21 20 52" src="https://cloud.githubusercontent.com/assets/848085/25252263/367e2292-2614-11e7-9a3f-6e0931c889a8.png">

I think the OAuth app buttons are in the wrong place to match [nth-child(1)](https://github.com/mozilla/fxa-content-server/blob/bb8d2987014129fc4df8e722282cf9d4172ec3fe/tests/functional/oauth_settings_clients.js#L90),  because that'll look for a client-oAuthApp as the very first child in the list. I haven't had any luck yet with [nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) either.

This test is no longer flaky, it fails 100% of the time locally and against latest. Has the way web sessions is surfaced changed to cause this?

**Comment by vladikoff** [comment]
>  Has the way web sessions is surfaced changed to cause this?

yes! 

I was looking at that and CI in the PR was doing fine. I guess we need to tweak that a bit

**Comment by shane-tomlinson** [comment]
Re-opening - new error mode!

> StaleElementReference: [POST http://localhost:4444/wd/hub/session/db492279-0c4d-4470-967a-9a0d9fc3b411/element/3069/click / {}] The element reference of <button class="settings-button warning client-disconnect"> stale: either the element is no longer attached to the DOM or the page has been refreshed

**Comment by shane-tomlinson** [comment]
The reason this can happen is because [on line 87](https://github.com/mozilla/fxa-content-server/blob/c51e6b3574a2099ba96c735b6297c719b1a1fffd/tests/functional/oauth_settings_clients.js#L87) we check for the `321 Done` list item, then we delete the `123 Done` element, which is before it in the list. The `321 Done`. This causes the cached reference to the `321 Done` element to no longer be valid.

**Comment by shane-tomlinson** [comment]
> The reason this can happen is because on line 87 we check for the 321 Done list item, then we delete the 123 Done element, which is before it in the list. The 321 Done. This causes the cached reference to the 321 Done element to no longer be valid.

My explanation is invalid. 321 Done is in the DOM before 123 Done.
