### ISSUE TITLE
Emit a flow event for the beginning of the connect-another-device flow

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#4978]
It will make the metrics queries more efficient.

**Comment by philbooth** [comment]
IIUC, this is what now happens with the experiment events emitted by the content server. They're not emitted until the user actually enters the experiment or the control.

@shane-tomlinson, if you can confirm my understanding is correct, I'll close this one out.

**Comment by shane-tomlinson** [comment]
> IIUC, this is what now happens with the experiment events emitted by the content server. They're not emitted until the user actually enters the experiment or the control.

Yup.

**Comment by philbooth** [comment]
Thanks Shane!
