### ISSUE TITLE
Hitting `Esc` in a settings panel does not reset the form field.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#4982]
Found while investigating #4972.

STR

1. Sign in to a verified account, open /settings
2. Open the "Display name" panel.
3. Type in a new display name.
4. Hit the Escape key.
5. Re-open the "Display name" panel.
6. Name from step 3 is still in the form field.
7. Click "Cancel"
8. Re-open the "Display name" panel.
9. Display name has reverted to the original.

![esc-does-not-reset-form](https://cloud.githubusercontent.com/assets/848085/25339794/bcda1078-28fb-11e7-9bc0-612883b4bba9.gif)

**Comment by mutdmour** [comment]
I will work on this.

**Comment by vladikoff** [comment]
@mutdmour 👍

**Comment by vladikoff** [comment]
:dagger: , unless more people start using `ESC`
