### ISSUE TITLE
Reorder settings so display name is below account picture

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4984]
So that our sections are ordered to reflect the content on the page, the top sections should be in this order:
1. Avatar
2. Display name
3. Secondary email (does not always appear)

Bonus: blue buttons can appear together.

![reorder-settings](https://cloud.githubusercontent.com/assets/68213/25349717/ca04fab6-28f0-11e7-9658-ef36befae6ba.png)

**Comment by rfk** [comment]
> blue buttons can appear together.

+1000 :grin:
