### ISSUE TITLE
Drop permission screen for Pocket

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4986]
Now that Pocket is no longer a third party, we don't need to ask users for permission to share their account details with them. We should remove the permission step during FxA/Pocket registration.

**Comment by vladikoff** [comment]
wooo!

**Comment by rfk** [comment]
\o/ indeed!  But I do want to double-check that we have explicit approval from legal to do this; /cc @juliemccracken

**Comment by juliemccracken** [comment]
I will check with legal to confirm it's ok to remove the permission step for sharing account details.

**Comment by shane-tomlinson** [comment]
We cannot remove this for now.
