### ISSUE TITLE
Add "last sync time unknown" for sync devices when last sync time is unknown

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4988]
We have received feedback that users cannot distinguish between app, web sessions and sync clients.

Adding "last sync time unknown" will at least help users understand that the item is a sync device.

**Comment by rfk** [comment]
> We have received feedback that users cannot distinguish between app, web sessions and sync clients

Out of curiosity, is this feedback anywhere we can link to it for reference, or is this based on in-person testing?

> Adding "last sync time unknown" will at least help users understand that the item is a sync device.

A possible alternative could be "Connected to sync on XYZ" or "Syncing since XYZ" or similar using the timestamp of the login, rather than the timestamp of last activity.

**Comment by ryanfeeley** [comment]
> Out of curiosity, is this feedback anywhere we can link to it for reference, or is this based on in-person testing?

Both our copywriter and even some of the Sync engineers said they can't parse what's going on in the devices list.
