### ISSUE TITLE
Sort devices & apps section first by type then date

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4991]
If Sync contains the most sensitive data, and is the primary customer for Firefox Accounts, let’s sort devices & apps section first by type then date.
* Sync devices
* OAuth
* Web sessions

![group-by-type](https://cloud.githubusercontent.com/assets/68213/25361712/98009df4-2904-11e7-8584-abd56e01a9dc.png)

**Comment by rfk** [comment]
Nice, yes, I'm strongly +1 to grouping by type here.

**Comment by ryanfeeley** [comment]
@rfk I'm still thinking about this. Will everything that isn't a sync device have a URL? Like addons.mozilla.org, getpocket.com and accounts.firefox.com?

**Comment by rfk** [comment]
> Will everything that isn't a sync device have a URL?

Yes, I expect so.  Although in the future it might be e.g. the Hoverpad mobile app.

**Comment by vladikoff** [comment]
@udaraweerasinghege sort of related to https://github.com/mozilla/fxa-content-server/issues/4991 after https://github.com/mozilla/fxa-content-server/issues/3908 is done
