### ISSUE TITLE
Use "started syncing" timestamp for sync devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#4992]
Currently FxA appears to list last active time in the front end code, but then hides it with CSS. I understand that the time may not be accurate, but any timestamp will help users distinguish devices. Aside from the obvious ones, what issues are presented by innaccurate Sync times @rfk?

**Comment by rfk** [comment]
We can present an accurate "you signed in to this device at time X" timestamp for all devices, if that helps.  In fact right now that's the *only* time we're keeping track of IIRC.  It seems like this could be quite useful for distinguishing the devices, in particular for solving the "which one of these is the most recent incarnation of my device?" problem.

> Aside from the obvious ones, what issues are presented by innaccurate Sync times

A dramatically out-of-date "last active" time might cause users to think their sync is not working correctly when in fact it is.  They might also be confused if they do a "sync now" and don't see the timestamp update accordingly.

**Comment by ryanfeeley** [comment]
I'd like to include the word "sync" to differentiate from the other items in the section. Some options, all in lowercase deliberately:
* joined sync 3 days ago
* began syncing 3 days ago
* signed in to sync 3 days ago
* started syncing 3 days ago

**Comment by rfk** [comment]
👍; I think "started syncing 3 days ago" is my favorite but I'd be happy with any of these variations.

**Comment by ryanfeeley** [comment]
Because I think it will translate better than others, let's go with (in lowercase, like all the second lines should now be in devices):
* started syncing {timestamp}

**Comment by vladikoff** [comment]
ready to go, final string above ^

Phil and Vlad to chat about this

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/commit/15d9ec08b7ae98b394e7f24a2feaf24e9b7d6d42
