### ISSUE TITLE
Device names with unicode showing as ? in device mgr

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5003]
STEPS TO REPRODUCE
1. Register for Sync
2. Change the device name in Firefox prefs and include an unicode character like ❿

EXPECTED RESULTS
* New device name reflected in device mgr

ACTUAL RESULTS
* Unicode character is a ?

**Comment by rfk** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1348298 which is almost certainly caused by the same underlying issue.

**Comment by rfk** [comment]
I'm going to dup this to https://github.com/mozilla/fxa-auth-db-mysql/issues/229
