### ISSUE TITLE
Device names with emoji not updating in device mgr

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5004]
STEPS TO REPRODUCE
1. Register for Sync
2. Change the device name in Firefox prefs and include an unicode character like 😁

EXPECTED RESULTS
* New device name reflected in device mgr

ACTUAL RESULTS
* New name not showing up at all (but is in other devices)

**Comment by rfk** [comment]
> (but is in other devices)

It's not obvious what you mean by this, can you clarify?  Do you mean the emoji shows up on other devices, or that the names of other devices show up correctly in the device manager?

**Comment by ryanfeeley** [comment]
@rfk Yes, sorry for being unclear. On iOS when I send a tab, the new name + emoji shows up in the Send Tab view. I didn't test Android or any other devices yet.

**Comment by rfk** [comment]
I believe this is a dup of #1285 but leaving open for now to confirm there's nothing else going on

**Comment by rfk** [comment]
Erm, the link above should have been to https://github.com/mozilla/fxa-auth-server/issues/1285, and I am indeed going to close this as a dup
