### ISSUE TITLE
account_updates error message. No Such Channel 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5005]
STR 
1. Create a brand new account on latest.dev.lcip.org
2. Collect verification email and verify
3. Open browser console and turn on full logging
4. Change your display name
5. And ...
Fx53.0 macOS

```
account_updates error message. No Such Channel  WebChannel.jsm:148
	_sendErrorEventToContent resource://gre/modules/WebChannel.jsm:148:5
	_listener resource://gre/modules/WebChannel.jsm:103:11
	bound _listener self-hosted:914:17
```

**Comment by jrgm** [comment]
Note: could not reproduce in production. Something need to be set up w/ latest, etc.?

**Comment by jrgm** [comment]
Oh, yeah. Probably need to configure the browser.

**Comment by vladikoff** [comment]
@jrgm use https://github.com/vladikoff/fxa-dev-launcher/blob/master/README.md#basic-usage-example-in-os-x  with `FXA_ENV=latest npm start`
