### ISSUE TITLE
Reuse avatar loading spinning animation on avatars

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5006]
STEPS TO REPRODUCE
1. Log into FxA Settings
2. Click on Avatar

EXPECTED RESULTS
* Avatar loads instantly or has the spinning wheel that sign-in has

ACTUAL RESULTS
* Avatar is blank for a bit

This also applies to when you save a new avatar and close the modal, and it takes time to appear on top of settings frame.

![snooka](https://cloud.githubusercontent.com/assets/68213/25464873/ae18e3f2-2ab3-11e7-869a-765e1f66b4f8.gif)

**Comment by shane-tomlinson** [comment]
Dup of #4574 (and #3897), though this has a concrete suggestion. Closing those.
Ref #3374

**Comment by shane-tomlinson** [comment]
What's odd, is [we have code to show a spinner](https://github.com/mozilla/fxa-content-server/blob/d3668b997da59932cf26e536ce75780f76f03b30/app/scripts/views/mixins/avatar-mixin.js#L51)! I wonder why it's not being used. :/

**Comment by ryanfeeley** [comment]
@shane-tomlinson Differennt sizes?

**Comment by himanish-star** [comment]
@ryanfeeley , I would like to work on this issue

**Comment by ryanfeeley** [comment]
@himanish-star Go for it! A lot of people see this.

**Comment by himanish-star** [comment]
@ryanfeeley , I have already opened a PR #5804
