### ISSUE TITLE
Web sessions can sometimes be displayed with no name or timestamp

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5007]
As seen at the bottom on the screenshot in https://github.com/mozilla/fxa-content-server/issues/4987#issuecomment-297115457

**Comment by vladikoff** [comment]
@davismtl can you check in https://accounts.firefox.com/settings/clients?context=web&sessionsListVisible=true if you still see this ?

**Comment by davismtl** [comment]
Looks good to me.

**Comment by vladikoff** [comment]
Fixed!
