### ISSUE TITLE
Gather metrics on the number of web sessions users have in the wild

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5008]
One of the issues with web sessions identified in https://github.com/mozilla/fxa-content-server/issues/4987, was that there can be an unexpectedly large number of them due to how easy it is to orphan an existing sessionToken and create a new one.  To measure the success of any efforts to reduce that problem, we'll need some metrics on the number of web sessions that users have in the wild.

Perhaps we can add something akin to the "how many accounts are stored in localstorage" metrics that @shane-tomlinson added recently, to give us a breakdown of what web sessions users would see in the wild?

**Comment by shane-tomlinson** [comment]
@vladikoff asks - can we run a query on the backend somehow.

**Comment by rfk** [comment]
Good idea, perhaps we can do something similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1337932 to sample this on the backend.

**Comment by vbudhram** [comment]
from mtg: this has been fixed
