### ISSUE TITLE
Inconsistent string "This Firefox is connected" vs "This device is connected"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5012]
On /connect_another_device, we show the text "This device is connected", on /sms, we show "This Firefox is connected". My OCD kicked in.

<img width="461" alt="screen shot 2017-04-27 at 15 07 27" src="https://cloud.githubusercontent.com/assets/848085/25487139/45123928-2b5b-11e7-8f11-bf98bb584fb0.png">

<img width="461" alt="screen shot 2017-04-27 at 15 07 39" src="https://cloud.githubusercontent.com/assets/848085/25487161/4cc2b9ea-2b5b-11e7-8fbb-2ef12be52d52.png">

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
Ref #5009

**Comment by ryanfeeley** [comment]
Well spotted. I suppose the latter (Firefox) is better. Switch it?
