### ISSUE TITLE
"Missing sessionToken" being reported to Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5013]
Not enough to be too concerned, but there are more than 0. See https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/395316/

The error is when calling `FxAccountClient.prototype.recoveryEmailResendCode`.

**Comment by vladikoff** [comment]
@shane-tomlinson please include the event id in sentry links: `issues/:id/events/:id`

**Comment by rfk** [comment]
Unilaterally closing this out as it's several months old, let's re-open if this is still and issue and we plan to dig in
