### ISSUE TITLE
"Invalid data for command internal:signed_in" reported to Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5014]
See https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/395428/.

The common factor is the users are trying to sign into an oauth relier.

**Comment by vladikoff** [comment]
P2, to investigate this issue and then close

**Comment by vladikoff** [comment]
Seems like this was fixed up, no occurrences of events with that name now
