### ISSUE TITLE
Finalize web session reintroduction

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5027]
Get everything right about the design of web sessions before reintroducing it

**Comment by rfk** [comment]
BTW all the bugs you filed are grouped into this handy milestone: https://waffle.io/mozilla/fxa?milestone=FxA-127:%20re-enable%20web%20sessions

**Comment by vbudhram** [comment]
from mtg: @rfk triage?

**Comment by rfk** [comment]
Let's revisit this afresh if/when we decide to reprioritize it
