### ISSUE TITLE
circle-ci build for tag v1.86.0 failed; no docker image

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5032]
I tried to build the stage pipeline for content with v1.86.0 but no such image.

Tests failed https://circleci.com/gh/mozilla/fxa-content-server/6842

It's gonna happen. Just noting that it happened.

Discuss.

**Comment by jrgm** [comment]
> I tried to build the stage pipeline for content with v1.86.0 but no such image.

To be clear, this is the dockerflow pipeline, not the current pipeline that will be used this time around.

**Comment by philbooth** [comment]
Discussed in meeting, okay to close.

**Comment by vladikoff** [comment]
Closing for now, restarted the build...
