### ISSUE TITLE
Change web sessions and OAuth clients to "Revoke"

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5036]
Current red button for web sessions and OAuth clients is:

* Disconnect

To differentiate it from Sync devices we should change it to:

* Sign out

**Comment by rfk** [comment]
Careful, there's a good chance this won't actually "sign out" from the oauth relier in the way a user might believe, it just revokes their ability to access account data in FxA.

**Comment by vladikoff** [comment]
@ryanfeeley did you still want this , see comment above

**Comment by ryanfeeley** [comment]
@vladikoff I'm checking to see how widely "Revoke" is used and understood. Is it the most accurate label?

**Comment by ryanfeeley** [comment]
Revoke!
