### ISSUE TITLE
Add sign-in bounced screen

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5037]
Hoping for a magical collaboration of art & copy from @mheubusch & @mart3ll.

CONTEXT: When users sign in to Firefox on a new device, we require that they also verify their email (click a link sent to their email). Sometimes users lose access to their email. Sometimes it is permanent (e.g. job, ISP change) in which case they have no recourse. In fewer instances it is a temporary bounce. We would like to present a screen for when the email bounces that handles both cases well. We have to be careful, as for users who are trying to restore a backup to a new machine, they cannot.

Here is a ~~first second attempt I am hoping you can improve on~~ the final version to avoid confusion:
![image](https://cloud.githubusercontent.com/assets/68213/26463162/641c8ace-4151-11e7-9a8b-269b3530df20.png)

@vladikoff Will let us know when it is required.

**Comment by davismtl** [comment]
@ryanfeeley can we replace **Have another email address? Create a new account** to **Don't own that email anymore? Create a new account**

The screen on the right also seems like a great opportunity to let the user know they can add a secondary email. I'm just not sure how to do that without making the UI too busy.

**Comment by ryanfeeley** [comment]
> @ryanfeeley can we replace
> Have another email address? Create a new account
> to
> Don't own that email anymore? Create a new account

I'm only opposed to that in that it's a longer string. Perhaps @mheubusch can improve.

> The screen on the right also seems like a great opportunity to let the user know 
> they can add a secondary email. I'm just not sure how to do that without making 
> the UI too busy.

Would we allow a user to add a secondary email in this state @rfk @vladikoff?

If so, I would make that the primary action (big button) here and probably redesign the entire page.

**Comment by davismtl** [comment]
@ryanfeeley It's not in this state. Once they get out of this state.

> I'm only opposed to that in that it's a longer string.
2 characters more but far more accurate of a message.

**Comment by ryanfeeley** [comment]
@davismtl Checkmate!

Yours
* Don't own that email anymore? Create a new account

My latest
* No longer own that email? Create a new account

**Comment by davismtl** [comment]
@ryanfeeley works for me

**Comment by ryanfeeley** [comment]
@davismtl Updated graphic

**Comment by vladikoff** [comment]
@ryanfeeley is this still active? I think I lost track of the action items :(

**Comment by ryanfeeley** [comment]
Just got an illustration today. I'll work on the copy. 
<img width="190" alt="image" src="https://cloud.githubusercontent.com/assets/68213/26375769/2ff59468-3fd8-11e7-94a9-ed6030d8d163.png">

**Comment by vladikoff** [comment]
wow!

**Comment by ryanfeeley** [comment]
@vladikoff Attached as SVG (zipped)
[bounced.svg.zip](https://github.com/mozilla/fxa-content-server/files/1026646/bounced.svg.zip)

**Comment by ryanfeeley** [comment]
@vladikoff @davismtl I met with Michelle and she noticed several problems with the copy. She has some ideas and is going to get new copy before our standup tomorrow.

**Comment by mheubusch** [comment]
Just to clarify :)  - I didn’t say there were problems - nothing in the message was inaccurate or misleading or off-brand, I just thought there were improvements in how we structured the message.  More to come  . . .

**Comment by mheubusch** [comment]
Suggestion copy for bounce back email: 

Sorry. We’ve locked your account. 

The confirmation email we sent to sean@martell.com <mailto:sean@martell.com> was returned, and we’ve locked your account to protect your Firefox data.  
If this is a valid email address, let us know and we can help unlock your account. 

No longer own that email address? Create a new account.

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff Updated!
![image](https://cloud.githubusercontent.com/assets/68213/26460010/52e68bc0-4146-11e7-8fef-f86d7379ff8d.png)

**Comment by ryanfeeley** [comment]
@mheubusch Apparently we now block login attempts from bounced email for only 24 hours, instead of permanently. Would these small changes be okay?

* The confirmation email we sent to user@example.com was returned, and we've locked your account for 24 hours to protect your Firefox data.
* If this is a valid email address, **let us know** and we can help unlock your account sooner.

**Comment by davismtl** [comment]
> If this is a valid email address, let us know and we can help unlock your account sooner.

I would prefer we say: If it doesn't work in 24h, let us know. The purpose of the 24h is to prevent users from continuously contacting us for false alarms around bounced emails.

**Comment by ryanfeeley** [comment]
@davismtl  Is it safe to assume that *most* people viewing this screen will have lost permanent access to their email?

**Comment by davismtl** [comment]
Statistically, probably yes. However, @rfk and I have seen many bugs where users did not lose access to their accounts and wanted help logging in. We then had to ask jbuck to resend the user emails which requires database manipulations. This is why we added the 24h rule.

Putting the right message should avoid us and some users from dealing with bugzilla for false alarms.

**Comment by seanmonstar** [comment]
Slightly off-topic (not related to a new screen), if we wanted to eventually make this not manual, we could make a 'unbounce my email' functionality that uses a completely different sender, whose reputation isn't important. Like, an email from `unbounce@bouncingfirefoxes.net` with a unique string they paste into a form.

**Comment by rfk** [comment]
> This is why we added the 24h rule.

We haven't added this yet though, right @seanmonstar?  The rate of false-positive block reports is increasing, let's chat early this coming week about how to prioritize that work.

> Apparently we now block login attempts from bounced email for only 24 hours,
> instead of permanently.

This is not entirely accurate; IIUC the plan is to:

* If you get one bounce, block sends for 24 hours.
* If you get more than one bounce, block sends for a year.

Not sure how much of that nuance we really need to convey here though; It would be interesting to know what proportion of users would currently hit this screen within 24 hours of a bounce, to know how many people would be helped by the above measure.

**Comment by ryanfeeley** [comment]
@rfk @davismtl I think we can ship the current design now, and add nuance later. It's an improvement over the current experience.

**Comment by davismtl** [comment]
Sure, I just wanted to avoid putting an open invitation to contact us when it doesn't work when ultimately, they may be unblocked in 24h if it's their first offense.

**Comment by ryanfeeley** [comment]
Higher contrast SVG attached 
[Artboard 9.svg.zip](https://github.com/mozilla/fxa-content-server/files/1085719/Artboard.9.svg.zip)
