### ISSUE TITLE
Fetching devices view missing

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5040]
From the original feature doc, before devices are loaded, the Show button should indicate loading progress and expand the menu when the items are loaded (and not before).

![image](https://cloud.githubusercontent.com/assets/68213/25774768/27ce7538-3264-11e7-9f1c-9e8df7d3759c.png)

Related: https://github.com/mozilla/fxa-content-server/issues/4541

**Comment by rfk** [comment]
A related question @ryanfeeley - what about if the user clicks directly through to the expanded view at https://accounts.firefox.com/settings/clients, e.g. because they're linked there from UI inside Firefox.  Should we display the same as above until the list has finished loading?

**Comment by ryanfeeley** [comment]
@rfk I think we should show the same as above for that state too. The eye is attracted to animation, which is a good place to put it as the devices will appear shortly.
