### ISSUE TITLE
investigate RSS growth in firefox while running under teamcity

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5041]
Just a reminder that contentproc's are reaching sometimes 5GB in size, which seems, um, a tad excessive. The teamcity CI box has 15GB, which usually was sufficient to run 3 concurrent tests. But the box has hung recently on occasion, and last night I had to reboot it to get it running again (which then lead to problems with docker not shutting down cleanly, and requiring manual repair of /var/run/docker to get the containers running again). Sure, I could just get a bigger boat, but I've also been seeing egregious RSS sizes with nightly on my own laptop, under general non-internjs test usage. Perhaps our CI environment is a useful, reproducible stress test environment that platform eng might be interested in debugging. (Or perhaps it will be "you're running marionette in docker centos containers under host amazon linux. GTFO. You're weird. Go away ;-)).

**Comment by jrgm** [comment]
Also, noting, if there is interest, I can spin up another teamcity box, configured the same way to give to platform to hack away on.

**Comment by vladikoff** [comment]
>Also, noting, if there is interest, I can spin up another teamcity box, configured the same way to give to platform to hack away on.

@jrgm Yes , that would be really useful. I looked into this a bit "locally" but was not able to see this issue. We can attach the profiler to the 5gb RSS process. How can we make the box available to platform?

**Comment by jrgm** [comment]
> How can we make the box available (to SSH into) for platform eng?

I can spin up another stack tomorrow. If I have ssh pubkeys for whomever needs access, I can add them to the VIP list.

**Comment by jrgm** [comment]
and also usernames/emails so I can create teamcity user acccounts for those who need them.

**Comment by vladikoff** [comment]
Cannot reproduce this problem on Ubuntu 16.04

![](http://v14d.com/i/591203f6556ff.jpg)

**Comment by vladikoff** [comment]
After running the tests more I got to VIRT 3513M , RES 1618M:

![](http://v14d.com/i/591207a00c2ee.jpg)
