### ISSUE TITLE
/sms view does notify the browser about verified:true

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5042]
![image](https://cloud.githubusercontent.com/assets/128755/25809460/09510dd2-33db-11e7-82c4-3f81769576e9.png)

I was running the e2e tests and the test got stuck on the SMS view and the browser would still be in the "Verify your account" state. I inspected with devtools and /status was reporting "verified: true"

cc @shane-tomlinson any ideas?

**Comment by shane-tomlinson** [comment]
@vladikoff - the two *shouldn't* have any effect on each other. The browser should be in the background polling. That doesn't mean that's what's happening though. Consistently reproducible? Reproducible when run manually?

**Comment by shane-tomlinson** [comment]
@vladikoff - at this point, FxA doesn't notify the browser of anything because it expects the browser to be polling. That should have been the case even with pre-CAD screens.

**Comment by vladikoff** [comment]
from mtg: need to check this when using `same-tab`

**Comment by shane-tomlinson** [comment]
This is not unique to SMS or CAD, and doesn't require us to replace the original tab. It's enough just to unload about:accounts and verify in a 2nd browser. 

The odd part is no matter which STRs I use, I still see the OS notification that says "Nightly will begin syncing momentarily." As soon as I open about:preferences#sync, the browser updates its state. I'm going to (with more than a little hesitation) say we should not rule out a browser bug here.

**Comment by rfk** [comment]
> I'm going to (with more than a little hesitation) say we should not rule out a browser bug here.

/cc @mhammond :-)

Let me try to summarize the STR based on above comments:

* Sign in to sync by creating a new account
* Close about:accounts, open the hamburger menu
* Verify your account on another device

Expected: the hamburger menu transitions to show that your account is verified

Actual: the hamburger menu stays in the "verify your account" state

Is this more-or-less accurate?

**Comment by shane-tomlinson** [comment]
> Verify your account on another device

I suspected this was the case, but it's even easier. It doesn't matter where the account is verified.

> Is this more-or-less accurate?

Except for the above note, yeah.

**Comment by vladikoff** [comment]
@eoger could you check the STR and see if you hit this bug?

**Comment by vladikoff** [comment]
ping @eoger

**Comment by eoger** [comment]
Thank you, that was a pretty nasty bug introduced by the refactor of the fxa browser UI.
Filled https://bugzilla.mozilla.org/show_bug.cgi?id=1369092

**Comment by vladikoff** [comment]
Closing, into bugzilla!
