### ISSUE TITLE
Discuss adding a post-verification screen for secondary email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5043]
Would something like this work for onboarding @davismtl ? Adding email would take user to expanded email section in Settings.

**User Story:**  So that I don't get locked out of my account, as a user who owns more than one email address, I would like to to be CC:ed secondary notices to a secondary email to my Firefox Account.

* Subsequent screen: sign-in verification email
* Current browser is originating browser
* "No thanks" link leads to connect another (or subsequent) device screen

<img width="496" alt="ebfe5f06-3497-11e7-9ec0-ab3deadd77c5" src="https://cloud.githubusercontent.com/assets/68213/26010566/65632518-371b-11e7-94e1-98e69ba401ad.png">

**Comment by vbudhram** [comment]
@ryanfeeley I like this 👍, here are some quick thoughts of mine.

* Secondary emails are also useful to get account notifications. Not sure if it makes sense to include some of that in the messaging. 
* Could this also be prompted after a login? For example, `Looks like you don't have a backup email, would you like to add one?`

**Comment by davismtl** [comment]
>     Secondary emails are also useful to get account notifications. Not sure if it makes sense to include some of that in the messaging.
>     Could this also be prompted after a login? For example, Looks like you don't have a backup email, would you like to add one?

+1

Important to add in registration flow for new users but we need to hit existing users and login is a good time to do that.

**Comment by vbudhram** [comment]
From previous discussion, I mentioned a more generic `Secure your account` screen that could be shown after a login or verification step. This view would show several different options that a user could do to secure their account, secondary email, cleanup unused sessions/devices and delegate recovery.

This does seem big enough that we would want to put it into its own feature card though.

**Comment by rfk** [comment]
@vbudhram do you consider this in-scope for Q3?  Let's remove it from the milestone if it's not going to be in-scope.

**Comment by rfk** [comment]
Putting this in the "change email phase 2" milestone, we should revisit it this quarter as part of that work.

**Comment by rfk** [comment]
Closing this for now, let's revisit when we come up with new plans for the post-verification screen.
