### ISSUE TITLE
Remove "Maybe later" from /sms screen

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5044]
@ryanfeeley and @davismtl both agree that "Maybe later" should be removed from the /sms screen. It'll probably boost the number of users who send an SMS, and most /connect_another_device screens show the user the same app store links as showed on the /sms page.

ref #5026

**Comment by ryanfeeley** [comment]
Note that as we add other screens here (like secondary email or delegated account recovery options) this **Maybe later** can come out of retirement.
