### ISSUE TITLE
None of the “sha512” hashes in the integrity attribute match the content of the subresource.

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5052]
Open about:accounts sign in and devtools. Refresh a few times using the refresh button firefox. One of those requests will come back with error: 

> None of the “sha512” hashes in the integrity attribute match the content of the subresource.

cc @jrgm 

![image](https://cloud.githubusercontent.com/assets/128755/26002499/d7330d48-36fd-11e7-9739-95becf6bd1d8.png)

**Comment by vladikoff** [comment]
Firefox console: 

```
None of the “sha512” hashes in the integrity attribute match the content of the subresource. signin
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.contentCharset]  network-monitor.js:581
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.contentCharset] network-monitor.js:581
```

![image](https://cloud.githubusercontent.com/assets/128755/26002590/2366d550-36fe-11e7-9628-4d010c6e76c6.png)

**Comment by jbuck** [comment]
Re-uploaded content to the CDN

**Comment by vladikoff** [comment]
Fixed 👍

**Comment by mirague** [comment]
Did this happen only sometimes? Off-topic: We're facing a similar scenario where it only happens in a blue moon making it extremely hard to debug.
