### ISSUE TITLE
Send SMS UI Changes

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5057]
1) I noticed that in release, we are not displaying the app store buttons under the SMS field or legal text.

This is important because it actually indirectly explains to users what they will be sending themselves. This observation was made during UT on the Android page of the Moz.org site. 

We had included buttons in the feature doc mocups.

2) The legal text also seems like the same font size as our main call to action. This doesn't seem right. Ideally, we can make the font small enough so it is only on 3 lines rather than 4. I wouldn't be surprise if in French or German the text looks even longer, reaching 5 lines. 

If we don't want to go smaller on legal, then we should make the CTA more obvious. 

3) Also, we also have the "Why is this required?" and "Maybe later" on top of each other. Can we put them side by side like in the mockups from feature doc?

https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#

**Comment by davismtl** [comment]
Note that I may add more changes by the end of the day as I hear users go through this flow in UT.

**Comment by shane-tomlinson** [comment]
> I noticed that in release, we are not displaying the app store buttons under the SMS field or legal text.

We are, you must specify ?service=sync when visiting /sms. This is a dup of #4948.

<img width="708" alt="screen shot 2017-05-15 at 21 19 23" src="https://cloud.githubusercontent.com/assets/848085/26077544/515b168e-39b4-11e7-85d3-f761b7d6fdb4.png">

> The legal text also seems like the same font size as our main call to action. 

It's only the same size if you have gone into tablet mode. In desktop mode the CTA is 18px, the legal text 10px. In desktop mode, the legal text is 3 lines. See the above screenshot.

> Also, we also have the "Why is this required?" and "Maybe later" on top of each other. Can we put them side by side like in the mockups from feature doc?

Two issues. First, "Why is this required" was removed. Second, they were only stacked if you are in mobile or tablet mode, in desktop mode they were side by side.

**Comment by shane-tomlinson** [comment]
Here's an image from prod, with service=sync

<img width="751" alt="screen shot 2017-05-15 at 21 28 50" src="https://cloud.githubusercontent.com/assets/848085/26077880/88e7166a-39b5-11e7-8626-c2a51e38853b.png">

**Comment by davismtl** [comment]
Thanks @shane-tomlinson .
