### ISSUE TITLE
Add button missing hover and active state

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5062]
![hover](https://cloud.githubusercontent.com/assets/68213/26126031/103a6008-3a52-11e7-9c34-0e14ca2882ff.gif)

STEPS TO REPRODUCE
1. Sign into Settings
1. Hover mouse over Add, Refresh and other blue buttons

EXPECTED RESULTS
* Add button has hover and active effect like other blue buttons

ACTUAL RESULTS
* It just blue

**Comment by shane-tomlinson** [comment]
@philbooth noticed that this could be because the panels are not opened.
