### ISSUE TITLE
Stop hiding the subheading on Sync registration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5063]
In order to make the page more streamlined, we agreed to remove the subheading on the registration page. Other entry points have far higher password strength, completion rates, and verification rates. I think we should return it. Thoughts @davismtl?
![subheading](https://cloud.githubusercontent.com/assets/68213/26127047/f252fc86-3a55-11e7-82ec-8c605bfb6ba3.png)

**Comment by rfk** [comment]
+1 FWIW; hiding the info about where the user will end up, makes us that much more likely to open a phising/security issue if we accidentally expose that capability to other reliers.

**Comment by ryanfeeley** [comment]
One thing that the email correction feature taught us is that small details have a massive impact on how something is used. I bet this is the same case.

**Comment by davismtl** [comment]
I have no objections. I don't think that this will hurt. Will probably be positive.

**Comment by ryanfeeley** [comment]
Yay!!!!
