### ISSUE TITLE
Can anyone explain this drop in users going through the sendSms experiment?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5070]
Happened on 11-May-2017, which coincides with train 86 deployment.

<img width="739" alt="Screenshot of a chart showing a sudden drop in the number of users going through the sendSms experiment" src="https://cloud.githubusercontent.com/assets/64367/26150986/cf591348-3af8-11e7-9930-65ffbe93b8f5.png" />

Source: https://sql.telemetry.mozilla.org/queries/4615/source#9330

**Comment by shane-tomlinson** [comment]
Yup - https://github.com/mozilla/fxa-content-server/pull/4977.

We changed the bucketing logic. It used to be we decided whether the user was "in" the experiment at startup, even if the user was never going to see the CAD or SMS screens.

With that PR, we changed it so the decision is made IFF the user is going to see CAD or SMS.

**Comment by philbooth** [comment]
Splendid, thanks!

**Comment by rfk** [comment]
Does...does that mean that the big jump in treatment success rate on May 11 is a real thing and not a metrics artifact?

<img width="1062" alt="capture" src="https://cloud.githubusercontent.com/assets/34695/26177178/0d7cdecc-3b9c-11e7-8d60-67ef5dff31f1.PNG">

I was trying not to get excited about it in the theory that it might be a metrics problem, but \o/ if not!

**Comment by davismtl** [comment]
+1 on @rfk question

**Comment by shane-tomlinson** [comment]
> Does...does that mean that the big jump in treatment success rate on May 11 is a real thing and not a metrics artifact?

ISTM that treatment is doing much better than control with the new numbers, but we should check to make sure.

> I was trying not to get excited about it in the theory that it might be a metrics problem, but \o/ if not!

There *was* (and may still be) a metrics problem before May 11th - we reported far too many users in the experiment because we made the decision on startup instead of at the point where the screen selection is made.
