### ISSUE TITLE
Refresh button is dark on iOS after it is used once

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5076]
STEPS TO REPRODUCE
1. Have some device connected to sync
2. On an iOS device, open device manager
3. Tap on Refresh

EXCEPTED RESULTS
* It spins and returns to normal colour

ACTUAL RESULTS
* It's darker than it should be

![img_2420_1024](https://cloud.githubusercontent.com/assets/68213/26170633/1a1a340e-3b10-11e7-8ca0-7d889e0d0bf4.jpg)
![img_2419_1024](https://cloud.githubusercontent.com/assets/68213/26170632/1a17d362-3b10-11e7-80eb-565e44a6f968.jpg)

**Comment by vladikoff** [comment]
🗡 this is a dead P5
