### ISSUE TITLE
Discuss allowing OAuth reliers to receive FxA profile picture

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5080]
Currently we only offer reliers like Pocket and AMO the name and email address. What is involved from our end to also afford them the profile picture?

**Comment by rfk** [comment]
IIRC AMO can already request the profile picture if they want it, since they're a "trusted relier".  For Pocket, we just need to agree to allow it, and check with legal on ToS etc.

**Comment by vladikoff** [comment]
from mtg: seems like already possible
