### ISSUE TITLE
Allow "Skip this step" functionality to be triggered from the web

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5085]
The proposed onboarding flow for desktop Firefox has an explicit "Skip this step" for Firefox Account.

As FxA onboarding will soon include a varying number of steps, we should be able to trigger this functionality from the web.

e.g. If we offer three different account enhancements in a row, "Maybe later" would go to the next screen until the last screen when "Maybe later" could act like "Skip this step"

**Comment by vladikoff** [comment]
from mtg: not sure what the next step should be! need to discuss

**Comment by vladikoff** [comment]
follow up: Shane knows what to do 👍

**Comment by vladikoff** [comment]
From mtg with @ryanfeeley we decided to skip on this, the "skip" step works well right now with the new onboarding flow
