### ISSUE TITLE
Add new addresses and creditcards engines to "choose what to sync"

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-content-server#5087]
I thought I already opened one of these, but I can't find it. Apologies if it is a dupe.

We are adding 2 new engines to Sync, almost certainly to be named "Addresses" and "Credit Cards". Bug 1361285 tracks adding these to about:preferences#sync, and we need the same things listed in "choose what to sync".

Issue #4863 is possibly related, but I'll let @ryanfeeley and @davismtl fight out whether that strictly blocks this issue or not.

2 complications I see:
1) We want these engines to be disabled by default for existing Sync users, but checked by default in "choose what to sync". This means that the engines will default to disabled in Firefox (whereas every other engine defaults to enabled), which will complicate our "declined" handling.

2) We possibly don't want to show these engines for Desktop Firefox versions which don't have support for those engines - but that's questionable - for all we know, the user may have a version of Firefox that *does* support it that they will connect later. A similar issue exists for mobile - iOS certainly will not support the engine in the first few releases, Android may support syncing the data even though it wont actually use it. @ryanfeeley, @davismtl, what are your thoughts here?

In particular, 1) will require us to make additional changes to the webchannel messages for that flow. IIUC, the content-server only tells us what engines were declined - it doesn't tell us what engines were *offered* - which might make it tricky for us to know whether to enable these 2 new engines. I guess there are 2 directions we could take here - something like:

1) The browser tells the server if it knows about these engines - then assumes that if they don't come back in declined, then the user must have accepted them, so we should enable them. Whether this makes sense or not probably depends on the answer to (2) above.

2) The server includes a new list of engines that were offered - we then explicitly enable all engines in "offered" but not in "declined".

**Comment by mhammond** [comment]
Hah - found the tab on my laptop with the unsubmitted ticket :)

I wrote something there that is a facet of the above, but worth making explicit:

Complicating things slightly is that the support for these engines will be in a system extension, and in a worst-case scenario, this extension may be disabled. This means that UA sniffing probably isn't going to be good enough.

**Comment by shane-tomlinson** [comment]
> This means that UA sniffing probably isn't going to be good enough.

What if we extend [the fxaccounts:fxa_status](https://bugzilla.mozilla.org/show_bug.cgi?id=1308038) concept (but not the existing patch) to finally pass the `capabilities` the browser supports? We've been kicking around this idea for a long time, and we finally have a concrete use case. The browser could send back a list of supported Sync buckets and we'd show the ones listed?

**Comment by mhammond** [comment]
FTR, https://bugzilla.mozilla.org/show_bug.cgi?id=1361285 is for the client-side change to about:prefs, which has uxreview+ (ie, I believe we can consider the strings there as final)

**Comment by rfk** [comment]
from mgt: there's an open question here about how we signal opt-in to these collections, given that:

* They default to opt-out
* The output of the choose-what-to-sync screen is a list of "declined engines", not selected engines

@mhammond is going to think about this and suggest a path forward.

**Comment by ryanfeeley** [comment]
Desktop design: https://mozilla.invisionapp.com/share/AP8TFZ22G#/228643730_1-1_Autofill

**Comment by vladikoff** [comment]
@mhammond should we try to push this forward? I got FF56 in nightly today 👀

**Comment by rfk** [comment]
There's more details on the required behaviour in the email thread here:

  https://mail.mozilla.org/pipermail/dev-fxacct/2017-June/002378.html

@mhammond if you're happy with where that thread wound up, can you please propose concrete WebChannel protocol changes for us to implement on the FxA side?

**Comment by mhammond** [comment]
At a high-level, I believe all we need is:

1) the content server shows 2 new engines, "Addresses" and "Credit Cards" for all desktop 56+.
2) the browser is confident that these 2 engines have been offered, so the fact they aren't in "declined" means they were accepted.

> What if we extend the fxaccounts:fxa_status concept (but not the existing patch) to finally pass the capabilities the browser supports?

I'm not sure how far to go here. There doesn't seem value in listing all the engines the client supports, as the list of existing engines is already hard-coded - ie, I'm guessing that it's not useful for the content server to work out what to do if somehow "bookmarks" wasn't listed. I'm open to the client listing all these existing engines, it just doesn't seem particularly worthwhile.

So as a straw-man: desktop asserts it supports the "addresses" and "creditcards" capabilities - all other engines remain implied.

When FxA sends the "login" message, it should also list the engines it offered.

So - a concrete proposal:

* When FxA sends a "fxaccounts:fxa_status" message, desktop currently replies with {signedInUser: {email: "...", ...}. We extend that so it also includes a top-level "capabilities" object, which looks something like, say, {capabilities: {engines: ["creditcards", "addresses"]}}. As mentioned above, other engines remain implied.

* If the client supplied capabilities["engines"], the "fxaccounts:login" message sent back to the client will include, say "enginesOffered" - in this case it would just return exactly what was passed in capabilities. This is the signal to desktop that the engines were definitely offered, so it can be assumed that the user left them selected if they don't appear in declined. All other engines remain implied here too.

I'm happy to change the spelling of any of the above, and also to re-think whether existing engines should remain implied. @shane-tomlinson, WDYT?

**Comment by shane-tomlinson** [comment]
Design from @ryanfeeley:

<img width="378" alt="screen shot 2017-06-13 at 15 55 01" src="https://user-images.githubusercontent.com/848085/27175776-26f833c4-51b8-11e7-8fc6-8fdd4a736c8d.png">

**Comment by shane-tomlinson** [comment]
@mhammond - your approach sounds reasonable to me. What do you think we need for the MVP for 56? 

> 1. the content server shows 2 new engines, "Addresses" and "Credit Cards" for all desktop 56+.
> 2. the browser is confident that these 2 engines have been offered, so the fact they aren't in "declined" means they were accepted.

I could probably get the above done in a day or two, if I hard-code the Fx version, and if I ignore the capabilities scheme. 

Do you think the capabilities scheme is worthwhile? I'm happy to implement it, thought my guess is that it'll take an additional day or two to get things just so.

**Comment by ryanfeeley** [comment]
@mhammond Oops, I wasn't clear that only desktop would be making it.

**Comment by vladikoff** [comment]
From mtg: 

@shane-tomlinson if `capabilities` is a lot of work then let's try this:

1. Detect Firefox Desktop 56+
2. Send a new array of `engines` or `offeredCapabilities` - this lists all presented capabilities.

If `capabilities` is easy then replace 1.  

cc @eoger

**Comment by shane-tomlinson** [comment]
For the phase 1 MVP, I would almost certainly just hard code Fx Desktop 56 and send `engines` to the browser. Phase 2 would be to remove the UA sniff & look for capabilities. 

Phase 2 could be super easy but the difficulty is still a little unknown whereas UA sniffing is a well trodden path. I might even be able to get them both done in one train, I just want to have a plan to get something in front of users ASAP.

**Comment by vladikoff** [comment]
> I just want to have a plan to get something in front of users ASAP

Yeap, I asked @mhammond and he said sending `engines` to Desktop should be good 👍  
(As mentioned in comment above)

**Comment by mhammond** [comment]
Sadly, I was wrong about the fact we can hard-code everything - the entire CC feature has some risk of not making 56. Addresses seems fine - can we maybe hard-code that to get the ball rolling and handle CC later?

**Comment by shane-tomlinson** [comment]
> Sadly, I was wrong about the fact we can hard-code everything - the entire CC feature has some risk of not making 56. Addresses seems fine - can we maybe hard-code that to get the ball rolling and handle CC later?

I'll start with addresses first then, thanks @mhammond!

**Comment by mhammond** [comment]
Note also none of this has landed in nightly yet. Bug 1361010 is the tracker, but that's probably not the right bug for when nightly can take advantage of this issue - I'll open that Monday.

**Comment by shane-tomlinson** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1374501.
