### ISSUE TITLE
Update Choose What to Sync graphic with this SVG version

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5098]
We have a bunch of new illustrations! Let's update the Choose What to Sync graphic with this SVG version. May require some vertical spacing finesse. Contact me to work through. Don't forget to responsively scale it down like the current version.

![current-proposed](https://cloud.githubusercontent.com/assets/68213/26411814/d50ef20e-4074-11e7-8c4b-ac727671b15a.png)

ZIPPED SVG attached:
[choose-what-to-sync.svg.zip](https://github.com/mozilla/fxa-content-server/files/1026104/choose-what-to-sync.svg.zip)

**Comment by vladikoff** [comment]
wow!

**Comment by shane-tomlinson** [comment]
@ryanfeeley these icons remind me of two speakers next to a laptop + it looks pretty washed out. Are we sure about this?

**Comment by ryanfeeley** [comment]
@shane-tomlinson A darker image is coming! Not sure he'll tackle the stereo problem. I never saw that myself, though I prefer concentric drivers to three-way designs :)

**Comment by ryanfeeley** [comment]
@shane-tomlinson Here is the higher contrast image! [Artboard 7.svg.zip](https://github.com/mozilla/fxa-content-server/files/1085716/Artboard.7.svg.zip)
