### ISSUE TITLE
Request: add explanation of benefits to verification screen

### ISSUE THREAD

**Issue by mcomella** [mozilla/fxa-content-server#5101]
@liuche and I are building a standalone Sync library for Android/iOS. When a user signs into their FxA, we need them to verify their account in order to access their sync data.

I'm concerned that, without an explanation about why verification is required (i.e. to get sync data), users will cancel their login after they entered their credentials but before they verified their account.

I propose that we could explain why verification is useful to the user on the verification page (e.g. "To grant the application access to your sync data, you must verify your account.").

@rfk mentioned that perhaps the wording could be improved and this information applied to all sync log ins and requested I open that possibility up to discussion here.

---

As a library, one alternative (or additional) solution could be when the user hits cancel to after logging in but before verifying their account, prompt the user with a dialog: "If you don't verify your account, <application-name> will be unable to access your sync data. Continue?"

I'm not a designer so I don't know what's best for the library and wider sync. Any thoughts?

**Comment by rfk** [comment]
Concretely (and @mcomella please correct me if I've misunderstood) the ask is to consider whether we make it more obvious that this screen represents a mandatory step that the user has to complete, and why:

<img width="346" alt="capture" src="https://cloud.githubusercontent.com/assets/34695/26425589/aff67498-4118-11e7-888b-c167254ee74b.PNG">

@ryanfeeley I know you've wordsmithed this quite a lot already, any feedback on the above?

**Comment by mcomella** [comment]
I have no credentials for UX'ing, but I think I'd like to emphasize to the user, "If you don't verify, **sync won't work!**" which I don't feel the either the current implementation or the proposal above highlight.

**Comment by ryanfeeley** [comment]
It's a good point. A lot of users will miss the **Confirm this sign-in** heading, and just see "To better protect" and assume it's an optional step. It's a mandatory step, and we can perhaps make that more immediately clear.

@rfk @mcomella how about something like?
* To confirm this sign-in, click the confirmation the link we have emailed to user@example.com

**Comment by rfk** [comment]
I like making it more next-action oriented, seems like a significant improvement.  I wonder if we can be even more specific with something like "To allow access to your Firefox data...".

**Comment by mcomella** [comment]
> "To allow access to your Firefox data..."

I like this because it reminds the user what they're getting from this extra step. Rather than "confirm this sign-in" (as a user, what do I get out of that? Maybe I don't actually want to put in the effort to sign in anyway), the user sees "To allow access to your Firefox data..." (as a user, "Oh, I do really want to access my bookmarks from this browser/app, I should do what it says.").

**Comment by ryanfeeley** [comment]
@rfk @mcomella Much preferred, and is only shown to Sync users, so we can be more specific.

How about:
* To allow access to your Firefox data, open the confirmation link sent to user@example.com

**Comment by rfk** [comment]
This WFM 👍 

I kinda wanna A/B test it to see whether it really performs better...@shane-tomlinson how much hassle would that be for such a small change, given our recent improvements to experiment metrics?

**Comment by vladikoff** [comment]
Current:

![image](https://user-images.githubusercontent.com/128755/37299491-d8a7434c-25f9-11e8-85e3-b42d5f590654.png)

**Comment by vladikoff** [comment]
from mtg: closing it as a WONTFIX (from @ryanfeeley)
