### ISSUE TITLE
Content server CSP errors on settings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5106]
@vladikoff says to just paste this screenshot.
<img width="1866" alt="screen shot 2017-05-25 at 4 58 52 pm" src="https://cloud.githubusercontent.com/assets/68213/26470412/93b32c24-416b-11e7-8ba2-cdc79e8c6665.png">

**Comment by rfk** [comment]
Did this happen on ly when you expanded the "devices and apps" view?  I wonder if there's an accidental inline script in one of the SVGs or something like that.

**Comment by vladikoff** [comment]
@rfk it did happen when he was off Wifi , you can see the POST request failing
