### ISSUE TITLE
fxa-content request logging is broken

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-content-server#5111]
`{"Timestamp":1496238677870000000,"Logger":"fxa-content-server","Type":"server.requests.127.0.0.1 - - \"POST /metrics HTTP/1.0\" 200 2.608 16 \"https://accounts.firefox.com/\" \"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0\"","Severity":6,"Pid":15482,"EnvVersion":"2.0"}`

Because everything gets concatenated into the "Type" field you can't do anything useful in Kibana.

This is because we [log using a single parameter](https://github.com/mozilla/fxa-content-server/blob/277e046a3a27ff946a709fd03f10e0fa04ad565c/server/lib/logging/route_logging.js#L33).

**Comment by vladikoff** [comment]
> Will need to add Application logs for the content-server into Kibana

**Comment by vladikoff** [comment]
@udaraweerasinghege the first param in the linked code above should be the name, 'server.requests' 

The second one should be the actual object. 

See example in the profile server https://github.com/mozilla/fxa-profile-server/blob/a8fc8d6f62b5e2c8ea19ecf61ae224d447d27c00/lib/server/_static.js#L34
