### ISSUE TITLE
Prime iOS users about notification permission prompt

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5122]
Push technology is coming to iOS and will make Sync blazingly fast. Sync will simply "sync" more immediately, and changes will appear instantly. It's the holy grail.

The downside is that in order use Push, we need their permission for iOS notifications because it is used to register with our Push service.

Currently, as soon as iOS users submit the login or registration form, they are presented with this iOS notification permission dialog:
<img width="209" alt="screenshot 2017-06-01 16 42 06" src="https://cloud.githubusercontent.com/assets/68213/26700069/0781c312-46ea-11e7-81a9-b4c74c7c10eb.PNG">

Too many of them are declining.

Instead we would like to prime them so that they have some context before seeing this dialog.

Here is one approach shown only to iOS users on login (or registration). Let's discuss!
<img width="509" alt="screenshot 2017-06-01 16 42 06" src="https://cloud.githubusercontent.com/assets/68213/26699884/60ffe37a-46e9-11e7-9472-33e55d8dcae0.png">

**Comment by davismtl** [comment]
Glad we're taking a look at this. However, that proposed design doesn't follow best practice for push. (current version doesn't either, obviously)

After login/registration, we should have an entire screen explaining benefit. If the user says "Allow", display pop-up where they will click "Allow" again. If they say, "not now", we don't display it.

The reason being is if the user clicks "Don't Allow", we can never ask them again. We don't want to be in that situation. By having them say "not now" on an interstitial, we can ask them again at a later date.

Also, I'd like us to say something more meaningful than just **fastest** Sync experience.

We may need to work with iOS team on this but it is on their radar already. They've brought it up in a meeting with me this week.

**Comment by vladikoff** [comment]
> After login/registration, we should have an entire screen explaining benefit.

Hm if I understand your proposal correctly, then it would be too late to show that screen. Device Registration happens right at login. To register we need the push callback. To get the callback we need the permission accepted. To get the user to accept it, we need to explain why they need it :)

**Comment by vbudhram** [comment]
> Device Registration happens right at login

Can we update device info after it has been registered? If so, then it could be possible to show the notifications benefit screen, then prompt for permissions then update with pushUrls?

**Comment by vladikoff** [comment]
> Can we update device info after it has been registered?

Yeah that is possible, but when I think about it it feels fragile. We will need to send another request. 
If that request is from the client then FxiOS needs to send it. 
If that request is from the content-server, then we need to keep the content server open in FxiOS, so it can send the update.

**Comment by davismtl** [comment]
It's likely worth asking iOS team if they have any features unrelated to accounts that may require the use of Push notifications (e.g. reading list reminder). _Perhaps_ there is a reason to ask outside of the FxA registration/login flows.

@vladikoff if device registration depends on it, what happens if users refuse push notifications?

Also, IIUC, we can still use push internally for the functioning of the app, regardless of what the user chooses. The user's preference in the pop-up is for displaying notifications outside of the app (lock screen, badge icon, banner). Is that interpretation correct?

**Comment by vladikoff** [comment]
> Also, IIUC, we can still use push internally for the functioning of the app, regardless of what the user chooses.

This is not the case (per Mobile team). Once the user cancels then we do not get a Push callback from Apple's services

**Comment by vladikoff** [comment]
Okay I'm going to close this if we are not planning to do any content-server work make this experience better. Please reopen if we have an actionable plan that we can implement.
