### ISSUE TITLE
Remove disabled button state for login and registration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5130]
We have received feedback from onboarding user testing that users are perceiving our disabled submit buttons (on login and registration) to mean that the forms themselves are disabled.

Instead of making them appear enabled when minimum form requirements are met, we should make them always appear enabled and rely on our now excellent form validation to keep users on the right path.

**Comment by davismtl** [comment]
Can we cohort this? While I'm confident it will help users, I think it's important we measure the impact of changes we make to our forms.

**Comment by ryanfeeley** [comment]
@davismtl If there's bandwidth, sure! What I expect we should see a change in.

1. Screen views should remain stable
   * fxa.content.screen.signin/signup/force_auth
1. Authentication success should increase the most
   * fxa.content.signin/signup/force_auth.success
1. Too short password should not increase
   * fxa.content.error.signin/signup/force_auth.auth.1009
1. Missing password should not increase
   * fxa.content.error.signin/signup/force_auth.auth.1010
1. Missing email should not increase
   * fxa.content.error.signin/signup/force_auth.auth.1011

Make sense?

Are there other metrics we can use? Are flow/engage metrics still up?

**Comment by shane-tomlinson** [comment]
IRL conversation - We can remove the "disabled" state universally, not just to these two forms.

**Comment by ryanfeeley** [comment]
@rfk Here's a great one to a/b test.

**Comment by vladikoff** [comment]
from mtg, Basically: Active state is just no `disabled` attr

**Comment by shane-tomlinson** [comment]
I had a quick go at this, *almost* everything worked as expected. Some of the forms in the /settings page need to have better error validation before this approach is used universally, esp the settings->avatar->camera page. It's possible to click "Take picture" without first granting browser permissions to use the camera. It seems like we should be able to disable the button for this special case until permissions are granted.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Well spotted.
