### ISSUE TITLE
Use Hoverpad app icon for devices list

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5134]
Copy existing add-ons/Pocket colour, and use this SVG for the Hoverpad icon (but call it Notes).
[universal-notepad-large.svg.zip](https://github.com/mozilla/fxa-content-server/files/1068679/universal-notepad-large.svg.zip)

**Comment by vladikoff** [comment]
Ty!

**Comment by vladikoff** [comment]
@ryanfeeley is it supposed to be this dark 
![image](https://user-images.githubusercontent.com/128755/27091604-a66690d2-502e-11e7-8a7f-c2363c2d3dda.png) ?

**Comment by ryanfeeley** [comment]
@vladikoff No, it should match the Pocket or Add-ons icons we have. I viewed source and in HTML it is set as #505050. Is that applicable in HTML or do you want a new graphic?

**Comment by vladikoff** [comment]
This was fixed!

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/pull/5245
