### ISSUE TITLE
Add remoteAddressChain support for content server logs

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5149]
Example in Hapi: https://github.com/mozilla/fxa-auth-server/blob/2610d2f5f4c46b069b05239d2f6f831e4d216fa1/lib/server.js#L276

**Comment by vladikoff** [comment]
@udaraweerasinghege let's try to add this to the addressChain logger that we just added. See if the other servers have a test for this

**Comment by udaraweerasinghege** [comment]
Do we want to add client address as another property as well? https://github.com/mozilla/fxa-auth-server/blob/2610d2f5f4c46b069b05239d2f6f831e4d216fa1/lib/server.js#L286

**Comment by vladikoff** [comment]
@udaraweerasinghege yeap! good notice!
