### ISSUE TITLE
Discuss method to update verified status for secondary emails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5151]
Currently, on the secondary emails panel, a user has to click the `Refresh` button to see the verification state of the email changed. While this saves resources it does provide an inconsistent and confusing user experience.

Some possible ideas

* Add polling when secondary email panel is open
  * If there is an unverified email, and secondary email panel is open we could poll auth server for updates.
* Send push notification
  * Have auth-server send push notification on email status update and update content server accordingly.
* Open a webchannel/websocket
  * When panel is open, listen for email update events.

My preference is probably to add polling and *see how it works*. There shouldn't be too much extra work because we have all the functions already.

@shane-tomlinson @vladikoff Thoughts?

**Comment by rfk** [comment]
> Open a webchannel/websocket 

We have a couple of instances of this "timely updates" problem now, e.g. in the devices view as well as here.  Are we at the point where we should consider a more generic solution based on e.g. a shared websocket through which the auth-server can publish events direct to the page?

(It's my understanding that websockets might be better than push for this because push requires e.g. a permission prompt when used from web content, but I don't understand it deeply so I could easily be wrong).

**Comment by shane-tomlinson** [comment]
Here's an interesting read from 5 years ago. 

https://www.w3.org/2012/10/Qualcomm-paper.pdf

If the issues mentioned haven't been addressed, both XHR polling and WebSockets kill battery life on mobile devices.

WebSockets hold open a TCP connection to the server, possibly causing fixed limit resource exhaustion in, e.g., sockets or file descriptors. We could add more servers to address this, but...

IIUC, push notifications were developed in part to solve these problems. Can we get a "pass" from the Firefox team to avoid the permission prompt?

**Comment by vladikoff** [comment]
my thoughts: 

I don't think the real time updates to settings are required. Polling is fine for the `unverified` email, but even then users can just use `Refresh`. I'm also not sold on the custom push setup and WebSockets. Too much overhead for no pay off.

**Comment by vbudhram** [comment]
> I don't think the real time updates to settings are required

I am kind of along the same lines too. Websockets would be good but I'm not sure we are at the tipping point for adding it. If we narrowed requirements for polling down to

1) Only when emails panel open
2) Only when there is an unverified email
3) Match polling rate as confirm account

this good be a good first prototype.

**Comment by vladikoff** [comment]
Let's revisit this later
