### ISSUE TITLE
/connect_another_device asking user to sign in again even though the user just signed up

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5159]
I just reproduced this in Firefox 53, my guess is E10s is enabled.

STR

1. Open about:preferences#sync
2. Sign up for a new Firefox Account
3. In the same browser, open the verification link
4. Why am I being asked to sign in *again*? I just signed in?
5. Look in localStorage. The account is stored, without a sessionToken.

This has all the hallmarks of the E10s problem where localStorage from about:accounts is isolated from localStorage in the verification tab.

<img width="1078" alt="screen shot 2017-06-19 at 11 54 03" src="https://user-images.githubusercontent.com/848085/27282202-e341d3ec-54e6-11e7-8155-f0941f69e7eb.png">

This means that our multi-device metrics for CAD phases 1 and 2 are likely being inflated by users that are being asked to sign in again. AGGGGGHHHH.

cc @davismtl, @philbooth, @rfk, @ryanfeeley

**Comment by davismtl** [comment]
Forget phase 1-2, this means our overall m-d numbers are likely inflated, no?

This feels pretty major since e10s in on by default in 54.

**Comment by philbooth** [comment]
> ...this means our overall m-d numbers are likely inflated, no?

Fwiw, I think we've always known there are a lot of people classed as multi-device who aren't really. I have an open action item to tweak the logic for making that decision, which I will definitely get round to this week.

The question is how many of these people are there? I have a chart that attempts to answer that:

https://sql.telemetry.mozilla.org/queries/4837#9867

**Comment by seanmonstar** [comment]
So, what is the current thinking here? Killing `about:accounts` gives us this for "free"?

**Comment by shane-tomlinson** [comment]
> So, what is the current thinking here? Killing about:accounts gives us this for "free"?

This is fixed by a combination of browser and FxA patches. Closing.
