### ISSUE TITLE
Discuss how we should animate new illustrations

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5168]
We have some great new illustrations that have been animated in after effects.

Here is an example in very compressed GIF format:

![open-link_1](https://user-images.githubusercontent.com/68213/27443258-76e5a500-5740-11e7-8e4f-13948e6c014b.gif)

Frame-based animations are too large (250kb or more), but we would like them animated.

The animations could be done in CSS as they are all simple shape transforms (fade, scale, rotate).

Let's discuss what works best? We can provide PNGs or SVGs of the component pieces.

For reference, here is one of the better CSS animation sites out there: https://tympanus.net/codrops/tag/animation/

**Comment by ryanfeeley** [comment]
Email: ![sent](https://user-images.githubusercontent.com/68213/27445229-f87e30cc-5746-11e7-9c94-e3671ddf0848.gif)

**Comment by ryanfeeley** [comment]
![sync devices](https://user-images.githubusercontent.com/68213/27445236-00315b46-5747-11e7-8967-f77694bc2d6d.gif)

**Comment by ryanfeeley** [comment]
![syncing](https://user-images.githubusercontent.com/68213/27445241-052863a6-5747-11e7-97e2-b2a656193787.gif)

**Comment by potch** [comment]
These all lend themselves extremely well to SVGs animated using CSS. Can take a pass at one to see what it would look like code and payload-size wise.

**Comment by ryanfeeley** [comment]
@potch That would be fantastic! We'll get some SVGs ready.

**Comment by ryanfeeley** [comment]
@potch Attached! The illustrations are done by @mart3ll and the animations were done in After effects by @epang [Syncing.zip](https://github.com/mozilla/fxa-content-server/files/1098197/Syncing.zip)

**Comment by potch** [comment]
@ryanfeeley any way I can get the final graphic composed, with circles and hearts placed in the proper locations in a single SVG?

**Comment by ryanfeeley** [comment]
@vladikoff I'm on PTO but these compose SVGs are in another issue. Can you
find?

**Comment by vladikoff** [comment]
@ryanfeeley might have this!

**Comment by ryanfeeley** [comment]
@potch Updated the assets and included composed SVG (comp.svg) as well! Is this what you need? [Syncing-assets.zip](https://github.com/mozilla/fxa-content-server/files/1140326/Syncing-assets.zip)

**Comment by potch** [comment]
@ryanfeeley awesome. thanks!

**Comment by ryanfeeley** [comment]
@potch Eric suggest we remove the movement of the chain links at the beginning.

The SVGs for all four are now here!

[SVG Files.zip](https://github.com/mozilla/fxa-content-server/files/1146366/SVG.Files.zip)
