### ISSUE TITLE
Capitalize the authorization code when typed into the form

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5169]
Code in the email is capitalized, so it feels that there should be similar treatment for when it's actually typed into the form. Otherwise, my mind instantly goes to "is it case sensitive? probably not...", and I'm double checking myself - "what I typed looks different visually".

![screen shot 2017-06-22 at 10 56 30 am](https://user-images.githubusercontent.com/465422/27448508-e4ffcd56-5739-11e7-8916-93ffa440a7e2.png)

**Comment by vladikoff** [comment]
@ryanfeeley thoughts?

**Comment by shane-tomlinson** [comment]
@seanmonstar had a good point that this is pretty trivial to do using the `text-transform: uppercase` CSS declaration. Unfortunately that also uppercases the placeholder text, and I didn't put in enough time to figure that part out.

**Comment by ryanfeeley** [comment]
Bummer about the placeholder inheritance. Can't be solved? If solvable, do it!

**Comment by seanmonstar** [comment]
It's possible to style the placeholder text differently: https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder

```css
#code {
  text-transform: uppercase;
}

#code::placeholder {
  text-transform: none;
}
```

Standardized in Firefox 51, before that there is `::-moz-placeholder`.

**Comment by vladikoff** [comment]
:shipit:

**Comment by ryanfeeley** [comment]
@davismtl This would make life easier for people who type in authorization codes, and likely improve success. Low hanging fruit!

**Comment by davismtl** [comment]
@ryanfeeley is it case sensitive? Will it fail to unblock if it is not identical case?

**Comment by ryanfeeley** [comment]
@davismtl It is not, this just reduces user worry that it might be in the middle of typing a code.

**Comment by davismtl** [comment]
yeah, makes sense. Let's bring it up in triage on Monday.

**Comment by shane-tomlinson** [comment]
This is a pretty easy, CSS only, change, we can do what @seanmonstar mentioned above.
