### ISSUE TITLE
test failures on travis: Failed test: generates a valid assertion

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5178]
For an example, see https://travis-ci.org/mozilla/fxa-content-server/builds/248398128?utm_source=github_status&utm_medium=notification

> Failed test: generates a valid assertion
> => Invalid request signature

This seems to have started when we merged the [node v6 changes](https://github.com/mozilla/fxa-content-server/pull/5173), but I can't figure out why travis didn't catch the problem then. 

@vladikoff - you mentioned yesterday that the verifier was still on node 4, could this be related?

**Comment by philbooth** [comment]
Fwiw, I think the js-client tests are failing with the same error:

https://travis-ci.org/mozilla/fxa-js-client/builds/237501080

(debug locally to see the error)

**Comment by philbooth** [comment]
@shane-tomlinson, at least for the js-client, the key commit in the auth server seems to be the buffers => strings change, `0cfd39ca`. Tests pass against the node 6 commit but fail with that one.

**Comment by philbooth** [comment]
Fwiw, sitting with @seanmonstar now, think we have a fix.

**Comment by philbooth** [comment]
I believe this was fixed by mozilla/fxa-auth-server#1966. Closing, but re-open if it's still an issue for anyone.
