### ISSUE TITLE
Sign-in flow: Never send users to about:preferences after Sign-in

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#5197]

**Comment by seanmonstar** [comment]
This sounds like a good-first-bug, but I don't actually know what it entails. @shane-tomlinson am I right?

**Comment by shane-tomlinson** [comment]
> This sounds like a good-first-bug, but I don't actually know what it entails. @shane-tomlinson am I right?

We have little/no control over this and require a browser patch to make it so. If the user opens FxA within about:accounts, as soon as the browser detects the account is verified, it takes over and displays settings.

We should file an issue about this in bugzilla. If the browser stops using about:accounts and instead opens FxA directly, this problem will be solved automatically.

cc @mhammond, @eoger - is there already a bug on file about scrapping about:accounts? How about one to stop sending users to about:preferences#sync as an interim step?

**Comment by mhammond** [comment]
Is this https://bugzilla.mozilla.org/show_bug.cgi?id=1357085?

**Comment by shane-tomlinson** [comment]
That's the one, thanks @mhammond!

**Comment by shane-tomlinson** [comment]
Fx 57 is in Nightly now, we'll have to get the browser patch landed in the next 5 weeks or so.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1357085#c7

**Comment by rfk** [comment]
As Kit notes in https://bugzilla.mozilla.org/show_bug.cgi?id=1357085#c8 there's also a content-server side portion to this, wherein we need to transition away from the confirmation polling screen and show some useful content.

**Comment by shane-tomlinson** [comment]
> As Kit notes in https://bugzilla.mozilla.org/show_bug.cgi?id=1357085#c8 there's also a content-server side portion to this, wherein we need to transition away from the confirmation polling screen and show some useful content.

That part is pretty easy. In fact, if about:accounts is removed, [it's already done](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-desktop-v2.js#L67).

**Comment by davismtl** [comment]
This issue has overlap with
mozilla/fxa-content-server/issues/5262

**Comment by vladikoff** [comment]
@shane-tomlinson was this fixed? I had to adjust the e2e test to not expect prefs as a landing target :)

**Comment by vladikoff** [comment]
Needs 57 detection
