### ISSUE TITLE
Tapping "Tap to sign in" on Android takes me to a "Create a Firefox Account" flow 

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5216]
After getting logged out (for some unknown to me reason) out of my account, and being unable to sign-in on Desktop (see https://github.com/mozilla/fxa-content-server/issues/5215), I'm seeing some weird behaviour on Android.

I'm currently seeing "Cannon connect. Tap to sign in." message in Sync Prefs. Tapping on it takes me to `about:accounts?action=force_auth&entrypoint=preferences` page. Which renders as a "Create account" dialog.

Pressing "Create Account" takes me to a "Sign-in confirmed", and I get a "sign in confirmed email". Attempting to sync fails however, and I'm back to the "Cannot connect. Tap to sign in.". 

![screenshot_1499468804](https://user-images.githubusercontent.com/465422/27979965-f9f2b894-6347-11e7-86ba-4634a309f437.png)

**Comment by grigoryk** [comment]
And on iOS I see the same dialog, but with a `Account no longer exists. Recreate it?` message...

**Comment by grigoryk** [comment]
On iOS, clicking through "Create Account", I get an authorization code prompt. After entering an authorization code, I'm taken to Sign-in Confirmed page. Trying to sync, I get another "can't sync" message. Opening the about:accounts page, I'm taken to the signin page directly, where it's asking me for a password. Entering my password triggers another authorization code prompt. After entering the code again, I am _now_ able to sync!

Going back to my Android device, it's still stuck at the "Create Account" state, which I follow through, get another authorization code prompt, enter it, and I'm now able to sync again.

**Comment by grigoryk** [comment]
After following through the steps above, I'm now able to sign-in on Desktop as well! E.g. https://github.com/mozilla/fxa-content-server/issues/5215 did not happen anymore.

**Comment by shane-tomlinson** [comment]
@grigoryk - is this fixed now?

**Comment by grigoryk** [comment]
Yes, I believe this was a different manifestation of https://github.com/mozilla/fxa-content-server/issues/5215

**Comment by vladikoff** [comment]
👍 thanks for the response
