### ISSUE TITLE
Fix show password border radius problem

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5233]
I noticed that the Show Password has a different border radius than the parent text input.

![border-radius](https://user-images.githubusercontent.com/68213/28134890-66f137b8-6712-11e7-9711-09c33215ae3a.gif)

I was hoping to fix this myself, but was unable to do all the states (hover, focus, etc) in DevTools.

It looks like what is 2px should be 4px.

Anyone keen to try?

**Comment by apoorvasingh17** [comment]
Has this issue been resolved?

**Comment by vladikoff** [comment]
@apoorvasingh17  hey, nope still happening! See links above for the attempted pull request

**Comment by xevrem** [comment]
Change the CSS class `.password-row .show-password-label` from `border-radius: 0 2px 2px 0` to `border-radius: 0 4px 4px 0` it is used in `<label for="show-old_password" class="show-password-label">` which is causing the pinched border on the right-side corners. the
