### ISSUE TITLE
Prevent page zooming on mobile browsers

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5234]
STEPS TO REPRODUCE
1. Visit FxA settings on a mobile browser in responsive view
2. Pinch or double tap to zoom

ACTUAL RESULTS
![2017-07-12 22 34 17](https://user-images.githubusercontent.com/68213/28148865-5f1d3d62-6757-11e7-8c1f-23bc37c45bcb.png)

EXCEPTED RESULTS
- Zoom is disabled as described in this @darkwing [blog article](https://davidwalsh.name/zoom-mobile-browsers)

**Comment by vladikoff** [comment]
@shane-tomlinson any input on this?

**Comment by ryanfeeley** [comment]
However Facebook does it works well on mobile web.

**Comment by shane-tomlinson** [comment]
Ref #2228 where this was previously discussed.
