### ISSUE TITLE
Avatar view messed up on smallest iPhone

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5235]
Let's get iOS ready for account management.

STEPS TO REPRODUCE
1. Upload an avatar in Firefox for iOS

EXPECTED RESULTS
- Image preview area fits into white overlay
- Image not stretched

ACTUAL RESULTS
- Image stretched, not centered, and black preview area is oversized
![2017-07-12 22 33 35](https://user-images.githubusercontent.com/68213/28148977-28671a12-6758-11e7-9cc2-ec0846f5bcc6.png)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/3485
