### ISSUE TITLE
Allow users to correct phone number after resend

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5244]
STEPS TO REPRODUCE
1. Sign up for a Sync account
2. Verify in original Firefox
3. Send yourself an SMS
4. Resend the SMS
5. Realize that you entered the wrong phone number

EXPECTED RESULTS
![resent-expected](https://user-images.githubusercontent.com/68213/28228648-5af1feba-68ad-11e7-97c7-146d2fcc30f5.png)

ACTUAL RESULTS
![resent-actual](https://user-images.githubusercontent.com/68213/28228348-22fbd914-68ac-11e7-9895-a4af1599e830.png)

**Comment by vladikoff** [comment]
Oh I actually did get "mistyped number?"  before, not sure where it went...

**Comment by ryanfeeley** [comment]
@vladikoff My first screenshot was wrong as it wsa the "link to sent" and not "link resent to".

Although whoever did the shake is owed a high five from me. Are we using that in other places too?

**Comment by vladikoff** [comment]
@ryanfeeley "I keep getting mistyped number", do you not get the link?

**Comment by ryanfeeley** [comment]
@vladikoff That not relevant. A user could have entered in the wrong number and not realized until after hitting resend.

**Comment by vladikoff** [comment]
@ryanfeeley Oh i see it now, you hit resend and that made "mistyped?" disappear. yea we can fix that. 

(I don't think it is a ` FxA-130: Crouton Flow` bug though, this seems minimal. However we can still fix it)

**Comment by ryanfeeley** [comment]
The boy who cried crouton flow.
