### ISSUE TITLE
Blue buttons lack active state

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5254]
STEPS TO REPRODUCE
1. Visit devices list
1. Click and hold Refresh button
1. Drag cursor off button while holding

EXPECTED RESULTS
1. Button becomes dark when clicked
1. Button returns to default colour when cursor dragged away

ACTUAL RESULTS
![off-state](https://user-images.githubusercontent.com/68213/28381127-bcf09526-6c87-11e7-91bb-5e6b965216cd.gif)
1. Button does not change when clicked
1. Button gets darked when cursor dragged away

**Comment by shane-tomlinson** [comment]
Ref #5255
