### ISSUE TITLE
Add drag-off state for buttons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5255]
All of our buttons have a hover state. We should apply the same state for when users click on a button, but drags off. This lets the user subtly know that the action will be performed, but which button to return their cursor to if they want to perform the action.

Example from Bootstrap: 
![what-a-drag](https://user-images.githubusercontent.com/68213/28381400-bc2b35c8-6c88-11e7-8a97-0a6a659ffcc4.gif)

OS X does not do this, but likely because they don't offer hover states for their buttons:
![off-state-osx](https://user-images.githubusercontent.com/68213/28381426-cf7a5fe6-6c88-11e7-9b90-ae55c68e2cf6.gif)

**Comment by ryanfeeley** [comment]
Related: https://github.com/mozilla/fxa-content-server/issues/5254

**Comment by ryanfeeley** [comment]
@shane-tomlinson I discussed this in depth with some visiting UXers. they disagree with me, and suggest we instead use the off state.

This is actually a simple fix I can do myself.

Essentially we replace the a:active with a:hover:active. That gets use the effect for both active and active but dragged off.

Would you prefer I make a PR?

**Comment by shane-tomlinson** [comment]
> Would you prefer I make a PR?

@ryanfeeley - I'm never going to say no to a PR from you!

**Comment by anweshknayak** [comment]
Hey can I take this up ?

**Comment by ryanfeeley** [comment]
@anweshknayak Sure! Follow the bootstrap model. Basically press down + dragging off the button should have the same effect as hover. Just slightly darker than not on. Might be tricky to get universally, but worth a shot!

**Comment by hritvi** [comment]
Hey @vladikoff @ryanfeeley! Can I take this issue?

**Comment by DGRamya** [comment]
@vladikoff , I can see that PR is not accepted for this issue, Can I work on this?

**Comment by vladikoff** [comment]
@DGRamya the PR is still pending, sorry. It lives here https://github.com/mozilla/fxa-content-server/pull/5999
