### ISSUE TITLE
Expand Connect Another Device to all sync Desktop sign-ins

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5262]
**Currently, in several situations, Sync users aren't seeing our great connect another device experience when they've verified a new account or confirm a sign-in.**

Here is the feature doc that @ryanfeeley , @shane-tomlinson and @davismtl worked on for this:
https://docs.google.com/document/d/1I2lspQj1x7AMIahM7PgcphnMSfLX-pJC_teru4HYaBs/edit#heading=h.q9y5y6jxb0qy

Here is the feature card for this work:
https://projects-beta.growthhackers.com/cards/add-connect-another-device-to-signin/ghpyETxuFuK63zGPZsC4kw

## Current
<img alt="" src="https://user-images.githubusercontent.com/68213/28432994-21f65ac0-6d58-11e7-97ae-84aef836d883.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28433030-44c2acb6-6d58-11e7-9dc1-3bd3b5a387d5.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28433029-44c1f726-6d58-11e7-9e25-58270b0bbded.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28433494-d66d48a0-6d59-11e7-8730-9c0677f9a12c.png" width="160">

With a small addition of copy, we can roll out our Connect Another Device campaign to all, this campaign is safe to roll out to all remaining Sync authentications.

## Proposed
<img alt="" src="https://user-images.githubusercontent.com/68213/28432931-e3ab9e4c-6d57-11e7-9225-b5a97d46bdd0.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28432932-e3b187d0-6d57-11e7-83c1-68bb789502e8.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28432933-e3b4d1c4-6d57-11e7-870e-831863375d4c.png" width="160"> <img alt="" src="https://user-images.githubusercontent.com/68213/28432934-e3b7b29a-6d57-11e7-8b69-9adbe5afbd71.png" width="160">

**Comment by shane-tomlinson** [comment]
@ryanfeeley - this is a full feature card waiting to happen.

**Comment by davismtl** [comment]
Already done yesterday for the product meeting:
https://projects-beta.growthhackers.com/cards/add-connect-another-device-to-signin/ghpyETxuFuK63zGPZsC4kw

**Comment by davismtl** [comment]
Also this one:
 https://projects-beta.growthhackers.com/cards/add-connect-another-device-to-signin/ghpyETxuFuK63zGPZsC4kw

**Comment by rfk** [comment]
@davismtl the two links above appear to be the same, is that accurate?

We need to do more definition work before this is ready for engineering, and perhaps we can do that asynchronously in this bug.  Let me start with a scoping question for @davismtl and @ryanfeeley.  IIUC the proposal here is that we should show the CAD screen after every new connection to sync, either on the "account verified" screen or the "signin confirmed" screen.  Are there cases where do we *not* want to show the CAD screen?

**Comment by rfk** [comment]
By contrast, the linked "feature card" says to only show it when they have a single device connected, not if they're already in a multi-device setup.

**Comment by davismtl** [comment]
> We need to do more definition work before this is ready for engineering
Agreed 

> Are there cases where do we not want to show the CAD screen?
Excellent question!

> By contrast, the linked "feature card" says to only show it when they have a single device connected, not if they're already in a multi-device setup.
I even see flaws with that approach.

I'll try to get a feature doc started this week.

**Comment by davismtl** [comment]
small update (before I close this lingering tab):

rfeeley and I met last Friday to discuss this. The user login flows are numerous and full of exceptions that are really complicated so we're trying figure out how to make sure we come up with a solution to get users to connect another device at login that avoids TONS of logic.

We have identified that promoting features that require multiple devices might be a subtle way to nudge existing users to setup a second device. It would also result in much less logic in our flows.

That being said, stay tuned for more details as we explore this idea more.

**Comment by davismtl** [comment]
Here is the feature doc that @ryanfeeley , @shane-tomlinson and I worked on for this:
https://docs.google.com/document/d/1I2lspQj1x7AMIahM7PgcphnMSfLX-pJC_teru4HYaBs/edit#heading=h.q9y5y6jxb0qy

**Comment by davismtl** [comment]
@shane-tomlinson @rfk 
Should this be part of train-95 now that we have a define feature doc?
It has some overlap with mozilla/fxa-content-server/issues/5197 as defined by the feature card.

**Comment by shane-tomlinson** [comment]
> Should this be part of train-95 now that we have a define feature doc?

TBH, I want to take a break from CAD for a week to give my head a break and tie off other loose ends.

**Comment by shane-tomlinson** [comment]
> TBH, I want to take a break from CAD for a week to give my head a break and tie off other loose ends.

My head was cloudy this morning, I thought we were cutting the train next week. I'll start on this next week and see where we get, hopefully we can get at least part of it done for train-95.

**Comment by rfk** [comment]
I'm going to put "train-95" on this to remind us to consider it when closing out the train.
