### ISSUE TITLE
addresses and creditcard engines are disabled by default

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-content-server#5269]
With a new nightly that does the "new engine" handshake, you are correctly presented with new "addresses" and "creditcards" engines - however, they are disabled by default. I believe UX wants everything enabled by default.

**Comment by mhammond** [comment]
(actually, full disclosure - I only enabled "addresses", not "creditcards", as the latter is at risk for 56 - but it appears they are probably the same)

**Comment by shane-tomlinson** [comment]
>  I believe UX wants everything enabled by default.

Oh. I totally misread [this requirement](https://github.com/mozilla/fxa-content-server/issues/5087):

> We want these engines to be disabled by default for existing Sync users, but checked by default in "choose what to sync". This means that the engines will default to disabled in Firefox (whereas every other engine defaults to enabled), which will complicate our "declined" handling.

I ignored/didn't see/saw and forgot the part of `checked by default in "choose what to sync"` and interpreted the whole thing as "disabled by default"

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Did we discuss this? Did I uncheck those by default based on something you told me? I have a PR that fixes this on train-91, just want confirmation the fix is "Doing the right thing".
