### ISSUE TITLE
"Receive the monthly Firefox newsletter" looks too large on new firstrun page.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5271]
STR

1. In Fx 54, create and open a new profile.
2. Look at the "Receive the monthly Firefox newsletter" text, it's too big compared to its surroundings.

<img width="457" alt="screen shot 2017-07-24 at 12 06 36" src="https://user-images.githubusercontent.com/848085/28520798-de9f358a-7068-11e7-9f8b-448c7799d571.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson Agreed! Make the font size the same as the legal copy at this width?
