### ISSUE TITLE
Update Confirm view to handle when verification is using Push

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-content-server#5279]
The auth-server will determine whether to send a message via email or push, as defined in https://github.com/mozilla/fxa-auth-server/issues/1978. It will respond with a `verificationMethod` of... something that isn't `email`, which should be determine in this work. Easiest suggest is `verificationMethod: "push"`, but perhaps a more generic term is desired for if we add other methods?

The confirm view needs to be updated to display appropriate text depending on if the user should look in their email or at another device. Clicking a resend button probably should still just send the message as an email.

@ryanfeeley I recall you had a new graphic for this page, some animating thingy. Also, strings would be needed.

**Comment by vladikoff** [comment]
@seanmonstar could you triage this? Do you need graphics / mocks from @ryanfeeley ?

**Comment by ryanfeeley** [comment]
@seanmonstar @vladikoff Something different than in the feature doc? https://docs.google.com/document/d/16fdARc6MC9XO7FBG9YJ4bpeqhHcv1G3ua0uzeS4EckY/edit#

**Comment by vladikoff** [comment]
🗡 closing this for now
