### ISSUE TITLE
SMS did not show during Sync Fest

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5285]
STR:

1) Create new account
2) Get account verification link from email and append `forceExperimentGroup=treatment&signinCodes=true`
3) Open updated verification link in same browser different tab.

Expected:
Taken to SMS screen.

Actual:
Taken to account verified screen.

I was under the impression that SMS was enabled for Canada and US? I have not been able to reproduce this locally but saw it during sync fest.

**Comment by vladikoff** [comment]
@vbudhram wasn't it SMS that didn't show up, not CAD?

**Comment by vbudhram** [comment]
Woops you are right, updating.

**Comment by shane-tomlinson** [comment]
@vbudhram - which browser version?

**Comment by shane-tomlinson** [comment]
This can happen on Firefox 54 if E10s is enabled.

**Comment by vbudhram** [comment]
@shane-tomlinson I believe @ryanfeeley was using Nightly.

**Comment by shane-tomlinson** [comment]
The strange part about this is on signup, desktop users should never see "account verified". If they don't see SMS, they should be taken to CAD. This sounds suspiciously like a user that is signing in that had to go through signin confirmation.

**Comment by vladikoff** [comment]
>   <@stomlinson>	vladikoff: sms is only set to 50% of people in eligible countries.

**Comment by shane-tomlinson** [comment]
Re-opening, I just had this problem on Nightly.

STR

1. Sign up for a new FxA account for Sync.
2. In the same browser, different tab, open the verification link with `&forceExperimentGroup=treatment`
3. I'm sent to CAD?

**Comment by vladikoff** [comment]
Yay!
