### ISSUE TITLE
addresses engine always offered for Firefox 56+

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-content-server#5292]
I know we agreed to this way back when, but it seems a little risky and may be worth addressing: the "addresses" engine is always offered to Firefox 56 even when that preference is pref'd off in desktop itself. There's a small risk addresses will not be enabled for 56 and if it is not, it's probably bad to offer the engine.

I understand there's a bit of a risk in making this change on the server, but I'm not quite sure how to balance that against the risk of addresses not making 56 - IIUC, the only thing we are waiting on is QA signoff, and I *think* it will be fine, but I'm getting this on file anyway.

**Comment by rfk** [comment]
Mark clarified in IRC that *if* addresses ships in 56 then it will advertise that fact in the device capability handshake, so IIUC the ask here is to remove the hardcoded "show addresses engines to Firefox 56+" and let it fall back to the more general "show addresses engines if it's advertised in the capabilities handshake".

I've no idea how big a change that is for us on the FxA side tho...

**Comment by shane-tomlinson** [comment]
> I've no idea how big a change that is for us on the FxA side tho...

Not much. We assumed this would happen someday. PR incoming.

**Comment by rfk** [comment]
@mhammond would you like this in production before 56 goes to beta?

**Comment by mhammond** [comment]
> would you like this in production before 56 goes to beta?

I guess that would be ideal, but a few days after wouldn't hurt

**Comment by mhammond** [comment]
FTR, it appears this engine is only going to be enabled on 56 for en-US users where geoip says the user actually *is* in the US - and at this stage, the preference is only flipped to true by default on Nightly - so after the merge, it will *not* be available by default on 56. All of which means we are certainly doing the right thing by getting it out ASAP - so thanks for jumping on this!
