### ISSUE TITLE
Improve email settings responsive layout

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5297]
STEPS TO REPRODUCE
1. Open Secondary Email section when "Make primary" is available and adjust window width

EXPECTED RESULTS
1. Secondary email is truncated with ellipsis when buttons approach
1. When wrapping, the leftmost button is left-aligned with the email and buttons below

ACTUAL RESULTS
![responsive](https://user-images.githubusercontent.com/68213/28672756-a09cc674-72ae-11e7-8a42-4d482cd647b9.gif)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can you update the title to talk about responsive design or mobile browsers? I read this to mean performance related responsiveness.
