### ISSUE TITLE
flakey functional test on travis - mailcheck - tooltip works

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5309]
I've seen this a lot lately, here's one example:

https://travis-ci.org/mozilla/fxa-content-server/builds/259314046#L5006

**Comment by vladikoff** [comment]
It was fine for months, but not anymore :(

Seems like the Travis distro upgrade is to blame

**Comment by shane-tomlinson** [comment]
> NoSuchElement: [POST http://localhost:4444/wd/hub/session/deba6942-9dc9-408f-8343-ad175e66ff66/element / {"using":"css selector","value":".tooltip-suggest > span:nth-child(1)"}] Unable to locate element: .tooltip-suggest > span:nth-child(1)
>
> For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
>
> Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
> 
> System info: host: 'testing-gce-414267d0-f3d5-4dbd-af1d-68d0ba464f2c', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_131'
>
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> 
> Capabilities [{moz:profile=/tmp/rust_mozprofile.k8mpEWHIAVMP, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=4.4.0-83-generic, moz:processID=8426.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
> 
> Session ID: 22d7d905-ffa2-4e6d-b372-4c0880f18bb6
> 
> *** Element info: {Using=css selector, value=.tooltip-suggest > span:nth-child(1)}
>   at runRequest  <node_modules/leadfoot/Session.js:92:40>
>   at <node_modules/leadfoot/Session.js:113:39>
>   at new Promise  <node_modules/dojo/Promise.ts:411:3>
>   at ProxiedSession._post  <node_modules/leadfoot/Session.js:67:10>
>   at ProxiedSession.find  <node_modules/leadfoot/Session.js:1304:15>
>   at Command.<anonymous>  <node_modules/leadfoot/Command.js:42:36>
>   at <node_modules/dojo/Promise.ts:393:15>
>   at run  <node_modules/dojo/Promise.ts:237:7>
>   at <node_modules/dojo/nextTick.ts:44:3>
>   at _combinedTickCallback  <internal/process/next_tick.js:73:7>
>   at process._tickCallback  <internal/process/next_tick.js:104:9>
>   at Command.find  <node_modules/leadfoot/Command.js:23:10>
>   at Command.prototype.(anonymous function) [as findByCssSelector]  <node_modules/leadfoot/lib/strategies.js:29:16>
>   at Command.<anonymous>  <tests/functional/lib/helpers.js:179:8>
>   at Command.<anonymous>  <tests/functional/lib/helpers.js:55:25>
>   at runCallback  <node_modules/leadfoot/Command.js:526:31>
>   at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
>   at <node_modules/dojo/Promise.ts:393:15>
>   at run  <node_modules/dojo/Promise.ts:237:7>
>   at <node_modules/dojo/nextTick.ts:44:3>
>   at _combinedTickCallback  <internal/process/next_tick.js:73:7>
>   at process._tickCallback  <internal/process/next_tick.js:104:9>
>   at Command.then  <node_modules/leadfoot/Command.js:542:10>
>   at Test.tooltip works [as test]  <tests/functional/mailcheck.js:37:10>
>   at <node_modules/intern/lib/Test.js:191:24>
>   at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
>   at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
>   at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
>   at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
>   at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
>   at _combinedTickCallback  <internal/process/next_tick.js:73:7>
>   at process._tickCallback  <internal/process/next_tick.js:104:9>
> No unit test coverage for firefox on any platform
> firefox on any platform: 1/92 tests failed

**Comment by shane-tomlinson** [comment]
Re-opening... Just saw 3 failures in a row.

**Comment by vladikoff** [comment]
@shane-tomlinson I have not seen this happen. I Thinking the 3 in a row failures could have been with a PR that was not rebased? Please reopen if not true

**Comment by shane-tomlinson** [comment]
Here's an example from yesterday: https://travis-ci.org/mozilla/fxa-content-server/builds/269669704?utm_source=github_status&utm_medium=notification

**Comment by vladikoff** [comment]
aw :(
