### ISSUE TITLE
signup bounce not triggered from about:accounts

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5311]
STR

1. from about:preferences#sync, click "sign up"
2. Sign up for a new account.
3. While at the /confirm screen, restart the in-memory DB.
4. Where's the bounce notification?

This happens because signup/signin polling does not occur within about:accounts.

ref #5037

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/5197 - getting rid of about:accounts might make this bug a bit simpler.

**Comment by shane-tomlinson** [comment]
Moving this to blocked because the content server fix doesn't fully fix the problem. This will require a browser fix.

The problem is if about:accounts is open when an email bounce is detected, the content server redirects to /signin or /signup, displays an error message, and then the browser comes in, detects the session has gone bad, and reload about:accounts?action=signin

**Comment by rfk** [comment]
Some scoping questions, in the hope of figuring out how to get this unblocked.

> This will require a browser fix.

What's the right behaviour for the browser in this case - just leave the page active in about:accounts so we can show our own messaging.

> the browser comes in, detects the session has gone bad

Does it detect this because it's doing it's own polling, in addition to the polling that content-server is doing?

> getting rid of about:accounts might make this bug a bit simpler.

FWIW I mentioned this in the sync standup last week, and while there was no outright rejection of the idea of just killing about:accounts, there was also no real enthusiasm either.

**Comment by shane-tomlinson** [comment]
> What's the right behaviour for the browser in this case - just leave the page active in about:accounts so we can show our own messaging.

Yes.

> Does it detect this because it's doing it's own polling, in addition to the polling that content-server is doing?

Yes.

> FWIW I mentioned this in the sync standup last week, and while there was no outright rejection of the idea of just killing about:accounts, there was also no real enthusiasm either.

There was enthusiasm for removing it ~ 6 months to a year ago. Something change to dampen the enthusiasm?

**Comment by vladikoff** [comment]
@rfk to unblock this somehow

**Comment by shane-tomlinson** [comment]
We have a plan. Outlined in https://bugzilla.mozilla.org/show_bug.cgi?id=1393393. Starting with Fx 57, Firefox is no longer going to redirect to about:preferences#sync, instead it'll rely on the content-server to handle the screen transition. To do the screen transition, we'll have to poll for the verification status, and in doing so, we'll handle signup bounces.

Moving to next. Assigning to me.
