### ISSUE TITLE
Replace the Connect Another Device icon with this SVG

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5319]
![image](https://user-images.githubusercontent.com/68213/29574028-632e3fb8-872e-11e7-99ab-5b6b38e33295.png)

Two hearts that beat as one.
Soon to be animated (fingers crossed).
[comp.svg.zip](https://github.com/mozilla/fxa-content-server/files/1190826/comp.svg.zip)

**Comment by ryanfeeley** [comment]
@davismtl I would love to see if this illustration has a positive impact. Good candidate for A/B test?

**Comment by davismtl** [comment]
2 things before we do this:
- Let's finish our existing CAD work (signin)
- Create a small feature doc with hypothesis, test plan and success metrics for this proposed A/B test
