### ISSUE TITLE
`null has no properties` being reported in Sentry

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5323]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/632666/events/11503181/

I haven't tested this, but I believe the STRs are:

1. From the firstrun page, sign up to FxA for Sync.
2. Click through CWTS. 
3. On the `Verify your email` screen, click the browser's `back` button.
4. Verify the email.

There are two problems:

1. https://github.com/mozilla/fxa-content-server/blob/f9f7f10d4310163ffc256d1536322d470dcfe646/app/scripts/views/mixins/experiment-mixin.js#L61 doesn't check whether `experiments` can be dereferenced.
2. https://github.com/mozilla/fxa-content-server/blob/f9f7f10d4310163ffc256d1536322d470dcfe646/app/scripts/views/confirm.js#L111 starts a confirmation poll, but we never stop the poll when the view is destroyed.

Breaking the above into two separate issues.

**Comment by vladikoff** [comment]
> I haven't tested this, but I believe the STRs are:

@shane-tomlinson confirmed:

<img src=http://v14d.com/i/5981e8d009887.png />
