### ISSUE TITLE
Refreshing the signin-bounced screen loses context

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5334]
From https://github.com/mozilla/fxa-content-server/pull/5318#issuecomment-319789992. @shane-tomlinson pointed out that when you refresh on the signin-bounced screen, context is lost so the email address is not displayed.

To fix it, some kind of fallback behaviour should be implemented in `views/sign_in_bounced::beforeRender`, which checks `this.model.has('email')` and redirects when `false`. My preference would be to redirect to sign-in, so that if the user hasn't properly understood the bounced screen they can just try to sign in again and get a second bite of the cherry. The other option would be to redirect to sign-up.

@ryanfeeley and @davismtl, any suggestions?

**Comment by ryanfeeley** [comment]
Had to Google "second bite of the cherry" but that sounds ideal if we can't maintain context after page refresh. Take them to sign-in so they can see it again.

Out out curiosity, this feature harmonizes well with sign-in unblock too?

**Comment by shane-tomlinson** [comment]
> Out out curiosity, this feature harmonizes well with sign-in unblock too?

Signin unblock doesn't do any polling; we'd have to add it to find out whether the email bounced.

**Comment by ryanfeeley** [comment]
@shane-tomlinson A smell a new bug? Shall I file?
