### ISSUE TITLE
Change "Working" from red to blue

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5354]
Right now "Working..." is displayed after 10 seconds... We discussed that maybe this is a bit too quick...

@ryanfeeley - thoughts?

**Comment by shane-tomlinson** [comment]
@ryanfeeley says we might actually be *too slow* to display this issue.

@philbooth says "red makes it seem worse than it is" 

Should it be blue?

Ref #5344

**Comment by ryanfeeley** [comment]
@shane-tomlinson Blue is a great idea.

According to our performance guidelines, after around 2000ms (but up to 5000) we should consider showing "Working…". Beyond 7000ms we should give more feedback (like progress, or at least more detail).

What do you think?

**Comment by shane-tomlinson** [comment]
>  Beyond 7000ms we should give more feedback (like progress, or at least more detail).

We don't really have any info related to progress or more details to give. It's just taking a while.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Can we build it in?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Can we build it in?

There's nothing really to progress, other than image uploads everything we do is a simple send a tiny blob of data or fetch a tiny blob of data.

**Comment by ryanfeeley** [comment]
![image](https://user-images.githubusercontent.com/68213/32965540-bdafe2a6-cba4-11e7-9ad0-e55e46bf2ff6.png)

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/37411009-29c4d530-2778-11e8-9022-43043a14502d.png)

**Comment by vladikoff** [comment]
@MynahMarie this bug is a good one to get started. Follow the get started here: https://github.com/mozilla/fxa-content-server#quick-start

Then try to change the colour of the working message to blue. To see the `Working...` message you need to set a breakpoint like this: 

![image](https://user-images.githubusercontent.com/128755/37411421-24338a20-2779-11e8-87b5-a42b95d42c01.png)

**Comment by MynahMarie** [comment]
@vladikoff Ok thank you! working on it now :)

**Comment by DGRamya** [comment]
@vladikoff ,  I do not see any successful PR for this issue, Can I work on this?

**Comment by vladikoff** [comment]
@DGRamya please try! early PR here: https://github.com/MynahMarie/fxa-content-server/commit/00bdb0acd1488d2d0fe7050308d2f62c5a40e3a6
