### ISSUE TITLE
Reduce the # of tests run on circle

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5355]
Circle runs sometimes take a long long time. We run a lot of tests, many tests are for browser integrations that are no longer used all that often.

The suggestion is to remove the suites that are no longer "current" (fx_desktop_v1, fx_desktop_v2, firstrun_v1) from the list of suites run on Circle, but still run these on teamcity.

cc @jrgm, @vladikoff, @philbooth, @vbudhram - thoughts?

**Comment by vladikoff** [comment]
👍
