### ISSUE TITLE
Corner radius on password show button wrong

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5361]
Our show password button has the wrong corner radius that is overlapping the field. It should match the underlying field.
![corner-radius](https://user-images.githubusercontent.com/68213/29284867-68d9eeb0-80fa-11e7-9fb5-da87097fb886.gif)

**Comment by vladikoff** [comment]
Duplicate of https://github.com/mozilla/fxa-content-server/issues/5233

**Comment by shane-tomlinson** [comment]
> ![corner-radius](https://user-images.githubusercontent.com/68213/29284867-68d9eeb0-80fa-11e7-9fb5-da87097fb886.gif)

This image makes me feel like it's 1996 all over again. Long Live `<blink>`
