### ISSUE TITLE
[Sentry] WebChannel error: TypeError: aWindow is null

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5363]
See this even for more info: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/627725/events/11669100/

Stack:

```
pbu_privacyContextFromWindow@resource://gre/modules/PrivateBrowsingUtils.jsm:49:5
isBrowserPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:45:12
isPrivateBrowsingMode@resource://gre/modules/FxAccountsWebChannel.jsm:354:31
shouldAllowFxaStatus@resource://gre/modules/FxAccountsWebChannel.jsm:379:13
getFxaStatus@resource://gre/modules/FxAccountsWebChannel.jsm:390:9
async*_receiveMessage@resource://gre/modules/FxAccountsWebChannel.jsm:188:9
listener@resource://gre/modules/FxAccountsWebChannel.jsm:248:11
deliver@resource://gre/modules/WebChannel.jsm:324:9
_listener@resource://gre/modules/WebChannel.jsm:97:13
```

**Comment by rfk** [comment]
Possible edge-case in the browser handshake code?  /cc @shane-tomlinson.

**Comment by shane-tomlinson** [comment]
!@#!@%$. [This originally checked whether sendingContext.browser](https://dxr.mozilla.org/mozilla-central/rev/63ca686c3f1e870649b6d9c559973d100573aec2/services/fxaccounts/FxAccountsWebChannel.jsm#349) existed and it was suggested to remove the check.

**Comment by shane-tomlinson** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1393393

**Comment by shane-tomlinson** [comment]
Patch opened.

**Comment by shane-tomlinson** [comment]
In 1393393, @mhammond and I decided to WONTFIX this for now. The theory is this occurs for users that open FxA and immediately close the window immediately. Closing, we can re-open if the metrics alter significantly or we realize there is an actual problem.
