### ISSUE TITLE
Working… (999) error when disconnecting an Android device

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5365]
This appeared during Sync Fest yesterday. Not sure it can be replicated, but the 999 error appeared when we attempted to disconnect an Android device.
![img_20170815_113026](https://user-images.githubusercontent.com/68213/29369721-6f1e4244-8271-11e7-907e-0c8521ac5b96.jpg)

**Comment by rfk** [comment]
Thanks @ryanfeeley.  If you do happen to catch one of these in the wild again, it would be great if you can also screenshot the contents of the "console" and "network" tabs from the developer tools panel.  These can often help diagnose exactly which request is getting the timeout an maybe even why.

Did the "working..." stay indefinitely, or eventually go away?

**Comment by vladikoff** [comment]
No reports of this anywhere for a while, let's reopen if we see it again
