### ISSUE TITLE
configuration.js should standardize on snake_case or camelCase, not both.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5369]
The mixture of camelCase and snake_case in https://github.com/mozilla/fxa-content-server/blob/1acf7aeb09a2c5f46f8dc5b2ce2601042c8021e3/server/lib/configuration.js#L63:L67 is more than annoying, it causes confusion, and confusion makes it easier to make mistakes.

Let's decide.

**Comment by vladikoff** [comment]
from mtg: 

# Just use camelCase for new properties
