### ISSUE TITLE
CAD phases 2/3 metrics aren't comparing apples to apples

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5379]
@philbooth brought this up yesterday after looking at https://sql.telemetry.mozilla.org/dashboard/connect-another-device-phase-2.

With CAD phase 3, we use the signinCode to to fetch a `continued_from` field from the DB. `continued_from` is the flow_id of the signin on the desktop device, it ties together the logins on the mobile and desktop devices. We use this to determine the exact the # of users that complete the signin flow on their mobile device as a result of sending an SMS. CAD phase 2, as it currently stands, has no such mechanism to tie together the two logins. We had to assume that if a user signed up on desktop, sent themselves an SMS, and then signed in on a mobile device, the signin on their mobile device was a result of sending themselves an SMS.

Turns out, the CAD phase 2 method of counting includes far more people than the CAD phase 3 method. Suspiciously more.

I propose we work around this by changing where we make the [choice which experiment group the user is a member of](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/views/mixins/connect-another-device-mixin.js#L77). Instead of sending a signinCode IFF the user is a member of the `signinCodes` group, *always* send it if the user is a member of either `signinCodes` or `treatment`. This will ensure `continued_from` is always available for the metrics. When [the signinCode is consumed](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/models/auth_brokers/base.js#L172), call the [send-sms-install-link.js->choose](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js#L26) function again to determine the group, possibly doing some tomfoolery to ensure that only `treatment` or `signinCodes` is returned.

cc @philbooth.

**Comment by philbooth** [comment]
> I propose we work around this by changing where we make the [choice which experiment group the user is a member of](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/views/mixins/connect-another-device-mixin.js#L77). Instead of sending a signinCode IFF the user is a member of the `signinCodes` group, *always* send it if the user is a member of either `signinCodes` or `treatment`. This will ensure `continued_from` is always available for the metrics. When [the signinCode is consumed](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/models/auth_brokers/base.js#L172), call the [send-sms-install-link.js->choose](https://github.com/mozilla/fxa-content-server/blob/e8a9af8a3cb1f020a2bd54cb82eab2624f5ed918/app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js#L26) function again to determine the group, possibly doing some tomfoolery to ensure that only `treatment` or `signinCodes` is returned.

Hrm, could do this although it seems like a load faffing about for something which isn't that big of a deal? I reckon we can mitigate most of the noise in the query itself, just by ignoring non-iOS/Android operating systems. Maybe wait and see how I get on with that (this week at some point) before making a decision?
