### ISSUE TITLE
# of users going through the SMS flow seems suspiciously low

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5382]
First noticed by @philbooth when comparing [CAD phases 1-3 metrics](https://github.com/mozilla/fxa-content-server/issues/5379) and then corroborated by @ryanfeeley with his DataDog graphs. It seems nearly an order of magnitude more users are going through the CAD phase 1 flow *when they verify in the same browser* than the SMS flow. This is suspicious because [2/3 of users who verify in the same browser](https://github.com/mozilla/fxa-content-server/pull/5332) are supposed to be sent to /sms, at least if they are in a supported country. We believe bulk of our new users are in North America, so this discrepancy is confusing.

Possible problems:

1. Our assumption about where new users are located is incorrect.
2. [The logic used to determine which bucket a user is in is incorrect](https://github.com/mozilla/fxa-content-server/issues/5378).
3. The logic to determine whether a [user is eligible to send an SMS is incorrect](https://github.com/mozilla/fxa-content-server/blob/d22f4cde9c8c9b54938e8f956b00ded1caf77a24/app/scripts/views/mixins/connect-another-device-mixin.js#L97).

We know the second is a problem. The issue with attributing the discrepancy to that alone is that the issue manifested by sending *all* users to the same bucket. We wouldn't expect *any* users to be sent to CAD or SMS.

Unfortunately, we are not logging on either the front or back ends why a user is ineligible for SMS. 

Maybe a good starting place is for the frontend to log something like:

* "sms.ineligible.no_session" 
* "sms.ineligible.android"
* "sms.ineligible.ios"
* "sms.inelibible.another_accont_signed_in"
* "sms.ineligible.not_chosen_for_experiment"
* "sms.ineligible.server_says_no"

cc @philbooth

**Comment by shane-tomlinson** [comment]
Re-opening, my PR erroneously said it fixed this problem. All that PR does is log why the user is ineligible. We can close this when we determine why and if there are any next steps.

**Comment by shane-tomlinson** [comment]
Moving to blocked until metrics start to come in.

**Comment by vladikoff** [comment]
from mtg: blocked on metrics

**Comment by shane-tomlinson** [comment]
Some metrics:

<img width="982" alt="screen shot 2017-09-18 at 21 17 07" src="https://user-images.githubusercontent.com/848085/30562562-65beed0a-9cae-11e7-846a-dd876d0ef1d6.png">

Users are being blocked for two primary reasons:

1. they verify in a country we do not support
2. they verify in Android

Closing, now to decide on next steps.
