### ISSUE TITLE
Create a new view for Sign in confirmation using push notification.

### ISSUE THREAD

**Issue by vershwal** [mozilla/fxa-content-server#5383]
As the user clicks on the push-notification for sign-in confirmation, the confirmation view appears. Something like this : 
![screenshot from 2017-08-23 17-57-22](https://user-images.githubusercontent.com/17474532/29615386-66652996-882b-11e7-8f8a-b3e4e220aa90.png)

Next, we need to figure out how to generate the URL that will redirect to this page and will be sent with the push notification.
cc @seanmonstar

**Comment by shane-tomlinson** [comment]
@seanmonstar, @vershwal - is this already in progress? Can you triage as you see fit?

**Comment by vershwal** [comment]
Hey @shane-tomlinson, Sorry I missed your comment. I am just working on this. I'll file a PR soon

**Comment by vladikoff** [comment]
Latest Pull request for this is here: https://github.com/mozilla/fxa-content-server/pull/5389

**Comment by vladikoff** [comment]
Closing this for now
