### ISSUE TITLE
Confirm email button not showing up in emails

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5387]
According to Guigs, over the weekend, 4 users filed sumo tickets saying that they could not see the button in our email confirmations.

Here is one of of those: 
https://support.mozilla.org/en-US/questions/1172737#answer-1000190

**Comment by rfk** [comment]
I fired off an email-on-acid test to see if we've introduced any new rendering issues, but the results all look OK to me:

  https://www.emailonacid.com/app/acidtest/display/summary/2jI6fVxd16utFcWtb5UigC4zdMV1IeEr227VfgI8NrGmD

To have a hope of reproducing this we'll need to now how the affected users are checking their email, e.g.:

* What mail provider do they use?
* What program are they using to check their email?
* If they're checking via the web, what web browser and version are they using?

**Comment by davismtl** [comment]
I have asked the above questions to Rachel. Meanwhile I got some additional insights from Rachel. These different email problems seem to be unrelated to one another. The above stated problem seems to have occurred but the others are different in nature. The others are comprised of:

- 2 users no longer having access to their email to login (nothing to do here)
- Another person was confusing the sumo verification email with the FxA verification email
- Another tried to add a secondary email but got an "unexpected error".

None of these seem actionable yet. I'll wait to hear back from her to see if we should close this issue.

**Comment by shane-tomlinson** [comment]
Blocked on info from Rachel.

**Comment by vladikoff** [comment]
No follow at this time
