### ISSUE TITLE
Signup Success Rate Dropped on FirstRun

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5388]
To my knowledge nothing has changed to the onboarding flow.

Meanwhile, registration rate has dropped A LOT.
https://sql.telemetry.mozilla.org/queries/2412?p_start_date=2017-02-01#4457

Did we brake anything?

**Comment by rfk** [comment]
The drop occurs on August 16, which is indeed pretty much spot on the release of train-93.  Do we see changes in other metrics in a similar timeframe?

**Comment by rfk** [comment]
The "volume" and "verification %" graphs at the above link do not show the same drop, so I wonder if this is specifically something going wrong with the flow-completion event.

**Comment by rfk** [comment]
I made a more detailed signup funnel graph for first-run, and I think the best view of it is this:

  https://sql.telemetry.mozilla.org/queries/26259/source#68950

Screenshotted here:

<img width="891" alt="capture" src="https://user-images.githubusercontent.com/34695/29803440-3e8cebaa-8cbf-11e7-8613-4c5afafcf1ee.PNG">

That's the signup funnel on the first-run page, using raw event volume, from "engage" through to "complete".  You can see there was a big drop in the number of users engaging with the form in late June, and for some reason the number of users engaging has increased dramatically with train-93.

What's interesting is that it doesn't correspond to an increase in *view* of the signup page:

  https://sql.telemetry.mozilla.org/queries/26259/source#68875

So we've either done something to make users more likely to click into the form, or we've changed the circumstances under which the "signup.view.engage" event is triggered.

We launched two experiments with train-93, "confirm password" and "non-disabled button".  Could either of those have caused this spike in engage events?

**Comment by rfk** [comment]
> So we've either done something to make users more likely to click into the form,
> or we've changed the circumstances under which the "signup.view.engage" event is triggered.

I think it's the later.  I added the "count_view" line to the above sign-up funnel, and check this out:

<img width="1359" alt="capture" src="https://user-images.githubusercontent.com/34695/29803585-56db89ae-8cc0-11e7-8864-442755644b41.PNG">

As of FxA train-93, it seems that almost everyone who views the signup form triggers an "engage" event.  Are we e.g. auto-focussing into the form or something new like that?

**Comment by shane-tomlinson** [comment]
> Are we e.g. auto-focussing into the form or something new like that?

We've always autofocused, even in the firstrun page.

**Comment by davismtl** [comment]
Per this morning's meeting, 
- registrations haven't dropped so we think it is related to engage. As I result, I plotted the following that seems to confirm it: https://sql.telemetry.mozilla.org/queries/2412/source?p_start_date=2017-02-01#69851
- It also seems to mostly impact firstrun: https://sql.telemetry.mozilla.org/queries/1975#3534

**Comment by shane-tomlinson** [comment]
There are two problems:

1. If any of the view's input elements have a value prefilled from the form-prefill model, an `engaged` event will [be logged as a result of the `input` event being fired on the element](https://github.com/mozilla/fxa-content-server/blob/7f2abc6837dc46c04611d58e6ca21b113a6c6c4d/app/scripts/views/mixins/form-prefill-mixin.js#L41).
2. The [check for whether an element should be prefilled will respond with `true`](https://github.com/mozilla/fxa-content-server/blob/7f2abc6837dc46c04611d58e6ca21b113a6c6c4d/app/scripts/views/mixins/form-prefill-mixin.js#L28) even if the formPrefill model contains an empty string for that field. Users that go from the signin to signup page w/o entering anything on the signin page will have [an empty string saved for both the email and password fields](https://github.com/mozilla/fxa-content-server/blob/7f2abc6837dc46c04611d58e6ca21b113a6c6c4d/app/scripts/views/mixins/form-prefill-mixin.js#L51).
