### ISSUE TITLE
Failing functional test on teamcity: Firstrun Sync v2 email first email specified by relier, not registered

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5390]
https://tc-test.dev.lcip.org/viewLog.html?buildId=15182&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

> NoSuchElement: [POST http://localhost:4444/wd/hub/session/ad3044ed-e787-4fd7-b8f4-ecc7b56bed55/element / {"using":"css selector","value":"#fxa-signup-password-header"}] Unable to locate element: #fxa-signup-password-header For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.4.0', revision: 'unknown', time: 'unknown' System info: host: '54bb1476a3ba', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_112' Driver info: org.openqa.selenium.firefox.FirefoxDriver Capabilities [{moz:profile=/home/teamcity/agent/temp/buildTmp/rust_mozprofile.OE7WES53TEZE, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.3, platformVersion=4.4.41-36.55.amzn1.x86_64, moz:processID=27054.0, browserName=firefox, javascriptEnabled=true, platformName=linux}] Session ID: 97fee7da-d564-49c5-ab9d-2fc1151af33d *** Element info: {Using=css selector, value=#fxa-signup-password-header} at runRequest <node_modules/intern/node_modules/leadfoot/Session.js:92:40> at <node_modules/intern/node_modules/leadfoot/Session.js:113:39> at new Promise <node_modules/intern/node_modules/dojo/Promise.ts:411:3> at ProxiedSession._post <node_modules/intern/node_modules/leadfoot/Session.js:67:10> at ProxiedSession.Session.find <node_modules/intern/node_modules/leadfoot/Session.js:1304:15> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:42:36> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at Command.find <node_modules/intern/node_modules/leadfoot/Command.js:23:10> at Command.prototype.(anonymous function) [as findByCssSelector] <node_modules/intern/node_modules/leadfoot/lib/strategies.js:29:16> at Command.<anonymous> <tests/functional/lib/helpers.js:151:8> at Command.<anonymous> <tests/functional/lib/helpers.js:56:25> at runCallback <node_modules/intern/node_modules/leadfoot/Command.js:526:31> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:543:11> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Command.<anonymous> <tests/functional/lib/helpers.js:162:14> at runCallback <node_modules/intern/node_modules/leadfoot/Command.js:526:31> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:543:11> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Command.<anonymous> <tests/functional/lib/helpers.js:159:8> at Command.<anonymous> <tests/functional/lib/helpers.js:56:25> at runCallback <node_modules/intern/node_modules/leadfoot/Command.js:526:31> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:543:11> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Command.<anonymous> <tests/functional/lib/helpers.js:1085:8> at Command.<anonymous> <tests/functional/lib/helpers.js:56:25> at runCallback <node_modules/intern/node_modules/leadfoot/Command.js:526:31> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:543:11> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Command.<anonymous> <tests/functional/lib/helpers.js:1087:8> at Command.<anonymous> <tests/functional/lib/helpers.js:56:25> at runCallback <node_modules/intern/node_modules/leadfoot/Command.js:526:31> at Command.<anonymous> <node_modules/intern/node_modules/leadfoot/Command.js:543:11> at <node_modules/intern/node_modules/dojo/Promise.ts:393:15> at run <node_modules/intern/node_modules/dojo/Promise.ts:237:7> at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13> at Command.then <node_modules/intern/node_modules/leadfoot/Command.js:542:10> at Test.registerSuite.email specified by relier, not registered [as test] <tests/functional/fx_firstrun_v2_email_first.js:153:8> at <node_modules/intern/lib/Test.js:191:24> at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15> at runCallbacks <node_modules/intern/browser_modules/dojo/Promise.ts:11:11> at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4> at run <node_modules/intern/browser_modules/dojo/Promise.ts:237:7> at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3> at nextTickCallbackWith0Args <node.js:436:9> at process._tickCallback <node.js:365:13>

**Comment by vladikoff** [comment]
TeamCity will run!
