### ISSUE TITLE
emailFirst experiment not being reported to DataDog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5397]
Now that train-94 is out the door, I went to look at the emailFirst metrics on DataDog. The experiment metrics aren't being reported! The "email_first" screen metrics are though, so far they look pretty decent!

**Comment by vladikoff** [comment]
@shane-tomlinson so no tags on existing events? I cannot see them either

**Comment by shane-tomlinson** [comment]
Ahha! The problem is [we are creating the experiment without passing the experimentGroup](https://github.com/mozilla/fxa-content-server/blob/fd2f01cb8c4012c1ce2519b512936fa9f518288e/app/scripts/views/mixins/email-first-experiment-mixin.js#L31)!
