### ISSUE TITLE
Ponton app logo is stretched

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5399]
EXPECTED RESULTS:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/68213/29876752-96cfa986-8d6b-11e7-8cee-1bdf36a4e473.png">

ACTUAL RESULTS:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/68213/29876549-1fa86258-8d6b-11e7-80f9-cd015c433ea9.png">

**Comment by vladikoff** [comment]
This is due to `background-size: 32px 32px;` css

**Comment by ryanfeeley** [comment]
@vladikoff So all our graphics needs to be centered on 32 x 32 px?
