### ISSUE TITLE
How to get rid of escape-characters?

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server#5407]
Where do these escape-characters on Firefox Accounts come from and how to get rid of them? 

See: https://imgur.com/a/uisRm

**Comment by rfk** [comment]
Thanks for the report @peiying2; what locale are you seeing this in?

**Comment by peiying2** [comment]
@rfk looks like folks on IRC #fxa were working on it.  

https://github.com/mozilla/fxa-content-server-l10n/blob/4ed63475640699e57124ad143d93752c8ebd9ff1/locale/rm/LC_MESSAGES/client.po#L76 - Romansh is the locale.

**Comment by gion-andri** [comment]
The same issue seems to exist also on other screens: 
https://imgur.com/a/MJ3LA

(tested some minutes ago on https://latest.dev.lcip.org/ )

Is there a way to fix this problem an all screens? Potentially, a `'` character could be used in every string.

**Comment by vladikoff** [comment]
@gion-andri Thanks for testing, we shall check that string!
