### ISSUE TITLE
Correct experiment reporting metrics to DataDog

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5416]
If I break down fxa.content.loaded for the past 4 hours by exp_group, I see some strange combinations of metrics.

```
24.92%     exp_group:control,exp_group:disabledbuttonstate
24.89%     exp_group:control,exp_group:signuppasswordconfirm
24.73%     exp_group:disabledbuttonstate,exp_group:treatment
24.2%      exp_group:signuppasswordconfirm,exp_group:treatment
0.8%       exp_group:N/A
0.23%      exp_group:control,exp_group:disabledbuttonstate,exp_group:treatment
0.17%      exp_group:control,exp_group:signuppasswordconfirm,exp_group:treatment
0.03%      exp_group:disabledbuttonstate,exp_group:signincodes,exp_group:treatment
0.02%      exp_group:signincodes,exp_group:signuppasswordconfirm,exp_group:treatment
0.02%      exp_group:control,exp_group:signincodes,exp_group:signuppasswordconfirm
0.019%     exp_group:control,exp_group:disabledbuttonstate,exp_group:signincodes
```

I forget the actual intended enrolment numbers, but I imagine that it should look something more like:

```
30%     exp_group:control
30%     exp_group:treatment
40%     exp_group:N/A
```

and if broken by experiment, something like:
```
20%     experiment:disabledbuttonstate
20%     experiment:signuppasswordconfirm
20%     experiment:signincodes
40%     experiment:N/A
```

[Source](https://app.datadoghq.com/dash/54206/fxa-content---registration?live=true&page=0&is_auto=false&from_ts=1504274571518&to_ts=1504278171518&tile_size=m&fullscreen=171093169)

**Comment by shane-tomlinson** [comment]
cc @vladikoff

**Comment by vladikoff** [comment]
Looking at the graphs the data seems fine after the fix: 

![image](https://user-images.githubusercontent.com/128755/29981613-4f5e752a-8f1c-11e7-81e1-6b9fa9a43c32.png)

**Comment by vladikoff** [comment]
having experiment names under `exp_group` looks wrong, don't use that. 
it should be `exp_group: treatment / control ` and `experiment:someexperiment`

**Comment by ryanfeeley** [comment]
@vladikoff I'm saying that the data coming in looks weird. I can break down anything by user agent, operating system, train name. Why can't I break things down by experiment names? See the source chart link above.

**Comment by shane-tomlinson** [comment]
ref #5443

**Comment by rfk** [comment]
IIUC the official word is we need to migrate away from datadog, so I'm going to close this issue.  Let's re-open if we need to fix it in the interim.
