### ISSUE TITLE
Success message should be white not black

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5418]
I remember testing this before doing the Photon PR, and it was white, but I see black…
![screenshot 2017-09-01 15 17 21](https://user-images.githubusercontent.com/68213/29985088-80532dce-8f2b-11e7-9314-2bc08a06945e.png)

**Comment by apoorvasingh17** [comment]
Hi, can I take this up?

**Comment by vladikoff** [comment]
Sorry @apoorvasingh17 , we already have a PR in progress to fix this.
