### ISSUE TITLE
Tests not running on teamcity

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5427]
Looks like destructuring is blowing up everything!

<img width="696" alt="screen shot 2017-09-04 at 15 01 51" src="https://user-images.githubusercontent.com/848085/30029665-a2b9722e-9179-11e7-9ced-03f7cc125358.png">

@jrgm - I thought teamcity was all node 6 now?

**Comment by jrgm** [comment]
Fixed.

**Comment by shane-tomlinson** [comment]
Thanks @jrgm!
