### ISSUE TITLE
Stop emitting so many screen.settings events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5428]
Currently, we emit extra `screen.settings` events when users close the settings sub-views, like "Devices & apps" or "Communication preferences". I'd like to change this behaviour so that those transitions do not cause the main `screen.settings` event to be re-emitted every time, but not if that is going to mess up anyone's dashboards.

@ryanfeeley do you have any metrics in DataDog that might be borked if I were to make this change?

**Comment by philbooth** [comment]
Talked about this in the meeting, we've agreed that the extra events can be got rid of.

**Comment by ryanfeeley** [comment]
👍
