### ISSUE TITLE
Log output for the server tests is worse than useless

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5431]
When I run the server tests, they log a line for every passing test case and don't log any lines at all for failing test cases. This is the diametric opposite of what it should be.

I want to be able to easily see which tests are failing from looking at the output. Instead, I have to compare the output against the list of all tests and see which ones are missing, which is time-consuming and completely mental.

**Comment by vladikoff** [comment]
Might help:

```diff
diff --git a/tests/intern_server.js b/tests/intern_server.js
index 9ca4e39c..6c3b71df 100644
--- a/tests/intern_server.js
+++ b/tests/intern_server.js
@@ -9,6 +9,7 @@ define([
   intern.webdriver = {};
   intern.environments = [];
   intern.functionalSuites = [];
+  intern.reporters = ['Pretty'];
   intern.suites = [
     'tests/server/routes',
     'tests/server/l10n-entrained',

```

**Comment by philbooth** [comment]
> Might help...

Thanks, it does! That reporter does at least show fail messages and, added bonus, it has shiny colours! 🌈
