### ISSUE TITLE
Inaccurate message when verifying in Fx for iOS w/ already signed in user.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5434]
STR

1. In Firefox for iOS, sign up for a new user.
2. Open the verification link in Firefox for iOS.
3. Be confused.

Screen cap generated on Fx desktop forcing the UA string to be that of Fx for iOS:

<img width="423" alt="screen shot 2017-09-05 at 15 30 24" src="https://user-images.githubusercontent.com/848085/30066296-0263e63c-9247-11e7-879d-4d110a7d8b63.png">

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
Found while developing #5408

**Comment by shane-tomlinson** [comment]
Assigning to @ryanfeeley for some designs.

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vladikoff I think our generic screen works well here for now.
![screen shot 2017-11-01 at 16 56 50](https://user-images.githubusercontent.com/68213/32297517-cb000f48-bf25-11e7-8b3d-e238efa4e90c.png)

**Comment by ryanfeeley** [comment]
@vbudhram We're still on a campaign to get users to connect additional devices. If they are signed in on more than one, we should use the "Still adding devices?" variants here: https://github.com/mozilla/fxa-content-server/issues/5262#issue-244461294

**Comment by vbudhram** [comment]
@ryanfeeley Gotcha, it just seemed strange to show the user the App Store button to download an app they already have downloaded on the device.

SMS may make more sense since they could send to another phone number?

**Comment by ryanfeeley** [comment]
@vbudhram Sounds like a job for A/B testing? The SMS variant is on that screen too.

**Comment by rfk** [comment]
Closing in favour of https://github.com/mozilla/fxa-content-server/issues/5858 which has more clear proposed outcome.
