### ISSUE TITLE
Make sync options two columns on iframe size

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5442]
The Sync options push the primary action button below the fold. We need to make them two columns. One way to achieve this is to use the newsletter opt-in font style, and make the columns narrower.

CURRENT:
<img width="200" alt="screenshot 2017-09-06 10 51 26" src="https://user-images.githubusercontent.com/68213/30118991-75a5efd6-92f2-11e7-8f15-0af851db5fb5.png">

PROPOSED:
<img width="200" alt="screenshot 2017-09-06 10 53 43" src="https://user-images.githubusercontent.com/68213/30118994-76093dac-92f2-11e7-9b96-bf56aa429440.png">

**Comment by shane-tomlinson** [comment]
@ryanfeeley says make the font 14px
