### ISSUE TITLE
Cannot differentiate between experiment groups of multiple experiments in DataDog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5443]
We use the same experiment group names for all experiments, generally `treatment`, and `control`.

[`q3FormChanges`, `disabledButtonState` and `verificationPassword`](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/experiment.js#L19) are all created [in any view that adds the `experiment-mixin`](https://github.com/mozilla/fxa-content-server/blob/4a705997867c0a496d907c2e442c40eabf0a5b6e/app/scripts/views/mixins/experiment-mixin.js#L29). `emailFirst` and the `sendSms` use the same experiment group names.

The statsd collector creates [an unprefixed `exp_group` tag for each experiment](https://github.com/mozilla/fxa-content-server/blob/4a705997867c0a496d907c2e442c40eabf0a5b6e/server/lib/statsd-collector.js#L82), but if a user is in multiple experiments, of which they will be if they are chosen for emailFirst or CAD, then it's possible for a single event to be tagged as both `treatment` and `control`. This is less than awesome.

I'm not sure if this affects the flow metrics as well.

cc @vladikoff and @philbooth.

Ref https://github.com/mozilla/fxa-content-server/issues/5416

**Comment by shane-tomlinson** [comment]
@ryanfeeley's data in https://github.com/mozilla/fxa-content-server/issues/5416 is an example of this problem occurring in reality.

**Comment by rfk** [comment]
> I'm not sure if this affects the flow metrics as well.

In our re:dash queries we typically filter by both event name and group name, so I don't think it'll have any effect there.

**Comment by shane-tomlinson** [comment]
> In our re:dash queries we typically filter by both event name and group name, so I don't think it'll have any effect there.

What if two group names are reported because the user is in two experiments?

**Comment by philbooth** [comment]
> What if two group names are reported because the user is in two experiments?

It depends on individual queries of course but there's the nothing in the schema itself which should have problems with that.

We have a dedicated [`flow_experiments` table](https://github.com/mozilla/fxa-auth-server/blob/master/docs/metrics-events.md#flow_experiments), which is populated from the `flow.experiment...` events. Each row has its own `experiment` and `cohort` columns, along with the `uid` and `flow_id`, so queries just need to make sure they `JOIN` with `flow_experiments` and nominate the experiment they're interested in.

**Comment by shane-tomlinson** [comment]
> so queries just need to make sure they JOIN with flow_experiments and nominate the experiment they're interested in.

Perfect, thanks for the clarification @philbooth. 

Looks like this problem only affects DataDog.

**Comment by vladikoff** [comment]
we can try having short names for a/b groups such as `dbs_treatment`, `cad_treatment`, etc

**Comment by rfk** [comment]
IIUC the official word is we need to migrate away from datadog, so I'm going to close this issue.  Let's re-open if we need to fix it in the interim.
