### ISSUE TITLE
Login page fails to load in iOS 9 mobile safari

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5452]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1397691, tested this in mobile Safari and it fails to load. From console logs, it appears to be a CSP error.

![screen shot 2017-09-07 at 9 43 03 am](https://user-images.githubusercontent.com/1295288/30166329-f52c54b6-93b0-11e7-8f03-36cf196b508d.png)

Tested using the same url as Firefox iOS: https://accounts.firefox.com/signin?service=sync&context=fx_ios_v1

**Comment by vladikoff** [comment]
![](http://v14d.com/i/59b15913d3209.png)

![](http://v14d.com/i/59b15936b1f4e.png)

**Comment by vbudhram** [comment]
Did a quick check and this was working in train 93. Not sure what could have introduced it but an trace seems to point to something email-first or sync engine.

<img width="502" alt="screen shot 2017-09-07 at 5 46 18 pm" src="https://user-images.githubusercontent.com/1295288/30187289-0feb025c-93f7-11e7-8421-bf5d62894c36.png">

**Comment by vladikoff** [comment]
@shane-tomlinson @vbudhram removing the static getter fixes the issue in Safari 9:

```diff
diff --git a/app/scripts/lib/experiments/grouping-rules/email-first.js b/app/scripts/lib/experiments/grouping-rules/email-first.js
index cb0c52e1..75c9eea3 100644
--- a/app/scripts/lib/experiments/grouping-rules/email-first.js
+++ b/app/scripts/lib/experiments/grouping-rules/email-first.js
@@ -75,17 +75,6 @@ define((require, exports, module) => {
     static sampleRate (env) {
       return env === 'development' ? 1.0 : 0.2;
     }
-
-    /**
-     * The experiment name
-     *
-     * @readonly
-     * @static
-     * @return {String}
-     */
-    static get name () {
-      return EXPERIMENT_NAME;
-    }
   }
```

So we need to modify this a bit to make Safari 9 work again

**Comment by shane-tomlinson** [comment]
> So we need to modify this a bit to make Safari 9 work again

Strange, it seems like that should be compiled by babel to something useful. We might not need the static getters on the class, I'm not sure they are used anywhere.

**Comment by vladikoff** [comment]
Fixed in Fixed in https://github.com/mozilla/fxa-content-server/pull/5479
