### ISSUE TITLE
Update Copy Around Newsletter Opt-in

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5460]
From Ben Niolet (and retention marketing team): 

"TL;DR: We would like to change the language on email opt-ins on the accounts sign up form and in the settings UI for Accounts. This is so we don't confuse users when we start sending Account-related email that isn't opt-in. 

(...)

We have worked up some draft copy and would like to work with you to get this implemented. Additionally, we'd like to change the Account sign-up form email opt-in language. It currently refers to a monthly newsletter, but we have moved away from monthly newsletters (*and newsletters in gerneral*) and think we have some more accurate language. 

The copy we worked up and the existing experience for comparison is here: 

https://docs.google.com/a/mozilla.com/document/d/1jzL4yM_JafGN1OmHPGaAmtasJxHMlkaYumbL1g88Fo4/edit?usp=sharing

"

**Comment by davismtl** [comment]
I'm just making sure we are crystal clear on the choice of copy before we schedule this change.

**Comment by shane-tomlinson** [comment]
@davismtl - are we crystal clear yet?

**Comment by davismtl** [comment]
Yes, they've updated to include copy in registration form opt-in.

**Comment by ryanfeeley** [comment]
@davismtl I commented on the doc. This piece of UI seems ripe for A/B testing to me, but I'm sure there has to be a lot of evidence pointing to what works best already.

**Comment by davismtl** [comment]
@ryanfeeley I don't care to test it in Settings.

On the registration form, the copy change seems pretty minimal. I don't think changing the small print copy of the newsletter subscription will impact registration to accounts. So I would vote to not test it. Too much overhead for such a little change.

I do however like your recommended improvement to it. Shorter is better.

What would be the hypothesis if you tested it?

**Comment by ryanfeeley** [comment]
The change would increase the number of people signing up for the newsletter without having an adverse affect in signup success overall.

**Comment by davismtl** [comment]
Ben Niolet signed off on your shorter copy. Due to the small size of the change, I don't think an A/B test is worth the overhead. (feature doc, engineering work, analysis, etc)

Let's just roll it out. Legal wants the change too IIUC.

**Comment by vladikoff** [comment]
@davismtl sorry, what is the **final** copy for this? Thanks!

**Comment by davismtl** [comment]
@vladikoff I commented in the Google Doc with your name so you can easily see the two pieces of copy.

**Comment by vladikoff** [comment]
@davismtl awesome, thank you!
