### ISSUE TITLE
email-first experiment is not sufficiently isolated to compare apples to apples

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5469]
@davismtl and I discussed this on Friday in our 1:1, capturing here some of our thoughts.

* Bucket user into one of "verify password", "email-first" and "disabled button state" and "control".
* Remove the verify-password field until that experiment has proven itself out, because we believe this causes ~ 6% dropoff.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/5479
