### ISSUE TITLE
Restore utm_* to metricsContext for /account/create and /account/login

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5487]
We used to include the `utm_*` query parameters in the `metricsContext` bundle sent to many backend API requests, but we stopped doing it over in (https://github.com/mozilla/fxa-js-client/pull/223, https://github.com/mozilla/fxa-content-server/pull/4456) because we didn't need it for redash anymore.

Turns out that other things were using it though, in particular the marketing team uses them for metrics purposes when users opt-in to the marketing emails:

  https://github.com/mozilla/fxa-basket-proxy/blob/master/lib/events/index.js#L59

And they also use `utm_campaign` as an experiment flag to tunnel some metrics information through the first-run flow and into basket:

  https://github.com/mozilla/fxa-basket-proxy/blob/master/lib/events/index.js#L94

They haven't run any experiments that used this functionality for a while, so we didn't notice when it stopped working.  But they want to run one now:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1392860

How terrible will it be to restore the `utm_*` parameters to `metricsContext` in /account/create and /account/login calls, so that we can pass them through to basket?  I'm open to finding a different approach but it seems like just putting them back would be the simplest approach.

/cc @philbooth @shane-tomlinson for comment.

**Comment by philbooth** [comment]
> How terrible will it be to restore the `utm_*` parameters to `metricsContext` in /account/create and /account/login calls, so that we can pass them through to basket?

Not at all terrible, happy to do it.

Actually I'm surprised/impressed that anyone even managed to depend on them, I didn't think they were around in the back-end for very long!

**Comment by philbooth** [comment]
Note to self: If people are depending on this stuff it's important to have tests that make sure we don't optimise it away again in the future.

**Comment by philbooth** [comment]
> ...in /account/create and /account/login calls...

For the sake of simplicity in the auth server, I'll probably just add them as optional properties to the schema that is re-used everywhere. So it will be possible to send them to any of our `metricsContext` consuming endpoints, we just won't do anything with them in most places for now.

**Comment by philbooth** [comment]
Auth server portion: mozilla/fxa-auth-server#2119

**Comment by rfk** [comment]
Thanks @philbooth!  IIUC we'll need to get the auth-server part deployed before any content-server change goes live, in order to avoid erroring out due to unknown properties.  What do you think about doing the content-server change in a train-96 point release, so we can get it live soon after the train-96 deploy?

**Comment by vladikoff** [comment]
cc @vbudhram
