### ISSUE TITLE
Fx >= 57 transitions to the wrong screen after unblocking a Sync signin

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5488]
Follow on from #5472.

Firefox >= 57 transitions to /settings instead of /signin_confirmed or /connect_another_device.

See https://github.com/mozilla/fxa-content-server/blob/f1f8a00cc61ca7efd1afb8b91746129b1f69a69a/tests/functional/sync_v3_sign_in.js#L202

**Comment by vladikoff** [comment]
from mtg: what is the fix for this?
