### ISSUE TITLE
OAuth permissions are not translated

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5490]
Found while investigating #5407.

<img width="428" alt="screen shot 2017-09-15 at 14 28 23" src="https://user-images.githubusercontent.com/848085/30484457-ed872834-9a19-11e7-90ba-756f8dae01a5.png">

**Comment by rfk** [comment]
Dup of #4758?

**Comment by shane-tomlinson** [comment]
Yes, closing as dup.
