### ISSUE TITLE
Broken link when deleting an account

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa-content-server#5493]
Deleted an account from iOS, I got the following screen:
The broken string is `Looking for Firefox Sync? <a %(escapedSyncSuggestionAttrs)s>Get started here</a>`

![img_1508](https://user-images.githubusercontent.com/1294206/30517969-e931416c-9b67-11e7-9468-a672b8b7734a.PNG)

**Comment by shane-tomlinson** [comment]
This is actually working as expected. Within the iOS FxA panel, there is no way to open new tabs, so all external links are converted to inline links. You can see the same behavior if you visit the Terms of Service and Privacy policy.

Background information in https://github.com/mozilla/fxa-content-server/issues/2225 and https://github.com/mozilla/fxa-content-server/issues/3164

**Comment by TheoChevalier** [comment]
Oh I see, had no idea :) Thanks for the explanation, I guess this can be safely closed

**Comment by rfk** [comment]
It does seem like we could avoid showing this message at all though, since we're inside the iOS "settings" view so we're pretty definitely for there from sync already.  I wonder if the act of deleting the account clears the "service=sync" and other query parameters and causes us to show this message.

**Comment by shane-tomlinson** [comment]
>  I wonder if the act of deleting the account clears the "service=sync" and other query parameters and causes us to show this message.

It does - https://github.com/mozilla/fxa-content-server/blob/b8f299bb485ba15a0fd3d6bc166fd008badfd6b2/app/scripts/views/settings/delete_account.js#L45

**Comment by shane-tomlinson** [comment]
>  clearQueryParams: true, 

I added `clearQueryParams` in dbc531c1598d8dadf44d7c8d5b9e66f462d8cc40, but I do not recall why.
