### ISSUE TITLE
Add support for deriving scoped keys in the oauth flow

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5494]
In support of [1], content-server will need to add support for deriving scoped keys as part of the oauth flow, including:

* Detecting a `keys_jwk` query parameter as a signal that the relier wants keys
* Calling the API provided in [2] to determine which of the requested scopes have associated keys, and fetch the metadata needed to calculate them
* Deriving key material for each scope following the specification in [1]
* Encrypting the key material to the provided `keys_jwk` public key, to produce a `keys_jwe` bundle.
* Passing the `keys_jwe` bundle back to the relier via the API provided in [3]

[1] https://docs.google.com/document/d/1IvQJFEBFz0PnL4uVlIvt8fBS_IPwSK-avK0BRIHucxQ/edit#heading=h.mqdsr2ucjm61
[2] https://github.com/mozilla/fxa-oauth-server/issues/483
[3] https://github.com/mozilla/fxa-oauth-server/issues/484

**Comment by vladikoff** [comment]
from mtg: ship it with a some kind of a feature flag

**Comment by shane-tomlinson** [comment]
@vladikoff - is this for train-100?

**Comment by vladikoff** [comment]
> @vladikoff - is this for train-100?

**Comment by rfk** [comment]
>  is this for train-100?

Yeah, we talked about landing it preffed-off if we feel like the code is ready, so that there's a shorter path to enabling it in time for Lockbox beta assuming the reviews etc work out.  Obviously part of that is assuring ourselves that the feature-flag adequately protects us from any unforseen issues in the new code!  I feel like it does.
