### ISSUE TITLE
Connect another device screen shows black box

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5496]
STEPS TO REPRODUCE
1. Be signed in to Sync
2. Visit https://accounts.firefox.com/connect_another_device

ACTUAL RESULTS
Black box and missing Android logo. Using latest Nightly.
<img width="1241" alt="screenshot 2017-09-18 15 34 51" src="https://user-images.githubusercontent.com/68213/30560975-8b04f8a6-9c87-11e7-86dd-65c4258e7252.png">

**Comment by vladikoff** [comment]
O_o

**Comment by vladikoff** [comment]
This is not even svg yet

**Comment by shane-tomlinson** [comment]
I don't know why that's happening, I see this:

<img width="715" alt="screen shot 2017-09-18 at 21 05 03" src="https://user-images.githubusercontent.com/848085/30562098-d578325c-9cac-11e7-92fb-d8e7df83f04d.png">

**Comment by rfk** [comment]
Rendering bug in Nightly maybe? 😀

**Comment by vladikoff** [comment]
@ryanfeeley Seems like a Firefox / Computer problem.

**Comment by ryanfeeley** [comment]
Yeah probably.
