### ISSUE TITLE
# of users in email-first experiment has dropped w/ the updated bucketing

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5502]
Caused by https://github.com/mozilla/fxa-content-server/pull/5479.

email-first was rolled out to 2.5% of the global population from about:preferences#sync. With #5479, we essentially divided this by 3. Now we have far fewer people in the experiment.

Here are the results:

<img width="959" alt="screen shot 2017-09-19 at 15 55 34" src="https://user-images.githubusercontent.com/848085/30599048-ea8f30ac-9d4a-11e7-8beb-7f8937dd4ee8.png">

To get back to the original count of people in the experiment, we should set the % to 10% now that a 4th experiment has been added.

**Comment by vladikoff** [comment]
@shane-tomlinson please triage is out of backlog 

:cake:
