### ISSUE TITLE
Give already used link screens a purpose

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5503]
I don't think we track views of this page, but seems like a good place to re-use the Connect Another Device logic. Make sense @shane-tomlinson? (use updated SVG)
![already-confirmed](https://user-images.githubusercontent.com/68213/30601046-f677bcf2-9d2e-11e7-9941-cee84c6c6709.png)

**Comment by ryanfeeley** [comment]
We could also do this for the verification link expired page. Simply put "Verification link expired" in the green bar, and the same relevant Connect Another Device content for the body.

![img_3976](https://user-images.githubusercontent.com/68213/30712100-ce5e7138-9ed8-11e7-9e79-5ae1f4ee83f8.PNG)

**Comment by vladikoff** [comment]
Not actionable for now
