### ISSUE TITLE
Can not change Account Picture on iOS

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5504]
Saw this in today's sync fest.

Manage Account -> Account Picture -> Add -> Upload -> Take Photo (or any other option) redirects to currently open tab (or home panel).

If “Synced devices” part of the history panel was open, a sync is triggered as well.

**Comment by rfk** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1393746, which should be fixed in upcoming deploy.

**Comment by grigoryk** [comment]
Ah, thanks Ryan. This seems like a dupe. I should update my iOS device, as well :)

**Comment by vladikoff** [comment]
Should be fixed!
