### ISSUE TITLE
Checkmark on sign-in confirmed page is slow to load

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5505]
Particularly slow on mobile.

Perhaps the page is actually fetching the image? If so, could we use a simple inline SVG instead?

**Comment by shane-tomlinson** [comment]
This entire flow is going to change with https://github.com/mozilla/fxa-content-server/pull/5408, though I can't imagine it'll be any faster. Inline images with a data URI might work, but that'd cause the template to explode in size which would slow down the initial JS download.

**Comment by vladikoff** [comment]
WONTFIX for now
