### ISSUE TITLE
Buttons wrap in FxA secondary email if string is too long in button

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa-content-server#5508]
Buttons wrap in FxA secondary email if string is too long in button

**Comment by juliemccracken** [comment]
Please see attached screen shot for an example

![bad-wrap](https://user-images.githubusercontent.com/17153650/30650721-8541543a-9dd8-11e7-918f-67816f363587.png)

**Comment by ryanfeeley** [comment]
Fixed?

**Comment by vladikoff** [comment]
@vbudhram @ryanfeeley wrap should be fixed? do we worry about the `...`?

**Comment by vbudhram** [comment]
@ryanfeeley Thought this was fixed in https://github.com/mozilla/fxa-content-server/pull/5681, the secondary email correctly wraps now. The issue for `Add...` button in German was in another [issue](https://github.com/mozilla/fxa-content-server/issues/5639).

**Comment by ryanfeeley** [comment]
@vbudhram @vladikoff For clarification, in German the ellipsis is correctly preceded by a space.

So in english we are waiting… and in German we are waiting …

We just have to make sure this button does not wrap

**Comment by ryanfeeley** [comment]
@vbudhram @vladikoff Bulgarian still looks downright vulgarian. Nowrap!
<img width="537" alt="image" src="https://user-images.githubusercontent.com/68213/38874839-0f3eeb8c-4227-11e8-8ff5-95d55bc3c57e.png">
