### ISSUE TITLE
Cached login screen displays old primary email when logging into AMO

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa-content-server#5509]
Cached login screen displays old primary email when logging into AMO
- User changes email, then signs in to AMO or Pocket, and original primary email is shown
<img width="485" alt="old-primary" src="https://user-images.githubusercontent.com/17153650/30651005-47172148-9dd9-11e7-962a-40a8dee16c11.png">

**Comment by vbudhram** [comment]
This was tested during today's Sync Fest and it showed the correct primary email. Closing!
