### ISSUE TITLE
Time stamp on devices and apps should truncate with ellipsis instead of colliding

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa-content-server#5510]
Time stamp on devices and apps should truncate with ellipsis instead of colliding

Please consult attached image.
![collide](https://user-images.githubusercontent.com/17153650/30652262-d2f68282-9ddc-11e7-86e0-25fa2b0da70a.png)

**Comment by rfk** [comment]
On a positive note, I think the emoji in device names are working correctly :-)

**Comment by philbooth** [comment]
I think the suggestion here contradicts the behaviour defined by @ryanfeeley, which was to wrap. That was implemented in #5693 and will be deployed in train 100 so I'm closing this, feel free to re-open though if anyone thinks I'm wrong.
