### ISSUE TITLE
[Sentry] New broker method needed for click

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5515]
Ref https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/647600/events/12083839/

@shane-tomlinson is this something to worry about?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson is this something to worry about?

Hmmm, this is very strange. How would model.type be set to `click`, seems like we are setting the model from a click event, which seems like The Wrong Thing.

**Comment by shane-tomlinson** [comment]
I haven't been able to figure out the source of this error. Putting back into "next".

**Comment by vladikoff** [comment]
@shane-tomlinson should this be active for next week?

**Comment by vladikoff** [comment]
![wat](https://user-images.githubusercontent.com/128755/32563110-50783b5c-c47e-11e7-9d5a-41380aeec738.gif)

**Comment by vladikoff** [comment]
```diff
diff --git a/app/scripts/views/app.js b/app/scripts/views/app.js
index 5a2412a1..4ff2e959 100644
--- a/app/scripts/views/app.js
+++ b/app/scripts/views/app.js
@@ -94,6 +94,7 @@ define(function (require, exports, module) {
     showView (View, options) {
       return p().then(() => {
         options.model = options.model || new Backbone.Model();
+        console.log('options.model.get(\'type\')', options.model.get('type'))
 
         var currentView = this._currentView;
         if (currentView instanceof View) {
```

**Comment by vladikoff** [comment]
Another model type leak here below. Somehow this model type propagates to this function https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/mixins/verification-reason-mixin.js#L25 @shane-tomlinson ?

![modelz](https://user-images.githubusercontent.com/128755/32563969-a8f63f34-c480-11e7-9789-8e87fb363e51.gif)
