### ISSUE TITLE
Metrics and amplitude events are mozlog 1

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-content-server#5523]
I was trying to track down why the Amplitude events were not being archived in the heka logs and one thing that I realized is that the logs are not valid mozlog format:

https://github.com/mozilla/fxa-content-server/blob/386886ee0c22b36ef05fa6cd84619e7978a8f7a4/server/lib/amplitude.js#L164-L175

Maybe switch that to use https://github.com/mozilla/fxa-content-server/blob/master/server/lib/logging/log.js ?

**Comment by philbooth** [comment]
@jbuck, I want to make sure there'll be no fallout from making the amplitude events a different format to the others emitted from this repo.

Currently, the amplitude event is in the same format as:

* `server/lib/flow-event.js`
* `server/lib/metrics-collector-stderr.js`
* `server/lib/routes/post-csp.js`

If we make it different to those, will it confuse anything else in our log-processing infrastructure? Or is that not a problem because we know we're the only consumers of these events?

**Comment by philbooth** [comment]
@jbuck, one difference with using `server/lib/logging.js` is that it forces everything through `stdout` whereas obviously at the moment I'm writing to `stderr`. Where do you expect to receive these events, `stdout` or `stderr`? Or do you read from both?

**Comment by philbooth** [comment]
Fwiw, I just realised the current format is identical to mozlog. Only the use of `stdout`/`stderr` differs. Is that the cause of the problem you're seeing @jbuck?

Event from the existing code:

```
{"op":"amplitudeEvent","time":1506357795913,"device_id":"3b1a1f4322d94f28a207476bbf9b16fb","event_type":"fxa_login - view","session_id":1506357795093,"event_properties":{"device_id":"3b1a1f4322d94f28a207476bbf9b16fb"},"user_properties":{"flow_id":"4a5e7f7b8659904025e2326bdfe750a5452819f937b380ab292d182a7da5552f"},"app_version":"96","language":"en"}
```

Event with changes to log via `mozlog`:

```
{"op":"amplitudeEvent","time":1506417750271,"device_id":"63b65492a24d44c186c088af723e6ade","event_type":"fxa_login - view","session_id":1506417743869,"event_properties":{"device_id":"63b65492a24d44c186c088af723e6ade"},"user_properties":{"flow_id":"052f414549111b543d00ffc59c29c268cb08c5add581511348a9db4b2764d475"},"app_version":"96","language":"en"}
```

**Comment by philbooth** [comment]
@jbuck, did #5525 make these events start showing up in the archived logs?

**Comment by jbuck** [comment]
I think something went horribly wrong:

Sep 28 14:23:38 ip-172-31-51-187 docker[4862]: {"Timestamp":1506608618743000000,"Logger":"fxa-content-server","Type":"server.amplitude.[object Object]","Severity":6,"Pid":5,"EnvVersion":"2.0"}

**Comment by vladikoff** [comment]
This is needed for quicksight

**Comment by philbooth** [comment]
The plan is to implement a logging 2.0 pipeline side-by-side with our current Heka based pipeline for the flow metrics and ensure that both are working the same. Once we're happy, we can flip the content server over to use mozlog 2.

**Comment by philbooth** [comment]
See also: mozilla/fxa-activity-metrics#99

**Comment by jbuck** [comment]
Also noting that we'll need to switch over the exact target daily export as well before we can move to mozlog 2.0...

**Comment by vladikoff** [comment]
from meeting: not needing this for now
