### ISSUE TITLE
Replace our avatar upload and clear icons with new Photon icons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5530]
CURRENT
![icons-current](https://user-images.githubusercontent.com/68213/30918340-43fdfa66-a36c-11e7-8407-477dd63efcfe.png)

* glyph-clear-32.svg
* glyph-upload-32.svg

PROPOSED (sized at 300%)
![variations](https://user-images.githubusercontent.com/68213/30919338-11336ca8-a36f-11e7-96e2-7cda75acd33c.png)

Source:
* http://design.firefox.com/icons/viewer/#close%2016
* http://design.firefox.com/icons/viewer/#new%2016

**Comment by vladikoff** [comment]
http://design.firefox.com/icons/viewer/#close 16
