### ISSUE TITLE
Use the two-hearts-beat-as-one SVG on CAD

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5532]
Our current [CAD page]( https://accounts.firefox.com/connect_another_device?service=sync) still uses the old illustration:
![image](https://user-images.githubusercontent.com/68213/30922878-6fc604ac-a378-11e7-8440-1d7a3e2e5b74.png)

We should instead use the new sweet animated SVG "account-verified.svg".

**Comment by vladikoff** [comment]
Need to double check this in train-96

**Comment by ryanfeeley** [comment]
@vladikoff You are right, it's in! https://latest.dev.lcip.org/connect_another_device
