### ISSUE TITLE
Failing functional test - Firefox Desktop Sync v2 reset password - reset password, verify same browser 

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5533]
> Error: UnexpectedBrowserNotification at Command.<anonymous> <tests/functional/lib/helpers.js:1468:43> at Command.<anonymous> <tests/functional/lib/helpers.js:1467:8> at Command.<anonymous> <tests/functional/lib/helpers.js:56:25> at Test.reset password, verify same browser [as test] <tests/functional/sync_v2_reset_password.js:75:10>

Introduced by https://github.com/mozilla/fxa-content-server/pull/5529

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/5536
