### ISSUE TITLE
Figure out the descrepancy in email-first metrics.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5548]
Looking at the metrics in https://sql.telemetry.mozilla.org/dashboard/fxa-email-first, it looks like treatment is generally outperforming the control group, but https://sql.telemetry.mozilla.org/queries/45007 makes it look like control outperforms treatment. We need to figure out why.

cc @davismtl - can you add your thoughts?

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by davismtl** [comment]
@shane-tomlinson I think you are spot on in the description of this problem.

Based on your dashboard, 
- the cohort sizes look the same
- treatment has more login
- treatment has more registration
- treatment has more flow_completes
- But... in one of the bottom charts, it looks like control has the best conversion rates. 
https://sql.telemetry.mozilla.org/queries/45007/source#121771

This doesn't seem to add up at first.

**Comment by irrationalagent** [comment]
I should have some time to investigate this within the next couple days

**Comment by shane-tomlinson** [comment]
@irrationalagent has come up with new queries that figured this out. I made a big mistake in my joins, using LEFT JOIN when I should have been using INNER JOIN. Closing.
