### ISSUE TITLE
Let's load the spinner even earlier!

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5553]
In #5483, @vladikoff changed the spinner to load from a `data:` URI. This has made a huge improvement to two key performance metrics, speed index and start render.

It knocked about 1.5 seconds off our start render time and improved our speed index by about 20%. Visually, that looks like this:

<img width="840" alt="Screen shot of a chart showing a 1.5 second improvement in start render time" src="https://user-images.githubusercontent.com/64367/31175795-5abbfbbc-a908-11e7-9daa-214b0810b593.png" />

<img width="838" alt="Screen shot of a chart showing a 20% improvement in speed index (first view)" src="https://user-images.githubusercontent.com/64367/31175847-94a497c6-a908-11e7-9509-c9781f8a6762.png" />

<img width="840" alt="Screen shot of a chart showing a 40% improvement in speed index (repeat view)" src="https://user-images.githubusercontent.com/64367/31175806-6721e196-a908-11e7-9a29-0c9ce53687c8.png" />

For more detailed analysis, the full median waterfalls can be found here:

* **Before:** [24th July 2017](https://www.webpagetest.org/result/170724_S1_14VY/3/details/#waterfall_view_step1)
* **After:** [2nd October 2017](https://www.webpagetest.org/result/171002_VM_15ea6807e6f350e6685d097496c61148/9/details/#waterfall_view_step1)

In that second waterfall it can be seen there are further gains available. If we were to load scripts and CSS asynchronously (with enough inline CSS to style the spinner and any other "immediate" styles), we could knock a further 3.5 seconds off our start render time. Hopefully that would lead to improved engage/submit metrics (and we could run it as an experiment to try and prove that).

/cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
👍 

We could get an easy win out of deferring/asyncing the main JS bundle w/o even worrying about styles yet.

An idea on how to measure this is to do our first server-side initiated experiment. The server would decide whether a user is part of the experiment, and if so, which group. It'd set a cookie so that decision persists. If the user is part of the treatment group, defer/async the script. For any user that's a member of the experiment, write one or more data- attributes to the body element. The front end would see the data- attributes and know to not bucket the user into any other experiments. It would report the experiment/bucket to metrics, and we would hopefully be able to compare treatment & control.

**Comment by philbooth** [comment]
> We could get an easy win out of deferring/asyncing the main JS bundle w/o even worrying about styles yet.

Definitely worth testing this but fwiw, the CSS and JS bundles are pretty much exactly parallel in the waterfall, so just moving the JS on its own may not get start render to happen any earlier. But let's try it out, I may be wrong.

**Comment by rfk** [comment]
>  The server would decide whether a user is part of the experiment, and if so, which group. 

In the past we've talked about having the server emit the `flow.begin` event in order to capture the start of the funnel as early as possible, would it make sense to do that as part of this change in order to get accurate flow_time measurements between the two groups?

**Comment by philbooth** [comment]
Just noting that I checked the [most recent waterfall](https://www.webpagetest.org/result/180313_Y9_ff23d0919866c38a48a536c385173f46/5/details/#waterfall_view_step1) in light of the Webpack change, and I think there's still work we can do here so let's keep this one open.

**Comment by vladikoff** [comment]
Please reopen if we still want to do this, or try other approaches to make the app faster
