### ISSUE TITLE
Screen needed for "Upgrade to the latest Firefox"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5558]
In support of "Discontinue support for old Firefoxes", we need a screen we can display
to users whose browsers are really really out of date that allows them to upgrade their
version of Firefox.

@ryanfeeley asked me to open a bug and assign it to him for designs.

**Comment by ryanfeeley** [comment]
LINK: https://www.mozilla.org/en-US/firefox/new/?scene=2
<img width="489" alt="image" src="https://user-images.githubusercontent.com/68213/31246238-b272e3fc-a9da-11e7-9874-f69636ab15b4.png">

**Comment by rfk** [comment]
@davismtl r? ^

**Comment by davismtl** [comment]
r+
