### ISSUE TITLE
Remove `treatment` group from `sendSms` experiment.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5561]
@irrationalagent has shown that [the `signinCodes` group outperforms the `treatment` group](https://sql.telemetry.mozilla.org/queries/42818#115860). We can make a good story about how CAD phase 3 outperforms CAD phase 2, even though it's really only a slight modification.

I propose we remove the `treatment` group so that only `control` and `signinCodes` remain. We'll push more users through `signinCodes`, and might learn something new...

An alternative is to remove the control group since they don't send SMS at all.

cc @rfk and @davismtl.

**Comment by davismtl** [comment]
I propose that we remove control for all markets we support SMS.

For markets that don't support SMS, control is still our best bet.

Follow up questions:
- how easy is it to deploy to new markets?
- what markets do we want to support? (my thoughts: most European countries)

**Comment by shane-tomlinson** [comment]
> I propose that we remove control for all markets we support SMS.
>
> For markets that don't support SMS, control is still our best bet.

👍 To be eligible for the experiment at all, the user must be in a market that supports SMS. If they are in a market w/o support, the `control` experience is the default, they just aren't reported as such.
