### ISSUE TITLE
Release SMS pt3 to Spain, Portugual and Italie.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5574]
SMS pt 3 had important improvements to mobile pairing. 

Let's deploy this to more European countries:
Spain, Portugual and Italie.

**Comment by rfk** [comment]
@shane-tomlinson do we need to complete the Germany rollout before moving ahead with this?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do we need to complete the Germany rollout before moving ahead with this?

No good reason to wait AFAICT.
