### ISSUE TITLE
iOS QR Code Scanning

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5576]
In order for device pairing to work, we need to figure out how we can scan QR codes with Firefox on iOS.

Identified options:
- iOS 11 might support WebRTC (does Firefox?)
- QR code scanner in native camera (iOS 11 only)
- Firefox has a native QR code scanner that works with iOS 10 too.

Let's figure out the pros and cons and which one we would ideally like to use based on technical constraints.

**Comment by vladikoff** [comment]
taking train-102 off from this, please re-"activate" once we start working on this again

**Comment by vladikoff** [comment]
🗡 closing for now,  Pairsona work
