### ISSUE TITLE
"Send Firefox over SMS" screen displayed after verifying a sign-in of an Android device

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa-content-server#5584]
My STRs:
- sign-in into FxA on an Android device
- verify sign-in on desktop via the email link
- observe this:
![image](https://user-images.githubusercontent.com/465422/31511960-65bcb02e-af57-11e7-9eb5-6c1f8f6c7234.png)

It's a bit of an awkward moment to display this screen, given that I've just signed-in from a mobile device.

**Comment by shane-tomlinson** [comment]
Thanks @grigoryk - this is a dup of #5196. We just haven't gotten around to prioritizing it yet.
