### ISSUE TITLE
Update to new Firefox logo?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5588]
IIUC there's a snazzy new Firefox logo coming with the 57 release.  @ryanfeeley should we update the versions of the logo used in this repo to match?  I couldn't find an existing ticket for it.

**Comment by ryanfeeley** [comment]
Yes! We should align with 57 launch. I have the repo, but not sure I should post publicly. Will send you on IRC.

**Comment by rfk** [comment]
We're deliberately not going to do a deploy at the same time as the 57 rollout, so we can't "ship" the updated logo to coincide with the 57 release.  But it'd be ideal if we could have this ready to display with the 57 release...@shane-tomlinson just thinking out loud here, but how feasible would it be to show the new logo to users on >=57 and the old logo to users on <57?

**Comment by rfk** [comment]
> how feasible would it be to show the new logo to users on >=57 and the old logo to users on <57?

From meeting, we're going to try this approach so it'll be ready for the 57 release
