### ISSUE TITLE
Include location and change secondary lines to sentence case

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5597]
Goodbye lowercase. It was nice while it lasted.

Because we shouldn't lowercase location names, here is what we should do for locations and the other secondary lines. I've included enough sentence case examples to paint a clear picture, but ask if not.

<img width="582" alt="sentence case" src="https://user-images.githubusercontent.com/68213/31687747-2ab97764-b358-11e7-9f61-455b19f8c40b.png">

**Comment by davismtl** [comment]
Looks good to me. I've added it to Feature doc: https://docs.google.com/document/d/1R80nsISQwrIalPyzWMRgu6dYCpbOHxvrl1TKjrdjfpA/edit#

Any thoughts on how it should wrap on mobile? Just double checking.

**Comment by vbudhram** [comment]
@ryanfeeley I like it 👍🏽. 

@shane-tomlinson would there be any issues with string translations? Would we need a semi-complete list of possible locations for translators?

**Comment by ryanfeeley** [comment]
@davismtl Great question! Left aligned to text with margin: 10px 0;

Both lines can wrap in this view as depicted below:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/68213/31728166-8db65f8e-b3f9-11e7-9307-5b339bbd5636.png">

**Comment by philbooth** [comment]
@ryanfeeley, how sure are you about including the state code in the location text like that? Might it seem weird for some locations? e.g. For me in the UK it will show up as `EN` for England, which doesn't like a useful addition to wedge between city and country like that.

**Comment by philbooth** [comment]
(although maybe it just seems weird in the UK I realise, in which case you can ignore me)

**Comment by ryanfeeley** [comment]
@philbooth I'm all for using the less specific location that we use in the tooltip today. For example, I see "Ontario, Canada" and not Toronto. If we do that, there will be less wrapping and we can use "in" instead of "near".

Thoughts? @davismtl?

**Comment by philbooth** [comment]
> Thoughts?

It works for me, but also so does "City, Country".

**Comment by ryanfeeley** [comment]
"in State, Country" might be smaller than "near City, Country", be accurate enough, and be more Mozilla-like (not creeping people out or revealing too much information on the screen).

I'll defer to @davismtl on the decision. I'm not sure where the current tooltip is coming from so I'm not sure what options there are.

**Comment by davismtl** [comment]
I think for security, there is benefit to being as accurate as possible. So I think @ryanfeeley 's initial proposal is fine.

I think there is benefit to include the approximate city. It might remind you that you forgot to logout of a public computer while you were traveling. (which you shouldn't do in the first place but... you get the point)

And Phil, if you were in Wales, WLS might be more useful than EN.

**Comment by philbooth** [comment]
@vbudhram makes a good point about translations above in https://github.com/mozilla/fxa-content-server/issues/5597#issuecomment-337581902.

Currently, we translate the "Last active over 2 months ago" bit. We don't translate the location bits because that would require asking localisers to translate every possible value for city, state and country, which is a huge list.

If I make these changes, we'll end up with a mixture of translated and untranslated content, unless we can come up with a cunning plan.

@ryanfeeley, @davismtl, do either of you have a cunning plan? Or will the untranslated locations be okay?

**Comment by davismtl** [comment]
> Consider what it will look like if we're mixing RTL and LTR text in the same line, for instance. That sounds like chaos to me.

Oh God, sounds horrible. I don't have a cunning plan unfortunately.

Does our Max Mind db include translations? I know their paid version does for the most common: "Chinese, French, German, Japanese, Spanish, Brazilian Portuguese, and Russian"
https://www.maxmind.com/en/geoip2-city

**Comment by philbooth** [comment]
> Does our Max Mind db include translations? I know their paid version does for the most common: "Chinese, French, German, Japanese, Spanish, Brazilian Portuguese, and Russian".

Oh, interesting. @jrgm, do we use a free Maxmind db or one of the enterprise ones?

**Comment by philbooth** [comment]
Apparently, Unicode CLDR has localised countries and regions:

http://cldr.unicode.org/

**Comment by philbooth** [comment]
> Unicode CLDR has localised countries and regions

https://github.com/unicode-cldr/cldr-json

**Comment by rfk** [comment]
Interesting, so would the idea be to give localizers a single string like "Last sync {localizedTimeAgo} near {localizedCity}, {localizedState}, {localizedCountry}" and then do automated localization of the various components, possibly on the server side?

I recall our current "last sync {localizedTimeAgo}" approach being suboptimal for some languages, but still workable; let's ping @mathjazz for input here.

We can also consider preffing this on for English only for a couple of trains to shake out any other bugs in parallel with sorting the localization.

**Comment by philbooth** [comment]
> ...automated localization of the various components, possibly on the server side?

Yep, done in the auth server as part of the devices request, which is when we localise the time.

**Comment by philbooth** [comment]
> The tricky part is the `localizedTimeAgo`...

Cool, we already localise the time with `moment` fwiw, just the location is changing in this issue.

**Comment by philbooth** [comment]
Looking at the territory subdivisions dataset in CLDR (which I think is the closest to what we want):

https://www.unicode.org/cldr/charts/latest/supplemental/territory_subdivisions.html

I think we'll need to be quite adaptable on the front end in terms of what translations we have available to display. For instance, in the UK the cities are there but in the US & Canada they aren't.

I think we should localise a few different formats and then the content server can pick the most precise available at runtime:

* "Last sync %(translatedTimeAgo)s in %(translatedCountry)s"
* "Last sync %(translatedTimeAgo)s in %(translatedState)s, %(translatedCountry)s"
* "Last sync %(translatedTimeAgo)s near %(translatedCity)s, %(translatedState)s, %(translatedCountry)s"

...and so on.

/cc @davismtl, @ryanfeeley.

**Comment by philbooth** [comment]
Bumping this back to `train-100`, because it depends on auth server work and we don't want to be monkeying about point releases around the time of Fx57.

**Comment by philbooth** [comment]
> ...the territory subdivisions dataset in CLDR...

Unfortunately this data is not localised currently. Only the territory names (countries) are localised:

https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en-GB/territories.json

I've had a search for other data sources, but didn't find anything usable.

I'll crack on with the localised countries for now, but I'm not sure what to do about cities and states. @davismtl, @ryanfeeley, what do you suggest?

**Comment by philbooth** [comment]
Just noting so I don't forget when I come back to this, there is a WIP branch that does the server-side country translation here:

https://github.com/mozilla/fxa-auth-server/compare/phil/content-5597

**Comment by davismtl** [comment]
Initial thoughts:
- If possible, give as many details to EN and only Country for other languages
- If last point is too complicated, just display country for now for everyone.

Investigate using MaxMind localization.

**Comment by zbraniecki** [comment]
that sounds good! I hope that eventually we can add region/city outside of US. I know that Europe would expect that and I expect Asia as well. Not sure about cultural patterns in SA, Africa and India, but I think it's ok to approach it gradually.

**Comment by ryanfeeley** [comment]
I agree with Alex. Adopt user language as much as possible.

If we wrote Moscow, Russia in Russian (I think) it would look like:
* Last sync 2 hours ago near Москва-Россия

I would not recognize that.

It’s perhaps more likely that users will know their city and country name in English than in Russian, but still, I suppose we should try and use the user’s language as much as possible.

**Comment by philbooth** [comment]
Just flagging up that there is a whole other can of worms I need to be careful of here, I just realised.

Because we're translating parts of this string using three different systems now, there are also three different sets of translated languages available and thus three different results when picking the best available language from the `Accept-Language` header.

In practice this won't happen often because the most popular languages are covered in all three cases. But there might be occasions when discrepancies occur. For the benefit of those cases, the back-end should communicate to the front-end which translation it has used so that we can maintain consistency. And inside the back-end we need to maintain consistency of translation language between `moment` and `cldr`.

I need to improve our test coverage in both the back-end and front-end to make sure this is solid.

**Comment by philbooth** [comment]
> Because we're translating parts of this string using three different systems now, there are also three different sets of translated languages available and thus three different results possible when picking the best available language from the `Accept-Language` header.

This is wrong. The translation via `moment` uses the same list of supported languages that the front-end does, I should have looked more closely at the code in `fxa-shared`. If I follow a similar approach with `cldr`, it will all work correctly.

> I need to improve our test coverage in both the back-end and front-end to make sure this is solid.

Still need to do this bit though, of course.
