### ISSUE TITLE
Release SMS pt 3 to Romania

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5611]
We have all the logic for sending SMS to Romania, yet we have only enabled the for mozilla and softvision addresses. We should remove the gating logic and allow all RO users to send SMS.

**Comment by vbudhram** [comment]
@davismtl can you triage?

**Comment by davismtl** [comment]
Well, I see that Shane already has a lot of markets schedules for train 100 so I guess it depends on the effort for removing the logic.
