### ISSUE TITLE
SMS experiment group updates - fully rolled out countries should only use `signinCodes`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5632]
@davismtl - my memory from Friday is already hazy.

Was it countries that are fully rolled out only use the `signinCodes` group, effectively ending the experiment for those countries, and for countries that are in the process of being rolled out, we should only use `treatment` and `signinCodes` - where `treatment`=CAD phase 2 (sms w/o signin code) and `signinCodes`=CAD phase 3 (sms w/ signin code)?

**Comment by davismtl** [comment]
Fully rolled out = phase 3 with codes
Any tests moving forward should be phase 1 vs phase 3 to validate if users are comfortable with SMS.

I **don't** see any scenario where phase 2 would beat phase 3 so there is no point using phase 2 moving forward for any tests. Kill it!
