### ISSUE TITLE
Communications Preferences->Manage Subscriptions sends me to /settings/null

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5641]
Not every time, but perhaps 50% of the time: https://accounts.firefox.com/settings/null

STR:
- signup for a new sync account in prod
- after confirming email, to to /settings
- Click Communication Preferences->Change...
- Click Subscribe
- some time later, or immediately, repeat. Click Communication Preferences->Change...
- Now click 'Manage Subscriptions'

Sometimes I go to page where I can manage subscriptions. But, often as not, I go to /settings/null.

**Comment by shane-tomlinson** [comment]
It seems like we don't have the user's basket id/endpoint yet in some cases.

**Comment by vladikoff** [comment]
Possible to reproduce if you create a new account and go to settings right away

**Comment by rfk** [comment]
> Possible to reproduce if you create a new account and go to settings right away

Just to record some IRL conversations for posterity: 
 * new user accounts get created in basket async, by processing "account created" events out of SQS
 * if the user visits communication-preferences before basket has processed the event for their account, we won't be able to find their basket token
  * that's probably what's causing this but to manifest

**Comment by rfk** [comment]
Some users are definitely hitting this in the wild, see e.g. https://twitter.com/mikeywaites/status/934668032168820736
