### ISSUE TITLE
CAD screen on originating iOS says to sign in to iOS

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5644]
STEPS TO REPRODUCE
1. Open a fresh version of Firefox iOS
1. Create a Firefox Account
1. Verify the account in the same browser

EXPECTED RESULTS
- Users are given generic instructions to install Firefox on another device to complete set-up
![proposed](https://user-images.githubusercontent.com/68213/31957211-0c344134-b8bc-11e7-8bfa-a6adbe507a55.png)

ACTUAL RESULTS
- Users are told to sign in to Sync on this browser (even though it already is signed in)
![current](https://user-images.githubusercontent.com/68213/31957323-6a195988-b8bc-11e7-82dd-e4e691199c15.png)

**Comment by shane-tomlinson** [comment]
Unassigning myself until we prioritize this.

**Comment by shane-tomlinson** [comment]
Dup of #5434, closing.

**Comment by ryanfeeley** [comment]
@shane-tomlinson This came up in Sync Fest as looking pretty bad. We need to fix this.
