### ISSUE TITLE
Question: Should countries in which SMS is fully rolled out report being part of the experiment?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5648]
Follow on from #5632 and #5647. In #5647, the only experiment group used for countries that are fully rolled out is `signinCodes`. Even though there is only one group, [the user still reports experiment metrics](https://github.com/mozilla/fxa-content-server/blob/f6054ff32eb42a2b1a3d5aa31f6e5a8b11c065cc/app/scripts/views/mixins/connect-another-device-mixin.js#L126). This doesn't seem quite right to me. It seems like if a country is fully rolled out, we should not enroll the user in the experiment, rather we should just use the normal metrics that are submit.

@davismtl, @rfk, @philbooth - thoughts?

**Comment by shane-tomlinson** [comment]
cc @irrationalagent too.

**Comment by davismtl** [comment]
If an experiment has **ended** for a cohort of users, new users should not be enrolled in the experiment.

What is the exception? 
Sometimes, the quickest way to rollout a win is to turn the winning variation to 100%, leaving the testing logic in place. But once the experiment code is no longer needed (normally shortly after win) and that the winning variation has become default in the code, the users should not longer appear to be part of an experiment.

Example: when I would run tests in Optimizely, changes were done via injection. If we had a clear winner, we'd turn up the winner to 100% to benefit from the win immediately. We would turn off the test once we had the real integration ready to go out to production.

Make sense?

**Comment by rfk** [comment]
>  It seems like if a country is fully rolled out, we should not enroll the user in the experiment,
> rather we should just use the normal metrics that are submit

This seems right to me, we should continue collecting the flow-event metrics for those users so we can monitor overall health of the feature, but we shouldn't report them as being part of the experiment, otherwise we'll wind up with wildly different cohort sizes for treatment and control.

In our re:dash metrics, are we able to filter down to just users from a particular country for this experiment?  I don't think we have geo data in those metrics yet.

**Comment by davismtl** [comment]
> In our re:dash metrics, are we able to filter down to just users from a particular country for this experiment? I don't think we have geo data in those metrics yet.

I don't see country in any of this: https://github.com/mozilla/fxa-auth-server/blob/master/docs/metrics-events.md

Just locale.

**Comment by philbooth** [comment]
> In our re:dash metrics, are we able to filter down to just users from a particular country for this experiment? I don't think we have geo data in those metrics yet.

mozilla/fxa-content-server#4069

**Comment by philbooth** [comment]
> In our re:dash metrics, are we able to filter down to just users from a particular country for this experiment? I don't think we have geo data in those metrics yet.

You can do this in Amplitude very easily fwiw. Here's users in the `signinCodes` cohort broken down by country:

https://analytics.amplitude.com/org/31251/chart/096t5xp

**Comment by vladikoff** [comment]
cc @shane-tomlinson to close this ?

**Comment by shane-tomlinson** [comment]
> cc @shane-tomlinson to close this ?

We have to remove the reporting yet for fully rolled out countries to close this out. I'll do that this week.
