### ISSUE TITLE
Add padding above Save settings button

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5661]
Choose what to Sync page seems to be missing some space beneath datatypes. Extra 10px?
<img width="1088" alt="screenshot 2017-10-30 14 10 16" src="https://user-images.githubusercontent.com/68213/32192236-00adff4e-bd8a-11e7-8e8d-63ecc8fb1189.png">

**Comment by vidhithebest** [comment]
Hi I'm a beginner. Can I work on this issue?

**Comment by himanish-star** [comment]
@vladikoff , Can I take over this issue ?

**Comment by himanish-star** [comment]
@ryanfeeley , how do I reach this page you are talking about . It's been an hour now and I was unable to findout the out the site. Could you tell the steps to reach there
