### ISSUE TITLE
Make the hearts in the SVG beat

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5662]
How are your SVG animation skills? Can you make the hearts throb in unison?
https://accounts.firefox.com/connect_another_device?service=sync

**Comment by kritisingh1** [comment]
@ryanfeeley what exactly are the SVG hearts supoosed to do? Like when the user opens the page he/she sees the animated SVG or on hovering over it? I mean can you please explain the expected behaviour a bit more clear? Thanks.

**Comment by ryanfeeley** [comment]
Thanks @kritisingh1! The hearts are animated correctly here, but the rings are not right (they are correct in production).

Can you take the best of both and make a PR?
[syncing-beating-hearts.html.zip](https://github.com/mozilla/fxa-content-server/files/1661740/syncing-beating-hearts.html.zip)

**Comment by kritisingh1** [comment]
Yeah sure. I will try :)

**Comment by anweshknayak** [comment]
@kritisingh1 you still on this?
