### ISSUE TITLE
Did the switch to docker slow down request times and can we do anything about it?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5672]
I demoed [this chart](https://sql.telemetry.mozilla.org/queries/5420#11032) to some of you in SF back in June, but never did anything else about it:

![Screen shot showing an increase in network time on content server requests, starting on the 14th June](https://user-images.githubusercontent.com/64367/32279545-f34c779e-bf10-11e7-9b96-9edc4a87f372.png)

It shows a small-in-absolute-terms-but-big-in-relative-terms increase (almost 100%, actual number redacted) in what I loosely labelled "network time" on that chart. Concretely, "network time" is defined as the sum of:

* `domainLookupEnd - domainLookupStart`
* `connectEnd - connectStart`
* `responseEnd - responseStart`

The increase began on June 14th and could have been for any reason but I'm going to go out on a limb and say it was probably the switch to docker that caused it, just because the times match up and I'm a big fan of sweeping statements.

Annoyingly, we weren't logging individual navigation timing metrics back then, so I can't get finer granularity to pinpoint precisely which metric(s) consumed the extra time. But I'm going to go out on another limb (I'm all limbs today) and say it's probably `connectEnd - connectStart`, because that seems like a plausible candidate.

No idea if there's anything we can do about this and I might be wildly wrong in my assumptions about the cause of it. But it occurred to me today that I should have opened an issue about it at the time, so people can look into it properly if they're so inclined.

Of course, if it turns out there's nothing we can do about it, closing this issue is fine. But maybe there is something we can do about it?

/cc @jbuck @jrgm

**Comment by vladikoff** [comment]
I remember when @jrgm talked about this being the case yeah. However not a 100% increase :)

**Comment by vbudhram** [comment]
from mtg: no apparent change, closing
