### ISSUE TITLE
Change password section persists errors after repeating openings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5680]
STEPS TO REPRODUCE
1. Log in to FxA settings
1. Open password section
1. Leave either field blank or invalid
1. Press Change button to get validation
1. Press Cancel
1. Press Change to reopen the section

EXPECTED RESULTS
1. Red warnings are gone and section is like new

ACTUAL RESULTS
1. [Red warnings persist](https://youtu.be/dA1DC9k-1NU)

**Comment by mutdmour** [comment]
I will work on this.

**Comment by vladikoff** [comment]
:+1:
