### ISSUE TITLE
Adjust the "continue to Lockbox" messaging in lockbox OAuth flow

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5702]
From meeting with the Lockbox team earlier this week, @ryanfeeley and Ryan Gaddis have been working on some tweaks to the verbiage in our OAuth signin form.  We currently say something like "Sign In to continue to Lockbox" but that's not terribly compelling messaging.

@ryanfeeley can you please coordinate with the Lockbox team to capture the final requirements here?

I'm a little hesitant about doing a one-off customization specifically for Lockbox here, because that's really not a scalable approach.  But let's get a clear idea of the ask, and then figure out what will make sense from our perspective.

**Comment by devinreams** [comment]
>I'm a little hesitant about doing a one-off customization specifically for Lockbox here, because that's really not a scalable approach. 

Agreed 💯 

FYI: Ryan Gaddis = @changecourse

**Comment by changecourse** [comment]
I think for beta, a message that allows someone to "Continue to Lockbox" or equivalent would be sufficient. 

That type of approach wouldn't be considered a one-off customization, right? (As both Sync and Pocket have similar, personalized messages)

**Comment by rfk** [comment]
Right now we have "Continue to %s" and we can make the %s be whatever you like (e.g. "Lockbox" rather than "Lockbox Web Extension") but I'm not outright ruling out changing it to something else.  @changecourse you had some proposed text in the meeting last week, can you please share it here?

**Comment by vladikoff** [comment]
from mtg: 

- Change to `Lockbox` as service name for production
- No changes to front-end for now...

**Comment by rfk** [comment]
> Change to Lockbox as service name for production

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1423068 to actually action the above change.

**Comment by ryanfeeley** [comment]
"Continue to %s" is accomodates both login and registration, and works for most services. Google uses it likely for this purpose.
