### ISSUE TITLE
Send previous sessionToken when re-authenticating, to avoid email confirmation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5703]
We have a seldom-used code-path where a user has an active sessionToken stored in localStorage n accounts.firefox.com, but we have to prompt them for their password again anyway before completing an OAuth login flow:

  https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/sign_in.js#L239

To achieve this, we basically end up just discarding the current sessionToken and creating a new one via `/account/login` here:

  https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L421

That new sessionToken currently does not inherit any verification state from the existing one, which is currently fine because OAuth flows don't require a verified sessionToken.

With Lockbox, that's about to change.

Lockbox intends to do an OAuth login once per browser session.  And since Lockbox wants keys, every login session will need to prompt for the user's password, call `/account/login` to generate a new sessionToken, and force the user through an email verification loop.

I think we should have this code-path send the *old* sessionToken over to the server, so that we can copy verification state from it rather than doing a fresh email loop every time.  This might be as simple as adding a "sessionToken" request parameter to the existing `/account/login` endpoint, like we did for `/password/change/finish` [1].  Or perhaps it warrants a new API endpoint, like `/account/login/refresh`?

@shane-tomlinson I recall discussing something similar to this with you in the past; thoughts?

[1] https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-passwordchangefinish

**Comment by shane-tomlinson** [comment]
Using a sessionToken in this manner seems reasonablish, though I wonder if there's a better way. Overriding /account/login seems strange because the user isn't logging in. I also worry about unused sessionTokens staying in existence, from a security perspective, though my worries could be unfounded. 

What you are trying to get is an updated keyFetchToken so that Lockbox can fetch keys w/o requiring an email verification loop, right? The fact that the only way to get a keyFetchToken is to generate a new sessionToken seems like an implementation detail that can be made to change, though my knowledge of the backend lacks here.

Right now there is a 1:1 mapping of sessionTokens->keyFetchTokens, does it need to be 1:1? Could it be 1:N where multiple keyFetchTokens are associated with a single sessionToken? Have the user enter their password, present a hash of the password and the existing (hopefully verified) sessionToken to the auth server, the auth-server returns a new keyFetchToken that can be used to get kB.

Using this scheme, we wouldn't have orphaned sessionTokens when new keyFetchTokens are generated, and once a keyFetchToken is used, it's jettisoned from the DB anyways. If the sessionToken is destroyed, all outstanding keyFetchTokens are also destroyed.

If a 1:N mapping is not feasible, it seems reasonable that we should clean up orphaned sessionTokens, at least if the sessionToken being presented is a Lockbox sessionToken. Obviously we can't just jettison Sync sessionTokens because we'd cause a logout of Sync.

**Comment by rfk** [comment]
> What you are trying to get is an updated keyFetchToken so that Lockbox can
> fetch keys w/o requiring an email verification loop, right?

There are a few reasons why we might hit the code path in question currently:

* You're logging in to lockbox and need to get a fresh keyFetchToken.
* You're logging in to an OAuth relier with a sessionToken that doesn't come from sync, so we prompt for your password again.
* You're logging in to a relier that has asked us to re-prompt for the password for security reasons.

I'm currently most interested in fixing the first, but it may be that there's a solution that cleans up all three cases.

> The fact that the only way to get a keyFetchToken is to generate a new sessionToken
> seems like an implementation detail that can be made to change

Agreed.

> Right now there is a 1:1 mapping of sessionTokens->keyFetchTokens, does it need to be 1:1?
> Could it be 1:N where multiple keyFetchTokens are associated with a single sessionToken?

I don't think there's anything but an indirect association between sessionTokens and keyFetchTokens on the backend.  They're created together, and they share the same verification status, but they're otherwise not explicitly linked.

> Have the user enter their password, present a hash of the password and the existing (hopefully
> verified) sessionToken to the auth server, the auth-server returns a new keyFetchToken that can
> be used to get kB

This sounds doable to me, and it seems a lot like "refreshing an existing sessionToken".  If you made the key-fetch part here optional, then it could also allow us to address the other two use-cases listed above.

**Comment by rfk** [comment]
Based on the above, my strawman API would be something like this, which is basically `/account/login` using an existing sessionToken:

----

**POST /session/refresh**

🔒 HAWK-authenticated with session token

Refresh an existing `sessionToken`, updating its `authAt` timestamp, and optionally obtaining a new `keyFetchToken` if `keys=true`.

*Query parameters*:
* keys: boolean, optional
    Indicates whether a key-fetch token should be returned in the success response.
* service: validators.service
    Opaque alphanumeric token to be included in verification links.

*Request body*:
* authPW: string, min(64), max(64), regex(HEX_STRING), required
  The PBKDF2/HKDF stretched password as a hex string.
* service: validators.service
  Opaque alphanumeric token to be included in verification links.
* resume: string, optional
  Opaque URL-encoded string to be included in the verification link as a query parameter.
* reason: string, max(16), optional
   Alphanumeric string indicating the reason for establishing a new session; may be "login" (the default) or "reconnect".
* unblockCode: string, regex(BASE_36), length(unblockCodeLen), optional
  Alphanumeric code used to unblock certain rate-limitings.
* metricsContext: metricsContext.schema

*Response body*:
* uid: string, regex(HEX_STRING), required
* keyFetchToken: string, regex(HEX_STRING), optional
* verificationMethod: string, optional
   The medium for how the user can verify.
* verificationReason: string, optional
   The authentication method that required additional verification.
* verified: boolean, required
* authAt: number, integer
  Authentication time for the session (seconds since epoch).

----

Thoughts?

**Comment by shane-tomlinson** [comment]
@rfk - looks reasonable though some questions.

1. `service` is included as both a query parameter and in the request body.
2. What is `login` reason? If `login`, should a new `sessionToken` be returned?
3. I see unblockCode, which makes sense, how will this interact with "signin confirmation"?

**Comment by rfk** [comment]
> service is included as both a query parameter and in the request body.
> What is login reason? If login, should a new sessionToken be returned?

These, I just copied directly from the docs for /account/login, they may not make as much sense on a new endpoint.

> I see unblockCode, which makes sense, how will this interact with "signin confirmation"?

I think the logic here should match that used on login; if you use an unblock code with an unverified session, it graduates to verified status.

**Comment by shane-tomlinson** [comment]
> I think the logic here should match that used on login; if you use an unblock code with an unverified session, it graduates to verified status.

I should have used better punctuation. The question was supposed to be how the endpoint will interact with "signin confirmation". Will there be a new endpoint to confirm the refresh? Will it be called a refresh confirmation?

**Comment by rfk** [comment]
> Will there be a new endpoint to confirm the refresh? Will it be called a refresh confirmation?

I don't think we'll need to, because it's using an existing session token.  Whatever confirmation you wanted to do should happen against the existing sessionToken, using existing session-token-confirmation APIs.
