### ISSUE TITLE
Enable SMS for Monaco

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5705]
Follow on for https://github.com/mozilla/fxa-content-server/issues/5573 and https://github.com/mozilla/fxa-content-server/pull/5698. I couldn't find any Monaco based mobile phone numbers that passed the validation logic, so I didn't enable it as part of #5698.

**Comment by shane-tomlinson** [comment]
@davismtl - there are ~ 35k people in Monaco and I couldn't find a number that validated. Can you re-triage this as you see fit?

**Comment by davismtl** [comment]
Low priority. I think it was mentioned with all the other french speaking countries.

**Comment by vladikoff** [comment]
@shane-tomlinson what are the next steps for this one?

**Comment by shane-tomlinson** [comment]
I'd close it personally. 35k really isn't very many.

**Comment by vladikoff** [comment]
yeah, @davismtl please reopen if needed
