### ISSUE TITLE
Are the errors in sms-errors.js correct?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5708]
The errors listed in [sms-errors.js](https://github.com/mozilla/fxa-content-server/blob/171e85f8854e358dc557fa19666d0e1171f07262/app/scripts/lib/sms-errors.js#L25) were all specific to Nexmo. Are they still used?

**Comment by shane-tomlinson** [comment]
cc @philbooth

**Comment by philbooth** [comment]
Just saw this sorry, also answered in IRC. Delete them.

**Comment by vbudhram** [comment]
from mtg: remove the errors

**Comment by shikhar-scs** [comment]
@philbooth could you please specify what all errors in sms-errors.js need to be removed ? Ill work on this and remove them accordingly.

**Comment by vladikoff** [comment]
@shane-tomlinson could you clarify which errors you use currently? it seems you added some new ones later on

**Comment by shane-tomlinson** [comment]
We don't use any errors from sms-errors, they are all based on nexmo's error codes and we have moved to Amazon. 

Remove the entire sms-errors.js file, plus [the conversion on lines 791-793 in fxa-client](https://github.com/mozilla/fxa-content-server/blob/41add48551e4bd798c6cb9d9cae9a45f9a6f0790/app/scripts/lib/fxa-client.js#L791), plus [these SmsErrors.is checks here](https://github.com/mozilla/fxa-content-server/blob/41add48551e4bd798c6cb9d9cae9a45f9a6f0790/app/scripts/views/sms_send.js#L173), plus any tests: 

* https://github.com/mozilla/fxa-content-server/blob/41add48551e4bd798c6cb9d9cae9a45f9a6f0790/app/tests/spec/lib/fxa-client.js#L1272
* https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/sms_send.js#L222:L238

And finally, [update `SmsErrors.toError('THROTTLED')` in this test](https://github.com/mozilla/fxa-content-server/blob/41add48551e4bd798c6cb9d9cae9a45f9a6f0790/app/tests/spec/views/sms_sent.js#L124) to be `AuthErrors.toError('THROTTLED')`

**Comment by shikhar-scs** [comment]
Sure @shane-tomlinson Ill do that soon and file a PR asap.

**Comment by shikhar-scs** [comment]
@shane-tomlinson how do I require AuthErrors for 
> And finally, update SmsErrors.toError('THROTTLED') in this test to be AuthErrors.toError('THROTTLED')
grunt testing gives out an error because of this.
``` /home/shikhar/Desktop/mozillaFxaContentServer/fxa-content-server/app/tests/spec/views/sms_sent.js
  124:69  error  'AuthErrors' is not defined  no-undef
```

**Comment by shikhar-scs** [comment]
@shane-tomlinson I've filed a related PR . Please review
