### ISSUE TITLE
Static legal and terms pages have the old logo

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5709]
Using Nightly, the links to the privacy and terms pages in Quantum first run still show the old logo.
- https://accounts.firefox.com/legal/privacy
- https://accounts.firefox.com/legal/terms

**Comment by rfk** [comment]
I'm going to go ahead and nominate this for last-minute "can we include this in train-100?" discussion, since at face value it seems like a small fix with high UX value for consistency purposes.  "No, we can't" is a totally appropriate answer though.

**Comment by ryanfeeley** [comment]
What's surreal to me is that the same URL in the same browser produces a different logo in a different context.

**Comment by vladikoff** [comment]
from mtg: make it just the new logo logo, needs the extra class
