### ISSUE TITLE
Make CWTS columns work in wider iframe

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5710]
The iframe got wider in this first run and now the columns don't work. Urgent bug.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/68213/32746094-a069ea22-c882-11e7-87d5-666a8f28a0b2.png">

**Comment by vladikoff** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1397532

**Comment by vladikoff** [comment]
Need to revert the 420px width, make it 318px; and using padding or probably white borders to get the spacing. cc @ryanfeeley

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1397532#c11

**Comment by shane-tomlinson** [comment]
@ryanfeeley - now that the firstrun team has fixed this problem on their side, do we need to do anything on our side?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yes, weirdly our layout flows well to two and even three columns when not in the iframe. We should fix our side so it works as well inside the iframe. I'm not sure why it doesn't work currently honestly.

**Comment by shane-tomlinson** [comment]
> I'm not sure why it doesn't work currently honestly.

For column layout to work, it needs actual pixel widths instead of percentages. We have pixel width set for "trustedUI" and "big", but not "small"
