### ISSUE TITLE
Replace mistyped email link in success message with Back link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5711]
The "Mistyped email" in our success message adds space and makes the message confusing.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/68213/32747557-1f6137f0-c887-11e7-9c12-1fd30b0a71f1.png">
We should return it to where it was: under the primary button labelled as "Back".

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Is this a dup of #5724?
