### ISSUE TITLE
Generate error entries from centralized lists

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5715]
Follow on from #5707.
Ref #4906 

This is an excellent suggestion by @philbooth that was discussed in the past but never acted upon. Whenever new errors are added to the auth, oauth, and profile servers, we often forget to add new entries to the content server. The result is whenever these errors are reported to /metrics, they are reported as an error with `[object Object]` and are not useful at all.

It seems like for safety, we should generate error list entries from a centralized location. If an entry already exists in our error list, ignore the generated error. If not, add the generated error.

**Comment by philbooth** [comment]
Or if we don't want to cook the whole hog and generate the actual definitions, we could still generate some kind of test stub that asserts all of the errors have definitions and fails a build somewhere if they don't instead.

**Comment by shane-tomlinson** [comment]
Are we ever going to do this? No. Closing.
