### ISSUE TITLE
Add default avatar when signing into new service

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5735]
I believe the avatar is shown if one is set, but is not if empty.

We should always show something here to make the layout easier to parse.

![add-avatar](https://user-images.githubusercontent.com/68213/33030636-cf1c7152-cde9-11e7-9321-bc90149a5202.png)

**Comment by shane-tomlinson** [comment]
> I believe the avatar is shown if one is set, but is not if empty.

I think it's slightly different - If the user has signed into the service previously, one is displayed.

**Comment by shane-tomlinson** [comment]
One for Austin.

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-profile-server/issues/295

**Comment by vladikoff** [comment]
Should be fixed if we fix https://github.com/mozilla/fxa-profile-server/issues/295

**Comment by vladikoff** [comment]
This is fixed
