### ISSUE TITLE
Make /connect_another_device redirect to /sms for eligible users

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5737]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1418466

Copied over from https://bugzilla.mozilla.org/show_bug.cgi?id=1418466#c5

As things stand today, the content server decides whether to send a user to 
/sms or /connect_another_device on /verify_email and other /complete_* screens.

/connect_another_device asks the user to install Firefox on their mobile device
but only shows the user the buttons to the app stores whereas /sms also allows
the user to send themselves an SMS with an install link.

By sending users directly to /connect_another_device, eligible users will
never be sent to /sms.

On the content server, we'll need to update the /connect_another_device endpoint
so that it makes the decision whether to stay on /connect_another_device or
send the user to /sms. This shouldn't be difficult to do, but we should make
this update before this patch works its way to beta/release or else
we are going to start wondering why the number of users going to /sms
drops in eligible countries.

**Comment by davismtl** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1420701
