### ISSUE TITLE
Use universal link to open Firefox preferences on iOS from sign-in button

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5743]
Can we open Firefox preferences on iOS from a sign-in button using a universal link? Like so:
![ios-sign-in](https://user-images.githubusercontent.com/68213/33098295-ea348488-ceda-11e7-9ea5-bb41348b4bea.png)

@vbudhram Possible?

**Comment by vbudhram** [comment]
@ryanfeeley Yup! That is possible. Only caveat is at this screen we won't know if the user is already signed into the device. If the button was a little generic, `Manage settings`, then when they click it we could deeplink into the iOS settings page which would then prompt to sign-in or show their account settings.

**Comment by vladikoff** [comment]
> Only caveat is at this screen we won't know if the user is already signed into the device. If the button was a little generic, Manage settings, 

👍

**Comment by ryanfeeley** [comment]
Messages | Email verified | This Firefox is connected
------------ | ------------- | -------------
Sign in to this Firefox to complete set-up | States | States
Still adding devices?  Sign in to this Firefox to complete set-up | States | States

**Comment by shane-tomlinson** [comment]
@ryanfeeley - This table screams at me that we are making our lives more difficult than need be. Can this be simplified?

**Comment by vladikoff** [comment]
waiting on https://github.com/mozilla/fxa-bugzilla-mirror/issues/423

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1425351#c5
