### ISSUE TITLE
Emit an event when DNT headers are encountered

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5744]
When DNT headers are encountered, we strip all of the `utm_` params out of our Flow/Amplitude data. But we don't log anything that let's us count how many times we've done this, which makes it impossible to say what proportion of the "not set" spike in this chart is due to DNT headers and what proportion might be due to something wrong in our code:

https://sql.telemetry.mozilla.org/queries/48786/source#131514

If we were to log some kind of "dnt-header" event, completely anonymised of course and offering no insight other than the ability to count how many times it happens per day, it might help us make sense of what we're seeing.

**Comment by vladikoff** [comment]
from mtg: Log to Kibana??
