### ISSUE TITLE
Teamcity failing functional test - settings secondary emails - gated in unverified session open verification new tab

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5748]
gated in unverified session open verification new tab |  
-- | --
Current failure:#3686 No changes 22 Nov 17 08:39First failure:#3685 No changes 21 Nov 17 20:38This test looks flaky:Test status change in build without changes: from successful to failedFrequent test status changes: 20 changes out of 33 invocationsView test history »JavaScriptError: [POST http://localhost:4444/wd/hub/session/6253ea0a-b347-47ea-a2e3-23eb9dfa1255/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t\t(function poll() {\n\t\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse {\n\t\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t})();\n\t\t\t\t\t}).apply(this, arguments);","args":["return (function (selector, options) {\n        var matchingEls = document.querySelectorAll(selector);\n\n        if (matchingEls.length === 0) {\n          return null;\n        }\n\n        if (matchingEls.length > 1) {\n          throw new Error('Multiple elements matched. Make a more precise selector - ' + selector);\n        }\n\n        var matchingEl = matchingEls[0];\n\n        // Check if the element is visible. This is from jQuery source - see\n        // https://github.com/jquery/jquery/blob/e1b1b2d7fe5aff907a9accf59910bc3b7e4d1dec/src/css/hiddenVisibleSelectors.js#L12\n        if (! (matchingEl.offsetWidth \|\| matchingEl.offsetHeight \|\| matchingEl.getClientRects().length)) {\n          return null;\n        }\n\n        // use jQuery if available to check for jQuery animations.\n        if (typeof $ !== 'undefined' && $(selector).is(':animated')) {\n          // If the element is animating, try again after a delay. Clicks\n          // do not always register if the element is in the midst of\n          // an animation.\n          return null;\n        }\n\n        return true;\n      }).apply(this, arguments);",[".new-email",{}],28000,67]}] Document was unloaded Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z' System info: host: '40de4d2b8a2a', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144' Driver info: driver.version: unknown   at Command.<anonymous>  <tests/functional/lib/helpers.js:96:8>   at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>   at Command.parent.then.then.then  <tests/functional/lib/helpers.js:135:14>   at Command.<anonymous>  <tests/functional/lib/helpers.js:132:8>   at Command.<anonymous>  <tests/functional/lib/helpers.js:56:25>   at Test.gated in unverified session open verification new tab [as test]  <tests/functional/settings_secondary_emails.js:102:12> |   | Current failure: |   | #3686 | No changes | 22 Nov 17 08:39 |   | First failure: |   | #3685 | No changes | 21 Nov 17 20:38
  | Current failure: |   | #3686 | No changes | 22 Nov 17 08:39
  | First failure: |   | #3685 | No changes | 21 Nov 17 20:38

cc @vbudhram - not sure what's going on with this one.

**Comment by vbudhram** [comment]
@shane-tomlinson Not sure either, even though error appears to be duplicate selector, there is only one thing with that ID that I am aware of. I added some delays just to see how TC handles it.

**Comment by shane-tomlinson** [comment]
@vbudhram - Looking a bit more closely, I see `Document was unloaded`. Is that the actual error rather than duplicate IDs?

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-content-server/commit/86bdc39a8e5d84b39be1208c9a15042bc27bd660
