### ISSUE TITLE
Many fxa_pref-password events do not have the FxA uid

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5761]
In [Bug 1419552](https://bugzilla.mozilla.org/show_bug.cgi?id=1419552) we noticed that many "fxa_pref - password" events in amplitude, don't see to have the FxA uid set.  Instead they just have the random integer uid allocated by amplitude.  This makes it hard to do e.g. retention analysis using these events.

Do we have the FxA uid handy to include when sending these events over to amplitude?

**Comment by rfk** [comment]
Here's an example of how amplitude is seeing these events - mostly anonymous from users who are browsing directly to preferences, and occasionally tied back to a real uid because they occurred in a flow with over events:

<img width="679" alt="capture" src="https://user-images.githubusercontent.com/34695/33352180-ca78eda6-d4fb-11e7-9a12-7e5d96b1fa8d.PNG">

(the ids there are all anonymized before sending to amplitude, so I figured this was OK to put in a public bug)

**Comment by philbooth** [comment]
Only just saw this sorry. #5762 was a dup of this, should be fixed in train 101.
