### ISSUE TITLE
Reset account for Lockbox

### ISSUE THREAD

**Issue by sandysage** [mozilla/fxa-content-server#5776]
If I want to reset my Firefox Account (ie "forgot password"), I'm taken to:

![screenshot-2017-12-6 reset account](https://user-images.githubusercontent.com/850418/33686004-a6a876c2-da90-11e7-900b-e8ff327ff4f2.png)

What, if any, changes can be made to the text:
> When you reset your password, you will lose any Sync data that is not on one of your devices. Learn how Sync works.

To inform users that reset also means losing all saved Lockbox data.

cc @changecourse @devinreams

**Comment by ryanfeeley** [comment]
@sandysage I'm not a fan of this page (though it's my doing) as users often ignore the warning. In the longer term I'd prefer to redesign it but in the short term, which of these options do you prefer if any?

removed "Sync"
> When you reset your password, you will lose any data that is not on one of your devices. Learn how Sync works.

changed "Sync" to "synced"
> When you reset your password, you will lose any synced data that is not on one of your devices. Learn how Sync works.

/cc @rfk

**Comment by sandysage** [comment]
@ryanfeeley My biggest concern with either of these statements is that there is no preservation of Lockbox data upon reset. If there is a password reset, for any reason, a user will not be able to access saved logins in Lockbox. Which means neither of these statements would be true for Lockbox.

Is there an option to display a Lockbox specific sentence, if the user has the Lockbox app authorized with that Firefox Account?

**Comment by ryanfeeley** [comment]
@sandysage Oh yes, the FxA password is used for local Lockbox data too. We’ll need something more specific for sure (at least for users who are using Lockbox). Let me check with the team and figure something out. I think this requires more than a small string change.

**Comment by ryanfeeley** [comment]
@sandysage @rfk I'm thinking about changing the first screen to show something like this, and then following up with a screen that shows the types of data that are in use (e.g. bookmarks, history, lockbox passwords, firefox passwords, etc).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/68213/34180906-4dc1f152-e4de-11e7-9f70-6e1b4d17a0fa.png">

**Comment by pdehaan** [comment]
Yo, @ryanfeeley,

How does that form work? From the "Remember password? Sign in" link, it seems that you're unauthenticated. So my guess is that I could use the above form to enter any random email address and find out what data they have associated with their FxA email, no?

Why not just a list of example data that may be wiped by resetting an account, and then you don't need the new page w/ types of data. It's less personal and specific, but maybe safer.

**Comment by rfk** [comment]
> So my guess is that I could use the above form to enter any random email address and
> find out what data they have associated with their FxA email

Yeah, we definitely want to avoid leaking information about what services a user is using in an unauthenticated setting.  But maybe...

> following up with a screen that shows the types of data that are in use (e.g. bookmarks,
> history, lockbox passwords, firefox passwords, etc).

If we did this on the screen *after* the user clicks through the email link, then I think that should be OK.  So the flow would look something like:

1. See initial warning text as above, and enter your email to proceed.
2. Receive the reset email, click through the link.
3. See a new screen with details of what data is at risk (or, go straight to (4) if no data is at risk).
4. See the screen to enter a new password, losing the data noted in step (3) above.

In the future, we may be able to add more options at step (3), such as recovery keys from a connected device, or using facebook delegated recovery, etc.  @ryanfeeley does this line up with what you have in mind?

**Comment by ryanfeeley** [comment]
@pdehaan @rfk Well spotted and great recovery!!! I would love to do something like this that also avoids leaking the kind of data users are syncing. My first attempt did not factor this in, but this is what crit is for.

I will take another pass at this today.

**Comment by vladikoff** [comment]
from mtg: @ryanfeeley is working on this...

**Comment by ryanfeeley** [comment]
Work in progress: https://www.lucidchart.com/invitations/accept/7840053b-61cf-4c9a-b589-bc6d388a246e

**Comment by vladikoff** [comment]
@ryanfeeley has the design done, will add it here so we can start working on it

**Comment by ryanfeeley** [comment]
Final proposed copy (last row, first page only) with small design changes: https://www.lucidchart.com/documents/view/eed48806-9d4c-48ea-b333-778ebdf840e1

**Comment by ryanfeeley** [comment]
<img alt="Dynamic Image from LucidChart" src="https://www.lucidchart.com/publicSegments/view/54215f4f-6f54-4918-b245-9d17a8c482d1/image.png">
