### ISSUE TITLE
Verification password on signup A/B test - :thumbsup: or :thumbsdown:?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5777]
The analysis sent out a couple of months ago indicated verification password was causing a negative impact on signup, but having a positive impact on password reset rate, and overall, though overall the retention rate was slightly lower.

Are we going to continue with this experiment, graduate it to "fully released", or rip it out?

**Comment by rfk** [comment]
The variant with improved UX does appear to be performing slightly better than the initial variant, at least in my amateur analysis here:

  https://projects.growthhackers.com/u/orgs/mozilla-corporation/projects/FAAS/cards/FAAS-87

I'd like to leave it deployed for a few more weeks to see what the 4-week retention is for the new version.  It may turn out to be a win for retention after a few weeks.

**Comment by vladikoff** [comment]
from mtg: blocked on weeks

**Comment by vladikoff** [comment]
from mtg: @rfk has a dashboard, redshift exploded, waiting for it to recover.

**Comment by vladikoff** [comment]
from mtg: `Verification password ` is a go!
