### ISSUE TITLE
Email-first events not sent to Amplitude

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#5788]
Noticed this while trying to create a funnel for the email-first on first-run experiment.

**Comment by vladikoff** [comment]
@philbooth @shane-tomlinson could you take a look at this one before end of week? (or do we retag this from train-103?)

**Comment by vladikoff** [comment]
@juliemccracken says @philbooth is on PTO, we will need to figure this out without him

cc @rfk
