### ISSUE TITLE
Link to FxA documentation from the sign-in/sign-up views?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5790]
In a similar spirit to the principle of putting documentation as close as possible to the thing it documents, I wonder if we should link to amazing new docs that we're going to write on the sign-in and sign-up forms. Just a little link underneath all the main content, which interested parties can follow to find out more about our security/encryption story.

What do you guys reckon?

**Comment by rfk** [comment]
I'm a tentative +1 to exploring this, if we can do it in an appropriately unobtrusive way.  It might be a nice way to get more techincally-minded folks out into our docs to hear about our "story" of why FxA is different.  My only concern would be whether it adds any significant maintenance or testing burden that outweighs the value there.

**Comment by vladikoff** [comment]
Please reopen if we are going to have future priority for this.
