### ISSUE TITLE
CSP in NoScript may be causing "unexpected error" when logging in

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#5806]
A friend of mine reported this while trying to log into Firefox Sync. He has NoScript installed:

> The error, from the Console, appears to be a XSS blocking (from NoScript) between mozilla.net and firefox.com:
>
>`"ContentSecurity Policy: The page’s settings blocked the loading of a resource at blob:https://accounts.firefox.com/8f420321-dc97-4333-b82c-b35a394e6c57 (“script-src https://accounts.firefox.com https://accounts-static.cdn.mozilla.net”)."`

> Once I fully disable the Add-On (No Script swallows the request silently), my Sync is successful.

He got an "Unexpected error" (I redacted the email address): 

![unexpected](https://user-images.githubusercontent.com/2365255/34545719-9c0833be-f0a3-11e7-969f-58598b0010f3.png)

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/34590983-39a8d4e0-f188-11e7-9449-f35da7f96211.png)


Cannot reproduce this particular issue:

- Via `about:accounts`(Firefox UI sync login) and latest NoScript there are no issues. I'm guessing NoScript is ignored when about:accounts is used.
- Via Web you have to Trust or Temp Trust `firefox.com` and `accounts.firefox.com` and then it will work. If it's not trusted then the page will just spin.

If anyone else has issues with this please comment below

**Comment by vladikoff** [comment]
See above. If anyone else has this problem please let us know...
