### ISSUE TITLE
Create custom `Why is this happening` site for token code experiement

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5830]
Ref https://github.com/mozilla/fxa-content-server/pull/5706#discussion_r161091543

**Comment by vladikoff** [comment]
If it is any easier we can just add a new section to the page we already have

**Comment by vbudhram** [comment]
Contacted SUMO team to update https://support.mozilla.org/en-US/kb/accounts-blocked page to state that `Report sign-in` link is optional (sign-in codes have them but token codes do not). If no report link, then user should change their password.

**Comment by vbudhram** [comment]
SUMO has updated this page to reflect that `Report link` is optional.
