### ISSUE TITLE
Functional test "open directly to /signup page, refresh on the /signup page" is failing on master

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5836]
~~Seems to be failing because it's in the email-first flow, when the test expects to be on `/signup`.~~

Error:

```
× firefox on linux 3.13.0-139-generic - Firefox Desktop Sync v3 email first - open directly to /signup page, refresh on the /signup page (23.161s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/a67a6c55-3ccf-4dba-abff-fa6539e3bb58/element / {"using":"css selector","value":"#fxa-signup-password-header"}] Unable to locate element: #fxa-signup-password-header
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-139-generic', java.version: '1.8.0_102'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:152:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:53:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:163:12>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:160:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:53:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:190:12>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:187:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:53:23>
      at Test.open directly to /signup page, refresh on the /signup page [as test]  <tests/functional/sync_v3_email_first.js:57:10>
      at <src/lib/Test.ts:260:47>
```

Screenshot:

![Screenshot showing the FxA email-first login flow and an "unexpected error" message](https://screencap.co.uk/images/d61396aa9e34101d3437d7e503afc407182b3f93.png)

**Comment by philbooth** [comment]
Doesn't fail for me locally I notice. Could it be config related?

**Comment by philbooth** [comment]
> Seems to be failing because it's in the email-first flow, when the test expects to be on `/signup`.

Wait, that's wrong sorry.

Looking at the test, it is supposed to be in the email-first flow. It's failing because the "unexpected error" stopped it from moving on to the next screen.

**Comment by turtleloveshoes** [comment]
Hi there, there are about 6 found open user cases in the forums reported to me by a contributor.
https://support.mozilla.org/en-US/questions/1200235
https://support.mozilla.org/en-US/questions/1200237
https://support.mozilla.org/en-US/questions/1200238
https://support.mozilla.org/en-US/questions/1200235
https://support.mozilla.org/en-US/questions/1200237
https://support.mozilla.org/en-US/questions/1200238

Is there a work around, do they remove the account and then try to log in again?

**Comment by philbooth** [comment]
> Hi there, there are about 6 found open user cases in the forums reported to me by a contributor.
> https://support.mozilla.org/en-US/questions/1200235
> https://support.mozilla.org/en-US/questions/1200237
> https://support.mozilla.org/en-US/questions/1200238
> https://support.mozilla.org/en-US/questions/1200235
> https://support.mozilla.org/en-US/questions/1200237
> https://support.mozilla.org/en-US/questions/1200238
>
> Is there a work around, do they remove the account and then try to log in again? 

@turtleloveshoes, also replied in IRC, but there was a temporary outage last night caused by one of the back-end Sync servers failing. In each of the above cases, if the user retries stuff should work for them now.

**Comment by turtleloveshoes** [comment]
Thank you!!

**Comment by turtleloveshoes** [comment]
Also for the record - the previous post was repeated - 
https://support.mozilla.org/en-US/questions/1200234
https://support.mozilla.org/en-US/questions/1200229
https://support.mozilla.org/en-US/questions/1199655

**Comment by philbooth** [comment]
So, returning to the test failure from the first comment, I can reproduce it locally if I replicate the command that is failing in CI and run against the `dev.lcip` servers:

```
node tests/intern.js --suites=circle --fxaAuthRoot=https://fxaci.dev.lcip.org/auth --fxaEmailRoot=http://restmail.net --fxaOauthApp=https://oauth-fxaci.dev.lcip.org --fxaUntrustedOauthApp=https://321done-fxaci.dev.lcip.org --fxaProduction=true
```

And actually, if you remove the `--bailAfterFirstFailure=true` switch you can see that it's not just limited to one failing test, the vast majority of them fail. Not sure if one of those servers is down or busted, digging into it some more now...

**Comment by philbooth** [comment]
From triage: @jrgm is on the case!

**Comment by philbooth** [comment]
This should be working now.

**Comment by philbooth** [comment]
Functional tests are indeed passing now: https://circleci.com/gh/mozilla/fxa-content-server/9200
