### ISSUE TITLE
No UI feedback when re-sending secondary email verification

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5838]
STR:

* Add a secondary email to your account, but don't verify it.
* Click on the "Not in inbox or spam folder? Resend" link here:

![capture](https://user-images.githubusercontent.com/34695/35134646-e02ff1c8-fd2b-11e7-81a8-15aa5fba526b.PNG)

Actual results:

* Nothing appears to happen, I've no idea whether it worked or not.
* But it did actually work, because the email showed up in my inbox.

Expected results:

* Some sort of visual indication that the click was accepted and acted on.
* I think other instances of this link disappear and fade back in, or something like that?

/cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@rfk I think it's appearing out of view. This issue was designed to resolve that. Can we prioritize it higher? https://github.com/mozilla/fxa-content-server/issues/5552

**Comment by rfk** [comment]
>  Can we prioritize it higher?

If you want to nominate it for Crouton2, please do :-)

I'm going to close this in favour of #5552
