### ISSUE TITLE
Add sign-in link treatment to tokenCode experiment

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5843]
In my haste, I didn't realize that there were two treatment groups in this experiment per https://docs.google.com/document/d/1xQtCGBJ9XZuF1q9faZV3YIiOnxomQMHKiTP62YSf3v8/edit.

We should add the `treatment1` (sign-in link treatment) and corresponding tests. Ideally, would like to target a 104 point release for this.

**Comment by rfk** [comment]
> We should add the treatment1 (sign-in link treatment) and corresponding tests

Does anything prevent us from giving these more easily-digestible names, like `treament-link` and `treament-code`?  Otherwise analysis will be a continuous process of trying to remember which treatment group is which :-)

**Comment by vbudhram** [comment]
> Does anything prevent us from giving these more easily-digestible names

Nope, these can be changed easily! Will update.
