### ISSUE TITLE
 npm run start-remote error

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/fxa-content-server#5850]
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir

**Comment by vbudhram** [comment]
@anweshknayak Which version of node are you using?

**Comment by anweshknayak** [comment]
v6.9.2
@vbudhram

**Comment by vbudhram** [comment]
@anweshknayak Thanks, will close!

**Comment by anweshknayak** [comment]
@vbudhram whats the fix for this? How am I supposed to test the changes from here? Changes will reflect in fxa-local-dev?

**Comment by vbudhram** [comment]
@anweshknayak I misunderstood your comment and thought it was fixed. There are a couple of ways to get started working on issues in this repo.

First way is clone fxa-content-server and use `npm install` and then `npm run start-remote`.

Another way is to clone fxa-local-dev, use `npm install` and then run `./pm2 start servers.json`. Upon install, fxa-local-dev creates a sub directory for fxa-content-server that you can edit and test with.

When in doubt, you can try deleting your old fxa-content-server and install from the first method.

Let me know if this helps!

**Comment by anweshknayak** [comment]
@vbudhram thanks. Its working
