### ISSUE TITLE
Remove green success messages from CAD permalinks

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5852]
Parts of Nightly now hard link to our CAD page when users try to access a Sync feature that requires another device (like sending a tab).

Discussed in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1418466).

For URLs [like this](https://accounts.firefox.com/connect_another_device?service=sync&context=fx_desktop_v3&entrypoint=sendtab) we don't need to show the **This Firefox is connected** message.

## Current
<img width="477" alt="image" src="https://user-images.githubusercontent.com/68213/35365969-0cc00ee0-0145-11e8-8f81-c3c576bd6411.png">

## Proposed
<img width="474" alt="image" src="https://user-images.githubusercontent.com/68213/35365993-2223c970-0145-11e8-9c85-36e18c66ebc1.png">

**Comment by mhammond** [comment]
Note that in bug 1432277, we are proposing to add a link to this page before the user has connected to sync on *this* device (ie, in about:preferences#sync when we aren't configured, you will find links to download Android and iOS - we are going to replace those links with a link to this page).

The wording proposed above doesn't seem ideal for this scenario.

**Comment by ryanfeeley** [comment]
@mhammond Oops, sorry, I clarified in the bug. I was only referring to users who are signed in. No changes for users who are not signed in, or not yet verified. Now time to return to some relevant evening reading.
<img width="248" alt="screenshot 2017-10-31 12 32 20" src="https://user-images.githubusercontent.com/68213/35367782-32a94dde-014e-11e8-9350-a817c99ebcb9.png">

**Comment by vbudhram** [comment]
@ryanfeeley What is the priority for this?

**Comment by ryanfeeley** [comment]
@vbudhram High as it will be needed for 59.

**Comment by vladikoff** [comment]
it works ! 

![image](https://user-images.githubusercontent.com/128755/35926970-8814f9ae-0bf7-11e8-83ec-b22ef45412ba.png)
