### ISSUE TITLE
Login Confirmation Message on iOS is Inaccurate.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5855]
Steps to reproduce:
- Sign in on Firefox on iOS
- Open link to confirm email in Firefox on iOS
- Page opened says: 
"This Firefox is connected

Open setting and select sign in to Firefox to complete set-up"

![login-confirmation-ios](https://user-images.githubusercontent.com/19537086/35453952-d9a94110-0280-11e8-98ac-4df804f68f82.png)

@ryanfeeley recommendations for content here would be good

**Comment by rfk** [comment]
IIUC this is the same as https://github.com/mozilla/fxa-content-server/issues/5858, so I'm closing it in favour of that bug which has a proposal for new UI.
