### ISSUE TITLE
Add lock icon in front of SMS phone field

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5856]
Per discussions in Sync Fest, let's add a small lock in front of SMS field in CAD since rfeeley and I both have proof from past tests that it increases confidence and conversion.

**Comment by davismtl** [comment]
CC @ryanfeeley

**Comment by rfk** [comment]
> proof from past tests that it increases confidence and conversion

I believe you, but...what exactly is the lock supposed to indicate?  Can we make it e.g. link to a description of how we securely handle your details?

**Comment by ryanfeeley** [comment]
Related, go to 17:00 in this video to learn about **Peak Padlocks Per Page**. https://air.mozilla.org/privacy-for-normal-people/

**Comment by ryanfeeley** [comment]
Three options (although I'm reusing the browser’s padlock icon, not part of Photon)

# Padlock Button
![padlock-button](https://user-images.githubusercontent.com/68213/35530978-ad5d8690-0503-11e8-82c5-c1fa681aac04.png)

# Small Padlock Placeholder
![small-padlock-left](https://user-images.githubusercontent.com/68213/35530979-ad6e0b0a-0503-11e8-9d4c-cc179200aa8b.png)

# Large Padlock Placeholder
![large-padlock-left](https://user-images.githubusercontent.com/68213/35530977-ad33ab36-0503-11e8-800a-0e27311e9cd5.png)

**Comment by davismtl** [comment]
> what exactly is the lock supposed to indicate?

A mouse over might just say that we do not store the phone number for other use.

**Comment by vladikoff** [comment]
from mtg: backlog, @ryanfeeley and @davismtl do you want this in `next`?

**Comment by davismtl** [comment]
I can't speak for @ryanfeeley but this is not a huge priority for me at the moment. 

I think there is more value in working on something like this since since we know the extra password field that we released causes some drop-off in registration:
https://github.com/mozilla/fxa-content-server/issues/5857

**Comment by ryanfeeley** [comment]
@vladikoff The lock is now official Photon https://design.firefox.com/icons/viewer/#lock
