### ISSUE TITLE
Inline Email and password validation

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5857]
During Sync Fest we observed that during registration we only validate the email format and that the 2 password fields match on form submit.

This causes the browser to offer saving a potentially wrong email or password.

The user then needs to make the changes and submit again.

Let's do validation on blur so that users can fix problems immediately.

I don't think it's necessary to A/B test this but if we prefer to then we can create a lightweight feature doc.

**Comment by davismtl** [comment]
CC @ryanfeeley

**Comment by MynahMarie** [comment]
@vladikoff Can I work on this as part of my Outreachy contribution?

**Comment by vladikoff** [comment]
@MynahMarie this bug is a bit complex. Here's a simpler one to get started first: https://github.com/mozilla/fxa-content-server/issues/5354#issuecomment-373058970

**Comment by hritvi** [comment]
Hey, @davismtl @vladikoff. Can I work on this issue? Thanks!

**Comment by davismtl** [comment]
To provide additional clarification to the last comment, @vladikoff I am not opposed to resolving this issue before getting NIST style password validation. The basic functionality requested in this bug is a basic we should do which will most certainly help registration and login rates.

**Comment by shane-tomlinson** [comment]
With the password strength experiment, we do inline validation of the password. Closing. If we want to do email at a later date, let's open a new bug.
