### ISSUE TITLE
Notification in Communication Preferences not aligned properly

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/fxa-content-server#5860]
![screenshot from 2018-01-29 14 21 25](https://user-images.githubusercontent.com/8139783/35501852-247a8780-0501-11e8-9316-47adfb15233c.png)

**Comment by anweshknayak** [comment]
@ryanfeeley @vbudhram should I send a PR ?

**Comment by vladikoff** [comment]
Yes please!
