### ISSUE TITLE
TOTP Setup flow initial UX

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5863]
To help with planning here are the initial requirements for this flow. Based on [doc](https://docs.google.com/document/d/1m4D_7DZAfXt4e-bEbfI-5s_x2XFO7TEQo1a_SQcj1O8/edit#heading=h.yzz637baqr7a).

- There is a new "settings" page section or sub-screen, where users can opt-in to using TOTP as a second factor for authentication on their account.
- The MFA settings are not visible by default. 
- The MFA settings are visible to users who specify a feature-flag in the URL 
- The MFA settings are visible to users who have opted-in to MFA on their account (optional)
- Users who visit the MFA settings page can enroll a TOTP device or app (e.g. Google Authenticator) by scanning a QR code.
- After enrollment, the user is presented with backup codes to store in case they lose their MFA device. 
- After enrollment, the user must submit a TOTP code to verify correct setup. 

This version will contain rough user interfaces based on this [doc](https://www.lucidchart.com/documents/view/833ea3ae-65bc-4b0a-94cb-3290ec27ae85). These requirements and designs may change based on user and security reviews.

**Comment by vladikoff** [comment]
@ryanfeeley for train-106

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/5962
