### ISSUE TITLE
TOTP Sign-in flow initial UX

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5864]
To help with planning here are the initial requirements for this flow. Based on [doc](https://docs.google.com/document/d/1m4D_7DZAfXt4e-bEbfI-5s_x2XFO7TEQo1a_SQcj1O8/edit#heading=h.yzz637baqr7a).

- When signing in, after correctly entering their password, users with a TOTP enrollment will be prompted to enter a TOTP code to complete the login flow.
- If signing in to sync, the TOTP code must be entered before they can fetch key material. 
- If signing in to an OAuth relier, the TOTP code must be entered before any authorization code is generated. 
- Users with a TOTP enrollment cannot use an email confirmation loop to bypass entering the TOTP code.
- If a user has a TOTP enrollment, and their login attempt is blocked due to rate-limiting or other security measures, they may be prompted for a sign-in unblock code sent via email.

This version will contain rough user interfaces based on this [doc](https://www.lucidchart.com/documents/view/833ea3ae-65bc-4b0a-94cb-3290ec27ae85). These requirements and designs may change based on user and security reviews.

**Comment by vladikoff** [comment]
@ryanfeeley for train-106

**Comment by vbudhram** [comment]
Fixed in #5962
