### ISSUE TITLE
TOTP SUMO Support link

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5866]
As part of supporting TOTP, we need to create a SUMO link for users.

Ref: https://docs.google.com/document/d/1m4D_7DZAfXt4e-bEbfI-5s_x2XFO7TEQo1a_SQcj1O8/edit#

**Comment by vladikoff** [comment]
from mtg: SUMO is working on it

**Comment by shane-tomlinson** [comment]
@vbudhram to open bugzilla bug.

**Comment by vbudhram** [comment]
This has been fixed!
