### ISSUE TITLE
Missing or duplicate items on iOS link escaped

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa-content-server#5869]
On iOS, clicked on Firefox Account and went to the Firefox Accounts page.
Clicked on Devices & Apps and scrolled to the bottom.
Note that the "Missing or duplicate items" link isn't clickable:

![img_0601](https://user-images.githubusercontent.com/74699/35651806-d728183a-0695-11e8-994c-203a0b831def.jpg)

**Comment by rfk** [comment]
This is, unfortunately, on purpose.  We can't open external links in the special embedded web view that iOS uses to display the FxA settings, so they get rendered into this non-clickable form.  I don't recall if we had a plan for improving this situation.

**Comment by andymckay** [comment]
Ah thanks for the explanation. I see similar links in terms of service and the privacy notice. Could we set up a shorter URL at least?

**Comment by vladikoff** [comment]
Yes we can use http://mzl.la/1VFtdM1 instead for this article

**Comment by vladikoff** [comment]
3 draft solutions:

* Fix iOS browser to support this
* Ask SUMO for a short link with UTM params (always use)
* For iOS use short links with no utm params (only use in iOS)

**Comment by andymckay** [comment]
Fixing iOS to support this would be the best. In the meantime, this URL maintains params "mzl.la/ios-missing":

[DESKTOP-GF9I56E:~]$ curl -ILs mzl.la/ios-missing | grep Location
Location: https://support.mozilla.org/kb/fxa-managing-devices?utm_source=accounts.firefox.com&utm_medium=referral&utm_campaign=fxa-devices
Location: https://support.mozilla.org/en-US/kb/fxa-managing-devices?utm_source=accounts.firefox.com&utm_medium=referral&utm_campaign=fxa-devices

**Comment by vladikoff** [comment]
@andymckay oh cool! 

> mzl.la/ios-missing

is there a way to remove `ios` from that? so we can reuse this in the future? something like `mzl.la/fxa-missing":` ?

**Comment by andymckay** [comment]
I can't get bit.ly to keep the mzl.la once I customise it, do we care if its bit.ly, vs mzl.la? If not https://bit.ly/fxa-missing works.

**Comment by vladikoff** [comment]
> do we care if its bit.ly, vs mzl.la?

I think in the past we wanted to make sure we use mzl.la (for sms at least)

> once I customise it

@andymckay does it create a random `mzl.la/[random_chars]` ? that could possibly be better than a bit.ly custom url

**Comment by vladikoff** [comment]
🗡
