### ISSUE TITLE
Change copy on newsletter section in Settings

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5873]
Currently our newsletter copy is:

> We may send you emails related to your Firefox Account.
> 
> Additionally, you can choose whether to receive the latest news about Mozilla and Firefox. 

Change it to:

> You will receive communications relating to your account security, changes to our policy, your account’s functionality and initial emails to help you get the most from your Firefox Account. 
> 
> Additionally, you can subscribe to receive promotional emails with the latest news from Mozilla and Firefox.

Note that marketing is looking to split "account functionality and onboarding" emails from "security and policy".

This change is just an intermediary step. @bniolet1 will coordinate with our team to add an onboarding opt-out option here in the settings. (security and policy need to remain obligatory)

**Comment by davismtl** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Original copy in context:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/68213/35833640-0608a36e-0aa0-11e8-8241-e4df499c3136.png">

**Comment by vladikoff** [comment]
@ryanfeeley to confirm
