### ISSUE TITLE
Firefox icon overlaps info notification on iOS

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5879]
On Firefox iOS Beta they are introducing Choose What to Sync options. The Firefox logo overlaps the email created notification.

![img_0875](https://user-images.githubusercontent.com/1295288/35740851-21cd26cc-0804-11e8-950e-9af121947405.PNG)

**Comment by vladikoff** [comment]
this will be released EOM, nexting...

**Comment by vladikoff** [comment]
I saw some screenshots and the CWTS should **not** have the firefox logo, we hide it for that screen
