### ISSUE TITLE
Disable the Done button in unverified secondary email section

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5897]
As the user cannot collapse the section until the state of the unverified secondary email has changed, they should not be able to press the Done button (and definitely not get a blue mousedown effect)

![done](https://user-images.githubusercontent.com/68213/36031629-5eaa0342-0d79-11e8-8488-14c6ae76856c.gif)

**Comment by hritvi** [comment]
Hello, @vladikoff I would like to work on this issue.

**Comment by vladikoff** [comment]
@hritvi sure!

@vbudhram got any pointers for @hritvi ?

**Comment by vbudhram** [comment]
@hritvi Thanks for taking this up, from the issue it seems that we should apply the `disable` class to the Done button.

You should be able to apply it the template located [here](https://github.com/mozilla/fxa-content-server/blob/bdb690bd6d9534565fd96c644da950f8c2ba934b/app/scripts/templates/settings/emails.mustache#L78). Doing this, we can also remove the `secondary-disable` class.

**Comment by DGRamya** [comment]
Hello @vladikoff , Is this issue still open for solving? Can I work on this?

**Comment by vbudhram** [comment]
Hey @DGRamya sorry but this issue is fixed, feel free to check out others!
