### ISSUE TITLE
Sink placeholder back into field when emptied

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5900]
STEPS TO REPRODUCE
1. Add content to any account form field that has a placeholder and watch the placeholder float above
2. Delete the content in the field

EXPECTED RESULTS
* Placeholder sinks back into place

ACTUAL RESULTS
* Placeholder stays above in small type

<img width="452" alt="_new_password__should_be_placeholder_text_1024" src="https://user-images.githubusercontent.com/68213/36104466-21169388-0fe0-11e8-8ae8-ad49401cfe13.png">

**Comment by mtrivera** [comment]
I would like to work on this issue.

**Comment by vladikoff** [comment]
Sure @mtrivera!

**Comment by mtrivera** [comment]
I'm thinking functional tests would be good here with some TDD tests. Would I append my code to existing test files or create my own?

**Comment by vladikoff** [comment]
@mtrivera There are some placeholder unit tests already that you can you :+1:

**Comment by vladikoff** [comment]
@mtrivera There are some placeholder unit tests already that you can use :+1:

**Comment by shane-tomlinson** [comment]
Floating placeholders are out with the Photon redesign, closing.
