### ISSUE TITLE
Consider using cache immutable

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa-content-server#5914]
With Firefox 49 we shipped Cache-Control: Immutable which stops the browser re-validating CSS and JS and getting 304's back. Assuming that our js and css is in fact immutable, this might be a simple and slight perf win.

https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/

**Comment by jrgm** [comment]
Yeah, being able to be more explicit about immutable urls is better, and we should add this to our cache-control headers.

Yet, `max-age` used to mean what I read https://tools.ietf.org/html/rfc7234#section-4.2 to mean, and browsers in the recent past didn't IMS recent requests below that time.

But ¯\_(ツ)_/¯

**Comment by vladikoff** [comment]
Closing for now, let's revisit this if still needed later....
