### ISSUE TITLE
Enabled token code sync experiment for 1.8% of users

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5919]
After speaking with lief, we landed on exposing 1.8% of users to each group (treatment-link, treatment-code, control) in the sync token code experiment. This experiment will need to run for 2 weeks to give a statistically significant result and take into account any weekly login patterns.

This experiment should be available in train 106 and be enabled as a point release.

cc @rfk @davismtl

**Comment by davismtl** [comment]
Remember to set a clear control in experiments

**Comment by vladikoff** [comment]
from mtg: point release for 106

**Comment by rfk** [comment]
from mtg: 1.8% per cohort

**Comment by vbudhram** [comment]
This has been merged!
