### ISSUE TITLE
Auto-filled password in 'create account' and 'sign-in' dialogs does not light up 'Submit' button

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-server#593]
If the password is auto-filled in either the create account or sign in dialogs, a user action (clicking 'show' or adding and deleting a space, for example) is required before the 'Submit' button is enabled.

**Comment by kumar303** [comment]
This is happening for me as well using Firefox's built-in password manager

**Comment by shane-tomlinson** [comment]
ref #2450
