### ISSUE TITLE
Add pushbox URL(s) to the fxa-client-configuration document

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5931]
As part of the [new send-tab system](https://docs.google.com/document/d/1YT6gh125Tu03eM42Vb_LKjvgxc4qrGGZsty1_ajf2YM/edit#heading=h.mt5o69jf1o39), client devices need to be able to discover the URL of the new "pushbox" service that helps them send and receive large, durable message payloads.

Let's add the URL of this service to the fax-client-configuration document so that they can discover it alongside other sync-related service URLs.  We should also keep an eye out for other related URLs that it might be profitable to expose there, e.g. the URL of the push servers.

**Comment by vladikoff** [comment]
@eoger let us know if you still need this and we will reopen!
