### ISSUE TITLE
Remember password has no apparent link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#5932]
Oddly when I hover our new **Remember password** link on latest, there is no apparent link. It's a button? Can we make it a link instead?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/68213/36678733-8600d5c4-1adf-11e8-8382-476af865223c.png">

**Comment by vladikoff** [comment]
from mtg with @ryanfeeley: there are reasons it's that way due to force_auth and signin

**Comment by ryanfeeley** [comment]
👍
