### ISSUE TITLE
Disable 'clear' for default avatar

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5935]
Screen: 

![image](https://user-images.githubusercontent.com/128755/36736235-1a7abdd4-1ba6-11e8-8696-03b25ac83565.png)

**Comment by vladikoff** [comment]
This doesn't throw anymore, but we can detect `avatarDefault` and not show `clear` as an enhancement

**Comment by hritvi** [comment]
Hey @vladikoff . Can i challenge myself with this issue? Thanks!

**Comment by vladikoff** [comment]
@hritvi yeap, https://github.com/mozilla/fxa-content-server/blob/master/README.md#quick-start Find how `avatarDefault`. is used in the code and use it for the avatar change view

**Comment by akshitac8** [comment]
Hey @vladikoff Is this bug up for solving?

**Comment by vladikoff** [comment]
@akshitac8 Yeap! See https://github.com/mozilla/fxa-content-server#quick-start for steps to get started. 

We have a template the uses `avatarDefault` https://github.com/mozilla/fxa-content-server/blob/24eddb8a28e6d4b366c82df5738e97a1d3b3e7ea/app/scripts/templates/settings/avatar.mustache#L6

Template variable gets the value from https://github.com/mozilla/fxa-content-server/blob/24eddb8a28e6d4b366c82df5738e97a1d3b3e7ea/app/scripts/views/settings/avatar.js#L31

We need to change `hasProfileImage` (https://github.com/mozilla/fxa-content-server/blob/24eddb8a28e6d4b366c82df5738e97a1d3b3e7ea/app/scripts/templates/settings/avatar_change.mustache#L17 ) to use `avatarDefault` instead. Need to hide the clear button in the template if `avatarDefault` is "true"

**Comment by akshitac8** [comment]
@vladikoff  ohkay, I will start working on this and thank you for assigning the issue. 
will I to need to install java environment for tackling this issue?

**Comment by vladikoff** [comment]
> will I to need to install java environment for tackling this issue?

Nope

**Comment by vladikoff** [comment]
@akshitac8 However you need to make sure you can start the server, register and get to http://127.0.0.1:3030/settings to work with avatar template files

**Comment by akshitac8** [comment]
Ohkay, I will give it a try and comment back for further doubts.
Thank you:)

**Comment by DGRamya** [comment]
@vladikoff, hey. I started working on this issue, I did the pre-requisite setup for fxa-content server and then executed "npm run start-remote". But I am getting the below error:

`Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/home/ramya/work_space/fxa-content-server/node_modules/grunt-sass/node_modules/node-sass/vendor'
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/home/ramya/work_space/fxa-content-server/node_modules/grunt-sass/node_modules/node-sass/vendor'
Loading "l10n-generate-pages.js" tasks...ERROR
>> SyntaxError: Unexpected token =
Loading "l10n-generate-pages.js" tasks...ERROR
>> SyntaxError: Unexpected token =
Warning: Task "sass" not found. Use --force to continue.`

I tried installing

**Comment by DGRamya** [comment]
Resolved  it. Please ignore the previous comment.

**Comment by DGRamya** [comment]
@vladikoff  
I am working on the ticket and to set the development environment, I have cloned the fxa-content-server repo and running 'sudo npm run start-remote' after 'npm install'. The application is starting on the local server but upon opening in browser it is throwing  following error
'GET http://127.0.0.1:3030/i18n/client.json 404 (Not Found)'

**Comment by DGRamya** [comment]
@vladikoff 
I have fixed the issue and raised PR. Please review
