### ISSUE TITLE
Option to `change` or `add` avatar for new account in settings?

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#5936]
This is just a general question about the default avatar settings. When logging in with a newly created account, the settings panel says `Change` with gray button. This is different from the `Add` with blue button that I was expecting.

Is this intended? Seemed strange that I never added one to be given the option to change it.

Ref: https://github.com/mozilla/fxa-profile-server/issues/295

**Comment by vladikoff** [comment]
Yeah I think we are gonna need to add a field fo the API signaling that the provided avatar is default 

would be also useful for https://github.com/mozilla/fxa-content-server/issues/5935

**Comment by vladikoff** [comment]
This should be fixed now
