### ISSUE TITLE
Merge warning with email first

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#5949]
With email first, we now give the merge warning after entering just the email.

This might be a good thing, but maybe it's a bad thing. I'd like us to think about what it should be doing rather than what it is doing all of a sudden since changing to the email first flow.

<img width="1270" alt="screen shot 2018-03-05 at 9 02 16 am" src="https://user-images.githubusercontent.com/19537086/36989237-ffdb3e0e-2055-11e8-9b6b-a5716187d4a9.png">

**Comment by ryanfeeley** [comment]
@davismtl It's a good thing, and I'm glad you caught it. I use fresh profiles too often and wouldn't see this.

On second look, I bet we could get better copy on this.

**Comment by davismtl** [comment]
Agreed on copy. @ryanfeeley Can you look into that for us?

**Comment by ryanfeeley** [comment]
@davismtl Filed a request. https://trello.com/c/S8ipDa1x/68-improve-our-sync-merge-warning

**Comment by vladikoff** [comment]
from mtg: desktop issue
