### ISSUE TITLE
train-107: revert disabling of avatar test? 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#5963]
Following up on https://bugzilla.mozilla.org/show_bug.cgi?id=1443961#c3, https://github.com/mozilla/fxa-content-server/commit/f5fb6657c253da9ca4baac829edadf8fe4cf68f3 was to workaround the fxaci/train-106 test expectations, right? Should be reverted, right?

/cc @vbudhram, @vladikoff

**Comment by vladikoff** [comment]
@jrgm that change never made to 107 as far as I see

**Comment by rfk** [comment]
I edited this out when I merged train-106 into train-107; sorry, I should have mentioned that explicitly.

**Comment by rfk** [comment]
(specifically in this merge commit: https://github.com/mozilla/fxa-content-server/commit/8505c345739128d2e4d1aaa7e72de2726be59f2d)

**Comment by vladikoff** [comment]
Closing this then, I think..
