### ISSUE TITLE
Remove `get-metrics-errors.js` endpoint

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#5970]
We stopped sending things there in 2015
![image](https://user-images.githubusercontent.com/128755/37177978-1b31bd5e-22ef-11e8-9123-d0bb17e53b03.png)

**Comment by hritvi** [comment]
Hii @vladikoff ! Can i take this issue? Thanks.

**Comment by vladikoff** [comment]
@hritvi yes please!

**Comment by hritvi** [comment]
I have created the pull request. Please review. Thanks :)
