### ISSUE TITLE
Why do we bother with a changelog?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5977]
I've raised this before in various channels, but a changelog is only worth maintaining if it's a truthful record of changes and versions. Yet it seems like in most releases we perform operations that break the changelog. So -- *deliberately provocative question alert* -- should we just delete the changelog?

I'd rather we kept it and maintained it truthfully, but it stresses me out when it's wrong and annoys me when we have to perform weird merge magic to make it right again.

A case in point: At the time of writing (I have a PR lined up to fix it), [the `train-107` change log](https://github.com/mozilla/fxa-content-server/blob/v1.107.3/CHANGELOG.md) has duplicate sections for 107.1 and 107.0, and is missing the info for 106.6 and 106.7. [The change log in `master`](https://github.com/mozilla/fxa-content-server/blob/498c392686da38117f11df913c9f1acb6d23122c/CHANGELOG.md) is missing releases 106.4, 106.5, 106.6, 106.7, 107.2 and 107.3.

These problems are easy to avoid if we employ a sane merge strategy. I'm about to fix them now by doing the appropriate merges and resolving conflicts as I go, but is it worth the effort if we're only going to re-offend the same way in future trains?

/rant

**Comment by vladikoff** [comment]
I found the changelog really useful, even in the current state of it

> Yet it seems like in most releases we perform operations that break the changelog

However, yeah, if there are steps we can do to make it more truthful I am all for it 👍

**Comment by jrgm** [comment]
+1 to sane merge strategy and keeping changelog

**Comment by philbooth** [comment]
Putting my face on this and pulling it into active as I'm going to document what the process should be, probably here:

https://github.com/mozilla/fxa/tree/master/docs/local-development

**Comment by philbooth** [comment]
Actually, we already have some docs about this here, I think I wrote them last time this came up in retro:

https://github.com/mozilla/fxa/blob/master/docs/dev-process.md#tagging-releases

I'll probably stick with trying to make those better.
