### ISSUE TITLE
Iframe gives "please enable cookies" error when "Accept third-party cookies" is set to "From visited"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5984]
STR:

* In your Firefox preferences, set "Accept third-party cookies" to "From visited"
* Visit https://accounts.firefox.com directly
* Load FxA signin in an iframe, e.g. by visiting https://www.mozilla.org/en-US/firefox/59.0/whatsnew/

Expected results:

* You can see the FxA signin form

Actual results:

* FxA displays its "Cookies and local storage are required" error.

It seems like something's going wrong here, because "From visited" should encompass FxA after we visit it directly.

**Comment by rfk** [comment]
I'm no expert on this code, but digging in a little, it could be that we just don't examined the "visited" status of the site for non-cookie forms of storage:

  https://dxr.mozilla.org/mozilla-central/source/dom/base/nsContentUtils.cpp#9189

Which says:

```
      // XXX For non-cookie forms of storage, we handle BEHAVIOR_LIMIT_FOREIGN by
      // simply rejecting the request to use the storage. In the future, if we
      // change the meaning of BEHAVIOR_LIMIT_FOREIGN to be one which makes sense
      // for non-cookie storage types, this may change.
```

**Comment by april** [comment]
Note that visiting https://accounts-static.cdn.mozilla.net/images/88b55e5a.spinnerlight@2x.png (or any page on accounts-static.cdn.mozilla.net) doesn't seem to fix the problem either.

**Comment by april** [comment]
After discussing this with @dveditz, we agree that Firefox should probably not be behaving this way for localStorage. I'm going to open up a bug for it.

**Comment by vladikoff** [comment]
Waiting for firefox bug..

**Comment by april** [comment]
It's a complicated issue, trying to figure out what the best behavior should be and setup a demo site.

**Comment by vladikoff** [comment]
sounds good!

**Comment by shane-tomlinson** [comment]
@april - Was a bug opened for this? My (honestly pretty poor) Bugzilla foo didn't come up with anything. Now that Fx 60 is released, we are seeing a surge in these errors.

**Comment by april** [comment]
Sorry for taking so long to get back to you! I was at Google I/O and I'm just catching up.

I did file a bug and create a test site to at least get this documented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1462802

Although from my discussions, it seems like this might be a `WONTFIX`.

**Comment by shane-tomlinson** [comment]
Thanks for filing the bugzilla issue @april, the listed STRs are very useful. I'd like to revisit whether we actually *need* localStorage and sessionStorage on the FxA side, it seems like we should be able to provide at least a minimal experience. Unfortunately we won't be able to prioritize this imminently, possibly next quarter at the earliest.
