### ISSUE TITLE
Is the flow.signin_from.fx_ios event wrong?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#5986]
Here:

https://github.com/mozilla/fxa-content-server/blob/3105aa0557204694572a8c3dfd325e119fe1547c/app/scripts/views/connect_another_device.js#L123

That line is in the `! canSignIn` branch. Should the event be `install_from` instead of `signin_from`, like all the other events in that branch?

**Comment by vladikoff** [comment]
This is because if you are ON fx_ios you should just sign_in, not install_from. @shane-tomlinson reopen this if we want to change this
