### ISSUE TITLE
Remove https://secure.gravatar.com from CSP rules?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#5994]
IIUC we no longer support gravatar for profile images, so we should be able to remove https://secure.gravatar.com from  img-src in our CSP rules.

**Comment by vladikoff** [comment]
Yes!

**Comment by DGRamya** [comment]
@vladikoff @rfk 
For the above mentioned issue, I have identified that we should remove or comment "GRAVATAR" from imgSrc .
      imgSrc: addCdnRuleIfRequired([
        SELF,
        DATA,
        // Gravatar support was removed in #4927, but we don't want
        // to break the site for users who already use a Gravatar as
        // their profile image.
        GRAVATAR,
        PROFILE_IMAGES_SERVER
      ]),

Could you please guide how to test this?

**Comment by vladikoff** [comment]
@DGRamya Hey! Yeap so find all mentions of gravatar in server code and delete them

Remove it from this test as well https://github.com/mozilla/fxa-content-server/blob/cd7c3dd2a780d67f38b647e2226a733613c68df8/tests/server/csp.js

You can run `npm run test-server` to make sure it all passes. Then it should be good 👍

**Comment by vladikoff** [comment]
> You can run npm run test-server to make sure it all passes.

**Comment by vladikoff** [comment]
> You can run npm run test-server to make sure it all passes.

For this to work you need to have the server running

**Comment by DGRamya** [comment]
@vladikoff , Thank you, I will continue working.

**Comment by vladikoff** [comment]
This was fixed in https://github.com/mozilla/fxa-content-server/pull/6015
