### ISSUE TITLE
Test needs to be checked, expected 'Web Session, Firefox 40.0'  vs '40'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6001]
AssertionError: expected 'Web Session, Firefox 40.0' to equal 'Web Session, Firefox 40'

Ref: https://github.com/mozilla/fxa-content-server/pull/6000

**Comment by philbooth** [comment]
This means I broke it in mozilla/fxa-auth-server#2356. Will dig into it tomorrow, sorry.

**Comment by vladikoff** [comment]
@philbooth no worries, that feature is still disabled 👜
