### ISSUE TITLE
SMS CAD as a standalone

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6006]
We have this standalone page:
https://accounts.firefox.com/sms?service=sync

Marketing is working on deploying their version of SMS to more markets but it doesn't support deepling and autofill. This feels like a huge waste of resources to duplicate effort.

Questions:
1) Can someone confirm that the above URL does the deeplinking magic from the SMS? I'm under the impression that it does but... I can't replicate because deeplinking never works if you already had the app installed. I can never clear my ID from Adjust.

2) If another team wants to use it, what would be the best way for them to embed it to page? I dare not say iFrame in case we have other ideas.

3) Are there any other reasons that this might be a bad idea?

And finally, I acknowledge that if another team wants to use our SMS, we need to figure out SMS budget with them.

**Comment by vladikoff** [comment]
@vbudhram or does anyone else know ^

**Comment by vladikoff** [comment]
from mtg: "Deep link should work, but saved info won't be there"

**Comment by vladikoff** [comment]
@davismtl could you please put this into one of the tables in Air Table? (if we still plan to do this)

**Comment by davismtl** [comment]
done
