### ISSUE TITLE
Enable email first layout for Oauth Reliers

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6009]
Lockbox would love have the email first flow. It is currently only available for Sync.

Let's enable it as an option for reliers.

**Comment by vladikoff** [comment]
For Q2?

**Comment by vladikoff** [comment]
from mtg: nice to have before the thing ships

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-oauth-server/pull/540
