### ISSUE TITLE
Regenerate recovery codes when all codes are used up

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6018]
From https://github.com/mozilla/fxa-content-server/pull/5992, I wanted to work this in another issue since there might be a several moving parts with it. Main questions I had were

* What happens with an Oauth relier on login?
* What happens with Sync on login?

The [wireframes](https://www.lucidchart.com/documents/view/833ea3ae-65bc-4b0a-94cb-3290ec27ae85/0) does not show where the user is redirected after clicking `Done`. It makes sense to me that it would show the regenerate dialog and then continue the regular login process after clicking `Done`.

@ryanfeeley Does this match what you were thinking?

**Comment by ryanfeeley** [comment]
Oops, my lines were wrong. How is this?
<img width="487" alt="image" src="https://user-images.githubusercontent.com/68213/38264872-55a411be-3742-11e8-8cb8-b74474571e70.png">

**Comment by vbudhram** [comment]
@ryanfeeley This looks good. Only minor thing is that from https://github.com/mozilla/fxa-auth-server/issues/2355, we will send `New sign-in to` emails when logging in from key requesting services (ex. sync).

**Comment by ryanfeeley** [comment]
@vbudhram Slight update…
<img width="292" alt="image" src="https://user-images.githubusercontent.com/68213/38267460-97f3580c-3749-11e8-8735-2186e392ab6c.png">

**Comment by vbudhram** [comment]
While working on https://github.com/mozilla/fxa-auth-server/issues/2409, ISTM that automatically regenerating recovery codes when they run out, may have less significance. User's would have gotten several emails at this point about regenerating their codes (one for each time they used it below the configured minimum). Additionally, I can see this feature having a few edge cases regarding verification that might make it a bit more complicated to implement over https://github.com/mozilla/fxa-auth-server/issues/2409.

I am in favor of backlog/closing until there is a strong case for automatically regenerating them in addition to notifying users when they have low codes.

@rfk Thoughts?

**Comment by vbudhram** [comment]
> but we could also offer to disable TOTP on their account, since it's clearly not working out well for them in practice.

I didn't think about that but it does seem doable.

> What are some of the edge-cases you're worried about?

The edge cases would arise because I was thinking about redirecting to `/settings/` and reusing our recovery codes modal, which might cause problems with oauth and sync sign-in flows . Users can dismiss modal, not save recovery codes or close window at these points and not get into the final service.

Maybe having a custom view specifically for this state would help alleviate some of the edge cases above. I can pitch some updated UX for this.

**Comment by davismtl** [comment]
@vbudhram how's progress here? Should this be moved to train 116?

**Comment by vladikoff** [comment]
for: Crouton III

**Comment by vladikoff** [comment]
from mtg: to be triaged

**Comment by rfk** [comment]
> we could also offer to disable TOTP on their account, since it's clearly not working out well for them in practice.

From discussion, disabling TOTP seems like the safest/best option; @vbudhram is going to propose something concrete on the mailing list.

**Comment by vladikoff** [comment]
from mtg: active!
