### ISSUE TITLE
Replace Show password with 👁 icon

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6023]
Our **Show** password button has a few problems that I think an icon will fix.

PROBLEMS
1. The label "Show" varies in length by language, but the visible area of the password itself does not. This leads to a bad situation where more of the the password is visible in some languages than others. A universal icon will equalize this.
1. "Show" is probably more understood as a way to toggle to visible and no simply peek (on press only)
1. In Internet Explorer an eye icon is used for the behaviour of "peeking" at the password. Likely more familiar to our large Windows user base.

SPECS
* Icon is centred in button space. Button space should match field height (e.g. 43 pixels)
* Visible password area can now be field width minus field height
* Button has a white background unless hovered or press. Eyeball is never shown on top of password.
* SVG icon: [password-show.svg.zip](https://github.com/mozilla/fxa-content-server/files/1880373/password-show.svg.zip)

METRICS
* Would be great to see if more users are making use of this than before, especially in other languages

![eye password](https://user-images.githubusercontent.com/68213/38371971-c1970834-38bb-11e8-9fe4-10f6c5bb9163.png)

child of #6083

**Comment by kawal2266** [comment]
I want to resolve this issue.Can you tell me where I can find this html file for sign in page?

**Comment by kawal2266** [comment]
@ryanfeeley

**Comment by shane-tomlinson** [comment]
@kawal2266 - 

* html - https://github.com/mozilla/fxa-content-server/issues/6023#issuecomment-379161500
* css - https://github.com/mozilla/fxa-content-server/blob/654ce11392709b0dd94d2ca05988347af764da29/app/styles/modules/_password-row.scss#L108

**Comment by kawal2266** [comment]
@ryanfeeley  I was trying to solve this issue...but accidentally I have removed dpkg and some other packages from my OS..and now no other project dependencies can be downloaded.. So I have to install Ubuntu again , but as my exams are approaching I won't be able to do that in coming week.
I will work on another issue once I have the setup.
Sorry for being unable to solve the issue.

**Comment by vladikoff** [comment]
@hritvi Sure! give it a try!

**Comment by vladikoff** [comment]
@hritvi any luck with this?
