### ISSUE TITLE
Layout responds strangely in popup

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6024]
When you resize the FxA pop-up window (from Notes login) it does not respond properly.
<img width="419" alt="screen shot 2018-04-04 at 10 52 43 am" src="https://user-images.githubusercontent.com/68213/38376025-a2d9a64a-38c5-11e8-9c3f-31918cc40c20.png">

**Comment by shane-tomlinson** [comment]
I just tried this with the new layout, it's now A-OK:

<img width="371" alt="screen shot 2018-10-03 at 08 38 07" src="https://user-images.githubusercontent.com/848085/46396638-dbab9400-c6e7-11e8-8233-f9eb68a0f426.png">
