### ISSUE TITLE
Form input validation throws `Uncaught (in promise) undefined`

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6025]
Noticed this while testing https://github.com/mozilla/fxa-content-server/pull/5992. Any input field will throw `Uncaught (in promise) undefined`, if `validateAndSubmit` is fails.

<img width="342" alt="screen shot 2018-04-05 at 4 38 24 pm" src="https://user-images.githubusercontent.com/1295288/38390605-cb9c54ea-38ef-11e8-870d-ffb6f6a9cb4d.png">

Not sure if this is expected behavior, but seemed odd.

**Comment by vladikoff** [comment]
See https://github.com/mozilla/fxa-content-server/issues/6333#issuecomment-402484922

**Comment by sv-ohorvath** [comment]
Verified on Stage: Train 116.
