### ISSUE TITLE
Opt out of experiments when `navigator.webdriver` is set

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#6026]
From https://github.com/mozilla/fxapom/issues/206#issuecomment-378859781, there is a `navigator.webdriver` flag that will be set when a page is being run by automated tests:

  https://w3c.github.io/webdriver/webdriver-spec.html#interface

Can we use this as an additional flag to opt out of experiments in order to provide stable UI for testing?  Similar to what we already do here:

  https://github.com/mozilla/fxa-content-server/blob/d1f878b0d4909ca100d488e1a7d9834803ac95c8/app/scripts/lib/experiment.js#L66

**Comment by vladikoff** [comment]
Sure!
