### ISSUE TITLE
"email first" flow does not check for firefox.com domains

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6027]
Noticed this while looking at #5947.

![screen shot 2018-04-06 at 11 19 50](https://user-images.githubusercontent.com/848085/38416377-0f8ef204-3984-11e8-953f-e4fa8b5d64ed.png)

Compare this to the legacy signup page:

![screen shot 2018-04-06 at 11 20 34](https://user-images.githubusercontent.com/848085/38416415-2924362a-3984-11e8-9277-f28d8d90615e.png)

**Comment by vladikoff** [comment]
blocks #6125
blocks #6527
