### ISSUE TITLE
Remove OLD Firefox favicon

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6030]
Hey @deeptibaghel this might be a good bug to fix and will help you understand how the fxa-content-server server works and tests.

See this file: 
https://github.com/mozilla/fxa-content-server/blob/master/server/lib/routes/get-favicon.js#L3-L20

We don't want to serve `favicon-pre57.ico` to any clients anymore.

And this test file: https://github.com/mozilla/fxa-content-server/commit/46921fbaee7e18f28e7371f28e9129da6f2de5e0#diff-93ac7c95323fbdb8653af1e1dbe2c18c

When the server is running you can run `npm run test-server` to run server tests

**Comment by deeptibaghel** [comment]
Thanks @vladikoff , i am working on the issue :)

**Comment by deeptibaghel** [comment]
Thanks @vladikoff  , i am working on the issue :)
