### ISSUE TITLE
Verify password not focused when switching from sign in to sign up

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6040]
Switching from `unknown account . sign up?` has bad focus behaviour 

<img src=https://user-images.githubusercontent.com/128755/38590539-c243f22c-3cff-11e8-9d4c-0bb178fab11d.gif width=300 />

@shane-tomlinson what should this do? focus `vpassword` first?

**Comment by shane-tomlinson** [comment]
>  what should this do? focus vpassword first?

Yup, if it's not filled in already.

**Comment by farhan787** [comment]
May I fix this ?

**Comment by shane-tomlinson** [comment]
@farhan787 we are in the (slow) process of deprecating this page. I'm going to close this as INVALID.
