### ISSUE TITLE
UX: clarity on "Cancel" vs. "Done"

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6045]
On the Settings page there are a number of actions a user can take. Half of them have a "Done" button, and the other half "Cancel". Cancel makes more sense to me across the board, so I'm wondering if a more uniform button would be preferable?

Done:
account photo
display name
secondary email
devices and apps

Cancel:
communication prefs
password
delete account

**Comment by rbillings** [comment]
Additionally I see the default settings have:
Account picture - Add option has "Done"
Display name - Add option has "Cancel"
Secondary email - Add option has "Cancel"

**Comment by vladikoff** [comment]
@ryanfeeley thoughts? was this by design?

**Comment by ryanfeeley** [comment]
Definitely carefully designed. 

**Cancel** will revert the form to the previous state and close/collapse the section.

**Done** is synonymous with **Close** and does not impact the actions that have taken place however deep inside the section.

**Comment by rbillings** [comment]
Sounds good, thanks for the clarification!
