### ISSUE TITLE
TOTP: Authy & Google Authenticator accept expired codes

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6046]
Testing using: https://accounts.firefox.com/settings?showTwoStepAuthentication=true

1) Enable Two-step authentication
2) Open Google authenticator, scan QR code  [*also repros with Authy]
3) view security code, wait for it to expire
4) after a new confirmation code appears, enter expired code & click "Confirm"

expected: Invalid code error
actual: MFA enabled successfully

Duo did work as expected, and did not accept expired security codes

**Comment by vladikoff** [comment]
How "expired" where the expired codes? see this issue https://github.com/mozilla/fxa-content-server/issues/6005

**Comment by rbillings** [comment]
The timeslice had expired, & a new code had been generated. If it's set to accept the last valid code this is a non-issue. Although Duo did NOT accept the last valid code. 

I'll try 2 or 3 codes in and report back.

**Comment by rbillings** [comment]
I went through Duo, Authy & Google Authenticator and they all accept the current security code, and one prior security code. It does not work 2+ codes back.

If this is expected behavior I'll make a note for updating test cases & this issue can be closed.

**Comment by vladikoff** [comment]
> If this is expected behavior I'll make a note for updating test cases & this issue can be closed.

I think it is. @vbudhram confirm and close if so?

**Comment by vbudhram** [comment]
@rbillings This is expected behavior. The window back is configurable, but is defaulted to only 1. I'll update this in the feature doc for future reference as well.
