### ISSUE TITLE
TOTP: Rate limiting is not blocking users

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6047]
Testing on Nightly, https://accounts.firefox.com/settings?showTwoStepAuthentication=true
1) Enable MFA on an account
2) Sign out
3) Sign in with username + password
4) enter invalid security code
5) repeat 2+ times with invalid security codes in quick succession

expected: user is blocked after 2 attempts every 30 seconds 
actual: user is not blocked, is able to re-enter multiple codes [3+ per 30 seconds]

6) after 8* rapid invalid security codes, enter a valid security code

expected: user is blocked
actual: user is able to log in

**Comment by vbudhram** [comment]
This was added to train-110, which should be tagged next week, ref: https://github.com/mozilla/fxa-auth-server/pull/2386.

**Comment by rbillings** [comment]
Ah! I didn't see a train tag on the waffle board- and assumed "done" meant already in train 107 based on the feature doc. I will verify on train 110.

**Comment by vladikoff** [comment]
from mtg: might need to tag issues as "ready to test", etc

**Comment by rfk** [comment]
IIUC this should now be ready for testing

**Comment by rbillings** [comment]
Verified this works as expected, closing.
