### ISSUE TITLE
TOTP: Can't disable 2FA if I used a recovery code to sign in 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6056]
Devices:  Google Pixel (Android 8.1.0), HTC 10 (Android 8.0), Huawei Honor (Android 5.1.1);
Prerequisites: use an account with 2FA enabled and with recovery codes saved.

STR:
1.  Launch Firefox and go to Sign In page;
2. Enter credentials and tap on Sign In;
3. Use a recovery code to Sign In; 
4. Go to https://accounts.firefox.com/settings?showTwoStepAuthentication=true and tap on "disable" button. 

Actual results: no action is taken, 2FA is still enabled.
Expected results: 2FA is disabled.

Note: not reproducible when security code is used.

**Comment by vbudhram** [comment]
@SorinaFlorean This has been fixed in https://github.com/mozilla/fxa-auth-server/issues/2385 and will be available in upcoming train. Should we close this or do you want to keep it open until you verify?

**Comment by SorinaFlorean** [comment]
We can close it and I will verify when is ready for test. Thank you!

**Comment by SorinaFlorean** [comment]
This is working as expected. Tested on production and on staging server and the 2FA can be disabled when we use recovery codes.
