### ISSUE TITLE
TOTP: after adding MFA, CAD doesn't connect

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6059]
After creating an account and adding MFA, signing on with the same account to another device does not show the device as being connected.

1) browser: create account, verify, add MFA
2) open Firefox Nightly on Android, accounts.firefox.com, sign in with new account and MFA

expected: devices are connected, display in Devices and apps
actual: user is logged in with same account on 2 devices, Devices and Apps does not display second device, no messaging

**Comment by vladikoff** [comment]
Did Firefox on Android start syncing at all ?

**Comment by rbillings** [comment]
No syncing took place.

**Comment by rbillings** [comment]
I will also add that signing in/out, clicking Refresh, etc. did not change anything.

**Comment by rbillings** [comment]
This is totally my bad- I created the account on accounts.firefox.com & neglected to sign into Sync. It was fine after I added that step- which is also a good reminder to separate these actions on the test cases.
