### ISSUE TITLE
UX: Create Account gap between PW and Age on mobile/minimized screens

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa-content-server#6061]
Using mobile, or a smaller browser window shows extra spacing on the Create Account page between the second password and Age fields.

<img width="482" alt="screen shot 2018-04-12 at 10 19 09 am" src="https://user-images.githubusercontent.com/737878/38695833-44779cc4-3e42-11e8-8dc5-16f2e83ba639.png">

**Comment by vladikoff** [comment]
cc @ryanfeeley , by design?

This is because there is a password hint in there.

**Comment by ryanfeeley** [comment]
Yes, there is password advice that appears when you focus the password field. We didn't want to move the fields around in a jarring manner so left some space.

**Comment by vladikoff** [comment]
@ryanfeeley @rbillings closing for now, let me know if i should reopen.
