### ISSUE TITLE
Make too many login attempts warning absolute.

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6063]
CURRENT
![screen shot 2018-04-12 at 4 37 12 pm](https://user-images.githubusercontent.com/68213/38703157-76f97fd6-3e70-11e8-9516-ff7af3053262.png)

PROPOSED
![image](https://user-images.githubusercontent.com/68213/38703172-827e1560-3e70-11e8-8b04-dd54a48544aa.png)

**Comment by vladikoff** [comment]
omg

**Comment by vladikoff** [comment]
🗡 Closing as a WONTFIX for now
