### ISSUE TITLE
TOTP: Wrong email name when disabling 2FA 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6073]
Devices: Google Pixel(Android 8.1.0), Samsung Galaxy Tab S3 (Android 7.0).
Prerequisite: the user is signed in with an account with 2FA enabled.

STR:
1. Go to "manage account" settings.
2. Tap on "disable" options from Two-step Authentication section.
3. Verify email.

Actual results:  "Two-step Authentication removed" email is received.
Expected results:  "Two-step Authentication disabled" email is received.

Note: "Two-step Authentication disabled" is displayed in the content of the email.

**Comment by vladikoff** [comment]
@shane-tomlinson to change the wording, then we cut strings

**Comment by SorinaFlorean** [comment]
I can confirm that is is fixed on staging server-Train 111. "Removed" is replaced with "disabled".
