### ISSUE TITLE
Report password metrics to establish baseline for PW strength meter

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6074]
Several metrics are suggested in [this feature doc](https://docs.google.com/document/d/1dvpiZ-EAxVDHkXjwekyAougFufUDwB50nT9l9xo177k/edit#heading=h.n5radimwnm7x):

* Length
* Estimated strength

One way to estimate strength: log2(size_of_charset) * password_length

child of mozilla/fxa#294

**Comment by shane-tomlinson** [comment]
Will these be Flow events, Activity events or Amplitude events?

**Comment by philbooth** [comment]
@shane-tomlinson, probably flow events in this case.

Rules of thumb for event definitions:

  * It's a flow event if it's part of the sign-in/sign-up flow.

  * It's an activity event if there is a significant action or change of state at the account level.

  * It's an amplitude event if Alex says it's an amplitude event.

**Comment by rfk** [comment]
It's not directly related to this issue, but I wanted to mention it in case it's obvious how to add this while you're in there...in service of [1] we've also discussed wanting metrics on how long it takes us to PBKDF the user's password during the login flow.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1320222

**Comment by irrationalagent** [comment]
FWIW I think flow event is fine. If we can also wrangle these as event properties tied to amplitude events `fxa_reg - submit` and/or `fxa_reg - created` then that would be ideal as well.

**Comment by shane-tomlinson** [comment]
After discussing approaches to reporting pw-strength metrics with @g-k and @moz-jvehent, I'm going to close this issue as WONTFIX. We are going to take a different approach to reporting metrics, one that'll only work once we implement the actual UI. 

Instead of collecting length, we are going to report the delta where delta is the difference in the pw strength of the first and last password submits, as reported by zxcvbn.

**Comment by irrationalagent** [comment]
@shane-tomlinson IIUC then if someone only submits once (i.e. they were successful on the first try) then we will report 0 or nothing for our measure? In other words, we will only have a non-0 measurement for cases where someone submits something that's too weak, then submits again. 

I'm trying to understand how this new measurement will affect our ability to measure the experiment's success. We want to know which UI variant leads to the stronger passwords, e.g. perhaps something about variant G causes users to submit passwords (on the first try) with length 9 on average while variant F leads to an average of 9.5. Since both are over 8, that means most of the time there we will will have 0s for data. Will this make it difficult for us know that F is in fact the winner?

**Comment by g-k** [comment]
@irrationalagent can we count the 0s as satisfying the minimum required by a variant and try variants with different minimums? Or could we conduct an experiment on users with non-zero delta? e.g. we expect >50% of users to submit a non-zero delta across all variants and variant G will result in a larger increase.

**Comment by irrationalagent** [comment]
So if one variant has significantly **less** non-zero deltas than another we will then at least know that variant leads to the fewest resubmits (people meeting the requirements on the first try), which would be a mark in its favor. 

However, we still wouldn't know for sure which variant leads to the best passwords overall, as it could be the case that resubmissions on variants with *more* non-zero deltas (for some reason) ultimately bring the overall strength of the passwords for that variant up. In other words: can we rule out the possibility that a rejection somehow causes some users to "overcompensate" and choose a longer-than-average password? If we think that's not plausible, then going with the variant with the least resubmits (fewest non-0 deltas) will probably be the safest bet.

I hope I'm not being pedantic here, I just want to make sure that we have the data needed to make the right choice. 

Trying variants with different minimums might be an interesting idea, I'll have to think about it (although I'm not sure we want to change it from 8 at this point). There's definitely going to be a trade-off between strength and sign-up success - strength will go up and sign up completion will (eventually) go down as the minimum increases. I'm not sure what we'd consider the "sweet spot" there. And if we were to do this, I'm not sure that just using deltas wouldn't lead to the same problem as above.
