### ISSUE TITLE
Update marketing-email-prefs and marketing-email-client to match native basket api

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6076]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1417298#c6 and https://github.com/mozilla/fxa-basket-proxy/pull/56

* [x] - [SCOPES](https://github.com/mozilla/fxa-content-server/blob/71a20af50045a4e62bc5f42f216a92b727fb4543/app/scripts/models/marketing-email-prefs.js#L16) should be `basket profile:email`
* [ ] - POST to `/subscribe/` not `/subscribe`, ensure request includes the `X-Requested-With: XMLHttpRequest` header
* [x] - The [POST to /subscribe/](https://github.com/mozilla/fxa-content-server/blob/71a20af50045a4e62bc5f42f216a92b727fb4543/app/scripts/lib/marketing-email-client.js#L67) should encode data as `application/x-www-form-urlencoded` instead of JSON.

**Comment by rfk** [comment]
> The POST to /subscribe should encode data as application/x-www-form-urlencoded instead of JSON

IIRC it also needs to be `/subscribe/` rather than `/subscribe`, 

Also noting explicitly that we'll need to deploy the above basket PR before we can deploy the content-server changes.

**Comment by shane-tomlinson** [comment]
> IIRC it also needs to be /subscribe/ rather than /subscribe,

Good to know, we post to `/subscribe`

**Comment by rfk** [comment]
I *expect* that fxa-basket-proxy will accept `POST /subscribe/` in addition to `POST /subscribe`, but if it doesn't we should add that in for migration purposes.

**Comment by rfk** [comment]
> I expect that fxa-basket-proxy will accept POST /subscribe/ in addition to POST /subscribe,

Looks like it does, explicit test added in https://github.com/mozilla/fxa-basket-proxy/pull/57
