### ISSUE TITLE
Auto disable the SMS view when current spend is close to limit

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#6077]
Strawman proposed by @jbuck in the kick-off meeting just now:

* Once per hour, each content server process could check the current spend against the limit using [`GetSMSAttributes`](https://docs.aws.amazon.com/sns/latest/api/API_GetSMSAttributes.html) from the SNS API.

* If spend is within, say, 2% of limit, set some kind of flag that can be propagated to the client-side routing, so that it knows not to redirect to `/sms` [from `/connect-another-device`](https://github.com/mozilla/fxa-content-server/blob/c18bdf3cb32dc44b770b765d65f648b7568d5996/app/scripts/views/connect_another_device.js#L48-L58).

**Comment by jbuck** [comment]
It'll also need to check the Cloudwatch API for the current SMS spend along the lines of: `aws cloudwatch get-metric-statistics --namespace 'AWS/SNS' --metric-name 'SMSMonthToDateSpentUSD' --start-time '2018-04-01T00:00:00Z' --end-time '2018-04-17T00:00:00Z' --period '3600' --statistics 'Average'`

**Comment by rfk** [comment]
> each content server process 

Does this necessarily need to be done by content-server? 

While we haven't always kept to it, one of the premises of having content-server be a separate service is that it can do as little as possible, and reduce potential attack surface for anyone trying to inject things into the fxa web content.  If thiscould equivalently be done in e.g. fxa-auth-server than it's probably worthwhile doing it there in the interests of keeping content-server simple.

**Comment by philbooth** [comment]
As per mozilla/fxa-auth-server#2399, there is already a hook in the auth server for including this check, which I forgot about yesterday. We can include it in the response from `/sms/status` and no content server code will need to change. Closing this.
