### ISSUE TITLE
server test suites failing on latest.dev.lcip.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6078]
See e.g., https://tc-test.dev.lcip.org/viewLog.html?buildId=36528&buildTypeId=fxa_LatestServerTests&tab=buildLog

Seems PR https://github.com/mozilla/fxa-content-server/pull/5973 means some updates are needed for some `./tests/server` tests. A large number of them seem perhaps due to the expecting attribute values to be inside quotes, and now they're not. Tests on latest on teamcity were all passing until that PR landed.

**Comment by vladikoff** [comment]
```irc
22:52:53]  <vladikoff>	jrgm, ah i guess before quotes were stripped from the real tags
[22:52:57]  <vladikoff>	but fake ie tags still had them
[22:53:00]  <vladikoff>	or something
```

**Comment by jrgm** [comment]
https://github.com/mozilla/fxa-content-server/commit/e2f1acf7cd14b0eaefc68267e6eb90602e71b6c7 has the changes (expect no double-quotes on attribute values) that get the tests to pass, but since doubly-quoting is the canonical formatting, it's not really the right way.

**Comment by vladikoff** [comment]
Fixed!
