### ISSUE TITLE
Fetch OAuth `code` and `state` directly from /authorization response

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6084]
We currently get the `state` and `code` query parameters [by parsing the redirect URL in the response](https://github.com/mozilla/fxa-content-server/blob/5bf0a5f6ef784a86daa1fa09a16256ea865d98ad/app/scripts/models/auth_brokers/oauth.js#L24) to the auth-server's `/v1/authorization` endpoint.

With https://github.com/mozilla/fxa-oauth-server/pull/541/files, we can stop parsing the `redirect` url and instead get the values directly from the response body.

**Comment by rfk** [comment]
I'm going to need this for a little refactor I'm doing in service of https://github.com/mozilla/fxa-content-server/pull/6017, so putting my face on it
