### ISSUE TITLE
[Stage][Train 110] Can't log in to Pocket and Addons with an existing FF account

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6091]
Platforms: Win 10, Android 7.11, Android 5.11.

Steps to reproduce:
1. Go to hamburger menu and log in with a Firefox account;
2. Go to https://getpocket.com/login?e=4;
3. Tap on "Log in with Firefox".

Expected results: "Sign in to continue to Pocket" page is displayed and the account used at step 1 is pre-filled. Tapping on "Sign in" takes the user to pocket site. 

Actual results: the username and password is pre-filled but when I tap on "Sign in" button the message "unknown account.Sign in"  is displayed and I must re-create the same account in order to access Pocket.

Note: this is only reproducible on stage server and not on production.
Also reproducible for Addons account.

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - Is https://accounts.stage.mozaws.net being used for both step 1 and signing in to Pocket?

**Comment by SorinaFlorean** [comment]
@shane-tomlinson  Yes, the issue was tested on stage server following all the steps.

**Comment by vladikoff** [comment]
> Platforms: Win 10, Android 7.11, Android 5.11.

> Steps to reproduce:

> Go to hamburger menu and log in with a Firefox account;
> Go to https://getpocket.com/login?e=4;

@SorinaFlorean I assume your Firefox is configured to use the stage server, which means the hamburger menu will be using the stage server for sync. However other Firefox Accounts OAuth reliers will still use production servers, the profile configuration change does not affect those web properties or add-ons.
