### ISSUE TITLE
When disconnecting the account a message to reconnect is displayed

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6093]
Platforms: Win 10x64, Android 7.1.1;
Staging server [train 110] and production.
Prerequisite: the user is logged with an account.

Steps to reproduce:
1.Go to hamburger menu and tap on account name;
2. Tap on Disconnect -> Disconnect and observe the behavior.

Actual results: After the account is disconnected the message "please sign in to reconnect account x" with a yellow sign is displayed for 2-3 seconds. 

Expected results: no message is displayed after the account is disconnected. 

![production server](https://user-images.githubusercontent.com/24588037/39050257-69b5a2f8-44ad-11e8-9372-3e056aa67f4b.gif)

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - Thanks for the screen cap, I believe this is a bug with Firefox itself rather than us. Other than one call to sign out the user from FxA, FxA doesn't control any of that UI.

@mhammond, @eoger - Do you want this migrated to bugzilla?

**Comment by eoger** [comment]
Yes please!

**Comment by vladikoff** [comment]
Moved to here: https://bugzilla.mozilla.org/show_bug.cgi?id=1458762
