### ISSUE TITLE
Report how long PBKDF takes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6098]
Migrated from https://github.com/mozilla/fxa-content-server/issues/6074 to track separately, in support of https://bugzilla.mozilla.org/show_bug.cgi?id=1320222.

We would like to increase the number of rounds of PBKDF are used, but want to know how long it already takes on a variety of devices.

**Comment by shane-tomlinson** [comment]
Note: Make sure the number cannot be correlated to a user once sent to the backend.

**Comment by vladikoff** [comment]
WONTFIX
