### ISSUE TITLE
Implement "improve strength design G"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6105]
https://mozilla.invisionapp.com/share/J4GN45QVDFU#/screens/289506550

child of mozilla/fxa#294

**Comment by vladikoff** [comment]
from mtg: waiting on legal review

**Comment by vladikoff** [comment]
from mtg: there were no alternative designs that people agreed to. waiting for an updated design from @changecourse

**Comment by vladikoff** [comment]
from mtg: "not doing this for now in Q4", @shane-tomlinson reopen if we wanna work on this still?

**Comment by shane-tomlinson** [comment]
Updated designs: https://app.zeplin.io/project/5b870c13b52a0b16a5a3c8fa/dashboard
