### ISSUE TITLE
teamcity stage server test errors, incorrect versions being reported

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6107]
https://tc-test.dev.lcip.org/viewLog.html?buildId=37545&tab=buildResultsDiv&buildTypeId=fxa_StageServerTests

```
Show diff between expected and actual values

AssertionError: package version: expected '1.110.1' to equal '1.110.0'
  at <tests/server/ver.json.js:27:16>
« Hide stacktrace
```

It's like the test is pulling in an old package.json from before the point release.

@jrgm or @jbuck - any ideas?

**Comment by jrgm** [comment]
@shane-tomlinson - yeah, I had set GIT_COMMIT in the teamcity build command to force a version. This was to work around https://github.com/mozilla/fxa-content-server/issues/6078. When that is fixed, I can let it run the tests normally (based on whatever version accounts.stage.mozaws.net/__version__ says it's running).

**Comment by vladikoff** [comment]
"By Design"
