### ISSUE TITLE
Cannot sign in after a clear data

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6109]
Device:
Huawei MediaPad M3 Lite 10 (Android 7.0)
Huawei P8 Lite (Android 6.0)

Build: Nightly 61.0a1, Beta 60.0b15.
Not reproducing on 59 Release.

Steps to reproduce:
1. Sign in to Sync with a Firefox account.
2. Clear app data from Android settings>Apps>Firefox Nightly>Storage>Clear data.
3. Open the browser and go to Settings>Sign in.
4. Log in again with the same account.

Expected result:
The sync account should not be saved when clearing the app data. 
If the username is saved though, the user should be able to log back in.

Actual result:
The username is saved in Sync, but the user is not logged in. An error is displayed: "Cannot connect. Tap to sign in."
Tapping the message and trying to sign in, you get a success message that the account is connected.
Going back to settings>sync, the account is still not connected, the same error is displayed.
Can only sign in after the previous account is disconnected.

Corresponding bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1456487

**Comment by vladikoff** [comment]
Fixed 2 days ago https://bugzilla.mozilla.org/show_bug.cgi?id=1456487
