### ISSUE TITLE
Do we still need the `Sync Migration` feature?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6122]
@mhammond, @rfk - Are "Sync Migrations" from old Sync still happening?

I came across [this text: `Migrate your sync data by creating a new Firefox Account.`](https://github.com/mozilla/fxa-content-server/blob/8caf2c1e797c6303004eb68383a9c9df99cafdc7/app/scripts/templates/sign_up.mustache#L26) in one of our templates and would like to remove the feature if it's no longer being used.

**Comment by mhammond** [comment]
Desktop no longer supports the migration flow, so yeah, killing it is fine.

**Comment by shane-tomlinson** [comment]
Thanks @mhammond!
