### ISSUE TITLE
Gavatar avatar images fail to load in settings

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6127]
Noticed this today

<img width="935" alt="screen shot 2018-04-26 at 4 18 25 pm" src="https://user-images.githubusercontent.com/1295288/39329896-c3a8f67e-496d-11e8-8524-4c43f4fc9b8c.png">

Avatars still load in iOS and desktop Firefox though.

**Comment by vbudhram** [comment]
@rfk I believe it is disabled for adding new ones? I added mine a long time ago and vaguely remember it loading properly for a while.

It appears that the profile server correctly returns the profile image (https://secure.gravatar.com/avatar/d4edc9d5579c9847f7f98e58a6a8ebc2?s=600), but that fails a content-server validation.

I might very well be the only person that has a gavatar image still set 😆

**Comment by vladikoff** [comment]
@jrgm could we check how many people have gravatar set in db?

**Comment by vladikoff** [comment]
2% of people have an avatar that is a gravatar, let us know what we want to do here

1. Do nothing
2. revert the CSP rule removal
3. invest time into porting the gravatar avatars into firefoxusercontent

**Comment by shane-tomlinson** [comment]
> 2% of people have an avatar that is a gravatar, let us know what we want to do here

Is this 2% of *all users* or 2% of users that have an avatar set? If the 2nd, I imagine that's a far smaller number. Are we talking thousands, hundreds of thousands, hundreds?

**Comment by vladikoff** [comment]
2% of those that have avatar set
