### ISSUE TITLE
List some suggested TOTP apps?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#6151]
From some early tester feedback, :glob noticed that our setup UI has the text:

"Add a layer of security to your account by requiring security codes from one of these authentication apps."

But "these authentication apps" doesn't link anywhere or show any more info.  Is this going to be a link to e.g. the SUMO article from https://github.com/mozilla/fxa-content-server/issues/5866?

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/issues/5866. New SUMO page: https://support.mozilla.org/en-US/kb/secure-firefox-account-two-step-authentication
