### ISSUE TITLE
Support HTTP/2 ("H2")

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxa-content-server#6152]
@jbuck and others know best the technical reason(s) potentially blocking us from enabling HTTP/2 (or "H2").

(See https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/ and probably other, related docs.)

As @philbooth and I are working on tooling and perf-metrics gathering, and there hasn't been a rush so far, it might be nice to get a good/better baseline of solid perf data, before doing so.  It'd be nice to compare the before and after, with hopefully some measurable, impactful gains.

See http://www.webpagetest.org/result/180502_YB_03a201286e58fe77d36504c4748029a0/1/details/#step1_request2

**Comment by jbuck** [comment]
To support HTTP/2 we would need to switch from the classic ELB's we're currently using over to ALB or Cloudfront both of which support HTTP/2. Switching to ALB makes the most sense, but the problem we had making this move is that it doesn't support the same ciphersuite as ELB. Specifically it's missing `DHE-RSA-AES128-SHA` which is used by a good portion of Samsung SBrowser clients. I last checked this a year ago, so it's on @jrgm or I to run the ciphersuite statistics again and see if the use of that ciphersuite has changed.

**Comment by vladikoff** [comment]
Not actionable by content-server devs, I suggest creating a devops bugzilla bug for this
