### ISSUE TITLE
Safari iOS seems to have the same issues as Chrome Android with OAuth System browser when polling for emails

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6162]
Safari iOS seems to have the same issues with OAuth System browser when polling for emails

Ref: https://github.com/mozilla/fxa-content-server/issues/6089

**Comment by rfk** [comment]
We moved this out of next because it wasn't clear how urgent it was, or what next steps are.  @vladikoff please re-triage and add more info as appropriate.

**Comment by vladikoff** [comment]
Closing for now, didn't see any reports of this
