### ISSUE TITLE
Modernize the CSS building pipeline

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6165]
child of https://github.com/mozilla/fxa-content-server/issues/6261

We should replace the old `grunt sass watch` CSS building with a webpack `sass-loader` thing

Example: https://github.com/mozilla/notes/blob/40a6fa0435999b1a82fd2504726afab3418c67d0/webpack.config.js#L46

If this works well we won't have to run a separate command to update CSS files and just use the WebPack watcher

**Comment by Gabbyjose** [comment]
Hi there, I'm interested in working on this ticket if it's still available!

**Comment by vladikoff** [comment]
@gabbyjose hey! sorry, this is a large issue, please see other issues with a 'help wanted' label

**Comment by Gabbyjose** [comment]
@vladikoff thank you!
