### ISSUE TITLE
Add SUMO page for recovery key

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6173]
As part of the feature, we should have the proper SUMO articles and documentation written. Article can be based on

Feature doc: https://docs.google.com/document/d/1PVFwH276xgOd2N3GV40anBavKWXMxQd2bGcti7NBPYQ/edit#
UX: https://www.lucidchart.com/documents/edit/a96815b8-fea5-492f-b908-555192b199c4/0.

child of mozilla/fxa#297

**Comment by vladikoff** [comment]
from mtg: needs to be sent to SUMO

**Comment by vladikoff** [comment]
from mtg: needs to be sent to SUMO?
