### ISSUE TITLE
Migrate current gravatar profile images

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6180]
From https://github.com/mozilla/fxa-content-server/pull/6177#issuecomment-387848890, we should have a plan or path forward for migrating current gavatar users to not use gavatar. I could see this done in a few different ways

* Manually migrate gavatar avatar images in some background task
* Migrate when users request a profile picture

Feel free to recommend others!

**Comment by philbooth** [comment]
> Manually migrate gavatar avatar images in some background task

There might be legal issues with this and, even if there aren't, it might make us seem kind of creepy. Better to do it with user permission I think.

**Comment by vbudhram** [comment]
> There might be legal issues with this

Heh, yea that is true. We could promote changing avatars in some account tune up flow. Or even not do anything at all and let these users change pictures on their own.

**Comment by shane-tomlinson** [comment]
> Or even not do anything at all 

Are there downsides to this approach? Why did we remove the CSP rule in the first place?

**Comment by vbudhram** [comment]
@shane-tomlinson Probably should have clarified, just meant not doing anything at this moment and revisit later. With the CSP rule in place, the avatar would only not load on the web (loads correctly on browser menus). Removing it seems low cost and gives a consistent user experience.

**Comment by vladikoff** [comment]
> Why did we remove the CSP

It was a CSP clean up, but a little early. IMHO we should not worry too much about this at this time

**Comment by shane-tomlinson** [comment]
> It was a CSP clean up, but a little early. IMHO we should not worry too much about this at this time

I wholeheartedly agree.

**Comment by vladikoff** [comment]
🗡
