### ISSUE TITLE
Can navigate to recovery codes even if you do not have TOTP setup

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6186]
Found this in https://github.com/mozilla/fxa-content-server/pull/6181. Users should not be able to directly navigate to `/settings/two_step_authentication/recovery_codes`, if they do not have TOTP setup. We should redirect them to TOTP setup page instead.

**Comment by farhan787** [comment]
@vbudhram may I fix this ? And by TOTP setup do you mean "/settings/two_step_authentication" or something else ?

**Comment by vbudhram** [comment]
@farhan787 Sure you can work on this. 

> And by TOTP setup do you mean "/settings/two_step_authentication" or something else ?

Correct, if they have not added TOTP/Two-step authentication, the user should not be able to navigate directly to `/settings/two_step_authentication/recovery_codes`. If they try, then we should add some logic to redirect them to `/settings/two_step_authentication`.
