### ISSUE TITLE
Show new "user-card" view in legacy signin & signin cached view

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6198]
In #6187, I only added the user-card view to the email-first flow. Lockbox is going to be using the legacy, non-OAuth, signin flow for their V1. The card needs to be added to the legacy signin & cached signin view.  (or we remove the legacy views.)

**Comment by vladikoff** [comment]
@shane-tomlinson please reopen this if you think we are gonna get to this legacy view

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson please reopen this if you think we are gonna get to this legacy view

The only thing we should do to the legacy view is rip it out!
