### ISSUE TITLE
[Train 112]  Links are performing like buttons

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6204]
Environment: Win10, Samsung Galaxy Tab S3(Android 7.0)
Stage server - Train 112

Steps to reproduce:
1. Log in with an account;
2. Go to Manage devices;
3. From Two-Factor Authentication tap/click on "these authentication apps" link.
4. Go back to Manage account page.

Actual results:  "these authentication apps" link is performing like a button and remains selected after the page is opened. 

Expected results:  "these authentication apps" link is opened without visual effects.

Notes: 
- On Android devices, reproducible only when is performed short tap on the link.
- On desktop reproducible with all the links: e.g. can't scan code? Missing or duplicate items.
- Also, on desktop the buttons  (e.g. Add, change) remains selected when middle click on them.
 
![2018_05_17_11_57_21_firefox_accounts_two_step_authentication_firefox_nightly](https://user-images.githubusercontent.com/24588037/40176696-faa45024-59e4-11e8-89e9-88e4aa5addfc.png)

**Comment by SorinaFlorean** [comment]
![screenshot_2018-05-18-10-12-27](https://user-images.githubusercontent.com/24588037/40221152-41c57ef2-5a84-11e8-90b8-5d8ba39f7d8e.png)

**Comment by shane-tomlinson** [comment]
Here's the relevant Photon design section re links: https://design.firefox.com/photon/components/links.html

The link is supposed to receive a button-like focus-ring on focus. When clicking on the link, it receives focus, so I'm not sure what to do here. Maybe the CSS :focus and :active selectors order needs to be swapped.

Regardless of how to handle the focus state, there are still a couple of other things wrong here:
* There should be no list-item bullet to the left.
* It looks like there are two bottom lines on the link.
* If we keep the :focus state, the focus-ring doesn't seem to be applied to the top.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/FirefoxUX/photon/issues/303

**Comment by shane-tomlinson** [comment]
Fixed by #6215, closing.
