### ISSUE TITLE
Unexpected error in Communication preferences

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6206]
Environment: Win10, Samsung Galaxy Tab S3(Android 7.0)
Stage server: train 112.

Steps to reproduce:
1. Log in with an account;
2. Go to Manage Devices;
3. From Communication preferences tap on "Change"

Actual results: "unexpected error" message is displayed with red and isn't aligned.
Expected results: the user can change preferences choosing subscribe or unsubscribe. 

Note: see the screenshot https://i.imgur.com/zx1Sq8u.png

**Comment by shane-tomlinson** [comment]
@jrgm or @jbuck - For stage, is a fake-basket-proxy hooked up to handle these requests?

**Comment by shane-tomlinson** [comment]
Thanks for the report @SorinaFlorean, styling issues in #6216!
