### ISSUE TITLE
New UI seems a bit off 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6209]
Build:
Fxa Train 112
Staging server

While testing Train 112, we've gone through several pages of the FxAccounts flows and observed the Photon UI changes. There are a few improvements we would like to suggest.

We feel like the font looks disproportionate, too small in some areas and in some cases too lightweight.
For e.g.: on the create account page it looks like there are 2-3 different fonts, the lower ones are too tiny (https://drive.google.com/open?id=1f8u5g_qCVxh_Qfwp8CuB6Ot3WtCBKrBS), button labels could be bold, etc.

Also, the success confirmation banners have a green color that appears as too bright.

We've created a folder with a few screenshots taken on Windows 10 to exemplify: https://drive.google.com/open?id=15uTTS_RCdg9s6eMreJPARZW0P221GrOK

**Comment by shane-tomlinson** [comment]
Thanks for the report @sv-ohorvath. I am using a combination of the [Photon styleguide](https://design.firefox.com/photon/welcome.html) and the styles as specified in this [Zeplin project](https://app.zeplin.io/project/5ad79b0f8964ebca1c06cab8/screen/5ad79b98e49230ff0c40561f). If you can send me your email address, I can give you access.

That green, yeah, I agree about it looking too bright. That's color [specified by Photon](https://design.firefox.com/photon/components/message-bars.html). Perhaps we can experiment with making the entire background dark so it doesn't look so jarring.

**Comment by shane-tomlinson** [comment]
>  If you can send me your email address, I can give you access.

Duh, all I had to do is open your Github profile, invite sent.

**Comment by vladikoff** [comment]
Please reopen new issues if there are remaining UI components that need updating
