### ISSUE TITLE
Can we be more clear about the implications of resetting your password?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#6213]
From this discourse discussion:

  https://discourse.mozilla.org/t/help-lost-all-of-my-synced-passwords/28715

A user who was resetting their password saw our warning message about data loss, but interpreted it to mean that only recent data would be lost.  Relevant quotes:

 * "There was a note stating latest saved/synced passwords may be lost, HOWEVER, I lost all of my passwords"
* "I would not have reset my password if I knew this was going to happen.  The message only stated that ‘recent’ data would be deleted."

It may be worth reviewing the wording in light of this feedback to see if we can clarify it further.

**Comment by shane-tomlinson** [comment]
I sympathize with the user, though there is no mention of "recent" anywhere in our text. Do we imply that? The thing I find most confusing is "some of your data will be erased".

/reset_password:
> NOTE: If you reset your password, some of your data will be erased (including synced server data like history and bookmarks). That’s because we encrypt your data with your password to protect your privacy. 

/complete_reset_password:
> REMEMBER: If you reset your password, some of your data will be erased (including synced server data like history and bookmarks). That’s because we encrypt your data with your password to protect your privacy.

email:
> Click the button within the next hour to create a new password. The request came from the following device:

Regardless of whether we imply "recent" somewhere, I'm going to go out on a limb and say users who rely upon the Fx password manager don't really give a toss about whether their history is lost, however if their passwords are lost they can no longer sign into their favorite sites.

**Comment by vladikoff** [comment]
@juliemccracken to check this..

**Comment by vladikoff** [comment]
from mtg: waiting until the end of this week?

**Comment by MeridelW** [comment]
I worked on the original copy for this. Below is a revised version, which I think works much better on a couple of different levels.  

**/reset_password:**
NOTE: When you reset your password, you reset your account. You may lose some of your personal information (including history, bookmarks, and passwords).

**/complete_reset_password:**
REMEMBER: When you reset your password, you reset your account. You may lose some of your personal information (including history, bookmarks, and passwords).

**Comment by MeridelW** [comment]
Checking in on this. New copy has been provided - is there someone on this thread who could implement it?  @vladikoff ? 
@juliemccracken - please point me in the right direction if I am knocking on the wrong door. =)

**Comment by MeridelW** [comment]
@shane-tomlinson No problem, and thank you for the update!
