### ISSUE TITLE
Provide a button to “Go to Lockbox” from the confirmation screen

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6217]
blocks #6083.

Provide a button to “Go to Lockbox” from the confirmation screen – as shown in the designs via InVision.

<img width="341" alt="screen shot 2018-05-21 at 14 05 54" src="https://user-images.githubusercontent.com/848085/40310104-a8e3417e-5d03-11e8-9967-b5c684de3556.png">

**Comment by vladikoff** [comment]
Please reopen if this is still needed !
