### ISSUE TITLE
Show password button is not correctly displayed using Windows & low DPI screens

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa-content-server#6235]
### Steps to reproduce:
1. Open https://addons.mozilla.org/en-US/firefox/
2. Click on the log in button from the top right corner
3. Enter an email and start typing your password
4. Observe the "Show password" button

### Expected results:
The button is correctly displayed

### Actual results:
The "eye" icon form is not distinguishable.

### Notes/Issues
Verified in FF 60.0.1 on Win7(x64) Issue can't be reproduced when using Latest Nightly.
Screencast for this issue: 
![showpasswordbutton](https://user-images.githubusercontent.com/15685441/40709854-cf58ff8a-63ff-11e8-9c5b-ca1416aa2d55.png)

**Comment by shane-tomlinson** [comment]
@madalincm - this is what it looks like locally for me:

<img width="451" alt="screen shot 2018-05-31 at 11 31 23" src="https://user-images.githubusercontent.com/848085/40777594-38147c68-64c6-11e8-8d3e-b50681387747.png">

Are you using a low DPI screen? Chances are we have all been using high DPI monitors and didn't test on enough screens/devices.

**Comment by shane-tomlinson** [comment]
Here's what it looks like for me in a low DPI linux VM:

<img width="408" alt="screen shot 2018-05-31 at 11 34 34" src="https://user-images.githubusercontent.com/848085/40777759-a97091a8-64c6-11e8-8e94-fe1e7b084db7.png">

Maybe I have to go lower DPI still?

**Comment by madalincm** [comment]
I do not think this is DPI related as I can reproduce the issue only on Release. When I try it on Nightly the icon is correctly displayed: 
![showpasswordbuttonnightly](https://user-images.githubusercontent.com/15685441/40779756-ca5a04ea-64de-11e8-97eb-a3d1af646654.png)

Using FF Release 60.0.1 I was able to reproduce it on 3 different work stations (two Win10 x64 and one Win7 x64). I am using a 23 inch monitor with full hd resolution.

**Comment by shane-tomlinson** [comment]
>  (two Win10 x64 and one Win7 x64)

AHA! Thanks for that info, I'm using a Mac and Linux. I'll boot up a Windows VM now.

**Comment by shane-tomlinson** [comment]
In a Windows 7 VM it looks reasonable, however on a first-gen Surface tablet the icon does look pretty bad. Thanks for the info @madalincm, I'll see if our designers are able to fix this.

**Comment by vladikoff** [comment]
from mtg: vlad to check this on Surface

**Comment by vladikoff** [comment]
> from mtg: vlad to check this on Surface

I will try ...

**Comment by vladikoff** [comment]
I tested this on Windows with a non-retina screen and yes the SVG itself doesn't look good https://accounts-static.cdn.mozilla.net/images/3788faf2.icon-show-password.svg

**Comment by vladikoff** [comment]
from mtg: also ask about a11y

**Comment by vladikoff** [comment]
@ryanfeeley could you please provide a new icon? I have a machine at the office that we can test this on...

**Comment by ryanfeeley** [comment]
I checked with our design systems group. The SVG was never optimized. Run it through this: https://github.com/BohemianCoding/svgo-compressor

**Comment by shane-tomlinson** [comment]
@ryanfeeley - will that compressor make the icon look less awful on Windows machines with low dpi screens?

**Comment by vladikoff** [comment]
> @ryanfeeley - will that compressor make the icon look less awful on Windows machines with low dpi screens?

I don't think it will, but we can try

**Comment by ryanfeeley** [comment]
The advice was "I see that the icon has groups, defs, use and mask. This is not ideal. Where did you grabbed the icon? It probably missed the SVGO polish"

**Comment by muffinresearch** [comment]
We've had similar issues on AMO wrt windows, specifically the mask always seem to the be the issue.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I ran the icon through SVGO, no change. There is a deprecated [icon in the photon style guide](https://design.firefox.com/icons/viewer/), though that looks slightly different to the one you originally suggested.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - This is the icon I was referring to from the photon style guide:

<img width="120" alt="screen shot 2018-08-14 at 14 10 52" src="https://user-images.githubusercontent.com/848085/44093596-f0088fb8-9fcb-11e8-8fdd-b0b46a536639.png">

Even though it's deprecated, should we use that until a new eye icon is developed? Does anyone on the design team have an updated icon we could use?

**Comment by ryanfeeley** [comment]
@shane-tomlinson OK, I re-exported from Sketch into Illustrator, clean it up as much as possible, re-exported and optimized. This file is so small and simple, I can't imagine there is any weirdness with it.
[password-show.svg.zip](https://github.com/mozilla/fxa-content-server/files/2337589/password-show.svg.zip)
