### ISSUE TITLE
Enter security/recovery code pages not centered (iOS)

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6244]
Device: iPhone SE (11.0.1)
Stage server: Train 113

Steps to reproduce: log in with an account with 2FA enabled and pay attention to Enter security code page, is not centered.

Screenshot:
![img_0008](https://user-images.githubusercontent.com/24588037/40791305-dfa53f7e-64ff-11e8-9293-e1e4a2830782.PNG)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Train 118.
