### ISSUE TITLE
action=email hangs if email is provided

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6259]
From https://github.com/mozilla/bedrock/pull/5713#issuecomment-393928445

@shane-tomlinson could you take a look at this for @jpetto ? I am on the plane tomorrow morning so I will be AFK for a bit...

https://latest.dev.lcip.org/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

http://accounts.firefox.com/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

https://stable.dev.lcip.org/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

If I remove the `email` param then it is fine.

**Comment by shane-tomlinson** [comment]
Everything works as expected browsing to http://127.0.0.1:3030/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

**Comment by shane-tomlinson** [comment]
> Everything works as expected browsing to

With a caveat, the profile has to be set up to accept WebChannel messages from http://127.0.0.1:3030.

What I suspect is happening here is that you are visiting the URL using a Firefox profile that is not set up to respond to WebChannel messages for that environment. For example, I have to use my "local" profile to visit http://127.0.0.1:3030/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com and see anything. However, if using the "local" profile I see a spinner when I visit http://accounts.firefox.com/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

If I use a new profile everything works as expected if I visit http://accounts.firefox.com/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form&email=aaaaa%40eqwe12312e.com

<img width="1051" alt="screen shot 2018-06-06 at 10 40 52" src="https://user-images.githubusercontent.com/848085/41030382-1e52d6c6-6976-11e8-9250-d6765ff39223.png">

If I try to load the local URL above, the spinner is displayed.

The `/` page sends a `can_link_account` message to the browser to show this dialog if needed:

<img width="852" alt="screen shot 2018-06-06 at 10 41 38" src="https://user-images.githubusercontent.com/848085/41030423-39cb26ec-6976-11e8-89d5-ca7d4bf39eaa.png">

I suspect the main problem here is a configuration issue. We could display an error message that says "WebChannel message not received", but I do not have a good feel for how much effort that will be.

**Comment by vladikoff** [comment]
ah, i guess we are missing some setting in the dev launcher?

**Comment by shane-tomlinson** [comment]
> ah, i guess we are missing some setting in the dev launcher?

I'll have a look, dev launcher has always worked great for me!

**Comment by shane-tomlinson** [comment]
> > ah, i guess we are missing some setting in the dev launcher?
> I'll have a look, dev launcher has always worked great for me!

Yeah, I suspect there's a missing profile setting, if I use the dev-launcher, type `FXA_ENV=latest npm start`, then [the latest URL w/o the email](visit https://latest.dev.lcip.org/?action=email&context=fx_desktop_v3&service=sync&entrypoint=firstrun&flow_id=458029fd573efdf59c6b1b176d39295b8071f368aa406c5f92d9c81c7dc3e5cf&flow_begin_time=1528241487775&utm_content=fx-60.0&utm_source=firstrun&utm_medium=referral&utm_campaign=fxa-embedded-form) and enter an email, the UI gets stuck as well.

**Comment by shane-tomlinson** [comment]
Digging in more.

**Comment by vladikoff** [comment]
Fixed via https://github.com/vladikoff/fxa-dev-launcher/commit/93b4bb390384cd00f6a423e93be83a77007d98a7
