### ISSUE TITLE
TOTP: Make Code input field type="number"

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6266]
I just went through the TOTP flow on my phone and I noticed that when I click in the field to type code, it is doesn't change the keyboard to number pad.

I think we could make it a little easier if we make the input type a number.

(granted, the smart thing is to copy/paste it but Authenticator might be on another device)

**Comment by vbudhram** [comment]
This is a duplicate of https://github.com/mozilla/fxa-content-server/issues/6240.
