### ISSUE TITLE
about:welcome Audit integration of email first without iFrame

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6267]
On about:welcome , they've rebuilt the /firstrun experience without the iframe.

From an FxA standpoint, 
- let's sign off to make sure it is well integrated with proper parameters.
- let's confirm we have a way to track the email first form view without the iFrame

The only UX prob I detected is that it doesn't support a signed in state however I question how regularly a signed in user will get to about:welcome

For context:
https://bugzilla.mozilla.org/show_bug.cgi?id=1448918#c62

**Comment by vladikoff** [comment]
@ericawright here's an example of how the integration works https://github.com/jpetto/bedrock/pull/2/commits/af5d94abfe27152a0f767b3348704b7674095857

Let us know if there are any issues, especially with origin requests

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1471514

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1448918#c62

Ref: https://github.com/mozilla/fxa-content-server/issues/5882

**Comment by ericawright** [comment]
@vladikoff  thanks, I was looking into it this morning briefly and there was an issue with the origin request. I saw @piatra assign themselves to the issue though, I'll double check to see if they will be implementing it.

**Comment by shane-tomlinson** [comment]
This is done!

**Comment by davismtl** [comment]
@shane-tomlinson & @philbooth according to the bug, QA sees flow_begin_id and flow_begin_time in Firefox 63.0a1 (nightly).
https://bugzilla.mozilla.org/show_bug.cgi?id=1471514#c19

However, when I look in Amplitude, I don't see any email_first form views:
https://analytics.amplitude.com/mozilla-corp/chart/new/ntqg9o3

What am I doing wrong? Am I looking at the right params here? Is it just that there is no volume in nightly so this is normal? I tried to trigger the event myself but no luck.
