### ISSUE TITLE
Ensure that button spinner is white not grey

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6284]
I noticed that the spinner we are using on red and blue buttons is a light grey to transparent. It should instead be set to white to transparent for these instances (and remain the same when it is set against white, grey or black backgrounds).

<img width="574" alt="screen shot 2018-06-18 at 1 33 46 pm" src="https://user-images.githubusercontent.com/68213/41552334-7184d1fc-72fc-11e8-9171-dc1c25722c10.png">
<img width="692" alt="screen shot 2018-06-18 at 1 33 43 pm" src="https://user-images.githubusercontent.com/68213/41552335-719e1dc4-72fc-11e8-8683-12a4ed3db0de.png">

**Comment by ShivangiKakkar** [comment]
Hey! @ryanfeeley @shane-tomlinson 
It's my first time contributing here, I would like to try this one out if it qualifies for a good first bug.
I find this issue an interesting one to start with :)

**Comment by shane-tomlinson** [comment]
@ShivangiKakkar - I think all that should need to be done is in the .scss files, change references of `spinnergrey` to `spinnerlight`, I haven't looked to know for sure though. If you run into any problems please let me know!

**Comment by ShivangiKakkar** [comment]
Thanks a lot! :) @shane-tomlinson

**Comment by ShivangiKakkar** [comment]
@shane-tomlinson 
I am facing this issue regarding `Sign in`.

<img width="992" alt="screen shot 2018-08-27 at 7 36 37 pm" src="https://user-images.githubusercontent.com/35342019/44670245-c2a42900-aa3f-11e8-9f98-f90c6c6df8c8.png">
Would you please guide me through this?

**Comment by ShivangiKakkar** [comment]
@shane-tomlinson Hey! I need your help regarding this:
- If I change the references of `spinnergrey` to `spinnerlight`, the color of spinner changes to `blue` from `grey`. 
- I inspected through the spinner images, there is no image for `white` spinner, there are only `blue` and `grey` spinner images. Do I need to add one(white one)? What do you suggest? 
Thanks in advance :)

**Comment by vbudhram** [comment]
@ShivangiKakkar You are right there are no images for a white spinner.

@ryanfeeley I took a stab a creating a white spinner based on the `spinnerlight.svg`. Does this look good?

[spinnerwhite.svg.zip](https://github.com/mozilla/fxa-content-server/files/2349409/spinnerwhite.svg.zip)
![screen shot 2018-09-04 at 12 25 58 pm](https://user-images.githubusercontent.com/1295288/45044303-bcb0d800-b03d-11e8-9baf-5f5a60a1bbc1.png)

**Comment by ryanfeeley** [comment]
@vbudhram Looks great, but shouldn't this something we can change with CSS? My SVG/CSS knowledge is lacking, granted.

**Comment by ShivangiKakkar** [comment]
@ryanfeeley @vbudhram I can try changing the color with CSS but using a different CSV would surely be an easier solution.

**Comment by ShivangiKakkar** [comment]
> @ShivangiKakkar You are right there are no images for a white spinner.
> 
> @ryanfeeley I took a stab a creating a white spinner based on the `spinnerlight.svg`. Does this look good?
> 
> [spinnerwhite.svg.zip](https://github.com/mozilla/fxa-content-server/files/2349409/spinnerwhite.svg.zip)
> ![screen shot 2018-09-04 at 12 25 58 pm](https://user-images.githubusercontent.com/1295288/45044303-bcb0d800-b03d-11e8-9baf-5f5a60a1bbc1.png)

@vbudhram  Sir, Can you please guide me towards the solution in order to close this issue.  Thanks :)

**Comment by vbudhram** [comment]
@ShivangiKakkar Sorry about the late response, but if you are still interested in working on this you can.

Unfortunately, I don't believe we will be able to use css on this because the svg uses gradients and `stop-color` options. I think css can be used to update only the fill style. It would make sense to use a new svg and update where needed.

**Comment by shreya99oak** [comment]
Hey! @vbudhram is anyone working on this? Can I take it up?

**Comment by vbudhram** [comment]
@shreya99oak Sure! Let me know if you have any questions.
