### ISSUE TITLE
"Show" button overlapping "Change" button

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6306]
Environment: Nexus 6P(Android 8.1.0)
Server: production - Nightly 62.0a1 (06-25)

Steps to reproduce:
1. Go to Manage account page;
2. Switch between Subscribe sections, devices&apps, tap on Change, Show several times.

Notes: I don't have more clear steps to follow because it only happened once and after that, the "Show" button was displayed without issues.

Actual results: see the screenshot.
![screenshot_20180625-171645](https://user-images.githubusercontent.com/24588037/41856494-ead8eb78-789d-11e8-868d-18d3b8bffa5e.png)

**Comment by richa031** [comment]
is this issue still open?

**Comment by shane-tomlinson** [comment]
It doesn't look to be:

<img width="328" alt="screenshot 2019-01-23 at 13 34 56" src="https://user-images.githubusercontent.com/848085/51610089-c0bd9380-1f13-11e9-9bb9-9791efcb5126.png">

@SorinaFlorean can you check this one to see if it's still a problem? Locally it looks alright.

**Comment by SorinaFlorean** [comment]
Wasn't able to reproduce this issue on production or on stage server. I will close it.
