### ISSUE TITLE
CWTS on Android hides the button below fold

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6314]
When registering on a Nexus 5 running Android (1080x1920), the button to complete the step is not easily visible. It's not obvious that we need to scroll down.

![screenshot_2018-06-27-04-03-36](https://user-images.githubusercontent.com/19537086/41939118-b593ecfe-7949-11e8-8e4c-1ba775e52a4e.png)

I think there is a lot of weird padding at the top above the green bar that we can remove.

**Comment by shane-tomlinson** [comment]
Good spot @davismtl, I think that big space up there is where the icon normally displays, but we removed the icon way back from this page for just this reason. For this page, we should indeed remove that padding.

**Comment by philbooth** [comment]
@davismtl can you triage this out of the backlog if it's more urgent?

**Comment by davismtl** [comment]
Putting this up as a potential papercut to fix in Q3.

Other observation, the checkboxes are on 1 column. On iOS, they span two columns. Is this caused by the screen resolution or just another bug?

**Comment by shane-tomlinson** [comment]
> Is this caused by the screen resolution or just another bug?

Caused by screen resolution. Do you know the resolution of your screen?

Ref https://github.com/mozilla/fxa-content-server/issues/5710, https://github.com/mozilla/fxa-content-server/pull/5738, https://github.com/mozilla/fxa-content-server/pull/5500

**Comment by davismtl** [comment]
Mentioned at bottom of first comment: 1080x1920

**Comment by shane-tomlinson** [comment]
> Mentioned at bottom of first comment: 1080x1920

Sorry, should have read more closely. The physical resolution isn't what's important here, but rather the resolution as the browser sees it (CSS pixels), which depends on the [device pixel ratio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio). The CSS pixel size is what causes the breakpoints to trigger. It looks like [the nexus 5 has a devicePixelRatio of 3](https://bjango.com/articles/min-device-pixel-ratio/), meaning 1080 physical pixels translates to 360 CSS pixels. 

We make affordances to enable a 2 column display [for < 319 pixels](https://github.com/mozilla/fxa-content-server/blob/eb10ac87016da56422c827d32491852c0d1d3f21/app/styles/modules/_custom-rows.scss#L163) and [for < 520px](https://github.com/mozilla/fxa-content-server/blob/eb10ac87016da56422c827d32491852c0d1d3f21/app/styles/modules/_custom-rows.scss#L159), so the theory is it should be displaying 2 columns, I probably busted things with the Photon updates.
