### ISSUE TITLE
No space between "Settings" and "Open websites in" - Lockbox

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6319]
Environment:
Device: iPhone SE (11.0.1)
Lockbox version 1.1 (1552)

Steps to reproduce:
1. Open Lockbox app;
2.  Go to settings -> Open Website in and pay attention to the header.

Actual results: no space between "Settings" and "Open websites in".
Expected results: space between words

![img_0013](https://user-images.githubusercontent.com/24588037/42084435-4d79470a-7b96-11e8-93ce-d348465e43fd.PNG)

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - I suspect this one will get a better audience at https://github.com/mozilla-lockbox/lockbox-ios/issues

**Comment by SorinaFlorean** [comment]
@shane-tomlinson thanks, I will close then.
