### ISSUE TITLE
Visual issues of rating option from Feedback page - Lockbox 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6320]
Environment:
Device: iPhone SE (11.0.1)
Lockbox version 1.1 (1552)

Steps to reproduce:
1. Open Lockbox app;
2. Go to settings -> Send Feedback.

Actual results: 
- "x" too close to the star
- "x" too small compared to the stars
- the stars are not centered

Expected results: no visual issues are displayed.

![img_0012](https://user-images.githubusercontent.com/24588037/42084738-364f9a1a-7b97-11e8-87c3-af94fbdc54cd.PNG)

**Comment by SorinaFlorean** [comment]
If this isn't the right place for Lockbox issue, please let me know. Thanks!

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - I think this one should be filed in https://github.com/mozilla-lockbox/lockbox-ios/issues

**Comment by SorinaFlorean** [comment]
@shane-tomlinson thanks.
