### ISSUE TITLE
[PW-strength] Opening the "List of common passwords" link, would expect to see a list of actual passwords

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6324]
Page: https://accounts.stage.mozaws.net/signup?action=email&service=sync

This is more of a suggestion for improvement:
- When opening a "list of common passwords" link, one would expect to see the passwords, or a website where they can search for them, as, for example, https://haveibeenpwned.com/Passwords.
- On the support page, we have this line again: "It is not in the public database of 50,000 most common leaked passwords. " where users might expect to get a reference to that list.

Only mentioning that list and never giving the users the source is a bit confusing and frustrating, because it's not easy to find it in a google search either.

**Comment by shane-tomlinson** [comment]
I proposed a change to add a link to the top 50k passwords to https://support.mozilla.org/en-US/kb/password-strength, waiting for approval. The list is at https://mozilla.github.io/application-services/docs/accounts/50000-most-common-passwords.html

**Comment by vladikoff** [comment]
blocked, waiting for SUMO

**Comment by vladikoff** [comment]
Done!
