### ISSUE TITLE
[PW-strength] Hide keyboard on mobile devices when "show password" is tapped

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6326]
Build: Train 115- Staging server
Devices:
Pixel (Android P)
Mi 4i (Android 5.0.2)

STR:
1. Open https://accounts.stage.mozaws.net/signup?action=email&service=sync
2. Type in a password and tap the eye icon to show the password.

Expected result: Currently on Production, without the password hint, the keyboard is hidden when 'show password' is tapped.

Actual result: The keyboard is hidden and then bounces back up, making an unpleasant motion of the page. See video:
https://drive.google.com/file/d/1RXwGnkqlG5UYa9J1je9qKdB_BCMi5AuQ/view?usp=sharing

**Comment by shane-tomlinson** [comment]
Thanks @sv-ohorvath, this should be fixed with the fix for [this issue pointed out in #6299](https://github.com/mozilla/fxa-content-server/issues/6299):

> Do not autofocus the password field on blur when invalid, it makes it to that screen reader users cannot easily read the balloon.

Keeping this open so that we can verify once fixed.

**Comment by vladikoff** [comment]
blocked: needs QA

**Comment by sv-ohorvath** [comment]
Verified as fixed on Train-119. Thank you!
