### ISSUE TITLE
circle is using node 6 to run tests

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6328]
See `: 6` at https://github.com/mozilla/fxa-content-server/blob/master/circle.yml#L25.

I tried changing it in https://github.com/mozilla/fxa-content-server/tree/fix-circle-node-8 but the `grunt build` fails: https://circleci.com/gh/mozilla/fxa-content-server/10455

**Comment by shane-tomlinson** [comment]
@jrgm, I suspect the failure you pointed out (sass dependency problem) is an npm version mismatch problem, when I force installed npm@6 in https://github.com/mozilla/fxa-content-server/pull/6335, all good and rebuilt without cache, all good.

**Comment by shane-tomlinson** [comment]
More context, I think node@8 by default uses npm@5 instead of 6.

**Comment by jrgm** [comment]
> More context, I think node@8 by default uses npm@5 instead of 6.

Ah, yes. node@6 does come with npm@5, at this time.
