### ISSUE TITLE
console error when submitting an invalid form: uncaught exception: undefined

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6333]
STR

1. Visit any form page
2. Open the console log
3. Submit an invalid form

> uncaught exception: undefined

**Comment by shane-tomlinson** [comment]
This is caused by throwing the exception in form.js->validateAndSubmit:

https://github.com/mozilla/fxa-content-server/blob/eb10ac87016da56422c827d32491852c0d1d3f21/app/scripts/views/form.js#L194

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/6025
