### ISSUE TITLE
password is not checked immediately on submit w/ new password strength bubble

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6339]
STR

1. Open https://accounts.firefox.com?service=sync&action=email
2. Enter in a test email that'll force the new UI (@mozilla.com, @softivision.ro, @softvision.com)
3. Submit the form w/o entering a password.

Expected
* Bubble is updated to point out password is too short
* Password input field is marked invalid

Actual
* Nothing. No feedback.

**Comment by sv-ohorvath** [comment]
Verified on Stage: Train 116.
