### ISSUE TITLE
Failing functional test on latest: Signin in Chrome for Android, verify same browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6345]
> NoSuchElement: [POST http://localhost:4444/wd/hub/session/d50c6a4a-753c-4384-be01-6291865120ca/element / {"using":"css selector","value":"#fxa-signin-header"}] Unable to locate element: #fxa-signin-header For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z' System info: host: 'c067e5721c1c', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144' Driver info: driver.version: unknown at Command.<anonymous> <tests/functional/lib/helpers.js:156:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:167:12> at Command.<anonymous> <tests/functional/lib/helpers.js:164:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1243:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1245:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1306:10> at Command.<anonymous> <tests/functional/lib/helpers.js:1302:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Command.<anonymous> <tests/functional/lib/helpers.js:1360:12> at Command.<anonymous> <tests/functional/lib/helpers.js:1357:6> at Command.<anonymous> <tests/functional/lib/helpers.js:57:23> at Test.signin in Chrome for Android, verify same browser [as test] <tests/functional/oauth_sign_in.js:246:10> at <src/lib/Test.ts:260:47>

See https://tc-test.dev.lcip.org/viewLog.html?buildId=39922&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

**Comment by vladikoff** [comment]
Screencap https://screencap.co.uk/images/cceca7a2cf6560118c8614105079871325471042.png

**Comment by shane-tomlinson** [comment]
Oh dear....

**Comment by shane-tomlinson** [comment]
@vladikoff - when running this test locally I see an "invalid client_id" error:

<img width="982" alt="screen shot 2018-07-12 at 07 32 05" src="https://user-images.githubusercontent.com/848085/42616361-de8460cc-85a5-11e8-882f-d012d876f7b9.png">

**Comment by shane-tomlinson** [comment]
Apply this patch:

```patch
diff --git a/package.json b/package.json
index 3ea4c8c11..de9d5e903 100644
--- a/package.json
+++ b/package.json
@@ -13,10 +13,10 @@
     "start-production": "NODE_ENV=production grunt build && CONFIG_FILES=server/config/local.json,server/config/production.json grunt serverproc:dist",
     "start-remote": "scripts/run_remote_dev.sh",
     "test": "node tests/intern.js --unit=true",
-    "test-circle": "node tests/intern.js --suites=circle --fxaAuthRoot=https://fxaci.dev.lcip.org/auth --fxaEmailRoot=http://restmail.net --fxaOauthApp=https://oauth-fxaci.dev.lcip.org --fxaUntrustedOauthApp=https://321done-fxaci.dev.lcip.org --fxaProduction=true --bailAfterFirstFailure=true",
+    "test-circle": "node tests/intern.js --suites=circle --fxaAuthRoot=https://fxaci.dev.lcip.org/auth --fxaEmailRoot=http://restmail.net --fxaOAuthApp=https://oauth-fxaci.dev.lcip.org --fxaUntrustedOauthApp=https://321done-fxaci.dev.lcip.org --fxaProduction=true --bailAfterFirstFailure=true",
     "test-functional": "node tests/intern.js",
     "test-functional-oauth": "node tests/intern.js --suites=oauth",
-    "test-latest": "node tests/intern.js --fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 --fxaContentRoot=https://latest.dev.lcip.org/ --fxaEmailRoot=http://restmail.net --fxaOauthApp=https://123done-latest.dev.lcip.org/ --fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ --fxaProduction=true --fxaToken=https://token.dev.lcip.org/1.0/sync/1.5",
+    "test-latest": "node tests/intern.js --suites=oauth --fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 --fxaContentRoot=https://latest.dev.lcip.org/ --fxaEmailRoot=http://restmail.net --fxaOAuthApp=https://123done-latest.dev.lcip.org/ --fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ --fxaProduction=true --fxaToken=https://token.dev.lcip.org/1.0/sync/1.5",
     "test-server": "node tests/intern.js --suites=server",
     "test-travis": "node tests/intern.js --suites=travis"
   },
```

run:
> `npm run test-latest -- --grep="Chrome for Android"

"No key bearing scopes" shows in the console:
<img width="1297" alt="screen shot 2018-07-12 at 07 38 10" src="https://user-images.githubusercontent.com/848085/42616617-d9040cd2-85a6-11e8-8537-d0be8e7af7fd.png">


It seems like there are a couple of problems:

1. The test requires correct key bearing scopes
2. If no key bearing scopes are presented, we should surface an error to the UI to help RPs debug
3. The local test needs to use a valid client_id

**Comment by shane-tomlinson** [comment]
Closing this issue as fixed. Thanks @vladikoff!

**Comment by shane-tomlinson** [comment]
This test is still failing on latest even though we fixed it locally, re-opening.

**Comment by vladikoff** [comment]
This passes for me now, fixed by https://github.com/mozilla/fxa-dev/commit/45fce7e99d3d3f491befa9cbb2ff9b85d4251e38

**Comment by shane-tomlinson** [comment]
NNIIICE!
