### ISSUE TITLE
Lockbox name in Devices and apps is strange

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6346]
![image](https://user-images.githubusercontent.com/128755/42516231-91d031fa-842b-11e8-813e-ad1842595ac8.png)

What is "1"?  Not sure!

**Comment by rfk** [comment]
Maybe this is some sort of synthesized name that we made up for the device record, based on the user-agent string?

**Comment by vladikoff** [comment]
from mtg: this should be fixed once we move to the OAuth flow

**Comment by vladikoff** [comment]
> from mtg: this should be fixed once we move to the OAuth flow

🗡
