### ISSUE TITLE
oauth-server errno 119 not added to list of errors in oauth-errors.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6358]
The [OAuth server's errno 119](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/error.js#L273) has not been added to the content-server's [list of errors](
https://github.com/mozilla/fxa-content-server/blob/29c7fb8e473d53d793d85766ccaaaae89dd2a1ab/app/scripts/lib/oauth-errors.js#L90) and will be untranslated for users if it ever occurs.

**Comment by hritvi** [comment]
Hey @shane-tomlinson, is this still a error? Can I work on this?

**Comment by shane-tomlinson** [comment]
@hritvi - you sure can!
