### ISSUE TITLE
Analyze PW strength metrics

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6371]
This experiment is now released to 10% of users, Some rough graphs:

* https://analytics.amplitude.com/mozilla-corp/chart/4b90aw2
* https://analytics.amplitude.com/mozilla-corp/chart/jvwikep

cc @irrationalagent

blocks https://github.com/mozilla/fxa-bugzilla-mirror/issues/425

**Comment by vladikoff** [comment]
waiting for experiment to finish...

**Comment by vladikoff** [comment]
waiting for experiment results...

**Comment by irrationalagent** [comment]
Experiment results logged [here](https://docs.google.com/document/d/1dvpiZ-EAxVDHkXjwekyAougFufUDwB50nT9l9xo177k/edit?ts=5ac3f806#heading=h.nwl6zihubrlw). 

overall a success.

We are rolling out 50%/50% to en locales and 5%/5% de. Should we close this now or wait till full rollout?

**Comment by shane-tomlinson** [comment]
Let's keep this open until we roll out everywhere.

@irrationalagent - I created a new chart for German only users - https://analytics.amplitude.com/mozilla-corp/chart/jvwikep. Looks like German user conversion rates are similar to English. Should we roll this out to 50/50 in Germany too?

100% to English?

**Comment by irrationalagent** [comment]
Germany definitely looks like its heading in the right direction, but it hasn't quite got to the [95% confidence level](https://analytics.amplitude.com/mozilla-corp/chart/yninbt8) that's traditionally the minimum cutoff for significance. But its pretty close. Your call if you want to give it a few more days or just go ahead with 50/50. The fact that we already saw an improvement in English should increase our confidence a bit. 

English still looking strong so I'm a +1 for rolling that one out.

**Comment by irrationalagent** [comment]
Update:  DE looks good to go, en results holding strong, :shipit: IMO

**Comment by rfk** [comment]
analyzed!

**Comment by rfk** [comment]
> Let's keep this open until we roll out everywhere.

Whoops, didn't see this in the meeting earlier, re-opening.

**Comment by rfk** [comment]
From meeting, the final analysis we want to do is to check performance in RTL locales, see https://github.com/mozilla/fxa-content-server/issues/6516 about enabling that in experiment config.

**Comment by shane-tomlinson** [comment]
Blocked waiting for Arabic metrics.

**Comment by vladikoff** [comment]
from mtg: ~4% less well on AR locale. @shane-tomlinson should we roll this out to 100% everywhere?

**Comment by vladikoff** [comment]
@shane-tomlinson move this out of blocked if it's not blocked anymore

**Comment by shane-tomlinson** [comment]
No longer blocked. Rolled out to 100% everywhere in https://github.com/mozilla/fxa-content-server/pull/6563. Closing!
