### ISSUE TITLE
duplicate some "core" use cases to send test email to emailservice.*@restmail.net

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6372]
For some basic set of tests that exercise **all** the emails types that are sent, copy and alter them to use an email address matching `/emailservice.[A-Za-z0-9._%+-]+@restmail.net$/` so the fxa-email-service is used for latest, stable, and stage. CI.

**Comment by jrgm** [comment]
Note: doing this with latest will fail because the latest instance needs to be replaced to pick up the IAM role changes (ec2 instances do not pick up later changes to iam roles). I'll look at doing that tomorrow (and I guess I should do it for stage too).

**Comment by vladikoff** [comment]
from mtg: functional tests for fxa-email-service
