### ISSUE TITLE
action=email goes to /settings instead of some login screen

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6391]
In the Android component we switched to use email-first and with a generated oauth link it opens settings instead of a form to sign in with.

Simplified url seems to be https://accounts.firefox.com/?action=email&email=vlad@restmail.net (if you are already logged in with that it will open settings)

I will follow up with the url the android component generates

**Comment by vladikoff** [comment]
![](http://v14d.com/i/5b58a01ccde00.jpg)

**Comment by shane-tomlinson** [comment]
Already on the case in #6360

**Comment by carolkng** [comment]
Possibly related (although maybe not relevant if the settings page doesn't pop up anymore?): when attempting to sign out and log in again from the /settings page, the login screen shows "Invalid OAuth parameter: client_id".

The url after pressing the signout button is: https://accounts.firefox.com/signin with `context` and `service` query parameters
