### ISSUE TITLE
Emails over 26 characters are not fully visible in the password screen

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6396]
Ref: https://github.com/mozilla/notes/issues/1321

![](https://user-images.githubusercontent.com/31243259/43326790-5cceea7e-91c2-11e8-89f7-4884823f6a68.gif)

**Comment by changecourse** [comment]
One potential approach for handling this has been created with #6507

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/6507

**Comment by shane-tomlinson** [comment]
@ryanfeeley could we get your input on how to handle this?

@farhan787 please follow along here instead of #6965.

**Comment by ryanfeeley** [comment]
Let's revert to the original design which is more robust.
<img width="508" alt="Screen Shot 2019-03-05 at 2 02 36 PM" src="https://user-images.githubusercontent.com/68213/54151229-bfd3b900-4410-11e9-8258-e73d96d0b415.png">

**Comment by farhan787** [comment]
@shane-tomlinson I'm implementing this.

**Comment by shane-tomlinson** [comment]
> Let's revert to the original design which is more robust.

@ryanfeeley thanks for the input, do you want this on mobile, desktop, or both? Any thoughts to https://github.com/mozilla/fxa-content-server/issues/6507?

**Comment by ryanfeeley** [comment]
@shane-tomlinson We would do this for mobile, desktop, apps, web views, whatever. The only difference is the size of the elements. The avatar would go down to 71px. No card layout (as it truncates the email too often)
