### ISSUE TITLE
2FA on Mobile Not Redirecting

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6399]
There has been a report of 2FA not redirecting despite what seems to be successful login (they received an email).

https://twitter.com/daverideout/status/1023968386697576449

(also see Lockbox Slack conversation on July 30th)

Note that Stefan and I have both tested but have not experienced this problem.

Perhaps a starting point here is to look at metrics.

**Comment by davismtl** [comment]
Looks like @irrationalagent [already made a chart.](https://sql.telemetry.mozilla.org/queries/57756/source#150374)
There does seem to be an iOS problem given the success rate is so low.

**Comment by vbudhram** [comment]
Looks like the tweet has been deleted? I've test this with my 2FA production account with Lockbox and didn't experience any issues.

I did notice that after logging in, I received a push notification from the FxiOS application and the screen automatically redirected from the Lockbox settings page (from the Lockbox encryption details page).

**Comment by irrationalagent** [comment]
here is the funnels for each OS all-time:
https://sql.telemetry.mozilla.org/queries/57758/source#150462

You can see that for iPhone there is already a large drop-off between viewing the totp form and engaging with it

**Comment by devinreams** [comment]
I also encountered and reproduced this issue.

Related discourse thread from the same reporting customer: 
https://discourse.mozilla.org/t/lockbox-app-authentication-issue-with-2fa-code/30586/3

**Comment by davismtl** [comment]
@irrationalagent I am puzzled by why the drop off is between engage and submit.

When does the submit event get sent to us? i.e. If it requires the page to redirect for the submit to track, that might explain why we're not tracking it. It would also be a clear symptom of a bug.

**Comment by irrationalagent** [comment]
I should clarify that while there is a larger than expected drop between engage and submit, there is a much bigger drop between view and engage. [i changed the chart to make that more clear](https://sql.telemetry.mozilla.org/queries/57758/source#150462)

**Comment by davismtl** [comment]
@irrationalagent could you segment that iPhone cohort by OS version or region/language or whatever else might be relevant? Clearly some people are succeeding so I want to see how the different segments of iPhone perform.

**Comment by shane-tomlinson** [comment]
I wonder whether the [icon being too big](https://github.com/mozilla/fxa-content-server/issues/6347) prevented a lot of iOS users from finding the submit button to know what to do? A second theory is that [we haven't really solved all of the problems reporting metrics on iOS](https://github.com/mozilla/fxa-content-server/issues/4458). The first seems more likely to me, with train-117 going to prod this week hopefully the rate improves since the [icon was made smaller](https://github.com/mozilla/fxa-content-server/pull/6359).

**Comment by davismtl** [comment]
> I wonder whether the icon being too big prevented a lot of iOS users from finding the submit button

That might explain the overall lower rate. As described in the discourse comment, that may be the problem too since there is no mention on submitting the code so I've reached out to get clarification:

https://discourse.mozilla.org/t/lockbox-app-authentication-issue-with-2fa-code/30586

**Comment by shane-tomlinson** [comment]
> i believe the button said ‘verify’ - and when clicked after entering the code it may have looked a shade darker, but did not move past that screen. however, i would get a ‘successful login’ email anyway.

mmmm....

**Comment by devinreams** [comment]
>i believe the button said ‘verify’ - and when clicked after entering the code it may have looked a shade darker, but did not move past that screen

I had the same experience ☝️

**Comment by irrationalagent** [comment]
we don't have device/model data, for completeness [here's the funnels by locale but they don't vary too much](https://sql.telemetry.mozilla.org/queries/57861/source#150580). 

doesn't explain Devin and above user's problen, but....

it may still be that some users aren't seeing the submit button - it explains (1) the huge drop-off between view and engage, and (2) the bigger-than-expected drop-off between engage and submit (some users enter the code or tap the entry box and generate an engage event but can't submit).

Furthermore, while iPad is still bad, its not as bad as iPhone, which makes me think the larger display may have allowed more of those users to actually see or access the button. m2c.

**Comment by vbudhram** [comment]
@irrationalagent I re-ran https://sql.telemetry.mozilla.org/queries/57758/source#150379 and limited it to just September and it appears to have a roughly 5% better success rate than previous month. However, it is still significantly lower than android and other clients.

When testing on my iOS device, there does appear to be 2-3 second delay after submitting the 2FA code where the verify button is dark blue and appears that nothing is happening. It could be possible that users are not waiting for this to complete?

@ryanfeeley What are your thoughts on putting a spinner on this button while the request completes.

**Comment by ryanfeeley** [comment]
@vbudhram Definitely use our button spinner if the delay is longer than a second. This is loosely spelled out on our designing for performance guidelines. https://design.firefox.com/photon/introduction/design-for-performance.html

**Comment by vbudhram** [comment]
@irrationalagent Is it possible to see how many [invalid codes](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/auth-errors.js#L472) are entered for iOS users before a successful login when compared to other platforms?

@ryanfeeley There seems to be some inconsistencies with the spinner when testing locally (no delay, and spinner works) vs in production (intermittent delay). Any fixes probably won't make this train, so I'll bump to 122 and investigate more.

**Comment by irrationalagent** [comment]
@vbudhram I don't see that 1054 error code in the re:dash flow data, probably because it is coming from the content server. [would any of the auth server events like this](https://github.com/mozilla/fxa-auth-server/blob/67b70534d0e712a8f34515a94e55fe3a935e503b/lib/error.js#L777) be usable for the same purpose, since those get to re:dash? [you can see a list of the events related to totp here](https://github.com/mozilla/fxa-auth-server/blob/67b70534d0e712a8f34515a94e55fe3a935e503b/lib/error.js#L777)

**Comment by vbudhram** [comment]
@irrationalagent Looks like that endpoint doesn't return an explict error when it is an invalid code, it return `false` and logs `totpToken.unverified`, ref https://github.com/mozilla/fxa-auth-server/blob/67b70534d0e712a8f34515a94e55fe3a935e503b/lib/routes/totp.js#L333. 

If a user got `route./session/verify/totp.400.155`, this means that somehow they are trying to verify a code but they never created a TOTP token.

**Comment by irrationalagent** [comment]
@vbudhram [here's a chart looking at `totpToken.unverified`](https://sql.telemetry.mozilla.org/queries/58981/source#152784) for the percentages, the denominator is the number of flows hitting the totp input screen during signin. It doesn't appear that `iphone` is that much worse than windows 10 or android.

**Comment by rfk** [comment]
@vbudhram I wonder if this might be related to https://github.com/mozilla/fxa-content-server/pull/6630 ?
