### ISSUE TITLE
Merge warning dialog still displayed after all the options from disconnect was checked

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6430]
Environment:
Stage server - Train 118
Win 10x64

STR:
1. Log in an account on Desktop;
2. Gp to Menu->Disconnect;
3. Check both options: remove Firefox sync data and remove other private data;
4. Tap on "Disconnect&Delete";
5. Sign in with a different account.

Actual results:
A merge warning dialog is displayed: 
"Are you sure you want to sign in to Sync?
A different user was previously signed in to Sync on this computer. Signing in will merge this browser’s bookmarks, passwords and other settings with x mail."

Expected results:
No dialog is displayed.

Screenshot: https://i.imgur.com/xL2blyF.png

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - The merge warning is displayed from within the browser and we are unable to fix the problem from the FxA side. Can you file this in Bugzilla under the [Firefox->Sync component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Sync)?
