### ISSUE TITLE
"signin token code" failures on latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6435]
4 signin token code functional tests always fail on teamcity:

* verified - treatment-code - invalid code
* verified - treatment-code - valid code
* verified - treatment-code - valid code then click back
* verified - treatment-link - open link new tab

https://tc-test.dev.lcip.org/viewLog.html?buildId=41038&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

https://screencap.co.uk/images/5999146a920f6e91d882fee4b1384ff4705a3e58.png

It looks like the token codes are not asked for, rather the UI redirects back to the OAuth app before before the code is entered.

cc @vbudhram - on latest the regexp to force signin confirmation is `^(sync.*@restmail\.net)$`, the tests [use a non-Sync address](https://github.com/mozilla/fxa-content-server/blob/fb9267dcd8654ff038976b395f313080b438f1ba/tests/functional/sign_in_token_code.js#L43). Would that cause this problem?

**Comment by shane-tomlinson** [comment]
Re-opening, still failing.

**Comment by vbudhram** [comment]
This is no longer failing! Fixed in https://github.com/mozilla/fxa-content-server/pull/6490
