### ISSUE TITLE
Circle reports "Your config file has errors and may not run correctly

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6438]
From https://circleci.com/gh/mozilla/fxa-content-server/11076:

> jobs: build: docker: 0: extraneous key [env] is not permitted

![screen shot 2018-08-13 at 12 37 08](https://user-images.githubusercontent.com/848085/44029589-bc17e3e2-9ef5-11e8-9e1e-ea7ac4ef0ccf.png)

**Comment by vladikoff** [comment]
I think we can maybe remove 'env'

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-content-server/commit/6738986af70394279b5ad0f749daa8564c601fd1
