### ISSUE TITLE
[Account recovery] Message from Re-enter password screen not centered

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6439]
Environment:
Win10x64, Android, staging server

STR:
1. On Manage account section, go to Account recovery; 
2. Tap on "Add" -> "Generate" -> Pay attention to 're-enter password' modal;

Expected results: 'Enter your password to view your recovery key' message is displayed without visual issues compared with the other fields/buttons from the page.

Actual results:  'Enter your password to view your recovery key' message is left aligned and not centered. 

Desktop:
![2018_08_13_13_59_47__account_recovery_firefox_nightly](https://user-images.githubusercontent.com/24588037/44031052-67c679c8-9f0b-11e8-8bb1-27ae9d3714a1.png)

Mobile - portrait view: 
![screenshot_2018-08-13-15-13-32](https://user-images.githubusercontent.com/24588037/44031125-ac3f7758-9f0b-11e8-9fb3-43ecfb5e338d.png)

Mobile- landscape view:
![screenshot_2018-08-13-15-18-58](https://user-images.githubusercontent.com/24588037/44031327-4e3086a6-9f0c-11e8-9d54-f493e55a8c93.png)

**Comment by shane-tomlinson** [comment]
@hritvi - this would be a good one to start to see how the stylesheet processing is done. Shouldn't be too complex. If you need help let me know!

**Comment by hritvi** [comment]
Thanks @shane-tomlinson for assigning the issue. I am working on it.

**Comment by hritvi** [comment]
I am not able to find the account recovery section in manage accounts. Can you provide a link for that. Thanks in advance.

**Comment by hritvi** [comment]
@shane-tomlinson I have made a PR for the issue. But I had to stop the server with <code>killall node</code>. While searching for stop script in package.json, I found that it does not have any stop script written. Should I file an issue for that or am I missing something?

**Comment by shane-tomlinson** [comment]
> I found that it does not have any stop script written. Should I file an issue for that or am I missing something?

How are you running the servers? If using `npm start` from the content-server directory, all you have to do is hit CTRL-C in the console with the server. If you are using [fxa-local-dev](https://github.com/mozilla/fxa-local-dev), the `pm2` utility is used to control all interactions with all the servers, to stop all the servers you can do a `pm2 kill`. fxa-local-dev [has pretty good pm2 usage docs in it's README.md](https://github.com/mozilla/fxa-local-dev/blob/master/README.md).

**Comment by hritvi** [comment]
I started the server using <code>npm run start-remote</code> and even after CTRL-C the server was running on port 3030

**Comment by shane-tomlinson** [comment]
> I started the server using npm run start-remote and even after CTRL-C the server was running on port 3030

Ohh, start-remote is one I hadn't considered. I'll have a look, there's a good chance you found a bug!

**Comment by hritvi** [comment]
May I resolve this bug?

**Comment by shane-tomlinson** [comment]
> May I resolve this bug?

You can, if you get stuck let me know!

**Comment by hritvi** [comment]
I suppose writing a stop script would do the task. 
Could you explain me in brief what does this [commit](https://github.com/mozilla/fxa-content-server/commit/8fc2b8cbd0be97b12a2b1d0f7a688f38016f003f) does? Thanks in advance.

**Comment by shane-tomlinson** [comment]
> I suppose writing a stop script would do the task. We could call the script using npm stop
> Could you explain me in brief what does this commit does? Thanks in advance.

A stop script isn't really needed, rather the [start script is out of date](https://github.com/mozilla/fxa-content-server/blob/8aa7f7154fc3f816b71ef2321bf60038b68b88a0/scripts/run_remote_dev.sh#L10). We no longer use `grunt sass` and `grunt watch`, so that line can be removed. 

On lines 7, the `& MH=$!` is only there to put the server process in the background so that `grunt sass watch` can be called. Because line 10 is removed, that portion of line 7 can be removed. And because that portion of lines 7 can be removed, line 12 can be removed.

P.S. I wrote that before you suggested that you could work on it. I didn't want to steal your thunder so never opened a PR with that fix.
