### ISSUE TITLE
[Account recovery] Visual issues with Download and Print buttons

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6440]
Environment:
Win10x64, Android 8.0.0
Staging server - Train 118

STR:
1. Go to Manage account and generate a new recovery key;
2. Pay attention to download and print buttons.

Results: the text is out of the box and is duplicate.

Screenshot:
![2018_08_13_16_08_14_firefox_accounts_firefox_buttons](https://user-images.githubusercontent.com/24588037/44033858-55fa6868-9f14-11e8-9636-bd98f04dfabf.png)

**Comment by SorinaFlorean** [comment]
This is still reproducible on Train 119.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Stage server - Train-120.
