### ISSUE TITLE
Enhancement: change "Add" button with "Enable" from Account recovery section

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6452]
Environment: 
Android, Win

Steps to reproduce:
1. Go to Manage account and pay attention to Account recovery section.

Reason: we don't add a new picture or secondary email, we "set" a recovery key to help us to don't lose information when we forgot our password, so my opinion is that "Enable" is more accurate. And this probably will not create confusion that we have to add a new account for the existing one.

![image](https://user-images.githubusercontent.com/24588037/44090572-492f1402-9fd3-11e8-987f-9bd4fbda5c75.png)

**Comment by ryanfeeley** [comment]
👍
