### ISSUE TITLE
Implement channel server client & state machine

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6454]
This is to connect to https://github.com/mozilla-services/pairsona/tree/chatty
https://github.com/mozilla-services/pairsona/pull/9

The client will need to connect to a WebChannel server and maintain connection state.
I'm unsure of how to handle disconnection/re-connect logic at this point and have deferred.

**Comment by shane-tomlinson** [comment]
To be defined:

1. The format of the messages coming from the channel server. We know packets will contain at least a few bits of data - location info of the sending client, encrypted data sent by sending client.
2. Disconnect/reconnect logic. If the connection drops, do we auto-reconnect? The connection is dropped by the server to all clients if one client disconnects.
3. How to surface the channel server endpoint config to the client.

cc @jrconlin, @rfk

**Comment by rfk** [comment]
> Disconnect/reconnect logic. If the connection drops, do we auto-reconnect?
> The connection is dropped by the server to all clients if one client disconnects.

My gut feeling is we should abort what we're doing in this case, either showing an error or returning to a previous screen so the user can try again.

**Comment by shane-tomlinson** [comment]
> My gut feeling is we should abort what we're doing in this case, either showing an error or returning to a previous screen so the user can try again. (The probability of disconnection should be small in practice since we intend the connections to be short-lived.)

That's the approach I'm taking now. 💯

**Comment by shane-tomlinson** [comment]
Fixed by #6641, closing.
