### ISSUE TITLE
Disabling sign-in confirmation

### ISSUE THREAD

**Issue by nicolasmeric** [mozilla/fxa-content-server#6458]
Hi.
I would like to disable sign-in confirmation for newly-created accounts using self-hosted fxa-account-server and fxa-auth-server.

fxa-content-server web interface asks for email confirmation even if skipForNewAccounts configuration parameter is enabled in fxa-auth-server configuration.

Is this the expected behavior ? What have I missed ?

I'm using fxa-auth-server 1.118.0 and fxa-content-server 1.118.1.

**Comment by philbooth** [comment]
Hmm, I'm only eyeballing the code but that looks like it should work, unless maybe your customs server instance is flagging it as a suspicious request. Did you try changing any other settings round there, like `skipForNewAccounts.maxAge` for instance?

On thing you could try I guess is to set `allowedEmailDomains` or `allowedIPs` in your config for `fxa-customs-server`. But tbh I feel like I'm missing something more fundamental here, hopefully someone else has another suggestion...

**Comment by nicolasmeric** [comment]
Thanks for your answer.

I use the default maxAge value, which is 4 hours. Changing it to 0 didn't disable the email confirmation.

I do not find  any allowedEmailDomains or allowedIPs options neither in server/lib/configuration.js for fxa-content-server, nor in config/index.js for fxa-auth-server

**Comment by philbooth** [comment]
> I use the default maxAge value, which is 4 hours. Changing it to 0 didn't disable the email confirmation.

Sorry, I should have been clearer, does it make any difference if you change it to something much bigger like `"1 year"`?

> I do not find any allowedEmailDomains or allowedIPs options neither in server/lib/configuration.js for fxa-content-server, nor in config/index.js for fxa-auth-server

They're settings for a different service, `fxa-customs-server`, which is called by the auth server to rate-limit/block traffic. Not sure how you set up your FxA stack / if you have it running, but worth checking if it's there.
