### ISSUE TITLE
Add a QR code scanning capabilty to the pairing flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6464]
The pairing flow currently assumes the QR code displayed by the auth will be scanned by a QR code scanner built into the browser. Since Fenix isn't yet built and we have no idea whether it'll have a QR code scanner to begin with, we should build the functionality ourselves so we can demo what the flow could look like end to end.

**Comment by shane-tomlinson** [comment]
This needs some UX.

**Comment by hritvi** [comment]
Can u explain what kind of UX this needs @shane-tomlinson and can I work on this issue? Thanks in advance:)

**Comment by rfk** [comment]
@shane-tomlinson given that @vladikoff has a working demo app with a built-in scanner, and that it's possible to use a third-party scanner to trying this out, is there any value in keeping this issue open or should we just close it?

**Comment by shane-tomlinson** [comment]
🗡
