### ISSUE TITLE
"Unexpected Error" in Circle tests whenever confirming 2FA tokens

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6478]
See https://screencap.co.uk/images/52d5fcc3b3fce7e8bdd7f825f09725ae1e0c0ee9.png from https://circleci.com/gh/mozilla/fxa-content-server/11607

cc @vbudhram

**Comment by shane-tomlinson** [comment]
In the auth-db, I see:

>  in the auth-db I see {"Timestamp":1535034134873000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":4,"Pid":5,"EnvVersion":"2.0","Fields":{"code":404,"route":"gettotpid","method":"GET","path":"/totp/97cf9ab7dc094b788aba8472a5897933","err":"Error: Not Found","t":2}}

**Comment by vladikoff** [comment]
[11:05:38]  <vladikoff>	vbudhram, stomlinson, i see a `{"Timestamp":1535021851903000000,"Logger":"fxa-auth-server","Type":"server.EndpointError","Severity":2,"Pid":5,"EnvVersion":"2.0","Fields":{"op":"server.EndpointError","message":"127.0.0.1:8000 error: request timed out","reason":"socket hang up","method":"POST"}}`

**Comment by vbudhram** [comment]
It looks like the requests completed, but the auth-server closed the connection before they were done

```
{"Timestamp":1535038624265000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":7,"EnvVersion":"2.0","Fields":{"code":200,"route":"gettotpid","method":"GET","path":"/totp/b16410f8602249e49cd51c7debbf8861","t":1}}
{"Timestamp":1535038624295000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":7,"EnvVersion":"2.0","Fields":{"code":200,"route":"posttotpidupdate","method":"POST","path":"/totp/b16410f8602249e49cd51c7debbf8861/update","t":17}}
{"Timestamp":1535038632708000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":7,"EnvVersion":"2.0","Fields":{"code":200,"route":"postaccountidrecoverycodes","method":"POST","path":"/account/b16410f8602249e49cd51c7debbf8861/recoveryCodes","t":8392}}
```

When adding TOTP, we perform scrypt for each of the recovery codes (8 total). Anything landed that might change the performance of these?

**Comment by shane-tomlinson** [comment]
From IRC:

> it seems like there are multiple problems. 
> 1) the timeout is too short. 
> 2) It seems like the user should be notified if the creation fails (socket hangup), 
> 3) a Not Found error when fetching the user's totp codes is translated to a 500/unexpected error instead of something usable.

**Comment by shane-tomlinson** [comment]
> 3. a Not Found error when fetching the user's totp codes is translated to a 500/unexpected error instead of something usable.

@vbudhram pointed out that the Not Found could be coming from another endpoint calling getTotpToken and that the problem could be caused by scrypt taking too long. We have bumped the poolee timeout to 15s because we saw `socket hang up`.

If there is a problem when calling the customs server, the auth server translates the error to a [backendServiceFailure](https://github.com/mozilla/fxa-auth-server/blob/e504e391294ebf5c150cea109c2e75a476e92215/lib/error.js#L818). It seems if the connection to the DB times out, this would be a reasonable error to surface here too.

**Comment by shane-tomlinson** [comment]
So the root problem comes from the instance being throttled by Amazon. @jbuck changed the instance type so that credit isn't a problem but suggests we should move to a larger box once we understand the usage patterns a little bit better.

Closing as fixed, I'm going to open a separate issue on the auth server suggesting the "socket hangup" error be converted to a "backend service error" to be displayed to the user instead of "unexpected error".

Thanks @vbudhram, @vladikoff and @jbuck!
