### ISSUE TITLE
tests: failed to generate profile for this config

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6487]
@shane-tomlinson could you check with the latest firefox-profile update I get the following: 

```
➜  fxa-content-server git:(master) npm run test-functional-oauth -- --grep="user signed in locally"

> fxa-content-server@1.119.2 test-functional-oauth /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> node tests/intern.js --suites=oauth "--grep=user signed in locally"

Creating Firefox profile...
Note: Failed to generate a Firefox profile for this configuration.
Listening on localhost:9090 (ws 9077)
Tunnel started
BUG: suiteEnd was received for invalid session 
```

do you get the same?

**Comment by shane-tomlinson** [comment]
@vladikoff - did you `npm install`? I saw that when using the old version with the new code, here's what i get now:

> ➜  fxa-content-server git:(master) ✗ npm run test-functional-oauth -- --grep="user signed in locally"                                                  git:(master|✚1

> fxa-content-server@1.119.3 test-functional-oauth /Users/shanetomlinson/development/fxa-content-server
> node tests/intern.js --suites=oauth "--grep=user signed in locally"

Creating Firefox profile...
Listening on localhost:9090 (ws 9077)
Tunnel started

‣ Created remote session firefox on darwin 17.7.0 (6e115d16-e202-5140-8c54-5c4f9dc11458)
~ firefox on darwin 17.7.0 - oauth email first - signup (grep)
~ firefox on darwin 17.7.0 - oauth email first - signin verified (grep)
~ firefox on darwin 17.7.0 - oauth email first - signin unverified (grep)
~ firefox on darwin 17.7.0 - oauth email first - email specified by relier, not registered (grep)
~ firefox on darwin 17.7.0 - oauth email first - login_hint specified by relier, not registered (grep)
~ firefox on darwin 17.7.0 - oauth email first - email specified by relier, registered (grep)
~ firefox on darwin 17.7.0 - oauth email first - login_hint specified by relier, registered (grep)
~ firefox on darwin 17.7.0 - oauth email first - login_hint specified by relier, registered, user changes email (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached Sync credentials (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached Sync credentials, user changes email (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached Sync credentials, login_hint specified by relier (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached Sync credentials, login_hint specified by relier, user changes email (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached OAuth credentials (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached OAuth credentials, login_hint specified by relier (grep)
~ firefox on darwin 17.7.0 - oauth email first - cached OAuth credentials, login_hint specified by relier, user changes email (grep)
✓ firefox on darwin 17.7.0 - Firefox desktop user info handshake - OAuth flows - OAuth signin page - user signed into browser, no user signed in locally (1.896s)
✓ firefox on darwin 17.7.0 - Firefox desktop user info handshake - OAuth flows - OAuth signin page - user signed into browser, user signed in locally (5.201s)
~ firefox on darwin 17.7.0 - oauth choose redirect - get client_id for other tests (grep)
~ firefox on darwin 17.7.0 - oauth choose redirect - oauth endpoint redirects to signup with an unregistered email (grep)
~ firefox on darwin 17.7.0 - oauth choose redirect - oauth endpoint redirects to signin with a registered email (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - service specified (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - invalid access_type (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid access_type (offline) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid access_type (online) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - missing client_id (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - empty client_id (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - space client_id (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - invalid client_id (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - unknown client_id (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - empty prompt (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - space prompt (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - invalid prompt (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid prompt (consent) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - invalid redirectTo (url) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid redirectTo (url) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - invalid redirect_uri (url) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid redirect_uri (url) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - missing scope (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - empty scope (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - space scope (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - no valid scopes (untrusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid scope (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - valid scope (untrusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with no action (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with signin (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with force_auth with no email (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with unknown action (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with force_auth (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth query parameter validation - authorization with email (trusted) (grep)
~ firefox on darwin 17.7.0 - oauth signin - with missing client_id (grep)
~ firefox on darwin 17.7.0 - oauth signin - with missing scope (grep)
~ firefox on darwin 17.7.0 - oauth signin - with invalid client_id (grep)
~ firefox on darwin 17.7.0 - oauth signin - with service=sync specified (grep)
~ firefox on darwin 17.7.0 - oauth signin - verified (grep)
~ firefox on darwin 17.7.0 - oauth signin - verified using a cached login (grep)
~ firefox on darwin 17.7.0 - oauth signin - unverified, acts like signup (grep)
~ firefox on darwin 17.7.0 - oauth signin - unverified with a cached login (grep)
~ firefox on darwin 17.7.0 - oauth signin - oauth endpoint chooses the right auth flows (grep)
~ firefox on darwin 17.7.0 - oauth signin - verified, blocked (grep)
~ firefox on darwin 17.7.0 - oauth signin - verified, blocked, incorrect password (grep)
~ firefox on darwin 17.7.0 - oauth signin - signin in Chrome for Android, verify same browser (grep)
~ firefox on darwin 17.7.0 - oauth - TOTP - can add TOTP to account and confirm oauth signin (grep)
~ firefox on darwin 17.7.0 - oauth - TOTP - can remove TOTP from account and skip confirmation (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, verify same browser (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup in Chrome for Android, verify same browser (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, verify same browser with original tab closed (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, verify same browser by replacing the original tab (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, verify different browser - from original tab's P.O.V. (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, verify different browser - from new browser's P.O.V. (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup with existing account, coppa is valid (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup with existing account, coppa is valid, credentials are wrong (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup with existing account, coppa is empty (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup with existing account, coppa is empty, credentials are wrong (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup with existing account, coppa is too young (grep)
~ firefox on darwin 17.7.0 - oauth signup - signup, bounce email, allow user to restart flow but force a different email (grep)
~ firefox on darwin 17.7.0 - oauth reset password - reset password, verify same browser (grep)
~ firefox on darwin 17.7.0 - oauth reset password - reset password, verify same browser with original tab closed (grep)
~ firefox on darwin 17.7.0 - oauth reset password - reset password, verify same browser by replacing the original tab (grep)
~ firefox on darwin 17.7.0 - oauth reset password - reset password, verify in a different browser, from the original tab's P.O.V. (grep)
~ firefox on darwin 17.7.0 - oauth reset password - reset password, verify in a different browser, from the new browser's P.O.V. (grep)
~ firefox on darwin 17.7.0 - oauth settings clients - rp listed in apps, can be deleted (grep)
~ firefox on darwin 17.7.0 - oauth force_auth - with a registered email (grep)
~ firefox on darwin 17.7.0 - oauth force_auth - with an unregistered email (grep)
~ firefox on darwin 17.7.0 - oauth force_auth - verified, blocked (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin verified (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - re-signin verified, no additional permissions (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin unverified, acts like signup (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signup, verify same browser (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signup, then signin with no additional permissions (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin from signup page (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin with new permission available b/c of new account information (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin with additional requested permission (grep)
~ firefox on darwin 17.7.0 - oauth permissions for untrusted reliers - signin after de-selecting a requested permission (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - signup without `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - signup with `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - signin without `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - signin with `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - signin without `prompt=consent`, then re-signin with `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - force_auth without `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - oauth permissions for trusted reliers - force_auth with `prompt=consent` (grep)
~ firefox on darwin 17.7.0 - signin with OAuth after Sync - signin to OAuth with Sync creds (grep)
~ firefox on darwin 17.7.0 - signin token code - verified - control (grep)
~ firefox on darwin 17.7.0 - signin token code - verified - treatment-code - valid code (grep)
~ firefox on darwin 17.7.0 - signin token code - verified - treatment-code - valid code then click back (grep)
~ firefox on darwin 17.7.0 - signin token code - verified - treatment-code - invalid code (grep)
~ firefox on darwin 17.7.0 - signin token code - verified - treatment-link - open link new tab (grep)
TOTAL: tested 1 platforms, 2 passed, 0 failed, 104 skipped
➜  fxa-content-server git:(master) ✗

**Comment by vladikoff** [comment]
Seems fine on a different machine, closing for now
