### ISSUE TITLE
None of the 'oauth email first' tests are working on latest/TeamCity

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6489]
to reproduce run: 

```
npm run test-latest -- --suites=oauth --grep="cached Sync credentials"

```

Ref: https://tc-test.dev.lcip.org/viewLog.html?buildId=41539&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=1815

it all goes to 

<img src=https://screencap.co.uk/images/18a00d9eb485ce3e7f2840a05e7194e59b47f899.png width=450 />

**Comment by vladikoff** [comment]
cc @shane-tomlinson any ideas?

**Comment by shane-tomlinson** [comment]
Dup of #6493 which has more context.
