### ISSUE TITLE
[Account recovery] Generate a new recovery key is displayed when setting a new password for Pocket

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6492]
Environment:
Win10
Stage server - Train 119

Steps to reproduce:
1. Enable Account recovery for the account;
2. Go to https://getpocket.com/login?e=4 and tap on "Login with Firefox";
3. From "Sign in to Pocket" screen choose "Forgot password?" and send an email to reset the password;
4. Go to email and create a new password;
5. Pay attention to the screen after the password was successfully changed.

Actual results: "Generate a new recovery key" option is available and tapping on it opens "re-enter password" screen in order to generate a key.

Expected results: "Generate a new recovery key" option is not available and is not displayed. 

Note: The key wasn't used and the password wasn't changed for the account. 

![2018_08_23_15_33_27_your_password_has_been_reset-pocket](https://user-images.githubusercontent.com/24588037/44573013-30c1c500-a78e-11e8-8008-428f714fefc1.png)

**Comment by vbudhram** [comment]
@SorinaFlorean This definitely should not have appeared. Assigning myself for a fix this train.

**Comment by vbudhram** [comment]
From slack wit sorina:

* I wasn't able to reproduce this on stage because I couldn't login with Pocket there
* On stage when using sync account with recovery key enabled, but resetting without recovery key, does not show the button

**Comment by SorinaFlorean** [comment]
I will investigate more when the stage - train 121 is available for testing. Tried to reproduce today but the field wasn't displayed. I will close this and if is reproducible on Production/stage I will open again.
