### ISSUE TITLE
Failing functional tests on teamcity - OAuth email first

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6493]
[The change on fxa-dev to enable signin confirmation for new accounts the default](https://github.com/mozilla/fxa-dev/commit/994ca44e1f221ffd1db5cd17deb7e8efabe82a4c) caused the tests against [latest to bust on teamcity](https://tc-test.dev.lcip.org/viewLog.html?buildId=41576&tab=buildResultsDiv&buildTypeId=fxa_LatestFirefoxBetaTests) because the tests do not expect signin confirmation.

**Comment by vladikoff** [comment]
@shane-tomlinson do we need the same setting flipped in stage?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do we need the same setting flipped in stage?

If we run the functional tests against stage, yeah.
