### ISSUE TITLE
Accounts page takes time to load 

### ISSUE THREAD

**Issue by hritvi** [mozilla/fxa-content-server#6494]
https://accounts.firefox.com/settings takes some time to load even after the site is loaded. 
We can add a preloader to fix that.
![fxa](https://user-images.githubusercontent.com/32164618/44580442-8e1e3c00-a7b7-11e8-85e7-cd0470ae83c3.gif)

**Comment by shane-tomlinson** [comment]
I believe this is a dup of https://github.com/mozilla/fxa-content-server/issues/3374

**Comment by hritvi** [comment]
Oh i see. But still the issue is not resolved yet. Was'nt this [PR](https://github.com/mozilla/fxa-content-server/pull/3564) supposed to resolve the issue?

**Comment by shane-tomlinson** [comment]
>  Wasn't this PR supposed to resolve the issue?

Looks like that's broken again.

**Comment by philbooth** [comment]
@shane-tomlinson can you triage out of the backlog as necessary?

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/3374
