### ISSUE TITLE
Enhancement: only one email when the password is changed

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6497]
Environment:
Train 118, stage server

Steps to reproduce: reset the password using the recovery key. Go to email.

Actual results: 2 emails are received, one informing that the password was changed using recovery key and one email that the password was changed.

Expected: only one email received, that the password was changed using the recovery key.
The other email is more accurate for the times when we change without a key.

**Comment by hritvi** [comment]
Can I work on this issue?

**Comment by hritvi** [comment]
Should I wait for the [PR](https://github.com/mozilla/fxa-js-client/pull/283/files) to get merged? Or may I pull [add-accountResetWithRecoveryKey](https://github.com/mozilla/fxa-js-client/tree/add-accountResetWithRecoveryKey) and then start my work?

**Comment by hritvi** [comment]
Isn't the function [here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/account.js#L1414) also needs to be changed to accept the options param?
