### ISSUE TITLE
Add "recovery key previously generated" message where applicable 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6498]
If we generate a new recovery key when we change the password or from Manage account page, when we go to email and choose "create new recovery key" an "unexpected error" message is displayed. And the user is not informed that the key was already generated.

**Comment by vbudhram** [comment]
@SorinaFlorean Thanks for report! I updated this to be a bug because we should show a proper error message for this.

**Comment by vbudhram** [comment]
from mtg: Prioritizing this for next train
