### ISSUE TITLE
Create icon for Lockbox in Device and Service Manager

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6504]
Currently, in device manager, Lockbox looks like a desktop or mobile device. Can we consider giving it its own icon like AMO?

![screen shot 2018-08-27 at 10 09 38](https://user-images.githubusercontent.com/19537086/44674179-98bc1980-a9e1-11e8-9266-ca484a90aab3.png)

**Comment by davismtl** [comment]
CC @ryanfeeley

**Comment by vladikoff** [comment]
@davismtl we have one https://github.com/mozilla/fxa-content-server/blob/master/app/images/icon-service-lockbox.svg

**Comment by davismtl** [comment]
Oh great. Is this issue a duplicate then? Or leave it open to roll it out?

**Comment by rfk** [comment]
When Lockbox finishes transitioning over to use the OAuth flow they should start getting this icon by default; right now they use the same login flow as desktop so they get the same icon.

I believe the current beta uses OAuth, @davismtl could you try it out and see if it behaves as you expect?

**Comment by devinreams** [comment]
I see it! 🤘 

![d5cc8782-6c26-435f-aaf2-0fa71e818612](https://user-images.githubusercontent.com/49511/44726682-83082c00-aa95-11e8-81e6-ca299ce0cbc3.jpeg)

**Comment by devinreams** [comment]
@changecourse is this (still) the proper rounded version of the lock icon? 👆

I know it shifted slightly but don’t quite have the eye to tell.

**Comment by changecourse** [comment]
Double checked the source, and the corners for that icon are good. 

There's definitely a mix in terms of levels of fidelity when it comes to the various icons presented in the Devices list, which would be worth considering standardization in a follow-up issue.
