### ISSUE TITLE
Create an icon for TVs in Device and Service manager

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6506]
With Firefox on the Fire TV, we should have a TV icon in the Device and Service manager. Follow on from #6503.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Should this have a Fire or amazon logo on it?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I think a generic TV would be great to start with. If you have one with a FireTV or Amazon logo, I'd take both. :D

**Comment by vladikoff** [comment]
Let's revisit this once we actually have this integration
