### ISSUE TITLE
Is tests/tools/firefox_profile.js passing the config to firefox_profile_creator.js in a form the latter expect?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6513]
@vladikoff. I happened to notice something I don't get, so I'll ask.

At https://github.com/mozilla/fxa-content-server/blob/master/tests/tools/firefox_profile.js#L13

the config is JSON.stringify'd twice and put on the command line for 

https://github.com/mozilla/fxa-content-server/blob/master/tests/tools/firefox_profile_creator.js#L13

to JSON.parse once, getting a `String` value.

At https://github.com/mozilla/fxa-content-server/blob/master/tests/tools/firefox_profile_creator.js#L26 etc., properties like `fxaContentRoot` are referenced on that `String`, and those values are `undefined`, which is then coerced into `undefinedforce_auth?service=...`.

Am I misreading how this works.

**Comment by jrgm** [comment]
.. or maybe this is just insulating it from shell interpolation?

**Comment by vladikoff** [comment]
we can refactor this in the future, we don't need to spawn a process for the profile anymore
