### ISSUE TITLE
Firefox slow to become verified

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6524]
I noticed that Firefox (release) appears to be much slower to convert to verified state after email verification than it previously was. Now long enough for users to think that it didn't work.

STEPS TO REPRODUCE
1. Launch a fresh profile and register an account
1. Verify the email in any browser or device
1. You will see the Connect Another Device page

EXPECTED RESULTS
* Firefox within 3 seconds Firefox shows a notification to say that syncing will begin momentarily
* Firefox will go from unverified state to verified state within 3 seconds

ACTUAL RESULTS
* Firefox takes between 23 seconds to one minute to enter the verified state

**Comment by rfk** [comment]
May be related to devices failing to register a push endpoint:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1489294

(Although I've only seen the above bug in Nightly, not Release).  @ryanfeeley any chance you have some about:sync-log logs from the device where this failed, which you could share privately for me to check whether it's the same issue?

**Comment by rfk** [comment]
If that is the cause, then it may also indicate a bug in Firefox: if it fails to register its push endpoint, then it should poll for verification status more aggressively so that it doesn't take a minute to detect.

**Comment by shane-tomlinson** [comment]
cc @mhammond

**Comment by rfk** [comment]
@ryanfeeley has this improved now that we fixed a hotfix for the device registration issue?

**Comment by rfk** [comment]
It seems to be working correctly in a quick test I did just now, so I'm going to tentatively declare this fixed.
