### ISSUE TITLE
iOS - 2FA doesn't work after a password change 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6525]
Server: 
Staging - Train 120
NR on Production.

STR:
1. Log in on an iOS device and on desktop with the same account.
2. Enable 2FA.
3. Reset/change the password in Manage account, from the desktop browser.
4.  Re-connect to sync on the iOS device.

Expected result:
2FA code is required to complete the login. The user is logged in.

Actual results:
2FA code isn't verified. No success/error message displayed. The 2FA page doesn't redirect the user to his sync account.
You can tap Done and return to the app, the account looks like it's connected, but there are sync errors. 
[sync errors after 2FA verification.txt](https://github.com/mozilla/fxa-content-server/files/2360303/sync.errors.after.2FA.verification.txt)

**Comment by vbudhram** [comment]
Hey @sv-ohorvath Thanks for report! 

I wonder if we should revoke all existing sessions when 2FA is added to an account. This should in theory require all accounts to re-authenticate.  Additionally, iOS should also have surfaced these sync errors to the user or logged them out as well.

**Comment by vbudhram** [comment]
@sv-ohorvath To confirm, in Step 2, you enabled 2FA on the desktop device correct?

**Comment by sv-ohorvath** [comment]
@vbudhram Yes, that is correct.

**Comment by rfk** [comment]
> 4. Re-connect to sync on the iOS device.

It's not clear to me what happens at step 4 here.  Did the iOS device get disconnected from sync when you enabled 2FA on the account?  Or did you explicitly disconnect and reconnect?

**Comment by rfk** [comment]
Oh, my bad, the password change would have disconnected the iOS device from sync, makes sense 👍
