### ISSUE TITLE
 Verify your account" message takes longer to disappear than before

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa-content-server#6526]
Server:
Staging & Production
Win 10 x64.

STR: 
1. Log in with a sync account on desktop.
2. Open the email link to verify the account.
3.  Wait for the "verify your account" message to disappear in the hamburger menu & in about:preferences.

Expected results: The warning used to disappear almost instantly after the account verification.

Actual results: 
It takes several seconds / a minute for the message to disappear.

**Comment by shane-tomlinson** [comment]
Thanks for the report @sv-ohorvath, this was also reported in https://github.com/mozilla/fxa-content-server/issues/6524 where there is a bit more discussion. Closing this one.
