### ISSUE TITLE
email first flow does not block firefox.com domains

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6530]
Noticed this while debugging #6528 

https://github.com/mozilla/fxa-content-server/blob/88fa20fd157637f7518498bc65d998aa2649c15a/app/scripts/views/sign_up.js#L143

blocks #6125 
blocks #6527

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/6027
