### ISSUE TITLE
Add mozilla.org accounts to allowed CORS origins

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6535]

**Comment by shane-tomlinson** [comment]
@vladikoff - it looks like www.mozilla.org is already added: https://github.com/mozilla-services/cloudops-deployment/blob/ed2b0aa51e3a05c80a492f3e532b86ac28c6497b/projects/fxa/puppet/yaml/type/fxa.content_server.prod.yaml#L5. Do we need to add just `mozilla.org`?

**Comment by shane-tomlinson** [comment]
@stephaniehobson predicts the What's New change to use the iframeless flow will be shipped to prod today (Sep 11), it'd be good if we can get this figured out before they make the update.

**Comment by vladikoff** [comment]
This was fixed
