### ISSUE TITLE
teamcity failing functional test - [recovery code] can regenerate recovery code when low

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6536]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=42226&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=650

It looks like the `fxaccounts:login` message is not being received by the browser.

cc @vbudhram - you had some ideas in IRC what might be causing this, most likely being a config change is needed on latest?

**Comment by vbudhram** [comment]
Verified fixed against latest

```
node tests/intern.js --grep="can regenerate recovery code when low" --fxaAuthRoot=https://latest.dev.lcip.org/auth/v1 --fxaContentRoot=https://latest.dev.lcip.org/ --fxaEmailRoot=http://restmail.net --fxaOAuthApp=https://123done-latest.dev.lcip.org/ --fxaUntrustedOauthApp=https://321done-latest.dev.lcip.org/ --fxaProduction=true --fxaToken=https://token.dev.lcip.org/1.0/sync/1.5
```
