### ISSUE TITLE
Implement a "hybrid pairing authority" broker

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-server#6546]
As described in our implementation plan [1], we want to implement the Desktop side of the Fenix pairing flow using a hybrid approach.  There will be native code in Desktop [2] which communicates with Fenix over the WebSocket channel and which handles key material, but OAuth authorization UI will remain in web content on https://accounts.firefox.com.

To achieve this, we'll need to create a special OAuth broker subclass that knows how to communicate with the Desktop component over webchannel messages.  It will need to:

* Obtain geolocation info about the connecting device, and include that in the OAuth signin screen.
* Obtain `keys_jwe` from the browser rather than attempting to calculate it locally.
* Return `code` and `state` to the browser via webchannel message, rather than redirecting at the end of the flow.

The name of this thing could also use some bikeshedding...

[1] https://docs.google.com/document/d/1mFf0sfEK8o1csXLeyK1x4GS9SUMIq4q8bu25LiydPew/edit#heading=h.ksihj7yht5w6
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1490671

**Comment by shane-tomlinson** [comment]
Subsumed by #6617, closing.
