### ISSUE TITLE
Font size in Arabic appears smaller than English

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6556]
One of the folks in the office who speaks Arabic offered the feedback that the font size in Arabic seems significantly smaller than English, and that would cause trouble for sight impaired users.

### Arabic

<img width="731" alt="screen shot 2018-09-14 at 17 40 29" src="https://user-images.githubusercontent.com/848085/45563702-125b6080-b846-11e8-8e42-c6ba90647308.png">

### English
<img width="775" alt="screen shot 2018-09-14 at 17 41 04" src="https://user-images.githubusercontent.com/848085/45563703-125b6080-b846-11e8-995f-5dcfceef915d.png">

**Comment by shane-tomlinson** [comment]
@ryanfeeley - could I get your input on how to handle this, for Arabic, can we increase the font size by 1px in the pw strength bubble?

**Comment by ryanfeeley** [comment]
@shane-tomlinson This is the same size as the newsletter opt-in and other small fragments of copy around the site. Should they all be bumped up 1px in Arabic? I'm OK with that, but just don't want it to break anything.

**Comment by vladikoff** [comment]
I feel like it's up to the browser to make sure all languages have the right font-size, we cannot check all possible locales and start adjust for it. Reopen if you strongly feel we should have a custom rule for this.

**Comment by shane-tomlinson** [comment]
> I feel like it's up to the browser to make sure all languages have the right font-size, we cannot check all possible locales and start adjust for it. Reopen if you strongly feel we should have a custom rule for this.

Yes, we should still do this, [conversion rates for AR are significantly lower than other locales](https://analytics.amplitude.com/mozilla-corp/chart/jvwikep). We regularly make affordances for "long languages" like German, this is a similar problem.
