### ISSUE TITLE
Make list of recovery codes clearer

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6559]
Currently, it's not obvious if there are 4 or 8 recovery codes for TOTP. Let's enumerate them 1-8 to make it more obvious. (or something like that)

**Comment by ryanfeeley** [comment]
I ❤️ Unicode.


CURRENT:
<img width="222" alt="screen shot 2018-09-17 at 4 07 47 pm" src="https://user-images.githubusercontent.com/68213/45647657-665b8480-ba94-11e8-81e4-1db2f1d03e44.png">

PROPOSED:
<img width="224" alt="screen shot 2018-09-17 at 4 10 53 pm" src="https://user-images.githubusercontent.com/68213/45647673-6e1b2900-ba94-11e8-86ff-fcf6375d5e34.png">

Font size: 1.4em

➊
➋
➌
➍
➎
➏
➐
➑

**Comment by vladikoff** [comment]
I wonder if some machine renders in such a way or if you copy paste it and your code will now be `1HTBXGWYWMH` (1 coming from the unicode part).

**Comment by ryanfeeley** [comment]
I’m no expert but if done as an ordered list with :before pseudoclass content, you might be able to get around that. https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#Accessibility_concerns

**Comment by vbudhram** [comment]
@ryanfeeley For recovery key, we used a dotted line around the text. Might be possible to do that here?

<img width="407" alt="screen shot 2018-09-19 at 9 44 51 am" src="https://user-images.githubusercontent.com/1295288/45757205-d0893c00-bbf0-11e8-8e5e-ff8c0549f453.png">

**Comment by ryanfeeley** [comment]
This works too.

It sadly introduces my least favourite Firefox rendering choice – improper corners. https://www.impressivewebs.com/comparison-css-border-style/

Would love to see real corners on these.

**Comment by bini11** [comment]
Hey @ryanfeeley Is this bug still open? I would like to work on it. Can i take this up?

**Comment by lmorchard** [comment]
@bini11 Go ahead and give this a try, let me know if you have any questions!

**Comment by AlbionaHoti** [comment]
Hi,

If @bini11 is not available to work on this issue, would like to start working on it -> I'm an outreachy applicant.
@lmorchard just leaving this here :)

**Comment by bini11** [comment]
@lmorchard Hey can i go for dotted line around the keys like in recovery or add numbers?

**Comment by lmorchard** [comment]
I'd say go for the dotted line unless @ryanfeeley objects - seems like that was where this issue last left off in the decision process?

**Comment by bini11** [comment]
@lmorchard  While running local fxa-content-server with remote Firefox account servers getting only 3 recovery codes in tow-step authentication instead of 8?
![RECOVERY](https://user-images.githubusercontent.com/34271745/54852816-cebf4300-4d0f-11e9-9879-6570096eecdc.png)

**Comment by ryanfeeley** [comment]
@bini11  I'm not sure about the number of recovery codes, @vbudhram may have ideas, but the outline solution is fine.

I'm curious how your links are purple and not blue? Any ideas?

**Comment by bini11** [comment]
@ryanfeeley seems like colors are little bit altered after taking screenshot otherwise on the local server links are blue.

**Comment by vbudhram** [comment]
Hey @bini11 this is not actually an error, it can be configured [here](https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L867). We generate 3 recovery codes for fxa-local-dev because it is easier to test some scenarios with less, it is also a little faster to create 3 then 8.

For this issue, you will want to follow the style found [here](https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L867).

**Comment by shane-tomlinson** [comment]
Fixed by #7109, closing.
