### ISSUE TITLE
TOTP: only 3 recovery codes displayed

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6568]
Environment:
Stage - Train 121
Platform: Android, Win, iOS

Steps to reproduce:
1. Go to Manage Account and enable Two-step authentication;
2. Pay attention to recovery codes.

Expected results: 8 recovery codes are displayed.
Actual results: 3 codes are displayed. 

![screenshot_20180919-112430_firefox nightly](https://user-images.githubusercontent.com/24588037/45743182-2c10f500-bc04-11e8-9745-518f6b9c8738.jpg)

**Comment by vbudhram** [comment]
@SorinaFlorean Thanks for the find, however this is actually working as expected for the stage environment. We had to update it to generate 3 codes to get some of our integration tests working. However, it will still generate 8 in production.
