### ISSUE TITLE
"Incorrect password" displayed if we change the password and then switch to primary email again

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6571]
Environment:
Platform: iOS, Android, Win10
Train 121

Steps to reproduce:
1. Add a secondary email (Manage account- Secondary email);
2. Make primary the secondary email;
3. Change the password;
4. Make secondary the primary email (switch between accounts);
5. Log out and Sign in again with the new password.

Expected results: the user is logged in.
Actual result: "Incorrect password" message is displayed.

**Comment by vbudhram** [comment]
Hey @SorinaFlorean, I tried to reproduce this on our stage/local environment with no luck on iOS, OSX and windows.

Is there an extra step here that I might be missing? Possible to make a quick video of this?

**Comment by vbudhram** [comment]
@SorinaFlorean Thanks! I was doing a change password through the setting page, from video you are doing a password reset. I'll try to reproduce again.
