### ISSUE TITLE
Loading button adds unneeded height 

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6578]
![devices](https://user-images.githubusercontent.com/68213/45974192-a7144a00-c00e-11e8-8064-dac47b22da37.gif)

STEPS TO REPRODUCE
1. Have devices connected to your Firefox Account
1. Log in to FxA settings go to Devices section
1. Click on Show button

EXPECTED RESULTS
* Button enters loading state
* Horizontal rule does not move

ACTUAL RESULTS
* Horizontal rule moves down

**Comment by yogmel** [comment]
Hi @ryanfeeley,

May I take this issue?

Thanks!

**Comment by AlbionaHoti** [comment]
Hi @ryanfeeley 

I am an Outreachy applicant, can I work on this issue?

Thank you!

**Comment by shane-tomlinson** [comment]
> May I take this issue?
@yogmel, you sure can.

@AlbionaHoti mind finding a [different issue to tackle](https://github.com/mozilla/fxa-content-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)?

**Comment by yogmel** [comment]
Thanks @shane-tomlinson! I will work on it and will send you updates tomorrow.

**Comment by lmorchard** [comment]
@yogmel If shane is busy, I'm available for questions & help too. Looks like we can't assign issues on GitHub to folks outside the core team, so I think I'll just assign it to myself to track it

**Comment by DraciVik** [comment]
Hi @yogmel. If you're having problems or you're unable to contribute right now may I take this issue on? I am an Outreachy applicant and I am looking for bugs to solve. Thank you!

**Comment by yogmel** [comment]
Hi @lmorchard, thanks for your availability! Unfortunately, I had some problems installing all the requirements to run FXA (due to Docker and my OS). :(
I will, then, pass on this issue to any Outreachy applicant.
@AlbionaHoti , are you still interested in this issue?

**Comment by AlbionaHoti** [comment]
> Hi @lmorchard, thanks for your availability! Unfortunately, I had some problems installing all the requirements to run FXA (due to Docker and my OS). :(
> I will, then, pass on this issue to any Outreachy applicant.
> @AlbionaHoti , are you still interested in this issue?

Hey @yogmel Yes I am! Thank you.

@shane-tomlinson Will continue with this one - as a new outreachy applicant - I hope you have the time to give me some starting guide - For now I am starting the project on my laptop.

**Comment by lmorchard** [comment]
@AlbionaHoti I can help here too, as Outreachy mentor. Feel free to email me at lorchard@mozilla.com with any questions! I'm also in IRC, but availability there is dependent on time zone.
