### ISSUE TITLE
[train-121] increase of Unexpected error for lib/errors in importSearchParamsUsingSchema error

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6581]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/4744592/

Ticked up with release of train-121

**Comment by vladikoff** [comment]
this looks like it stopped per https://sentry.prod.mozaws.net/operations/fxa-content-product/?query=importSearchParamsUsingSchema
