### ISSUE TITLE
redirect when a request to /authorization contains an invalid email?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-content-server#6584]
Currently, when the `email` parameter is invalid and action is email the user is shown the "Bad Request" page. It'd be a bit nicer if they were just directed to the signup or signin page.

**Comment by shane-tomlinson** [comment]
>  It'd be a bit nicer if they were just directed to the signup or signin page.

The same problem also occurs on the about:welcome page. We wouldn't send the user to /signin or /signup (one of my Q4 goals is to consolidate all flows to use email-first), but we could we could pre-fill the invalid email on the email-first page and say it's invalid. 

I'm trying to figure out what repercussions that could have and whether it breaks any assumptions for other integrations. If it does, we should be able to use different validation for different fields.
