### ISSUE TITLE
iOS Associated Domain Breaks Password Autofill in iOS 12

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6599]
We use associated domains for our emails to deeplink user back into Firefox after a login or registration email so we don't break our flow by passing them over to Chrome or Safari.

With the release of iOS 12, they added a password autofill feature. Due to this, any of our users that has accounts.firefox.com saved to a password manager will have it autofilled on every website because Apple is not handling webview browsers properly.

Details of bug here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1492473

Stefan, Gavin, Justin and  I identified 2 options:
1) we have links open in Safari and we redirect users to Firefox using firefox://
2) we use a different cname for our associated domain, one that would not be in someone's password manager so that iOS won't suggest their account's password.

We believe there is less risk at breaking things with option 2 since we could continue to use Adjust links without risking breaking SMS or the flow on Android.

Note that a bug has been filed with Apple.

**Comment by st3fan** [comment]
I added some more detail about the second option in the Bugzilla bug. I don't think there is anything actually confidential about this bug so feel free to discuss here too if that is better.

**Comment by vladikoff** [comment]
from mtg: point release for 122?

**Comment by rfk** [comment]
As mentioned in the meeting, I think we need to tread somewhat cautiously here - changing the way links work in our emails affects all clients, and we don't want to cause unintended bustage for e.g. desktop logins by rushing a fix for iOS logins.

IIUC the plan is to:

* Create a new domain https://confirm.accounts.firefox.com whose only purpose is to 302 to https://accounts.firefox.com, preserving path and query parameters.
* Add https://confirm.accounts.firefox.com as an associated domain for the iOS Firefox app, replacing https://accounts.firefox.com
* Change the links in all our emails from https://accounts.firefox.com to https://confirm.accounts.firefox.com
* Carefully monitor our metrics and be ready to roll back if this has unintended effect on other platforms

Quick q: are there any links (e.g. the install link for Adjust used in our SMS) which will need to change to the new associated domain, but for which "confirm.accounts.firefox.com" would be kind of a weird hostname?

**Comment by garvankeeley** [comment]
PR for Firefox iOS 14.0 (next release): https://github.com/mozilla-mobile/firefox-ios/pull/4284

**Comment by shane-tomlinson** [comment]
Closing as fixed, QA plan to follow from @vbudhram

**Comment by vbudhram** [comment]
A rough draft of QA test plan: https://docs.google.com/document/d/1mA_xLV5hRc3c7yfeMi6yInZ07JyhJYctf6y0fYxiZbY/edit?usp=sharing

**Comment by SorinaFlorean** [comment]
We tried to test this on stage - Train 123 but we didn't get the expected results from the Test Plan. Talked with Vijay on slack and seems that in order to verify there are some settings that need to be done on stage.
We will keep the qa-needed label until we can verify this, stage or prod. Thanks!

**Comment by SorinaFlorean** [comment]
Tested this in production based on the Test Plan made by @vbudhram and you can see the results there. There were some problems with iOS, but overall the testing was ok.
