### ISSUE TITLE
Get designs for pairing flow with PAKE

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6614]
This requires coordination with @ryanfeeley 

https://www.lucidchart.com/documents/view/9a420c19-1e92-42a5-8eae-908a442c1044/0

blocked by #6670

**Comment by vladikoff** [comment]
from mtg:  @ryanfeeley on PTO until Oct 29

**Comment by jdragojevic** [comment]
per estimating meeting.  Closing this one when we have a clearer plan for what we're doing for PAKE after security reviews.
