### ISSUE TITLE
No spacing between 'Get the latest news' text and its checkbox

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/fxa-content-server#6626]
STR

1. Open AMO -dev and Register a new account
2. Observe the layout of the [Create a new profile form](https://stable.dev.lcip.org/oauth/signup?scope=profile&state=4362a548375ffeaea118c514fce9b28075e4dc7cf346ee7a73a1106cd9032b93%3AL2VuLVVTL2ZpcmVmb3gvdXNlci9hbm9ueW1vdXMtYTYxNWY3M2M2MzFlNTdmNmQxMzIwNjRkMTdjOWQ5YmQv&redirect_url=https%3A%2F%2Famo.addons-dev.allizom.org%2Ffxa-authenticate&client_id=cb6a5ba26feea430)

Actual result:
There is no spacing between the 'Get the latest news about Mozilla and Firefox'  text and the checkbox next to it

Expected result:
Space should be added between 'Get the latest news' and its checkbox 

Notes:
- reproduced on the dev server with FF62, Won10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/46614308-33019800-cb1e-11e8-8f1b-e19ee4203ef2.png)

**Comment by vbudhram** [comment]
from mtg: Seen this in a couple other areas, moving into next

**Comment by SorinaFlorean** [comment]
Works as expected - Train 123, stage server. Verified on iOS, Win, Android.
