### ISSUE TITLE
Add `Use a different account` to TOTP signin and Recovery code page

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6634]
We should update these login pages to have these links. Clicking the link should return to the `/signin` page.

![image](https://user-images.githubusercontent.com/1295288/46885387-d2c46c00-ce25-11e8-9421-a0cad47a59a1.png)

**Comment by arshadkazmi42** [comment]
I would like to take this up.

**Comment by vbudhram** [comment]
Hey @arshadkazmi42, welcome to work on this issue.

I would recommend using [fxa-local-dev](https://github.com/mozilla/fxa-local-dev) for testing/development. You would be able to see more descriptive errors in terminal. Also recommend using Node 8 if not already using that.

**Comment by arshadkazmi42** [comment]
@vbudhram 
Both are same repo? For the fix, I have to create PR in `fxa-local-dev` repo?

**Comment by vbudhram** [comment]
@arshadkazmi42 `fxa-local-dev` clones all the repos needed by FxA behind the scenese. You would only need to create patch in the `/fxa-local-dev/fxa-content-server` repo.

**Comment by arshadkazmi42** [comment]
@vbudhram Thanks for clearing the doubts. I  will create a PR for this soon.

**Comment by vbudhram** [comment]
Hey @arshadkazmi42 Looks like a CSP error when accessing using `localhost`, try going to `http://127.0.0.1:3030/settings`.

**Comment by arshadkazmi42** [comment]
@vbudhram Still its showing same error with this also `http://127.0.0.1:3030/settings`

**Comment by arshadkazmi42** [comment]
@vbudhram So after some debugging I found, `client.json` is missing and this url `http://127.0.0.1:3030/i18n/client.json` is returning 404.
I think due to this only it is crashing.  Does it require some configurations? Which I have missed

**Comment by vbudhram** [comment]
@arshadkazmi42 That route should be returning a json object with localization information. Does the `/fxa-local-dev/fxa-content-server/dist/i18n/` or `/fxa-local-dev/fxa-content-server/app/i18n/` directory contain localization files?

If you run `npm install` in the `fxa-content-server` repo, it should fetch and install the latest. You can also run `./pm2 logs 3` from the `fxa-local-dev` folder to see the output of the content-server build process.

**Comment by arshadkazmi42** [comment]
I deleted `node_modules` from `fxa-content-server` and reinstalled using `npm i`.

But doing that on running I am getting this error

script not found : /Users/fxa-local-dev/fxa-content-server/node_modules/.bin/grunt

**Comment by arshadkazmi42** [comment]
Got it working. finally  👍 Will work on the fix and submit a PR by  tomorrow. Thanks for all the help @vbudhram

**Comment by arshadkazmi42** [comment]
I got it up and running. But now I am getting this error in my console.

`fxa-content-server.server.geo.ERROR: geodb.error Error: Unable to fetch data`

and login/signup is not working. Is there any way to load the otp page directly or is there some config to fix this error?

**Comment by arshadkazmi42** [comment]
@vbudhram Created PR

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/6700
