### ISSUE TITLE
Mobile Deeplinking Broken?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6642]
During Sync Fest today, we went through the registration flow.

We were unable to get the SMS deeplinking to work. It is my understanding that it doesn't normally work twice on the same phone but I was using a new phone so I thought it would work.

*Steps to reproduce*
- register for an account
- confirm an email
- send an sms to install
- install through App Store
- open app

*Expected result*
User sees the login form with their email prepopulated

*Actual result*
User is sent to regular onboarding flow

**Comment by davismtl** [comment]
@SorinaFlorean can you help me confirm this bug by using a device that has never gone through the SMS flow?

**Comment by SorinaFlorean** [comment]
@davismtl sure, tomorrow morning I will investigate and get back with an answer. Sorry for late reply.

**Comment by vbudhram** [comment]
@davismtl Did a quick test of this and deeplinking did not work for me as well.

> it doesn't normally work twice on the same phone

Following instructions at https://docs.adjust.com/en/testing-console/, you should be able to clear you advertising ID from adjust which in theory should have it work on same device again.

**Comment by SorinaFlorean** [comment]
Here are my findings on my personal device (Huawei P9(Android 7.0): 
- First time SMS flow: after I installed and opened the app I got the email already filed: https://i.imgur.com/QK5pnaq.png
- Second SMS flow: nothing was filed, I just had to enter the credentials again. Hope this helps.

**Comment by davismtl** [comment]
@SorinaFlorean 
Before your second flow, did you follow the instructions from the link that @vbudhram shared in #issuecomment-430734467 ? 

Is it possible for you to test on an iOS device too?
Android and iOS deeplinking are a bit integrated differently.

**Comment by shane-tomlinson** [comment]
Action Items:
* Audit adjust to make sure we didn't break things there.
* Confirm whether deep linking is broken on iOS after clearing the Adjust advertiser ID.

@SorinaFlorean - Do you have an iOS device you can confirm with too?

**Comment by SorinaFlorean** [comment]
Yes, we have. I can manage to test on Wednesday, if is not too late, tomorrow we have 64 beta 3.

**Comment by SorinaFlorean** [comment]
@vbudhram I need an Adjust account in order to test this based on https://docs.adjust.com/en/testing-console/. Can you help me? Thanks!

**Comment by vbudhram** [comment]
@davismtl Possible to access to test console? Or we could clear it manually?

**Comment by davismtl** [comment]
I am no longer an admin of Adjust so I've requested access for @SorinaFlorean with st3fan so that she can clear her ad id herself which should also allow to test more regularly.

**Comment by rfk** [comment]
From mtg: 
* need to get Sorina set up with Adjust access in order to test this properly.
* need a volunteer to deep dive into code on the iOS side
* hypothesis: recent changes to app-link setup may have broken this

Let's migrate this to bugzilla so we can loop in the iOS team; assigning to myself to do so

**Comment by rfk** [comment]
Let's move this to https://bugzilla.mozilla.org/show_bug.cgi?id=1510811 in order to more easily loop in the Firefox for iOS folks.
