### ISSUE TITLE
"New Sign-in to Firefox" email is received if we try to enable 2FA with invalid code

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6649]
Environment:
Android, iOS, Win10

Steps to reproduce:
1. Go to Manage account and tap on Enable from Two-Factor authentication;
2. Scan the QR code;
3. Type an invalid authentication code;

Other steps:
1. Go to Sign In page and enter credentials for an account with 2FA enabled;
2.  Type a random 6-digit code;
3. Check email inbox.

Actual results: "New Sign-in to Firefox" email is received.
Expected results: Email is not received since the code was invalid.  

Note: 
- reproducible even if I change one number or more.
- not reproducible with recovery codes.

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - is this when trying to *enable* 2FA or when trying to sign in to an account after 2FA is enabled?

**Comment by SorinaFlorean** [comment]
Both cases, I've put both str because I found the issue in two ways.

**Comment by vladikoff** [comment]
from mtg: @vbudhram this might be fixed

**Comment by vbudhram** [comment]
Confirmed that this is still happening, putting up fix soon.

**Comment by SorinaFlorean** [comment]
Works as expected on Train 126.
