### ISSUE TITLE
Android device not listed on iOS if we want to send tab

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6652]
Environment: Stage server - Train 123

Steps to reproduce:
1. Log in with an account on iOS, Android and desktop;
2. On iOS, open a page and tap on three dots menu->Send to device;
3. Choose Android.

Actual results: Android device is not listed, only desktop.
Expected results: the page is sent to the Android device.

Notes:
- Not reproducible on production.
- Sending tab from Android to iOS works as expected.

**Comment by shane-tomlinson** [comment]
@SorinaFlorean - Does the Android device show up in desktop?

**Comment by shane-tomlinson** [comment]
@vbudhram to investigate

**Comment by shane-tomlinson** [comment]
@SorinaFlorean is it possible to do a video cap of the STRs on the iOS device? Did you force a Sync refresh so that it fetches the device list?

**Comment by SorinaFlorean** [comment]
Here is the video with the behavior: https://drive.google.com/open?id=1HKKeret7E-vpYsXU_zC2i4V1Y3z1wzpB.
Note that Sync was performed before I tried to send the tab to Android device, and is listed in Manage account ->Devices and apps section: Google Pixel. If there is some extra info needed please contact me. Thanks!

**Comment by rfk** [comment]
@SorinaFlorean I notice in your screen cap that you have *two* android devices connected, one called "Beta on Pixel" and the other "Firefox 63, Android":

<img width="534" alt="capture" src="https://user-images.githubusercontent.com/34695/48180088-2c14b200-e376-11e8-861d-2cda41de00d8.PNG">

Do you in fact have two android devices connected to this account, or might this be a clue that Android as done something weird during the device registration process?

According to the code at [1], Firefox for iOS will only show devices in its send-tab list if they have registered an FxA device record *and* have created a sync "clients" collection record that contains their FxA device id.  My guess here is that Android's device registration process is, for whatever reason, not working properly in Stage so it's not meeting those requirement, and is being hidden on Firefox for iOS.

[1] https://github.com/mozilla-mobile/firefox-ios/blob/3299e02fe72f9fa7f035b9123481797bd33ef906/Storage/SQL/SQLiteRemoteClientsAndTabs.swift#L207

**Comment by rfk** [comment]
If you're able to reproduce this with an Android, iOS and Desktop device all connected to the same account, then it would be very useful if you could use the [about:sync](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) addon on the desktop device share your clients collection and FxA device records.  That is: install the add-on, go to about:sync, and share the contents of these two tabs from the resulting view:

![capture](https://user-images.githubusercontent.com/34695/48180724-dee60f80-e378-11e8-9663-3906533a9d6a.PNG)

**Comment by SorinaFlorean** [comment]
Sorry for the late reply here. Tested again on stage - Train 125 and production and this issue is not reproducible anymore. The Android device is listed on iOS and the tabs were sent successfully. I will close this and check on the next stage also. Thanks!
