### ISSUE TITLE
[stage][train-123] two tests consistently failing in stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6655]
firefox on linux 4.4.41-36.55.amzn1.x86_64: settings change email (2)
  can change primary email, change password and login  	    
  can change primary email, change password, login, change email and login 

See:

https://tc-test.dev.lcip.org/viewLog.html?buildId=43988&tab=buildResultsDiv&buildTypeId=fxa_StageTests

There's a couple of screenshots in the build log that may offer a hint.

**Comment by vbudhram** [comment]
Hey @jrgm took a look at this some more and I found that in stage, the change email and password change takes over 20 seconds to perform and the test times out. In local and latest testing it takes less than 2 seconds. Did any of the recent migrations on stage change the performance of database?

Stage env
<img width="862" alt="screen shot 2018-10-24 at 12 51 34 pm" src="https://user-images.githubusercontent.com/1295288/47447465-97ae2b00-d78b-11e8-8f33-fc56fed59565.png">

Latest env
<img width="866" alt="screen shot 2018-10-24 at 12 54 01 pm" src="https://user-images.githubusercontent.com/1295288/47447632-fb385880-d78b-11e8-9858-afa07d117560.png">

I'm surprised that this is the only test failing with timeouts. I can increase the timeout for these tests but maybe it would be better to upgrade database?

**Comment by jrgm** [comment]
Well, this is interesting. In stage, in slow query logs, accountRecord_4 is taking ~4 seconds to execute.

If I take the body from accountRecord_4:
```
explain
    SELECT
        a.uid,
        a.email,
        a.normalizedEmail,
        a.emailVerified,
        a.emailCode,
        a.kA,
        a.wrapWrapKb,
        a.verifierVersion,
        a.authSalt,
        a.verifierSetAt,
        a.createdAt,
        a.locale,
        a.lockedAt,
        COALESCE(a.verifierSetAt, a.createdAt) AS profileChangedAt,
        e.normalizedEmail AS primaryEmail
    FROM
        accounts a,
        emails e
    WHERE
        a.uid = (SELECT uid FROM emails WHERE normalizedEmail = LOWER('an-email-that-exists-in-emails-and-accounts@example.com'))
    AND
        a.uid = e.uid
    AND
        e.isPrimary = true;
```

and do an EXPLAIN on it, I get:
```
MySQL [fxa]> source /tmp/q.sql
+----+-------------+--------+-------+-----------------+-----------------+---------+-------+------+-------------+
| id | select_type | table  | type  | possible_keys   | key             | key_len | ref   | rows | Extra       |
+----+-------------+--------+-------+-----------------+-----------------+---------+-------+------+-------------+
|  1 | PRIMARY     | a      | const | PRIMARY         | PRIMARY         | 16      | const |    1 | NULL        |
|  1 | PRIMARY     | e      | ref   | emails_uid      | emails_uid      | 16      | const |    1 | Using where |
|  2 | SUBQUERY    | emails | const | normalizedEmail | normalizedEmail | 767     | const |    1 | NULL        |
+----+-------------+--------+-------+-----------------+-----------------+---------+-------+------+-------------+
3 rows in set (0.00 sec)
```

So, instead of `using index` or `using index condition`, `using where`.

Stage has `O(10million)` rows in `accounts` and `emails`.

I looked at production, and he explain is the same there.

In production, `accountRecord_4` is not showing up in slow query logs, although the long query time is 3s in production. But running the SELECT manually there takes no time. This may be due to having much more memory in production, I guess.

**Comment by jrgm** [comment]
> Did any of the recent migrations on stage change the performance of database?

Only recently did I create a bunch of new accounts and sessionTokens in stage (part of trying to understand this migration bug). Basically an order of magnitude increase in stage.

**Comment by jrgm** [comment]
In stage, I added another stored procedure:

```
CREATE PROCEDURE `accountRecord_TestDeleteMe2` (
  IN `inEmail` VARCHAR(255)
)
BEGIN
explain
    SELECT
        a.uid,
        a.email,
        a.normalizedEmail,
        a.emailVerified,
        a.emailCode,
        a.kA,
        a.wrapWrapKb,
        a.verifierVersion,
        a.authSalt,
        a.verifierSetAt,
        a.createdAt,
        a.locale,
        a.lockedAt,
        COALESCE(a.verifierSetAt, a.createdAt) AS profileChangedAt,
        e.normalizedEmail AS primaryEmail
    FROM
        accounts a,
        emails e
    WHERE
        a.uid = (SELECT uid FROM emails WHERE normalizedEmail = LOWER(inEmail))
    AND
        a.uid = e.uid
    AND
        e.isPrimary = true;
END;
```
```
MySQL [fxa]> CALL accountRecord_TestDeleteMe2('abcabdab@fastmail.fm');
+----+-------------+--------+-------+---------------+------------+---------+-------+----------+-------------+
| id | select_type | table  | type  | possible_keys | key        | key_len | ref   | rows     | Extra       |
+----+-------------+--------+-------+---------------+------------+---------+-------+----------+-------------+
|  1 | PRIMARY     | a      | const | PRIMARY       | PRIMARY    | 16      | const |        1 | NULL        |
|  1 | PRIMARY     | e      | ref   | emails_uid    | emails_uid | 16      | const |        1 | Using where |
|  2 | SUBQUERY    | emails | ALL   | NULL          | NULL       | NULL    | NULL  | 12869531 | Using where |
+----+-------------+--------+-------+---------------+------------+---------+-------+----------+-------------+
3 rows in set (4.98 sec)

Query OK, 0 rows affected (4.98 sec)
```
Which is very different than what the EXPLAIN SELECT shows from the command line. Note that the EXPLAIN in the stored procedure takes 5 seconds, probably because it has to perform the subquery to complete the EXPLAIN. o_O

**Comment by jrgm** [comment]
Interesting that the earlier incarnations of this SP are fast. (accountRecord_3 isn't callable since it expects the profileChangedAt column on fxa.accounts).

```
MySQL [fxa]> CALL accountRecord_2('abcabdab@fastmail.fm');
 ...
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MySQL [fxa]> CALL accountRecord_1('abcabdab@fastmail.fm');
  ...
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

MySQL [fxa]> 
```

**Comment by jrgm** [comment]
`CALL accountRecord_4('email-that-exists@example.com')` in production takes a loong time (I killed it after 8 seconds).

**Comment by rfk** [comment]
From IRC conversation, there's a theory that an encoding issue is responsible for the difference in query plan between the raw select, and the select inside a stored-procedure.  We now explicitly do `SET NAMES utf8mb4 COLLATE utf8mb4_bin;` before running our migration scripts.  I wonder if creating the stored procedure with `latin1` encoding instead would make a difference to the query plan?

**Comment by rfk** [comment]
We addressed the immediate issue by rolling back to `accountRecord_2`.  I'm going to close this bug and open two in its place:

* https://github.com/mozilla/fxa-auth-db-mysql/issues/433 to fix the specific case of this query
* https://bugzilla.mozilla.org/show_bug.cgi?id=1504907 to figure out what on earth caused the performance issue here, so we can avoid it happening again in general
