### ISSUE TITLE
about:welcome / entrypoint activity-stream-firstrun email first form views not making it to amplitude

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-content-server#6660]
The fix from the activity stream folks (https://bugzilla.mozilla.org/show_bug.cgi?id=1490826) seems to have generally worked as we can see the increase in form views volume in redash:

https://sql.telemetry.mozilla.org/queries/58886/source#154218

So the problem is on our end with mapping flow events to amplitude events.

The flow event used to plot the chart above `flow.enter-email.view` *should* be mapped automatically to the amplitude event `fxa_email_first - view` however that doesn't seem to be happening for some reason. I'll update this bug when I find out more

CC @davismtl if you were wondering about this. If you want an estimate of form views you'll have to look at re:dash until we fix this.

**Comment by irrationalagent** [comment]
I think I figured out the problem here. 

https://github.com/mozilla/fxa-content-server/blob/408f61d3d086f984aa3721a88f3476470f3cbbad/server/lib/routes/get-metrics-flow.js#L15

should be just `screen.enter-email` without the `.view` bit.

That's because as it currently is it won't match this:
https://github.com/mozilla/fxa-content-server/blob/0921bc53e92f3b8e4e796f51cc46202d1cfae25e/server/lib/amplitude.js#L81

I discovered this by accident when working on this pr https://github.com/mozilla/fxa-content-server/pull/6654

@philbooth can you confirm my reasoning here? if so I'll put up a quick pr to fix it

@philbooth can you confirm my reasoning here? if so,

**Comment by philbooth** [comment]
Yep, bang on, nice work. Recommend you branch from and open the PR against the `train-123` branch, so that we can deploy this sooner as a point release.
