### ISSUE TITLE
Missing space to the right of newsletter checkbox

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6678]
There's missing a space next to the checkbox. Seen in Nightly, not sure if it's also happening in release.

![image](https://user-images.githubusercontent.com/19537086/47752789-ae082b00-dc52-11e8-8af4-0d333391d9a5.png)

**Comment by shane-tomlinson** [comment]
Dup of #6626 which should have been fixed with yesterday's release.

**Comment by shane-tomlinson** [comment]
Verified the fix in both Nightly and Release:

<img width="504" alt="screenshot 2018-10-31 at 06 35 09" src="https://user-images.githubusercontent.com/848085/47770448-5a8bf080-dcd7-11e8-8597-92ff930f499c.png">

<img width="554" alt="screenshot 2018-10-31 at 06 35 21" src="https://user-images.githubusercontent.com/848085/47770458-64adef00-dcd7-11e8-83ef-9ceaf0e4962d.png">
