### ISSUE TITLE
AMO icon not showing up in device manager

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6679]
During SyncFest, we signed in to AMO and when we went to our device manager, there was no icon.

![image](https://user-images.githubusercontent.com/19537086/47755784-d72db900-dc5c-11e8-8ec5-233fb0e64836.png)

**Comment by SorinaFlorean** [comment]
We found this also on production, unfortunately, we can't test on stage because we can't point addons to stage.

**Comment by ryanfeeley** [comment]
@vladikoff I still see this. Need it be reopened?

**Comment by vbudhram** [comment]
@ryanfeeley Looks like this is tagged for train 126, which should be deployed in Orlando.

**Comment by ryanfeeley** [comment]
![giphy](https://user-images.githubusercontent.com/68213/49179544-7effda80-f320-11e8-84a6-c66444f3b46b.gif)
