### ISSUE TITLE
[train-124] new error? - SecurityErrortemplates/account_recovery_confirm_key in r error The operation is insecure.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6691]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/4914725/?query=is:unresolved

**Comment by vladikoff** [comment]
Could not repro this, I got into a weird state when the form https://accounts.firefox.com/account_recovery_confirm_key passed validation, but only happened once. not clear what is causing this.

**Comment by vladikoff** [comment]
Also this error is from 123 not 124, if you search by name: 

![](http://v14d.com/i/7fc76558d3e0d7722c6f0884bbe0f172831c3f006a95a2112ec327fddecf16d4.jpg)

**Comment by vladikoff** [comment]
Let's revisit this if this comes up again
