### ISSUE TITLE
Pass to SalesForce for LiveNation campaign

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6693]
The marketing team is organizing a live stream of a couple of music events.

The streams will be gated with FxA.

The desired outcome is that users will be able to signup early and get a reminder of the event.

My questions are:
- what would be the best way for SalesForce to track that a user authenticated on this page? Do we already pass any context to SalesForce around where a user signed up? Can the page itself capture the email and sent it to SalesForce? IIUC, they can tell the difference between our reliers but this will be via a mozilla.org page so I don't know how they will be able to detect users from this entry point.

**Comment by davismtl** [comment]
CC @jdragojevic @shane-tomlinson

**Comment by shane-tomlinson** [comment]
@davismtl - we send `client_id`, `service`, `utm_campaign`, `utm_content`, `utm_medium`, `utm_source`, and `utm_term`

ref https://github.com/mozilla/fxa-content-server/blob/ae979c68fb57c45a64d4295de5911dd1b992da2b/app/scripts/lib/marketing-email-client.js#L17

**Comment by shane-tomlinson** [comment]
@davismtl I just realized that is only sent for users who sign up for the newsletters. Will dig in more.

**Comment by rfk** [comment]
> Do we already pass any context to SalesForce around where a user signed up?

We publish all *sync* login events to salesforce via the logic here, but it's very specific to sync:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/utils/signin.js#L246
  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L193

> Can the page itself capture the email and sent it to SalesForce?

I believe the Basket API supports FxA OAuth tokens these days:

  https://github.com/mozmeao/basket/commit/73ef44a1622704009297b43acd9e6f14b3e65a28

So it may be possible for the mozilla.org page to do an OAuth flow, request the "basket" scope, and then subscribe the user to a newsletter using the resulting OAuth token.

**Comment by davismtl** [comment]
Good news. Since Shane setup this LiveNation page as an OAuth relier, we will be returning the email to the page and so mozilla.org will handle passing everything to basket with the right parameters.

Based on the discussions noted in the document below, FxA will have no further work required other than setting up a relier for that team:

https://docs.google.com/document/d/1-NaIG-pt_gy5SAvarNtP10QUksUQgh4916KKxn3gujs/edit

I will close this issue for now since it is no longer relevant.

**Comment by shane-tomlinson** [comment]
Thanks @davismtl for the update!
