### ISSUE TITLE
Apostrophe in username triggers "Valid email required" message

### ISSUE THREAD

**Issue by jscher2000** [mozilla/fxa-content-server#6702]
This came up on SuMo: https://support.mozilla.org/questions/1239965

The following appears when clicking "Create account":

![fx63-accounts-firefox-valid-email-required](https://user-images.githubusercontent.com/8264646/48294100-35198800-e437-11e8-8875-4b19ec7e25f5.png)

I only see beacons in the Network Monitor so I'm not sure how the validation is being done.

When I look at the isValidEmailAddress() function in /lib/routes/validators.js, it allows apostrophes in the username part of the email address (parts[0]).

Something else??

**Comment by vladikoff** [comment]
@philbooth @shane-tomlinson backlog or next?

**Comment by philbooth** [comment]
> backlog or next?

Seems small enough that we can just get it done this train, I've popped my face on it.

**Comment by shane-tomlinson** [comment]
> Thank you all for your detective work. Is this issue in the right repository to get validate.js updated or does it need to be reposted on https://github.com/mozilla/fxa-content-server/issues ?

For an immediate fix to allow apostrophe's, over in the content server. The longer term goal of sharing validation code will require changes to several repos.
