### ISSUE TITLE
Button width vs string length

### ISSUE THREAD

**Issue by Djfe** [mozilla/fxa-content-server#6717]
This string is way shorter in the english version:
https://pontoon.mozilla.org/de/firefox-accounts/all-resources/?search=Prim%C3%A4r&string=169656

I'm not sure if we can make the translation shorter, but it's fairly easy to adjust the button's width
![firefox_2018-11-20_01-09-48](https://user-images.githubusercontent.com/5685512/48742858-01bdd100-ec61-11e8-9df3-33cea8f7102d.png)

**Comment by hritvi** [comment]
This issue is the same as #5968 and I have worked on it earlier but due to some time constraints couldn't complete it. I had made a PR addressing this issue #5988. 
Could I resume my work on this @shane-tomlinson ? Thanks!
