### ISSUE TITLE
No `fxa_login - view` or `fxa_reg - view` reported for Screenshots

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6742]
See https://github.com/mozilla/fxa-activity-metrics/issues/111#issuecomment-446213504

In https://analytics.amplitude.com/mozilla-corp/chart/wbs7p7m/edit/blup2af, @philbooth shows Amplitude events *are* being reported, he queried `fxa_login - success` and `fxa_reg - created`. 

Screenshots doesn't specify `action=email` and is using the legacy flow.

**Comment by irrationalagent** [comment]
It doesn't seem like content server events generally get passed with an oauth client_id or service parameter ever?

**Comment by philbooth** [comment]
It's just a hunch at this stage, I haven't actually debugged anything yet, just mentioning in case you're interested in working on this @irrationalagent.

Anyway, I wonder if something is going wrong with the initialization of `this._service` in `app/scripts/lib/metrics.js` (i.e. on the client-side). If it's not set there, it won't be in the metrics payload and hence not visible in any content server events until it comes back in the resume token (where I think I have seen it working).

Alternatively, if it is set properly then and does show up in the payload to `POST /metrics`, the problem must be in the content server back-end somewhere.
