### ISSUE TITLE
[Train 127] Email overlaps "Make primary" button in Secondary email section from Manage Accounts

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa-content-server#6751]
**Environment:**
Platform: Android 8, Android 9
Server: Stage

**Steps to reproduce:**
1. Login with FxA account and go to Manage accounts page.
2. Add a secondary email and verify you received an email.
3. Go back to Manage accounts page and tap on "Change" button from Secondary Email section.

**Actual results:**
Email address is overlapping the "Make primary" button.

**Expected results:**
Email should not overlap any button. 

**Note:**
Not reproducible on Windows 10 or iOS.

![screenshot_20181213-113043_firefox beta](https://user-images.githubusercontent.com/45595767/49931353-586ca280-fecf-11e8-8f8b-63d0d5255d77.jpg)

**Comment by shane-tomlinson** [comment]
Does this prevent clicking on the "make primary" button? It seems like a z-index issue could be at play where the email address shields the clickable area of the button.

**Comment by miralobontiu** [comment]
Hi Shane,
No, it doesn`t affect the functionality of the button.

**Comment by vladikoff** [comment]
i think the CI tests cannot click this button though, per failures in `test4`

![](https://screencap.co.uk/images/17735b0e7937a07a6960b56384f01d45e5ad63ba.png)

Was some css changed in Train 127 for this?

**Comment by SorinaFlorean** [comment]
Verified as Fixed - stage server Train 128.
