### ISSUE TITLE
Improve accessibility by giving device icon alternative text description

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6752]
In Settings we show a list of device icons that indicate the platform, and a device name.

<img width="300" alt="devices" src="https://user-images.githubusercontent.com/68213/49961687-4ac01880-fee1-11e8-9cf9-06416aad6085.png">

To improve accessibility, we should include the device platform in the alternative text description.

**Comment by vladikoff** [comment]
After discussing this with @ryanfeeley we couldn't find a suitable solution that will benefit the row items

![image](https://user-images.githubusercontent.com/128755/50362062-2a710900-0534-11e9-93d4-696c557c6285.png)

**Comment by ryanfeeley** [comment]
@vladikoff Why post screenshots of our DMs man?
<img width="134" alt="image" src="https://user-images.githubusercontent.com/68213/50363712-d7e71b00-053a-11e9-8c4c-0398c9b5091f.png">

**Comment by vladikoff** [comment]
@ryanfeeley oh no!
