### ISSUE TITLE
[Train 127] Base32 decoding of FxA Recovery Key discards last character

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#6758]
Environment:
Android, Win 10
Stage -Train 127

Steps to reproduce:
1. Go and enable Account recovery;
2. Tap on forgot password from "Password" section;
3. Go to email and paste the recovery key and change the last character ( I changed 4 with another number);
4. Click on "confirm recovery key".

Expected results:
"Recovery key invalid" message is displayed.

Actual results:
The key is valid and change password page is displayed.

Notes: Not reproducible if we change 2 values.

Video:
https://drive.google.com/open?id=1vDazjGAlp3FqLJizdLU8mdLuKKgHK46l

**Comment by shane-tomlinson** [comment]
This is a dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1513360, which has a WIP PR in https://github.com/mozilla/fxa-content-server/pull/6749
