### ISSUE TITLE
Inconsistent `System Unavailable` Error in Functional tests

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6763]
I've seen this a few times in the past couple weeks. Our CircleCi tests fail because of `System Unavailable` 

Ref: https://screencap.co.uk/images/7b69ebf9578e5d571aa8cc5abc10f42681773862.png
https://circleci.com/gh/mozilla/fxa-content-server/15029?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

There isn't an indication which system might be down.

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by shane-tomlinson** [comment]
I've seen this as well and assumed we merged something and caused a server restart. There's a saying about assuming things.

**Comment by vladikoff** [comment]
this got fixed up it seems
