### ISSUE TITLE
Type on "confirmation code" form input is not numeric

### ISSUE THREAD

**Issue by devinreams** [mozilla/fxa-content-server#6765]
Like #6240 #6266 the new "confirmation code" (not TOTP, but in lieu of the confirmation link via email) screen on mobile does not throw up the number keyboard but instead the normal alpha/numeric keyboard.

**Comment by vladikoff** [comment]
add a slash plus shane says

**Comment by shane-tomlinson** [comment]
Look at the age input, it'll need a `pattern="\n+` attribute I think.
