### ISSUE TITLE
Add app icon for Screenshots

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6769]
FxA users can login to Screenshots. We should add an app icon.

<img width="553" alt="screen shot 2018-12-20 at 12 23 23 pm" src="https://user-images.githubusercontent.com/1295288/50301570-b6f8ca00-0455-11e9-9834-e73977017bb7.png">

**Comment by ryanfeeley** [comment]
@vbudhram We got one! https://design.firefox.com/icons/viewer/#screenshot

**Comment by SorinaFlorean** [comment]
I wasn't able to verify on stage server, the screenshots icon is not listed in devices&apps section, probably because is not pointed to stage, but we will look when Train 128 is in prod.

**Comment by SorinaFlorean** [comment]
Verified on production, the icon is listed in Manage account -> Devices and apps section.
