### ISSUE TITLE
We should eventually timeout on email verification

### ISSUE THREAD

**Issue by jbonacci** [mozilla/fxa-content-server#68]
or at least stopping slamming the idp server with GET requests ad nauseum until the user clicks on the link to complete the verification process:

...etc...
16:54:12.200 GET https://idp.dev.lcip.org/v1/recovery_email/status [HTTP/1.1 200 OK 123ms]
16:54:12.520 "verify!!!" [object Object] flow.js:299
...etc...

I think we put something in place in Persona, to stop hitting the server after X amount of time.
Maybe I am dreaming that...

**Comment by shane-tomlinson** [comment]
Link to:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1122443
* https://github.com/mozilla/fxa-content-server/issues/2038
* https://github.com/mozilla/fxa-content-server/pull/2039

**Comment by vladikoff** [comment]
> stop hitting the server after X amount of time.

from triage:
If it is not an issue for ops we can close this for now.

**Comment by jrgm** [comment]
This is not the place to track it, but it is an issue for overall performance, and just wasted resources.
