### ISSUE TITLE
Remove code for old storage name in app/scripts/models/uniqueUserId.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-content-server#6852]
I was poking about in our UUID implementation and noticed [this comment](https://github.com/mozilla/fxa-content-server/blob/8fc1679bfee8456996c0a02f97ffdb843f62299a/app/scripts/models/unique-user-id.js#L56-L58):

```js
// stomlinson on 2015-07-08:
// `uuid` is the old name, this is transition code
// and can hopefully be removed after a time.
```

I reckon 3.5 years is sufficiently prudent that we can think about deleting the transition code now.

**Comment by hritvi** [comment]
May I work on this issue? I think only the code mentioned [here](https://github.com/mozilla/fxa-content-server/blob/8fc1679bfee8456996c0a02f97ffdb843f62299a/app/scripts/models/unique-user-id.js#L55) need to be removed.

**Comment by philbooth** [comment]
@hritvi, yep it should be a case of just ripping out that first `if` condition then updating any tests that were asserting it. I'm not sure whether we have those tests or not btw, if not it might be worth adding one to assert that the old condition has definitely gone away.

**Comment by hritvi** [comment]
I have pushed a commit to remove the if statement [here](https://github.com/hritvi/fxa-content-server/commit/e5bea37201d4d0b1f360dc3b0f9a4eba374e7813).
Is [this](https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/models/unique-user-id.js#L78) the test for uuid @philbooth? I think that we should remove this and instead add assert regarding removal of old condition.

**Comment by philbooth** [comment]
> Is [this](https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/models/unique-user-id.js#L78) the test for uuid @philbooth?

Not sure. It looks like it's related, definitely, although I don't see it calling thje `fetch` method anywhere. But maybe I just don't understand how it's all wired together, I'm not very familiar with this part of the code.

But the simplest way to tell for certain is to run the unit tests and see if it fails! (http://127.0.0.1:3030/tests/index.html if you're using fxa-local-dev)

As long as we have a test that fails without your change applied and passes with it, then we know we're in a good place.
