### ISSUE TITLE
Vertically center avatar buttons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6854]
CURRENT:
<img width="463" alt="screen shot 2018-12-21 at 1 53 36 pm" src="https://user-images.githubusercontent.com/68213/50612255-60ed4300-0ea7-11e9-9493-6e5d7951bedd.png">

PROPOSED (lifted 20px):
<img width="463" alt="screen shot 2018-12-21 at 1 53 36 pm copy" src="https://user-images.githubusercontent.com/68213/50612258-634f9d00-0ea7-11e9-9ec2-00cc95601e51.png">

**Comment by sakshi97** [comment]
Hi. Can I take up this issue to get started with the repository?

**Comment by shane-tomlinson** [comment]
@sakshi97 - We'd be happy for you to take up this issue! To get started, have a [look at the docs](https://github.com/mozilla/fxa-content-server/#quick-start) and see if you can get the servers started.

The affected is [here](https://github.com/mozilla/fxa-content-server/blob/69bfd93a8ac209ea855e3691f54cd5177d3947f5/app/scripts/templates/settings/avatar_change.mustache#L15).
The affected CSS is [here](https://github.com/mozilla/fxa-content-server/blob/69bfd93a8ac209ea855e3691f54cd5177d3947f5/app/styles/modules/_avatar.scss#L218).

**Comment by hritvi** [comment]
@sakshi97 are you working on this? If not, may I take this issue @shane-tomlinson?
