### ISSUE TITLE
POST /metrics reports being rejected: :child "deviceId" fails because ["deviceId" is required]"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6867]
This started with train-127, several 10k's per day:

https://sentry.prod.mozaws.net/operations/content-express-server-prod/issues/626954/?query=is:unresolved

cc @philbooth

**Comment by shane-tomlinson** [comment]
Could this have something to do with https://github.com/mozilla/fxa-content-server/commit/c10d699ad63a77e8e58977d492930d36e5b1c24f

**Comment by philbooth** [comment]
Ah yeah, probably, sorry...

**Comment by philbooth** [comment]
Presumably if we reinstate the ` || NOT_REPORTED_VALUE` it should fix it, I can have a play tomorrow.

**Comment by shane-tomlinson** [comment]
fixed by #6868, closing.

**Comment by shane-tomlinson** [comment]
> fixed by #6868, closing.

I'm being optimistic, we haven't deployed the fix to verify yet.
