### ISSUE TITLE
tooltips not translated in local development

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6871]
Tooltips are fine on prod, but not local development:

### local
<img width="777" alt="screenshot 2019-01-11 at 15 32 32" src="https://user-images.githubusercontent.com/848085/51043253-2f1a6180-15b6-11e9-971c-17b60687fc77.png">

### prod
<img width="740" alt="screenshot 2019-01-11 at 15 32 54" src="https://user-images.githubusercontent.com/848085/51043258-30e42500-15b6-11e9-8bb1-664105ac9f50.png">

**Comment by TheoChevalier** [comment]
Are you by chance using a en-GB or en-US build of Firefox for local dev and fr for prod? Those tooltips are added by the browser, so they match the locale of your browser UI

**Comment by shane-tomlinson** [comment]
> Those tooltips are added by the browser, so they match the locale of your browser UI

Within FxA, we override all browser based tooltips and create our own.
