### ISSUE TITLE
Allow blank "email" query parameter

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6880]
I noticed while testing https://phabricator.services.mozilla.com/D16120 (the new about:newinstall page being developed) that they allow the self-hosted email-first form to be submit w/o requiring an email. That's a little odd, but worse is when FxA opens we show an "Invalid parameter: email" error.

<img width="466" alt="screenshot 2019-01-16 at 13 17 26" src="https://user-images.githubusercontent.com/848085/51251378-1da7cf80-1991-11e9-92b3-ac3b410069a4.png">

STRs:

1. Open https://accounts.firefox.com/?service=sync&action=email&context=fx_desktop_v3&email=

**Comment by farhan787** [comment]
@shane-tomlinson may I work on this ?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson may I work on this ?

You sure can!
