### ISSUE TITLE
Browser crashes when User tries to set avatar image with Camera option.

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/fxa-content-server#6905]
[Affected versions]:
Firefox Nightly 66.0a1 and above

[Affected Platforms]:
Windows 10

[Prerequisites]:
Add-on installed
Treatment branch set.
Verified account.

[Steps to reproduce]:
1. Click on Avatar icon.
2. When expanded, click on image icon.
3. Select Camera option.

[Expected result]:
User is able to set an avatar image using camera option.

[Actual result]:
Browser crashes when User tries to set avatar image with Camera option.

[Notes]:
Please find screenshot attached.
![fxa enus treatment avatar crash](https://user-images.githubusercontent.com/44404741/51745115-a48b3500-2080-11e9-90db-84f4f6df42db.gif)

**Comment by shane-tomlinson** [comment]
@vladikoff to have a look on a Windows 10 machine.

**Comment by shane-tomlinson** [comment]
I have no problems setting a profile photo using today's version of Nightly (2019-02-11) on Windows 10 or Unbranded Firefox 65 w/ v1.0.3 of the addon. @LucianaQueirolo is this still a problem for you?

**Comment by shane-tomlinson** [comment]
Closing this as WORKSFORME
