### ISSUE TITLE
"Learn more" is not hyperlinked when creating an underage account on iOS

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa-content-server#6906]
Environment: Train 129 - Stage server
Device: iOS SE (12.0.1)

Steps to reproduce:
 1. Launch Firefox with a new profile and go to hamburger menu.
 2. Create an underage account.
 3. Tap on "Learn more" from the message "Cannot create account. You must meet certain age requirements to create a Firefox Account. Learn more."

Expected result:
 The "Learn more" should be hyperlinked and the user should be redirected to https://www.ftc.gov/news-events/media-resources/protecting-consumer-privacy/kids-privacy-coppa

Actual result:
 "Learn more" is not hyperlinked and, therefor, cannot be accesed.

Notes:
 Also reproducible on production.

![image-1](https://user-images.githubusercontent.com/45595767/51826432-b45c8080-22ef-11e9-8105-cf072b9a8b6d.jpg)

**Comment by shane-tomlinson** [comment]
This is intentional on Firefox for iOS because there is no way to open the link w/o breaking the Firefox Accounts flow. See https://github.com/mozilla/fxa-content-server/issues/2225 for the original description of the problem.
