### ISSUE TITLE
`Forgot password` label after password changed is not aligned properly

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6907]
Noticed this while testing https://github.com/mozilla/fxa-content-server/pull/6859, it is reproducible on master.

STR
1. Create account
2. Login and change password
3. After successful password change, open password change panel again

<img width="516" alt="screen shot 2019-01-30 at 11 13 08 am" src="https://user-images.githubusercontent.com/1295288/51995292-6d51c500-2480-11e9-8f28-1c248c5be5a0.png">

Note that after you refresh the page it becomes properly aligned.

**Comment by Luna-Coder** [comment]
Hello I am an Outreachy candidate and would like to contribute to this project by having this bug assigned to me. Thank you.

**Comment by lmorchard** [comment]
Hmm, I *think* this issue might already have been fixed, but we didn't close it yet. Looks like @vbudhram might have merged the fix?

**Comment by shane-tomlinson** [comment]
This *has* been fixed, closing.

**Comment by lmorchard** [comment]
@Luna-Coder Sorry about that! But, you're super welcome to try picking up a different issue!
