### ISSUE TITLE
two consistently failing tests on "latest" teamcity

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server#6909]
(hit return too early)

Also happens on stage:

https://tc-test.dev.lcip.org/viewLog.html?buildId=46557&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests

- force customize sync checkbox to be checked 
  https://screencap.co.uk/images/f18aed0bd6dc7e55ad93795ee71ebab4a54675a4.png

- show password ended with mouseup
  https://screencap.co.uk/images/e0a7283be1703ee4f6701eadf56ee338fc175a52.png

**Comment by vladikoff** [comment]
@jrgm these are probably due to the geckodriver update and just the assertions need to be adjusted.

**Comment by shane-tomlinson** [comment]
Dup of #6900
