### ISSUE TITLE
Cleanup password reset TOTP tests

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-content-server#6931]
With the introduction of https://github.com/mozilla/fxa-content-server/pull/6878, there are some scenarios where the UX wouldn't necessarily do what would be expected. 

If we fix this test case, https://github.com/mozilla/fxa-content-server/pull/6878#discussion_r248227090, then it breaks https://github.com/mozilla/fxa-content-server/blob/15eac26724cb80a922b08459354e2aba70d773b2/tests/functional/oauth_reset_password.js#L252.

**Comment by shane-tomlinson** [comment]
@vbudhram - we fixed this last minute before merging, didn't we?

**Comment by vbudhram** [comment]
@shane-tomlinson yea we did! Closing
