### ISSUE TITLE
Merge oauth & oauth-redirect auth brokers

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6933]
The oauth and oauth-redirect auth-brokers were separated because there was a time when there was a different type of broker, an oauth-webchannel broker that used oauth as it's parent class. This is no longer the case and these two still being separate no longer serves any meaningful purpose.

Let's merge the two and simplify the overall hierarchy

**Comment by hritvi** [comment]
Hey @shane-tomlinson I could not locate the oauth-redirect relier among [these files](https://github.com/mozilla/fxa-content-server/tree/master/app/scripts/models/reliers). Can you help me find this? Thanks :slightly_smiling_face: 

Also may I work on this? I found this quite interesting.

**Comment by shane-tomlinson** [comment]
Aye... I specified incorrectly. I meant [the brokers](https://github.com/mozilla/fxa-content-server/tree/master/app/scripts/models/auth_brokers). Updating the title/description.

**Comment by shane-tomlinson** [comment]
> Also may I work on this? I found this quite interesting.

You sure can! This will be trickier than some of the other tasks you have worked on, if you run into any problems let me know!

**Comment by hritvi** [comment]
Thanks!!

**Comment by hritvi** [comment]
I suppose the codes [here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/oauth.js#L190-L231) are redundant and therefore can be removed along with the tests associated with this functions from this [file](https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/models/auth_brokers/oauth.js).

Rest of the [oauth.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/oauth.js) can be merged with [oauth-redirect.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/oauth-redirect.js).

What say @shane-tomlinson?
