### ISSUE TITLE
Deintensify the colour of our success messages

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6943]
Current:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/68213/52352240-3e949b00-29fa-11e9-9389-53140cc083e9.png">

Proposed:
![image](https://user-images.githubusercontent.com/68213/52352204-32a8d900-29fa-11e9-9cc2-0a8280fa0cbb.png)

New background colour: #c7fbbf
New text and link colour: #063311

Also checks out for contrast ratio.
https://contrast-ratio.com/#%23063311-on-%23c7fbbf

Still green but less intense…
![giphy](https://user-images.githubusercontent.com/68213/52352119-07be8500-29fa-11e9-851c-9b00663ab686.gif)

**Comment by shane-tomlinson** [comment]
These colors come straight from the [photon style guide](https://design.firefox.com/photon/components/message-bars.html).

**Comment by ryanfeeley** [comment]
@shane-tomlinson The style guide is about to be updated. My proposal comes directly from our UX team’s principal designer @shorlander. A larger palette refresh will soon follow.

**Comment by shreya99oak** [comment]
Can I take this up?

**Comment by shane-tomlinson** [comment]
> Can I take this up?

Sure, I suspect it'll involve updating https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/app/styles/_variables.scss#L131
