### ISSUE TITLE
Change focus ring on red buttons to blue

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6950]
Request from @shorlander that we use the same focus colour on all our buttons.

Current:
![focus](https://user-images.githubusercontent.com/68213/52498299-64f73980-2ba6-11e9-924a-f1945ead34cf.gif)

Proposed:
Same focus ring colour on all buttons
https://design.firefox.com/photon/components/buttons.html

**Comment by shreya99oak** [comment]
@shane-tomlinson Can I work on this?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Can I work on this?

You sure can, and I think it'd make @ryanfeeley very happy. I suspect it's as simple as removing these lines: https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/app/styles/modules/_button-row.scss#L62:L72
