### ISSUE TITLE
Allow for independent on/off configuration items for flow-events, amplitude, and stderr.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6956]
Right now the configuration item [client_metrics.stderr_collection_disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L75) disables *all* the server side metrics, and I inadvertently caused a metrics black-hole expecting just the StderrCollector metrics to be disabled. We should have a way of enabling or disabling these 3 independently.

Blocks #6932

**Comment by farhan787** [comment]
@shane-tomlinson may I work on this ?

**Comment by shreya99oak** [comment]
@farhan787 are you still working on this? I would like to give it a shot

**Comment by farhan787** [comment]
@shreya99oak @shane-tomlinson has not allowed me yet, so I'm waiting for his instructions. Btw, it's in my queue.

**Comment by shane-tomlinson** [comment]
@farhan787 you can take this, I just saw this request. @shreya99oak can you find another issue to work on?

**Comment by shane-tomlinson** [comment]
The basic idea is that we want 3 separate configuration items:

1. [client_metrics.stderr_collection_disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L75). If client_metrics.stderr_collection_disabled is true, it will will disable [writing normal events to stderr](https://github.com/shane-tomlinson/fxa-content-server/blob/f4166836728781c77b8110362cdfe18d16d46e8a/server/lib/routes/post-metrics.js#L164), no change from today.

2. [flow_metrics_disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L156). If `flow_metrics_disabled` is true, it will [disable writing flow events to stderr](https://github.com/shane-tomlinson/fxa-content-server/blob/f4166836728781c77b8110362cdfe18d16d46e8a/server/lib/flow-event.js#L230).

3. [amplitude.disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L33), where this is of the shape `amplitude: { disabled: { definition here }}`. If `amplitude.disablbed` is true, it will disable writing [amplitude events to stderr](https://github.com/shane-tomlinson/fxa-content-server/blob/f4166836728781c77b8110362cdfe18d16d46e8a/server/lib/amplitude.js#L155).

If those the flow/amplitude events are disabled, it'd be preferable to not do any pre-processing on the incoming data before the event is written.

**Comment by farhan787** [comment]
> @farhan787 you can take this

@shane-tomlinson thanks

**Comment by shreya99oak** [comment]
> @farhan787 you can take this, I just saw this request. @shreya99oak can you find another issue to work on?

Sure! How about #5742 ?

**Comment by farhan787** [comment]
> 2. [flow_metrics_disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L156). If `flow_metrics_disabled` is true, it will [disable writing flow events to stderr](https://github.com/shane-tomlinson/fxa-content-server/blob/f4166836728781c77b8110362cdfe18d16d46e8a/server/lib/flow-event.js#L230).

@shane-tomlinson by flow_metrics_disabled do you mean `FLOW_ID_KEY` because on the link flow_metrics_disabled there is no such thing. Could you please correct me if I'm wrong.

**Comment by shane-tomlinson** [comment]
>  do you mean FLOW_ID_KEY because on the link flow_metrics_disabled there is no such thing. 

`flow_metrics_disabled` needs to be a new configuration option in this case.

**Comment by farhan787** [comment]
> 3. [amplitude.disabled](https://github.com/mozilla/fxa-content-server/blob/0a91eb540681858bc96798c2c0851e964595f8a7/server/lib/configuration.js#L33), where this is of the shape `amplitude: { disabled: { definition here }}`. If `amplitude.disablbed` is true, it will disable writing [amplitude events to stderr](https://github.com/shane-tomlinson/fxa-content-server/blob/f4166836728781c77b8110362cdfe18d16d46e8a/server/lib/amplitude.js#L155).

@shane-tomlinson by amplitude.disabled do you mean `are_dist_resources` or I have to add something like in case of `flow_metrics_disabled` ?

**Comment by shane-tomlinson** [comment]
>  by amplitude.disabled do you mean are_dist_resources or I have to add something like in case of flow_metrics_disabled

This needs to be a new configuration option [of the shape `amplitude: { disabled: { definition here }}`](https://github.com/mozilla/fxa-content-server/issues/6956#issuecomment-475237773)
