### ISSUE TITLE
Shorten the focus ring around Forgot password link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#6957]
I noticed that in the Password Settings section the focus ring around the Forgot password link is full width. Would be nice to have it fit the link, instead of act as a block.

CURRENT
<img width="491" alt="image" src="https://user-images.githubusercontent.com/68213/52659791-2e822d00-2ecc-11e9-952e-0ba004e09a4f.png">

PROPOSED
<img width="140" alt="image" src="https://user-images.githubusercontent.com/68213/52659933-8ae54c80-2ecc-11e9-9442-5b730d663d09.png">

**Comment by shane-tomlinson** [comment]
Well spotted! I wonder if that full width password link is the reason for #6907?

**Comment by ryanfeeley** [comment]
@shane-tomlinson I'm not sure and I couldn't identity the CSS issue with inspector but it appears to be behaving as a block.

**Comment by shreya99oak** [comment]
Can I take this up?

**Comment by shane-tomlinson** [comment]
@shreya99oak - you sure can! If you run into any problems just let me know.

**Comment by na899** [comment]
Is this issue still unresolved?

**Comment by bini11** [comment]
Hey @shane-tomlinson Is this issue is still unresolved? May i work on this?

**Comment by lmorchard** [comment]
Looks like @shreya99oak has a Pull Request in progress for this issue - @shreya99oak, are you still working on this?

@bini11, you may want to try selecting another issue. @shreya99oak is may still be working on this or @na899 may pick it up. Lots of interest here!

**Comment by shreya99oak** [comment]
Yes yes
