### ISSUE TITLE
Enter password for signin screen does not accommodate small screens

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6965]
Found by @SorinaFlorean in https://github.com/mozilla/blurts-server/issues/770

---------------------

Environment
iOS - iPhone SE(12.0.1)

Steps to reproduce:

1. Create an account for FM;
2. Log out;
3. Tap on "Sign in";

Actual results: the email field is autocompleted but the name is not centered on the screen.
Expected results: the email field is autocompleted and no visual issues are displayed.

Screenshot:
![img_0059](https://user-images.githubusercontent.com/24588037/52800198-f02f6e00-3083-11e9-9113-b247c73f0382.PNG)

**Comment by farhan787** [comment]
@shane-tomlinson I don't have an iphone so how can I reproduce it on my mac ?

**Comment by shane-tomlinson** [comment]
@ryanfeeley can you provide some guidance here?

@farhan787 can you hold off until @ryanfeeley specs out what this should look like? The easiest thing to do is just load up the page and resize the window, or open dev tools to the "Inspector" panel and click the "responsive mode" icon in the upper right of dev tools, it looks like this:

<img width="128" alt="Screenshot 2019-03-11 at 15 08 46" src="https://user-images.githubusercontent.com/848085/54134279-99614e00-440f-11e9-9328-d66ca9ae955e.png">

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/6396, closing.

**Comment by farhan787** [comment]
@shane-tomlinson sure, I'll wait for your instructions.
