### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/fxa-content-server#6968]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/fxa-content-server/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by philbooth** [comment]
@shane-tomlinson, there is one wiki page in this repo, related to testing the SMS flow. Do we still need it? Or could we migrate it to the `docs` directory?

**Comment by shane-tomlinson** [comment]
@philbooth looks like it'd be fine in the docs directory to me.

**Comment by shane-tomlinson** [comment]
I have restricted write access to the wiki until we migrate the docs elsewhere.
