### ISSUE TITLE
Create SVG icon for Monitor in Devices&Apps section

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6971]
From https://github.com/mozilla/blurts-server/issues/769

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
One for Ryan Gaddis. Ryan, we need a Monitor icon for the FxA device manager, based no the icons listed here.
https://github.com/mozilla/fxa-content-server/tree/master/app/images

Will show up here: http://accounts.firefox.com/settings/clients

**Comment by ryanfeeley** [comment]
Eric Pang had already made one so I resized and optimized it. Does this work @shane-tomlinson? [icon-service-monitor.svg.zip](https://github.com/mozilla/fxa-content-server/files/2881782/icon-service-monitor.svg.zip)
