### ISSUE TITLE
Remove arrow from button on email confirmation screeen

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6978]
When you confirm an email in a Firefox that is not signed in, we tell users to sign in.

During Sync fest, it was noted to remove the arrow from this button.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/19537086/53128622-22285080-351a-11e9-8318-a45ca2cedfb6.png">

**Comment by hritvi** [comment]
May I work on this issue @davismtl. Thanks :slightly_smiling_face:

**Comment by davismtl** [comment]
I have no objection,  CC @shane-tomlinson in case you have engineering questions.

CC @ryanfeeley he knows this is being addressed per his request
