### ISSUE TITLE
Spacing needed between copy and image on profile picture picker

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-content-server#6979]
During Sync Fest, it was observed that there's missing padding between the image and "Position and rotate your picture as needed".

<img width="474" alt="image" src="https://user-images.githubusercontent.com/19537086/53128725-5dc31a80-351a-11e9-98c0-dc4839e08fce.png">

**Comment by hritvi** [comment]
May I work on this issue. If I am not wrong this page loads when you change your profile picture, right?

**Comment by davismtl** [comment]
Correct, this page loads when you change your profile picture.

@ryanfeeley what should the padding be so we can provide clearer instructions?

**Comment by ryanfeeley** [comment]
16px
