### ISSUE TITLE
Clean up uap.supportsSvgTransformOrigin() usage in views

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#6988]
Ref: https://github.com/mozilla/fxa-content-server/pull/6985#discussion_r259128535

![image](https://user-images.githubusercontent.com/128755/53204692-42c7d780-35fa-11e9-96ab-7d66ad715a20.png)

**Comment by hritvi** [comment]
May I take this issue @vladikoff?

**Comment by vladikoff** [comment]
@hritvi sure!

**Comment by hritvi** [comment]
@vladikoff Do I have to add the `setInitialContext` function [here](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/base.js)?
