### ISSUE TITLE
I am able to write any type of characters in the phone number field

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa-content-server#6994]
Environment:
Device: Android, Windows;
Build: Stage [Train 131], Production;

Prerequisites:
Make sure you are logged on a valid account

Steps to reproduce:
1.  Go to https://accounts.firefox.com/sms?service=sync;
2.  Write multiple characters on the number filed (numbers, letters, alphanumeric characters);

Expected results:
I am able to write only the numbers in the phone number filed. Additionally, I can write the '+' character.

Actual results:
I am able to write any type of characters in the number field.

Notes:
-Screenshot:
![screenshot_3](https://user-images.githubusercontent.com/40264165/53230448-5d985b80-368f-11e9-989d-cfab9d6d318f.png)

**Comment by shane-tomlinson** [comment]
This was purposeful because phone number formats differ all over the world. See https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md

**Comment by sv-sdeiac** [comment]
Due to comment 1, I'll close this issue. Thanks for the clarification.
