### ISSUE TITLE
Add an OAuth success screen at /oauth/success/<client_id>

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6996]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1528355

Both the reference browser and Fenix complete their flow by redirecting to `https://accounts.firefox.com/oauth/success/<client_id>`, which currently doesn't exist.

Let's show a placeholder similar to the Sync success screen so the browser
doesn't need to redirect *back* to `/connect_another_device?showSuccessMessage=true`.

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
cc @vladikoff

**Comment by hritvi** [comment]
May I work on this @shane-tomlinson ?

**Comment by vladikoff** [comment]
@hritvi sorry this one is already assigned in next

**Comment by vladikoff** [comment]
@hritvi You may work on this issue if you want!

**Comment by vladikoff** [comment]
@hritvi I just realized that we really need to fix this issue. I can give you until Thursday (March 21) to send some PR and we can work on landing it. Hope that's enough time!

**Comment by hritvi** [comment]
Ya sure @vladikoff. I would try to resolve this as soon as possible.

**Comment by vladikoff** [comment]
@hritvi to answer your question from IRC, just use the design from https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/templates/ready.mustache 

You might be able to just reuse the template as well
