### ISSUE TITLE
Travis uses Firefox 58, 7 versions behind.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7002]
[Travis is pinned to Firefox 58](https://github.com/shane-tomlinson/fxa-content-server/blob/94769cb4e4944c2bd2baf259c4789cb74e354d80/.travis.yml#L10). That's 7 versions behind. We should update that.

**Comment by shane-tomlinson** [comment]
ref #6976

**Comment by hritvi** [comment]
May I work on this @shane-tomlinson ? Also, do it only requires changing the version from Firefox 58 to 65 [here](https://github.com/shane-tomlinson/fxa-content-server/blob/94769cb4e4944c2bd2baf259c4789cb74e354d80/.travis.yml#L10) or there is more to it? Thanks

**Comment by shane-tomlinson** [comment]
Fixed by #7025
