### ISSUE TITLE
Pairing: Make sure Android device icon shows up for Fenix and Reference Browser

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-server#7015]
Currently we just show a laptop or something: 

![](http://v14d.com/i/c11b3147ce479adcaee55dedb9971d5a71bb9e071e8b2a2ebb24866e9b742ba3.jpg)

**Comment by farhan787** [comment]
@vladikoff  may I take this issue?

**Comment by shane-tomlinson** [comment]
@ryanfeeley do we have an icon for Firefox for Android or Fenix, or do we use https://github.com/mozilla/fxa-content-server/blob/master/app/images/icon-device-phone-android.svg?

**Comment by shane-tomlinson** [comment]
Fixed by #7065, closing.
