### ISSUE TITLE
[Android Enhancement] Rotate button is positioned too close to the zoom icon

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa-content-server#7023]
STR:
1. Log in to a valid Firefox account.
2. Go to Manage Account page.
3. Add a picture by tapping on the "Upload" button - choose Camera and try to rotate the taken picture.

Actual results:
The icon to rotate the picture is so small, that I accidentally tapped on zoom icon/button, instead of the rotate icon/button.

Expected results:
I should be able to rotate the picture without "hitting" other buttons.

Please see attached screenshot:
![screenshot_20190307-171106_firefox beta](https://user-images.githubusercontent.com/45595767/53967603-336a8300-40fe-11e9-824a-9bd767a086c8.jpg)

**Comment by farhan787** [comment]
May I work on this ?
