### ISSUE TITLE
Different length for success message depending if the page is scrolled or not 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#7026]
Environment:
Platform: Windows10
Stage - Train 132

Steps to reproduce:
1. Log in with an FF account and go to Manage account.
2. Change the account picture and pay attention to the success message.
3. Scroll down till the end of the page;
4. Change the account picture again and pay attention to the success message.

Expected results: for both steps 2 and 4, the success message is displayed the same.

Actual results: 
- step 2: 
![1](https://user-images.githubusercontent.com/24588037/54018233-cce27500-4190-11e9-8b6b-18651a6a8a4a.png)

- step 4: 
![2](https://user-images.githubusercontent.com/24588037/54018244-d2d85600-4190-11e9-847b-827d208cd3c4.png)

**Comment by farhan787** [comment]
@SorinaFlorean  may I take this ?

**Comment by shane-tomlinson** [comment]
Well spotted @SorinaFlorean!

@farhan787, let's wait for @ryanfeeley's input on how to handle this, he's our UX designer.

**Comment by farhan787** [comment]
@shane-tomlinson I didn't see your message, I hope the changes I made are good to fix this issue.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Now with the nicer paler green, I think we should go full width in both cases. Make sense?

**Comment by farhan787** [comment]
IMHO I think @ryanfeeley is right, it should be full width in both cases.

**Comment by farhan787** [comment]
@shane-tomlinson the same thing is happening with secondary email also.

**Comment by farhan787** [comment]
@shane-tomlinson and @ryanfeeley I've updated the success messages for full length for both situations.
