### ISSUE TITLE
[Android] Cannot duplicate a bookmark

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa-content-server#7027]
**STR:**
1. Sign in with valid credentials.
2. Add a bookmark.
3. Sign in with the same account on a second device.
4. Duplicate the bookmark on the second device.
5. Trigger sync and verify the duplicate is synced back to the first device.

**Expected result:**
Another bookmark with the same URL appears on the first device.

**Actual result:**
On the second device, the bookmark is not duplicated.

**Notes:**
- I signed in on multiple devices: Windows 10, iPhone SE (12.1.4), OnePlus 5T (Android 9), and Samsung Galaxy S8 (Android 8).
- In about:sync-log, there are no validation errors.  
- The bookmark is duplicated on Windows 10, iPhone SE (12.1.4), OnePlus 5T (Android 9).

![duplicate-bookmark](https://user-images.githubusercontent.com/45595767/54018248-d7047380-4190-11e9-8fb3-e5c5df473519.png)

**Comment by shane-tomlinson** [comment]
Thanks @miralobontiu, this looks to me to be a problem with Firefox for Android rather than Firefox Accounts. Can you migrate this to https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android?
