### ISSUE TITLE
Green banner for Account recovery enabled/disabled actions not displayed

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa-content-server#7029]
Environment: Android, iOS, Win10
Stage - Train 132

Steps to reproduce:
1. Log in and go to Manage account.
2. Go to "Account recovery" and tap on "enable".
3. Generate a new recovery key.
4. Revoke the key.

Expected results: the green banner "Account recovery enabled" is displayed at step 3 and for step 4 - another banner.

Actual results: the green banner is not displayed for step 3 nor step 4. 

Note:
 I've made a video with the issue and also with the "Two-step authentication" section to see how it behaves.

Video:  https://drive.google.com/open?id=1SM3-I3NKcoSZZh4NBTnxM_-hiAQuqTq-

**Comment by hritvi** [comment]
Hey @SorinaFlorean the video is not accessible by me. I have requested the access for it, could you please look into it.

**Comment by hritvi** [comment]
May I work on this?
