### ISSUE TITLE
Deprecate context=fx_desktop_v2

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7030]
## Description

Firefox was changed to use `context=fx_desktop_v3` in [Firefox 46](https://bugzilla.mozilla.org/show_bug.cgi?id=1204714), yet we still support `context=fx_desktop_v2`. Firefox 46 is now 19 versions old and no longer within our "ESR + 1" window, which currently goes back to [Firefox 52](https://wiki.mozilla.org/Release_Management/Calendar).

### Steps to reproduce

Open `https://accounts.firefox.com/?service=sync&context=fx_desktop_v2`

### Expected result

The user should [be asked to update their browser](https://github.com/mozilla/fxa-content-server/pull/6895) like we now do for `fx_desktop_v1`.

### Actual result

The user can sign in using an old, insecure browser.

**Comment by farhan787** [comment]
@shane-tomlinson may I fix this ?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson may I fix this ?

Had I read this before I did the update already, I would have said yes!

**Comment by farhan787** [comment]
> > @shane-tomlinson may I fix this ?
> 
> Had I read this before I did the update already, I would have said yes!

@shane-tomlinson the important thing is issue should be fixed, no matter who does it :-)
