### ISSUE TITLE
Merge fx-desktop-v1 auth broker into fx-ios-v1

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7033]
## Description

Support for context=fx_desktop_v1 was removed in #6895, but we still have the [fx-desktop-v1](https://github.com/mozilla/fxa-content-server/blob/8adcfd3173857e45f1798dd6dacdfa1ce04c342d/app/scripts/models/auth_brokers/fx-desktop-v1.js#L1) auth broker. Since fx_desktop_v1 can no longer be used, let's merge fx-desktop-v1.js into [fx-ios-v1.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/fx-ios-v1.js#L1) ensuring any properties/behaviors overridden by fx-ios-v1 remain the same. Any tests that exist only for [fx-desktop-v1.js](https://github.com/shane-tomlinson/fxa-content-server/blob/88de680d56263fc647dfe21954b62f26ff90ce0e/app/tests/spec/models/auth_brokers/fx-desktop-v1.js#L1) should also be migrated to [fx-ios-v1](https://github.com/shane-tomlinson/fxa-content-server/blob/88de680d56263fc647dfe21954b62f26ff90ce0e/app/tests/spec/models/auth_brokers/fx-ios-v1.js#L1)

**Comment by farhan787** [comment]
@shane-tomlinson can I take this ?

**Comment by shane-tomlinson** [comment]
You sure can @farhan787! If you run into any problems, please let me know!

**Comment by farhan787** [comment]
@shane-tomlinson sure! I'll let you know.
