### ISSUE TITLE
Remove support for node 8, support 10+

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7040]
We still support node 8 but our Docker images are now built using node 10. Let's drop support for node 8.

**Comment by farhan787** [comment]
@shane-tomlinson could you please elaborate where are we using node 8.

**Comment by shane-tomlinson** [comment]
@farhan787 it's still specified in [package.json](https://github.com/mozilla/fxa-content-server/blob/7af51def9f7fde6acccf9ecf5dd797341570c0dd/package.json#L166) and [.nvmrc](https://github.com/mozilla/fxa-content-server/blob/7af51def9f7fde6acccf9ecf5dd797341570c0dd/.nvmrc#L2)

**Comment by farhan787** [comment]
@shane-tomlinson may I take this one ?

**Comment by championshuttler** [comment]
Can i take this up? I would like to work on it.

Thanks

**Comment by farhan787** [comment]
@championshuttler I think you didn't noticed my PR, I've already done that.
