### ISSUE TITLE
Profile upload view layout not working on mobile

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#7045]
## Description

Mobile view of uploading profile picture is broken.

### Steps to reproduce

Turn on Sync and upload a profile picture.

### Expected result

Uploaded image should fit in view

### Actual result

It looks like this.
![IMG_9330](https://user-images.githubusercontent.com/68213/54308644-cb57e900-45a4-11e9-8a87-7ea587c410a2.PNG)
r

### Environment

iPhone SE iOS 12.14

**Comment by hritvi** [comment]
May I work on this @ryanfeeley?

**Comment by shane-tomlinson** [comment]
You already reported this @ryanfeeley! https://github.com/mozilla/fxa-content-server/issues/5313 Closing as a dup.

**Comment by davismtl** [comment]
@hritvi , we would certainly welcome help. Please see the referenced issue #5313
