### ISSUE TITLE
Unable to sign up 

### ISSUE THREAD

**Issue by championshuttler** [mozilla/fxa-content-server#7056]
## Description

After setting up the project , when I try to signup I am getting the error https://pastebin.com/YAghL34j
Describe the issue that you're seeing.

I try to debug the error but unable to do so.
 
I am checking the status `auth-server db mysql PORT 8000` is showing the errors in `./pm2 status` Output is here https://pastebin.com/FdGEVbfu

For the `|pm2 logs|` here is the output  https://pastebin.com/kVzJ0uyQ

### Expected result

Able to signup / login

### Actual result

Unable to signup/ login

### Environment

I tried with both Node 8 and Node 10. Facing same issue

What browser and operating system are you using?

Tried with Firefox and Chrome
MacOS 10.13

**Comment by shane-tomlinson** [comment]
@championshuttler - From this line, it looks like you do not have Docker running:

> 20|pairing | See 'docker run --help'.
> 20|pairing | docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by r-arvind** [comment]
![Screenshot from 2019-03-20 00-12-52](https://user-images.githubusercontent.com/32129503/54632918-1a21e900-4aa5-11e9-9d61-e0e2cb8e0844.png)

@shane-tomlinson I am facing the same issue, can you explain as to what is happening and how to fix it?

**Comment by hritvi** [comment]
@r-arvind @championshuttler there is some issue with the localhost. Instead, you would be able to signin at 127.0.0.1:3030. Even I tried a lot to search for an appropriate reason for this issue, but at last, concluded that there is some problem with my local PC. But as this issue is more frequent and not dependent on the local machine, I think that it would need some more discussions.

**Comment by lmorchard** [comment]
I haven't looked too deeply into this issue, but just talking about `localhost` versus `127.0.0.1`: Those are definitely not interchangeable as URLs. They might go to the same place, network-wise, but in an URL [they are different distinct *origins* with respect to security concerns and such](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

I think for FxA in development, everything is tied to `127.0.0.1:3000` as the expected origin.

**Comment by r-arvind** [comment]
Wow, it works at 127.0.0.1. That was unexpected, never realized that localhost won't work. I was struggling to find the issue for a long long time. Thanks!!

**Comment by shane-tomlinson** [comment]
Thanks for the info @hritvi! I'm going to close this issue.

**Comment by hritvi** [comment]
Thanks @lmorchard for clearing all my origin related doubts. Until now I used to think that 127.0.0.1 points to localhost only and both are the same things :sweat_smile: .
