### ISSUE TITLE
Add client icon for Send in device list

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#7062]
I noticed that there is no device icon for Send in the client list. Here is one!
[Send_Glyph.svg.zip](https://github.com/mozilla/fxa-content-server/files/2984139/Send_Glyph.svg.zip)

**Comment by ryanfeeley** [comment]
I ran it through https://jakearchibald.github.io/svgomg/

**Comment by AlbionaHoti** [comment]
Hi, @ryanfeeley I am an outreachy applicant and would like to work on this issue :)

**Comment by lmorchard** [comment]
@AlbionaHoti feel free to take this one on! Do you have a good idea of what needs to be done here? Feel free to ask!

**Comment by AlbionaHoti** [comment]
@lmorchard Thank you!

As I can see - there is the Devices & Apps button on Settings page - When it's open it shows a list of devices - it helped me the clients.js file in settings folder and the clients.js in testing where it was mentioned the "device list" | Is the idea to add the icon somewhere there or is it something else?

**Comment by lmorchard** [comment]
@AlbionaHoti Yeah, looks like in that devices list is where this image should go.

I haven't worked on that area of the app yet, but I see [this list of services and images in `app/styles/modules/_settings.scss`](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/modules/_settings.scss#L525) associated with service names. You should be able to add the image and add a style there to match on `data-name='Firefox Send'`.

**Comment by lmorchard** [comment]
@AlbionaHoti Yeah, looks like in that devices list is where this image should go.

I haven't worked on that area of the app yet, but I see [this list of services and images in `app/styles/modules/_settings.scss`](https://github.com/mozilla/fxa-content-server/blob/master/app/styles/modules/_settings.scss#L525) associated with service names. You should be able to add the image and add a style there to match on `data-name='Firefox Send'`.

**Comment by lmorchard** [comment]
(oops, hit the wrong button and didn't mean to close)
