### ISSUE TITLE
[Train-133] "Sync now" is not working on Android

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa-content-server#7075]
Devices: Samsung Galaxy Note 8 (Android 9.0), desktop Windows 10

**STR:**
1. Sign in with the same Firefox account on two devices, at least one has to be an Android.
2. Go to Settings -> Firefox account -> "Sync now" and tap on it.

**Expected result:**
Sync should start immediately.

**Actual results:**
Sync starts but stops in a few seconds without syncing. "Last synced: never" is displayed under "Sync now".

Note: not reproducible on production.

![sync](https://user-images.githubusercontent.com/45595767/54754811-1ac59700-4bed-11e9-83e0-cc459b49b70e.gif)

**Comment by shane-tomlinson** [comment]
Hi @miralobontiu, this bug looks like it should be filed in Bugzilla under [the Firefox for Android](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android) product.

**Comment by miralobontiu** [comment]
Thanks, Shane! Will do!
