### ISSUE TITLE
tweak the version grunt task to include contributors file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#708]
Currently we're generating the CONTRIBUTORS file using npm task: `$ npm run contributors` which pipes the output to [CONTRIBUTORS.md](https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTORS.md)

I'd be super neat if we had a Grunt task that generates the CONTRIBUTORS file so we can generate the file and commit it when we bump the version and update the changelog.

**Comment by vladikoff** [comment]
Let's make it part of `grunt version` that we have, the alias task should run `npm run contributors` and make the change to the file.
