### ISSUE TITLE
Add errno 121 to oauth-errors.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#7095]
Over in mozilla/fxa-auth-server#2969, @rfk added errno 121 to the oauth errors, "Invalid grant_type". We'll need to add that to [oauth-errors.js](https://github.com/shane-tomlinson/fxa-content-server/blob/3803c6ef1e6787aea963e37e99b1281aa2c3eebb/app/scripts/lib/oauth-errors.js#L99).

**Comment by hritvi** [comment]
Just a idea, shouldn't we write a script to automatically add any errors which are added in the auth-server. Or is there any other thing that is stopping us from doing that.

**Comment by shane-tomlinson** [comment]
We have a bug about sharing errors across repos, but I can't find it. It's mentioned [in this one](https://github.com/mozilla/fxa-shared/issues/60).

**Comment by philbooth** [comment]
When we move to a monorepo we won't need a script, the definitions can just be included in both places.
