### ISSUE TITLE
Bower sometimes asks to send usage stats, which isn't too cool

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#744]
### Steps to reproduce:
1. Download fxa-content-server and run `npm install`.
### Actual results:

Bower seems to hang while waiting for my input:

> _[?] May bower anonymously report usage statistics to improve the tool over time? (Y/n)_

@vladikoff pointed out this Bower issue, which seems to be the culprit, even though I'm still seeing the behavior locally in 1.3.1: bower/bower#1102
### Expected results:

Shut up, bower! You're not my real dad!
### Workaround:

Set the npm postinstall to use something like this: `bower install --config.interactive=false -s;`
### How this makes me feel:

![How about no](http://snickerpants.com/blog/wp-content/uploads/2013/01/bear-how-about-no-wj9.jpg)

**Comment by theothermattm** [comment]
(( slow clap )) fantastic bug report.

**Comment by jpbochi** [comment]
![](http://i2.kym-cdn.com/photos/images/masonry/000/370/259/7a9.png)

**Comment by InvDeath** [comment]
I use Bower inside Docker and this is really issue.
