### ISSUE TITLE
Password generator when creating passwords

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#768]
Everywhere we insist that “Passwords must be at least 8 characters.” we should offer help concocting good passwords.

The following is a straw man password helper UI based loosely on the Schneier Scheme: https://www.schneier.com/essay-246.html
and also: http://www.hughcalc.org/pwgen.cgi

![password-playground](https://f.cloud.github.com/assets/68213/2476352/45f47bca-b062-11e3-8fc3-ff2b32ca4194.png)

This allows users to experiment and play, and eventually copy their new password which can be be pasted in the previous screen (standing a better chance to be captured by a password manager if one is installed).

Please provide your criticism and improvements, and I will refine and develop the idea here.

**Comment by pdehaan** [comment]
Saw this today in some ad: https://howsecureismypassword.net/
This is another pretty good article I read the other day: 

> _"... recommend that popular web services adopt a commonly shared algorithm for their password strength meters. In particular, they suggest using or extending the zxcvbn algorithm used by Dropbox or the KeePass open-source implementation of it."_
> &mdash; via http://readwrite.com/2015/03/27/password-strength-weaker-than-you-think

I did some Googling but wasn't able to find KeePass' password strength algorithm, but this may be a good start: https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/

http://keepass.info/help/kb/pw_quality_est.html

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I propose this is moved to an FxA user story where it is more likely to be prioritized.

**Comment by shane-tomlinson** [comment]
Another snippet of info:
http://www.computerworld.com/article/2978392/data-security/tired-of-memorizing-passwords-a-turing-award-winner-came-up-with-this-algorithmic-trick.html

**Comment by rfk** [comment]
It's now a feature card in Aha: https://mozilla.aha.io/features/FXA-48
