### ISSUE TITLE
HTML totally isnt getting minified

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#828]
### Steps to reproduce:
1. Check HTML source for following jazz:
  - <view-source:https://accounts.firefox.com/signin>
  - <view-source:https://accounts-latest.dev.lcip.org/signin>

### Actual results:
```html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>„Firefox“ paskyros</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="/latin/firasans-regular,firasans-light,clearsans-regular/fonts.css">
        <link rel="stylesheet" href="/styles/295a5976.main.css"/>
        <script src="/bower_components/modernizr/1a5317ff.modernizr.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="fox-logo"></div>
        <div id="stage">
          <!-- this will be overwritten if JS is enabled -->
          <noscript>
            „Firefox“ paskyroms reikia „Javascript“.
          </noscript>

        </div>

        <a id="about-mozilla" rel="author" target="_blank" href="https://www.mozilla.org/about/?utm_source=firefox-accounts&amp;utm_medium=Referral"></a>

        <!-- no build declaration, main.js build
             is done by requirejs and not concat.
             rev/usemin will still replace the URL
             with a cache aware URL.
         -->
        <script src="/scripts/7c04dec4.main.js"></script>
    </body>
</html>
```

### Expected results:
Minify that junk! (see #656 also)

---

Its a bit confusing, since we do have a grunt-contrib-htmlmin Grunt task, but it seems to not really minify.
1. [/grunttasks/htmlmin.js](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/htmlmin.js)
2. which gets called from [$ grunt concurrent:dist (grunttasks/concurrent.js:15-19)](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/concurrent.js#L15-L19)
3. which gets called from [$ grunt build (grunttasks/build.js:19)](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/build.js#L19)

I find it a bit confusing since it looks like [grunttasks/build.js:22](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/build.js#L22) minifies the app/sync/*.html files.
Then in [grunttasks/copy.js:33-54](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/copy.js#L33-L54) it looks like we're overwriting the minified files with the unminified versions.

**Comment by vladikoff** [comment]
This is not working or something https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/concurrent.js#L21

**Comment by pdehaan** [comment]
Here's the output from me running `$ grunt htmlmin` from the Terminal:

```
$ grunt htmlmin
Running "htmlmin:dist" (htmlmin) task
Minified dist/500.html 1.49 kB → 1.49 kB
Minified dist/502.html 1.49 kB → 1.49 kB
Minified dist/503.html 1.54 kB → 1.54 kB

Done, without errors.


Execution Time (2015-06-02 17:49:31 UTC)
loading tasks  4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 4s
```

I think the main issue is that all the options and whitespace collapsing are disabled in the [/grunttasks/htmlmin.js](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/htmlmin.js) file. Not sure why we're only minifying those three templates, or if we should also minify the templates in "/server/templates/pages/dist/".

**Comment by shane-tomlinson** [comment]
> I think the main issue is that all the options and whitespace collapsing are disabled in the /grunttasks/htmlmin.js file. Not sure why we're only minifying those three templates, or if we should also minify the templates in "/server/templates/pages/dist/".

This is curious.

**Comment by shane-tomlinson** [comment]
There are a couple of things going on.

1. All the options are commented out in htmlmin.js
1. We only minify the error pages, the other pages are copied to `dist` in the `usemin` task, after `htmlmin` has already run.
