### ISSUE TITLE
Enable accounts.firefox.com to report downtime/maintenance on status.mozilla.org

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#829]
via https://github.com/mozilla/fxa-content-server/pull/825#issuecomment-38905822

I'd be neat to have some general page for maintenance announcements, downtime explanations, etc. Would come in handy since I think we've had some minor downtime w/ trains and db migrations, etc.

For Persona, I found the [@personastatus](https://twitter.com/personastatus) Twitter account which directed me to http://personastatus.org/.

**Comment by pdehaan** [comment]
@jrgm: Is this still something we want, and if so, is there a better place for us to file this?

**Comment by vladikoff** [comment]
@gene1wood it seems this is now using StatusHub,
![image](https://cloud.githubusercontent.com/assets/128755/9137392/37f63182-3ceb-11e5-9890-8102d7dd9462.png)

Is it possible to add " accounts.firefox.com " to the list under MOZILLA WEBSITES?
I can also send an email if you know who has access to that dashboard

**Comment by vladikoff** [comment]
ping @gene1wood or @karlht, who should we ping about this?

**Comment by gene1wood** [comment]
@vladikoff I'd recommend hitting up Cloud Services Operations (Travis Blow's team) and they should be able to help.

**Comment by vladikoff** [comment]
@gene1wood excellent thanks!!

**Comment by vladikoff** [comment]
Sent an email, nothing to do here from the content server point of view
