### ISSUE TITLE
Suggest corrections when users misspell their email address

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#871]
Following our current error treatment (except using our blue instead of green or red), we should alert users when they type in an email domain that we suspect is incorrect.

![did-you-mean-blue](https://cloud.githubusercontent.com/assets/68213/2606829/7a2dead6-bb55-11e3-8df1-bd540a662cdd.png)

Can we use this library?
https://github.com/Kicksend/mailcheck

**Comment by ckarlof** [comment]
@dannycoates, I'd like to get this into prod either via feature flag (default off) or as a small "percent deployment" to get further data on. Can you work with @vladikoff on integrating this feature with able?

**Comment by ckarlof** [comment]
@kparlante, I'd like to move this forward. We'd still like to run a version of the algorithm against a sample of our email DB to see how many false positives we get. How can we best proceed with that? Maybe we can just get a sample of the email domains from @ckolos for the FxA DB?

**Comment by ckolos** [comment]
List updated in bz. Not linked here.

**Comment by kparlante** [comment]
domains from create & bounce logs of one date sent to @vladikoff via encrypted files

FWIW, looked like ~90% of the creates were from the top 100 domains (top 100 domains of that day, not the db data).

**Comment by vladikoff** [comment]
@ckolos and @kparlante Thank you for providing the data!
