### ISSUE TITLE
Can't submit re-authentication form after a time

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#893]
Left the "force re-authentication" tab open.

about:accounts?action=reauth

Went to bed. In the morning I returned to the tab, tried to enter the password, but the submit button does not become active even if the minimum number of password characters is entered.

![reauth](https://cloud.githubusercontent.com/assets/68213/2679202/0f7395a4-c16f-11e3-8b3b-1f02718ec4d3.png)

Also nothing happens when I press "enter".

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-content-server/pull/2509
