### ISSUE TITLE
Add Firefox logo to emails from content server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#901]
/summon @johngruen @ryanfeeley 

Should the emails from the server include the Firefox logo (like the site)?
AFAIK, we don't have an "Accounts/Sync" specific logo we could use instead, but not sure if this could benefit from more branding:

![verify_your_account_-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/2683229/576c1470-c1a7-11e3-9334-eb52051b8794.png)

**Comment by shane-tomlinson** [comment]
All emails templates are now located in the fxa-auth-mailer repo. Moved this to https://github.com/mozilla/fxa-auth-mailer/issues/28
