### ISSUE TITLE
If we encounter non-validation error (e.g., "Unexpected error" or "Service unavailable") during a form submission, don't disable the form after showing the error

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#904]
*Old title:* "service unavailable" error banner does not disappear between requests

tested w/ broken staging env.
ver.json on stage is giving me
```json
{"version":"0.8.0","commit":"6da5ee4b9fd614563a92f48a8c97a2ecf0759ee3"}
```

### Steps to repro:
1. Break some servers, we turned off database so auth server cannot connect.
2. Try and create a new account. (You should get a "service unavailable" error header appear after ~60s).
3. Edit the form and try and submit again.

### Actual result:
You wait a long time to get that Service Unavailable banner. Subsequent attempt to create an account doesn't clear that banner so you get confused as to what's happening because the UI doesn't change. We're testing this on Stage so maybe the UI is improved with Gruen's recent UI tweaks.

### Expected result:
After pressing the "Next" button, clear the `<div class="error">...</div>` bidness.

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/2685070/7cd23232-c1c3-11e3-922a-9dcc9643404c.png)

**Comment by shane-tomlinson** [comment]
@pdehaan - your face is plastered on this, are you handling this one?

**Comment by shane-tomlinson** [comment]
This is a valid issue, but I'm going to close this unless we still decide to prioritize the work.
