### ISSUE TITLE
Awkward "Learn More" text in PrivacyNotice text

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#947]
See mozilla/legal-docs#69
Live: https://accounts-latest.dev.lcip.org/legal/privacy

### Actual results:

> You send us different types of data depending on what features of the Services you use. Learn More.
> ...
> We use cookies, clear GIFs and other web technologies to offer and improve our products and services. Learn More.

The "Learn More" doesn't do anything, like toggle the bullet points. They apparently use the toggling features on the main privacy page.

Not sure if we want to accept the awkwardness or try and turn the Learn More into a toggle, or try and remove it...

Should be easy enough to remove "Learn More." strings using the grunt-text-replace task we're already using to strip the extended markdown timestamps, but searching for "Learn More." is obviously a bit trickier since it's locale specific and we probably don't want to bake in translated strings for 10-30 locales.

**Comment by shane-tomlinson** [comment]
Closing b/c this is a legal doc issue. @pdehaan filed mozilla/legal-docs#69

**Comment by shane-tomlinson** [comment]
Ah, nevermind, I see how it is supposed to work now. @johngruen's comment tells the path forward - https://github.com/mozilla/fxa-content-server/issues/947#issuecomment-41046190. Re-opening.

**Comment by vladikoff** [comment]
from triage:

We should strip out "Learn More" from the text when we pull the docs.

**Comment by pdehaan** [comment]
**PROTIP:** Easiest way is to just add a new replacement in the [/grunttasks/replace.js](https://github.com/mozilla/fxa-content-server/blob/master/grunttasks/replace.js) file:

```js
      {
        from: '.  Learn More.',
        to: '.'
      }
```

This will only work in English translations, but that may be good enough.

**Comment by vladikoff** [comment]
> This will only work in English translations, but that may be good enough.

ah yes, forgot that these strings are from a different source. hmmm..

**Comment by shane-tomlinson** [comment]
@johngruen - any update on this?

**Comment by issues-bouncer** [comment]
Hey @johngruen, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by vladikoff** [comment]
@johngruen i think you mentioned something about this in a recent meeting. Will this be fixed automatically in the legal docs repo? cc @pdehaan

**Comment by johngruen** [comment]
@vladikoff yep!

**Comment by vladikoff** [comment]
Thanks John!

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/legal-docs/pull/374
