### ISSUE TITLE
Figure out marketing email integration UX for FxA with an eye toward early capture

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#992]
![screen_shot_2014-04-23_at_3_26_50_pm](https://cloud.githubusercontent.com/assets/3323249/2782287/912d6752-cb1d-11e3-9cbe-73e9c58dd2be.png)

This is the UX part of #993 
@ryanfeeley 
Add a checkbox to let users join the Firefox and You mailing list from FxA creation.

**Comment by ckarlof** [comment]
Closing this in favor of our FxA/Basket integration bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1041074
