### ISSUE TITLE
Pass User Emails on to our Marketing Team

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa-content-server#993]
This is the engineering part of #992 
@ckarlof @pmclanahan to fill in the details.

**Comment by rfk** [comment]
@ckarlof, has all the useful content and actions from this issue been moved into the bugzilla tracking bug?  If so then we should close this one out to avoid splitting context.

**Comment by ckarlof** [comment]
I think this is indeed stale. Tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1041074
