### ISSUE TITLE
Add a "forgot password" affordance to change password flow

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-server#994]
Found in https://accounts-latest.dev.lcip.org/ver.json (commit 7e5162c42e5177347a591123f489af9b71fdbb2c)

```json
{"version":"0.11.0","commit":"7e5162c42e5177347a591123f489af9b71fdbb2c"}
```

---

### Steps to reproduce:
1. Create an account on https://accounts-latest.dev.lcip.org/ and log in.
2. Goto the [change password](https://accounts-latest.dev.lcip.org/change_password) screen from /settings.
3. Try changing your email address without remembering your current password. It's been a long couple hours and I've already changed it a few times today but cannot remember exactly what the last password change was since I'm testing special chars.

### Actual results:
The page only says "Incorrect password" mockingly, but there is no option to click "Forgot Password" or otherwise change my password without the original/current password.

Going back to https://accounts-latest.dev.lcip.org/ just redirects me to https://accounts-latest.dev.lcip.org/settings since I'm currently logged in.

I either have to click "Sign out" or else manually go to https://accounts-latest.dev.lcip.org/signin so I can click the "Forgot password?" link and force a password reset.

### Expected results:
Something a bit more user friendly, although admittedly I'm an edge case since I'm both logged in yet I don't remember my actual password.

Unrelated, and probably best suited for a separate bug, but if we have to re-upload a user's data after they change their password, we may want to add some messaging around that in case they are on a slow connection or have a large amount of data to sync.

**Comment by vladikoff** [comment]
@ryanfeeley @johngruen any ideas where to include that in the new settings?

Somewhere in the "Password" section?

**Comment by ckarlof** [comment]
This becomes a more important if we start encouraging users to change their password in response to security events: https://github.com/mozilla/fxa-auth-mailer/issues/51

**Comment by vladikoff** [comment]
Talked to @ryanfeeley and this is what we devised! 


![image](https://cloud.githubusercontent.com/assets/128755/9472952/31dd13ee-4b26-11e5-94db-d8d7cd51b7de.png)
